### ISSUE TITLE
Opening links with firefox from snap on telegram from snap results with error

### ISSUE THREAD

**Issue by ilya-fedin** [telegramdesktop/tdesktop#6278]
### Steps to reproduce
1. Remove all browsers
2. Install Firefox from Snap
3. Install Telegram from Snap

### Expected behaviour
Link should be open in Firefox

### Actual behaviour
```
user-open error: cannot open supplied URL
```
If there are natively installed browser, opening works
Opening in Firefox snap from VSCode snap, for example, works too

### Configuration
**Operating system:**
Arch Linux (Deepin DE)
**Version of Telegram Desktop:**
1.17.13
**Used theme**:
Default
<details><summary><b>Logs</b>:</summary>

[log.txt](https://github.com/telegramdesktop/tdesktop/files/3384419/log.txt)
</details>

**Comment by Saul-BT** [comment]
Same thing here

**Comment by ilya-fedin** [comment]
It was fixed by itself on my device 🤔
