### ISSUE TITLE
"Haven't received code" is not working on Mac Client

### ISSUE THREAD

**Issue by itinance** [telegramdesktop/tdesktop#6279]
### Steps to reproduce

I have installed Telegram Desktop 5.5.1 (176369) from AppStore and typed in my Mobile number. However, I received the code so late that it was already expired.
When I enter the Code, it gives the error message "Code expired".

I clicked on "Haven't received code?" but nothing happens. When I uninstall the Application and reinstall it back, my Mobile number is still known to the application and sending a new code is still not working. I hoped there would be some way to start from scratch, but the Application keeps its state across Uninstallation and re-installation without any notice how to remove all data completely from my machine.

### Expected behaviour

1. I would expect to be able to resend the code once again
2. There must be any chance to remove the stored Mobile number from my Mac when I uninstall the Application (as described also in #6280) 

### Actual behaviour

1. The code is not resent again
2. Mobile phone number remains stored somewhere allthough I have reinstalled the App from my machine

### Configuration
**Operating system:**
Mac OS Mojave 10.14.5 (18F203)

**Version of Telegram Desktop:**
5.5.1 (176369) from AppStore

**Used theme**:
Dark

<img width="385" alt="Screenshot 2019-07-12 09 03 58" src="https://user-images.githubusercontent.com/1758597/61109175-8ffef580-a484-11e9-9727-d5cf2e49188e.png">

**Comment by 23rd** [comment]
Same.
https://github.com/telegramdesktop/tdesktop/issues/6280#issuecomment-510791039
