### ISSUE TITLE
How to remove abandoned data from Mac client after uninstallation?

### ISSUE THREAD

**Issue by itinance** [telegramdesktop/tdesktop#6280]
After uninstallation of Telegram client, some data like my Mobile number are still stored somewhere on my machine.

I have tried to find the location in

~/Library/Caches
~/Library/Application Support
Keychain

No chance. But when I reinstall the application, it still knows my Mobile number.
Proof:

<img width="385" alt="Screenshot 2019-07-12 09 03 58" src="https://user-images.githubusercontent.com/1758597/61109901-56c78500-a486-11e9-9db7-2216881964c3.png">

How can I remove all data that the client was saving on my machine? Where are they stored?

**Operating system:**
Mac OS Mojave 10.14.5 (18F203)

**Version of Telegram Desktop:**
5.5.1 (176369) from AppStore

**Comment by 23rd** [comment]
Sorry, you are using the Mac native client, not the Telegram Desktop.
https://github.com/telegramdesktop/tdesktop/issues/5921#issuecomment-483126605
