### ISSUE TITLE
Validate Username 

### ISSUE THREAD

**Issue by SmartManoj** [telegramdesktop/tdesktop#6283]
### Steps to reproduce
1. http://t.me/me
2. 
3. 

### Expected behaviour
Tell us what should happen
Should Say Invaid
### Actual behaviour
Tell us what happens instead
Says not found

### Configuration
**Operating system:**

**Version of Telegram Desktop:**

**Used theme**:

<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by 23rd** [comment]
It works as it should.

**Comment by SmartManoj** [comment]
But username should be five letters
