### ISSUE TITLE
[Question] How to convert a Basic Group to Supergroup

### ISSUE THREAD

**Issue by SmartManoj** [telegramdesktop/tdesktop#6285]
https://t.me/tgbeta/3424

1. • Making the group public.
2. • Changing group chat history visibility.
3. • Restricting a member.
4. • Changing default admin permissions.
5. • Group members reach 196.

Tried 2,3,4
Not working

**Comment by 23rd** [comment]
Did you try in mobile apps?

**Comment by SmartManoj** [comment]
Nope . Is this need to test in official client?

**Comment by ArmeF97** [comment]
So you didn't try telegram desktop?

**Comment by SmartManoj** [comment]
No , I first tried in telegram desktop only

**Comment by SmartManoj** [comment]
> official client.
> official mobile client.

**Comment by 23rd** [comment]
@SmartManoj I just tried 2, 3, 4 and every way works.

**Comment by SmartManoj** [comment]
What are the current difference between them

**Comment by 23rd** [comment]
The difference is how the server processes and stores messages from the group.
If you do not know the difference between them, why do you need to convert groups?

**Comment by SmartManoj** [comment]
So only older supergroup  have this option -> delete message for everyone as default.

**Comment by 23rd** [comment]
I converted a group and I see this box. 
![image](https://user-images.githubusercontent.com/4051126/61171064-e3ec0600-a57a-11e9-850c-d66bb2ebe29c.png)

**Comment by SmartManoj** [comment]
> 3\. member.

Will bots consider as members?

**Comment by 23rd** [comment]
Yes.

**Comment by ArmeF97** [comment]
> 2 Changing group chat history visibility.
This always worked for me

**Comment by SmartManoj** [comment]
Only 2nd worked

**Comment by SmartManoj** [comment]
For 4th one
![image](https://user-images.githubusercontent.com/7231077/61171121-c033ba80-a590-11e9-81c0-715e8bd7a161.png)

**Comment by SmartManoj** [comment]
> > 2 Changing group chat history visibility.
> 
> This always worked for me
2nd one worked

**Comment by SmartManoj** [comment]
3rd one
![image](https://user-images.githubusercontent.com/7231077/61171174-88794280-a591-11e9-9ea7-33fe54164817.png)

**Comment by SmartManoj** [comment]
How to unrestrict them?

**Comment by ArmeF97** [comment]
Go to groups settings, under restricted users

**Comment by SmartManoj** [comment]
I think it is only for users

**Comment by 23rd** [comment]
>How to unrestrict them?

Just return all permissions to this user.

**Comment by SmartManoj** [comment]
![image](https://user-images.githubusercontent.com/7231077/61171236-616f4080-a592-11e9-8b48-9a0199281ea1.png)
