### ISSUE TITLE
[Question] Empty Could Not start dialog

### ISSUE THREAD

**Issue by SmartManoj** [telegramdesktop/tdesktop#6286]
When opening link from browser 

![image](https://user-images.githubusercontent.com/7231077/61143722-9d51c980-a4f0-11e9-9086-c5a646050cd2.png)

![image](https://user-images.githubusercontent.com/7231077/61143763-b9ee0180-a4f0-11e9-9517-8cb59cb0bb54.png)

reg settings
`reg add "HKCU\Software\Classes\tdesktop.tg\shell\open\command" /ve /d """D:\1.Manoj\2.Soft-war\5.Rest\T\T.exe\""  -many -workdir ""D:\1.Manoj\2.Soft-war\5.Rest\TGs\TG\"" -- ""%%1\""" /f
`

**Comment by ilya-fedin** [comment]
Too little info
