### ISSUE TITLE
[Feature Request] Ability to record video Telescopes

### ISSUE THREAD

**Issue by jvlianodorneles** [telegramdesktop/tdesktop#6287]
### Is your feature request related to a problem?
No.

### Describe the solution you'd like
Ability to record video messages in the Telescope format.

### Additional context
The vast majority of personal computers have webcams and the ability to record video messages in the format would surely bring different types of audiences to the platform.

**Comment by ArmeF97** [comment]
Add the description to your title

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/781
