### ISSUE TITLE
[Feature Request]  Group button in channel

### ISSUE THREAD

**Issue by ArmeF97** [telegramdesktop/tdesktop#6289]
### Is your feature request related to a problem?
Kinda. When you are admin of a channel linked to a group, there is no button to go to the group, the only one it's hidden in the channel settings
![immagine](https://user-images.githubusercontent.com/6240983/61170818-ee080780-a56e-11e9-98bb-57da4bad9c53.png)

### Describe the solution you'd like
Add a group button
![immagine](https://user-images.githubusercontent.com/6240983/61170826-02e49b00-a56f-11e9-8df1-94247709e09e.png)

### Describe alternatives you've considered
Well, you can click the group from channel settings, but I think it's very bad.

**Comment by SmartManoj** [comment]
How it is linked?

**Comment by ArmeF97** [comment]
New telegram feature, you can link a group to a channel, in order to make channels post commentable

**Comment by SmartManoj** [comment]
https://t.me/tgbeta/3648

**Comment by ArmeF97** [comment]
Yes, this, now you understand?

**Comment by SmartManoj** [comment]
![image](https://user-images.githubusercontent.com/7231077/97099334-d5612980-16ad-11eb-84ee-9c98d82bd4c0.png)

**Comment by ArmeF97** [comment]
Perfect
