### ISSUE TITLE
Windows: maximized app extends to second screen

### ISSUE THREAD

**Issue by SPQRobin** [telegramdesktop/tdesktop#629]
I have a Windows desktop computer with two screens. When I maximize the Telegram app, the app's window extends to the other screen for a bit, which you can see on the attached photo.

It happens on either screen (i.e. it extends to the left screen when Telegram is maximized on the right screen and vice versa).

![photo_2015-04-05_01-48-46](https://cloud.githubusercontent.com/assets/1571471/6995154/05dc01ca-db36-11e4-87bd-97a03b72ebfd.jpg)

Thanks,
Robin

**Comment by auchri** [comment]
Duplicate #373
