### ISSUE TITLE
[Question] Thank you for not writing in Electron

### ISSUE THREAD

**Issue by oneturkmen** [telegramdesktop/tdesktop#6290]
Just wanted to Thank You entire team for not writing in Electron and taking a time to write it in Qt instead (as far as I know). My laptop is slow, and is always happy when there is a free spare RAM. Thanks again!

**Comment by charlesroddie** [comment]
Yes this is highly appreciated. Having a high quality desktop app supporting sync is a big differentiator over other messaging platforms (signal, skype, also teams, slack). It's why I use Telegram.
