### ISSUE TITLE
Telegram Desktop crashed in malloc

### ISSUE THREAD

**Issue by ivan-tretyak** [telegramdesktop/tdesktop#6293]
### Steps to reproduce
1. Install Telegram from repositories.(optionally, the bug is reproduced from the binary version from the site)
2. Chatting.
3. Departure program

### Expected behaviour
Continue chatting

### Actual behaviour
Now there is a complete exit from the program (the process is being killed).

### Configuration
**Operating system:** Fedora 30

**Version of Telegram Desktop:** 1.7.10

**Used theme**:

<details><summary><b>Logs</b>:</summary>
16:31:37 reporter-system: Process 1815 (telegram-desktop) crashed in malloc()
16:31:37 reporter-system: Process 1815 (telegram-desktop) crashed in malloc()
16:31:27 systemd-coredum: Process 1815 (telegram-deskto) of user 1000 dumped core.

Stack trace of thread 1815:
#0  0x00007f033b94bf66 _int_malloc (libc.so.6)
#1  0x00007f033b94db8f malloc (libc.so.6)
#2  0x00007f033bc97de9 _Znwm (libstdc++.so.6)
#3  0x00007f033cb744e2 _ZN8QRawFontC1Ev (libQt5Gui.so.5)
#4  0x00007f033caf6ff2 _ZN11QTextEngineC1ERK7QStringRK5QFont (libQt5Gui.so.5)
#5  0x00007f033caf9b8a _ZN16QStackTextEngineC1ERK7QStringRK5QFont (libQt5Gui.so.5)
#6  0x00007f033cc49f4e n/a (libQt5Gui.so.5)
#7  0x00007f033cc4b2e8 _ZN8QPainter8drawTextERK6QRectFRK7QStringRK11QTextOption (libQt5Gui.so.5)
#8  0x000000000292b2e7 _ZNK2Ui12EmptyUserpic5paintER7Painteriiii (telegram-desktop)
#9  0x0000000001b7eec0 _ZNK8PeerData12paintUserpicER7Painteriii (telegram-desktop)
#10 0x0000000001f2c8c0 _ZN12HistoryInner23enumerateItemsInHistoryILb1EZNS_17enumerateUserpicsIZNS_10paintEventEP11QPaintEventE4$_13EEvT_EUlN3gsl8not_nullIPN11HistoryView7ElementEEEiiE_EEvP7HistoryiT0_ (telegram-desktop)
#11 0x0000000001f1453c _ZN12HistoryInner10paintEventEP11QPaintEvent (telegram-desktop)
#12 0x00007f033cffa16e _ZN7QWidget5eventEP6QEvent (libQt5Widgets.so.5)
#13 0x0000000002931404 _ZN2Ui15RpWidgetMethods11handleEventEP6QEvent (telegram-desktop)
#14 0x00007f033cfb7af6 _ZN19QApplicationPrivate13notify_helperEP7QObjectP6QEvent (libQt5Widgets.so.5)
#15 0x00007f033cfc0e80 _ZN12QApplication6notifyEP7QObjectP6QEvent (libQt5Widgets.so.5)
#16 0x0000000001abea03 _ZN4Core7Sandbox6notifyEP7QObjectP6QEvent (telegram-desktop)
#17 0x00007f033c5b8ae8 _ZN16QCoreApplication15notifyInternal2EP7QObjectP6QEvent (libQt5Core.so.5)
#18 0x00007f033cff2c9a _ZN14QWidgetPrivate14sendPaintEventERK7QRegion (libQt5Widgets.so.5)
#19 0x00007f033cff34d9 _ZN14QWidgetPrivate10drawWidgetEP12QPaintDeviceRK7QRegionRK6QPointiP8QPainterP19QWidgetBackingStore (libQt5Widgets.so.5)
#20 0x00007f033cff41f3 _ZN14QWidgetPrivate22paintSiblingsRecursiveEP12QPaintDeviceRK5QListIP7QObjectEiRK7QRegionRK6QPointiP8QPainterP19QWidgetBackingStore (libQt5Widgets.so.5)
#21 0x00007f033cff31ec _ZN14QWidgetPrivate10drawWidgetEP12QPaintDeviceRK7QRegionRK6QPointiP8QPainterP19QWidgetBackingStore (libQt5Widgets.so.5)
#22 0x00007f033cff41f3 _ZN14QWidgetPrivate22paintSiblingsRecursiveEP12QPaintDeviceRK5QListIP7QObjectEiRK7QRegionRK6QPointiP8QPainterP19QWidgetBackingStore (libQt5Widgets.so.5)
#23 0x00007f033cff40d6 _ZN14QWidgetPrivate22paintSiblingsRecursiveEP12QPaintDeviceRK5QListIP7QObjectEiRK7QRegionRK6QPointiP8QPainterP19QWidgetBackingStore (libQt5Widgets.so.5)
#24 0x00007f033cff40d6 _ZN14QWidgetPrivate22paintSiblingsRecursiveEP12QPaintDeviceRK5QListIP7QObjectEiRK7QRegionRK6QPointiP8QPainterP19QWidgetBackingStore (libQt5Widgets.so.5)
#25 0x00007f033cff40d6 _ZN14QWidgetPrivate22paintSiblingsRecursiveEP12QPaintDeviceRK5QListIP7QObjectEiRK7QRegionRK6QPointiP8QPainterP19QWidgetBackingStore (libQt5Widgets.so.5)
#26 0x00007f033cff31ec _ZN14QWidgetPrivate10drawWidgetEP12QPaintDeviceRK7QRegionRK6QPointiP8QPainterP19QWidgetBackingStore (libQt5Widgets.so.5)
#27 0x00007f033cff41f3 _ZN14QWidgetPrivate22paintSiblingsRecursiveEP12QPaintDeviceRK5QListIP7QObjectEiRK7QRegionRK6QPointiP8QPainterP19QWidgetBackingStore (libQt5Widgets.so.5)
#28 0x00007f033cff40d6 _ZN14QWidgetPrivate22paintSiblingsRecursiveEP12QPaintDeviceRK5QListIP7QObjectEiRK7QRegionRK6QPointiP8QPainterP19QWidgetBackingStore (libQt5Widgets.so.5)
#29 0x00007f033cff40d6 _ZN14QWidgetPrivate22paintSiblingsRecursiveEP12QPaintDeviceRK5QListIP7QObjectEiRK7QRegionRK6QPointiP8QPainterP19QWidgetBackingStore (libQt5Widgets.so.5)
#30 0x00007f033cff40d6 _ZN14QWidgetPrivate22paintSiblingsRecursiveEP12QPaintDeviceRK5QListIP7QObjectEiRK7QRegionRK6QPointiP8QPainterP19QWidgetBackingStore (libQt5Widgets.so.5)
#31 0x00007f033cff40d6 _ZN14QWidgetPrivate22paintSiblingsRecursiveEP12QPaintDeviceRK5QListIP7QObjectEiRK7QRegionRK6QPointiP8QPainterP19QWidgetBackingStore (libQt5Widgets.so.5)
#32 0x00007f033cff40d6 _ZN14QWidgetPrivate22paintSiblingsRecursiveEP12QPaintDeviceRK5QListIP7QObjectEiRK7QRegionRK6QPointiP8QPainterP19QWidgetBackingStore (libQt5Widgets.so.5)
#33 0x00007f033cff31ec _ZN14QWidgetPrivate10drawWidgetEP12QPaintDeviceRK7QRegionRK6QPointiP8QPainterP19QWidgetBackingStore (libQt5Widgets.so.5)
#34 0x00007f033cff41f3 _ZN14QWidgetPrivate22paintSiblingsRecursiveEP12QPaintDeviceRK5QListIP7QObjectEiRK7QRegionRK6QPointiP8QPainterP19QWidgetBackingStore (libQt5Widgets.so.5)
#35 0x00007f033cff40d6 _ZN14QWidgetPrivate22paintSiblingsRecursiveEP12QPaintDeviceRK5QListIP7QObjectEiRK7QRegionRK6QPointiP8QPainterP19QWidgetBackingStore (libQt5Widgets.so.5)
#36 0x00007f033cff40d6 _ZN14QWidgetPrivate22paintSiblingsRecursiveEP12QPaintDeviceRK5QListIP7QObjectEiRK7QRegionRK6QPointiP8QPainterP19QWidgetBackingStore (libQt5Widgets.so.5)
#37 0x00007f033cff40d6 _ZN14QWidgetPrivate22paintSiblingsRecursiveEP12QPaintDeviceRK5QListIP7QObjectEiRK7QRegionRK6QPointiP8QPainterP19QWidgetBackingStore (libQt5Widgets.so.5)
#38 0x00007f033cff31ec _ZN14QWidgetPrivate10drawWidgetEP12QPaintDeviceRK7QRegionRK6QPointiP8QPainterP19QWidgetBackingStore (libQt5Widgets.so.5)
#39 0x00007f033cff41f3 _ZN14QWidgetPrivate22paintSiblingsRecursiveEP12QPaintDeviceRK5QListIP7QObjectEiRK7QRegionRK6QPointiP8QPainterP19QWidgetBackingStore (libQt5Widgets.so.5)
#40 0x00007f033cff31ec _ZN14QWidgetPrivate10drawWidgetEP12QPaintDeviceRK7QRegionRK6QPointiP8QPainterP19QWidgetBackingStore (libQt5Widgets.so.5)
#41 0x00007f033cff41f3 _ZN14QWidgetPrivate22paintSiblingsRecursiveEP12QPaintDeviceRK5QListIP7QObjectEiRK7QRegionRK6QPointiP8QPainterP19QWidgetBackingStore (libQt5Widgets.so.5)
#42 0x00007f033cff31ec _ZN14QWidgetPrivate10drawWidgetEP12QPaintDeviceRK7QRegionRK6QPointiP8QPainterP19QWidgetBackingStore (libQt5Widgets.so.5)
#43 0x00007f033cfc9c2a n/a (libQt5Widgets.so.5)
#44 0x00007f033cfc9fc1 n/a (libQt5Widgets.so.5)
#45 0x00007f033cfe2065 _ZN14QWidgetPrivate16syncBackingStoreEv (libQt5Widgets.so.5)
#46 0x00007f033cffabc8 _ZN7QWidget5eventEP6QEvent (libQt5Widgets.so.5)
#47 0x0000000002931404 _ZN2Ui15RpWidgetMethods11handleEventEP6QEvent (telegram-desktop)
#48 0x00007f033cfb7af6 _ZN19QApplicationPrivate13notify_helperEP7QObjectP6QEvent (libQt5Widgets.so.5)
#49 0x00007f033cfc0e80 _ZN12QApplication6notifyEP7QObjectP6QEvent (libQt5Widgets.so.5)
#50 0x0000000001abea03 _ZN4Core7Sandbox6notifyEP7QObjectP6QEvent (telegram-desktop)
#51 0x00007f033c5b8ae8 _ZN16QCoreApplication15notifyInternal2EP7QObjectP6QEvent (libQt5Core.so.5)
#52 0x00007f033c5bba93 _ZN23QCoreApplicationPrivate16sendPostedEventsEP7QObjectiP11QThreadData (libQt5Core.so.5)
#53 0x00007f033c60de47 n/a (libQt5Core.so.5)
#54 0x00007f033be57edd g_main_context_dispatch (libglib-2.0.so.0)
#55 0x00007f033be58270 n/a (libglib-2.0.so.0)
#56 0x00007f033be58313 g_main_context_iteration (libglib-2.0.so.0)
#57 0x00007f033c60dbd5 _ZN20QEventDispatcherGlib13processEventsE6QFlagsIN10QEventLoop17ProcessEventsFlagEE (libQt5Core.so.5)
#58 0x00007f033c5b79eb _ZN10QEventLoop4execE6QFlagsINS_17ProcessEventsFlagEE (libQt5Core.so.5)
#59 0x00007f033c5bf726 _ZN16QCoreApplication4execEv (libQt5Core.so.5)
#60 0x0000000001ab97fb _ZN4Core7Sandbox5startEv (telegram-desktop)
#61 0x0000000001aac467 _ZN4Core8Launcher18executeApplicationEv (telegram-desktop)
#62 0x0000000001aabfb0 _ZN4Core8Launcher4execEv (telegram-desktop)
#63 0x0000000002b5f3be main (telegram-desktop)

Stack trace of thread 1849:
#0  0x00007f033b9b85c7 __poll (libc.so.6)
#1  0x00007f0338d9b38a n/a (libxcb.so.1)
#2  0x00007f0338d9cffa xcb_wait_for_event (libxcb.so.1)
#3  0x00007f03292edb98 n/a (libQt5XcbQpa.so.5)
#4  0x00007f033c411786 n/a (libQt5Core.so.5)
#5  0x00007f033bdef5a2 start_thread (libpthread.so.0)
#6  0x00007f033b9c3303 __clone (libc.so.6)

Stack trace of thread 1859:
#0  0x00007f033b9b85c7 __poll (libc.so.6)
#1  0x00007f033be581de n/a (libglib-2.0.so.0)
#2  0x00007f033be58313 g_main_context_iteration (libglib-2.0.so.0)
#3  0x00007f033c60dbd5 _ZN20QEventDispatcherGlib13processEventsE6QFlagsIN10QEventLoop17ProcessEventsFlagEE (libQt5Core.so.5)
#4  0x00007f033c5b79eb _ZN10QEventLoop4execE6QFlagsINS_17ProcessEventsFlagEE (libQt5Core.so.5)
#5  0x00007f033c410635 _ZN7QThread4execEv (libQt5Core.so.5)
#6  0x00007f033c411786 n/a (libQt5Core.so.5)
#7  0x00007f033bdef5a2 start_thread (libpthread.so.0)
#8  0x00007f033b9c3303 __clone (libc.so.6)

Stack trace of thread 1850:
#0  0x00007f033b9b85c7 __poll (libc.so.6)
#1  0x00007f033be581de n/a (libglib-2.0.so.0)
#2  0x00007f033be58313 g_main_context_iteration (libglib-2.0.so.0)
#3  0x00007f033be58361 n/a (libglib-2.0.so.0)
#4  0x00007f033be814e2 n/a (libglib-2.0.so.0)
#5  0x00007f033bdef5a2 start_thread (libpthread.so.0)
#6  0x00007f033b9c3303 __clone (libc.so.6)

Stack trace of thread 2064:
#0  0x00007f033b9b85c7 __poll (libc.so.6)
#1  0x00007f033be581de n/a (libglib-2.0.so.0)
#2  0x00007f033be58313 g_main_context_iteration (libglib-2.0.so.0)
#3  0x00007f033c60dbd5 _ZN20QEventDispatcherGlib13processEventsE6QFlagsIN10QEventLoop17ProcessEventsFlagEE (libQt5Core.so.5)
#4  0x00007f033c5b79eb _ZN10QEventLoop4execE6QFlagsINS_17ProcessEventsFlagEE (libQt5Core.so.5)
#5  0x00007f033c410635 _ZN7QThread4execEv (libQt5Core.so.5)
#6  0x00007f033c411786 n/a (libQt5Core.so.5)
#7  0x00007f033bdef5a2 start_thread (libpthread.so.0)
#8  0x00007f033b9c3303 __clone (libc.so.6)

Stack trace of thread 1852:
#0  0x00007f033b9b85c7 __poll (libc.so.6)
#1  0x00007f033be581de n/a (libglib-2.0.so.0)
#2  0x00007f033be585a3 g_main_loop_run (libglib-2.0.so.0)
#3  0x00007f033855ed5a n/a (libgio-2.0.so.0)
#4  0x00007f033be814e2 n/a (libglib-2.0.so.0)
#5  0x00007f033bdef5a2 start_thread (libpthread.so.0)
#6  0x00007f033b9c3303 __clone (libc.so.6)

Stack trace of thread 1853:
#0  0x00007f033b9b85c7 __poll (libc.so.6)
#1  0x00007f033be581de n/a (libglib-2.0.so.0)
#2  0x00007f033be58313 g_main_context_iteration (libglib-2.0.so.0)
#3  0x00007f032941ca9d n/a (libdconfsettings.so)
#4  0x00007f033be814e2 n/a (libglib-2.0.so.0)
#5  0x00007f033bdef5a2 start_thread (libpthread.so.0)
#6  0x00007f033b9c3303 __clone (libc.so.6)

Stack trace of thread 1866:
#0  0x00007f033b9b85c7 __poll (libc.so.6)
#1  0x00007f033be581de n/a (libglib-2.0.so.0)
#2  0x00007f033be58313 g_main_context_iteration (libglib-2.0.so.0)
#3  0x00007f033c60dbd5 _ZN20QEventDispatcherGlib13processEventsE6QFlagsIN10QEventLoop17ProcessEventsFlagEE (libQt5Core.so.5)
#4  0x00007f033c5b79eb _ZN10QEventLoop4execE6QFlagsINS_17ProcessEventsFlagEE (libQt5Core.so.5)
#5  0x00007f033c410635 _ZN7QThread4execEv (libQt5Core.so.5)
#6  0x00007f033c411786 n/a (libQt5Core.so.5)
#7  0x00007f033bdef5a2 start_thread (libpthread.so.0)
#8  0x00007f033b9c3303 __clone (libc.so.6)

Stack trace of thread 2228:
#0  0x00007f033b9b85c7 __poll (libc.so.6)
#1  0x00007f033be581de n/a (libglib-2.0.so.0)
#2  0x00007f033be58313 g_main_context_iteration (libglib-2.0.so.0)
#3  0x00007f033c60dbd5 _ZN20QEventDispatcherGlib13processEventsE6QFlagsIN10QEventLoop17ProcessEventsFlagEE (libQt5Core.so.5)
#4  0x00007f033c5b79eb _ZN10QEventLoop4execE6QFlagsINS_17ProcessEventsFlagEE (libQt5Core.so.5)
#5  0x00007f033c410635 _ZN7QThread4execEv (libQt5Core.so.5)
#6  0x00007f033c411786 n/a (libQt5Core.so.5)
#7  0x00007f033bdef5a2 start_thread (libpthread.so.0)
#8  0x00007f033b9c3303 __clone (libc.so.6)

Stack trace of thread 1856:
#0  0x00007f033b9b85c7 __poll (libc.so.6)
#1  0x00007f033be581de n/a (libglib-2.0.so.0)
#2  0x00007f033be58313 g_main_context_iteration (libglib-2.0.so.0)
#3  0x00007f033c60dbd5 _ZN20QEventDispatcherGlib13processEventsE6QFlagsIN10QEventLoop17ProcessEventsFlagEE (libQt5Core.so.5)
#4  0x00007f033c5b79eb _ZN10QEventLoop4execE6QFlagsINS_17ProcessEventsFlagEE (libQt5Core.so.5)
#5  0x00007f033c410635 _ZN7QThread4execEv (libQt5Core.so.5)
#6  0x00007f033c889f4a n/a (libQt5DBus.so.5)
#7  0x00007f033c411786 n/a (libQt5Core.so.5)
#8  0x00007f033bdef5a2 start_thread (libpthread.so.0)
#9  0x00007f033b9c3303 __clone (libc.so.6)

Stack trace of thread 1867:
#0  0x00007f033b9b85c7 __poll (libc.so.6)
#1  0x00007f033be581de n/a (libglib-2.0.so.0)
#2  0x00007f033be58313 g_main_context_iteration (libglib-2.0.so.0)
#3  0x00007f033c60dbd5 _ZN20QEventDispatcherGlib13processEventsE6QFlagsIN10QEventLoop17ProcessEventsFlagEE (libQt5Core.so.5)
#4  0x00007f033c5b79eb _ZN10QEventLoop4execE6QFlagsINS_17ProcessEventsFlagEE (libQt5Core.so.5)
#5  0x00007f033c410635 _ZN7QThread4execEv (libQt5Core.so.5)
#6  0x00007f033c411786 n/a (libQt5Core.so.5)
#7  0x00007f033bdef5a2 start_thread (libpthread.so.0)
#8  0x00007f033b9c3303 __clone (libc.so.6)

Stack trace of thread 1868:
#0  0x00007f033b9b85c7 __poll (libc.so.6)
#1  0x00007f033be581de n/a (libglib-2.0.so.0)
#2  0x00007f033be58313 g_main_context_iteration (libglib-2.0.so.0)
#3  0x00007f033c60dbd5 _ZN20QEventDispatcherGlib13processEventsE6QFlagsIN10QEventLoop17ProcessEventsFlagEE (libQt5Core.so.5)
#4  0x00007f033c5b79eb _ZN10QEventLoop4execE6QFlagsINS_17ProcessEventsFlagEE (libQt5Core.so.5)
#5  0x00007f033c410635 _ZN7QThread4execEv (libQt5Core.so.5)
#6  0x00007f033c411786 n/a (libQt5Core.so.5)
#7  0x00007f033bdef5a2 start_thread (libpthread.so.0)
#8  0x00007f033b9c3303 __clone (libc.so.6)

Stack trace of thread 2226:
#0  0x00007f033bdf8bec read (libpthread.so.0)
#1  0x00007f033c537134 n/a (libQt5Core.so.5)
#2  0x00007f033c562852 n/a (libQt5Core.so.5)
#3  0x00007f033c508c0b _ZN11QFileDevice8readDataEPcx (libQt5Core.so.5)
#4  0x00007f033c50f792 _ZN16QIODevicePrivate4readEPcxb (libQt5Core.so.5)
#5  0x0000000002da801c _ZN7Storage4File4readEN3gsl4spanISt4byteLln1EEE (telegram-desktop)
#6  0x0000000002da8207 _ZN7Storage4File15readWithPaddingEN3gsl4spanISt4byteLln1EEE (telegram-desktop)
#7  0x0000000002d94af5 _ZNK7Storage5Cache7details14DatabaseObject13readValueDataESt5arrayIhLm7EEl (telegram-desktop)
#8  0x0000000002d946ac _ZN7Storage5Cache7details14DatabaseObject3getERKNS0_3KeyEON4base15unique_functionIFvONS1_11TaggedValueEEEE (telegram-desktop)
#9  0x0000000002d87a35 _ZN3crl7details4list5EntryIZNKS0_20object_on_queue_dataIN7Storage5Cache7details14DatabaseObjectEE5asyncIZNS8_4withIZNS5_8Database10getWithTagERKNS5_3KeyEON4base15unique_functionIFvONS6_11TaggedValueEEEEE4$_11EEvOT_EUlvE_EEvSO_EUlvE_E7ProcessEPNS1_10BasicEntryE (telegram-desktop)
#10 0x0000000002cb95da _ZN3crl7details4list7processEv (telegram-desktop)
#11 0x0000000002cb98b4 _ZN3crl5queue15ProcessCallbackEPv (telegram-desktop)
#12 0x00007f033c414d6b n/a (libQt5Core.so.5)
#13 0x00007f033c411786 n/a (libQt5Core.so.5)
#14 0x00007f033bdef5a2 start_thread (libpthread.so.0)
#15 0x00007f033b9c3303 __clone (libc.so.6)

Stack trace of thread 1883:
#0  0x00007f033b9b85c7 __poll (libc.so.6)
#1  0x00007f033be581de n/a (libglib-2.0.so.0)
#2  0x00007f033be58313 g_main_context_iteration (libglib-2.0.so.0)
#3  0x00007f033c60dbd5 _ZN20QEventDispatcherGlib13processEventsE6QFlagsIN10QEventLoop17ProcessEventsFlagEE (libQt5Core.so.5)
#4  0x00007f033c5b79eb _ZN10QEventLoop4execE6QFlagsINS_17ProcessEventsFlagEE (libQt5Core.so.5)
#5  0x00007f033c410635 _ZN7QThread4execEv (libQt5Core.so.5)
#6  0x00007f033c411786 n/a (libQt5Core.so.5)
#7  0x00007f033bdef5a2 start_thread (libpthread.so.0)
#8  0x00007f033b9c3303 __clone (libc.so.6)

Stack trace of thread 1882:
#0  0x00007f033bdf54d5 pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0)
#1  0x00007f030844153b n/a (i965_dri.so)
#2  0x00007f030844127b n/a (i965_dri.so)
#3  0x00007f033bdef5a2 start_thread (libpthread.so.0)
#4  0x00007f033b9c3303 __clone (libc.so.6)

Stack trace of thread 2211:
#0  0x00007f033bdf583c pthread_cond_timedwait@@GLIBC_2.3.2 (libpthread.so.0)
#1  0x00007f033c4171b9 _ZN14QWaitCondition4waitEP6QMutex14QDeadlineTimer (libQt5Core.so.5)
#2  0x00007f033c4172db _ZN14QWaitCondition4waitEP6QMutexm (libQt5Core.so.5)
#3  0x00007f033c414f73 n/a (libQt5Core.so.5)
#4  0x00007f033c411786 n/a (libQt5Core.so.5)
#5  0x00007f033bdef5a2 start_thread (libpthread.so.0)
#6  0x00007f033b9c3303 __clone (libc.so.6)

Stack trace of thread 1884:
#0  0x00007f033b9b85c7 __poll (libc.so.6)
#1  0x00007f033be581de n/a (libglib-2.0.so.0)
#2  0x00007f033be58313 g_main_context_iteration (libglib-2.0.so.0)
#3  0x00007f033c60dbd5 _ZN20QEventDispatcherGlib13processEventsE6QFlagsIN10QEventLoop17ProcessEventsFlagEE (libQt5Core.so.5)
#4  0x00007f033c5b79eb _ZN10QEventLoop4execE6QFlagsINS_17ProcessEventsFlagEE (libQt5Core.so.5)
#5  0x00007f033c410635 _ZN7QThread4execEv (libQt5Core.so.5)
#6  0x00007f033c411786 n/a (libQt5Core.so.5)
#7  0x00007f033bdef5a2 start_thread (libpthread.so.0)
#8  0x00007f033b9c3303 __clone (libc.so.6)

Stack trace of thread 2227:
#0  0x00007f033b9b85c7 __poll (libc.so.6)
#1  0x00007f033be581de n/a (libglib-2.0.so.0)
#2  0x00007f033be58313 g_main_context_iteration (libglib-2.0.so.0)
#3  0x00007f033c60dbd5 _ZN20QEventDispatcherGlib13processEventsE6QFlagsIN10QEventLoop17ProcessEventsFlagEE (libQt5Core.so.5)
#4  0x00007f033c5b79eb _ZN10QEventLoop4execE6QFlagsINS_17ProcessEventsFlagEE (libQt5Core.so.5)
#5  0x00007f033c410635 _ZN7QThread4execEv (libQt5Core.so.5)
#6  0x00007f033c411786 n/a (libQt5Core.so.5)
#7  0x00007f033bdef5a2 start_thread (libpthread.so.0)
#8  0x00007f033b9c3303 __clone (libc.so.6)

Stack trace of thread 2063:
#0  0x00007f033b9b85c7 __poll (libc.so.6)
#1  0x00007f033be581de n/a (libglib-2.0.so.0)
#2  0x00007f033be58313 g_main_context_iteration (libglib-2.0.so.0)
#3  0x00007f033c60dbd5 _ZN20QEventDispatcherGlib13processEventsE6QFlagsIN10QEventLoop17ProcessEventsFlagEE (libQt5Core.so.5)
#4  0x00007f033c5b79eb _ZN10QEventLoop4execE6QFlagsINS_17ProcessEventsFlagEE (libQt5Core.so.5)
#5  0x00007f033c410635 _ZN7QThread4execEv (libQt5Core.so.5)
#6  0x00007f033c411786 n/a (libQt5Core.so.5)
#7  0x00007f033bdef5a2 start_thread (libpthread.so.0)
#8  0x00007f033b9c3303 __clone (libc.so.6)

Stack trace of thread 2231:
#0  0x00007f033b9b85c7 __poll (libc.so.6)
#1  0x00007f033be581de n/a (libglib-2.0.so.0)
#2  0x00007f033be58313 g_main_context_iteration (libglib-2.0.so.0)
#3  0x00007f033c60dbd5 _ZN20QEventDispatcherGlib13processEventsE6QFlagsIN10QEventLoop17ProcessEventsFlagEE (libQt5Core.so.5)
#4  0x00007f033c5b79eb _ZN10QEventLoop4execE6QFlagsINS_17ProcessEventsFlagEE (libQt5Core.so.5)
#5  0x00007f033c410635 _ZN7QThread4execEv (libQt5Core.so.5)
#6  0x00007f033c411786 n/a (libQt5Core.so.5)
#7  0x00007f033bdef5a2 start_thread (libpthread.so.0)
#8  0x00007f033b9c3303 __clone (libc.so.6)

Stack trace of thread 2219:
#0  0x00007f033b9b85c7 __poll (libc.so.6)
#1  0x00007f033be581de n/a (libglib-2.0.so.0)
#2  0x00007f033be58313 g_main_context_iteration (libglib-2.0.so.0)
#3  0x00007f033c60dbd5 _ZN20QEventDispatcherGlib13processEventsE6QFlagsIN10QEventLoop17ProcessEventsFlagEE (libQt5Core.so.5)
#4  0x00007f033c5b79eb _ZN10QEventLoop4execE6QFlagsINS_17ProcessEventsFlagEE (libQt5Core.so.5)
#5  0x00007f033c410635 _ZN7QThread4execEv (libQt5Core.so.5)
#6  0x00007f033c411786 n/a (libQt5Core.so.5)
#7  0x00007f033bdef5a2 start_thread (libpthread.so.0)
#8  0x00007f033b9c3303 __clone (libc.so.6)

Stack trace of thread 2222:
#0  0x00007f033b9b85c7 __poll (libc.so.6)
#1  0x00007f033be581de n/a (libglib-2.0.so.0)
#2  0x00007f033be58313 g_main_context_iteration (libglib-2.0.so.0)
#3  0x00007f033c60dbd5 _ZN20QEventDispatcherGlib13processEventsE6QFlagsIN10QEventLoop17ProcessEventsFlagEE (libQt5Core.so.5)
#4  0x00007f033c5b79eb _ZN10QEventLoop4execE6QFlagsINS_17ProcessEventsFlagEE (libQt5Core.so.5)
#5  0x00007f033c410635 _ZN7QThread4execEv (libQt5Core.so.5)
#6  0x00007f033c411786 n/a (libQt5Core.so.5)
#7  0x00007f033bdef5a2 start_thread (libpthread.so.0)
#8  0x00007f033b9c3303 __clone (libc.so.6)

Stack trace of thread 2225:
#0  0x00007f033bdf583c pthread_cond_timedwait@@GLIBC_2.3.2 (libpthread.so.0)
#1  0x00007f033c4171b9 _ZN14QWaitCondition4waitEP6QMutex14QDeadlineTimer (libQt5Core.so.5)
#2  0x00007f033c4172db _ZN14QWaitCondition4waitEP6QMutexm (libQt5Core.so.5)
#3  0x00007f033c414f73 n/a (libQt5Core.so.5)
#4  0x00007f033c411786 n/a (libQt5Core.so.5)
#5  0x00007f033bdef5a2 start_thread (libpthread.so.0)
#6  0x00007f033b9c3303 __clone (libc.so.6)

Stack trace of thread 2224:
#0  0x00007f033bdf583c pthread_cond_timedwait@@GLIBC_2.3.2 (libpthread.so.0)
#1  0x00007f033c4171b9 _ZN14QWaitCondition4waitEP6QMutex14QDeadlineTimer (libQt5Core.so.5)
#2  0x00007f033c4172db _ZN14QWaitCondition4waitEP6QMutexm (libQt5Core.so.5)
#3  0x00007f033c414f73 n/a (libQt5Core.so.5)
#4  0x00007f033c411786 n/a (libQt5Core.so.5)
#5  0x00007f033bdef5a2 start_thread (libpthread.so.0)
#6  0x00007f033b9c3303 __clone (libc.so.6)

</details>

**Comment by Aokromes** [comment]
this bug is still valid? if yes, plz next time send crash and post crash id here. if you dont' get crash send dialog, plz use gdb.

**Comment by GiorgioBelli** [comment]
i have the same problem on Linux Mint 19

here the gdb output:
https://pastebin.com/nwgBi5vx

**Comment by Aokromes** [comment]
your is more https://github.com/telegramdesktop/tdesktop/issues/7086

**Comment by Aokromes** [comment]
no answer after near 1 month, if this bug is still valid, open a new ticket with one updated telegram version downloaded from desktop.telegram.org or github.com
