### ISSUE TITLE
Ui::TypingAnimation causes high CPU utilization, likely due to excessive rendering

### ISSUE THREAD

**Issue by kennylevinsen** [telegramdesktop/tdesktop#6294]
Telegram on Linux (installed with flatpak) sees high CPU utilization during animations such as Ui::TypingAnimation.

Based on brief look at the source, my hunch is that this is caused by excessive painting: It seems that everything renders every time paint is kicked off, rather than only rendering content that has changed.

This probably also means that damage tracking is not used, further lowering efficiency.

### Steps to reproduce
1. Open Telegram
2. Have someone type, causing typing animations in the friend list
3. Monitor CPU utilization.

### Expected behaviour
CPU utilization should be mostly unaffected.

### Actual behaviour
CPU utilization is around 30%.

For reference, playing a 1080p youtube video with MPV uses ~10% CPU on this machine. One would imagine that 3 dots should be cheaper to render than 1080p worth of content changing on every frame. :)

### Configuration
**Operating system:**

Arch Linux on an XPS13 (note the low-power CPU, which amplifies utilization). Running under Wayland.

**Version of Telegram Desktop:**

1.7.14

**Used theme**:

Classic

**Comment by 23rd** [comment]
I'm afraid it's a duplication of this #4406. =(
