### ISSUE TITLE
Read receipts not showing

### ISSUE THREAD

**Issue by SmartManoj** [telegramdesktop/tdesktop#6298]
![image](https://user-images.githubusercontent.com/7231077/61216531-2f451680-a72b-11e9-8d73-de5c4e938163.png)

 

### Actual behaviour
Works in other clients

### Configuration
**Operating system:** Windows 10

**Version of Telegram Desktop:** 1.7.14

**Used theme**: Midnight

<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by RememberTheAir** [comment]
Can you at least re-check your issues before submitting them? There's the whole unfilled template there, you didn't even bother to remove it.

Also, you didn't even say what kind of chat is that. Is it a private chat? If so, make sure the other user is not using one of those clients that allow you to hide read receipt

**Comment by SmartManoj** [comment]
Private chat


Weird ,after sending message to him , it shows !!
Tried restart the app before

**Comment by SmartManoj** [comment]
@RememberTheAir What  should do I fill in Expected behaviour ?
The negation of Title ?

**Comment by Aokromes** [comment]
this issue is still valid?

**Comment by Aokromes** [comment]
no answer after more than 1 month, closing, if this bug is still valid open a new ticket using updated telegram version.

**Comment by SmartManoj** [comment]
Nope

> this issue is still valid?
