### ISSUE TITLE
[Bug] URL href link at the end of group names is incorrect

### ISSUE THREAD

**Issue by ghost** [telegramdesktop/tdesktop#630]
telegram version: 0.8.0
env: Linux 64 bits

When setting a group name with an URL at the end of it,
the line showing the change renders incorrectly the URL:

ie: fabienwang changed the group name to «test: https://etherpad.mozilla.org/im00oAY706»
The link contains the » at the end while it shouldn't

**Comment by Aokromes** [comment]
this bug is still valid on 1.9.8?

**Comment by Aokromes** [comment]
no answer after near 1 month, if this bug is still valid, open a new ticket with one updated telegram version downloaded from desktop.telegram.org or github.com
