### ISSUE TITLE
[Feature Request] update notification badge for muted chats

### ISSUE THREAD

**Issue by tooomm** [telegramdesktop/tdesktop#6300]
Telegram on iOS updates the badge count on new messages for muted chats.
No notification is shown but the count increases.

I would like to see the same behavior on Telegram Desktop.
The Telegram icon in the lower right taskbar shows no badge once a new message for a muted chat arrives.

If it would be a setting (default on?) that would be pretty nice, too! Globally, or on a per chat basis when you enable the muted chat for example.

Telegram Desktop on Windows 10, v1.7.14

**Comment by RememberTheAir** [comment]
![image](https://user-images.githubusercontent.com/16143208/61267990-5981ed00-a79a-11e9-86e7-a2c677b947be.png)
It's there

**Comment by tooomm** [comment]
👍
