### ISSUE TITLE
Please implement the PTT (Push To Talk) feature on smartphones and computers.

### ISSUE THREAD

**Issue by cat9life** [telegramdesktop/tdesktop#6309]
Communication like a walkie talkie (type "Zello")

**Comment by SmartManoj** [comment]
[Check ](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.voiceaccess)

**Comment by cat9life** [comment]
Hello!
I want to update the request for the implementation of the function
with an example

Microsoft Teams is getting a Walkie Talkie feature so you can reach colleagues all day long
https://www.theverge.com/2020/1/9/21058313/microsoft-teams-walkie-talkie-push-to-talk-feature-preview

**Comment by SmartManoj** [comment]
error
