### ISSUE TITLE
Fcitx input method Support

### ISSUE THREAD

**Issue by Norgerman** [telegramdesktop/tdesktop#631]
I find it that the reason why the tdesktop cannot use fcitx input method is that should link the qt5-fcitx plugin static lib manually.Qt5-fcitx project is on github too, but it only has shared lib,so I tried to build it into a static lib but I failed to link and load it in a qt static project.And I try to rebulid tdesktop but always    show error generatedfiles not found(system opensuse 13.2).

**Comment by shouya** [comment]
#442

**Comment by telegramdesktop** [comment]
Please check out 0.8.50 dev version, it should be fine there, I've added Qt plugins for IBus and Fctix.

**Comment by Norgerman** [comment]
Thanks!
