### ISSUE TITLE
Disabled Notifications cause popup circles

### ISSUE THREAD

**Issue by chgad** [telegramdesktop/tdesktop#6311]
### Steps to reproduce
1. Create Groupchat
2. Disable Notifications (Forever)
3. Tell someone to write into it

### Expected behaviour
I expect that if someone writes in the groupchat i do not get a Desktopnotification. No Message, No Redcircle with white number of not read messages and neither a Greycircle.
### Actual behaviour
In the Taskbar i get a red circle with white numbers for Notification disabled Chats. And in the Programm bar (Upper right Corner for Ubuntu) i get the grey circle with white numbers in it.

### Configuration
**Operating system: Ubuntu 18.10**

**Version of Telegram Desktop: 1.7.14**

**Used theme**:

**Comment by SmartManoj** [comment]
You get badge counter or the notification popup

Could you provide a ScreenShot?

**Comment by chgad** [comment]
Ofcourse:

![Telegramm_example_screenshot](https://user-images.githubusercontent.com/21121667/61448102-8da00e00-a952-11e9-8f9b-9c71a0909e3a.png)

Here you go.
The Red circle stays there even if i read the one message from the first Chat.

**Comment by SmartManoj** [comment]
It is badge counter only 
https://github.com/telegramdesktop/tdesktop/issues/5053#issuecomment-410285112

**Comment by chgad** [comment]
Thanks, found the setting solved the issue.

**Comment by SmartManoj** [comment]
@chgad Next time , Close and comment
