### ISSUE TITLE
tg links broken

### ISSUE THREAD

**Issue by SmartManoj** [telegramdesktop/tdesktop#6313]
### Steps to reproduce
1. Open tg://msg_url?url=http://smartmanoj.blogspot.com
2.
3.

### Expected behaviour

Should show Choose Recipient...
### Actual behaviour
Just opening telegram

### Configuration
**Operating system:** Windows 10

**Version of Telegram Desktop:** 1.7.14

**Used theme**: Midnight

<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by Sea-n** [comment]
This is **NOT** normal URL that clients should handles

Please use http://t.me/share/url?url=XXX for sharing link

E.g. https://www.sean.taipei/&text=Hello+World

**Comment by SmartManoj** [comment]
That too fails 
https://telegram.dog/share/url?url=http://smartmanoj.blogspot.com/

**Comment by SmartManoj** [comment]
![image](https://user-images.githubusercontent.com/7231077/61715385-ace7d280-ad7a-11e9-9cbd-610c49248d78.png)

**Comment by SmartManoj** [comment]
"D:\1.Manoj\2.Soft-war\5.Rest\T\T.exe" -workdir "D:/1.Manoj/2.Soft-war/5.Rest/T/" -- "%1"

I just noticed that only forward slash should be used in -workdir flag
