### ISSUE TITLE
Rotate images in the desktop application

### ISSUE THREAD

**Issue by 4680864** [telegramdesktop/tdesktop#6317]
### Is your feature request related to a problem?
Images cannot be rotated.

### Describe the solution you'd like
The menu must contain items to rotate the image

### Describe alternatives you've considered
—

### Additional context
Almost always the images are created on a mobile phone that can be rotated in the hands of any way, but the monitor in the hands can not spin.

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/1413
