### ISSUE TITLE
[Feature Request] WebM support

### ISSUE THREAD

**Issue by faissaloo** [telegramdesktop/tdesktop#6318]
### Is your feature request related to a problem?
Only MP4s seem to play, Webms are just downloadable like regular files.  

### Describe the solution you'd like
Would be great if I Webms could be played like MP4s are in the in app video player, it's a pretty widely used format.  

### Describe alternatives you've considered
N/A  

### Additional context
N/A

**Comment by 23rd** [comment]
#2842.
