### ISSUE TITLE
[Feature Request] Notify user when unable to connect for a long time

### ISSUE THREAD

**Issue by Jamesits** [telegramdesktop/tdesktop#632]
Sometimes the network is unstable, and Telegram Desktop lost connection but since it's in background, I have no idea if it's working or not. So please add a function to notify user if the connection is break for a certain time (e.g. 3 minutes).

**Comment by cobalto** [comment]
THIS IS A HUGE NEED.

**Comment by earendil02** [comment]
Agreed, very useful!

**Comment by Walkman100** [comment]
Maybe not a notification, but at least the tray icon should change colour or something

Or an option to select one of them :P

**Comment by verma-neeraj-in** [comment]
Both of these would be nice addition. :+1:

**Comment by auchri** [comment]
Duplicate #470
