### ISSUE TITLE
Images sent from Reddit become stickers

### ISSUE THREAD

**Issue by MasterGroosha** [telegramdesktop/tdesktop#6321]
### Steps to reproduce
0. Use Firefox
1. Go to Reddit. For example, [this link](https://www.reddit.com/r/rubberducks/comments/cfxtbn/i_have_children_now/) (safe for work)
2. Right click on image, "Copy Image" (to clipboard)
3. Paste it somewhere in Telegram

### Expected behaviour
Image should be sent as image

### Actual behaviour
Image is sent as sticker

![изображение](https://user-images.githubusercontent.com/2780044/61597665-e3f3a200-ac1b-11e9-889a-2f746c054245.png)

### Configuration
**Operating system:** Windows 10
**Version of Telegram Desktop:** 1.7.15 beta
**Version of Mozilla Firefox:** 68.0.1 64-bit

**Comment by omkarnathsingh** [comment]
Reddit images are webp format which is same as Stickers. Its a feature, not a bug.

**Comment by mehti1367** [comment]
I followed your steps and it sent as image.

**Comment by Aztek92** [comment]
The same problem is now with 9gag. Quite IRRITATING.

**Comment by GuillaumeCauvet** [comment]
> 
> 
> Reddit images are webp format which is same as Stickers. Its a feature, not a bug.

Unlik from the Frontpage or a post, if I open the source of an image, the url parameters still has a "&auto=webp" but it would copy/past as an actual image from there, not a sticker

**Comment by twojnarowski** [comment]
I have this problem when saving images from 9gag to my phone. They are saved in .webp format and after sending it on android telegram app, they become a sticker, and other people in chat can't see anything in the picture, since it is small like a sticker and can't be enlarged.

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/6276
