### ISSUE TITLE
[Feature Request] Allow resend of messages sent before conversion of Supergroup 

### ISSUE THREAD

**Issue by SmartManoj** [telegramdesktop/tdesktop#6326]
### Is your feature request related to a problem?

Currently we can forward messages to the group.

### Describe the solution you'd like

It would be convenient if there is a resend option in context menu

**Comment by 23rd** [comment]
It's pretty similar to that #5142 issue.
In addition, this function will be so rarely used that it will only overload the context menu. This feature can be good for your own fork.
