### ISSUE TITLE
Jump to pinned message hotkey triggers on double caret input

### ISSUE THREAD

**Issue by VeRychard** [telegramdesktop/tdesktop#6327]
### Steps to reproduce
1. Have at least 4 pinned conversations
2. Select a conversation which is not pinned
3. Start texting, and try writing "^^"

### Expected behaviour
the string "^^" is written in the current chat

### Actual behaviour
After the first character doesn't appear in your chat, it switches to the the 3rd pinned conversation and one "^" character appears in it's text input

### Configuration
Win10

**Version of Telegram Desktop:**
1.7.15beta

<details>I write caret with "Alt Gr + 3", and the jump to 3rd conversation is bound to "Ctrl + 3", and it should only trigger on that and not on "Alt + Ctrl + 3".
</details>

**Comment by b3z** [comment]
This problem doesn't exist on v1.7.14 macOS 10.14.5

**Comment by VeRychard** [comment]
If you added the 3rd, 4th pinned convo right now, do a restart on the app, and then try it again. (on win sometimes the problem didn't appear without restart)
Else I'm thinking the difference is in macOS key mapping.

**Comment by Aokromes** [comment]
this issue is still valid?

**Comment by VeRychard** [comment]
> this issue is still valid?

Re-checked in Win - v2.1.8 beta, seems working fine, even if you have folders or not.

closing
