### ISSUE TITLE
Archived chats are always at the bottom of search results

### ISSUE THREAD

**Issue by RememberTheAir** [telegramdesktop/tdesktop#6330]
### Steps to reproduce
1. archive a chat
2. search for its title

### Expected behaviour
Search results are ordered by last message sent, regardless of their archiving status

### Actual behaviour
Chats in the archive are always listed at the bottom

***

I'm not sure this is a bug, it's probably intended to work like that, but I don't think it's actually useful to users to have their archived chats at the bottom of the results. I find myself searching for archived chats more often than I search for non-archived ones. Also, mobile apps sort the search result regardless of their archiving status, and it's actually a pain to scroll down the search results just to find that chat/channel you are looking for

### Configuration
**Operating system:** Windows 10/Linux Mint

**Version of Telegram Desktop:** 1.7.15

**Comment by Aokromes** [comment]
this issue is still valid?

**Comment by RememberTheAir** [comment]
Yes

**Comment by RememberTheAir** [comment]
Still relevant

**Comment by RememberTheAir** [comment]
Behavior didn't change, so i guess it's still valid

**Comment by john-preston** [comment]
Yes, it works as intended. Right now there is no fast easy way to merge two lists together, they're shown one after another.

**Comment by RememberTheAir** [comment]
Okay, I understand. I can close the issue now
