### ISSUE TITLE
Video preview is blurred

### ISSUE THREAD

**Issue by Neurotoxin001** [telegramdesktop/tdesktop#6332]
### Steps to reproduce
1. For example go to this post https://t.me/lentachold/24881
2. It's blurred and I can't see thumbnail to preview what is that video, I must click...

This issue with small videos too:
https://t.me/oldlentach/34486
https://t.me/moscowmap/12772

### Expected behaviour
Preview must be loaded

### Actual behaviour
Preview is not loading

### Configuration
**Operating system:** win10 ltsc 1809

**Version of Telegram Desktop:** 1.7.15

**Used theme**: default

![image](https://user-images.githubusercontent.com/39812401/61779365-35ad4f80-ae09-11e9-9811-476ee6939780.png)
![image](https://user-images.githubusercontent.com/39812401/61779541-89b83400-ae09-11e9-83c6-8690a39c0d12.png)

Why do you remove "auto-download videos" from settings?...

**Comment by Neurotoxin001** [comment]
It's still not fixed and it's annoying

**Comment by Neurotoxin001** [comment]
When I go to "videos" in channel media - all previews is loading instantly, why you can't do that they will loading when I open the channel?

**Comment by Neurotoxin001** [comment]
Seems like it's fixed in 1.9.2 beta, thanks!!!

**Comment by Neurotoxin001** [comment]
Can you please fix it? 1.9.7 still have this issue. There are many ppl that don't want to use autoplay, but without autoplay there is annoying blur. :/

**Comment by john-preston** [comment]
@Neurotoxin001 A high quality thumbnail can be generated only when streaming started and first frame of the video is downloaded. Right now this happens only when video is autoplayed or manually started.

**Comment by Neurotoxin001** [comment]
I understand that but:
1. Why it's working on iOS official app without autoplay?
2. Why some of videos have high quality thumbnail even after clear media cache and restart the app?
3. Why they can be loaded after open "Videos" tab from the channel info?

**Comment by john-preston** [comment]
@Neurotoxin001 1. I think they still download a part of file to generate thumbnails.

2. Some videos have a large thumbnail sent along the document (320x320), some have only small, that looks ugly without blur (90x90).

3. 🤔 that's interesting, maybe there are large thumbnails along the document after all, videos overview doesn't load any parts of the file, only the thumbnails.

**Comment by Neurotoxin001** [comment]
But can you "fix" it?

And little more about 3:
If I open this
![image](https://user-images.githubusercontent.com/39812401/72975298-a269cc80-3de1-11ea-8a17-83fc4634983a.png)
And download thumbnails for all videos:
1. all videos in channel will have high quality thumbnail when I scroll and see them
2. then I restart app
3. some of videos is again become with blurred thumbnail

**Comment by john-preston** [comment]
@Neurotoxin001 Is it a public channel so I can test right on it?

**Comment by Neurotoxin001** [comment]
Yes. it's public channel

**Comment by Neurotoxin001** [comment]
![image](https://user-images.githubusercontent.com/39812401/72985858-f8e20580-3df7-11ea-97bb-eb38958b6301.png)

**Comment by Neurotoxin001** [comment]
Seems like some videos still "bugged":
https://t.me/c/1278861388/204 (invite link https://t.me/joinchat/AAAAAEw54EysYosPjBKkpw)
![image](https://user-images.githubusercontent.com/39812401/73116672-736f6a00-3f4b-11ea-99d4-24996c36510e.png)

And https://t.me/c/1278861388/197 (same invite link)
![image](https://user-images.githubusercontent.com/39812401/73116675-841fe000-3f4b-11ea-8ad4-caf6b864be96.png)

https://t.me/c/1278861388/174
![image](https://user-images.githubusercontent.com/39812401/73116698-c47f5e00-3f4b-11ea-961f-c2ef6c9c6da0.png)


First video have good quality, second is crappy.

**Comment by Neurotoxin001** [comment]
Same issue with gifs:
https://t.me/twochannel/16573955
https://t.me/twochannel/16573962
https://t.me/twochannel/16573967
https://t.me/twochannel/16573969
https://t.me/twochannel/16573977

**Comment by Neurotoxin001** [comment]
> (invite link https://t.me/joinchat/AAAAAEw54EysYosPjBKkpw)

"large" videos doesn't load too:
![image](https://user-images.githubusercontent.com/39812401/73422404-f0c72000-4339-11ea-946f-a1d568698e3e.png)

**Comment by Neurotoxin001** [comment]
Another example:
https://t.me/bazabazon/2906

**Comment by Neurotoxin001** [comment]
I don't know what is wrong with this:
https://t.me/huepub/11513

Size is small...
![image](https://user-images.githubusercontent.com/39812401/73431448-7f936700-4351-11ea-9cc6-5ad4617d3cc8.png)

**Comment by Neurotoxin001** [comment]
Some more examples:
https://t.me/breakingmash/16013
https://t.me/breakingmash/16012
https://t.me/breakingmash/16010
https://t.me/mudak/34895

They doesn't load even when I open the channel videos list
![image](https://user-images.githubusercontent.com/39812401/73446662-33a2eb00-436e-11ea-9dfe-6c5742066307.png)

**Comment by john-preston** [comment]
@Neurotoxin001 This one was a server side bug, please check now (after app relaunch).

**Comment by Neurotoxin001** [comment]
These is fixed:
https://t.me/Lshot/15891
https://t.me/presshata/4409
https://t.me/breakingmash/16013
https://t.me/breakingmash/16012
https://t.me/breakingmash/16010
https://t.me/mudak/34895
https://t.me/huepub/11513

But these is not:
https://t.me/twochannel/16573955
https://t.me/twochannel/16573962
https://t.me/twochannel/16573967
https://t.me/twochannel/16573969
https://t.me/twochannel/16573977

**Comment by john-preston** [comment]
@Neurotoxin001 Those look like old-uploaded GIFs (maybe from Saved GIFs tab? I don't know), because they have not thumbnails cropped to 320x320 (that I don't blur, because they're big enough), but the ones cropped to 90x90 (before some time ago this was the resolution for thumbnails of videos / GIFs), and those are blurred, because they're too small.

**Comment by Neurotoxin001** [comment]
Ok then, but now I noticed blur on this:
https://t.me/mudak/34895 too (added it to "fixed" list by mistake)

Before I click on it:
![image](https://user-images.githubusercontent.com/39812401/73646561-c1dae200-468a-11ea-9b31-dfcd792f4404.png)

After:
![image](https://user-images.githubusercontent.com/39812401/73646566-c56e6900-468a-11ea-8c89-6442035222d8.png)

**Comment by john-preston** [comment]
@Neurotoxin001 Thanks :) This one is tdesktop bug, I make non-blurred version only when width and height of the thumbnail is larger than 160px. But this thumbnail 145x320, because this video has very strange aspect ratio (very narrow).

I'll fix it in the next version (if at least one side is larger than 240 I won't blur it no matter what second side's size is).

**Comment by Neurotoxin001** [comment]
Seems like it's still not fully fixed:
https://t.me/mbkhmedia/16686

![image](https://user-images.githubusercontent.com/39812401/74015772-505ca580-49a2-11ea-8fac-183db15e4d09.png)
![image](https://user-images.githubusercontent.com/39812401/74015786-55b9f000-49a2-11ea-92c0-1b81e1dc3075.png)

Videos have Width: 1 280 pixels and Height: 720 pixels and it's still blurred.

**Comment by john-preston** [comment]
@Neurotoxin001 I think this one happens because of an album. I'll try to apply the same fix for album videos thumbnails.

**Comment by Neurotoxin001** [comment]
Some of videos here:
https://t.me/rand2ch

is blurred even in videos list:
![image](https://user-images.githubusercontent.com/39812401/74107272-1e546a80-4b7f-11ea-8771-7d388424f3a6.png)

But when I open the post with video - all is fine.
First blurred video (after egg):
https://t.me/rand2ch/13311

**Comment by Neurotoxin001** [comment]
1.9.11 issue still here even after clearing cache https://github.com/telegramdesktop/tdesktop/issues/6332#issuecomment-583298663

![image](https://user-images.githubusercontent.com/39812401/74184123-42837a80-4c57-11ea-86ec-0c9446da44aa.png)

**Comment by Neurotoxin001** [comment]
Another example:
https://t.me/r_chp/5674
![image](https://user-images.githubusercontent.com/39812401/74240515-3517d000-4ceb-11ea-89ef-4fcf6f386acb.png)


Please check it before new beta.

**Comment by Neurotoxin001** [comment]
1.9.12 :(

![image](https://user-images.githubusercontent.com/39812401/74272630-049e5900-4d20-11ea-9802-ac12fdef2304.png)

**Comment by Neurotoxin001** [comment]
Don't know why but in this channel:
http://t.me/joinchat/AAAAAFHdmc0FeBEdk0UEeQ
All gifs is blurred

1.9.13

**Comment by Neurotoxin001** [comment]
https://t.me/karaulny/197900

Even without album blurred too.
1.9.14

**Comment by Neurotoxin001** [comment]
![image](https://user-images.githubusercontent.com/39812401/75703550-bc43dc80-5cc8-11ea-8b73-03503515f300.png)

https://t.me/rand2ch/15265
1.9.14

**Comment by john-preston** [comment]
@Neurotoxin001 Ok, I found a mega-stupid bug with albums, so in albums it should be better in the next version.

**Comment by john-preston** [comment]
(rand2ch/15265 was affected and other album examples)

**Comment by john-preston** [comment]
@Neurotoxin001 https://t.me/karaulny/197900 this one is blurred on purpose, it is a video uploaded by some old software (I guess.. or buggy), because it has 90x50 thumbnail. If you upload a video right now through the official apps they should generate and save a thumbnail with a 320 pixel largest side, not 90 like before. I don't blur 320px thumbnails, because they look fine, but I do blur old small ones.

**Comment by Neurotoxin001** [comment]
Albums is fixed now, thanks, but this https://github.com/telegramdesktop/tdesktop/issues/6332#issuecomment-583874301 is still here

Try it by yourself on https://t.me/rand2ch
Just open video list and scroll down ~4 full mouse scrolls, some of videos have preview, some is blurred. It's stay blurred even after restart. But when I go to these videos in channel - previews is loaded. Issue only in videos list in channel info. 1.9.20

![image](https://user-images.githubusercontent.com/39812401/76684357-7cf88280-661c-11ea-9bbf-833849950573.png)

**Comment by Neurotoxin001** [comment]
2.1.4 is still have ^ this issue.

**Comment by Neurotoxin001** [comment]
LOL seems like you must just wait for a few seconds and then previews is being loaded...

https://i.imgur.com/hbHyctn.mp4

**Comment by Neurotoxin001** [comment]
> LOL seems like you must just wait for a few seconds and then previews is being loaded...

But seems like it's working not always...

Here thumbs is not loading even if I wait
https://t.me/tg1337const

**Comment by Neurotoxin001** [comment]
In 2.1.8 beta seems like it's finally fixed, now thumbs loads very fast and does not reset after relaunch
