### ISSUE TITLE
[Question] message filter

### ISSUE THREAD

**Issue by hvuhsg** [telegramdesktop/tdesktop#6333]
Hi I want to make a fork of this software with the option to filter unwanted message from channels and groups

That mean to change for example every photo to text "photo"

Which file can i add my filter in.

Iam a programmer but I didn't found any documentation or understand the code to know where to 
add my filter function

if turn photo to text its take more then a function
plz help me not to see the photo at all

**Comment by SmartManoj** [comment]
Kinda #5292
