### ISSUE TITLE
[Bug] Unable to search music by filename

### ISSUE THREAD

**Issue by MaxRev-Dev** [telegramdesktop/tdesktop#6335]
### Steps to reproduce
1. Open a chat with music uploads
2. Try to search by filename or by partial track name

### Expected behaviour
Find a file by a partial name of song.

### Actual behaviour
Files that doesn't have metadata are not found. Also it requires a full name from the file metadata.

### Configuration
OS: **Windows 10 Pro, build 1903 (18362.239)**
Version: **1.7.15**, Dark Theme

### Screenshots
<details>
  <summary>Click to expand</summary>
<p>

1. Search by metadata
![image](https://user-images.githubusercontent.com/24393967/61955904-b2385d80-afc4-11e9-8569-7fc89c7b5114.png)
![image](https://user-images.githubusercontent.com/24393967/61955926-bcf2f280-afc4-11e9-8814-0fd85fc82a55.png)

2. Search by filename
![image](https://user-images.githubusercontent.com/24393967/61955950-ca0fe180-afc4-11e9-81c5-c48810b2b2f0.png)
![image](https://user-images.githubusercontent.com/24393967/61955971-d431e000-afc4-11e9-8392-279cf90bc7d4.png)
</p>
</details>

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/6173
