### ISSUE TITLE
[Question] Where is the code related to the search box and the function of receiving pictures video?

### ISSUE THREAD

**Issue by skycloudly** [telegramdesktop/tdesktop#6337]
Where is the code related to the search box and the function of receiving pictures video?I plan to recompile a telegram client without search box and picture video according to the source code.Please help me

**Comment by ilya-fedin** [comment]
https://github.com/telegramdesktop/tdesktop/blob/dev/Telegram/SourceFiles/ui/search_field_controller.cpp#L98
I don't know what you mean by "picture video"
