### ISSUE TITLE
Missing Feature - Call Rejection Message.

### ISSUE THREAD

**Issue by SmartManoj** [telegramdesktop/tdesktop#6338]
![image](https://user-images.githubusercontent.com/7231077/61993534-c6df2900-b08a-11e9-80fe-5de7f2bd91ae.png)
![image](https://user-images.githubusercontent.com/7231077/61993538-d3fc1800-b08a-11e9-8544-ad3c1947ee1b.png)

**Comment by SmartManoj** [comment]
@stek29 Create another issues template for this kind

**Comment by auchri** [comment]
Why do you think that the current template is not suitable for your type of request?

**Comment by SmartManoj** [comment]
In question template ?

**Comment by auchri** [comment]
What?

**Comment by SmartManoj** [comment]
> current template

Which one ?

**Comment by SmartManoj** [comment]
error
