### ISSUE TITLE
Packet processing failed when play voice

### ISSUE THREAD

**Issue by MrMahdi313** [telegramdesktop/tdesktop#6339]
### Expected behaviour
doesn't play voice

### Actual behaviour
Tell us what happens instead
got error like this:
`[ogg @ 0x7f0358001400] Packet processing failed: Invalid data found when processing input`

### Configuration
**Operating system:**
Fedora30 KdePlasma-Spin

**Version of Telegram Desktop:**
1.7.14
**Used theme**:
Night-Mode
<details><summary><b>Logs</b>:</summary>
[log_start9.txt](https://github.com/telegramdesktop/tdesktop/files/3438210/log_start9.txt)
</details>

**Comment by 23rd** [comment]
#5843.
