### ISSUE TITLE
Can delete default stickers

### ISSUE THREAD

**Issue by Brawl345** [telegramdesktop/tdesktop#634]
When you make a sticker (convert any picture to WebP and send it as file), it will be saved in the stickers list and you can delete it with the "X" in the upper right corner, when you hover over it. But you can also delete the default stickers, when you hover over them, even though there's no "X".

Tested on Windows 8.1 with v0.8.1 dev

**Comment by Akamaru** [comment]
Same here on Windows 8.1 with tdesktop 0.8.1 dev

**Comment by xtopolis** [comment]
Related to this bug: Deleting all of the default stickers can cause the app to crash. (MacOSX)

I do not have solid steps to reproduce, but when the sticker feature first came out, it was more prevalent. I did reproduce it in [0.8.11 stable], but not reliably.

Not necessarily a bug, but it would be nice if the default stickers were optional/or did not come back on app restart if they were deleted.

**Comment by auchri** [comment]
Hide the default sticker pack: #909
