### ISSUE TITLE
Media cache is never cleared and become very big on MacOS

### ISSUE THREAD

**Issue by gagarine** [telegramdesktop/tdesktop#6345]
The `~/Library/Group Containers/*.keepcoder.Telegram/account-*/postbox/media` folder can become super big (100 GB) as it's never cleared.

Someone even wrote a blog post about it: https://medium.com/@eugene_lazarev/telegram-on-mac-os-takes-no-care-about-your-disk-storage-and-feels-great-about-it-2c62ded92924

**Comment by john-preston** [comment]
@gagarine This is not Telegram Desktop, but another app for macOS. You can try Telegram Desktop at https://desktop.telegram.org

**Comment by gagarine** [comment]
Thanks @john-preston ! It's actually this one then https://github.com/overtake/TelegramSwift
I realize now than depending where you go on the telegram website you have two different version:
- https://telegram.org/dl/macos
- https://telegram.org/dl/desktop/mac
