### ISSUE TITLE
Everybody on the member list popup is shown as admin

### ISSUE THREAD

**Issue by wodim** [telegramdesktop/tdesktop#6347]
On the popup that appears when you hover over the "x members" label at the top of the window when you're looking at a group, everybody has a grey star next to their names, even if they are not admins. I think this only happens if you're an admin yourself.

![image](https://user-images.githubusercontent.com/1001553/62051930-b9ee4100-b214-11e9-92e6-f021001351c9.png)

### Configuration
**Operating system:** Windows 

**Version of Telegram Desktop:** 1.7.14

**Used theme**: None?

**Comment by Aokromes** [comment]
cannot reproduce on 1.7.15 windows 10 20h1.
tested on groups and super groups where i am admin, owner and member.

**Comment by b3z** [comment]
> cannot reproduce on 1.7.15 windows 10 20h1.
> tested on groups and super groups where i am admin, owner and member.

also can't reproduce on 1.7.14 MacOS 10.14.5

**Comment by wodim** [comment]
Popup:

![image](https://user-images.githubusercontent.com/1001553/62426890-18bb2b00-b6eb-11e9-88a7-7d81cfc62061.png)

Group Info "window":

![image](https://user-images.githubusercontent.com/1001553/62426900-2ffa1880-b6eb-11e9-88ce-b318de3ea92b.png)

**Comment by Aokromes** [comment]
https://i.imgur.com/nXHKu98.png

**Comment by wodim** [comment]
Admin, not creator.

**Comment by b3z** [comment]
> Admin, not creator.

Do you have an Admin in the group?

**Comment by wodim** [comment]
Yes I do. I am an admin, not a creator (my star is grey, not blue).

**Comment by wodim** [comment]
I didn't clarify this because I wasn't sure about the importance of being a creator. Someone who's an admin can reproduce it but the creator can't.

**Comment by RadRussianRus** [comment]
@wodim Is this bug still valid? Can you repoduce it on latest 1.9.21?

**Comment by wodim** [comment]
Yes.

**Comment by ilya-fedin** [comment]
Maybe you can give more info on group settings?

**Comment by wodim** [comment]
Sure. Ask away.

**Comment by ilya-fedin** [comment]
> Sure. Ask away.

I mean please give as more info as you can. Is it public or private, when it was created, if is it was created as non-supergroup, if messages are visible for new members and etc.

**Comment by Aokromes** [comment]
i cannot reproduce myself tried:
a group where i am owner.
a group where i am admin.
a group where i am user.

**Comment by wodim** [comment]
It was created on Feb 3, 2014.

I don't know if it was a non-supergroup or whether it actually is. How can I check?

I don't know if messages are visible for new members. We haven't invited anybody in years. I don't see anything regarding that in the "Manage group" dialog.

**Comment by ilya-fedin** [comment]
> How can I check?

Is it private? Have you seen `All members are admins` setting in group settings?

**Comment by wodim** [comment]
It is "private" in the sense that it is not publicly searchable and there is no invite link.

I can't say if there ever was a setting that said "All members are admins", I think that at no point of time all users were admins. I think there have always been normal users with no privileges.

**Comment by ilya-fedin** [comment]
Does this group have recent actions (admin's log)?

**Comment by wodim** [comment]
No, there is no action log option.

**Comment by ilya-fedin** [comment]
Well, it is not a supergroup and this explains why no one can reproduce this (these groups are deprecated and there is no way to create such group in 2020
