### ISSUE TITLE
Telegram starts super slow and Unicode fonts like Chinese and others show as square signs

### ISSUE THREAD

**Issue by huyndnse63331** [telegramdesktop/tdesktop#6348]
### Steps to reproduce
1. Run Telegram 1.7.15 beta on Ubuntu 18.04.2 (amd64)

### Actual behaviour
The binary `/opt/Telegram/Telegram` starts super slow, appropriate 1min and i managed to fix using this solution (https://github.com/telegramdesktop/tdesktop/issues/4240#issuecomment-388311151) &rarr; then i got another problem with the Unicode fonts (chinese, koreans, ...), they appeared in square signs so i got a solution for this at (https://github.com/telegramdesktop/tdesktop/issues/1900#issuecomment-216743570). But after i tried to add the `QT_IM_MODULE` in `~/.zshrc`, it didn't work. It only boots fast but the fonts were not fixed.
I created a bash script for starting Telegram as below
```bash
#!/bin/bash

FONTCONFIG_FILE=/etc/fonts/ /opt/Telegram/Telegram
```
Only 1 of those 2 options work, it won't work while i put them together, so 1 of the problems still remains.

### Configuration
**Operating system:** Ubuntu 18.04.2 (amd64)

**Version of Telegram Desktop:** 1.7.15 Beta

**Comment by huyndnse63331** [comment]
hello no one? :(

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/4576
