### ISSUE TITLE
Installation corrupted on Windows 10?

### ISSUE THREAD

**Issue by dragGH102** [telegramdesktop/tdesktop#6350]
I didn't have particular issues with Telegram desktop app on Windows 10 till a few weeks ago.

Since a few times I restart my Windows 10 machine with Telegram Desktop v.1.7.13 every time I restart the Telegram app shows a generic symbol (instead of telegram logo) and won't start unless I reinstall it

I don't know how to better explain the issue

**Comment by Aokromes** [comment]
Hi, try updating to 1.8.2 if you don't have this issue anymore you can close the ticket yourself.

**Comment by dragGH102** [comment]
the error hasn't happened (after I changed the way it autostarted). As far as I understand telegram updates itself from the UI, without manual installation. right?
