### ISSUE TITLE
[Feature Request] Multiple pinned messages per group at once

### ISSUE THREAD

**Issue by slondr** [telegramdesktop/tdesktop#6351]
Right now, groups only allow a single message to be pinned. New pins override old ones. My groups would like to be able to have multiple pins at once, so more than one message can be saved.

This would bring Telegram into feature parity with competitors such as Discord and Slack.

**Comment by RememberTheAir** [comment]
This must be supported by the API first, so tdesktop can't do nothing about it.

Btw, as a workaround, you can link multiple messages in your pinned message to make it easier to jump to different important messages in your chat

**Comment by slondr** [comment]
Interesting. Thank you for the response.
Where should I go to raise feature requests for the upstream API?

**Comment by RememberTheAir** [comment]
There isn't really a place where to suggest new features for the API, but usually, if enough people asks for something on [Twitter](https://twitter.com/telegram) or to the in-app support, Telegram might consider to implement the feature

**Comment by slondr** [comment]
Alright then. Thanks for the help!
