### ISSUE TITLE
I can not log in my account using Tdesktop

### ISSUE THREAD

**Issue by muhammedfurkan** [telegramdesktop/tdesktop#6352]
### Steps to reproduce
1. I return to the phone number screen when I enter the verification code
2. 
3. 

### Expected behaviour
Tell us what should happen
 I return to the phone number screen when I enter the verification code
### Actual behaviour
Tell us what happens instead

### Configuration
**Operating system:**
Windows 10 Release 10.0.18362 structure 18362

**Version of Telegram Desktop:**
1.7.14
**Used theme**:
Original

<details><summary><b>Logs</b>:</summary>
[log.txt](https://github.com/telegramdesktop/tdesktop/files/3450743/log.txt)

https://github.com/telegramdesktop/tdesktop/files/3450743/log.txt

https://del.dog/qocikumuca.sql
</details>

**Comment by LucaTheHacker** [comment]
try to use portable version
