### ISSUE TITLE
Incorrect error message in inviting user to channel

### ISSUE THREAD

**Issue by csepanda** [telegramdesktop/tdesktop#6355]
### Steps to reproduce
1. Add user who has blocked you to contacts. Let's call this user _Foo_
2. Create new channel or use existing one managed by you.
3. Try to invite this user _Foo_ to channel. No matter in channel info or in its creation.

### Expected behaviour
Telegram client should state that user has blocked you.

### Actual behaviour
Telegram show the following message:
> Could not add this user. Please try again latter.

### Configuration
**Operating system:**
Debian 9 GNU/Linux

**Version of Telegram Desktop:**
1.17.4

**Used theme**:
Night mode, Matrix

### Notes
Also same issue occurres when user try to add this user _Foo_ to existing group.

**Comment by Aokromes** [comment]
for me it looks intended.

**Comment by csepanda** [comment]
@Aokromes does this mean that such behaviour should be considered as privacy protection? I suppose that it is question in area UX vs privacy. If privacy in this question prevail over user's experience, I suppose, this issue may be closed.
