### ISSUE TITLE
Stickers are not displayed correctly

### ISSUE THREAD

**Issue by alpvonkri** [telegramdesktop/tdesktop#6358]
### Steps to reproduce
1. Open a chat (personal, group, channel) with any sticker (static or animated)

### Expected behaviour
1. Stickers should display correctly

### Actual behaviour
1. The stickers shows oversized, overlapping other stickers and/or messages, and blinking in the case of the animated ones.

### Configuration
**Operating system:**
1. Linux 64 bits
2. Windows 64 bits

**Version of Telegram Desktop:**
1. Prerelease 1.7.15

**Used theme**:
1. Default: Blue

### Evidence
**Images**:
![image](https://user-images.githubusercontent.com/104341/62471629-aab24a80-b762-11e9-9d8b-c4438298a1b4.png)
![image](https://user-images.githubusercontent.com/104341/62471714-daf9e900-b762-11e9-91a3-f1938be5c57b.png)

**Comment by john-preston** [comment]
@alpvonkri What exact version is shown in the About box or in the main menu?

**Comment by alpvonkri** [comment]
@john-preston it says alpha 4

**Comment by john-preston** [comment]
@alpvonkri It is a private alpha version, it’s issues are not tracked on this repository. I guess someone from testers leaked the version to the public and I’ll have to change the signing key now :(

To have this issue fixed you can logout, remove the TelegramForcePortable folder and download the latest public beta version.
