### ISSUE TITLE
[Feature Request] LaTeX syntax and code syntax highlight

### ISSUE THREAD

**Issue by mrpatiwi** [telegramdesktop/tdesktop#636]
This would be very useful for developers and scientists

**Comment by stolidity** [comment]
My friends and I were just talking about needing a /code \`code\` option in telegram. Would be sweet.

**Comment by drguildo** [comment]
Even just the ability to paste text in a fixed width font and no emoticons would help code readability a lot.

**Comment by stolidity** [comment]
Hell, even if it actually handled multiple spaces and tab correctly it would be better.

**Comment by rockneurotiko** [comment]
:+1:, would be awesome

**Comment by analca3** [comment]
You can use @LaTeX2IMGbot while Telegram adds it by default. Don't flood my Raspberry Pi, please :P. Source code is here.

https://github.com/analca3/LaTeX2IMGbot

**Comment by auchri** [comment]
Duplicate #250
