### ISSUE TITLE
Crash on waiting for DVD ROM

### ISSUE THREAD

**Issue by MPeti1** [telegramdesktop/tdesktop#6361]
### Steps to reproduce
1. Put a CD or DVD in your DVD ROM
2. Open it in a file explorer (Basic Windows file explorer, Total Commander)
3. Right click on a file which is on the CD/DVD, hover over "Send", select Telegram
4. Telegram Desktop opens, select a recipient, click send
5. Telegram Desktop hangs, and than crashes

### Expected behaviour
Tell us what should happen
It should wait for the optical drive to start reading the files, maybe display an indicator that the program is waiting for the optical drive

### Actual behaviour
Tell us what happens instead
Telegram crashes because it's main thread is probably locked for too long by waiting for the optical drive to respond

### Configuration
**Operating system: Windows 10 1809**

**Version of Telegram Desktop: 1.7.7**

**Used theme**: A custom theme, the app does not display anything related to it. I don't think it relevant anyway

<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
I would insert it if I would find it. There's no log file in the Telegram Desktop folder, and there's no information regarding it's whereabouts in the program nor in the project Wiki page
</details>

**Comment by Aokromes** [comment]
plz next time use send crash and post id here.

**Comment by Aokromes** [comment]
no answer after 1 month, if this bug is still valid, open a new ticket with one updated telegram version downloaded from desktop.telegram.org or github.com

**Comment by MPeti1** [comment]
Oh, sorry, I didn't see the email about your first answer. I'll check it now if it's still a problem

**Comment by MPeti1** [comment]
It seems to be ok now, I can't reproduce the problem in the way I first described it. The file is uploading and the progress is updated continuously as it should
