### ISSUE TITLE
Editmessage shortcut not working

### ISSUE THREAD

**Issue by LucaTheHacker** [telegramdesktop/tdesktop#6364]
### Steps to reproduce
1. Text a lot
2. scroll visual
3. try to edit a message

### Expected behaviour
When press upkey I should be able to edit my  message

### Actual behaviour
Sometimes on upkey pressing chat scrolls up

### Configuration
**Operating system:** W10-64bit

**Version of Telegram Desktop:** 1.7.15 beta

**Used theme**: nightmode default

**Comment by MasterGroosha** [comment]
Hmm... using 1.8.1 "up" arrow keeps scrolling instead of editing only when text field is not empty. If it is empty, "edit" action starts. Might this be your issue?

**Comment by LucaTheHacker** [comment]
Fixed in new version, surely will be better to edit a message whilst typing another one (like on android)
