### ISSUE TITLE
Invalid PBF data

### ISSUE THREAD

**Issue by MrMahdi313** [telegramdesktop/tdesktop#6366]
### Steps to reproduce
1. alias on ~/.bashrc:
`tstu='telegram-desktop -many -workdir ~/Apps/Telegram/Student/data'`
2.open terminal and enter this command on terminal:
`tstu`

### Actual behaviour
show this error interminal:
` Invalid PBF data`
![image](https://user-images.githubusercontent.com/20910185/62822054-688a6e00-bb93-11e9-8355-63062e03bd25.png)
and sometimes automatic crashed.

### Configuration
Lenovo G510
Fedora KDE-Plasma Spin

**Version of Telegram Desktop:**
1.7.14
**Used theme**:
Night Mode
<details><summary><b>Logs</b>:</summary>
[log_start0.txt](https://github.com/telegramdesktop/tdesktop/files/3479048/log_start0.txt)
</details>

**Comment by Vascom** [comment]
Same problem on telegram-desktop 2.1.10.

**Comment by ilya-fedin** [comment]
> show this error interminal

There's no such strings in tdesktop source code

> and sometimes automatic crashed

Please provide a backtrace

**Comment by MrMahdi313** [comment]
> > show this error interminal
> 
> There's no such strings in tdesktop source code
> 
> > and sometimes automatic crashed
> 
> Please provide a backtrace

Sorry i don't have access to that system and i didn't get this error again
