### ISSUE TITLE
Adding Telegram bot to a group chat doesn't work as expected on Mac OS 

### ISSUE THREAD

**Issue by OleksiiZuiev** [telegramdesktop/tdesktop#6367]
### Steps to reproduce
1. Open the browser with the link https://telegram.me/YouScanBot?startgroup=CGVO-WJUYqDIbNcogUWa-g5VW11RWlLdubH1dd2YszMHB_GtcqQcZBKPycxv2Hic 
(https://monosnap.com/file/zXNE8ghtn7CDTwSzsiILGk09jzfyPQ)
2. Click "Open Telegram.app"

### Expected behaviour
Telegram client is opened, and the dialog to select a group is displayed.

### Actual behaviour
In the Telegram.app private chat with the bot is displayed (https://monosnap.com/file/KF6G4a6POMxbEcoqgT1L2u1Vrxoi61)

### Configuration
**Operating system:**
Mac OS Mojave 10.14.5

**Version of Telegram Desktop:**
Telegram  5.5.1 (176369) 

**Version of the browser**
Google Chrome 76.0.3809.100 (Official Build) (64-bit)

**Comment by 23rd** [comment]
Sorry, you are using the Mac native client, not the Telegram Desktop.
https://github.com/telegramdesktop/tdesktop/issues/5921#issuecomment-483126605

**Comment by OleksiiZuiev** [comment]
Hi, @23rd, thank you for quick reply.

I've just reproduced the issue with the Telegram client 3.8.2.119501 Stable - is this the right one?

**Comment by 23rd** [comment]
Hmm, the current version of Telegram Desktop is 1.7.x.

**Comment by OleksiiZuiev** [comment]
@23rd checked in 1.7.x and it works! 🔥🎉🤗
