### ISSUE TITLE
Google Chrome doubleclicks when click goes from telegram

### ISSUE THREAD

**Issue by ramzes642** [telegramdesktop/tdesktop#6369]
When changing focus from telegram to google chrome it makes a doubleclick.
No other software does like this combination. 
Telegram + Firefox - no
Telegram + Explorer - no
Telegram + Desktop - no

Any other windows + Chrome - no

Just only from tg to chrome. I don't know why....
Both restarted, still works with incognito window too.

### Steps to reproduce
1. Click to telegram window
2. Click to google chrome

### Expected behaviour
Click once

### Actual behaviour
Doubleclick occured. It is very annoying because it maximizes windows, fullscreening videos etc.

### Configuration
**Operating system:** Windows 10 pro 1903

**Version of Telegram Desktop:** 1.7.14
**Version of Google Chrome:** 76.0.3809.100

**Used theme**: Dark theme

Video: https://yadi.sk/i/P8eNNv99QIkUbA

**Comment by swandir** [comment]
The problem seems to be with Chrome and has to do with current input mode (language).

For me it happens when I switch from any window with a non-default input mode while it's the default one for Chrome.

**Comment by venomin** [comment]
> The problem seems to be with Chrome and has to do with current input mode (language).
> 
> For me it happens when I switch from any window with a non-default input mode while it's the default one for Chrome.

Hi, have the same problem. Can confirm, when switching from other window with different input language chrome double clicks.
Have you found any information on this bug somewhere else?
may be workaround?

**Comment by swandir** [comment]
@venomin I haven't. Seems like the issue wasn't reported or discussed at the time.

I've submitted the issue through Chrome Help back then, but it's unlikely to get attention that way. Someone would need to properly report it in the Chromium Project bug tracker. I'm not using Windows for some time now.

I believe the best you can do for now is to either disable the option to allow different input modes for application (I wouldn't want to give up the useful feature, though) or train yourself to click on Chrome's tabs instead of empty space on the title bar (annoying, I know 😅).

**Comment by Aokromes** [comment]
so, you say the bug belongs to chromium bugtracker and not here?

**Comment by swandir** [comment]
> so, you say the bug belongs to chromium bugtracker and not here?

So it seems. As I remember, it is reproducible with Chromium and apps other than tdesktop.

It's just that tdesktop perhaps is most affected because its users tend to switch between it and the browser often and use different input modes.

**Comment by mixaildudin** [comment]
A very annoying bug, I always and up accidentally dragging Google Chrome or getting the video I'm watching to go fullscreen

**Comment by Exerionius** [comment]
I can't find a bugreport about the same issue in the Chromium bugtracker. Did anyone create it?

**Comment by danmerey** [comment]
Oof, I thought I'm the only one with that problem! But I have this in Opera, which has the same engine (I just reported this bug to them, I hope, at least they will fix that). Thanks for clarification about the keyboard setting, I thought I would have this double click bug forever.

**Comment by alexantr** [comment]
@danmerey new Edge browser has same bug 😀
