### ISSUE TITLE
Crash or lag when paste large screenshots 

### ISSUE THREAD

**Issue by mvxxx** [telegramdesktop/tdesktop#6370]
### Steps to reproduce
1.  Make "large" screenshot - by large I mean at least 30-40% of window (1920 x 1080)
2.  Paste that via ctrl + v to chat
3.  User need to wait ~10 seconds or more due to program's freeze, telegram sometimes crashes

### Expected behaviour
Normal pasting, without waiting. If it is impossible due, it shouldn't freeze. (Maybe progress bar on other thread?)

### Actual behaviour
 User need to wait ~10 seconds or more due to program's freeze, telegram sometimes crashes

### Configuration
**Operating system:**
Xubuntu 18.04 but problem occurs also on win 10
**Version of Telegram Desktop:**
1.6.3
**Used theme**:
dark
<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/6187
