### ISSUE TITLE
Does not display numbers, stable version and beta

### ISSUE THREAD

**Issue by youngda** [telegramdesktop/tdesktop#6371]
### Steps to reproduce

![gg](https://user-images.githubusercontent.com/12874231/62748168-288b9400-ba8a-11e9-9155-6913f21f3457.png)

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

### Configuration
**Operating system:**
win10
**Version of Telegram Desktop:**
1.7.14&&1.7.15
**Used theme**:
all theme Not working
<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by youngda** [comment]
Changing the language also does not display properly

**Comment by Aokromes** [comment]
this bug is still valid on 1.9.8? if yes, what's the language of your windows os?

**Comment by Aokromes** [comment]
no answer after near 1 month, if this bug is still valid, open a new ticket with one updated telegram version downloaded from desktop.telegram.org or github.com
