### ISSUE TITLE
Linux desktop version couldn't open

### ISSUE THREAD

**Issue by mubat** [telegramdesktop/tdesktop#6373]
Application show crash popup on start
![Selection_069](https://user-images.githubusercontent.com/3623986/62762024-d69a3c80-ba90-11e9-962e-1eb08a236948.png)

After "SKIP" I have empty log:
![Selection_070](https://user-images.githubusercontent.com/3623986/62762098-fb8eaf80-ba90-11e9-864a-9c01536a88a8.png)

### Configuration
**Operating system:** Linux Mint 19.1 Tessa x86_64 

**Version of Telegram Desktop:** I dont know. Latest from repository

**Comment by Aokromes** [comment]
this bug is still valid? if yes plz run it with gdb.

**Comment by mubat** [comment]
No, now works fine
