### ISSUE TITLE
Timestamp for Sender Emoji don't disappears

### ISSUE THREAD

**Issue by ThigSchuch** [telegramdesktop/tdesktop#6375]
### Steps to reproduce
1. Send an emoji
2. Watch the timestamp

https://imgur.com/a/mtcOi9K

### Expected behaviour
Disappear.

### Actual behaviour
Shows fixed.

### Configuration
**Operating system:** Windows 10

**Version of Telegram Desktop:** v1.8

**Used theme**: Default Dark

**Comment by john-preston** [comment]
@ThigSchuch This is intended. Otherwise the space looks buggy.

**Comment by ThigSchuch** [comment]
Ok, but it's kind strange.
