### ISSUE TITLE
Program does not launch in Ubuntu Mate 15.04 64 bit

### ISSUE THREAD

**Issue by spsf64** [telegramdesktop/tdesktop#638]
Tested versions 0.8 and 0.8.3 64 bit
Error:
/Telegram$ ./Telegram
libs init..
Segmentation fault (core dumped)

**Comment by spsf64** [comment]
Problem still present in version 0.8.4 64 bit

**Comment by Turbito** [comment]
I have the same problem in antergos linux 64 bits

**Comment by johnuren1980** [comment]
I may have a workaround. On Ubuntu MATE, if you open a terminal and type:
*unset QT_STYLE_OVERRIDE;*
and launch Telegram from the terminal, it works. 
I now have this in a script to launch Telegram. Can this be fixed please?

**Comment by amirmasud** [comment]
Same problem v0.8.7

**Comment by AsavarTzeth** [comment]
I just want to confirm that the workaround, mentioned by johnuren1980 works for me.

**Comment by johnuren1980** [comment]
With 0.8.17 64bit, I can report that the QT_STYLE_OVERRIDE workaround is no longer needed and the program no longer segfaults for me.
