### ISSUE TITLE
Telegram Desktop 1.8.0 crashes at start in Windows 10

### ISSUE THREAD

**Issue by ginsenghung** [telegramdesktop/tdesktop#6380]

**Comment by ginsenghung** [comment]
I just updated the Telegram Desktop version to the 1.8.0 and when it finished updating it suddenly closed. I uninstalled it and then I installed again and nothing. It crashes when it is gonna start to select a chat to view it closes.

**Comment by Metal-Ghost** [comment]
this problem opened in 
https://github.com/telegramdesktop/tdesktop/issues/6379
you and other problem is :
Assertion Failed! "i != end(_items)" stickers_emoji_pack.cpp:441

**Comment by john-preston** [comment]
@Metal-Ghost The version was broken after it was released :) Can you try now please? Is it still crashing?

**Comment by ginsenghung** [comment]
Now magically I installed the same version that I previously download from here, the one that caused the crash and it worked fine.
