### ISSUE TITLE
Feature request: special formatting for quoted text — e.g., serif typeface?

### ISSUE THREAD

**Issue by Twilightssuperb** [telegramdesktop/tdesktop#6382]
Big thx for strikeout text. I still need some little feature to mark quotes in messages. I don't know how could it be realized while Telegram has some quote formatting — link preview is marked with vertical line in the bottom of message. Vertical line inside message? But then message will look like ripped apart...

Maybe, you would implement one more font style (while Telegram already has monospace, but it's OK for code, not for texts) — serif typeface for quotes (not for links)? Also quoted text should be automatically ornamented with quotation marks, e.g. special heavy double quotation marks ❝❞. To my mind, it seems to be simple and nice solution.

Slab serif (Roboto Slab) or condensed (Roboto Condensed) fonts could be also used instead of serif typeface.

**Comment by Twilightssuperb** [comment]
Excuse me, @john-preston, just mention you to remind about it if you missed this issue.

**Comment by Twilightssuperb** [comment]
Just have written something — issue (feature request) is still actual. It was closed accidentally.

**Comment by ilya-fedin** [comment]
This is an api issue, there's no quote formatting in the protocol

**Comment by Twilightssuperb** [comment]
> This is an api issue, there's no quote formatting in the protocol

What if devs would just add serif font typeface or any other (slab or condensed)? Monospace typeface is not a better solution for texts (it was made for code), but now I use it to mark some quotes inside post.

Especially since Roboto (basic font family for Telegram Android) and Open Sans (basic font family for Telegram Desktop) both already have Condensed typefaces.

**Comment by ilya-fedin** [comment]
If you request for setting to change font in app then no way, core developers are strongly against allowing users to choose fonts in the app.

**Comment by Twilightssuperb** [comment]
Not to change, just as option (like monospace typeface). Default font is sans and **optional** are monospace and condensed (or serif/slab serif).

**Comment by ilya-fedin** [comment]
Font change is not implemented due to necessity to add an option exactly. Core developers want to have as less options as possible.

**Comment by Aokromes** [comment]
such feature belongs to https://bugs.telegram.org/

**Comment by Aokromes** [comment]
such feature belongs to https://bugs.telegram.org/
