### ISSUE TITLE
Language selector is not opening without Internet

### ISSUE THREAD

**Issue by mymedia2** [telegramdesktop/tdesktop#6385]
### Preconditions ###

1. No Internet connection.
2. Clean user profile, first run.

### Steps to reproduce ###

1. Launch Telegram Desktop.
2. Click on "Start messaging" button.
3. Go to settings.
4. Try to change app language.

### Actual behavior ###

1. Nothing happens.

### Configuration ###

OS: Debian GNU/Linux
Version: 1.8.1

**Comment by john-preston** [comment]
@mymedia2 Languages are cloud based, no way to change them without internet.
