### ISSUE TITLE
Android "Share" link for service notification account is annoying

### ISSUE THREAD

**Issue by Spudz76** [telegramdesktop/tdesktop#6386]
When sharing a picture from Photos or such, "Telegram" shows up as both an App and as the service notification contact (+42777) and I have mistakenly sent pictures to +42777 where I thought I was selecting "Telegram" just the app (for choose-target within the app vs direct to a contact)

But then "Telegram" the app has the same name as "Telegram" the account and the only real difference on the Share panel is a tiny tiny tiny little app icon on the user avatar icon.

Either rename "Telegram" the account to something like "SVCNOTIFY" so it does not show up nearly identical to the App link, or remove the account from all Share popups (since it is not really meant to be sent to, anyway)  It clutters the recent-contacts list for no reason.

I assume the account is redirected to dev-null anyways, but I still don't want to send pictures (or anything else) to it by accident or otherwise.

**Comment by MasterGroosha** [comment]
I'm sorry, but this is Telegram Desktop repo, not Telegram for Android repo
