### ISSUE TITLE
[Question] Slowmode prevents from using QuickShare with comment

### ISSUE THREAD

**Issue by MasterGroosha** [telegramdesktop/tdesktop#6387]
_In general, this is not only Telegram Desktop issue, but (my guess) a server-side one. However, in case server-side team decides not to change anything, TDesktop might have a workaround._

Imagine the following step-by-step situation:
1. Alice creates a group and enables [SlowMode](https://telegram.org/blog/silent-messages-slow-mode#slow-mode).
2. Bob joins this group.
3. Bob goes to any channel, presses on QuickShare arrow by that post, selects Alice's chat and writes a comment.
4. Bob presses "Send"

**What happens now**: Bob gets an error "Slowmode enabled, you can only send one message at a time" (or something like that). Nothing is sent until you empty "comment" field.

Possible solutions:
1. The best one: server-side team makes an exception for such posts with comments. Problem solved for all platforms.
2. A warning appears "SlowMode enabled, please go to that chat and write your comment manually".
3. Post is sent without comment, but comment text is pasted into input field as draft to be sent after slowmode timer reaches zero.

But really the slowmode seems unfinished now and "fixing" quick share with comment by making an exception to only one case (you cannot add multiple comments when using quick share) might be the best approach.

**Comment by Sominemo** [comment]
Options 2 and 3 are questionable for me. Maybe just queue the comment?

**Comment by Sominemo** [comment]
Not answered yet

**Comment by ilya-fedin** [comment]
> Not answered yet

I don't see a question in the post

**Comment by Sominemo** [comment]
> But really the slowmode seems unfinished now and "fixing" quick share with comment by making an exception to only one case (you cannot add multiple comments when using quick share) might be the best approach.

**Comment by ilya-fedin** [comment]
This doesn't look like a question, there's even no question mark
