### ISSUE TITLE
Telegram ignores -style and $QT_QPA_PLATFORMTHEME

### ISSUE THREAD

**Issue by GoldsteinE** [telegramdesktop/tdesktop#6388]
Possibly related to #987
### Steps to reproduce
1. Set `QT_QPA_PLATFORMTHEME` env var to some valid style (`qt5ct` in my case) or run Telegram with `-style` arg
2. Run Telegram Desktop
3. See `QApplication: invalid style override passed, ignoring it.` error. It shows up also when running Telegram with no theme set at all, so it seems like Telegram is still overriding style.

### Expected behaviour
Telegram should start with given Qt theme, so file dialogs looks native.

### Actual behaviour
Telegram starts with some ugly fallback theme (it's easy to see in file dialogs)

### Configuration
**Operating system:**
Arch Linux with i3
**Version of Telegram Desktop:**
1.8.1-1 from official repos
**Used theme**:
«Night Mode by Christian Ospina» if it's somehow matters.
And `qt5ct`/`Breeze` Qt theme

**Comment by Johnnynator** [comment]
> Set QT_QPA_PLATFORMTHEME env var to some valid style (qt5ct in my case) or run Telegram with -style arg

> 3. See QApplication: invalid style override passed, ignoring it. error. It shows up also when running Telegram with no theme set at all, so it seems like Telegram is still overriding style.

These both are due to the patchset used by Arch, yes it is unoptimal under some conditions, but the unsetting of `QT_QPA_PLATFORMTHEME` is needed when dynimacilly linking against qt5.

**Comment by Aokromes** [comment]
@Johnnynator then this is 3rd party bug?

**Comment by Johnnynator** [comment]
This specific bug is 3rd party specific. But e.g. the official binary would also ignore -style since Telegram employs its own style stuff. Due to that it is more or less invalid.

**Comment by GoldsteinE** [comment]
> This specific bug is 3rd party specific. But e.g. the official binary would also ignore -style since Telegram employs its own style stuff. Due to that it is more or less invalid.

Telegram uses default file open/close dialogs, which are affected by Qt style.

**Comment by Johnnynator** [comment]
Than make a proper bug report about these with all conditions to reproduce preferable without distribution specific patches. I'm aware that there might be bugs with the gtk integration stuff and e.g. the gtk style plugin when dynamic linking Qt5, which was the reason that on most distribution there was a patch in place that resetted the style. In other words the bug you describe is a result of Arch working around other bugs that never for properly reported.
