### ISSUE TITLE
[Feature Request] Add pin to bottom for chats

### ISSUE THREAD

**Issue by paoletto** [telegramdesktop/tdesktop#6389]
please add a pin to bottom feature. There are groups and other channels (most notably telegram changelog) that always float up with new messages, and people end up deleting messages from there to have it go down again.

**Comment by RememberTheAir** [comment]
This is kind of a duplicate of #4796. By the way, you can archive a chat (right click on a chat -> archive) to hide it from your chats list

**Comment by paoletto** [comment]
Well, i don't want to hide or archive anything. I want to have it available, just out of the way.
For me to check when i want (e.g., in the case of some groups), or when i know there's something new (in the case of telegram updates), but otherwise not floating up all the time

**Comment by RememberTheAir** [comment]
> For me to check when i want (e.g., in the case of some groups), or when i know there's something new (in the case of telegram updates), but otherwise not floating up all the time

That's exactly what the archive is for

**Comment by paoletto** [comment]
> > For me to check when i want (e.g., in the case of some groups), or when i know there's something new (in the case of telegram updates), but otherwise not floating up all the time
> 
> That's exactly what the archive is for

Then please add pin to bottom for (or simply move to bottom) the archive folder. I don't think it should stay even above the pinned chats..

**Comment by RememberTheAir** [comment]
You can right-click on the archive's chat list item and move it to the side menu

![image](https://user-images.githubusercontent.com/16143208/62863880-6b5b9f00-bd0a-11e9-96be-4b1d16d089d2.png)

**Comment by paoletto** [comment]
hm.. right.. well a bit inconvenient, but i guess better than nothing, and i could live with it.. Thanks, i will close this issue then

**Comment by paoletto** [comment]
although it would be good if the unread count for new messages in archived chats wouldn't be shown in the tray (since they are archived..)

**Comment by paoletto** [comment]
and another awesome thing: service notifications chat cannot be archived -.- 
WTF?

**Comment by RememberTheAir** [comment]
@paoletto that account is going to notify you about new logins, verification codes, failed login attempts, authorizations about web logins using your account's phone number. So pretty important stuffs, that's why you can't archive it
