### ISSUE TITLE
Telegram Desktop is using an outdated Emoji set. Please update the Emoji set to the latest version and please add the skin tone modifier feature and the new Emoji categories to the Telegram Desktop Emoji drawer.

### ISSUE THREAD

**Issue by wp9015362** [telegramdesktop/tdesktop#639]
@telegramdesktop :

The Emoji set in Telegram Desktop is now outdated, see:

http://blog.emojipedia.org/apple-2015-emoji-changelog-ios-os-x

Could you please update the Emoji set to the latest version and could you please add the skin tone modifier feature to the Telegram Desktop Emoji drawer?

Also submitted for:

https://github.com/zhukov/webogram/issues/760
https://github.com/DrKLO/Telegram/issues/986

Regards

**Comment by wp9015362** [comment]
And please also add the new Emoji categories to the Telegram for Android Emoji drawer, which are also described over there:

> http://blog.emojipedia.org/apple-2015-emoji-changelog-ios-os-x
>
> 😃 People
> 🌸 Nature
> 🍔 Food & Drink
> 🎉 Celebration
> 🏃 Activity
> 🌇 Travel & Places
> 🔣 Objects & Symbols

Regards

**Comment by sergioad** [comment]
Or maybe you can use the Twitter ones?

**Comment by cobalto** [comment]
+1

**Comment by wp9015362** [comment]
> @cobalto wrote:
> 
> +1

+1 to what exactly?

> @sergioad wrote:
> 
> Or maybe you can use the Twitter ones?

The open source Twitter "Twemoji" Emoji set:

https://blog.twitter.com/2014/open-sourcing-twitter-emoji-for-everyone
https://github.com/twitter/twemoji

indeed would be quite smiliar, see the following comparison for example:

http://mroth.github.io/emojicompare/

This comparison is showing an outdated version of the Twitter "Twemoji" Emoji set though.

Over the last couple of days the Twitter "Twemoji" Emoji set already has received some nice improvements, see:

https://github.com/twitter/twemoji/commits/gh-pages
https://github.com/twitter/twemoji/issues
https://github.com/twitter/twemoji/issues?q=is%3Aissue+is%3Aclosed

So, the updated set looks better now. They still need to create PNGs from the updated SVGs though, see:

https://github.com/twitter/twemoji/issues/60

Regards
