### ISSUE TITLE
[Feature Request] Add Pin-to-bottom for chats

### ISSUE THREAD

**Issue by paoletto** [telegramdesktop/tdesktop#6390]
Or else chats that are, for example, silenced, keep floating up.
Most notable example is telegram changelog.
I end up deleting messages from there to have it go back, but ideally i'd like to keep messages and just not have it in the way all the time.

**Comment by RememberTheAir** [comment]
You should merge this issue to #6389

**Comment by paoletto** [comment]
yeah sorry, i thought the first one didn't go through.. i can close this one
