### ISSUE TITLE
[Feature Request] Please add location permission switch

### ISSUE THREAD

**Issue by wotmshuaisi** [telegramdesktop/tdesktop#6394]
### Is your feature request related to a problem?

we've found some chinese security police sending Telegram location message to decoying users to click location share message for getting their location

### Describe the solution you'd like

please append a button in privacy settings to close location permission

### Describe alternatives you've considered

we already had alternative solution but it's not convenient enough to close location permission in android settings

**Comment by Aokromes** [comment]
your issue is about android / ios client?
