### ISSUE TITLE
Gifs not playing

### ISSUE THREAD

**Issue by LucaTheHacker** [telegramdesktop/tdesktop#6395]
### Steps to reproduce
1. Send from mobile a .gif.mp4 gif

### Expected behaviour
Gif should play also with media viewer, but is not happening

### Actual behaviour
GIf is showed as gif in normal chat, but if opened in media viewer becomes a normal photo.

### Configuration
**Operating system:** W10 64bit

**Version of Telegram Desktop:** 1.8.1

**Used theme**: midnight

**Comment by Aokromes** [comment]
try on 1.9.8

**Comment by LucaTheHacker** [comment]
Same problem, but happens randomly

**Comment by Aokromes** [comment]
and on 1.9.20?

**Comment by LucaTheHacker** [comment]
seems to be fixed

Il lun 16 mar 2020, 19:04 Aokromes <notifications@github.com> ha scritto:
