### ISSUE TITLE
Khmer Font is too small

### ISSUE THREAD

**Issue by williamgh2019** [telegramdesktop/tdesktop#6397]
### Steps to reproduce
1. 
2. 
3. 

### Expected behaviour
Normal Khmer Fonts 

### Actual behaviour
Too small
![tele](https://user-images.githubusercontent.com/17005582/62861456-c0f57300-bd2d-11e9-9154-1c0ca3915693.jpg)

### Configuration
**Operating system:**
Windows 10

**Version of Telegram Desktop:**
v1.7.14

**Used theme**:
Default

<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/5172 generic bug.

**Comment by ilya-fedin** [comment]
Is this still valid?
