### ISSUE TITLE
New message notification sound failure when earphone plugged in on Windows

### ISSUE THREAD

**Issue by imbushuo** [telegramdesktop/tdesktop#640]
If "Play sound" is enabled and any type of audio stream is playing, any new message notification sound will cause the system to play strange sound. Sometimes speaker only, sometimes both earphone and speaker.

Platform: Windows 8.1 Pro on Surface Pro 3

**Comment by puckipedia** [comment]
yup, I had this too, same conditions... Specifically: I would define the sound played as random noise. This happened to me every time with headphones, did test once with speaker, but that didn't work (both times I used youtube from IE11 desktop mode). No logs anywhere seem to notify something's wrong, in both telegram and `eventvwr`. The 'Hardware ID' is `HDAUDIO\FUNC_01&VEN_10EC&DEV_0288&SUBSYS_10EC0191&REV_1000` (Realtek HD Audio).

**Comment by imbushuo** [comment]
Recently I've noticed it will only happen when earphone plugged in. So strange...

**Comment by Aokromes** [comment]
this bug is still valid?

**Comment by Aokromes** [comment]
poke.

**Comment by Aokromes** [comment]
no answer for more than 1 month, if this bug is still valid open a new ticket using one updated version downloaded from releases tab.
