### ISSUE TITLE
On screen keyboard does not open on Linux

### ISSUE THREAD

**Issue by RussianNeuroMancer** [telegramdesktop/tdesktop#6402]
### Steps to reproduce
1. Install Linux version of Telegram Desktop on device with touchscreen
2. Launch Telegram Desktop
3. Tap on text input field via touchscreen

### Expected behaviour
At least with Wayland-version of Gnome Shell on screen keyboard should appear on the screen. This is what happen with own Gnome apps and Wayland-version of Firefox for example.

### Actual behaviour
On screen keyboard does not appear on the screen.

### Configuration
**Operating system:** Ubuntu 19.04

**Version of Telegram Desktop:** 1.5.11

**Used theme**: default

**Comment by RussianNeuroMancer** [comment]
Issue is also reproducible with Gnome Shell 3.34 Wayland session and running Telegram Desktop 1.8.8 with QT_QPA_PLATFORM=wayland

**Comment by Aokromes** [comment]
better leave #218 as single ticket.

**Comment by RussianNeuroMancer** [comment]
@Aokromes maybe rename #218 then?

**Comment by Aokromes** [comment]
cannot rename, only add or remove labels, that's why i removed windows one xd
