### ISSUE TITLE
Slowmode countdown appearing even when slowmode is not enabled

### ISSUE THREAD

**Issue by RememberTheAir** [telegramdesktop/tdesktop#6404]
### Steps to reproduce
1. try to send two messages consecutively in a chat

### Expected behaviour
If slowmode is off, you're free to send them

### Actual behaviour
I've had this issue with a couple of small chats (~12 members), where Telegram Desktop warns me that I cannot send messages in the chat for n seconds because slowmode is on. Actually, slowmode for that chats has never been activated.

I don't think it's an API issue because from Android I was perfectly able to send messages, while at the same time tdesktop was blocking me from sending them. Another weird thing is that the amount of seconds I was being limited for was not fixed (10/30/60 seconds)

I don't have much more details to give unfortunately. But I'm curious to see whether I'm the only one experiencing this issue or there are other people with the same problem

### Configuration
**Operating system:** Windows 10

**Version of Telegram Desktop:** 1.8.1

**Used theme**: matrix

**Comment by Aurdo** [comment]
Happened to me as well on desktop. Android version continued to work as intended. Restarting the desktop app seemed to solve the issue for me.
### Configuration
**Operating system:** Windows 10
**Version of Telegram Desktop:** 1.8.1

**Comment by seiya-git** [comment]
@Aurdo 
Restarting the desktop app doesn't solve the issue for me.

**Comment by john-preston** [comment]
Should be fixed in 1.8.2.

**Comment by RememberTheAir** [comment]
Yes, doesn't happen anymore apparently. I'll re-open in case this issue shows up again
