### ISSUE TITLE
animated GIFs larger than 10 MB are not animated

### ISSUE THREAD

**Issue by Mithgol** [telegramdesktop/tdesktop#6405]
### Steps to reproduce
1. See https://t.me/tginfochat/718308
2. See https://t.me/tginfochat/718307
3. See https://t.me/tginfochat/718306
4. See https://t.me/tginfochat/718303
5. See https://t.me/tginfochat/718300

### Expected behaviour
All of these animated GIFs should be displayed as animations (and Telegram on Android does display them as animations, for example).

### Actual behaviour
Telegram Desktop displays these GIFs as thumbnails of downloadable files… but does not animate them.

### Configuration
**Operating system:** Windows 7 Professional, 64 bit, with Service Pack 1.

**Version of Telegram Desktop:** 1.8.1, stable.

**Used theme**: not sure.

**Note:** issue #4250 is different. (It's fine for larger animated GIFs to not be recompressed. But they shouldn't stop being animated.)

**Comment by 23rd** [comment]
Your GIFs are over 10 MB.

![image](https://user-images.githubusercontent.com/4051126/62999320-b85c8400-be76-11e9-99fa-40f7d14faaaf.png)

**Comment by Remu-rin** [comment]
@23rd 
This setting is for autodownload. With disabled autodownload and manual click to download, those gifs are not animated when you open them in fullscreen (like photo and video). But if autoplay gifs setting is enabled, they are at least animated in chat (not fullscreen).

**Comment by Mithgol** [comment]
@23rd I have that setting raised to the value of “up to 200 MB” in groups, but the issue remains unaffected.

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/6188 ?

**Comment by Mithgol** [comment]
#6188 seems like what happens if a large GIF is posted from Telegram Desktop: thumbnail's animated, but the fullwidth view does not.

However, GIFs from the above “Steps to reproduce” are posted from Telegram on Android and thus they have one more problem:

1) they aren't autodownloaded by Telegram Desktop even if “Limit by size” is larger (and their thumbnails look small as if those were “images sent as files”);

2) when downloaded manually, thumbnail becomes animated, but the fullwidth view does not (as in #6188; though we don't know yet if the file in #6188 is larger than 10 MB).

**Comment by Mithgol** [comment]
Well, @egorpugin has attached [a sample GIF](https://github.com/telegramdesktop/tdesktop/issues/6188#issuecomment-553673474) at #6188, and that sample seems to be below 10 megabytes.

Might be a different issue then.

**Comment by 23rd** [comment]
Since recent versions, the mechanics of GIF playback have changed, so it looks like your problem is solved? Can you check your links in the first post please?

**Comment by Remu-rin** [comment]
With disabled auto-download those gifs don't have context menu option to open in fullscreen, and their thumbnails are still small.

**Comment by Aokromes** [comment]
i tested 3 of those and all animate for me.

**Comment by Mithgol** [comment]
The original problem is fixed.

I can confirm the problem seen by @Remu-rin (the thumbnails are still small until and unless a large GIF is downloaded), but that should probably be reported as a new issue.
