### ISSUE TITLE
[Feature Request] NOT include muted chats in archived groups count

### ISSUE THREAD

**Issue by neesti** [telegramdesktop/tdesktop#6408]
Please add an option to Notifications settings and Badge counter. 

Include (or NOT include) muted chats in archived groups or channel count. 

![image](https://user-images.githubusercontent.com/14938202/63047162-1b86fe80-bee9-11e9-8b0c-a081b3cc0618.png)

**Comment by MasterGroosha** [comment]
If an archived chat isn't muted, then it will be automatically pulled from archive on new message

**Comment by neesti** [comment]
I mean that I need an option for NOT include muted archved group/channel count.

**Comment by neesti** [comment]
I think adding this feature is more important after version 2.0
