### ISSUE TITLE
[Question] Chat list sidebar doesn't stay collapsed; intentional or bug?

### ISSUE THREAD

**Issue by LunarTwilight** [telegramdesktop/tdesktop#6409]
If I collapse the chat list sidebar, so that only the icons are shown, then when I reopen telegram after closing it to the tray, it opens with the chat list sidebar uncollapsed, which looks to be due to it auto focusing on search. Is this intentional or is it a bug?

**Comment by john-preston** [comment]
@LunarTwilight It is intentional. If no chat is selected the left column is fully visible.

**Comment by LunarTwilight** [comment]
Ah, tho it makes the UI kinda jumpy because when you click on a chat it switches to just showing the icons.
