### ISSUE TITLE
[Feature Request] Add an option to display the nickname at my messages

### ISSUE THREAD

**Issue by bodqhrohro** [telegramdesktop/tdesktop#6411]
### Is your feature request related to a problem?
Nicks are not only for anonymity or for confusing. Nicks can also be branding. People can be known better by nick than by full name in WWW.

However, official Telegram clients currently enforce displaying a full name first, while nick names of other chat members can be seen only after an explicit action, like opening the profile or mentioning. There is no obvious reason for this; it could be reasonable if you controlled that the users actually type in their real names — but you don't.

### Describe the solution you'd like
I'd wish an option that controls what other users that didn't add me to contacts see above my messages: full name, nick name, or even both. Of course, this should be reflected in API and implemented in the clients for other platforms as well.

### Describe alternatives you've considered
Many of users type in nick names instead of full names because of this limitation. However, this is a messy approach: the fields should be used what they are intended for.

### Additional context
Similar feature in Google account settings:
![2019-08-15-154837_1366x768_scrot](https://user-images.githubusercontent.com/2134486/63097256-a2cf8300-bf78-11e9-8464-cecfde743765.png)

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/549
