### ISSUE TITLE
Don't run in background when close button is pressed

### ISSUE THREAD

**Issue by GabVenturato** [telegramdesktop/tdesktop#6412]
### Is your feature request related to a problem?
Since in GNOME they removed the tray bar, I think applications should consider this change letting users to not rely on the tray bar that needs to be added with extensions and that not always work well.

### Describe the solution you'd like
I think the most intuitive behavior when the close button is pressed, would be that the application closes, and not that it continues to run in background.

### Describe alternatives you've considered
Or you could try convince GNOME developers that removing the tray bar now is not the best choice, but they seems quite convinced about it, and I think they have some good points anyway.

### Additional context
Don't suggest to install extensions to enable tray bar please :)

**Comment by pioruns** [comment]
Telegram on Windows desktop have this:
![2019-08-22 16_55_28-Telegram (1)](https://user-images.githubusercontent.com/1646393/63530091-b0978200-c4fd-11e9-8a66-6bd9447cfa22.png)

Disabling "Show Tray Icon" causes Close button to exit the application completely, instead of minimizing it to Windows tray. Check if you have this option on Linux.
If you do, and Close button causes the application to disappear into not visible Tray bar in your GNOME desktop, then this is inconsistency with Windows build.

**Comment by GabVenturato** [comment]
That option would be perfect, but in Linux I have nothing similar. I attach a screenshot from my settings section "System integration", but I can't find that option neither here or anywhere else.

I'm using version 1.8.1.

![Screenshot from 2019-08-22 18-05-14](https://user-images.githubusercontent.com/7904029/63530785-792dd300-c507-11e9-86c2-844842c1df9f.png)

**Comment by pioruns** [comment]
Well, certainly this is +1 "feature request" for Linux then :)
Maybe devs will reply here if this is on their roadmap.
Also, can you verify Telegram behaviour without GNOME desktop or any other desktop where the tray is accessible? Just to make sure we understand correctly the problem.

**Comment by GabVenturato** [comment]
I don't have other desktop environments installed, and I'm not sure what you mean with "understand correctly the problem". 

Maybe could be useful to know that until two/three weeks ago I had an extension to show the tray bar in GNOME, and actually telegram was running on the traybar after closing with the "x" button from the window. Instead, closing from the "icon menu" in the traybar was causing telegram to quit properly. But since I don't have anymore the icon on the traybar I can't close properly the application.

**Comment by pioruns** [comment]
![2019-08-22-172458_1366x768_scrot](https://user-images.githubusercontent.com/1646393/63532227-17b73580-c502-11e9-89c6-82427b1e25a2.png)

"I'm not sure what you mean with "understand correctly the problem"."

Exactly that - look at my picture here, from Linux build. Using newest version 1.8.2, Linux 64-bit build, on Linux Mint LMDE. Everything works as in Windows - enabled tray icon is closing Telegram to tray, disabled tray icon is closing app completely.

Do you use newest version 1.8.2? Try reinstalling it, you certainly don't have option here you should have.

**Comment by GabVenturato** [comment]
Very strange, I'm using Fedora 30, and I don't have the update yet, but trying the version downloadable from the website I still don't have that option.

You can see here the screenshot:

![Screenshot from 2019-08-22 22-38-12](https://user-images.githubusercontent.com/7904029/63548112-e0f71480-c52d-11e9-958f-a2bb2222d1bb.png)

**Comment by pioruns** [comment]
Wow, interesting :) Can you download any Linux Mint/Ubuntu whatever, with non-GNOME environment, to confirm that this option exists in non-GNOME Linux systems? Looks like Telegram is not compatible with newest GNOME then, but it's OK with other Linux systems.

**Comment by GabVenturato** [comment]
Yeah that's quite strange :) anyway in these days I don't have much time to try in other environments, but I asked a firend with arch+KDE and he has that option too, here the screenshot:

![Screenshot_20190822_233252](https://user-images.githubusercontent.com/7904029/63551530-b446fb00-c535-11e9-9e8b-8b0f8dd792cf.png)

I don't know if you think it's enough to prove the problem, maybe could be interesting to test if someone with GNOME actually have this option, that would be even stranger!

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/3830
