### ISSUE TITLE
[Feature Request] Show message preview in muted chats

### ISSUE THREAD

**Issue by neesti** [telegramdesktop/tdesktop#6413]
Please add an option into Telegram settings to show message preview in muted chats. 

Thank you.

**Comment by MasterGroosha** [comment]
What do you mean by "message preview"?

**Comment by neesti** [comment]
I mean this for muted chats too. 
![image](https://user-images.githubusercontent.com/14938202/63249660-2b9f3500-c27f-11e9-8741-443800eeeaca.png)

**Comment by MasterGroosha** [comment]
But muted chats do not show notifications at all, do they? Since there are no notifications, there are no previews? 
And if there is a notification, then the chat isn't muted. I'm confused %)

**Comment by neesti** [comment]
I taked this screenshot only for better my meaning. 
I need show preview EVEN when I mute some chats/group/channel.

**Comment by RememberTheAir** [comment]
@neesti I think you just want an option to disable notification's sound then

**Comment by neesti** [comment]
No, I need sound notificatuon only for unmuted chats/groups/channels, But I don't want to lose show preview in muted chats/groups/channels.

**Comment by RememberTheAir** [comment]
the whole point of muting a chat is that you're not going to receive notifications for new messages. There's no way the app is going to show you a notification for muted chat (unless you get mentioned). If you want to receive a message notification/preview for a chat, you have to unmute it. Maybe one day tdesktop will ad an option to disable notification's sound, so you'll be able to decide whether to be notified of incoming messages without your device to ring
