### ISSUE TITLE
Unsupported UTF-8 chars in nicknames cutting

### ISSUE THREAD

**Issue by BANOnotIT** [telegramdesktop/tdesktop#6416]
In channel [Telegram X Android](https://t.me/tgandroidtests) there is [a message](https://t.me/tgandroidtests/113246) from @Durofa who's nickname causes such visual bug:

![image](https://user-images.githubusercontent.com/11363215/63216190-7d8a7280-c13a-11e9-90ef-dca75e336500.png)
  

### Expected behaviour
Circles could be cut earlier

### Configuration
**Operating system:**
Linux Ubuntu 16.04

**Version of Telegram Desktop:**
1.8.1

**Comment by d-Rickyy-b** [comment]
This issue still persists in v2.4.4
