### ISSUE TITLE
Muted channels become unmuted till I mute them again

### ISSUE THREAD

**Issue by meliezer** [telegramdesktop/tdesktop#6419]
### Steps to reproduce
1. Use Telegram with some (or all) muted channels.

### Expected behaviour
The channels should stay muted.

### Actual behaviour
Once in a week (roughly) I get notifications from muted channels, and I see that they are not marked as muted.

### Configuration
It happens for month with latest versions in different systems: Linux, web, Android.
I couldn't find how to report an issue of the Telegram system itself, so I report here.

**Comment by MasterGroosha** [comment]
Since you're using Android version, could that be because you accidentally press "Unmute" button in app when you browse channels? Sometimes it happens for me

**Comment by meliezer** [comment]
Thank you. I'll be more careful, but I really don't think it's my case.

**Comment by pioruns** [comment]
I had channels muted for a year, no single notification from them, or any device. Today I revisited some of them on Telegram desktop, no notifications, everything clear.
Cannot reproduce this bug.

**Comment by Aokromes** [comment]
cannot reproduce myself being on 10s.

**Comment by meliezer** [comment]
Thank you. Actually I also cannot reproduce this issue :)



Il giorno dom 26 gen 2020 alle ore 20:30 Aokromes <notifications@github.com>
ha scritto:
