### ISSUE TITLE
[Feature request] Tab auto-complete

### ISSUE THREAD

**Issue by sander3991** [telegramdesktop/tdesktop#642]
Recently @ mentions and #hashtags are included in Telegram. However on the Desktop version it's pretty common to use the 'tab' key to auto-complete if you have 1 recommendation left. (or auto-complete if a portion of the results is the same. 

I would love if this could become a feature where pressing 'tab' when you have 1 result left, it will auto-complete to that result.

**Comment by cobalto** [comment]
+1

**Comment by iElmar** [comment]
+1

**Comment by Zarthus** [comment]
This would be great indeed.

**Comment by nebulade** [comment]
That would be truly great if a better username tab completion could be added. The current arrow-key based is a bit non-intuitive.

**Comment by senyk** [comment]
:+1: to all of the above :)

**Comment by Aokromes** [comment]
another vote for add it!

**Comment by sirspudd** [comment]
+1 it would be glorious. The angelic host would launch into choral refrains the likes of which don't bear mentioning.

**Comment by xtopolis** [comment]
:+1:

**Comment by them3gabyte** [comment]
+1

**Comment by Mindstormer619** [comment]
Also, the autocomplete should also be able to work by display name. Often, people have usernames which are completely different from the display name. This presents an inconvenience.

:+1:

**Comment by daedalus01** [comment]
+1

**Comment by kireledan** [comment]
I'll try and take a go at this feature this weekend.

**Comment by them3gabyte** [comment]
Awesome weekend for us ^^

**Comment by nvx** [comment]
Any update on this? Would be quite handy to have!

**Comment by ahmadalli** [comment]
it works at 0.9.1
