### ISSUE TITLE
[Feature Request] Add timeout for Data/Chat Export

### ISSUE THREAD

**Issue by zcqian** [telegramdesktop/tdesktop#6423]
### Is your feature request related to a problem?
In some cases Telegram Desktop will get stuck on exporting data/chat due to it being unable to download a photo or attachment.

### Describe the solution you'd like
It would be helpful if Telegram Desktop added the option/feature that allows the download to timeout, so that the export process may continue. At the end, it should inform the user that parts of the export has failed.

### Describe alternatives you've considered
Not exporting photos/attachments. This is not desirable. Furthermore, I am uncertain that if downloading of text/stickers will always succeed, which means adding the feature is still useful even when ignoring photos/attachments.

### Additional context
I tried exporting some of my chats and Telegram Desktop keeps getting stuck on the exact same place, downloading a tiny 88KB photo. I tried other clients to view the chat history at that time, and the photo won't load in any official client (did not try unofficial ones). It seems like a backend problem, but the frontend/client should be able to continue with the export even if the backend fails to return a photo.

**Comment by jacopo-j** [comment]
I'm also experiencing this problem. @Aokromes I think this issue should be considered a bug, not an enhancement since this problem effectively prevents the chat export function to work correctly if any media in any chat cannot be downloaded.

**Comment by ArmeF97** [comment]
Also maybe related to mine https://github.com/telegramdesktop/tdesktop/issues/5704

**Comment by rinukkusu** [comment]
Hitting this bug too.

![grafik](https://user-images.githubusercontent.com/804848/90223799-ffc17b80-de0e-11ea-9947-143676293002.png)

**Comment by pv7721** [comment]
Same here, I'm stuck after the 1st 3,5% of the history items to export, most likely a screenshot missing. What's peculiar it's that I've managed to perform a full export mid June and that file used to be there...

**Comment by legentz** [comment]
Same problem here...

**Comment by MrMrRobat** [comment]
I have exact same issue. While technically it's not a bug, I think this is not just a regular feature request either, because lack of timeout just breaks data export.

BTW, have anyone somehow overcome this without deleting messages that causing this to happen?

**Comment by john-preston** [comment]
Sorry, guys.

@MrMrRobat @legentz @pv7721 @rinukkusu @jacopo-j @zcqian can you please send me log.txt after a minute of stucked photo download? It should not contain any sensitive data, but you can check yourself before sending or contact me in private at t.me/preston and send it there. I hope there is information about an error code for that download request.

If not, I'll have to ask you to enable debug logs for the export (they will be huge and contain all network requests) and either send them to me or look for the error there yourself (I'll tell what to look for).

**Comment by pv7721** [comment]
> Sorry, guys.
> 
> @MrMrRobat @legentz @pv7721 @rinukkusu @jacopo-j @zcqian can you please send me log.txt after a minute of stucked photo download? It should not contain any sensitive data, but you can check yourself before sending or contact me in private at t.me/preston and send it there. I hope there is information about an error code for that download request.
> 
> If not, I'll have to ask you to enable debug logs for the export (they will be huge and contain all network requests) and either send them to me or look for the error there yourself (I'll tell what to look for).

John, I've realized that at least in my case, the two or three times this happened all that I needed to do was to stop the export, exit Telegram altogether, delete the incomplete export folder and relaunch Telegram and perform the export. So I've realized (but I don't know if this workaround works for everybody, I think it should, at least it should be tried) that this is not so much a FR (feature request), but some sort of a "lock" issue (or resource exhaustion or whatever) that simply goes away after a Telegram relaunch.

I sometimes perform 3 exports in a row, one being kinda long, and first I incorrectly reckoned that this might have something to do with BIG files (one of the exports was always stuck at different stages of a big file), but then I got similar issue with a smaller export and with a tiny file. I also thought that this might have been fixed during an upgrade (but why? simply because Telegram is relaunched after an upgrade) so this is how I figured out I should try relaunch Telegram before attempting my export.

I really hope this helps!

**Comment by john-preston** [comment]
@pv7721 Yeah, thanks. But this is some separate (not that bad as the originally reported) issue, because in the originally reported issue the relaunch and repeated attempts don't help.

**Comment by MrMrRobat** [comment]
@john-preston, I can't reproduce it right now, but in my case issue was certainly caused by voice message that could not be loaded (on any device, so I presume there was a problem at backend) at the time.

**Comment by jacopo-j** [comment]
@john-preston I have attached my log.txt file from my last attempt (yesterday). As you can see, I started the export at 2021.03.16 14:55:46 and aborted it at 2021.03.16 19:32:58. Although I can't say for sure when the export got stuck, looking at the file I can see errors happening at 2021.03.16 17:04:45 so I'm pretty sure that's when the problem occurred.
[log.txt](https://github.com/telegramdesktop/tdesktop/files/6155119/log.txt)

**Comment by john-preston** [comment]
Those FILE_REFERENCE_EXPIRED are processed in code and should not lead to hanging of the export :( So I guess those are some FLOOD_WAIT_ or some code 5XX.

**Comment by john-preston** [comment]
I've added a "Skip this file" link if download takes more than five seconds. This comes in handy not only in case of stuck files but also in case of accidental (and not really needed) large files.

This should become available in the next version.
