### ISSUE TITLE
[Linux] snap doesn't allow uploading certain file types

### ISSUE THREAD

**Issue by glenfordwilliams** [telegramdesktop/tdesktop#6425]
### Steps to reproduce
1. try to upload a zip file

### Expected behaviour

file should be uploaded
### Actual behaviour
upload fails immediately
### Configuration
**Operating system:**
linux
**Version of Telegram Desktop:**
1.7.13  https://snapcraft.io/telegram-desktop
**Used theme**:

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/5778#issuecomment-472353541
