### ISSUE TITLE
[Visual] Archiving info doesn't fit the box

### ISSUE THREAD

**Issue by Akionka** [telegramdesktop/tdesktop#6429]
### Steps to reproduce
1. Just archive any chat

### Expected behavior

Info text fits the box

### Actual behavior
It doesn't

### Configuration
**Operating system: Linux Mint 19.2**

**Version of Telegram Desktop: 1.8.2 BETA**

**Used theme**: built-in matrix with custom bg

![image](https://user-images.githubusercontent.com/42269025/63419032-bc574b80-c40c-11e9-8df7-564e7bb1fccc.png)

**Comment by 23rd** [comment]
#6381.
