### ISSUE TITLE
Little problem with preview photo (from instagram)

### ISSUE THREAD

**Issue by Lazek** [telegramdesktop/tdesktop#643]
OS: Windows 8 Pro
Telegram Desktop: 0.8.3

Little problem with preview image from instagram, screenshot in attach.
![bug_preview](https://cloud.githubusercontent.com/assets/10336636/7066721/1f715d24-dece-11e4-9414-0072657e1d43.PNG)

**Comment by auchri** [comment]
I think this is not client related :)
