### ISSUE TITLE
Strange behavior with private group

### ISSUE THREAD

**Issue by johnny-silverhand** [telegramdesktop/tdesktop#6430]
### Steps to reproduce
1. Leave private group on iOS device
2. Open Telegram Desktop
3. Private group not deleted

### Expected behaviour
Don't show private group and messages after leaving on another devices.

### Actual behaviour
After leaving a private group on my iOS device. The group remained in the main list. But disappeared on the device. There is a history of a private group to search for messages.

I guess messages and group should be deleted.

### Configuration
**Operating system:** Linux, iOS

**Version of Telegram Desktop:** 1.8.2

**Used theme**: Dark

**Comment by Aokromes** [comment]
this issue is still valid?

**Comment by johnny-silverhand** [comment]
@Aokromes failed to reproduce
