### ISSUE TITLE
Telegram crashes when I send specific video

### ISSUE THREAD

**Issue by llybin** [telegramdesktop/tdesktop#6432]
### Steps to reproduce
1. Download video file (16+): https://yadi.sk/i/TN9iLko_UeSG5Q
2. Send this video to any chat
3. Get crash.

### Actual behaviour
Telegram crashes when I send specific video. With others works well.

### Configuration
**Operating system:**
Archlinux

**Version of Telegram Desktop:**
1.8.2 tried both stock and arch linux build

**Used theme**:
default

<details><summary><b>Logs arch linux build</b>:</summary>
free(): corrupted unsorted chunks

KCrash: crashing... crashRecursionCounter = 2

KCrash: Application Name = telegram-desktop path = /usr/bin pid = 17976

KCrash: Arguments: /usr/bin/telegram-desktop 

QSocketNotifier: Invalid socket 48 and type 'Write', disabling...

QSocketNotifier: Invalid socket 49 and type 'Write', disabling...

QSocketNotifier: Invalid socket 50 and type 'Write', disabling...

QSocketNotifier: Invalid socket 55 and type 'Write', disabling...

[1]    17976 alarm      telegram-desktop
</details>

<details><summary><b>Logs stock binary</b>:</summary>
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x7fe56c051800] Protocol name not provided, cannot determine if input is local or a network protocol, buffers and access patterns cannot be configured optimally without knowing the protocol

malloc(): unsorted double linked list corrupted

..stuck..
</details>

**Comment by Aokromes** [comment]
this bug is still valid? if yes, plz click send crash and post crash id here, if you don't get crash report window plz use gdb.

**Comment by llybin** [comment]
not reproduced anymore, thanks, closed.
