### ISSUE TITLE
When archiving chats a part of the banner texture is cut (150% scaling)

### ISSUE THREAD

**Issue by MarcAnt01** [telegramdesktop/tdesktop#6433]
### Steps to reproduce
Archive a chat

### Expected behaviour
Display the whole text

### Actual behaviour
Tell us what happens instead
The last row is being cut

### Configuration
**Operating system:**
Windows 10

**Version of Telegram Desktop:**
1.8.1 Microsoft Store

**Used theme**:
Dark theme

<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

![image](https://user-images.githubusercontent.com/43090263/63463701-ff8dda80-c45d-11e9-92b2-0dc7f8058858.png)

**Comment by 23rd** [comment]
#6381.
