### ISSUE TITLE
Why do emojis have white strokes on them (On Windows,  v1.8.2)?

### ISSUE THREAD

**Issue by mrillusi0n** [telegramdesktop/tdesktop#6436]
Please provide an option to disable white strokes on emojis.
![image](https://user-images.githubusercontent.com/37063502/63594799-0db23700-c5d5-11e9-8311-72c93c05d60d.png)

**Comment by davtur19** [comment]
Settings > Chat Settings> Large Emoji
Uncheck, and you will have old emojis

**Comment by mrillusi0n** [comment]
@davtur19 Thanks!
