### ISSUE TITLE
Clipboard is cleared when telegram-desktop is closed

### ISSUE THREAD

**Issue by Rasie1** [telegramdesktop/tdesktop#6437]
### Steps to reproduce
1. Select and copy something to clipboard from telegram-desktop
2. Stop telegram-desktop
3. Try to paste from clipboard

### Expected behaviour
Text is pasted

### Actual behaviour
Clipboard is empty and nothing is pasted

### Configuration
4.15.18-1-MANJARO

**Version of Telegram Desktop:**
1.5.15

**Comment by julchiar** [comment]
You might be running into this:

> It is also important to realize that according to the selection protocols, nothing is copied until it is pasted. For example, if you select some word in a terminal window, close the terminal and then want to paste it somewhere else, it will not work because the terminal is gone and the text has not been copied anywhere. If you want the word to be preserved after closing terminal window, consider installing a clipboard manager.

https://wiki.archlinux.org/index.php/Clipboard#Managers

**Comment by Rasie1** [comment]
Yes, you correct, I'm closing the issue 

I actually checked the same thing with terminal, seems that it somehow works it out without clipboard manager
