### ISSUE TITLE
[Bug] Links aren't opened in Microsoft Edge Chromium (W10)

### ISSUE THREAD

**Issue by MarcAnt01** [telegramdesktop/tdesktop#6439]
### Steps to reproduce
1. Download Microsoft Edge from [here](https://www.microsoftedgeinsider.com/en-us/download/) the channel I've chosen is Canary one
2. Set it as default browser from Windows 10 settings
3. Open a link from Telegram Desktop

### Expected behaviour
Open the links

### Actual behaviour
Links are opened properly only once I set Chrome or Microsoft Edge uwp as default browsers, no chance with Chromium Edge
### Configuration
Windows 10 1903

**Version of Telegram Desktop:**
1.8.2 Microsoft Store

**Comment by fqdb** [comment]
I'm using Opera as my default browser and have the same issue. Seems like links only work with a popular browser.

**Comment by MarcAnt01** [comment]
> I'm using Opera as my default browser and have the same issue. Seems like links only work with a popular browser.

Moved to beta channel and fixed here, but since it used to happen only with TD, I think it's an issue of the client

**Comment by Aokromes** [comment]
it worked for me for years with opera and they work for me with edge chromium.
