### ISSUE TITLE
Notification window stays on top forever!

### ISSUE THREAD

**Issue by hyounesi** [telegramdesktop/tdesktop#644]
OS: Windows 7 Ultimate
Telegram Desktop: 0.8

Notification windows stay on top (at max 3 windows) and it is annoying, I think it's better to hide it after 3 or some seconds. Thanks

**Comment by eckcon** [comment]
it would be great if it was possible to set a time after which it disapears

**Comment by stufkan** [comment]
Agreed.
Notifications should disappear after a predefined time

**Comment by auchri** [comment]
Notifications are disappearing after some time.
