### ISSUE TITLE
SysTray integration upon auto-start (Linux/Cinnamon)

### ISSUE THREAD

**Issue by uliska** [telegramdesktop/tdesktop#6441]
Systray integration is not read/respected when Telegram is started upon logon.

### Steps to reproduce
1. Add Telegram to autostart programs (Cinnamon/Linux Mint)
2. Set "Show in Systray" option in Telegram (or whatever it is called in the English version)
3. Reboot

### Expected behaviour

1. Telegram opens upon start of the desktop
2. The systray icon is shown and works
3. (As per #1865 I'd love to see a setting for starting up in systray in the GUI)

### Actual behaviour

1. Telegram opens in a maximised window (OK)
2. No systray icon is shown
3. The switch is activated in the extended settings
4. If I switch the setting off and then on again the systray icon appears

### Configuration
**Operating system:**

Linux Mint 19.2
Cinnamon Desktop

**Version of Telegram Desktop:**

1.8.2 (but the behaviour was identical before)

**Used theme**:

I don't think the themes are relevant for this issue

### My Conclusions

When Telegram is not started through autostart the problem is not present. Obviously there is a condition that prevents Telegram from respecting the systray setting when launched as an autostart application. Maybe a race condition in the code or between desktop launch and Telegram launch processes.

**Comment by uliska** [comment]
The last sentence of my description led me to do another test: When I set a delay in the autostart settings the issue is *not* present.

So obviously the case is that when the setting is used upon starting Telegram the Desktop Environment is not ready yet.

So maybe there's nothing that Telegram can really do about it, but then it should at least be documented as a limitation. I'd assume this is not specific to my DE/OS configuration but also affects other environments

**Comment by neesti** [comment]
I have this issue in linux mint 19.2 with cinnamon desktop.
I press ALT+F and enter "r" into it's text box and Telegram icon in systray will present.

**Comment by ilya-fedin** [comment]
Is this valid?

**Comment by Aokromes** [comment]
no answer for near 3 months, closing.if this bug is still valid open a new ticket using updated version.
