### ISSUE TITLE
Text coming through firewall but pictures not allways

### ISSUE THREAD

**Issue by alsmcc** [telegramdesktop/tdesktop#6444]
### Steps to reproduce
1. Connect Desktop-App through firewall
2. Send and receive 
3. 

### Expected behaviour
All pictures are delivered immediately

### Actual behaviour
Some chats are working correctly and all media is shown. But in some chats only the frame of the picture is shown and it keeps on trying to get connection. While in the same chat all text messages are delivered immediately

### Configuration
**Operating system:
Win 10

**Version of Telegram Desktop:**
1.8.2
**Used theme**:
standard
<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by patrickdundas** [comment]
This isn't an issue with telegram, it is an issue with your firewall configuration. Without further details about your firewall, we can't help you solve this problem.

**Comment by Aokromes** [comment]
no answer after months, closing.
