### ISSUE TITLE
read message counter went to minus

### ISSUE THREAD

**Issue by islamsav** [telegramdesktop/tdesktop#6446]
![image](https://user-images.githubusercontent.com/43797131/63758462-ddb4ad80-c8cc-11e9-81fd-01ddda6b4ba8.png)

**Comment by islamsav** [comment]
1.7.13 desktop version on Windows

**Comment by RememberTheAir** [comment]
Duplicate of #6100, also there has been a few more stable releases after 1.7.13, I suggest you to update your app

**Comment by MasterGroosha** [comment]
@RememberTheAir even more, 1.8.x is also stable
