### ISSUE TITLE
some font display as tofu,for example 𝙪𝙩𝙘𝙗𝙧𝙪𝙚𝙪

### ISSUE THREAD

**Issue by Nojike** [telegramdesktop/tdesktop#6450]
### Steps to reproduce
1. 
2. 
3. 

### Expected behaviour
Tell us what should happen
display font directly as linux
### Actual behaviour
Tell us what happens instead
font became [tofu](https://imgur.com/rZpLW37)
### Configuration
**Operating system:**
macOS mojave 10.14.6
**Version of Telegram Desktop:**
1.8.2
**Used theme**:
midnight
<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/6056
