### ISSUE TITLE
Can delete Message from other person on both devices

### ISSUE THREAD

**Issue by TheJoKlLa** [telegramdesktop/tdesktop#6453]
### Steps to reproduce
1. right click on an message from the other person
2. select delete by other
3. click delete

### Expected behaviour
Feature is only useful for own messages

### Actual behaviour
Deletes Message at both sides

### Configuration
**Operating system:**
Windows 10

**Version of Telegram Desktop:**
1.8.2

**Comment by Aokromes** [comment]
https://techcrunch.com/2019/03/25/going-going-gone/
