### ISSUE TITLE
Big Emojis "remove" some Links

### ISSUE THREAD

**Issue by ThigSchuch** [telegramdesktop/tdesktop#6454]
### Steps to reproduce
1. Select an emoji
2. Create link in it
3. Send

https://imgur.com/a/hftMIsE

Not all links happen this, couldn't found a pattern.

### Expected behaviour
Clickable and/or show preview.

### Actual behaviour
"Remove" link, it's hidden, I was able to see it in Android.

### Configuration
**Operating system:** Windows 10

**Version of Telegram Desktop:** 1.8.2

**Used theme**: Default Dark

**Comment by mirh** [comment]
Perhaps related to this, big emoji also kill the "forwarded from" message header.
