### ISSUE TITLE
oversized notifications when interface scale is 150%+ 

### ISSUE THREAD

**Issue by ScDor** [telegramdesktop/tdesktop#6455]
### Steps to reproduce
1. Change Settings/Interface scale to 150% or 200%
2. Minimize Telegram
3. Wait for some message to come
4. Notification will appear in an oversized window, taking up to 20% of the screen

### Expected behaviour
Notification window appears in size that doesn't take too much of the screen

### Actual behaviour
Notification window is oversized and takes too much space of the screen

### Configuration
**Operating system:**
Windows 10
**Version of Telegram Desktop:**
1.8.2
**Used theme**:
Dark

**Comment by Aokromes** [comment]
myself i use 150% and never had oversized notification.

**Comment by Aokromes** [comment]
try on 1.9.8.
