### ISSUE TITLE
Characters with accents are not inserted in the message box after right-clicking inside a chat

### ISSUE THREAD

**Issue by douglasrizzo** [telegramdesktop/tdesktop#6456]
### Steps to reproduce
1. Open a chat by choosing one of the contacts.
2. With the chat open on the right side of the window, right click the text box used to type messages **or** anywhere inside a chat with another user (a message or the chat background) **or** the arrow to send the message **or** a contact in the contacts list. There is no need to interact with the right-click menu.
2. Without moving the focus out of the chat window, try to type a character with accents (*e.g.* é, ã, ü) in the message box.

### Expected behaviour
The character with accents is displayed.

### Actual behaviour
The character is inserted without accents.

### Configuration
**Operating system:** Manjaro Linux 18.0.4 (Illyria) with Linux kernel 4.19

**Version of Telegram Desktop:** 1.8.1

**Used theme**: Default night theme

### Additional details
* Moving the focus out of the chat and back to it reverses this behavior (*e.g.* by closing and reopening the chat or the Telegram window or by clicking out of the window and back into it).
* Right-clicking the search box does not inflict this behavior, probably because it moves the focus out of the chat window when it is done.

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/1041
