### ISSUE TITLE
[Question] Is it possible to disable/restrict my private channel export for subscribers?

### ISSUE THREAD

**Issue by azat11** [telegramdesktop/tdesktop#6458]
I want to publish content and be sure that no one can just export all of the channel history and use the content somewhere else. At least making it impossible to export the content would help a lot.

I'm open to any other solutions within Telegram too. Private group doesn't work for me because I need every new member/subscriber to see all of the previous history. So I am kind of at an impasse. hope there is some solution to this.

**Comment by MasterGroosha** [comment]
Since your channel is private, only subscribers can see its content. So, only subscribers can use "export".

**Comment by azat11** [comment]
Yeah, I know that. I still wanted to limit export capability to just me, the creator.
I guess it's not possible right now.

**Comment by MasterGroosha** [comment]
Unfortunately, this is not possible, also a channel subscriber can "manually" (using API) export all messages anyway.

**Comment by azat11** [comment]
Well, for now with no alternative I have to use this. Thanks for replies.

**Comment by MasterGroosha** [comment]
@azat11 Please consider closing the issue if your question is answered
