### ISSUE TITLE
[Feature Request] Freeze and stop sorting chatlist while mouse cursor is over it

### ISSUE THREAD

**Issue by f242** [telegramdesktop/tdesktop#6459]
### Is your feature request related to a problem?
I often click the wrong way because the chat rooms jump up and down

### Describe the solution you'd like
I want to click on the chat room that the cursor points to

### Describe alternatives you've considered
Freeze and stop sorting chatlist while mouse cursor is over it

**Comment by ilya-fedin** [comment]
#6068
