### ISSUE TITLE
[BUG] Disable auto-formatting messages

### ISSUE THREAD

**Issue by deconstruction** [telegramdesktop/tdesktop#646]
Please add the possibility to disable message auto-formatting, currently tdesktop removes spaces, line breaks, tabulation, etc, which renders code snippets into unreadable mess. The checkbox to show the messages "as-is" would be very useful for developers.

UPD:

After some digging I discovered that tdesktop doesnt format messages, even worse, it MODIFIES them before sending, by removing tabs and other symbols (for example it converts >> to »). Nor android nor web telegram clients are not doing this, only tdesktop. Why tdesktop cripples messages is beyond me, I think this is completely unacceptable behavior and should be considered bug.

**Comment by cobalto** [comment]
+1

**Comment by NeoLegends** [comment]
Perhaps even full code blocks with syntax highlighting à la markdown with ``` backticks

**Comment by ppparadox** [comment]
+1

**Comment by Rufflewind** [comment]
I have a [preliminary patch that allows this feature to be disabled](https://github.com/telegramdesktop/tdesktop/compare/master...Rufflewind:replace-punctuation-setting).  However, I did *not* test whether it works as I couldn't figure out how the build system worked.

**Comment by peterfarrell** [comment]
This is affecting us as well. Makes sharing commands with a team very hard.

**Comment by auchri** [comment]
Duplicate #522
