### ISSUE TITLE
[Bug] macOS UTF-8 character not display 

### ISSUE THREAD

**Issue by doctor-frankenstein** [telegramdesktop/tdesktop#6460]
when i trying to type character like this (belong to UTF-8 charset):

[Unicode Block “Mathematical Alphanumeric Symbols”](https://www.compart.com/en/unicode/block/U+1D400)

example of some characters:

```
U+1D43C	𝐼	
Mathematical Italic Capital I
U+1D43D	𝐽	
Mathematical Italic Capital J
U+1D43E	𝐾	
Mathematical Italic Capital K
U+1D43F	𝐿	
Mathematical Italic Capital L
U+1D440	𝑀	
Mathematical Italic Capital M
U+1D441	𝑁	
Mathematical Italic Capital N
U+1D442	𝑂	
Mathematical Italic Capital O
U+1D443	𝑃	
Mathematical Italic Capital P
U+1D444	𝑄	
Mathematical Italic Capital Q
U+1D445	𝑅	
Mathematical Italic Capital R
U+1D446	𝑆	
Mathematical Italic Capital S
U+1D447	𝑇	
Mathematical Italic Capital T
U+1D448	𝑈	
Mathematical Italic Capital U
```

there are screenshots about I'm typing into `𝑭𝒓𝒂𝒏𝒌𝒆𝒏𝒔𝒕𝒆𝒊𝒏`

![image](https://user-images.githubusercontent.com/46594603/63990644-5eff8080-cb17-11e9-92de-a39bbd7d59ba.png)

### Steps to reproduce

1. Use Telegram Desktop Version (NOT Mac App Store version) download from [https://telegram.org/dl/desktop/mac](https://telegram.org/dl/desktop/mac)
2. Type (copy) `𝑭𝒓𝒂𝒏𝒌𝒆𝒏𝒔𝒕𝒆𝒊𝒏` into chat input

### Expected behaviour

I'm tested Telegram Desktop Version on 

- Ubuntu 16.04/18.04 
- Windows 10

It's working fine

BUT on macOS was broken

### Actual behaviour

Some of UTF-8 charset character not display, show like tofu

### Configuration

- **Operating system: macOS Mojave 10.14.6 (18G87)**
- **Version of Telegram Desktop: 1.8.2**

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/6056
