### ISSUE TITLE
[Feature Request] [Ubuntu] Move please "connecting..." message to somewhere

### ISSUE THREAD

**Issue by mavlutovr** [telegramdesktop/tdesktop#6462]
### Is your feature request related to a problem?
Little bit

### Describe the solution you'd like
Sometime Telegram is in "Connecting" mode. And it little bit difficult to write a message (see screenshot below).

### Describe alternatives you've considered
Can you move the message "Connecting..." to somewhere?
For example, to top of the window. Or minimize it to small icon like spinner.

### Additional context
https://i.imgur.com/4P4aiKO.png

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/2336
