### ISSUE TITLE
Telegram Desktop freezes upon native (non-Windows) notification

### ISSUE THREAD

**Issue by RollingOnChrome** [telegramdesktop/tdesktop#6463]
**Steps to reproduce**
Disable Windows notifications in settings
Wait for a message to trigger a notification

OR

Disable Windows notifications in settings
Scroll down to "Location on the screen" in settings and mouse over corners to trigger multiple Telegram notifications

**Expected behavior**
Telegram continues to function.

**Actual behavior**
Telegram freezes and must be manually killed (via Task Manager) and reopened.

**Configuration**
Operating system: Windows 10 pro 1903, build 18362.295
Version of Telegram Desktop: 1.8.2 (either installed or portable)

**Comment by Aokromes** [comment]
this bug is still valid?

**Comment by Aokromes** [comment]
no answer after near 1 month, if this bug is still valid, open a new ticket with one updated telegram version downloaded from desktop.telegram.org or github.com
