### ISSUE TITLE
Telegram desktop build error in Visual Studio 2019

### ISSUE THREAD

**Issue by albert-ch-cheng** [telegramdesktop/tdesktop#6465]
I followed the build instructions listed in the wiki to build tdeskop by VS2019.
When selecting Telegram project and using Build->Build Telegram to generate telegram.exe, VS2019 complained some errors:
"E0135 namespace "style" has no member of "TextStyle".

Is there anyone knowing what's going wrong with my build procedure?
I guess I missed some steps before I open Telegram.sln by VS2019.
But according to the build instruction, after "gyp/refresh.bat" is executed, the Telegram.sln will be prepared ready and correct for building.
Any advise?

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/4980
