### ISSUE TITLE
[Serious Bug] Links are not updating

### ISSUE THREAD

**Issue by bl4ckh47h4ck3r** [telegramdesktop/tdesktop#6468]
Links are not updated if the content of the link (like images) are changed. If content of the URL updated telegram uses its previous cached item for showing which is very bad.

It's a serious problem. I am also facing it badly. My github account when shared it's not showing others pic instead of showing my profile pic → https://github.com/bl4ckh47h4ck3r

I have contacted with GitHub. They have told me its not their problem. I have deleted my github account with that catched profile picture.

Through it was deleted it's showing the cached image for that invalid link. Needed to be fixed ASAP. Because, it is a matter of privacy

![image](https://user-images.githubusercontent.com/54761717/64073042-8a6ea080-ccba-11e9-889b-ea8294c2c4e0.png)

**Comment by Aokromes** [comment]
i think it's not telegram desktop bug.

@WebpageBot

**Comment by Aokromes** [comment]
and even less serious.
