### ISSUE TITLE
Audio output doesn't switch on bluetooth headset

### ISSUE THREAD

**Issue by NicKoehler** [telegramdesktop/tdesktop#6469]
**Steps to reproduce:**
1. Open Telegram Desktop.
2. Play some voice messages.
3. Try to switch audio output to a bluetooth device.

**Expected behaviour:**
The sound should switch to the bluetooth device.

**Actual behaviour:**
The sound continues to play on speakers/wired headphones.

**Operating system:**
Operating System: Manjaro Linux 
KDE Plasma Version: 5.16.4
KDE Frameworks Version: 5.60.0
Qt Version: 5.13.0
Kernel Version: 4.19.66-1-MANJARO
OS Type: 64-bit
Processors: 8 × Intel® Core™ i7-4790K CPU @ 4.00GHz
Memory: 15,5 GiB

**Version of Telegram Desktop:**
1.8.2

**Used theme**:
Midnight theme

**Notes:**
Opening Telegram Desktop from terminal and playing audio results in this:

`[ogg @ 0x7f151c00d4c0] 727 bytes of comment header remain`
`Invalid return value 0 for stream protocol`
`Invalid return value 0 for stream protocol`
`Invalid return value 0 for stream protocol`
`Invalid return value 0 for stream protocol`

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/2231
