### ISSUE TITLE
New youtube preview worse than the previous one

### ISSUE THREAD

**Issue by AbelToy** [telegramdesktop/tdesktop#647]
What happened to the previous youtube preview that had the thumbnail, title and duration? It was way prettier and better than the new one!

**Comment by AxelCompte** [comment]
Besides the layout thing, I want to say that the newer has many bugs.

**Comment by petesimon** [comment]
I agree with @AbelToy . Generally, a smaller preview such as a thumbnail would be better. Currently, the large preview eats up too much of my chat window. Also short URL format http://youtu.be/abcde  or SSL https://youtu.be/abcde do not generate a preview at all.

**Comment by CyberMew** [comment]
What's the reason for the closure?

**Comment by auchri** [comment]
That are the new link previews (https://telegram.org/blog/link-preview) which work much better than the old ones
