### ISSUE TITLE
[Question] Build error in Visual Studio 2019

### ISSUE THREAD

**Issue by XEGARE** [telegramdesktop/tdesktop#6471]
Hello. Please tell me what is the reason why cannot find the necessary files? And why doesn’t the "call ninja.exe ..." work?
[Screen](https://i.imgur.com/60MBk3s.jpg)

Configuration only Win32. This is on any build mode (Releas / Debug)

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/4980
