### ISSUE TITLE
[Feature Request] Split screen and PIP mode

### ISSUE THREAD

**Issue by fabyRojas** [telegramdesktop/tdesktop#6473]
Split screen option like the one they have incorporated in Skype to be able to have a better organization, in addition able to watch the videos in pip mode

**Comment by clsv** [comment]
Pip mode is a must feature. When you watch a video, you can't use messenger, and if you close video, you have to skip to the time you stopped. It would be nice to remember a moment of video stop too.

**Comment by Aokromes** [comment]
the 1st
https://github.com/telegramdesktop/tdesktop/issues/2105
the 2nd 
https://github.com/telegramdesktop/tdesktop/issues/4369
