### ISSUE TITLE
Video is saved without extension by default on the downloads folder 

### ISSUE THREAD

**Issue by toktoakhil** [telegramdesktop/tdesktop#6474]
### Steps to reproduce
1. Send a video to the saved chat. 
2. open telegram on desktop and download the video from the saved chats
3. Can see video is saved on the downloads location with out video extension.
4. If we do a save video as option it gets saved correctly with extension.
5. I was checking it with .mp4 video

### Expected behavior
Video must be saved with correct extension.
### Actual behavior
Video get saved without extension.

### Configuration
**Operating system:** Windows 10

**Version of Telegram Desktop:** 1.8.2

**Used theme**: Default theme

<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by toktoakhil** [comment]
@svenstaro

**Comment by svenstaro** [comment]
What
