### ISSUE TITLE
[Feature Request] Add blocking mediafile sending to chat.

### ISSUE THREAD

**Issue by perevertysh** [telegramdesktop/tdesktop#6475]
Add blocking mediafile sending  to chat. 
Makes option to switch on/off sending mediafile in chat to  prevent or block sending  and openning not wished content.

**Comment by MasterGroosha** [comment]
Group admins can restrict sending mediafiles for all participants.

**Comment by perevertysh** [comment]
> Group admins can restrict sending mediafiles for all participants.
it's about private chats.

**Comment by MasterGroosha** [comment]
If you're talking about Telegram Desktop, simply disable message and/or sender name preview in notification

OR

temporarily disable notifications at all.

**Comment by perevertysh** [comment]
> If you're talking about Telegram Desktop, simply disable message and/or sender name preview in notification
> 
> OR
> 
> temporarily disable notifications at all.

it's too rude methods. In this situation you can messaging, but in limited mode.
And it's about laptops. Much more, you can disable mediafiles on the work and not care about, your girlfriend booty will flash in corner of window, when you'll open chat)

**Comment by Aokromes** [comment]
this will need api support very likely.
