### ISSUE TITLE
Telegram Desktop automatically replaces non-breaking spaces (Unicode U+00A0) by ordinary spaces (Unicode U+0020) in edited messages

### ISSUE THREAD

**Issue by Mithgol** [telegramdesktop/tdesktop#6477]
### Steps to reproduce
1. Close Telegram Desktop on all devices, open Telegram on Android.
2. Visit “Saved messages”.
3. Create some sample message. (I'll use “Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua” in this example.)
4. Use some [non-breaking spaces](https://en.wikipedia.org/wiki/Non-breaking_space) (Unicode U+00A0) so that it becomes obvious (on your Android screen and with your font size) that words adjacent to these spaces are used together to start the next line of text. (I'll use a non-breaking space between “consectetur” and “adipiscing” and another one between “eiusmod” and “tempor” in this example.)
5. Save the created message in “Saved messages”.
6. Open Telegram Desktop on Windows.
7. Visit “Saved messages”.
8. Make an edit that should not touch the non-breaking spaces in the message that was saved on step 5. For example, add “(…)” on the next line of text.
9. Use Telegram on Android to observe the non-breaking spaces that are no longer non-breaking. They are (most likely) replaced by ordinary spaces (Unicode U+0020).

### Expected behaviour
The words adjacent to non-breaking spaces are moved together to the next line of text when they do not fit at the end of a line.

The message's first lines of text continue to look as those saved on step 5:

![(screenshot)](https://cloudflare-ipfs.com/ipfs/QmeZUfP8fF2peHKpzByHp25TZHByWecaZLsQF6r2rcwEsZ)

Only the additional “(…)” appear below that previous save.

### Actual behaviour
A line break happens between the words (“consectetur” and “adipiscing” in this example) that should have been separated by a non-breaking space. It is, apparently, an ordinary space (Unicode U+0020) now.

![(screenshot)](https://cloudflare-ipfs.com/ipfs/QmeUEfEPo742tauprRppXVoxMM8v5ZGaguQzgjestSrrGc)

### Configuration
**Operating system:** Windows 7 Professional, 64 bit, with Service Pack 1.

**Version of Telegram Desktop:** 1.8.2, stable.

**Used theme**: not sure.

### P. S.

It becomes necessary to observe the effects of non-breaking spaces in Telegram on Android because issue #6393 obscures them in Telegram Desktop.

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/6393

**Comment by Mithgol** [comment]
#6393 what?
