### ISSUE TITLE
Telegrams automatically scrolls all messages, marking them as read

### ISSUE THREAD

**Issue by Pzixel** [telegramdesktop/tdesktop#6479]
### Steps to reproduce
1. Open chat on DeviceA
2. Open chat on DeviceB

### Expected behaviour
When I get new messages in the chat I get notification in both clients

### Actual behaviour
Sometimes chat on DeviceB gets scrolled automatically, so I don't see if there are new messages

### Configuration
Win10 x64
Telegram v1.8.2

---

Sometimes some stange bug happens to me: all messages in the chat are scrolled automatically. It seems that it incorrectly determines other sessions and if this chat is opened on other device it just scrolls. It's very inconvinient since I can't see if anybody write anything or even when I get mentioned. See attachment for visualization.

Although forcebly terminating other sessions help I consider this being a bug.

On the gif I just scroll chat up and you see it automatically scrolls down when new message incomes (I don't press pagedown or anything, using only mouse wheel):

![telegram_aut-scroll](https://user-images.githubusercontent.com/11201122/64123430-0517e880-cdad-11e9-8be3-6121eb0b13bb.gif)

**Comment by 23rd** [comment]
#4989.
