### ISSUE TITLE
[Feature Request] Ability to start minimised / in tray on Linux

### ISSUE THREAD

**Issue by Justinzobel** [telegramdesktop/tdesktop#648]

**Comment by cobalto** [comment]
![asdasdad](https://cloud.githubusercontent.com/assets/1196314/7284130/c68629bc-e911-11e4-987b-8374366d9d3a.PNG)
????

**Comment by gim-** [comment]
![screenshot from 2015-04-22 23-20-18](https://cloud.githubusercontent.com/assets/1240012/7284439/37ca022c-e946-11e4-915b-65bc4226e715.png)

**Comment by cobalto** [comment]
Which OS?

**Comment by gim-** [comment]
@cobalto GNU/Linux. I guess this feature is available on Windows obly.

**Comment by Justinzobel** [comment]
Solus https://www.solus-project.com, so yes, Linux.

**Comment by auchri** [comment]
Duplicate #948
