### ISSUE TITLE
[Question] Compile entire client witouth 2check read confirmation?

### ISSUE THREAD

**Issue by GnubiBORED** [telegramdesktop/tdesktop#6480]
Its possible? Someone did something like thath? my idea is thath when you read a message in some way telegramclient sends a http request to server for tell its readed and mark in reciever client as read, so
1-If you block these call
2-Recompile entire client source  witouth these request

would work? Someone tried?

**Comment by RadRussianRus** [comment]
See 1.4 here:
https://core.telegram.org/api/terms#1-privacy-amp-security

This feature violates Telegram API ToS.

**Comment by GnubiBORED** [comment]
okay basically if i do these gonna get account banned... i dont know why they dont add these feature anyway or if already developer team say something about this in git or in public, if it goes against their tos i will not do it anyway thanks for answer

**Comment by RememberTheAir** [comment]
> basically if i do these gonna get account banned

Telegram's ToS says "_If you do not update the app to fix the highlighted issues within 10 days, we will have to discontinue your access to Telegram API_", that means they're just going to revoke your app's keys, not ban your account. And anyway, there are tens (if not hundreds) of apps published on popular stores (even on the PlayStore) that blatantly violete the ToS and didn't probably face any consequence. So yeah if you do that, chances are Telegram won't care
