### ISSUE TITLE
[Feature Request] Show user id in profiles

### ISSUE THREAD

**Issue by Neurotoxin001** [telegramdesktop/tdesktop#6481]
It's very usefull for ban people in all chats where I have my bot because bots can only ban by id if there is no people in chat with bot.

Now for view id I must use Nicegram for iOS, because official iOS TG app doesn't support this like official TDesktop...

**Comment by Neurotoxin001** [comment]
+

**Comment by Neurotoxin001** [comment]
Why bot is ignored my message? https://github.com/telegramdesktop/tdesktop/issues/6481#issuecomment-715880854

I still need it

**Comment by Eeroz** [comment]
This would be really helpful for admins in communities with several groups.

**Comment by martiliones** [comment]
If anyone is wondering, there's Telegram fork with this feature

Kotatogram
https://github.com/kotatogram/kotatogram-desktop

**Comment by ef1m0ff** [comment]
up! Any updates ??? Kotatogram hasn't been updated since Dec 2021. We need this feature in Telegram Desktop!

**Comment by Neurotoxin001** [comment]
Seems like it's done https://github.com/telegramdesktop/tdesktop/commit/625ae87eea162e375303f319314fff65d65fb9f8
