### ISSUE TITLE
When uploading file, comment dialog is unfocused until I click or alt+tab

### ISSUE THREAD

**Issue by nyanpasu64** [telegramdesktop/tdesktop#6483]
### Steps to reproduce
1. Open a chat
2. Click the paper clip and upload a file (same bug on .rtf or .png) into the chat
3. When the file upload dialog appears, try to type into the caption textbox, or press Enter to upload the file.

### Expected behaviour
Keystrokes enter the caption text box

### Actual behaviour
Keystrokes do not enter the caption text box. Pressing Tab, Shift+Tab, up/down, or Enter do not take effect. If I switch away and and back to Telegram, the caption textbox takes focus, and I can type or press Enter. If I click any part of the Telegram window, keyboard focus is regained.

### Configuration
**Operating system:** Windows 10 x64

**Version of Telegram Desktop:** 1.8.2

**Used theme**: Matrix (I may have edited the colors)

Where do I find log.txt?

<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by wodim** [comment]
This is making me go crazy. You don't want to pay for my hospital bills do you

**Comment by wodim** [comment]
This was fixed some time ago @wolfbeast
