### ISSUE TITLE
[Question] image view distortion of win32 release

### ISSUE THREAD

**Issue by realtk2eye** [telegramdesktop/tdesktop#6484]
after lunach Telegram.exe all of image display distortion 

login dialog:
![image](https://user-images.githubusercontent.com/54877352/64224763-5211d100-cf0b-11e9-92bf-9e806ab5b542.png)
setting:
![image](https://user-images.githubusercontent.com/54877352/64224794-6a81eb80-cf0b-11e9-8d42-b73456cc5788.png)
and user photo 
![image](https://user-images.githubusercontent.com/54877352/64224880-c51b4780-cf0b-11e9-80ef-d170ef7c9d31.png)

search bar:
![image](https://user-images.githubusercontent.com/54877352/64224508-6bfee400-cf0a-11e9-868b-a06b102dd4da.png)

maybe some problem in QT image ?

**Comment by john-preston** [comment]
@realtk2eye Is it the official build or your own?

**Comment by realtk2eye** [comment]
> @realtk2eye Is it the official build or your own?

my own build

**Comment by 23rd** [comment]
#5967.

**Comment by john-preston** [comment]
@realtk2eye I had to change Qt patch a little for the new builds to work without fine, it is MSVC compiler bug. It'll be published soon, I hope within a week.

**Comment by john-preston** [comment]
@realtk2eye See https://github.com/telegramdesktop/tdesktop/issues/5967 for details.

**Comment by realtk2eye** [comment]
thanks !
