### ISSUE TITLE
The context menu doesn't work correctyly!

### ISSUE THREAD

**Issue by MIMAXUZ** [telegramdesktop/tdesktop#6488]
I am using latest update of Windows10 and latest update Telegram desktop. While using app the context menu doesn't work correctly. Once it goes, it opens and closes. Opening with a few clicks. Where is problem? Here is video url: [https://twitter.com/i/status/1169288418402197504](url)

**Comment by Aokromes** [comment]
plz, fill OS, telegram desktop version, etc.

**Comment by Aokromes** [comment]
no answer after near 1 month, closing.
