### ISSUE TITLE
[Feature Request] Add grouping of tabs

### ISSUE THREAD

**Issue by token0** [telegramdesktop/tdesktop#6490]
Add grouping of tabs, i.e. ability to create custom group tabs with min/max button:
```

Friends [-]
    contact 1
    contact 2
    contact 3
Family [-]
    Mom
    Dad
    Sis
News [-]
    blablabh
    northkoreanpost
    oldyorktimes
Etc1 [+]
Work [+]

```
Because it's very inconvenient, when you have about 100+ tabs.

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/1107
