### ISSUE TITLE
[Feature Request] Please add secret chats support for linux desktop app

### ISSUE THREAD

**Issue by superorc** [telegramdesktop/tdesktop#6491]
### Is your feature request related to a problem?
There is no option to create secret chat on telegram-desktop-1.8.2-2.fc30.src.rpm
### Describe the solution you'd like
Please add feature in the same way like it provided on Android , e.g. just add support for creating secret chats, sync between devices are not required.

**Comment by Aokromes** [comment]
#871

**Comment by aBARICHELLO** [comment]
`telegram-cli` supports secret chat: https://github.com/kenorb-contrib/tg
