### ISSUE TITLE
Remove parking emoticon from favorites

### ISSUE THREAD

**Issue by lapo-luchini** [telegramdesktop/tdesktop#6492]
### Steps to reproduce
1. write a message, then write the quite usual textual smiley ":P" (colon, P)
2. the «🅿️» emoticon gets suggested
3. it's very easy to accept the suggestion by mistake (and I never never mean to it)
4. the «🅿️» emoticon is now #3 in the "most used emojis" panel, which I hate even more than the too-usual-and-wrong suggestion

### Expected behaviour
Use a slightly longer prefix to suggest that emoticon, such as ":Pa".

### Actual behaviour
Wrong suggestion that is too easy to accept and difficult to avoid.
(basically, I'd need to remember to always write "colon, P, escape")

### Configuration
**Operating system:**
Windows 10

**Version of Telegram Desktop:**
Version 1.8.3

**Used theme**:
Dark.

**Comment by 23rd** [comment]
#6067.

**Comment by lapo-luchini** [comment]
Thanks @23rd, I didn't find that.
