### ISSUE TITLE
[Question] voip number restriction

### ISSUE THREAD

**Issue by boistordu** [telegramdesktop/tdesktop#6493]
Hi,

I'm really sorry in advance to open a ticket here, but your twitter guys never answer to me like he's denying my tweets or they get filtered. Nor does telegram login help.
And I couldn't find a single source of information about that. 
I'm trying to register with a new voip number and it says that the number is not good. But if I try to call it from my cellphone it works, socould anyone of your team ask the team on twitter to answer me or maybe answer me here?

thanks in advance

**Comment by Aokromes** [comment]
sorry, but this doesn't belong to telegram desktop.
