### ISSUE TITLE
Cannot access settings with keyboard

### ISSUE THREAD

**Issue by yhaskell** [telegramdesktop/tdesktop#6494]
## Expected behaviour

I should be able to get to settings with keyboard, and then navigate through settings also with keyboard

## Actual behaviour

* I cannot open settings screen without mouse.
* When Settings screen is open, tab key switches between search and chat edit box (both are in background).

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/2109
