### ISSUE TITLE
Crash because of removed schedule message

### ISSUE THREAD

**Issue by Neurotoxin001** [telegramdesktop/tdesktop#6495]
### Steps to reproduce
1. Post something with schedule in group that you have access to recent actions
2. Wait for post, then remove it
3. Go to recent actions
4. Click to any other chat
5. Crash

### Configuration
**Operating system:** win 10 ltsc 1809

**Version of Telegram Desktop:** 1.8.3

**Used theme**: default tinted

last line in log after crash:
`[2019.09.06 11:59:36] Assertion Failed! "i != end(_data)" data_scheduled_messages.cpp:370`

**Comment by Aokromes** [comment]
plz on next crash press send crash report and post crash id.

**Comment by Neurotoxin001** [comment]
Your Report Tag: 6f5a5505-9dde-469e-b8ef-497114aa16ca

**Comment by john-preston** [comment]
@Neurotoxin001 Thanks you! I'll fix that in the next update.
