### ISSUE TITLE
Cannot edit scheduled messages

### ISSUE THREAD

**Issue by MasterGroosha** [telegramdesktop/tdesktop#6496]
# Steps to reproduce
1. Schedule a message (text or photo with caption)
2. Try to edit text / caption

### Expected behaviour
You should be able to edit a scheduled message.

### Actual behaviour
You can edit scheduled messages on Android and iOS, but not in TDesktop.

### Configuration
**Version of Telegram Desktop:** ~~1.8.4 Stable~~ 2.1.0 Stable

**Comment by RadRussianRus** [comment]
Still revelant on 1.8.5 beta.

**Comment by viktorfrom** [comment]
Using Telegram 1.8.4, it could not be reproduced in MacOS 10.14.6. However, I was able to reproduce the bug in Win10, version 1903.

**Comment by Neurotoxin001** [comment]
Can confirm that I can edit scheduled post on telegram for iOS, but can't on telegram for desktop 1.8.15

**Comment by Neurotoxin001** [comment]
On 2.1 and earlier versions if I change posting time from iOS app it wont update on desktop until restart

**Comment by AminTaheri23** [comment]
This is still a problem!

**Comment by DmitrijOkeanij** [comment]
Still miss!

**Comment by hartkotet** [comment]
Still missing. 2.1.17 beta.

**Comment by ilya-fedin** [comment]
https://github.com/telegramdesktop/tdesktop/commit/0a4f3f310c32cbdfe25859e1bc9d97f8cd81a5a1
