### ISSUE TITLE
can you design a new funtion?

### ISSUE THREAD

**Issue by rehan91** [telegramdesktop/tdesktop#6499]
When there are lots of person talked before in my left panel，it's hard to find a certain person who i want to chat with.And,my contact list show in a chaos,so it's not very easy to differentiate them.
  so,can you just consider this solution:add a collapse panel in left panel where we can customize it's name and choose who will be included.Then,we can find certain person easily next time,for example,if i want to find one of my colleague,i can unfold a collapse panel named "colleague",then find him in a short time.This function is seems like to pin a tags to my contacts.
  Anticipate your reply.

**Comment by LucaTheHacker** [comment]
cringe lol, this section is for issue on tdesk, is not a find-job.

**Comment by Neurotoxin001** [comment]
https://github.com/telegramdesktop/tdesktop/issues/1107
