### ISSUE TITLE
Context menu: icon transparent

### ISSUE THREAD

**Issue by auchri** [telegramdesktop/tdesktop#65]
Only a small issue:
Make the background of the context-menu icon transparent

Currently white:
![context menu](https://cloud.githubusercontent.com/assets/5092164/3635226/bdf2db06-0f64-11e4-897a-b43f7876ecb1.png)

**Comment by formatq** [comment]
If I understand correctly what kind of icon is it? then the issue can be closed

![fm_160818_124850](https://cloud.githubusercontent.com/assets/3082584/17767229/883b097a-6548-11e6-8005-552f0331ab9c.png)
