### ISSUE TITLE
Chat background won't change

### ISSUE THREAD

**Issue by ErickGiffoni** [telegramdesktop/tdesktop#6502]
### Steps to reproduce
1. Open Telegram desktop app
2. Go to settings > Appearance > Chat background 
3. Choose a background and set apply 

### Expected behaviour
Chat background should change to the selected background after this process 

### Actual behaviour
A ' ✅ ' pops out, which means the system is giving me feedback that the process is all right, but when I'm back to any chat I realize the background hasn't changed. 
This occurred several times.

### Configuration
**Operating system:** MacOS Mojave 10.14.5
**Version of Telegram Desktop:** 5.7 (181136)

**Used theme**: Night blue

<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by ErickGiffoni** [comment]
Apparently the error was fixed.

**Comment by Aokromes** [comment]
also, you are using telegram for macos , not telegram desktop, telegram desktop version is 1.8.4 atm.
