### ISSUE TITLE
Full-width Spaces (U+3000) displayed as Regular Spaces (U+0020)

### ISSUE THREAD

**Issue by lee011** [telegramdesktop/tdesktop#6503]
### Steps to reproduce
Type messages with full-width spaces (U+3000) and send. (e.g. `123　456　789`)

### Expected behaviour
Full-width spaces are displayed.

### Actual behaviour
Regular spaces (U+0020) are displayed. (`123 456 789` for the example above)

### Configuration
**Operating system:** Windows 10 1903

**Version of Telegram Desktop:** 1.8.4

**Used theme**: Tinted

### Notes
Full-width spaces are displayed normally on my Telegram for Android.

This is what I see on my Telegram for Android:
![Screenshot_20190908-003613_Telegram](https://user-images.githubusercontent.com/11925743/64477694-4eaf6b80-d1d1-11e9-8972-ffd94e2d0eef.jpg)

And this is what I see on Telegram Desktop:
![image](https://user-images.githubusercontent.com/11925743/64477704-5bcc5a80-d1d1-11e9-89a4-a3c590a78d6a.png)

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/6393 it looks generic bug.
