### ISSUE TITLE
[Feature Request] "Shortcut" to save message when right clicking

### ISSUE THREAD

**Issue by tooomm** [telegramdesktop/tdesktop#6505]
### Is your feature request related to a problem?
When you want to save a message to the "Saved Messages" chat you have to right click and forward that message to that conversation which is highly unintuitive.

### Describe the solution you'd like
Right click --> "Save Message" option
There could be the saved messages logo as well to stress where the message is copied/linked.

### Describe alternatives you've considered
I can't think of any other place where users would expect that.

**Comment by jeffythedragonslayer** [comment]
Or enable clicking and dragging messages to the Saved Messages chat.

**Comment by enchained** [comment]
This feature is still very relevant to me
