### ISSUE TITLE
Clicking on any KDE notification trigger Telegram App

### ISSUE THREAD

**Issue by ACheshirov** [telegramdesktop/tdesktop#6507]
### Steps to reproduce
1. Clicking on any KDE notification (Geary's one for example) trigger Telegram app as well
![screenshot](https://user-images.githubusercontent.com/25287575/64489377-308e4d80-d25b-11e9-8f09-3bd166f58b03.png)
![screenshot2](https://user-images.githubusercontent.com/25287575/64489378-35eb9800-d25b-11e9-80f8-0a1944276423.png)
2. You can see that:
- on first screenshot Telegram app is staying in Tray menu.
- on second screenshot when I clicked on Geary notification, Telegram is triggered too (along with Geary app) and appeared to my taskbar.

Second scenario: Telegram is already open and just staying on taskbark, clicking on any notification it starts blinking as well.
I share two screenshots again
![screenshot_3](https://user-images.githubusercontent.com/25287575/64489477-536d3180-d25c-11e9-97c9-8c64df59a64f.png)
![screenshot_4](https://user-images.githubusercontent.com/25287575/64489478-5536f500-d25c-11e9-9a0e-9a9fdb0b63c0.png)

It's really strange behaviour

### Expected behaviour
Telegram should trigger on notification click only when that notification is related to it

### Configuration
OS: KDE neon User Edition 5.16 x86_64 
Kernel: 4.18.0-18-generic

**Version of Telegram Desktop:**
v 1.8.4

**Used theme**:
Night theme

**Comment by D219** [comment]
Same problem on Debian with KDE and Kubuntu.

**Comment by doctorx32** [comment]
Also noticed on Gnome desktop

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/1026
