### ISSUE TITLE
Inline function doesn't work in Scheduled Messages panel

### ISSUE THREAD

**Issue by jvlianodorneles** [telegramdesktop/tdesktop#6508]
### Steps to reproduce
1. Schedule a message
2. Try to schedule another message, using the inline function of any bot, in the Scheduled Messages panel

### Expected behaviour
Normal operation of the inline function, as in other clients

### Actual behaviour
After entering bot name, inline function is not activated

### Configuration
**Operating system:** Linux 5.0.0-27-generic #28-Ubuntu x86_64 GNU/Linux

**Version of Telegram Desktop:**
1.8.5 beta

**Used theme**:
Default

**Comment by john-preston** [comment]
@jvlianodorneles Yeah, not ready yet :)
