### ISSUE TITLE
Bug: Duplicate message on editing

### ISSUE THREAD

**Issue by Scukerman** [telegramdesktop/tdesktop#6509]
### Steps to reproduce
1. Post a message with text
2. Edit it
3. Add a picture from clipboard by hitting Ctrl+V (Cmd+V)

### Expected behaviour
Append a picture to the rest of the text

### Actual behaviour
The original message remains unchanged, the new one posts and looks as desired.
As a result, we have two posts with the same text.

### Configuration
**Operating system:**
macOS Mojave 10.14.6
Darwin Kernel Version 18.7.0

**Version of Telegram Desktop:**
1.8.4

**Used theme**:
Some night theme I installed in 2017 or even earlier (don't remember when themes feature was introduced)

**Comment by Scukerman** [comment]
While editing:
![image](https://user-images.githubusercontent.com/6469803/64533661-a3133200-d31c-11e9-84d4-13a0912d2b1d.png)

After editing:
![image](https://user-images.githubusercontent.com/6469803/64533690-b45c3e80-d31c-11e9-9ef6-2ea77a8339cd.png)

Note: When I hit Enter to apply the change, the input expects to edit the first message.

**Comment by Scukerman** [comment]
Posted a message without picture:
![image](https://user-images.githubusercontent.com/6469803/64533957-38162b00-d31d-11e9-85ce-01d296515049.png)

Trying to append the image to the message (I hit "Up" button):
![image](https://user-images.githubusercontent.com/6469803/64534016-55e39000-d31d-11e9-8425-2532def1d4d6.png)

Saved the change (I hit Enter):
![image](https://user-images.githubusercontent.com/6469803/64534059-66940600-d31d-11e9-850e-2f2b89018cbf.png)

**Comment by RadRussianRus** [comment]
It's not a bug, it's server-side limitation. You cand add picture to message, that was sent without media.
