### ISSUE TITLE
Does not start (crashes) in OSX 10.6.8

### ISSUE THREAD

**Issue by richdb** [telegramdesktop/tdesktop#651]
The app not start in OSX 10.6.8, is crash at startup. I place the error log this evening. I still work on 10.6.8. because the other updates of OSX really sucks. So I hope this app can be fixed so it works.

**Comment by richdb** [comment]
Mmmm .. looks it not support 10.6.8. anymore? :(

**Comment by auchri** [comment]
OS X 10.6 was never supported
