### ISSUE TITLE
"Close" icon doesn't work when creating a cloud theme

### ISSUE THREAD

**Issue by RememberTheAir** [telegramdesktop/tdesktop#6510]
### Steps to reproduce
1. open an 't.me/addtheme' url of a theme you've created and that doesn't have a desktop palette yet
2. **don't edit any value**
3. use the close button on the upper-right corner of the theme edit window

### Expected behaviour
The "Are you sure you ant to close the editor" popup appears

### Actual behaviour
Nothing happens

**Edit**: even when you edit some values and close the editor discarding the changes, the editor doesn't close

### Configuration
**Operating system:** Windows 10

**Version of Telegram Desktop:** 1.8.5 (edit: happens on 1.8.6 too)

**Comment by john-preston** [comment]
@RememberTheAir It should close the editor. It closes for me, though.

**Comment by RememberTheAir** [comment]
@john-preston [here](https://telegra.ph/file/38e9d19848ae107144d0b.mp4) you can see a screen recording of the issue. Maybe it depends on the window size?

**Comment by john-preston** [comment]
@RememberTheAir I see, thanks!
