### ISSUE TITLE
Strange behaviour with drafts

### ISSUE THREAD

**Issue by jvlianodorneles** [telegramdesktop/tdesktop#6511]
### Steps to reproduce
1. Write message in message field and do some quick editions on it before send.

### Expected behaviour
Expected behavior is the normal behavior of the draft system, as is the case with other clients. Sorry if that sounds rude, but I don't know another way to describe it. :)

### Actual behaviour
When I am typing, by doing some quick editing on the text it goes back to a previous state by itself. It simply returns to an earlier draft state and throws the cursor to the end of the field. Yet, it often happens that after sending the message, it simply reappears in the message box (even after the message has already been sent and shown in chat as such). The issue only occurs on Telegram Desktop and there is no way to be a connection speed issue because it occurs anywhere I am connected.

### Configuration
**Operating system:**
Linux 5.0.0-27-generic #28-Ubuntu x86_64 GNU/Linux

**Version of Telegram Desktop:**
1.8.5 beta

**Used theme**:
Default

I've recorded a video showing what happens. Observe at 0:18.

https://tlgur.com/d/4qlRd6xg

**Comment by slumbergod** [comment]
Affects me too. Using linux version and the bug has been present for several recent releases. It seems quite random though. Sometimes the message gets sent and the typing box is cleared and at other times the message that was just sent reappears in the typing box.

**Comment by Kinrany** [comment]
Me too, Windows version. Didn't happen before today. Happens during editing: in the middle of typing it jumps to an earlier version.

**Comment by kortov** [comment]
Got the same issue sometimes on Ubuntu 18.04

**Comment by kortov** [comment]
I guess it's the same as #4922

**Comment by Aokromes** [comment]
it looks so.

**Comment by Kinrany** [comment]
Looks like the same problem, with the caveat that it restores a previous draft. It does not always clear the text box.
