### ISSUE TITLE
Scheduled message sends at different time

### ISSUE THREAD

**Issue by Ouch** [telegramdesktop/tdesktop#6512]
### Steps to reproduce
1. Schedule a message 
2. Wait for it to send
3. Look at timestamp

### Expected behaviour
Send scheduled message at 12:00PM 

### Actual behaviour
Sent scheduled message at 11:59PM rather than at expected 12:00PM. It seems to send the message roughly a minute or 30 seconds before the expected time. Not sure if this in-fact a bug, but it was unexpected as I was working with important timings.

### Configuration
**Operating system:** 
macOS Mojave Version 10.14.6

**Version of Telegram Desktop:** 
5.7 (181163) AppStore

**Used theme**:
Default

**Comment by 23rd** [comment]
Sorry, you are using the Mac native client, not the Telegram Desktop.
https://github.com/telegramdesktop/tdesktop/issues/5921#issuecomment-483126605
