### ISSUE TITLE
[Feature Request] Self Destructive Messages Similar to Mobile App

### ISSUE THREAD

**Issue by nayeemahmed84** [telegramdesktop/tdesktop#6514]
### Is your feature request related to a problem?
No

### Describe the solution you'd like
Self Destructive Messages Similar to Mobile App

### Describe alternatives you've considered
This feature is already available in the Signal Desktop App

**Comment by jewelbdx** [comment]
Really! It would be a nice feature. That will make Telegram great!

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/6103
