### ISSUE TITLE
"new contacts" keep creating new conversations and notification even if it is turned off in settings

### ISSUE THREAD

**Issue by kaplandani** [telegramdesktop/tdesktop#6515]
### Steps to reproduce
1. disable new contact notifications
2. have  a friend join telegram
3. you get notification + new conversation no one wants to get. 

### Expected behaviour
NOTHING - no one cares who joined telegram. 

### Actual behaviour
You get notification and a new conversation flooding your app/desktop. 

### Configuration
**Operating system:**
both desktop and android. 

**Version of Telegram Desktop:**

**Used theme**:

<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/964
