### ISSUE TITLE
Missing settings option to disable emoji autocompletion

### ISSUE THREAD

**Issue by heaven** [telegramdesktop/tdesktop#6516]
This was introduced in #627, but this addition ignores the people who don't need this and there's no option to disable this popup.

I don't want to disable "replace emoji" but only need to disable this annoying popup with emojis that appears on every `:`. This is incredibly annoying, especially when writing code snippets (why does it appear in ``` blocks?) and also considering the second `Esc` key closes the chat. There are people who use Telegram not only for sending smiles.

Reporting as bug because this is a bug in the UX. There should be a separate option to disable this autocompletion.

**Comment by 23rd** [comment]
Did you try to disable `Suggest emoji replacements` option?

**Comment by heaven** [comment]
@23rd hi, not the replacement but the popup that appears every time I enter ":".

**Comment by sonnydbb** [comment]
Please, puh-lease make this pop-up optional. It is immensely annoying and totally unnecessary to anyone using Telegram for anything useful.

**Comment by 23rd** [comment]
And still I can't understand what the matter is to disable the `Suggest emoji replacements` option.

**Comment by constXife** [comment]
Agreed, as ruby developer I'm often using symbols like symbol == :test in chat and I really-really hate emoji popup.

**Comment by zwimer** [comment]
This bug still exists.

**Comment by ilya-fedin** [comment]
> This bug still exists.

https://github.com/telegramdesktop/tdesktop/issues/6516#issuecomment-565838488

Can't understand why this issue is still open, this option does what is described in the first post: disables the popup, but doesn't disable the replacement.
