### ISSUE TITLE
Wallpaper resolution is too damn low

### ISSUE THREAD

**Issue by mrmaffen** [telegramdesktop/tdesktop#652]
I'm using Telegram Desktop on my new fancy 2560x1440 monitor and yea the wallpaper looks quite awful :/
![telegram_wallpaper_res_too_low](https://cloud.githubusercontent.com/assets/1526877/7093017/18279e64-dfb6-11e4-9c92-66e559fe93f8.png)

**Comment by mrmaffen** [comment]
After all this time this is still an issue :(

**Comment by john-preston** [comment]
@mrmaffen I suggest you choose any wallpaper you like from the internet :(

Those are server-side cloud wallpapers, they're the same for all Telegram apps, I can't change them anyway.

**Comment by mrmaffen** [comment]
@john-preston Hey John, love your work! Telegram being open-source is one of the best things about it. I've already converted almost all of my friends and family from WhatsApp to Telegram :)

Of course I'm aware that I can choose my own wallpaper, but I thought that those cloud wallpapers should be offered in sufficient size and resolution as to look good on most computer screens. But since they are not baked into telegram-desktop I guess that this here isn't the right place to bring up the issue.
