### ISSUE TITLE
Microsoft Store version is outdated

### ISSUE THREAD

**Issue by drrlvn** [telegramdesktop/tdesktop#6521]
### Steps to reproduce
1. Download Telegram Desktop from Microsoft Store (https://www.microsoft.com/store/productId/9NZTWSQNTD0S)
1. Version is 1.8.2 while newer version have been out for 5+ days.

### Expected behaviour
Download latest version from Microsoft Store.

### Actual behaviour
Version on Microsoft Store is 1.8.2 which is outdated.

### Configuration
**Operating system:** Windows 10

**Version of Telegram Desktop:** 1.8.2

**Comment by john-preston** [comment]
@drrlvn Yeah, I'll try to upload an update there soon.

**Comment by drrlvn** [comment]
@john-preston That would be great, thanks!

**Comment by beerisgood** [comment]
Is this a official version? Cause the Telegram website doesn't list that: https://telegram.org/apps

It only list the unofficial [Unigram](https://github.com/UnigramDev/Unigram)

**Comment by drrlvn** [comment]
Telegram on the Microsoft Store has been updated.
