### ISSUE TITLE
Can't remove collage from schedule in 1 click

### ISSUE THREAD

**Issue by Neurotoxin001** [telegramdesktop/tdesktop#6523]
### Steps to reproduce
1. Upload 2+ media to schedule
2. Try to select scheduled message to delete it or just try to right click on it if there is text under the media collage, there is no "delete" button
3. You can't
4. You must click "delete" on every media one by one for delete scheduled post

https://i.imgur.com/Jn60Hu3.mp4

### Configuration
**Operating system:** win 10 ltsc 1809

**Version of Telegram Desktop:** 1.8.8

**Used theme**: default dark

**Comment by john-preston** [comment]
@Neurotoxin001 You can select them by pressing the mouse near the album and dragging the mouse up or down and then delete the selected album by a button at the top bar.

**Comment by Neurotoxin001** [comment]
Ah, yes, thanks. But it would be great if there was a "delete message" button, as in regular chats, when you click on the text under the collage.
