### ISSUE TITLE
Cannot select emoji when sending multiple files

### ISSUE THREAD

**Issue by Sepehrtooz** [telegramdesktop/tdesktop#6525]
![photo_2020-03-31_12-46-31](https://user-images.githubusercontent.com/55192376/78003297-af5cec00-734d-11ea-93f7-00e93eb19639.jpg)
![photo_2020-03-31_12-46-37](https://user-images.githubusercontent.com/55192376/78003316-b5eb6380-734d-11ea-97c8-fe07219353e6.jpg)

### Configuration
**Operating system:**
Win7
**Version of Telegram Desktop:**
1.8.8
**Used theme**:
Tinted
<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by jeffythedragonslayer** [comment]
Can you reupload the screenshot?  The hyperlink href data is wrong.

**Comment by Sepehrtooz** [comment]
[image: Capture.PNG]
[image: Capture2.PNG]
When I change the type of sending photos, the emoji panel opens in the
previous location

**Comment by jeffythedragonslayer** [comment]
I'm only seeing the screenshot files names this time.

**Comment by Sepehrtooz** [comment]
Can you see the photos now?

**Comment by jeffythedragonslayer** [comment]
Nope.

**Comment by Sepehrtooz** [comment]
https://ibb.co/VWzq9Mm
https://ibb.co/3CGhp08

**Comment by Sepehrtooz** [comment]
If you don't see the photos in these links, send message in telegram:
@Losangelesguy

**Comment by jeffythedragonslayer** [comment]
Those I can see :)

**Comment by Sepehrtooz** [comment]
I chatted with you in email, while photos aren't displayed here :/

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/commit/4ae760dd7e1f4224bbca8f22232211d6b53f56a6
