### ISSUE TITLE
Arabic font is unreadable on Fedora 30

### ISSUE THREAD

**Issue by ThaSami** [telegramdesktop/tdesktop#6528]
english is fine 
however arabic in unreadable 
![image](https://user-images.githubusercontent.com/25616506/64716124-7866dc00-d4ca-11e9-9b03-2eb4301e2536.png)

**Version of Telegram Desktop:**
latest version from Gnome software
**Used theme**:
dark / light same..

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/5172
