### ISSUE TITLE
Update problems

### ISSUE THREAD

**Issue by InterpolKun** [telegramdesktop/tdesktop#653]
Windows client doesnt install new update. It's tells "Update check failed :(". Switch to another language doesnt help. I cant log in in my account beacuse of 2-step verification, which comes with THIS update. Ok, i will reinstall new version, but check, please, this issue well. Thx.

**Comment by auchri** [comment]
#645

**Comment by InterpolKun** [comment]
So i tell, that switching to another language doesnt help.

**Comment by Vilmodao** [comment]
I have the same update problem with Telegram Desktop **portable**. Now I use version 0.8.4, but problem became few versions ago.
Some info about: Win 7 x 64, Telegram Desktop **portable** 0.8.4

1. Automatically update doesn't work. Nothing happens at all. But log file shows this:
>[2015.04.25 18:40:32] Getting difference! no updates timer: 0, remains: -1
>[2015.04.25 18:40:32] Getting difference for 1139, 1429976251
>[2015.04.25 18:43:32] Getting difference! no updates timer: 0, remains: -1
>[2015.04.25 18:43:32] Getting difference for 1139, 1429976431
>[2015.04.25 18:46:32] Getting difference! no updates timer: 0, remains: -1
>[2015.04.25 18:46:32] Getting difference for 1139, 1429976612

2. If I manualy check for update I'll see like downloading progress:
![Screenshot_1](http://s24.postimg.org/nel8gnk2d/screenshot_1429977430.jpg)

But there is no real downloading on my network monitor. It's just fake dowload progress.

Log for manual updete check:
>[2015.04.25 18:51:19] Update Error: cant rename temp dir 'F:/qwert/Telegram/tupdates/temp' to ready dir 'F:/qwert/Telegram/tupdates/ready', error 10: Unknown error

In this time folder /tupdates/temp is completely empty

**Comment by Vilmodao** [comment]
Still have problem with 0.8.7.
Log:
>[2015.05.02 17:49:49] Update Error: cant rename temp dir 'F:\qwert\Telegram\tupdates\temp' to > > >ready dir 'F:\qwert\Telegram\tupdates\ready'. Error code: 5, error message: Отказано в доступе.

Does anyone care about this?

**Comment by kiwikern** [comment]
Had the same problem. Seems to be fixed with 0.8.22 though.

**Comment by Vilmodao** [comment]
My problem seems solved.

**Comment by Katzen-Gott** [comment]
@InterpolKun could you please check and close if fixed?
