### ISSUE TITLE
bug on TDesktop 1.8.8

### ISSUE THREAD

**Issue by user38192** [telegramdesktop/tdesktop#6532]
When i turn on a local passcode,  and block telegram, sometimes i can see images on notification pop-ups
Telegram Desktop 1.8.8.
![Безым2222янный](https://user-images.githubusercontent.com/55229344/64762006-ff0ccf00-d545-11e9-901f-a0b99b12995b.png)

**Comment by MasterGroosha** [comment]
There used to be bug that despite notification settings, when an unknown user (the one you didn't chat with before) sends you a message, TDesktop will show their avatar. Maybe this is somehow connected.
