### ISSUE TITLE
Can you support secret chat on Windows/Linux as Mac OS X?

### ISSUE THREAD

**Issue by wenssh** [telegramdesktop/tdesktop#654]
Can you support secret chat on Windows/Linux as Mac OS X?
I just want to chat with my friends in privacy, I don't care whether it can sync from another platform or not.

**Comment by kireledan** [comment]
There are numerous duplicate issues asking for secret chat. Please use the search utility before posting an issue.

**Comment by formatq** [comment]
Need to create FAQ page, describe this why and give link to all issue like this

**Comment by wenssh** [comment]
I searched before I open this issue. I'm sorry for bothering.
Secret chat is the only reason that I use Telegram, I will try to use it on my phone.
