### ISSUE TITLE
Font size for Ethiopic font is too small

### ISSUE THREAD

**Issue by redet-G** [telegramdesktop/tdesktop#6543]
It is very hard to read Ethiopic font as its font size is too small. why want you
### Steps to reproduce
- view this text in telegram desktop 
የጎንደር ዩንቨርሲቲ የመጥፋት አደጋ የተጋረጠበትን የግእዝ ቋንቋ ለመታደግ በአዲሱ የትምህርት ዘመን በመጀመሪያ ዲግሪ የቋንቋ ትምህርት ለመስጠት መዘጋጀቱን አስታወቀ፡፡ የዩንቨርሲቲው የአካዳሚክ ምክትል ፕሬዘዳንት ዶክተር ካሳሁን ተገኘ ለኢዜአ እንደተናገሩት ኢትዮጵያ የግእዝ ቋንቋ ባለቤት ብትሆንም ለቋንቋው ማደግና መስፋፋት የተሰጠው ትኩረት አነስተኛ ነው፡፡ “በዚህም ሳቢያ ቋንቋው የመጥፋት አደጋ የተጋረጠበት ከመሆኑም በላይ በግዕዝ ቋንቋ የተጻፉ በርካታ የብራና መጻፍትን ለጥናትና ምርምር ስራ ለማዋል አልተቻለም “ብለዋል፡፡
### Expected behaviour
similar readability as English text

### Actual behaviour
smaller font size just for Ethiopic font

### Configuration
**Operating system:**
windows 10
**Version of Telegram Desktop:**
1.8.8

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/5172 generic bug.
