### ISSUE TITLE
[Feature Request] Images with messages.

### ISSUE THREAD

**Issue by afliw** [telegramdesktop/tdesktop#655]
It would be goo to have the ability to add a message when sending the image, so when the image successfully upload and arrive to the other end, they see the image with the intended text (over the image, like Snapchat, would be great, but I think something like the "Reply" function would be enough).

Thanks for your attention and for making this great app.
Regards!

**Comment by chaosdrop** [comment]
+1-ish Mobile version has has image captions which would be nice to do the same/similar on the desktop version.

**Comment by auchri** [comment]
duplicate #727
