### ISSUE TITLE
Sound/Video does not stop when desktop window closed

### ISSUE THREAD

**Issue by flybd5** [telegramdesktop/tdesktop#6550]
### Steps to reproduce
1. Open telegram
2. Play any video with sound
3. Close window

### Expected behaviour
Window closes and audio/playback stops or pauses

### Actual behaviour
Windows closes but audio/playback continues

### Configuration
**Operating system:**
Ubuntu 18
**Version of Telegram Desktop:**
1.8.8
**Used theme**:

<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by Aokromes** [comment]
maybe it's because it's not really closed and instead it's on background?

**Comment by flybd5** [comment]
I know the difference between closed and minimize or sent to the background. That is not the case. The windows was closed. Video and audio must stop. It's well known accepted user interface behavior.

**Comment by flybd5** [comment]
More than a year later and still not fixed. That's what I call "responsiveness". Not. More like the mark of a dev team that thinks new features is more important than fixing bugs, the mark of "agile".

**Comment by ilya-fedin** [comment]
This is not an issue since tdesktop has tray icon and is closed to tray icon and runs in background. If you want to fully close the application on window close, disable tray icon

**Comment by flybd5** [comment]
That is irrelevant to the issue. The desktop app is violating a very basic, universal rule of UI design. Close the window? Stop any audio or video.

**Comment by ilya-fedin** [comment]
Some people like to listen tracks when Telegram works in the background. This is not an issue.

**Comment by flybd5** [comment]
Those people can minimize the window if that's the case. Do you not
understand the difference between "minimize" and "close"? Perhaps that is
the root cause of this issue. I can upload a video if you need help with
that. This IS an issue.

**Comment by ilya-fedin** [comment]
I disagree, minimizing leaves an icon in the taskbar. This behavior is intended and is not an issue, not like you it or not.

**Comment by flybd5** [comment]
No, your behavior may be intended, but the role who determines whether it
is an issue or not, and whether they like it or not, is NEVER the
developer, it is the USER. Business 101. But then again, this is a classic
amateur mistake. I guess that explains things. You have my permission to
close this issue under "Amateur developer's 'feature not bug' mistake."

P.S. A professional would add an option to the settings to have the app
behave according to accepted UX/UI standards. And maybe even hire a
competent UI/UX designer.

**Comment by flybd5** [comment]
Fine. Stale dev brains is the root cause of this issue.
