### ISSUE TITLE
TG Desktop 1.8.8 huge cpu usage and memory leak

### ISSUE THREAD

**Issue by user38192** [telegramdesktop/tdesktop#6552]
Huge CPU usage and RAM usage 1 hour after launch.
Telegram Desktop 1.8.8
Windows 10 1903 x64
Custom theme. 

![1](https://user-images.githubusercontent.com/55229344/64926974-05809c80-d80d-11e9-956d-ae6a238dc5c4.jpg)
![2](https://user-images.githubusercontent.com/55229344/64926975-05809c80-d80d-11e9-8d32-a83fd1ebeb19.jpg)

**Comment by patrickdundas** [comment]
Could you include your custom theme in case that plays into it? With everything the same except the theme, I cannot reproduce.

**Comment by user38192** [comment]
it not custom theme, its original tg desktop theme.

**Comment by user38192** [comment]
Telegram Desktop 1.8.9, same thing, some hours after launch
Original tg  theme, Windows 10 x64 1903

<img width="518" alt="333" src="https://user-images.githubusercontent.com/55229344/65839692-671a2e00-e318-11e9-80c5-92921d4f6d0e.PNG">

**Comment by Aokromes** [comment]
what's your motherboard?

**Comment by user38192** [comment]
> 
> 
> what's your motherboard?

I am on notebook hp probook 430 g5

**Comment by Aokromes** [comment]
In case someone knows how to fix, debug build 1.8.13 running under ubuntu linux x64

https://gist.github.com/37b7ee627100c703518b6586a1ed9713

**Comment by bestpika** [comment]
`1.8.15` have the same issue on Windows 8.1 x64.

**Comment by fakhamatia** [comment]
What is normal RAM usage for Telegram in Linux?
I have Ubuntu 18.04 and Telegram 1.8.15 and its use 336.3MiB

**Comment by Aokromes** [comment]
try after https://github.com/telegramdesktop/tdesktop/commit/5f5d5629f8e36f4eb6f9c478eb1b76a4cdb08b17

**Comment by fakhamatia** [comment]
@Aokromes 
![Screenshot from 2020-01-26 10-15-56](https://user-images.githubusercontent.com/20030910/73131694-1647e700-4025-11ea-951b-c7c6681f7e82.png)

**Comment by Aokromes** [comment]
more valgrind logs
https://t.me/tgbetachat/218737
https://t.me/tgbetachat/218757

**Comment by fakhamatia** [comment]
![ksnip_20200224-040557](https://user-images.githubusercontent.com/20030910/75123281-4b466880-56bb-11ea-8b68-2d28a42a085c.png)

1.6.16 Beta
