### ISSUE TITLE
deadlock on startup with qt5gtk2 style

### ISSUE THREAD

**Issue by t-wissmann** [telegramdesktop/tdesktop#6554]
I don't consider this a critical bug, and I'm not sure whether this is telegram-desktop's fault.

With the [qt5gtk2 style](https://bitbucket.org/trialuser02/qt5gtk2/src/master/) and the environment `export QT_STYLE_OVERRIDE=qt5gtk2`, telegram-desktop does not start up but hangs:
```
$  QT_STYLE_OVERRIDE=qt5gtk2 telegram-desktop                                             49s

(telegram-desktop:5323): GLib-GObject-WARNING **: 20:49:57.612: cannot register existing type 'GdkDisplayManager'

(telegram-desktop:5323): GLib-CRITICAL **: 20:49:57.612: g_once_init_leave: assertion 'result != 0' failed

(telegram-desktop:5323): GLib-GObject-CRITICAL **: 20:49:57.612: g_object_new_with_properties: assertion 'G_TYPE_IS_OBJECT (object_type)' failed

```
If I run it in strace, then the strace ends with
```
openat(AT_FDCWD, "/usr/share/locale/de/LC_MESSAGES/gtk30.mo", O_RDONLY) = 12
fstat(12, {st_mode=S_IFREG|0644, st_size=109915, ...}) = 0
mmap(NULL, 109915, PROT_READ, MAP_PRIVATE, 12, 0) = 0x7fffe830c000
close(12)                               = 0
futex(0x7ffff4653a28, FUTEX_WAKE_PRIVATE, 2147483647) = 0
rt_sigaction(SIGPIPE, {sa_handler=SIG_IGN, sa_mask=[PIPE], sa_flags=SA_RESTORER|SA_RESTART, sa_restorer=0x7ffff403c7e0}, {sa_handler=SIG_IGN, sa_mask=[PIPE], sa_flags=SA_RESTORER|SA_RESTART, sa_restorer=0x7ffff403c7e0}, 8) = 0
futex(0x7ffff4653a28, FUTEX_WAKE_PRIVATE, 2147483647) = 0
getpeername(2, 0x7fffffffd600, [128])   = -1 ENOTSOCK (Socket-Operation an einem nicht-Socket)
futex(0x7ffff4653a28, FUTEX_WAKE_PRIVATE, 2147483647) = 0
ioctl(2, TCGETS, {B38400 opost isig icanon echo ...}) = 0
getpid()                                = 5695
stat("/etc/localtime", {st_mode=S_IFREG|0644, st_size=2298, ...}) = 0
write(2, "\n(telegram-desktop:5695): GLib-G"..., 135
(telegram-desktop:5695): GLib-GObject-WARNING **: 20:57:48.381: cannot register existing type 'GdkDisplayManager'
) = 135
ioctl(2, TCGETS, {B38400 opost isig icanon echo ...}) = 0
getpid()                                = 5695
stat("/etc/localtime", {st_mode=S_IFREG|0644, st_size=2298, ...}) = 0
write(2, "\n(telegram-desktop:5695): GLib-\33"..., 128
(telegram-desktop:5695): GLib-CRITICAL **: 20:57:48.381: g_once_init_leave: assertion 'result != 0' failed
) = 128
ioctl(2, TCGETS, {B38400 opost isig icanon echo ...}) = 0
getpid()                                = 5695
stat("/etc/localtime", {st_mode=S_IFREG|0644, st_size=2298, ...}) = 0
write(2, "\n(telegram-desktop:5695): GLib-G"..., 166
(telegram-desktop:5695): GLib-GObject-CRITICAL **: 20:57:48.381: g_object_new_with_properties: assertion 'G_TYPE_IS_OBJECT (object_type)' failed
) = 166
futex(0x7ffff4653a28, FUTEX_WAIT_PRIVATE, 131, NULL
```
(I can provide you a full strace if it helps.)

After these messages, telegram-desktop hangs and no window is opened.
Other qt5 applications (e.g. [qt5tools, like qdbusviewer](https://www.qt.io) and [cantata](https://github.com/CDrummond/cantata)) work fine and don't print any of the above error messages. Also `telegram-desktop` works as expected with any other `QT_STYLE_OVERRIDE`.

I'm using telegram-desktop 1.8.8 on arch linux and qt5gtk2 0.6. I'm not sure how likely it is that one can find the problem of this corner case setup. I'm posting this here mainly for documentation purposes :-)

**Comment by Aokromes** [comment]
this bug is still valid?

**Comment by t-wissmann** [comment]
I still get the deadlock, but maybe it is my fault anyway:
On https://bitbucket.org/trialuser02/qt5gtk2/src/master/ it is written:
> `export QT_QPA_PLATFORMTHEME=qt5gtk2`
> Attention! Environment variable QT_STYLE_OVERRIDE should be removed before usage.

So I assume I should not have set `QT_STYLE_OVERRIDE` in the first place, but `QT_QPA_PLATFORMTHEME` instead. With the latter, I don't experience any problems. I think we can consider this issue as fixed or irrelevant.
