### ISSUE TITLE
[Feature Request] Email Registration

### ISSUE THREAD

**Issue by trymeouteh** [telegramdesktop/tdesktop#6555]
I know this may not be the place to request this,

This will be a handy feature since it will allow users to use telegram without a phone number. Email addresses are global but phone numbers are regional since if you move to a different region or country you will most likely get a new phone number.

I do not like using my phone number to sign up and that is what has kept me from using Telegram. Please add a email option.

**Comment by Aokromes** [comment]
i don't think they will never allow that email registration can lead to far more spam.https://github.com/telegramdesktop/tdesktop/issues/3148
