### ISSUE TITLE
How to add contact by username?

### ISSUE THREAD

**Issue by namoplasta** [telegramdesktop/tdesktop#656]
I can create username, but I can not add contacts by username or i not know make this.

Who has username can talk to me, but I can not see what is the username he uses, I lost a contact when cleaned the history, did not know he was removed from the contact list, I thought it only removed when I excluded.

**Comment by Alirezaaa** [comment]
Related to #331.
If you cleared history for a contact which is added by his/her username, you still have the chat in your phone device chats list.

**Comment by namoplasta** [comment]
I not have a modern cellphone.

**Comment by auchri** [comment]
#925
