### ISSUE TITLE
[Question] Are the map preview images generated from OpenStreetMap data?

### ISSUE THREAD

**Issue by camelCaseNick** [telegramdesktop/tdesktop#6560]
I came across issue #2787, because I am interested in the use of OpenStreetMap. Now I asked myself if the map preview images are generated from OpenStreetMap data, because the origin is undisclosed. 

It is also interesting if it is not OpenStreetMap, what it is instead.

(If so, from this answer arises my request for adding the necessary attribution.)

**Comment by mxa** [comment]
They most definitely are rendered from OSM data. No doubt here.

**Comment by camelCaseNick** [comment]
@mxa You are right! I will hence file an issue to comply with attribution requirement.
