### ISSUE TITLE
Sticker panel doesn't remember where it was after restart

### ISSUE THREAD

**Issue by imashxtyz** [telegramdesktop/tdesktop#6562]
### Steps to reproduce
1. Open sticker panel for stickers or gifs and scroll a bit
2. Close telegram
3. Open telegram

### Expected behaviour
Sticker panel should remember which panel I was last time - emoji, stickers or gifs - and also should remember where I scrolled

### Actual behaviour
It's always default emoji panel

### Configuration
**Operating system:**
Windows 7 64bit
**Version of Telegram Desktop:**
1.8.8
**Used theme**:
Classic

**Comment by patrickdundas** [comment]
I believe this is intended behavior

**Comment by imashxtyz** [comment]
@patrickdundas wasn't intended until recently though. They should at least let us know and close this as resolved if it's intended. But I doubt it is. If so it is less convenient than it was before.

**Comment by Aokromes** [comment]
maybe fixed by https://github.com/telegramdesktop/tdesktop/commit/af818b40aad888a0a1d694d81705477b31afd415 ?
