### ISSUE TITLE
Can't input Chinese in Ubuntu 19.04

### ISSUE THREAD

**Issue by hkdb** [telegramdesktop/tdesktop#6564]
### Steps to reproduce
1. Open Telegram Desktop
2. Switch to Chinese input (ibus-RIME)
3. Attempt to type Chinese

### Expected behaviour
Able to type Chinese. 

### Actual behaviour
No list of characters to choose. Not even sure if Chinese input is working at all.

### Configuration
**Operating system:**
Ubuntu 19.04
**Version of Telegram Desktop:**
v.1.8.8
**Used theme**:
Default night mode
<details><summary><b>Logs</b>:</summary>
N/A
</details>

**Comment by hkdb** [comment]
FYI, Chinese input works fine in 1.8.4

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/2013

**Comment by hkdb** [comment]
Unfortunately, that workaround doesn't work. In fact, I already have QT_IM_MODULE=ibus in my environment. The only thing I am thinking is whether anything has changed with QT that caused this for all QT apps or just Telegram...

**Comment by Rivers47** [comment]
Same, but other qt5 programs seem to work fine. It's interesting how telegram being the only program I need for input method fails to work...

**Comment by dispensable** [comment]
Same problem, but if I switch to ubuntu's own source `apt install telegram-desktop` and set `QT_IM_MODULE` env, the IM can work perfectly.

Is there some update or new patch made the IME behavior broken ?
