### ISSUE TITLE
Messages in previews are not formatted

### ISSUE THREAD

**Issue by tanyaionova** [telegramdesktop/tdesktop#6567]
### Steps to reproduce
1. Write a message
2. Look at chat preview / reply preview
![image](https://user-images.githubusercontent.com/42947087/65209327-6e337780-daa0-11e9-817f-fe550f6035ee.png)

### Expected behaviour
Text has formatting

### Actual behaviour
Text loses formatting
![image](https://user-images.githubusercontent.com/42947087/65209336-768bb280-daa0-11e9-8ac1-0e30db49a6d6.png)
![image](https://user-images.githubusercontent.com/42947087/65209342-7ab7d000-daa0-11e9-8415-b9d6cd311253.png)

### Configuration
**Operating system:**
`Linux 5.2.11-1-MANJARO x86_64`

**Version of Telegram Desktop:**
1.8.2

**Used theme**:
Default night mode

Looks like #3979 is not fixed

**Comment by patrickdundas** [comment]
#3979 was auto-closed as it went stale for 380+ days. According to one comment, this may be intended behavior. Personally, when I want to see a message preview, I don't care about seeing the formatting.

https://github.com/telegramdesktop/tdesktop/issues/3979#issuecomment-345362481

**Comment by tanyaionova** [comment]
Yep, that's not so critical bug, and yes, that might be intended behaviour (I see this in Android app too). But this could be an eye candy worth fixing anyway.
