### ISSUE TITLE
Such links "tg://resolve?domain=" do not work in portable Telegram Desktop

### ISSUE THREAD

**Issue by online** [telegramdesktop/tdesktop#6568]
### Steps to reproduce
1. Click on any links, e. g. → "tg://resolve?domain="
2. Nothing happens
3. …

### Expected behaviour
I expect a suggestion to open a link in Telegram Desktop (portable), when I click on link "tg://resolve?domain=" in Chrome browser.

### Actual behaviour
I click on the link, but nothing happens.

### Configuration
**Operating system:** Windows 10, build 1903 (recently reinstalled)

**Version of Telegram Desktop:**
v1.8.8

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/2641
