### ISSUE TITLE
[Feature Request] Be able to download all the files of a channel in a selecte directory.

### ISSUE THREAD

**Issue by felisucoibi** [telegramdesktop/tdesktop#6573]
There are some channlees that have some files to download.
Could be nice a way to choose a folder to download all the files of a channel.

**Comment by MasterGroosha** [comment]
Just go to that channel, click on 3-dots button to the right of channel title and select "Export chat history". There you can customize output location.

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/5661
