### ISSUE TITLE
Telegram crash when accessing Stickers on Arch Linux ARM

### ISSUE THREAD

**Issue by frankgould** [telegramdesktop/tdesktop#6574]
### Steps to reproduce
1. Start app and open a contact thread.
2. Hover over emojis and click on STICKERS tab.
3. App hangs for a few seconds then disappears.
4. App restarts.

### Expected behavior
The app should display all the stickers and allow me to select one to send.

### Actual behaviour
App freezes, window disappears for a few seconds, then restarts app

### Configuration
**OS:**
Linux 4.19.71-2-ARCH #1 SMP PREEMPT Sun Sep 15 00:20:03 UTC 2019 armv7l GNU/Linux
**Version of Telegram Desktop:** 1.8.8
**Used theme**: nightmode.

I could not find where the log file is located. I tried turning off animations and gifs with no change in results. I just won't be using stickers and need other users to avoid because if they post a sticker, my app crashes.

**Comment by Johnnynator** [comment]
Arch armv7l is no official supported target. Can you at least post a backtrace (with debug symbols) here?

**Comment by frankgould** [comment]
I'm new at core dumps and backtrace on third party apps. I followed the Arch Linux wiki to generate a couple files that I think you're asking me to provide.

journalctl: https://pastebin.com/v8cYsxzG
core dumps & backtrace: https://pastebin.com/NNN4Tnyv

Please let me know if I can provide anything more. Some direction might be helpful for me.

**Comment by kolay-v** [comment]
Same issue on arch Linux aarch64.

**Comment by Aokromes** [comment]
#6647
