### ISSUE TITLE
Windows 10 Notification Center / Clicking on a notification only closes it

### ISSUE THREAD

**Issue by tooomm** [telegramdesktop/tdesktop#6575]
### Steps to reproduce
1. Receive a message
2. Don't click the notification
3. Open Action center to see the notification there
4. Click the notification

### Expected behaviour
Open the corresponding chat.
At best scroll to the correct position and highlight the message.

### Actual behaviour
Notification only disappears.

### Configuration
**Operating system:** Windows 10 1903

**Version of Telegram Desktop:** 1.8.8

**Used theme**: default

**Comment by marcoValkyriweb** [comment]
What is your notification setting, Native or Telegram one?
Settings > Notifications > Native Notifications
![image](https://user-images.githubusercontent.com/34270069/67684583-1be94e80-f99c-11e9-95b1-e34e990f9b33.png)
I think the default is to have it off, and notifications work fine for me on 1903.

**Comment by tooomm** [comment]
@marcoValkyriweb I've native ones enabled, I guess otherwise (with the default? telegram ones) I would not even see windows system notifications at all, but some other self-coded pop-up.

**Comment by birdkiwi** [comment]
I have this problem too.
BTW, pop-up notifications don't open Telegram too. Sometimes it opens, but mostly no.

**Comment by jmml97** [comment]
This is happening to me here. Windows version 2004 and Telegram Desktop 2.1.10.

**Comment by tooomm** [comment]
Actually, clicking a notification only makes it disappear shortly... (Telegram, or the corresponding chat/message are still not opened.)
...the notification keeps reappearing if you close and reopen the notification center for me on Windows 10 20H2.
