### ISSUE TITLE
[Feature Request] Ban and delete all messages when click on "user joined" message

### ISSUE THREAD

**Issue by Neurotoxin001** [telegramdesktop/tdesktop#6576]
### Is your feature request related to a problem?
It's take too long time to find spamer in users list who joined in group and don't post anything, and it will be faster if you make able to block and delete all messages when I click on "user joined" message
https://i.imgur.com/HXcjVQW.mp4

### Describe the solution you'd like
Here is how's it's working on iOS telegram app:
https://i.imgur.com/7qrT28G.mp4

**Comment by DJ-ZX** [comment]
this is definitely needs to be done, as well as other channel and group management improvements - now it's too complex and not obvious

**Comment by john-preston** [comment]
Should be fixed by https://github.com/telegramdesktop/tdesktop/commit/8c224f7aca89f327e0eebeeb7be4e7bbe9693ce2
