### ISSUE TITLE
Error on release make

### ISSUE THREAD

**Issue by nikchis** [telegramdesktop/tdesktop#6577]
### Steps to reproduce
1. Used this guide to compile sources: https://github.com/telegramdesktop/tdesktop/blob/dev/docs/building-cmake.md
2. Got an error on last step (run `/tdesktop/out/Release$ make $MAKE_THREADS_CNT`)

### Expected behaviour
Successfull make

### Actual behaviour
Error

### Configuration
**Operating system:**
Ubuntu 18.04.3 LTS
Linux 4.19.71-v8+ aarch64 GNU/Linux

**GCC:**
gcc (Ubuntu/Linaro 7.4.0-1ubuntu1~18.04.1) 7.4.0

**G++:**
g++ (Ubuntu/Linaro 7.4.0-1ubuntu1~18.04.1) 7.4.0

**Version of Telegram Desktop:**
latest (v1.8.8)

<details><summary><b>Logs</b>:</summary>
 
`~/tg_build/tdesktop/out/Release$ make $MAKE_THREADS_CNT`

`
Could not read from progress file.
Building CXX object CMakeFiles/lib_lottie.dir/home/nikchis/tg_build/tdesktop/Telegram/SourceFiles/lottie/lottie_animation.o`

`
cc1plus: error: -Werror=class-memaccess: no option -Wclass-memaccess
CMakeFiles/lib_lottie.dir/build.make:62: recipe for target 'CMakeFiles/lib_lottie.dir/home/nikchis/tg_build/tdesktop/Telegram/SourceFiles/lottie/lottie_animation.o' failed`

`
make[2]: *** [CMakeFiles/lib_lottie.dir/home/nikchis/tg_build/tdesktop/Telegram/SourceFiles/lottie/lottie_animation.o] Error 1`

`
CMakeFiles/Makefile2:901: recipe for target 'CMakeFiles/lib_lottie.dir/all' failed
make[1]: *** [CMakeFiles/lib_lottie.dir/all] Error 2`

`
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2`
</details>

**Comment by Johnnynator** [comment]
Telegram expects to have at least GCC 8.1,`-Wclass-memaccess` was introduced with GCC 8. So you either have to upgrade your GCC version or try to patch around it (and expect more issues to crop up).

**Comment by nikchis** [comment]
@Johnnynator thank you! make started with gcc 8.3.0

**Comment by nikchis** [comment]
Got a new one:
```
Building CXX object CMakeFiles/lib_export.dir/home/nikchis/tg_build/tdesktop/Telegram/SourceFiles/export/output/export_output_html.o

/home/nikchis/tg_build/tdesktop/Telegram/SourceFiles/export/output/export_output_html.cpp: In function ‘QByteArray Export::Output::{anonymous}::SerializeString(const QByteArray&)’:
/home/nikchis/tg_build/tdesktop/Telegram/SourceFiles/export/output/export_output_html.cpp:115:17: error: comparison is always true due to limited range of data type [-Werror=type-limits]
   } else if (ch >= 0 && ch < 32) {
              ~~~^~~~
cc1plus: all warnings being treated as errors
CMakeFiles/lib_export.dir/build.make:232: recipe for target 'CMakeFiles/lib_export.dir/home/nikchis/tg_build/tdesktop/Telegram/SourceFiles/export/output/export_output_html.o' failed
make[2]: *** [CMakeFiles/lib_export.dir/home/nikchis/tg_build/tdesktop/Telegram/SourceFiles/export/output/export_output_html.o] Error 1
CMakeFiles/Makefile2:1300: recipe for target 'CMakeFiles/lib_export.dir/all' failed
make[1]: *** [CMakeFiles/lib_export.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/4275
