### ISSUE TITLE
AltGr acts like Ctrl in shortcuts on some keyboard layouts

### ISSUE THREAD

**Issue by Luapix** [telegramdesktop/tdesktop#6579]
### Steps to reproduce
1. Enable Windows' French AZERTY keyboard layout
2. Press AltGr + Shift + 0 / Ctrl + Alt + Shift + 0 (equivalent on Windows international layouts) in a chat window

### Expected behaviour
This should not do anything : AltGr + Shift + 0 is not a registered shortcut (by default) in Telegram Desktop.

### Actual behaviour
The Saved Messages window opens, as if Ctrl + 0 / Ctrl + Shift + 0 had been pressed.

This is problematic, as some keyboard layouts (such as [this extended AZERTY one](http://mjulier.free.fr/clavier/)) define some characters under an AltGr + Shift + ?? shortcut. Telegram / Qt prioritizes the shortcut over the keyboard combination, preventing the user from typing some characters (in my case, À) unless they disable / change the shortcut.

It's also possible that this is a Qt problem, but I do not know how one would confirm this.

### Configuration
**Operating system:** Windows 10 Pro 64 bit (18362.356)

**Version of Telegram Desktop:** 1.8.8

**Comment by nerai** [comment]
Not a solution, and you probably know this already, but pressing AltGr is pretty much the same as Ctrl+Alt. Shortcuts in most programs fire when all required modifiers are present (in this case, Ctrl). So AltGr+Shift+0 is seen as Ctrl+Alt+Shift+0 which suffices to fire Ctrl+0.

It's a tricky situation. I'm using a keyboard layout that requires me to press some keys twice instead of mapping every key to a single input combination (e.g. `""` = `"` and `"a` = `ä`), so I don't suffer from this particular problem, but that is of course not a general solution.

**Comment by Luapix** [comment]
I think the problem is simply that :

> Shortcuts in most programs fire when all required modifiers are present

If this is indeed the expected behavior in most programs, then this isn't a bug and should be closed. However, I don't think this is generally true (Ctrl+Tab is different from Ctrl+Shift+Tab after all), and I personally would expect shortcuts modifiers to be matched exactly instead, even if only for corner use cases such as mine.
Changing the keyboard layout is more of a workaround for the bug, rather than a solution. My personal solution was to simply disable the Ctrl + 0, 1, 2, etc. shortcuts entirely in the configuration.

**Comment by Aokromes** [comment]
this bug is still valid?

**Comment by Luapix** [comment]
I tested just now under version 1.9.8, and the bug as described initially seems to be gone.

Under an AZERTY layout on Windows, the Saved Messages shortcut (Ctrl+0) now activates only when pressing Ctrl+Shift+0 (reminder that inputting '0' requires pressing Shift under that layout). All other combinations (Ctrl+0, Ctrl+Alt+0 / AltGr+0, Ctrl+Alt+Shift+0 / AltGr+Shift+0) input the expected character (which allows for inputting 'À' in my extended layout as originally mentioned).

This issue can probably be closed as resolved.
