### ISSUE TITLE
[Question] How to set api_id and api_hash on Windows environment ?

### ISSUE THREAD

**Issue by alberto-fc** [telegramdesktop/tdesktop#6580]
Hi,

I can see on cmake compile instruction how to set the api keys:

`gyp/refresh.sh --api-id YOUR_API_ID --api-hash YOUR_API_HASH`

But I can't find way to do it in windows on the oficial instructions (officially):

https://github.com/telegramdesktop/tdesktop/blob/dev/docs/building-msvc.md

Thank you.

**Comment by RadRussianRus** [comment]
It's practically the same: `gyp\refresh.bat --api-id YOUR_API_ID --api-hash YOUR_API_HASH`. But yeah, I think that should be mentioned explicitly in docs.
