### ISSUE TITLE
Scrolling one unread message marks all as read

### ISSUE THREAD

**Issue by aNNiMON** [telegramdesktop/tdesktop#6582]
### Steps to reproduce
1. Open the chat or the channel with 10+ unread messages
2. Scroll down a little

### Expected behaviour
Only visible messages should be marked as read

### Actual behaviour
All messages are marked as read.

### Configuration
**Operating system:** Windows 7, Windows 10, Arch Linux

**Version of Telegram Desktop:** 1.8.8

**Used theme**: any

**Comment by JSBmanD** [comment]
I confirm the same behavior - Win10, Ubuntu 18.04, TG 1.8.8.

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/775
