### ISSUE TITLE
[Feature Request] Network Speed Upload Limitation Removal

### ISSUE THREAD

**Issue by TakuyaSama** [telegramdesktop/tdesktop#6583]
### Brief Explanation
Telegram Desktop limits the upload speed hugely.

### Solution I'd Like
Telegram Desktop should be able to use the full connection speed (600 symmetrical Mbps), not just the max observed by me, (about 20 Mbps).

### Alternatives
Removal of the upload speed limitation.

### Additional Context
I also observed that if i queue more than 1 file to upload, the upload speed increases slightly (i observed 10 Mbps when i was uploading 1 single file and 2x, up to 20 Mbps when i was uploading 2 files).

**Comment by foremtehan** [comment]
It planned on purpose, If they allow user to use all their upload bandwidth some of bad users uses telegram as data center and will upload everything in telegram.

**Comment by TakuyaSama** [comment]
@foremtehan 

> It planned on purpose, If they allow user to use all their upload bandwidth some of bad users uses telegram as data center and will upload everything in telegram.

Hmmm, i understand that point, but then, what reason is for Telegram to promote the cloud as a permanent cloud, without limit of files and a really high file size limit (1.5 GB)? It's more like they're limiting artificially the service via the technical side.

Greetings ^^.

**Comment by milankragujevic** [comment]
Why was this closed? It is an issue, it takes up to 5 minutes to upload a 100 KB file from Telegram Desktop, while on the same Internet connection, from Android, it uploads instantly. This has been happening for months.
