### ISSUE TITLE
Broken Link Line-Wrapping behaviour

### ISSUE THREAD

**Issue by NotAFile** [telegramdesktop/tdesktop#6584]
### Steps to reproduce
1.  View a long message with link on an affected platform

### Expected behaviour
link is displayed with correct wrapping

### Actual behaviour
![image](https://user-images.githubusercontent.com/5447747/65380117-72e07180-dcd4-11e9-9811-b440daaf2897.png)

### Configuration
**Operating system:** Fedora Linux 29, wayland

**Version of Telegram Desktop:** 1.8.8, flatpak commit dfa291688c38

**Used theme**: none/default

no relevant log output

**Comment by xvitaly** [comment]
Typical issue, related to updated Qt. Whole project must be rebuilt from sources against new version of Qt (even minor).

**Comment by WyRe** [comment]
Same issue on Arch Linux. The [official repos package](https://www.archlinux.org/packages/community/x86_64/telegram-desktop/) has not the issue, but it has other different issues like eventual spontaneous crashes.

Anyway contributors are now talking about this [in flathub repo](https://github.com/flathub/org.telegram.desktop/issues/92)

**Comment by Aokromes** [comment]
can you try on 1.9.1 beta?

**Comment by WyRe** [comment]
@Aokromes it is that version in flatpak?

**Comment by Aokromes** [comment]
it's to see if it's telegram bug or 3rd party bug.

**Comment by WyRe** [comment]
@Aokromes as I've said ... telegram 1.8.15 version from [official Arch repos](https://www.archlinux.org/packages/community/x86_64/telegram-desktop/) has not the issue, and also the people is talking about this issue in [flathub repo](https://github.com/flathub/org.telegram.desktop/issues/92)

**Comment by Aokromes** [comment]
so, flathub bug not telegram desktop?

**Comment by WyRe** [comment]
> so, flathub bug not telegram desktop?

I would say so

**Comment by xvitaly** [comment]
@Aokromes This is a known build issue due to Qt private API usage.

**Comment by WyRe** [comment]
I would say this is closed.
