### ISSUE TITLE
Inputed accent chars such as ', ^ and ~ are ignored by the telegram client

### ISSUE THREAD

**Issue by DiogoConstantino** [telegramdesktop/tdesktop#6585]
### Steps to reproduce
1. write á, or â, or ã, or à on the text input box
2. characters appear without accents.

### Expected behaviour
Telegram should write the accents the users are writing.

### Actual behaviour
Telegram displays characters withtout the accents

### Configuration
**Operating system:**
Ubuntu 18.04

**Version of Telegram Desktop:**
v 1.8.8

<details><summary><b>This is a recent regression but apparently common regression</b>:</summary>
This didn't happened previously with the package downloaded directly from the Telegram website, only on the snap package. Only had this regression with current version or maybe other very recent version.
</details>

**Comment by Aokromes** [comment]
#1041
