### ISSUE TITLE
Powertoys and Fancyzones not working with Telegram

### ISSUE THREAD

**Issue by JavierSegoviaCordoba** [telegramdesktop/tdesktop#6587]
Telegram is not working with Fancyzones for some reason.

https://github.com/microsoft/PowerToys

**Comment by Aokromes** [comment]
if you enable override winsnap it works. if that does the job for you, you can close this ticket.

**Comment by JavierSegoviaCordoba** [comment]
The problem is with shift + mouse, it is only working with the keyboard hotkeys.

**Comment by Aokromes** [comment]
i wonder if powertoys bug instead telegram bug:
https://github.com/microsoft/PowerToys/issues/227

**Comment by JavierSegoviaCordoba** [comment]
Yeah, maybe it is a Microsoft problem.

**Comment by Aokromes** [comment]
plz test on power toys 0.15.
https://www.neowin.net/news/microsoft-powertoys-015-focuses-on-quality-improvements

**Comment by Aokromes** [comment]
no answer after more than 3 months, closing, if you still have this bug plz update telegram desktop and power toys and try again and open a new ticket if it's still bugged.

**Comment by JavierSegoviaCordoba** [comment]
It is working, sorry I didn't read before.
