### ISSUE TITLE
Hide update button

### ISSUE THREAD

**Issue by roberth1990** [telegramdesktop/tdesktop#659]
Can there be created an option to hide the update button? When telegram is installed as root on linux it cannot be updated by clicking that button, and having it there flashing is distracting.

**Comment by jtojnar** [comment]
Just unclick the Update automatically checkbox in settings.

**Comment by ppparadox** [comment]
Why would you install it as root?

**Comment by roberth1990** [comment]
Because I like to use a packagemanager to add/remove/update it.

**Comment by jtojnar** [comment]
Like I wrote, that’s what “Update automatically” checkbox is for.

**Comment by roberth1990** [comment]
Yes I unchecked that it fixed the problem.

**Comment by jtojnar** [comment]
You can close this, then.
