### ISSUE TITLE
[Question] Telegram Build Failed

### ISSUE THREAD

**Issue by KiDisplayBlueScreen** [telegramdesktop/tdesktop#6590]
Windows 10 Environment
I do everything like https://github.com/telegramdesktop/tdesktop/blob/dev/docs/building-msvc.md

But in the last line when I call "gyp\refresh.bat --api-id 17349 --api-hash 344583e45741c457fe1862106095a5eb"

I get below error:
gyp: Variable python -c "print('5.6.2'.replace('.', '_'))" must expand to a string or list of strings; found a bytes
[ERROR] Failed generating for format: ninja
FAILED

What should I do now?

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/4980
