### ISSUE TITLE
[Mac] Tab-completing :joy: emoji inconsistent with behavior on windows/web platform.

### ISSUE THREAD

**Issue by Jonchun** [telegramdesktop/tdesktop#6591]
### Steps to reproduce
1. Type :jo and hit tab.
2. You will get 🇯🇴 instead of 😂 

### Expected behaviour
Not sure what intended behavior is. If you go by alphabetical order, 🇯🇴 is correct. However, 😂 is definitely a much more popular emoji.

### Actual behaviour
I get 🇯🇴 

### Configuration
**Operating system:**
MacOS 10.14.6

**Version of Telegram Desktop:**
5.7 (181196) Stable for MacOS

**Used theme**:
Default

**Comment by 23rd** [comment]
Sorry, you are using the Mac native client, not the Telegram Desktop.
https://github.com/telegramdesktop/tdesktop/issues/5921#issuecomment-483126605
