### ISSUE TITLE
GIF not sending

### ISSUE THREAD

**Issue by fireandfuel** [telegramdesktop/tdesktop#6592]
### Steps to reproduce
1. Open the Emoticon Panel, select the GIFS panel
2. Send GIF as message to a group or to to Telegram chat

### Expected behaviour
Telegram Desktop should send the GIF as message

### Actual behaviour
The loading indicator appears as overlay over the GIF, the GIF will NOT be send.
The GIF animation will be played, but the "sending" indicator doesn't turn into "send" indicator.

### Configuration
**Operating system:**
Windows 10 x64 Version 1903

**Version of Telegram Desktop:**
1.8.8

**Used theme**:
Own theme, based on a dark theme

**The bug can't be reproduced every time**

<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by wodim** [comment]
Looks like this, it's not clear to me if it's a problem with tdesktop or the server. It hasn't happened to me on Android at least. You can just send the very same gif again and it will go through okay

![image](https://user-images.githubusercontent.com/1001553/65585118-3b96ec80-df82-11e9-84a3-c166cac753ca.png)

**Comment by Yuubari** [comment]
Confirming this for 1.8.8 on Windows 10 as well. I tried using my HTTP proxy to work around this but it does not help. The Android sends GIFs fine.

**Comment by Brawl345** [comment]
Same problem in 1.8.8 and 1.8.9 on Windows 8.1.

Workaround: Send the GIF again and it will work. Right click the GIF that's not sending and delete the message. Faster than restarting TG imho.

**Comment by john-preston** [comment]
@Brawl345 Is it with saved GIFs or with GIFs search results?

**Comment by Brawl345** [comment]
@john-preston I've only tested saved GIFs. It's hard to replicate, it only happens sometimes, but often enough to be annoying.

**Comment by SkaveRat** [comment]
Can confirm for linux client, including the most recent update.

**Comment by tkuijer** [comment]
Still present for W10 X64 in 1.8.10

**Comment by Brawl345** [comment]
It's fixed for me on W8.1 x64 in 1.8.10
