### ISSUE TITLE
[Linux] Unable to type accents in vowels (áéíóú)

### ISSUE THREAD

**Issue by chenchix** [telegramdesktop/tdesktop#6594]
### Steps to reproduce
1. Try to type á é í ó ú

### Expected behaviour
Letter with accent is written in telegram desktop app

### Actual behaviour
Vowel without accent

### Configuration
**Operating system:**
Ubuntu 19.04

**Version of Telegram Desktop:**
1.8.7 beta
1.8.8 stable

**Used theme**:
Dark

<details><summary><b>Logs</b>:</summary>

</details>

**Comment by Aokromes** [comment]
#1041
