### ISSUE TITLE
[Feature Request] Rename sticker pack

### ISSUE THREAD

**Issue by phaux** [telegramdesktop/tdesktop#6597]
### Is your feature request related to a problem?
After you create a sticker pack using `/newpack` command of `@Stickers` bot you can set a name. There's no way to change that name after the pack is created.

### Describe the solution you'd like
New command `/rename` for Stickers bot.

### Describe alternatives you've considered
The only thing you can do is to create a completely new sticker pack AFAIK, which sucks because you can't use the same url as the previous one.

**Comment by RememberTheAir** [comment]
Unfortunately this isn't related to tdesktop. It's more an API issue since there is no method to rename a stickers pack. You should ask to the in-app support or on [Twitter](https://twitter.com/telegram)

**Comment by KonnikPahoni** [comment]
Hm this should definitely be implemented!

**Comment by DefectiveSoul** [comment]
Still not added.... :(
Maby then add ability to export and import whole stickerpacks (only those wich you created) ? So you could just change some packname var inside file inside archive with all those exported stickers

**Comment by RememberTheAir** [comment]
This feature is out of the scope of Telegram Desktop, someone should bring it to https://bugs.telegram.org (if there isn't one already)
