### ISSUE TITLE
Get double click when focus to another window.

### ISSUE THREAD

**Issue by flymanru** [telegramdesktop/tdesktop#6598]
### Steps to reproduce
1.  Focus to telegram window
2.  Focus to another window by one left click mouse
3.  Get double click

### Expected behaviour
One click = one click.

### Actual behaviour
When I focus to another window from telegram by one click I get double click but I didn't.
For example - set pause youtube video in chrome, chat in telegram, back to youtube video in chrome by one click and see how it transfer to full screen (as if I double clicked).

### Configuration
**Operating system:**
Windows 10Pro 18362.30

**Version of Telegram Desktop:**
Telegram 1.8.8

**Used theme**:
Night mode

**Comment by flymanru** [comment]
After program restart issue can be gone.

**Comment by Aokromes** [comment]
this bug is still valid?

**Comment by flymanru** [comment]
yes, but it's double click bug in windows 10 for different applications. Issue can be closed.
