### ISSUE TITLE
Add build instructions from the terminal

### ISSUE THREAD

**Issue by gim-** [telegramdesktop/tdesktop#660]
At this moment there is [inscructions on how to build this client through GUI of Qt Creator](https://github.com/telegramdesktop/tdesktop/blob/master/QTCREATOR.md). Though the problem with it is that you have to manually do many things through GUI, which is kind of weird to be honest, I've never seen something like this before. Usually it's considered to be a good practice to add the ability to build a program from the terminal so we can create scripts to do it automatically.

**Comment by auchri** [comment]
Feel free to create such instructions

**Comment by gim-** [comment]
Why would you close the issue and mark it as "invalid" then? Either way I'm not a developer of this project to provide others with build instructions, especially I'm not willing to invest my time and contribute after seeing how you handle issues.

**Comment by auchri** [comment]
It seems you are the only one who cares about building from the terminal and you did not create a pull request.
We are fine with the GUI way and we are also not willing to invest our time in such things.

**Comment by gim-** [comment]
I cared about this because I wanted to create a telegram-desktop package for GNU/Linux distribution I use, which is not as easily done without automation. You don't care and I don't either any more. We can end with that.
