### ISSUE TITLE
[Feature Request] Add filter for Current Downloads

### ISSUE THREAD

**Issue by justmic007** [telegramdesktop/tdesktop#6601]
### Is your feature request related to a problem?
I am downloading multiple files from our official channel but could not sort out the files am currently downloading

### Describe the solution you'd like
I will prefer you **add a button** to filter **current and pending** downloads from the list of files shared in the channel

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/6546 
https://github.com/telegramdesktop/tdesktop/issues/809
