### ISSUE TITLE
[Bug] No playback audio with videos

### ISSUE THREAD

**Issue by MarcAnt01** [telegramdesktop/tdesktop#6602]
### Steps to reproduce
1.  Play a video

### Expected behaviour
Have playback audio

### Actual behaviour
No playback audio, audio is fine for voice messages, video messages and calls

### Configuration
**Operating system:**
Windows 10 1903

**Version of Telegram Desktop:**
1.8.8 Microsoft Store

**Used theme**:

<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/5481

**Comment by MarcAnt01** [comment]
@Aokromes different operating system and there it seem to affect voice messages and audios, too, while in my case they are always fine

**Comment by Aokromes** [comment]
afaik voice notes bug was ios send voice notes issue, the rest, people reports windows there too.
