### ISSUE TITLE
[Feature Request] Video player skip some seconds when right/left arrow keys are pressed

### ISSUE THREAD

**Issue by ldeluigi** [telegramdesktop/tdesktop#6606]
### Is your feature request related to a problem?
No.

### Describe the solution you'd like
While playing any video in the __Media Viewer__ I'd like to be able to skip 5/10 or any amount near those of seconds by pressing the right key, and to rewind the same amount if pressing the left key.
Also the other two arrows could be used to navigate between videos or adjust the volume.

### Describe alternatives you've considered
Any other hotkey could be used to achieve the same thing, but it wouldn't be as user friendly as the the arrow keys are.

### Additional context
If needed, ask and I'll provide some, but I don't think they are necessary.

**Comment by john-preston** [comment]
@ldeluigi Left-right arrows already move through photos-videos there :(

**Comment by ldeluigi** [comment]
> @ldeluigi Left-right arrows already move through photos-videos there :(

Not in fullscreen mode, it seems.

**Comment by Aokromes** [comment]
he means left/right keys are used to browse between files on full screen mode.

**Comment by ldeluigi** [comment]
![image](https://user-images.githubusercontent.com/44567586/97079441-34626800-15f4-11eb-9b62-812fe0d2c0eb.png)


In this view (fullscreen) arrow keys do nothing. I'd expect instead to control progress (similar to youtube) with those. And maybe you can keep the possibility to go to the next video with Ctrl + Arrow.

**Comment by Aokromes** [comment]
> > lest make this generic for all multimedia shortcuts.
> 
> What does it means?

increase / decrease volume, advance / rewind on video/song, anything related to music or videos.

**Comment by bolocholo** [comment]
This is the most important feature I'd like Telegram to add. I'd really be very grateful.

**Comment by mylove1302** [comment]
I've been waiting for this feature for a long time !!

**Comment by vishwajeet1132** [comment]
This is a much required feature. As we can seek the video on telegram Mobile version (like YT controls) but there is no way to this in telegram Desktop.

**Comment by cencuansen** [comment]
this feature has not been supported so far! but why? I can't understand.

**Comment by john-preston** [comment]
@cencuansen Because they switch between media.

**Comment by ldeluigi** [comment]
> @cencuansen Because they switch between media.

this isn't a reason, it's just how things go at the moment! the behvaiour of the arrows should be changed in relation to the typical user expectations (a very important aspect of user experience)

**Comment by Aokromes** [comment]
> > @cencuansen Because they switch between media.
> 
> this isn't a reason, it's just how things go at the moment! the behvaiour of the arrows should be changed in relation to the typical user expectations (a very important aspect of user experience)

well, my "user expectation" is when i have multiple files next/previous keys changes of file.

**Comment by ldeluigi** [comment]
What about full screen mode? Arrows do nothing there atm

**Comment by RememberTheAir** [comment]
> well, my "user expectation" is when i have multiple files next/previous keys changes of file for example on xnview.

I believe most people will expect the video to seek some seconds. This is a common behavior among most web players and some popular media players (vlc, mpv)

**Comment by john-preston** [comment]
@ldeluigi Fullscreen mode indeed can enable this.

@RememberTheAir I understand that this is really expected, but this is a real problem - you can't just handle the arrows differently for videos. You move through the media by arrows, through photos, and suddenly among them one video occurs - you can't just get trapped inside it without a way to continue to move through the media.

**Comment by john-preston** [comment]
@AndrewBogdanovTSS This can be done, although everyone expects arrow keys, like youtube, vlc etc. This could be taught if such actions existed as buttons in the media player controls as well with shortcut tooltips.

**Comment by AndrewBogdanovTSS** [comment]
Heaving a bit different key is always better than don't have any key at all, so I would rather go with a more specific key if that is easier to implement, after all, Telegram is not only a video player so no reason to adhere to similarities in youtube or vlc

**Comment by ldeluigi** [comment]
Nevertheless, I'd be already happy if we get arrow skip in full screen mode.

_I hope that it won't be a problem if, in the future, there will be a different behavior for arrow keys in full screen/normal mode (that is, skip seconds in full screen is just arrow click while it's ctrl+arrows in normal screen mode)_

**Comment by Aokromes** [comment]
> > well, my "user expectation" is when i have multiple files next/previous keys changes of file for example on xnview.
> 
> I believe most people will expect the video to seek some seconds. This is a common behavior among most web players and some popular media players (vlc, mpv)

well, telegram aint a web player, the video player of telegram is more a multimedia viewer like xnview, irfanview, windows photos app, and there, the right / left keys changes to next / previous file.

**Comment by cencuansen** [comment]
seeking forward or seeking rewind has been added to telegram on mobile version recently.

**Comment by ILoveSkilledCoders** [comment]
This is very frustrating. 

I'm going to have to download the video & then watch it in VLC. I can't not be able to go back & forth on the video as I'm taking notes.

This is when the video pops out of the full screen. I can't stand full screen b/c I don't have access to my computer when it's in full screen.

Thanks
