### ISSUE TITLE
[BUG] Does not recognize IBus switch between Bengali and English after updating ibus to 1.5.20-5.fc30

### ISSUE THREAD

**Issue by TH3L0N3C0D3R** [telegramdesktop/tdesktop#6608]
### Steps to reproduce
1. Update ibus to 1.5.20-5.fc30 x86_64 in Fedora 30 (Gnome) system.
2. Open Telegram Desktop
3. Switch input language to any of these Bengali keyboard layout (CTRL + Space)
 - Bengali Avro Layout (https://github.com/sarim/ibus-avro)
 - Openbangla Keyboard (https://github.com/OpenBangla/OpenBangla-Keyboard)
 - Probhat Layout
4. Type anything in Telegram message box.

### Expected behaviour
Telegram should recognize switch from English to Bengali (CTRL + Space) IBus input method and let me write in Bengali.

### Actual behaviour
It always types in English.

### Configuration
**Operating system:** Fedora 30 x86_64 Gnome v3.32.2

**Version of Telegram Desktop:** 1.8.9

**Used theme**: Default (Classic)

**Note**: `QT_IM_MODULE=ibus` trick did not work for me.

**Comment by Aokromes** [comment]
generic bug.
https://github.com/telegramdesktop/tdesktop/issues/2013
