### ISSUE TITLE
Italic text is simply slanted

### ISSUE THREAD

**Issue by wodim** [telegramdesktop/tdesktop#6609]
Windows 10, Telegram 1.8.9, italic text in messages looks like this:

![image](https://user-images.githubusercontent.com/1001553/65821952-a4a98900-e23c-11e9-9382-5847068b4a0c.png)

Probably because in [tdesktop/Telegram/Resources/fonts/](https://github.com/telegramdesktop/tdesktop/tree/dev/Telegram/Resources/fonts) there are no italic fonts. Could these be included?

**Comment by Aokromes** [comment]
maybe fonts needs to be updated from https://github.com/google/fonts/tree/master/apache/opensans

**Comment by wodim** [comment]
This was fixed recently. Italic fonts were added. Now it looks good:

![image](https://user-images.githubusercontent.com/1001553/73202600-a6785000-413b-11ea-914c-d4f1d2c68b26.png)
