### ISSUE TITLE
macOS version numbers of version 1.8.9 broken

### ISSUE THREAD

**Issue by core-code** [telegramdesktop/tdesktop#6610]
### Steps to reproduce
1. download version 1.8.9 for macOS here https://github.com/telegramdesktop/tdesktop/releases/download/v1.8.9/tsetup.1.8.9.dmg
2. extract the app and inspect its version number with QuickLook or ColumnView

### Expected behaviour
i expect to see version number 1.8.9 for version 1.8.9

### Actual behaviour
it claims to be version 1.8.8

### Configuration
macOS

**Version of Telegram Desktop:**
1.8.9

someone has obviously forgot to update the version number string for this release.
info: the bug is causes by faulty *CFBundleShortVersionString* and *CFBundleVersion* entries in your *Info.plist* file

while you are at fixing bugs in your Info.plist, please remove the *CFBundleGetInfoString* entry from your Info.plist. this has been deprecated for more than 10 years (!) and actually makes it impossible to inspect the version number of the app using the 'Get Info' view, as mentioned above you have to us  QuickLook or ColumnView.

<img width="715" alt="Screenshot 2019-09-29 at 18 35 58" src="https://user-images.githubusercontent.com/1261954/65835580-65387680-e2e8-11e9-9c48-fe0607201270.png">

**Comment by john-preston** [comment]
Should be fine in 1.8.10.

**Comment by core-code** [comment]
thanks
