### ISSUE TITLE
Thumbs up is to large & missing name from poster

### ISSUE THREAD

**Issue by steffanhalv** [telegramdesktop/tdesktop#6615]
### Steps to reproduce
1. Write single thumbs up
2. Post it
3. ...

### Expected behaviour
It should just appear normaly as all other inputs, we usually use thumbs up to know if people is joining for an event or not (very often) and this was very easy to follow up before when it was small size & you could see the name. Now you have to scroll forever & click on each profile image to see their name. So we now have to ask people to add a dot sign behind emoijs to prevent this which is not prefered & not everyone understand this.
### Actual behaviour
It takes the whole screen and hides the name of the poster
### Configuration
**Operating system:**
all
**Version of Telegram Desktop:**
5.7 (181196)
**Used theme**:
default
<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by RememberTheAir** [comment]
Settings -> "Chat settings" -> disable "large emojis"
