### ISSUE TITLE
Opening chat group marks all messages as read, even unseen messages

### ISSUE THREAD

**Issue by garmilw** [telegramdesktop/tdesktop#6616]
Problem: opening  a chat group in Telegram Desktop on Windows automatically marks all messages in that chat group as being read, even unseen messages.

In the Android and iOS versions of Telegram, opening a chat group shows one screen full of messages.  If there are more messages than can be displayed, the unseen messages remain marked as unread.  Example, if I open SFW-Chat and it has 25 unread messages, the app displays the first 5 messages (marking them as read) and leaves the other 20 messages as unread.

In the Windows Telegram Desktop app, opening SFW-Chat marks all 25 messages as read as soon as the first 5 messages are displayed.   This is a significant behavior change from the Android and iOS versions and means that you can not tab out of the group without losing your place on what you have and have not seen yet.

I would like to see the Windows Telegram Desktop app behave the same way as the Android and iOS apps.  Only mark those messages seen as read, leave all other messages in the group as unread so you can read part of a group, close it, and come back later to pick up where you left off.

This problem is seen in the Windows Telegram desktop app and the web Telegram app (web.telegram.com).  I do not know if the two occurrences of this problem are related.

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/775
