### ISSUE TITLE
Smiley window disappears while using Trackpoint scroll

### ISSUE THREAD

**Issue by ojura** [telegramdesktop/tdesktop#662]
IBM thinkpads come with a Synaptics driver that enables scrolling with the middle (blue) mouse button. When that button is pressed, the mouse cursor icon changes to a different one which indicates that the scrolling functionality has been enabled. However, Telegram thinks that mouse is no longer hovering the smiley choice window and closes it.

Tested under Windows 8, Telegram 0.8.4.

**Comment by auchri** [comment]
Is this still the case? If yes, reopen the issue

**Comment by juraj5** [comment]
Yeah, this is still an issue for me.

**Comment by mhverbakel** [comment]
Same issue here. Windows 7, Telegram 0.8.52. The issue is with the built in touchpad, when scrolling using two fingers. At first, the scrolling seems to work, but then the window suddenly closes. By stopping, the mouse position 'returns', and thus the window stays open.

**Comment by Tercus** [comment]
I have that problem on version 0.9.49 of the desktop App and Windows 7. Whenever I scroll using the scroll area on the right side of the touchpad, the mousecursor changes to the scroll-indicator and the emoji/sticker window closes.

**Comment by Gollam** [comment]
Same issue here, Windows 10, lenovo laptop. The window disappears with the right side scrolling of the touchpad, and also with double finger gesture scrolling.

**Comment by Aokromes** [comment]
this bug is still valid on 1.9.8?

**Comment by mhverbakel** [comment]
Nope, I can't reproduce it at least.
