### ISSUE TITLE
Membership link opens in browser!

### ISSUE THREAD

**Issue by neesti** [telegramdesktop/tdesktop#6622]
Hello.
I use Telegram desktop 1.8.11 on Linux mint 19.2 with cinnamon desktop.
When I click on a group membership link, it opens in Firefox instead f opening it in a Telegram desktop!

**Comment by john-preston** [comment]
@neesti Give me please an example.

**Comment by neesti** [comment]
https://t.me/joinchat/ED7S31C3ziINx-_soSy_2g‌

**Comment by neesti** [comment]
I checked this bug in Windows version of Telegram, There is in there too.

**Comment by john-preston** [comment]
@neesti Yes, indeed, all internal links are broken :(
