### ISSUE TITLE
release 1.8.11: 32 bit linux binary is missing

### ISSUE THREAD

**Issue by lemmy04** [telegramdesktop/tdesktop#6623]
### Steps to reproduce
1. try downloading the 32bit version of telegram desktop 1.8.11 for linux

### Expected behaviour
there should be a 32bit linux binary - or at least an announcement that there isnt.

### Actual behaviour
there is no 32bit binary of telegram desktop 1.8.11 available for download

### Configuration
any web browser, any OS

**Comment by john-preston** [comment]
@lemmy04 Yeah, thanks, didn't build it yet.

**Comment by lemmy04** [comment]
it's there now :)

**Comment by john-preston** [comment]
@lemmy04 It shouldn't be 😳

**Comment by lemmy04** [comment]
well, all i can see is that there's both binaries now...
https://build.opensuse.org/package/show/home:lemmy04/Telegram

**Comment by lemmy04** [comment]
ok me blind. that's 1.8.10.

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/releases/tag/v1.8.12
