### ISSUE TITLE
[Feature Request] Allow choosing 24-hour time with English language

### ISSUE THREAD

**Issue by Maia-Everett** [telegramdesktop/tdesktop#6624]
### Is your feature request related to a problem?
I use the English language in Telegram, but I live in a country that uses 24-hour time. Telegram used to display 24-hour time for me, but recently switched to the AM/PM format.

### Describe the solution you'd like
I would like the old behavior with 24-hour time restored, or an ability to switch between 12-hour and 24-hour time display in application settings.

### Describe alternatives you've considered
I have my system locale set to display 24-hour time, but Telegram ignores this.

### Additional context
None.

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/1920
