### ISSUE TITLE
[Question] what's involved in building Telegram from source on linux...

### ISSUE THREAD

**Issue by lemmy04** [telegramdesktop/tdesktop#6625]
...when I want to use as much as possible of the libraries provided by my linux distribution?

**Comment by Johnnynator** [comment]
Having fun patching the build system and some of the source code, official supported is only what is mentioned in the [cmake guide](https://github.com/telegramdesktop/tdesktop/blob/dev/docs/building-cmake.md) which statically links quite a lot libraries.

**Comment by lemmy04** [comment]
ouch. sounds like fun. would you like pull requests if i get to a point where the client actually builds using system libs on more than one linux distribution?

**Comment by Aokromes** [comment]
preston is who must answer that :P but i am sure if you make PR allowing to choose system libs or old style i am sure he will allow that.

**Comment by john-preston** [comment]
@lemmy04 You can push a separate building instruction file with that, current one is the one that is used for the official builds.

Also you can start by looking on patches for flathub build or downstream package maintainer builds that already build tdesktop with system libraries.

**Comment by xvitaly** [comment]
> ...when I want to use as much as possible of the libraries provided by my linux distribution?

Look at [this](https://github.com/rpmfusion/telegram-desktop/blob/master/telegram-desktop-build-fixes.patch).

**Comment by beholders-eye** [comment]
this only works for a RPM based distro and it seems to remove features, I mean, it disables a lot of what makes Telegram great.

**Comment by xvitaly** [comment]
> this only works for a RPM based distro

Yes, because I'm Fedora maintainer and don't care about other distributions.

> I mean, it disables a lot of what makes Telegram great.

Out patch disable only three features:
1. updater, because GNU/Linux distributions use repositories to deliver updates to end users;
2. crash reporter, because on Fedora we use internal crash reporter - abrt;
3. generating of shortcuts and mime-handlers, because we already has them in package.

**Comment by beholders-eye** [comment]
I thought, by roughly reading the patch, that it also removed rlottie and other things. If not, then I apologize for my rash question, it is actually a great help!

**Comment by xvitaly** [comment]
> I thought, by roughly reading the patch, that it also removed rlottie and other things

We removed all bundled libraries to use packaged versions from Fedora repositories.

**Comment by ilya-fedin** [comment]
DESKTOP_APP_USE_PACKAGED=ON
