### ISSUE TITLE
Can't type Korean in to telegram desktop with ibus

### ISSUE THREAD

**Issue by SJang1** [telegramdesktop/tdesktop#6627]
### Steps to reproduce
1. use ibus and add korean as input
2. install/open telegram desktop
3. Try to type in korean

### Expected behaviour
Just works with no issue and can type in Korean.

### Actual behaviour
Even on korean mode, it inputs english.
Switching korean/english mode doesn't work if I am on telegram.

### Configuration
**Operating system:** Fedora 31(now on beta)

**Version of Telegram Desktop:** 1.8.11 from snap store or telegram.org both

**Used theme**:default

<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/2013 generic bug
