### ISSUE TITLE
Clicking on post link open a browser

### ISSUE THREAD

**Issue by nikitasius** [telegramdesktop/tdesktop#6628]
### Steps to reproduce
1. Get a post link `https://t.me/example/123`
2. Paste in chat
3. Click on it
4. it will open a browser instead of opening message in UI

### Expected behaviour
Show a post in telegram's UI

### Actual behaviour
It calls browser to open a weblink

### Configuration
**Operating system:**
`Linux pentagon 4.9.0-11-amd64 #1 SMP Debian 4.9.189-3+deb9u1 (2019-09-20) x86_64 GNU/Linux`
**Version of Telegram Desktop:**
1.8.11
**Used theme**:
Dark

<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by RememberTheAir** [comment]
Duplicate and fixed with 1.8.12
