### ISSUE TITLE
"Full" version history is not up to date

### ISSUE THREAD

**Issue by teo1978** [telegramdesktop/tdesktop#6630]
![image](https://user-images.githubusercontent.com/542107/66050098-d8cac580-e52c-11e9-848f-9f906730099b.png)

![image](https://user-images.githubusercontent.com/542107/66050113-de281000-e52c-11e9-9826-cd12f86da3a7.png)

**Comment by weaver299** [comment]
Updates are also very frequent sometimes, and I run TG Desktop on multiple computers so it's nagging me to update constantly... and in the settings there's an opt-in for beta versions which I have turned off... does that setting even do anything?  </rant>

**Comment by MasterGroosha** [comment]
@weaver299 all recent releases were "stable" ones, that's why it constantly prompted you to update. Normally stable updates don't come as often though.

![изображение](https://user-images.githubusercontent.com/2780044/66103223-c2207f00-e5bd-11e9-9aa0-06f456aea070.png)

**Comment by john-preston** [comment]
@weaver299 Sorry I had to release a lot of updates in several days. I'll have to release at least one more :( But I hope then it'll be at last stable for some time.

**Comment by teo1978** [comment]
Still incomplete, 1.8.11 isn't mentioned

**Comment by teo1978** [comment]
And now a 1.8.13 has come out and it's not mentioned either.

Are you maintaining the version history by hand??

**Comment by john-preston** [comment]
@teo1978 Yes, the one on site. Because it should list only significant updates, that have some major changes. I'll add one last bugfix version just to avoid confusion.

**Comment by teo1978** [comment]
I see. Then maybe the message shouldn't say "_full_ version history".

And/or, if there's a more detailed changelog somewhere else, maybe a link to it from the version history page could be nice.

**Comment by Aokromes** [comment]
> I see. Then maybe the message shouldn't say "_full_ version history".
> 
> And/or, if there's a more detailed changelog somewhere else, maybe a link to it from the version history page could be nice.

if you want real full history: https://github.com/telegramdesktop/tdesktop/commits/dev

**Comment by MasterGroosha** [comment]
Or this one.
https://github.com/telegramdesktop/tdesktop/blob/dev/changelog.txt

@john-preston is it automatically updated?

**Comment by john-preston** [comment]
@MasterGroosha This one is written by hand as a "source" for github releases page messages.
