### ISSUE TITLE
[Feature Request] Chat folders or some sort of grouping

### ISSUE THREAD

**Issue by FelipeGDC** [telegramdesktop/tdesktop#6631]
### Is your feature request related to a problem?
Nope, as of now, there's no differentiation of any type of chat that you might have, you have a list of every chat/channel/group that you are currently in, and you have an archived list of the one you wish not to see.

It would be nice to have some sort of way of grouping chats in any way, so to have say all family chats grouped together, or college chats/groups together.

### Describe the solution you'd like
Some way to create folders that might collapse or expand where you can put any type of chat you wish? 

### Describe alternatives you've considered
Any type of separation would be nice, let it be folders, or tabs, or static categories. At worst, some sort of forced organization where all simple chats are first, then groups and then channels would be cool.

### Additional context
Not much else to add.

**Comment by CarlosLopezES** [comment]
+1 to this request. For example, now in Telegram are many offers and discounts channels, so this feature will be nice to avoid miss friends chats.

If is impossible to be implemented globally across Telegram, maybe with local storage will be enough to do the trick.

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/1107
