### ISSUE TITLE
In 1.8.12 key “-scale ...” seems to be broken

### ISSUE THREAD

**Issue by Twilightssuperb** [telegramdesktop/tdesktop#6632]
I used to launch Telegram Desktop with label (.lnk file) and key “-scale ...” inside it. All was good (e.g., in 1.8.10) till today I've just launched 1.8.12... Key doesn't work. Even when I created new label for Telegram.exe.

**Comment by john-preston** [comment]
@Twilightssuperb which value is not working exactly?

**Comment by john-preston** [comment]
Is it below 100?

**Comment by RememberTheAir** [comment]
@john-preston I can confirm it doesn't work with values < 100, but with larger ones it works. Windows 10

**Comment by Twilightssuperb** [comment]
> Is it below 100?

Yes, argument -scale 80 doesn't work. Thx for fix and 1.8.13 release. 🤝
