### ISSUE TITLE
[Feature Request] Button for manually checking for updates

### ISSUE THREAD

**Issue by nop144d** [telegramdesktop/tdesktop#6633]
### Is your feature request related to a problem?
I'm running two instances of the desktop app, one is upgraded to the latest version the other didn't yet.

### Describe the solution you'd like
A refresh-like button near the "Version x.y.z" text at the bottom of the main menu for checking/forcing the upgrade.

### Additional context
Something like this, but not that ugly.
![tdesktop-check-updates](https://user-images.githubusercontent.com/11941221/66064630-d0878000-e556-11e9-8fa5-bc60538462d0.png)

**Comment by Aokromes** [comment]
go settings->advanced->check for updates.

**Comment by nop144d** [comment]
Thanks for pointing to the "setting", however wouldn't it be nice to have to not hide it in settings and make it more visible?
