### ISSUE TITLE
strikethrough is lost when quoting

### ISSUE THREAD

**Issue by qqrm** [telegramdesktop/tdesktop#6637]
### Steps to reproduce
1. Send message with strikethrough 
2. quote
3. strikethrough  lost

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

### Configuration
**Operating system:**
win 10 x64

**Version of Telegram Desktop:**
1.8.12

**Used theme**:
![Annotation 2019-10-03 003317](https://user-images.githubusercontent.com/4681325/66083695-85c93080-e575-11e9-9cf7-b43631f47a1d.png)

<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by MasterGroosha** [comment]
This is the same issue as #6567 
Basically any formatting is missing in message preview during reply.
