### ISSUE TITLE
[Feature Request] Adding more interface scales (75%, 90%, 175%, 225%, 275%)

### ISSUE THREAD

**Issue by dikeyfd** [telegramdesktop/tdesktop#6638]
### Is your feature request related to a problem?
I have 13" notebook with UHD+ matrix 3200x1800.
And using scale 150% symbols are small and 200% scale symbols are big.

### Describe the solution you'd like
I have 2 variants of solutions:
1. Adding more scales for example 75%, 90%, 175%, 225%, 275% or more flex tuning scale by using scaling step by 10% and from 50% to 300%.

2. Adding option choicing font name, weight and size.

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/commit/47910b2ae180b6429adafef13ebf97cb75ad9dca
