### ISSUE TITLE
TDesktop freezes after few minutes of start

### ISSUE THREAD

**Issue by IRGC** [telegramdesktop/tdesktop#6639]
not sure its a bug but the recent versions are not working properly on my Win7  , it freezes and have the pointer show loading when Telegram window is open. 
anyone else experiencing same behaviour or just my pc has issue?

**Comment by Aokromes** [comment]
maybe https://github.com/telegramdesktop/tdesktop/commit/3779ad46caf47acdb69f5d602aa0522bd3a314c8

**Comment by Aokromes** [comment]
@IRGC can you test on at least 1.8.13?

**Comment by IRGC** [comment]
@Aokromes i no longer have this problem, i think it was my computer issue.
thanks for reply.
