### ISSUE TITLE
Chat text deleted after closing and reopening

### ISSUE THREAD

**Issue by mbaldassarri** [telegramdesktop/tdesktop#664]
Hello! Let me explain the following scenario:
If I send a message to a person or a group and the network is switched off,  the text remains visible in the chat (and this is obviously normal).
Then I close the app (maybe I must reboot the OS) and once I've turned the network on (i.e. Wi-fi) i re-open it, but the message is no longer visible, it is completelly lost.
It could happen when somebody is on the train or on other mobility state: the connection could get lost while the person sends a message (maybe a big string), he / she have to rewrite it once the network operates again. Thank you.

I'm using Ubuntu distribution (Xubuntu 14.10)

**Comment by RyuzakiKK** [comment]
Same here, if I send a message when the network isn't available, and before it returns I close telegram, I lose the sent message.
I think we need a cache with the unsent messages, so in this way telegram can try to re-send them even after someone close the program.

I'm using Linux too.

**Comment by Aokromes** [comment]
this bug is still valid?

**Comment by Aokromes** [comment]
poke.

**Comment by Aokromes** [comment]
no answer after more than 1 month, if this bug is still valid open a new ticket using updated telegram version downloaded from releases tab.
