### ISSUE TITLE
[Feature Request] AutoLock Time

### ISSUE THREAD

**Issue by banghasan** [telegramdesktop/tdesktop#6640]
### Is your feature request related to a problem?
I need to set autolock to active after certain time, eg after 15 minutes. But Telegram only give option to autolock afer 1 minute, 5 minutes, 1 hour, and 5 hours

![autolock](https://user-images.githubusercontent.com/5436959/66126521-d4c5a300-e613-11e9-8acc-3d9bc99c9fbd.png)

### Describe the solution you'd like
I'd like you to add more option for autolock time. Eg after 15 minutes, after 30 minutes

### Describe alternatives you've considered
As an alternative, you could also make it possible for user to input custom time for autolock.

**Comment by BrainNull** [comment]
I need similar option for muting chats/channels/dialogs

> ### Is your feature request related to a problem?
> I need to set autolock to active after certain time, eg after 15 minutes. But Telegram only give option to autolock afer 1 minute, 5 minutes, 1 hour, and 5 hours
> 
> ![autolock](https://user-images.githubusercontent.com/5436959/66126521-d4c5a300-e613-11e9-8acc-3d9bc99c9fbd.png)
> 
> ### Describe the solution you'd like
> I'd like you to add more option for autolock time. Eg after 15 minutes, after 30 minutes
> 
> ### Describe alternatives you've considered
> As an alternative, you could also make it possible for user to input custom time for autolock.

**Comment by Aokromes** [comment]
1/5/15/30/1h/2h/3h/6h/12h better imho

**Comment by kirsan31** [comment]
Still actual.

**Comment by banghasan** [comment]
Still waiting for an update for this feature

**Comment by banghasan** [comment]
When will this feature be implemented? 😨

**Comment by john-preston** [comment]
Closed by b3622b4

Should appear in the next release.
