### ISSUE TITLE
cannot read text on bot-generated 6 emoji buttons under a video

### ISSUE THREAD

**Issue by Mithgol** [telegramdesktop/tdesktop#6643]
### Steps to reproduce
1. Record a vertical 4K video (2160×3840). It is likely that any other video with the same aspect ratio (9:16) can also be used to reproduce the issue.
2. Open Telegram on Android.
3. Save the video in “Saved messages” and add a text caption.
4. Forward the video to the LikeBot https://t.me/like (“A cool bot to create posts with emoji-based like buttons”).
5. Send a text message to the same bot with the following 6 emoji: 👍🤔👎😍🤬☀️
6. The bot responds with a post preview that contains the same video, the same caption and the 6 emoji buttons. It also provides another button titled “Publish”.
7. Click on the latter button (“Publish”) and choose a channel where you are permitted to post.
8. Visit the channel and confirm that the video and the caption and the buttons are all visible and that LikeBot counts the clicks on the buttons.
9. Close Telegram on Android.
10. Use Telegram Desktop on Windows to visit the same channel.

### Expected behaviour
Text should be readable on the 6 buttons, including emoji and the possible following click counter.

Example: https://t.me/ReadMithgol/66 on Android.

![(screenshot)](https://cloudflare-ipfs.com/ipfs/QmfMfjJmxXW22m61ZvEUFQoqV5ZhrYpukoJ1oArbKsHC1F/emojiButtonsAndroid.jpg)

### Actual behaviour
Cannot read text on bot-generated 6 emoji buttons under a video.

The text is replaced by “…” entirely.

Example: https://t.me/ReadMithgol/66 in Telegram Desktop on Windows.

![(screenshot)](https://cloudflare-ipfs.com/ipfs/QmfMfjJmxXW22m61ZvEUFQoqV5ZhrYpukoJ1oArbKsHC1F/emojiButtonsWindows.png)

### Configuration
**Operating system:** Windows 7 Professional, 64 bit, with Service Pack 1.

**Version of Telegram Desktop:** 1.8.13, stable.

**Used theme:** not sure.

**Note:** a very similar issue (#3593) was ignored in the past.

**Comment by Mithgol** [comment]
This issue has not been resolved.

**Comment by joshcoales** [comment]
Has not been resolved
