### ISSUE TITLE
Fullscreen outgoing messages are on wrong side

### ISSUE THREAD

**Issue by Simon-Laux** [telegramdesktop/tdesktop#6644]
### Steps to reproduce
1. Go from normal window into fullscreen window

### Expected behaviour
Outgoing messages should be still on the **right** side.

### Actual behaviour
Outgoing messages are on the **left** side.

### Configuration

**Version of Telegram Desktop:** 1.8.13

**Comment by RememberTheAir** [comment]
Settings -> chat -> uncheck the "adaptive layout" option

**Comment by Simon-Laux** [comment]
So that is actually a feature :eyes: ?
That setting only appears in full-screen, that needs to be said too.
