### ISSUE TITLE
Paste text doesn't work under Wayland (not XWayland)

### ISSUE THREAD

**Issue by RussianNeuroMancer** [telegramdesktop/tdesktop#6645]
### Steps to reproduce
1. Install Ubuntu 19.10, install Telegram Desktop from repository, install qtwayland5 and libqt5waylandclient5 packages.
2. Login into Wayland session on login screen.
3. Launch Telegram like this `QT_QPA_PLATFORM=wayland telegram-desktop` and try to paste text from clipboard.

### Expected behaviour
Paste text from clipboard works, just like with launching telegram-desktop without QT_QPA_PLATFORM=wayland (in this case it running under XWayland in Wayland session).

### Actual behaviour
Nothing happens, paste from clipboard doesn't work.

### Configuration
**Operating system:** Ubuntu 19.10 aarch64
**Version of Telegram Desktop:** 1.8.8
**Version of Qt:** 5.12.4
**Used theme**: dark theme

I have to add that using `QT_QPA_PLATFORM=wayland` is necessary for usage on laptops with HiDPI displays, because in case of HiDPI displays using Gnome Shell Wayland session with enabled fraction scaling is preferred option as it implement most polished HiDPI scaling currently available in GNU/Linux. Running Telegram under Xwayland (which is current Qt default) on setup with enabled fractional scaling makes Telegram window content look blurry and hardly readable, which is why I have to launch Telegram with `QT_QPA_PLATFORM=wayland`

**Comment by makarov-roman** [comment]
fedora 31, wayland. Bug is reproducible on ru keyboard layout. en is working good.

**Comment by makarov-roman** [comment]
For those who struggling with this. You can make all your QT apps use XWayland:

`QT_QPA_PLATFORM=xcb`
Add this to /etc/environment file, restart

**Comment by ilya-fedin** [comment]
https://bugreports.qt.io/browse/QTBUG-66497
