### ISSUE TITLE
The window of telegram desktop sometimes keeps flashing on OSX

### ISSUE THREAD

**Issue by ATShiTou** [telegramdesktop/tdesktop#6646]
### Steps to reproduce
I can not reproduce it.

### Expected behaviour
The window of telegram desktop sometimes keeps flashing on OSX.

### Configuration
**Operating system:**
OSX 10.14.5

**Version of Telegram Desktop:**
1.8.2
**Used theme**:
default

**Comment by 4unkur** [comment]
I have noticed that the flashing appears after the computer went to sleep and woke up.  

I recorded a screencast of how it looks like: https://youtu.be/E5XFTNafrWE

Telegram Desktop 1.8.15

macOs 10.15.2

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/5963 ?

**Comment by 4unkur** [comment]
@Aokromes yep, it's the same issue. Can be closed as duplicate.  
Installing Telegram Mac app from AppStore is not the solution as I have both installed and use them both for different accounts: 1 for work, 2nd personal. I keep personal closed on my work
