### ISSUE TITLE
TDesktop 1.8.13 crash on xubuntu 18.04

### ISSUE THREAD

**Issue by user38192** [telegramdesktop/tdesktop#6648]
Telegram Desktop 1.8.13 (installed from snapcraft) crash on xubuntu 18.04.3 (kernel 5.0.0-29-generic #31~18.04.1-Ubuntu SMP ) several times a day 
![2](https://user-images.githubusercontent.com/55229344/66254249-51739100-e77c-11e9-8124-4932bb530c95.png)

**Comment by MikeMilligan** [comment]
I'm having the same problem with this version on Windows 7. First time my Telegram crashes in about 2 years of using it.

![telegram](https://user-images.githubusercontent.com/16447558/66262208-083a3600-e7aa-11e9-9391-95024e725f70.png)

The log doesn't seem to show much but I'm including it anyway: 
[telegram_log.txt](https://github.com/telegramdesktop/tdesktop/files/3693798/telegram_log.txt)

**Comment by john-preston** [comment]
Does it happen when you enter something like ":a" (or other letters after ":") in text field? @user38192 @MikeMilligan

**Comment by user38192** [comment]
> Does it happen when you enter something like ":a" (or other letters after ":") in text field? @user38192 @MikeMilligan

I think no, almost always when telegram crash it be minimized on tray, no active chatting

**Comment by MikeMilligan** [comment]
> 
> 
> Does it happen when you enter something like ":a" (or other letters after ":") in text field? @user38192 @MikeMilligan
I think so yes. But I couldn't find the steps to reproduce the crashes, most of the times it worked just fine.

I went back to version 1.8.11 after my post and no more crashes since then.

**Comment by john-preston** [comment]
@MikeMilligan Can you please check 1.8.15? It should be out already, I hope it fixes that crash.

**Comment by user38192** [comment]
Telegram 1.8.15 also crash, now i listened music and chatting in telegram and it crashed((

**Comment by Aokromes** [comment]
@user38192 can you start telegram with gdb to get one crashlog since it looks crash handler fails to you?

**Comment by user38192** [comment]
> @user38192 can you start telegram with gdb to get one crashlog since it looks crash handler fails to you?

i got a error when i start gdb
1) sudo /usr/bin/gdb
2)(gdb) attach 23102 
and get
`Attaching to process 23102
[New LWP 23319]
[New LWP 23320]
[New LWP 23321]
[New LWP 23331]
[New LWP 23332]
[New LWP 23333]
[New LWP 23335]
[New LWP 23338]
[New LWP 23340]
[New LWP 23341]
[New LWP 23372]
[New LWP 23373]
[New LWP 23374]
[New LWP 23375]
[New LWP 23385]
[New LWP 23543]
warning: Unable to find libthread_db matching inferior's thread library, thread debugging will not be available.
warning: Unable to find libthread_db matching inferior's thread library, thread debugging will not be available.
0x00007fe2eb55a74d in poll () from target:/lib/x86_64-linux-gnu/libc.so.6
`

**Comment by Aokromes** [comment]
simply do gdb ./Telegram

**Comment by user38192** [comment]
> simply do gdb ./Telegram

i got ./Telegram: No such file or directory
(i installed telegram from snap, /snap/telegram-desktop/current/bin) 

When i try 
gdb /snap/telegram-desktop/994/bin/Telegram
i get: Reading symbols from /snap/telegram-desktop/994/bin/Telegram...(no debugging symbols found)...done.

**Comment by MikeMilligan** [comment]
> 
> 
> @MikeMilligan Can you please check 1.8.15? It should be out already, I hope it fixes that crash.

I'm so sorry for the delay. I only saw your message early this morning.

I updated to 1.8.15 and it has been working for hours without crashes.
