### ISSUE TITLE
v. 1.8.12+ VS2019 build failed after switching to range-v3 0.9

### ISSUE THREAD

**Issue by kirsan31** [telegramdesktop/tdesktop#6649]
VS 2019 (16.3.2) build failed with many of this errors in the sdk files:

<details><summary>errors</summary>

1>C:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\um\oaidl.h(487): error C2220: the following warning is treated as an error
1>C:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\um\oaidl.h(487): warning C5103: pasting '/' and '/' does not result in a valid preprocessing token
1>C:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\um\oaidl.h(487): note: to simplify migration, consider the temporary use of /Wv:18 flag with the version of the compiler with which you used to build without warnings
1>C:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\shared\wtypes.h(745): note: in expansion of macro '_VARIANT_BOOL'
1>C:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\um\oaidl.h(487): error C2059: syntax error: '/'
1>C:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\um\oaidl.h(487): error C2238: unexpected token(s) preceding ';'

![image](https://user-images.githubusercontent.com/17767561/66258256-a975bc00-e7ab-11e9-9dc8-4753902f491e.png)

</details>

The problem is in this commit: https://github.com/telegramdesktop/tdesktop/pull/6501/commits/1be93ecb1c4e41ff0c3e593f3fac85c2a0540988.

@farseerfc @john-preston  any thoughts?

Thanks.

**Comment by 23rd** [comment]
Try to completely rebuild the solution or checkout to `0.9.0`.

**Comment by kirsan31** [comment]
@23rd thanks for the advise.

> Try to completely rebuild the solution

Already tried (rebuild, clean + rebuild), even new build form scratch.

> or checkout to 0.9.0.

Same error.

Errors above appear on every project inside solution, even on _Updater_ witch I believe have no dependency on range-v3...

**Comment by 23rd** [comment]
Okay, the next suggestion is to update `Windows SDK` from `Visual Studio Installer`.

**Comment by john-preston** [comment]
@kirsan31 This was a merged PR, you can see it in the PR list. In my version (VS2019 16.2.5) it works fine. It will be fun if the next stable release of VS will force to fall back to range-v3 0.5.0 :/

**Comment by 23rd** [comment]
Yes, it should be successfully built with `VS 2019 16.3.2, Windows SDK 10.0.18362.0, range-v3 0.9.1`.

**Comment by kirsan31** [comment]
I am not 100 sure for now (have other errors), but I think, that updating to SDK 10.0.18362 resolved the problem. Thanks all.
I will close this issue, when understand that all is ok.

**Comment by kirsan31** [comment]
Yes, with SDK 10.0.18362 all work fine. @23 thanks again.
May be it's worth to be mentioned in VS build instruction?
