### ISSUE TITLE
Заблокирован телеграмм

### ISSUE THREAD

**Issue by nullptr2** [telegramdesktop/tdesktop#6650]
В Железногорске полностью заблокировали телеграмм, работает только через VPN больше никак.

**Comment by MasterGroosha** [comment]
I'm afraid this is not TDesktop issue. Use VPN/Proxy (MTProxy preferred in EE-mode).

**Comment by p1ratrulezzz** [comment]
Попробуйте использовать MTProxy, их полно сейчас

**Comment by MairwunNx** [comment]
@nullptr2 вопросы к власти или к РКН в Российской Федерации. У меня работает и без Proxy и VPN, видимо везет пока что. Но однозначно не проблема tdesktop, закрывайте issue.
