### ISSUE TITLE
[Feature Request] Delete an account immediatelly

### ISSUE THREAD

**Issue by rbatllet** [telegramdesktop/tdesktop#6651]
### Is your feature request related to a problem?
I would like to delete an account immediately and permanently for security reasons without having to wait a month, or more time.

### Describe the solution you'd like
Implement a way to delete the account immediately like in WhatsApp.

![androidpit-how-to-disable-delete-whatsapp-account-triptych-w782](https://user-images.githubusercontent.com/3993987/66266414-03ff2e80-e825-11e9-8acf-aa06839ca6ff.png)

**Comment by Aokromes** [comment]
this doesn't belong to telegram desktop repository.

**Comment by rbatllet** [comment]
Thank you very much for nothing!

**Comment by rbatllet** [comment]
It's a feature request for Telegram!!! @Aokromes. Before closing a request, read it better!

**Comment by Aokromes** [comment]
Such feature request must be done to telegram twiteer, telegram desktop doesn't have delete account feature.
