### ISSUE TITLE
Telegram Desktop 1.8.13 often crashes when adding emoji in text

### ISSUE THREAD

**Issue by jpostma01** [telegramdesktop/tdesktop#6652]
### Steps to reproduce
1.  Type something like :hea   (for making a heart emoji)
2.  While typing, the quick-emoji-menu pops up (see attached photos)
3. With the arrow keys scroll through the emoji to find the one you want in your text
4. At step 3 my Telegram Desktop crashes most of the time

### Expected behaviour
Should be able to search an emoji without crashes

### Actual behaviour
Telegram Desktop 1.8.13 crashes

### Configuration
I am using:
- Windows 10 Pro
- Intel Core i7 2600K
- 8 GB DDR3 1333 MHz

**Version of Telegram Desktop:**
Telegram Desktop 1.8.13

**Used theme**:
I am using standard Night Mode

<details><summary><b>Logs</b>:</summary>

![crash-message](https://user-images.githubusercontent.com/10140966/66271291-9f5fc600-e85c-11e9-9fcc-e5403be9610a.png)

![input](https://user-images.githubusercontent.com/10140966/66271292-9ff85c80-e85c-11e9-963b-d6e11663a0e7.png)

![photo_2019-10-06_16-50-40](https://user-images.githubusercontent.com/10140966/66271293-9ff85c80-e85c-11e9-9493-6be9381f9f04.jpg)

![version](https://user-images.githubusercontent.com/10140966/66271294-9ff85c80-e85c-11e9-981e-e4493c01702a.PNG)

</details>

**Comment by Aokromes** [comment]
plz, on next crash paste here the crash report id.

**Comment by Aokromes** [comment]
Your Report Tag: 395648e0-cc1a-42de-8ff5-59b1851ba91d
Your User Tag: 3b08bf5ba1637129

**Comment by jpostma01** [comment]
This is what I got at the latest crash:

Your Report Tag: a3ba4602-8198-40cb-94c0-c2bb730f8242
Your User Tag: 89e4064427bccff4
