### ISSUE TITLE
Threads and Subgroups

### ISSUE THREAD

**Issue by aminya** [telegramdesktop/tdesktop#6657]
I wish there were threads/subgroups in Telegram like they are in Slack.
![image](https://user-images.githubusercontent.com/16418197/66337242-6b3fe000-e904-11e9-82e7-eb78600b0ace.png)

Also, replying to a message creates a threadl ike reply discussion, which keeps things organized
![image](https://user-images.githubusercontent.com/16418197/66337340-91fe1680-e904-11e9-911c-36a004c1dd47.png)

**Comment by user38192** [comment]
+1 i am too wait this function

**Comment by RadRussianRus** [comment]
They should be done in API first
