### ISSUE TITLE
[Question] How to export group or channel?

### ISSUE THREAD

**Issue by kenorb** [telegramdesktop/tdesktop#6658]
Before I could see the _Export_ option in the settings of the group, it's no longer the case.

Is this option has been removed? Otherwise, how do I export the group or channel which I've joined?

> 5.7 (181196) Stable on macOS

**Comment by RadRussianRus** [comment]
Are you sure that you're using Telegram Desktop, not native Telegram for macOS app? Telegram Desktop uses different versioning system, latest is 1.8.15.

**Comment by kenorb** [comment]
> Are you sure that you're using Telegram Desktop, not native Telegram for macOS app? Telegram Desktop uses different versioning system, latest is 1.8.15.

Thank you, I wasn't aware there are two completely different versions. I've installed the one from _Releases_, replacing the previous version, now I can see the _Export chat_ option. Thanks.
