### ISSUE TITLE
Impossibility to write some Czech characters

### ISSUE THREAD

**Issue by Elep331** [telegramdesktop/tdesktop#6659]
Hi, I am not able to write some Czech characters in Telegram Desktop through Czech keyboard. For example "ď". In the previous versions, it works.

Telegram Desktop 1.8.15 (64 bit) @ Fedora Workstation 30 (64 bit)

**Comment by MrIndeciso** [comment]
I also have this issue with other characters.
My layout is called "United Kingdom Extended". On Telegram Desktop I can't use one of the key modifiers and so I can't write characters like è à ì ò ù. In previous versions this worked but was not consistent. Other key combinations work without any issue.
I am using Telegram Desktop 1.8.15 on Fedora Workstation 30 64 bit too.

**Comment by ravanscafi** [comment]
Related to #1041?

**Comment by Aokromes** [comment]
the 2nd the same, the 1st, idk

**Comment by Aokromes** [comment]
this bug is still valid?

**Comment by Aokromes** [comment]
no answer after near 1 month, if this bug is still valid, open a new ticket with one updated telegram version downloaded from desktop.telegram.org or github.com
