### ISSUE TITLE
[Question] How to contribute to Telegram source codes?

### ISSUE THREAD

**Issue by LucianaMarques** [telegramdesktop/tdesktop#6660]
Hi there,

I have a feature in mind that I would like to build, however, I have not seen in any Telegram Apps source code a guidelines document for Contributing, as in other open source projects. Having said that, I'd like to know if these guidelines are formally specified, and if not, what should I do to send my patch (are github pull requests enough?).

Thanks!

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/blob/dev/.github/CONTRIBUTING.md
