### ISSUE TITLE
Can't start after update

### ISSUE THREAD

**Issue by YetAnotherRussianCoder** [telegramdesktop/tdesktop#6662]
### Actual behaviour
It just don't start

### Configuration
Slackware-current post 14.2 x86-64(kernel 4.19.75)

latest version(1.8.13)
![2019-10-09-160255_1280x768_scrot](https://user-images.githubusercontent.com/33904988/66484060-ef35cb80-eaae-11e9-8f6b-91065e6fb54f.png)

**Comment by Aokromes** [comment]
latest is 1.8.15.

**Comment by Aokromes** [comment]
no answer after months, closing.
