### ISSUE TITLE
Notifications stop and messages show up as read by me on sender's client

### ISSUE THREAD

**Issue by nop144d** [telegramdesktop/tdesktop#6666]
### Steps to reproduce
1.  Start or continue a chat with someone (no need to write anything)
2.  Lock the screen
3.  Wait until an update of TDesktop is available

### Expected behaviour
Nothing should be affected (at least on other devices)

### Actual behaviour
You no longer receive notifications (on your phone) from the person with whom you started the chat. Moreover, the messages the person sends appear as read by you on their side. Probably, your online status is also affected (you become always online).

### Configuration
**Operating system:**
Windows 10

**Version of Telegram Desktop:**
Before upgrading to 1.8.15, it was version 1.8.11, however I doubt it is fixed. Will try to reproduce when a new version is available.

**Used theme**:

<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
My guess is that when the update button appears on the client it activates the window (being previously inactivated by locking the screen) which in it's turn makes your client behave like you are in the chat.

Suggested solution: Check if Telegram's window is currently active before drawing the update button. Or draw the button without activating the window, I'm not sure if this is possible or not, forgot the WinAPI details.
</details>

**Comment by nop144d** [comment]
Reposting my comment here as it gone under "Logs" paragraph.

My guess is that when the update button appears on the client it activates the window (being previously inactivated by locking the screen) which in it's turn makes your client behave like you are in the chat.

Suggested solution: Check if Telegram's window is currently active before drawing the update button. Or draw the button without activating the window, I'm not sure if this is possible or not, forgot the WinAPI details.

**Comment by nop144d** [comment]
Reproduced during 1.8.15->1.9.37 upgrade

Happy New Year!

**Comment by Aokromes** [comment]
this issue is still valid?

**Comment by nop144d** [comment]
I need binaries of previous version to try to reproduce. Is there any archive for of old versions?

**Comment by RememberTheAir** [comment]
@nop144d the releases page of this repository

**Comment by Aokromes** [comment]
no answer after more than 1 month, closing, if this bug is still valid open a new ticket using updated telegram version.
