### ISSUE TITLE
[Question] How to return a group I left?

### ISSUE THREAD

**Issue by chshersh** [telegramdesktop/tdesktop#6669]
I've created a group fro two people. The other person left the group, and now I'm left the group as well. I didn't delete it, I just left the group. I want to return back to the group, and I can find this group and see it group from my search bar. However, I see a message that "group is inaccessible" and I don't see messages there.

Is it possible to restore the group and all messages there? Thanks!

**Info**

I'm using Telegram Desktop (version 1.8.15) on Ubuntu 18.04

**Comment by Aokromes** [comment]
you cannot.
