### ISSUE TITLE
Right click in input field hangs app if there is a big image in clipboard #linux #xfce #usability #ui

### ISSUE THREAD

**Issue by phpony** [telegramdesktop/tdesktop#6671]
Looks like app is preforming some kind of check of clipboard's contents when you preform a right click in input field, probably to detect is "Paste" a viable option or not. But this check fails miserably on really big PNG images being in clipboard. Having 5000x5000px PNG in clipboard makes Telegram Desktop app completely unresponsive after right-click in input field for a sole minute before popup menu appears.

### Steps to reproduce
1. Copy any big (5mb+ 5000x5000px) PNG image into clipboard.
2. Preform a click of right mouse button at message input field.

### Expected behaviour
Popup menu should appear instantly.

### Actual behaviour
Whole app becomes unresponsive for up to a minute, than popup menu shows.

### Configuration
OS: Debian 10 buster
Kernel: x86_64 Linux 4.19.0-6-amd64
Shell: bash 5.0.3
DE: XFCE
WM: Xfwm4
CPU: Intel Core i5-3320M @ 4x 3.3GHz
GPU: Mesa DRI Intel(R) Ivybridge Mobile 
RAM: 7677MiB

**Version of Telegram Desktop:**
v 1.8.15

**Comment by phpony** [comment]
I measured this two:
- time between I preform a right click in input field and popup menu appears
- time between I choose "Paste" option (or press Ctrl+V directly) and modal dialogue appears.

And it's the same. So, app is doing the same job as is does when you actually paste content (detecting/decoding clipboard contents?) when it should not. I think for usability reasons context popup menu should be instant and should not process any large data on each mouse click, ain't it? And if it does, why is it doing the same slow job again after you actually choose a "Paste" option? Something is wrong here.

**Comment by magnus-gross** [comment]
Cannot reproduce on Version 1.8.15 on Arch Linux.

I copied a large PNG image (8,353 × 5,986) into clipboard and I only notice a 500ms delay when I click on paste, but none, if I only right click for the context menu.

**Comment by Neurotoxin001** [comment]
So, there is similar issue with crash on Windows 10 LTSC 1809
1.9.8 TG
https://github.com/telegramdesktop/tdesktop/issues/7055

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/5730
