### ISSUE TITLE
Pasting images from certain websites (eg reddit) transforms the image into a sticker

### ISSUE THREAD

**Issue by Sowee0** [telegramdesktop/tdesktop#6673]
### Steps to reproduce

1- Copy an image from reddit
2- Paste in Telegram desktop
3- Image is now a sticker (the default image options don't even appear)
### Expected behaviour
The usual image upload dialog should open (send as file or send as image)

### Actual behaviour
The image is sent as a sticker

### Configuration
**Operating system:** Windows 10

**Version of Telegram Desktop:** WUP

**Used theme**: Night Mode

[Example here](https://i.imgur.com/vHOLYUz.png)

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/6321
