### ISSUE TITLE
No "share my phone number" checkbox if user is blocked

### ISSUE THREAD

**Issue by Neurotoxin001** [telegramdesktop/tdesktop#6674]
### Steps to reproduce
1. go to dialog with user
2. open user profile
3. block the user
4. close profile window and open it again
5. now "add to contacts"
6. there is no "share my phone number" checkbox

On ios telegram app I can see this checkbox even if I try to add blocked user, but on desktop there is no this checkbox.
video - https://i.imgur.com/NucYwwY.mp4

### Configuration
**Operating system:** win 10 ltsc 1809

**Version of Telegram Desktop:** 1.8.15

**Used theme**: default dark

**Comment by Neurotoxin001** [comment]
Just because I can... On ios I can see this checkbox even if user is blocked.

**Comment by john-preston** [comment]
@Neurotoxin001 Well, maybe it is a bug on iOS.

**Comment by Neurotoxin001** [comment]
No, it's bug on desktop, because when I add contact - it's become unblocked. On ios I can choose share my number or not but on desktop I can't choose that.

**Comment by Neurotoxin001** [comment]
1.9.3 bug is still here.

**Comment by Neurotoxin001** [comment]
+

**Comment by Neurotoxin001** [comment]
Fixed
