### ISSUE TITLE
The Call Pop-up does not get hidden/closed on Wayland after accepting a call

### ISSUE THREAD

**Issue by Bryophyllum** [telegramdesktop/tdesktop#6675]
### Steps to reproduce
1. Run Telegram on a Wayland compositor (only tested it with GNOME 3.34) with the environment variable `QT_QPA_PLATFORM=wayland` set;
2. Make a call;
3. When the call starts, click on other app window so that Telegram loses focus.

### Expected behaviour
The call pop-up should disappear after losing focus.

### Actual behaviour
The call pop-up does not completely disappear after losing focus, it is still visible on the workspace overview (KDE and GNOME have this feature where all active workspaces and opened windows on them are shown at once), and most likely, at the same time, positioned below a currently active window.

### Configuration
**Operating system:** Fedora Silverblue 31

**Version of Telegram Desktop:** 1.8.14 via [Flatpak](https://github.com/flathub/org.telegram.desktop)

**Used theme:** The vanilla Night theme

**Comment by Aokromes** [comment]
this bug is still valid on 1.9.21?

**Comment by Bryophyllum** [comment]
@Aokromes Yes, it is; I can reproduce it on the 1.9.21. I'm still on GNOME Wayland running on Fedora 31 and I still use the Telegram Flatpak, with an environmental variable override `--env=QT_QPA_PLATFORM=` set to enable the Qt Wayland backend, from Flathub.

**Comment by Aokromes** [comment]
can you try on 2.1?

**Comment by Bryophyllum** [comment]
The behaviour is unchanged. For all it's worth, I'm on GNOME 3.36, Fedora 32.

**Comment by ilya-fedin** [comment]
Could you add some screencast? I can't understand what bug is.

**Comment by Bryophyllum** [comment]
@ilya-fedin I'm sorry about the delay. 

That is to say, the call window never gets minimized to the background on Wayland after a voice call has been established; whereas it does on X11.
[Screencast.zip](https://github.com/telegramdesktop/tdesktop/files/4605740/Screencast.zip)

**Comment by ilya-fedin** [comment]
> That is to say, the call window never gets minimized to the background on Wayland after a voice call has been established; whereas it does on X11.

Hmm, can you run in terminal and look if there will be any warnings when the window should be hidden

Wayland has restrictions for window control, probably this is an one another restriction :(

**Comment by Bryophyllum** [comment]
I'm only able to spot these two warnings: 
```
qt.qpa.wayland: Wayland does not support QWindow::requestActivate()
qt.qpa.wayland: setGrabPopup called with a parent, 
  QtWaylandClient::QWaylandXdgSurface(0x55fbcaa80fc0) which does not match the current topmost 
  grabbing popup, QtWaylandClient::QWaylandXdgSurface(0x55fbcb150a50) According to the xdg-shell 
  protocol, this is not allowed. The wayland QPA plugin is currently handling it by setting the parent to 
  the topmost grabbing popup. Note, however, that this may cause positioning errors and popups 
  closing unxpectedly because xdg-shell mandate that child popups close before parents
```
