### ISSUE TITLE
Unread message count in dock not showing since update to Mac OS Catalina (10.15)

### ISSUE THREAD

**Issue by Cassolotl** [telegramdesktop/tdesktop#6676]
### Steps to reproduce
1. Update your Mac to Catalina (10.15)
2. Receive messages from people who aren't muted.
3. The app makes the "ping" sound and the icon bounces, but there is no red unread messages count on the dock icon.

### Expected behaviour
Red unread messages count on the dock's Telegram icon.

### Actual behaviour
The app makes a notification sound and the icon bounces, and in the chat list the unread messages count is blue and not greyed out, but on the dock icon there is no unread message count in red at all.

### Configuration
**Operating system:** Mac OS Catalina (10.15)

**Version of Telegram Desktop:** 1.8.15

**Used theme**: Classic

<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by vrnvorona** [comment]
Same behavior after last update. Beta 5.9.1 didn't help.

**Comment by Cassolotl** [comment]
I fixed it! :)

System Preferences > Notifications > Telegram > enable "badge app icon"
