### ISSUE TITLE
Duplicated stickers when export chat history

### ISSUE THREAD

**Issue by Neurotoxin001** [telegramdesktop/tdesktop#6677]
### Steps to reproduce
1. export chat history of any chat with bunch of stickers
2. open the /stickers/ folder
3. there is too many duplicates with same size
![image](https://user-images.githubusercontent.com/39812401/66798035-663aec00-ef15-11e9-9cb8-26dcd2ea17f0.png)

Can you please improve export function to detect same stickers and do not download them for many times?

### Configuration
**Operating system:** win 10 ltsc 1809

**Version of Telegram Desktop:** 1.8.15

**Used theme**: dark default

**Comment by Neurotoxin001** [comment]
+

**Comment by maxoku** [comment]
Is that fixed?
