### ISSUE TITLE
Double enter to send images stopped working

### ISSUE THREAD

**Issue by joolsmtw** [telegramdesktop/tdesktop#6678]
### Steps to reproduce
1. Choose an image to send through the file explorer in a chat
2. Press enter (once and for the first time) to choose the image
3. Try and press enter again to quickly send the image with the standard options (compressed image, blank/no description)

### Expected behaviour
Double pressing enter (once to choose the image in the file explorer, and another time to send it quickly with the standard options) should send the image quickly

### Actual behaviour
After the first enter, it demands a manual mouse input to select either a description (i.e. putting the cursor in the description field) or a manual press on "send" in general.

### Configuration
**Operating system:**
Windows 10

**Version of Telegram Desktop:**
1.8.15

(recently updated from 1.1.22)

**Used theme**:
Standard

**Comment by jeffythedragonslayer** [comment]
I can't reproduce this on 1.9.20 with windows 10.  After pressing enter to select an image in the file explorer, in telegram the empty caption field has focus.  Pressing enter again sends it.
