### ISSUE TITLE
Youtube preview not showing

### ISSUE THREAD

**Issue by imashxtyz** [telegramdesktop/tdesktop#6681]
After sending youtube videos telegram must show preview, but recently for some videos it is only showing this
![image](https://user-images.githubusercontent.com/46919076/66847736-3e9c6000-efb7-11e9-924e-d305207fb40b.png)

**Operating system:**
Windows 7 64bit
**Version of Telegram Desktop:**
1.8.15
**Used theme**:
Classic

**Comment by Aokromes** [comment]
not telegram desktop bug :/ android affected too.
