### ISSUE TITLE
[Feature Request] User-defined chat grouping (workspaces and folders)

### ISSUE THREAD

**Issue by jdelgadocr** [telegramdesktop/tdesktop#6682]
### Is your feature request related to a problem?
We run our subscription business on Telegram. Having user private channels/groups, marketing public channel, multiple vendors channels/groups/bots, new and potential client chats... I personally have over 150 chat objects. having all chat objects (channels, groups, users, bots) mixed together is simply chaotic. I was using Bettergram as it provides basic object type grouping but it seems to be now broke after some Windows updates.

### Describe the solution you'd like
Ability to create custom groups where user can place any mix of chat objects, basically workspaces and more grouping inside as folders. Please look at Telefuel.com

### Describe alternatives you've considered
I attempted to use Telefuel alternative client but they choose to implement from ZERO using a different environment (React??) which is not mature enough and lacks the basic features we currently have with the current official UI (voice messages, paste videos, voice calls, etc). Telefuel has the right concept but building a new UI from scratch is not the right direction. My opinion.

### Additional context
![telefuel](https://user-images.githubusercontent.com/47994550/66854942-926b6280-ef3f-11e9-98b7-69deeef5eddb.png)

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/1107
