### ISSUE TITLE
Drag & Drop doesn't work on Telegram Desktop Flatpak 

### ISSUE THREAD

**Issue by darksystem23** [telegramdesktop/tdesktop#6683]
Hello, I'm using Telegram Desktop Flatpak on GNU/Linux and drag & drop doesn't work from Thunar of XFCE. It says "Could not send an empty file..."

### Configuration
**Operating system:**

```
System:
  Host: aaron-pc Kernel: 4.14.149-1-MANJARO x86_64 bits: 64 compiler: gcc 
  v: 9.2.0 Desktop: Xfce 4.14.1 tk: Gtk 3.24.12 info: xfce4-panel, plank 
  wm: xfwm4 dm: LightDM 1.30.0 Distro: Manjaro Linux 
Machine:
  Type: Laptop System: Acer product: Aspire E5-573 v: V3.72 serial: <filter> 
  Mobo: Acer model: ZORO_BH v: Type2 - A01 Board Version serial: <filter> 
  UEFI: Insyde v: 1.37 date: 02/16/2016 
Battery:
  ID-1: BAT1 charge: 32.1 Wh condition: 32.1/37.0 Wh (87%) volts: 17.1/14.8 
  model: SANYO AL15A32 type: Li-ion serial: <filter> status: Full 
CPU:
  Topology: Dual Core model: Intel Core i5-5200U bits: 64 type: MT MCP 
  arch: Broadwell rev: 4 L2 cache: 3072 KiB 
  flags: avx avx2 lm nx pae sse sse2 sse3 sse4_1 sse4_2 ssse3 vmx 
  bogomips: 17605 
  Speed: 800 MHz min/max: 500/2700 MHz Core speeds (MHz): 1: 802 2: 800 
  3: 800 4: 802 
Graphics:
  Device-1: Intel HD Graphics 5500 vendor: Acer Incorporated ALI 
  driver: i915 v: kernel bus ID: 00:02.0 chip ID: 8086:1616 
  Display: x11 server: X.Org 1.20.5 driver: intel unloaded: modesetting 
  alternate: fbdev,vesa resolution: 1366x768~60Hz 
  OpenGL: renderer: Mesa DRI Intel HD Graphics 5500 (Broadwell GT2) 
  v: 4.5 Mesa 19.2.1 compat-v: 3.0 direct render: Yes 
Audio:
  Device-1: Intel Broadwell-U Audio vendor: Acer Incorporated ALI 
  driver: snd_hda_intel v: kernel bus ID: 00:03.0 chip ID: 8086:160c 
  Device-2: Intel Wildcat Point-LP High Definition Audio 
  vendor: Acer Incorporated ALI driver: snd_hda_intel v: kernel 
  bus ID: 00:1b.0 chip ID: 8086:9ca0 
  Sound Server: ALSA v: k4.14.149-1-MANJARO 
Network:
  Device-1: Realtek RTL8111/8168/8411 PCI Express Gigabit Ethernet 
  vendor: Acer Incorporated ALI driver: r8169 v: 2.3LK-NAPI port: 3000 
  bus ID: 02:00.0 chip ID: 10ec:8168 
  IF: enp2s0 state: down mac: <filter> 
  Device-2: Qualcomm Atheros QCA9377 802.11ac Wireless Network Adapter 
  vendor: Foxconn driver: ath10k_pci v: kernel port: 3000 bus ID: 03:00.0 
  chip ID: 168c:0042 
  IF: wlp3s0 state: up mac: <filter> 
Drives:
  Local Storage: total: 704.24 GiB used: 114.12 GiB (16.2%) 
  ID-1: /dev/sda vendor: SanDisk model: SDSSDP256G size: 238.47 GiB 
  speed: 6.0 Gb/s serial: <filter> scheme: GPT 
  ID-2: /dev/sdb type: USB vendor: Toshiba model: MQ01ABD050 
  size: 465.76 GiB rotation: 5400 rpm serial: <filter> scheme: GPT 
Partition:
  ID-1: / size: 60.00 GiB used: 20.13 GiB (33.5%) fs: f2fs dev: /dev/sda2 
  ID-2: /home size: 167.97 GiB used: 94.00 GiB (56.0%) fs: f2fs 
  dev: /dev/sda3 
Sensors:
  System Temperatures: cpu: 37.0 C mobo: N/A 
  Fan Speeds (RPM): N/A 
Info:
  Processes: 241 Uptime: 8m Memory: 15.59 GiB used: 1.96 GiB (12.6%) 
  Init: systemd v: 242 Compilers: gcc: 9.2.0 Shell: bash v: 5.0.11 
  running in: xfce4-terminal inxi: 3.0.36
```

**Version of Telegram Desktop:**

`Telegram Desktop Flatpak 1.8.14`

**Used theme**:

`Default Theme - Night Mode`

**Comment by xvitaly** [comment]
Flatpak applications run in a restricted sandboxes. Check this: https://github.com/flatpak/xdg-desktop-portal/issues/99

**Comment by Aokromes** [comment]
so won't fix?

**Comment by darksystem23** [comment]
> Flatpak applications run in a restricted sandboxes. Check this: [flatpak/xdg-desktop-portal#99](https://github.com/flatpak/xdg-desktop-portal/issues/99)

 They are talking about adding a Mimetype "application/x-file-contents" or something like that to the *.desktop file? and some other possible solutions... I tried but it doesn't work.

But if I put the file in the sandbox home folder of Telegram it works perfectly (/home/user/.var/app/org.telegram.desktop/picture.png), but that is a little annoying. Yeah, maybe I can make a link to that folder to make the things easier. But if it can't be fixed and use the routes outside of the sandbox only for drag & drop in the future, it would be very sad... 

Thanks for the help :)

**Comment by darksystem23** [comment]
I fixed with `flatpak override --user --filesystem=home org.telegram.desktop` the user has to set the override. It's simple like that

**Comment by xvitaly** [comment]
> I fixed

This is not a fix. You have just disabled isolation and divided the whole point of Flatpak to zero.

**Comment by Johnnynator** [comment]
> > I fixed
> 
> This is not a fix. You have just disabled isolation and divided the whole point of Flatpak to zero.

> Flatpak is a next-generation technology for building and distributing desktop applications on Linux

The point of Flatpak is not sandbox but having an easy way to distribute binaries without having to care about different Linux distributions. https://www.flatpak.org/ does not even mention sandboxing once.

**Comment by darksystem23** [comment]
> > I fixed
> 
> This is not a fix. You have just disabled isolation and divided the whole point of Flatpak to zero.

That depends on what perspective you are looking at and purposes

**Comment by Sioma112233** [comment]
> > > I fixed
> > 
> > 
> > This is not a fix. You have just disabled isolation and divided the whole point of Flatpak to zero.
> 
> > Flatpak is a next-generation technology for building and distributing desktop applications on Linux
> 
> The point of Flatpak is not sandbox but having an easy way to distribute binaries without having to care about different Linux distributions. https://www.flatpak.org/ does not even mention sandboxing once.

This is just not true.
The [wiki page](https://en.wikipedia.org/wiki/Flatpak) starts with that.
I would advise reading more about Flatpak that their front page that's supposed to be short
