### ISSUE TITLE
Why did commit code grow 5 fold in size (Linux)? 

### ISSUE THREAD

**Issue by braselectron** [telegramdesktop/tdesktop#6688]
First of all, great job! Fantastic project! Thank you!

I have been using Telegram (mobile and desktop) since I found it on the web.  I'm a Linux user for the last 20 years.

I noticed that the code commit for Linux 64/32bits has grown by a fold of FIVE! this last few months (ie. from 19 MB for commit 1.2.17 to now +100MB for 1.8.15).

Could this be caused by forgeting to remove the debug option or the new code is "very" object oriented now, and in big blocks ?

I know that many new features were included, but 5 times bigger is crazy, specially if you use very tight RAM distros on ARM platforms and older x86 hardware.

Is this the end for the RAM/CPU limited systems ?

**Comment by john-preston** [comment]
@braselectron What do you mean by commit code?

**Comment by braselectron** [comment]
Thank you for your feedback.
In version control systems, a commit adds the latest changes to [part of] the source code to the repository, making these changes part of the head revision of the repository.
commits = release versions after updates/changes

**Comment by john-preston** [comment]
If you speak about the git repository size, then what difference does it make what size it has? Because your first message looks like it is about the compiled code size, not the repository size.

**Comment by braselectron** [comment]
Sorry, I did not express my self correctly in English language.  

I noticed that the "deb" installer code for Linux 64/32bits has grown by a fold of FIVE! this last few months (ie. from 19 MB for version 1.2.17 to now the "deb" is +100MB for version 1.8.15).

Hope you can understand now my point of view.  

Thank you, again, for your feedbacks.

**Comment by Johnnynator** [comment]
> Sorry, I did not express my self correctly in English language.
> 
> I noticed that the "deb" installer code for Linux 64/32bits has grown by a fold of FIVE! this last few months (ie. from 19 MB for version 1.2.17 to now the "deb" is +100MB for version 1.8.15).

You should check your numbers, the binary size between 1.2.17 and 1.8.15 in this repo is a difference of ~+20% (82.4Mib -> 99.2MiB). IDK which deb you are talking about, but the package in Debian Sid (`1.8.15-1+b1`) has a installed Size of roughly 51MiB. So yes there is a increase in size, but nowhere near 5x.

**Comment by braselectron** [comment]
telegram-desktop Version 1.2.17-1   (ubuntu repository)
whereis telegram-desktop: /usr/bin/telegram-desktop
system size: 19,186,728 ~ 19 MB  
Installed: abr 21,  2018
OS: Ubuntu 18.04.3 LTS  x86_64
Kernel: 4.15.0-65-generic
CPU: Intel i7-4500U (4) @ 3.000GHz
DE: GNOME 3.28.4

`$ cd /var/cache/apt/archives/`
`$ ls -la telegram-desktop_1.2.17-1_amd64.deb`
`-rw-r--r-- 1 root root 16873796 abr 22  2018 telegram-desktop_1.2.17-1_amd64.deb`

> > 16,873,796 ~ 17MB

**Comment by Johnnynator** [comment]
So I just checked both ubuntu deps, `telegram-desktop_1.2.17-1_amd64.deb` has a tdesktop bin of `18.3MiB`, `telegram-desktop_1.8.8-1_amd64.deb` has a binary of `43,1MiB` which is a bit more than twice the size, but nowhere near 5x.

**Comment by Aokromes** [comment]
new features, larger binaries. i don't think caring about 17 or 43MB on a world where pics can be such large.

**Comment by braselectron** [comment]
@Aokromes sorry but you are not helping.  Please don't answer questions you cannot understand, answers should not be misleading for other readers who seek knowledge. 

@Johnnynator please also check your numbers and my original question.   The fact is that the binary is many time the size when you compare the the version of 1.2.17-1 deb version telegram-desktop_1.2.17-1_amd64.deb and the the 1.8.15 release that after installed inflates and becomes 104MB

34,004,272 tsetup.1.8.15.tar.xz  -> 104,025,296 telegram-desktop

Conclusion:  1.2.17-1 binary is 17M
                     1.8.15 binary is now 104M

104 / 17 = 6.1 times de original size, actually more than 5 folds.

If is continues this path we will need a Terabyte system to run Tg-desktop in less than 3 years.

**Comment by john-preston** [comment]
@braselectron You need to compare tsetup.1.2.17 with tsetup.1.8.15.

**Comment by john-preston** [comment]
@braselectron Perhaps 1.2.17-1.deb was using dynamic linking to Qt and other libraries, if someone builds 1.8.15 the same way it won't be 100mb as well.

**Comment by Johnnynator** [comment]
> @Johnnynator please also check your numbers and my original question. The fact is that the binary is many time the size when you compare the the version of 1.2.17-1 deb version telegram-desktop_1.2.17-1_amd64.deb and the the 1.8.15 release that after installed inflates and becomes 104MB
> 
> 34,004,272 tsetup.1.8.15.tar.xz -> 104,025,296 telegram-desktop
> 
> Conclusion: 1.2.17-1 binary is 17M
> 1.8.15 binary is now 104M
> 
> 104 / 17 = 6.1 times de original size, actually more than 5 folds.
> 
> If is continues this path we will need a Terabyte system to run Tg-desktop in less than 3 years.

What John Preston said, you can't compare the tsetup tar ball with the ubuntu deb, Ubuntu links dynamically against the system libs while the tar ball in this repo contains a statically linked qt5 (+ some other libs).

**Comment by Aokromes** [comment]
@braselectron i have show you the exact official binary sizes, they are from 85 to 104 not from 17 to 104. you cannot compare ubuntu repo with official repo, you must compare official repos or ubuntu repos, if the 2nd they don't belong here.

**Comment by braselectron** [comment]
@Aokromes and @Johnnynator now, based on your last messages I understand what happened.  That explains the code increase (ie.  "Ubuntu links dynamically against the system libs while the tar ball in this repo contains a statically linked libs").  Got it, now it makes sense.  Thank you.
