### ISSUE TITLE
[Question] My group was spammed by bots. How can I delete all messages from those bots?

### ISSUE THREAD

**Issue by beppe9000** [telegramdesktop/tdesktop#6690]
Am I expected to select over 4k messages one by one or is there a better way?

BTW... One would expect that the SHIFT modifier would allow to select the first message, navigate to the last message, press SHIFT and select all the messages in between.

**Comment by Aokromes** [comment]
sorry, this doesn't belong to here, i suggest you if it's a single or multiple bots right click over a message and delete->"delete all from this user"
