### ISSUE TITLE
[Question] why setting QT_IM_MODULE to xim in snap/scripts/telegram_launch ?

### ISSUE THREAD

**Issue by farseerfc** [telegramdesktop/tdesktop#6691]
The code here https://github.com/telegramdesktop/tdesktop/blob/dev/snap/scripts/telegram-launch#L20-L21 is setting `QT_IM_MODULE` to `xim` even when it already has value of `ibus`.
As far as I know, Qt5 don't have xim support from the beginning, this is why we need/have ibus fcitx hime and other IM modules linked-in in the first place.
So this code effectively disabled ibus for snap launch, why doing this?

**Comment by ilya-fedin** [comment]
There are no telegram_launch anymore
