### ISSUE TITLE
No "Show tray icon" option in Gnome

### ISSUE THREAD

**Issue by GabVenturato** [telegramdesktop/tdesktop#6693]
I'm experiencing this problem on Fedora 30 with Gnome 3.32.2. I've inserted information about it in #6412 and in #3830. Since the former has been closed (and I opened it as a feature request, because I didn't noticed it was a bug before discussing it), and the latter seems to be a bit ignored and filled with other ideas and stuff too, I'm opening a new bug.

### Steps to reproduce
1. Install Telegram from dnf (or downloading from the website, the version is the same)
2. Check the settings

### Expected behaviour
I expect to see something like:
![63530091-b0978200-c4fd-11e9-8a66-6bd9447cfa22](https://user-images.githubusercontent.com/7904029/66999435-4acb0f00-f0d6-11e9-848e-baa2eedcaeaf.png)

### Actual behaviour
I see this instead:
![telegram](https://user-images.githubusercontent.com/7904029/66999469-5ddddf00-f0d6-11e9-8466-d275813da01d.png)

### Configuration
**Operating system:** Fedora 30

**Version of Telegram Desktop:** 1.8.15

**Used theme**: Classic

**Comment by Aokromes** [comment]
not a bug, it's intended gnome to don't ship tray icon.

"Carlos from Linux & GNOME here. We are trying to approach important apps using status icons to provide better alternatives that are more integrated with the system. Status icons have been deprecated for some time and we plan to remove the systray for GNOME 3.26."

**Comment by GabVenturato** [comment]
Yeah I know it, but the problem is that if I press the closing button the application remains open. So if you don't want to show that option in GNOME is great, I agree with that choice. But then if I close the application, then that should be closing, and not stay open in background, otherwise I loose control on it, right?

So yes, maybe my bug is not the correct one..? Should I open a bug to correct the behavior and not the settings options?

Thanks :)
