### ISSUE TITLE
[Feature Request] Edit time of scheduled posts

### ISSUE THREAD

**Issue by Neurotoxin001** [telegramdesktop/tdesktop#6694]
### Is your feature request related to a problem?
Yes. It's annoying to re-schedule posts if I want to change posting time

### Describe the solution you'd like
Make able "edit" posting time of scheduled posts

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/6496#issuecomment-543524895

**Comment by Neurotoxin001** [comment]
> #6496
But it's just "edit", not the "edit time".

**Comment by RememberTheAir** [comment]
I think this can be re-opened, since  #6496 is asking for an option to edit the text/caption of scheduled messages, while here op is asking about the scheduling time. I see them as two different requests
