### ISSUE TITLE
Land line setup fails

### ISSUE THREAD

**Issue by AmazingArjan** [telegramdesktop/tdesktop#67]
Just tried this software on windows 8.1, and fails to verify my landline number. It doens't get further than the screen where you actually have to enter the country+Phonenumber.
I'm on a regular private internet connection, without firewall, filters etc.

I'm using Telegram with landline, since i don't have a cellphone number anymore. Works great for example on the "unofficial Telegram Chrome app", but doens't work here in TelgramDesktop. A fix would be great.

**Comment by RyanCarlisle** [comment]
I'm not able to use a landline number for Telegram....I've been trying to use Telegram with landline, since i don't have a cellphone number anymore.....Kindly direct me on what should I do...

**Comment by telegramdesktop** [comment]
@RyanCarlisle Currently Telegram supports only mobile numbers, as I know. Anyway, this issue has nothing to do with Telegram Desktop app.

**Comment by RyanCarlisle** [comment]
So would I be able to use my landline number if I got the desktop app??

**Comment by RyanCarlisle** [comment]
I'm still not able to use my landline number for the desktop app...I've trying on the Telegram for web too....Kindly direct me on what should I do...

**Comment by pingram3541** [comment]
I know this is old but support for VoIP numbers was announced.

"As of 7 February 2017, Telegram now supports VoIP numbers, so you can now register with virtual numbers such as numbers issued by Google Voice."

However when using my Google Voice number it gives me an API error and says account does not exist, you must first create an account via the Android/iOS app.

I don't want to use the mobile app, just the desktop/web app.  This seems counter-intuitive to the allowance of using VoIP/Landline and Google Voice telephone numbers for account registration/verification purposes.

It's a shame I can't simply move on since many businesses have adopted using Telegram as their official means of contact...I am shut out unless I explicitly give in to my own hang ups about using android/ios devices which is not cool IMO Telegram people.

**Comment by john-preston** [comment]
@pingram3541 You can click on "here" link when you see the advice to use iOS / Android app on Telegram Desktop and still sign up from desktop only. This is not adviced for most of the users because you don't get your contacts imported that way.

**Comment by pingram3541** [comment]
There is no "here" link, that is the problem.  After entering my valid telephone number I expect it to call me or something similar to confirm/verify but instead I am met with a modal overlay dialog stating the following:

Error
You don't have a Telegram account yet, please sign up with Android / iPhone first.

There is an option for "more details" and an "ok" button which exits the modal dialog when clicked.  The "more details" link appears to me some API output...

```
Method: auth.sendCode
Result: {"_":"rpc_error","error_code":400,"error_message":"PHONE_NUMBER_APP_SIGNUP_FORBIDDEN"}
```

**Comment by pingram3541** [comment]
It works in the desktop app thx.

Maybe we can make it more clear how to go about registration with a non-smartphone number via the web app.  A simple notice to use the desktop app would suffice or just fix the web app to also allow this type of registration.  Thx again.

**Comment by pingram3541** [comment]
Well duh, I'm trying to register my number, I'm stuck in a catch22, my number needs to be registered before I can register it???

oh...and no "here" link anywhere.

![screen shot 2018-02-01 at 10 13 41 am](https://user-images.githubusercontent.com/319284/35695204-aeb46f9a-0738-11e8-8598-eb82ec1fade3.png)

**Comment by john-preston** [comment]
@pingram3541 Try the app from https://desktop.telegram.org

**Comment by pingram3541** [comment]
Yes thats what I did.  I downloaded the OSx desktop app 3.7.5 which is the source of the above screenshot

**Comment by john-preston** [comment]
@pingram3541 No, you didn't do what I said. I said try the version from https://desktop.telegram.org, not the one you post here.

**Comment by pingram3541** [comment]
I absolutely did.  Here is the screenshot of that url.

![screen shot 2018-02-01 at 10 45 18 am](https://user-images.githubusercontent.com/319284/35696730-194eec3c-073d-11e8-8d94-27f771b84021.png)

I downloaded the dmg from the blue button.

**Comment by pingram3541** [comment]
Ok.  I'm in finally yay!

I have to say, very confusing and not sure how I would have done this without you.

First it would have helped to know this can only be done from the "desktop" app and not the web app.

Second it would have been nice to know there are multiple versions of the same or similarly named desktop app called "desktop" with 2 very similar, almost identical format web pages.  One of which is not directly linked on the home page to help my situation as it directs to macos.telegram.org vs desktop.telegram.org when choosing to download the desktop app.

example macos.telegram.org:
![screen shot 2018-02-01 at 10 50 56 am](https://user-images.githubusercontent.com/319284/35697242-77c07faa-073e-11e8-9df1-0003e99cf1e4.png)

example desktop.telegram.org:
![screen shot 2018-02-01 at 10 45 18 am](https://user-images.githubusercontent.com/319284/35697277-862dda38-073e-11e8-866e-329b4c939108.png)

I see they have diff GPL versions and also different program versions and the setup screens were also different.  Yet, I still I don't understand why these 2 different versions exist and why someone would end up using one vs the other.

**Comment by stek29** [comment]
@pingram3541 because TDesktop is cross-platform and macOS native one is more fitting into macOS (& has secret chats)

**Comment by pingram3541** [comment]
@stek29 Thx Viktor, I see that now, just confusing for someone in my position trying to register a new acct without a smart phone.  Fell down the rabbit hole so-to-speak.  These questions would have never some up if the reg UE/UI was standardized and provided the same capabilities.  Maybe this feedback can help improve future development.  Cheers!
