### ISSUE TITLE
Youtube image preview error

### ISSUE THREAD

**Issue by cobalto** [telegramdesktop/tdesktop#670]
Every time I receive a youtube link, the interface goes crazy.

![erro_tdesktop](https://cloud.githubusercontent.com/assets/1196314/7284184/1a05361e-e912-11e4-8e41-3dc35a8b7354.PNG)

**Comment by kleuter** [comment]
Looks like it relevant to https://github.com/telegramdesktop/tdesktop/issues/674

**Comment by auchri** [comment]
Is this still the case? If yes, reopen the issue
