### ISSUE TITLE
Can't paste image while scheduling

### ISSUE THREAD

**Issue by Wirtos** [telegramdesktop/tdesktop#6702]
### Steps to reproduce
1. Press "schedule" button while inside a channel
2. Copy image and try to paste it into telegram

### Expected behaviour
Image should be pasted just like in normal mode

### Actual behaviour
Nothing happens

### Configuration
**Operating system:**
Windows 10

**Version of Telegram Desktop:**
1.8.15
**Used theme**:
None

**Comment by damnfella** [comment]
I can confirm this issue.
