### ISSUE TITLE
[Feature Request] Translate incoming messages

### ISSUE THREAD

**Issue by Programie** [telegramdesktop/tdesktop#6707]
### Is your feature request related to a problem?
Some Telegram channels contain messages which I don't understand and therefore have to copy messages and use a translator like Google Translate to translate it to a language I understand.

### Describe the solution you'd like
Telegram should provide a "Translate" button to translate a message to another language just like known from Facebook.

### Describe alternatives you've considered
I used Google Translate before which requires some manual steps (copy message, open Google Translate, paste to Google Translate) just to get the actual message translated.

**Comment by Aokromes** [comment]
i don't think this will be implemented ever.

**Comment by Programie** [comment]
But are there any reasons why this won't be implemented?

**Comment by Aokromes** [comment]
privacy.

**Comment by carlosnewmusic** [comment]
> privacy.

could be implemented through the firefox project, [Bergamot proyect](https://browser.mt/) 
only someone is needed for [this position](https://careers.mozilla.org/position/gh/1666741/)

**Comment by str** [comment]
Translation should work on user's demand. If the user does not request the text to be translated, there is no privacy issue.

**Comment by Programie** [comment]
This should still be implemented.

**Comment by KarenArzumanyan** [comment]
This would be really good. For example, how twitter is done. I vote for this feature.

**Comment by RememberTheAir** [comment]
This suggestion should be voted on the official bugs/suggestions tracker: https://bugs.telegram.org/c/32

**Comment by Ziggizag** [comment]
This is a critically important feature, really blocking users from reading foreign-language newsgroups. There should be an option to translate a given message on-demand, as well as to batch-translate all messages in a given group. This has nothing to do with privacy at all - contrary to @Aokromes point! Moreover - this should be a top priority - much more important than yet another emoji or sticker package...

**Comment by juanpc2018** [comment]
https://en.wikipedia.org/wiki/Universal_translator
https://youtu.be/lIKppXg0sYw

**Comment by juanpc2018** [comment]
> privacy.

That argument is flawed....
Spell Check is a leak.
cookies are a leak,
javascript is a leak,
cellphone microphone, camera.
OS,
etc...
There is No privacy...

i write something, and youtube display adds of that...
i dont have youtube account, 
i dont have google account,
youtube knows what i wrote.

everything is collected.

The only true privacy is to create a complete different private Network.
with Private Satellites.

**Comment by thomas-ed** [comment]
this would be great!

**Comment by jpdh9881** [comment]
This would be a great feature, even if it only worked for public channels.

As a rough solution, I made a translation server in Node.js that requires creating a Telegram group and Telegram bot. When you forward messages to the group, the bot registers the message. The translation server reads that message, translates it, then sends it back to the group via the bot. You can find it [here](https://github.com/jpdh9881/telegram-translator). Any feedback would be welcome.

**Comment by D-EVE-R** [comment]
go guys and push your request here https://bugs.telegram.org/c/12893

**Comment by fulmine500** [comment]
this feature is already present on the android version in Settings-> language-> show translate button

and with the use of the web version on chrome, it is possible to translate all the content

**Comment by axopoulos** [comment]
So is it planned to implement translation in Desktop version?

**Comment by yo3hjv** [comment]
Nothing new?
Can't be a security/privacy issue once that is active in the phone version!

**Comment by 3kbest** [comment]
I vote for translation on demand as you have on the mobile versions 👍

**Comment by pegr69** [comment]
Pls implement ondemand translation support

**Comment by Aokromes** [comment]
implemented on 4.3.2

**Comment by Ziggizag** [comment]
Thank you so much !!!
