### ISSUE TITLE
Lower voice message bitrate

### ISSUE THREAD

**Issue by Bleuzen** [telegramdesktop/tdesktop#6708]
Hi, I noticed that voice messages sent from Telegram Desktop are pretty big in file size (~ 0.5 MB per minute). Sometimes when one is on a slow mobile connection (just normal german interwebs) it takes really long to download voice message, especially if the voice message is a little longer.

But the good news is: the size of voice messages can be reduce really easy. Just lower the bitrate.
I found out (in https://github.com/telegramdesktop/tdesktop/blob/17baac710ebc6dd2f2e4ad726384a36afed60304/Telegram/SourceFiles/media/audio/media_audio_capture.cpp#L253) that the voice message bitrate from Telegram Desktop is 64 kbps.

I wonder why it is that high. People should not send music as voice messages and for voice only audio this is too much.
I did some tests and in terms of audio quality, I do not hear a difference anymore with opus bitrates higher as ~ 20 kbps.
Maybe, just in case there is some music in the background, optimal bitrate could be 32 kbps.

So, I would request / recommend to lower the voice message bitrate from 64 kbps to 32 kbps. You wont hear a difference anyway. But this would make voice msg chats only half of the size. (much better for slow connections and does not take up that much space on mobile devices)

-----
Oh and btw., the Telegram mobile/Android app uses a bitrate of only 16 kbps with an only 16 k samplerate, so this is even lower. (a little too low if you ask me, but well, thats not topic for this repo.)

**Comment by Aokromes** [comment]
maybe someone can create one pull request adding one dropdown for this to 16,24,32,48,64,96,128kbps :)

**Comment by Bleuzen** [comment]
Well yes, if someone has too much free time, a dropdown could be added.
But it is not really needed.

- Bitrates above 32 kbps do not make sense, because you won't hear a difference for a mono voice recording.
- Bitrates under 32 kbps do not make much sense, because some people with good ears may start to notice quality decrease in certain circumstances

So I don't think we need a dropdown, since I do not see a use case for other bitrates. Remember: these are voice messages. If someone wants to send music in very good quality: just send a flac or wav file.

To set the bitrate to fixed 32 kbps for voice messages would be just fine.

**Comment by marcoValkyriweb** [comment]
Is it currently set to constant or variable bitrate?

https://github.com/telegramdesktop/tdesktop/blob/17baac710ebc6dd2f2e4ad726384a36afed60304/Telegram/SourceFiles/media/audio/media_audio_capture.cpp#L272

Looks like it gets resampled, so I see no need to change it to lower if the 64Kbps is only used if it makes a difference in audio quality or the device doesn't support resampling.

I like the 64Kbps, I do have contacts that record music snippets via Telegram.

**Comment by Bleuzen** [comment]
@marcoValkyriweb It is set to average bitrate I think. A silent voice message made it to 55 kbps and a voice message with much action made it to 71 kbps. So it is a little variable, but still around the 64 kbps and too big.

As for music:
1. There is absolutely no reason to send music as voice message on Telegram. The quality of with a microphone recorded music in mono will be bad anyway. Just tell them to send a music file, this is really easy and offers a lot better quality.
2. I tested it to convert music even to 20 kbps and it still sounds... well, not great anymore, but good enough for a voice message. With 32 kbps it is really ok.

**Comment by marcoValkyriweb** [comment]
Mind uploading that "silent" voice clip? 
I checked trying to be silent on mine, it still picks up background noise, a slight hiss from the mic since I've upped the microphone boost to +10db, so I think it would actually be rare to have a proper "silent" voice clip. Maybe rather implement a noise gate probably? Then opus will also probably increase the "quality" of that section recorded while still achieving 64Kbps.

Have you also checked if 2/3 people are talking what the quality is like? Make sure they have different ranges. Also then try recording a quick meeting or something.

Yeah, by music I mean e.g. they quickly record a snippet while doing it live to see if it's any good or not in the group, not something that's already published. Telegram really needs group voice calls, would be cool, though that's a different issue entirely.

**Comment by try2flyb4ucry** [comment]
Hi, Any news on this?

**Comment by Bleuzen** [comment]
> assume that the user has lost interest or resolved the problem

nah, no

**Comment by Bleuzen** [comment]
> We therefore assume that the user has lost interest or resolved the problem on their own.

still no
