### ISSUE TITLE
"Launch Telegram when system starts" does not work

### ISSUE THREAD

**Issue by seekM** [telegramdesktop/tdesktop#6709]
### Steps to reproduce
1. Go to "Settings" -> "Advanced" 
2. At "System integration" check the "Show taskbar icon" and "Launch Telegram when system starts" boxes
3. Reboot

### Expected behaviour
Telegram should start automatically

### Actual behaviour
Telegram doesn't start

### Configuration
**Operating system:** Windows 10 Pro, Version 1903 (Build 18362.418)

**Version of Telegram Desktop:** 1.8.15

**Used theme**: Classic

<details><summary><b>Logs</b>:</summary>
Since Telegram does not start, nothing is written to Telegram's log.txt. Please let me know if there is additional information I can provide to help debug this.
</details>

**Comment by Aokromes** [comment]
works for me (TM)

**Comment by p0358** [comment]
Press Win+R, enter `shell:startup` and check if there is correct Telegram shortcut there, try launching Telegram using that shortcut. If it works, then it might be OS issue

**Comment by seekM** [comment]
Launching Telegram using the shortcut works.

I also tested this again, now Telegram also starts automatically after booting Windows. I don't know why it didn't work before, but now it does. Thanks!
