### ISSUE TITLE
Cannot play voice message 

### ISSUE THREAD

**Issue by MarcSteven** [telegramdesktop/tdesktop#6710]
### Steps to reproduce
1. Someone sends me a voice message
2. I click the button to play
3. And the button changes the status-playing but the progress was always pause at 00:00

### Expected behaviour
Tell us what should happen
The voice message can be played

### Actual behaviour
Tell us what happens instead
The voice message cannot be played

### Configuration
**Operating system:**
Mac os 10.15
**Version of Telegram Desktop:**
1.8.15

**Used theme**:

<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by Aokromes** [comment]
this bug is still valid?

**Comment by MarcSteven** [comment]
Yeah it's existing sometimes.

**Comment by Aokromes** [comment]
they are send by old iphones or people using old telegram versions on iphone (ie people using telegram x)?

**Comment by MarcSteven** [comment]
@Aokromes  Yeah I used iPhone XR and it has this issue, does it mean you give up it absolutely?

**Comment by Aokromes** [comment]
no, i am asking if the audio was send by old telegram iphone versions or new telegram iphone versions or telegram x.

**Comment by MarcSteven** [comment]
The latest version

**Comment by Aokromes** [comment]
if you can repo 100% with some specific audio maybe you can send it to preston to allow debug it.

**Comment by MarcSteven** [comment]
The audio is okay, I can use iTune to play it well.

**Comment by Aokromes** [comment]
@MarcSteven you tried to contact t.me/preston ?

**Comment by MarcSteven** [comment]
I cannot find him

**Comment by Aokromes** [comment]
search @ preston on telegram (without space)

**Comment by MarcSteven** [comment]
Okay, I will download the app and try to find , and then hope the bug will be fixed!

**Comment by MarcSteven** [comment]
@Aokromes  Sorry for this delay, I downloaded it and then tried it,  sometimes the voice was paused when I clicked the button of play.

**Comment by ilya-fedin** [comment]
> sometimes the voice was paused when I clicked the button of play.

What does this mean?

**Comment by MarcSteven** [comment]
@ilya-fedin I mean sometimes it cannot play the voice even though you clicked the button of play.

**Comment by ilya-fedin** [comment]
>  I mean sometimes it cannot play the voice even though you clicked the button of play.

Give a log after such attempt to play

**Comment by MarcSteven** [comment]
ok, I will.

**Comment by ilya-fedin** [comment]
> ok, I will.

How long should we wait?

**Comment by MarcSteven** [comment]
Just now I downloaded the latest version and tried more, it never happened again. So now closed it .
Perhaps there is a bug from the previous version. @ilya-fedin
