### ISSUE TITLE
Privacy settings for voice messages

### ISSUE THREAD

**Issue by Twilightssuperb** [telegramdesktop/tdesktop#6713]
I don't wanna get voice messages from anybody but my contacts. It's annoying so hard to listen voices from unknown people — while they could type a text and only text.

But there is no such setting in Telegram! I see options for voice calls and phone number, but nothing for voice messages. It's not just for desktop, it's for whole Telegram, however...

**Comment by Aokromes** [comment]
very likely this needs to be done api-side.
