### ISSUE TITLE
Amharic Font is too tiny to read on telegram desktop

### ISSUE THREAD

**Issue by serak** [telegramdesktop/tdesktop#6716]
### Steps to reproduce
1. check Amharic posting from this link https://t.me/tikvahethiopia using telegram desktop
2. and check the same link on web.telegram.org 

### Expected behaviour
Font should be readable as the one seen from web version of telegram

### Actual behaviour
Font too small to read

### Configuration
**Operating system:**
Microsoft Windows 10 build 1903
**Version of Telegram Desktop:**
1.8.15
**Used theme**:
Default with night mode on
<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/4072#issuecomment-524523439

**Comment by Yohass** [comment]
you can use telegram web @ https://web.telegram.org on your browser and you will be able to read  Amharic texts ....with the comfort of your browser without even installing telegram desktop.
