### ISSUE TITLE
Mention (@) is not replaced with the contact name from the contact list

### ISSUE THREAD

**Issue by FedorSafronov** [telegramdesktop/tdesktop#6717]
### Steps to reproduce
1. Make sure that you have a contact in your contact list with a "normal" name (John Smith) and make sure that this user has its own username (@mycoolusernamehere123)
2. Mention this user in a chat

### Expected behaviour
You should see that "John Smith" is mentioned in the message.

### Actual behaviour
You see that @mycoolusernamehere123 is mentioned in the message.

Now imagine that you have a lot of contacts in your contact list and chats with a lot of users. You cannot understand who's mentioned in a message.

### Configuration
**Operating system:** macOS Catalina 10.15

**Version of Telegram Desktop:** 1.8.15

**Used theme**: Classic

**Comment by tdchien** [comment]
Agree with this. It would be better if mention display in name which save in my contact, it' easier for understand

**Comment by RememberTheAir** [comment]
I think this is the intended behavior and it's probably not going to change until also the mobile apps will behave differently
