### ISSUE TITLE
Unread count doesn't update again after new messages gets deleted unread

### ISSUE THREAD

**Issue by tooomm** [telegramdesktop/tdesktop#6718]
That's how I observed this:
1. Receive several messages
2. Don't read them
2. Sender deletes the newest for both parties again
3. Telegram Desktop unread count badge kept ticking up on new messages, but doesn't update on delete
(On iOS it did remove the notification with the message preview and updated the app badge accordingly!)

### Expected behaviour
Unread count gets reduced to the correct number on unread message deletions.

### Actual behaviour
Unread count stays unchanged and shows for example "2", even if the last message gets deleted again by the sender and there is only "1" new, unread message left for you.

### Configuration
**Operating system:** Windows 10 64bit

**Version of Telegram Desktop:** 1.8.15

**Used theme**: default

**Comment by kirsan31** [comment]
Sadly, it's only one small part of big [problem](https://github.com/telegramdesktop/tdesktop/issues/775).

**Comment by tooomm** [comment]
Oh wasn’t aware they are related.
The other one is also very annoying!

Hope somebody understands it in full and takes the time to look into that at one point. Always difficult with this not so trivial changes...
