### ISSUE TITLE
add by phone number

### ISSUE THREAD

**Issue by samanad** [telegramdesktop/tdesktop#6719]
### Steps to reproduce
1. add new contact by phone number
2. 
3. 

### Expected behaviour
Tell us what should happen
that user has telegram and should be added
### Actual behaviour
Tell us what happens instead
it always say he is not on telegram yet
### Configuration
**Operating system:**mac

**Version of Telegram Desktop:**

**Used theme**:

<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by trochdewei** [comment]
Probably, user activated this option

![image](https://user-images.githubusercontent.com/37622670/68008644-0ffdd500-fc99-11e9-9dff-48765a12bc66.png)

**Comment by samanad** [comment]
no, this is not the subject because when i use telegram web version it doesn't give the error and the user is added to my telegram01.11.2019, 10:17, "trochdewei" <notifications@github.com>:Probably, user activated this option


—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
--  saman ghiasi about.me/perspolis
