### ISSUE TITLE
[Feature Request] Sectional list, File preview, Share preview

### ISSUE THREAD

**Issue by esajjad** [telegramdesktop/tdesktop#672]
1. Sectional list: 
1.1 "Favorite section" (personal selection group or people)
1.2 "Group section" with "Pin" ability
1.3 "People section" with "Pin" ability
![tel-f1](https://cloud.githubusercontent.com/assets/4344360/7332225/e9151124-eb4a-11e4-822a-b4b8e2454aec.png)

2. "File preview" same as "Forward preview"
![tel-f2](https://cloud.githubusercontent.com/assets/4344360/7332226/e91a3122-eb4a-11e4-8b23-1b936f7e9de6.png)

3. "Share preview" in setting (Because data is not deletable and user may share unwanted data in public)
![tel-f3](https://cloud.githubusercontent.com/assets/4344360/7332227/e91da186-eb4a-11e4-858f-425e0cb1b4f3.png)

**Comment by auchri** [comment]
1. See #1107, looks better
2. and 3. I'll create a new issue for the 2 points

**Comment by Mateusresende** [comment]
And seriously, it places category, tag,
and it's hard to stay up all the time organizing the contact agenda.
You lose a lot of time, and we still forget people, because you get thrown back there.
And I have to write down the names on the wall.
