### ISSUE TITLE
[Feature Request] Decrease distraction on demand: option to see only favorite contacts

### ISSUE THREAD

**Issue by petRUShka** [telegramdesktop/tdesktop#6722]
### Is your feature request related to a problem?
One of the favorite features of Telegram fork [Bettergram](https://www.bettergram.io/) (discontinued at the moment) is "Favorite tab" (among other tabs). It helps to focus on what you do and to not distract yourself more than you want to be distracted (especially with minimized notifications options). 

![https://i.imgur.com/wk7saW1.png](https://i.imgur.com/wk7saW1.png)

### Describe the solution you'd like
Idea is to have a button to hide all but favorite contacts. Also to have a way to add contact to Favorites.

### Describe alternatives you've considered
Alternative is to have not button but special tab for Favorites.

### Additional context
Why is so important to have option to see only favorites and decrease distraction when you want to? Tristan Harris former Product Philosopher at Google [has explained](https://medium.com/thrive-global/how-technology-hijacks-peoples-minds-from-a-magician-and-google-s-design-ethicist-56d62ef5edf3).

**Comment by ccrowles** [comment]
I would love this so much. It's literally the reason why I'm not using TDesktop anymore, and why on my phone I have Plus Messenger. Unfortunately the only valid fork with tabs for desktop for me was Bettergram (although riddled with crypto stuff), but the development was halted. Tabs or categories or at least just a "Favourites" tab would be extremely useful for those of us with lots of chats. Having personal chats, groups, bots and channels all mixed together is extremely confusing and distracting.

**Comment by petRUShka** [comment]
@ccrowles, I was suggested to look at [Telegreat](https://telegre.at/) (which is fork of Telegram Desktop). There are tabs by the way.

**Comment by ccrowles** [comment]
@petRUShka Yeah, it's the next best thing since Bettergram shut down and I'm currently using it, but it doesn't have a "favorites" tab sadly, only tabs by type. If I see for example a notification in the private chats tab, I won't know until I open it if it's from someone important or not.

**Comment by petRUShka** [comment]
> @petRUShka Yeah, it's the next best thing since Bettergram shut down and I'm currently using it, but it doesn't have a "favorites" tab sadly, only tabs by type. If I see for example a notification in the private chats tab, I won't know until I open it if it's from someone important or not.

And unfortunately it is not opensource anymore :( The development have moved to private repo...

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/1107
