### ISSUE TITLE
Bad text alignment

### ISSUE THREAD

**Issue by SleeplessSloth** [telegramdesktop/tdesktop#6723]
### Steps to reproduce
1.1. Either: Send or receive a message with a link or a word with repeated letters
1.2. Or: Send or receive a message in a channel with buttons underneath
1.3. Or: Forward a message
2. Watch the client fail to align the text correctly

### Expected behaviour
The text should be shown normally

### Actual behaviour
1. The message is shown with each letter on a new line
2. The buttons under a message in a channel are unreadable
3. The name of the person who wrote the message originally is replaced with ...

### What I tried
1. Reset fontconfig to default
2. Change Telegram's interface scaling
3. Change themes
4. Create a new user account

### Configuration
**Operating system:** Arch Linux

**Version of Telegram Desktop:** 1.8.15

### Screenshots:
![20191027_235031](https://user-images.githubusercontent.com/37976824/67643209-011fc700-f915-11e9-8fcb-4a06d57d86ea.png)
![20191027_235237](https://user-images.githubusercontent.com/37976824/67643216-198fe180-f915-11e9-940c-2a0fb2f4f856.png)
![20191027_235257](https://user-images.githubusercontent.com/37976824/67643201-f6fdc880-f914-11e9-8781-c7ba824ec3c7.png)

**Comment by iainlane** [comment]
I'm seeing this with the Flatpak of 1.8.15, but *not* the snap.
