### ISSUE TITLE
[Feature Request] Hide spoiler messages

### ISSUE THREAD

**Issue by mbakulin** [telegramdesktop/tdesktop#6724]
Sometimes in large group chats there can be messages that some users consider inappropriate or spoilers.

It would be nice if sender and/or chat admin could mark such messages as spoilers and hide them in one way or another. Many text forums have this feature, or discord, or reddit: you have a short text with description, like: "Spoilers to GoT S07E03" or "Insect warning", and any user can willingly click on the plus sign to expand the message. This way the sender can send a potentially risky message without hurting anyone. Pictures can be sent in a blurred form, like on reddit, or just be hidden like text.

**Comment by Aokromes** [comment]
@HideSpoilersBot

**Comment by RememberTheAir** [comment]
I would like to see something along these lines but that's something that must be supported by the API too

**Comment by mbakulin** [comment]
> @HideSpoilersBot

1) Doesn't work for me, at least just now 2) What if I don't want to share my messages with an unknown third-party bot?

**Comment by mbakulin** [comment]
@Aokromes 
> @HideSpoilersBot

1) Doesn't work for me, at least just now 2) What if I don't want to share my messages with an unknown third-party bot?

**Comment by Aokromes** [comment]
it still needs to be supported by api.
