### ISSUE TITLE
Media view is covered by taskbar Linux Mint

### ISSUE THREAD

**Issue by proea** [telegramdesktop/tdesktop#6726]
### Steps to reproduce
1. Open any window with enabled "Always on Top"
2. Open media viewer in Telegram Desktop

### Expected behaviour
Media Viewer should not be covered by task bar

### Actual behaviour
Media Viewer is covered by task bar (+ issue #5607)

### Configuration
**Operating system:**
Linux Mint 19.1

**Version of Telegram Desktop:**
1.8.15

![image](https://user-images.githubusercontent.com/2929968/67751180-ad5ecc00-fa41-11e9-9ce6-469c91f78950.png)

**Comment by Aokromes** [comment]
maybe mint task bar have also on top?

**Comment by proea** [comment]
@Aokromes this is repeated only when one window is displayed on top on the screen

**Comment by ilya-fedin** [comment]
Is this still valid?
