### ISSUE TITLE
[Feature Request] Hide unread count in chat list for muted chats

### ISSUE THREAD

**Issue by roobre** [telegramdesktop/tdesktop#6727]
### Is your feature request related to a problem?
Muted chats (specially groups) still show a badge with the number of unread messages, and the name in bold. Many of us like to check muted groups from time to time, yet the current behavior creates an unpleasant feeling of urge. In my opinion this does not mix well with the concept of muting, where the user does not want to be notified and just check the group manually.

Perhaps an additional setting would be the best to avoid breaking the current use case.

### Describe the solution you'd like
An additional setting to avoid highlighting muted chats in any way. Item should still go to the top of the list, though.

### Describe alternatives you've considered
N/A

### Notes
I find this source tree difficult to navigate on my own, but I am willing to work on a PR for this if you can drop some hints to me, like where to add the new setting and where the logic that decides if the badge is shown or not should be added.

**Comment by RememberTheAir** [comment]
There's an hidden setting that adds a button to hide your muted chats. See `workmode` in https://github.com/telegramdesktop/tdesktop/wiki/Hidden-modes

**Comment by roobre** [comment]
Oh, I didn't know this existed!

It certainly solves my problem, thank you!
