### ISSUE TITLE
Can't disable video messages playing automatically with mouse on hover

### ISSUE THREAD

**Issue by rignaneseleo** [telegramdesktop/tdesktop#6728]
### Steps to reproduce
1. Receive a Video Message in a chat
2. Pass the mouse OVER the video
3. The audio plays

### Actual behaviour
Now it plays automatically (and often accidentally) and it is annoying. Also because I think the volume is really high.

### Expected behaviour
I'd like to have the option to remove this auto play. I want to click on the video message in order to have it to start.

### Configuration
**Operating system:**
MacOS 10.15
**Version of Telegram Desktop:**
5.8 (185085) AppStore
**Used theme**:
Dark

**Comment by Aokromes** [comment]
this is for telegram desktop, you are using telegram macos.
