### ISSUE TITLE
show the remote time of the receiver

### ISSUE THREAD

**Issue by FelixFurtmayr** [telegramdesktop/tdesktop#6729]
## Is your feature request related to a problem?
No.

## Solution: See the remote time of the receiver
![grafik](https://user-images.githubusercontent.com/16761317/67893073-32d3a080-fb56-11e9-9364-665f23d22f22.png)

 ### why
* currently in international collaboration you have to do the calculation in your head or look the time up online. for me this takes 30 seconds each and is kind of annoying when you work with people from several continents. 
* make it easier to send the messages to people when they are at work 
* help you to organize meetings with the correct time; preparing a meeting can be done very nice with telegram already, but this would be a killer feature for my planning 

### Implementation
* there may be enough space to show the "remote time" in the layout
* the question is, where you get the remote time from (not sure if is available or should be available). I see two solutions:
  * knowing the remote time of the receiver an making it public to the sender (problem for data protection?)
* setting a remote timezone (this can be wrong if the person is in another country, but could be done very easy over profile information). if there is any data protection problem, it would be fine for me, to only set the country of the other person and calculate the time from that.

**Comment by RememberTheAir** [comment]
Duplicate of #5806

**Comment by FelixFurtmayr** [comment]
@RememberTheAir thank you for the quick reply and sorry that the feature request was already there. Did not find it myselfe. I close it and will have a look at the other ticket.
