### ISSUE TITLE
Connection timeout at startup, network clearly up

### ISSUE THREAD

**Issue by matthiasbeyer** [telegramdesktop/tdesktop#673]
Hi,

telegram cannot connect to the server at startup for me:

```
Telegram-client version 0.01-beta, Copyright (C) 2013 Vitaly Valtman
Telegram-client comes with ABSOLUTELY NO WARRANTY; for details type `show_license'.
This is free software, and you are welcome to redistribute it
under certain conditions; type `show_license' for details.
 *** Connect with 173.240.5.1:443 timeout
 *** Can not create connection to DC. Is network down?
```

My network is clearly up (I couldn't write this if it wasn't, right). Any Ideas how to debug this (I'm just a user, though)?

I'm on NixOS 64 bit.

**Comment by gonnz4** [comment]
I have the same error. :C

**Comment by auchri** [comment]
@matthiasbeyer you are talking about a different client: Telegram-client version 0.01-beta, Copyright (C) 2013 Vitaly Valtman
