### ISSUE TITLE
Window titlebar does not follow GTK theme with Qt's Wayland backend 

### ISSUE THREAD

**Issue by Newbytee** [telegramdesktop/tdesktop#6730]
### Steps to reproduce
1. Run Telegram Desktop with the Qt Wayland backend
2. Observe a titlebar which does not follow the GTK choosen theme

### Expected behaviour
Telegram's titlebar should follow my GTK theme as it does with Qt's X11 backend. 
![image_2019-10-30_22-23-34](https://user-images.githubusercontent.com/4428753/67900114-058def00-fb64-11e9-8134-e741df4580cc.png)

### Actual behaviour
Telegram's titlebar is unthemed and does not follow my GTK theme when using Qt's Wayland backend. This is especially noticeable when using dark GTK themes.
![Screenshot from 2019-10-30 22-21-58](https://user-images.githubusercontent.com/4428753/67900046-d7a8aa80-fb63-11e9-9f52-b61fe65ecf0c.png)
(don't mind the variance in window size and buttons, that's because these screenshots are from two different PCs)

### Configuration
**Operating system:**
Fedora 31 Workstation

**Version of Telegram Desktop:**
1.8.15

**Used theme**:
Default Night Mode, no Qt theme

**Comment by scsmash3r** [comment]
Same issue observed in Win 7 or in Win 8.1 with Windows 7 compatibility mode:
![image](https://user-images.githubusercontent.com/4781532/69287724-fb5d8e80-0bff-11ea-8a42-00ab2f254e68.png)

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/5714

**Comment by Newbytee** [comment]
@Aokromes No, not a duplicate. Telegram Desktop does follow your GTK theme's titlebar when using X.Org/X11. The issue you linked concerns making the entire Telegram Desktop application support GTK themes, whereas this one is about disparity between rendering in Wayland and X.Org/X11.

**Comment by Aokromes** [comment]
implementing that will implement this.

**Comment by Johnnynator** [comment]
This bug is afaik fixed with qt 5.14+

![Screenshot from 2020-01-27 14-27-30](https://user-images.githubusercontent.com/7373356/73178478-9d728900-4111-11ea-8d53-f2df68763e76.png)
