### ISSUE TITLE
High cpu usage Linux

### ISSUE THREAD

**Issue by freeseacher** [telegramdesktop/tdesktop#6738]
### Steps to reproduce
1. no idea
2. but got strace
3. 

### Expected behaviour
no cpu usage

### Actual behaviour
high cpu usage

### Configuration
**Operating system:**
Mint 19.2
**Version of Telegram Desktop:**
1.8.15
**Used theme**:
Coffe
<details><summary><b>Logs</b>:</summary>
[trace.txt](https://github.com/telegramdesktop/tdesktop/files/3799239/trace.txt)

</details>

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/3640
