### ISSUE TITLE
Ugly persian Font

### ISSUE THREAD

**Issue by dddeveloperrr** [telegramdesktop/tdesktop#6739]
Hi guys ,
i use telegram snap (version 1.8.15). the problem is Persian font is really unreadable.

how can i change telegram fonts? somebody help please. this is how Persian writings looks like and i cant read it at all 

![image](https://user-images.githubusercontent.com/11577640/68053782-06f51e00-fd02-11e9-9c53-1ecd89a2ceac.png)

**Comment by Aokromes** [comment]
generic bug.
https://github.com/telegramdesktop/tdesktop/issues/5172
