### ISSUE TITLE
Chat layout problem (0.8.6 dev)

### ISSUE THREAD

**Issue by kleuter** [telegramdesktop/tdesktop#674]
Not sure if it was fixed in 0.8.7, this chat is displayed normally after the update.
![sshot-2015-04-25- 10-53-12](https://cloud.githubusercontent.com/assets/2600624/7332319/241659b0-eb3a-11e4-96ca-03877f343dfc.png)
Windows 8.1 x64

**Comment by cobalto** [comment]
Exactly the same as #670, as it seems

**Comment by auchri** [comment]
Is this still the case? If yes, reopen the issue
