### ISSUE TITLE
Create a link clicked notification

### ISSUE THREAD

**Issue by RamiMohammedSeid** [telegramdesktop/tdesktop#6740]

**Comment by RamiMohammedSeid** [comment]
What the f***
Get your s*** together 23rd

**Comment by RememberTheAir** [comment]
@RamiMohammedSeid lol what? I can't even tell what is this issue about. The title doesn't mean anything. Not only you decided to not use any of the templates GitHub prompted you, you also decided that not including _any_ description to the issue what a good idea. No wonder this issue has been marked as invalid, it makes it look like you have no interest in whatever you were trying to accomplish by opening it. Open a new issue with a decent title and a description using one of the templates. That's basic common sense

**Comment by RamiMohammedSeid** [comment]
It clearly means something.

**Comment by RamiMohammedSeid** [comment]
When someone touches or clicks my link
It doesn't tell me how many people clicked the link or if the link is clicked or not

**Comment by RamiMohammedSeid** [comment]
@RememberTheAir  I know but please reopen it.

**Comment by RamiMohammedSeid** [comment]
I really need to know if my crush clicked my link or not?

**Comment by RamiMohammedSeid** [comment]
> @RamiMohammedSeid lol what? I can't even tell what is this issue about. The title doesn't mean anything. Not only you decided to not use any of the templates GitHub prompted you, you also decided that not including any description to the issue what a good idea. No wonder this issue has been marked as invalid, it makes it look like you have no interest in whatever you were trying to accomplish by opening it. Open a new issue with a decent title and a description using one of the templates. That's basic common sense

Please @RememberTheAir

**Comment by RememberTheAir** [comment]
@RamiMohammedSeid I can't reopen the issue, I'm not a collaborator. Anyway, I doubt Telegram would add such a feature. You should use some link shortener service that also tracks how many time your links have been opened
