### ISSUE TITLE
[Feature Request] Multiple Accounts in the desktop app.

### ISSUE THREAD

**Issue by chirag-jn** [telegramdesktop/tdesktop#6741]
### Describe the solution you'd like
The mobile app supports logging into multiple accounts together at a time. Is there a way in which we can have the same feature on the desktop app too?

### Describe alternatives you've considered
Currently, we can run two accounts in Linux by running one on the desktop app and the other account by using the web app. But this adds to inconvenience sometimes.

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/4261
