### ISSUE TITLE
[Feature Request] "mark all as read" option on archive right-click

### ISSUE THREAD

**Issue by RememberTheAir** [telegramdesktop/tdesktop#6742]
### Is your feature request related to a problem?
Nope

### Describe the solution you'd like
An option in the right-click menu of the "archive" item to mark all my archived chats as read, similarly to what was introduced with Telegram for Android 5.12.1

### Describe alternatives you've considered
None

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/6004
