### ISSUE TITLE
[Bug] Tooltip and hover with notification

### ISSUE THREAD

**Issue by maxoku** [telegramdesktop/tdesktop#6744]
### Steps to reproduce
1. Open Telegram window
2. Open other window that will cover Telegram window
3. Place mouse cursor on the right part of the screen where emoji's are and wait for a notification

### Expected behaviour
A notification appears and that's it.

### Actual behaviour
Along with notification appears also a tooltip of emoji that would be hovered if the Telegram window was on top. After focusing on Telegram window again this emoji is hovered. 
It shows also tooltip of timestamps and hovering titlebar buttons.

### Configuration
Operating system: Windows 8.1
Version of Telegram Desktop: 1.8.15
Used theme: Day

**Comment by AlynxZhou** [comment]
I can confirm this on Arch Linux, not only emoji tooltip, but also time tooltip of the message can show over other windows. This even happens when I put telegram-desktop in on workspace and change to another workspace, it still shows tooltip over other applications.

Plus, if you put cursor on time and switch to another workspace, you cannot reproduce this bug. You can only reproduce this bug when your mouse is not in telegram window and then move to the time position.

**Comment by maxoku** [comment]
Before it appeared only if window wasn't minimized, but now it also happens even if windows is minimized. So it worked on every element that gived tooltip like timestamps. Should probably be more if Telegram had more tooltips. Nevertheless as I mentioned it also hovers the emoji, but not only, titlebar buttons are also effected. I'm e.g. having hovered close button very often. I think it's a more global problem with the hovering and tooltip is an addition.

**Comment by maxoku** [comment]
The same also happened when I was watching a video in Telegram.

**Comment by maxoku** [comment]
Is it fixed?

**Comment by ilya-fedin** [comment]
> Is it fixed?

This is a question for you

**Comment by maxoku** [comment]
Didn't notice lately, but again, I was busy in last few weeks and didn't have much chats on Telegram. Will have to test it, but if no one is is sending me messages then it's not possible.
Besides question is that if anyone even tried to fix it?

**Comment by ilya-fedin** [comment]
> Besides question is that if anyone even tried to fix it?

This issue sounds like a low-level issue from Qt or system window manager, I don't think that this could be fixed by app developers

**Comment by AlynxZhou** [comment]
> > Besides question is that if anyone even tried to fix it?
> 
> This issue sounds like a low-level issue from Qt or system window manager, I don't think that this could be fixed by app developers

However I never saw this problem on other programs...strange thing

**Comment by ilya-fedin** [comment]
> However I never saw this problem on other programs...strange thing

It is clear that tdesktop can't show tooltips on the top of other program if the system or Qt don't send these events, tdesktop doesn't ask Qt for them and, thus, the issue is on Qt or system side

**Comment by AlynxZhou** [comment]
> > However I never saw this problem on other programs...strange thing
> 
> It is clear that tdesktop can't show tooltips on the top of other programs if the system or Qt don't send these events, tdesktop doesn't ask Qt for them and, thus, the issue is on Qt or system side

We already got different system here, if we can check other Qt programs it will be better, but this bug hardly shows recently.

**Comment by ilya-fedin** [comment]
> but this bug hardly shows recently

Qt updates from time to time, so this could be already fixed

**Comment by AlynxZhou** [comment]
> > but this bug hardly shows recently
> 
> Qt updates from time to time, so this could be already fixed

That will be good, but I am using my desktop PC recently which is using Xorg, and when I got this bug I use laptop which is using Wayland, not sure if it's related.

**Comment by ilya-fedin** [comment]
> and when I got this bug I use laptop which is using Wayland, not sure if it's related.

Qt wayland backend is really unstable
