### ISSUE TITLE
[Feature Request] add support for join in group based on country

### ISSUE THREAD

**Issue by blacklat** [telegramdesktop/tdesktop#6747]
Recently in several groups of telegram users from Asia are entering and leaving the group causing a disturbance to the users of the group. We don't like Asian people, we don't want Asian people in the group, but we want the group to remain public, but only for latin america. Unsurprisingly, asia contributes to the destruction of the internet with scans and 24-hour attacks. No one in the rest of the world has any interest in any Asian sites or keeping in touch with anyone there. Please add the option to keep the group public but you can choose the allowed countries or just choose the denied ones. For sure if this option is made all Asian countries will be the most blocked in the telegram groups.

To the Asians reading this message ... We don't like you, we don't want you in our groups, obviously your activity in our groups is hostile, so go the hell and disappear.

**Comment by CzarnaMamba** [comment]
thats harsh

**Comment by blacklat** [comment]
> thats harsh

harsh is asian people doing shit 24 hours and noone does nothing about that

**Comment by zeroone2numeral2** [comment]
This is the worst issue I've stumbled upon here so far

**Comment by blacklat** [comment]
> This is the worst issue I've stumbled upon here so far

me too, this problem is called asian people

**Comment by Olfi01** [comment]
> > This is the worst issue I've stumbled upon here so far
> 
> me too, this problem is called asian people

The problem is called racism my friend

**Comment by MorningSage** [comment]
Yes, I’d agree.. it’s funny that out of the 4 billion people that live in Asia, ALL of them are horrible.  I mean, what are the odds of that?  😳

Oh, and remember all the serial killers that came out of America?  Guess that was just a fluke.  Oh, and Hitler?  Yeah... funny how Asia works...

**Comment by MorningSage** [comment]
[Feature Request]

Block all idiots.  I’m tired of dealing with them.  Can we just have a setting to keep my group public but choose to deny the jerks?  That would be awesome.
