### ISSUE TITLE
IPAD IOS 8.3 & Telegram Messenger APP 2.12: Direktphoto Problem!

### ISSUE THREAD

**Issue by marcoklv** [telegramdesktop/tdesktop#675]
If i try to take & send a photo in Telegram APP with IPAD 2 directly. The App hangs and breakdown. Only one time the APP shows the photo frame and tell me after new start i have to re-send the photo. Re-send was o.k. than but after this the App hangs after taking a photo and try to send direct. 

System: IPad 2 with IOS 8.3
Telegram Messenger App 2.12

**Comment by Katzen-Gott** [comment]
Looks like it's telegram for iOS, not tdesktop.

**Comment by ppparadox** [comment]
Wrong place to report the problem.
