### ISSUE TITLE
[Feature Request] Source tarball with git submodules

### ISSUE THREAD

**Issue by Johnnynator** [telegramdesktop/tdesktop#6750]
The github provided source tarball does not include submodules. It would be nice if you could just manually upload one for newer releases that include them. Just fetching the tarballs for building is quite common for linux distributions (only some do allow falling pack to just use `git clone`). And now having to keep track of 9 more submodules is not really motivating.

**Comment by Aokromes** [comment]
I supose that "issue" belongs to github and not to telegram desktop repo.

**Comment by Johnnynator** [comment]
Debatable. But even if one would say github should provide this features, it is not wrong to ask if @john-preston can provide these tarballs in the mean time. And this is afaik a known "issue" to github that is more or less a wontfix.

**Comment by xvitaly** [comment]
> I supose that "issue" belongs to github and not to telegram desktop repo.

GitHub will not provide full tarballs with submodules due to potential legal issues.

**Comment by john-preston** [comment]
@Johnnynator Please check:

https://github.com/telegramdesktop/tdesktop/releases/download/v1.9.0/tdesktop-1.9.0-full.tar.gz

Is this what you need?

**Comment by Johnnynator** [comment]
Yes, that looks about right.
