### ISSUE TITLE
[Bug] Text highlight color is weird

### ISSUE THREAD

**Issue by Kylmakalle** [telegramdesktop/tdesktop#6751]
## 1.9 beta
![image](https://user-images.githubusercontent.com/24507532/68247969-f65be500-002c-11ea-9e4a-4c1dd1c4eefe.png)

## 1.8.16 
![image](https://user-images.githubusercontent.com/24507532/68248014-0d9ad280-002d-11ea-9c01-6bce143a8ec1.png)

MacOS 10.15 

### [!] NB
This also affects TON Wallet, shared libraries issue? (Wallet 0.9.3)
![image](https://user-images.githubusercontent.com/24507532/68248103-3de27100-002d-11ea-8540-647807bbee34.png)

**Comment by Aokromes** [comment]
cannot reproduce on 1.9.8 on windows.

**Comment by Kylmakalle** [comment]
Fixed by dev at November 12, aka _long time ago_

@Aokromes It was MacOS specific, so don't mark issues with tag if you can't check on the same OS.
