### ISSUE TITLE
Emoji domain links don't work

### ISSUE THREAD

**Issue by LBroe** [telegramdesktop/tdesktop#6752]
When clicking on a link that contains an emoji like 🛩.to (xn--188h.to), nothing happens. Other IDN domains like ö.de (xn--nda.de) work. This relates to #2832, but it works on Telegram mobile now, so it doesn't seem to be a server problem anymore.

### Steps to reproduce
1. Send a message like "🛩.to"
2. Click the link

### Expected behaviour
It should open a the domain or the Punycode version

### Actual behaviour
Nothing happens

### Configuration
**Operating system:** Linux / Windows

**Version of Telegram Desktop:** 1.8.8 / 1.8.15

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/2832

**Comment by LBroe** [comment]
@Aokromes It's not a duplicate, because it's not an api issue any more. If I right-click the link and copy the url, I can paste it into the browser and everything works as expected. It also works on Android.
