### ISSUE TITLE
Numpad doesn't work

### ISSUE THREAD

**Issue by armanatory** [telegramdesktop/tdesktop#6754]
### Steps to reproduce
1. Try to use the Numpad keys anywhere such as entring the local passcode or even type into the message or search box.

### Expected behaviour
Enter the pressed character.

### Actual behaviour
LIke when my Numpad is off. It uses the numbers as the arrow keys. For instance, the "8" key navigates a chat history upper.

### Configuration
Ubuntu 18.04 LTS

**Version of Telegram Desktop:**  1.9 Beta

**Used theme**: Default

**Comment by armanatory** [comment]
The latest update has conveyed this issue for me

**Comment by Aokromes** [comment]
works for me on windows 10 20h1.

**Comment by john-preston** [comment]
Looks like a Qt bug :( https://forum.freecadweb.org/viewtopic.php?style=3&t=35102

**Comment by zevilz** [comment]
Same bug on Debian 10

**Comment by MasterGroosha** [comment]
Just noticed the same on Manjaro Linux

**Comment by john-preston** [comment]
Happened to be my Qt build issue.
