### ISSUE TITLE
[bug] Language switching not work in app

### ISSUE THREAD

**Issue by zevilz** [telegramdesktop/tdesktop#6755]
Language switching not work after update.

### Actual behaviour

I can use only the language that was set at the time the application was launched.

### Configuration

Debian 10 amd64 (xfce4.12 + xxkb)
Version of Telegram Desktop: 1.9 Beta
Used theme: Default

**Comment by BANOnotIT** [comment]
Same issue for me.

# Configuration
Ubuntu 16.04 (Unity 7.4.5)
Version of TD: 1.9 beta
Theme: idunno

**Comment by john-preston** [comment]
https://github.com/telegramdesktop/tdesktop/commit/1a4c1cbbf4ae14108fcf3173acf43640f2885b96 this should fix that one as well.

**Comment by ShepardEG** [comment]
Same issue

Configuration
OS: Ubuntu 18.04 bionic
DE: Unity 7.5.0
WM Theme: Ambiance

**Comment by rakvium** [comment]
Same issue, happens after a delivered update to 1.9.
System restart and application restart does not help.

@john-preston should I reinstall the app or will there be a delivered fix?

**Configuration**
---
OS: Ubuntu 16.04.6 LTS (Xenial)
DE: Unity 7.4.5
Version of TD: 1.9 beta
WM Theme: Ambiance

```
$ file Telegram
Telegram: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/l, for GNU/Linux 2.6.24, BuildID[sha1]=bfadc2114956513fe3b31f4f7f27a48b3469a1a7, stripped
```

**Comment by john-preston** [comment]
@rakvium It will work in the 1.9.1

**Comment by BANOnotIT** [comment]
> @rakvium It will work in the 1.9.1

When will 1.9.1 be delivered?

**Comment by Aokromes** [comment]
already delivered.
