### ISSUE TITLE
"Add to dictionary" should remove red underline from word

### ISSUE THREAD

**Issue by MasterGroosha** [telegramdesktop/tdesktop#6756]
### Steps to reproduce
1. Write a word which would trigger a spell check
2. Right-click on word
3. Choose "Add to dictionary"

### Expected behaviour
Every occurence of chosen word should remove the red underline.

### Actual behaviour
Currently it doesn't show underline only for future occurences of such word. In the example below, I right-clicked on the second "badbadword" and added it to dictionary, then typed the third one.

![изображение](https://user-images.githubusercontent.com/2780044/68282306-7ebca300-008a-11ea-8d22-a9113e65b7a2.png)

### Configuration
**Operating system:** Windows 10
**Version of Telegram Desktop:** 1.9 beta

**Comment by 23rd** [comment]
Actually it removes red underlines if the text has any other wrong words. For example: `badbadword badbadword badbadword verygoodword`. But yeah, this is a bug, thanks.

**Comment by v-kydela** [comment]
@23rd 
@john-preston 

I can still repro this in version 1.9.3. Should the issue be reopened?
