### ISSUE TITLE
[bug] weird custom language packs displaying (scale at 90%)

### ISSUE THREAD

**Issue by RememberTheAir** [telegramdesktop/tdesktop#6757]
### Steps to reproduce
1. **set the scaling rateo to 90%** (I haven't tried with the standard 100% but I guess this is a relevant information)
2. add some custom language packs (edit: just checked from the Android app and it looks like I don't have any custom language pack added. Maybe not just a visual bug?)
2. open the languages menu

### Expected behaviour
The list of language packs is displayed correctly

### Actual behaviour
There is some weird overlapping: https://i.imgur.com/pT23fOV.jpg

### Configuration
**Operating system:** Windows 10

**Version of Telegram Desktop:** 1.9 beta

**Used theme**: matrix

**Comment by Aokromes** [comment]
this bug is still valid on 1.9.8?

**Comment by RememberTheAir** [comment]
It looks like it's fixed
