### ISSUE TITLE
[Question] new spellchecker: selecting a spellchecking language different from the system language

### ISSUE THREAD

**Issue by RememberTheAir** [telegramdesktop/tdesktop#6758]
This is a question: would it be technically possible to make the spellchecker use a language different from my system language, or the same language we've set from Telegram's language settings? I often participate in English discussions while keeping my system language to my native language. The new spellchecker would be much more useful when I'm writing in English rather then when I use my native language

**Comment by p0358** [comment]
For me the spellcheck works for both my system language, and for English, just as those emoji predictions. However, corrected words propositions work only for English. My Telegram language is set to not English as well. Gonna create a separate bug report for this

**Comment by 23rd** [comment]
Now the spellcheck library is checking the supported languages from the `%AppData%\Microsoft\Spelling\` directory. So if you install an additional language through the system settings, it should be picked up by tdesktop.
