### ISSUE TITLE
Neo layout not working properly with 1.9

### ISSUE THREAD

**Issue by Ninja-Koala** [telegramdesktop/tdesktop#6759]
### Steps to reproduce
1.  Activate neo layout (setxkbmap de neo when using x11, or set with gui)
2.  Start Telegram Desktop
3.  Try writing '?' by pressing caps lock and h key at the same time

### Expected behaviour
In example Step 3 it is expected that a '?' is typed.
Generally, all neo layers are expected to work properly, as with Telegram Desktop version 1.8

### Actual behaviour
An 's' is typed in the example.
Generally, all neo layers above 2 behave the same as layer 1.
This means I'm able to write normal letters in lowercase and uppercase,
but i can write nearly no special characters.
Probably other alternative layouts are affected as well.
I also noticed that changing the keyboard layout after opening telegram desktop
doesn't have an effect, i think this might be related.
See https://en.wikipedia.org/wiki/Keyboard_layout#Neo
for further information.

### Configuration
**Operating system:** Arch Linux

**Version of Telegram Desktop:** 1.9 Beta

**Used theme**: Classic

**Comment by Johnnynator** [comment]
Maybe same cause as https://github.com/telegramdesktop/tdesktop/issues/6754 ?

**Comment by Ninja-Koala** [comment]
Probably. In any case, this was fixed with Beta version 1.9.1
