### ISSUE TITLE
[Feature Request] Add contacts from file and right-click menu

### ISSUE THREAD

**Issue by rutja76** [telegramdesktop/tdesktop#676]
Two issues in one post:
- It would be nice if there were an option for adding contacts from file, e.g. from .vcf files. Otherwise it's a kind of a burden to have phone contacts imported if one uses only Telegram Desktop (the only option is adding them manually one by one)
- There is no right click menu on contacts, and that could be an improvement to the desktop version which actually now resembles a version for touch-screen devices more than a software for computers.

**Comment by kireledan** [comment]
I've implemented the right click menu in my fork. I'll submit a PR soon once I do more cleanup. Right now I have Open conversation and Delete. Anything else I should add to the right click menu?

**Comment by Walkman100** [comment]
> Anything else I should add to the right click menu?

Adding here since I've found I could've done with right-click menu options:
- Contact info
- copy username
- edit contact/chat name
- delete (contact)/leave (chat)
- view shared media
- view (profile) image

**Comment by kireledan** [comment]
Implemented in PR #774

**Comment by auchri** [comment]
Context menu added with v 0.9.15 stable

Feel free to open a new issue for adding contacts from files if you think that's important.

**Comment by Walkman100** [comment]
WOOH :tada:

**Comment by easy-o** [comment]
please,

can s.o. open a new issue for adding contacts from files?

**Comment by mdan312** [comment]
Related: #4696
