### ISSUE TITLE
Notifications popping up from wrong place in Linux Mint

### ISSUE THREAD

**Issue by feralheart** [telegramdesktop/tdesktop#6761]
### Steps to reproduce
1. Install Linux Mint
2. Install Telegram
3. Get a message

### Expected behaviour
It should use the built in notification place (popping up from upper right corner)

### Actual behaviour
Popping up from lower right corner

### Configuration
**Operating system:**
Linux Mint With Cinnamon destkop

**Version of Telegram Desktop:**
1.8.15

**Used theme**:
Dark theme

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/3831 ?

**Comment by feralheart** [comment]
Sry, I didn't seen that there is already an issue for that. Thank you for pointing it out :)
