### ISSUE TITLE
Regression: Shift+Enter is not working in 1.9 beta for GNU/Linux

### ISSUE THREAD

**Issue by bodqhrohro** [telegramdesktop/tdesktop#6762]
### Steps to reproduce
1. Open a chat.
2. Type a line.
3. Press Shift+Enter.

### Expected behaviour
A newline is inserted.

### Actual behaviour
Nothing happens.

### Configuration
**Operating system:** Debian GNU/Linux 11

**Version of Telegram Desktop:** 1.9 beta

**Used theme**: Classic

**Comment by bodqhrohro** [comment]
There are also other input issues. Combinations like Shift+arrows, Shift+Home don't work as well.

Keyboard layouts also work strange. I have three of them: English, Russian and Ukrainian, and set Loloswitcher up to enable them by pressing LShift, RShift, and AltGr respectively. First two work well, but when I press AltGr, the Ukrainian layout seems to be enabled, according to the indicator, but Latin characters are actually typed. And when AltGr is held to call the third row, the Ukrainian characters from the first row are actually typed, and thus the real third row (with Russian, Belorussian letters, and typographical symbols) is inaccessible. Pretty interesting bug, is all of this related to https://github.com/telegramdesktop/tdesktop/issues/6754?

**Comment by Aokromes** [comment]
works for me on debian 10 and telegram desktop 1.9.8 on spanish locales.
