### ISSUE TITLE
Regression: libnotify support is gone in 1.9 beta for GNU/Linux

### ISSUE THREAD

**Issue by bodqhrohro** [telegramdesktop/tdesktop#6763]
### Steps to reproduce
1. Receive a notification.

### Expected behaviour
The notification is displayed via libnotify.

### Actual behaviour
The setting for native notifications is gone, and thus notifications can be displayed only in a builtin way. `ldd ~/.TelegramDesktop/Telegram` doesn't even show libnotify, so it's completely gone from the build.

### Configuration
**Operating system:** Debian GNU/Linux 11

**Version of Telegram Desktop:** 1.9 beta

**Used theme**: Classic

**Comment by john-preston** [comment]
@bodqhrohro Libnotify was loaded in runtime before, it was never in ldd.

**Comment by bodqhrohro** [comment]
Hmm, looks like the freeze of `dunst` was the issue. The native notifications support returned back after Telegram restart. Sorry for disturbance.
