### ISSUE TITLE
1.9.1 beta issue:Telegram.exe - Entry Point Not Found

### ISSUE THREAD

**Issue by CNMan** [telegramdesktop/tdesktop#6765]
1.9.1 beta can't work on Windows Embedded PosReady 2009, 1.8.15 works fine.

```
Telegram.exe - Entry Point Not Found

The procedure entry point GetUserPreferredUILanguages could not be located in the dynamic link library KERNEL32.dll.
```

**Comment by john-preston** [comment]
@CNMan I'm sorry, I guess the support for that OS ended together with Windows XP and Vista.

https://docs.microsoft.com/en-us/windows/win32/api/winnls/nf-winnls-getuserpreferreduilanguages

It tells that this function is available starting with Windows Vista.
