### ISSUE TITLE
Spellchecking does not propose corrected words in my system language

### ISSUE THREAD

**Issue by p0358** [telegramdesktop/tdesktop#6767]
### Steps to reproduce
Working:
1. Perform a typo in English (non-typo words are not underlined)
2. Typo gets underlined correctly
3. Right-click it to see proposed word corrections, they're in English as expected

Bug:
1. Perform a typo in system language that is different from English (non-typo words are not underlined)
2. Typo gets underlined correctly
3. Right-click it to see proposed word corrections, they're in English, there are no corrections for the system language, while the typo itself is an easy one to correct

### Expected behaviour
See corrections in my language as well

### Actual behaviour
Actually, upon further testing, it seems that it does indeed display corrections in my language, but only if there are not enough English ones.
So, it first gives any available English corrections, then falls back to the other language.
Expected behaviour would be then to sort them by their similiarity to the typo'ed word.

**Example 1:**
for word "**bylem**", you get: `xylem, bylaw, beam, bye, Belem`
the correct word "**byłem**" is clearly far more similiar to the typo than some of those English corrections

**Example 2:**
for word "zrobic", from English propositions you only get: `sorbic`
thus, you also get to see the expected correction in the expected language: **`zrobić`**
so the list is: `sorbic, zrobić`
and then ideally, after similiarity-based sorting, it'd be in this order: `zrobić, sorbic`

### Configuration
**Operating system:** Windows 10 1903 (18362.356)

**Version of Telegram Desktop:** 1.9.1 beta

**Used theme**: shouldn't really matter

<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
Let me know if it would really help in this case at all
</details>

**Comment by maxoku** [comment]
There's even greater problem than English words coming before Polish. It can also show suggestions from a language that isn't installed on the system. E.g. benz**è** or bad**à** appeared while they have national letters that are neither English or Polish. Clearly a bug.

**Comment by Aokromes** [comment]
try on 1.9.19.

**Comment by maxoku** [comment]
@Aokromes 
I just checked that I don't get any suggestions for underlined words in that beta 🤨

**Comment by p0358** [comment]
Not much has changed, besides other languages installed in the system also being recognized (resulting in even more clutter due to described issue, as could be seen in example 2 for me).
Example 1, the most iconic I think, stays exactly the same.
@maxoku The suggestions are not hidden in a sub-menu

**Comment by maxoku** [comment]
@p0358 haha, thanks I need new glasses lol why is it on the bottom though? :thinking: 
For word `bylem` I have: belem, bulim*, ble, balim*, ballem.
For word `zrobic` I have: robis*, trobis*, robi, r**à**bic*, robin.
`*` means it's a word that is not in Polish or English (underlined in the browser).

**Comment by 23rd** [comment]
I think it should be better in the latest stable version.

**Comment by maxoku** [comment]
Yeah, seems to be better now.

**Comment by p0358** [comment]
Yep, it does seem to be better. For the two examples I provided, I now get the expected correction as the first one 👍

**Comment by p0358** [comment]
So I think I can close it, to decrease the number of opened issues on this repo
