### ISSUE TITLE
[Bug][GNOME 3][IBus] Input method character selector pop-up does not appear

### ISSUE THREAD

**Issue by cty12** [telegramdesktop/tdesktop#6769]
### Steps to reproduce
1. Launch Telegram desktop. Focus the cursor onto any chat box. 
2. Type using `ibus-libpinyin`.

### Expected behaviour

Character selector is expected to pop-up. 

### Actual behaviour

No ibus character selector UI. 

### Configuration
**Operating system:**

Fedora 31
GNOME 3.34
Intelligent Pinyin 1.11.1

**Version of Telegram Desktop:**

1.8.15

**Used theme**:

None. 

<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/2013
