### ISSUE TITLE
OS X bug when closing fullscreen window

### ISSUE THREAD

**Issue by pedroadame** [telegramdesktop/tdesktop#677]
Hi, the default app behavior in OS X fullscreen mode is when clicking the red 'X' it moves to the normal space. Telegram Desktop keeps in a separate space with full black background.

**Comment by ryush00** [comment]
<img width="1280" alt="2015-09-24 7 32 47" src="https://cloud.githubusercontent.com/assets/4997174/10071247/47f35ad2-62f3-11e5-8a3d-00aaa38a844e.png">

__The Scary Screenshot__

We can see notifications and click them to reopen window.

**Comment by stek29** [comment]
Anything new about this issue?

**Comment by Aokromes** [comment]
this bug is still valid on 1.9.8?

**Comment by Aokromes** [comment]
no answer after near 1 month, if this bug is still valid, open a new ticket with one updated telegram version downloaded from desktop.telegram.org or github.com
