### ISSUE TITLE
Secret chats still NOT working in Desktop app

### ISSUE THREAD

**Issue by andriusign** [telegramdesktop/tdesktop#6770]
Testing Telegram 1.9.1 beta on Linux Mint 19.2. There is no secret chat option. I guess that many of the previous answers in numerous threads about this issue are convincing me NOT to use Telegram anymore. Sad...

**Comment by Aokromes** [comment]
#871

**Comment by andriusign** [comment]
Shame on you Aokromes! Really big shame.

**Comment by aBARICHELLO** [comment]
`telegram-cli` supports secret chat: https://github.com/kenorb-contrib/tg
