### ISSUE TITLE
Secret chats NOT being fixed!

### ISSUE THREAD

**Issue by andriusign** [telegramdesktop/tdesktop#6771]
Since this is not being fixed #[871](https://github.com/telegramdesktop/tdesktop/issues/871)
 and the thread is closed please take at least some responsibility to finally implement secret chat functionality or tell your users to f*o.

Testing Telegram 1.9.1 beta on Linux Mint 19.2. There is no secret chat option. I guess that many of the previous answers in numerous threads about this issue are convincing me NOT to use Telegram anymore. Sad... Anyone who is concerned about their privacy should look for other solutions instead of Telegram. This app is a complete disaster when it comes to securing your conversations.

**Comment by Aokromes** [comment]
this is still a duplicate ticket of #871

**Comment by andriusign** [comment]
Shame on you @Aokromes at least open #871 for discussion.

**Comment by RememberTheAir** [comment]
@andriusign okay so let me translate it for you: secrets chats on desktop are not in the plans of Telegram for now. No amount of upvotes on GitHub issues is going to make them change their mind. You are free to use anything else that fits your need

**Comment by andriusign** [comment]
Sad of course. Thanks for actually taking your time to answer this thread :) Testing Riot.im now.

**Comment by damnfella** [comment]
There is Unigram, which uses Secret Chats. You should try that if you really are in need of secret chats..

**Comment by andriusign** [comment]
Nah, I think I'll stay with Riot.im. :lock:
