### ISSUE TITLE
[Feature Request] Optionally display the profile photo for the blocked users

### ISSUE THREAD

**Issue by axionl** [telegramdesktop/tdesktop#6772]
### Is your feature request related to a problem?
Hidden the profile photo for the blocked users is too obvious for the user who could know the status at once. You may just not want to have a private chat in a short time with someone rather than a group chat which would be influenced by no avatar.

### Describe the solution you'd like
Add an additional profile image options to display it for the blocked users.

**Comment by axionl** [comment]
I think I found a solution.

**Comment by yashpalgoyal1304** [comment]
care to share the solution here?
