### ISSUE TITLE
"default interface scale" setting resets after reboot

### ISSUE THREAD

**Issue by marcomilone** [telegramdesktop/tdesktop#6773]
1. Boot computer 
2. Open Telegram

### Expected behaviour
"default interface scale" setting should not reset after system reboot

### Actual behaviour
"default interface scale" setting resets to 100% after system reboot
Does not reset after re launch

### Configuration
**Operating system:**
Ubuntu 19.10

**Version of Telegram Desktop:**
1.9.1 beta

**Used theme**:
night

**Comment by olo81** [comment]
I have the same

I will add that this is not always the case

**Comment by marcomilone** [comment]
I found a clue.

After a fresh restart
Telegram is loaded (with wrong interface scale).

If I close and re-open (without touching anything),
it loads with the right scale.

**Comment by the-spyke** [comment]
Also, if I unset `Default interface scale` and set 200% manually, after rebooting Telegram will open in 100%. And this time after I set 200% again, the `Default interface scale` option gets on by itself.
