### ISSUE TITLE
Unable to disable notifications for stickers

### ISSUE THREAD

**Issue by SGOrava** [telegramdesktop/tdesktop#6774]
# Steps to reproduce
1. Install telegram desktop on Linux
2. Enable native notifications
3. Go to some chat group and disable notifications for it
4. Let someone send stickers (those scary huge images which break the conversation)

### Expected behaviour
Nothing, to be precise no notification of any kind from the channel with disabled notifications unless I am directly mentioned.

### Actual behaviour
Notification is shown for each sticker posted in group with disabled notifications.

### Configuration
**Operating system:** Arch Linux

**Version of Telegram Desktop:** 1.8.15

**Used theme**: Night mode (are there other themes ?)

**Comment by Aokromes** [comment]
this bug is still valid on 1.9.8?

**Comment by SGOrava** [comment]
who knows ?

**Comment by Aokromes** [comment]
i don't have arch to test, if this bug is still valid plz confirm, if no answer i will close this ticket next week.

**Comment by SGOrava** [comment]
probably not.
