### ISSUE TITLE
Folders in explorer disappears when file saving after ~1gb used RAM

### ISSUE THREAD

**Issue by Neurotoxin001** [telegramdesktop/tdesktop#6777]
### Steps to reproduce
1. use telegram for some time
2. when app will use ~1gb of ram try to save some file in some folder
3. left side of explorer with folders will disappear

### Configuration
**Operating system:** win10 ltsc 1809

**Version of Telegram Desktop:** 1.9.1 beta

**Used theme**: default dark

![image](https://user-images.githubusercontent.com/39812401/68576720-a2635d00-047f-11ea-83b6-197503c14fec.png)
![image](https://user-images.githubusercontent.com/39812401/68576767-bc9d3b00-047f-11ea-8fea-163c78bea1f0.png)
https://i.imgur.com/Bh75YrT.mp4

And only restart is helps:
![image](https://user-images.githubusercontent.com/39812401/68576827-e8202580-047f-11ea-823c-fbab876dd243.png)
![image](https://user-images.githubusercontent.com/39812401/68576864-f8d09b80-047f-11ea-80cc-94d1bb04b5dc.png)
https://i.imgur.com/3Delpzl.mp4

**Comment by Neurotoxin001** [comment]
Plus to this effect I notice the new:

I can't click links. And restart is helps. All problems appears when Telegram start eating 1gb+ RAM

![image](https://user-images.githubusercontent.com/39812401/71502118-3b5b0580-287f-11ea-87f3-1b78c8be0516.png)

**Comment by Aokromes** [comment]
this bug is still valid?

**Comment by Neurotoxin001** [comment]
Seems like it's fixed. Didn't notice that since about 1.9.6

**Comment by Neurotoxin001** [comment]
Nope, not fixed in 2.1.4 even with 800mb of used RAM

**Comment by Neurotoxin001** [comment]
This issue is still here too https://github.com/telegramdesktop/tdesktop/issues/6777#issuecomment-569188729
