### ISSUE TITLE
[Feature Request] Option to see Usernames when looking at member lists.

### ISSUE THREAD

**Issue by damnfella** [telegramdesktop/tdesktop#6779]
_This suggestion came from another user in [Telegram Desktop Talk](https://t.me/TelegramDesktopTalk)_
## Names are not unique.
**I require usernames to be a member of my groups and should not have to click on each profile to see if they have one.** I have seen members change their screen names like dirty underwear to hide.

Names aren't unique. There could be many with the same name. Optionally, display by Usernames which are unique would have a benefit to many.

### There is ENOUGH screen space on desktops
![photo_2019-11-12_01-03-05](https://user-images.githubusercontent.com/51771172/68615042-3ff27700-04e8-11ea-83c8-f4719b929a40.jpg)
This dialog box could get bigger when fully maximized. Usernames next to last seen time, more than enough.

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/549

**Comment by damnfella** [comment]
umm, **nickname != username** 🙄

**Comment by Aokromes** [comment]
fixed :P
