### ISSUE TITLE
Autostart for Flatpak release

### ISSUE THREAD

**Issue by busukxuan** [telegramdesktop/tdesktop#6780]
### Is your feature request related to a problem?
Currently, I use Telegram Desktop through Flatpak. It seems there is no autostart feature to run Telegram on startup. I am aware of this other request #422, but I think the Flatpak solution is much different from the traditional Linux desktop solution.

### Describe the solution you'd like
Some simple and user-friendly way to tell Telegram to autostart on desktop login. I'd prefer autostart by default and opt-out as opposed to opt-in. I suggest using the Flatpak's new Background portal, which was discussed here: https://github.com/flatpak/flatpak/issues/118. According to that page, the portal's interface documentation is here: https://github.com/flatpak/xdg-desktop-portal/blob/master/data/org.freedesktop.portal.Background.xml#L34.

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/commit/2a9023479faeadc6b63c640c0f43dee14f831307 does the job for you?

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/commit/05eabfd539c99b0983c134527a2640e91fed0aca
