### ISSUE TITLE
Game players results in supergroup

### ISSUE THREAD

**Issue by Remu-rin** [telegramdesktop/tdesktop#6781]
### Steps to reproduce
1. Open supergroup and find a message with a game that members played

### Expected behaviour
Results should show up

### Actual behaviour
Often there is no results, starting from 1.8.0 version

### Configuration
**Operating system:** Windows

**Version of Telegram Desktop:** 1.9.1

**Comment by john-preston** [comment]
@Remu-rin Please check if they are there in older versions, like 1.7.*

You can download older versions from the github releases page.

**Comment by Remu-rin** [comment]
@john-preston I checked 1.7.15, it's ok. Seems like something between 1.7.15 and 1.8.0.

**Comment by john-preston** [comment]
@Remu-rin Can you provide an example in some public group? Or all of the examples are private?

**Comment by Remu-rin** [comment]
@john-preston Found public example: https://t.me/tginfochat/285948 and actually any game in that group ("top players" in search field).

**Comment by john-preston** [comment]
@Remu-rin I've found the bug, thanks. It should be fine in the next version.
