### ISSUE TITLE
[Feature Request] Hide emoji button option

### ISSUE THREAD

**Issue by seadz** [telegramdesktop/tdesktop#6783]
### Is your feature request related to a problem?
Emoji button on input string often is accidentally hovered by mouse and big list of emojis pops up
Many people doesnt use any amoji at all and this popup can be annoing.

### Describe the solution you'd like
Add option to hide emoji button. Or hide it when user uncheck all of emoji iptions in settings.

**Comment by Hexaae** [comment]
... AND add option to delay/disable annoying instant-popup on Emoji button please!

**Comment by hooramin** [comment]
> ... AND add option to delay/disable annoying **instant-popup** on Emoji button please!

The times it covers my screen, I just want to hit my head to the wall !

**Comment by Sopor** [comment]
Or make it only popup when the button is pressed. Now it is so annoying when it popups only by hover the mouse over it :(

**Comment by Volutar** [comment]
UI option item with "hover / click to open smiley menu" would cover almost everyone's needs.
Hover = with delay of 200ms, click = open side menu (as we see, but with delay)
Click = open menu with click (not aside, as option above, anyone willing this type - would switch to Hover and click). Next click - hides menu.

That simple.

**Comment by Hexaae** [comment]
I really don't understand what are the devs waiting for ignoring one of the **most wanted** feature.

**Comment by nr1995** [comment]
Just make it so it needs to be CLICKED to open.
No, just give us the OPTION.
It spreads itself over my screen unintentionally like 30 times a day.
It's like the corpse of rotting roadkill in the middle of an otherwise immaculately-designed app.
How many times does this issue need to be opened to get taken seriously?

**Comment by Eric-01** [comment]
A good workaround would be to make the emoji popup appear only when a user hovers over the button for a short period of time (now it is instant). Easy to do and effective.

**Comment by Eric-01** [comment]
IMO the best workaround would be to make the emoji popup appear only when a user hovers over the button for a short period of time (now it is instant). Easy to do and effective enough.

**Comment by kocane** [comment]
For the love of God, at least add an delay to that damn button.

**Comment by RememberTheAir** [comment]
Beta 3.5.3 has an option under `settings -> advanced -> experimental` to activate the emoji panel on click only

**Comment by Sopor** [comment]
It seems that i was forced to enable `update automatically` for it to show up.

Thanks @RememberTheAir!

**Comment by Ternvein** [comment]
And still no option to disable or switch from mouse-hover to click.

**Comment by Aokromes** [comment]
> And still no option to disable this button or switch from mouse-hover to click.

https://i.imgur.com/KKylJV0.png

**Comment by Hexaae** [comment]
> It should be here (sorry for the weird crop but I've tried to hide my stuff without editing the clip):
> 
>  2022-03-02_08-43-11.mp4

I don't have Version and update section in the Advanced options... I downloaded it from MS Store, Telegram Desktop 4.0 x64.

**Comment by Aokromes** [comment]
you need to download from webpage and enable updates and maybe beta.

**Comment by Hexaae** [comment]
Yes, this is what I did but I hope this ESSENTIAL option will appear also on the MS Store version...
