### ISSUE TITLE
Links and text is verticals

### ISSUE THREAD

**Issue by sinneren** [telegramdesktop/tdesktop#6786]
### Steps to reproduce
1. Don't know, local issue

### Actual behaviour

![scrennshot](https://user-images.githubusercontent.com/696609/68773458-a25c8c00-063c-11ea-823c-bd3c05060ac7.png)

### Configuration
**Operating system:**
Linux Mint 19.1
Linux version 4.15.0-66-generic (buildd@lgw01-amd64-044) (gcc version 7.4.0 (Ubuntu 7.4.0-1ubuntu1~18.04.1)) #75-Ubuntu SMP Tue Oct 1 05:24:09 UTC 2019

**Version of Telegram Desktop:**
1.8.15

**Used theme**:
Any

**Comment by 2martens** [comment]
I can confirm this problem. On my machine a similar problem can be observed.
Linux Mint 19.2
Linux version 4.15.0-66-generic

Telegram Desktop Version: 1.8.15

**Comment by Aokromes** [comment]
i am sure this is duplicate, but cannot find the other.

**Comment by 23rd** [comment]
@Aokromes #6723?

**Comment by sinneren** [comment]
Ok, rebuild, I understand. But how to do it simply? I am win user, but must using mint for developers instances and dont know anything about unix.

**Comment by Aokromes** [comment]
try downloading 1.9.1 beta.
