### ISSUE TITLE
So many scams use fake "Official Group", so let's set Grou Invite default to "My contacts"

### ISSUE THREAD

**Issue by cnukaus** [telegramdesktop/tdesktop#6787]
### Is your feature request related to a problem?
I have record of 5+ people that I know or heard of, being victim of "official exchagne groups", and lost dozens of ETH..

This is partially because they were added to scam groups that they thought are "official group" of exchanges

### Describe the solution you'd like
Change default of "Who can add me to groups and channels" to "My contacts",

### Describe alternatives you've considered
or Even better. a white list check box by default is blank or only the most recent contact

**Comment by Aokromes** [comment]
i suggested this long time ago... but it doesn't belong here.
