### ISSUE TITLE
[Feature Request] [Linux] Implement systray icon via Status Notifier 

### ISSUE THREAD

**Issue by andrey-krutov** [telegramdesktop/tdesktop#679]
KUbuntu 15.04 ships with new KDE5. The KDE5 developers drops old systray implementation via xembed. Now they use Status Notifire API (http://api.kde.org/frameworks-api/frameworks5-apidocs/knotifications/html/classKStatusNotifierItem.html). So  there is no tray icon anymore in KDE5.

Related links
http://blog.martin-graesslin.com/blog/2014/03/system-tray-in-plasma-next/
http://blog.martin-graesslin.com/blog/2014/06/where-are-my-systray-icons/

**Comment by focuz** [comment]
Confirmed... This Plasma5/KDE5 issue needs to be addressed a.s.a.p. since Kubuntu 15.05, Netrunner 15, along with some other distros, now ship with Plasma 5.

**Comment by AndydeCleyre** [comment]
Related to #516.

**Comment by xpumax** [comment]
any progress on this?

**Comment by AndydeCleyre** [comment]
Fixed with 0.8.45!

**Comment by datamaan** [comment]
Awesome! Thanks a lot.

2015-08-03 17:31 GMT+02:00 Andy Kluger <notifications@github.com>:

**Comment by focuz** [comment]
The change log ought to be a bit more specific than "Bug fixes and other minor improvements", but thanks for properly implementing this much needed functionality!
