### ISSUE TITLE
[Feature Request] Hungarian translate is totally done, when it will be in Telegram?

### ISSUE THREAD

**Issue by forraskod** [telegramdesktop/tdesktop#6790]
The Hungarian translation is here: https://translations.telegram.org/hu/. Totally translated for some time past.
There will be in Telegram as default?

**Comment by Aokromes** [comment]
https://t.me/setlanguage/hu-beta it's beta.

**Comment by damnfella** [comment]
this seems more of a question 🤔

**Comment by forraskod** [comment]
> https://t.me/setlanguage/hu-beta it's beta.

It's not beta; translators can't change the link. Otherwise it's done for a long time.

**Comment by forraskod** [comment]
> this seems more of a question thinking

What do you mean?

**Comment by damnfella** [comment]
> What do you mean?
Well, this issue is labelled as feature request, instead of a question 🤔

**Comment by Aokromes** [comment]
anyway, being cloud the translations, very likely aren't related to telegram desktop per se.
