### ISSUE TITLE
[Feature Request] Chinese/Asian language search support

### ISSUE THREAD

**Issue by mrr010** [telegramdesktop/tdesktop#6792]
https://github.com/telegramdesktop/tdesktop/issues/564
https://github.com/telegramdesktop/tdesktop/issues/1562
https://github.com/telegramdesktop/tdesktop/issues/1834
https://github.com/DrKLO/Telegram/pull/629

All the information you need is in the above related links
Chinese/Asian language search support is needed.
Thanks.

**Comment by Haruhi-su** [comment]
Yes, we need Chinese search

**Comment by Aokromes** [comment]
https://bugs.telegram.org/c/724
