### ISSUE TITLE
Cannot create a hyperlink with IP address

### ISSUE THREAD

**Issue by RadRussianRus** [telegramdesktop/tdesktop#6794]
## Steps to reproduce
1. Open "Create link" from context menu or Ctrl+K in message field
2. Try to create link with http://1.1.1.1/ or https://1.1.1.1/ as URL

### Expected behaviour
Hyperlink should be created, like in both default Android client and TGX, and can be sent in message,

### Actual behaviour
URL field is highlighted red, indicating that link is incorrect.

### Configuration
**Operating system:** Windows 10 x64
**Version of Telegram Desktop:** 1.9.1 beta

**Comment by damnfella** [comment]
Yes. I can confirm this.

**Comment by RadRussianRus** [comment]
Not fixed in 2.4.4.

**Comment by RadRussianRus** [comment]
Still revelant, since it's not fixed in 2.7.5.
