### ISSUE TITLE
Bots commands appear after "/" which comes after emoji

### ISSUE THREAD

**Issue by Senderman** [telegramdesktop/tdesktop#6796]
### Steps to reproduce
1. type any text in chat with bots that have declared commands in BotFather
2. put any emoji after your text, then put /
3. profit

### Expected behaviour
Commands suggestion should not appear (if you put "/" after text, it wouldn't)

### Actual behaviour
It appears

### Configuration
**Operating system:**
Archlinux
**Version of Telegram Desktop:**
1.8.15 from Arch Repo
**Used theme**:
Custom
<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by aNNiMON** [comment]
Another way:
Copy copy to clipboard any text with line break, paste this text from clipboard and type "/"
![image](https://user-images.githubusercontent.com/1321838/68993588-77637980-0882-11ea-94b1-265fdd1ecf2e.png) pasted "test\n"
![image](https://user-images.githubusercontent.com/1321838/68993601-a0840a00-0882-11ea-90f4-e14fadf59018.png) typed "/"

**Comment by Aokromes** [comment]
this issue is still valid?

**Comment by Senderman** [comment]
yes, both with emoji and line break

**Comment by Senderman** [comment]
This problem still exists!

**Comment by Senderman** [comment]
Still exists on 2.7.1

**Comment by Vezono** [comment]
Still exists on 3.2.4

**Comment by aNNiMON** [comment]
Looks like it's not reproducible anymore.

**Comment by Senderman** [comment]
Not reproducible on 4.3.4
