### ISSUE TITLE
Spell check has problems with Chinese.

### ISSUE THREAD

**Issue by redapple0204** [telegramdesktop/tdesktop#6797]
### Steps to reproduce
1.Open your telegram client 
2. Enter Chinese

### Expected behaviour
There should be no red underline under Chinese.

### Actual behaviour
A red underline will appear under all Chinese.

### Configuration
**Operating system:Windows10 LTSB 2015**

**Version of Telegram Desktop:1.9.1**

**Used theme**:default

### Picture

![photo_2019-11-16_18-06-19](https://user-images.githubusercontent.com/16254644/68994035-14d9a000-08b9-11ea-9561-b2944c7e9a31.jpg)

**Comment by 23rd** [comment]
Should be fixed in the latest beta (1.9.2).
