### ISSUE TITLE
[Question]  Is it possible forward message to multiple users ?

### ISSUE THREAD

**Issue by Partizanin** [telegramdesktop/tdesktop#6798]
I tried to resend message to several user, but when i click on first user, it open our chat with him and do not allow me to choose other users.

![image](https://user-images.githubusercontent.com/5072597/69009317-d5648f80-095c-11ea-974e-5f7516821b29.png)

![image](https://user-images.githubusercontent.com/5072597/69009320-ddbcca80-095c-11ea-8d0a-9b35a469907e.png)

![image](https://user-images.githubusercontent.com/5072597/69009322-e1e8e800-095c-11ea-961e-ad446a75deb3.png)

**Comment by Aokromes** [comment]
no on desktop, you need to use android for that.

**Comment by RadRussianRus** [comment]
There is Fast Share for channel posts, which supports multiple chat sharing. It would be nice to enable this for all types of forwards.

**Comment by Aokromes** [comment]
indeed, idk why there are 2 message forward systems.

**Comment by Partizanin** [comment]
может быть, имеет смысл создать проблему ?

**Comment by Partizanin** [comment]
maybe it makes sense to create issue?

**Comment by kirsan31** [comment]
https://github.com/telegramdesktop/tdesktop/issues/1841

**Comment by Partizanin** [comment]
@kirsan31 nice, thanks
