### ISSUE TITLE
Do not create a .desktop file from binary.

### ISSUE THREAD

**Issue by ManuelSchneid3r** [telegramdesktop/tdesktop#680]
Instead ship it with the downloaded files or if you want it to be created by the binary let it be made manually with an option. E.g. "telegram --desktop-file".

The placement of this file is up to the packagers and atm the genreated file pollutes the start menu if the binary and desktopfile is installed systemwide.

**Comment by ManuelSchneid3r** [comment]
Same as #933

**Comment by dielsonsales** [comment]
That's the way packages should work. I think it's weird that Telegram creates itself a .desktop file, and even overrates the previous one if you've editted it.

**Comment by auchri** [comment]
Duplicate #933
