### ISSUE TITLE
Orange app highlight stays after reading messages on mobile

### ISSUE THREAD

**Issue by tooomm** [telegramdesktop/tdesktop#6800]
### Steps to reproduce
1. Receive messages
2. Get notification on both, mobile and desktop
3. Read messages on mobile
4. Check desktop

### Expected behaviour
No more leftovers from the already read messages elsewhere. All goes back to normal, same as if I would have read the messages on Desktop.

### Actual behaviour
Badges are gone 👍
The app icon in the superbar has still a flashy orange background 👎 
![orange_highlight](https://user-images.githubusercontent.com/9874850/69040319-e9a49d00-09ed-11ea-874e-88cfa82e62ca.png)

I don't recall if the app pulled itself out of the task bar in the lower right. If yes, it should go back there!

Might be connected to https://github.com/telegramdesktop/tdesktop/issues/6053.

### Configuration
**Operating system:** Windows 10 64bit

**Version of Telegram Desktop:** 1.8.15

**Used theme**: Default

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/5280
