### ISSUE TITLE
Is it ok that tdesktop uses 20% of my GPU resources ?

### ISSUE THREAD

**Issue by foremtehan** [telegramdesktop/tdesktop#6801]
Operating system: Windows 10

Version of Telegram Desktop: 1.18.15

Today i realised every time i click on any chat in telegram desktop it uses 20% of my GPU resources

Proof:

Without selecting a chat :

![Capture](https://user-images.githubusercontent.com/53290883/69054048-05c13200-0a20-11ea-987e-5ae5f09d844f.jpg)

**But as soon as i select an chat** :

![Captureasdasdsadasd](https://user-images.githubusercontent.com/53290883/69054059-0b1e7c80-0a20-11ea-83ad-e08efb0dba5d.jpg)

**Comment by Aokromes** [comment]
cannot reproduce
https://i.imgur.com/O4pKEO7.png

**Comment by foremtehan** [comment]
Swear to god as i have created this ticket the issue has gone someone in tdesktop are mining crypto with user resources

**Comment by Aokromes** [comment]
i doub you can force telegram desktop to mine crypto currencies.
