### ISSUE TITLE
Incorrect window's size after opening since 1.9.0

### ISSUE THREAD

**Issue by timocov** [telegramdesktop/tdesktop#6804]
### Steps to reproduce

I have 2 displays: the first one is FullHD (the main one) with 100% scaling and the second one is 4K (see screenshot below) with 150% scaling.

![image](https://user-images.githubusercontent.com/3112183/69149607-e55caa80-0ae7-11ea-8c02-9b56136c78c5.png)

_(here "2" is the main FullHD display, and "1" is 4K the second display)_

If I move the app to the second (4K, `1`) monitor, let's say to the left-bottom corner, resize it a bit, wait some time (until the app saves the settings), close the app and then open it again, the size of the window is multiplied by `(DPI of 4K display) / (DPI of FullHD display)`.

The issue starts from 1.9.0 version.

### Expected behaviour

The size of window remains the same as before closing.

### Actual behaviour

The size is multiplied by `DPI_OF_DISPLAY_1 / DPI_OF_DISPLAY_2` value (in my case in 144/96=1.5 times).

### Configuration

**Operating system:** Windows 10

**Version of Telegram Desktop:** 1.9.0, 1.9.1 (1.8.15 is OK)

### Logs (related to `Window Pos`)

- Version 1.8.15, first run - [1.18.5_first.txt](https://github.com/telegramdesktop/tdesktop/files/3864677/1.18.5_first.txt)
- Version 1.8.15, second run - [1.18.5_second.txt](https://github.com/telegramdesktop/tdesktop/files/3864681/1.18.5_second.txt)
- Version 1.9.0, first run - [1.19.0_first.txt](https://github.com/telegramdesktop/tdesktop/files/3864682/1.19.0_first.txt)
- Version 1.9.0, second run - [1.19.0_second.txt](https://github.com/telegramdesktop/tdesktop/files/3864684/1.19.0_second.txt)

**Comment by timocov** [comment]
@Aokromes @john-preston any news? 🙂

**Comment by john-preston** [comment]
Not yet :( It looks like Qt started applying some dpi correction to the coordinates you set for a window.

**Comment by timocov** [comment]
Thanks for the fix @john-preston. I'm not sure whether it's related, but in the latest version is restores previous geometry correctly, but I can't see anything in the window:

![image](https://user-images.githubusercontent.com/3112183/74218778-ebfc5780-4cbb-11ea-820f-689d0bbac9f8.png)

Resizing, toggling maximize mode, hiding and showing again - all of these don't fix the problem. The only fix I've found - move window to the main screen, resize it a bit (to save latest position/geometry), close the app and then open it again.

**Comment by john-preston** [comment]
@timocov Yes, this is a regression with multi-monitor setup when the window is created not on the primary screen. I hope to fix that in the next version.

**Comment by timocov** [comment]
Got it, thank you!

**Comment by Unapedra** [comment]
Still happening to me, too. Telegram Desktop version 2.4.7.
