### ISSUE TITLE
bug with export

### ISSUE THREAD

**Issue by anonanons** [telegramdesktop/tdesktop#6807]
At one point (approximately the middle of the process), when trying to export data, an error occurred 400: location_not_available. I tried to check at different conferences and the result is the same. 
1.9.1 beta, theme classic
![Screenshot_2](https://user-images.githubusercontent.com/57991903/69240415-3d65e080-0bbe-11ea-915c-bdf5ae70ad2d.png)

**Comment by anonanons** [comment]
the issue was resolved, there was a problem with the sticker that killed the export, found it and deleted it and it all worked

**Comment by talkstream** [comment]
Please, re-open it if possible. I can't export too, but the stickers are disabled to export. I'm trying to keep my saved messages, there are more than 12000 items. I'm not sure if I can find the message with a problem 🤷‍♂️

**Comment by john-preston** [comment]
@talkstream Do you have the same 400: LOCATION_NOT_AVAILABLE error? I'll add this one to be skipped in export.

**Comment by talkstream** [comment]
@john-preston yes, exactly. That's how I found this post in the search.

But I have no idea which message causes the problem.

**Comment by john-preston** [comment]
@talkstream I hope it'll be fixed in the next version.
