### ISSUE TITLE
notification getting focus while pops up

### ISSUE THREAD

**Issue by agedz** [telegramdesktop/tdesktop#6808]
### Steps to reproduce
1. use telegram
2. switch on other app(sublime_text, web browser and etc.)
3. when telegram notification pops up  it will get focus on it and when it fade out focus back on app

### Expected behaviour
previously telegram notification does not get focus, it just pops up

### Actual behaviour
it is very very annoying, because if you typing at that time, you actually type nothing while notification have focus on it

### Configuration
**Operating system:**
LSB Version:	:core-4.1-amd64:core-4.1-noarch
Distributor ID:	Fedora
Description:	Fedora release 31 (Thirty One)
Release:	31
Codename:	ThirtyOne
Gnome(wayland) version 3.34.1

**Version of Telegram Desktop:**
telegram-desktop.x86_64                                  1.8.15-1.fc31                        @rpmfusion-free 
**Used theme**:
default(daily)

**Comment by steog88** [comment]
This bug is particularly annoying in connection with #4664: the telegram window gets focus the first time a notification arrives, and then marks all the messages as read in the open chat.
I experienced this in Ubuntu, in the desktop in my office, which stays with the screen locked most of the time.

**Comment by makarov-roman** [comment]
Same here. As a workaround you can enable Native Notifications in the Settings.
This issue is only reproducible only wayland session. So moving back to x11 could also be workaround.

**Comment by makarov-roman** [comment]
Also you can make all your QT apps use XWayland:

`QT_QPA_PLATFORM=xcb`
Add this to /etc/environment file, restart

**Comment by agedz** [comment]
> Same here. As a workaround you can enable Native Notifications in the Settings.
> This issue is only reproducible only wayland session. So moving back to x11 could also be workaround.
