### ISSUE TITLE
position on 2nd monitor lost after coming back from sleep on macOS

### ISSUE THREAD

**Issue by cigumo** [telegramdesktop/tdesktop#6810]
### Steps to reproduce
1. put Telegram Desktop app on second monitor
2. put the system to sleep
3. wake up the system
4. the Telegram Desktop window appears in the first monitor

### Expected behaviour
The window should appear in original position in the second monitor.

### Actual behaviour
The window is moved to the first monitor.

### Configuration
**Operating system:** macOS mojave

**Version of Telegram Desktop:** 1.8.15

**Used theme**: default

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/2840
