### ISSUE TITLE
100% CPU usage after forwarding or image posting to chat

### ISSUE THREAD

**Issue by rsdsoft** [telegramdesktop/tdesktop#6812]
CPU usage are very higher sometimes after messages forwarding or image/video posting. And never stops until Telegram restart

### Steps to reproduce
1. To forward message with image to some group, or to post image/video to group

### Expected behaviour
CPU usage should be ok

### Actual behaviour
CPU usage  50-100% and never stops until Telegram restart manually

### Configuration
Windows 10
Telegram 1.9.1
Day Theme

**Comment by Aokromes** [comment]
try updating to 1.9.8.

**Comment by Aokromes** [comment]
no answer after near 1 month, if this bug is still valid, open a new ticket with one updated telegram version downloaded from desktop.telegram.org or github.com
