### ISSUE TITLE
copy-paste hotkeys and russian garbled text, fedora.

### ISSUE THREAD

**Issue by Deviner75** [telegramdesktop/tdesktop#6813]
I'm using fedora, if on russian layout, copy-paste doesn't work or if I do RMB-> copy I get garbled text as a result of operation "Ð”Ð°Ð¹ ÑÑÑ‹Ð»ÐºÑƒ"
it works with every other app and browser. it's only Telegram issue.

### Steps to reproduce
1. to copy-paste russian text message to a chrome browser or to any place pretty much.

### Expected behaviour
Russian text pasted

### Actual behaviour
I get a garbled text as a result of paste operation example: " Ð”Ð°Ð¹ ÑÑÑ‹Ð»ÐºÑƒ"

### Configuration
**Operating system:**
fedora 5.3.7-301.fc31.x86_64)

**Version of Telegram Desktop:**
v 1.8.15

**Used theme**:
tinted theme

**Comment by xvitaly** [comment]
Try Telegram Desktop from RPM Fusion repository. It should work fine.

**Comment by Deviner75** [comment]
it worked great, thanks!

**Comment by Deviner75** [comment]
> Try Telegram Desktop from RPM Fusion repository. It should work fine.

it worked great, thanks!
