### ISSUE TITLE
"Don't include in unread count" and "mute archived"

### ISSUE THREAD

**Issue by Intenditore** [telegramdesktop/tdesktop#6814]
I wonder, would devs ever listen to us?
I'm freaking pissed off I have to click-click-click-click through all the chats with new messages to zero the unread count. Why don't I uncheck "include muted chats in unread count"? Simply because there ARE chats I WANT to be included! But there's no chat-specific settings for that.
I expected archiving the chat would exclude it from unread count automatically, but freaking no! Why? What's the logic? I don't need to know if there's something new in archived chats!
Is that so hard to fix?
It's not even group calling or video chats! It's a few lines of code!
You promised much but now you stuck on the simplest things, wtf

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/6105

Ref group calling and video calls, that belongs to twiteer.
Also have on mind telegram desktop only have one dev.
