### ISSUE TITLE
Label popping up occasionally when playing games with 125% scaling (telegram one), on windows.

### ISSUE THREAD

**Issue by HeavenlyChorus** [telegramdesktop/tdesktop#6815]
### Steps to reproduce

1. Use 125% scaling (telegram one not windows)
2. Minimize
3. Play some games
4. Use Simplified Chinese (not sure if this matters)

### Expected behaviour

Not interrupting my gaming

### Actual behaviour
![](https://i.loli.net/2019/11/24/FaYwSuc14IjhZHp.png)
When having cursor hovering over timestamps/posted links, etc, labels like this would pop up, which is normal.
But after i minimize the window and play games, the label would pop up onto my crosshair in game (if the game has a crosshair, for eg FPS games like CSGO, or somewhere else if the game doesnt have one) if someone posted links/ send some messages in the group i have left open before.
There were no such issues when i was on 100% scaling, and it keeps happening after switching to 125%.

### Configuration

**Operating system:** windows 10 1903 18362

**Version of Telegram Desktop:** 1.8.15

**Used theme**: Night Mode

**Comment by RadRussianRus** [comment]
Noticed that too with other apps. Windows 10 x64 1909, TD 1.9.1 beta. Happens with both Russian and English language, so I think it doesn't depend on locale.

**Comment by ilya-fedin** [comment]
#6744
