### ISSUE TITLE
[Bug] Archived chats unread count appearing in taskbar 

### ISSUE THREAD

**Issue by m4teh** [telegramdesktop/tdesktop#6816]
When minimized, unread archived chats appear as "[Telegram] (240)" for example.
Have to delete/unjoin groups to clear and empty taskbar count.

This could also be a feature request, however I thought the point of an archive was to archive.

- Linux x64

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/6314
