### ISSUE TITLE
Number of total messages in 'acrhived chats' becomes negative when message deleted

### ISSUE THREAD

**Issue by grazy27** [telegramdesktop/tdesktop#6817]
### Steps to reproduce
1. Add channel to archived chats. 
2. Read all messages, delete message from this channel(As another user)
3. Check message quantity label

### Expected behaviour
There shouldn't be any label with message quantity

### Actual behaviour
Label present and shows that there is -1 unread message
![image](https://user-images.githubusercontent.com/24507515/69498679-47a41980-0ef3-11ea-8872-330cf15990e2.png)

### Configuration
**Operating system:**
Win 10
**Version of Telegram Desktop:**
1.8.15
**Used theme**:
White

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/6100
