### ISSUE TITLE
Backspace not working when CapsLock is active

### ISSUE THREAD

**Issue by palsan** [telegramdesktop/tdesktop#6818]
### Steps to reproduce
1. type anything in message input
2. switch on Caps Lock
3. try backspace

### Expected behaviour
symbol before caret is expected to be deleted

### Actual behaviour
nothing happens

### Configuration
**Operating system:**
Linux Xubuntu 18.04

**Version of Telegram Desktop:**
Telegram v1.8.15

**Used theme**:
Standard

<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by dreua** [comment]
Could not reproduce on Fedora 30 (Gnome, X-Server) so this is most likely something specific to xface or the input system in use. Have you checked that it is only telegram i.e. other apps you use don't have this issue?

**Comment by Aokromes** [comment]
no answer after more than 2 months, if this bug is still valid, open a new ticket with one updated telegram version downloaded from desktop.telegram.org or github.com
