### ISSUE TITLE
[macOS 10.15.1]Accent menu not appearing on long press of a character

### ISSUE THREAD

**Issue by Momofil31** [telegramdesktop/tdesktop#6819]
### Steps to reproduce
1.  Try to write a message
2. Long press on a character like "e"
3. It should appear a menu that let you chose accented characters

### Expected behaviour
<img width="219" alt="Schermata 2019-11-25 alle 10 50 52" src="https://user-images.githubusercontent.com/11832130/69529923-752fa800-0f71-11ea-867e-76d888516dc3.png">

### Actual behaviour
Instead it writes "eeeeeeeeeeeeee"
<img width="564" alt="Schermata 2019-11-25 alle 10 51 22" src="https://user-images.githubusercontent.com/11832130/69529955-8678b480-0f71-11ea-8b25-9f06ffa87e94.png">

### Configuration
**Operating system: macOs Catalina 10.15.1

**Version of Telegram Desktop:** 1.8.15

**Used theme**: default

**Comment by 23rd** [comment]
In beta, this feature has a different behavior and sort of works, but still has a lot of problems. It doesn't look like it will be fixed soon. =(

**Comment by albertomn86** [comment]
Same problem in version 2.1.5 downloaded from the web:
![image](https://user-images.githubusercontent.com/14975138/83327224-8fc53f80-a27a-11ea-8e99-70f706d897e2.png)


Using the version 6.1.4 downloaded from the App Store it works perfectly:
![image](https://user-images.githubusercontent.com/14975138/83327195-6b696300-a27a-11ea-8288-bd2bfe2bcebe.png)
