### ISSUE TITLE
Allow to disable "log in to comments.app"

### ISSUE THREAD

**Issue by BO41** [telegramdesktop/tdesktop#6821]
I do not want to log in to comments.app and I do not want to be asked again.
At least I want it to remember my settings from the last time I unchecked both boxes.

Please don't push people into login into this page

**Comment by Aokromes** [comment]
can you take one screenshot of where you get that thing?

**Comment by BO41** [comment]
![app](https://user-images.githubusercontent.com/29450609/69567874-54d40d80-0fb2-11ea-9078-c71b8b10091e.jpg)
it is the ["Comments for channels"](https://comments.app/) feature
