### ISSUE TITLE
[Crash] Telegram Mac crash when sending message

### ISSUE THREAD

**Issue by Akaryatrh** [telegramdesktop/tdesktop#6822]
### Steps to reproduce
1. Select a conversation
2. Type a message "Test" (without quotes)
3. Type enter key or click on send button

### Expected behaviour
Message should be sent and displayed

### Actual behaviour
Telegram app crashes and quits unexpectedly

### Configuration
**Operating system:**
MacOS 10.13.6 (17G65) (Sierra)

**Version of Telegram Desktop:**
5.8.1 (185463) (problem occurs since version 5.7 (181196))

**Used theme**:
default theme

<b>Logs</b>:
[telegram-crash-report.txt](https://github.com/telegramdesktop/tdesktop/files/3888907/telegram-crash-report.txt)

**Comment by Aokromes** [comment]
this tracker is for telegram multiplataform desktop, not telegram macos.

**Comment by Akaryatrh** [comment]
@Aokromes Indeed, bug doesn't exist on Multiplatform app. Where should I report the issue then?

**Comment by Aokromes** [comment]
@macswift
