### ISSUE TITLE
Unable to create link with a cyrillic domain

### ISSUE THREAD

**Issue by meequz** [telegramdesktop/tdesktop#6823]
### Steps to reproduce
1. Start writing any message
2. Press ctrl+k to create a link
3. Fill the 'Text' field with any text
4. Fill the 'URL' field with any URL with cyrillic domain (example: https://моладзь.бел)
5. Press 'CREATE'

### Expected behaviour
The link is created and inserted in the message.

### Actual behaviour
The 'URL' field highlighted with red meaning error, the link is not created.

### Configuration
**Operating system:**
Linux Mint 19.1 Tessa 64-bit, MATE 1.20.1
**Version of Telegram Desktop:**
1.8.15
**Used theme**:
Night

**Comment by sa3eedDev** [comment]
#6805 fix this problem too.

**Comment by meequz** [comment]
This is an error. The issue still exists on the latest 2.4.4 desktop client, GNU/Linux version. Just tested it.

**Comment by meequz** [comment]
the issue is still present
![image](https://user-images.githubusercontent.com/2832374/115875552-01d3e380-a44e-11eb-91d9-1082cc1c6679.png)
Telegram Desktop v 2.7.1

**Comment by meequz** [comment]
Still (v3.7)

**Comment by meequz** [comment]
3 years already, wow
