### ISSUE TITLE
[snap] Telegram doesn't show the content of /media and /mnt.

### ISSUE THREAD

**Issue by RDKRACZ** [telegramdesktop/tdesktop#6824]
I am unable to attach files from usb storage - telegram can't see user folder in /media and /mnt.
I tried running telegram-desktop with sudo.

mkdir: cannot create directory '/run/user/0': Permission denied
No protocol specified
QXcbConnection: Could not connect to display :0
Telegram[0x13b32ea]
Telegram[0x1c390d3]
Telegram(_ZN15google_breakpad16ExceptionHandler12GenerateDumpEPNS0_12CrashContextE+0x382)[0x206091e]
Telegram(_ZN15google_breakpad16ExceptionHandler12HandleSignalEiP9siginfo_tPv+0x1c3)[0x20604f9]
Telegram(_ZN15google_breakpad16ExceptionHandler13SignalHandlerEiP9siginfo_tPv+0x1ab)[0x2060211]
/lib/x86_64-linux-gnu/libpthread.so.0(+0x11390)[0x7ff2740c2390]
/lib/x86_64-linux-gnu/libc.so.6(gsignal+0x38)[0x7ff2737fd428]
/lib/x86_64-linux-gnu/libc.so.6(abort+0x16a)[0x7ff2737ff02a]
Telegram[0xb63413]
Telegram(_ZN14QXcbConnectionC2EP19QXcbNativeInterfacebjPKc+0xee6)[0x2496416]
Telegram(_ZN15QXcbIntegrationC1ERK11QStringListRiPPc+0x2d1)[0x2467921]
Telegram[0x24666cd]
Telegram[0x2c568f3]
Telegram[0x29a7a6f]
Telegram[0x29a8a95]
Telegram[0x2f18821]
Telegram[0x29aaa3f]
Telegram[0x2669249]
Telegram(_ZN4Core7SandboxC1EN3gsl8not_nullIPNS_8LauncherEEERiPPc+0x36)[0x1c217a6]
Telegram(_ZN4Core8Launcher18executeApplicationEv+0x5e)[0x1c3493e]
Telegram(_ZN4Core8Launcher4execEv+0x47)[0x1c34a57]
Telegram(main+0x32)[0xb95a92]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf0)[0x7ff2737e8830]
Telegram(_start+0x29)[0xba5ab9]
fish: “sudo telegram-desktop” terminated by signal SIGABRT (Abort)
[18:51:58] asus@asus /home/asus (134) 

Creating a directory '/run/user/0' only remove the line from log that complain about the inability to create a directory.

Zorin OS 15; kernel 5.0.0-32-generic
Telegram version - 1.8.15

**Comment by RDKRACZ** [comment]
Same on another laptop running Ubuntu Mate 19.04.

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/5955
