### ISSUE TITLE
GIFs are not played in the chat

### ISSUE THREAD

**Issue by bodqhrohro** [telegramdesktop/tdesktop#6829]
### Steps to reproduce
1. Open a chat.
2. Open a GIF file via the clip button.
3. Send it.

### Expected behaviour
The GIF is looped.

### Actual behaviour
GIF stops playing, sometimes on the first frame, sometimes several frames later. This happens both in the chat and in the media viewer, and is not resolved by scrolling the chat or switching chats. However, the previews of the sent GIFs in the GIF tab of the emoji picker are played.

### Configuration
**Operating system:** Debian GNU/Linux 11

**Version of Telegram Desktop:** 1.9.1 beta

**Used theme**: Classic

**Comment by Hezkore** [comment]
Since the latest update; my GIFs don't even play a single frame.
They also don't play when I try to open them.
I have to save them and then open them up in an external program just to see them.

**Comment by Laiteux** [comment]
Me and multiple friends are having this issue as well.

**Comment by Aokromes** [comment]
this bug is still valid? test on 1.9.8

**Comment by bodqhrohro** [comment]
I still can reproduce it in 1.9.8, but in a bit different way. GIFs are played well in media viewer already, but they're still stuck in chats. Also, when I close the media viewer, the frame in the chat is changed to the last frame that was shown in the media viewer when it was closed.

**Comment by heroys6** [comment]
Same issue on Windows 10, Telegram Desktop v1.8.15

**Comment by Hezkore** [comment]
> 
> 
> Same issue on Windows 10, Telegram Desktop v1.8.15
I'm not sure why you'd still be on v1.8.15... 

I haven't had the GIF issue in a while anyways.
I'm on 1.9.9 now and sent a GIF today that worked.
