### ISSUE TITLE
attribution of OpenStreetMap

### ISSUE THREAD

**Issue by camelCaseNick** [telegramdesktop/tdesktop#6830]
### Steps to reproduce
1. create or find a location message
2. look at the map preview image

### Expected behaviour
Find the OpenStreetMap attribution. (see https://www.openstreetmap.org/copyright, https://wiki.osmfoundation.org/wiki/Licence/Licence_and_Legal_FAQ#How_should_I_attribute_you.3F)

### Actual behaviour
No hint is given data from OpenStreetMap is used.

### Configuration
**Operating system:** Ubuntu 16.04
**Version of Telegram Desktop:** 1.8.15
**Used theme**: Classic

**Comment by Aokromes** [comment]
this is server side, imho you must contact https://twitter.com/telegram or in app support.

**Comment by camelCaseNick** [comment]
Hey, stale bot, even though not directly solvable here, it's not resolved here. I'll close it then, thanks.
