### ISSUE TITLE
Download full album or selected photos

### ISSUE THREAD

**Issue by WPFilmmaker** [telegramdesktop/tdesktop#6835]
### Is your feature request related to a problem?
Right now if you are sent multiple photos you have to download them one by one

### Describe the solution you'd like
Option to save full album at once 

### Describe alternatives you've considered
even better first select images you want, right click and "download selected images"

### Additional context
version Linux 1.8.15

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/1382
