### ISSUE TITLE
Minimum window dimensions too big

### ISSUE THREAD

**Issue by BO41** [telegramdesktop/tdesktop#6836]
Please allow resizing the window to any size I want.
Currently the minimum dimensions are `380x480`.
I would like to resize my window to less than 480px in height

**Comment by john-preston** [comment]
@BO41 It is not supported well, even in 480 there are some problems with the layout.

**Comment by BO41** [comment]
Can't be too bad for the height, can it?
I would prefer to have the choice :)

Maybe you can make it just a bit smaller and not completely free? :thinking:

**Comment by Aokromes** [comment]
as hackaround you can use sub 100% scale.

**Comment by BO41** [comment]
@Aokromes thanks, nice idea.
But how can I go below 100%? Only see 100-300%

**Comment by 23rd** [comment]
@BO41 https://github.com/telegramdesktop/tdesktop/issues/6055#issuecomment-496599363.

**Comment by BO41** [comment]
setting the scale below 100% worked perfectly and is even better than just a smaller window, thanks
(maybe consider adding it to the scale menu?)
