### ISSUE TITLE
Telegram won't install or launch

### ISSUE THREAD

**Issue by KD9FNA** [telegramdesktop/tdesktop#6838]
I have had a strange issue with Telegram for a while on my Windows installation and am attempting to fix it.  This could be a bug with Telegram or an issue with my setup.  

When attempting to install Telegram, the installer runs like normal and creates the directory structures in the AppData/Roaming folder.  When the installer finishes and offers to run Telegram, I select yes.  In Task Manager I can see that Telegram is running, but it does not show up in the task bar or in the hidden icons list.  There is no indication that it runs other than what is visible in Task Manager.  

The same issue happens when attempting to run the portable version of Telegram.  Both versions do create a log file, but for the sake of brevity I am only including the log from the installer version below and excluded the date/time information.  The portable version creates an almost identical log with only minor differences in the directories.

Steps to reproduce:
1. Install telegram
2. Installer finishes as normal
3. Attempt to run Telegram from start menu or by navigating to directory and running the .exe file

Configuration:
Windows 10 Home 64-bit, version 1809

Log file contents:
Launched version: 1008015, install beta: [FALSE], alpha: 0, debug mode: [FALSE], test dc: [FALSE]
Executable dir: C:/Users/.../AppData/Roaming/Telegram Desktop/, name: Telegram.exe
Initial working dir: C:/Users/.../AppData/Roaming/Telegram Desktop/
Working dir: C:/Users/.../AppData/Roaming/Telegram Desktop/
Command line: C:\Users\...\AppData\Roaming\Telegram Desktop\Telegram.exe
Executable path before check: C:/Users/.../AppData/Roaming/Telegram Desktop/Telegram.exe
Logs started

**Comment by Aokromes** [comment]
can you try to run it as administrator or windows 8 / 7 compatibility modes?

**Comment by KD9FNA** [comment]
> can you try to run it as administrator or windows 8 / 7 compatibility modes?

Thank you!  I managed to get it working through Windows 8 compatibility mode.  I tried running it as administrator previously but that didn't work.  Now both the portable and installer versions are working as they should.
