### ISSUE TITLE
[Question] How I get auth_key

### ISSUE THREAD

**Issue by dinumo12** [telegramdesktop/tdesktop#6840]
Hello. Tell me how I can get auth_key in the form:

"4a7191d0a340d76ccd2a4629d965424d0039045b8b5582c5aba805c3cc717b8fc1ff18f651606a530bf16dbfb7cd31ffd4595889aa7074495854a29455be8ded29d6898f96492133ae54b44e7b27e44e9e7cc4e445a879744e19735880e9ce739b1b7768a7a7c5442f583863de8021ea11303a23a2f259cdfa977b611fc73b27cc38dfdc137b06151443e73d16d31230ef3ad966093343ff92c883dfad710f7feb713790d085f867ddea7bd6755b511y040a13e71c5e008394e93fa30306b74cda41b4604034447832cf9a312380c521ae4b811e5704a5s14000f0efe6167c1088cd5a76b41c0bdae43e852a1b8fa1445d2ac5d606a02e8856cab20f199df185"

Thanks for any answers)

**Comment by Aokromes** [comment]
https://core.telegram.org/mtproto/auth_key
