### ISSUE TITLE
[Feature Request] Implement XMPP federation in the Telegram server

### ISSUE THREAD

**Issue by stevenroose** [telegramdesktop/tdesktop#6841]
Federating over XMPP would allow Telegram users to chat with other users on the XMPP/Jabber network and join Jabber chatrooms. Reversely, it would enable the wider Jabber network to join Telegram chatrooms.

The last few months, there has been [some discussion](https://github.com/wireapp/wire-server/issues/631) on the Wire server implementing such federation as well. Many people knowledgeable of the XMPP protocol gave their 2 cents on the actual task of implementing this form of federation. So I would refer to that discussion for references and some names that might be willing to help.

It would be awesome if Telegram would do the right thing and join an open federated chat network instead of being yet-another-silo messenger app that locks-in its users.

**Comment by Aokromes** [comment]
if such thing is implemented it will be needed applications wide and not telegram-desktop only.

**Comment by stevenroose** [comment]
Sure, it should be at the Telegram server level first and then probably some client UX improvements to make it work more seamless. There is just no repo for the Telegram server or Telegram service as a whole.

**Comment by woj-tek** [comment]
While this would be very handy, given https://telegram.org/faq#q-can-i-run-telegram-using-my-own-server:

> Our architecture does not support federation yet. Telegram is a unified cloud service, so creating forks where two users might end up on two different Telegram clouds is unacceptable. To enable you to run your own Telegram server while retaining both speed and security is a task in itself. **At the moment, we are undecided on whether or not Telegram should go in this direction.**

I'm quite doubtful it will ever happen.

**Comment by stevenroose** [comment]
@Aokromes This has gotten quite some love. I suppose it was closed because it was not made in the correct repository? Do you have a suggestion as where I can place this feature request more appropriately?

**Comment by Aokromes** [comment]
> @Aokromes This has gotten quite some love. I suppose it was closed because it was not made in the correct repository? Do you have a suggestion as where I can place this feature request more appropriately?

in app "ask a question" but i seriously doub they will implement it.

**Comment by MurzNN** [comment]
Federate Telegram with XMPP can be implemented via Matrix.org bridges feature: https://github.com/matrix-org/matrix-bifrosthttps://matrix.org/bridges/#Telegram and
