### ISSUE TITLE
[Question] How to create a link to a username with a predefined message

### ISSUE THREAD

**Issue by K1DV5** [telegramdesktop/tdesktop#6842]
There is [t.me/username]() but I was trying to attach a message to that, something like [t.me/username?message=hi](). WhatsApp has [wa.me/+44555?text=hi]() and there is [mailto:who@example.com]() for emails. How can I achieve something similar?

**Comment by Aokromes** [comment]
i don't think this is or it will be possible.

**Comment by K1DV5** [comment]
Right, thanks anyway
