### ISSUE TITLE
some text (usually - links) prints one symbol by line

### ISSUE THREAD

**Issue by youctac** [telegramdesktop/tdesktop#6843]
### Steps to reproduce
1. Just look at screenshot

### Expected behaviour
Text or links without \n after each symbol

### Actual behaviour
Screen

### Configuration
**Operating system:** Fedora 31

**Version of Telegram Desktop:** 1.8.15

**Used theme**: normal/dark

<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>
![Снимок экрана от 2019-12-04 22-58-20](https://user-images.githubusercontent.com/39337015/70176479-9b7be300-16e9-11ea-8580-194e79edb8f8.png)
![Снимок экрана от 2019-12-04 22-58-01](https://user-images.githubusercontent.com/39337015/70176481-9b7be300-16e9-11ea-8b69-d5be3e180747.png)

**Comment by 23rd** [comment]
#6584.
#6837.
#6786.
#6723.
