### ISSUE TITLE
[Feature Request] 

### ISSUE THREAD

**Issue by RomanLevak** [telegramdesktop/tdesktop#6844]
### Description of the problem
let's say someone sent me a lot of pictures and i want to download few of them, for these i need to manually right click on each one, then 'Save Image As' and so on ... . This may take a lot of time and become annoying. Can you please provide a way to firstly select pictures user want to download and then download them at once ?

### solution i'd like
If user holds a 'control' key, then left clicking on each picture would add it to the selected images group, which can be downloaded later.

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/1382

**Comment by Aokromes** [comment]
hackaround: create one temp group forward all desired pics there and use export pictures feature.
