### ISSUE TITLE
Slowmode bug

### ISSUE THREAD

**Issue by LucaTheHacker** [telegramdesktop/tdesktop#6845]
### Steps to reproduce
1. send a message in a chat with slowmode (the most useless but used thing ever)
2. write another message
3. spam send key until counter is to 0

### Expected behaviour
Message should be sent when send key is pressed after timer end.

### Actual behaviour
Message won't never be sent and will remain with a clock instead of tick.

### Configuration
**Operating system:** W10 1909

**Version of Telegram Desktop:** 1.8.15

**Used theme**: Nightmode default

**Comment by Aokromes** [comment]
this bug is still valid?

**Comment by LucaTheHacker** [comment]
> this bug is still valid?

Yes

**Comment by LucaTheHacker** [comment]
Fixed.
