### ISSUE TITLE
Startup notification support

### ISSUE THREAD

**Issue by Carlovan** [telegramdesktop/tdesktop#6847]
I'm using the [i3 windows manager](https://i3wm.org/) which uses the [startup notification standart](https://specifications.freedesktop.org/startup-notification-spec/startup-notification-latest.txt) to correctly handle applications execution.

Seems like Telegram Desktop does not support this. It would be very handy to have it.

**Comment by ilya-fedin** [comment]
> Seems like Telegram Desktop does not support this.

Supports, just like any other Qt app: https://github.com/qt/qtbase/blob/v5.12.8/src/plugins/platforms/xcb/qxcbscreen.cpp#L599
