### ISSUE TITLE
Solar Hijri calendar - jdate [Feature Request] 

### ISSUE THREAD

**Issue by farazsahebdel** [telegramdesktop/tdesktop#6848]
Hi Telegram developers
The Telegram instant messaging service has more than 50 million users in Iran and 60% of the country's Internet's bandwidth is spent on using this app.
For the official calendar in Iran, Solar Hijri calendar.
please add Solar Hijri calendar in Popular Iranian messenger.

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/4182
