### ISSUE TITLE
When compiling telegram appears： C2872 "ranges": ambiguous symbols

### ISSUE THREAD

**Issue by chinaxd** [telegramdesktop/tdesktop#6849]
**### Steps to reproduce**
1.    Build instructions for Visual Studio 2019
       Follow the instructions of the installation web page(   https://github.com/telegramdesktop/  tdesktop/blob/v1.6.7/docs/building-msvc.md),  step by step, and succeed to the end. In addition, we changed tdsktop to git version 1.6.7. 

**### Expected behaviour**
1.  vs.net 2019 Compile
     We open VS.NET 2019 and successfully compile all other libraries. When we compile telegram,
     Project will have compilation errors，as follows：
     C2872	“ranges”: Ambiguous symbols	Telegram	       E:\TBuild\tdesktop\Telegram\SourceFiles   
                                                                                               \ settings\settings_calls.cpp	79
     C2872	“ranges”: Ambiguous symbols	Telegram	       E:\TBuild\tdesktop\Telegram\SourceFiles   
                                                                                               \ settings\settings_calls.cpp	86
     C2872	“ranges”: Ambiguous symbols	Telegram	       E:\TBuild\tdesktop\Telegram\SourceFiles   
                                                                                               \ settings\settings_calls.cpp	93
     C2872	“ranges”: Ambiguous symbols	Telegram	       E:\TBuild\tdesktop\Telegram\SourceFiles   
                                                                                               \ settings\settings_calls.cpp	100
     C2872	“ranges”: Ambiguous symbols	Telegram	       E:\TBuild\tdesktop\Telegram\SourceFiles   
                                                                                               \ settings\settings_calls.cpp	115_
     .....

I found that "ranges" is the namespace name in the ranges V3 library, and also found that "ranges" namespace appears in the header file of MSVC . I think it should be the cause of the problem, but I don't know how to deal with it. 

**### Actual behaviour**
    What should I do to eliminate this error and compile normally.
   Thank you in advance.

**### Configuration**
    win10 

**Version of Telegram Desktop:**
   1.6.7

**Comment by Aokromes** [comment]
telegram desktop stable is 1.8.5 and beta 1.9.1

**Comment by 23rd** [comment]
Checkout your range v3 to `0.5.0`.

**Comment by chinaxd** [comment]
@23rd . range V3 is 0.4.0.  My solution now is to change the namespace to another name.
