### ISSUE TITLE
Stickers stop animating

### ISSUE THREAD

**Issue by AkaZecik** [telegramdesktop/tdesktop#6851]
Stickers that were already sent in a conversation stop animating on Ubuntu's and Windows' Telegram Desktop version after the following steps:

## How to reproduce
1. Send some animating sticker.
2. Hover over the 'smiley' icon on the right bottom and **click** on it.

Now the sticker that was sent in the first step is not animating, even after closing the side panel that had opened.

## How to fix it
1. Hover over the 'smiley' icon on the right bottom and **don't click** on it.
2. Move the mouse away from the icon.

Now the sticker is animating again.

## My configuration

I'm using `Ubuntu 18.04 LTS` and `Windows 10` with Telegram version `1.8.15` downloaded from here: https://desktop.telegram.org/. I haven't reinstalled Telegram after discovering the issue.

**Comment by jeffythedragonslayer** [comment]
I see the sent sticker sometimes stop animating immediately when I mouse over the smiley icon again, but not consistently.
