### ISSUE TITLE
Broken rendering Ъ in small case

### ISSUE THREAD

**Issue by POPSuL** [telegramdesktop/tdesktop#6852]
### Steps to reproduce
1.  just write yourself message like `Ъъ`

### Expected behaviour
`ъ` should render correctly, like that:
IMG > ![image](https://user-images.githubusercontent.com/683358/70363599-1d802d80-18dd-11ea-829c-5208667b1105.png) < /IMG

### Actual behaviour
![image](https://user-images.githubusercontent.com/683358/70363286-e9583d00-18db-11ea-8745-900cb262f7bf.png)
small `ъ` have thickened right side and left side of letter looks like squared

### Configuration
Windows 10.0.18362

**Version of Telegram Desktop:**
1.8.15

**Used theme**:
Tinted

**Comment by Aokromes** [comment]
Hi, try updating to 1.9.1 beta.

**Comment by Aokromes** [comment]
it looks good to me on 1.9.8
https://i.imgur.com/fPnRDiQ.png
