### ISSUE TITLE
[Feature Request] ScreenShot Function

### ISSUE THREAD

**Issue by jack24254029** [telegramdesktop/tdesktop#6853]
### Is your feature request related to a problem?
No.

### Describe the solution you'd like
Hi, I need a screen shot function on Telegram Desktop like Line.

### Describe alternatives you've considered
Maybe can add this function entrance in send file button.

### Additional context
Screenshot function on Line.
![image](https://user-images.githubusercontent.com/13265628/70370587-e2ddbb80-1903-11ea-9ab8-31932abcf12e.png)
I think can add screenshot function on Telegram like this.
![image](https://user-images.githubusercontent.com/13265628/70370652-be361380-1904-11ea-8860-2c9abb9db715.png)

**Comment by Aokromes** [comment]
on windows you can use alt+print screen key.

**Comment by jack24254029** [comment]
But I do not want to print whole screen.
Sometimes, I only need print specific range on my screen and Line can do it.
Like this.
![image](https://user-images.githubusercontent.com/13265628/70392837-cda97f80-1a1e-11ea-8687-35a4786f1c60.png)

**Comment by Aokromes** [comment]
well windows ships screenshot taking tool, for sure macos too.

**Comment by jack24254029** [comment]
Ok. I will try 「Win+Shift+S」on Windows 10.
Thank you.

**Comment by Laiteux** [comment]
use https://github.com/ShareX/ShareX
