### ISSUE TITLE
Scale is not adjusted automatically on different displays

### ISSUE THREAD

**Issue by afcruzs** [telegramdesktop/tdesktop#6854]
### Steps to reproduce
1. Set up a machine with two monitors. One monitor with 100% scale and the other with 200%.
2. Disable default interface scale.
3. Open telegram in one monitor and then switch the app to the second monitor.

This setup is very common on laptops with high resolution which connect to an external monitor (surface book 2 for example).

### Expected behaviour
The scale of the telegram window should auto scale depending on the monitor (this happens automatically with other apps like chrome, spotify or whatsapp).

### Actual behaviour
The scale remains either 100% or 200% depending on what is configured on the telegram app.

### Configuration
**Operating system:** Windows 10 pro
**Version of Telegram Desktop:** 1.8.15

**Comment by mikeozerov** [comment]
I think "Default interface scale" should means "Windows interface scale settings".
I mean it should be two options:
1. Windows default interface scale (with changing scale between displays)
2. Custom interface scale (only for telegram in percents)

But now it works strange. "Default interface scale" toggle just set scale on 100% and that's all.
### Configuration
**Operating system**: Windows 10 pro
**Version of Telegram Desktop**: 1.8.15

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/6196
