### ISSUE TITLE
Option to check for update disappears when autoupdate is disabled

### ISSUE THREAD

**Issue by anohren** [telegramdesktop/tdesktop#6855]
### Steps to reproduce
1. Disable autoupdate
2. Watch as the option to manually check for updates disappears

### Expected behaviour
Tell us what should happen:

The option to check manually for an update should reasonably be even more prominently available when autoupdate is *not* enabled, since manual updates are then the only remaining alternative.

### Actual behaviour
Tell us what happens instead:

Manually checking for updates -- the very option that becomes relevant when autoupdate is disabled --  is hidden when autoupdate is disabled.

### Configuration
**Operating system:**
Windows 10

**Version of Telegram Desktop:**
1.8.15

**Used theme**:
Don't know anything about themes.

<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/4643

**Comment by anohren** [comment]
> #4643

It does not look like the same issue, but ok.

**Comment by Aokromes** [comment]
it's, he want to have manual update checking without have autoupdater enabled, like you.
