### ISSUE TITLE
[Question] Switch file picker to KDE one in Linux

### ISSUE THREAD

**Issue by Jzarecta** [telegramdesktop/tdesktop#6856]
I use Arch Linux and have the telegram desktop on version 1.8.15 and wonder why when I add an image I get a gtk file chooser and is there a way I can use the Qt one under KDE dolphin file chooser. This file chooser comes when I try to add and upload media like an image or video.

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/2411
