### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by karinlinux** [telegramdesktop/tdesktop#6859]
I think telegram desktop in the latest version (1.8.15) has memory leak
![Screenshot from 2019-12-09 08-46-16](https://user-images.githubusercontent.com/31069662/70409473-1f72f980-1a61-11ea-8f6c-b5a33dc2fa04.png)

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/1317
