### ISSUE TITLE
[BUG] Two hyphens (--) replaced into a dash (—) in urls, breaking them

### ISSUE THREAD

**Issue by cemmeydan** [telegramdesktop/tdesktop#686]
Telegram Desktop 0.8.7
Win 8.1

Typing two hyphens (--) in succession replaces them into a long dash character (—) automatically, just as in >> is turned into ». However the same conversion is also applied when the characters are inside urls, which breaks the link.

* Bug: Characters should never be replaced automatically when inside links

* Enhancement: There should also be another setting which disables automatic replacement of such characters (for when people copy paste code snippets in a message), not just emojis. Disabling "replace emojis" doesn't work.

**Comment by ppparadox** [comment]
+1

**Comment by deconstruction** [comment]
More on this https://github.com/telegramdesktop/tdesktop/issues/646

**Comment by auchri** [comment]
Duplicate #522
