### ISSUE TITLE
The letter "Ə" "ə" is not rendered correctly.

### ISSUE THREAD

**Issue by orkhanfarmanli** [telegramdesktop/tdesktop#6861]
### Steps to reproduce
1. Just copy and paste Ə or ə to any chat.

### Expected behaviour
They should render correctly.

### Actual behaviour
The letters I mentioned are not rendered correctly because of the new font. They were okay before recent updates. These letters are from Azerbaijani language.

### Configuration
**Operating system:**
Deepin Linux 15.11

**Version of Telegram Desktop:**
1.8.15
**Used theme**:
Night
<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by Aokromes** [comment]
works for me on telegram 1.9.1 beta on windows.
https://i.imgur.com/cO18ToF.png

**Comment by Aokromes** [comment]
i got reports of working fine on debian testing with 1.9.1 beta and ubuntu 18.04 with 1.8.5 stable and 1.9.1 beta, maybe it's deepin bug.

**Comment by orkhanfarmanli** [comment]
No other application in my system has such a weird issue. I'm using stable version of the Telegram app.

**Comment by Aokromes** [comment]
can you try 1.9.8?

**Comment by orkhanfarmanli** [comment]
Okay, it's fixed now. Thanks!
