### ISSUE TITLE
Video streaming is broken on 1.9.1 beta

### ISSUE THREAD

**Issue by compliment** [telegramdesktop/tdesktop#6862]
### Steps to reproduce
1.  Stream videos on 1.9.1 beta
Example video https://t.me/tgbeta191brokestreaming/2
Although most of the videos aren't stream-able, it falls back to download.  

### Expected behaviour

Should stream those videos like it does on 1.8.15 
### Actual behaviour

Falls back to download with console output `[mov,mp4,m4a,3gp,3g2,mj2 @ 0x7fca00000900] Protocol name not provided, cannot determine if input is local or a network protocol, buffers and access patterns cannot be configured optimally without knowing the protocol`
### Configuration
**Operating system:**
Archlinux x86_64
**Version of Telegram Desktop:**
1.9.1 beta
**Used theme**:
Doesn't matter.
<details><summary><b>Logs</b>:</summary>
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x7fca00000900] Protocol name not provided, cannot determine if input is local or a network protocol, buffers and access patterns cannot be configured optimally without knowing the protocol`
</details>

Edit: formatting

**Comment by john-preston** [comment]
This video doesn't stream for me in 1.8.15 as well.
