### ISSUE TITLE
!!! Pirated products

### ISSUE THREAD

**Issue by tsln1998** [telegramdesktop/tdesktop#6863]
I found a software called Potato that copied the Telegram code without marking the source

The software is recompiled using Telegram source code, A lot of resources in the software are copied directly from the Telegram client, but the software copyright is not indicated

WebSite: https://www.alanturing.me/

**Comment by tsln1998** [comment]
![image](https://user-images.githubusercontent.com/16133088/70503536-9510bf80-1b5e-11ea-9a58-98b739cb4d1f.png)
![image](https://user-images.githubusercontent.com/16133088/70503583-ab1e8000-1b5e-11ea-8b03-d3125cdb53c6.png)

**Comment by Aokromes** [comment]
poke telegram on twitter.
