### ISSUE TITLE
Drag of URLs is not working

### ISSUE THREAD

**Issue by karl007** [telegramdesktop/tdesktop#6864]
### Steps to reproduce
1. send or receive an link/url
2. try to drag the URL or the preview icon

### Expected behaviour
Have a draggable link to drop on Browser, Terminal or Texteditor to get the link as a new tab or as text.

Normal behaviour in every app in OSX.

### Actual behaviour
Select the text under the mouse cursor

**Version of Telegram Desktop: 5.8 (185085) AppStore OSX**

**Comment by Aokromes** [comment]
this is for telegram desktop multiplataform, not telegram macos.

**Comment by karl007** [comment]
I'm sorry - new issue: https://github.com/overtake/TelegramSwift/issues/383
