### ISSUE TITLE
On Fedora 31, unable to paste text into telegram message line.

### ISSUE THREAD

**Issue by cybule** [telegramdesktop/tdesktop#6865]
### Steps to reproduce
1. Open telegram, go to any chat. 
2. Mark piece of text in terminal or any other window. 
3. Try to paste it into telegram using mouse middle button.

OR

1. Open telegram, go to any chat. 
2. Mark piece of text in terminal or any other window and do Ctrl+C to copy.
3. Try to paste it into telegram using right mouse button menu and then Paste.

### Expected behaviour
Text should be copied into telegram message line.

### Actual behaviour
Text is not copied into telegram message line.
Tell us what happens instead

### Configuration
Fedora 31

**Version of Telegram Desktop:**
1.8.15

**Used theme**:
Night.

**Comment by art-shutter** [comment]
Can confirm same symptoms with similar set-up.
This is absolutely irritating as I use telegram for work in fedora 31

**Comment by xrstalker** [comment]
@art-shutter @cybule 
I've met similar problem. For me it looks like CTRL+character combinations were randomly stopping working.
Then I've found that [comment](https://github.com/telegramdesktop/tdesktop/issues/6645#issuecomment-562172846). Problem was exactly that it said. Shortcuts work on en keyboard layout and don't on ru. Proposed fix is adding QT_QPA_PLATFORM=xcb to /etc/environment. It worked for me. Can you check it?

**Comment by art-shutter** [comment]
@xrstalker 
Thanks, this worked like a charm! Tested shortcuts on both latin and cyrillic layouts.

Though I am still concerned that this requires extra settings. IMO, ctrl+c/ctrl+v should work out of the box.

**Comment by ilya-fedin** [comment]
https://bugreports.qt.io/browse/QTBUG-66497?jql=text%20~%20%22wayland%20key%20sequences%22

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/6645
