### ISSUE TITLE
[Feature Request] Setting for deleting messages

### ISSUE THREAD

**Issue by Broeckel** [telegramdesktop/tdesktop#6867]
Please add an option to automatically tick that button, also delete for ...

![Screenshot from 2019-12-11 17-26-01](https://user-images.githubusercontent.com/45721680/70640389-c7d8b780-1c33-11ea-85b1-d64cbe7b7dcf.png)

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/3334
