### ISSUE TITLE
Show only unread conversations

### ISSUE THREAD

**Issue by lukeflegg** [telegramdesktop/tdesktop#6868]
I suspect I have about 20 conversations with unread messages inside right now.
But it's so difficult to find them!

I use Telegram a lot, so have many conversations and just manually scrolling down trying to find all the unread messages is frustrating.

I think it would be good for Telegram to help people actually reply and not miss messages.

**Comment by lukeflegg** [comment]
I was so happy when "Mark unread" came out because I often read a message and realise it needs more time than I have, or it's asking me to check something and get back to them soon, so marking unread is great for making sure I follow up later

However, the unreads so easily get lost with all the new updates in other chats, so I drop the ball and people think "I can't trust Luke to get back to me via Telegram"

Even Gmail, for years, has allows me to have unread conversations appear above more recent conversations I've read.

There's several ways to enable this in Telegram I think.
One way is a toggle switch "Unread at top" which could even reset itself back to default when you next open Telegram, or after a certain period of time (if you're worried that users would forget to turn it off)

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/1067
