### ISSUE TITLE
Doesn't work with Windows on screen keyboard

### ISSUE THREAD

**Issue by Vabe7** [telegramdesktop/tdesktop#6871]
If you tab into the writing section jn a chat the Windows onscreen keyboard appears. Telegram should recognize that the screen size has changes and adjust the size, so that you see what you are typing, but Telegram doesn't resize correctly, so you can't see what you are typing.

And when you close the keyboard to Check what you habe written, your desktop appears where the keyboard was.

Only after minimizing it, it appears normal again.

Version is 1.8.15
Operating System is Windows 10 Home
![TelegramKeyboardBug](https://user-images.githubusercontent.com/37805053/70846666-0486f780-1e5c-11ea-8bc7-f07959f0f79d.jpg)

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/1297
