### ISSUE TITLE
[Question] Twitter account sold???

### ISSUE THREAD

**Issue by Geobert** [telegramdesktop/tdesktop#6873]
https://twitter.com/DealsDailyGrind/status/1205906193040003072

Seriously???!! Or hacked?

**Comment by john-preston** [comment]
@Geobert It was first not used for a long time, then stolen, then sold, I guess.

**Comment by Geobert** [comment]
Some communication about the account being stolen would have been nice, or did I missed it?

**Comment by john-preston** [comment]
@Geobert Well, it was not used for almost a year, I forgot about it. I don't know where to post info about it being lost, because only it's followers are interested in that information and they see it already in their Twitter feed :/

**Comment by Geobert** [comment]
Maybe telegram messenger account could have said something? Aren't you guys officialy related to Telegram?

**Comment by john-preston** [comment]
@Geobert Well, I think the absolute majority of telegram twitter followers were not interested in that one. For tdesktop I had my own, personal account. Maybe twitter can block it now or idk.

**Comment by tjj530** [comment]
@john-preston block the account? Why? It was purchased. They can do whatever they would like with it from there on out.

**Comment by MAGICCC** [comment]
@tjj530 I doubt Twitter allows to sell accounts... And no I don't want to read their ToS now.

**Comment by tjj530** [comment]
@MAGICCC people buy and sell social media accounts literally all the time. Block them then, it’s not hard.

**Comment by Sominemo** [comment]
I recommend doing this
![s4akdwhs2u](https://user-images.githubusercontent.com/19842935/70856778-912cc680-1eeb-11ea-91ef-4ee0e4e1a855.gif)

**Comment by Aokromes** [comment]
well, this issue aint telegram desktop bug.
