### ISSUE TITLE
Last time Telegram Desktop was not closed properly

### ISSUE THREAD

**Issue by Newcool1230** [telegramdesktop/tdesktop#6874]
### Steps to reproduce
1. Launching Telegram App

### Expected behaviour
Open properly and display chats.
It was working yesterday and the weeks before.

### Actual behaviour
A box pops up telling me "Last time Telegram Desktop was not closed properly" 
![1SS39THt 1](https://user-images.githubusercontent.com/10657253/70853429-a534e180-1e73-11ea-9499-7d5959eaeb07.png)
Then it closes after 1 sec

### Configuration
**Operating system:**
Win 10 pro Version 1803 (OS build 17134.1069)

**Version of Telegram Desktop:**
Version 1.8.15.0

**Used theme**:
Darkmode?

<details><summary><b>Logs</b>:</summary>
[log.txt](https://github.com/telegramdesktop/tdesktop/files/3964245/log.txt)
</details>

**Comment by Aokromes** [comment]
to start, i suggest you to update your windows to at least 1903, also download beta version and when it crashes i click send crash and post crash id here.

**Comment by Newcool1230** [comment]
> to start, i suggest you to update your windows to at least 1903, also download beta version and when it crashes i click send crash and post crash id here.

Downloading v 1.9.1 beta, fixes the issue. No crash. Nothing. Telegram also did not crash this morning or yesterday. When I started my computer this morning and tried to open the App the window popped up. Windows is still version 1803.

**Comment by Aokromes** [comment]
maybe windows got updated and that update crashed telegram.

**Comment by Newcool1230** [comment]
> maybe windows got updated and that update crashed telegram.

Maybe, but I made sure that I would not get an update from windows. I'm waiting until 1903 is stable before updating.

**Comment by Aokromes** [comment]
1903 is stable, 1909 is being pushed to everyone.

**Comment by shima1957** [comment]
can help me?
