### ISSUE TITLE
Automatically hidden taskbar doesn't appears by mouse action when Telegram window is maximized.

### ISSUE THREAD

**Issue by s1q** [telegramdesktop/tdesktop#6875]
### Steps to reproduce
1. Activate taskbar autohide in Windows 10
2. Maximize Telegram 1.9.1 window
3. Move mouse cursor to the bottom of the screen

### Expected behaviour
Automatically hidden taskbar should appear

### Actual behaviour
It is not appear

### Configuration
Windows 10 1909

**Version of Telegram Desktop:**
1.9.1

**Used theme**:
Dark Standart

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/3579
