### ISSUE TITLE
Hardware search buttons support [Feature Request] 

### ISSUE THREAD

**Issue by utmuk** [telegramdesktop/tdesktop#6876]
Please add support for hardware search button. For example Whatsapp and Chrome support it. Many other apps do too. Pressing the hardware search button does the same things as the tapping the search button in app.

**Comment by dreua** [comment]
What is your platform / operating system? I believe this repository is only for the desktop app but your question sounds more like iOS or Android.

**Comment by utmuk** [comment]
Yes, it is for Android. Where can I make feature requests for mobile platforms?

**Comment by Aokromes** [comment]
https://t.me/tgbetachat
