### ISSUE TITLE
User name missing if first response is a big emoji (confusing in large groups)

### ISSUE THREAD

**Issue by dreua** [telegramdesktop/tdesktop#6877]
### Steps to reproduce

1. Join large group with people you don't know
2. Wait for or ask someone to write multiple messages the first being a single (large) emoji.

### Expected behaviour
User name should be displayed on the beginning of each message "block" for clarity.

### Actual behaviour
User name is omitted if first message of a "block" is a single (large) emoji. I was seriously confused because it looks like the last 5 messages are from "gru..." which didn't make sense. In groups the colored user name is an important visual cue to signal the author of the following messages and in this case it is missing.

![Screenshot from 2019-12-15 16-36-06](https://user-images.githubusercontent.com/15114715/70865374-3338c700-1f5d-11ea-9ca5-f0e7528de599.png)

### Configuration
**Operating system:**
Fedora 30

**Version of Telegram Desktop:**
1.8.15

**Used theme**:
Dark

**Comment by Aokromes** [comment]
it's intended, in fact, android changed to this way.
