### ISSUE TITLE
[Question] Where are the group informations stored?

### ISSUE THREAD

**Issue by Exosylver** [telegramdesktop/tdesktop#6878]
I would like to add an if statement that doesn't let some groups display their contents- where can i find the area where the groups info is displayed?

**Comment by Aokromes** [comment]
very likely such thing will need api support because if no other clients will be allowed to show that info

**Comment by ilya-fedin** [comment]
>  where can i find the area where the groups info is displayed?

https://github.com/telegramdesktop/tdesktop/blob/dev/Telegram/SourceFiles/info/profile/info_profile_actions.cpp#L221
