### ISSUE TITLE
[Feature Request] 

### ISSUE THREAD

**Issue by MichaelSolotky** [telegramdesktop/tdesktop#6879]
Having a lot of unread messages, why they all become read if I click the icon of the channel? I sometimes keep some messages in channels unread in order too read them in future. In the android version of telegram when I click an icon of a channel, only a few old messages become read, but in telegram desktop (for macOS) it's not like that. It becomes painful, when I misclick.
Please, make it the same as in the android app.

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/775
