### ISSUE TITLE
Cannot support Input method(fcitx & ibus) on linux

### ISSUE THREAD

**Issue by dongfengweixiao** [telegramdesktop/tdesktop#688]
hi,telegram on linux cannot support any Input method.I think the reason is that telegram compiled with static(Opera early version have the same problem).So i try recompile it,but failed.

**Comment by pan-long** [comment]
related issue #375

**Comment by NgoHuy** [comment]
I wrote the patch to fix it here #843 
Try recompile and give me result, ^^

**Comment by telegramdesktop** [comment]
Please check out 0.8.50 dev version, it should be fine there, I've added Qt plugins for IBus and Fctix.
