### ISSUE TITLE
[Feature Request] Add music hotkeys control

### ISSUE THREAD

**Issue by TheSimpleCoder** [telegramdesktop/tdesktop#6884]
Add the ability to control rewind, pause, etc. with global hot multimedia keys.

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/3342

**Comment by z1MO** [comment]
@Aokromes why is this request considered a duplicate of bug 3342? It's about something else ...
And I can’t find the answer in other tickets, why don’t you add the music management functionality using hotkeys. Answer here or leave a link to the answer, please.

**Comment by RememberTheAir** [comment]
@z1MO music control keys are supposed to work but they don't, so it's a bug (and that ticket is about that bug)
