### ISSUE TITLE
Timestamp Tooltip appears out-of-context

### ISSUE THREAD

**Issue by Entih** [telegramdesktop/tdesktop#6885]
### Steps to reproduce
1. Have open an active Telegram chat or group.
2. Tab into another program which occludes Telegram or occupies the full screen.
3. Have a new message be posted.  If the cursor happens to be over the screenspace where a timestamp is after this message is posted (underneath the active window), the full-date tooltip may appear.

### Expected behaviour
Nothing.  Window being out-of-context and fully occluded by other windows should preclude tooltip from showing up over unrelated programs.

### Actual behaviour
Tooltip appears and remains until it is dismissed by tabbing into Telegram.  Provided is an example screenshot of the tooltip being visible from within a windowed fullscreen game: https://i.imgur.com/BwfhXLH.png

### Configuration
**Operating system:**
Win 10 64-bit
**Version of Telegram Desktop:**
1.8.15
**Used theme**:
'Tinted' theme

**Comment by gafoo** [comment]
Same at win7 64 at home and win10 64 at work, but names of emoji. classic theme, night mode, telegram desktop 1.8.15 https://i.imgur.com/FC51CXp.png
