### ISSUE TITLE
[Feature Request] cjk input

### ISSUE THREAD

**Issue by opqriu** [telegramdesktop/tdesktop#6886]
Linux does not cjk use only fcitx because the input environment is complex. I'm glad there's a web version. However, I prefer the desktop version.
If you don't mind, I'll ask.  Is there any chance that another cjk input will be supported someday?

- uim (made Japan)
- nimf (I like.. This is input Korean without bugs. https://nimf-i18n.gitlab.io/ko/installation)

Thank you for reading it. Merry Christmas Happy end of the year.

**Comment by ilya-fedin** [comment]
> If you don't mind, I'll ask. Is there any chance that another cjk input will be supported someday?

It is impossible to include all the input plugins, but [nimf is here](https://github.com/telegramdesktop/tdesktop/blob/d2291f5b17e0c169083a34e51053a99546207ec8/Telegram/SourceFiles/qt_static_plugins.cpp#L45) for a very long time.
You can use telegram from system repositories and it will use system input plugins, as any other Qt application installed from system repositories.
Although there are multiple input plugins included into static binary, I have a feel that they doesn't work anyway and the only option is to use distribution package if you need to type with input engines.

**Comment by ilya-fedin** [comment]
I just tried to convert fcitx/hime/nimf build to upstream buildscripts with actual (the one that embedded currenlty are very-very old)

However, I only succeeded with fcitx. Hime and nimf doesn't have possibility to build only qt5 plugin, without the input engine itself.
If you can convince hime and nimf upstreams to add such an option in their build scripts, I'l try to update them and maybe they will start working again
PS: i see that nimf is trying to switch to meson, however, it requires a new python which isn't present on Ubuntu 14.04 that is used to build tdesktop. If they do that, it will be a new blocker.

**Comment by ilya-fedin** [comment]
nimf was updated, should work now
It it doesn't work for you, please provide errors from console.

**Comment by Aokromes** [comment]
@opqriu

**Comment by Aokromes** [comment]
@opqriu can you post what ilya requested?

**Comment by Aokromes** [comment]
no answer, if this issue is still valid open a new ticket addming all requested data by ilya.
