### ISSUE TITLE
[Feature Request] Stop converting text emoticons to stickers/images

### ISSUE THREAD

**Issue by wolfbeast** [telegramdesktop/tdesktop#6887]
### Is your feature request related to a problem?
Text emoticons like <3 if posted by themselves or as a duplicate with no text in a message are being converted to animated (oversized) images or stickers. Telegram really shouldn't do that.
**Note:** this is a request for telegram clients across the board (also mobile where slapping a huge sticker breaks chat flow by pushing text off the small screen) not just for desktop.

### Describe the solution you'd like
Please only convert to graphical (unicode) emoji at most, and don't automatically convert to animated images/stickers unless the user explicitly chooses to send an image or sticker.

### Describe alternatives you've considered
I've tried working around this issue but the only solution is to break emoticons so they no longer trigger this.

### Additional context
![Image1](https://user-images.githubusercontent.com/3359132/71307956-60bac000-23f6-11ea-86b0-6ea42b187dc6.jpg)

**Comment by john-preston** [comment]
@wolfbeast If you want to send just <3 you can send it as text, by disabling emoji replacements in Settings.

**Comment by wolfbeast** [comment]
But that's not what I would prefer. I would prefer emoji in texts sent, just not have them replaced with images/animations/stickers.

**Comment by wodim** [comment]
That's a setting in chat settings... "large emoji".
