### ISSUE TITLE
[Feature Request] The expansion of the black list to the public chat

### ISSUE THREAD

**Issue by DmitrySkibitsky** [telegramdesktop/tdesktop#6889]
Good time of day. It would be desirable that the black list was extended to public chats + as an additional parameter for mentions in messages of the blocked user. Sometimes a person just prevents you from being in the chat while leaving the chat, just in order to get rid of unwanted messages, too, do not want to.

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/1025
