### ISSUE TITLE
Queued messages never sent and lost after relaunch

### ISSUE THREAD

**Issue by syphernl** [telegramdesktop/tdesktop#689]
Scenario:
* Telegram Desktop 0.8.7 on Ubuntu 15.04
* Started up with working internet connection
* Telegram Desktop launched
* Made some changes to my network configuration, static IP / no internet temporarily some time after that (~30-60 minutes)
* Afterwards changed back to previous network configuration => working internet
* Sent a few messages to my contact via Telegram Desktop. All of which showed the clock icon indicating it hasn't been sent yet.
* This was odd so I re-launched Telegram Desktop

Result:
* Queued messages (~10) were never sent 
* Queued messages were gone permanently once Telegram Desktop was restarted

Expected behavior:
* Warning about messages that cannot be sent
* Telegram Desktop properly dealing with lost/returned internet connection
* Queued (unsent) messages not being deleted once Telegram Desktop is closed / reopened.

**Comment by TheAppService** [comment]
Yep, please fix that! I had the same problem (Messages were lost) already a few times.

**Comment by AndydeCleyre** [comment]
This is extra frustrating when working with inconsistently available internet, and the frustration is compounded by the fact that it's impossible to quit the program (without manually sending a kill signal) on the plasma 5 desktop (#516).

**Comment by auchri** [comment]
Duplicate #664
