### ISSUE TITLE
Status circle on desktop doesnt refresh properly

### ISSUE THREAD

**Issue by Qik000** [telegramdesktop/tdesktop#6890]
### Steps to reproduce
1. Have someone come active
2. Go to their chat
3. That person has to go offline
4. If youre not in the Telegram window or not hovering over the persons contact (while not haiving it selected) the circle wont update
5. Hover your mouse over the contact to update the circle (you dont even have to focus the window)

### Expected behaviour
The little circle should update without this interaction

### Actual behaviour
The little circle doesnt update unless its hovered or otherwise updated client-side

### Configuration
**Operating system:**
Linux Ubuntu 18.04.3 LTS

**Version of Telegram Desktop:**
1.8.15

**Used theme**:
Default

**Comment by damnfella** [comment]
A GIF recording could help explain visual issues much better.

**Comment by Qik000** [comment]
I can explain further, i dont have a means of capturing that as its semi-random

**Comment by DeltaTimo** [comment]
It happens much more reliably when not sharing your last-seen/online status.

0. You do not need to have a chat selected.

Then, as above,

1. have a contact send you a message or have them type. (anything that sets their status to online regardless of sharing last-seen and online status)
2. Wait for the online status to disappear.
3. The circle next to the avatar stays in the contacts list until the corresponding contact's chat is opened or hovered over with the mouse cursor.

This happens on Linux also.

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/6410
