### ISSUE TITLE
[Feature Request] Prefill message field with your previously sent message

### ISSUE THREAD

**Issue by howabouthis** [telegramdesktop/tdesktop#6891]
### Is your feature request related to a problem?
When messaging with a bot that requires specific input, it's easy to mistype the commands. Once you mistype the command, there's no way to prefill the message field with the contents of your last sent message. Instead, you have to write the command all over again.

Also, when you're making multiple syntactically similar queries to the bot, it would be useful to only slightly modify the previous command instead of typing the whole thing again.

### Describe the solution you'd like
There could be a keyboard shortcut to prefilling the message field with the contents of your previously sent message. 

This is very similar behavior to most shells, where pressing up will prefill the command line with the previous shell command. 

### Describe alternatives you've considered
I've tried copy pasting the previously sent command with mouse, but it's usually about as slow as just retyping the whole command.

**Comment by Aokromes** [comment]
why no simply press up and modify your typos?

**Comment by howabouthis** [comment]
> why no simply press up and modify your typos?

Pressing up edits the previous message, it doesn't send a new message.
Most bots that I've dealt with don't register updated messages the same way they do new messages.

**Comment by john-preston** [comment]
@howabouthis You can press up, ctrl+a, ctrl+c, escape, ctrl+v :)

**Comment by howabouthis** [comment]
> @howabouthis You can press up, ctrl+a, ctrl+c, escape, ctrl+v :)

That's a bit closer to the functionality I'm looking for, although too many steps for my taste.
