### ISSUE TITLE
Mac OS X - no scrollbar

### ISSUE THREAD

**Issue by Wanny** [telegramdesktop/tdesktop#6892]
I noticed that in Mac OS X, the scrollbars don't show in the chat window:

![telegram](https://user-images.githubusercontent.com/569307/71325908-3cccac80-24d2-11ea-853e-e0411176a890.png)
(I scrolled up in this chat so the "go to bottom" button shows up)

I tried setting "Show scroll bars" to Always in the OS's general settings and they still don't show up.

I'm using version 5.8.2 beta (non Apple Store version because screw censorship)

**Comment by Aokromes** [comment]
this is for telegram desktop. not telegram macos native application.

**Comment by Wanny** [comment]
oh. For a moment I thought they were the same.

**Comment by Aokromes** [comment]
nope, telegram desktop is version 1.9.1 beta :)
