### ISSUE TITLE
Extremely limited upload speeds 8kb/s-30kb/s

### ISSUE THREAD

**Issue by benhowardau** [telegramdesktop/tdesktop#6893]
I have a 50mpbs connection up/down, and for the past year my telegram upload speeds on Mac desktop and iOS are both limited to 8kbps-30kbps, this is also the case on 4G on iOS. Uploading a 2mb image takes about 10 minutes and it's making working on telegram almost impossible. I've tried multiple networks and reinstalling telegram, but the upload speed has never improved in over a year now.

If anyone has any information, suggestions or has been experiencing similar things. Please let me know. 

Here is a screenshot of network activity while uploading a 2MB file on wifi 50mpbs connection. 

<img width="362" alt="Screen Shot 2019-12-23 at 6 33 04 pm" src="https://user-images.githubusercontent.com/24599507/71346574-ea63bc80-25b3-11ea-8699-b1893e0a5968.png">

**Comment by Aokromes** [comment]
for me it's slow, but no that slow, what version of macos telegram are you using?

**Comment by benhowardau** [comment]
Mac OS Catalina 10.15.1 (19B2106) Telegram v5.8 (185085) // iOS 13.3 Telegram 5.12.2

**Comment by Aokromes** [comment]
this bugtracker is for the multiplataform telegram desktop, not for native macos application.
