### ISSUE TITLE
Tooltip of Links, dates are hovering above the other apps

### ISSUE THREAD

**Issue by 4unkur** [telegramdesktop/tdesktop#6895]
I'm not sure how to reproduce this, but I encountered it about 5 times now.

### Configuration
**Operating system:**

macOs Catalina 10.15.2 (19C57)

**Version of Telegram Desktop:**

1.8.15

**Used theme**:

Night

The tooltip is shown when I hover the link:  

![image](https://user-images.githubusercontent.com/7892851/71396999-52fb7980-2646-11ea-8432-b277c68a2332.png)

The problem is, that tooltip is shown even if Telegram Desktop is not active:

<img width="832" alt="Screen Shot 2019-12-24 at 11 40 28" src="https://user-images.githubusercontent.com/7892851/71396590-f8155280-2644-11ea-866f-498205580ead.png">

This is the PHPStorm, but I encountered the tooltip on the other windows too and I am not sure how to reproduce this. It appears randomly. Also, it is not the case when I hover on the link in Telegram and press CMD Tab to switch to the other app. It's more like, I'm just using another app and this tooltip comes out of nowhere. Also, this tooltip doesn't go away until I open the Telegram app

**Comment by 4unkur** [comment]
Issue is not related to URLs only, date tooltips are also shown:  

![image](https://user-images.githubusercontent.com/7892851/71412494-1ba5c080-2678-11ea-95f3-d28cd80e301e.png)

![image](https://user-images.githubusercontent.com/7892851/71412502-24969200-2678-11ea-9cc7-90d81752f9e5.png)

I was just working in PHPStorm & it came out...

**Comment by lennoximus** [comment]
I have probably a related issue here. When you have an opened tab with emoji's and you get a new message in the app, emoji tooltip appears on top of all applications, while you are hovering the very same location on the screen of the emoji. Complicated explanation, but I can attach the screenshot.
![bbbbbbbb](https://user-images.githubusercontent.com/5410417/71437218-ae3e7200-2701-11ea-85f4-aca3494c01ec.PNG)
Tooltip is positioned near the current cursor position, to be clear.
OS: `Windows 7 64-bit `
Version of Telegram Desktop: `1.8.15`
Used theme: `Night`

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/6885 ?

**Comment by 4unkur** [comment]
@Aokromes yep, it's the same. Closing as duplicate
