### ISSUE TITLE
Archived chat unarchived automatically when get personal message

### ISSUE THREAD

**Issue by fOrgeth** [telegramdesktop/tdesktop#6896]
### Steps to reproduce
1. Move chat to archive
2. Somebody write personal (@your_nick_name) message to you
3. Chat unarchived automatically

### Expected behaviour
Nothing! Archived chat must keep archived

### Actual behaviour
Chat moved to main list

### Configuration
**Operating system:**
macOs 10.14.3 (same behavior at Android)

**Version of Telegram Desktop:**
1.8.15

**Used theme**:
Dark

<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

Same wrong behavior with muted chats.

**Comment by Aokromes** [comment]
Afaik this is intended.

**Comment by balboag** [comment]
_When an archived chat gets a notification, it will pop out of the folder and back into your chat list. Muted chats will stay archived forever._

https://telegram.org/blog/archive-and-new-design#everything-in-its-place

**Comment by fOrgeth** [comment]
Sorry, missed this detail: main problem is muted chats unarchived too!

**Comment by balboag** [comment]
> Sorry, missed this detail: main problem is muted chats unarchived too!

A muted chat will be unarchived if someone replies to a message from you, mentions you or pins a message on a group. Notification settings from the 1:1 chat with that user apply in these cases, so the only way to prevent it would be by muting users who reply/mention you or pin with notification.

**Comment by fOrgeth** [comment]
> > Sorry, missed this detail: main problem is muted chats unarchived too!
> 
> A muted chat will be unarchived if someone replies to a message from you, mentions you or pins a message on a group. Notification settings from the 1:1 chat with that user apply in these cases, so the only way to prevent it would be by muting users who reply/mention you or pin with notification.

But this is nonsense. I do not want to mute users, but there are chats that I want to keep in the archive.
