### ISSUE TITLE
Cannot hear audio while playing video on Telegram Desktop

### ISSUE THREAD

**Issue by somnathrakshit** [telegramdesktop/tdesktop#6899]
Although calls, video messages, voice messages and audio files work smoothly, the audio cannot be heard when a video is being played from Telegram Desktop. I have been using Telegram Desktop 1.9.1 beta. However, the same thing happens on the latest stable version as well.

### Steps to reproduce
1. Upload a video that contains audio as well.
2. Try to play the video from Telegram Desktop version 1.9.1 beta.
3. Although the video plays smoothly, audio cannot be heard at all.

### Expected behaviour
Audio should play along side the video.

### Actual behaviour
Although the video plays smoothly, audio cannot be heard at all.

### Configuration
**Operating system:** Ubuntu 18.04

**Version of Telegram Desktop:** 1.9.1 beta

**Used theme**: Tinted

**Comment by Aokromes** [comment]
works for me on 1.9.1 beta running on windows.
it also works for me on 1.8.5 and 1.9.1 beta running on ubuntu 18.04

**Comment by LoaderB0T** [comment]
Could be related to #5481

**Comment by somnathrakshit** [comment]
It now works properly on 1.9.3. Close this issue now?

**Comment by Aokromes** [comment]
p.s. you can close your own issues.
