### ISSUE TITLE
Emoji autocomplete has 2 entries for :facepalm

### ISSUE THREAD

**Issue by MasterGroosha** [telegramdesktop/tdesktop#6901]
### Steps to reproduce
1. Start typing :facepalm in chat
2. Watch autocomplete

### Expected behaviour
One male-facepalm emoji and one female-facepalm emoji

### Actual behaviour
![изображение](https://user-images.githubusercontent.com/2780044/71475793-e1146300-27f2-11ea-9787-9c5d94570534.png)

I guess the second one is a "shortcut" for :facepalm: (while emoji picker has only :man-facepalming: ) and emoji autocomplete shows both variants as separate emoji 

### Configuration
**Version of Telegram Desktop:** 1.9.1 beta

**Comment by rakvium** [comment]
@MasterGroosha I guess this is not a bug. There is a regular Face Palm (`:person-facepalming:`) emoji character in Unicode, and its modifiers: male (`:man_facepalming:`) and female (`:female_facepalming:`).
See https://emojipedia.org/face-palm/
Telegram has chosen a man as a default person for the facepalm character, and, for example, a woman as a default person for the shrug emoji :woman_shrugging:
