### ISSUE TITLE
I think it's bag in "workmode"

### ISSUE THREAD

**Issue by irocker04** [telegramdesktop/tdesktop#6903]
![Снимок](https://user-images.githubusercontent.com/19604184/71542789-74cd6700-298c-11ea-8eee-8cc47db40b92.PNG)

**Comment by damnfella** [comment]
#bug*

**Comment by irocker04** [comment]
> bug*
> **Unread count shows negative values (-1)**
> 
> Please provide steps to reproduce this.

I just seen all message in muted chats... No other steps =)

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/6100
