### ISSUE TITLE
请问什么时候开始添加中文呢？When do you start adding Chinese?

### ISSUE THREAD

**Issue by Evilrabbit520** [telegramdesktop/tdesktop#6904]
## 写在前面（Write in front）

众所周知，中国是全世界最大的市场，当然使用电报的潜在用户亦是如此，所以，当一个人在软件中无法发现自己国家的母语是很难过的，所以 我恳请电报团队，在下一个发布版本将中文添加在其内部，这样，会有一大堆用户涌入的，再次感谢！

As we all know, China is the world's largest market, and of course the potential users of telegrams are also the same. Therefore, it is very sad when a person cannot find the native language of his country in the software. Chinese is added inside, so there will be a lot of users coming in, thanks again!

**Comment by damnfella** [comment]
## Many other languages are still in beta. 

Currently, chinese-beta is available. Click these links and apply them now!
- [Chinese (Simplified) (简体中文) (beta)](https://t.me/setlanguage/zh-hans-beta)
- [Chinese (Traditional) (繁體中文) (beta)](https://t.me/setlanguage/zh-hant-beta)


***
## Other languages can be found at [translations.telegram.org](https://translations.telegram.org)

![image](https://user-images.githubusercontent.com/51771172/71558658-978a7900-2a7b-11ea-850a-914966c2a04a.png)

### Apply your Native language!
![image](https://user-images.githubusercontent.com/51771172/71558930-4cbe3080-2a7e-11ea-934e-c061a20ca9ff.png)

**Comment by Evilrabbit520** [comment]
哦，非常感谢，我已经尝试将Beta版本加入了我的电报系统，感谢您的帮助，谢谢！


Oh, thank you very much, I have tried to add the Beta version to my telegram system, thank you for your help, thank you!




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"chilly bones"<notifications@github.com&gt;;
发送时间:&nbsp;2019年12月29日(星期天) 晚上11:33
收件人:&nbsp;"telegramdesktop/tdesktop"<tdesktop@noreply.github.com&gt;;
抄送:&nbsp;"Debug"<wangjianing@inidt.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [telegramdesktop/tdesktop] 请问什么时候开始添加中文呢？When do you start adding Chinese? (#6904)




Many other languages are still in beta.
 
Currently, chinese-beta is available. Click these links and apply them now!
  
Chinese (Simplified) (简体中文) (beta)
 
Chinese (Traditional) (繁體中文) (beta)
  
 
Other languages can be found at translations.telegram.org
 

 
Apply your Native language!

**Comment by damnfella** [comment]
Your Welcome!

Close this issue :)
