### ISSUE TITLE
Can't open gif in fullscreen with disabled autoplay

### ISSUE THREAD

**Issue by Remu-rin** [telegramdesktop/tdesktop#6908]
### Steps to reproduce
1. Disable gif autoplay
2. Find a message with a gif, click to download
3. Try to open gif in fullscreen (to get larger view or to be able to zoom)

### Expected behaviour
You should be able to open gif in fullscreen without enabling autodownload. Why even merge autoplay and autodownload settings? It's different things.
At least you should be able to do this via context menu item.

### Actual behaviour
Disabling autodownload now disables autoplay too, preventing opening gif in fullscreen.
Even in context menu "open gif" item disappears.

### Configuration
**Operating system:** Windows

**Version of Telegram Desktop:** 1.9.2

**Comment by Remu-rin** [comment]
Also, previously when you opened gif in fullscreen and clicked on it again, fullscreen closed. Now it does not, you need to click outside of the gif or use X button in the corner.

**Comment by Remu-rin** [comment]
And now you don't see gifs size when autodownload is disabled. Even on mouseover. Also "gif" text in the corner is hidden until mouseover for some reason, making harder to distinguish gifs and videos.

**Comment by Remu-rin** [comment]
Also now you don't see any difference between already downloaded and not downloaded gifs. Previously apart from the size there were visually different buttons to play and download. Now it shows play button everywhere.

**Comment by aNNiMON** [comment]
+1

One more issue: immediately after sending the GIF it can be opened in full screen just by clicking on it. But after a while clicking on it just starts or stops playback.

**Comment by john-preston** [comment]
@aNNiMON If autoplay is disabled there should be "Open GIF" in context menu. It is not there right now, I'll fix that in the next version.
