### ISSUE TITLE
Can't see upload progress when replace media with autoplay enabled

### ISSUE THREAD

**Issue by Neurotoxin001** [telegramdesktop/tdesktop#6909]
### Steps to reproduce
1. Enable autoplay for videos/gifs
2. Post some video/gif
3. Try to replace media with "edit" button
4. You can't see upload progress and video/gif is still playing

### Configuration
**Operating system:** win 10 ltsc 1809

**Version of Telegram Desktop:** 1.9.2 beta

**Used theme**: default dark

**Comment by john-preston** [comment]
@Neurotoxin001 Do you see the progress as a radial animation? Or no radial animation is shown either?

**Comment by Neurotoxin001** [comment]
No radial animation, but when I click on video it's ask me to stop or continue upload

**Comment by Neurotoxin001** [comment]
And also another visual bug:
1. upload some video in chat/channel
2. you can't see the time of uploading or status of post (read or not), even when I mouse over on post with video, for example https://t.me/rand2ch/11436
3. to show it you must write some caption under video

![image](https://user-images.githubusercontent.com/39812401/71576414-af0c4500-2b01-11ea-979b-2c93f4bdf02b.png)
![image](https://user-images.githubusercontent.com/39812401/71576426-b6cbe980-2b01-11ea-87c0-14e7a476f1ab.png)

**Comment by john-preston** [comment]
@Neurotoxin001 Thanks! I'll fix both that things in the next version.
