### ISSUE TITLE
"Send by Ctrl-Enter" setting doesn't work in picture description field

### ISSUE THREAD

**Issue by mikkovedru** [telegramdesktop/tdesktop#6911]
### Steps to reproduce
1. Go to "`Settings`" -> "`Chat Settings`" -> "`Messages`" and enable `Send by Ctrl+Enter` setting
2. Drag and drop a picture to yourself. You will receive a pop-up, where you can write a text description.
3. Start writing.
4. Press `Enter` to create a new line.
5. Notice, that instead of simply creating a new line the picture/text were sent.

### Expected behaviour
- Pressing `Enter` should create a new line.
- Pressing `Ctrl+Enter` should send the picture (or update the text, if I am editing the already sent picture/text)

### Actual behaviour
- Pressing `Enter` sends the picture
- Pressing `Ctrl+Enter` sends the picture

In order to create a new line I am forced to press `Shift+Enter`. I am glad, that this work-around exists, but simply pressing `Enter` should be enough. Keys should not have a different and opposing functionality in the seemingly similar text fields.

### Configuration
**Operating system:**
Linux Mint Cinnamon 19.2

**Version of Telegram Desktop:**
1.9.2 beta. 

**Used theme**:
Classic

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/6634
