### ISSUE TITLE
100% CPU load when edit post with autoplay video

### ISSUE THREAD

**Issue by Neurotoxin001** [telegramdesktop/tdesktop#6912]
### Steps to reproduce
1. enable autoplay for videos
2. post some video in chat/channel or your saved messages (ctrl+0)
3. add some caption (w/o caption all is fine)
4. press "edit" on post
5. CPU usage will be 97-98%

### Configuration
**Operating system:** win10 ltsc 1809

**Version of Telegram Desktop:** 1.9.2 beta

**Used theme**: default dark

**UPD**: Same for gifs **and images**

**Comment by hookzof** [comment]
I confirm

![image](https://user-images.githubusercontent.com/22233835/71582146-e981dc00-2b19-11ea-95ae-2decd4594058.png)
