### ISSUE TITLE
[Feature Request] Add more Lines input field for edititng media caption

### ISSUE THREAD

**Issue by AlexMercier** [telegramdesktop/tdesktop#6914]
Telegram support 1024 sumbols for media caption. But input field for media caption shows only 3 lines which accomodate only 60 symbols per screen. This is very very uncomfortable to work with edititng long text in captions (Photo, Video, Docs).   

Can you please expand input field or make it expandable with mouse cursor like Edit Text fields in Chrome browser etc.
Thnk you.

Windows 10 x64, Desktop Client Version: 1.9.2 beta.
Font size in Windows 125%
Screen 1920x1080

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/5395
