### ISSUE TITLE
Video messages in 1.9.2

### ISSUE THREAD

**Issue by Remu-rin** [telegramdesktop/tdesktop#6915]
### Steps to reproduce
1. Open https://t.me/telegram/90 and https://t.me/telegram/104

### Expected behaviour
Problem 1: Video messages in chat should be larger, like other messages with text or image.
Problem 2: On video messages without caption you should be able to see timestamp and view counter (if on/from channel).

### Actual behaviour
Problem 1: Video messages are now smaller, similar to GIF. Same problem with link previews with video, like coub.com.
Problem 2: You can't see timestamp and view counter on video message without caption. Same problem with GIFs.

### Configuration
**Operating system:** Windows

**Version of Telegram Desktop:** 1.9.2

**Comment by john-preston** [comment]
@Remu-rin By video messages you mean round video messages or any video files?

**Comment by Remu-rin** [comment]
@john-preston Regular video files, not round.

**Comment by Neurotoxin001** [comment]
1. Agree
2. Already fixed https://github.com/telegramdesktop/tdesktop/commit/4aaecfd531581677dbd309d02fb0597eb92e351f
