### ISSUE TITLE
File selection dialog degraded on 1.9.2

### ISSUE THREAD

**Issue by atis** [telegramdesktop/tdesktop#6916]
### Steps to reproduce
1. Press Send file

### Expected behaviour
Fully featured Gnome / Nautilus dialog should open (was working on previous version)

### Actual behaviour
Very minimalistic file dialog opens - i have hard time identifying it, but it looks like wine

### Configuration
**Operating system:**
Ubuntu 18.04 / Mate 1.20.1

**Version of Telegram Desktop:**
1.9.2

**Used theme**:
default

<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by atis** [comment]
![Selection_1017](https://user-images.githubusercontent.com/1108226/71606659-8de83a80-2b7b-11ea-83a6-42cb7c7451c2.png)

**Comment by Aokromes** [comment]
idk witch is but i don't think it's wine (i have tried on 3 different linuxes and i don't remember to have wine installed on them)

**Comment by atis** [comment]
On 1.8.15 (installed in separate directory) file dialog is desktop default (Nautilus) with all shortcuts and file preview. 

![Selection_1018](https://user-images.githubusercontent.com/1108226/71607685-1b2f8d00-2b84-11ea-9ad9-d30b846b8880.png)

**Comment by Aokromes** [comment]
maybe it will be fixed soon(TM)
https://github.com/telegramdesktop/tdesktop/commit/1ee7801c0b5f74269104fa7d914c9a0821e1628e

**Comment by atis** [comment]
@Aokromes thanks, waiting for next build to see if it helps.
I wish i hadn't spent hour reading about Qt and GTK dialogs :D

**Comment by john-preston** [comment]
@atis I've fixed that in code, will be available today.

**Comment by vapespb** [comment]
@john-preston @atis
KDE, same trouble in 1.9.2, and it's repaired now in 1.9.3, thanks

**Comment by atis** [comment]
Fixed in 1.9.3
Thanks

**Comment by atis** [comment]
@john-preston @Aokromes Same issue again in 1.9.20 beta

**Comment by atis** [comment]
Fixed in 1.9.21
