### ISSUE TITLE
Can't typing chinese at Ubuntu on 1.8.15

### ISSUE THREAD

**Issue by atx49559** [telegramdesktop/tdesktop#6918]
Install from 18.04 snap store
Telegram ver 1.8.15
iBUS and gcin both cant' typing chinese
please fix it thank you!!

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/2013

**Comment by venorz** [comment]
Same problem here on Ubuntu 19.10, but only happens when I installed Telegram from snap store. The apt source version is absolute OK.

**Comment by atx49559** [comment]
Thanks, the apt source version is OK!
Btw, Install Telegram in Ubutnu 18.04 LTS
