### ISSUE TITLE
Group chat in the archive still increases the number of unread messages, although it should not

### ISSUE THREAD

**Issue by IlyaBarkov** [telegramdesktop/tdesktop#6919]
### Steps to reproduce
1. Install Telegram Desktop
2. Add to any group chat
2. Move group chat to archive
4. Wait for new chat messages

### Expected behaviour
When new messages arrive, there are no notifications. The counter of the number of unread messages on the icon in the system tray should not change.

### Actual behaviour
When new messages arrive, there are no notifications. But the counter of the number of unread messages on the icon in the system tray increases. Although this should not be, because group chat is in the archive.
In the Telegram version for smartphones, this is not observed, only in the Telegram for the desktop.

### Configuration
**Operating system:**
Windows 10

**Version of Telegram Desktop:**
1.8.15

**Used theme**:
default (standard)

**Comment by john-preston** [comment]
They're counted as muted. You can remove muted chats from the unread counter in Settings > Notifications.

**Comment by IlyaBarkov** [comment]
> They're counted as muted. You can remove muted chats from the unread counter in Settings > Notifications.

No, if you turn it off there, then all the counters are not displayed - both the main chats and the chats from the archive. But only archive chats should be excluded from this analysis. That is, make the same logic as in Telegram for Android, for example.

**Comment by IlyaBarkov** [comment]
> They're counted as muted. You can remove muted chats from the unread counter in Settings > Notifications.

That is, if the chat is archived, then it should not fall into the unread counter at all. Regardless of the settings for basic chats.

**Comment by john-preston** [comment]
@IlyaBarkov For now it does so — by design, sorry. This can be changed in the future.

**Comment by IlyaBarkov** [comment]
> @IlyaBarkov For now it does so — by design, sorry. This can be changed in the future.

But this also contradicts the logic of work in Telegram for Android or for iPhone. It turns out that I have Telegram on 2 devices (smartphone and desktop computer) - and they have the opposite logic of working with archive chats?
