### ISSUE TITLE
Build Failed

### ISSUE THREAD

**Issue by alsoGAMER** [telegramdesktop/tdesktop#6921]
### Steps to reproduce
1. Follow the build instruction for gyp/CMake
2. Wait for "Linking CXX executable ../bin/Telegram"

### Expected behavior
The building process should complete without errors

### Actual behavior (build log)
https://pastebin.com/nQtGN8U6

### Configuration
**Operating system:
NAME="Ubuntu"
VERSION="16.04.6 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.6 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial**

**Virtual Environment:
Google Cloud Platform**

**Version of Telegram Desktop:**
1.9.3

**Used theme**:
Not relevant

**Comment by john-preston** [comment]
I hope it works that way :/

**Comment by alsoGAMER** [comment]
Nope, same error, but the architecture of the cpu at gcp is 64bits, not 32
