### ISSUE TITLE
[Feature Request] User chat restriction for less than one day

### ISSUE THREAD

**Issue by vladislav805** [telegramdesktop/tdesktop#6923]
### Is your feature request related to a problem?
Now there is no way to restrict the user to a short time, for example, to several hours.

### Describe the solution you'd like
In "custom" add the time selection. API allows this to be implemented.

### Describe alternatives you've considered
Instead of adding to "custom", make a separate item "restrict for ..." -> N minutes / hours.

### Additional context
--

**Comment by BoberMod** [comment]
It would be better not only "for less than one day", but for custom time in general, like "restrict to 02.02.2019 12:19" (day and time in this day).

**Comment by Neurotoxin001** [comment]
Use combot.

**Comment by vladislav805** [comment]
> Use combot.

@Neurotoxin001, why should I use some kind of bot when I could do it natively through the Telegram interface?

**Comment by Neurotoxin001** [comment]
Because it's already done and using by many people for years.

**Comment by vladislav805** [comment]
@Neurotoxin001, this does not negate the fact that in the native **official** client you can not set the time for end restriction.
P.S. This is a Telegram repository, not a place to advertise bots. Thanks for understanding.

**Comment by CrazyHackGUT** [comment]
> Use combot.

Combot is free only before you have up to 1000 members.
So your suggestion is shit for big chats.

**Comment by RememberTheAir** [comment]
This honestly sounds more as a bug rather than an enhancement, since users expect to be able to restrict people for a few hours/minutes - especially if they come from a mobile app

**Comment by Neurotoxin001** [comment]
+

**Comment by RememberTheAir** [comment]
It's still impossible to select the current day from the date picker when restricting an user
