### ISSUE TITLE
GIF files no longer play at all

### ISSUE THREAD

**Issue by Hezkore** [telegramdesktop/tdesktop#6925]
Gifs used to play just fine, I sent one about 2 days ago.
But the latest update totally broke Gifs.
Example:
![2020-01-01_05-16-39](https://user-images.githubusercontent.com/1727541/71638078-4f737e00-2c56-11ea-80a7-927bafedd419.gif)

### Steps to reproduce
1. Record a Gif
2. Send Gif and notice it play in the preview window
3. Notice the Gif not playing the conversation window
4. Click the Gif to open it and notice it's not playing
5. Download Gif and open it via an external application and notice it playing fine

### Expected behaviour
Gifs should work

### Actual behaviour
They don't work, and never show a single frame

### Configuration
**Operating system:**
Windows 10

**Version of Telegram Desktop:**
v 1.9.3

**Used theme**:
Night

**Comment by john-preston** [comment]
@Hezkore Can you contact me at @preston and send me some such gifs? Thanks.

**Comment by zun010** [comment]
Yep, i have the problem too

**Comment by NayruLove** [comment]
I have this problem too
In my case, gif have the "play" icon in it center, and not play even when i click to that "Play" icon, instead it come to full screen with preview like a single image file.
![image](https://user-images.githubusercontent.com/24603413/71704040-94d8ac80-2e0a-11ea-95ab-53dc6b1f2a47.png)

**Comment by Laiteux** [comment]
Me and multiple friends are having this issue as well.

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/6829 ?

**Comment by winterwolf** [comment]
Same problem on Manjaro Linux 18.1.5

**Comment by rainydaydriver** [comment]
Same issue. Windows 10.  Version 1.9.3.  Have had this issue since version 1.9.3.  Uninstalling and then reinstalling telegram fixes the issue for about a day before it happens again.

**Comment by AsuraTS** [comment]
Same issue. Windows 10. Version 1.9.3.
Also, gif files are saved as .mp4 video, not a gif - 

![2020-01-14 23-01 003](https://user-images.githubusercontent.com/12550060/72380454-7fc31e00-3726-11ea-8e36-2053060059db.jpg)

**Comment by Hezkore** [comment]
I'm not sure, but was this fixed in the recent Telegram update?

**Comment by Aokromes** [comment]
test on 1.9.8 plz

**Comment by zun010** [comment]
> test on 1.9.8 plz

Everything works, thank you
