### ISSUE TITLE
Square, indicating a space

### ISSUE THREAD

**Issue by dobcrypto** [telegramdesktop/tdesktop#6928]
A square, indicating a space is displayed, how to remove?
![y9M8urVaT26cpcixlkfxyA 1](https://user-images.githubusercontent.com/16653151/71641401-7f4d7080-2cac-11ea-9312-361329bb05e2.png)
 
### Steps to reproduce
Just autoupdate from latest stable version.

### Expected behaviour
Lack of these squares.

### Actual behaviour
A square, indicating a space is displayed everywhere(chat, masseges, etc).
### Configuration
**Operating system:**
Win 7 SP1 x64
**Version of Telegram Desktop:**
1.9.3
**Used theme**:
Classick

**Comment by dobcrypto** [comment]
Version of Telegram Desktop:
1.9.7
Same shit =(
Please, fix this.

**Comment by Aokromes** [comment]
what's the language of your OS? because i cannot reproduce myself.

**Comment by dobcrypto** [comment]
@Aokromes Russian.
Maybe its coz no some needed lng files/parts in Win, dont know...
No matter what lng I select in Telegram Ru or Eng, same problem.

**Comment by Aokromes** [comment]
https://t.me/tgbetachat/215251 here another cannot reproduce.

**Comment by groozchique** [comment]
I recommend to check Windows settings, check the updates or reinstall it (lol) since I can't reproduce it on freshly installed Windows 7 SP1 x64 build with Russian language without any updates installed (link above)

**Comment by Aokromes** [comment]
@dobcrypto can you check https://superuser.com/questions/336197/unicode-characters-suddenly-start-displaying-as-boxes-in-some-applications ?

**Comment by dobcrypto** [comment]
@Aokromes I think I know wtf is it.
I'm use long years this tool https://code.google.com/archive/p/gdipp/downloads
So, after kill this in procces - TG display good.
But I do not want to refuse to use the gdipp. =(

**Comment by Aokromes** [comment]
well, it's clear it's not telegram desktop bug, report the bug to the developers of that application.
