### ISSUE TITLE
[Question] What happened to the scrolling in the latest version?

### ISSUE THREAD

**Issue by damnfella** [telegramdesktop/tdesktop#6930]
**Why is it difficult to scroll for the touchpad users 🤔 ?**

In the previous version (v 1.8.15):
- The speed of scrolling will depend on the speed of swiping

In the new version (v. 1.9.3):
- No matter the swipe speed, the number of lines/messages I can scroll is the same. and is rather more difficult now.

Please bring back the old scrolling method, it's very difficult for me to scroll.

**Comment by jeffythedragonslayer** [comment]
What operating system is this on?

**Comment by damnfella** [comment]
Windows 10. But i've even tested this on linux mint 19.3

**Comment by ilya-fedin** [comment]
> Why is it difficult to scroll for the touchpad users thinking ?

Qt was updated in v1.9.0, does this answer your question?

> Please bring back the old scrolling method, it's very difficult for me to scroll.

And I hope you understand that this is not possible

**Comment by damnfella** [comment]
> hope you understand that this is not possible

why not?

**Comment by ilya-fedin** [comment]
> why not?

Because features from Qt 5.12 are used. And it is impossible to use old Qt version forever anyway.
+ there are was no wayland on 5.6.
