### ISSUE TITLE
[Bug] Minimize button on titlebar unmaximize window

### ISSUE THREAD

**Issue by maxoku** [telegramdesktop/tdesktop#6932]
### Steps to reproduce
1. Maximize Telegram Window
2. Click on minimize button on titlebar
3. Click on the taskbar or tray icon

### Expected behaviour
Window should appear again maximized like it was before

### Actual behaviour
Window is restored unmaximized.

### Configuration
Operating system: Windows 8.1
Version of Telegram Desktop: 1.9.3
Used theme: Day

If I minimize window from taskbar icon by clicking on it or by context menu it behaves normally.
Also if I'm restoring window from minimize button the restoring animation is distorted like it's not restoring from the taskbar icon, but from the right (empty) part of the taskbar.

Also context menu doesn't work on titlebar. I think that might be related, but maybe I should just open new bug report for it? :thinking:

**Comment by maxoku** [comment]
@john-preston 
It would be nice if you stated why are you closing this? It should be opened till it fixed.
And could you answer me if I have to open new bug report for no context menu on titlebar?

**Comment by Aokromes** [comment]
It's fixed on 322367c

**Comment by maxoku** [comment]
@Aokromes @john-preston 
That's nice, but even beta with this fix isn't released, so technically it isn't. Is there a schedule anywhere for releases? And thanks for the respond and taking care of the problem. Though I would like to see the result myself (even if in beta) and close the issue by myself when I see it's fixed.
And what about context menu in titlebar?
