### ISSUE TITLE
Officializing completed VEC (Venetian language) localization

### ISSUE THREAD

**Issue by AlessandroMocellin** [telegramdesktop/tdesktop#6933]
Hello,
if you know how to help us on this, please contact me
This is the full translation: t.me/setlanguage/lenguaveneta
All strings are translated, but some are blocked by a "critical phrase" marker, which apparently can be overcome only by some sort of approval by Telegram staff.
The link for the officialized localization should be "/vec"

Thanks!
Alessandro Mocellin
@Academia_Bona_Creansa

**Comment by RememberTheAir** [comment]
I think you should contact the in-app support for this kind of requests

**Comment by AlessandroMocellin** [comment]
I already did

Il mar 21 apr 2020, 19:19 RememberTheAir <notifications@github.com> ha
scritto:
