### ISSUE TITLE
[Feature Request] Personal Dictionary and Ignored Words

### ISSUE THREAD

**Issue by ali-shamakhi** [telegramdesktop/tdesktop#6934]
### Is your feature request related to a problem?
Currently, there is no way to manage custom words added to dictionary (of the spellchecker) or words that are ignored.

### Describe the solution you'd like
Add these two sections to the settings:

- Personal Dictionary
- Ignored Words

Both of them will list the corresponding words with the ability to delete any entry.

**Comment by Aokromes** [comment]
it looks not even microsoft have such feature.
https://www.windowscentral.com/how-edit-custom-spell-check-dictionary-windows-10
