### ISSUE TITLE
[UI] Sticker post date crawls out of the window

### ISSUE THREAD

**Issue by CrazyHackGUT** [telegramdesktop/tdesktop#6935]
If user posted sticker and client uses minimal width, post date can crawls out of the window:
<details><summary><b>Screenshots</b>:</summary>
<img src="https://user-images.githubusercontent.com/12576822/71645086-32898a00-2cec-11ea-8b63-01d8e943253a.png" />
<img src="https://user-images.githubusercontent.com/12576822/71645092-4503c380-2cec-11ea-9c63-cea4200a1184.png" />
<img src="https://user-images.githubusercontent.com/12576822/71645110-8300e780-2cec-11ea-99cf-37b5699154fb.png" />
</details>

**OS**: Windows 10 (10.0.17763.914)

**Comment by vladislav805** [comment]
Confirm. Windows 10
Windows scale: 125%; Telegram scale: 125%.
![image](https://user-images.githubusercontent.com/10882576/71645192-7f1d9700-2ce5-11ea-97f1-94bf32819685.png)

**Comment by Rabb1tof** [comment]
Confirm too.
