### ISSUE TITLE
GIF search needs download the GIF to see them

### ISSUE THREAD

**Issue by ea4eoz** [telegramdesktop/tdesktop#6937]
### Steps to reproduce
1. Search for a GIF
2. Wait for search results to appear

### Expected behaviour
Tell us what should happen

GIFs must be animated

### Actual behaviour
Tell us what happens instead

Only previews of GIFs are shown, needing download to see the actual GIF, which defeat any search purpose. Same problem with user saved GIFs in GIF tab.

### Configuration
**Operating system:**
Debían bullseye

**Version of Telegram Desktop:**
1.9.3

**Used theme**:
Default

An example:

![Screenshot_20200101_235911](https://user-images.githubusercontent.com/46333142/71647228-d9255900-2cf3-11ea-8907-0b6ead6dab13.jpg)

Changing Data and storage configuration do not solve the problem.

**Comment by ea4eoz** [comment]
After playing with the settings I discovered the Automatically download files option must be active to see the gifs. Somehow Telegram mistakes GIFs with files.

**Comment by john-preston** [comment]
@ea4eoz Yeah, I need to attach this auto download to GIFs auto play instead of files auto download.
