### ISSUE TITLE
Telegram desktop crash on aarch64 with animated stickers

### ISSUE THREAD

**Issue by pulpo** [telegramdesktop/tdesktop#6938]
### Steps to reproduce
1. Open Telegram Desktop on ARM device
2. Search for a chat with an animated sticker, or try to send a animated sticker
3. Stickers reproduce and then telegram crash

### Expected behaviour
The app should stay open

### Actual behaviour
Tell us what happens instead

### Configuration
**Operating system:** Manjaro-ARM 19.12

**Version of Telegram Desktop:** 1.8.15

**Used theme**: Default in night mode

<details><summary><b>Logs</b>:</summary>
[swscaler @ 0x7f7c3f74b0] No accelerated colorspace conversion found from yuv420p to bgra.
Abortado (`core' generado)

</details>

**Comment by Silur** [comment]
same issue, output of gdb from binary (no debug symbols)
```
0x0000fffff460eab8 in raise () at /usr/lib/libc.so.6
#1  0x0000fffff45fbce8 in abort () at /usr/lib/libc.so.6
#2  0x0000aaaaab81b940 in MTP::internal::TypeData::~TypeData() ()
#3  0x0000aaaaaca61c58 in  ()
#4  0x0000aaaaaca61f6c in Lottie::Cache::readHeader(Lottie::FrameRequest const&) ()
#5  0x0000aaaaaca62098 in Lottie::Cache::Cache(QByteArray const&, Lottie::FrameRequest const&, base::unique_function<void (QByteArray&&)>) ()
```

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/6574

**Comment by Silur** [comment]
As the referenced issue is also closed and doesn't include a direct core dump I don't see any reason to close this one too as it's far from being resolved :)
