### ISSUE TITLE
Telegram 1.9.2/.3 fails on Mint 17 (Ubuntu 14?)

### ISSUE THREAD

**Issue by EinzigArdik** [telegramdesktop/tdesktop#6939]
README.md says Telegram Desktop supports _Ubuntu 12.04 - Ubuntu 19.10._

After I updated Telegram "inline" (using the update button inside Telegram) it failed silently.

Starting Telegram from terminal gives this error:

<pre>/home/ardik/Telegram/Updater:
    /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.20' not found
    (required by /home/ardik/Telegram/Updater)
</pre>

My libstdc++6 supports  `GLIBCXX_3.4.19' max.
My gcc is of version Ubuntu 4.8.4-2ubuntu1~14.04.4
It apparently is the newest version available on Mint 17, which is based on Ubuntu 14.04.

If I'm not missing something essential, then
Telegram 1.9(.3) - at least the `updater` - is not supported in Ubuntu 12 & 14.

So either 

- it should be linked against  `GLIBCXX_3.4.19' (or probably even lower for Ubuntu 12.04 support) to further support these - admittedly old - versions,

or

- README.md should be updated accordingly

_Nonetheless, many thanks for this wonderful project!_

**Comment by EinzigArdik** [comment]
Introduced in 1.9.2
1.9.1 starts properly.

**Comment by john-preston** [comment]
@EinzigArdik I think with migration to CMake I forgot to link libstdc++ statically :(

**Comment by docholiday** [comment]
The same problem occured on CentOS 7.

**Comment by Akhlys** [comment]
the libstdc++ in Mint 17.3, perhaps Mint 17.9 as well, is too old for telegram desktop. Made a system upgrade to mint 18 today (which surprisingly went through without much hassle) and telegram desktop runs again. As support for Mint 17.3 ended 2019, tho in april, I first thought that was some kind of prank :D

**Comment by jamal919** [comment]
> The same problem occured on CentOS 7.
> To be precise, I'm on CentOS Linux release 7.7.1908 (Core).
> 
> The libstdc++6 here also supports `GLIBCXX_3.4.19' max.
> The newest gcc version here is gcc-4.8.5-39.el7.x86_64

Exactly the same issue with same configuration here.

**Comment by josepsanzcamp** [comment]
> @EinzigArdik I think with migration to CMake I forgot to link libstdc++ statically :(

Hi.

Seems that the same problem too apply to the Updater binary.

Josep.

**Comment by john-preston** [comment]
@josepsanzcamp It should be fine in 1.9.4, was broken in 1.9.3 :(

**Comment by josepsanzcamp** [comment]
Hi John.

I'm using the latest binaries (tsetup.1.9.7.tar.xz) downloaded from the https://desktop.telegram.org/ and seems that the Updater binary continues having the same issue:

ldd /usr/local/bin/Updater 
/usr/local/bin/Updater: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /usr/local/bin/Updater)
	linux-vdso.so.1 =>  (0x00007fff00bea000)
	libc.so.6 => /lib64/libc.so.6 (0x00007fcac452a000)
	libstdc++.so.6 => /lib64/libstdc++.so.6 (0x00007fcac4223000)
	libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007fcac400d000)
	/lib64/ld-linux-x86-64.so.2 (0x00007fcac48f8000)
	libm.so.6 => /lib64/libm.so.6 (0x00007fcac3d0b000)

Thanks in advance.

Josep.

**Comment by josepsanzcamp** [comment]
Hi John.

As a temporary solution in CentOS 7, I'm using this trick:

LD_PRELOAD=$HOME/torbrowser/Browser/TorBrowser/Tor/libstdc++/libstdc++.so.6 $HOME/bin/Telegram &

When telegram try to do a self update, with this trick runs as expected and telegram restarts executing the new release.

Josep.

**Comment by john-preston** [comment]
@josepsanzcamp oh shi~, I still didn't fix it indeed. Thanks for the report and your patience.

**Comment by nmschorr** [comment]
Same problem.  Tried Josep's workaround on Centos 7 and couldn't get it to work.

/etc-> cat redhat-release
CentOS Linux release 7.7.1908 (Core)

/home/admin/apps/Telegram-> set | grep libstdc++.so.6
LD_PRELOAD=/usr/lib64/libstdc++.so.6

/home/admin/apps/Telegram-> ls
Telegram  Updater

/home/admin/apps/Telegram-> ./Telegram
/home/admin/apps/Telegram/Updater: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /home/admin/apps/Telegram/Updater)

**Comment by josepsanzcamp** [comment]
Hi Nancy.

I found the correct libstdc++.so.6 using this trick:

for i in $(locate libstdc++.so); do echo $i; readelf -a -W $i 2>/dev/null|grep ABS|grep 3.4.20; done

In my case, the tor browser provide their own libstdc++.so.6 that is compatible with the Updater binary.

Josep.

**Comment by nmschorr** [comment]
> Hi Nancy.
> 
> I found the correct libstdc++.so.6 using this trick:
> 
> for i in $(locate libstdc++.so); do echo $i; readelf -a -W $i 2>/dev/null|grep ABS|grep 3.4.20; done
> 
> In my case, the tor browser provide their own libstdc++.so.6 that is compatible with the Updater binary.
> 
> Josep.

Thanks Josep. All fixed now. -Nancy

**Comment by josepsanzcamp** [comment]
Hi John and Nancy.

I confirm that the Updater binary of the release 1.9.13 runs without problems in Centos 7.

Thanks.

Josep.

**Comment by josepsanzcamp** [comment]
Hi again.

Today, Telegram was updated to the release 2.1.10, and my surprise has been that and old error appeared again.

Telegram: /lib64/libc.so.6: version `GLIBC_2.18' not found (required by Telegram)

In reality, is not the same error that the previously reported error, but it's similar in esency. Another time the GLIBC_2.18 is causing problems in my system.

To try to fix a problem without updating my operating system (centos 7 at the moment), I have downloaded the glibc-2.18 and have compiled it on my system.

```
wget http://ftp.gnu.org/gnu/glibc/glibc-2.18.tar.gz
tar xvzf glibc-2.18.tar.gz 
cd glibc-2.18/
mkdir build
cd build/
../configure --prefix=/opt/glibc-2.18
make -j4
make install
```

And then, to launch Telegram, I have created a script with the follow line:

```
/opt/glibc-2.18/lib/ld-linux-x86-64.so.2 --library-path /opt/glibc-2.18/lib:/usr/lib64/ $HOME/bin/Telegram
```

And now, it works as expected!!!

I understand that you are using a more modern glibc release, I'm not requesting a legacy compatibility with olds systems in this message, I only want to inform and contribute with a temporary solution to help other users that can live the same problem with the Telegram Desktop.

Josep.

**Comment by john-preston** [comment]
@josepsanzcamp Strange, I shouldn't have changed anything yet. Which was the last version that worked fine in your case?

**Comment by josepsanzcamp** [comment]
Hi John.

I have downloaded some previous releases and this is the results of my tests:

- 2.1.10 => problem found
- 2.1.9.beta => problem found
- 2.1.8.beta  => problem not found, but appear a message in the top of the window explaining that I must to update the operating system if I want to continue receiving updates after september, 1
- 2.1.7 => problem not found

Referring to the message of the top window: it's mandatory to update the operating system??? or I can continue using Telegram with updates using a more new release of glibc as I'm doing now???

Thanks in advance.

Josep.

**Comment by john-preston** [comment]
@josepsanzcamp It still shouldn't have happened, I need to fix that :(

Yes, for now in Linux I'll look on glibc version when depreciating old systems. But I'll start building them in Ubuntu 16.04 starting from September.

**Comment by docholiday** [comment]
> Hi John.
> 
> I have downloaded some previous releases and this is the results of my tests:
> 
>     * 2.1.10 => problem found
> 
>     * 2.1.9.beta => problem found
> 
>     * 2.1.8.beta  => problem not found, but appear a message in the top of the window explaining that I must to update the operating system if I want to continue receiving updates after september, 1
> 
>     * 2.1.7 => problem not found
> 
> 
> Referring to the message of the top window: it's mandatory to update the operating system??? or I can continue using Telegram with updates using a more new release of glibc as I'm doing now???
> 
> Thanks in advance.
> 
> Josep.

I can confirm this problem again. As Josep me and my colleagues are on CentOS 7 (CentOS 7.8 with all updates).
We can't use CentOS/RedHat 8 yet in our company as our patchmanagement doesn't support the new package structure there, so we are stuck with the glibc versions we get with CentOS 7 for now. Would really appreciate telegram working with it until our switch to CentOS 8.

**Comment by ilya-fedin** [comment]
> or I can continue using Telegram with updates using a more new release of glibc as I'm doing now???

glibc is a base of your system, you can't "just update glibc"

**Comment by john-preston** [comment]
@docholiday The latest 2.1.11 should really work in CentOS 7. Is it working?

**Comment by josepsanzcamp** [comment]
Hi @docholiday 

I confirm that 2.1.11 is working successfully with the default glibc of the centos 7.

Josep.

**Comment by docholiday** [comment]
Hi John, hi Josep,

sorry for the late reply. Yes, I can confirm that telegram is working again on CentOS 7 (including a warning, that it will stop updating on september 1st, if the OS is not updated before). Thanks!
