### ISSUE TITLE
Disable notifications in muted chats

### ISSUE THREAD

**Issue by TheAppService** [telegramdesktop/tdesktop#694]
Hello,

could you please add an ability to disable those notifications:
![bildschirmfoto vom 2015-05-02 16 30 14](https://cloud.githubusercontent.com/assets/6033570/7441442/8c1335ca-f0e8-11e4-8393-c689dcb3b177.png)
When the chat, they relate to is muted ?

Thank you very much!

Daniel

**Comment by TheAppService** [comment]
Or could you perhaps offer the settings to toggle that off for every chat ? Especially in chats where many people write many messages it's just annoying.

**Comment by auchri** [comment]
Implemented in 0.8.53 dev
