### ISSUE TITLE
[Question] How to custom Spell-Checker dictionary?

### ISSUE THREAD

**Issue by neesti** [telegramdesktop/tdesktop#6940]
Hello.
When we add a word to spell-checker of Telegram, where the word will be saved, I mean which file or path?
I mean those words that have been marked by a red line and the user can add that word to the spell-checker dictionary.

Thank you.

**Comment by Aokromes** [comment]
on windows:
https://www.windowscentral.com/how-edit-custom-spell-check-dictionary-windows-10

**Comment by neesti** [comment]
I use Linux Mint 19.3

**Comment by Aokromes** [comment]
https://www.systutorials.com/docs/linux/man/1-enchant/
