### ISSUE TITLE
Telegram mark all messages as read

### ISSUE THREAD

**Issue by Ali-Hamed** [telegramdesktop/tdesktop#6942]
### Steps to reproduce
1.When i open a channel or group and i read for example 3 messages from the channel or groupe all the massage are marked as read while in telegram for mobile this problem doesn't happen.

2. Telegram for Android Have already a feature to Count Unread messages ,when i open a channel or group with 100 messages in it and read only 3 messages , the notification count of this channel/group  change from 100 to 97 which don't happen in telegram for windows

### Expected behaviour
the messages count should change(decrease) as i read few messages 

### Actual behaviour
**when i enter a channel/group the message count vanish as if i read all the messages while i only read few**

### Configuration
**Operating system:**
Windows 10 - 64 bit 
**Version of Telegram Desktop:**
v 1.9.3  which was released 31.12.19
**Used theme**:
Classic

**Hope to hear from you soon**

**Comment by Ali-Hamed** [comment]
Sorry i forget to mention, when i open telegram for android after this issue happen ,the channel/group message also marked as all read while i really read only few messages(using Telegram Desktop)

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/775

**Comment by Ali-Hamed** [comment]
@Aokromes ,this definitely a popular bug since you opened the issue on May 31, 2015 ,almost 5 years (1677 days) with no progress.
@Aokromes
