### ISSUE TITLE
[Feature Request] Bot developer mode

### ISSUE THREAD

**Issue by OctoNezd** [telegramdesktop/tdesktop#6944]
### Is your feature request related to a problem?
A clear and concise description of what the problem is.

Discord has "Developer mode" that allows to get user/channel/server IDs. Telegram has IDs that can be impossible to get without userbot or bot.
### Describe the solution you'd like

Some toggle in settings/command, like "devmode" for bot developer that allows to copy user/chats/message IDs, like in Discord.

### Describe alternatives you've considered

None!
### Additional context

<details>
<summary>Example of realization (Discord):</summary>

![Screenshot_20200102_165504](https://user-images.githubusercontent.com/15308404/71670336-a2495480-2d80-11ea-94df-7d8cdfcdf09b.png)

![Screenshot_20200102_165554](https://user-images.githubusercontent.com/15308404/71670418-cad14e80-2d80-11ea-9e14-3264ac484a95.png)
</details>

**Comment by Neurotoxin001** [comment]
https://github.com/telegramdesktop/tdesktop/issues/6481
