### ISSUE TITLE
[Feature Request] Exit Telegram

### ISSUE THREAD

**Issue by cakesale** [telegramdesktop/tdesktop#6948]
### Is your feature request related to a problem?
I use sway on Linux which is a wayland based tiling window manager. There doesn't seem to be a way to exit the application as the right-click menu doesn't work and closing Telegram minimises it to the tray.

### Describe the solution you'd like
An "Exit Telegram" option needs to be present in the menu.

### Describe alternatives you've considered
I am not aware of a way to fix the problem of no right-click menu in sway but there doesn't seem to be any other option in the application itself. An alternative could be when you close the application in sway/i3 (Mod+Shift+Q) you get the option of closing or minimising the application. This option could be modifiable in the settings menu.

edit: seems I can use Ctrl + Q as per "https://github.com/telegramdesktop/tdesktop/wiki/Keyboard-Shortcuts"

**Comment by john-preston** [comment]
@cakesale Ctrl+Q :) but it should be in the tray menu :(

**Comment by cakesale** [comment]
> @cakesale Ctrl+Q :) but it should be in the tray menu :(

hehe thanks just saw this now on the wiki as well...

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/4391 ?

**Comment by damnfella** [comment]
@john-preston I believe there is a _temporary fix_ for all issues with closing Telegram where neither Tray nor `CTRL + Q` can be used:

- `Shift + Close button` -- a combination of key and click

**Comment by virus-found** [comment]
Thank you for this issue. Exactly what has been bothering me for months.

**Comment by sammoth** [comment]
run telegram like:

`XDG_CURRENT_DESKTOP=XFCE telegram-desktop`

you will then have the 'show tray' option in the settings menu. Disable it and Telegram will stop running in the background when the window is closed. You can have that environment variable set to whatever you want after changing the setting, I think.

**Comment by ilya-fedin** [comment]
>  the right-click menu doesn't work

Is this still valid on 1.9.20?

**Comment by Aokromes** [comment]
no answer for more than a month, closing.
