### ISSUE TITLE
[Feature Request] Add -class option to set WM_CLASS

### ISSUE THREAD

**Issue by XamarinDeveloper** [telegramdesktop/tdesktop#6951]
### Is your feature request related to a problem?
I use multiple telegram accounts and in ubuntu gnome, they're grouped in the dock by WM_CLASS of the telegram and because of that grouping accessing them by clicking in the dock is difficult 

### Describe the solution you'd like
I would like to have -class option so I add it to my .desktop file to set the WM_CLASS at startup

**Comment by najafimh** [comment]
This is a feature wanted by every single person using TDesktop with multiple accounts in linux.

**Comment by XamarinDeveloper** [comment]
Answered in #8255
