### ISSUE TITLE
Telegram crashes other applications on paste of image data (Linux)

### ISSUE THREAD

**Issue by Akhlys** [telegramdesktop/tdesktop#6952]
I noticed this problem persisting on many updates for Telegram, but since the latest version (or update to Linux Mint 18, which I had to do to get the latest version to run) it seems to happen way more frequently.
I was unable to find a bug report on this issue, even tho it seems to be an older one.

Basically what happens is, you copy an image to clipboard, paste it to telegram and telegram keeps running as if nothing happened while the other program crashes.
I had it happen mostly with firefox before, tho very rarely, once every two weeks or so. Since TG kept running, I supposed it was a bug in firefox, even tho pasting anywhere else worked as expected.
Since system/TG update, it happened with gimp too, and very frequently there - happened on 4 consecutive tries. Two different programs having the same issues interacting with Telegram (but no other programs) seems to point at an issue with Telegram.

### Steps to reproduce
1. Open Gimp (2.8 used here)
2. Open an image and select a random portion of it, copy to clipboard
_EDIT: it seems the problem occurs way more often, though not exclusively if memory serves well, if you actually select all (ctrl-a) instead of  random portion_
_EDIT 2: Just confirmed it also happens with mere selections_
3. Change to Telegram and hit paste.
4. if problem did not occur, repeat 2, 3 with different parts of the image
Note, it often works, if TG ask you to send as image or file, the bug did not occur

### Alternative steps to reproduce
I'm not sure why, but using this method with this exact image I could reproduce it this way on nearly every try, while it needed quite a few tries of the other method.
The image is a selected part of a screenshot from youtube, that I wanted to send to a friend. It is not specifically engineered to cause this issue.
_EDIT: through more testing, it seems the cause for being able to reproduce it way more with this image was not the image itself, but that this method used select-all. I'll leave it in for now as I can't be sure if that was the only reason this method of reproduction was so successful._
1. Open Gimp (2.8 used here)
2. Open image https://i.imgur.com/1ADl4cs.png in your browser, copy paste it to gimp
2. In gimp, hit select all, and copy
3. Change to Telegram and hit paste.
4. if problem did not occur simply hit abort in the telegram dialog and hit paste again, no need to copy anew.

I found no relieable way to reproduce it in firefox (or another browser). Copying this same image in google chrome and pasting in Telegram just does nothing (no crash either), so that may be a different bug (pasting it in, say, gimp worked as expected). Copying this image in firefox and pasting it in telegram worked as expected.
But as mentioned, I had the bug with firefox only very rarely.

### Expected behaviour
TG asking you to send as image or file, like it does in case the bug doesn't occur.

### Actual behaviour
The source of the image crashes.

### Configuration
Mint 18, freshly updated from Mint 17.3.
Gimp 2.8.16

**Version of Telegram Desktop:**
Telegram Desktop v. 1.9.3

**Used theme**:
Classic

As for logs, Gimp reports this to the console at crash time:

The program 'gimp' received an X Window System error.
This probably reflects a bug in the program.
The error was 'BadWindow (invalid Window parameter)'.
  (Details: serial 194616 error_code 3 request_code 18 minor_code 0)
  (Note to programmers: normally, X errors are reported asynchronously;
   that is, you will receive the error a while after causing it.
   To debug your program, run it with the --sync command line
   option to change this behavior. You can then get a meaningful
   backtrace from your debugger if you break on the gdk_x_error() function.)

(script-fu:10291): LibGimpBase-WARNING **: script-fu: gimp_wire_read(): error

The serial number keeps changing, the error/request/minor code does not

[screen recording of the bug in action.zip](https://github.com/telegramdesktop/tdesktop/files/4017795/screen.recording.of.the.bug.in.action.zip)

**Comment by Akhlys** [comment]
Exact same problem with the same way to reproduce and the same x window error using pinta (simple image editor) version 1.6

**Comment by SantiagoValdez** [comment]
Exact same problem. Old versions worked as expected.

**Comment by lgommans** [comment]
Same here. Not an issue with TDesktop I guess, but still interesting that it only happens with TDesktop. For what it's worth, with `--verbose` there is a bit more output that seems relevant before the same crash message appears:

    [...]
    clipboard: checking pixbuf format 'png'
      - checking mime type 'image/png'
    clipboard: sending pixbuf data as 'image/png'
    The program 'gimp' received an X Window System error.
    [...]

Other flags (like `--sync --stack-trace-mode=always --no-shm`) don't seem to change anything.

**Comment by Akhlys** [comment]
I'm not sure it's a problem with gimp, pasting anywhere else save for TG does work as expected. In fact, I use imgur now as a proxy, because pasting into the browser (imgur) works and copy-pasting from the browser into TG works as well.
and it happens with pinta as well, which I first wanted to use instead of gimp

**Comment by lgommans** [comment]
@Akhlys Well, GIMP crashes. I'd say it's clear that something is going wrong on GIMP's side, though it might still be that TDesktop does some invalid request.

I guess it would be interesting to find out which TDesktop commit caused the issue to figure out what changed and whether the new code might be wrong.

**Comment by Akhlys** [comment]
would probably be hard to figure out, because while it happens way more frequently now I had the same thing happen even with older versions, just that time it wasn't gimp but firefox and it happened like once or twice a month. maybe firefox changed something that fixed it, because I didn't experience an FF crash yet with the current version

**Comment by Aokromes** [comment]
Interesting, from lgommans' post the issue is at least 8 months old, i suggest you to run gimp with gdb.

**Comment by ilya-fedin** [comment]
Might be realted: https://bugreports.qt.io/browse/QTBUG-73044

**Comment by Akhlys** [comment]
> Might be realted: https://bugreports.qt.io/browse/QTBUG-73044

I had this problem as well, so I could see it being related. Also when copying from firefox. In those cases the source program did not crash

**Comment by vsego** [comment]
A workaround that works for me: after copying the image, I click on Clipman (clipboard applet in Xfce) and click on the image I just copied. This would normally make it the current copied object, but - since it was already there - it seemingly does nothing. However, the paste to Telegram Desktop then works flawlessly.

I too sometimes copy/paste from Gimp to Imgur or to Slack in Chrome, and that works just fine.

I just tried to copy an image in SeaMonnkey (didn't want to crash Chrome) and paste it to Telegram, and SeaMonkey crashed. It's worth noting that both SeaMonkey and Gimp are GTK applications, but Clipman is too.

**Comment by ilya-fedin** [comment]
https://gitlab.gnome.org/GNOME/gimp/-/issues/789#note_763330

> At lower level the problem is that the clipboard receiver (I suspect it is a Qt issue) closes its window before all chunks have been transferred. That triggers the "BadWindow" error.

Maybe the same situation with tdesktop :thinking:

**Comment by dgmvecuador** [comment]
Hi the problem is solved for me, I have updated to Ubuntu 20.04, now its working.

**Comment by Aokromes** [comment]
so, it was 3rd party bug?

**Comment by ilya-fedin** [comment]
> so, it was 3rd party bug?

inb4: "no, it isn't solved"

**Comment by Akhlys** [comment]
well..
"no, it isn't solved" :D 
At first I was happy because I had a TG update recently and my first try didn't crash gimp. The second one did. oh well.
still happens for me, but I didn't do an OS update. 
It might very well be a third party bug, esp. if OS-update solved it for that person, but well.. TG is the only program where it happens for me, never had it anywhere else. Maybe TG is doing something esotheric that isn't exactly wrong, but still happens to crash several other applications (Gimp, Pinta, SeaMonkey..)

**Comment by ilya-fedin** [comment]
> TG is the only program where it happens for me

It happens for me with other Qt programs also. At least with Qlipper.

**Comment by Akhlys** [comment]
yeah, I don't think I have any other qt programs. Then again, it's not like they all had a "made with qt" in the title

**Comment by dgmvecuador** [comment]
> > TG is the only program where it happens for me
> 
> It happens for me with other Qt programs also. At least with Qlipper.

Before the update, Firefox and Chrome didn't crash, and they worked properly, I know that they are not using Qt

**Comment by ilya-fedin** [comment]
> I know that they are not using Qt

The issue states that Qt program crashes **other** programs

**Comment by ilya-fedin** [comment]
Just checked - I can reproduce gimp crash with dolphin as well.
1) I created 5000x5000px image in gimp
2) copied it to clipboard
3) pasted it into home directory with mimetype image/png
4) gimp crashed

**Comment by Aokromes** [comment]
sooo 3rd party bug?

**Comment by ilya-fedin** [comment]
> sooo 3rd party bug?

yep, Qt bug

**Comment by ilya-fedin** [comment]
This looks like the right Qt bug
https://bugreports.qt.io/browse/QTBUG-56595

**Comment by Akhlys** [comment]
Nice job finding it, sounds indeed like the one. But..
Priority: P2: Important
Created: 18 Oct '16 07:07 
No update since. Nice.

**Comment by ilya-fedin** [comment]
> But..

Probably, people should comment on the bug to get the devs attention :thinking:

**Comment by Akhlys** [comment]
Well, I don't really think that was my place as I haven't used QT in.. 10 years or so, but I tried anyway. But the email confirmation never came. So, if someone already has an account there, please do

**Comment by ilya-fedin** [comment]
Anyone? :thinking:

**Comment by ilya-fedin** [comment]
@Akhlys maybe you? 🧐

**Comment by Akhlys** [comment]
@ilya-fedin which one of those do I get? and it's just an executable and won't screw with my normal TG version, right?

**Comment by ilya-fedin** [comment]
> which one of those do I get?

Just `Telegram`

> Are both with the port?

Actions build two version to test the build with multiple build options, both artifacts are debug builds, they are built from the same code.

**Comment by ilya-fedin** [comment]
Thanks for the testing

**Comment by Akhlys** [comment]
Thanks for the fixing ;)
