### ISSUE TITLE
Build system: no Python module `run_cmake` found

### ISSUE THREAD

**Issue by nonlinear-chaos-order-etc-etal** [telegramdesktop/tdesktop#6954]
### Steps to reproduce
1. I merged the new Telegram commits into my fork;
2. Ran `cd ../../fork-repo/Telegram/ && ./configure.sh -D TDESKTOP_API_ID=… -D TDESKTOP_API_HASH=… -D DESKTOP_APP_USE_PACKAGED=OFF`;

### Expected behaviour
It should do configuring successfully.

### Actual behaviour
```
./configure.sh -D TDESKTOP_API_ID=… -D TDESKTOP_API_HASH=… -D DESKTOP_APP_USE_PACKAGED=OFF
Traceback (most recent call last):
  File "/home/user/git/tdesktop-fork-repo/Telegram/configure.py", line 13, in <module>
    import run_cmake
ImportError: No module named run_cmake
```

### Configuration

**Operating system:** 

Ubuntu 14.04.6 LTS

**Version of Telegram Desktop:**

TDesktop latest commit:

Commit hash: 1f71630f51ea968cee59b4dd8aaf44a0b41512a2
Commit date:   Thu Jan 2 15:24:36 2020 +0300
Commit comment: Improve spell check underline color.

**Comment by 23rd** [comment]
```git submodule init
git submodule update```?

**Comment by nonlinear-chaos-order-etc-etal** [comment]
@23rd ty. I should have looked at `configure.py` before filing an issue…

**Comment by john-preston** [comment]
@nonlinear-chaos-order-etc-etal Please run "git submodule init", "git submodule sync" and "git submodule update", or cleanly "git clone --recursive" the whole repository.
