### ISSUE TITLE
With Korean Typing, using ctrl+enter to send, final character is duplicated

### ISSUE THREAD

**Issue by i5on9i** [telegramdesktop/tdesktop#6955]
### Steps to reproduce
1. Settings -> Chat Settings -> 'Send By Ctrl+Enter'
2. after typing korean, during the cursor block is at the last character
3. press ctrl+enter

### Expected behaviour
If you type '안녕' and press 'ctrl+enter' to send, telegram should send '안녕'

### Actual behaviour
but when I press 'ctrl + enter' with the cursor block wrapping the last character, 
telegram sends '안녕녕' instead of '안녕'

### Configuration
**Operating system:**
Windows 10

**Version of Telegram Desktop:**
1.9.3

**Used theme**:
in dark mode

<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by ilya-fedin** [comment]
Qt bug https://bugreports.qt.io/browse/QTBUG-76059 (seems to be unrelated to webengine since tdesktop affected as well)

**Comment by ilya-fedin** [comment]
Should be due to that Qt change, but I have no idea how to fix that without restoring the bug that fixed by that Qt change
https://github.com/qt/qtbase/commit/994e0e4c36315fc7656568f9f1e546362dae5466
