### ISSUE TITLE
Can't switch videos uploaded by me

### ISSUE THREAD

**Issue by Neurotoxin001** [telegramdesktop/tdesktop#6957]
### Steps to reproduce
1. upload any video to any channel or chat
2. open it in full screen
3. try to switch it to previous video with mouse scroll or arrows on keyboard
4. you can't. telegram restart is helps

This issue only with videos, but there is similar bug with GIFs:
1. send any 2 gifs to any chat
2. open one in full screen and try to switch — you can't
3. but if you right click on gif and press "open GIF" — you can switch it. but only with autoplay disabled. with autoplay enabled there is no "open GIF" in context menu

And before this https://github.com/telegramdesktop/tdesktop/issues/6943 is getting fixed — this issue not only with autoplay enabled but with disabled too.

### Configuration
**Operating system:** win 10 ltsc 1809

**Version of Telegram Desktop:** 1.9.3

**Used theme**: dark default

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/releases/tag/v1.9.6
