### ISSUE TITLE
[Feature Request] Move archive tab to the bottom of the conversation list

### ISSUE THREAD

**Issue by morags** [telegramdesktop/tdesktop#6958]
### Is your feature request related to a problem?
The archive tab is placed at the top of the conversation list draws too much attention.

### Describe the solution you'd like
Move archive tab to the bottom of the pane.

### Additional context
Placing the archive tab at the bottom of the pane will not only draw less attention to a tab that is likely less "urgent" than ongoing conversations, but conform with the ordering of the list - descending by date.

**Comment by Aokromes** [comment]
you can use https://i.imgur.com/00bnxsY.png

**Comment by Neurotoxin001** [comment]
What if user have 50+ chats? He must always scrolling to the bottom? Just click on "Move to main menu" on archive chats menu.
