### ISSUE TITLE
Show group admin

### ISSUE THREAD

**Issue by Aokromes** [telegramdesktop/tdesktop#696]
Hi, how about add a text of who is the group admin?
I noticed this feature on whatsapp and i think it's a good idea :)

**Comment by HostFat** [comment]
I agree :)

**Comment by auchri** [comment]
No api for that

**Comment by Aokromes** [comment]
Where i can feature request this?

**Comment by telegramdesktop** [comment]
Group admin is returned from server, so it could be done. But none of client apps do.

**Comment by auchri** [comment]
@telegramdesktop let Telegram Desktop be the first one! :smile:

**Comment by Aokromes** [comment]
Implemented somewhere between 0.9.28 and 0.9.32
