### ISSUE TITLE
ERROR: opus not found using pkg-config [Question] 

### ISSUE THREAD

**Issue by archive-me** [telegramdesktop/tdesktop#6960]
when i clone ffmpeg and configure it, i get below error:
<img width="831" alt="Screen Shot 1398-10-13 at 23 39 03" src="https://user-images.githubusercontent.com/42973767/71746682-c7be8700-2e82-11ea-9756-51109d059bb4.png">
![Screen Shot 1398-10-13 at 23 38 28](https://user-images.githubusercontent.com/42973767/71746684-cab97780-2e82-11ea-839e-3e7b067d49aa.png)
why not found config ffmpeg???

**Comment by ilya-fedin** [comment]
Because you have skipped the opus step?

**Comment by Aokromes** [comment]
no answer for a lot of time, closing.
