### ISSUE TITLE
The audio message does not have the status "Forwarded"

### ISSUE THREAD

**Issue by viktor02** [telegramdesktop/tdesktop#6961]
### Steps to reproduce
1. Send an audio in private messages
2. Forward to someone

### Expected behaviour
A message should appear stating that this is a forwarded message

### Actual behaviour
There is no message that it was forwarded

### Configuration
**Operating system:**
Windows 7
**Version of Telegram Desktop:**
1.9.3
**Used theme**:
Night or Default

Both messages in the screenshot were forwarded.
![forward](https://user-images.githubusercontent.com/19672960/71747594-21be4d00-2e81-11ea-9931-ed9afab8e557.PNG)

**Comment by Aokromes** [comment]
cannot reproduce on windows 10 and telegram desktop 1.9.14
https://i.imgur.com/ebh4zwA.png

**Comment by viktor02** [comment]
This is a voice message, everything is fine with him, but if you send mp3 file and forward it later, there will be no status. Win7, telegram desktop 1.9.14
![bugreport](https://user-images.githubusercontent.com/19672960/75051602-3ca35a00-54df-11ea-90f8-25f7131dcbd4.PNG)

**Comment by Aokromes** [comment]
btw, i see on android is the same, very likely this is api bug.

**Comment by reallyuniquename** [comment]
Still bugged.

**Comment by reallyuniquename** [comment]
Valid issue.

**Comment by Aokromes** [comment]
such feature belongs to https://bugs.telegram.org/
