### ISSUE TITLE
[Bug] Artifact of typing cursor after emoji

### ISSUE THREAD

**Issue by maxoku** [telegramdesktop/tdesktop#6962]
### Steps to reproduce
1. Type a word and space after it (not always necessary)
2. Click on emoji on the picker (not from suggestions or autocomplete) to add it to the message
3. Look at typing blinking cursor after the emoji

### Expected behaviour
The typing cursor should blink normally.

### Actual behaviour
The typing cursor leaves a small part of it on top when vanishes. Very annoying.
![blink](https://user-images.githubusercontent.com/17256400/71748883-2fb9a100-2e74-11ea-8055-2b2836697f33.jpg)

### Configuration
Operating system: Windows 8.1
Version of Telegram Desktop: 1.9.3
Used theme: Day

**Comment by Griboedoff** [comment]
same on
Operating system: Windows 10
Version of Telegram Desktop: 1.9.9
Used theme: Night

**Comment by maxoku** [comment]
Also happens after typing simple emoji codes like `:-) ;-) :-( :-D` etc.

**Comment by a14219** [comment]
Ubuntu 20.04.
Telegram Desktop v 2.1.

Same thing happens.

**Comment by maxoku** [comment]
Is it fixed?

**Comment by ilya-fedin** [comment]
> Is it fixed?

You are the reporter, this is a question for you

**Comment by maxoku** [comment]
But I'm not the only one with the problem. I didn't noticed it lately, but I haven't typed much emojis in last few weeks though.

**Comment by ilya-fedin** [comment]
> But I'm not the only one with the problem

You could be the only who alive in this issue

**Comment by maxoku** [comment]
So that's why I asked, if there are others then they'll answer.

**Comment by ilya-fedin** [comment]
@Aokromes can you add "waiting for answer" label?

**Comment by Griboedoff** [comment]
looks good for me

**Comment by Aokromes** [comment]
@maxoku can you write:
gfx card.
gfx card drivers.

the son of a friend had artifacts on one game and i fixed them updating video card drivers.

**Comment by maxoku** [comment]
@Aokromes ??? I doubt it's from graphic card or drivers. Nevertheless it seems to be good now, can't reproduce it anymore. Let's wait for the last participant and then I'll close it.

**Comment by Aokromes** [comment]
> @Aokromes ??? I doubt it's from graphic card or drivers. Nevertheless it seems to be good now, can't reproduce it anymore. Let's wait for the last participant and then I'll close it.

well, there is another bug affecting ONLY amd gfx card users.

**Comment by maxoku** [comment]
Then good thing I have nvidia :stuck_out_tongue:

**Comment by ilya-fedin** [comment]
No, as I can see, this was a bug from Qt and fixed by patching Qt
https://github.com/desktop-app/patches/commit/d8a949029e45f38bdf25ec655ad3938461b6bc86#diff-3384d27b8a68ca1c5812cc3c9602396b173d64d087de0b53359f988f1a6d2b15
