### ISSUE TITLE
snap package telegram-desktop reports outdated version.

### ISSUE THREAD

**Issue by R32fanboy** [telegramdesktop/tdesktop#6963]
### Steps to reproduce
1.  Install snapd on Raspbian Buster.
2.  Install telegram-desktop from snap on both stable and edge channels. 
3.  Check version number.

### Expected behaviour
Snap package telegram-desktop reports current version 1.8.15 and supports all recently-added features.

### Actual behaviour
Snap package telegram-desktop reports current version 1.3.10, a release from July 2018 that does not support any recently-added features or bugfixes. 

### Configuration
**Operating system:**
Raspbian Buster on any Raspberry pi including the latest Raspberry Pi 4b. 

**Version of Telegram Desktop:**
1.3.10, which is the issue.

**Comment by adasiko** [comment]
https://github.com/telegramdesktop/tdesktop/issues/6222
