### ISSUE TITLE
[Question] jom -j4 return "Error: File Makefile doesn't exist."

### ISSUE THREAD

**Issue by cookiesicharp** [telegramdesktop/tdesktop#6964]
I'm following the build instructions for VS 2019 a [this part](https://github.com/telegramdesktop/tdesktop/blob/dev/docs/building-msvc.md#clone-source-code-and-prepare-libraries) and these commands return "Error: File Makefile doesn't exist."

> jom -j4
jom -j4 install

I'm in this folder: `\Libraries\qt_5_12_5`

**Comment by Aokromes** [comment]
try again on updated source.

**Comment by mugavri** [comment]
same for me im on last commit 7bc86cc9af28ba3d04a5cb69f6f7c16bfe7f8719
