### ISSUE TITLE
Alphabetical order in contacts doesn't "ignore" accented initials

### ISSUE THREAD

**Issue by ThigSchuch** [telegramdesktop/tdesktop#6965]
### Steps to reproduce
0. You need a contact with accented initial
1. Open "contacts" from the menu
2. Find your contact with accented initial

### Expected behaviour
The name starts with A, but it is in the end of list

### Actual behaviour
![image](https://user-images.githubusercontent.com/20743110/71770720-bb800b80-2f0e-11ea-8845-ece4da7fdc3d.png)

### Configuration
**Operating system:** Windows 10

**Version of Telegram Desktop:** 1.9.3

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/2436
