### ISSUE TITLE
[Feature Request] Consider changing "Answer call" button colour

### ISSUE THREAD

**Issue by pcdevil** [telegramdesktop/tdesktop#6967]
### Is your feature request related to a problem?
Kind of? When getting a call on Telegram Desktop there are 2 actions, answer and reject call.

<details><summary>Screenshot</summary>

![Telegram Desktop Call Screen](https://gist.githubusercontent.com/pcdevil/375e68771ef08d69225e44dbb1f3e477/raw/telegram-desktop_call-screen.png)
</details>

Unfortunately both buttons are red, which makes me consider twice which I need press every time I see the screen.

### Describe the solution you'd like
For better UX and accessibility I'd request a colour-change on the answer call button to be green.

### Describe alternatives you've considered
N/A.

### Additional context
On Android this screen has better experience, with the same green button as proposed.

<details><summary>Screenshot</summary>

![Telegram Android Call Screen](https://gist.githubusercontent.com/pcdevil/375e68771ef08d69225e44dbb1f3e477/raw/telegram-android_call-screen.png)
</details>

**Comment by Tynach** [comment]
It might be best to make it blue, not green - I'm sure color blind users would appreciate having two colors they can all actually distinguish.

I'm not colorblind myself, mind you - I just know a few people who are, and have written some color blindness simulation code.

**Comment by pcdevil** [comment]
Very good point! It would be worth checking to change it a more _contrasty_ colour on other devices too!

**Comment by pcdevil** [comment]
Additional note: The colour of the answer button is depending on the theme:
- if the theme is dark, the button inherits the accent colour
- if the theme is light, the button uses the default green colour

I tried but didn't find the code where the colour is decided, but since it's already respected in some situations I suspect it wouldn't be a big change to make it.
