### ISSUE TITLE
Long audio track not resumed after telegram restart

### ISSUE THREAD

**Issue by HawkEye4** [telegramdesktop/tdesktop#6968]
### Steps to reproduce
1. Open a long track
2. Pause track
3. Close Telegram
4. Reopen Telegram and start from 0

### Expected behaviour
The track should start where I left it

### Actual behaviour
The track start from the beginning

### Configuration
**Operating system:** Windows 10, Ubuntu 19.10

**Version of Telegram Desktop:** 1.9.3

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/6374
