### ISSUE TITLE
Can't play GIF in full screen when GIF autoplay is turned off

### ISSUE THREAD

**Issue by f242** [telegramdesktop/tdesktop#6970]
### Steps to reproduce
1. turn off GIF autoplay
2. click to play on GIF in chat
3. it plays in chat and no way to play in full screen

**Comment by john-preston** [comment]
@f242 You should be able to right click it and choose Open GIF.

**Comment by f242** [comment]
@f242 i think it's not intuitive, usually in same case i see icon like this 
![image](https://user-images.githubusercontent.com/10371194/71827243-dee2bc00-30b0-11ea-8032-f36323f5e23b.png)
