### ISSUE TITLE
[Feature Request] Photos Have Black Bars If Odd Dimensions

### ISSUE THREAD

**Issue by seniorm0ment** [telegramdesktop/tdesktop#6971]
### Request / Issue
Photos that do not fit properly within a message box, get black barred unless clicked on.

### Solution
Have images not required to be within the dimensions of the message box I guess? Not entirely sure there may be another better way.

### Extra
Screenshot Example: https://b.catgirlsare.sexy/93sq.png
(The white is the photo, I just censored the photo)

**Comment by 23rd** [comment]
I guess this is not a feature request.

**Comment by Z3ROGRAV1TYx** [comment]
> 
> 
> I guess this is not a feature request.

Is it a bug? Seems like it wasn't intentional nor disintentional.. so seems like best put under feature request.

**Comment by grravity** [comment]
Reopen
