### ISSUE TITLE
1.9.3 chat keeps scrolling when AFK

### ISSUE THREAD

**Issue by imashxtyz** [telegramdesktop/tdesktop#6972]
### Steps to reproduce
1. Keep group chat open
2. Wait for new messages

### Expected behaviour
Chat should stop scrolling at last read message

### Actual behaviour
Chat keeps scrolling while you are away

You can't keep the chat open if you don't want to scroll up when you're back, very annoying.

But when you have "Settings" opened with active chat in background this works as expected for some reason.

### Configuration
**Operating system:**
Windows 7 x64
**Version of Telegram Desktop:**
1.9.3
**Used theme**:
Classic

**Comment by RememberTheAir** [comment]
If your focus is on an opened chat and you're at the bottom of it, tdesktop will automatically stay at the bottom of the chat - it's a feature. You can move back a bit in the chat history if you don't want the chat to automatically scroll as new messages arrive, but new messages will be marked as read anyway as soon as you give focus to the chat (see another issue which I cannot find right now)

**Comment by imashxtyz** [comment]
Nope, in earlier versions if your chat was in focus and you did nothing (i.e. not moving mouse) it would stop scrolling. Clearly it's broken.

**Comment by Neurotoxin001** [comment]
There is similar bug:
When you click on chat with unread messages and start scrolling to read them — if someone will post something, chat will scroll to bottom to that new message. This happens not all time but sometimes.
