### ISSUE TITLE
Confirmation when sending something into a Channel or forwarding messages

### ISSUE THREAD

**Issue by BartMitTyp** [telegramdesktop/tdesktop#6976]
I would like to be required to confirm sending a message into a channel
Also I would like to be asked to confirm, when forwarding any kind of data into groups or channels
Maybe make it another option in the chat settings

I had the problem twice now, that I forwarded messages or pictures into groups, which I didn't want to send there and don't want that to happen in the channel (once was because I was dumb, once because it was raining and my screen spazzed around)

**Comment by reallyuniquename** [comment]
This is issue tracker for Telegram Desktop and it does require additional confirmation before actually sending a forward into channel or group.

**Comment by BartMitTyp** [comment]
> 
> 
> This is issue tracker for Telegram Desktop and it does require additional confirmation before actually sending a forward into channel or group.

Oh I see, thank you.
