### ISSUE TITLE
[Feature Request] Use system dark/ligth theme mode

### ISSUE THREAD

**Issue by ai** [telegramdesktop/tdesktop#6977]
### Is your feature request related to a problem?

All modern OS has a built-in dark mode. It will be nice if the Telegram client will use it and switch to dark mode when OS switching to dark mode.

It is especially important because macOS and Linux can switch themes automatically based on time.

### Describe the solution you'd like

1. Telegram subscribe to OS theme changes.
2. If the theme was changed, Telegram changes it too.
3. Switcher allows changing app themes separately until OS will change the theme again.
4. Telegram saves the last OS theme before closing. During the startup, it compares previous and current OS themes to detect theme changes.

The current best practice to detect a dark theme in Linux is to check `dark` ending in the theme name.

### Describe alternatives you've considered

We can have a 3-mode switcher (light—auto—dark). The most flexible, but require UI changes.

### Additional context

All browsers respects OS dark/light theme changes. It is expected behavior from users right now.

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/6359
