### ISSUE TITLE
Deep linking is broken

### ISSUE THREAD

**Issue by levz0r** [telegramdesktop/tdesktop#6978]
### Steps to reproduce
1. Click here: https://t.me/(your-bot)?start=hello

### Expected behaviour
1. START button appears,
2. After START button is clicked, '/start hello' message is being sent to the bot.

### Actual behaviour
'/start' message is being sent without the PAYLOAD.

### Configuration
**Operating system:** Windows 10

**Version of Telegram Desktop:** 1.9.3

**Used theme**: Default (dark)

**Comment by jeffythedragonslayer** [comment]
That link just redirects me to https://telegram.org/ (on Manjaro Linux)

**Comment by Aokromes** [comment]
> That link just redirects me to [telegram.org](https://telegram.org/) (on Manjaro Linux)

you must fill a random bot name xd

**Comment by jeffythedragonslayer** [comment]
I tried it with 'gamee' bot and after launching saw a "/start" message sent by me without the "hello"
