### ISSUE TITLE
Saved GIFs downloads are bound to autodownload settings in èprivate chats

### ISSUE THREAD

**Issue by RememberTheAir** [telegramdesktop/tdesktop#6981]
### Steps to reproduce
1. disable private chats' documents autodownload setting (settings > advanced > private chats > files)
2. open saved GIFs panel

### Expected behavior
GIFs are downloaded and I don't have to click on each one of them

### Actual behavior
They are not downloaded. I don't know whether this is intended or not, but shouldn't there be a separate setting? It's not really straightforward to bind this behavior to _that_ setting. It's confusing twice because it is under private chats and it's the files autodownload setting

### Configuration
**Operating system:** Windows 10

**Version of Telegram Desktop:** 1.9.3

**Comment by john-preston** [comment]
@RememberTheAir It should accept any files autodownload. But perhaps they should be enabled always, otherwise there is no point in opening this section.

**Comment by RememberTheAir** [comment]
@john-preston I assumed that your comment implied it was in fact a bug and not the intended behavior. Was I wrong?
