### ISSUE TITLE
App freeze without crash report

### ISSUE THREAD

**Issue by Neurotoxin001** [telegramdesktop/tdesktop#6986]
### Steps to reproduce
It's random, I can't reproduce it, but it's happens sometimes when I download or upload video. Window is just freeze and app start eating 25% CPU. There is no crash report window after restart and no errors in logs.

![image](https://user-images.githubusercontent.com/39812401/72133330-35424a00-3392-11ea-956f-27bc21964386.png)

### Configuration
**Operating system:** win 10 ltsc

**Version of Telegram Desktop:** 1.9.3 but I noticed this issue before on old versions too

**Used theme**: dark default

**Comment by Neurotoxin001** [comment]
Where can I send you debug logs? They have private data? Can I upload them here?

Enabled them yesterday and start waiting this bug. Got it just now.

**Comment by Aokromes** [comment]
you can send @preston on telegram

**Comment by Neurotoxin001** [comment]
Seems like this https://github.com/telegramdesktop/tdesktop/commit/d24735b2173f4757cedd7bb54036f465d8c5d9ed is not fix for my issue? Just got crash right now, when uploading video to schedule.

**Comment by Aokromes** [comment]
try to go settings and enable beta to see if you get crash report.

**Comment by Neurotoxin001** [comment]
I already have this checkbox enabled.

**Comment by Neurotoxin001** [comment]
Didn't notice that on 1.9.7 and 1.9.8, if tomorrow all will be fine this issue can be closed.

**Comment by Neurotoxin001** [comment]
Seems like fixed

**Comment by Neurotoxin001** [comment]
Not fixed lol. Just got a freeze right now. And again without crash report.

1.9.10

**Comment by Neurotoxin001** [comment]
1.9.12 got freeze when uploading video, no crash report window.

**Comment by Neurotoxin001** [comment]
1.9.13 same.

**Comment by Neurotoxin001** [comment]
Just got it on 1.9.14 right now, still no crash report window and errors in log.

**Comment by Aokromes** [comment]
if you get 100% repo freeze, you may want to start task manager before it freezes, and when it freezes right click over telegram desktop -> create dump and send that to preston if it's proper.

**Comment by Neurotoxin001** [comment]
Ok, will do it when next crash appear.

**Comment by Aokromes** [comment]
i suppose xd it's up to @john-preston  to tell if it's valid or no

**Comment by Neurotoxin001** [comment]
Got it now after downloading video. Telegram.DMP = 873MB...

**Comment by Neurotoxin001** [comment]
I wonder if this memory dump contains any private/personal information of my account?
