### ISSUE TITLE
[Regression] Since 1.9, cannot open the context menu while recording (to record hands-free)

### ISSUE THREAD

**Issue by S-U-M-1** [telegramdesktop/tdesktop#6987]
### Steps to reproduce
1. Enter a chat.
2. Hold the left mouse button on the mic record button to start a recording.
3. While still holding it, move the mouse into the chat window and right-click to open the context menu.

### Expected behaviour
As in 1.8.15 and before, the context menu should open, and you should be able to left click off it, which leaves the voice recorder running and allows you to record hands-free.
![image](https://user-images.githubusercontent.com/29358863/72199215-0a5b0300-3431-11ea-94e7-428ce93a249c.png)

### Actual behaviour
Since 1.9, the recording stops, and the context menu doesn't open. I relied on this functionality to record long audios handsfree.

### Configuration
**Operating system:**
Windows 7 64-bit
**Version of Telegram Desktop:**
Tested on 1.9 and 1.9.3 then subsequently downgraded to 1.8.15
**Used theme**:
None
<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by john-preston** [comment]
This was not an intended feature, sorry. Handsfree should be done properly, this broke when Qt started treating events somehow differently.

**Comment by S-U-M-1** [comment]
> This was not an intended feature, sorry. Handsfree should be done properly, this broke when Qt started treating events somehow differently.

I knew it wasn't an intended feature. I still used it and relied on it. Thus, I will not be upgrading for a while.

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/3208
