### ISSUE TITLE
[Question] can't add admin?

### ISSUE THREAD

**Issue by gorut** [telegramdesktop/tdesktop#6988]
When I add a new admin, the message is as below. the solution?

`sorry, you were restricted by chat admin from performing this action `

**Comment by Aokromes** [comment]
it looks you are admin without add new admin permissions, not owner.

**Comment by gorut** [comment]
how can that be? even though I own the creator

**Comment by gorut** [comment]
sollutions please?

**Comment by ilya-fedin** [comment]
> sollutions please?

too little info

**Comment by Aokromes** [comment]
i suggest you to use in-app ask a question, or try with android version, if the issue is the same it's not from telegram desktop.
