### ISSUE TITLE
Message editing

### ISSUE THREAD

**Issue by ProWebCraft** [telegramdesktop/tdesktop#699]
Hey guys, I'd love to see message editing feature, like in Skype. It's very handy and most wanted feature for me and my friends!

**Comment by rutja76** [comment]
+1

**Comment by ATI3D** [comment]
+1

**Comment by brainoss** [comment]
+1

**Comment by ezdev128** [comment]
This is definitely must be!

**Comment by kosten** [comment]
+1

**Comment by ppparadox** [comment]
I don't think the API allows this.

**Comment by ezdev128** [comment]
@ppparadox then need to extend API. This feature is very usable.

**Comment by neodc** [comment]
+1

**Comment by ppparadox** [comment]
API extension is a very big deal.

**Comment by ezdev128** [comment]
@ppparadox imho, this is likely core functionality than optional, it must be implemented. About API extension - well, the life is a big deal too ;-)

**Comment by mirrr** [comment]
+1

**Comment by stufkan** [comment]
I find it very difficult to see a scenario where the advantage of this feature is greater than the disadvantage.

**Advantages:** (as I see it, feel free to add)
*Correct spelling mistakes, wording, etc. 
*Expand on something, ideas, a list, etc

**Disadvantages: **
*You can take back statements without it being visible in the flow of the chat (depending on the implementation of course)
*Delete statements
*Change the course of a conversation

I understand that editing a piece of text by sending another message does not look very pretty, but the negative uses of a feature like this are, in my opinion, far too great for a secure texting platform as Telegram

**Comment by Katzen-Gott** [comment]
@stufkan I think that there is no such option in telegram API, then this is wrong place to ask for this feature.
