### ISSUE TITLE
[Feature Request] Ability to label secret chats

### ISSUE THREAD

**Issue by IceCreamCone** [telegramdesktop/tdesktop#6992]
### Is your feature request related to a problem?
Right now, if a user has more than one secret chat with another user on different devices, it is quite frustrating trying to keep track of which chat goes to which device.

### Describe the solution you'd like
Being able to custom-label your secret chats would eliminate this problem. Extending this feature to all chats might also be something of use to some users.

### Describe alternatives you've considered
Alternatively, a feature could be implemented, which detects what hardware/device/OS your chat-partner is on and displays this information as an icon next to the chat title/contact name.

### Additional context
I will gladly attach screenshots should further clarification be required.

**Comment by 23rd** [comment]
Telegram Desktop does not support secret chats.

**Comment by IceCreamCone** [comment]
I do not understand; How come I have multiple secret chats in Telegram Desktop as of right now, then? Could you please elaborate?

**Comment by 23rd** [comment]
https://github.com/telegramdesktop/tdesktop/issues/5921#issuecomment-483126605

**Comment by IceCreamCone** [comment]
Thank you for the clarification!
