### ISSUE TITLE
New Unicode 12 Emojis support

### ISSUE THREAD

**Issue by rafitamolin** [telegramdesktop/tdesktop#6996]
### Steps to reproduce
1. Send these new emoji:

> 🥱 Yawning Face
> 🤎 Brown Heart
> 🤍 White Heart
> 🤏 Pinching Hand
> 🤏🏻 Pinching Hand: Light Skin Tone
> 🤏🏼 Pinching Hand: Medium-Light Skin Tone
> 🤏🏽 Pinching Hand: Medium Skin Tone
> 🤏🏾 Pinching Hand: Medium-Dark Skin Tone
> 🤏🏿 Pinching Hand: Dark Skin Tone
> 🦾 Mechanical Arm
> 🦿 Mechanical Leg
> 🦻 Ear With Hearing Aid
> 🦻🏻 Ear With Hearing Aid: Light Skin Tone
> 🦻🏼 Ear With Hearing Aid: Medium-Light Skin Tone
> 🦻🏽 Ear With Hearing Aid: Medium Skin Tone
> 🦻🏾 Ear With Hearing Aid: Medium-Dark Skin Tone
> 🦻🏿 Ear With Hearing Aid: Dark Skin Tone
> 🧏 Deaf Person
> 🧏🏻 Deaf Person: Light Skin Tone
> 🧏🏼 Deaf Person: Medium-Light Skin Tone
> 🧏🏽 Deaf Person: Medium Skin Tone
> 🧏🏾 Deaf Person: Medium-Dark Skin Tone
> 🧏🏿 Deaf Person: Dark Skin Tone
> 🧏‍♂️ Deaf Man
> 🧏🏻‍♂️ Deaf Man: Light Skin Tone
> 🧏🏼‍♂️ Deaf Man: Medium-Light Skin Tone
> 🧏🏽‍♂️ Deaf Man: Medium Skin Tone
> 🧏🏾‍♂️ Deaf Man: Medium-Dark Skin Tone
> 🧏🏿‍♂️ Deaf Man: Dark Skin Tone
> 🧏‍♀️ Deaf Woman
> 🧏🏻‍♀️ Deaf Woman: Light Skin Tone
> 🧏🏼‍♀️ Deaf Woman: Medium-Light Skin Tone
> 🧏🏽‍♀️ Deaf Woman: Medium Skin Tone
> 🧏🏾‍♀️ Deaf Woman: Medium-Dark Skin Tone
> 🧏🏿‍♀️ Deaf Woman: Dark Skin Tone
> 🧍 Person Standing
> 🧍🏻 Person Standing: Light Skin Tone
> 🧍🏼 Person Standing: Medium-Light Skin Tone
> 🧍🏽 Person Standing: Medium Skin Tone
> 🧍🏾 Person Standing: Medium-Dark Skin Tone
> 🧍🏿 Person Standing: Dark Skin Tone
> 🧍‍♂️ Man Standing
> 🧍🏻‍♂️ Man Standing: Light Skin Tone
> 🧍🏼‍♂️ Man Standing: Medium-Light Skin Tone
> 🧍🏽‍♂️ Man Standing: Medium Skin Tone
> 🧍🏾‍♂️ Man Standing: Medium-Dark Skin Tone
> 🧍🏿‍♂️ Man Standing: Dark Skin Tone
> 🧍‍♀️ Woman Standing
> 🧍🏻‍♀️ Woman Standing: Light Skin Tone
> 🧍🏼‍♀️ Woman Standing: Medium-Light Skin Tone
> 🧍🏽‍♀️ Woman Standing: Medium Skin Tone
> 🧍🏾‍♀️ Woman Standing: Medium-Dark Skin Tone
> 🧍🏿‍♀️ Woman Standing: Dark Skin Tone
> 🧎 Person Kneeling
> 🧎🏻 Person Kneeling: Light Skin Tone
> 🧎🏼 Person Kneeling: Medium-Light Skin Tone
> 🧎🏽 Person Kneeling: Medium Skin Tone
> 🧎🏾 Person Kneeling: Medium-Dark Skin Tone
> 🧎🏿 Person Kneeling: Dark Skin Tone
> 🧎‍♂️ Man Kneeling
> 🧎🏻‍♂️ Man Kneeling: Light Skin Tone
> 🧎🏼‍♂️ Man Kneeling: Medium-Light Skin Tone
> 🧎🏽‍♂️ Man Kneeling: Medium Skin Tone
> 🧎🏾‍♂️ Man Kneeling: Medium-Dark Skin Tone
> 🧎🏿‍♂️ Man Kneeling: Dark Skin Tone
> 🧎‍♀️ Woman Kneeling
> 🧎🏻‍♀️ Woman Kneeling: Light Skin Tone
> 🧎🏼‍♀️ Woman Kneeling: Medium-Light Skin Tone
> 🧎🏽‍♀️ Woman Kneeling: Medium Skin Tone
> 🧎🏾‍♀️ Woman Kneeling: Medium-Dark Skin Tone
> 🧎🏿‍♀️ Woman Kneeling: Dark Skin Tone
> 👨‍🦯 Man With Probing Cane
> 👨🏻‍🦯 Man With Probing Cane: Light Skin Tone
> 👨🏼‍🦯 Man With Probing Cane: Medium-Light Skin Tone
> 👨🏽‍🦯 Man With Probing Cane: Medium Skin Tone
> 👨🏾‍🦯 Man With Probing Cane: Medium-Dark Skin Tone
> 👨🏿‍🦯 Man With Probing Cane: Dark Skin Tone
> 👩‍🦯 Woman With Probing Cane
> 👩🏻‍🦯 Woman With Probing Cane: Light Skin Tone
> 👩🏼‍🦯 Woman With Probing Cane: Medium-Light Skin Tone
> 👩🏽‍🦯 Woman With Probing Cane: Medium Skin Tone
> 👩🏾‍🦯 Woman With Probing Cane: Medium-Dark Skin Tone
> 👩🏿‍🦯 Woman With Probing Cane: Dark Skin Tone
> 👨‍🦼 Man in Motorized Wheelchair
> 👨🏻‍🦼 Man in Motorized Wheelchair: Light Skin Tone
> 👨🏼‍🦼 Man in Motorized Wheelchair: Medium-Light Skin Tone
> 👨🏽‍🦼 Man in Motorized Wheelchair: Medium Skin Tone
> 👨🏾‍🦼 Man in Motorized Wheelchair: Medium-Dark Skin Tone
> 👨🏿‍🦼 Man in Motorized Wheelchair: Dark Skin Tone
> 👩‍🦼 Woman in Motorized Wheelchair
> 👩🏻‍🦼 Woman in Motorized Wheelchair: Light Skin Tone
> 👩🏼‍🦼 Woman in Motorized Wheelchair: Medium-Light Skin Tone
> 👩🏽‍🦼 Woman in Motorized Wheelchair: Medium Skin Tone
> 👩🏾‍🦼 Woman in Motorized Wheelchair: Medium-Dark Skin Tone
> 👩🏿‍🦼 Woman in Motorized Wheelchair: Dark Skin Tone
> 👨‍🦽 Man in Manual Wheelchair
> 👨🏻‍🦽 Man in Manual Wheelchair: Light Skin Tone
> 👨🏼‍🦽 Man in Manual Wheelchair: Medium-Light Skin Tone
> 👨🏽‍🦽 Man in Manual Wheelchair: Medium Skin Tone
> 👨🏾‍🦽 Man in Manual Wheelchair: Medium-Dark Skin Tone
> 👨🏿‍🦽 Man in Manual Wheelchair: Dark Skin Tone
> 👩‍🦽 Woman in Manual Wheelchair
> 👩🏻‍🦽 Woman in Manual Wheelchair: Light Skin Tone
> 👩🏼‍🦽 Woman in Manual Wheelchair: Medium-Light Skin Tone
> 👩🏽‍🦽 Woman in Manual Wheelchair: Medium Skin Tone
> 👩🏾‍🦽 Woman in Manual Wheelchair: Medium-Dark Skin Tone
> 👩🏿‍🦽 Woman in Manual Wheelchair: Dark Skin Tone
> 🧑‍🤝‍🧑 People Holding Hands
> 🧑🏻‍🤝‍🧑🏻 People Holding Hands: Light Skin Tone
> 🧑🏼‍🤝‍🧑🏻 People Holding Hands: Medium-Light Skin Tone, Light Skin Tone
> 🧑🏼‍🤝‍🧑🏼 People Holding Hands: Medium-Light Skin Tone
> 🧑🏽‍🤝‍🧑🏻 People Holding Hands: Medium Skin Tone, Light Skin Tone
> 🧑🏽‍🤝‍🧑🏼 People Holding Hands: Medium Skin Tone, Medium-Light Skin Tone
> 🧑🏽‍🤝‍🧑🏽 People Holding Hands: Medium Skin Tone
> 🧑🏾‍🤝‍🧑🏻 People Holding Hands: Medium-Dark Skin Tone, Light Skin Tone
> 🧑🏾‍🤝‍🧑🏼 People Holding Hands: Medium-Dark Skin Tone, Medium-Light Skin Tone
> 🧑🏾‍🤝‍🧑🏽 People Holding Hands: Medium-Dark Skin Tone, Medium Skin Tone
> 🧑🏾‍🤝‍🧑🏾 People Holding Hands: Medium-Dark Skin Tone
> 🧑🏿‍🤝‍🧑🏻 People Holding Hands: Dark Skin Tone, Light Skin Tone
> 🧑🏿‍🤝‍🧑🏼 People Holding Hands: Dark Skin Tone, Medium-Light Skin Tone
> 🧑🏿‍🤝‍🧑🏽 People Holding Hands: Dark Skin Tone, Medium Skin Tone
> 🧑🏿‍🤝‍🧑🏾 People Holding Hands: Dark Skin Tone, Medium-Dark Skin Tone
> 🧑🏿‍🤝‍🧑🏿 People Holding Hands: Dark Skin Tone
> 👭🏻 Women Holding Hands: Light Skin Tone
> 👩🏼‍🤝‍👩🏻 Women Holding Hands: Medium-Light Skin Tone, Light Skin Tone
> 👭🏼 Women Holding Hands: Medium-Light Skin Tone
> 👩🏽‍🤝‍👩🏻 Women Holding Hands: Medium Skin Tone, Light Skin Tone
> 👩🏽‍🤝‍👩🏼 Women Holding Hands: Medium Skin Tone, Medium-Light Skin Tone
> 👭🏽 Women Holding Hands: Medium Skin Tone
> 👩🏾‍🤝‍👩🏻 Women Holding Hands: Medium-Dark Skin Tone, Light Skin Tone
> 👩🏾‍🤝‍👩🏼 Women Holding Hands: Medium-Dark Skin Tone, Medium-Light Skin Tone
> 👩🏾‍🤝‍👩🏽 Women Holding Hands: Medium-Dark Skin Tone, Medium Skin Tone
> 👭🏾 Women Holding Hands: Medium-Dark Skin Tone
> 👩🏿‍🤝‍👩🏻 Women Holding Hands: Dark Skin Tone, Light Skin Tone
> 👩🏿‍🤝‍👩🏼 Women Holding Hands: Dark Skin Tone, Medium-Light Skin Tone
> 👩🏿‍🤝‍👩🏽 Women Holding Hands: Dark Skin Tone, Medium Skin Tone
> 👩🏿‍🤝‍👩🏾 Women Holding Hands: Dark Skin Tone, Medium-Dark Skin Tone
> 👭🏿 Women Holding Hands: Dark Skin Tone
> 👫🏻 Woman and Man Holding Hands: Light Skin Tone
> 👩🏻‍🤝‍👨🏼 Woman and Man Holding Hands: Light Skin Tone, Medium-Light Skin Tone
> 👩🏻‍🤝‍👨🏽 Woman and Man Holding Hands: Light Skin Tone, Medium Skin Tone
> 👩🏻‍🤝‍👨🏾 Woman and Man Holding Hands: Light Skin Tone, Medium-Dark Skin Tone
> 👩🏻‍🤝‍👨🏿 Woman and Man Holding Hands: Light Skin Tone, Dark Skin Tone
> 👩🏼‍🤝‍👨🏻 Woman and Man Holding Hands: Medium-Light Skin Tone, Light Skin Tone
> 👫🏼 Woman and Man Holding Hands: Medium-Light Skin Tone
> 👩🏼‍🤝‍👨🏽 Woman and Man Holding Hands: Medium-Light Skin Tone, Medium Skin Tone
> 👩🏼‍🤝‍👨🏾 Woman and Man Holding Hands: Medium-Light Skin Tone, Medium-Dark Skin Tone
> 👩🏼‍🤝‍👨🏿 Woman and Man Holding Hands: Medium-Light Skin Tone, Dark Skin Tone
> 👩🏽‍🤝‍👨🏻 Woman and Man Holding Hands: Medium Skin Tone, Light Skin Tone
> 👩🏽‍🤝‍👨🏼 Woman and Man Holding Hands: Medium Skin Tone, Medium-Light Skin Tone
> 👫🏽 Woman and Man Holding Hands: Medium Skin Tone
> 👩🏽‍🤝‍👨🏾 Woman and Man Holding Hands: Medium Skin Tone, Medium-Dark Skin Tone
> 👩🏽‍🤝‍👨🏿 Woman and Man Holding Hands: Medium Skin Tone, Dark Skin Tone
> 👩🏾‍🤝‍👨🏻 Woman and Man Holding Hands: Medium-Dark Skin Tone, Light Skin Tone
> 👩🏾‍🤝‍👨🏼 Woman and Man Holding Hands: Medium-Dark Skin Tone, Medium-Light Skin Tone
> 👩🏾‍🤝‍👨🏽 Woman and Man Holding Hands: Medium-Dark Skin Tone, Medium Skin Tone
> 👫🏾 Woman and Man Holding Hands: Medium-Dark Skin Tone
> 👩🏾‍🤝‍👨🏿 Woman and Man Holding Hands: Medium-Dark Skin Tone, Dark Skin Tone
> 👩🏿‍🤝‍👨🏻 Woman and Man Holding Hands: Dark Skin Tone, Light Skin Tone
> 👩🏿‍🤝‍👨🏼 Woman and Man Holding Hands: Dark Skin Tone, Medium-Light Skin Tone
> 👩🏿‍🤝‍👨🏽 Woman and Man Holding Hands: Dark Skin Tone, Medium Skin Tone
> 👩🏿‍🤝‍👨🏾 Woman and Man Holding Hands: Dark Skin Tone, Medium-Dark Skin Tone
> 👫🏿 Woman and Man Holding Hands: Dark Skin Tone
> 👬🏻 Men Holding Hands: Light Skin Tone
> 👨🏼‍🤝‍👨🏻 Men Holding Hands: Medium-Light Skin Tone, Light Skin Tone
> 👬🏼 Men Holding Hands: Medium-Light Skin Tone
> 👨🏽‍🤝‍👨🏻 Men Holding Hands: Medium Skin Tone, Light Skin Tone
> 👨🏽‍🤝‍👨🏼 Men Holding Hands: Medium Skin Tone, Medium-Light Skin Tone
> 👬🏽 Men Holding Hands: Medium Skin Tone
> 👨🏾‍🤝‍👨🏻 Men Holding Hands: Medium-Dark Skin Tone, Light Skin Tone
> 👨🏾‍🤝‍👨🏼 Men Holding Hands: Medium-Dark Skin Tone, Medium-Light Skin Tone
> 👨🏾‍🤝‍👨🏽 Men Holding Hands: Medium-Dark Skin Tone, Medium Skin Tone
> 👬🏾 Men Holding Hands: Medium-Dark Skin Tone
> 👨🏿‍🤝‍👨🏻 Men Holding Hands: Dark Skin Tone, Light Skin Tone
> 👨🏿‍🤝‍👨🏼 Men Holding Hands: Dark Skin Tone, Medium-Light Skin Tone
> 👨🏿‍🤝‍👨🏽 Men Holding Hands: Dark Skin Tone, Medium Skin Tone
> 👨🏿‍🤝‍👨🏾 Men Holding Hands: Dark Skin Tone, Medium-Dark Skin Tone
> 👬🏿 Men Holding Hands: Dark Skin Tone
> 🦧 Orangutan
> 🦮 Guide Dog
> 🐕‍🦺 Service Dog
> 🦥 Sloth
> 🦦 Otter
> 🦨 Skunk
> 🦩 Flamingo
> 🧄 Garlic
> 🧅 Onion
> 🧇 Waffle
> 🧆 Falafel
> 🧈 Butter
> 🦪 Oyster
> 🧃 Beverage Box
> 🧉 Mate
> 🧊 Ice
> 🛕 Hindu Temple
> 🦽 Manual Wheelchair
> 🦼 Motorized Wheelchair
> 🛺 Auto Rickshaw
> 🪂 Parachute
> 🪐 Ringed Planet
> 🤿 Diving Mask
> 🪀 Yo-Yo
> 🪁 Kite
> 🦺 Safety Vest
> 🥻 Sari
> 🩱 One-Piece Swimsuit
> 🩲 Briefs
> 🩳 Shorts
> 🩰 Ballet Shoes
> 🪕 Banjo
> 🪔 Diya Lamp
> 🪓 Axe
> 🦯 Probing Cane
> 🩸 Drop of Blood
> 🩹 Adhesive Bandage
> 🩺 Stethoscope
> 🪑 Chair
> 🪒 Razor
> 🟠 Orange Circle
> 🟡 Yellow Circle
> 🟢 Green Circle
> 🟣 Purple Circle
> 🟤 Brown Circle
> 🟥 Red Square
> 🟧 Orange Square
> 🟨 Yellow Square
> 🟩 Green Square
> 🟦 Blue Square
> 🟪 Purple Square
> 🟫 Brown Square

### Expected behaviour
It should display those new emojis.

### Actual behaviour
It displays a small box.

### Configuration
**Operating system:**  Microsoft Windows 10 Pro 10.0.17763

**Version of Telegram Desktop:** 1.9.3

**Used theme**: dark

**Comment by Aokromes** [comment]
a lot of them works for me on windows 10 201h.

**Comment by rafitamolin** [comment]
> a lot of them works for me on windows 10 201h.

Here's what I see, which isn't the expected result:

![1](https://s.chollo.to/sBe6w.png)
![2](https://s.chollo.to/sBh8D.png)
![3](https://s.chollo.to/sBIJG.png)
![4](https://s.chollo.to/sBWhH.png)

**Comment by ArmeF97** [comment]
Using ubuntu 20.04, I can't see new emojis

**Comment by adasiko** [comment]
> Using ubuntu 20.04, I can't see new emojis

I think it's more ubuntu bug
https://launchpad.net/ubuntu/+source/fonts-noto-color-emoji

> The Focal Fossa 20.04 - fonts-noto-color-emoji  0~20180810-1.1

**Comment by ArmeF97** [comment]
I think it's a telegram but. I can see al emoji, except the ones introduced with unicode 12

**Comment by Aokromes** [comment]
telegram manually adds support of new unicode versions on older operative systems.

**Comment by Twilightssuperb** [comment]
https://emojipedia.org/emoji-12.1/ Apple (iOS 13.2), Twitter and JoyPixels (ex-Emoji One) has published new emojis that could be implemented. Google too https://blog.emojipedia.org/android-10-0-emoji-changelog/

**Comment by rafitamolin** [comment]
Implemented in version 2.1.4 ✅
