### ISSUE TITLE
timestamps under video are ignored if adjacent to parentheses

### ISSUE THREAD

**Issue by Mithgol** [telegramdesktop/tdesktop#6997]
### Steps to reproduce
1. Visit https://t.me/ReadMithgol/140

### Expected behaviour
Timestamps «1:31» and «1:46» and «2:11» should be as active in Telegram Desktop as in Telegram for Android.

### Actual behaviour
Timestamps «1:31» and «1:46» and «2:11» are ignored (remain in plain text) presumably because they are adjacent to parentheses.

### Configuration
**Operating system:** Windows 7 Professional, 64 bit, with Service Pack 1.

**Version of Telegram Desktop:** 1.9.3.

**Used theme**: Day.

**Comment by john-preston** [comment]
Thanks, I'll fix that in the next version.
