### ISSUE TITLE
Folder icon with telegram client

### ISSUE THREAD

**Issue by belnet** [telegramdesktop/tdesktop#6998]
### Steps to reproduce
1. install a custom icon on the client folder
2. run telegram client
3. the read-only attribute is erased by the folder and the icon ceases to be displayed

problem play video: https://klikr.org/33843cc95c8acf3f4f5d137d1d43.gif

### Expected behaviour
Tell us what should happen

### Actual behaviour
the client erases the read-only attribute from the directory where telegram.exe is located
this should not happen.
even if recording is allowed in subfolders and files (which is logical), the attribute of the EXTERNAL directory should remain unchanged.
I suggest tracking this by the presence of the desktop.ini file in the directory.
if this file is present, then the client should check the attribute of the directory in which it is located, and not mindlessly erase it.
Windows OS processes desktop.ini which is responsible for displaying the icon on the folder ONLY if the read-only attribute is set on this folder

for example, I can set this attribute from the console:
https://klikr.org/7c7f0dc9e628adbb4e3c815be429.png
an icon on the folder will appear, BUT only until the first launch of telegram.
### Configuration
**Operating system:**
Win 10 LTSB (1604) x64.
**Version of Telegram Desktop:**
1,0 + 1.9.3
**Used theme**:
any

**Comment by Aokromes** [comment]
1.0.3? update the current telegram client version is 1.9.3

**Comment by belnet** [comment]
[img]https://klikr.org/c39828479815b5c19b02c9cb4675.png[/img]
it was a typo.
current client 1.9.3
but this problem has been going on since the first version.

**Comment by belnet** [comment]
> You copy a desktop.ini file into a folder to customize and maybe localize it. You have correctly set the file’s attributes to Hidden, System and Read-Only, but still your customizations do not work. To make it work you need to set the Read-Only or System flags on the folder where the desktop.ini file resides. As I am sure you know, folders cannot be read-only, neither can they “remember” your settings so that all new files placed in the folder become read-only as well. So this flag is purely to tell Windows that this is a special folder and that it should look for a desktop.ini file inside it.

TNX to Asura for this.
thus Read-Only or System
I set one of the attributes, as the specification requires, it works for the folder, but it’s worth starting the telegram as the attribute is overwritten (

**Comment by Aokromes** [comment]
i wonder if you can use this way on windows https://github.com/telegramdesktop/tdesktop/issues/1908#issuecomment-456922984

**Comment by belnet** [comment]
Unfortunately, the topics have nothing to do with my problem and it is character only for windows.
the telegram client should be able to correctly read and process the attributes of folders, and not stupidly overwrite them at its start, this is the bug.

it is a pity that the developers do not look into this thread.
Anyway, thank you for trying to help with my problem!
