### ISSUE TITLE
Avoid to open sticker panel on mouse hover

### ISSUE THREAD

**Issue by ivmazurenko** [telegramdesktop/tdesktop#7000]
### Steps to reproduce
1. Try to click on your message in a desktop application
2. Accidentally hover a mouse over sticker panel

### Expected behaviour
The sticker with penis has not been sent to your serious team.

### Actual behaviour
The sticker with penis was sent.

### Configuration
**Operating system:** 
any
**Version of Telegram Desktop:**
any
**Used theme**:
any

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/1333

**Comment by ivmazurenko** [comment]
@Aokromes Why do you close this bug? When the fix will be implemented? It is very annoying

**Comment by Aokromes** [comment]
because it's duplicated of the linked issue.

**Comment by ivmazurenko** [comment]
So, when this bug will be fixed?

**Comment by RememberTheAir** [comment]
@ivmazurenko it's not going to be fixed. It's the intended behavior

**Comment by ivmazurenko** [comment]
Maybe you can add the configuration button? 

It is not expected when unwanted popups are opened when you just moving the mouse to your message.  

![ezgif com-crop](https://user-images.githubusercontent.com/34516127/72677681-a62ae580-3aa7-11ea-8f29-2cf32422a31d.gif)
