### ISSUE TITLE
Hiding the window minimizes it

### ISSUE THREAD

**Issue by krunkerista** [telegramdesktop/tdesktop#7003]
### Steps to reproduce
1. Hide the **maximized** window with 
![image](https://user-images.githubusercontent.com/56792029/72456216-830ce700-37c4-11ea-9cc4-192c7ac5be9f.png)

2. Open up the window again 

### Expected behaviour
The window should appear as it was (maximized)

### Actual behaviour
It appears in the minimized mode

### Configuration
**Operating system:**
Windows 10

**Version of Telegram Desktop:**
1.9.3

**Used theme**:
Night mode

<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by Aokromes** [comment]
cannot reproduce this on 1.9.8 and windows 10 20h1.

**Comment by krunkerista** [comment]
The issue was fixed in version 1.9.4
