### ISSUE TITLE
Small issue with view after message editing

### ISSUE THREAD

**Issue by tedsemashov** [telegramdesktop/tdesktop#7004]
# Steps to reproduce
1. Write some message
2. Your interlocutor must answer on your message
3. Edit your message (which you sent earlier)

### Expected behaviour
Answered message view must be changed related edited message

### Actual behaviour
Answered message view is with old message (not changed according to edited message)

### Configuration
**Operating system:**
MacOS Mojave

**Version of Telegram Desktop:**
5.8 from App Store

**Used theme**:
Dark

<img width="478" alt="proof" src="https://user-images.githubusercontent.com/30953783/72476235-663cd780-37f5-11ea-95da-4d2a27691dab.png">

<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by Aokromes** [comment]
you are using native macos telegram application, not telegram desktop.
