### ISSUE TITLE
The application closes unexpectedly when a group is selected

### ISSUE THREAD

**Issue by evgeniy-nikitin** [telegramdesktop/tdesktop#7005]
### Steps to reproduce
1. I open the Telegram window.
2. On the left side of the window, select a group from the list and click there.
3. Emergency closing of Telegram window.

### Expected behaviour
A group should open and messages should be downloaded.

### Actual behaviour
If you click on a group in the left application column, the program window will be closed unexpectedly.

An error is displayed in the command line:
ASSERT: "(pos == end && glyphPosition == current.num_glyphs) || logClusters[pos] == glyphPosition" in file /home/preston/Telegram/tdesktop/Telegram/lib_ui/ui/text/text_block.cpp, line 142.

### Configuration
**Operating system:** Debian Jessie

**Version of Telegram Desktop:** 1.9.3

**Used theme**: default

**Comment by john-preston** [comment]
Is it possible to add me to this group? t.me/preston

**Comment by toptnc** [comment]
This happen to me too with versions 1.9.3 and 1.9.4
Operating System: Ubuntu 16.04
Theme: default

**Comment by evgeniy-nikitin** [comment]
@john-preston The problem remains in version 1.9.4.
