### ISSUE TITLE
Can't build Win32 on WindowsTargetPlatformVersion 8.1 and PlatformToolset v 142

### ISSUE THREAD

**Issue by trunov-ms** [telegramdesktop/tdesktop#7006]
Can't build on Win32 platform with WindowsTargetPlatformVersion 8.1 and PlatformToolset v 142 on tag v1.9.3
Errors look like
```
C:\Program Files (x86)\Windows Kits\8.1\Include\um\combaseapi.h(228,21): error C2760: syntax error: unexpected token 'identifier', expected 'type specifier' (compiling source file C:\TBuild\tdesktop\Telegram\lib_ui\ui\platform\win\ui_window_shadow_win.cpp) [C:\TBuild\tdesktop\out\Telegram\lib_ui\lib_ui.vcxproj]
C:\Program Files (x86)\Windows Kits\8.1\Include\um\oaidl.h(473,17): error C2059: syntax error: '/' (compiling source file C:\TBuild\tdesktop\Telegram\lib_ui\ui\platform\win\ui_window_shadow_win.cpp) [C:\TBuild\tdesktop\out\Telegram\lib_ui\lib_ui.vcxproj]
C:\Program Files (x86)\Windows Kits\8.1\Include\um\oaidl.h(473,35): error C2238: unexpected token(s) preceding ';' (compiling source file C:\TBuild\tdesktop\Telegram\lib_ui\ui\platform\win\ui_window_shadow_win.cpp) [C:\TBuild\tdesktop\out\Telegram\lib_ui\lib_ui.vcxproj]
C:\Program Files (x86)\Windows Kits\8.1\Include\um\oaidl.h(488,17): error C2059: syntax error: '/' (compiling source file C:\TBuild\tdesktop\Telegram\lib_ui\ui\platform\win\ui_window_shadow_win.cpp) [C:\TBuild\tdesktop\out\Telegram\lib_ui\lib_ui.vcxproj]
```

After replacing WindowsTargetPlatformVersion 8.1 to 10 in ALL vcxproj files build successfull

**Comment by Aokromes** [comment]
try on 1.9.8 build system and instructions changed.

**Comment by trunov-ms** [comment]
configure.bar -D ....
Warn about uninitialized values.
Version: 1.9.9
-- Selecting Windows SDK version 8.1 to target Windows 6.3.9600.
-- Performing Test HAVE_LONG_ATOMIC_WITHOUT_LIB
-- Performing Test HAVE_LONG_ATOMIC_WITHOUT_LIB - Success
-- Configuring done
-- Generating done
-- Build files have been written to: C:/TBuild/tdesktop/out

Same errors.
Build on Windows 2012r2 with installed Windows Software Development Kit for Windows 8.1
Can I change Windows SDK version to 10 in configuration without this ?
```
Get-ChildItem -Path "C:\\TBuild\\tdesktop\\out\\" -Filter "*.vcxproj" -Recurse | ForEach { 
    (Get-Content $_.FullName).Replace("8.1", "10") | Set-Content $_.FullName 
}
```

**Comment by Aokromes** [comment]
@john-preston or @23rd may answer that.

**Comment by 23rd** [comment]
Actually, I really doubt that you will be able to build anything on the old version of the VS compiler and the Windows SDK.
At least [range-v3 requires](https://github.com/ericniebler/range-v3#supported-compilers) the latest version of Visual Studio.

**Comment by trunov-ms** [comment]
I build Microsoft Visual Studio Community 2019 Version 16.4.3.
Maybe need change WindowsTargetPlatformVersion to 10 in script generating vcxproj files for msbuild project? I can find this params in code.

**Comment by 23rd** [comment]
Hmm.
You can try to download the latest version of Windows 10 SDK (`10.0.18362.0`) and configure the project with `-DCMAKE_SYSTEM_VERSION=10.0.18362.0` argument.

**Comment by trunov-ms** [comment]
@23rd builds successfull with this arg, thanks.
