### ISSUE TITLE
Telegram Passport broken on Windows since version 1.9.0

### ISSUE THREAD

**Issue by MelnikovIG** [telegramdesktop/tdesktop#7007]
### Steps to reproduce
1. Go to example site https://core.telegram.org/passport/example
2. Press button `Log in With Telegram`

### Expected behaviour
Telegram desktop opened without errors

### Actual behaviour
Telegram desktop opened with error window
![image](https://user-images.githubusercontent.com/6163811/72518523-9c666f80-3866-11ea-8bdb-47ecc6e40a1f.png)

### Configuration
**Operating system:**
Windows 10 (1903)

**Version of Telegram Desktop:**
1.9.3

**Version of browser:**
Chrome 79.0.3945.117

### Notes
* Bug reproduced since v 1.9.0, works fine on previous versions
* It is desktop version bug, mobile app works as expected

**Comment by john-preston** [comment]
Thank you for the report! This will be fixed in the next version.

**Comment by john-preston** [comment]
Should be fixed starting with 1.9.4.
