### ISSUE TITLE
update flatpack and snap apps to v1.9.3

### ISSUE THREAD

**Issue by YousefSaber** [telegramdesktop/tdesktop#7008]
flatpak and snap apps are outdated and hasn't been updated to v1.9.3 yet

**Comment by atx49559** [comment]
v1.9.3
"Enjoy system spell checker support on all modern systems."

I'm so excited for this update.
It's means finally I can typing chinese with iBus framework on Ubuntu 18.04?

**Comment by ilya-fedin** [comment]
Flatpak updated a long time ago, snap updated today
