### ISSUE TITLE
[Feature Request] Block resent of annoying images/gifs

### ISSUE THREAD

**Issue by d-uspenskiy** [telegramdesktop/tdesktop#7009]
### Is your feature request related to a problem?
Some times chat participants are sending annoying images/gifs. You can delete such message locally but he/she can send it later over and over again.

### Describe the solution you'd like
Save hash of images/gifs in locally deleted message. Check for this hash before showing images in newly arrived messages from any participant. Images can be substituted with button to download blocked image manually.

**Comment by Aokromes** [comment]
very likely this needs to be done api-side.

**Comment by MasterGroosha** [comment]
You can write a bot for this. Also as a group owner/admin you can restrict selected people from sending mediafiles completely.
