### ISSUE TITLE
[Feature Request] keyboard hotkey for forwarding

### ISSUE THREAD

**Issue by philipposkhos** [telegramdesktop/tdesktop#7011]
### Is your feature request related to a problem?
Only the forwarding doesn't have keyboard hotkey. It will be better to have it for only keyboard using.

### Describe the solution you'd like
Add a hotkey combination for forwarding. Ctrl+ up&down to select message and Ctrl + shift  + F to pop up a window choose forwarding to.

Thanks

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/2109
