### ISSUE TITLE
Telegram stays in "online" status on locked screen (mac) and marks messages readen

### ISSUE THREAD

**Issue by ramil-k** [telegramdesktop/tdesktop#7013]
### Steps to reproduce
1. Pre-requirement: 
1.1 mac os with multiple users.
1.2 telegram with the same account on multiple devices (phone+mac)
2. Log into one mac os account
3. Launch telegram
4. Open dialog with person [p]
5. Keep telegram with opened dialog on front
6. Lock screen via apple-icon menu
7. Log into another mac os account (without telegram running on this account)
8. Have [p] send you messages

### Expected behaviour
[p] does not see your status as online
[p]'s messages are not marked as read until I open telegram on phone or log back into first account
I get notifications of [p]'s messages on phone

### Actual behaviour
[p] sees your status as online
[p]'s messages are marked as read
I don't get notifications of [p]'s messages on phone

### Configuration
**Operating system:**
macOS catalina 10.15.2 (19C57)

**Version of Telegram Desktop:**
v 1.8.15

**Used theme**:
default

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/7049 generic bug.
