### ISSUE TITLE
[Feature Request] Keyboard hotkey for go to archived chats

### ISSUE THREAD

**Issue by amirrammari** [telegramdesktop/tdesktop#7015]
### Is your feature request related to a problem?
No.

### Describe the solution you'd like
You can select Xth pinned conversation with Ctrl+X (1≤X≤5)
For example, you can select 1st pinned conversation with Ctrl+1
Also, you select any conversation with Alt+Up and Alt+Down
But I can't go to archived chats.
Please assign a keyboard shortcut.
I suggestion assign ``` Ctrl+` ``` (Ctrl+Backquote)
Thanks.

### Additional context
![Telegram](https://user-images.githubusercontent.com/23485114/72618274-fee76a80-394f-11ea-98c4-d4876247cd1d.gif)

**Comment by f242** [comment]
ctrl+9

**Comment by amirrammari** [comment]
> ctrl+9

`Ctrl+9` not working.
is `Ctrl+9` suggestion?

**Comment by f242** [comment]
> 
> 
> > ctrl+9
> 
> `Ctrl+9` not working.
> is `Ctrl+9` suggestion?
version 1.9.4? this hotkey was appear yesteray wiht latest update

**Comment by Aokromes** [comment]
works for me on 1.9.4

**Comment by 23rd** [comment]
@amirrammari You can open the `tdata/shortcuts-custom.json` file and write it there.
```
[
     {
         "command": "show_archive",
         "keys": "ctrl+`"
     }
]

```
