### ISSUE TITLE
Real-time decrement of unread messages counter is absent, unlike the Android app.

### ISSUE THREAD

**Issue by aryanrawlani28** [telegramdesktop/tdesktop#7016]
### Steps to reproduce
1. Open telegram, select any chat with a lot of unread messages.
2. When clicked, we see the first unread message from the whole lot.
3. Scrolling down, this number remains constant and does not change.

### Expected behaviour
1. Expected behaviour should be real-time decreasing the counter of unread messages as we scroll through the chat.
2. If we scroll up instead, number remains the same as it is at that point of time, because I'm not reading any unread messages.
3. This is not an issue in the Android app, and works perfectly in the app.

### Actual behaviour
1. Instead of the expected behaviour, Telegram desktop shows the number of unread messages as constant, whether you scroll down or not. Once you get to the end of the chat, it disappears.

### Configuration
Win7 - 64bit

**Version of Telegram Desktop:**
V1.9.3

**Used theme**:
Dark
(Also same issue with the light theme, theme is not root cause here)

**Comment by Aokromes** [comment]
#775
