### ISSUE TITLE
[Feature Request] Add "Delivered to device" check

### ISSUE THREAD

**Issue by FinixFighter** [telegramdesktop/tdesktop#7017]
### Is your feature request related to a problem?
No

### Describe the solution you'd like
I know that "delivered to device" check has not been implemente dbecause Telegram is available for multiple devices. But I think that the user could have the possibility to activate this feature, specyfing that the "delivered to device" check popups when the message is delivered to at least one device. I think there's nothing wrong with such a feature, users would have the ability to enable/desable it in the chat settings (for example).

**Comment by MasterGroosha** [comment]
From [Telegram FAQ](https://telegram.org/faq#q-what-do-the-green-checks-mean):

> We don‘t have a ’delivered to device' status for messages because Telegram can run on as many devices as you want. So which particular one would that check mean?

**Comment by FinixFighter** [comment]
> From [Telegram FAQ](https://telegram.org/faq#q-what-do-the-green-checks-mean):
> 
> > We don‘t have a ’delivered to device' status for messages because Telegram can run on as many devices as you want. So which particular one would that check mean?

I know, but as I said, it could be for example a "Delivered to at least one device"

**Comment by RememberTheAir** [comment]
@FinixFighter that's why they didn't add it. "Delivered to at least one device" doesn't mean the user has received the message in a device he's bringing with him right now, so that information would be pointless and misleading in many cases
