### ISSUE TITLE
Release 1.9.4 misses the full source tar ball

### ISSUE THREAD

**Issue by Johnnynator** [telegramdesktop/tdesktop#7018]
https://github.com/telegramdesktop/tdesktop/releases/download/v1.9.4/tdesktop-1.9.4-full.tar.gz: Not Found

**Comment by Aokromes** [comment]
works for me

https://i.imgur.com/zrBlksh.png

**Comment by Johnnynator** [comment]
Yeah, it was added probably minutes if not seconds after I checked it.

**Comment by john-preston** [comment]
@Johnnynator Sorry, I'll upload assets later today.

**Comment by john-preston** [comment]
@Johnnynator Ah, they're there already. Ok.
