### ISSUE TITLE
Icon in notification tray does not scale.

### ISSUE THREAD

**Issue by fdistorted** [telegramdesktop/tdesktop#7019]
### Steps to reproduce
1. Install Telegram desktop to linux mint 19.3 xfce edition on a laptop with 14" 1080 display
2. set panel width to 40
3. set max icon size in Notification Area to 35

### Expected behaviour
Icon in Notification Area should scaled like other icons. On the [screenshot](https://imgur.com/Hf8RplD.png) you can see that zoom icon is scaled but telegram icon is looking strange.

### Actual behaviour
icon has fixed width of 22px
Image of the icon repeats

### Configuration
**Operating system:**
Linux Mint 19.3 Tricia x86_64 
Dell Latitude 7490 

**Version of Telegram Desktop:**
1.9.3

**Used theme**:
default night mode

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/3216
