### ISSUE TITLE
No System Tray Icon on Plasma Workspace 5 / KDE5

### ISSUE THREAD

**Issue by jalcine** [telegramdesktop/tdesktop#702]
In KDE4, the system tray for Telegram was usable. When upgrading to KDE5/PW5, the system tray icon is no longer visible. This is reproducible on the latest version of Telegram Desktop, version 0.8.11.

----
Related to issue #80.

**Comment by frapell** [comment]
Having this issue here as well

**Comment by sl1pkn07** [comment]
same here (plasma-desktop 5.3.0)

**Comment by varlesh** [comment]
Когда будет трей в 5-ой плазме?

**Comment by phoenixfirebrd** [comment]
This is due to some change in plasma 5. For more details read this blog. http://blog.martin-graesslin.com/blog/2014/06/where-are-my-systray-icons/

**Comment by jalcine** [comment]
Super dope, @phoenixfirebrd! So this seems to be a duality problem; with the version of Qt used and the libraries for application indicators on said machine. @telegramdesktop should take this into consideration.

**Comment by thomich** [comment]
can confirm that.... as @phoenixfirebrd wrote... hope soon an update is coming ;)

**Comment by HelixiR** [comment]
+1

**Comment by apcomptec** [comment]
+1

**Comment by ScorpionIT** [comment]
@telegramdesktop 
I suggest the use of http://jjacky.com/statusnotifier/ instead of libappindicator

**Comment by smvm** [comment]
+1

**Comment by jalcine** [comment]
@ScorpionIT Mind providing a patch?

**Comment by naught101** [comment]
for what it's worth, you can probably work around this by installing `wmsystemtray`, and running

```
wmsystemtray --non-wmaker --bgcolor white
```

and the dropbox icon should appear in a small window. Not the prettiest solution, but it works for now...

**Comment by XavierCLL** [comment]
+1 confirm, please fix it

**Comment by sergioad** [comment]
+1 I have not tray icon on plasma 5 too

**Comment by timeknows** [comment]
+1

**Comment by varlesh** [comment]
developers can say anything?

**Comment by Evalle** [comment]
+1

**Comment by KAMiKAZOW** [comment]
And thanks to #703 Telegram can't even be quit without resorting to the process manager…

**Comment by sergioad** [comment]
Indeed, this is why wee need even more urgently tray compatibility

**Comment by KAMiKAZOW** [comment]
Btw, that all would be no problem if Telegram just used regular Qt5 instead of its own patched fork.

**Comment by roberth1990** [comment]
This is ridiculous. +1

**Comment by senyk** [comment]
+1! :)

**Comment by naught101** [comment]
Guys, I don't think the +1s are going to help. If you can't code, just press subscribe, and wait for someone who can.

**Comment by Mte90** [comment]
+1

**Comment by KAMiKAZOW** [comment]
@naught101: No coder can help with this issue as long as the maintainer thinks depending on a broken Qt fork is a good idea...

**Comment by stalkerg** [comment]
+1 ждёмс

**Comment by marcogiannini** [comment]
some news?

**Comment by sergioad** [comment]
No news sadly

**Comment by senyk** [comment]
I take my +1 back and give it a -1.
I agree with @KAMiKAZOW  ... as long as the arch packages ships it's own Qt build this won't go away (unless you fix the Qt build within the telegram build...)

As soon as they use the system Qt5 all the problems with the tray are gone.
It seems it's that way right now because they have patches for Qt .. anyone knows what up with that?

**Comment by roberth1990** [comment]
What the heck are you talking about? It is the telegram developers who ship this with their own fork of qt.

**Comment by senyk** [comment]
Doesn't matter who the packager is, it's his fault never the less :)

**Comment by roberth1990** [comment]
Then why a -1?

**Comment by senyk** [comment]
True, in the light of telegram being their own packages I take the "-1" and re-add my "+1" ;)

**Comment by kvaster** [comment]
Any chances to have that fixed for plasma 5 ? :(

**Comment by Yukariin** [comment]
> Any chances to have that fixed for plasma 5 ? :(

Of course not! This is Telegram after all...

**Comment by EliaGeretto** [comment]
Same problem with Plasma 5 on Arch Linux. By the way, when I try to log out from my session, if Telegram is running, the process "plasmashell" crashes.

**Comment by kkofler** [comment]
For the current system tray protocol (Status Notifier) to work, you need Qt ≥ 5.4 (current is now 5.5, by the way) built with Status Notifier support. In particular, you have to build Qt with D-Bus support, because the Status Notifier protocol uses D-Bus. I'm not sure whether anything else is needed.

And I can only second what @KAMiKAZOW wrote: bundling a patched Qt is a horribly bad idea. If you want any improvements in Qt, you need to get them into upstream Qt. Distributions cannot ship a separate Qt with different patches for every single application, and upstreaming your improvements would also allow other applications to benefit from them.

**Comment by kvaster** [comment]
I've tried to compile telegram by myself, but unfortunatelly build process will break my 'clean' gentoo system - build process requires me to install patched version of qt to my system folders... Using static and patched version of Qt is really not good... Especially using 'internal' Qt functions like QtItemInt :( Telegram is dissapointing me :(

**Comment by pdf** [comment]
@kvaster build in a chroot or VM.

**Comment by kvaster** [comment]
Sounds like ...

**Comment by Yukariin** [comment]
@kvaster +1
I've tried to compile telegram on my gentoo laptop too and patched Qt it's... I don't know what to say about that >_<

**Comment by KAMiKAZOW** [comment]
https://twitter.com/telegramdesktop/status/623546631032598528

In the meantime I successfully packaged the alternative [Cutegram](http://aseman.co/en/products/cutegram/) client for Fedora based on the openSUSE packages. Works fine, incl. systray icon and Ctrl-Q #703

**Comment by Gunirus** [comment]
Fixed for me in the latest dev version.

**Comment by sl1pkn07** [comment]
FINALLY!!!

(with 0.8.41)

**Comment by sergioad** [comment]
COOL :smile:

**Comment by jalcine** [comment]
Sounds like it's been fixed. I'll close this issue then.

**Comment by igorastds** [comment]
@Yukariin @kvaster @KAMiKAZOW
I'm working on a Dockerfile (for running tdesktop on Gentoo).. after noticing that Cutegram now has a "nice" dependency on libtelegram-ae => libunity-dev => half of Ubuntu/launchpad. Not the best solution (basically chroots whole ubuntu), but should work for some time.. stuff will go to https://github.com/igorastds/tdesktop/tree/telegram-build-with-docker

**Comment by KAMiKAZOW** [comment]
@igorastds: That's a packaging problem of Ubuntu. Ubuntu's packaging bugs should be reported to Ubuntu.
