### ISSUE TITLE
[Feature Request] Ability to force all messages on the left

### ISSUE THREAD

**Issue by Storm-Engineer** [telegramdesktop/tdesktop#7020]
### Is your feature request related to a problem?
Currently the only way to have all messages on the left is via the "adaptive layout for wide screen" option which means you are forced to have Telegram full screen, or at least wider than the seemingly random magic value where it switches.

Own messages on the right may be popular due to phones, but it has one serious flaw: It causes own messages to start at random vertical positions rather than aligned.

The vast majority of languages in the World are Left to Right. With left-aligned or justified text, lines always start at the same place, which makes it easy to read. When right aligned, it will be inconsistent which both makes it hard to read and for me extremely annoying and frustrating.

### Describe the solution you'd like
Instead of a checkbox to toggle adaptive layout, provide us three options:
 - Own messages always left
 - Own messages always right
 - Adaptive

### Describe alternatives you've considered
-

### Additional context
While right-aligned own messages is a popular trend on mobile and people are used to it, scientifically and typographically there is absolutely no advantage to it, only disadvantage. Own messages can be made distinct via other means (avatars and color difference already does this job perfectly) but right-aligned text in Left-to-Right languages is always going to be awkward and uncomfortable to read. This is much less evident on mobile screens because text usually fils its width, but on desktop, it is definitely a problem.

From perspective of readability, the only case where text should ever be right-aligned is when using a Right-to-Left writing system.

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/5880
