### ISSUE TITLE
lost last messages while view group chat as guest

### ISSUE THREAD

**Issue by f242** [telegramdesktop/tdesktop#7023]
### Steps to reproduce
1. have account with about 50 active channels and 2-3 chats, i think it's important
2. uptume 48h also important
3. go to view as guest some group chat with activity 500msg/day by click @somegroup without join
4. opens last messages, for example
message 1 18:00
message 2 18:15
message 3 18:45
message 4 19:00
message 5 19:15  **<-** this message shows less 1 second and disappears
5. go to **Shared Links** of group, i know that last message contains hyperlink and seeing it here! right click on it and **Go To Message**
6. and i see in chat
message 1 18:00
message 2 18:15
**message 5 19:15** 
message 3 18:45
message 4 19:00

I can say that watching a chat without joining does not always display the latest messages

### Expected behaviour
nothing disappears

### Actual behaviour
as above

### Configuration
win10 x64 1909, latest telegram desktop, this bug about 6 months

**Comment by f242** [comment]
![image](https://user-images.githubusercontent.com/10371194/73575702-ca17ff00-4489-11ea-919d-f2d52ec7af24.png)

**Comment by f242** [comment]
![image](https://user-images.githubusercontent.com/10371194/73799131-1df65100-47c6-11ea-8824-e3b01ed0d82c.png)

**Comment by f242** [comment]
![image](https://user-images.githubusercontent.com/10371194/74094743-45675980-4af7-11ea-91b3-095ea2bcbed9.png)

**Comment by reallyuniquename** [comment]
A known bug.

**Comment by reallyuniquename** [comment]
A bug.
