### ISSUE TITLE
Telegram protocol can't delete after uninstalling

### ISSUE THREAD

**Issue by xmha97** [telegramdesktop/tdesktop#7024]
I removed the Telegram and installed it from the Microsoft Store.
Now registered two protocol for `tg://`
Please remove Telegram protocol when uninstalling...
![image](https://user-images.githubusercontent.com/23485114/72669072-ca081000-3a42-11ea-899c-54088272e226.png)

 
### Steps to reproduce
1. 
2. 
3. 

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

### Configuration
**Operating system:**

**Version of Telegram Desktop:**

**Used theme**:

<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by jeffythedragonslayer** [comment]
Likely (I have not tested it) this registry key needs to be deleted on uninstall:

HKEY_CLASSES_ROOT\tdesktop.tg
