### ISSUE TITLE
Build Qt without Vulkan

### ISSUE THREAD

**Issue by kbroulik** [telegramdesktop/tdesktop#7025]
Following the [Linux Build Instructions](https://github.com/telegramdesktop/tdesktop/blob/dev/docs/building-cmake.md) I wanted to build the custom Qt 5.12.5.
It failed in `QVkConvenience` due to a missing `QOpenGLTexture`.
Build instructions said to configure it with `no-opengl` but Vulkan was on.
Configuring it additionally with `-no-feature-vulkan` fixed the buid.
Perhaps this is something that should be addressed upstream since it makes no sense to have Vulkan depend on OpenGL in this way and then fail.

**Comment by Aokromes** [comment]
there is no -no-opengl anymore
