### ISSUE TITLE
[Question] How to choose a language for spell check?

### ISSUE THREAD

**Issue by adian** [telegramdesktop/tdesktop#7028]
I use Fedora 31 with English interface. Can I change spell check language (not English)?

**Comment by Aokromes** [comment]
afaik, you cannot, but i think you will get tips of every installed dictionary language.

**Comment by adian** [comment]
When I change Fedora interface to Polish, English and Polish spell check is working. But when I use English interface only English spell check is working :/

**Comment by ecafesroh** [comment]
Hey. I have the same problem on Debian 10. Telegram spellchecker completely ignores any language unless that language is set as a system language. I.e. if my system language is English I get only English spellchecking, if I switch my system language to German I get only German spellchecking (English gets turned off)

**Comment by 23rd** [comment]
Now you can choose a language from the Settings in the latest beta version.
