### ISSUE TITLE
Option to read all messages

### ISSUE THREAD

**Issue by wanderleihuttel** [telegramdesktop/tdesktop#7029]
Please! Include the option to read all messages (archived and normal) messages in telegram desktop!
In the android app (telegram X) is possible to read all archived message. But would be interesting an option to mark all messages as read!
Or another suggestion would be not show unread messages in the archived messages!

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/5998

**Comment by wanderleihuttel** [comment]
Sorry! I haven't seen that I've already had opened a feature request with these suggestions!
