### ISSUE TITLE
Quit with Ctrl-Q

### ISSUE THREAD

**Issue by KAMiKAZOW** [telegramdesktop/tdesktop#703]
Please implement quitting Telegram with Ctrl-Q like all other programs under Linux and many under Windows (should also work as Cmd-Q under OSX).

**Comment by ezdev128** [comment]
Personally, I'm against this. This shouldn't be core functionality or make it tunable in configuration.
Many people blame on this feature caused pressing ctrl+q instead of ctrl+tab.
Example: https://addons.mozilla.org/En-us/firefox/addon/disable-ctrl-q-shortcut/

**Comment by KAMiKAZOW** [comment]
Ctrl-Q is the standard shortcut for Quit under Linux. Cmd-Q is the standard shortcut for Quit under OSX. (Ctrl-W / Cmd-W closes the window.)
If that confuses Windows users, make it optional there but considering that out of millions of Firefox users only 3,670 installed that.
If unsend text is still in the text field, a warning could be displayed. That's AFAIK the only case data could be lost. In every other case no data can be lost and therefore an accidentally quit application would cause no harm.

**Comment by earendil02** [comment]
I agree, Ctrl-Q is the standard shortcut for Quit, and I think there should be a shortcut available to directly quit Telegram (not just close the window as with Alt-F4) without having to pass through the tray icon.

**Comment by roberth1990** [comment]
Yeah this is hopeless, I am tired of having to use killall to shut down telegram, since because of bug #702 .

**Comment by majewsky** [comment]
Same here, really annoying to find out that the client has been running for ours even though I intended to close it. I'd actually like an option to have Alt-F4 close the app completely instead of minimizing it to the (for me non-existing) systray.

**Comment by flipmess** [comment]
why is this closed? or is there a shortcut to quit telegram?

**Comment by auchri** [comment]
See #1060

**Comment by flipmess** [comment]
thx
