### ISSUE TITLE
add TCP datacenter ip and port manual

### ISSUE THREAD

**Issue by Metal-Ghost** [telegramdesktop/tdesktop#7031]
hi 
telegram will connect to 149.154.167.91 with port 443 in tcp direct mode
how can i add manual tcp ip and port and connect it (A telegram datacenter ip and port i have its not in list of config.h file) 
thanks all.

**Comment by Metal-Ghost** [comment]
no way?

**Comment by ilya-fedin** [comment]
> no way?

no way
