### ISSUE TITLE
[Feature Request] Gray dock bar icon when all messages are from muted channles 

### ISSUE THREAD

**Issue by hyzyla** [telegramdesktop/tdesktop#7036]
### Is your feature request related to a problem?
Currently, I have a lot of channels and groups with disabled notification settings (public channels and groups) and a few important chats where I receive notification about every message (chat with friends). Also, I use Telegram on PC with two monitors and I can miss some notifications as my attention can be on another monitor. As the visual notification for the unread message, I constantly check that my dock bar icon is empty (doesn't contains red icon with counter). But the icon in dock shows messages from all channels with red counter, even if I have only unread messages only from the channels with muted notification settings. I think, that showing a red counter is part of the visual notification, that I receive on checking my dock icon.

I'm using Ubuntu 18.04.3 LTS and Telegram client 1.8.15

### Describe the solution you'd like
I propose to show a gray counter on Ubuntu dock (maybe in another system too) when all unread messages are from muted channels and groups.
![image](https://user-images.githubusercontent.com/7952949/72802994-a9fc6a80-3c55-11ea-9323-ad084d4263b2.png)

Similar logic already implemented for tray icons:
![image](https://user-images.githubusercontent.com/7952949/72803005-ae288800-3c55-11ea-956c-296cb2b6020c.png)

If someone from the maintainer will approve that changes, I can even work on PR for solving my pain.

**Comment by ilya-fedin** [comment]
The spec says it's impossible
https://wiki.ubuntu.com/Unity/LauncherAPI

**Comment by hyzyla** [comment]
Thanks for reference. Issue could be closed, as it's impossible.

**Comment by ilya-fedin** [comment]
Looks like there are an old issue with a discussion https://github.com/telegramdesktop/tdesktop/issues/5913

**Comment by hyzyla** [comment]
@ilya-fedin I recently update my Telegram client and settings have a checkbox for disabling counting unread messages. I think related issue https://github.com/telegramdesktop/tdesktop/issues/5913  also could be closed.

![image](https://user-images.githubusercontent.com/7952949/73726974-39ffe100-4739-11ea-8b85-1b30fd4b3359.png)
