### ISSUE TITLE
Spell check error for ukrainian language 

### ISSUE THREAD

**Issue by lexesv** [telegramdesktop/tdesktop#7038]
### Steps to reproduce
1. Install ukrainian dictionary 
2. Run spell check 

### Expected behaviour
Spell check for ukrainian language

### Actual behaviour
![2020-01-21_15-10](https://user-images.githubusercontent.com/15149258/72807681-9c98ad80-3c60-11ea-889b-3b4322a90ff1.png)
![Screenshot_2020-01-21_15-19-09](https://user-images.githubusercontent.com/15149258/72808078-70316100-3c61-11ea-840d-73a940bf2171.png)

![2020-01-21_15-10_1](https://user-images.githubusercontent.com/15149258/72807691-a15d6180-3c60-11ea-88e7-e1f0e34601d5.png)

### Configuration
**Operating system:** Debian 10 amd64

**Version of Telegram Desktop:** 1.9.4

**Used theme**: no

**Comment by NickLion** [comment]
Same, 1.9.4 and 1.9.5 both are affected. It was fine before, sorry, don't remember what version I had.

OS: openSUSE Tumbleweed, x86_64
TG Version: 1.9.5

**Comment by sviperz** [comment]
Don't know if this is the same bug or another, but Telegram chooses wrong language for spell checking.

I'm using **Linux Mint 19.3 Cinnamon** with the following regional settings:

![Language_Settings](https://user-images.githubusercontent.com/11470610/72985921-17e09780-3df8-11ea-9b3f-b64c4fc672b8.png)

```
$ locale
LANG=en_US.UTF-8
LANGUAGE=en_US
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC=ru_RU.UTF-8
LC_TIME=en_US.UTF-8
LC_COLLATE="en_US.UTF-8"
LC_MONETARY=ru_RU.UTF-8
LC_MESSAGES="en_US.UTF-8"
LC_PAPER=ru_RU.UTF-8
LC_NAME=ru_RU.UTF-8
LC_ADDRESS=ru_RU.UTF-8
LC_TELEPHONE=ru_RU.UTF-8
LC_MEASUREMENT=ru_RU.UTF-8
LC_IDENTIFICATION=ru_RU.UTF-8
LC_ALL=
```
English spell checking works correctly. Still, for some reason Telegram is trying to use Belorussian language for spell checking text in Russian:

![Language_BE](https://user-images.githubusercontent.com/11470610/72986204-c2f15100-3df8-11ea-98a6-23e0815fd400.png)

Removing _hunspell-be_ package doesn't make any difference except that Telegram stops spell checking Belorussian language, but it still doesn't spell check Russian:

![Spell](https://user-images.githubusercontent.com/11470610/72986729-e9fc5280-3df9-11ea-9f0b-8e1a5f963d70.png)

It was fine indeed several versions before, but now it's broken.

OS: **Linux Mint 19.3 Cinnamon**
TG: **Telegram Desktop v1.9.7**

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/6767

**Comment by lexesv** [comment]
> _Spellchecking does not propose corrected words in my system language_

Sorry, but my problem is different.
Spellchecker does suggest the correct words in Ukrainian, but still marks the words as misspelled

**Comment by andriy85if** [comment]
I have the same problem. If the interface language is Ukrainian, then all the words entered in Ukrainian are emphasized as incorrect. 

This is a very big problem because it does not allow you to use spell check.

LinuxMint Cinnamon 19.3

**Comment by hematogender** [comment]
Same here. Russian and English spellcheckers work as expected, but Ukrainian one marks some words as wrong. If I choose a suggested word, choose to ignore or add a word to the dictionary, nothing happens.

Tried both aspell-uk and hunspell-uk backends, behavior doesn't change. 

Arch Linux 5.5.1-arch1-1
Telegram Desktop 1.9.9

**Comment by 23rd** [comment]
This should be fixed now in the latest beta version.

**Comment by dismine** [comment]
Thanks, I have just downloaded the beta version. It works for me.
