### ISSUE TITLE
High CPU Usage at app launch

### ISSUE THREAD

**Issue by joe733** [telegramdesktop/tdesktop#7039]
### Steps to reproduce
1. Quit telegram (even from tray)
2. Open telegram

### Expected behaviour
Normal CPU usage at startup (is it not? I'm not sure)

### Actual behaviour
High CPU usage

### Configuration
OS: elementary OS 5.1 Hera
CPU: Intel i5 2<sup>nd</sup> Gen
GPU: NVIDIA GeForce GT 525M
Mem: 12GB

**Version of Telegram Desktop:**
1.9.4

**Used theme**:
Classic

**ScreenGrab**
![A](https://user-images.githubusercontent.com/38415384/72810475-a54eab00-3c83-11ea-92a0-8cfa7586b1ba.gif)
@ 0:00 - Telegram running...
@ 0:23 - Quit Telegram using <kbd>Ctrl</kbd>+<kbd>Q</kbd>
@ 0:26 - Open Telegram - _High CPU usage_
@ 0:38 - Typing message stalls Telegram - _Heavy Memory & CPU usage_
@ 0:39 - Telegram Crashes

**Something from a [previous crash](https://github.com/telegramdesktop/tdesktop/issues/6983#issuecomment-575902363):**
```python
QApplication: invalid style override passed, ignoring it.
    Available styles: Windows, Fusion
Gtk-Message: 19:38:00.155: GtkDialog mapped without a transient parent. This is discouraged.
QTextCursor::setPosition: Position '13' out of range
QTextCursor::setPosition: Position '13' out of range
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x7fa8cc000900] Protocol name not provided, cannot determine if input is local or a network protocol, buffers and access patterns cannot be configured optimally without knowing the protocol
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x7fa90000ab00] Protocol name not provided, cannot determine if input is local or a network protocol, buffers and access patterns cannot be configured optimally without knowing the protocol
```

**Comment by Aokromes** [comment]
try again on 1.9.8 plz.

**Comment by joe247** [comment]
No issues on version 1.9.8. Thanks a lot!

**Comment by joe247** [comment]
Telegram crashed the 7th time! **v1.9.9**
```bash
QApplication: invalid style override passed, ignoring it.
    Available styles: Windows, Fusion
QTextCursor::setPosition: Position '8388607' out of range
QTextCursor::setPosition: Position '8388607' out of range
malloc_consolidate(): invalid chunk size
Aborted
```
![K](https://user-images.githubusercontent.com/38415384/73750283-e7e3ad80-4782-11ea-814b-741babe56e95.gif)
Yes, CPU usage shoots up too.

**Comment by Aokromes** [comment]
that crash is more https://github.com/telegramdesktop/tdesktop/issues/7095 than "high cpu ussage" :P

**Comment by joe247** [comment]
Got a temporary workaround...
1. Type what you want somewhere & copy paste it.
2. From next conversations onward it does not crash consistently (at least for now).

**Comment by Aokromes** [comment]
try 1.9.17.

**Comment by joe733** [comment]
> try 1.9.17.

I'm on 1.9.14. When checking for update (from under advanced settings) ... it says I'm on latest version.

**Comment by joe733** [comment]
Pretty stable in the beta version 1.9.20
