### ISSUE TITLE
"Could not send a empty file" error with non-roman character file names (Ubuntu 18.04)

### ISSUE THREAD

**Issue by reckus** [telegramdesktop/tdesktop#7043]
### Steps to reproduce
1. Try to send a file of which the file name and path to it contains non-roman characters (I've experimented with Korean, Japanese, Chinese and special characters) either through drag&drop or through attache button beside the chat input box.

### Expected behaviour
Caption input box should appear.

### Actual behaviour
Shows an error message "Could not send an empty file: [path and file name(which displays non-roman characters correctly)"

### Configuration
**Operating system:**
Ubuntu 18.04.3 LTS fully updated by Jan. 22. 2022.
tried on both en_GB.UTF-8 and ko_KR.UTF-8 locale settings

**Version of Telegram Desktop:**
1.9.5 for Linux
launched from terminal emulator, Nautilus, or .desktop file which contains "Encoding=UTF-8" line

**Used theme**:
classic

**Comment by Aokromes** [comment]
do you realize ubuntu 14.04 is EOL since hal 2019?

**Comment by reckus** [comment]
@Aokromes Sorry for confusion, it's 18.04.

**Comment by reckus** [comment]
This issue came also with saving problem which substituted all the non-roman characters of the file name with question marks.
And modifying Exec line of the .desktop file to "Exec=env LC_ALL=en_GB.UTF-8 %Telegram Path%", both problems got solved. Thanks.
