### ISSUE TITLE
[Bug] No context menu on titlebar

### ISSUE THREAD

**Issue by maxoku** [telegramdesktop/tdesktop#7045]
### Steps to reproduce
Click with right mouse button on titlebar.

### Expected behaviour
A context menu appears.

### Actual behaviour
Nothing happens.

### Configuration
Operating system: Windows 8.1
Version of Telegram Desktop: 1.9.6
Used theme: Day

**Comment by kirsan31** [comment]
Confirmed on Windows 7 and tdesktop 1.9.4.

**Comment by kirsan31** [comment]
`WM_SYSCOMMAND, SC_MOUSEMENU` correctly sending on `WM_NCRBUTTONUP`. But after that `WM_SYSCOMMAND` not firing, so we never show menu.

https://github.com/telegramdesktop/tdesktop/blob/b0c2ed839d43309ded0cc9a06adfd9bdf5766c17/Telegram/SourceFiles/platform/win/windows_event_filter.cpp#L228-L238 

I think this event is filtered somehow, but cant't find where...
cc @john-preston

**Comment by kirsan31** [comment]
I checked all filters down to `QEventDispatcherWin32::processEvents` and still find nothing :( The simple solution is to move menu logic from `WM_SYSCOMMAND && SC_MOUSEMENU` to `WM_NCRBUTTONUP` directly, but @john-preston may think differently...

**Comment by john-preston** [comment]
@kirsan31 Why do you need this menu at all? 🤔

**Comment by 23rd** [comment]
Just to remind that there is always `Alt+Space` as a workaround.

**Comment by kirsan31** [comment]
> @kirsan31 Why do you need this menu at all?

Technically yes, due to not native title bar, this menu is not needed. And on native bar, it's needed only by left click on top left corner :smile:

**Comment by Aokromes** [comment]
i suppose https://github.com/telegramdesktop/tdesktop/issues/2958

**Comment by kirsan31** [comment]
> i suppose #2958

No, there are code that show this menu manually. But it's broken somehow from 1.9.x ...
