### ISSUE TITLE
Telegram 1.9.3 crashes at start

### ISSUE THREAD

**Issue by vn971** [telegramdesktop/tdesktop#7047]
### Steps to reproduce
1. Install version 1.9.3 or 1.9.4 from ArchLinux (on 1.8.15 everything works fine and the bug doesn't reproduce).
2. try to start it

### Expected behaviour
Telegram starts up

### Actual behaviour
no GUI window is ever created, telegram dies with the following text in console:
```
(telegram-desktop-bin:3): GLib-GObject-WARNING **: 15:27:47.469: cannot register existing type 'GdkDisplayManager'

(telegram-desktop-bin:3): GLib-CRITICAL **: 15:27:47.470: g_once_init_leave: assertion 'result != 0' failed

(telegram-desktop-bin:3): GLib-GObject-CRITICAL **: 15:27:47.470: g_object_new_with_properties: assertion 'G_TYPE_IS_OBJECT (object_type)' failed

(telegram-desktop-bin:3): GLib-GObject-WARNING **: 15:27:47.470: invalid (NULL) pointer instance

(telegram-desktop-bin:3): GLib-GObject-CRITICAL **: 15:27:47.470: g_signal_connect_data: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed

(telegram-desktop-bin:3): GLib-GObject-WARNING **: 15:27:47.470: invalid (NULL) pointer instance

(telegram-desktop-bin:3): GLib-GObject-CRITICAL **: 15:27:47.470: g_signal_connect_data: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed

(telegram-desktop-bin:3): GLib-GObject-WARNING **: 15:27:47.471: cannot register existing type 'GdkDisplay'

(telegram-desktop-bin:3): GLib-CRITICAL **: 15:27:47.471: g_once_init_leave: assertion 'result != 0' failed

(telegram-desktop-bin:3): GLib-GObject-CRITICAL **: 15:27:47.471: g_type_register_static: assertion 'parent_type > 0' failed

(telegram-desktop-bin:3): GLib-CRITICAL **: 15:27:47.471: g_once_init_leave: assertion 'result != 0' failed

(telegram-desktop-bin:3): GLib-GObject-CRITICAL **: 15:27:47.471: g_object_new_with_properties: assertion 'G_TYPE_IS_OBJECT (object_type)' failed
```

### Configuration
**Operating system:** ArchLinux

**Version of Telegram Desktop:** 1.9.3, 1.9.4 (both). But the bug does NOT happen on 1.8.15

**Used theme**: "Day" blue.

Can I maybe gather some additional information from somewhere, or enable more logging, if that'll help?

**Comment by john-preston** [comment]
@vn971 Is this the version from https://desktop.telegram.org?

**Comment by vn971** [comment]
@john-preston yes, absolutely. This is the exact build instruction: https://git.archlinux.org/svntogit/community.git/tree/trunk/PKGBUILD?h=packages/telegram-desktop#n63

**Comment by vn971** [comment]
UPD: edited answer above.

**Comment by vn971** [comment]
(It is not compiled by me, but rather the Arch-s package is taken.)

**Comment by loscsol** [comment]
Same problem here and I found that solution in #4298 works in ArchLinux too

**Comment by vn971** [comment]
@loscsol that's not really a solution, is it? It's similar to saying "hey, download our APK files from here" instead of relying on Play Store. The version compiled from source should work. Lack of this promise also drives (or will drive) contributors away. If only a binary downloaded from a web site but not the source work, how can you ever trust it or fix anything?

**Comment by john-preston** [comment]
@vn971 Well, if the binary from site works and the version built by maintainers doesn't then the bug report should be addressed to maintainers. How the version from site is built is described in the build instructions.

**Comment by Johnnynator** [comment]
The Arch bug ticket: https://bugs.archlinux.org/task/65080?project=5&string=telegram-desktop

**Comment by vn971** [comment]
I'll close it for now since it seems Arch-specific at the moment.

Thanks a lot for the reference @Johnnynator , my bad in not finding it there (I did look up issues on this repo before posting though).

**Comment by vn971** [comment]
Fixed the issue locally by installing `libappindicator-gtk3` (without it, telegram crashes). Arch will soon make it a hard dependency, so that should fix it for other Arch users as well.

I'm not sure why TG crashes without the dependency though. Does it link against it, or is some "feature checking" code written not properly? That question is off-topic though, I'm just casually curious if there's something to fix on telegram-desktop side here.
