### ISSUE TITLE
my channel banned can you help my ?

### ISSUE THREAD

**Issue by zetatechi** [telegramdesktop/tdesktop#7048]
I had a channel with 80K members for 4 years. Telegram has banned it without a single warning. It's not fair because we didn't do anything wrong during these 4 years.

which is not related to terrorism, not related to sex , not related to spam! not related to child porn , not related to Annoyance for the telegram

![image](https://user-images.githubusercontent.com/60185719/72903220-1b194c00-3d42-11ea-890d-50bc9350a2e2.png)

**Comment by Aokromes** [comment]
this doesn't belong to telegram desktop instead to twiteer or ask a question in client.

**Comment by Aokromes** [comment]
and i am sure we told you multiple times on https://t.me/tgbetachat
