### ISSUE TITLE
1.9.6 Active group chat keeps you online even if you are AFK 

### ISSUE THREAD

**Issue by imashxtyz** [telegramdesktop/tdesktop#7049]
Few versions before if you would open any group chat and do nothing(e.g. no keyboard/mouse activity) you would become offline after few seconds. Right now it keeps you online and the chat keeps scrolling, which is annoying, because you have to scroll up after you're back.

**Comment by john-preston** [comment]
@imashxtyz What OS?

**Comment by imashxtyz** [comment]
@john-preston Windows 7 x64

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/4664
