### ISSUE TITLE
No System Stray Icon in Manjaro 0.8.12 with XFCE 4

### ISSUE THREAD

**Issue by s0me-1** [telegramdesktop/tdesktop#705]
With telegram-desktop v 0.8.11 build with Pamac from AUR repositories, tough it's working with KDE4

So no notifications in XFCE...

EDIT: Also, what is the command to start telegram minimized ?

**Comment by farukuzun** [comment]
+1
Relevant: 3102ca1133ab072c089ba7c765f914bed7e13a4e
I hope @telegramdesktop will fix it soon.

**Comment by auchri** [comment]
Is this still the case? If yes, reopen the issue
