### ISSUE TITLE
v 1.9.6 deployment artifacts/assets missing

### ISSUE THREAD

**Issue by henning-schild** [telegramdesktop/tdesktop#7051]
### Steps to reproduce
1. go to https://github.com/telegramdesktop/tdesktop/releases
2. look for i.e "Linux 64 bit: Binary" in assets
3. the previous releases have it, missing on the most recent one

### Expected behaviour
That asset should show up at some point after the release

### Actual behaviour
asset still not there after 21h

### Configuration
**Operating system:**
Linux

**Version of Telegram Desktop:**
1.9.6

**Used theme**:

<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by henning-schild** [comment]
Maybe the CI/CD pipeline got stuck, or running out of space etc. Or did the deploy location/mechanism change? If so where can i find the new asset?

**Comment by john-preston** [comment]
@henning-schild 1.9.6 fixes only one Windows-only crash in 1.9.5, so it was not built for any other platform.

**Comment by henning-schild** [comment]
Would be nice if the changelog said so. Thanks!
