### ISSUE TITLE
Mouseover update issue

### ISSUE THREAD

**Issue by mortiest** [telegramdesktop/tdesktop#7053]
What I'm about to report has only started to happen a couple updates ago, can't really precise when, but only now this have bothered me enough to take the time and report it. Perhaps it's not a bug but a feature.

So, when I have telegram opened on another screen, and my contacts are coming online and offline, they don't always update, so I can have a contact look like this for a long time:
![image](https://user-images.githubusercontent.com/41268340/72940610-10bd7900-3d67-11ea-9f00-0b213e940521.png)
Even with telegram focused again, I'm required to mouseover each contact to see the real deal.
![image](https://user-images.githubusercontent.com/41268340/72940769-58440500-3d67-11ea-8409-b1fdedf982d6.png)

Any suggestions? Would love to get that updated in real time, don't mind the load, perhaps is some power saving option? Is it possible to tweak it?

Thanks

Windows 10.0.18363 Build 18363
Telegram Desktop Version 1.9.6

**Comment by MouamleH** [comment]
Telegram Desktop Version 2.1.6
the issue is still there.

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/6410
