### ISSUE TITLE
Crash when pasting large image from clipboard

### ISSUE THREAD

**Issue by Neurotoxin001** [telegramdesktop/tdesktop#7055]
### Steps to reproduce
1. just use printscreen and paste image in paint
2. increase size of image to 10000x5625
3. scroll some channels, for example I was scroll videos here https://t.me/rand2ch
![image](https://user-images.githubusercontent.com/39812401/72977397-8536fd00-3de5-11ea-8d9a-03c08bf02978.png)
4. then copy image from paint to clipboard and paste 2-4 times in your saved messages
5. crash.

Crash id: 7eb47e01-076a-4fd1-80b4-cbd1f3968986 and  802d3bd6-5baf-44f9-b9e6-0cef68cb6195

This was on older versions too, but I don't remember the crash report window after crash so I decided to test it now.

### Configuration
**Operating system:** win 10 ltsc 1809

**Version of Telegram Desktop:** 1.9.7

**Used theme**: dark default

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/6671

**Comment by ilya-fedin** [comment]
> #6671

This bug is about Windows, while you linked the linux one
I'm sure that they have different causes

**Comment by ilya-fedin** [comment]
> 2. increase size of image to 10000x5625

The cause of this issue is OOM I guess
Telegram on Windows has only 32-bit build that can't eat more than 4 GB RAM
However, such big image can eat more than 4 GB RAM
And you get crash

But the linked issue have the cause in Qt XCB backend, what is linux-specific.

However, I can't see point in pasting a 10000x5625 image

**Comment by Neurotoxin001** [comment]
Read the update:
https://github.com/telegramdesktop/tdesktop/issues/5730#issuecomment-640459262

It's crashes even at 1gb ram.

**Comment by ilya-fedin** [comment]
> BUT when I try to paste 5000x3879 image - I can do that 7 times, and sometimes when I do that fast, telegram can't clear used RAM in time and I got crash (at 800-1000MB of used RAM).

If you want to shoot yourself in the foot - you will.

**Comment by Neurotoxin001** [comment]
> If you want to shoot yourself in the foot - you will.

So you want to say that I can't copy and paste 4k photos in TDesktop "fast" and I must do it slowly or I get a crash? And it's not a "bug" but "feature"?

Btw another crash id ba8d0716-3671-49e5-8f22-ed67adeac85d
With 4k images examples from here https://unsplash.com/images/stock/4k

**Comment by ilya-fedin** [comment]
> It's crashes even at 1gb ram.

Looks like limit is not 4G but 2G: https://docs.microsoft.com/en-us/windows/win32/memory/virtual-address-space

> And it's not a "bug" but "feature"?

This is a consequence of the lack of a 64-bit build.

**Comment by Neurotoxin001** [comment]
> Looks like the limit is not 4G but 2G

But when I test these crashed I am looking at task manager and there is only 900mb-1gb, not even close to 2gb ram usage when crash appears.

**Comment by ilya-fedin** [comment]
> But when I test these crashes I am looking at task manager and there is only 900mb-1gb, not even close to 2gb ram usage when crash appears.

Your #7971 also states about 1G ram. I guess this is a limit in practice.

However, there are an unofficial 64-bit that you can test: https://github.com/TDesktop-x64/tdesktop/releases

**Comment by Neurotoxin001** [comment]
> However, there are an unofficial 64-bit that you can test

Thanks! But is it safe to use?

**Comment by ilya-fedin** [comment]
> But is it safe to use?

I don't know

**Comment by ilya-fedin** [comment]
> It's crashes even at 1gb ram.

Make sure that you look for virtual memory and not physical memory. For example, `Commit` column in the resource monitor
https://filestore.community.support.microsoft.com/api/images/af9cd3c8-40b7-451c-aa1b-a99655f4b1a4

**Comment by Neurotoxin001** [comment]
Ok I tested that client and there is no crashes when pasting large images:
![image](https://user-images.githubusercontent.com/39812401/84081880-77c28e00-a9e7-11ea-9a05-f44886dc902e.png)

But it's strange that official client shows that I have 64bit windows, and this unofficial client shows 32bit. I have 64.

![image](https://user-images.githubusercontent.com/39812401/84081991-b3f5ee80-a9e7-11ea-99ef-b3e4cdcac444.png)

**Comment by ilya-fedin** [comment]
> But it's strange that official client shows that I have 64bit windows, and this unofficial client shows 32bit. I have 64.

The code that detects bitness checks for WOW64 (Win32 On Win64), but since the binary is 64-bit, it isn't used
https://github.com/TDesktop-x64/lib_base/blob/master/base/platform/win/base_info_win.cpp#L143

As you can see, they have custom Is64BitOS, but it is added to the OS version like a hack

The correct way to determine the architecture would be the same that used on linux now: https://github.com/TDesktop-x64/lib_base/blob/master/base/platform/linux/base_info_linux.cpp#L58

**Comment by Neurotoxin001** [comment]
2.4.3 still have this issue

new crash id d34b3033-ecde-4dbe-b8af-92b02bec409e

**Comment by Neurotoxin001** [comment]
Fixed in 2.5.7 64 bit
![image](https://user-images.githubusercontent.com/39812401/106188097-944e4900-61b7-11eb-904b-0a7026e974da.png)
