### ISSUE TITLE
Updater.exe is not accessible

### ISSUE THREAD

**Issue by jasonycw** [telegramdesktop/tdesktop#7056]
### Steps to reproduce
1. Click `Update`
2. Error pop up
3. Telegram can still launch properly

### Expected behaviour
No error pop up

### Actual behaviour
Error pop up
```
Failed to update Telegram :(
 C: Users/Jason Yu/AppData/roaming/Telegram Desktop/Telegram.exe is not accessible.
```

### Configuration
**Operating system:** Windows 10 1909

**Version of Telegram Desktop:** Currently **1.9.7**, has been happening since the last 4 versions

**Used theme**: None

<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

--------------

Also tried to download the installer and install, also get a similar error

```
C:\Users\Jason Yu\AppData\Roaming\Telegram Desktop\Updater.exe

An error occurred while trying to rename a file in the destination directory:

MoveFile failed; code 5.

Access is denied.

Click Retry to try again, Ignore to skip this file (not recommended), or Abort to cancel installation.
```
There is no **Updater.exe** under that location
![image](https://user-images.githubusercontent.com/4518597/72982571-55eeb300-3e1a-11ea-8c20-62180c343661.png)

**Comment by Aokromes** [comment]
can you try downloading https://github.com/telegramdesktop/tdesktop/releases/download/v1.9.7/tsetup.1.9.7.exe and check if update.exe is there for you after installing and then search for updates?

**Comment by jasonycw** [comment]
Yes, after I install with this `exe`, everything got reset and I need to login again.

But the `Updater.exe` is here now
![image](https://user-images.githubusercontent.com/4518597/73173894-66b46700-4141-11ea-94df-ffcc13b285f4.png)

**Comment by Aokromes** [comment]
but updater is there and works?

**Comment by jasonycw** [comment]
The `Updater.exe` is there after installing with the exe you provided, not sure if it is working
I double clicked it and it just open Telegram

Maybe need to wait until the next update?

**Comment by Aokromes** [comment]
you installed 1.9.7, check if you are using 1.9.7 or 1.9.8 :)

**Comment by jasonycw** [comment]
It is 1.9.8 right now, so it is working?

**Comment by Aokromes** [comment]
yes
