### ISSUE TITLE
[Feature Request] Work mode: Don't count unreaded messages in archived chats

### ISSUE THREAD

**Issue by KindDragon** [telegramdesktop/tdesktop#7057]
### Is your feature request related to a problem?
No

### Describe the solution you'd like
I would that unread message count for list item "Show all chats" exclude messages from archived chats

### Additional context
![image](https://user-images.githubusercontent.com/224272/72985024-1b731f00-3df6-11ea-9d6b-bcb08ae0dffd.png)

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/6314

**Comment by KindDragon** [comment]
It's not duplicate, my feature request about work mode

**Comment by Aokromes** [comment]
if it's implemented on normal mode you will have it on workmode.

**Comment by KindDragon** [comment]
But we can just change unread messages behavior just for workmode.
