### ISSUE TITLE
[Bug] Send button is not shown when sending a poll via @QuizBot button "Create a question"

### ISSUE THREAD

**Issue by 4nt0n10M4** [telegramdesktop/tdesktop#7058]
### Steps to reproduce
1. Go to [@QuizBot](https://t.me/QuizBot), and send `/newquiz`
2. Set a title for the quiz
3. Skip the description
4. Click on the button "`Create a question`"
![image](https://user-images.githubusercontent.com/29716718/72993403-9be55000-3df5-11ea-9db3-2b84b1c85c0a.png)
5. Then fill the inputs

### Expected behaviour
The send button will appear
### Actual behaviour
There's no send button
![image](https://user-images.githubusercontent.com/29716718/72993533-d9e27400-3df5-11ea-8151-a90674cc1e90.png)

### Configuration
**Operating system:** Windows 10

**Version of Telegram Desktop:** 1.9.7

**Used theme**: Night

**Comment by kirsan31** [comment]
You need to select right answer, cos it's quiz ;)
![image](https://user-images.githubusercontent.com/17767561/72994707-abba5f80-3e08-11ea-8381-6b41de781b5f.png)

**Comment by 4nt0n10M4** [comment]
Ooops sorry
