### ISSUE TITLE
[Question] Why did you remove the gif size?

### ISSUE THREAD

**Issue by sepehr-brj** [telegramdesktop/tdesktop#7061]
Is it possible to return it?

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/5803 same as this?

**Comment by Unkn9wn1** [comment]
i have this problem too... return it please

**Comment by Unkn9wn1** [comment]
Bump!

**Comment by 4a756e6f** [comment]
Gif size removed from version 1.9
Using 1.8.15  won't update till it come back

**Comment by sepehr-brj** [comment]
> #5803 same as this?

No

**Comment by sepehr-brj** [comment]
You hasn't replied to my question yet
If it was going to be fixed, it would have been fixed by now

**Comment by ilya-fedin** [comment]
> You hasn't replied to my question yet

Developers don't want to answer I guess
