### ISSUE TITLE
Sound in video disappears sometimes 

### ISSUE THREAD

**Issue by Neurotoxin001** [telegramdesktop/tdesktop#7063]
### Steps to reproduce
1. disable autoplay, clear telegram cache and relaunch the app
2. start watching some videos (I got this issue with this video 2 times https://t.me/rand2ch/12659 and 1 time with this https://t.me/rand2ch/12620)
3. don't touch playback-bar
4. sometimes, not always, sound will disappear on 2-3 second of video. but if you click on playback-bar to rewind - sound will back.

this is very old bug btw. there is some errors in logs also:
`[2020.01.24 09:54:35] Streaming Error: Error in avformat_open_input (code: -1094995529, text: Invalid data found when processing input).`
and
`[2020.01.24 09:55:11] Streaming Error: Error in avformat_open_input (code: -1, text: Operation not permitted).`
right after sound disappear.

### Configuration
**Operating system:** win 10 ltsc 1809

**Version of Telegram Desktop:** 1.9.7

**Used theme**: dark default

<details><summary><b>Logs</b>:</summary>

[log.txt](https://github.com/telegramdesktop/tdesktop/files/4107137/log.txt)

</details>

(If you want to know that is there this issue present without VoiceMeeter, I say - yes, this issue is present even with default windows 10 audio settings)

**Comment by Neurotoxin001** [comment]
Seems like 1.9.10 is fixed it, can't catch it anymore.

**Comment by Neurotoxin001** [comment]
Well I catch it again here:
https://t.me/mudak/35311

It's become much rare, but it's still happens. 1.9.12

**Comment by Neurotoxin001** [comment]
1.9.20 still have this but now without errors in log.

**Comment by Neurotoxin001** [comment]
1.9.22 same

**Comment by Neurotoxin001** [comment]
2.0.1 same :/

**Comment by Neurotoxin001** [comment]
Now it's just on every video…

**Comment by Aokromes** [comment]
well, since telegram desktop version is the same maybe it's something on your hardware or drivers.

**Comment by Neurotoxin001** [comment]
Maybe you right, disabled [Voicemeeter](https://www.vb-audio.com/Voicemeeter/) for now, will test it with default realtek drivers.

**Comment by reallyuniquename** [comment]
I experience the same issue and I doubt it's drivers or my hardware.

**Comment by Neurotoxin001** [comment]
Ok, got it now even with default realtek drivers, without Voicemeeter. So problem is in telegram, because all other apps is fine.

**Comment by Neurotoxin001** [comment]
2.1.6
this issue even with round videos.

**Comment by NatanielBR** [comment]
2.1.12 same.

In log file says:

...
[2020.06.20 09:07:39] App Info: writing encrypted user settings...
[2020.06.20 09:07:40] Audio Info: recreating audio device and reattaching the tracks
[2020.06.20 09:07:44] App Info: writing encrypted user settings...
[2020.06.20 09:08:11] Audio Info: Closing audio playback device.
**[2020.06.20 09:08:13] Streaming Error: Error in avformat_open_input (code: -1, text: Operation not permitted).**
[2020.06.20 09:08:13] Audio Info: recreating audio device and reattaching the tracks
[2020.06.20 09:08:21] Audio Info: Closing audio playback device.
**[2020.06.20 09:08:50] Streaming Error: Error in avformat_open_input (code: -1, text: Operation not permitted).**
[2020.06.20 09:08:51] Audio Info: recreating audio device and reattaching the tracks
[2020.06.20 09:08:51] Audio Info: Closing audio playback device.
[2020.06.20 09:08:52] Audio Info: recreating audio device and reattaching the tracks
...

I suppose that bold text is a bug related. 
My system info is:
OS: Windows 7 Ultimate
Telegram version: 2.1.12

**Comment by reallyuniquename** [comment]
While I experience the same issue I don't have `Streaming Error` in my logs or any audio related errors at all.

**Comment by Neurotoxin001** [comment]
Issue still here on 2.2 now again with errors

```
[2020.08.01 14:52:03] Audio Info: Closing audio playback device.
[2020.08.01 14:52:03] Streaming Error: Error in avformat_open_input (code: -1, text: Operation not permitted).
```

**Comment by reallyuniquename** [comment]
Still got it on 2.3.1.

**Comment by Neurotoxin001** [comment]
Didn't notice that for a long time, seems like it's been fixed

2.4.4

**Comment by Neurotoxin001** [comment]
Nope, it's still here, with same errors

`[2020.10.29 16:01:06] Streaming Error: Error in avformat_open_input (code: -1, text: Operation not permitted).`

**Comment by reallyuniquename** [comment]
Still a bug.

**Comment by Neurotoxin001** [comment]
2.8.1 still have it

**Comment by RememberTheAir** [comment]
This is weird because it happens the first time you open a video after launching the app, and then doesn't happen anymore

**Comment by Neurotoxin001** [comment]
`+`

**Comment by Neurotoxin001** [comment]
Still an issue

**Comment by reallyuniquename** [comment]
TDesktop 4.2. Not fixed.

**Comment by Disa-Kizonda** [comment]
Same

**Comment by Neurotoxin001** [comment]
Who have that problem do you have that options **enabled** in advanced settings?
![image](https://user-images.githubusercontent.com/39812401/204203541-de1622b7-ebfd-4855-a4fd-8567a8b70f4a.png)

I think they are the problem. But need more testing. After I turned them off, the sound stopped disappearing. On the other hand, the question arises what are these functions and what exactly they do, if they cause only problems (with sound and [flickering media](https://github.com/telegramdesktop/tdesktop/issues/17109))

If it can help I have Nvidia GeForce 1060 6GB and Intel i5 9600k

**Comment by Neurotoxin001** [comment]
Nope, still dissapears

**Comment by reallyuniquename** [comment]
Is there any chance you are on a slow internet connection and/or use proxy?

**Comment by Neurotoxin001** [comment]
No. Internet is fine.

**Comment by Neurotoxin001** [comment]
After these commits it's fixed for me:
https://github.com/telegramdesktop/tdesktop/commit/af95bd6fb74426f5783d61daefd011b0fd8e635c
https://github.com/telegramdesktop/tdesktop/commit/0880a83c2c7d06d20f2fb06ce020fac14cbee6d8

Need more testing from other people that have this bug.

**Comment by Neurotoxin001** [comment]
yes it's fixed
