### ISSUE TITLE
[Question] how to get libdrm.a

### ISSUE THREAD

**Issue by aiwujing1001** [telegramdesktop/tdesktop#7064]
Drop static libdrm library from libdrm-dev. *

![image](https://user-images.githubusercontent.com/46815850/73051261-4c6a5700-3ebd-11ea-9c0e-a990d57e5e91.png)

apt-get install will not have libdrm.a

**Comment by john-preston** [comment]
Either build it with the rest of the dependencies or maybe drop it from used ffmpeg build.

**Comment by psychosys** [comment]
```
sudo apt-get install libpciaccess-dev
git clone https://salsa.debian.org/xorg-team/lib/libdrm
cd libdrm
git checkout libdrm-2.4.95-1
./autogen.sh
./configure --enable-static
make
sudo make install
```

**Comment by Aokromes** [comment]
22b099429aa9368fe0339ee48bcf6dbcdd3ac8d5
