### ISSUE TITLE
High CPU usage when application is running with another user account

### ISSUE THREAD

**Issue by nre-ableton** [telegramdesktop/tdesktop#7065]
### Steps to reproduce
1. Start Telegram under a user account
2. Use the fast-user switching feature of macOS to switch to another user account
3. Wait a bit ...

### Expected behaviour
Telegram should be effectively paused in the background

### Actual behaviour
Telegram uses 100% CPU on one core

### Configuration
**Operating system:**
macOS Mojave 10.14.6

**Version of Telegram Desktop:**
1.9.7

**Used theme**:
Default

<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by Aokromes** [comment]
this issue is still valid?

**Comment by nre-ableton** [comment]
I wasn't able to reproduce the behavior just now with version 2.1.5, but I will reopen this issue if I encounter it again.
