### ISSUE TITLE
Always opens maximized on Ubuntu 19.04

### ISSUE THREAD

**Issue by coolemza** [telegramdesktop/tdesktop#7069]
### Steps to reproduce
1. Choose Open Telegram from top bar menu
![image](https://user-images.githubusercontent.com/9666579/73116858-fdc9c500-3f6f-11ea-9adf-e2ae676f39b4.png)

2. Telegram desktop window opens maximized

### Expected behaviour
Should be last size/position

### Actual behaviour
Always opens maximized

### Configuration
Ubuntu 19.04

**Version of Telegram Desktop:**
1.9.8
**Used theme**:
default

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/1380
