### ISSUE TITLE
Улучшенный просмотр истории

### ISSUE THREAD

**Issue by zaz600** [telegramdesktop/tdesktop#707]
Если у вас есть чаты с большим количеством человек и в этих чатах генерируется ~5к сообщений за 3 часа, то крайне неудобно обозревать историю с момента последнего прочитанного сообщения.
Пример.
Уходим спать в 02-00. Утром видим 5000 новых сообщений, которые оставили люди из других часовых поясов, например. Сидишь и листаешь вниз.
Для улучшения процесса анализа большого количества сообщений с момента последнего прочитанного, предлагаю:

1. Вверху окна, например, сделать фильтры для навигации по времени сообщений. Например, Перейти к (сегодня) 15:00, перейти к (вчера) 16:00, 18:30 и т.п. Если в заданное время не было сообщений. переходим к ближайшему. Также можно сделать фильтр: показать сообщения с ... по ... 
2. Вверху добавить фильтр навигации по хэштэгам открытого окна. Не глобальный поиск во всех открытых чатах, а просто список хештегов (начиная с заданного времени) с указанием времени сообщения в котором эти хештеги были указаны. Например, 
#политика 20:00 10.05.2015
#женщины 20:30 10.05.2015
При клике на хештег переходим в историю сообщений. Далее обозреваем о чем в это время шла речь.

**Comment by ezdev128** [comment]
@zaz600 Желательно бы это все описать на английском языке. Сообщество Telegram не только русскоязычное.

**Comment by zaz600** [comment]
@ezdev128 дерзайте)) сообщество - да. разрабы - нет

**Comment by ezdev128** [comment]
@zaz600 ну так зачем Вы пишете разрабам на русском языке, если они не русскоязычные? :-)

**Comment by zaz600** [comment]
сообщество - да, не всё русскоязычно. разрабы - нет, по большей мере русскоговорящие. Так яснее?:)
если согласны и можете перевести, сделайте, пожалуйста))

**Comment by ezdev128** [comment]
@zaz600 Вы явно переоцениваете мои скиллы в переводах :-)

@zaz600 suggests to extend the functionality of history:
1. Add timestamp links at the top of history, e.g. [ 'Today', 'Yesterday', '1 week', '1 month', '1 year', (least date of last message received) ]
2. Add hashtags cloud links, e,g., [ #girls, #politics, ... ]

**Comment by auchri** [comment]
English please
