### ISSUE TITLE
high DPI Windows 10 placing of main window Telegram desktop client

### ISSUE THREAD

**Issue by ryder203** [telegramdesktop/tdesktop#7070]
### Steps to reproduce
1. Set Windows 10 DPI scaling to 175% on 3840x2160 pixel
2. Set Telegram client scaling to 175% using Telegram.exe -scale 175
3. Restart Windows having Telegram desktop client in autostart / start minimized in tray

### Expected behaviour
After the Windows restart the Telegram client window should open (when clicking on the tray icon) where it had been (in my case right bottom corner of Windows Desktop)

### Actual behaviour
The client window is placed randomly anywhere on the desktop (when clicking on the tray icon after a restart of Windows 10)

### Configuration
**Operating system:**
Windows 10 64bit 1909
**Version of Telegram Desktop:**
1.9.8
**Used theme**:
default
<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/6804
