### ISSUE TITLE
Can't input Chinese when app scaled larger than 100% (e.g. 125%)

### ISSUE THREAD

**Issue by lekoOwO** [telegramdesktop/tdesktop#7072]
### Steps to reproduce
1. Update the app to 1.9.X on Windows.
2. Scale the app larger than 100% (for example, 125%)

### Expected behaviour
Input normally.

### Actual behaviour
Cannot input Chinese, stucks at English IME.
App keep crashes on startup since scaled and restarted once.
### Configuration
**Operating system:**
Windows 10 1909

**Version of Telegram Desktop:**
1.9.8
**Used theme**: default

<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)

[log.txt](https://github.com/telegramdesktop/tdesktop/files/4112026/log.txt)

Nothing special logged...
</details>

**Comment by Aokromes** [comment]
next time you have a crash, plz send crash and post crashid here.

**Comment by rexx0520** [comment]
> next time you have a crash, plz send crash and post crashid here.

It just crashes and terminating itself, even no crash window shows up

**Comment by rexx0520** [comment]
BTW, Telegram crashes periodly on 1.8.X (maybe hourly, not quite sure), but the scaling and input is normal.
No sure if it's related.

**Comment by Aokromes** [comment]
try enabling beta to see if you get the crash window.

**Comment by rexx0520** [comment]
> try enabling beta to see if you get the crash window.

edited https://github.com/telegramdesktop/tdesktop/issues/7072#issuecomment-578404196 for more precise description.

I'm enabling beta now.

**Comment by rexx0520** [comment]
> try enabling beta to see if you get the crash window.

Still no crash window

**Comment by Aokromes** [comment]
maybe you can contact https://t.me/preston for a debug build

**Comment by ilya-fedin** [comment]
Is this still valid?
