### ISSUE TITLE
Crash on clicking SEND/CANCEL button with left and right mouse buttons in same time in image uploading popup

### ISSUE THREAD

**Issue by kopoba** [telegramdesktop/tdesktop#7073]
### Steps to reproduce
1. open telegram
2. paste any image form buffer i used this one https://www.google.com/images/branding/googlelogo/2x/googlelogo_color_272x92dp.png
3. in appeared popup click and hold left mouse button on SEND or CANCEL and simultaneously click right mouse button
4. App crashed

### Expected behaviour

App don't crash and must show menu to schedule message

### Actual behaviour
App crashed

### Configuration
**Operating system:**
Windows 7 Maximum version 6.1 (build 7601:Service Pack 1)
**Version of Telegram Desktop:**
1.9.8 stable
**Used theme**:
Dark
<details><summary><b>Logs</b>:</summary>

[74342cc3-b71e-479e-9c78-9ec7e78cef8d.zip](https://github.com/telegramdesktop/tdesktop/files/4112157/74342cc3-b71e-479e-9c78-9ec7e78cef8d.zip)
[log.txt](https://github.com/telegramdesktop/tdesktop/files/4112161/log.txt)
</details>

Reproduced at least on one more independent users client.
If you need more information please point on it so i can provide it.

**Comment by Aokromes** [comment]
plz click send crash and put crash id here.

**Comment by kopoba** [comment]
> 
> 
> plz click send crash and put crash id here.

Sadly there is no such option app just disappears without suggestions to send crash report.
But at starting telegram i see window for a brief moment saying "Last time Telegram Desktop was not closed properly" Checking for updates...

**Comment by Aokromes** [comment]
cannot reproduce myself.

**Comment by kopoba** [comment]
> 
> 
> cannot reproduce myself.

Is there any place where telegram saves crash report? Or maybe there is some option to force telegram save crash report?

**Comment by Aokromes** [comment]
try enabling beta on settings and crash the client and look if it shows you send crash report and post id here.

**Comment by kopoba** [comment]
> 
> 
> try enabling beta on settings and crash the client and look if it shows you send crash report and post id here.

this works! But report cant be sended maybe because tg banned in russia. But was able to save report to file.
[KopobaCrash.zip](https://github.com/telegramdesktop/tdesktop/files/4114344/KopobaCrash.zip)

**Comment by Aokromes** [comment]
cool :) @john-preston

**Comment by kopoba** [comment]
I also was able to send report via proxy because tg don't want to start before you send report this makes me sad.

**Comment by Aokromes** [comment]
i think you can skip that deleting old crashes xd

**Comment by john-preston** [comment]
@kopoba There always should be a SKIP button at the bottom.

**Comment by kopoba** [comment]
> 
> 
> @kopoba There always should be a SKIP button at the bottom.

Yeh my bad Skip button looks like its disabled so i never try to hover it or click. Thanks for your help and patience
