### ISSUE TITLE
[Question] Can I read saved settings using an older app version?

### ISSUE THREAD

**Issue by Thoufak** [telegramdesktop/tdesktop#7074]
Hi. I would like to read the cached phone number from the tdata created in the newer version. Is that possible? I'm trying to get it from the localstorage.cpp at the line "case dbiLoggedPhoneNumber", but it appears to be an empty string. The tdata is valid and authorized (I can open it with a newer version).

Particular versions I tested with:
Old version – 1.9.3
New version – 1.9.7

**Comment by Thoufak** [comment]
I've found out that this is not possible. My next question is how difficult would it be to support reading settings of newer versions? Perhaps, there's some cryptographical/security issue which prevents this? Or is it more an artificial thing made in case there are some changes in the newer versions about saving/reading settings?

**Comment by john-preston** [comment]
@Thoufak Yes, each version writes the version number together with the data and old versions don't even try to read data from new versions, because data changes and there is no guarantee that anything correct will be read.

**Comment by Thoufak** [comment]
> @Thoufak Yes, each version writes the version number together with the data and old versions don't even try to read data from new versions, because data changes and there is no guarantee that anything correct will be read.

Thank you very much.
