### ISSUE TITLE
macOS version numbers of version 1.9.8 and 1.9.9 broken

### ISSUE THREAD

**Issue by core-code** [telegramdesktop/tdesktop#7075]
### Steps to reproduce
1. download version 1.9.8 for macOS here https://github.com/telegramdesktop/tdesktop/releases/download/v1.9.8/tsetup.1.9.8.dmg
2. extract the app and inspect its version number with QuickLook or ColumnView

### Expected behaviour
i expect to see version number 1.9.8 for version 1.9.8

### Actual behaviour
it claims to be version 1.9.7

### Configuration
macOS

**Version of Telegram Desktop:**
1.9.8

someone forgot to update the version number string for this release.
info: the bug is causes by faulty *CFBundleShortVersionString* and *CFBundleVersion* entries in your *Info.plist* file

<img width="353" alt="Screenshot 2020-01-25 at 20 19 49" src="https://user-images.githubusercontent.com/1261954/73126222-4acd8b80-3fb0-11ea-8afa-2a3f7e1f1ffa.png">

**Comment by core-code** [comment]
note 1:
this has happened previously, see here: https://github.com/telegramdesktop/tdesktop/issues/6610

note 2:
also from the last bug report, this has not been addressed yet:

> while you are at fixing bugs in your Info.plist, please remove the CFBundleGetInfoString entry from your Info.plist. this has been deprecated for more than 10 years (!) and actually makes it impossible to inspect the version number of the app using the 'Get Info' view, as mentioned above you have to us QuickLook or ColumnView.

cc @john-preston

**Comment by Aokromes** [comment]
the latest official version is 1.9.7 for macos, i suppose he used 1.9.8 on link because generation scripts.

**Comment by core-code** [comment]
version 1.9.9 is broken too. its version number is 1.9.8:
<img width="245" alt="Screenshot 2020-01-29 at 14 23 19" src="https://user-images.githubusercontent.com/1261954/73360325-f6255b80-42a2-11ea-8c70-863ae1db18f0.png">

**Comment by john-preston** [comment]
@core-code 😰 thanks.

**Comment by Aokromes** [comment]
this bug is still valid?

**Comment by core-code** [comment]
no, the current version 1.9.14 is fine and does not have broken version numbers.

however, given how often this has been broken in the past we can be fairly certain this will happen again unless some technical measures to prevent this are installed

**Comment by john-preston** [comment]
@core-code I think I've added a "rm Info.plist" step to the build script before xcodebuild-ing the app, so I hope it won't happen again.

The field in the Info.plist was not hardcoded, I don't know why xcode sometimes didn't re-generate it when version changed. But now it should, given that otherwise there is no Info.plist at all.

**Comment by core-code** [comment]
awesome, thanks!
