### ISSUE TITLE
Wrong link/chat/hashtag cursor on hover

### ISSUE THREAD

**Issue by DanyGee** [telegramdesktop/tdesktop#7081]
### Steps to reproduce
1. Launch app
2. Hover over a link/hashtag/chat

### Expected behaviour
Cursor should change it's shape from pointer to hand with pointy finger signalling a link

### Actual behaviour
Cursor changes to grab hand
![20200126_094438](https://user-images.githubusercontent.com/26818551/73132871-307fc600-4021-11ea-8c0c-f1f52380e9e8.jpg)

### Configuration
**Operating system:**
```
System:    Host: elementary-os Kernel: 5.3.0-26-generic x86_64 bits: 64 gcc: 7.4.0 Desktop: Gnome  (Gtk 3.22.30)
           Distro: elementary OS 5.1 Hera
Machine:   Device: desktop Mobo: ASUSTeK model: Z170-DELUXE v: Rev 1.xx serial: N/A
           UEFI: American Megatrends v: 3504 date: 06/29/2017
CPU:       Quad core Intel Core i7-6700K (-MT-MCP-) arch: Skylake-S rev.3 cache: 8192 KB
           flags: (lm nx sse sse2 sse3 sse4_1 sse4_2 ssse3 vmx) bmips: 31999
           clock speeds: max: 4300 MHz 1: 3448 MHz 2: 3909 MHz 3: 3768 MHz 4: 3546 MHz 5: 3127 MHz 6: 3863 MHz
           7: 3520 MHz 8: 3754 MHz
Graphics:  Card: NVIDIA GP104 [GeForce GTX 1080] bus-ID: 01:00.0
           Display Server: x11 (X.Org 1.20.5 ) driver: nvidia Resolution: 3840x2160@60.00hz
           OpenGL: renderer: GeForce GTX 1080/PCIe/SSE2 version: 4.6.0 NVIDIA 440.48.02 Direct Render: Yes
Audio:     Card-1 Intel 100 Series/C230 Series Family HD Audio Controller driver: snd_hda_intel bus-ID: 00:1f.3
           Card-2 NVIDIA GP104 High Definition Audio Controller driver: snd_hda_intel bus-ID: 01:00.1
           Sound: Advanced Linux Sound Architecture v: k5.3.0-26-generic
Network:   Card-1: Intel Ethernet Connection (2) I219-V driver: e1000e v: 3.2.6-k bus-ID: 00:1f.6
           IF: enp0s31f6 state: up speed: 1000 Mbps duplex: full mac: <filter>
           Card-2: Broadcom and subsidiaries BCM4360 802.11ac Wireless Network Adapter driver: wl bus-ID: 07:00.0
           IF: wlp7s0 state: down mac: <filter>
           Card-3: Intel I211 Gigabit Network Connection driver: igb v: 5.6.0-k port: c000 bus-ID: 0b:00.0
           IF: enp11s0 state: down mac: <filter>
Drives:    HDD Total Size: 2930.7GB (3.5% used)
           ID-1: /dev/nvme0n1 model: PCIe_SSD size: 120.0GB
           ID-2: /dev/sdb model: Samsung_SSD_850 size: 1024.2GB
           ID-3: /dev/sda model: Samsung_SSD_850 size: 256.1GB
           ID-4: /dev/sdc model: Crucial_CT1050MX size: 1050.2GB
           ID-5: /dev/sdd model: KINGSTON_SH100S3 size: 120.0GB
           ID-6: /dev/sde model: KINGSTON_SV300S3 size: 120.0GB
           ID-7: USB /dev/sdf model: SNA size: 240.1GB
Partition: ID-1: / size: 110G used: 97G (93%) fs: ext4 dev: /dev/sde1
RAID:      No RAID devices: /proc/mdstat, md_mod kernel module present
Sensors:   System Temperatures: cpu: 31.0C mobo: N/A gpu: 0.0:53C
           Fan Speeds (in rpm): cpu: 0
Info:      Processes: 277 Uptime: 5 min Memory: 2355.1/64257.8MB Init: systemd runlevel: 5 Gcc sys: 7.4.0
           Client: Shell (bash 4.4.201) inxi: 2.3.56 
```
**Version of Telegram Desktop:**
1.9.8

**Used theme**:
Default elementary OS theme.

**Other info**:
Happens **only** on eOS.
Not happening on Windows, Ubuntu, Deepin, PoP_OS and KDE Neon.

If you need more info - let me know.

**Comment by Aokromes** [comment]
afaik, not on chat lists.

**Comment by gorghino** [comment]
I confirm this problem on 1.9.9 and Elementary OS 5.1 Hera (GTK 3.22.30).
I get hand cursor on contact list on the left and also on stickers/gif into the chat.

**Comment by gorghino** [comment]
Still present in 1.9.14 version

**Comment by DanyGee** [comment]
:warning:  Still present in 1.9.16 beta

**Comment by DanyGee** [comment]
:warning: Still present in 1.9.18 beta

**Comment by gorghino** [comment]
Still present in 1.9.21

**Comment by Aokromes** [comment]
latest is 2.0.1

**Comment by gorghino** [comment]
Sorry @Aokromes , I've just updated.
Still present in 2.0.1 for everything is clickable (sticker/gif/url)

**Comment by a14219** [comment]
I'm experiencing a similar issue with Ubuntu 20.04 and Telegram v 2.1.
It's a pointing hand, but it's different from system's cursor. I only see this one in Telegram.

![cap](https://user-images.githubusercontent.com/64659987/80833021-06c0d700-8bee-11ea-971f-288fc2177cb0.png)

**Comment by DanyGee** [comment]
Seems like v2.1.1 fixes it :tada: 
Others, pls check.

**Comment by gorghino** [comment]
Confirmed on Elementary OS

**Comment by Aokromes** [comment]
> Confirmed on Elementary OS

confirmed fixed on 2.1.1 ?

**Comment by gorghino** [comment]
![image](https://user-images.githubusercontent.com/1898283/80870096-8d37f000-8ca4-11ea-9fef-ce57e1d80cdb.png)

Yes confirmed on 2.1.1 on Elementary OS 5.1.4 Hera
Linux 4.15.0-99-generic
GTK 3.22.30

**Comment by gorghino** [comment]
Yes, confirmed on Telegram 2.1.1

Elementary OS 5.1.4 Hera
Linux 4.15.0-99-generic
GTK 3.22.30

**Comment by darrist** [comment]
The same behaviour is happening on my Mac OS Big Sur, when a tiling manager is active (I use Rectangle) and controlled the window.
