### ISSUE TITLE
Old version in Ubuntu repository (1.2.17 while the most recent is 1.9.8 on telegram.org for linux)

### ISSUE THREAD

**Issue by halacs** [telegramdesktop/tdesktop#7082]
### Steps to reproduce
1.  Install an Ubuntu with Cinnamon UI then issue apt install telegram-desktop
2. Start telegram and check its version
3. You will see 1.2.17

### Expected behaviour
When someone sends a sticker, telegram shows that sticker as it happens on Android or on Windows.

### Actual behaviour
Sticker are not working. When someone sends a sticker, telegram shows a message I should upgrade and there is no sticker showed.

After issuing apt purge telegram-desktop and downloading telegram from telegram.org, now I have a much newer telegram - 1.9.8 - what supports stickers too.

apt repository should be updated or created another one like in case of syncthing.

### Configuration
**Operating system:**
istributor ID:	Ubuntu
Description:	Ubuntu 18.04.3 LTS
Release:	18.04
Codename:	bionic

cinnamon-session 3.6.1

**Version of Telegram Desktop:**
1.2.17

**Comment by john-preston** [comment]
@halacs I don't know, who maintains this apt repository, sorry.

**Comment by halacs** [comment]
@john-preston would it be possible to have an own repository maintained by developers of telegram?

**Comment by Aokromes** [comment]
https://packages.ubuntu.com/bionic/telegram-desktop

**Comment by halacs** [comment]
@Aokromes yes, you linked the package what I'm speaking about. It is not a rare thing that there is an old package. Based on your answer it is okay for the developers of telegram, while others like syncthing things it is worst to provide an own repository what is much easier to maintain as cooperating with debian's or ubuntu's team.

**Comment by Aokromes** [comment]
for that https://github.com/telegramdesktop/tdesktop/issues/2122

**Comment by halacs** [comment]
So what was the conclusion finally? Using flatpak and snap? Are they official and updated regularly? To be honest I love to use telegram but don't have enough time to understand all the details how things working under the hood even if I would like to do so. I highly appreciate your work with telegram!

**Comment by evgeniy-nikitin** [comment]
@halacs Perhaps you should download a suitable binary from https://github.com/telegramdesktop/tdesktop/releases and install it. It is better to remove the package from the repository as outdated.

**Comment by Aokromes** [comment]
or annoy distribution package maintainers xd

**Comment by halacs** [comment]
I did both. I found out the most recent version I need to have after installing binary release :)
I started to "annoy" distribution package maintainers too, but I though similar "custom" repository can work as in case of syncthing works very well.

**Comment by halacs** [comment]
Regarding the distribution repository: "Ubuntu is no rolling release. This means that package versions usually are not updated to higher versions than the one initially provided with a certain Ubuntu release."
https://answers.launchpad.net/ubuntu/+faq/3037

**Comment by Aokromes** [comment]
snap is now updated.

**Comment by halacs** [comment]
Thank you!
