### ISSUE TITLE
10 mentions after receiving 1 album in reply

### ISSUE THREAD

**Issue by aNNiMON** [telegramdesktop/tdesktop#7083]
### Steps to reproduce
1. Send a message in a group chat
2. Scroll up a bit to old messages (otherwise you will not receive @ mention)
3. Let someone respond to your message with an album of 10 photos

### Expected behaviour
You should receive 1 mention 

### Actual behaviour
You receive:
1 desktop notification with text "Album"
10 mentions
![MINDBLOWING](https://user-images.githubusercontent.com/1321838/73137821-f3d5be00-4064-11ea-90ed-b8f628665692.png)
10 entries in search by replies
![OMG](https://user-images.githubusercontent.com/1321838/73138224-0a7e1400-4069-11ea-8c41-e688c35f99fd.png)

### Configuration
**Operating system:** Arch Linux, Windows 7

**Version of Telegram Desktop:** 1.9.8

**Used theme**: any

**Comment by aNNiMON** [comment]
Same behavior on Android clients, but I think it's still an issue. It might be worth converting this to the generic issue for rethinking albums handling.

**Comment by john-preston** [comment]
@aNNiMON This is the way albums work - it is several separate messages really. The server counts them separate in mentions, sorry.
