### ISSUE TITLE
[Bug] Service account id 777000 showing inline keyboard in forwarded message from channel to attached group

### ISSUE THREAD

**Issue by On1x** [telegramdesktop/tdesktop#7084]
### Steps to reproduce
1. Attach group to channel
2. Add bot as administrator to channel
3. Write message in channel
4. Add inline keyboard by bot to new channel post

### Expected behaviour
When channel owner post a message it forwarded to attached group by service account with id 777000 without inline keyboard. After message edit by bot (method `editMessageReplyMarkup`), forwarded message in group edited by service account with id 777000 without inline keyboard.

### Actual behaviour
When channel owner post a message it forwarded to attached group by service account with id 777000 without inline keyboard. But after message edit by bot (method `editMessageReplyMarkup`), forwarded message in group edited by service account with id 777000 now with inline keyboard.

### Configuration
**Operating system:** Windows 10

**Version of Telegram Desktop:** 1.9.8

**Used theme**: Default

**Comment by On1x** [comment]
Seems it service account bug - it's ignore inline keyboard when channel message created, but not ignore when it updated. Inline keyboard cant work in group anyway, bot catch updates only from channel (even if it is added to the group).

**Comment by On1x** [comment]
Any updates? It's very annoying user experience. User press the button in message in group chat, witch he didn't must see it at all and got no callback! Please, share any news

**Comment by On1x** [comment]
Suggestion — maybe it issue can be resolved by telegram server team? I'm think that 777000 is service account and work on back end, not client side?

**Comment by On1x** [comment]
Problem was NOT SOLVED.

**Comment by john-preston** [comment]
@On1x I was told it should've been fixed in August. Are you sure it is still happening?

**Comment by On1x** [comment]
SOLVED
