### ISSUE TITLE
[Question] 2-factor authentication on the telegram?

### ISSUE THREAD

**Issue by VaGNaroK** [telegramdesktop/tdesktop#7088]
hello, I am a regular user of the telegram and I would like to know if someday they intend to add another form of authentication outside the ones already existing in the telegram, I access several services with a password and use google authenticator to use these accounts, could they in the future be able to add this form of authentication more to further improve security?

**Comment by wuniversales** [comment]
No, please, I'm tired of so many passwords

**Comment by RememberTheAir** [comment]
@wuniversales he's not suggesting another password, he's suggesting an alternative to the only 2FA solution Telegram offers (that is, the 2FA the password)

**Comment by damnfella** [comment]
This should be asked to Twitter's @telegram 

Only those people (marketing team) will be able to answer this question.
