### ISSUE TITLE
Menubar icon not dimming on non-active desktop in dark mode -- Mac OS X

### ISSUE THREAD

**Issue by Infiniwild** [telegramdesktop/tdesktop#7089]
### Steps to reproduce
1. Enable *Dark Appearance* system-wide
2. Have Telegram *Show tray icon* checked under Preferences -> Advanced -> System integration

### Expected behaviour
Telegram icon in system tray should dim on non-active screen.

### Actual behaviour
Telegram icon stays 'lit' on non-active screen.

<img width="425" alt="Screen Shot 2020-01-27 at 7 57 53 AM" src="https://user-images.githubusercontent.com/11062580/73187001-eb6d9980-40dd-11ea-91dc-44f42bb397d2.png">

### Configuration
**Operating system:**
Mac OS X (10.15 Catalina)
2nd display (extended desktop)

**Version of Telegram Desktop:**
1.9.8

**Used theme**:
Day (same behaviour in other themes)

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/4271 ?

**Comment by Infiniwild** [comment]
You're right, what I'm seeing is the same as #4271 . My search didn't come up with that, guess I missed the right terms to find it.
