### ISSUE TITLE
[Feature Request] Press tab key to complete username in group chat.

### ISSUE THREAD

**Issue by them3gabyte** [telegramdesktop/tdesktop#709]
Hello,

IS it possible to implement this feature in Telegram group chat? When we type '@' there is a list of all the members in the group, if we know only the first letters we press tab and it auto completes it until it has a conflict just like in UNIX Shell we use tab to complete directories and commands.
Similar feature can also be seen in IRC chats.

**Comment by nebulade** [comment]
Duplicate of #642
