### ISSUE TITLE
Building without spellchecking fails

### ISSUE THREAD

**Issue by Streetwalrus** [telegramdesktop/tdesktop#7090]
Building without spellchecking fails with the following:

```
/usr/bin/ld: Telegram/liblib_tgvoip.a(AudioInputALSA.cpp.o): undefined reference to symbol 'dlclose@@GLIBC_2.2.5'
/usr/bin/ld: /usr/lib/gcc/x86_64-pc-linux-gnu/9.2.0/../../../../lib/libdl.so: error adding symbols: DSO missing from command line
```

A workaround is adding `-Wl,,--copy-dt-needed-entries` to the linker flags, but I don't think I should have to do this at all. I've inspected the cmakelists for the spellchecking library but there isn't really anything interesting there.

Full build script: https://gist.github.com/Streetwalrus/21de36687227051aa6ef49b5dfe16950

**Comment by Streetwalrus** [comment]
I can't even reopen this?

**Comment by Aokromes** [comment]
post the hash of the code you are using to avoid to be closed xd

**Comment by Streetwalrus** [comment]
Thanks. This is for 1.9.8 on Arch Linux, all the relevant details are in the linked build script.

**Comment by Aokromes** [comment]
i mean ie https://github.com/telegramdesktop/tdesktop/commit/327c9caed75c0cb420fd3a0c87c0316c4e1f615a

**Comment by Aokromes** [comment]
anyway https://github.com/telegramdesktop/tdesktop/issues/7042

**Comment by Streetwalrus** [comment]
No that's not the same issue at all. My script is based on the official Arch package, which uses system-provided openal and does not use breakpad/crash reporting.

**Comment by Aokromes** [comment]
maybe some include missing then?

**Comment by Streetwalrus** [comment]
I forgot to mention that building with spellchecking enabled works just fine. I'm trying to figure out what the difference is. It's not a missing include because it's linking that fails.

**Comment by Aokromes** [comment]
> I forgot to mention that building with spellchecking enabled works just fine. I'm trying to figure out what the difference is. It's not a missing include because it's linking that fails.

I have seen such things on another project where i am and the fail on linking was that, missing include.

**Comment by Streetwalrus** [comment]
It looks like the problem is that `-ldl` needs to be passed to the compiler after `Telegram/liblib_tgvoip.a`, but the generated ninja file puts it first. Apparently, [order does matter](https://stackoverflow.com/a/55086637). For some reason compiling with spellchecking, this isn't a problem. The only difference in the linking command is the four objects it adds. I don't really know what else to add.

**Comment by Aokromes** [comment]
yeah, on non-pch builds include order matter.

**Comment by Streetwalrus** [comment]
WTH does PCH have to do with this?

**Comment by Aokromes** [comment]
it was informative text.

**Comment by ilya-fedin** [comment]
I can't reproduce with [Nix](https://nixos.org/nix/) and the following cake flags:
```
  cmakeFlags = [
    "-DTDESKTOP_API_TEST=ON"
    "-DDESKTOP_APP_USE_PACKAGED_RLOTTIE=OFF"
    "-DTDESKTOP_USE_PACKAGED_TGVOIP=OFF"
    "-DDESKTOP_APP_DISABLE_SPELLCHECK=ON"
    "-DTDESKTOP_DISABLE_GTK_INTEGRATION=ON"
  ];
```

**Comment by Aokromes** [comment]
@Streetwalrus try the suggested fix and if works close ticket :)

**Comment by Streetwalrus** [comment]
That's not a "suggested fix". They're using an entirely different distro which is known to have a funky linker setup, and a different set of options as well which I don't want to use. One big difference I can see is they're not disabling the glibc wrappers which might explain why it's not failing for them.

You know what though? I'm gonna close this bug, because it's impossible to get anything fixed in tdesktop anyway (which is why I'm patching the damn thing in the first place). The hack works, so I don't care.

**Comment by ilya-fedin** [comment]
> they're not disabling the glibc wrappers

they disabled by default, your list of configure options is almost set to default values.

**Comment by Streetwalrus** [comment]
Fair enough. I didn't write that script, I just took the one from my distribution and modified it to my liking.

**Comment by ilya-fedin** [comment]
Can you try on 1.9.19?
