### ISSUE TITLE
Win10_x64-preparation: Stuck at jom/configure.bat [Question] 

### ISSUE THREAD

**Issue by moonbaseDelta** [telegramdesktop/tdesktop#7094]
All steps through _x86 Native Tools Command Prompt for VS 2019.bat_ seems to be fine, yet at the "jom install" I get a number of "Ошибка в синтаксисе команды." ('error at command syntax') and then the [step](https://github.com/telegramdesktop/tdesktop/blob/dev/docs/building-msvc.md#build-the-project) I get:

```
Warn about uninitialized values.
Version: 1.9.8
CMake Error at %BuildPath%/Libraries/Qt-5.12.5/lib/cmake/Qt5Core/Qt5CoreConfig.cmake:15 (message):
  The imported target "Qt5::Core" references the file
     "%BuildPath%/Libraries/Qt-5.12.5/lib/Qt5Core.lib"
  but this file does not exist.  Possible reasons include:

  * The file was deleted, renamed, or moved to another location.
  * An install or uninstall procedure did not complete successfully.
  * The installation package was faulty and contained
     "%BuildPath%/Libraries/Qt-5.12.5/lib/cmake/Qt5Core/Qt5CoreConfig.cmake"
  but not all the files it references.

Call Stack (most recent call first):
  %BuildPath%/Libraries/Qt-5.12.5/lib/cmake/Qt5Core/Qt5CoreConfig.cmake:31 (_qt5_Core_check_file_exists)
  %BuildPath%/Libraries/Qt-5.12.5/lib/cmake/Qt5Core/Qt5CoreConfig.cmake:157 (_populate_Core_target_properties)
  %BuildPath%/Libraries/Qt-5.12.5/lib/cmake/Qt5/Qt5Config.cmake:28 (find_package)
  cmake/external/qt/package.cmake:23 (find_package)
  CMakeLists.txt:34 (include) 

-- Configuring incomplete, errors occurred!
See also "%BuildPath%/tdesktop/out/CMakeFiles/CMakeOutput.log"
```

I've already tried to reemerge the Qt, also with diffrent version (5.15) - the problem stays. Right now I have no clue what to do with that.

**Comment by moonbaseDelta** [comment]
I'm still there, the problem is the Qt build. I took built version from there https://github.com/telegramdesktop/dependencies_windows and it let me run Debug version on VS2019. Yet, the Release depends on full set of Qt libs while in the repo was not any "qwebp.lib" file.

**Comment by robinfoxnan** [comment]
QT build step , i meet somethint with openssl , 
at last, i download all zip from qt website,
compile them with no patch, then ok,

but  today, i try to 
configure.bat -D TDESKTOP_API_ID=17349 -D TDESKTOP_API_HASH=344583e45741c457fe1862106095a5eb -D DESKTOP_APP_USE_PACKAGED=OFF

i meet errors like this:
CMake Error at D:/TBuild/ThirdParty/cmake/share/cmake-3.17/Modules/FindPackageHandleStandardArgs.cmake:164 (message):
  Could NOT find Python (missing: Python_EXECUTABLE Interpreter)

**Comment by moonbaseDelta** [comment]
Well, it was the path to the build folder all along! 
Some folders contained '_', '+', and '-'. For some reasons jom script is not at all prepared for that scenario. 

One cannot change all Qt-sources and jom-scripts so the only way with that kind of problem - move build directory to some location with simple name (and probably shot).

I suggest that it should be mention in docs.
