### ISSUE TITLE
Telegram Is Constantly Crash, Its Use Unviable [ Open ]

### ISSUE THREAD

**Issue by LWFlouisa** [telegramdesktop/tdesktop#7095]
### Steps to reproduce
1. Open up Telegraam
2. Retype the message you were going to send.
3. Telegram crashes.

### Expected behaviour
Crashes are what should not be happening. This has been happening daily now. Other chatrooms I use do not have this problem.

### Actual behaviour
Crashes, as in completely shuts down instantly.

### Configuration
Linux Mint 19.1

Hard to tell, updates are automatic.

**Used theme**:
Night mode

No logs.

**Comment by LWFlouisa** [comment]
Now I haven't, I explicitely said Linux Mint 19.1 Please go troll elsewhere.

**Comment by Aokromes** [comment]
it's one bot, you failed to supply telegram desktop version and because that it closed the issue (mistakenly labeling it as macos).
i suggest you if you get a send crash window click on it and post crash id here.
if you don't get crash window plz run telegram desktop with gdb and post report here.

**Comment by john-preston** [comment]
Please launch Telegram, open Settings, Advanced and switch on "Install beta versions".

Then go to the chat that crashes and reproduce the crash.

Then relaunch the app, it should ask you to send a crash report.

Please send the report and post the "crash report tag" here.

**Comment by iniOr** [comment]
Same issue here.

Linux mint 19.3 x64, nothing in the log located on /home/$user/.local/share/TelegramDesktop/log.txt

Restarted with beta enabled and can't reproduce crash.

Will post crash report if I can reproduce it.

**Comment by Aokromes** [comment]
cannot crash myself with official telegram desktop (not telegram-desktop from linux distribution) https://i.imgur.com/TRm8nR4.png

**Comment by iniOr** [comment]
I confirm that I experience crashes since days when opening the app.
dpkg -l |grep telegram
ii  telegram-desktop                                                 1.2.17-1                                                    amd64        official telegram messaging app

**Comment by Aokromes** [comment]
1.2.17? that's extreme old, i suggest you to download official version from https://desktop.telegram.org/

**Comment by iniOr** [comment]
dpkg -l |grep telegram
ii telegram-desktop 1.2.17-1 amd64 **official telegram messaging app** -> why confuse users with two totally different apps that both claims being **official** ?

I figured that I had both versions (telegram-desktop package AND "official") installed and apparently I was using the "official" version when the crash happened.

Now changed build to beta and waiting for the crash to happen again, also what a ridiculous decision to rewrite the log at each launch it really help debugging for sure.

**Comment by Aokromes** [comment]
> dpkg -l |grep telegram
> ii telegram-desktop 1.2.17-1 amd64 **official telegram messaging app** -> why confuse users with two totally different apps that both claims being **official** ?
> 
> I figured that I had both versions (telegram-desktop package AND "official") installed and apparently I was using the "official" version when the crash happened.

Linux distributions maintains their packages on "special" ways (because that they have 1.2.17(-1) thing

https://launchpad.net/ubuntu/+source/telegram-desktop

**Comment by aaruni96** [comment]
I have been having this issue as well, for almost a month now.

Attaching my crash report. (Appears to be some kind of a segmentation fault)

Telegram version 1.9.8, on PopOS based on Ubuntu 19.10

[report.telegramcrash.txt](https://github.com/telegramdesktop/tdesktop/files/4121859/report.telegramcrash.txt)

**Comment by Aokromes** [comment]
your maybe it's related to https://github.com/telegramdesktop/tdesktop/issues/7086

**Comment by aaruni96** [comment]
I don't write in Hebrew, just plain old english. But I see libenchant_aspell in the crash log. 

Do you know how I disable that for a program ?

**Comment by Aokromes** [comment]
you can disable spellcheck on telegram settings.

**Comment by iniOr** [comment]
Got the latest update, opened Telegram started typing -> crash.

Nothing in the logs.

**Comment by Aokromes** [comment]
plz try to run it under gdb or valgrind.

**Comment by iniOr** [comment]
Can you explain me how to proceed to run it under gdb or valgrind ?

Since yesterday I disabled the spellchecker and no more crash.

**Comment by Aokromes** [comment]
gdb ./Telegram

or

valgrind --tool=memcheck --leak-check=full --log-file=valgrind.log ./Telegram

**Comment by iniOr** [comment]
Started Telegram since 4 hours with valgrind, enabled spellchecker but can't reproduce crash.

Here a link to valgrind log : https://cloud.octarine.io/s/s6LkSdbBTZrTQ8F/download

Let me know if I can do more to track this issue

**Comment by philipzae** [comment]
This has been happening to me as well for a while and i thought new version updates would solve it but unfortunately not and I'm on Linux Mint 19.3.

Here are gdb crash for various versions.
**Telegram 1.9.4**
```
Thread 6 "Thread (pooled)" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffdbf03700 (LWP 5691)]
0x00007fff99fd8e30 in void std::vector<acommon::FilterChar, std::allocator<acommon::FilterChar> >::_M_realloc_insert<acommon::FilterChar const&>(__gnu_cxx::__normal_iterator<acommon::FilterChar*, std::vector<acommon::FilterChar, std::allocator<acommon::FilterChar> > >, acommon::FilterChar const&) ()
   from /usr/lib/x86_64-linux-gnu/libaspell.so.15
```

**Telegram 1.9.9**
```
Thread 5 "Thread (pooled)" received signal SIGABRT, Aborted.
[Switching to Thread 0x7fffdc7a7700 (LWP 6495)]
__GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
51	../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
```

**Comment by john-preston** [comment]
@philipzae Please disable spellcheck in Settings > Advanced :( I hope it will stop crashing when moved to another spell check engine.

**Comment by Aokromes** [comment]
@philipzae plz on the 2nd use bt then bt full

**Comment by philipzae** [comment]
@john-preston yes disabling spell check on 1.9.9 seems to have stopped the crashing but i've downgraded to 1.9.3 and no crashing with spellchecking on. :D

@Aokromes here you go. 
[crash report.txt](https://github.com/telegramdesktop/tdesktop/files/4138006/crash.report.txt)

**Comment by ronlaws86** [comment]
[New Thread 0x7fffa59c3700 (LWP 5820)]
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x7fff98003e40] Protocol name not provided, cannot determine if input is local or a network protocol, buffers and access patterns cannot be configured optimally without knowing the protocol

Thread 13 "Thread (pooled)" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffbf7fe700 (LWP 5810)]
0x00007fff9db66e2d in void std::vector<acommon::FilterChar, std::allocator<acommon::FilterChar> >::_M_realloc_insert<acommon::FilterChar const&>(__gnu_cxx::__normal_iterator<acommon::FilterChar*, std::vector<acommon::FilterChar, std::allocator<acommon::FilterChar> > >, acommon::FilterChar const&) ()
   from /usr/lib/x86_64-linux-gnu/libaspell.so.15
(gdb) 

Steps to re-produce reliably on 1.9.9 

- Open telegram with spellcheck on. 
- Open any chat
- Type a bunch of gibberish 
- observe telegram imploding.

**Comment by cy6erlion** [comment]
Hi, thank you for Telegram Desktop,

I also am experiencing crashes but I don't know what is causing them, my systems info:

```bash
 $ uname -a
Linux cy6erlion 4.10.0-38-generic #42~16.04.1-Ubuntu SMP Tue Oct 10 16:32:20 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```

But I have noticed that it crashes occasionally when I try to type something and once I restart it after a crash it crashes again this can happen for 3 restarts then everything works normally again.

**Comment by PeterMX** [comment]
> [New Thread 0x7fffa59c3700 (LWP 5820)]
> [mov,mp4,m4a,3gp,3g2,mj2 @ 0x7fff98003e40] Protocol name not provided, cannot determine if input is local or a network protocol, buffers and access patterns cannot be configured optimally without knowing the protocol
> 
> Thread 13 "Thread (pooled)" received signal SIGSEGV, Segmentation fault.
> [Switching to Thread 0x7fffbf7fe700 (LWP 5810)]
> 0x00007fff9db66e2d in void std::vector<acommon::FilterChar, std::allocatoracommon::FilterChar >::_M_realloc_insert<acommon::FilterChar const&>(__gnu_cxx::__normal_iterator<acommon::FilterChar*, std::vector<acommon::FilterChar, std::allocatoracommon::FilterChar > >, acommon::FilterChar const&) ()
> from /usr/lib/x86_64-linux-gnu/libaspell.so.15
> (gdb)
> 
> Steps to re-produce reliably on 1.9.9
> 
> * Open telegram with spellcheck on.
> * Open any chat
> * Type a bunch of gibberish
> * observe telegram imploding.
> 
> ![image](https://user-images.githubusercontent.com/11991709/73607256-ad73e800-45ab-11ea-9ee8-97b3db297303.png)

I also have same issue in Telegram 1.9.10 beta, but here it crash only if I start typing at the same time I opened a chat, if I wait some seconds to start typing it will NO crash.
when it crash:
Thread 9 "Thread (pooled)" received signal SIGSEGV, Segmentation fault.
[Cambiando a Thread 0x7fffe542d700 (LWP 20805)]
0x00007fffba206616 in void std::vector<acommon::FilterChar, std::allocator<acommon::FilterChar> >::_M_realloc_insert<acommon::FilterChar const&>(__gnu_cxx::__normal_iterator<acommon::FilterChar*, std::vector<acommon::FilterChar, std::allocator<acommon::FilterChar> > >, acommon::FilterChar const&) ()
   from /lib/x86_64-linux-gnu/libaspell.so.15

**Comment by hadbabits** [comment]
Just popped in to say I'm having this issue too on Linux; on my laptop and desktop. 

Linux Mint 19.1 Cinnamon
Kernel: 5.0.0-25

Telegram Version 1.9.9

I'll try the beta version and check back.

**Comment by hadbabits** [comment]
Just popped in to say I'm having this issue too on Linux; on my laptop and desktop. 

Linux Mint 19.1 Cinnamon
Kernel: 5.0.0-25

Telegram Version 1.9.9

I'll try the beta version and check back.

Edit: So I tried 1.9.10 and so far it hasn't occurred again. I tried restarting my computer and opening chats and typing as quickly as possible, but haven't gotten it to crash yet. I'll post again if it happens.

**Comment by Gliscor** [comment]
I'm also experiencing crashes on my TG Desktop 1.9.10 (also on 1.9.9 and portable version too), Windows 7 Home Premium x64, only happens when i click discuss in a particular channel and start scrolling up and up until the crash happens. 

Crash Report ID: 4d21e372-df11-44ed-a8c4-d3cffbf2978a
Log: see attached file
[log.txt](https://github.com/telegramdesktop/tdesktop/files/4175631/log.txt)

**Comment by C-Bouthoorn** [comment]
FWIW, I can reproduce it by opening telegram and quickly typing some text with capital letter in any type of chat very fast after opening Telegram.

Here's my stacktrace:
```gdb
Thread 10 "Thread (pooled)" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffd67fc700 (LWP 13984)]
0x00007ffff4638f2e in malloc () from /usr/lib/libc.so.6
(gdb) bt
#0  0x00007ffff4638f2e in malloc () at /usr/lib/libc.so.6
#1  0x00007ffff040765e in  () at /usr/lib/libglib-2.0.so.0
#2  0x00007ffff04080fe in g_ucs4_to_utf8 () at /usr/lib/libglib-2.0.so.0
#3  0x00007ffff04081d6 in g_utf8_normalize () at /usr/lib/libglib-2.0.so.0
#4  0x00007fffd404a333 in  () at /usr/lib/libenchant-2.so.2
#5  0x00007fffd404b28c in  () at /usr/lib/libenchant-2.so.2
#6  0x00007fffd404b584 in enchant_pwl_check () at /usr/lib/libenchant-2.so.2
#7  0x00007fffd40471ab in  () at /usr/lib/libenchant-2.so.2
#8  0x00007fffd404800f in enchant_dict_check () at /usr/lib/libenchant-2.so.2
#9  0x0000555555952838 in  ()
#10 0x00005555559556df in  ()
#11 0x0000555555957479 in  ()
#12 0x000055555595759b in  ()
#13 0x0000555555953912 in  ()
#14 0x000055555595aaf6 in  ()
#15 0x00007ffff50291f2 in  () at /usr/lib/libQt5Core.so.5
#16 0x00007ffff5025fc6 in  () at /usr/lib/libQt5Core.so.5
#17 0x00007ffff7e2a4cf in start_thread () at /usr/lib/libpthread.so.0
#18 0x00007ffff46ad2d3 in clone () at /usr/lib/libc.so.6
```

The log.txt doesn't seem to contain any related information.

Version: `community/telegram-desktop 1.9.9-1`
Language: [Swedish](https://translations.telegram.org/sv/)

Disabling System Spell Checker seems to fix the issue.

Some more versions which may be relevant:
```
extra/aspell 0.60.8-1 [installed]
extra/aspell-nl 0.50.2-5 [installed]
extra/enchant 2.2.7-1 [installed]
extra/hunspell 1.7.0-2 [installed]
extra/hunspell-en_GB 2018.04.16-6 [installed]
community/aspell-sv 0.51-2 [installed]
community/hunspell-nl 2.10g-5 [installed]
```

Trying to test it on valgrind failed because of valgrind's single-threaded nature which slows Telegam's multi-threaded process down by a huge factor, which means I can't type text soon enough for it to trigger.

**Comment by Aokromes** [comment]
try updating to 1.9.17 enabling spell checker again.

**Comment by Juanlu001** [comment]
Using 1.9.19, so far so good! :clap: Thanks!
