### ISSUE TITLE
Partial search is not working

### ISSUE THREAD

**Issue by Cussa** [telegramdesktop/tdesktop#7096]
Suppose I sent a message like the following:

111222333444555

If I try to find by "111", there are not found results. Same behavior for "222", "333" and "444". However, searching by "555" returns the message. 

- 5: none results
- 55: none results
- 555: message returned
- 222: none results
- 333: none results
- 444: none results
- 4555: none results
- 44555: none results
- 444555: none results

I created a simple group to do the tests: https://t.me/joinchat/BVZNyRTeFq-UR_uko7TE6Q

App version: 1.9.8

**Comment by Aokromes** [comment]
this bug is api, it exist on all platform.
