### ISSUE TITLE
All messages in chat mark as read

### ISSUE THREAD

**Issue by nvlad** [telegramdesktop/tdesktop#7097]
### Steps to reproduce
1. open chat with many unread messages
2. switch to another chat
3. switch back

### Expected behaviour
mark as read visible messages

### Actual behaviour
all messages in chat marked as read

### Configuration
**Operating system:**
Windows

**Version of Telegram Desktop:**
1.9.8 and early

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/775
