### ISSUE TITLE
Translation - French

### ISSUE THREAD

**Issue by Venopsis** [telegramdesktop/tdesktop#71]
Hello,

I tried your desktop application and I would say that's the better one I've never tried :D

I would like to propose you my help by translate the application from English to French.
And it's for free for sure.

Cordially, Venopsis.

**Comment by telegramdesktop** [comment]
When language is approved as an official one it would be done through Transifex:
https://www.transifex.com/projects/p/telegram-desktop

Before that you can only use your own translation files through Alt+Shift+Click on Change Language and selecting your own .strings file.
