### ISSUE TITLE
[Feature Request] Allow links in group and channel info.

### ISSUE THREAD

**Issue by DmitrijOkeanij** [telegramdesktop/tdesktop#7101]
Now if I made link it needed to write full link text, and it all visible to people.
But in most cases real people do not need to see link text like https://mysite.site/dir/dir/page
They only need to see. [MySite](#) as link text.

So request is to add standart formatting options to group info.
May be not all, but links and emojis are needed.

**Comment by Aokromes** [comment]
very likely this will need api support, and i am quite sure this was rejected by marketing team.

**Comment by DmitrijOkeanij** [comment]
I understand. But do not know where to write such requests related to api and all platforms.

**Comment by ilya-fedin** [comment]
https://github.com/kotatogram/kotatogram-desktop/commit/5129c7b48091b56fd4124a201369a1384799f846
