### ISSUE TITLE
Videos wont play in armhf snap package

### ISSUE THREAD

**Issue by AliDjango** [telegramdesktop/tdesktop#7102]
related to new armhf and arm64 snap packages #6222 @john-preston 
### Steps to reproduce
1. Play any kind of video file/message

### Expected behaviour
Video must play normally

### Actual behaviour
Video won't start playing.it shows the thumbnail and doesn't start

### Configuration
**Operating system:**
Raspbian Buster on Raspberry pi 3
**Version of Telegram Desktop:**
1.9.9-1-gc03df169b
**Used theme**:

<details><summary><b>Logs</b>:</summary>
here are some logs that are outputet to the terminal(i cant find log.txt for snap package):
https://pastebin.com/JzMCWGxA
</details>

**Comment by ilya-fedin** [comment]
This is most likely related to #7103
So, [this question](https://github.com/telegramdesktop/tdesktop/issues/7103#issuecomment-579934138) is relevant

**Comment by AliDjango** [comment]
audio problem is related to #7103 but there is also a video problem 
this won't be fixed but for future references, the problem is this line
```
[2020.03.08 11:52:23] Streaming Error: Unable to sws_scale to good size 640, got 0.
[2020.03.08 11:52:23] Audio Error: playing changed while loading
[2020.03.08 11:52:24] Audio Info: Closing audio playback device.
```
