### ISSUE TITLE
Audio files and voice messages and notification sound won't play in armhf package

### ISSUE THREAD

**Issue by AliDjango** [telegramdesktop/tdesktop#7103]
related to new armhf and arm64 snap packages #6222 @john-preston 
### Steps to reproduce
1. Play any kind of audio file/message
2.  or even get a notification
### Expected behaviour
Audio must play normally.notifications must have sound

### Actual behaviour
Audio won't start playing.and notifications dont play a sound

### Configuration
**Operating system:**
Raspbian Buster on Raspberry Pi 3
**Version of Telegram Desktop:**
1.9.9-1-gc03df169b
**Used theme**:

<details><summary><b>Logs</b>:</summary>
here are some logs that are outputet to the terminal(i cant find log.txt for snap package):
https://pastebin.com/JzMCWGxA
</details>

**Comment by ilya-fedin** [comment]
Snaps don't support alsa, install pulseaudio

**Comment by Aokromes** [comment]
> Snaps don't support alsa, please install pulseaudio

are you sure? https://forum.snapcraft.io/t/the-alsa-interface/7766/4 here it states it does, but disabled by default xd
https://bugs.launchpad.net/snapd/+bug/1835290

**Comment by ilya-fedin** [comment]
We can add the alsa interface, but it anyway don't find the alsa config.
https://github.com/diddlesnaps/snapcraft-alsa adds support for pulse-through-alsa, but it doesn't make sense when the application has native pulse support.
Even [VLC](https://github.com/videolan/vlc/blob/master/extras/package/snap/snapcraft.yaml) doesn't include any hack for alsa

**Comment by Aokromes** [comment]
then this is a won't fix xd

**Comment by AliDjango** [comment]
@ilya-fedin  
> Even VLC doesn't include any hack for alsa
I don't know about VLC snap package but vlc itself works with alsa in raspbian.

**Comment by ilya-fedin** [comment]
Ok, I'll check

**Comment by ilya-fedin** [comment]
I got it.

**Comment by AliDjango** [comment]
using pulseaudio fixes the problem but if someone wants to use alsa,alsa support was added in `1.9.19-beta-18-g1dc6d942c`  read [here](https://github.com/telegramdesktop/tdesktop/issues/7324#issuecomment-596073677) for more info.it may or may not work as is just a workaround though.
