### ISSUE TITLE
telegram not starting ubuntu

### ISSUE THREAD

**Issue by giovanni5** [telegramdesktop/tdesktop#7105]
### Steps to reproduce
1. launch telegram in ubuntu

### Expected behaviour
Telegram starts

### Actual behaviour
it doesn't start

### Configuration
ubuntu 19.10 on wayland
telegram installed from snap

<details><summary><b>Output from terminal</b>:</summary>
This application failed to start because it could not find or load the Qt platform plugin "wayland-egl"
in "".

Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, xcb.

Reinstalling the application may fix this problem.
Annullato (core dump creato)

</details>

**Comment by snpefk** [comment]
Same here. Log from cli 
```
This application failed to start because it could not find or load the Qt platform plugin "wayland-egl"
in "".

Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, xcb.
```

**Comment by snpefk** [comment]
Workaround to start from cli `export DISABLE_WAYLAND=1 && telegram-desktop &`

**Comment by EndrII** [comment]
@john-preston, You need to add wayland plugins to the telegram distribution. To solve this problem in my applications I usually use [cqtdeployer tool](https://github.com/QuasarApp/CQtDeployer). It successfully copes with capturing the necessary plugins.

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/2353

**Comment by ugtar** [comment]
running the edge snap, and starting today I'm getting this error even when running X (not wayland) on 18.04.3, so it's not just an issue with wayland. I'm using the `DISABLE_WAYLAND=1 telegram-desktop &` workaround

**Comment by ugtar** [comment]
oh, DISABLE_WAYLAND used to be set in the environment inside the snapcraft.yaml file but it was removed a few days ago:
https://github.com/telegramdesktop/tdesktop/commit/9536a3c98e25fe8d6f08dc99764f4ec94319e4d5#diff-5fde7a6d86053f0e1d88c0a2a238941fL32
