### ISSUE TITLE
Telegram Desktop doesn't start on Ubuntu 18.04

### ISSUE THREAD

**Issue by Rizzen** [telegramdesktop/tdesktop#7106]
### Steps to reproduce
1. Try to start Telegram on Ubuntu 18.04

### Expected behaviour
Telegram Desktop should starts

### Actual behaviour
Telegram Desktop didn't start 

### Configuration
**Operating system:**
Ubuntu 18.04

**Version of Telegram Desktop:**
1.9.9-3-ge6cec4964
**Used theme**:

<details><summary><b>Logs</b>:</summary>
if I try to start it from terminal, there is following output:

```
rizzen@rizzen:~$ telegram-desktop 
This application failed to start because it could not find or load the Qt platform plugin "wayland-egl"
in "".
Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, xcb.
Reinstalling the application may fix this problem.
Aborted (core dumped)
```
The issue appeared just today, I've tried to reinstall application, but it didn't fix the problem.
</details>

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/7105#issuecomment-579832159
