### ISSUE TITLE
Telegram Desktop native does not recognise IME input on Manjaro with i3wm

### ISSUE THREAD

**Issue by Laichar** [telegramdesktop/tdesktop#7108]
### Steps to reproduce
1.  Open Telegram
2. Switch to a Chinese IME/any other input method that is an IME
3. Type

### Expected behaviour
The typed text should appear rendered in the target language.

### Actual behaviour
Telegram continues to detect the last keyboard used and maps the keys to the layout of the last keyboard

### Configuration
**Operating system:**
Manjaro Linux
**Version of Telegram Desktop:** telegram-desktop 1.9.8-1

**Used theme**: Night

<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/2013

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/2013#issuecomment-579947280
