### ISSUE TITLE
[Linux] [snap] Please support for russian spellchecker via hunspell

### ISSUE THREAD

**Issue by sergeG** [telegramdesktop/tdesktop#7113]
Snap does not provide russian hunspell dictionary, therefore spellchecking is not working. Please fix this. 

/snap/telegram-desktop/current/usr/share/hunspell
/snap/telegram-desktop/current/usr/share/hunspell/de_BE.aff
/snap/telegram-desktop/current/usr/share/hunspell/de_BE.dic
/snap/telegram-desktop/current/usr/share/hunspell/de_DE.aff
/snap/telegram-desktop/current/usr/share/hunspell/de_DE.dic
/snap/telegram-desktop/current/usr/share/hunspell/de_LU.aff
/snap/telegram-desktop/current/usr/share/hunspell/de_LU.dic
/snap/telegram-desktop/current/usr/share/hunspell/en_AU.aff
/snap/telegram-desktop/current/usr/share/hunspell/en_AU.dic
/snap/telegram-desktop/current/usr/share/hunspell/en_CA.aff
/snap/telegram-desktop/current/usr/share/hunspell/en_CA.dic
/snap/telegram-desktop/current/usr/share/hunspell/en_GB.aff
/snap/telegram-desktop/current/usr/share/hunspell/en_GB.dic
/snap/telegram-desktop/current/usr/share/hunspell/en_US.aff
/snap/telegram-desktop/current/usr/share/hunspell/en_US.dic
/snap/telegram-desktop/current/usr/share/hunspell/en_ZA.aff
/snap/telegram-desktop/current/usr/share/hunspell/en_ZA.dic
/snap/telegram-desktop/current/usr/share/hunspell/es_AR.aff
/snap/telegram-desktop/current/usr/share/hunspell/es_AR.dic
/snap/telegram-desktop/current/usr/share/hunspell/es_BO.aff
/snap/telegram-desktop/current/usr/share/hunspell/es_BO.dic
/snap/telegram-desktop/current/usr/share/hunspell/es_CL.aff
/snap/telegram-desktop/current/usr/share/hunspell/es_CL.dic
/snap/telegram-desktop/current/usr/share/hunspell/es_CO.aff
/snap/telegram-desktop/current/usr/share/hunspell/es_CO.dic
/snap/telegram-desktop/current/usr/share/hunspell/es_CR.aff
/snap/telegram-desktop/current/usr/share/hunspell/es_CR.dic
/snap/telegram-desktop/current/usr/share/hunspell/es_CU.aff
/snap/telegram-desktop/current/usr/share/hunspell/es_CU.dic
/snap/telegram-desktop/current/usr/share/hunspell/es_DO.aff
/snap/telegram-desktop/current/usr/share/hunspell/es_DO.dic
/snap/telegram-desktop/current/usr/share/hunspell/es_EC.aff
/snap/telegram-desktop/current/usr/share/hunspell/es_EC.dic
/snap/telegram-desktop/current/usr/share/hunspell/es_ES.aff
/snap/telegram-desktop/current/usr/share/hunspell/es_ES.dic
/snap/telegram-desktop/current/usr/share/hunspell/es_GT.aff
/snap/telegram-desktop/current/usr/share/hunspell/es_GT.dic
/snap/telegram-desktop/current/usr/share/hunspell/es_HN.aff
/snap/telegram-desktop/current/usr/share/hunspell/es_HN.dic
/snap/telegram-desktop/current/usr/share/hunspell/es_MX.aff
/snap/telegram-desktop/current/usr/share/hunspell/es_MX.dic
/snap/telegram-desktop/current/usr/share/hunspell/es_NI.aff
/snap/telegram-desktop/current/usr/share/hunspell/es_NI.dic
/snap/telegram-desktop/current/usr/share/hunspell/es_PA.aff
/snap/telegram-desktop/current/usr/share/hunspell/es_PA.dic
/snap/telegram-desktop/current/usr/share/hunspell/es_PE.aff
/snap/telegram-desktop/current/usr/share/hunspell/es_PE.dic
/snap/telegram-desktop/current/usr/share/hunspell/es_PR.aff
/snap/telegram-desktop/current/usr/share/hunspell/es_PR.dic
/snap/telegram-desktop/current/usr/share/hunspell/es_PY.aff
/snap/telegram-desktop/current/usr/share/hunspell/es_PY.dic
/snap/telegram-desktop/current/usr/share/hunspell/es_SV.aff
/snap/telegram-desktop/current/usr/share/hunspell/es_SV.dic
/snap/telegram-desktop/current/usr/share/hunspell/es_US.aff
/snap/telegram-desktop/current/usr/share/hunspell/es_US.dic
/snap/telegram-desktop/current/usr/share/hunspell/es_UY.aff
/snap/telegram-desktop/current/usr/share/hunspell/es_UY.dic
/snap/telegram-desktop/current/usr/share/hunspell/es_VE.aff
/snap/telegram-desktop/current/usr/share/hunspell/es_VE.dic
/snap/telegram-desktop/current/usr/share/hunspell/fr.aff
/snap/telegram-desktop/current/usr/share/hunspell/fr.dic
/snap/telegram-desktop/current/usr/share/hunspell/fr_BE.aff
/snap/telegram-desktop/current/usr/share/hunspell/fr_BE.dic
/snap/telegram-desktop/current/usr/share/hunspell/fr_CA.aff
/snap/telegram-desktop/current/usr/share/hunspell/fr_CA.dic
/snap/telegram-desktop/current/usr/share/hunspell/fr_CH.aff
/snap/telegram-desktop/current/usr/share/hunspell/fr_CH.dic
/snap/telegram-desktop/current/usr/share/hunspell/fr_FR.aff
/snap/telegram-desktop/current/usr/share/hunspell/fr_FR.dic
/snap/telegram-desktop/current/usr/share/hunspell/fr_LU.aff
/snap/telegram-desktop/current/usr/share/hunspell/fr_LU.dic
/snap/telegram-desktop/current/usr/share/hunspell/fr_MC.aff
/snap/telegram-desktop/current/usr/share/hunspell/fr_MC.dic
/snap/telegram-desktop/current/usr/share/hunspell/it_CH.aff
/snap/telegram-desktop/current/usr/share/hunspell/it_CH.dic
/snap/telegram-desktop/current/usr/share/hunspell/it_IT.aff
/snap/telegram-desktop/current/usr/share/hunspell/it_IT.dic
/snap/telegram-desktop/current/usr/share/hunspell/pl_PL.aff
/snap/telegram-desktop/current/usr/share/hunspell/pl_PL.dic
/snap/telegram-desktop/current/usr/share/hunspell/pt_BR.aff
/snap/telegram-desktop/current/usr/share/hunspell/pt_BR.dic
/snap/telegram-desktop/current/usr/share/hunspell/pt_PT.aff
/snap/telegram-desktop/current/usr/share/hunspell/pt_PT.dic

Telegram Desktop 1.9.9, snap, Ubuntu

**Comment by Aokromes** [comment]
try updating to 1.9.17

**Comment by sergeG** [comment]
Works in  snap 1.9.21. Many thanks!
