### ISSUE TITLE
[Linux] [snap] Telegram tasktray icon incorrect display after update to 1.9.9

### ISSUE THREAD

**Issue by franksmcb** [telegramdesktop/tdesktop#7115]
### Steps to reproduce
Have snapd install Telegram Desktop 1.9.9

### Expected behaviour
Tasktray icon should display correctly with Telegram icon and show message indicator
### Actual behaviour
Tasktray icon does not display proper icon and does not message indicator

### Configuration
**Operating system:**
Ubuntu MATE 20.04, 19.10, 18.04
**Version of Telegram Desktop:**
1.9.9

With 1.9.9
![2020-01-30_10-42_1](https://user-images.githubusercontent.com/44311495/73475864-1c252b80-4389-11ea-83d4-db725f688118.png)
Before 1.9.9 
![tg-old-jpg](https://user-images.githubusercontent.com/44311495/73475865-1c252b80-4389-11ea-8036-85cc7084a7fa.jpg)

**Used theme**:

<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by samael** [comment]
Ubuntu Mate 18.04. Same problem

**Comment by ilya-fedin** [comment]
Can you click tray by right button and open about dialog, then screenshot it?
Example:
![изображение](https://user-images.githubusercontent.com/17829319/73505450-72668e80-43ca-11ea-823d-d569747410a3.png)

**Comment by franksmcb** [comment]
![image](https://user-images.githubusercontent.com/44311495/73508385-0455a380-4399-11ea-8b11-b1e6156f051d.png)

**Comment by ilya-fedin** [comment]
This is what I suspected :(
Ubuntu MATE uses unity's indicator with a very limited support of SNI
Replacing this applet with MATE's Notification Area applet should fix the issue.

**Comment by ilya-fedin** [comment]
https://bugs.launchpad.net/ubuntu/+source/sni-qt/+bug/1600136

**Comment by ilya-fedin** [comment]
There are a hack in Qt, but looks like snaps doesn't have access to the process list :(
https://github.com/qt/qtbase/blob/v5.9.5/src/platformsupport/themes/genericunix/dbustray/qdbustrayicon.cpp#L196

**Comment by Aokromes** [comment]
so, 3rd party bug?

**Comment by ilya-fedin** [comment]
+/-, ideally ubuntu maintainers should add mate to the list in that file (and fix all qt applications in his repo/snap), but it should be possible to workaround on our side.

**Comment by franksmcb** [comment]
This worked correctly in versions prior up to and including 1.8.15

**Comment by ilya-fedin** [comment]
@franksmcb appindicator is used for mate before, but I and preston are trying to leave only Qt in tdesktop

**Comment by yulayula16** [comment]
This issue looks relatable to my issue here, except instead of incorrect icon in they tray, it disappears from view when notification counters update.

**Settings > Advanced >** Uncheck **Show Tray Icon**, and Check **Show Tray Icon** to bring icon back, clear notification from a chat or wait for new chat message to appear, and icon disappears.

![telegram_borked](https://user-images.githubusercontent.com/60402017/74149154-07814700-4c57-11ea-981c-8793e6bd6a71.gif)

**Comment by ilya-fedin** [comment]
No, this issue is about AppIndicator and IconPixmap incompatibility. Cinnamon uses XEmbed.

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/commit/3b4dfa138176b4d1e3cb14be1be638ebe2f52713
