### ISSUE TITLE
Crash with multiple files

### ISSUE THREAD

**Issue by LucaTheHacker** [telegramdesktop/tdesktop#7118]
### Steps to reproduce
1. download the photo from https://damettoluca.com/assets/images/telegramcrash.jpg
2. copy it from desktop and paste many times into telegram desktop 

### Expected behaviour
I should be able to send many files without problems

### Actual behaviour
High ram, cpu and gpu usage, (like 9GB of ram, 70% of i7-7700k and 90% of GTX1050) and a nice crash

### Configuration
**Operating system:** W10Pro 18363.592

**Version of Telegram Desktop:** 1.9.9

**Used theme**: nightmode default

**Comment by Neurotoxin001** [comment]
https://github.com/telegramdesktop/tdesktop/issues/6671#issuecomment-578533015
