### ISSUE TITLE
[Feature Request] Gif SIZE !

### ISSUE THREAD

**Issue by Unkn9wn1** [telegramdesktop/tdesktop#7119]
Hi, why you guys removed gif size?
we need it, make it ok please

**Comment by RememberTheAir** [comment]
Duplicate of #7061

**Comment by Unkn9wn1** [comment]
Yes, it's because it's a problem for me, i want is back

**Comment by RememberTheAir** [comment]
One issue is enough. Duplicate issues will be closed

**Comment by Unkn9wn1** [comment]
i know, but before closing, developers read it 😄
