### ISSUE TITLE
[Feature Request] Right click on round button moves to latest message

### ISSUE THREAD

**Issue by f242** [telegramdesktop/tdesktop#7120]
### Is your feature request related to a problem?
Can't quickly switch to latest message after read conversation through click on original message. Left click moves one step later, only scroll helps.

### Describe the solution you'd like
Right-clicking a round button would solve the problem
![image](https://user-images.githubusercontent.com/10371194/73551053-c15a0580-4456-11ea-8b64-12e8100f4400.png)

**Comment by jeffythedragonslayer** [comment]
I can't reproduce this behavior.  Left clicking the round button always takes me to the latest message in any chat.

**Comment by f242** [comment]
@jeffythedragonslayer you need to click on quote in conversation to move to earlier messages and after this  you can't quick move to latest message

**Comment by jeffythedragonslayer** [comment]
Oh ok, if I click on a quote it takes me to the quoted message, then clicking the round button takes me back to the quoting message again.  To go to the latest message though clicking the round button again works.

**Comment by f242** [comment]
@jeffythedragonslayer i mean conversation, you talk about single reply
