### ISSUE TITLE
Impossible to sign up without a last name

### ISSUE THREAD

**Issue by mymedia2** [telegramdesktop/tdesktop#7121]
### Steps to reproduce
1. Start registration of a new user.
2. Enter a phone number and confirm your PIN-code.
3. Type a first name.
4. Click the "Sign up" button.

### Expected behaviour
1. You are able to login into Telegram and see (empty) chat list.

### Actual behaviour
1. Nothing happens instead.

![TelegramDesktop_screencast.gif](https://user-images.githubusercontent.com/9163157/73587107-31ed3a80-44c8-11ea-8c4a-a511fea641d9.gif)

### Configuration
**Operating system:** GNU/Linux Ubuntu MATE 19.10 (Eoan Ermine)
**Version of Telegram Desktop:** 1.9.9 (snap package)
**Used theme:** Default
**Logs:** [TelegramDesktop_workdir.zip](https://github.com/telegramdesktop/tdesktop/files/4142154/TelegramDesktop_workdir.zip)

**Comment by jeffythedragonslayer** [comment]
FYI, the clicking "Edit name" in the settings menu allows you to erase your last name, so you could technically just create it with anything to start with for a workaround.

**Comment by Megamiun** [comment]
Altought this is a solution, I think it would be better to just allow the user to create it without a Last name, no?

Or is the last name a required field to creating a new account in the server?

**Comment by mymedia2** [comment]
The bug is still present in the latest beta, v2.4.11. Why on earth you presume, if the reporter is not proactive, the bug disappears by itself?

**Comment by Aokromes** [comment]
it's a bot, it asked if the bug was still valid 1 month ago, and "said" the ticket will be closed after 7d if no one answers, but it was closed after 1 month.

**Comment by mymedia2** [comment]
@ilya-fedin it is so vitriolic comment. It is not my duty to recover bug reports after these bots of yours.

**Comment by ilya-fedin** [comment]
> it is so vitriolic comment.

common, where's your sense of humor?
