### ISSUE TITLE
[Feature Request] Record an audio message by pressing and not holding the button.

### ISSUE THREAD

**Issue by Faralaks** [telegramdesktop/tdesktop#7123]
if I want to record a long voice message, I have to hold down the microphone button for a long time.

Make it possible to record a message by clicking the button. and send by clicking again.
Or you can do it as in the mobile app: the ability to pull up to continue recording and release the mouse. then send the message by clicking again.

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/3208
