### ISSUE TITLE
Group chat stop updating if I not a member of it

### ISSUE THREAD

**Issue by Neurotoxin001** [telegramdesktop/tdesktop#7125]
### Steps to reproduce
1. open https://t.me/ru2chnews but don't join
2. new messages will updating for some time but then they will stop updating
3. to view new messages you must close chat and then reopen it.

to simplify it you can send @ru2chnews to your saved messages.

### Configuration
**Operating system:** win 10 ltsc 1809

**Version of Telegram Desktop:** 1.9.9

**Used theme**: dark default

There is no errors in logs.

**Comment by Aokromes** [comment]
i don't think this is a bug.

**Comment by Neurotoxin001** [comment]
> i don't think this is a bug.

This is bug because it's happens not with all chats, for example with https://t.me/abuwtf (press Discuss) all is fine, I can even see who is typing. In @ru2chnews I can't. And for example in znakomstva_chats I can't too.

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/4692
