### ISSUE TITLE
Zero icon (:zero:) malformed when entered on the desktop

### ISSUE THREAD

**Issue by tkossak** [telegramdesktop/tdesktop#7126]
### Steps to reproduce
1. Go to "Saved Messages" (in **Telegram Desktop on Linux**)
2. Write message: `:zero::one::two::three:` - do not copy paste it, write it, so telegram can change text into icons for example `:zero:` into ":zero:". Then send the message with four icons (:zero::one::two::three:).
3. Open This message in **Telegram on android phone**: icon ":zero:" has different color than icons :one:, :two:, and :three:.

### Expected behaviour
Icon ":zero:" should be the same color as other icons. It should look like this:
![image](https://user-images.githubusercontent.com/3728245/73595114-fc227300-4514-11ea-9518-334f2e46d497.png)
![image](https://user-images.githubusercontent.com/3728245/73595120-047aae00-4515-11ea-8f8c-d3184e7b2b2b.png)

### Actual behaviour
In **android telegram** ":zero:" icon has different color than the rest of the icons. It happens in both classic and dark mode. It happens even if you enter one icon ":zero:" in the message (other text in the message doesn't matter). Screenshots:
![image](https://user-images.githubusercontent.com/3728245/73595062-959d5500-4514-11ea-9d88-12d0a6f368cb.png)
![image](https://user-images.githubusercontent.com/3728245/73595065-9b933600-4514-11ea-9ba1-ee5092736519.png)

### Configuration
**Operating system:** Linux Manjaro 18.1.5

**Version of Telegram Desktop:** 1.9.9
(Telegram for android: v5.14.0 (1851) arm-v7a

**Used theme**: Night mode (on telegram desktop)

**Comment by tkossak** [comment]
No, I did not lost interest, the bug still persists and is annoying.

**Comment by ilya-fedin** [comment]
I guess this should be fixed on telegram android side

**Comment by tkossak** [comment]
I thought telegram desktop sends wrong icon (wrong unicode characters). You mean telegram desktop sends proper unicode characters, only android telegram interprets/displays them wrongly?

**Comment by ilya-fedin** [comment]
As far as I know, telegram android replaces native emojis with internal pixmaps just like tdektop, but looks like zero icon has multiple valid sequences and telegram android doesn't replace them all, that's why you see native android zero emoji.

**Comment by tkossak** [comment]
I just tested and it seems to be fixed. Don't know who did it but thank you, the issue can be closed :)
