### ISSUE TITLE
Interface scale does not change automatically when moving the window

### ISSUE THREAD

**Issue by junalmeida** [telegramdesktop/tdesktop#7127]
### Steps to reproduce
1. Have a two monitor setup with different scale (DPI)
2. Move telegram desktop from one monitor to another, or unplug the monitor to force it to move.
3. See the window smaller or bigger than the current scale of the monitor

### Expected behaviour
Telegram should detect the scale it is currently on and adjust automatically

### Actual behaviour
Telegram is displayed at the wrong scale

### Configuration
**Operating system:** Windows 10

**Version of Telegram Desktop:** 1.9.7

**Used theme**: Night

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/6196
