### ISSUE TITLE
Resizable emoji/sticker panel

### ISSUE THREAD

**Issue by looki** [telegramdesktop/tdesktop#713]
I think it would be nice if the sticker menu was resizable, especially considering that the list of stickers is growing and that we've already created quite an amount of custom stickers among a group of friends. It keeps taking longer and longer to scroll through the list with every new sticker.

**Comment by darristan** [comment]
+1. Esp considering the segmentation of display used in Desktop. Might as well include smooth scrolling.

**Comment by DiThi** [comment]
Using telegram in a 4K monitor with 100% UI scale. This menu is ridiculously small. +1

**Comment by telegramdesktop** [comment]
@DiThi Why not 200%?

**Comment by DiThi** [comment]
@telegramdesktop because I have everything else at 100%, using it like I would use 2-3 individual monitors.

**Comment by DaFri-Nochiterov** [comment]
+1

**Comment by JarrettBillingsley** [comment]
The sticker window is really, really unwieldy. The popup closes instantly if you happen to move your cursor off it; it's really hard to scroll it without a scroll wheel (graphics tablet user here!); only about five packs display at the bottom; larger packs require scrolling up and down...

It's desktop and you have the screen real estate; why not make it a sidebar or something? Have tabs for each sticker pack and display the entire pack at once. The sticker previews are also really small for a desktop screen.

Failing all that, why not just have the same "emoji sticker input" that the mobile client has?

**Comment by sergey-miryanov** [comment]
+1
Also imho will be useful show smile for each sticker.

**Comment by JarrettBillingsley** [comment]
Well now we have the emoji sticker input, but the emoji input box suffers the same issues the sticker input box does, lol

**Comment by atommixz** [comment]
I need the magnifying glass to select the stickers

**Comment by tstackhouse** [comment]
+1 for this, it would be nice if it were collapsible as well.  I personally don't care for it being ever present on the side of my window.

**Comment by tmladek** [comment]
Please, can I hide the panel?

**Comment by DiThi** [comment]
The panel can be easily hidden by clicking the classic emoji/sticker icon in the text input field.
But we still have the problem of very tiny things, and a new one: The window is not resized back when you hide the panel.

**Comment by JarrettBillingsley** [comment]
This is so, so, so much better than before, THANK YOU ❤️

**Comment by stek29** [comment]
Closing in favour of #3265
