### ISSUE TITLE
Native notifications feature missing

### ISSUE THREAD

**Issue by Storm-Engineer** [telegramdesktop/tdesktop#7130]
I used to use native notifications because the regular ones are constantly displayed on the wrong screen with no way to control which screen to use, but after updating a few days ago, the option for native notifications disappeared and Telegram is back using its own ones.

### Steps to reproduce
1. Go to settings / Notifications
2. Try to look for the option to use native notifications

### Expected behaviour
A checkbox should be present

### Actual behaviour
Option missing

### Configuration
**Operating system:**
Arch Linux
**Version of Telegram Desktop:**
1.9.7 / 1.9.9
**Used theme**:
N/A

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/3831#issuecomment-356715454

**Comment by ilya-fedin** [comment]
Which DE are you using?

**Comment by xvitaly** [comment]
@Storm-Engineer Do you have D-Bus installed and running?

**Comment by AndydeCleyre** [comment]
@Storm-Engineer I don't know why this was marked as a dupe of the other issue, it's obviously a different issue.

Please provide more details about your native notification / DE setup. Which DE? Which notification server?

I'm on Arch, with Plasma Desktop (launched via SDDM), and TD `1.9.9`, and use native notifications. This is what my notifications settings screen looks like:

![Screenshot_20200203_122117](https://user-images.githubusercontent.com/1787385/73675048-bdf59280-467f-11ea-89ea-efbb42685ead.png)

**Comment by Storm-Engineer** [comment]
Sorry for the late reply, I missed the emails about getting replies. The issue is still present. :(

@ilya-fedin KDE/Plasma 5, everything is set up the recommended way.

@xvitaly Yes I do. This is a fully set up and configured system I'm using for years. And other programs can still use native notifications no problem.

@AndydeCleyre Arch, KDE/Plasma 5, and I think it uses the libnotify backage? But...

Found something weird: Someone at Arch forums asked if it works if I use the notify-send command (which according to the wiki needs libnotify) to create a notification before launching Telegram, and indeed, it does!

So when Telegram starts automatically upon logging into KDE the option is missing. Then I kill Telegram, run notify-send in terminal, and then start Telegram again and BOOM, the option is back!

**Comment by ilya-fedin** [comment]
>  and I think it uses the libnotify backage?

No


> So when Telegram starts automatically upon logging into KDE the option is missing

Hmm, so kde launches apps before notification daemon is started. If so, it is a kde bug, not tdesktop one :(

**Comment by ilya-fedin** [comment]
@Storm-Engineer https://github.com/telegramdesktop/tdesktop/issues/7308#issuecomment-593756986

**Comment by ilya-fedin** [comment]
Duplicate of #5590

**Comment by Mte90** [comment]
I can confirm this issue and the workaround on Linux with KDE.
I launch telegram at boot from the autostart settings in KDE, but running a notification and restart telegram that options is available again.

**Comment by solarkraft** [comment]
I have this issue on 2.2, but tdesktop is *not* auto started. My notification daemon (mako) is running and perfectly displays notifications sent with notify-send. No combination of restarts appears to fix the issue.

**Comment by ilya-fedin** [comment]
Send your log.txt (~/.local/share/TelegramDesktop/log.txt if isn't installed snap/flatpak)

**Comment by solarkraft** [comment]
Okay, never mind - it seems a lot like the issue actually *is* with my notification daemon. Sorry for bothering!

**Comment by cauebs** [comment]
@solarkraft Could you say what was the issue? I also have `mako` running, `notify-send` works, but I don't get the "Use native notifications" option on Telegram.

**Comment by ilya-fedin** [comment]
@cauebs make sure that mako is running at the time of Telegram autostart

**Comment by cauebs** [comment]
Thanks for the follow up. I actually figured it out yesterday: Telegram is not giving me that checkbox, but I noticed that this does not mean native notifications are not available. In fact, they are enabled by default and I can't get the regular notifications (which does not bother me). It's all fine :laughing:

**Comment by ilya-fedin** [comment]
You're probably running Wayland, there's no custom notifications due to lack of positioning APIs on Wayland and so there's no checkbox. But it will appear as soon as Wayland will (if would) have enough API.
