### ISSUE TITLE
[Feature Request] Group / Channels Privacy Raname

### ISSUE THREAD

**Issue by phate191** [telegramdesktop/tdesktop#7132]
### Is your feature request related to a problem?
Sometimes we have groups or channel with clear and abvious name, but can be embarassing if this group as associated to medical/psicological support or other private matters.
In public places (work, library, cafè) with the chat open, the gigantic group title is in nice view for every one pass behind us.

### Describe the solution you'd like
A simple solution can be a **local** rename option (or better still, a rename for the specified account), to hide the huge and bold title of the group / notify toast. And also a toggle to hide the toast notification for the specified chat/group/channel like on the mobile (Android in my case) version.

### Describe alternatives you've considered
I don't see any other alternative to enhance privacy in public spaces.

**Comment by Aokromes** [comment]
you can simply archive the embarassing ones.

**Comment by phate191** [comment]
> you can simply archive the embarassing ones.

Absolutely for the chat list, but not for the chat itself when is open
