### ISSUE TITLE
update telegram

### ISSUE THREAD

**Issue by maxnosib** [telegramdesktop/tdesktop#7133]
### Steps to reproduce
Telegram Desktop for centos7 crashes when updating and does not start again
you have to manually go into the .local / share / TelegramDesktop / tdata folder and run the updated version

### Configuration
** centos7:**

**1,9*:**

**Comment by Aokromes** [comment]
you got it from centos repo or github / desktop.telegram.org ?

**Comment by Aokromes** [comment]
no answer after more than 1 month, closing.
