### ISSUE TITLE
The Desktop version can't edit the Scheduled Messages, Android version can edit.

### ISSUE THREAD

**Issue by hizengbiao** [telegramdesktop/tdesktop#7136]
### Is your feature request related to a problem?
I have write some scheduled messages in my group, sometimes i want to change some content, but the Windows Telegram only have 3 choices: "Copy Text"/"Send Now"/"Delete Messages". However, the Android Telegram have already have the funtion "Edit Text".

### Describe the solution you'd like
If the Windows Telegram can also edit the Scheduled Messages, that would be better, thanks.

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/6496
