### ISSUE TITLE
[Feature Request] Add periodic reminders to your favorites

### ISSUE THREAD

**Issue by systracer** [telegramdesktop/tdesktop#7138]
There is a very convenient time reminder in your favorites. Unfortunately, you can’t set up a repeat of reminders, without this, the function is inferior.

If you add the ability to repeat the reminder after an arbitrary time, this completely eliminates the need to use other reminder programs.

For example, I want to show the same reminder every month or every day and now I can’t do it.

**Comment by xlarin** [comment]
This is the function of my dreams!
I support this proposal!

**Comment by RememberTheAir** [comment]
Unfortunately this is an API issue and tdesktop can't add it without backend support for repeated reminders

**Comment by systracer** [comment]
That is why I ask you to add such support. This is a feature request.

**Comment by RememberTheAir** [comment]
You can report this kind of features on Twitter (https://twitter.com/telegram) or to the in-app support
