### ISSUE TITLE
[Feature Request] Allow to only automatically check+notify about updates (without auto-install!)

### ISSUE THREAD

**Issue by tooomm** [telegramdesktop/tdesktop#7139]
### Is your feature request related to a problem?
It's quite annoying to manually check and update from time to time.

### Describe the solution you'd like
Telegram only allows to automatically check for updates with automatically installing them right away.
I would like to see notifications about new updates and easily install at my choice.

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/4643
