### ISSUE TITLE
Telegram crashes upon opening and typing

### ISSUE THREAD

**Issue by fourlastor** [telegramdesktop/tdesktop#7140]
### Steps to reproduce
1. Open telegram
2. Start typing in chat

### Expected behaviour
Telegram should stay open while you type

### Actual behaviour
It either freezes completely (need to force close) or crashes with the following errors:
```
  ~ Telegram/Telegram 
Qt: Session management error: Authentication Rejected, reason : MIT-MAGIC-COOKIE-1 authentication rejected
free(): double free detected in tcache 2
[1]    16311 abort (core dumped)  Telegram/Telegram
``` 

### Configuration
**Operating system:** Ubuntu 19.10

**Version of Telegram Desktop:** 1.9.9

**Used theme**:
![image](https://user-images.githubusercontent.com/1263058/73837634-2a080000-4812-11ea-97eb-7329a9a81753.png)

How do I get the logs if necessary?

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/7095
