### ISSUE TITLE
Some pictures won't load

### ISSUE THREAD

**Issue by skipik** [telegramdesktop/tdesktop#7142]
### Steps to reproduce
1. Join https://t.me/meduza_news and https://t.me/tmfeed
2. Use those channels for some time, try to read as much posts as you can, including the old ones
3. 

### Expected behaviour
All the pictures will be loaded

### Actual behaviour
Some pictures won't load in those two channels only. It's prob related to some cache issue (may be in TDLib) as it doesn't happen right after the channel joining but after some time (1-2 days)

![111](https://user-images.githubusercontent.com/24621645/73877982-c2ca6a00-486a-11ea-8519-7b030ab32a09.png)

### Configuration
**Operating system:**
Microsoft Windows 10 Enterprise (x64) Build 18363.628 (1909/November 2019 Update)

**Version of Telegram Desktop:**
Telegram Desktop 1.9.9

**Used theme**:
Default day theme

<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by skipik** [comment]
Prob similar to this one https://github.com/telegramdesktop/tdesktop/issues/7091
I also have this issue on TDLib based Telegram X and don't have on the official Telegram for android.

**Comment by Neurotoxin001** [comment]
I have same issue sometimes and in log this error:
`RPC Error: request 1308 got fail with code 400, error FILE_REFERENCE_EXPIRED`

**Comment by skipik** [comment]
https://github.com/pyrogram/pyrogram/issues/315
https://github.com/Dineshkarthik/telegram_media_downloader/pull/4
This info might be useful also.

**Comment by Neurotoxin001** [comment]
2.1.8 beta start having this issue more often

even if I press, it won't download:
![image](https://user-images.githubusercontent.com/39812401/83806526-534e7500-a6ba-11ea-9f50-b88d977af946.png)

https://pastebin.com/0BLUWd5P

**Comment by Neurotoxin001** [comment]
2.1.18 issue still here
![image](https://user-images.githubusercontent.com/39812401/87115822-fb88c800-c27c-11ea-8a7b-78369f7ad3aa.png)
![image](https://user-images.githubusercontent.com/39812401/87115832-03486c80-c27d-11ea-8041-df6533d41f26.png)

**Comment by reallyuniquename** [comment]
@Neurotoxin001 that's actually #8043 which is fixed for me on 2.1.13.

#7142 is about URL previews (this one).
#8043 is about posted images failing to load.

**Comment by Neurotoxin001** [comment]
URL previews seems fixed, but I have this issue with avatars (after ~15 hours of running Telegram without restarts).
![image](https://user-images.githubusercontent.com/39812401/95708541-3841d200-0c65-11eb-9c78-412902dd6753.png)

Most channel avatars just blurred when I open them. But this is only with first avatar image, when I scroll to second (if it exist) - it's fine

2.4.3. Only restart helps.

**Comment by skipik** [comment]
I still have the problem.

**Comment by Neurotoxin001** [comment]
I have problem only with video/photo avatars. When client is running 10+ hours I can't see them.

`[2021.04.11 00:04:56] RPC Error: request 41621 got fail with code 400, error FILE_REFERENCE_EXPIRED`
`[2021.04.11 00:04:57] Streaming Error: Error in avformat_open_input (code: -1, text: Operation not permitted).`

2.7.1
win 10

**Comment by Neurotoxin001** [comment]
Update. Issue still here not only with channel/group avatars.

Here is some link previews after all night running in tray (and they won't load until restart):
![image](https://user-images.githubusercontent.com/39812401/114501912-8eeb9100-9c33-11eb-99b3-577adf3f8859.png)

**Comment by Neurotoxin001** [comment]
2.7.4 still have this issue

![image](https://user-images.githubusercontent.com/39812401/117246297-10a29900-ae45-11eb-873f-f569fd651860.png)

**Comment by Neurotoxin001** [comment]
2.9.5 still have it

**Comment by skipik** [comment]
Yes, I can confirm that the problem is still reproducible.

**Comment by Neurotoxin001** [comment]
3.6.1 still have it

**Comment by Neurotoxin001** [comment]
Issue is still here (4.2.4, Windows 10)

![image](https://user-images.githubusercontent.com/39812401/196843880-e10a9502-1fd7-4e41-b5a6-a5934ad381ab.png)

https://user-images.githubusercontent.com/39812401/196844011-4b20a58d-0efc-4f34-8690-d3630ece1c25.mp4


```
[2022.10.20 05:44:28] RPC Error: request 72349 got fail with code 400, error FILE_REFERENCE_EXPIRED
[2022.10.20 05:44:29] RPC Error: request 72351 got fail with code 400, error FILE_REFERENCE_EXPIRED
[2022.10.20 05:44:30] RPC Error: request 72353 got fail with code 400, error FILE_REFERENCE_EXPIRED
```

**Comment by Neurotoxin001** [comment]
Remove "stale" tag please
