### ISSUE TITLE
Collapsed muted archived group chats still show notifications

### ISSUE THREAD

**Issue by PgLoLo** [telegramdesktop/tdesktop#7148]
I have muted group chat in COLLAPSED archive. But notifications are still both on the tray icon and in the main screen:

![image](https://user-images.githubusercontent.com/5480856/73932875-48dac500-48ec-11ea-90d2-cf543b7b199b.png)
![image](https://user-images.githubusercontent.com/5480856/73932891-509a6980-48ec-11ea-8fd4-2fa29b76953a.png)

Fix it please.

**Comment by PgLoLo** [comment]
Ubuntu 18.04 btw, telegram installed with snap

**Comment by john-preston** [comment]
You can remove muted chats from the counter in Settings > Notifications.

**Comment by PgLoLo** [comment]
> You can remove muted chats from the counter in Settings > Notifications.

thank you, solved
