### ISSUE TITLE
[Feature Request] Allow to change media volume in PiP

### ISSUE THREAD

**Issue by MasterGroosha** [telegramdesktop/tdesktop#7149]
### Describe the solution you'd like
It would be nice if we'll be able to change volume of media files played in PiP mode. I see 2 possible options:
1) Add horizontal volume slider to PiP
2) Show vertical slider when you scroll wheel over PiP windows (like in VLC player)

### Describe alternatives you've considered
AFAIK now I have to return to "classic" mode and change volume there. Or use system volume slider.

### Additional context
Relevant as of TDesktop 1.9.10

**Comment by MasterGroosha** [comment]
This is still relevant

**Comment by MasterGroosha** [comment]
This is still relevant

**Comment by sashacmc** [comment]
Dear @MasterGroosha,
I added a pull request to control the sound in the pip window.
https://github.com/telegramdesktop/tdesktop/pull/16274
Feel free to vote and support.

**Comment by sashacmc** [comment]
The feature is available in the latest release.
