### ISSUE TITLE
Crash wen using playback speed video

### ISSUE THREAD

**Issue by crashmax-off** [telegramdesktop/tdesktop#7151]
### Steps to reproduce
![6d1249061a150f2c2cef30ae453cb118](https://user-images.githubusercontent.com/15673111/74002230-733e8800-49a9-11ea-81bb-c24acbba072b.gif)
This is happening when the video stopped

### Configuration
**Operating system:** Windows 10 x64

**Version of Telegram Desktop:** 1.9.10 beta

<details><summary><b>Logs</b>:</summary>
[2020.02.07 12:42:14] Assertion Failed! "active()" media_streaming_player.cpp:830
</details>

**Comment by john-preston** [comment]
@crashmax-off Thanks! I'll fix that in the next version.

**Comment by Aokromes** [comment]
fixed on 1.9.11.
