### ISSUE TITLE
[Question] How to build portable version

### ISSUE THREAD

**Issue by psychosys** [telegramdesktop/tdesktop#7152]
I need to compile a portable version that stores the **data** files in the same directory as executable file ..

**Debug version** stores the profile data inside the same directory but it chews the drive by making many log files ( of course it is debug version 🤣 

so my question is how to build the Release version to be portable OR how to disable logging in debug version ..

Thanks

**Comment by john-preston** [comment]
@psychosys You can use the prebuilt version or your own build and create a directory named TelegramForcePortable in the same directory the app is located. Then data will be stored there.

**Comment by psychosys** [comment]
@john-preston Thank you very much ! .. and thanks for your fantastic work ...
