### ISSUE TITLE
Smaller icon in Ubuntu 18.04

### ISSUE THREAD

**Issue by clausmichele** [telegramdesktop/tdesktop#7153]
![Screenshot from 2020-02-07 09-23-01](https://user-images.githubusercontent.com/31700619/74012909-9eb27a00-498b-11ea-9457-63f156ff7a3d.png)

### Steps to reproduce
Install 1.9.10 version on Ubuntu

### Expected behaviour
Icon should remain the same

### Actual behaviour
Icon becomes smaller

### Configuration
Ubuntu 18.04
1.9.10

**Comment by NickKush** [comment]
Same.

Ubuntu 18.04
Telegram 19.10

![photo_2020-02-07_14-25-23](https://user-images.githubusercontent.com/10407618/74025743-b0a91280-49b5-11ea-8d68-6db96b1f7bec.jpg)

**Comment by PeterMX** [comment]
same, it comes with Telegram 1.9.10. But I have **Ubuntu 19.10**, so please update issue name to "Ubuntu" instead of "Ubuntu 18.04"

**Comment by PeterMX** [comment]
I think the issue was introduced here https://github.com/telegramdesktop/tdesktop/commit/2807c5ef19a9edfde7934f1673facc89a9337bce
