### ISSUE TITLE
Telegram Icon Not Working After Update

### ISSUE THREAD

**Issue by stivens13** [telegramdesktop/tdesktop#7154]
Steps to reproduce
Click on Telegram Icon in the menu bar on top (Mac) when Telegram window is not active

Expected behaviour
Telegram window appears

Actual behaviour
Icon menu appears with options: 
- Minimize to tray
- Disable Notifications
- Quit Telegram

Earlier, this menu was triggered only with right click or left click when Telegram window is active.

Configuration
MacBook Pro 2016 13", MacOS Mojave 10.14.6 (18G3005)
Telegram 1.9.10 Beta

**Comment by yulayula16** [comment]
Same issue affects Linux too.

**Telegram version:** 1.9.10 Beta
**OS:** Linux Mint 19.3

Whenever there's Telegram message counters on chats appear or disappear after being read the taskbar icon for Telegram disappears from view completely. I can go into the Settings to Disable and Enable the Taskbar Icon, but will immediately break when new messages come through and adds a counter to the icon for unread chats, and after reading them it still breaks. Red notification counters and Grey notification counters.

**Comment by ilya-fedin** [comment]
> Linux Mint 19.3

DE?

**Comment by yulayula16** [comment]
> > Linux Mint 19.3
> 
> DE?

Cinnamon Desktop

**Comment by ilya-fedin** [comment]
> Cinnamon Desktop

can't reproduce
![изображение](https://user-images.githubusercontent.com/17829319/74105854-79736680-4b59-11ea-95e8-b9895e917e98.png)

**Comment by ilya-fedin** [comment]
> Cinnamon Desktop

checked several times: can't reproduce. On a new message, on reading the new message: the icon stays
![изображение](https://user-images.githubusercontent.com/17829319/74106191-63b37080-4b5c-11ea-9256-2cae1a4e8dd9.png)

**Comment by yulayula16** [comment]
> > Cinnamon Desktop
> 
> checked several times: can't reproduce. On a new message, on reading the new message: the icon stays
> ![изображение](https://user-images.githubusercontent.com/17829319/74106191-63b37080-4b5c-11ea-9256-2cae1a4e8dd9.png)

You're probably not gonna get the same result running from VirtualBox like that. and just because you might not be able to reproduce it, others can, and in my case, it's 100% reproducible for any notification counter.

**Comment by ilya-fedin** [comment]
Anyway, this issue is about wrong displaying of tray context menu on macos ¯\_(ツ)_/¯
