### ISSUE TITLE
手机设置提示音不生效 Android Setting the prompt tone does not take effect

### ISSUE THREAD

**Issue by 1265578519** [telegramdesktop/tdesktop#7156]
![Screenshot_2020-02-07-07-13-03-889_org telegram m](https://user-images.githubusercontent.com/6442439/74073264-ae41c980-4a44-11ea-932b-b06bf01dd37e.png)
![Screenshot_2020-02-07-07-14-26-070_com android th](https://user-images.githubusercontent.com/6442439/74073265-b0a42380-4a44-11ea-8bbb-6f536995184a.png)
用系统自带的这些没有问题，提示音正常，自定义不行
There are no problems with the system's own, the prompt tone is normal, and customization is not possible

设置通话铃声，自定义正常工作
Set call temporary, custom work normally

**Comment by Aokromes** [comment]
this is telegram desktop, not telegram android.
