### ISSUE TITLE
Crash when change playback speed after video ends

### ISSUE THREAD

**Issue by Neurotoxin001** [telegramdesktop/tdesktop#7160]
### Steps to reproduce
1. open video
2. wait until video ends or just click on playback near end
3. change speed
4. crash

crash id:
f40987cc-dac7-487c-a912-3f65adf70928
d7cf659b-7c5c-452a-9e40-b4753955e6f9

### Configuration
**Operating system:** win 10 ltsc 1809

**Version of Telegram Desktop:** 1.9.10

**Used theme**: default dark

**Comment by john-preston** [comment]
@Neurotoxin001 Thank you for your report! This will be fixed in the next version.

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/7151
