### ISSUE TITLE
Unread message count badge no longer appears in Dash2Dock icon

### ISSUE THREAD

**Issue by ugtar** [telegramdesktop/tdesktop#7164]
The Dash2Dock icon always appears with no unread message count badge. I've noticed this since upgrading to 1.9.9 and it seems to be the case still on 1.9.10

### Configuration
**Operating system:**
Ubuntu 18.04.4, GNOME 3.28.2

**Version of Telegram Desktop:**
1.9.10-beta-3-g6cf9157fb installed from snap edge channel and
1.9.9-4-ga25792187 snap from stable channel

**Used theme**:
dark

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/7154 ?

**Comment by ilya-fedin** [comment]
The question is actual https://github.com/telegramdesktop/tdesktop/pull/7131#issuecomment-583870098

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/commit/77719750ee01910189c6717d70ee438ff8eaa40f

**Comment by ugtar** [comment]
fixed! thanks :+1:
