### ISSUE TITLE
Telegram Desktop: Telegram.exe - Bad Image

### ISSUE THREAD

**Issue by patgmiller** [telegramdesktop/tdesktop#7165]
### Steps to reproduce
1. Open Telegram
2. See Windows error: 

> TelegramDesktop: Telegram.exe - Bad Image. C:\Windows\System32\dataexchange.dll is either not designed to run on Windows or it contains an error. Try installing the program again using the original installation media or contact your system administrator or the software vendor for support. Error status 0xc0000020.

3. Also, every time a user messages this same error pops up.

### Expected behavior

One shouldn't see errors popping up while opening TelegramDesktop or when another user messages you.

### Actual behavior
Windows error pops up.

### Configuration
**Operating system:**
Windows 10 Home 1809 OS build: 17763.973
Intel Pentium J2900 @ 2.41 GHz 64-bit x64-based processor 8GB Ram 

**Version of Telegram Desktop:**
1.9.9 

**Used theme**: 
Not sure, probably the default, but I will confirm.

### Additional Information
I will look into getting logs associated with TelegramDesktop for this, but I did run a DirectX diagnostics based on search results for DataExchange.dll errors. Specifically this Microsoft article,  
about [dataexchange.dll errors](https://answers.microsoft.com/en-us/windows/forum/all/cwindowssystem32dataexchangedll-is-either-not/ebe4a54b-7dc5-4b62-8941-0f0f788f00e9).

**Attached dxdiag results**
[DxDiag-2020-02-09.txt](https://github.com/telegramdesktop/tdesktop/files/4177972/DxDiag-2020-02-09.txt)

**Comment by Aokromes** [comment]
try updating to 1.9.17

**Comment by Aokromes** [comment]
poke

**Comment by patgmiller** [comment]
@Aokromes this was for someone I was helping, I've instructed them to update to the latest 1.9.17, but they haven't been returning my messages. Either the update fixed it, or it's really not a priority for them. Thank you for your help.

**Comment by Kaktus1911** [comment]
Hi

I am getting the same Telegram.exe - Bad Image error since the last update....

br
