### ISSUE TITLE
Sinhala fonts are messed

### ISSUE THREAD

**Issue by eshan19997** [telegramdesktop/tdesktop#7167]
After the update Sinhala fonts have been changed on Telegram desktop they are very ugly and hard to read

[img]https://i.ibb.co/D5qYBMf/bug.jpg[/img]

TG version 1.9.9

windows 7 OS

**Comment by jeffythedragonslayer** [comment]
Possibly related to #7312

**Comment by Aokromes** [comment]
same bug of that and a lot more.
