### ISSUE TITLE
Telegram always crashed.

### ISSUE THREAD

**Issue by hang333** [telegramdesktop/tdesktop#7168]
### Steps to reproduce
1. Read the chat.
2. 
3. 

### Expected behaviour
Tell us what should happen

### Actual behaviour
Telegram Deskop crashed and exit.
It happens on me after v 1.8.15

### Configuration
**Operating system:** Windows 10 Version 1909 (OS Build 18363.476)

**Version of Telegram Desktop:** Telegram v1.9.10

**Used theme**:

<details><summary><b>Logs</b>:</summary>
ApiId: 2040
Assertion: Unexpected: Could not allocate! crash_reports.cpp:116
Binary: Telegram.exe
Launched: 10.02.2020 17:49:07
Platform: Windows
UserTag: 3083ae61dceaf9ab
Version: 1009010 beta
Memory-usage: 407 MB (peak), 406 MB (current)
Pagefile-usage: 326 MB (peak), 325 MB (current)

Google Breakpad caught a crash, minidump written in thread 19488
Minidump: f1c16f06-ab78-460f-90b8-1bb780370bda

Backtrace omitted.

</details>

**Comment by hang333** [comment]
[report.txt](https://github.com/telegramdesktop/tdesktop/files/4180106/report.txt)

**Comment by john-preston** [comment]
Can you please provide me with several latest crash dumps (from "tdata/dumps" folder near the Telegram.exe file)? You can upload them here or send them to me privately at t.me/preston.

**Comment by hang333** [comment]
![image](https://user-images.githubusercontent.com/3853064/74209447-c1fa6380-4cc2-11ea-9158-b4d165ac133c.png)
For unknown reason, all the dumps have zero content.

**Comment by hang333** [comment]
![image](https://user-images.githubusercontent.com/3853064/74218168-7a84cf00-4ce4-11ea-9b7d-ca9c921f4df9.png)

**Comment by Aokromes** [comment]
i suggest you to contact @preston on telegram maybe he can supply you one debug build.

**Comment by hang333** [comment]
Updated to v1.9.12, crashed when I click on a Image
```ApiId: 2040
Assertion: Unexpected: Qt FATAL message was generated! crash_reports.cpp:131
Binary: Telegram.exe
Launched: 12.02.2020 13:43:38
Platform: Windows
QtFatal: createDIB: CreateDIBSection failed (1920x1080, format: 6)
UserTag: 3083ae61dceaf9ab
Version: 1009012
Memory-usage: 424 MB (peak), 363 MB (current)
Pagefile-usage: 344 MB (peak), 283 MB (current)

Caught signal 11 (SIGSEGV) in thread 41424

Backtrace omitted.

Google Breakpad caught a crash, minidump written in thread 40844
Minidump: 3f346bd1-28a1-4bb9-9107-06fa51bd75ae

Backtrace omitted.
```
Dump is still 0kb.

**Comment by Aokromes** [comment]
try updating to 1.9.17

**Comment by hang333** [comment]
![image](https://user-images.githubusercontent.com/3853064/75206933-72339600-57b2-11ea-8239-4d68cd65b5df.png)
Crashed when loading pics.

**Comment by Aokromes** [comment]
has workaround, can you try downloading portable and save it into desktop and try doing same things? i wonder if your profile directory is corrupted.

**Comment by hang333** [comment]
Yeap, I always use portable edition.

**Comment by Aokromes** [comment]
and if you run it on c:\tdesktop ?

**Comment by hang333** [comment]
> and if you run it on c:\tdesktop ?

Same, but in v1.9.19
Crashed when open sticker menu.
```ApiId: 2040
Binary: Telegram.exe
Launched: 25.02.2020 22:57:53
Platform: Windows
UserTag: 16edae674e0d1d0e
Version: 1009019 beta
Memory-usage: 375 MB (peak), 308 MB (current)
Pagefile-usage: 305 MB (peak), 304 MB (current)

Google Breakpad caught a crash, minidump written in thread 50776
Minidump: 9f020813-40f2-41c6-9f81-fbc8c36cc8ec

Backtrace omitted.

Caught signal 22 (SIGABRT) in thread 45280

Backtrace omitted.
```

**Comment by Aokromes** [comment]
> > and if you run it on c:\tdesktop ?
> 
> Same, but in v1.9.19
> Crashed when open sticker menu.
> 
> ```
> Binary: Telegram.exe
> Launched: 25.02.2020 22:57:53
> Platform: Windows
> UserTag: 16edae674e0d1d0e
> Version: 1009019 beta
> Memory-usage: 375 MB (peak), 308 MB (current)
> Pagefile-usage: 305 MB (peak), 304 MB (current)
> 
> Google Breakpad caught a crash, minidump written in thread 50776
> Minidump: 9f020813-40f2-41c6-9f81-fbc8c36cc8ec
> 
> Backtrace omitted.
> 
> Caught signal 22 (SIGABRT) in thread 45280
> 
> Backtrace omitted.
> ```

can you try 1.9.20 beta?

**Comment by hang333** [comment]
> > > and if you run it on c:\tdesktop ?
> > 
> > 
> > Same, but in v1.9.19
> > Crashed when open sticker menu.
> > ```
> > Binary: Telegram.exe
> > Launched: 25.02.2020 22:57:53
> > Platform: Windows
> > UserTag: 16edae674e0d1d0e
> > Version: 1009019 beta
> > Memory-usage: 375 MB (peak), 308 MB (current)
> > Pagefile-usage: 305 MB (peak), 304 MB (current)
> > 
> > Google Breakpad caught a crash, minidump written in thread 50776
> > Minidump: 9f020813-40f2-41c6-9f81-fbc8c36cc8ec
> > 
> > Backtrace omitted.
> > 
> > Caught signal 22 (SIGABRT) in thread 45280
> > 
> > Backtrace omitted.
> > ```
> 
> can you try 1.9.20 beta?

No crash anymore, thanks.
