### ISSUE TITLE
Sudden Intermittent Crash

### ISSUE THREAD

**Issue by latiif** [telegramdesktop/tdesktop#7172]
### Steps to reproduce
0. Binary grabbed from Website directly (not via snap or some other package manger)
1. Sometimes (by typing into either Search bar or in a chat).

### Expected behaviour
Actually render the text I am typing and _NOT_ crash.

### Actual behaviour
Crashes immediately.

### Configuration
**Operating system:**
*OS* Mint 19.3 Tricia
*Kernel* x86_64 Linux 5.3.0-28 generic
*DE* Cinnamon 4.4.20 and XFCE 4.12

**Version of Telegram Desktop:**
Version 1.9.9

**Used theme**:
Built-in Tinted Theme
<details><summary><b>Logs</b> (obtained by running `grep "Telegram" /var/log/syslog`):</summary>
Feb 10 16:07:26 dell systemd-coredump[2097]: Process 2042 (Telegram) of user 1000 dumped core.#012#012Stack trace of thread 2042:#012#0  0x00007f43d7246e97 __GI_raise (libc.so.6)#012#1  0x00007f43d72488db __GI_abort (libc.so.6)#012#2  0x00007f43d7291897 __libc_message (libc.so.6)#012#3  0x00007f43d729890a malloc_printerr (libc.so.6)#012#4  0x00007f43d729fe1c _int_free (libc.so.6)#012#5  0x0000000000c76d22 n/a (/home/latiif/Programs/Telegram/Telegram)
</details>

**Comment by Aokromes** [comment]
plz try run telegram under gdb or if you don't get results under valgrind.

**Comment by RexNihil** [comment]
I've had this same issue, wherein Telegram Desktop intermittently quits while typing, no diacritics or anything odd, just randomly typing.

Ubuntu 18.04, installed via snap.
Telegram Desktop version 1.9.9

**Comment by latiif** [comment]
> plz try run telegram under gdb or if you don't get results under valgrind.

Could you elaborate on this?

**Comment by Aokromes** [comment]
gdb ./Telegram

**Comment by latiif** [comment]
> gdb ./Telegram

**THEN?** I have never debugged a binary with gdb before, so let me know what I should be on the look out for.

**Comment by Aokromes** [comment]
bt
bt full

pastebin result here.

**Comment by latiif** [comment]
Here is a [dump](https://pastebin.com/HvPFRejd).

I'll continue to use `gdb` and see what other logs I can get

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/7095
