### ISSUE TITLE
[Feature Request] Telegram for Windows 10 on ARM

### ISSUE THREAD

**Issue by phamwon** [telegramdesktop/tdesktop#7173]
### Is your feature request related to a problem?
Telegram x86 worked fine on Windows 10 on ARM, but it is runs a lot of RAM, more than Edge with 5 open tabs.

### Describe the solution you'd like
A build version for ARM64.

**Comment by theZasa** [comment]
Is there any way to know if/when this will happen?

**Comment by RememberTheAir** [comment]
@theZasa nope :(

**Comment by sunipkmukherjee** [comment]
It would be great to have a native WoA implementation of the already great Telegram Desktop app.

**Comment by matze19999** [comment]
don't close because nothing happend here by the developers yet

**Comment by tomcoleman** [comment]
can we please get this recompiled to include ARM64 so i can run it on my surface pro X without it killing the battery with emulation

**Comment by NerdyRedPanda** [comment]
An arm or arm64 build would be great since emulation is great but it is a little slower than non emulated apps so it would be ncie to not have to emulate telegram

**Comment by tomcoleman** [comment]
can someone download the opensource code and tick the option is visual studio to re-compile with arm support , maybe a fork?

Not sure why the official developers haven't done an arm build would take them like 5  seconds.

**Comment by matze19999** [comment]
> can someone download the opensource code and tick the option is visual studio to re-compile with arm support , maybe a fork?
> 
> Not sure why the official developers haven't done an arm build would take them like 5  seconds.

Because it doesn't take 5 seconds. All the depencies must also support arm(64).

**Comment by null-von-sushi** [comment]
> 
> 
> can we please get this recompiled to include ARM64 so i can run it on my surface pro X without it killing the battery with emulation

How did you even manage to install it?
I tried to install it, but I think they actually went through the effort of manually blocking it. 
Upon trying to run TG Desktop I get an error that it only works on 64bit processors.

And no, I did not enable 'hide x64 emulation capability'. So idk why it's failing unless Telegram chose to specifically block the install :/

**Comment by hathlife** [comment]
> > can we please get this recompiled to include ARM64 so i can run it on my surface pro X without it killing the battery with emulation
> 
> How did you even manage to install it? I tried to install it, but I think they actually went through the effort of manually blocking it. Upon trying to run TG Desktop I get an error that it only works on 64bit processors.
> 
> And no, I did not enable 'hide x64 emulation capability'. So idk why it's failing unless Telegram chose to specifically block the install :/

Use portable x64 version if you are using WoA 11. The experirence is not bad.

**Comment by null-von-sushi** [comment]
> 
> 
> > > can we please get this recompiled to include ARM64 so i can run it on my surface pro X without it killing the battery with emulation
> > 
> > 
> > How did you even manage to install it? I tried to install it, but I think they actually went through the effort of manually blocking it. Upon trying to run TG Desktop I get an error that it only works on 64bit processors.
> > And no, I did not enable 'hide x64 emulation capability'. So idk why it's failing unless Telegram chose to specifically block the install :/
> 
> Use portable x64 version if you are using WoA 11. The experirence is not bad.

It's not really usable for me as only English typing works, I cannot input Chinese :(

**Comment by hathlife** [comment]
> > > > can we please get this recompiled to include ARM64 so i can run it on my surface pro X without it killing the battery with emulation
> > > 
> > > 
> > > How did you even manage to install it? I tried to install it, but I think they actually went through the effort of manually blocking it. Upon trying to run TG Desktop I get an error that it only works on 64bit processors.
> > > And no, I did not enable 'hide x64 emulation capability'. So idk why it's failing unless Telegram chose to specifically block the install :/
> > 
> > 
> > Use portable x64 version if you are using WoA 11. The experirence is not bad.
> 
> It's not really usable for me as only English typing works, I cannot input Chinese though :(
![image](https://user-images.githubusercontent.com/19867269/141651531-1173638f-1a13-4bf3-9b2a-ce82a7295412.png)
MS pinyin ime works fine.

**Comment by null-von-sushi** [comment]
Yeah I tried it and pinyin works fine for me too, but for some random reason zhuyin does not.

**Comment by null-von-sushi** [comment]
not that this fixes anything, but I noticed Bopomofo does not work if you enable 'use previous version'. It works if you use the normal version, but that is missing options. I guess I should open a new bug for this, as it's a separate issue....
