### ISSUE TITLE
Chat administration features on mobile equal to desktop app

### ISSUE THREAD

**Issue by Intenditore** [telegramdesktop/tdesktop#7174]
As a admin of a few pretty popular chats I feel major pain when I can't administrate my chats from mobile app, Telegram X even. I can't even see "recent actions"! It's a shame
Please, add adequate and UNLIMITED chat settings and administrative features to your mobile apps!

**Comment by Aokromes** [comment]
sorry, this tracker is for native desktop, not android.

**Comment by john-preston** [comment]
@Intenditore They're present on official mobile apps for both iOS and Android.

**Comment by Intenditore** [comment]
> @Intenditore They're present on official mobile apps for both iOS and Android
I can't find them on BOTH



> 
> 
> sorry, this tracker is for native desktop, not android.

Can you lead me to an appropriate place?

**Comment by RememberTheAir** [comment]
@Intenditore questions about the Android app belong to the in-app support, or alternatively to Twitter (https://twitter.com/telegram)
