### ISSUE TITLE
Move "Chat management" to main "three dots" menu

### ISSUE THREAD

**Issue by Intenditore** [telegramdesktop/tdesktop#7175]
I'm always confused where to find the "chat management" in chat settings. It's messed up too much. I propose to move this menu item right to the "..." or "Chat info" menu

**Comment by RememberTheAir** [comment]
![image](https://user-images.githubusercontent.com/16143208/74171807-66cb6100-4c2f-11ea-9ea8-9126d73313f3.png)
It is already in the three dots menu. That's essentially the activity tdesktop opens when you click on the chat title. I guess you're talking about another thing?

**Comment by Aokromes** [comment]
no answer after months and like stated, it's already there, closing.
