### ISSUE TITLE
Last few seconds of written words get deleted roughly every minute.

### ISSUE THREAD

**Issue by TomNOYB** [telegramdesktop/tdesktop#7178]
### Steps to reproduce
1. Write a contact
2. Last words or complete sentence disappears
3. Get frustrated as this has been happening to me for over a year on multiple devices.

### Expected behaviour
Words should not disappear while writing.

### Actual behaviour
When I'm writing a text to a contact, suddenly the last words, or complete sentence disappears. It seems to be a timeframe in which the words disappear. So the faster you type, the more words are lost. 
In this reddit, they suppose it's due to a pc/mobile syncing problem in combination with a bad connection. 
https://www.reddit.com/r/Telegram/comments/8qojaa/words_being_deleted_while_typing_on_desktop/
I do use telegram mobile, however my internet connection is perfect and fast. 
I'm having the exact same issue on my pc and laptop.

### Configuration
**Operating system:** Windows 10

**Version of Telegram Desktop:** Always latest. Now 1.9.9

**Used theme**: No theme - night mode

<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

If I understand the issue, the solution would be for telegram to remember on which device the message has been written, and lock the ability to edit that message a few seconds longer on that device. That way, the message that has been synced from pc to mobile, will not suddenly sync back to the pc, and overwrite the 'newer' message there.

**Comment by Aokromes** [comment]
i am sure this is duplicate ticket....

**Comment by TomNOYB** [comment]
My apologies. I only just found a duplicate from beginning 2018.
Problem is, my internet is stable, and this issue has been here for years now. It's really driving me crazy.
For longer messages have have to write in a wordpad to then copy paste.

**Comment by Aokromes** [comment]
well, if it's open plz post there and close this.

**Comment by reallyuniquename** [comment]
@TomNOYB
Could you link the original issue?

**Comment by TomNOYB** [comment]
https://github.com/telegramdesktop/tdesktop/issues/2229
https://github.com/telegramdesktop/tdesktop/issues/4364
Not sure if they are the original, but I can't find any others.
Either way, the issue has been here for years.

**Comment by ilya-fedin** [comment]
I found opened ticket: #4492
