### ISSUE TITLE
No passcode entry field on start  in latest telegram update

### ISSUE THREAD

**Issue by codemeleon** [telegramdesktop/tdesktop#7179]
### Steps to reproduce
1. Start telegram
2. 
3. 

### Expected behaviour
I should be seeing passcode input filed
![66747823-e7a36780-ee9e-11e9-9d50-b0fdec0e8036](https://user-images.githubusercontent.com/7693569/74216442-28748700-4cad-11ea-8b18-a9fe975e5361.png)

### Actual behaviour
no Input field

![Screenshot_20200211_085734](https://user-images.githubusercontent.com/7693569/74216432-1f83b580-4cad-11ea-942d-9a24742e5e5e.png)

### Configuration
**Operating system:**
KDE Neon Testing Edition

**Version of Telegram Desktop:**
1.9.11

**Used theme**:
Night mode

<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by CB9TOIIIA** [comment]
YES // same problem

**Comment by Yazaedu** [comment]
Ubuntu 19.10
LXQt 0.14.1

same =(

**Comment by john-preston** [comment]
@codemeleon Yes, this is a regression with multi-monitor setup when the window is created not on the primary screen. If you plug out the second monitor and launch the app, it should be created on the main screen with field visible. I hope to fix that in the next version.

**Comment by john-preston** [comment]
@codemeleon As said in another issue, you can just drag the window to the main screen, resize it a bit, wait for several seconds and relaunch the app.

**Comment by codemeleon** [comment]
@john-preston First suggestion worked. However, second didn't.

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/commit/bcd0fe38f0ff6f5a45e33c97ae1d4865e6e4a998
