### ISSUE TITLE
[Feature Request] Reintroduce the option for the Media/Image Viewer to pan

### ISSUE THREAD

**Issue by Superbunnygirl** [telegramdesktop/tdesktop#718]
Telegram used to have the ability  to display uncompressed images at their normal size, in a mode that allowed for panning the image. This was avaliable in version 0.6.7 of Telegram desktop but was removed in later versions.
This video desmonstrates how the panning worked: (I have covered up the names of my contacts and chat groups for privacy)
http://a.pomf.se/omarfk.ogv

This was a great feature and It would be benefial to have it back, in its current form Telegram resizes the images (even uncompressed ones) to display them in the media viewer. This makes large  images difficult to view, especially on smaller resolutions.

Here is the "about" for the build I was using for the screencast.
![2015-05-15-004939_437x388_scrot](https://cloud.githubusercontent.com/assets/5305124/7647745/b11f5d74-fa9f-11e4-9973-7077e4de295c.png)

**Comment by auchri** [comment]
You can zoom with ctrl and +/-
