### ISSUE TITLE
[Feature Request] restore window position after close emoji panel

### ISSUE THREAD

**Issue by f242** [telegramdesktop/tdesktop#7183]
**CURRENT BEHAVIOUR**
![image](https://user-images.githubusercontent.com/10371194/74237419-94261680-4ce4-11ea-99b3-de4a9b612afe.png)
![image](https://user-images.githubusercontent.com/10371194/74237454-a6a05000-4ce4-11ea-8a5f-6a56923d832f.png)
![image](https://user-images.githubusercontent.com/10371194/74237470-af912180-4ce4-11ea-971a-cbe7dcd074ef.png)

**BETTER WHEN**
![image](https://user-images.githubusercontent.com/10371194/74237561-e7986480-4ce4-11ea-9bde-05d17ecc9869.png)
![image](https://user-images.githubusercontent.com/10371194/74237569-ed8e4580-4ce4-11ea-84ae-0ccaa0e4153e.png)
![image](https://user-images.githubusercontent.com/10371194/74237589-f252f980-4ce4-11ea-980c-f14690b3f4bc.png)

**Comment by john-preston** [comment]
Currently it closes without changing the window position. I'm not sure that this specific case should be handled differently. What if you moved the window?

**Comment by f242** [comment]
@john-preston every time when i close emoji panel i need to move window back to right corner manually, it's very inconvenient
