### ISSUE TITLE
Crash when opening a chat with an animated stickers

### ISSUE THREAD

**Issue by josecl200** [telegramdesktop/tdesktop#7185]
### Steps to reproduce
1. Click on a chat that has a recently sent animated sticker

### Expected behaviour
Chat should open normally without crashing

### Actual behaviour
The app crashes
### Configuration
**Operating system:**
Arch Linux with i3wm on Xorg
**Version of Telegram Desktop:**
1.9.9
**Used theme**:
Built-in tinted theme

**Comment by Aokromes** [comment]
plz next time you get a crash click send crash report and post id here, try also updating to 1.9.11 beta.
if you don't get a crash send window plz use gdb.

**Comment by Aokromes** [comment]
try updating to 1.9.17

**Comment by Aokromes** [comment]
@josecl200 can you try on 1.9.20?

**Comment by Aokromes** [comment]
no answer for more than 1 month, if this bug is still valid open a new ticket using one updated version downloaded from releases tab.
