### ISSUE TITLE
1.9.11 Freeze/Crash on file picker dialog

### ISSUE THREAD

**Issue by atis** [telegramdesktop/tdesktop#7186]
I had 2 freezes after choosing file. 
File picker doesn't close on choosing, but TG opens popup asking for description.
Issue appeared after last update

Ubuntu 18.04.3
Mate Desktop
Telegram 1.9.11 beta

**Comment by Aokromes** [comment]
plz, on next crash click send crash report and post id here, if you don't get send crash dialog, plz use gdb.

**Comment by atis** [comment]
Seems easy to reproduce, but so far the only message i got is:
`Gtk-Message: 23:11:21.467: GtkDialog mapped without a transient parent. This is discouraged.`

Will try gdb soon

**Comment by atis** [comment]
`(gdb) bt full
#0  0x00007f44ded32cf6 in __GI_ppoll (fds=0x7bbe9e8, nfds=4, timeout=<optimized out>, sigmask=0x0) at ../sysdeps/unix/sysv/linux/ppoll.c:39
        resultvar = 18446744073709551102
        sc_cancel_oldtype = 0
        tval = {tv_sec = 0, tv_nsec = 405012083}
`

Doesn't seem extremely useful. Any inspections i should try?

**Comment by mikhailnov** [comment]
@atis what do you see in `dmesg -T` after crashes?

**Comment by atis** [comment]
@mikhailnov nothing withing last hour (some USB disconnects before that)
It is not a real crash, as dialog stays open, and some minutes later window manager asks to kill it (killing telegram with it). I guess the dialog parent message is most related.

**Comment by mikhailnov** [comment]
`strace` will probably help you

**Comment by atis** [comment]
I couldn't find any GTK calls by running strace.

Problem still appears on 1.9.13

Seems that it is second call to file dialog that freezes, first always works.

**Comment by john-preston** [comment]
@atis Thanks for the report, I hope I'll fix that in the next version. For me this is indeed happening because of GTK file dialog mixed with Qt event loop (instead of Glib event loop).
