### ISSUE TITLE
Empty app password form

### ISSUE THREAD

**Issue by stryaponoff** [telegramdesktop/tdesktop#7188]
### Steps to reproduce
1. Run Telegram Desktop
2. See the bug

### Actual behaviour
Starting from yesterday, I can't use TDesktop because I can't enter 2FA password. There's an empty form. I've tried to download a new binary from telegram.org. It removed all my settings but it was working all day. Today I can't log in again.
![Снимок экрана от 2020-02-12 07-49-45](https://user-images.githubusercontent.com/3353718/74296027-f6c2f500-4d6c-11ea-9827-06f1764abee8.png)

### Configuration
Debian 10, GNOME 3.30.2

**Comment by Aokromes** [comment]
triplicate.

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/7179

**Comment by john-preston** [comment]
@stryaponoff Please move the app to the primary screen and then relaunch. This should be fixed in the next update, but I've removed it because of some problems. You can download it from the github releases page:

https://github.com/telegramdesktop/tdesktop/releases/tag/v1.9.12
