### ISSUE TITLE
1.9.12 win7 64 window size glitch on startup if fullscreen

### ISSUE THREAD

**Issue by imashxtyz** [telegramdesktop/tdesktop#7189]
If your telegram was fullscreen on close, it will be like on screenshot when started. You have to minimize, then restore, so it becomes windowed, than AGAIN minimize and restore to become fullscreen. If it was windowed everything is okay.

![1](https://user-images.githubusercontent.com/46919076/74309861-7f668300-4db7-11ea-88af-1b3ebf8550c4.PNG)

**Comment by peteski22** [comment]
It also seems to hang for a long time leaving a white rectangluar box in the middle of my desktop before eventually rendering. However I also get the issue you have with window size, but for me it's leaving huge white areas on the screen. Once it's all settled down, you can resize a few times to correct it, but it happens the next time you open Telegram too.

![image](https://user-images.githubusercontent.com/487783/74319084-45c15800-4d76-11ea-974f-feb993577534.png)

**Comment by Aokromes** [comment]
seriously guys, search before post bug, this is the 4th ticket for this bug, and it's on the 1st page.
https://i.imgur.com/g3VXGQF.png

**Comment by peteski22** [comment]
@Aokromes apology accepted ;)

**Comment by DIGIN4** [comment]
I'm having the same issue running Windows 10 home 64-bit and Intel UHD graphics 620
![Annotation 2020-02-12 140910](https://user-images.githubusercontent.com/5035329/74333778-47544580-4da1-11ea-94e3-de23d0e9822b.png)

**Comment by peteski22** [comment]
https://desktop.telegram.org/changelog isn't updated despite the new release being available which does fix this issue. Just a general question, is it worth referencing the issue # in the commit so it's clear why it was closed?
