### ISSUE TITLE
Autoplay (Limit by size) keeps sticking to 50MB when media download is disabled

### ISSUE THREAD

**Issue by yozachar** [telegramdesktop/tdesktop#7190]
### Steps to reproduce
1. Open `Settings` and navigate to `Advanced` options
2. Scroll down to `Automatic media download` section
3. Click on any of the 3 available options (`In private chats`, `In groups`, `In channels`)
4. Under `Autoplay` move the slider to any position, click `Save`.

### Expected behaviour
The selected slider position should be saved and visible in the UI.

### Actual behaviour
I don't know if it truly changes in backend, but at the UI, it sticks to `up to "50MB"`.

### Configuration
**Operating system:**
OS: Elementary OS 5.1 Hera
CPU: Intel i5 2nd Gen
GPU: NVIDIA GeForce GT 525M
Mem: 12GB

**Version of Telegram Desktop:**
1.9.9

**Used theme**:
Night + Green tint

**Screenshot**:
![Screenshot from 2020-02-12 16-04-07](https://user-images.githubusercontent.com/38415384/74328429-df5b2a80-4db3-11ea-902f-bc286ad09f54.png)

**Comment by john-preston** [comment]
@joe247 Maybe none of the media types are selected for autoplay? Then it is really saving zeros for all types.

**Comment by joe247** [comment]
> @joe247 Maybe none of the media types are selected for autoplay? Then it is really saving zeros for all types.

@john-preston thanks for the quick reply. I checked... and yes it's true. When no media is selected the two seek bar just resets to 10MB & 50MB.

But I think just disabling the seekbar with the set value will be better when no media is selected, than resetting them to 10MB & 50MB.

**Comment by john-preston** [comment]
@joe247 Yes, indeed.

**Comment by Aokromes** [comment]
this issue is still valid?

**Comment by joe733** [comment]
@Aokromes yes, I just tested it on 2.1.8 (beta). The issue still exists. The proposed idea for the solution is: https://github.com/telegramdesktop/tdesktop/issues/7190#issuecomment-585210951

> But I think just disabling the seek-bar with the (user) set value will be better when no media is selected, than resetting them to 10MB & 50MB.

**Comment by joe733** [comment]
@stalebot the issue still exists on `v2.4.4`

By the way I've another abstract idea about the solution.

> If the slider is set to `0` then the corresponding toggle button automatically switches off. But this mean to have at least 3 more sliders, one for each media type and a bunch of code for that logic.

![Screenshot from 2020-10-25 07-13-18](https://user-images.githubusercontent.com/38415384/97096978-d84e2100-1691-11eb-95b8-0b15e162df94.png)

**Comment by joe733** [comment]
Issue exists in `v2.4.14`

**Comment by joe733** [comment]
Still on `2.5.8`

**Comment by joe733** [comment]
Still a bug in `v4.1`

![Peek 2022-08-17 08-15](https://user-images.githubusercontent.com/38415384/185023347-85c6bd92-6ff9-4288-9641-9fecfea9a97a.gif)

**Comment by yozachar** [comment]
Still present in `v4.11.1`
