### ISSUE TITLE
2.1 win7 x64 video delete "The action can't be completed because the file is open in Telegram Desktop"

### ISSUE THREAD

**Issue by imashxtyz** [telegramdesktop/tdesktop#7191]
After you send gif/video you can't delete it from your PC because "The action can't be completed because the file is open in Telegram Desktop", you have to close telegram every time, delete the file you just sent and reopen telegram. This wasn't an issue few versions before, so I guess this is a bug.

**Comment by Asgoret** [comment]
Same story. I can`t download or send files becaus TG can`t open file manager and I can`t decline this action because TG is not active.

**Comment by jeffythedragonslayer** [comment]
Sounds like a file handle leak.

**Comment by Aokromes** [comment]
plz test on 1.9.20 beta.

**Comment by Aokromes** [comment]
poke.

**Comment by imashxtyz** [comment]
@Aokromes it's 2.0 already and the issue is still there
