### ISSUE TITLE
[Feature Request] Shortcuts to ease navigation around tdesktop

### ISSUE THREAD

**Issue by Jzarecta** [telegramdesktop/tdesktop#7194]
### Is your feature request related to a problem?
Add shortcuts to navite to the app different areas

### Describe the solution you'd like
Add a shortcut menu that allows to move around the app

### Describe alternatives you've considered
Ctrl-Shift-F to go to the global search for different channels, 
Ctrl-F to search inside the active chat
Tab to browse through the channels and groups on the right section of the app
_Alternatively_ do a vim-gmail type navigation where **j k** browse through posts, and **n p** browse through groups.
Shift-Up/RePag to go up on the chat window.

### Additional context
Probably add a shortcut cheatsheet like ? will display the shortcut map

**Comment by dreua** [comment]
Are you aware of this: https://github.com/telegramdesktop/tdesktop/wiki/Keyboard-Shortcuts ?
I second some built in shortcut map, should be another issue or issue title though.

**Comment by KoalaBear84** [comment]
OK, I would really like to have keyboard accessibility on the popups.

**Comment by dreua** [comment]
For an in app shortcut map, see my feature request #7639 .

I'd recommend to reword this issue to something that is not covered in other issues or closing it to avoid duplication and confusion.

**Comment by Sominemo** [comment]
Still relevant. Super relevant

**Comment by ilya-fedin** [comment]
#1060
