### ISSUE TITLE
Badge Counter not disabled on Linux

### ISSUE THREAD

**Issue by varlesh** [telegramdesktop/tdesktop#7196]
### Steps to reproduce
1. open **Settings-Notifications-Badge Counter**
2. disable **Count unread messages**
3. badge show on tray
4. restart app not solve problem

### Expected behaviour
Badge Counter should turn off

### Actual behaviour
Badge Counter showed

### Configuration
**Operating system:**
- Linux KDE Neon (Ubuntu 18.04)
- used QSystemTray (also with libappindicator this reproduced too)

**Version of Telegram Desktop:**
1.9.13
**Used theme**:
none
![image](https://user-images.githubusercontent.com/8083855/74411472-b8a10080-4e54-11ea-8ecb-23ab342ad78e.png)

**Comment by ilya-fedin** [comment]
`Count unread messages` setting switches between chat and messages counting, as far as I know.
