### ISSUE TITLE
[linux] file picker dialog does not close

### ISSUE THREAD

**Issue by MBoldyrev** [telegramdesktop/tdesktop#7198]
### Steps to reproduce
1. open a chat
2. click the clip icon
3. pick any file

### Expected behaviour
File chooser dialog closed. User can send more files by repeating the procedure.

### Actual behaviour
File picker dialog stays. If I forcefully close the file picker dialog and try sending a file again, Telegram crashes.

### Configuration
**Operating system:** Debian 10.

**Version of Telegram Desktop:** 1.9.13

**Used theme**: Night

<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by john-preston** [comment]
@MBoldyrev Thanks for your report! This will be fixed in the next version.

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/7186#issuecomment-585640042 https://github.com/telegramdesktop/tdesktop/commit/7bf2b607f92de40fabf840e348d986509ef2c00a
