### ISSUE TITLE
Mentions seems to tag ANYONE globally, even accounts outside of the conversation.

### ISSUE THREAD

**Issue by lindhe** [telegramdesktop/tdesktop#720]
Fortunately no notification is sent, but if I write @example in any chat (I've tried regular chats and groupchats. Secret chats are yet to be confirmed) @example will become a link to @example's profile even if that account neither is in the conversation nor in the senders contacts list.

This could be a privacy concern (any account can be identified without any notice to the user mentioned). 

Feel free to test it by mentioning my username @Lindhe. I give my consent for you to mention me in telegram chats for testing purposes.

**Comment by ErikThorsell** [comment]
I have tested the CLI-version as well, and one cannot see if one has been mentioned in a chat where one is not active.

**Comment by lindhe** [comment]
Also I can comfirm this behaviour in secret chats as well.

**Comment by ppparadox** [comment]
+1 ugly
