### ISSUE TITLE
Telegram Freezes when uploading file

### ISSUE THREAD

**Issue by slumbergod** [telegramdesktop/tdesktop#7200]
### Steps to reproduce
1. Click on File Upload icon
2. Select File
3. Random freeze requiring forced quit of application

### Expected behaviour
Tell us what should happen
The selected file should be accepted and the file upload dialog box disappears.

### Actual behaviour
Tell us what happens instead
The dialog box freezes. The file cannot be selected. The whole application becomes unresponsive. Not everytime. It's one of those random issues. 

### Configuration
**Operating system:**
Xubuntu 18.04.04
**Version of Telegram Desktop:**
1.9.13
**Used theme**:
Tinted
<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/7186#issuecomment-585640042 https://github.com/telegramdesktop/tdesktop/commit/7bf2b607f92de40fabf840e348d986509ef2c00a
