### ISSUE TITLE
Slow load at start

### ISSUE THREAD

**Issue by WrongBit** [telegramdesktop/tdesktop#7202]
Hi!
When I start messenger, it stays for a long time completely empty. WHAT is going on during that time?  It looks like you load everything and only then show me my list of people. It's BAD, ineffective decision.

At start you have to load ONLY contacts (means names) - it's fast. Then user most likely click one contact to send a message - let him to (type and) send a message! And only THEN load all history for this account. Later you can load history for other account (what is unnecessary actually).

**Comment by maxoku** [comment]
It doesn't rather load whole history, only the last message for all chats. Nevertheless it does do that very long which is annoying. If it can't do it quickly then it should store this basic data locally for quick access (startup).

**Comment by WrongBit** [comment]
I got why it starts slow, but cannot understand HOW I can improve it.
In any case there is word 'thread' which is known for 40 years. Why not just use it?? Why I should wait until clumsy code loads all messages? Just show me IMMEDIATELY all my contacts - that's enough. And ONLY when I select one of 'em - ok, show me CACHED history and start SEPERATE THREAD to refresh messages. Is it so hard to do?

**Comment by maxoku** [comment]
We users can only wait when (if) it will be resolved. I don't really think it's something hard to do, but the developer is rather not interested to do it.

**Comment by Aokromes** [comment]
> We users can only wait when (if) it will be resolved. I don't really think it's something hard to do, but the developer is rather not interested to do it.

preston fixed already few bugs making telegram to start slowly.

**Comment by WrongBit** [comment]
@Aokromes : hey, I see the difference! Now it starts practically immediately! THANKS PRESTON! :) The only confusing point is why it wasn't done before? It's really annoying when you quickly need to send a message, but wait, looking at empty window.

**Comment by Aokromes** [comment]
> @Aokromes : hey, I see the difference! Now it starts practically immediately! THANKS PRESTON! :) The only confusing point is why it wasn't done before? It's really annoying when you quickly need to send a message, but wait, looking at empty window.

a single dev working trying to fix to much bugs on 3 complete different platforms.

**Comment by maxoku** [comment]
Really? It does load little faster, but still not immediately for me. I appreciate fixing bugs though. Fixing bugs is a hard job, but I would also appreciate new functions that improve use of application.

**Comment by WrongBit** [comment]
@maxoku : It's not a "little". I specially test it (Win7x64). I exit Telegram and started - window was shown and after 3 seconds I see all my contacts. I think 3 seconds is OK. Previously I waited more than 10 sec!

**Comment by maxoku** [comment]
Well, I guess it depends from the net speed how fast it would appear, while previously seems there was a bug that delayed that. Nevertheless it's not a first time I'm mentioning about storing some basic data locally that it would be loaded immediately.

**Comment by WrongBit** [comment]
@maxoku Completely agree. Professional code will:

1. Load address book from local cache
2. Sync book with remote server
3. Load last 3 messages from the cache in the separate thread
4. ONLY when contact is selected, sync his history with the server, again in a separate thread. Obviously that "fresh history" has lowest priority, because you start new chat session.

I hope current code does at least half of that. :)
