### ISSUE TITLE
300% Scale issue on 4K second display.

### ISSUE THREAD

**Issue by Kolyan4ik95** [telegramdesktop/tdesktop#7206]
### Steps to reproduce
1. It must be 4k resolution display and FullHD display.
2. Set on 4k Display Setting Scale and Layout value 300%. (right click on Desktop > Display Settings > Scale and Layout )
3. Set FullHD display as main.
4. Run Telegram.
5. Drug'n'Drop Telegram to 4k. UI comes small and unreadeble.
![image](https://user-images.githubusercontent.com/39876997/74545382-d7d58600-4f59-11ea-85ec-e7fa5f1f6952.png)

6. Also you can open Telegram on 4k main display and move it to FullHD. UI comes huge and unreadeble too. But it is button shown with 100% UI scale. 

### Expected behaviour
App must change automatically UI scale according to the settings of current disply in Windows. 

### Actual behaviour
APP Ui comes very small or very big with unreadeble text and unreachable UI controls. 

### Configuration
Operating system: Windows 10 Pro, x64
Version of Telegram Desktop: 1.9.7
Used theme: Dark

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/1121
