### ISSUE TITLE
[Feature Request] Add read marker on dialogues when the sidebar is collapsed

### ISSUE THREAD

**Issue by WofWca** [telegramdesktop/tdesktop#7208]
### Is your feature request related to a problem?
Cannot see whether messages have been read when the dialogs sidebar is collapsed.

![1](https://user-images.githubusercontent.com/39462442/74583944-dbbfe180-5007-11ea-9b0c-c503bf36460a.png)

### Describe the solution you'd like
Add read markers, like with the "online" marker:

![2](https://user-images.githubusercontent.com/39462442/74583955-ff832780-5007-11ea-8dfa-f8d38b6059c7.png) ![3](https://user-images.githubusercontent.com/39462442/74583957-01e58180-5008-11ea-9459-384e52f3ae7b.png)

I don't say this is the best design, but you get the idea.

**Comment by Aokromes** [comment]
well, you have the amount of unread messages .....

**Comment by WofWca** [comment]
> well, you have the amount of unread messages .....

It wouldn't let me know whether a message has been read in case they didn't respond though.
