### ISSUE TITLE
File chooser freeze

### ISSUE THREAD

**Issue by uglynakedguy** [telegramdesktop/tdesktop#7210]
### Steps to reproduce
1. First time (once telegram app started) click on "paperclip" button opens file chooser. Sending any file is ok at this step.
2. But second attempt (and any attempt further) leads to freeze of file-chooser window if we click on any of two buttons "Open" or "Cancel".
3. Restarting telegram app helps, but here we go to step 1 and 2.

### Expected behaviour
Before last 2 (or maybe 3) updates sending files worked like a charm.
And file-chooser works fine at any other application.
### Configuration
**Operating system:**
OS: Arch Linux
Kernel: x86_64 Linux 5.5.3-arch1-1
GTK Theme: Adwaita [GTK2/3]
Window Manager: i3-gaps

**Version of Telegram Desktop:**
1.9.13 (official package https://telegram.org/dl/desktop/linux)

P.S. The Arch Linux repo package has no this issue, but it has its own file-chooser, and has no update option inside the app Settings.

Log.txt file has nothing about this issue.

**Comment by Aokromes** [comment]
the 4th ticket on a row for this....
