### ISSUE TITLE
Download directory cannot be selected.

### ISSUE THREAD

**Issue by qg0** [telegramdesktop/tdesktop#7211]
Telegram version 1.9.13
OS: OpenSUSE Tumbleweed Linux 5.5.2-1-default #1 SMP Sat Feb 8 07:54:02 UTC 2020 (994cf1f) x86_64 x86_64 x86_64 GNU/Linux
KDE Plasma 5

I want to change the download path from "**~/downloads/Telegram Desktop**" to just "**~/downloads**".

I choose **Settings -> Advanced -> "Download path" -> "Custom folder, cleared only manually"**

![image](https://user-images.githubusercontent.com/919099/74585377-83d8a900-500e-11ea-8f1b-b0c08e8f3aca.png)

There is only button "**Open**", not "Choose" or "Select".

![image](https://user-images.githubusercontent.com/919099/74585384-a36fd180-500e-11ea-9e93-49dfe419864d.png)

Then I fall into the subdirectories until I get to some **file**. i.e. the app would "save" downloaded files to a **file**.

![image](https://user-images.githubusercontent.com/919099/74585432-2db83580-500f-11ea-9d9e-d06722c85d1b.png)

Fo example, here "**/etc/hosts**" is a **file**, **not a directory**.

**Comment by Jeronimo17** [comment]
Also when downloading a file the default name now appears blank

**Comment by Giando** [comment]
**Same problem**: unable to download files to non-default folder.

### Configuration
**Operating system:** Debian GNU/Linux 9.12 (stretch)
**Version of Telegram Desktop:** 1.9.13
**Used theme**: [Fasano](https://t.me/addtheme/Fasano)

**Comment by ilya-fedin** [comment]
First of all, #7211 #7212 #7226 (and #7230, most likely) have the one cause. I propose to discuss them all here.
Telegram started to use xdg desktop portals on the static binary to use native file dialogs (gtk for gtk-based DEs and KDE for KDE)
I tested on NixOS and Ubuntu, the first has xdg-desktop-portal**-gtk** with version 1.4.0 and doesn't have the issue. The second has xdg-desktop-portal**-gtk** with version 1.0.7 and does have the issue. xdg-desktop-portal**-kde** doesn't have the issue at all. This should be reported to Ubuntu, but I have no idea how to it. :(

**Comment by qg0** [comment]
> KDE for KDE

KTorrent in KDE:

![image](https://user-images.githubusercontent.com/919099/74732177-411c0880-527c-11ea-8dfd-c763bb0946d6.png)

Telegram in KDE with XDG:

![image](https://user-images.githubusercontent.com/919099/74732230-63ae2180-527c-11ea-8ca1-05a2ed568b5e.png)

**Comment by ilya-fedin** [comment]
@qg0 you don't have xdg-desktop-portal-kde installed, I guess. :)

**Comment by Giando** [comment]
:warning: Even with the release of the latest version [v1.9.14](/telegramdesktop/tdesktop/releases/tag/v1.9.14) of @john-preston the problem persists. :warning:

**Comment by john-preston** [comment]
@Giando Do other file choosing options in tdesktop work, like choosing photos or files for sending?

**Comment by qg0** [comment]
> @Giando Do other file choosing options in tdesktop work, like choosing photos or files for sending?

Yes. Just attached the file (xdg).

**Comment by Giando** [comment]
> @Giando Do other file choosing options in tdesktop work, like choosing photos or files for sending?

Of course, no problem with sending files, only with downloading to the non-default folder.

**Comment by qg0** [comment]
> @qg0 you don't have xdg-desktop-portal-kde installed, I guess. :)

It was installed: xdg-desktop-portal-kde 5.18.0-1.1. But the opening window is still "native xdg".

**Comment by ilya-fedin** [comment]
> It was installed: xdg-desktop-portal-kde 5.18.0-1.1.

Did you forgot to relogin?

**Comment by qg0** [comment]
> > It was installed: xdg-desktop-portal-kde 5.18.0-1.1.
> 
> Did you forget to relogin?

It was installed since the first installation of distro many years ago, not now. Yes, I relogged even now. The problem is still exist.

**Comment by ilya-fedin** [comment]
> It was installed since the first installation of distro many years ago, not now.

So, xdg-desktop-portal prefers xdg-desktop-portal-gtk for some reason. Try to remove xdg-desktop-portal-gtk.

**Comment by qg0** [comment]
> > It was installed since the first installation of distro many years ago, not now.
> 
> So, xdg-desktop-portal prefers xdg-desktop-portal-gtk for some reason. Try to remove xdg-desktop-portal-gtk.

Just deleted the xdg-desktop-portal-gtk. Now it's the kde-like window. But the problem is the same. Telegram wants a file instead of a directory when I choose the download path.
Telegram version 1.9.14.

**Comment by ilya-fedin** [comment]
> But the problem is the same.

¯\_(ツ)_/¯
https://github.com/flatpak/xdg-desktop-portal/issues
https://github.com/flatpak/xdg-desktop-portal-gtk/issues
https://github.com/KDE/xdg-desktop-portal-kde (issues are disabled)

**Comment by qg0** [comment]
Here is a problem with [xdg-desktop-portal](https://github.com/flatpak/xdg-desktop-portal/issues/200).

**Comment by IlyaBizyaev** [comment]
> https://github.com/KDE/xdg-desktop-portal-kde (issues are disabled)

https://bugs.kde.org/buglist.cgi?component=general&product=xdg-desktop-portal-kde
