### ISSUE TITLE
toggle window maximize makes messages positioned left instead of right

### ISSUE THREAD

**Issue by mxdpeep** [telegramdesktop/tdesktop#7213]
### Steps to reproduce
1. toggle maximize
2. 
3. 

### Expected behaviour
my own messages positioned to the right

### Actual behaviour
my own messages positioned to the left

### Configuration
**Operating system:** Ubuntu 18.04.4 LTS

**Version of Telegram Desktop:** 1.9.13

**Used theme**: dark

**Comment by Aokromes** [comment]
not a bug, intended. you can disable adaptive layout on chat settings.
