### ISSUE TITLE
File dialogue does not handle symlinks correctly

### ISSUE THREAD

**Issue by karlsebal** [telegramdesktop/tdesktop#7214]
When attaching a file in telegram-desktop, symlinks are not followed but displayed as file when the destination is on a different device.

```shell
~/test$ df|awk '{print $1 "at" $6}'
[…]
/dev/sda3 at /
/dev/sdb4 at /store
[…]

~/test$ ls -l
lrwxrwxrwx 1 k k 13 Feb 15 13:50 Downloads -> ../Downloads/
lrwxrwxrwx 1 k k  6 Feb 15 13:50 store -> /store

:~/test$ realpath *
/home/k/Downloads
/store
```

So we have symlinks for the 2 folders but only the one located on `/dev/sda3` is displayed correctly and accessible via attachment dialogue.

![Bildschirmfoto von 2020-02-15 13-52-04](https://user-images.githubusercontent.com/10451995/74588204-b8426a00-4ffa-11ea-84c3-0de5a19c6472.png)

Telegram Desktop Version is 1.9.9, OS is Ubuntu Bionic 18.04

**Comment by ilya-fedin** [comment]
> So we have symlinks for the 2 folders but only the one located on `/dev/sda3` is displayed correctly and accessible via attachment dialogue.

Dialog is not a part of tdesktop, it's gtk...
I think your issue is slightly not by address...
