### ISSUE TITLE
Can't disable autoupdate

### ISSUE THREAD

**Issue by slumbergod** [telegramdesktop/tdesktop#7215]
### Steps to reproduce
1. Delete the installed version of Telegram
2. Extract the desire version from the archive and copy it to its destination
3. Start Telegram and enter the details to add your account
4. Rush into Advanced settings and disable autoupdate
5. Doesn't matter because it autoupdates to the latest broken version (1.9.13) anyway
6. Tried 5 times and no matter what I do I end up with the buggy version that is unusable for uploading files (another bug post)

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead
Autoupdate should not be set by default!!!!!!!
### Configuration
**Operating system:**
Xubuntu 18.04.4
**Version of Telegram Desktop:**
I want 1.9.12 but I keep getting the broken 1.9.13
**Used theme**:

<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by gagangulyani** [comment]
Does it check for existing config files and use them for setting Auto Update?

**Comment by jeffythedragonslayer** [comment]
FYI, autoupdate appears to be unimplemented on Marjaro.  The "Telegram Desktop was updated to version 1.9.14" service notification didn't appear until I ran "sudo pacman -Syu"

**Comment by ilya-fedin** [comment]
> FYI, autoupdate appears to be unimplemented on Marjaro.

Autoupdate is present only on official binaries :)
