### ISSUE TITLE
[Question] A few questions about the latest update

### ISSUE THREAD

**Issue by Khomyak-sibiryak** [telegramdesktop/tdesktop#7217]
Hello!

After updating the client to version 1.9.13, the ability to use custom icons for the tray was lost, for example, [these](https://github.com/senid231/kde_4k_telegram_tray_icons/).

When I right-click on the tray icon, I see that now the application uses its own theme for this, as well as animation.

I do not like that now the client stands out from the system as soon as he can. Is it possible to return the old behavior?

Archlinux, Xfce.

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/7192

**Comment by Khomyak-sibiryak** [comment]
There is no answer to the second question, but it is already closed. Awesome!
