### ISSUE TITLE
[Feature Request] Sane dir names for export

### ISSUE THREAD

**Issue by maksimotstavnov** [telegramdesktop/tdesktop#7219]
Currently, chats are exported to facelessly named directories like ```Chat01 .. Chat99```. 

It would be nice to have an option of more meaningful naming the dirs, perhaps with the names of the chats/groups included in the dir names.

**Comment by spassiba** [comment]
UP. Voting for this feature. That would be nice to have.

**Comment by reallyuniquename** [comment]
Yes, please.
