### ISSUE TITLE
Hi all! in my telegram, when playing a video, the timings on the control panel are cut off.

### ISSUE THREAD

**Issue by IPPON-47** [telegramdesktop/tdesktop#7221]
### Steps to reproduce
1. telegram start
2. telegram start video
3. 

### Expected behaviour
video control panel ok

### Actual behaviour
video control panel is bad

### Configuration
**Operating system:  Linux Rosa**

**Version of Telegram Desktop: v 1.9.13**

**Used theme**: Hi all! in my telegram, when playing a video, the timings on the control panel are cut off.  if you are comfortable, then I can speak Russian. Thanks!
![снимок104](https://user-images.githubusercontent.com/61110563/74603856-c490fa80-50c0-11ea-862c-d283abfa8e0f.jpeg)

<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by ilya-fedin** [comment]
If you're using a package from your distribution, please check that it depends on open sans font, since UI is designed only for Open Sans.
If it doesn't depend, this is packaging issue and you should report to the maintainer.

**Comment by Aokromes** [comment]
@IPPON-47

**Comment by Aokromes** [comment]
@IPPON-47

**Comment by Aokromes** [comment]
no answer after more than 1 month, closing.
