### ISSUE TITLE
telegram window size reduce automatically

### ISSUE THREAD

**Issue by nasaboy** [telegramdesktop/tdesktop#7222]
### Steps to reproduce
1. Quit telegram completely
2. Open telegram
3. repeat step1and step2

### Expected behaviour
The window size should be the same size as the last time it was opened

### Actual behaviour
telegram window size reduce automatically
The size of the window will shrink automatically, each time it is closed and then opened again, until it shrinks to a certain extent
### Configuration
**Operating system:**
windows10 1909 18363.657
**Version of Telegram Desktop:**
1.9.13 portable
**Used theme**:
default
<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
[log.txt](https://github.com/telegramdesktop/tdesktop/files/4210002/log.txt)
</details>

**Comment by nasaboy** [comment]
@john-preston can you fix it ? please

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/1189
