### ISSUE TITLE
FFmpeg media code should use higher image alignment

### ISSUE THREAD

**Issue by sfan5** [telegramdesktop/tdesktop#7225]
Internally, FFmpeg uses an alignment of up to 64:
https://github.com/FFmpeg/FFmpeg/blob/17ece3f74531cca47a8b90f905f5160fc3fa6ac0/libavutil/mem.c#L64

The code in tdesktop uses only 16:
https://github.com/telegramdesktop/tdesktop/blob/3bb9e8c7ebe6e17675fea0d702bf234319af1a9a/Telegram/SourceFiles/ffmpeg/ffmpeg_utility.cpp#L26

This appears to be cause of memory corruption crashes when playing some(?) GIFs and/or videos.
I have tested changing `kAlignImageBy` to 64 and can't reproduce such crashes anymore.

Here's how such a crash looks (reproduced on Telegram Desktop 1.9.13):
<pre>
$ telegram-desktop
double free or corruption (out)
malloc(): invalid size (unsorted)
zsh: abort (core dumped)  telegram-desktop
</pre>

**Comment by john-preston** [comment]
@sfan5 Thanks! I'll change to 64.
