### ISSUE TITLE
save as image issue

### ISSUE THREAD

**Issue by mahdi-moradi** [telegramdesktop/tdesktop#7228]
### Steps to reproduce
1. right-click on an image
2. show 'Open window dialog'
3. 

### Expected behaviour
show 'Save window dialog' and set the name of file

### Actual behaviour
show 'Open window dialog' and empty name field !!!

### Configuration
**Operating system:** Ubuntu 18.04.4 LTS

**Version of Telegram Desktop:** 1.9.13

**Used theme**: Dark

**Comment by Aokromes** [comment]
try updating to 1.9.17

**Comment by andriy85if** [comment]
> try updating to 1.9.17

I'm having the same problem on Linux Mint Cinnamon 19.3

The latest available version of Telegram 1.9.14 is installed

Are you suggesting to upgrade Telegram to Beta to test?

**Comment by Aokromes** [comment]
> > try updating to 1.9.17
> 
> I'm having the same problem on Linux Mint Cinnamon 19.3
> 
> The latest available version of Telegram 1.9.14 is installed
> 
> Are you suggesting to update Telegram to Beta to test?

yes

**Comment by andriy85if** [comment]
> > > try updating to 1.9.17
> > 
> > 
> > I'm having the same problem on Linux Mint Cinnamon 19.3
> > The latest available version of Telegram 1.9.14 is installed
> > Are you suggesting to update Telegram to Beta to test?
> 
> yes

I have updated Telegram to Beta 1.9.19. There is no problem. Saving files and pictures works well. I am waiting for the fix in the main version. Thank you!
