### ISSUE TITLE
Does not open the dialog window in attach file button

### ISSUE THREAD

**Issue by dognew** [telegramdesktop/tdesktop#7230]
### Steps to reproduce
1. Left-click  in attach file button (Clip button)

### Expected behaviour
Open file dialog.

### Actual behaviour
Does not open the dialog window.

### Configuration
**Operating system:**
Linux Mint 18
Xfce 64bits

**Version of Telegram Desktop:**
1.9.13
**Used theme**:
Night

**Comment by Aokromes** [comment]
x-duplicated. will be fixed on .14

**Comment by ilya-fedin** [comment]
@Aokromes i think it is a completely different issue...
@dognew can you say which of these package you have installed?
* xdg-desktop-porral
* xdg-desktop-portal-gtk
* xdg-desktop-portal-kde

**Comment by dognew** [comment]
> * xdg-desktop-porral
> * xdg-desktop-portal-gtk

Installed. Button with no action. In previous versions it worked correctly.

**Comment by ilya-fedin** [comment]
> but the same problem continued

Did you forget to relogin?

**Comment by dognew** [comment]
> > but the same problem continued
> 
> Did you forget to relogin?

Resolved the problem. I logout and login again.
