### ISSUE TITLE
Errors when configure QT, ERROR: Feature 'openssl-linked' was enabled, but the pre-condition '!features.securetransport && libs.openssl' failed.

### ISSUE THREAD

**Issue by robinfoxnan** [telegramdesktop/tdesktop#7231]
vs2017, chinese version, win10,

When i come to the code:
configure -prefix "%LibrariesPath%\Qt-5.12.5" -debug-and-release -force-debug-info -opensource -confirm-license -static -static-runtime -I "%LibrariesPath%\openssl_1_1_1\include" -no-opengl -openssl-linked OPENSSL_LIBS_DEBUG="%LibrariesPath%\openssl_1_1_1\out32.dbg\libssl.lib %LibrariesPath%\openssl_1_1_1\out32.dbg\libcrypto.lib Ws2_32.lib Gdi32.lib Advapi32.lib Crypt32.lib User32.lib" OPENSSL_LIBS_RELEASE="%LibrariesPath%\openssl_1_1_1\out32\libssl.lib %LibrariesPath%\openssl_1_1_1\out32\libcrypto.lib Ws2_32.lib Gdi32.lib Advapi32.lib Crypt32.lib User32.lib" -mp -nomake examples -nomake tests -platform win32-msvc

i meet some Errors like this :

ERROR: Feature 'openssl-linked' was enabled, but the pre-condition '!features.securetransport && libs.openssl' failed.
[config.log](https://github.com/telegramdesktop/tdesktop/files/4217954/config.log)

i tried many ways, but did not work

**Comment by john-preston** [comment]
@robinfoxnan Maybe you forgot to set LibrariesPath in the same command line session that you run this command?

**Comment by robinfoxnan** [comment]
@john-preston Thanks, 
I tried many kinds of cmd, but still meet the error,
at last ,  i go to the qt officical website, i download all the zip of 12.5.0,
unzip, then everything is ok now,
so , Maybe something is missing when  execute the cmd of 
    "perl init-repository --module-subset=qtbase,qtimageformats
      git checkout v5.12.5
      git submodule update qtbase
      git submodule update qtimageformats"

I will try with some more modules

**Comment by undrfined** [comment]
@robinfoxnan I've stumbled upon the same problem. Deleting `config.cache` and rerunning `configure` worked for me.

**Comment by SinaXhpm** [comment]
> 
> 
> @john-preston Thanks,
> I tried many kinds of cmd, but still meet the error,
> at last , i go to the qt officical website, i download all the zip of 12.5.0,
> unzip, then everything is ok now,
> so , Maybe something is missing when execute the cmd of
> "perl init-repository --module-subset=qtbase,qtimageformats
> git checkout v5.12.5
> git submodule update qtbase
> git submodule update qtimageformats"
> 
> I will try with some more modules

what link or website ? i have the same problem and deleting config.cache didnt help,can u tell me from where u download that zip files of qt ?

**Comment by mugavri** [comment]
i have the same issue on version qt 5_12_8

**Comment by ilya-fedin** [comment]
@robinfoxnan accroding to your log, LibrariesPath isn't set
@mugavri according to your log, you didn't build openssl with debug target
