### ISSUE TITLE
security concerns

### ISSUE THREAD

**Issue by halaei** [telegramdesktop/tdesktop#7232]
I have sent my security concerns to botsupport and security@telegram.org and Telegram's Twitter account with no feedback. So I repeat myself here as well.

1. Since the beginning of bot api, you only accept bot token as part of the url. This is bad because virtually all error reporting/logging systems logs the entire url if they report 400 or 500 errors. But they don't leak sensitive info if the token is part of post body params or in the headers. It would be nice if you add some alternative way for authentication.
note: I recalled this because a new email I received from GitHub. They are deprecating support of accepting tokens via query params because it is not safe! Why do you insist on ignoring the issue here?

2. I think the sample implementation for Telegram Login Widget is insecure. The code is in this github gist: https://gist.github.com/anonymous/6516521b1fb3b464534fbc30ea3573c2
It is linked by this page https://gist.github.com/anonymous/6516521b1fb3b464534fbc30ea3573c2
The reason I think the code is insecure is because strcmp() in line 16 is subject to timing attacks. To fix that hash_equals() can be used instead.
https://php.net/manual/en/function.hash-equals.php

3. About Telegram web Auth: Users need to have access to this "LOG OUT"button (see the attached picture) somewhere on the web, on your domains, t.me or telegram.org. Not just inside login pop-ups. Someone has logged in in my browser, I can do nothing to log in myself but to clear history first!

![photo_2020-02-04_15-15-36](https://user-images.githubusercontent.com/7089140/74723950-bc67c500-5250-11ea-9aff-20b7376d01b7.jpg)

**Comment by Aokromes** [comment]
sorry, but it doesn't belong here.

**Comment by RememberTheAir** [comment]
You may try to ping [@BotSupport](https://t.me/botsupport) with your concerns

**Comment by halaei** [comment]
@RememberTheAir It doesn't reply or see messages

**Comment by RememberTheAir** [comment]
@halaei how long ago did you write them? It usually take some time to get an answer. One week or so

**Comment by halaei** [comment]
@RememberTheAir 
I send my first concern more than 5 months ago, the second one 9 months ago and the third one 7 months ago to t.me/botsupport. My email to security at telegram org is 2 weeks old. :)

**Comment by halaei** [comment]
I have find a more important security issue. I will let botsupport and security email know tomorrow before making public.
