### ISSUE TITLE
External VideoPlayer doesn't work

### ISSUE THREAD

**Issue by MrMahdi313** [telegramdesktop/tdesktop#7234]
### Steps to reproduce
1. Open Telegram Settings
2. typing "videoplayer"
3. Select Play video button(video not downloaded)

### Expected behaviour
I want play video with external video player before download (download and play at same time).

### Actual behaviour
Play Video with external videoplayer just when video downloaded complete.

### Configuration
**Operating system:**
Fedora 31 (KdePlasma spin)
**Version of Telegram Desktop:**
1.8.15
**Used theme**:
Default night mode.
<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by john-preston** [comment]
@MrMahdi313 I think this is not possible.

**Comment by MrMahdi313** [comment]
I still think this feature can be attractive but I do not know if it is possible or not

**Comment by ilya-fedin** [comment]
> I still think this feature can be attractive but I do not know if it is possible or not

External players can't download files with mtproto protocol, so this is not possible
