### ISSUE TITLE
TG desktop drops messages from unsubscribed group

### ISSUE THREAD

**Issue by maksimotstavnov** [telegramdesktop/tdesktop#7235]
Telegram Desktops seems to drop messages when browsing an unsubscribed public (super)group. 

Enclosed are two screenshots of the same supergroup taken with TG for Android (v. 5.14.0) and with TG Desktop). Several dozens messages posted from 11:43 AM up to 8:22 PM are completely absent in desktop version.

**Operating system:** Debian 10

**Version of Telegram Desktop:** 1.9.13

**Used theme**: Classic

![TG_Android_drops_msgs_not png](https://user-images.githubusercontent.com/61102227/74764893-a4656500-5293-11ea-8808-58da29706743.png)
![TG_desktop_drops_msgs](https://user-images.githubusercontent.com/61102227/74764898-a5969200-5293-11ea-9159-e2e607c353c0.png)

**Comment by f242** [comment]
related bug #7023

**Comment by Aokromes** [comment]
this issue is still valid?

**Comment by ilya-fedin** [comment]
> this issue is still valid?

People regularly reproduce this issue when joining to one group where I admin. They can't see a message from captcha bot that is sent right after they joining in the group.

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/7023
