### ISSUE TITLE
Telegram Desktop Not Responding In Ubuntu 18.04 

### ISSUE THREAD

**Issue by HamedSanaei** [telegramdesktop/tdesktop#7237]
### Steps to reproduce
1. play a voice on telegram in Ubuntu OS.
2. click 0n 2x to speed up the playback speed.

### Expected behaviour
It should play the voice in 2x speed.

### Actual behaviour
Telegram crashes and not responding. waiting wouldn't help. it must be quitted.

### Configuration

**Operating system:**
Ubuntu 18.04 64bit

**Version of Telegram Desktop:**
Telegram Desktop 1.9.9

**Comment by Aokromes** [comment]
update to 1.9.14.
