### ISSUE TITLE
Configure telegram errors, 

### ISSUE THREAD

**Issue by robinfoxnan** [telegramdesktop/tdesktop#7239]
Hello,

When I Configure telegram with
configure.bat -D TDESKTOP_API_ID=17349 -D TDESKTOP_API_HASH=344583e45741c457fe1862106095a5eb -D DESKTOP_APP_USE_PACKAGED=OFF

I meet something wrong like these:
CMake Error at D:/TBuild/ThirdParty/cmake/share/cmake-3.17/Modules/FindPackageHandleStandardArgs.cmake:164 (message):
  Could NOT find Python (missing: Python_EXECUTABLE Interpreter)
  
  CMake Error at cmake/init_target.cmake:27 (target_compile_features):
  target_compile_features The compiler feature "cxx_std_20" is not known to
  CXX compiler

[CMakeOutput.log](https://github.com/telegramdesktop/tdesktop/files/4223122/CMakeOutput.log)

Thanks first

**Comment by robinfoxnan** [comment]
Win10, VS2017,  CMAKE 3.17

**Comment by john-preston** [comment]
@robinfoxnan Vs2017 is not supported.

**Comment by robinfoxnan** [comment]
@john-preston Thanks,

i installed Vs2019 Free Version, 
but it still likes this:

CMake Error at cmake/init_target.cmake:23 (target_compile_features):
  target_compile_features 
  The compiler feature "cxx_std_20" is not known to CXX compiler  "MSVC"  version 19.10.25017.0.

Call Stack (most recent call first):
  cmake/external/lz4/CMakeLists.txt:19 (init_target)

Thanks again.

**Comment by john-preston** [comment]
@robinfoxnan Current compiler version in "x86 Native Tools Command Prompt for VS 2019" is "Microsoft (R) C/C++ Optimizing Compiler Version 19.24.28316 for x86".

You need to run "configure.bat force" to replace completely the old configuration run.

**Comment by robinfoxnan** [comment]
@john-preston 
Thanks,
 that error is ok,
but i meet a new one:
-----------------------------------------------------------------------------------
CMake Error at D:/TBuild/ThirdParty/cmake/share/cmake-3.17/Modules/FindPackageHandleStandardArgs.cmake:164 (message):
  Could NOT find Python (missing: Python_EXECUTABLE Interpreter)
Call Stack (most recent call first):
  D:/TBuild/ThirdParty/cmake/share/cmake-3.17/Modules/FindPackageHandleStandardArgs.cmake:445 (_FPHSA_FAILURE_MESSAGE)
  D:/TBuild/ThirdParty/cmake/share/cmake-3.17/Modules/FindPython.cmake:354 (find_package_handle_standard_args)
  Telegram/cmake/generate_scheme.cmake:8 (find_package)
  Telegram/cmake/lib_scheme.cmake:18 (generate_scheme)
  Telegram/CMakeLists.txt:35 (include)
------------------------------------------------------------------------------------------
I do install the python2.7 in  dir of "D:\TBuild\ThirdParty", and add "D:\TBuild\ThirdParty\Python27" to PATH,
in cmd python --version is ok,

Thanks a lot.

**Comment by john-preston** [comment]
@robinfoxnan Maybe it supports only python 3, I'm not sure. I don't have such error :(

**Comment by robinfoxnan** [comment]
@john-preston 
thanks, 
i  add something in cmd like this:
configure.bat  force  -D TDESKTOP_API_ID=17349 -D TDESKTOP_API_HASH=344583e45741c457fe1862106095a5eb -D DESKTOP_APP_USE_PACKAGED=OFF-D PYTHON_EXECUTABLE=D:\TBuild\ThirdParty\Python27 -D  PYTHON2_INCLUDE_DIR=D:\TBuild\ThirdParty\Python27\include -D PYTHON2_EXECUTABLE=D:\TBuild\ThirdParty\Python27

then it worked, but  ; (
I meet the output: 
"
CMake Error at cmake/external/qt/package.cmake:23 (find_package):
  By not providing "FindQt5.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "Qt5", but
  CMake did not find one.

  Could not find a package configuration file provided by "Qt5" with any of
  the following names:

    Qt5Config.cmake
    qt5-config.cmake

  Add the installation prefix of "Qt5" to CMAKE_PREFIX_PATH or set "Qt5_DIR"
  to a directory containing one of the above files.  If "Qt5" provides a
  separate development package or SDK, be sure it has been installed.
Call Stack (most recent call first):
  CMakeLists.txt:34 (include)
"

i compiled QT5.12.0, and installed the out to "D:\TBuild\Libraries\Qt-5.12.5"
now, what should i do about the new error ,

thanks

**Comment by robinfoxnan** [comment]
@john-preston 
Cmake should be x64 version with python x64 version in win10x64,
Thanks,

**Comment by Aokromes** [comment]
python 2.x is deprecated.

**Comment by CateOppici** [comment]
@robinfoxnan 
did you find a workaround? I get this error too

> ## @john-preston
> Thanks,
> that error is ok,
> but i meet a new one:
> ## CMake Error at D:/TBuild/ThirdParty/cmake/share/cmake-3.17/Modules/FindPackageHandleStandardArgs.cmake:164 (message):
> Could NOT find Python (missing: Python_EXECUTABLE Interpreter)
> Call Stack (most recent call first):
> D:/TBuild/ThirdParty/cmake/share/cmake-3.17/Modules/FindPackageHandleStandardArgs.cmake:445 (_FPHSA_FAILURE_MESSAGE)
> D:/TBuild/ThirdParty/cmake/share/cmake-3.17/Modules/FindPython.cmake:354 (find_package_handle_standard_args)
> Telegram/cmake/generate_scheme.cmake:8 (find_package)
> Telegram/cmake/lib_scheme.cmake:18 (generate_scheme)
> Telegram/CMakeLists.txt:35 (include)
> I do install the python2.7 in dir of "D:\TBuild\ThirdParty", and add "D:\TBuild\ThirdParty\Python27" to PATH,
> in cmd python --version is ok,
> 
> Thanks a lot.

**Comment by avwuff** [comment]
I also experienced this issue.  If none of the above fixes worked, do the following:

1. Open Build Directory\tdesktop\Telegram\CMakeLists.txt
2. After init_target(Telegram), add the line:
`set(PYTHON_EXECUTABLE C:/TBuild/ThirdParty/Python27/python.exe) `
3. Save, and run the Configure.bat again.

Worked for me!

**Comment by caterandom** [comment]
@avwuff 
It worked setting "Python_EXECUTABLE"
Thank you so much!
