### ISSUE TITLE
Spellcheck works incorectly for not English language

### ISSUE THREAD

**Issue by dismine** [telegramdesktop/tdesktop#7240]
Hi.

Recently I have switched from Ubuntu to Mint. And the spellcheck feature no longer works correctly for me. It shows and fix English words, but don't work for other languages, Russian and Ukrainian.

### Steps to reproduce
1. Misspell in Russian language
2. Misspelled word will be underlined in red
3. Select in the context menu one of the proposed corrections.

### Expected behavior
The underline must disappear.

### Actual behavior
The underline disappears only on a short period of time and reaper again.

### Note
I see the correct proposals, but Telegram still complains about them. I have installed hunspell dictionaries for the target languages.

### Configuration

**Operating system**: Linux Mint 19.3 Cinnamon
Linux dismine 5.3.0-40-generic #32~18.04.1-Ubuntu SMP Mon Feb 3 14:05:59 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

**Version of Telegram Desktop**: 1.9.14 (not from the distro repo)

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/7038
