### ISSUE TITLE
Couldn`t remove gif file from computer

### ISSUE THREAD

**Issue by Partizanin** [telegramdesktop/tdesktop#7241]
### Steps to reproduce
1. Download gif file or mp4 to computer
2. Send file to someone
3. Try to remove file from computer

### Expected behaviour
It should be deleted

### Actual behaviour
It couldn't be delete because telegram process keeping that

### Configuration
**Operating system:**
Windows 10, version10.0.18362.116 ,10.0.18363.657

**Version of Telegram Desktop:**
1.9.14

**Used theme**:
Default "Tinted"
<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

 
![Prewiew image of problem](https://i.imgur.com/rWKetJ0.png)

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/7191
