### ISSUE TITLE
missing: Python_EXECUTABLE Interpreter

### ISSUE THREAD

**Issue by robinfoxnan** [telegramdesktop/tdesktop#7242]
when i try to configure telegram with cmd:
configure.bat  force  -D TDESKTOP_API_ID=17349 -D TDESKTOP_API_HASH=344583e45741c457fe1862106095a5eb -D DESKTOP_APP_USE_PACKAGED=OFF 

but i meet errors :
CMake Error at D:/TBuild/ThirdParty/cmake/share/cmake-3.17/Modules/FindPackageHandleStandardArgs.cmake:164 (message):Could NOT find Python (missing: Python_EXECUTABLE Interpreter)
Call Stack (most recent call first):
  D:/TBuild/ThirdParty/cmake/share/cmake-3.17/Modules/FindPackageHandleStandardArgs.cmake:445 (_FPHSA_FAILURE_MESSAGE)
  D:/TBuild/ThirdParty/cmake/share/cmake-3.17/Modules/FindPython.cmake:354 (find_package_handle_standard_args)
  Telegram/cmake/generate_scheme.cmake:8 (find_package)
  Telegram/cmake/lib_scheme.cmake:18 (generate_scheme)
  Telegram/CMakeLists.txt:35 (include)
-------------------------------------------------------------------------------------
i try to add param like that: (somebody said that should add param of dirs)
configure.bat  force  -D TDESKTOP_API_ID=17349 -D TDESKTOP_API_HASH=344583e45741c457fe1862106095a5eb -D DESKTOP_APP_USE_PACKAGED=OFF -D PYTHON_EXECUTABLE=D:/TBuild/ThirdParty/Python38/python.exe -D PYTHON_LIBRARY=D:/TBuild/ThirdParty/Python38/libs/python3.lib  -D PYTHON_INCLUDE_DIR=D:/TBuild/ThirdParty/Python38/include

but it dose not work at all, 
i do not know whether something wrong with dir ?

thanks

**Comment by ilya-fedin** [comment]
https://cmake.org/cmake/help/latest/module/FindPython.html
```
Python_ROOT_DIR
    Define the root directory of a Python installation.
```
Don't forget about case sensitivity.

**Comment by robinfoxnan** [comment]
@ilya-fedin 
Thanks first,
But How should I write the cmd, is it like this?

configure.bat  force  -D TDESKTOP_API_ID=17349 -D TDESKTOP_API_HASH=344583e45741c457fe1862106095a5eb -D DESKTOP_APP_USE_PACKAGED=OFF -D Python_ROOT_DIR=D:/TBuild/ThirdParty/Python38

but, it does not work,

**Comment by robinfoxnan** [comment]
@ilya-fedin 

I add a new system environment variable named 
Python_ROOT_DIR=D:/TBuild/ThirdParty/Python38
but still meet the same error,

**Comment by ilya-fedin** [comment]
https://github.com/Kitware/CMake/blob/master/Modules/FindPython/Support.cmake#L88
Check that your python installation is not portable and has these registry nodes

**Comment by robinfoxnan** [comment]
@ilya-fedin 
Thanks,
I add some message("__") in Support.cmake, so i find that the function find_program dose not work,
so there maybe 2 problems:
1) python for 32bit will not add items in registry,
2) cmake for 32bit will not work with some function,

I re install python3.8-x64  and CMake3.16-x64,
then everything is ok.

thanks a lot.

**Comment by ilya-fedin** [comment]
>     1. python for 32bit will not add items in registry,

32-bit programs on 64-bit systems install registry keys by other path, with SysWOW64.

**Comment by avwuff** [comment]
I also experienced this issue.  If none of the above fixes worked, do the following:

1. Open Build Directory\tdesktop\Telegram\CMakeLists.txt
2. After init_target(Telegram), add the line:
`set(PYTHON_EXECUTABLE C:/TBuild/ThirdParty/Python27/python.exe) `
3. Save, and run the Configure.bat again.

Worked for me!
