### ISSUE TITLE
Telegram randomly crashes when trying to autoplay a video

### ISSUE THREAD

**Issue by NulAsh** [telegramdesktop/tdesktop#7249]
### Steps to reproduce
1. Visit any chat with videos.
2. 
3. 

### Expected behaviour
Video automatically starts playing without sound.

### Actual behaviour
Telegram crashes because of "Out of memory" error (not every time).
This happens only when some video appears in visible part of the chat and Telegram tries to autoplay it. And sometimes it tries to allocate a lot of memory, more than 2 Gb.

### Configuration
Windows 7 SP1

**Version of Telegram Desktop:**
1.9.14
**Used theme**:
Classic
<details><summary><b>Logs</b>:</summary>
[log.txt](https://github.com/telegramdesktop/tdesktop/files/4231313/log.txt)

</details>

**Comment by john-preston** [comment]
@NulAsh It doesn't happen with random videos for me :( Can you please provide an exact video that crashes (more than once, exactly that video file) on autoplay? You can contact me at https://t.me/preston

**Comment by Aokromes** [comment]
poke @NulAsh

**Comment by NulAsh** [comment]
It happens with **random** videos. I'll write my own memory debugger and bring the proofs

**Comment by Aokromes** [comment]
i sugest you to install telegram 1.9.20 beta

**Comment by Aokromes** [comment]
any update @NulAsh on 1.9.22?

**Comment by Aokromes** [comment]
poke @NulAsh

**Comment by Aokromes** [comment]
no answer for near a month, closing, if this bug is still valid open a new ticket using updated telegram.
