### ISSUE TITLE
alternative NTFS stream for file

### ISSUE THREAD

**Issue by belnet** [telegramdesktop/tdesktop#7250]
### Steps to reproduce
1. open any chat or telegram conversation
2. copy link to cube for example this https://coub.com/view/29bzdu
3. in the right-click menu, preview where to select "save video as ..."

### Expected behaviour
Tell us what should happen

it is expected that telegrams will read and follow system policies like any normal Internet program.
in particular, a ban on marking files with alternative NTFS streams.

**DisableZoneInformation.reg**
Windows Registry Editor Version 5.00

[HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Policies\Attachments]
"SaveZoneInformation"=dword:00000001
----------------------------------------------------------------------------------------------
### Actual behaviour
Tell us what happens instead

instead, the file is marked as "potentially dangerous" downloaded from the Internet. this is contrary to system setup.

### Configuration
**Operating system:**
Win 10 LTSB x64

**Version of Telegram Desktop:**
1.9.14
**Used theme**:
night

<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary) see link below
https://pastebin.com/Z2iTTT2N
</details>

video reproducing the problem:
https://klikr.org/aedbe394a0cf3bda44bbb74e2597.gif

**Comment by Aokromes** [comment]
with the possibility of send things from linux or android or macos, i doub this is doable.

**Comment by belnet** [comment]
**Aokromes**, Thank you for looking at the tickets, I really hope for an early release of the corrected version of the program!
