### ISSUE TITLE
"There seems to be a problem with your sound card." when making calls in Debian 10

### ISSUE THREAD

**Issue by teran-mckinney** [telegramdesktop/tdesktop#7251]
### Steps to reproduce
1. Use Debian 10
2. Try to make a call

### Expected behaviour
Call should work.

### Actual behaviour
"There seems to be a problem with your sound card." when answered.

### Configuration
Debian 10

Tried 1.5.1 (from Debian) and 1.9.14. Same exact behavior.

Interface sounds work, I can do a microphone record and it goes through fine, can play it back without issue. Mic test works.

But when I make a call it bails out. I'm using Alsa, no Pulse Audio.

This is my .asoundrc:

```
pcm.!default {
    type asym
    playback.pcm "plughw:0"
    capture.pcm  "plughw:1"
}

ctl.!default {
    type hw
    card 1
}
```

This is in the log output:

```
E/tgvoip: pa_context_connect failed: Access denied
W/tgvoip: PulseAudio available but not working; trying ALSA
E/tgvoip: snd_pcm_open failed: Device or resource busy
I/tgvoip: AEC: 1 NS: 1 AGC: 1
E/tgvoip: Error initializing audio playback
V/tgvoip: Call state changed to 4
I/tgvoip: === send thread exiting ===
```

**Comment by teran-mckinney** [comment]
Also, in 1.5.1 or 1.9.14, if I click for audio device selection for mic or speakers, it hangs.

**Comment by ilya-fedin** [comment]
> E/tgvoip: snd_pcm_open failed: Device or resource busy

Alsa provides exclusive access to the device, close all other programs (and maybe services)

**Comment by teran-mckinney** [comment]
Only if Telegram is requesting exclusive access. Like I said, audio output and even the mic record feature work perfectly.

I don't see why Telegram would need exclusive access on a call.

**Comment by ilya-fedin** [comment]
> I don't see why Telegram would need exclusive access on a call.

This is how alsa works. If you choose a output itself instead of dmix/dsnoop output - app will grab it exclusively.

**Comment by teran-mckinney** [comment]
The only way I'm able to configure what Telegram does is with my asoundrc or ALSA_CARD settings. I'm not certain if it was exclusive or not but I could test that easily enough playing music at the same time.

Either way, mic works, playback works, calls don't work. I call it a bug.

**Comment by ilya-fedin** [comment]
> Either way, mic works, playback works, calls don't work. I call it a bug.

playback and mic are working through openal, calls - through tgvoip. They wants use the same output at the same time. And tgvoip can't open output, since it's not a dmix/dsnoop output and already using by openal.

**Comment by ilya-fedin** [comment]
> I call it a bug.

When you switching to the audio subsystem that doesn't support mixing without additional settings, you should understand which problems you will get

**Comment by teran-mckinney** [comment]
Are you saying that in theory something like:

```
pcm.!default {
    type asym
    playback.pcm "dmix:0"
    capture.pcm  "dmix:1"
}

ctl.!default {
    type hw
    card 1
}
```

Would work?

I have a builtin audio device that I'm not using for Telegram. Next is a USB DAC and headphone amplifier I use for output. Then I have a USB microphone for input.

**Comment by ilya-fedin** [comment]
```
pcm.!default {
    type asym
    playback.pcm "dmixer"
    capture.pcm  "dsnooper"
}

ctl.!default {
    type hw
    card 1
}

pcm.dmixer {
    type dmix
    ipc_key 1024
    slave {
        pcm "plughw:0"
        period_size 4096
        buffer_size 131072
        rate 50000
    }
    bindings {
        0 0
        1 1
    }
}

ctl.dmixer {
  type hw
  card 0
}

pcm.dsnooper {
    type dsnoop
    ipc_key 1024
    slave {
        pcm "plughw:1"
        channels 2
        period_size 4096
        buffer_size 131072
        rate 50000
    }
    bindings {
        0 0
        1 1
    }
}
```

**Comment by teran-mckinney** [comment]
I was getting segfaults with that configuration but thank you for sending it to me.

Ended up just doing ALSA_CARD=2 and using the headphone jack off the microphone. Didn't realize it worked that way and it seems like a fine solution.

Thank you!
