### ISSUE TITLE
Telegram desktop (daemon) quits with close ✗ button

### ISSUE THREAD

**Issue by joe733** [telegramdesktop/tdesktop#7252]
### Steps to reproduce
1. Open telegram
2. Click the close button

### Expected behaviour
The background daemon should be kept running for telegram.

### Actual behaviour
Telegram quits - even from background.

### Configuration
**Operating system**:
OS: Elementary OS 5.1 Hera
CPU: Intel i5 2nd Gen
GPU: NVIDIA GeForce GT 525M
Mem: 12GB

**Version of Telegram Desktop (AppImage)**:
1.9.14

**Used theme**:
Night + Green Tint

**Comment by Aokromes** [comment]
try updating to 1.9.17

**Comment by RobertoPerico** [comment]
Same problem here.
I'm running Arch Linux with Gnome 3.34 as DE.
Updating to 1.9.18 did not solve the issue.

**Comment by joe733** [comment]
> try updating to 1.9.17

I'm on 1.9.14. When checking for update... it says I'm on latest version.

**Comment by whidrasl** [comment]
Fedora 31,
Gnome 3.34.4,
Telegram 1.9.19 (firstly tried with 1.9.14)
Same problem

**Comment by ilya-fedin** [comment]
Telegram won't stay in background if there are no tray...
But you can use minimize button instead of close button :)

**Comment by whidrasl** [comment]
@ilya-fedin thanks for explanation. With tray extension (for example https://extensions.gnome.org/extension/1031/topicons/) tdesktop works as before (btw with this extension I don't see any telegram tray icon, but this has no matter for me)

**Comment by ilya-fedin** [comment]
> as before

It's funny that this check was always, but did not work, because check was made after the tray was initialized
It is fixed with https://github.com/telegramdesktop/tdesktop/commit/a88423a33f29adf903c16dd42f0a763ea2901694#diff-b779bfad93b62cad9ca1404476e5790bR152-L153, I guess

**Comment by Aokromes** [comment]
so, no telegram bug?

**Comment by ilya-fedin** [comment]
Yes, not bug
There are also https://github.com/telegramdesktop/tdesktop/issues/5004 where an option for minimize-by-close can be discussed

**Comment by black-roland** [comment]
> Telegram won't stay in background if there are no tray...

I wonder how staying in the background is related to the tray.

For example, other apps and messengers like Skype/Discord can run in the background and receive a notification without a tray icon. So did Telegram before 1.9.13. Some apps like Polari even ask if it should run in the background (was discussed a couple of years ago in #3830).

Could you elaborate a bit on this?

**Comment by ilya-fedin** [comment]
> So did Telegram before 1.9.13.

That was a bug :)

> Could you elaborate a bit on this?

If you want to ask why this approach was changed, then you should ask not me

**Comment by joe733** [comment]
> Telegram won't stay in background if there are no tray...
> But you can use minimize button instead of close button :)

Distributions like elementary OS do not ship with minimize button by default. The trays are disappearing in nearly every other DE too with `planks`. So I guess `close` to `minimize` was good approach by telegram until now.

I hope discussions at #5004 prove to be use full.

**Comment by ilya-fedin** [comment]
> So I guess `close` to `minimize` was good approach by telegram until now.

it was not approach, but a bug, in fact it tried to minimize to tray that doesn't exist. Current approach was added [6 years ago](https://github.com/telegramdesktop/tdesktop/commit/4221fe666f13f1d83c27c5f64e83d9bc8b3cfb51#diff-9c2b0c89960462e98f1e701c3c09ea41R471).
