### ISSUE TITLE
Option to hide the "bot" button

### ISSUE THREAD

**Issue by FelixFurtmayr** [telegramdesktop/tdesktop#7258]
## Reproduce
Imagine this situation:
1) create a group
2) integrate a bot (maybe with a message "it is tuesday 10:00, here the link to the weekly video session , ...")
3) bring in some non IT people. They accidentally press the "bot button" on the lower right (where ususally the "continue button" is).
## Suggestion
As I'm to lazy to explain to those people the button (and they are not interested), I suggest to being able to hide the button. 
Similar to "Disable notifications", maybe a "Hide bot button".

**Comment by damnfella** [comment]
just kick out the bot, or remove the command list from [@botfather](https://telegram.me/botfather) if you own the bot.

They'd still need to press the hide bot button, but I get what you're going after. anyway, this is more of an option that should exist on all platforms, if at all its going to be implemented.

**Comment by FelixFurtmayr** [comment]
"just kick out the bot" => does it still work then?

yes, they would have to press the button. but this can be accomplished. I'm only use telegram on my desktop. Last time I saw somebody using this chat on the phone. I was not really able to quit the bot - seems like the button was missing there.

**Comment by damnfella** [comment]
uh, which bot are you referring to btw? and to make sure we're talking about the same thing:

Is this the bot button?
![image](https://user-images.githubusercontent.com/51771172/75384916-cb134380-5904-11ea-8684-408a1772e858.png)

**Comment by FelixFurtmayr** [comment]
yes, that is true. we use skeddy to remind us of our team meeting:

![grafik](https://user-images.githubusercontent.com/16761317/75385107-73161600-58df-11ea-9c16-154d81b1622f.png)

actually there is little need to ever configure skeddy again. each time I open this chat, somebody came accidentally on the button. I see that as a problem. since we want to rather throw the bot out, as is this is annoying. Although the reminder is really helpfull.

**Comment by FelixFurtmayr** [comment]
in my case the button looks a bit different, but I assume, it is the same button as you show, only a different logo:

![grafik](https://user-images.githubusercontent.com/16761317/75385401-f9caf300-58df-11ea-8055-b720b5a5feb7.png)

the one on the left is for skeddy.

**Comment by damnfella** [comment]
buddy, Telegram doesn't own 99% of the bots.
bots are not made by Telegram, but literally anyone who are interested in providing services, including yourself. That means, if you have a problem with the bot, you have to speak with the bot's dev, and not telegram!


>in my case the button looks a bit different, but I assume, it is the same button as you show, only a different logo
I think this button isn't visible in groups, but in private message with the bot itself. 

If you understand what I've said, and you still think there's an issue tdesktop itself needs to solve, then please explain your problem properly.

**Comment by FelixFurtmayr** [comment]
I thought it would be cool if you could hide the button for all bots. especially as their button is there, where other messagers have a "send" button.

I know, that telegram is not responsible for the bots. I considered this a general feature, independent of the bot. If I'm wrong there, I'm sorry. My option is, that I don't have to know every technical detail to tell about a problem that we have. 

For me the problem is simple: The bot opens accidentally. I have two solutions:
1. tell somebody about it, as others could have the problem, too. find a solution.
2. throw the bot out and stop using bots in general

You made your point. I go with the second case and I will not ask here again for help.

**Comment by damnfella** [comment]
@Aokromes I think I missed the point in here. But it seems like there's an issue with bot buttons maybe?

@FelixFurtmayr Please use Saved Messages to schedule reminders for yourself. I cannot recommend a reminders bot, since I don't know a proper one. 
For the time being, you should consider using a proper app that's made for reminders.


I apologise if my communication seemed a little rude in a way 😓

**Comment by FelixFurtmayr** [comment]
thank you for the apology. you are welcome. acutally I know the situation just too well - some newbie asks without thinking ;-)

"since I don't know a proper one"
Ok, understood. I think it would be cool, to have one working bot for this tasks.

Do you have any good tip how to contact the developer of such a bot? Telegram is straight forward and I'm very happy with it. But that seems not true for the bots: For example the website of skeddy has no contact. Maybe they get a pull request from me, but I have to know where to place it.

I understand, that telegram may not be responsible for external bots, but would't some standard be a good idea (like having at least the contact to one developer)?
