### ISSUE TITLE
Spell checking

### ISSUE THREAD

**Issue by Zignd** [telegramdesktop/tdesktop#726]
That's it, I wish Telegram Desktop had support for spell checking with support for multiple language selection, not just the system default language.

**Comment by kosmodrey** [comment]
Duplicate #96

**Comment by mderoode** [comment]
+1, Spell check is the only blocking feature which is missing in the Telegram Desktop client for me.

**Comment by wolfjlupus** [comment]
+1 Plase sav su frmo ym mis-spelings! ;)

**Comment by rogyar** [comment]
As it was mentioned here https://github.com/overtake/telegram/issues/92
You can turn on the spell-checking option using context menu of the message input field.

**Comment by Zignd** [comment]
@rogyar Have you tried by yourself? Because there's no such option for me.

**Comment by wolfjlupus** [comment]
@rogyar It's not present in the PC version, the one linked is for OS X ( Mac ).

**Comment by aaronraimist** [comment]
@rogyar I cannot see this option on Linux (Xubuntu)
