### ISSUE TITLE
Updater need mtproxy and remember list of proxy

### ISSUE THREAD

**Issue by Kwaskoff** [telegramdesktop/tdesktop#7260]
### Is your feature request related to a problem?
My country banned. We need easy way to update telegram when we received bad version like today

### Describe the solution you'd like
Add mtproxy to updater and it need to remember list of proxy from telegram

![Imgur](https://imgur.com/XlGhb95.png)

**Comment by Aokromes** [comment]
theorically update with mtproxy was added on https://github.com/telegramdesktop/tdesktop/commit/03037121aacfe71107dc277d572850e6e8fa1a8f
