### ISSUE TITLE
[Linux, Cinnamon] Telegram tray icon is too small on high-DPI and doesnt match theme

### ISSUE THREAD

**Issue by cokkto** [telegramdesktop/tdesktop#7263]
![Screenshot from 2020-02-22 13-52-01](https://user-images.githubusercontent.com/8975496/75091826-5180fb80-557a-11ea-9a92-7283f7e786a5.png)

Manjaro Cinnamon, screen resolution 2880*1620
Issues:
- Icon is twice smaller than others 
- Menu is white whilst the desktop theme is dark. 

Linux: Manjaro Cinnamon latest, Linux kernel 5.5.2-1
Telegram: 1.9.14-1
Used themes: Mint-Y-Dark, Icons Papyrus-Adapta-Nokto-Maia

**Comment by ilya-fedin** [comment]
Version?

**Comment by cokkto** [comment]
> Version?

updated topic

**Comment by ilya-fedin** [comment]
> updated topic

too old

**Comment by cokkto** [comment]
> > updated topic
> 
> too old

updated to Telegram: 1.9.14-1 - same issue

**Comment by ilya-fedin** [comment]
> updated to Telegram: 1.9.14-1 - same issue

try 1.9.13

**Comment by cokkto** [comment]
> > updated to Telegram: 1.9.14-1 - same issue
> 
> try 1.9.13

no difference

**Comment by ilya-fedin** [comment]
> no difference

It should, on 1.9.13 there was 48px size.

**Comment by cokkto** [comment]
> > no difference
> 
> It should, on 1.9.13 there was 48px size.

Unfortunately. While I figured out that I can change a view of menu in a notification area by making suitable dark theme, icon size is not reacting in neither version of telegram. I tried community version from package manager, latest source (1.9.14) as well as I used precompiled binary from web site (1.9.13) - all of them have the same tray icon

**Comment by cokkto** [comment]
could it be some scale factor used by desktop environment that is ignored by telegram?

**Comment by ilya-fedin** [comment]
> While I figured out that I can change a view of menu in a notification area by making suitable dark theme

So, you're using old XEmbed tray which doesn't support HiDPI

**Comment by cokkto** [comment]
> > While I figured out that I can change a view of menu in a notification area by making suitable dark theme
> 
> So, you're using old XEmbed tray which doesn't support HiDPI

this i can not tell, I am not making this distro neither I know how to check it. But here on my screenshot there are f.lux or pCloud client icons and none has the same trouble

**Comment by ilya-fedin** [comment]
Google says:  “System Settings” -> “General” -> “Enable support for indicators”

**Comment by cokkto** [comment]
This works, thank you
