### ISSUE TITLE
Random crashes

### ISSUE THREAD

**Issue by Neurotoxin001** [telegramdesktop/tdesktop#7264]
### Steps to reproduce
Don't know exactly, just surfing channels.

In log I got:
`[2020.02.22 17:19:31] Assertion Failed! "state->readTill >= tillId" data_histories.cpp:414`

Report Tag: 9ac8051f-47b1-40a6-82fd-10f846a17b2e (don't know if it's been sended because I turn off my vpn for a moment).

This happens already 2 time per 5 hours.

### Configuration
**Operating system:** win 10 ltsc 1809

**Version of Telegram Desktop:** 1.9.15

**Used theme**: dark default

**Comment by Neurotoxin001** [comment]
Another one with the same error in log:
`[2020.02.22 22:20:37] Assertion Failed! "state->readTill >= tillId" data_histories.cpp:414`

Report Tag: 45049e42-5579-4e0f-bede-c63133681f33

**Comment by john-preston** [comment]
@Neurotoxin001 Yeah, sorry. I hope tomorrow there will be a fix version.
