### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [telegramdesktop/tdesktop#7265]
I would like to point out that an identifier like “[`_PsShadowWindows`](https://github.com/telegramdesktop/tdesktop/blob/6bbcec0c23d0f34a4ece450c3e699a5adc672aac/Telegram/SourceFiles/platform/win/main_window_win.cpp#L106 "Update candidate")” [does not fit](https://www.securecoding.cert.org/confluence/display/cplusplus/DCL51-CPP.+Do+not+declare+or+define+a+reserved+identifier "Do not declare an identifier which is reserved for the compiler implementation.") to the expected naming convention of the C++ language standard.
Would you like to adjust your selection for unique names?

**Comment by john-preston** [comment]
@elfring Yeah, I think I'll rename them some day along with some other refactoring.
