### ISSUE TITLE
Completion of error handling

### ISSUE THREAD

**Issue by elfring** [telegramdesktop/tdesktop#7266]
Would you like to add more error handling for return values from functions like the following?
- [av_malloc](https://ffmpeg.org/doxygen/trunk/group__lavu__mem__funcs.html#ga9722446c5e310ffedfaac9489864796d "Memory allocation") ⇒ [FFMpegReaderImplementation::start](https://github.com/telegramdesktop/tdesktop/blob/775d5b6dccf48c3310aed044b9022fc3d0a3518f/Telegram/SourceFiles/media/clip/media_clip_ffmpeg.cpp#L297)
- [avio_alloc_context](https://ffmpeg.org/doxygen/trunk/avio_8h.html#a853f5149136a27ffba3207d8520172a5 "Allocate and initialize an AVIOContext for buffered I/O.") ⇒ [Instance::Inner::onStart](https://github.com/telegramdesktop/tdesktop/blob/4ad293e2aed81cb402e11df0babbe53b3433d0cb/Telegram/SourceFiles/media/audio/media_audio_capture.cpp#L196)

**Comment by Aokromes** [comment]
pull requests are welcomed :)

**Comment by elfring** [comment]
How do you think about to improve [static source code analysis](https://en.wikipedia.org/wiki/List_of_tools_for_static_code_analysis#C.2C_C.2B.2B "Tools for code analysis") also for this software?

**Comment by Aokromes** [comment]
i suggested preston to run coverity or pvs-studio before, but, for sure 1st valgrind issues needs to be fixed or they will suicide xd
