### ISSUE TITLE
Mainstream messaging app as a subset inside Telegram chats

### ISSUE THREAD

**Issue by pabloopez** [telegramdesktop/tdesktop#7267]
### Is your feature request related to a problem?
Not a problem (well, having to install Whatsapp to talk to some of my contacts its kind of a problem).

### Describe the solution you'd like
Would it be doable to have whatsapp as a subset of chats inside of telegram? Use case: I enter my Whatsapp credentials, QR or whatever (same way I use for other non-official clients on Linux for Whatsapp or Whatsapp-web) and I have access to the chats and groups I have in my personal Whatsapp account. And all of it inside of Telegram. 

Some people is not going to move ever to Telegram, so this could be a way to solve this. Maybe not all features could be accesible from here, but I am not interested in anything more than send/receive messages pr pictures/files.

**Comment by damnfella** [comment]
Hello there. I don't think this would be a good idea, as its not only trying to be too monopolistic/ forceful, but also, I don't see this functioning well. As such, most users would be confused about the fundamental difference between the messaging apps.

Alternatively, you could use web versions of WhatsApp and Telegram in Opera Browser.
Or open 2 tabs in any other browser with **web.telegram.org** and **web.whatsapp.com**.
(make sure your ISP is not blocking the site).

Now, this Feature Request is unrelated or _far from implementation_ in the code of the official Messaging apps (well, at least Telegram has open source code). Hence it's best to make your own app, or ask other non-official-telegram and non-official-whatsapp developers to make this special for you.

P.S: Check out [@tgbetachat](https://telegram.me/tgbetachat/235242) for reactions to your issue xD

**Comment by Aokromes** [comment]
very likely whatsapp will ban such thing.

**Comment by damnfella** [comment]
close issue
