### ISSUE TITLE
Alex is a stupid nigger crying on Twitter

### ISSUE THREAD

**Issue by ghost** [telegramdesktop/tdesktop#7269]
![IMG_20200211_231746_167](https://user-images.githubusercontent.com/61384800/75118834-9302cb00-568e-11ea-9646-a4d3b9b2ea3e.jpg)
@Mazda--

**Comment by damnfella** [comment]
![image](https://user-images.githubusercontent.com/51771172/75119487-395bca00-56a9-11ea-80fa-f7732d43ee07.png)

You had 3 very clear options under this repository. You ignored them all. And you forgot your common sense.


Here. Sign your own ban wish.

**Comment by MasterGroosha** [comment]
@john-preston please, delete this shit

**Comment by Aokromes** [comment]
already told him and stek, but they are afk.

**Comment by glowhopper** [comment]
bruh
