### ISSUE TITLE
[Feature-request] Photo caption

### ISSUE THREAD

**Issue by mbnoimi** [telegramdesktop/tdesktop#727]
I suggest to add the feature of photo captions in similar way of mobile clients [...more](https://telegram.org/blog/captions-places)

**Comment by ianhyzy** [comment]
I'd also like this, sending them seperatly doesn't always look as nice

**Comment by Cadiducho** [comment]
Some news about this enhacement? This would be so cool

**Comment by srazi** [comment]
It's a must have feature and because there is `PhotoSendBox`, it should take just a little time for you to implement this feature.

**Comment by auchri** [comment]
Implemented with 0.9.5

**Comment by DaFri-Nochiterov** [comment]
Implemented, but not for all. Can add caption to photo selected in dialog (without copy and paste)? 

![image](https://cloud.githubusercontent.com/assets/10401817/10525686/4b40c24c-73b0-11e5-9734-31051437539b.png)

**Comment by telegramdesktop** [comment]
@DaFri-Nochiterov Not yet, sorry. Perhaps in some upcoming version.

**Comment by auchri** [comment]
Added with 0.9.10
