### ISSUE TITLE
Unread counter is locally correct but syncs wrongly

### ISSUE THREAD

**Issue by RememberTheAir** [telegramdesktop/tdesktop#7271]
### Steps to reproduce
1. open a chat with many unread messages on tdesktop
2. read some messages (not all of them)
3. open your chats list from another Telegram client

### Expected behaviour
The unread counter should display the same number of unread messages both on tdesktop and other clients

### Actual behaviour
tdesktop shows locally the correct number of messages left to read, but the counter syncs in a way that on other apps it always shows a _lower_ count.

Edit: also, if you quit tdesktop and reopen it, the unread count displayed by the app is the one you see locally (the correct one). I thought it was an issue with tdesktop not marking the chat history as read properly, does the app caches some info about the unread messages count locally?

Another info: I'm using the app at 90% scale 

### Configuration
**Operating system:** Windows 10

**Version of Telegram Desktop:** 1.9.16

**Comment by john-preston** [comment]
@RememberTheAir I can't reproduce lower on other devices. I can reproduce lower counter on tdesktop, while the request wasn't sent yet. Tdesktop sends read requests once every three seconds, is it the case?

**Comment by RememberTheAir** [comment]
Yes, you are right. I just logged in to another tdesktop instance and there the unread counter works correctly. The counter displayed TGX is also consistent with what I have read from tdesktop & correct. Since I've never had issues with the unread counter of the Android app, I assumed it was tdesktop's fault. But actually it's an issue with the Android app showing a wrong unread counter
