### ISSUE TITLE
New Taskbar Icons Folder Location?

### ISSUE THREAD

**Issue by jfk88** [telegramdesktop/tdesktop#7276]
Hi,

Since I'v updated to 1.9.14 in Arch, the client has stopped loading my customs taskbar icons located in /.local/share/TelegramDesktop/tdata/ticons. 

It seems it's now handled differently (i.e. #7268 ?). Is there still a folder where we can find those .png?

Thanks

**Comment by ilya-fedin** [comment]
You get confused between the taskbar icon and the tray icon. Your issue is #7192.

**Comment by jfk88** [comment]
Right, thanks!
