### ISSUE TITLE
[Question] Free Ram after watching

### ISSUE THREAD

**Issue by Khomyak-sibiryak** [telegramdesktop/tdesktop#7280]
Starting a client consumes 180 MiB ram. After watching the video, the client began to occupy 480 MiB ram. RAM is not freed up after the video is closed and will be in it.

The same thing happens when listening to music and even when scrolling through channels. RAM is not freed after closing the player or after closing the channel.

How to free up RAM after watching a video?

**Comment by jeffythedragonslayer** [comment]
Does this happen on Linux?  If so keep in mind RAM is 'used' for disk cache (https://www.linuxatemyram.com/)  And as @john-preston mentioned on the other thread, the HDD itself is used as a cache for downloading images and videos.

**Comment by Khomyak-sibiryak** [comment]
Yes, I use Linux. I understand everything, but in this way tdesktop consumes too much RAM and does not free it myself, I need to restart tdesktop in order to free resources. I do this several times a day.

**Comment by jeffythedragonslayer** [comment]
Definitely sounds like a memory then.  I am trying to get valgrind setup after fighting with vmware.

**Comment by zhelenskiy** [comment]
I think it would be great if we could choose the maximum amount of RAM to be used as a cache.

**Comment by ilya-fedin** [comment]
> How to free up RAM after watching a video?

You can't free RAM that is leaked
#7361
