### ISSUE TITLE
[Question] Emojis auto-replacement feature doesn't work for simple emojis. Is this expected?

### ISSUE THREAD

**Issue by KaplunYuriu** [telegramdesktop/tdesktop#7282]
I definitely remember that Telegram used to replace simple emojis (like :), :(, :D, :P, etc). 
But that's not longer a case for the last few months.  
This is not specific to one machine, it's reproducible on all PCs where I have telegram installed. 
I tried to re-install it, replace the emojis set (Mac, Android), but neither of the attempts helped. 
Is this an expected behavior? 
TG version:  1.9.14.

A short demo is attached. 
![emoji_demo](https://user-images.githubusercontent.com/6594970/75234850-f6424980-57c3-11ea-95de-5cf114c55548.gif)

**Comment by RememberTheAir** [comment]
> Is this an expected behavior?

I guess so. The emojis you listed are not meant to be replaced

**Comment by KaplunYuriu** [comment]
Interesting, why? 
They are commonly used and emoji definitely looks better than `:)`

**Comment by maxoku** [comment]
> They are commonly used and emoji definitely looks better than `:)`

I agree, it should be in telegram. I'm annoyed how every time I need to choose from a piker emoji instead of just typing `:)`, `:D`, `:P` etc.
Btw, replacing now works only for full name of emojis like when you type `:smile:`, `:joy:`, `:grin:`, `:wink:`, etc. then emoji will appear.

> Interesting, why?

I'd like to know that too :thinking:

**Comment by RememberTheAir** [comment]
tdesktop only replaces emojis like `:-)` or `:-(` so you have to put the nose if you want them to be autoreplaced. I don't know why nose-less emojis are not considered

**Comment by maxoku** [comment]
> tdesktop only replaces emojis like `:-)` or `:-(` 

Oh, I didn't noticed that lol. Nevertheless I found more and mostly it gives wrong emojis:
`:-)` :blush: `:blush:`,
`:-(` :disappointed: `:disappointed:`,
`;-P` :stuck_out_tongue_winking_eye: `:stuck_out_tongue_winking_eye:` [that is right, but case sensitive], 
`:-p` :yum: `:yum:` [case sensitive], 
`:-D` :smiley: `:smiley:` [case sensitive],
`8-)` :heart_eyes: `:heart_eyes:`,
`<3 ` :heart: `:heart:`
`B-)` :sunglasses: `:sunglasses:` [case sensitive]

I guess it's a leftover from previous system. I thought they deleted it, cuz it sucks. They should make the propper system for simple emojis, but I think they're just not interested :thinking:

**Comment by maxoku** [comment]
[780](https://github.com/telegramdesktop/tdesktop/issues/780) [627](https://github.com/telegramdesktop/tdesktop/issues/627) [](url)
![emoji set](https://user-images.githubusercontent.com/17256400/75330288-1c79ef00-5881-11ea-920f-5f61860665b2.png)
Some emojis needs to have additional space after the code to be replaced.

**Comment by Nascentes** [comment]
I'm seeing this same thing after the latest update, but for ALL emojis that I previously used quite a lot. Specifically:

```
:-) 
:+1: (thumbs up)
```

Pretty disappointed as this really throws off the flow of writing for me. Not a big deal on the smiley, but the thumbs up/down is a bummer. I can't get any emojis to auto-replace for me at this point and I no longer see the option for it in my settings. What gives? (macOS 5.9.3 (191685))

**Comment by RememberTheAir** [comment]
@Nascentes 

> macOS 5.9.3

If this is you Telegram's verison number, then you're not using Telegram Desktop, you are using the native MacOS app

**Comment by Nascentes** [comment]
@RememberTheAir - You are absolutely right. I didn't even realize there were separate versions. Installed the App Store variant just under a year ago. Still odd that I lost the behavior of emoji replacement, but that's a non-issue for me at this point. Removed the app store version and installed Telegram Desktop (1.9.14). No more complaints. Thank you!

**Comment by pixelcandy** [comment]
Up until last week Telegram *always* replaced `:)` with 😄 and `<3` with ❤️ 

I'm not sure what changed, but it's annoying to have to type `:heart` when `<3` is what I'm accustomed to in Telegram. Even iMessage changes `<3` into a heart.

**Comment by maxoku** [comment]
@pixelcandy 
Which version are you using? Telegram Desktop replaces `<3` with :heart:, look at the [screenshot](https://github.com/telegramdesktop/tdesktop/issues/7282#issuecomment-591323118).

**Comment by pixelcandy** [comment]
@maxoku it always used to until after an update about a week ago. I'm on latest version:

<img width="265" alt="Screen Shot 2020-03-06 at 9 50 31 AM" src="https://user-images.githubusercontent.com/57108128/76094021-f09cee80-5f8f-11ea-8ab6-c154da49ed66.png">

It no longer replaces `<3` with ❤️ for me:

<img width="523" alt="Screen Shot 2020-03-06 at 9 35 12 AM" src="https://user-images.githubusercontent.com/57108128/76094068-feeb0a80-5f8f-11ea-8241-72472860ecce.png">

**Comment by kirsan31** [comment]
@pixelcandy you are using native macOS client ;)

**Comment by pixelcandy** [comment]
@kirsan31 It's happening via Telegram on my iPhone as well - are you saying this is a mac issue? 

It's just weird that I've been using Telegram on my iPhone and macbook for over 2 years and it has always done the conversion properly 😦

**Comment by Nascentes** [comment]
@pixelcandy I hit the exact same thing on mac/iphone. For Mac, just remove the app (Finder > Applications / drag Telegram.app to Trash), and then re-download directly from https://desktop.telegram.org/

That'll fix the issue on your Mac. For iPhone, I just use the emoji key on my keyboard and insert one that way. Less effort than swapping to symbols to type it out, anyways, I find. Hopefully that works for you, as well. Otherwise, not sure what to tell you. Seems like a regression in the Apple version(s) of the app.

**Comment by pixelcandy** [comment]
@Nascentes Thank you! I didn't realize there was another version of Telegram. That fixed the problem. Thank you for taking the time to explain the solution 😄
