### ISSUE TITLE
[Feature Request] Add hardware video acceleration on Linux

### ISSUE THREAD

**Issue by Khomyak-sibiryak** [telegramdesktop/tdesktop#7286]
When watching a video through tdesktop, there is a high processor load. This feature will reduce the load on the processor and save battery. This does not work for Linux at the moment.

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/6312

**Comment by john-preston** [comment]
@Khomyak-sibiryak How do I do that?

**Comment by Khomyak-sibiryak** [comment]
@john-preston Good question ... Maybe use a library that supports hardware acceleration?

**Comment by Aokromes** [comment]
continue at https://github.com/telegramdesktop/tdesktop/issues/6312 :) i pointed a lib there.
