### ISSUE TITLE
 High memory usage on Animation/gif auto-play

### ISSUE THREAD

**Issue by c0re100** [telegramdesktop/tdesktop#7287]
### Steps to reproduce
1. Enable auto-play animations in advanced setting
2. Open task manager and go to https://t.me/AnimeHDGifs
3. Scroll up to view all animation messages until telegram desktop crash(OOM).
*Please keep monitoring Telegram Desktop's memory usage in task manager when scroll up*

### Expected behaviour
Animation/gif should not use too much memory.

### Actual behaviour
Animation/gif use so much memory.

### Configuration
**Operating system:** Windows 10 1909

**Version of Telegram Desktop:** Telegram Desktop 1.9.x/2.0.x/2.1.x/2.2.x/2.3.x/2.4.x/2.5.x/2.6.x Series 

<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by c0re100** [comment]
Well, I don't know I need to open a new issue or not? 
Cause it related High memory usage with auto-play issue. 
But I guess it should be fixed after this issue is solved.

### Steps to reproduce
1. Enable auto-play animations in advanced setting
2. Open task manager and go to https://t.me/AnimeHDGifs
4. Search #恋する小惑星 in Channel (~10 messages)
5. Click this 10 messages faster.
***Out Of Memory immediately.

### Expected behaviour
TDesktop should free allocated memory if you're not viewing specific animation message.

### Actual behaviour
Allocated memory doesn't free when you're jump to old messages via link or search. 
Cause High memory usage issue, a new huge allocated memory is on the way.
After 3-4 clicks(click faster of coz), TDesktop should OOM.

**Comment by c0re100** [comment]
> Well, I don't know I need to open a new issue or not?
> Cause it related High memory usage with auto-play issue.
> But I guess it should be fixed when this issue is solved.
> 
> ### Steps to reproduce
> 1. Enable auto-play animations in advanced setting
> 2. Open task manager and go to https://t.me/AnimeHDGifs
> 3. Search #恋する小惑星 in Channel (~10 messages)
> 4. Click this 10 messages faster.
>    ***Out Of Memory immediately.
> 
> ### Expected behaviour
> TDesktop should free allocated memory if you're not viewing specific animation message.
> 
> ### Actual behaviour
> Allocated memory doesn't free when you're jump to old messages via link or search.
> Cause High memory usage issue, a new huge allocated memory is on the way.
> After 3-4 clicks(click faster of coz), TDesktop should OOM.

Linux have same behaviour.
But Windows have free allocated memory when you switch to another chat, but Linux haven't.

**Comment by Aokromes** [comment]
this issue is still valid?

**Comment by c0re100** [comment]
> this issue is still valid?

Yes, still reproduce in v2.1.8

**Comment by john-preston** [comment]
@c0re100 Then I’m afraid it is used for the video frames.
