### ISSUE TITLE
[Feature Request] Adding new files when editing

### ISSUE THREAD

**Issue by AlphaHot** [telegramdesktop/tdesktop#7288]
### Is your feature request related to a problem?
I can't attach a new media file while editing a message.

### Describe the solution you'd like
I want to attach a new media file while editing a message.

### Describe alternatives you've considered
-------

## Additional context
https://github.com/telegramdesktop/tdesktop/blob/master/Telegram/SourceFiles/history/history_widget.cpp#L4259-L4262

![image](https://user-images.githubusercontent.com/58410019/75321212-14767b00-5892-11ea-806f-d69abe36c869.png)

**Comment by AlphaHot** [comment]
```diff
- if (_editMsgId) {
-    Ui::show(Box<InformBox>(tr::lng_edit_caption_attach(tr::now)));
-    return;
-}
```

**Comment by john-preston** [comment]
@AlphaHot This won't work. Editing only allows to replace one message with another, you can't add new messages in the middle of the conversation.

**Comment by AlphaHot** [comment]
@john-preston will you make it possible to add files while editing a message or not?

**Comment by john-preston** [comment]
@AlphaHot Not. It is not supported by the server side.

**Comment by AlphaHot** [comment]
@john-preston why is server code not open source?

**Comment by john-preston** [comment]
@AlphaHot I have no idea.
