### ISSUE TITLE
No proper migration from ~/.TelegramDesktop to ~/.local/share/TelegramDesktop

### ISSUE THREAD

**Issue by bodqhrohro** [telegramdesktop/tdesktop#7289]
### Steps to reproduce
1. Upgrade to 1.9.19 beta.
2. Hit "Quit Telegram".
3. Start Telegram over.

### Expected behaviour
The migration should happen seamlessly, by moving the old directory's content to the new place.

### Actual behaviour
Telegram has just switched the configuration folder and started like it's brand new. Not only I had to reconfigure it, but also to put in the login code when authorizing, which didn't seem to happen when I had lost the configuration before. I'm lucky because I have other clients activated, but somebody who has only this client activated may become locked out.

### Configuration
**Operating system:** Debian 11

**Version of Telegram Desktop:** 1.9.19 beta

**Used theme**: Classic

**Comment by john-preston** [comment]
@bodqhrohro Are you sure this is the case? Migration from ~/.TelegramDesktop to ~/.local/share/TelegramDesktop happened years and tens of versions ago.

**Comment by bodqhrohro** [comment]
@john-preston the last time when my `~/.TelegramDesktop/tdata` directory was changed is today at 16:01:03 UT+0200, right before the restart. And the `~/.local/share/TelegramDesktop` appeared only today. I noticed it only because I did an `ncdu` scan today and didn't quit the previous `ncdu` results that were scanned a few days ago.

Maybe there was some compatibility quirk which is broken now?

**Comment by john-preston** [comment]
@bodqhrohro I see, indeed it broke in the last two versions. Thanks!

**Comment by bodqhrohro** [comment]
Thanks. Does the accomplished migration mean that `~/.TelegramDesktop` may be safely deleted now, by the way?

**Comment by john-preston** [comment]
@bodqhrohro It should still be valid data if you just copy it to the new place (or wait for a new version).
