### ISSUE TITLE
Media auto-download preferences are reset after update

### ISSUE THREAD

**Issue by damnfella** [telegramdesktop/tdesktop#7290]
**Please don't reset my Media Auto-Download settings after an update**

![image](https://user-images.githubusercontent.com/51771172/75365008-94c4cc80-58e2-11ea-8e5e-0657b73e29e1.png)

- I am suffering internet data charges after every update. 
- Auto-downloading files by default should not be happening for groups and channels imo.

### Steps to Reproduce
1. Change the Media Auto-download settings
2. Update the app 
3. Get rekt with data charges when using mobile hotspot

### Configuration
**Windows 10 (1803)**
**Previous Version: TDesktop v1.9.18**
**Current Version: TDesktop v1.9.19**

**Comment by Aokromes** [comment]
for sure you got hit by the logout bug that reseted your settings.

**Comment by damnfella** [comment]
wait what? 🤔 

I thought the logout bug would log me out.
Actually, I didn't get logged out at all.

**Comment by damnfella** [comment]
well, this isn't an issue when updating to v1.9.22 beta

**Comment by Aokromes** [comment]
close if it's fixed then :)
