### ISSUE TITLE
Sending images from clipboard on Linux messes up colors

### ISSUE THREAD

**Issue by kodek16** [telegramdesktop/tdesktop#7292]
### Steps to reproduce
1. Use recent `imagemagick` on Linux (tested with v7.0.9-26).
2. Take a screenshot with `import -window root png:- | xclip -selection clipboard -t image/png`
3. Save the screenshot from clipboard to local file for later comparison: `xclip -selection clipboard -t image/png -o > original.png`
4. Paste the screenshot from clipboard to Telegram client, and use "send as file" ("send as image" has the same issue).
5. Download the sent image (file) from Telegram client.
6. Compare previously produces original file with downloaded file.

### Expected behaviour
Files are the same.

### Actual behaviour
Files are different, and the images actually look different on some clients (tested on Telegram Android, Telegram Web).

### Configuration
**Operating system:** Arch Linux

**Version of Telegram Desktop:** 1.9.14 / 1.9.19

**Used theme**: dark

<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

Screenshot illustrating how the problem looks on Android:

![image](https://user-images.githubusercontent.com/6691539/75384325-3564bd80-58de-11ea-90ea-08ef10d5abf6.png)

Above is the screenshot sent directly from clipboard, below is the same screenshot saved to file and sent from that file.

Actual files involved in the example:
![image_2020-02-26_21-21-25](https://user-images.githubusercontent.com/6691539/75384572-9db39f00-58de-11ea-9da4-4917fac32fee.png)
![original](https://user-images.githubusercontent.com/6691539/75384573-9db39f00-58de-11ea-99d5-eaba3627f311.png)

**Comment by jeffythedragonslayer** [comment]
Could it be getting compressed to JPEG wrong?  I'm not seeing a color difference like you when I try that but I did notice that if I upload a PNG, then try to "Save Image As..." the only file format available is "JPEG Image" and the resolution was reduced from 3840x2160 to 1280x720.

**Comment by annaproxy** [comment]
This is still reproducable on 2.0.1
![Screenshot of telegram update message, ironically](https://user-images.githubusercontent.com/32037919/78808928-adca9e00-79b5-11ea-99da-17888e3187a0.jpg)

**Comment by ilya-fedin** [comment]
Can't reproduce
```
Version: ImageMagick 7.0.9-0 Q16 x86_64 2020-04-03 https://imagemagick.org
Copyright: © 1999-2019 ImageMagick Studio LLC
License: https://imagemagick.org/script/license.php
Features: Cipher DPC HDRI OpenMP(4.5) 
Delegates (built-in): bzlib cairo djvu fontconfig freetype heic jng jp2 jpeg lcms lzma openexr png rsvg tiff webp x xml zlib
```
