### ISSUE TITLE
[Feature Request] Hotkey for silent message

### ISSUE THREAD

**Issue by winqooq** [telegramdesktop/tdesktop#7295]
### Is your feature request related to a problem?
Inconvenience of using silent messages

### Describe the solution you'd like
Add hotkey to send silent messages

### Describe alternatives you've considered
The ability to switch the send type from normal to silent message

### Additional context
¯\_(ツ)_/¯

**Comment by RadRussianRus** [comment]
There is an option to add shortcut for sending messages silently in `shortcuts-custom.json` in your `tdata` profile folder. This option called  `message_silently`, and was added in 7d51999 (TD 1.9.7+).

**Comment by Partizanin** [comment]
add custom shortkey, thanks 
![image](https://user-images.githubusercontent.com/5072597/87301170-c1872280-c517-11ea-99b8-2b70461edaec.png)
