### ISSUE TITLE
Microphone indicator at test (1.9.19 beta)

### ISSUE THREAD

**Issue by winqooq** [telegramdesktop/tdesktop#7296]
### Steps to reproduce
1. Open settings → Advanced → Call settings
2. Test microphone 

### Expected behaviour
Microphone indicator works

### Actual behaviour
In audio messages and calls, the sound comes from the microphone. But during testing, the indicator does not respond

### Configuration
Windows 7 x64 Ultimate (Assembly 7601)
Telegram Desktop 1.9.19 beta
Built in. Classic

[Screen video recording (imgur)](https://imgur.com/a/0MAxKnI)

**Comment by DP0150** [comment]
The same problem exists in Windows 10 Pro 1909 and Telegram Desktop 2.0.2.

**Comment by Aokromes** [comment]
for me now test mic works.

**Comment by winqooq** [comment]
@Aokromes, yes, this is fixed in TDesktop v2.3.1
