### ISSUE TITLE
Computer freezes while using telegram-desktop

### ISSUE THREAD

**Issue by EnriPv** [telegramdesktop/tdesktop#7297]
### Steps to reproduce
Just using the telegram-desktop app (the first time it occurred when I clicked in "create poll" in a group chat, not sure if it's correlated)
### Actual behaviour
The whole system frozen while using the application. It occurred several times only when using telegram-desktop.
I had to hard reboot the machine with the power button because nothing else worked.

### Configuration
Arch Linux x86_64
DE: Plasma
**Version of Telegram Desktop:**
1.9.14-2
**Used theme**:

<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by Aokromes** [comment]
i sugest you to try official package from desktop.telegram.org or releases of github. if it still freezes i sugest you to try beta version.

**Comment by ilya-fedin** [comment]
Why do you think that telegram is the case and not some kernel panic from bad wifi drivers?

**Comment by EnriPv** [comment]
I'm sorry, I had the same problem again and it wasn't related to Telegram

Ottieni Outlook per Android<https://aka.ms/ghei36>

________________________________
