### ISSUE TITLE
Clicking on tray icon or notification don't always bring window to front

### ISSUE THREAD

**Issue by definitio** [telegramdesktop/tdesktop#7302]
### Steps to reproduce
1. Click on Telegram icon on the taskbar or Telegram notification

### Expected behaviour
The Telegram window should appear in front of all other windows.

### Actual behaviour
Telegram window is on focus but remains hidden behind other windows.

### Configuration
**Operating system:**
Manjaro 19.0.1. Linux 5.5.6-1. KDE Plasma 5.17.5.

**Version of Telegram Desktop:**
v 1.9.14

**Used theme**:
Night

**Comment by ilya-fedin** [comment]
> Telegram window is on focus but remains hidden behind other windows.

Wayland?

**Comment by definitio** [comment]
@ilya-fedin X11

**Comment by mirh** [comment]
And similarly, clicking on notifications isn't able to bring the window in the foreground.

**Comment by Aokromes** [comment]
this issue is still valid?

**Comment by mirh** [comment]
Yes. 
I have to click furiously like twice or thrice on the tray icon because at least that could work.

**Comment by ilya-fedin** [comment]
Tray icon uses showFromTray:
https://github.com/telegramdesktop/tdesktop/blob/361b99b0c9c9f69bc8479a4413dbe62113405734/Telegram/SourceFiles/mainwindow.cpp#L143

Notifications are using showFromTray and reActivateWindow:
https://github.com/telegramdesktop/tdesktop/blob/361b99b0c9c9f69bc8479a4413dbe62113405734/Telegram/SourceFiles/window/notifications_manager.cpp#L615-L616

showFromTray uses activate:
https://github.com/telegramdesktop/tdesktop/blob/361b99b0c9c9f69bc8479a4413dbe62113405734/Telegram/SourceFiles/mainwindow.cpp#L744

activate uses Qt's setWindowState, setVisible, telegram's psActivateProcess and Qt's activateWindow:
https://github.com/telegramdesktop/tdesktop/blob/361b99b0c9c9f69bc8479a4413dbe62113405734/Telegram/SourceFiles/mainwindow.cpp#L715-L718

psActivateProcess on linux does nothing, seems to be mac-specific:
https://github.com/telegramdesktop/tdesktop/blob/361b99b0c9c9f69bc8479a4413dbe62113405734/Telegram/SourceFiles/platform/linux/specific_linux.cpp#L1066-L1068

reActivateWindow seems to be a linux-specific hack to focus on a right inner widget:
https://github.com/telegramdesktop/tdesktop/blob/361b99b0c9c9f69bc8479a4413dbe62113405734/Telegram/SourceFiles/window/main_window.cpp#L552-L569

I have no idea why this might not work, but I can reproduce this too

**Comment by definitio** [comment]
Still an issue.

**Comment by ilya-fedin** [comment]
> Still an issue.

Maybe this is some kwin bug after all?

**Comment by ilya-fedin** [comment]
@definitio please check if you have focus stealing prevention enabled in KDE settings and disable it if you have

**Comment by mirh** [comment]
I'm pretty sure to have tried all the settings 6 months ago, and none was really good.

**Comment by ilya-fedin** [comment]
I don't have any issues if I set to None here

**Comment by definitio** [comment]
@ilya-fedin It works for me. Thanks.
