### ISSUE TITLE
Possible blacklisting of @gif search terms

### ISSUE THREAD

**Issue by eldstal** [telegramdesktop/tdesktop#7303]
### Steps to reproduce
1. Open either the Windows app or the Android app (Telegram or Telegram X)
2. Enter a group chat
3. Enter the text `@gif putin` or `@gif vladimir`
4. Wait

### Expected behaviour
GIF search results should appear, as they do with any other search term. Type in `@gif kitten` and it works fine. `@gif trump` and `@gif medvedev` both work as expected.

### Actual behaviour
Nothing happens. The search is ignored and no results are presented.
`@gif` uses giphy.com, and on their site from the same machine I do get relevant hits.
Interestingly, the same search terms work fine in telegram with `@pic` which uses Yandex.

### Configuration
**Operating system:**
Windows 10, Android P

**Version of Telegram Desktop:**
1.9.14 on one windows machine.
Telegram X 0.22.4.1272-arm64-v8a on one android device.

Confirmed by 5 other users on different machines, some Windows and some Android.

**Used theme**:
Default

**Comment by RememberTheAir** [comment]
lol true

**Comment by ShiSHcat** [comment]
lol true

**Comment by Aokromes** [comment]
is it fails on other than telegram desktop very likely it's not telegram desktop issue.

**Comment by issaries** [comment]
Tried it out on two more devices with the same result.
First one being Telegram 1.9.14 on Archlinux.
Second is v5.15.0 (1869) on Android.

Also get the same result when searching for Hong Kong.

**Comment by develroo** [comment]
use @gif Russia. You will get plenty of Putin memes if that is what you are looking for.

**Comment by eldstal** [comment]
> 
> 
> use @gif Russia. You will get plenty of Putin memes if that is what you are looking for.

That's cool, but not the point. I agree that this isn't an issue with telegram desktop (the issue can remain closed, I'm trying to contact the backend folks)
