### ISSUE TITLE
[Feature Request] Build without wayland

### ISSUE THREAD

**Issue by PetrusZ** [telegramdesktop/tdesktop#7304]
### Is your feature request related to a problem?
No. But we don't need wayland. We already have xorg.

### Describe the solution you'd like
Build tdesktop without wayland.

### Describe alternatives you've considered
Add a build option, let us build without wayland.

**Comment by ilya-fedin** [comment]
Wayland support is in Qt, not tdesktop itself. Wayland support was enabled just in static binary builds, no difference with custom dynamic builds.

**Comment by PetrusZ** [comment]
My bad, thank you for your explanation.

**Comment by cca310** [comment]
> Wayland support is in Qt, not tdesktop itself. Wayland support was enabled just in static binary builds, no difference with custom dynamic builds.

Will the telegram desktop snap ever get wayland support?

**Comment by ilya-fedin** [comment]
https://github.com/telegramdesktop/tdesktop/blob/dev/snap/snapcraft.yaml#L24 (not soon, I guess)
