### ISSUE TITLE
tg:// not working on many devises on desktop

### ISSUE THREAD

**Issue by mishell-trickster** [telegramdesktop/tdesktop#7305]
I try to open chat via tg://resolve?domain=mishell_zero

It should open chat, but open only telegram app(not target chat). 

Telegram version: 1.9.14
OS: Linux, Windows, MacOS
Theme: Default

I tried this on 6 devices. 1 linux, 1 mac, 4 windows. Only on 2 windows laptops its work. Another devices just open app. 

This is bug? What should I do?

**Comment by ilya-fedin** [comment]
Try to open settings and write (as a cheat code, without a text field) `registertg`

**Comment by mishell-trickster** [comment]
> Try to open settings and write (as a cheat code, without a text field) `registertg`

Dont work, I see same bug. And this is not fix formally, because another people dont know about this method.

**Comment by ilya-fedin** [comment]
I don't know about windows/macos, but maybe I can help with linux.
Do you using official binary or snap/flatpak/distribution package?
If the first, can you attach ~/.local/share/applications/telegramdesktop.desktop?

**Comment by Aokromes** [comment]
@mishell-trickster

**Comment by mishell-trickster** [comment]
> I don't know about windows/macos, but maybe I can help with linux.
> Do you using official binary or snap/flatpak/distribution package?
> If the first, can you attach ~/.local/share/applications/telegramdesktop.desktop?

I use official binary.
This is my desktop file:

_[Desktop Entry]
Version=1.0
Name=Telegram Desktop
Comment=Official desktop version of Telegram messaging app
TryExec=/home/mishell/Desktop/Telegram
Exec=/home/mishell/Desktop/Telegram -- %u
Icon=telegram
Terminal=false
StartupWMClass=TelegramDesktop
Type=Application
Categories=Chat;Network;InstantMessaging;Qt;
MimeType=x-scheme-handler/tg;
Keywords=tg;chat;im;messaging;messenger;sms;tdesktop;
X-GNOME-UsesNotifications=true_

**Comment by ilya-fedin** [comment]
`xdg-mime query default x-scheme-handler/tg`

**Comment by Aokromes** [comment]
@mishell-trickster

**Comment by Aokromes** [comment]
no answer for over a month, closing.if this bug is still valid open a new ticket using updated version.
