### ISSUE TITLE
Extremely High CPU Usage - Internal Video Player (Mac)

### ISSUE THREAD

**Issue by MoE1N** [telegramdesktop/tdesktop#7307]
### Steps to reproduce
Watching a video on Telegram Desktop (Mac) using the internal video player.

### Actual behaviour
Telegram process CPU usage goes high up to 105% and the MacBook fans start going loud. 
If the video is of high quality, the CPU usage is higher!

### Configuration
**Operating system:**
macOS 10.15.3

**Version of Telegram Desktop:**
1.9.14

**Used theme**:
Default

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/6312 generic bug.

**Comment by MoE1N** [comment]
> #6312 generic bug.

This is a different one!

There is no problem with the playback!
No problem with the FPS!

But CPU usage goes very high, doesn't matter if you're in fullscreen mode or not, or in 4k resolution or not.

**Comment by Aokromes** [comment]
the cpu usage goes very high because no hardware acceleration.

**Comment by mohammad1ta** [comment]
Same issue
