### ISSUE TITLE
Crash after opening a link

### ISSUE THREAD

**Issue by mirhl** [telegramdesktop/tdesktop#731]
I had just opened a link (and switched chat) when program hanged, then crashed. 
I attached the dump below.

It's a zip file, you just have to rename the jpg. 

![telegram-0 8 13-20150518-190108-4628-2928.jpg](https://cloud.githubusercontent.com/assets/9366725/7686010/046f4066-fd93-11e4-92a3-616a90bd0899.jpg)

**Comment by telegramdesktop** [comment]
Thank you for your report! It will be great, if you could provide some more details. Was this a regular outside-going http/https link or some special link? You clicked it -> it was opened -> you activated Telegram window back and switched to other chat?

**Comment by mirhl** [comment]
I sent a link (or I received a link, I can't remember) I clicked on it, telegram seemed "to be sending" the link to firefox
And before the "sending" could end (I mean.. at least firefox didn't open a new tab in the meantime) I switched to another chat and windows waiting cursor came out (aka Windows error reporting had been triggered)

**Comment by auchri** [comment]
Fixed?

**Comment by mirhl** [comment]
Well, it's not like I could reproduce the crash in the first place, so I wouldn't know how to confirm. 
I just hoped the log could suggest you something. 

You are free to close this report if you believe people shouldn't be affected anymore.

**Comment by auchri** [comment]
I'll close this, please open a new issue if this happens again :)
