### ISSUE TITLE
Inline query photo results are always shown as gallery

### ISSUE THREAD

**Issue by delivrance** [telegramdesktop/tdesktop#7310]
### Steps to reproduce
1. Have a bot answer to inline queries with photo results and without setting the `gallery` flag in `messages.SetInlineBotResults` (i.e.: no gallery). You can only do this by using custom MTProto libraries such as Pyrogram, because the current Bot API doesn't allow you setting this parameter.
2. Query the bot.

### Expected behaviour
TDesktop should respect the `gallery` argument and show title+description like TAndroid does:
![image](https://user-images.githubusercontent.com/14043624/75630319-04d89880-5bea-11ea-81ac-029622c6a598.png)
Telegram Android with `gallery=False`; title and description are shown.

![image](https://user-images.githubusercontent.com/14043624/75630324-0b671000-5bea-11ea-95fc-db6f0ff2801d.png)
Telegram Android with `gallery=True`; full-width photos without title/description.

### Actual behaviour
No matter what the `gallery` value is, the result is the same:
![image](https://user-images.githubusercontent.com/14043624/75630343-5f71f480-5bea-11ea-8366-b41c0a3e551d.png)
Telegram Desktop

### Configuration
**Operating system:** macOS 10.15.3

**Version of Telegram Desktop:** 1.9.14

**Used theme**: -

**Comment by Aokromes** [comment]
this issue is still valid?

**Comment by Aokromes** [comment]
no answer after more than 1 month, closing, if this bug is still valid open a new ticket using updated telegram version.
