### ISSUE TITLE
Incorrect display/rendering of Malayalam language in version 1.9.19 beta

### ISSUE THREAD

**Issue by zcraber** [telegramdesktop/tdesktop#7312]
### Steps to reproduce

1. Open Telegram Desktop in Windows 10
2. Paste this dummy Malayalam text in **Saved Messages**:
> അമ്പൂളീശ് പ്രവാലം ആഡോയിഴിഞ്ഞു എന്നാമിസ ഫ്രാള്ളിപ്പി മോച നാമാവിശികു ലരിത് കൊച്ചാലിണ്ടര ജനിപാൻ മന്തലിക ഹമ്പസി അലവളപിശകി അപ്പിസ്ഥവത്ക്കരിക്കപ്പെട്ട പിര്യന്ത്ര.

### Expected behaviour
Correct rendering of Malayalam (version 1.2.6):

![image](https://user-images.githubusercontent.com/61133303/76099316-ea8b2a00-5ff0-11ea-98d2-2ec27fc2c7cc.png)

### Actual behaviour
Incorrect rendering of Malayalam (version 1.9.19 beta):

![image](https://user-images.githubusercontent.com/61133303/75651707-3d768180-5c7f-11ea-86db-e1498fac1d90.png)

### Configuration
**Operating system:**
Windows 10 Home
Version 1909

**Version of Telegram Desktop:**
1.9.19 beta

**Used theme**:
Default

<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by zcraber** [comment]
Just tried the 1.9.19 beta version and the issue still exists!

**Comment by jeffythedragonslayer** [comment]
I can't read Malayalam, but on 1.9.14 it looks like this:

![Malayalam](https://user-images.githubusercontent.com/13253146/76697028-55c7a280-6668-11ea-918e-6504796426ef.png)

Is that correct?

**Comment by zcraber** [comment]
> I can't read Malayalam, but on 1.9.14 it looks like this:
> 
> ![Malayalam](https://user-images.githubusercontent.com/13253146/76697028-55c7a280-6668-11ea-918e-6504796426ef.png)
> 
> Is that correct?

Yep, that's correct.

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/5172

**Comment by ilya-fedin** [comment]
Is this still valid?
