### ISSUE TITLE
[Feature Request] Shortcut for scheduled message

### ISSUE THREAD

**Issue by mkwork** [telegramdesktop/tdesktop#7316]
### Is your feature request related to a problem?
Scheduling message isn't available from keyboard.

### Describe the solution you'd like
Add shortcut to schedule current message e.g. <ctrl+s> or <ctrl+alt+enter>

**Comment by RememberTheAir** [comment]
As stated in [this](https://github.com/telegramdesktop/tdesktop/issues/7295#issuecomment-591719744) comment, you can add a `message_scheduled` key to your `tdata/shortcuts-custom.json` (more info in the linked comment)

**Comment by RadRussianRus** [comment]
@mkwork Is this still valid? You can set your own hotkey, as stated in previous comment.

**Comment by mkwork** [comment]
Thanks! It works. I've missed previous post notification.
