### ISSUE TITLE
[Feature Request] Ding.. Ding... Ding-Di-Di-Ding! Repeat notifications per chat in short succession are awful

### ISSUE THREAD

**Issue by GlassedSilver** [telegramdesktop/tdesktop#7318]
### Is your feature request related to a problem?
I think quite a few of us have those friends who message us in short and numerous messages rather than always a long message, patiently waiting for a reply. Mind you, I'm not blaming my friends and tbh I'm like that myself often times. This results on the other end in a jarring and INCREDIBLY annoying notification orchestra. I am NOT saying they are annoying me. I like that my friends can get excited and stuff. (if any of ya'll are reading this. :P)

### Describe the solution you'd like
However... I would like to hear a ding/have my phone vibrate/whatever ONCE per chat per let's say... 2-5 mins?

### Describe alternatives you've considered
Turn off notifications? Impractical...
Silent modes? Well... I already leave my phone on silent too often... It does generate other problems...
"Send as silent message" is something the sender has to do and it's impractical over time and clunky. It's good for one-off messages and I'm happy it's a thing. But this is a receiver concern, not a sender's issue necessarily.

### Additional context
n/a

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/429

**Comment by GlassedSilver** [comment]
2015 - ouch. And the Android app HAD it and then partially removed the feature......

Not holding my breath then.
