### ISSUE TITLE
[Question] I want to compile the release version of telegram through github action, but I got an error when compiling the fork project. Can you help me find out the problem?

### ISSUE THREAD

**Issue by indiff** [telegramdesktop/tdesktop#7322]
I want to compile the release windows version of telegram through Github action, but I got an error when compiling the fork project. Can you help me find out the problem?
我想通过 github action编译windows telegram的正式版本，但是我fork的项目编译的时候报错了， 能否帮忙看下问题在哪里？
https://github.com/indiff/tdesktop
https://github.com/indiff/tdesktop/blob/dev/.github/workflows/win.yml

**Comment by ilya-fedin** [comment]
Even if you fix the error, you can't build release version on github actions due to time limit. Release linker runs for multiple hours.

**Comment by indiff** [comment]
Did you build the release version on your own computer
