### ISSUE TITLE
Unable to add admin to a Telegram Supergroup - "Could not add user. Please try again later."

### ISSUE THREAD

**Issue by T-V-N** [telegramdesktop/tdesktop#7326]
### Steps to reproduce
1. Given a supergroup with the deleted creator. 
2. There are several admins with full rights including adding new admins

### Expected behaviour
Admins with the "Add new admins" right must be able to add new admins.

### Actual behavior
If an admin with the "Add new admins" right tries to add a new admin or bot(different users/bots tested) - the app returns an error "Could not add user. Please try again later."

### Configuration
**Operating system:**
Bug appears both on Linux/Windows versions.

**Version of Telegram Desktop:**
1.9.14
**Used theme**:
Standart theme

**Comment by jeffythedragonslayer** [comment]
In add_contact_box.cpp the function ShowAddParticipantsError() is the only place that generates the lang.string called lng_failed_add_participant which expands to that error message.  In this immediately invoked initializing lambda expression (IIILE) way at the bottom see:

```
const auto text = [&] {
                if (error == qstr("USER_BOT")) {
                        return tr::lng_cant_invite_bot_to_channel(tr::now);
                } else if (error == qstr("USER_LEFT_CHAT")) {
                        // Trying to return a user who has left.
                } else if (error == qstr("USER_KICKED")) {
                        // Trying to return a user who was kicked by admin.
                        return tr::lng_cant_invite_banned(tr::now);
                } else if (error == qstr("USER_PRIVACY_RESTRICTED")) {
                        return tr::lng_cant_invite_privacy(tr::now);
                } else if (error == qstr("USER_NOT_MUTUAL_CONTACT")) {
                        // Trying to return user who does not have me in contacts.
                        return tr::lng_failed_add_not_mutual(tr::now);
                } else if (error == qstr("USER_ALREADY_PARTICIPANT") && hasBot) {
                        return tr::lng_bot_already_in_group(tr::now);
                } else if (error == qstr("BOT_GROUPS_BLOCKED")) {
                        return tr::lng_error_cant_add_bot(tr::now);
                } else if (error == qstr("PEER_FLOOD")) {
                        const auto isGroup = (chat->isChat() || chat->isMegagroup());
                        return PeerFloodErrorText(isGroup
                                ? PeerFloodType::InviteGroup
                                : PeerFloodType::InviteChannel);
                } else if (error == qstr("ADMINS_TOO_MUCH")) {
                        return ((chat->isChat() || chat->isMegagroup())
                                ? tr::lng_error_admin_limit
                                : tr::lng_error_admin_limit_channel)(tr::now);
                }
                return tr::lng_failed_add_participant(tr::now);
        }();
```

**Comment by T-V-N** [comment]
I tested in a new group and still had the same problem.

**Comment by ilya-fedin** [comment]
Are you sure that this is a bug in tdesktop and there are no chance that server really forbids adding new admins?

**Comment by T-V-N** [comment]
> Are you sure that this is a bug in tdesktop and there are no chance that the server really forbids adding new admins?
It is. After some tests with other accounts, I've figured out that the telegram servers have silly restrictions against accounts blocked for spam. Apart from reasonable limitations (like inability to send messages to public groups and users who haven't added you to their contacts list) telegram prevents my account of adding admins to the groups created by me.
Looks like the desktop and mobile apps need explicit error message for such restriction like "You can't add admins since your account is banned from that" or so.

**Comment by ilya-fedin** [comment]
Then this is not a tdesktop bug

**Comment by T-V-N** [comment]
> Then this is not a tdesktop bug

The desktop, web, and both mobile apps have the same behavior - they display misleading error messages in the explained case.

**Comment by ilya-fedin** [comment]
And therefore this is is not a client-side bug and the issue can be closed

**Comment by T-V-N** [comment]
> And therefore this is is not a client-side bug and the issue can be closed

I've tested the case again using the same account:
TG version: 7.0 (204394) Stable
Platform: MacOS

The app doesn't display any messages after I add an admin to the telegram group. The admin isn't being added. 
![Kapture 2020-08-29 at 12 53 20](https://user-images.githubusercontent.com/7194885/91634145-b9ffd800-e9f6-11ea-8ec5-7ccc15530870.gif)

The app should at least display something even if there is an error from the backend, isn't it?

**Comment by ilya-fedin** [comment]
> TG version: 7.0 (204394) Stable

This is not tdesktop
