### ISSUE TITLE
Spelling error - wrong suggestion

### ISSUE THREAD

**Issue by Greendq** [telegramdesktop/tdesktop#7327]
### Steps to reproduce
1. Write word (in Russian) "где-нибудь" in the chat window
2. Internal spell-checker mark it with red underline
3. Internal spell-checker suggest second word to be replaced with "ни будь" which is wrong.

### Expected behaviour
No spelling errors should be displayed, correct spelling is "где-нибудь".

### Actual behaviour
Spellchecker report wrong spelling, which is incorrect.

### Configuration
**Operating system:** Windows 10 Pro English

**Version of Telegram Desktop:** 1.9.14

**Used theme**: Default light.

<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by Aokromes** [comment]
plz update to 1.9.19 beta.

**Comment by Greendq** [comment]
Bug persists:
![image](https://user-images.githubusercontent.com/4447232/75911521-5e45ff00-5e58-11ea-874a-2fd2605a75e4.png)

**Comment by Neurotoxin001** [comment]
1.9.14 no issue
![image](https://user-images.githubusercontent.com/39812401/75918564-05349600-5e6d-11ea-8784-ab4bfbe2e696.png)

**Comment by Greendq** [comment]
@Neurotoxin001 - did you installed any additional dictionaries? Is it possible that the dictionaries depend on GUI language?

**Comment by Neurotoxin001** [comment]
> did you installed any additional dictionaries
No. I have english language but it's same with russian

**Comment by ilya-fedin** [comment]
> Windows 10 Pro English

But tdesktop uses system spellcheck on win10, so tdesktop can't do anything about that :thinking:
