### ISSUE TITLE
[Question]  msg_incoming doesn't work for all channels?

### ISSUE THREAD

**Issue by waifwaif** [telegramdesktop/tdesktop#7329]
I have two telegram accounts (for testing)
and I broadcasted a message in 3 different private channels I created to test a custom notification sound.  2/3 worked.  any guesses why the third channel didn't work?  Thank you..

**Comment by jeffythedragonslayer** [comment]
Were you able to collect any debug logs?

**Comment by ilya-fedin** [comment]
> any guesses why the third channel didn't work?

Should work for any type of messages:
https://github.com/telegramdesktop/tdesktop/blob/dev/Telegram/SourceFiles/window/notifications_manager.cpp#L310
https://github.com/telegramdesktop/tdesktop/blob/dev/Telegram/SourceFiles/window/notifications_manager.cpp#L471
