### ISSUE TITLE
Missing checkbox when upload video

### ISSUE THREAD

**Issue by danielperez9430** [telegramdesktop/tdesktop#7331]
I need the possibility to send a video as a file again in Telegram Desktop. Before I could do, currently in Windows that checkbox is completely missing.

And I don't like the solution "compress the file in a Zip". I want to send things in the same way that can be done in the normal Telegram and in TG X as a file. Including videos (.MP4 and others)

I need a solution, thanks you

**Comment by jeffythedragonslayer** [comment]
Can you screenshot what you are seeing?  Or is the add caption dialog box gone as well?

**Comment by Aokromes** [comment]
try on 1.9.20 beta plz.

**Comment by danielperez9430** [comment]
@Aokromes I test beta 1.9.20 and still dont work

![](https://i.imgur.com/38MXGQ8.jpg)

**Comment by danielperez9430** [comment]
Telegram Desktop v2.4.5 and still missing
 
![imagen](https://user-images.githubusercontent.com/10388515/97785522-d90d1880-1ba5-11eb-84cf-4cdbf840fd7b.png)
