### ISSUE TITLE
Telegram autostarts in weird state

### ISSUE THREAD

**Issue by remcohaszing** [telegramdesktop/tdesktop#7332]
# Steps to reproduce

1. Configure Telegram to autostart in the system tray.
2. Reboot

*~/.config/autostart/telegramdesktop.desktop*:

```ini
[Desktop Entry]
Version=1.0
Name=Telegram Desktop
Comment=Official desktop version of Telegram messaging app
TryExec=/home/remco/.local/share/Telegram/Telegram
Exec=/home/remco/.local/share/Telegram/Telegram -autostart
Icon=telegram
Terminal=false
StartupWMClass=TelegramDesktop
Type=Application
Categories=Chat;Network;InstantMessaging;Qt;
MimeType=x-scheme-handler/tg;
Keywords=tg;chat;im;messaging;messenger;sms;tdesktop;
X-GNOME-UsesNotifications=true
```

### Expected behaviour

Telegram autostarts hidden in the system tray.

### Actual behaviour

Sometimes the expected, sometimes what is shown in this screenshot:

![image](https://user-images.githubusercontent.com/779047/75962142-7e5ed800-5ec3-11ea-9b99-282309b732ad.png)

### Configuration

**Operating system:** Pop_OS! 19.10

**Version of Telegram Desktop:** 1.9.19 beta

**Used theme**: Custom

**Comment by Aokromes** [comment]
i am quite sure this is duplicate

**Comment by Aokromes** [comment]
ok, it's duplicate of one ancient ticket i closed after asking if it's still valid, i leave this open.
https://github.com/telegramdesktop/tdesktop/issues/512

**Comment by Aokromes** [comment]
this issue is still valid on 2.1.8?

**Comment by ilya-fedin** [comment]
> this issue is still valid on 2.1.8?

Yes, I fitghting with this, but fix breaks Windows and I don't know how to debug on Windows...

**Comment by remcohaszing** [comment]
After nog having encountered the issue for months, I just ran into the problem after pressing the _Upgrade Telegram_ button to upgrade to version 2.2.
