### ISSUE TITLE
Notification icon does not appear in Ubuntu 18.04.4 top bar

### ISSUE THREAD

**Issue by thelonelybard** [telegramdesktop/tdesktop#7334]
### Steps to reproduce
1. Install Telegram Desktop using the CLI command from www.flathub.com
2. Run Telegram Desktop
3. All works well it seems except for the Notification Icon in top bar which is invisible

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

After installing Telegram Desktop, everything worked well. Except for the Notification badge in the top bar. It is there, but invisible (attached screenshot)

### Configuration
**Operating system:**
Ubuntu Linux 18.04.4 (x86_64)
**Version of Telegram Desktop:**
v 1.9.12 11.02.20
**Used theme**:
Tinted
<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>
![Screenshot from 2020-03-05 14-13-08](https://user-images.githubusercontent.com/60025528/75971630-7d41a100-5eeb-11ea-9083-21f640e62b7f.png)

**Comment by ilya-fedin** [comment]
> v 1.9.12

Please, upgrade to actual version (1.9.14). 
And check on the beta version (v1.9.19).

**Comment by ilya-fedin** [comment]
So what? :thinking:

**Comment by thelonelybard** [comment]
Hello,

What do you mean by so what?

**Comment by thelonelybard** [comment]
thank you. will do

**Comment by ilya-fedin** [comment]
> What do you mean by so what?

I tried to ask if you tried or not :)

**Comment by thelonelybard** [comment]
Okay, was a bit abrupt and I didnt know what u meant. 😅😅😅

So, i had to change my hdd and reinstall Ubuntu.

Okay. Just installed via flatpak and nope. Version 1.9.14 Telegram Desktop
still does not show the icon on the top tray. 😭




𝕭𝖊𝖗𝖙𝖗𝖆𝖓𝖉 𝕮.𝕾 𝕭𝖆𝖗𝖇𝖎𝖊𝖗

**Comment by ilya-fedin** [comment]
> Version 1.9.14

What on 1.9.19 beta?

**Comment by thelonelybard** [comment]
Ill try the beta and revert yo you. Thank you



𝕭𝖊𝖗𝖙𝖗𝖆𝖓𝖉 𝕮.𝕾 𝕭𝖆𝖗𝖇𝖎𝖊𝖗

**Comment by thelonelybard** [comment]
Okay. So the beta shows the notification. Mist be sometbing beta has that
stable doesnt.


Okay since, im relatively new to Linux, do I keep the extracted package in
Downloads and open the Telegram app whenever I need tknuse Telegram? Or it
goes in a diff folder?


𝕭𝖊𝖗𝖙𝖗𝖆𝖓𝖉 𝕮.𝕾 𝕭𝖆𝖗𝖇𝖎𝖊𝖗

**Comment by ilya-fedin** [comment]
Emm... flatpak package uses ostree and you can't just grub the files and copy/move it.

**Comment by thelonelybard** [comment]
okay. I removed the flatpak (version). Did the install and removal using
Terminal. I thot Grub was only to do with booting the OS. I'll read about
ostree :D

I am still learning my way around Linux so far. I will stick to the Beta
version. I don't see (unofficial) in the Telegram service notifications; so
all is good :)

**Comment by Aokromes** [comment]
fixed on 1.9.19
https://github.com/flathub/org.telegram.desktop/issues/65
