### ISSUE TITLE
Gif selection pane sometimes keeps rendering in the background

### ISSUE THREAD

**Issue by wchristian** [telegramdesktop/tdesktop#7335]
This is a more clear description of at least one of the causes of #3640.

### Steps to reproduce
1. Run TG, enter chat, mouse over emoji icon, change to gif tab.
2. Mouse away from emoji icon, alt-tab out of TG.
3. Wait some time. (Exact time not yet determined, might also relate to other triggers.)
4. Check TG CPU usage in task manager. Eventually it will be high.
5. Go into a chat, mouse over the emoji button, change the tab away from gifs to emoji, close the chat.
6. Check CPU usage again. It will be low.

### Expected behaviour
At step 4 CPU usage should never be high.

### Actual behaviour
It appears gifs keep rendering in the background.

### Configuration
**Operating system:** Windows 10

**Version of Telegram Desktop:** 1.9.14

**Used theme**: Tinted

Some additional info:

https://github.com/telegramdesktop/tdesktop/issues/3640#issuecomment-593379391
> High CPU usage on Debian (60%).
> All chats are closed.
> perf shows TG decodes some video:
> $ perf report |grep -v '^#' | head -3
> 8.54% QThread Telegram [.] ff_h264_decode_mb_cavlc
> 2.47% QThread Telegram [.] ff_h264_filter_mb_fast
> 1.49% QThread Telegram [.] 0x00000000019f1ce1
> 
> Telegram 1.9.14

**Comment by john-preston** [comment]
@wchristian Thanks! I’ll try to reproduce that.

**Comment by Corginyan** [comment]
The same bug happens all the time. Windows 7 v1.9.19beta and earier versions.
