### ISSUE TITLE
[Feature request] Add audio/video call for secret (end-to-end).

### ISSUE THREAD

**Issue by Nokia808** [telegramdesktop/tdesktop#7337]
Hi Currently, audio call allowed only outside secret chat (it is not end to end encrypted). It will be great jump for Telegram if it will allow audio/video calls to be end-to-end encrypted within secret chats .....

Thank you.

**Comment by RememberTheAir** [comment]
Audio calls are _always_ e2e encrypted: https://telegram.org/blog/calls#secure

**Comment by Nokia808** [comment]
@RememberTheAir 
Thank you very much for explanation. Only one thing confusing: is this also applied for Desktop application? I conclude from your replay "Yes", but what confusing is that Desktop application still has no secret chat feature ! So, you are already implemented on-device local encryption of audio calls (e2ee) while it's basic (secret chats feature) still not included in Desktop application ?

**Comment by RememberTheAir** [comment]
@Nokia808 voice calls on every telegram app are e2e encrypted, this includes tdesktop. Voice calls do not require persistence because they will start and end while you have tdesktop open, and don't need to be stored
