### ISSUE TITLE
Crashes when selecting a file

### ISSUE THREAD

**Issue by robertgzr** [telegramdesktop/tdesktop#7343]
### Steps to reproduce
1. Click 'Attach file'
2. Move the pointer from main window onto file selection window
3. Telegram crashes

### Configuration
**Operating system:** Gentoo (Linux 5.5.7)

**Version of Telegram Desktop:** 1.9.19 beta

**Used theme**: Tinted

<details><summary><b>Logs</b>:</summary>

```
(Telegram:15306): Gtk-WARNING **: 15:30:57.366: Loading IM context type 'xim' failed
qt.qpa.wayland: Wayland does not support QWindow::requestActivate()
Gdk-Message: 15:31:00.759: Error reading events from display: Success
```

</details>

**Comment by jeffythedragonslayer** [comment]
Does "ulimit -c unlimited" give you a core dump?

**Comment by ilya-fedin** [comment]
> Does "ulimit -c unlimited" give you a core dump?

I can reproduce it as well just in VM with Wayland :(
`G_MESSAGES_DEBUG=all` gives more info (`interface 'wl_pointer' has no event 5`), but I have no idea how to fix it :(

**Comment by ilya-fedin** [comment]
btw, it doesn't even crashes, just closes

**Comment by WhyNotHugo** [comment]
From my testing, telegram closes  when the filechooser gains focus, not before.

For some reason the Arch binaries don't show this, so comparing differences in build _might_ help narrow down something.

**Comment by ilya-fedin** [comment]
> For some reason the Arch binaries don't show this

Static binary uses gtk directly to open file dialog, while distributive packages are using file dialog from platformtheme plugins.
When Qt linked statically, you can't load these plugins at runtime, you need to link them statically too. And if you link qgtk3, your binary will depend on gtk3. So, tdesktop uses QLibrary (dlopen) to load gtk3 and uses gtk api directly.
