### ISSUE TITLE
Delay when sending mesage

### ISSUE THREAD

**Issue by blueberry6401** [telegramdesktop/tdesktop#7344]
Sometimes, sending a message on Telegram for Mac takes 1 minute to send. 
![camphoto_1804928587](https://user-images.githubusercontent.com/7337535/76158598-fcccab80-6149-11ea-9c34-bdf52c061b49.JPG)
Then I'm using Telegram on iPhone to send, on the same network, everything goes smooth.

**Comment by Aokromes** [comment]
you don't put version, but that doesn't looks telegram desktop instead telegram for macos.
