### ISSUE TITLE
Autocomplete @username doesn't work when tagging someone in a group

### ISSUE THREAD

**Issue by rafitamolin** [telegramdesktop/tdesktop#7345]
### Steps to reproduce
1. Write part of the username of someone inside a group after @
2. In some cases, it isn't autocompleted _(in my case, in a group with 28 members, like 30% of their @'s don't work like below)_

### Expected behaviour
The user should be displayed in a list just above the chat, like this
![](http://s.chollo.to/98JfJ.png)

### Actual behaviour
It isn't autocompleted, it's like they aren't on the group.
![](http://s.chollo.to/98Uvz.png)
![](http://s.chollo.to/98tth.png)

### Configuration
**Operating system:** Windows 10 Pro 10.0.18362

**Version of Telegram Desktop:** 1.9.19 beta

**Used theme**: dark

**Comment by Aokromes** [comment]
confirmed.

**Comment by xscd** [comment]
Its probably related to https://github.com/telegramdesktop/tdesktop/issues/7325

**Comment by rafitamolin** [comment]
> Its probably related to #7325 
It definitely is! Thanks for mentioning it!

**Comment by Qwerty-Space** [comment]
This only seems to occur with contacts.

**Comment by RememberTheAir** [comment]
@Qwerty-Space happened to me with non-contacts too, unfortunately
