### ISSUE TITLE
Default name lin Linux OS

### ISSUE THREAD

**Issue by neesti** [telegramdesktop/tdesktop#7349]
Hello.
In Linux Mint OS, When I want to save an image (Or even any other file) from telegram to my hard drive, that image dose not save as default name and I MUST write a name for it to save it.

**Comment by ilya-fedin** [comment]
Can you reproduce on beta?

**Comment by Tids** [comment]
@neesti do you use telegram from flathub?

**Comment by neesti** [comment]
> Can you reproduce on beta?

I'm sorry because I'm using this operating system for work.
So I had to wait for the next stable release and then test this bug in that release.

**Comment by neesti** [comment]
> @neesti do you use telegram from flathub?

No. I downloaded Telegram from official site.

**Comment by Qwerty-Space** [comment]
Same issue on Manjaro with telegram-desktop-bin from the AUR

**Comment by ilya-fedin** [comment]
It was fixed a long time ago. Install the beta version.

**Comment by Qwerty-Space** [comment]
"a long time ago" but it hasn't been pushed to the stable branch yet?

**Comment by ilya-fedin** [comment]
Yes, there are no stable releases for ~month :(

**Comment by neesti** [comment]
This issue is solved in 1.9.21 
Thanks.
