### ISSUE TITLE
Bug: microphone working badly in Telegram Desktop

### ISSUE THREAD

**Issue by xmha97** [telegramdesktop/tdesktop#7350]
Hello, I using Telegram Desktop on Windows 10
I can use the microphone on Skype, Voice Recorder, Camera, Adobe Audition, etc.
But microphone working badly in Telegram Desktop.
Please listen to the below voices and compare them:
[Voices.zip](https://github.com/telegramdesktop/tdesktop/files/4309250/Voices.zip)

You should add microphone settings like skype.
![Skype](https://user-images.githubusercontent.com/23485114/76263409-10743100-6274-11ea-9d53-77a30248ffad.png)

**Comment by xmha97** [comment]
I don't have any issue with Unigram and microphone working fine in Unigram.

**Comment by ilya-fedin** [comment]
#4990? :thinking:
