### ISSUE TITLE
[Question] Hex ServerName not working for MTProto proxy

### ISSUE THREAD

**Issue by majidrahi** [telegramdesktop/tdesktop#7353]
Hello, this proxy link with hex server name (0x6DEB43B7) works on telegram desktop or telegram x but not works on main telegram:
https://t.me/proxy?server=0x6DEB43B7&port=1005&secret=7pyplbgayNEr5FvcVrNUueptYWlsLmdvb2dsZS5jb20=

but its normal form (109.235.67.183) work on every type of telegram

https://t.me/proxy?server=109.235.67.183&port=1005&secret=7pyplbgayNEr5FvcVrNUueptYWlsLmdvb2dsZS5jb20=

How can I use hex as server name for main telegram?

**Comment by Aokromes** [comment]
this bug tracker is telegram desktop only, maybe someone at https://t.me/tgbetachat can help you.
