### ISSUE TITLE
[Question][Linux] Should Telegram stay running in background when window is clossed?

### ISSUE THREAD

**Issue by alosarjos** [telegramdesktop/tdesktop#7358]
Since some days ago (Can't remember since when exactly, sorry). TelegramDesktop on Linux (More concretely Arch running the Gnome desktop) finishes the process when closing the window. Before it would run in the background (as expected?) but now closing the window even with the Ctrl+W shortcut (Instead of Ctrl+Q which closes the app instead of just the window) will finish the process too.

This happens in stable and beta. ¿Is this intentional?

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/7252
