### ISSUE TITLE
[Feature Request] Add "Ask question" link

### ISSUE THREAD

**Issue by mbnoimi** [telegramdesktop/tdesktop#736]
I suggest to add "Ask question" link in settings of desktop client in same way of mobile clients.

![photo_2015-05-20_20-12-45](https://cloud.githubusercontent.com/assets/284547/7731933/a5ab28b0-ff2c-11e4-96e0-fed60d360aca.jpg)

**Comment by auchri** [comment]
Implemented with 0.8.49 dev
