### ISSUE TITLE
[Feature Request] Make telegram support amharic fonts

### ISSUE THREAD

**Issue by Maruf-S** [telegramdesktop/tdesktop#7362]
### Is your feature request related to a problem?
Yes, when Amharic characters are in telegram desktop chats. they are not displayed.

### Describe the solution you'd like
Make telegram support Amharic fonts

### Additional context
Telegram is the second biggest platform in Ethiopia but still, the country's official language Amharic is not supported in the desktop application.

**Comment by Maruf-S** [comment]
Thanks in advance

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/4072#issuecomment-524523439
