### ISSUE TITLE
High quality / high framerate videos perform terribly even on high-end CPUs

### ISSUE THREAD

**Issue by Leon422** [telegramdesktop/tdesktop#7363]
### Steps to reproduce
1. Play a 1080p 60 FPS video or something along these lines (in this case I'm playing 1080p 60 FPS videos generated by Nvidia Shadowplay)
2. The video won't play smoothly at all

### Expected behaviour
The video should play smoothly

### Actual behaviour
The video stutters and plays terribly

### Configuration
**Operating system:** Windows 10

**Version of Telegram Desktop:** 1.9.14

**Used theme**: Dark theme

Specs: i7 9750H @ 4 GHz, RTX 2070, 32 GB RAM

<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/6312#issuecomment-525712797
