### ISSUE TITLE
windows client does not scale properly on multi-dpi monitor setup / change

### ISSUE THREAD

**Issue by halliba** [telegramdesktop/tdesktop#7364]
### Steps to reproduce
1. Use Telegram on 1080p external Monitor via docking station (100% Scale) / internal monitor is disabled
2. unplug Monitor and use Telegram on internal 4k monitor (200% Scale) without restart

### Expected behaviour
Telegram should apply the per monitor dpi settings from windows 10  and scale from 100% to 200% accordingly.

### Actual behaviour
Telegram keeps the 100% scaling and is quiet hard to use, even with my young eyes.
Same problem when switching to a lower dpi monitor -> not scaled down to 100%.
Closing the Telegram Windows (without exiting process) and reopen it does not help.

### Configuration
**Operating system:** Windows 10 Pro 1909 Build 10.0.18363.657

**Version of Telegram Desktop:** 1.9.7 (latest in Microsoft Store) and 1.9.14 (downloaded as installer)

**Used theme**: default / tinted

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/6196

**Comment by halliba** [comment]
sry, chose the wrong words when searching for the issue. So ignore me :)
