### ISSUE TITLE
[Feature Request] Channel managers should be able to delete channel history

### ISSUE THREAD

**Issue by lemmy04** [telegramdesktop/tdesktop#7366]
### Describe the solution you'd like
I would like to be able to completely clear the history of a channel, instead of having to select all messages one by one and then delete - I use a telegram channel for system notifications from my systems monitoring.

### Describe alternatives you've considered
Alternative: a "select all" button that appears as soon as you start selecting messages would already be a big improvement.

**Comment by Aokromes** [comment]
i think this belongs to telegram api.

**Comment by lemmy04** [comment]
where would I post that request?

**Comment by RememberTheAir** [comment]
@lemmy04 you can suggest that to Telegram's Twitter account. Also even a "select all" button wouldn't be the proper solution. The client would have to fetch the whole channel history, possibly thousands or even millions of messages, to select and delete everything - and also the "delete this bunch of messages" request to the API would take some time. Usually deleting something should always be something fast that takes no time, so the correct way of doing it is a "clean history" option that would tell the server to wipe the history of the channel out (which needs api support)
