### ISSUE TITLE
After the last update telegramm will not start anymore on CentOS7

### ISSUE THREAD

**Issue by tuxmaster5000** [telegramdesktop/tdesktop#7369]
It looks the the glibc was changed :(

~/Telegram/Telegram 
/home/XX/Telegram/Updater: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /home/XX/Telegram/Updater)
ldd ~/Telegram/Updater 

/home/XX/Telegram/Updater: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /home/XX/Telegram/Updater)
	linux-vdso.so.1 =>  (0x00007ffc8e9b8000)
	libc.so.6 => /lib64/libc.so.6 (0x00007f37dbf68000)
	libstdc++.so.6 => /lib64/libstdc++.so.6 (0x00007f37dbc61000)
	libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007f37dba4b000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f37dc336000)
	libm.so.6 => /lib64/libm.so.6 (0x00007f37db749000)

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/7330 ?

**Comment by tuxmaster5000** [comment]
No, because in my case it don't crash.
Telegram calls the Updater, but the Updater can't executed, because it was linked using glibc version 3.4.20. And this is ABI incompatible to the one  which comes with CentOS7.

> strings /lib64/libstdc++.so.6 |grep GLIBCXX
> GLIBCXX_3.4
> GLIBCXX_3.4.1
> GLIBCXX_3.4.2
> GLIBCXX_3.4.3
> GLIBCXX_3.4.4
> GLIBCXX_3.4.5
> GLIBCXX_3.4.6
> GLIBCXX_3.4.7
> GLIBCXX_3.4.8
> GLIBCXX_3.4.9
> GLIBCXX_3.4.10
> GLIBCXX_3.4.11
> GLIBCXX_3.4.12
> GLIBCXX_3.4.13
> GLIBCXX_3.4.14
> GLIBCXX_3.4.15
> GLIBCXX_3.4.16
> GLIBCXX_3.4.17
> GLIBCXX_3.4.18
> GLIBCXX_3.4.19
So the binary can only linked against glibc up to 3.4.19.

**Comment by john-preston** [comment]
@tuxmaster5000 libstdc++ should be linked statically in Updater :/ I fixed this twice already, I can't believe it still doesn't work.

**Comment by john-preston** [comment]
@tuxmaster5000 Ah, the second fix was after the 1.9.9 version. You'll have to install the latest version from site, it should autoupdate fine after that.

**Comment by tuxmaster5000** [comment]
Yes, update it manual one time will fix it.
Thanks
