### ISSUE TITLE
Telegram freezes when playing an audio message when played x2 speed

### ISSUE THREAD

**Issue by lalejand** [telegramdesktop/tdesktop#7371]
### Steps to reproduce
1. clic on play button of an audio message
2. click on x2 speed

Now every audio message I try to listen to is in x2 mode, so Telegram freezes every time.

### Expected behaviour
Audio plays at x2 speed

### Actual behaviour
Telegram freezes. I have to kill the process

### Configuration
Ubuntu 19.10

Telegram 1.9.9 tainted theme, night mode

<details><summary><b>Logs</b>:</summary>
lalejand@Gedeon:~$ telegram-desktop 
Gtk-Message: 14:14:21.533: Failed to load module "canberra-gtk-module"
Gtk-Message: 14:14:21.534: Failed to load module "canberra-gtk-module"
Qt: Session management error: None of the authentication protocols specified are supported
libGL error: MESA-LOADER: failed to retrieve device information
libGL error: Version 4 or later of flush extension not found
libGL error: failed to load driver: i915
propsReply "An AppArmor policy prevents this sender from sending this message to this recipient; type=\"method_call\", sender=\":1.4335\" (uid=1000 pid=26982 comm=\"telegram-desktop \" label=\"snap.telegram-desktop.telegram-desktop (enforce)\") interface=\"org.freedesktop.DBus.Properties\" member=\"GetAll\" error name=\"(unset)\" requested_reply=\"0\" destination=\"org.freedesktop.NetworkManager\" (uid=0 pid=1292 comm=\"/usr/sbin/NetworkManager --no-daemon \" label=\"unconfined\")"
nmReply "An AppArmor policy prevents this sender from sending this message to this recipient; type=\"method_call\", sender=\":1.4335\" (uid=1000 pid=26982 comm=\"telegram-desktop \" label=\"snap.telegram-desktop.telegram-desktop (enforce)\") interface=\"org.freedesktop.NetworkManager\" member=\"GetDevices\" error name=\"(unset)\" requested_reply=\"0\" destination=\"org.freedesktop.NetworkManager\" (uid=0 pid=1292 comm=\"/usr/sbin/NetworkManager --no-daemon \" label=\"unconfined\")"
"Object path cannot be empty"

[ogg @ 0x7fb2880211c0] 727 bytes of comment header remain

</details>

The last line "[ogg ..." shows when I click on the audio message.

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/7333

**Comment by lalejand** [comment]
It still freezes with version 1.9.19.
In fact is I starts freezing when I click on something related to audio in telegram (x2 button, play button, audio signal, ...) after click on playing voice message.

**Comment by ilya-fedin** [comment]
snap? :)

**Comment by lalejand** [comment]
Yes, installed with snap.

**Comment by ilya-fedin** [comment]
Well, this is the case

**Comment by lalejand** [comment]
version 1.9.19 installed by other mean would work better than version 1.9.19 installed by snap?

**Comment by ilya-fedin** [comment]
Static binary and flatpak version shouldn't have this issue. Ubuntu package should.

**Comment by lalejand** [comment]
You are right :)

**Comment by ilya-fedin** [comment]
You can return to snap when #7376 will be accepted and built on the edge channel
