### ISSUE TITLE
[BUG] Sharing (not forwarding) to a chat resets its unread counter

### ISSUE THREAD

**Issue by enchained** [telegramdesktop/tdesktop#7372]
### Steps to reproduce
1. Have a chat with an unread counter or ask someone to send something to a chat you have in common.
2. Do not open this chat or read messages.
3. Share a post from any channel via arrow to that chat (not forward).

### Expected behaviour
Unread counter should stay the same as before the share, and reading position should stay on the first unread item.

### Actual behaviour
Unread counter resets itself even if you didn't open the chat and had a lot of unread messages. Your reading position is at the bottom and you have to scroll up to see what you've missed.

I was really excited about the recent counters fix and loving how I can read all the channels at my own pace now (@john-preston thank you! I am really grateful for the reading-while-scrolling implementation). 
What makes it a bit less exciting is that if I want to share something to my friends, I have to read all the messages first, or the counter will reset itself. This bug is global as far as I can say, iOS resets the counter all the same on sharing, sadly. I don't know if this is automatically done on the backend, but if not, it would be really nice if Telegram Desktop could prevent that counter-resetting "read" action on sharing.

### Configuration
**Operating system:**
Windows 10
**Version of Telegram Desktop:**
1.9.19 beta

**Comment by Aokromes** [comment]
it's the same on android.

**Comment by RememberTheAir** [comment]
> I don't know if this is automatically done on the backend

Yes, I think this is enforced by how the api works. As far as I remember, posting something in a chat (thus, forwarding too) makes the server reset the unread counter. I'm not 100% sure btw
