### ISSUE TITLE
Bug with opening context menu in KDE system tray

### ISSUE THREAD

**Issue by dadyarri** [telegramdesktop/tdesktop#7373]
### Steps to reproduce
1. Right click in KDE's system tray on Telegram's icon

### Expected behaviour
Opening context menu

### Actual behaviour
Nothing happened.

### Configuration
**Operating system:**
Manjaro Linux 
Version KDE Plasma: 5.17.5
Version KDE Frameworks: 5.66.0
Version Qt: 5.14.1
Kernel: 5.4.23-1-MANJARO
Architecture: x64

**Version of Telegram Desktop:**
1.9.14
**Used theme**:
Pixel Blue (https://t.me/addtheme/pixelblue)

**Additional:**
Bug reproduce only if English language selected. In Russian for example it works right.

**Comment by ilya-fedin** [comment]
I think this is a race condition on autostart rather than a language issue. It should be fixed by #7354
