### ISSUE TITLE
[Question] Task bar app name

### ISSUE THREAD

**Issue by Neurotoxin001** [telegramdesktop/tdesktop#7380]
Why the name in task bar now "Telegram - Telegram Desktop" on 1.9.20? Before 1.9.20 it's been just "Telegram".

![image](https://user-images.githubusercontent.com/39812401/76684396-d6f94800-661c-11ea-96fc-1ff364416e75.png)

![image](https://user-images.githubusercontent.com/39812401/76684449-36575800-661d-11ea-9d2c-76ffed16f678.png)

**Comment by Aokromes** [comment]
i think because this https://github.com/telegramdesktop/tdesktop/pull/7368

**Comment by Neurotoxin001** [comment]
Can it be returned to just "Telegram" in task bar?

**Comment by ilya-fedin** [comment]
According to https://doc.qt.io/qt-5/qwidget.html#windowTitle-prop - no :(

**Comment by john-preston** [comment]
@ilya-fedin Well, it can. You just don't set this name on Windows and maybe on macOS :)

**Comment by Neurotoxin001** [comment]
What about just "Telegram Desktop" without "Telegram - "?

**Comment by ilya-fedin** [comment]
> You just don't set this name on Windows and maybe on macOS :)

This stupid `- Telegram Desktop` is displayed on linux too :(

**Comment by perk11** [comment]
Maybe it could be shortened to just "Telegram" and then the first "Telegram" could be removed? So it's only the number of messages "(1) - Telegram" when there are messages and then just "Telegram" when there are no messages?
