### ISSUE TITLE
Keyboard layout not respected

### ISSUE THREAD

**Issue by tavurth** [telegramdesktop/tdesktop#7381]
Hi guys, I love telegram, thank you all for such an amazing and inspiring service.

### Steps to reproduce
1. OSX: Set your keyboard layout to [Colemak](https://colemak.com/)
2. Try to use a keyboard shortcut (CMD+k link) (CMD+i italics)
3. Keyboard shortcuts rely on QWERTY behaviour instead of QWFP

### Expected behaviour
Keyboard shortcuts should respect system language instead of purely the key-code

### Actual behaviour
Keyboard shortcuts were interpreted via key-code, which caused misalignment from the character pressed.

### Configuration
**Operating system:**
OSX
**Version of Telegram Desktop:**
<img width="315" alt="Screenshot 2020-03-14 at 23 34 38" src="https://user-images.githubusercontent.com/100964/76687478-61a56b80-664c-11ea-90e1-7234dcb95836.png">
**Used theme**:
Dark theme

**Comment by Aokromes** [comment]
you are using native macos application, not telegram desktop.

**Comment by tavurth** [comment]
Thank you! 

Searching for "github telegram mac osx application" brings me directly here, any idea how I can refine my query?

**Comment by Aokromes** [comment]
https://github.com/overtake/TelegramSwift/issues

**Comment by tavurth** [comment]
Thank you!
