### ISSUE TITLE
Application name is too long now "Telegram - Telegram Desktop"

### ISSUE THREAD

**Issue by perk11** [telegramdesktop/tdesktop#7385]
### Steps to reproduce
1. Start Telegram  Desktop when using KDE with task bar enabled

### Expected behaviour
Application name in the taskbar is not too long.

### Actual behaviour
Application name is "Telegram - Telegram Desktop". This doesn't fit in the taskbar and there is no good reason for that.
![image](https://user-images.githubusercontent.com/1924829/76695274-612dc480-668e-11ea-9c39-cce25321dace.png)
![image](https://user-images.githubusercontent.com/1924829/76695276-6559e200-668e-11ea-81e3-0335c5db67ec.png)

Looks like this was introduced in this commit 
https://github.com/telegramdesktop/tdesktop/commit/fda8a38bfc16aecd8721b5e560ef60c8447b157b

### Configuration
**Operating system:**
KDE Neon LTS 18.04
**Version of Telegram Desktop:**
1.9.20 beta

**Comment by jeffythedragonslayer** [comment]
On Manjaro (with xfce) it appears as simply "Telegram" followed by the number of unread messages in parenthesis.

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/7380
