### ISSUE TITLE
Can't link/tag people that exist in group

### ISSUE THREAD

**Issue by asadaiev** [telegramdesktop/tdesktop#7388]
**Short description:**
Some time ago, I found that can't connect some friends inside our group and every time this list is different. Possibility to tag become after some messages from them or smth like this

**Version:**
Telegram Desktop 1.9.14

**Steps to reproduce:**
1. Open telegram desktop
2. Open already created group with people added
3. Try to tag someone by @ 

**Actual result:**
List of people not full and adding after some messages from this people during the day

**Expected result:**
Should be available to tag anyone like in mobile version

**Comment by Aokromes** [comment]
update to 1.9.20 beta.
