### ISSUE TITLE
telegram-desktop app window not able to open on Sway / Wayland

### ISSUE THREAD

**Issue by salkin-mada** [telegramdesktop/tdesktop#7389]
### Steps to reproduce
1. `apt install telegram-desktop`
2. `apt update && apt upgrade`
3. run `telegram-desktop` from terminal

throws ->
```
Using Wayland-EGL
Using the 'ivi-shell' shell integration
Could not create a shell surface object.
```

### Expected behaviour
A window container with 'telegram-desktop' should open

### Actual behaviour
'telegram-desktop' process is running and i do get a task bar entry (small telegram logo) which shows amount of unread messages. But no window/GUI.

### Configuration
**Operating system:** Debian 10, SwayWm v1.4, qt v5.11.3
**Version of Telegram Desktop:** 1.5.11-1

**Comment by Aokromes** [comment]
1.5.11? that's extremely outdated. telegram desktop beta is now 1.9.20

**Comment by ilya-fedin** [comment]
> ### Steps to reproduce
> 
>     1. `apt install telegram-desktop`
> 
>     2. `apt update && apt upgrade`
> 
>     3. run `telegram-desktop` from terminal
> 
> 
> throws ->
> 
> ```
> Using Wayland-EGL
> Using the 'ivi-shell' shell integration
> Could not create a shell surface object.
> ```
> 
> ### Expected behaviour
> 
> A window container with 'telegram-desktop' should open
> ### Actual behaviour
> 
> 'telegram-desktop' process is running and i do get a task bar entry (small telegram logo) which shows amount of unread messages. But no window/GUI.
> ### Configuration
> 
> **Operating system:** Debian 10, SwayWm v1.4, qt v5.11.3
> **Version of Telegram Desktop:** 1.5.11-1

Seems to be a problem with debian's qt

**Comment by salkin-mada** [comment]
Yeah it is no telegram-dekstop issue. Something with my setup seems to have been broken.
