### ISSUE TITLE
🐞: "Attach file" opens Qt window not the default dialog-box

### ISSUE THREAD

**Issue by joe733** [telegramdesktop/tdesktop#7390]
### Steps to reproduce
1. Open Telegram Desktop
2. Select a conversation
3. Try to attach a file by clicking on 📎.
4. See the error

### Expected behaviour
The default (system designed) `attach-file` dialog box should appear.

### Actual behaviour
Qt dialog box appears.

### Configuration
**Operating system:**
OS: elementary OS 5.1 Hera
DE: Pantheon
CPU: Intel i5 2nd Gen
GPU: NVIDIA GeForce GT 525M
Mem: 12GB

> I'm not using any (neither GTK+ nor icon) themes.

**Version of Telegram Desktop:**
1.9.20 Beta

**Used theme**:
Night

**Screenshots**
The dialog box to attach files.
![Screenshot from 2020-03-16 07-02-32](https://user-images.githubusercontent.com/38415384/76716284-af59cb00-6755-11ea-9998-fa86686b3ae4.png)

The default dialog box (from Firefox) used to appear in telegram.
![Screenshot from 2020-03-16 07-01-54](https://user-images.githubusercontent.com/38415384/76716368-019aec00-6756-11ea-8a4c-acc98014e4d9.png)

---

> Seems similar to #3187... but that was 2017.

**Comment by ilya-fedin** [comment]
> GTK+ dialog box (please correct me if it is not called so) appears.

Qt dialog box

> The default dialog box (from Firefox) used to appear in telegram.

That's GTK+ dialog box

**Comment by joe733** [comment]
> > GTK+ dialog box (please correct me if it is not called so) appears.
> 
> Qt dialog box
> 
> > The default dialog box (from Firefox) used to appear in telegram.
> 
> That's GTK+ dialog box

Thanks, I corrected them.

**Comment by joe733** [comment]
Issue **not** seen in **v1.9.21 Beta**.
