### ISSUE TITLE
No thumbnail after copy-paster video link

### ISSUE THREAD

**Issue by guillaumecardon** [telegramdesktop/tdesktop#7392]
Hello,
Since some days (last update ?), when i copy paste a video link (mp4, webm or similar), thumbnail is not generated and video couldn't be played directly by my interlocutor..
(He need to download the file and open it with a videoplayer third party).
### Steps to reproduce
1. Go on 9gag.com
2. Find an animated post
3. Copy paste the source link in a Telegram conversation

### Expected behaviour
Thumbnail is generated by Telegram and is visible by interlocutor in the conversation, a click on the thumbnail launch the video

### Actual behaviour
No thumbnail (or a big black square).
A click on the link launch an external app (like VLC)

### Configuration
Windows 10 1903

Telegram 1.9.14

**Comment by Aokromes** [comment]
> Hello,
> Since some days (last update ?), when i copy paste a video link (mp4, webm or similar), thumbnail is not generated and video couldn't be played directly by my interlocutor..
> (He need to download the file and open it with a videoplayer third party).
> 
> ### Steps to reproduce
> 1. Go on 9gag.com
> 2. Find an animated post
> 3. Copy paste the source link in a Telegram conversation
> 
> ### Expected behaviour
> Thumbnail is generated by Telegram and is visible by interlocutor in the conversation, a click on the thumbnail launch the video
> 
> ### Actual behaviour
> No thumbnail (or a big black square).
> A click on the link launch an external app (like VLC)
> 
> ### Configuration
> Windows 10 1903
> 
> Telegram 1.9.14

update to at least 1.9.20 beta plz.

**Comment by guillaumecardon** [comment]
1.9.20 : Issue still here

![image](https://user-images.githubusercontent.com/47170797/76766153-d802b480-6797-11ea-9f85-5ad431220ffc.png)

**Comment by ilya-fedin** [comment]
https://github.com/telegramdesktop/tdesktop/issues/7309
