### ISSUE TITLE
Video download progress has gone

### ISSUE THREAD

**Issue by RememberTheAir** [telegramdesktop/tdesktop#7393]
### Steps to reproduce
1. start to download a video
2. look at the video size and progress circle

### Expected behaviour
tdesktop shows the download progress in the from of "downloaded bytes/total bytes", like it used to do

### Actual behaviour
There's only the progress circle telling us whether the download is advancing or not. I don't remember when this changed, but the app used to show also the progress in terms of downloaded data

### Configuration
**Operating system:** Windows 10

**Version of Telegram Desktop:** 1.9.20

**Comment by RememberTheAir** [comment]
Additional note: this also makes it hard to understand which video is currently being downloaded when there's a queue of them

**Comment by jeffythedragonslayer** [comment]
I'm seeing the total size only when downloading, but for me some videos thumbnails are not giving any visual feedback on the fact that they're being downloaded at all.

<img width="309" alt="video_download_total_size_only" src="https://user-images.githubusercontent.com/13253146/76802785-cf69a880-67ae-11ea-83d1-57e165f76d33.png">

**Comment by RememberTheAir** [comment]
Additional note, some time during this year the mobile apps added the size progress even for videos and large GIFs

**Comment by RememberTheAir** [comment]
Still valid

**Comment by RememberTheAir** [comment]
I guess it's still relevant

**Comment by blackjyn** [comment]
still valid

**Comment by RememberTheAir** [comment]
fixed

**Comment by Aokromes** [comment]
and this is why slate bot is needed (well it ignores enhancements, but sometimes devs forgets to close issues on fix) :)
