### ISSUE TITLE
My old phone number was reassigned and I can now see the new user's Telegram account

### ISSUE THREAD

**Issue by notsag-dev** [telegramdesktop/tdesktop#7395]
My old number was reassigned due to inactivity. I was still logged into my Telegram account from the desktop client and continued using it. Occasionally my name changed and I was logged into somebody else's account and vice-versa :D.

### Configuration
Telegram desktop for MacOS 4.5.141717 Stable
Operating System: MacOS High Sierra

**Comment by Giando** [comment]
This is not a Telegram problem.
It is a problem of the user.

To avoid it just go, in advance, in Settings -> Privacy and Security -> **2-step verification**, and enable it.
In the same path, there is also the **Active sessions** section which may be useful for "throwing out" the new "illegitimate user".

You can kindly close this issue.

Sincerely.

**Comment by notsag-dev** [comment]
Thank you for your answer, Giando!

What do you mean a problem of the user? In this case I am myself the "illegitimate user" as my old phone number is that person's number now 😄 . Don't you think that I should have been automatically logged out when the number was reassigned?

**Comment by Aokromes** [comment]
> Thank you for your answer, Giando!
> 
> What do you mean a problem of the user? In this case I am myself the "illegitimate user" as my old phone number is that person's number now 😄 . Don't you think that I should have been automatically logged out when the number was reassigned?

telegram cannot know phone number was reasinged.

**Comment by Giando** [comment]
> Thank you for your answer, Giando!
> 
> What do you mean a problem of the user? In this case I am myself the "illegitimate user" as my old phone number is that person's number now  . Don't you think that I should have been automatically logged out when the number was reassigned?

I literally mean it's your problem if you didn't replace your number before it was reassigned. :joy: 

But you're still in time to do it from:

Settings -> Edit profile -> Phone number -> **Change phone number**

![Istantanea_2020-03-17_03-14-53](https://user-images.githubusercontent.com/8095242/76815806-e801af00-67fe-11ea-805f-1b6bc836f668.png)

Sincerely. :wink:

**Comment by notsag-dev** [comment]
Thank you again for your help. I'm now using another phone number and I'm reporting this bug not because I want to keep my old account but because this is a security breach. It may be a different case but Whatsapp did kick me out of my account under the same circumstances which is the expected behavior.

Anyways, it was just for letting you know. Have a great day and thank you for your time.
