### ISSUE TITLE
Issue when installing Telegram desktop

### ISSUE THREAD

**Issue by emankhalaf** [telegramdesktop/tdesktop#7396]
Hi,
I am experiencing issue when installing Telegram Desktop to my laptop since I need to synchronize with my phone app. I have attached a screenshot for the pop-up alert message.
Thanks 
-->
### Steps to reproduce
1. 
2. 
3. 

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

### Configuration
**Operating system:**

**Version of Telegram Desktop:**

**Used theme**:

<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by jeffythedragonslayer** [comment]
How did you try to attach the screenshot?  I don't see it...

**Comment by emankhalaf** [comment]
![telegram-issue](https://user-images.githubusercontent.com/26454871/76837961-1baefa00-683c-11ea-8ad5-cff9b6222a11.jpg)
I have attached it here!

**Comment by Aokromes** [comment]
it looks you have very strict permisions to your appdata directory

**Comment by emankhalaf** [comment]
Any recommendations, please. I found this page link below:
https://www.windowscentral.com/how-enable-windows-10-sideload-apps-outside-store
Is that what needed? I am also keen not to harm my machine.
Thanks

**Comment by jeffythedragonslayer** [comment]
I don't know much about those controls, I always keep developer mode enabled. You could try fiddling with the permissions of the Telegram directory inside of Roaming if you don't want to make the AppData dir too open.

What if you try installing Telegram through the Microsoft Store?  Do you getthe same error?

**Comment by emankhalaf** [comment]
Excellent! I downloaded it from Microsoft store successfully.
Thanks so much
