### ISSUE TITLE
Let's add tabs to divide "Personal Messages", "Groups" & "Channels"

### ISSUE THREAD

**Issue by Estahbanati** [telegramdesktop/tdesktop#7397]
Channels and Groups have more frequent posts than Individuals, while Individuals usually are sending you private messages that you most likely need to see and respond quickly. But personal messages go down the list pretty fast and there is no filter to visually highlight them.

I recommend using the simple but successful method of dividing messages into 3 tabs: "Individuals/Personals", "Groups/Super Groups" and "Channels" above or under the list box. A red circle on the tab would show if there are any new messages waiting to be read under the tab.

**Comment by Aokromes** [comment]
duplicate.

**Comment by jeffythedragonslayer** [comment]
#1107?
