### ISSUE TITLE
Dark icon in system tray on Breeze Dark theme in KDE Plasma

### ISSUE THREAD

**Issue by Inlifeuser** [telegramdesktop/tdesktop#7399]
### Steps to reproduce
1. Open Telegram Desktop

### Expected behaviour
The icon should be light in the system tray

### Actual behaviour
A dark icon appears in the system tray

### Configuration
**Operating system:** Arch Linux (x86_64, recently updated) + KDE Plasma 5.18.3

**Version of Telegram Desktop:** 1.9.21 (Linux 64-bit binary from GitHub, installed in home directory)

**Used theme**: Day

**Screenshots**:
On Breeze Dark theme
![2020-03-17 12-26-29](https://user-images.githubusercontent.com/25416459/76847187-b7e3fb80-6852-11ea-911d-d360ba0f5177.png)

On Breeze Light theme (everything is fine here)
![2020-03-17 12-50-29](https://user-images.githubusercontent.com/25416459/76847364-fed1f100-6852-11ea-898d-937c57a930fe.png)

**Comment by ilya-fedin** [comment]
Please, report icon pack bugs to icon pack, not to tdesktop
https://github.com/KDE/breeze-icons

**Comment by jmayday** [comment]
@Inlifeuser I've reported it: https://bugs.kde.org/show_bug.cgi?id=418996

**Comment by Azarilh** [comment]
You can personally solve this by substituting the dark icons with the light ones.

sudo cp /usr/share/icons/breeze-dark/status/22/telegram* /usr/share/icons/breeze/status/22
sudo cp /usr/share/icons/breeze-dark/status/24/telegram* /usr/share/icons/breeze/status/24/

**Comment by danito8905** [comment]
the fix commit was remove the breeze-icons for telegram. 
So if you dont want wait the update then remove/rename this files and the original telegram icon will back.
![image](https://user-images.githubusercontent.com/29113406/80339439-0367cd00-8835-11ea-9e58-e8721ce3ec44.png)

/usr/share/icons/breeze/status/22/telegram-panel.svg
/usr/share/icons/breeze/status/22/telegram-attention-panel.svg
/usr/share/icons/breeze/status/22/telegram-mute-panel.svg

/usr/share/icons/breeze/status/24/telegram-panel.svg
/usr/share/icons/breeze/status/24/telegram-attention-panel.svg
/usr/share/icons/breeze/status/24/telegram-mute-panel.svg

https://github.com/KDE/breeze-icons/commit/309ea93012f3fe990625419bcca9c11915ebc8ad
