### ISSUE TITLE
[Feature request] Start app with password

### ISSUE THREAD

**Issue by christianromeni** [telegramdesktop/tdesktop#74]
Is it possible to add a password request when the app is launched...
I'm using the messenger at work... But I dont want my colleges to be able to just open the app. And loging out/in each time.. Is realy anoying.. :)

Greets - Chris

**Comment by ppparadox** [comment]
+1

**Comment by aleksey-khokhryakov** [comment]
+1
Password request after application lock.
App is locked on startup and after system lock

**Comment by fyahfox** [comment]
+1 for the password request feature

Also I would like to be able to configure telegram to logout automatically when closed.

**Comment by wiwwo** [comment]
Functionality done in mobile (android) version... 
When on Desktop? :-)

**Comment by wiwwo** [comment]
:+1:

**Comment by amitmahbubani** [comment]
+1 for this

**Comment by jamesburke-examtime** [comment]
Yay for the addition of a passcode :)

**Comment by joshery420** [comment]
Yep, @christianromeni should probably mark this as closed when he gets the chance. :)

**Comment by christianromeni** [comment]
YES! Finally!! Thanks! :))
