### ISSUE TITLE
"fontconfig" folder being kept created at home folder in Linux

### ISSUE THREAD

**Issue by TechnoSparks** [telegramdesktop/tdesktop#740]
I am using Linux Mint 17.1 32 bit system with Cinnamon as desktop.

Telegram desktop seemed to create a folder "fontconfig" in Home directory in Linux. The files are exactly the same as in /path-to-telegram-binary/fontconfig
If you delete the folder, it will be recreated (along with the contents) when Telegram launches again.

Considering that the files are the same, I consider this as a bug.

**Comment by completit** [comment]
Everyone running Linux has a [fontconfig](http://packages.ubuntu.com/search?keywords=fontconfig) file, it's generated by the system (generic font configuration library), so it's nothing to be scared of. :)

**Comment by TechnoSparks** [comment]
I have been using Linux for 4 years now. I have never seen such of a folder. The folder will creates itself right after the time telegram's process starts. I can do a screen record for proof, though.

**Comment by ShabbyX** [comment]
It's `.fontconfig` with a dot in the beginning that is normal. Telegram should actually be using that directory, rather than `fontconfig`.

**Comment by ppparadox** [comment]
Duplicate of #495
