### ISSUE TITLE
Unable to autocomplete user tags in multi-user chats

### ISSUE THREAD

**Issue by atk91** [telegramdesktop/tdesktop#7400]
### Steps to reproduce
1. Go to any multi-user chat
2. type @

### Expected behaviour
You should see a popup with chat members

### Actual behaviour
Popup shows just one user, the one who sent last message in chat

### Configuration
Arch Linux
Telegram Desktop version 1.9.14-3

**Used theme**:
Tinted

**Comment by xvitaly** [comment]
Fixed in 1.9.21.
