### ISSUE TITLE
persian font issue

### ISSUE THREAD

**Issue by jkmpariab** [telegramdesktop/tdesktop#7401]
### Steps to reproduce
read/write persian texts

### Expected behaviour
persian font should looks fine or just as it should be (just as version before)

### Actual behaviour
the new update (1.9.21) persian font is changed into a malformed look

### Configuration
**Operating system:**
Ubuntu 18.04 (Lubuntu desktop)

**Version of Telegram Desktop:**
1.9.21

**Used theme**:
Tinted

<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by jeffythedragonslayer** [comment]
Duplicate of #7312?

**Comment by Aokromes** [comment]
and more

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/5172
