### ISSUE TITLE
Telegram restored on current virtual desktop only by sequence "Minimize to tray", "Open telegram" in XFCE

### ISSUE THREAD

**Issue by Hubbitus** [telegramdesktop/tdesktop#7402]
### Steps to reproduce
1. Run telegram
2. Switch to another virtual desktop
3. Click on the tray icon or select "Open telegram" context menu item (from right-click by icon)

### Expected behavior
Telegram window appeared on the current desktop

### Actual behavior
1. Left click on tray icon is fully ignored
2. By right-click on the tray icon appeared menu, but click on the item "Open telegram" do nothing

### Configuration
**Operating system:** Fedora Linux 32 (on 31 all the same)

**Version of Telegram Desktop:**
1.9.21

**Used theme**:
Default

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/6129#issuecomment-638741697

**Comment by ilya-fedin** [comment]
> this issue is still valid?

Yes, because no one implemented this feature request and most likely it is not implementable (I can't find any API in Qt to get/set virtual desktop)

**Comment by Aokromes** [comment]
so, 3rd party issue?

**Comment by ilya-fedin** [comment]
> so, 3rd party issue?

non-issue IMHO, that item shouldn't move window to another virtual desktop, just open&focus
