### ISSUE TITLE
Display Farsi (Persian) fonts with wrong font-family

### ISSUE THREAD

**Issue by mostafaznv** [telegramdesktop/tdesktop#7404]
### Steps to reproduce
1. Update telegram to 1.9.21
2. Send/Receive a farsi (persian) text message

### Expected behaviour
displaying text messages with arial/tahoma/times (or a known font-family that supports farsi)

### Actual behaviour
displaying text messages like code blocks.

### Configuration
**Operating system:** Ubuntu 18.04.4

**Version of Telegram Desktop:** 1.9.21

**Used theme**: Default (Classic - Light)

<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

______________

in latest version of telegram, my farsi (persian) mesasges are displaying with a wrong font family.
it's annoying to read text messages.

screenshot:
https://pasteboard.co/IZw9STR.png

**Comment by Aokromes** [comment]
duplicate.
