### ISSUE TITLE
English strings in foreign localization

### ISSUE THREAD

**Issue by winqooq** [telegramdesktop/tdesktop#7406]
### Steps to reproduce
1. Set a language other than English
2. open settings → advanced settings → scroll down or open the context menu when entering text
### Expected behaviour
I see lines in my chosen language and the number of unread messages

### Actual behaviour
I see lines in English and do not see the number of unread messages

### Configuration
Windows 7 x64 Ultimate (Assembly 7601)
Telegram Desktop 1.9.21
Built in. Classic

<details><summary><b>Screenshots</b>:</summary>

![2](https://user-images.githubusercontent.com/55299850/76888051-e4683980-688b-11ea-8348-932e530e263e.png)

![1](https://user-images.githubusercontent.com/55299850/76888040-dfa38580-688b-11ea-8038-9945fad5a5a4.png)

![3](https://user-images.githubusercontent.com/55299850/76891375-8dfdf980-6891-11ea-8d7a-6ef99cf575e7.png)

</details>
Used localization: https://t.me/setlanguage/ru

**Comment by Aokromes** [comment]
i don't think this belongs here.

**Comment by jeffythedragonslayer** [comment]
I think it depends on whether those strings are hardcoded into the desktop app source or whether they're just missing from the localization.  The android app is telling me that the Russian pack is 100% complete though which clearly is not the case.

**Comment by ilya-fedin** [comment]
https://translations.telegram.org/ru/tdesktop/unsorted/

**Comment by winqooq** [comment]
1. this problem has just gone (or noticed just now)
2. as I understand it, it was connected with cloud localization and not with the client, right?

**Comment by Aokromes** [comment]
yup, this night where translated https://translations.telegram.org/ru/tdesktop/recent/translations
