### ISSUE TITLE
Bad Farsi Font in version 1.9.21

### ISSUE THREAD

**Issue by rezafarokhi** [telegramdesktop/tdesktop#7407]
### Expected behaviour
Use right font in Farsi

### Actual behaviour
After my telegram got an update to version 1.9.21 on Linux, My Farsi font has changed to another font that is really hard to read because it's really small font and it's not as bold as previous font.
Screenshot:
[https://ibb.co/DLHHdsd](url)

### Configuration
**Operating system:**
Ubuntu 19.10 x64
**Version of Telegram Desktop:**
1.9.21 Desktop
**Used theme**:
Classic
<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/5172
