### ISSUE TITLE
Telegram's systray icon

### ISSUE THREAD

**Issue by Chamrosh** [telegramdesktop/tdesktop#7409]
telegram 1.9.14
run telegram with : Exec=env TDESKTOP_DISABLE_TRAY_COUNTER=1 telegram-desktop -- %u
![b0r2_screenshot_20200308_235133](https://user-images.githubusercontent.com/10561726/76918148-d8f02f00-68da-11ea-987a-9eb38614e872.png)

telegram 1.9.21
used telegram  48px icon for panel!!!!
![Screenshot_20200318_054046](https://user-images.githubusercontent.com/10561726/76918224-0fc64500-68db-11ea-85a5-8637275886d3.png)

desktop: kde 5.18.3

**Comment by ilya-fedin** [comment]
#7192
