### ISSUE TITLE
Tray icon not displaying properly

### ISSUE THREAD

**Issue by completit** [telegramdesktop/tdesktop#741]
![icon-tray](https://cloud.githubusercontent.com/assets/5355219/7766505/77f8202a-0072-11e5-910e-e0c13a34f566.png)
The tray icon is on a white background instead of transparent.

**System information:**
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.2 LTS
Release:	14.04
Codename:	trusty

**Comment by kittee** [comment]
Same for me:
Archlinux
Awesome WM

**Comment by mbnoimi** [comment]
I've similar issue but the icon completely disappear while the process is active (I can hear application's notify for new messages)

- Linux Mint 17.1 xfce x64
- Telegram 0.8.17

**Comment by dejadejoder** [comment]
Same for me:
  * Debian jessie 8.1
  * Telegram v0.8.32

**Comment by completit** [comment]
@mbnoimi that happens to me very often since last update, I can hear notifications but the icon's not there lol, lucky I've assigned "CTR+T" to open Telegram

**Comment by mbnoimi** [comment]
@completit 

> By the way, did you setup a local passcode for it ? Maybe this could cause this issue.

I didn't

**Comment by hobarrera** [comment]
Duplicate of #492, apparently.

**Comment by dejadejoder** [comment]
Problem resolved with 0.8.43

**Comment by mbnoimi** [comment]
@dejadejoder No it doesn't 
![selection_015](https://cloud.githubusercontent.com/assets/284547/9037779/2bcccdc2-39f7-11e5-8d91-bf5d7634a961.png)

Linux Mint 17.1 x64 xfce

**Comment by kittee** [comment]
@mbnoimi are you sure you are using latest dev build?

**Comment by mbnoimi** [comment]
@kittee 
![selection_016](https://cloud.githubusercontent.com/assets/284547/9037848/ed362f44-39f7-11e5-9452-1a96aa4d1ed7.png)

**Comment by kittee** [comment]
@dejadejoder this seems like kinda different problem

**Comment by dejadejoder** [comment]
Maybe, but for me icon is now ok :
![screenshot_2015-08-03_145905](https://cloud.githubusercontent.com/assets/2197555/9037910/353ba038-39f0-11e5-80a2-14db6627b403.png)
(Debian 8+ i3wm 4.10.3)

**Comment by completit** [comment]
**Solved** by version 0.8.45
