### ISSUE TITLE
[Question] 1.9.21 Improved spell checking for Windows 7 and Linux

### ISSUE THREAD

**Issue by flerko** [telegramdesktop/tdesktop#7410]
In the latest update on windows 7, all words are simply underlined in red
Is this how it should work?

![1](https://user-images.githubusercontent.com/22788601/76920147-f3370680-68f4-11ea-9bb1-6dd2aa863b34.png)

**Comment by jeffythedragonslayer** [comment]
No... sounds like the spellcheck dictionary is not being read properly.

**Comment by john-preston** [comment]
@flerko Is the required dictionary downloaded in Settings > Advanced > Manage dictionaries?

**Comment by flerko** [comment]
Seems like dictionary was loaded, but the words are still underlined

![1](https://user-images.githubusercontent.com/22788601/76928671-72840480-690c-11ea-9d04-f2c8c293b37b.png)

**Comment by 23rd** [comment]
Can you try to remove the dictionaries (both) and download them again?
1. `Manage dictionaries > Context menu on the enabled dictionary > Remove Dictionary > Save`.
2.1 Then `Manage dictionaries > Enable the dictionaries you need > Save`.
2.2 Or just restart the application.

**Comment by flerko** [comment]
> Can you try to remove the dictionaries (both) and download them again?
> 
> 1. `Manage dictionaries > Context menu on the enabled dictionary > Remove Dictionary > Save`.
>    2.1 Then `Manage dictionaries > Enable the dictionaries you need > Save`.
>    2.2 Or just restart the application.

Reinstall dictionary and restart the app did not solve the problem :(

**Comment by 23rd** [comment]
Do you have the installed version or are you using the portable version?

**Comment by 32px** [comment]
same problem. all Russian words marked as wrong.
OS: Win 7 x64
![image](https://user-images.githubusercontent.com/62335919/76956620-fc50c380-6946-11ea-8d09-d3a88f487dc4.png)

**Comment by flerko** [comment]
> Do you have the installed version or are you using the portable version?

I have the installed version

![1](https://user-images.githubusercontent.com/22788601/76956679-b7c12a00-693e-11ea-9f89-5d3ca102148f.png)

**Comment by 23rd** [comment]
Thanks for your reports, this should be fixed in the next version.

**Comment by 23rd** [comment]
Well, actually, this issue was fixed a few versions ago.
@flerko Please can you give me a feedback?

**Comment by flerko** [comment]
@23rd Everything works great. Thank you very much!
