### ISSUE TITLE
Unreadable font for Armenian texts

### ISSUE THREAD

**Issue by vanushwashere** [telegramdesktop/tdesktop#7412]
### Steps to reproduce
Just  send or receive message written in Armenian 
![image](https://user-images.githubusercontent.com/24995381/76938284-c93f0d80-690f-11ea-9a99-00b3e9059b12.png)

The font changed after the update to version 1.9.21

### Configuration
**Operating system:** KDE Neon 5.18.3

**Version of Telegram Desktop:** 1.9.21 installed via Snap

**Used theme**: Tinted Blue

**Comment by vanushwashere** [comment]
Russian text for example:
![image](https://user-images.githubusercontent.com/24995381/76938511-23d86980-6910-11ea-8a0c-4ecde7081b33.png)

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/5172 generic bug.
