### ISSUE TITLE
Persian font in telegram-desktop 1.9.21

### ISSUE THREAD

**Issue by edwinans** [telegramdesktop/tdesktop#7413]
### Steps to reproduce
Back to a previous version of telegram-desktop in linux.

### Expected behaviour
Tell us what should happen

### Actual behaviour
I think that Persian font has been changed due to a new update of my telegram-desktop in ubuntu 18.04, and every Persian writer can notice that this font isn't appropriate and nearly unreadable for us(Persian speakers)! 
So please bring it back to the previous version!
I attached both(new and last) fonts of the Persian font.

### Configuration
Ubuntu 18.04
![new_persian_font](https://user-images.githubusercontent.com/30560280/76950732-cd1c6100-690a-11ea-832a-5fb321c859db.jpg)
![last_persian_font](https://user-images.githubusercontent.com/30560280/76950749-d279ab80-690a-11ea-8b40-2074cb41d84f.jpg)

**Version of Telegram Desktop:**
1.9.21
**Used theme**:

<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by Aokromes** [comment]
seriously, you guys cannot search? it's the 5th ticket about this.
