### ISSUE TITLE
[Feature Request] Detect screen resolution/DPI changes on Wayland

### ISSUE THREAD

**Issue by Vantuz** [telegramdesktop/tdesktop#7415]
### Is your feature request related to a problem?
I have laptop with 4k screen and 1080p external display. My laptop is configured so that when display is connected my laptop screen is used as second screen and its resolution is set to 1080p (as there are some apps I use that do not support wayland natively). So, when I connect my external display Telegram interface becomes very small and I have to restart it so that it looks normal again.

### Describe the solution you'd like
Is it possible to redraw interface when screen setup is changed or when multi DPI setup is used and window is moved from low DPI screen to high DPI?

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/6196
