### ISSUE TITLE
Monospace Hebrew Font

### ISSUE THREAD

**Issue by yonathan06** [telegramdesktop/tdesktop#7416]
### Steps to reproduce
1. Open a message in Hebrew 

### Expected behavior
Regular sans-serif font in Hebrew

### Actual behavior
Monospace font in Hebrew (for all text messages and user names)

### Configuration
**Operating system:**
Ubuntu 18.04.4

**Version of Telegram Desktop:**
1.9.21

**Used theme**:
Happens in both regular and dark mode

![Screenshot from 2020-03-18 16-41-29](https://user-images.githubusercontent.com/5816863/76976209-58fab100-693c-11ea-9d0c-7fde95d3922a.png)

**Comment by ilya-fedin** [comment]
snap?

**Comment by ilya-fedin** [comment]
If yes, https://github.com/telegramdesktop/tdesktop/issues/5172#issuecomment-600590891

**Comment by grreeenn** [comment]
It's super annoying. Hebrew instantly became unreadable :( is it possible to revert it in some way? I get most of my news feeds through telegram, and they just got unusable :(((

**Comment by ilya-fedin** [comment]
> is it possible to revert it in some way?

Then, people from #7144 will not be able to use telegram again

**Comment by grreeenn** [comment]
totally understandable, just wanted to know if I can make a local version rollback somehow...

Also, I see that there's only "snap" version affected - what is this, what's the other one and where can I read about it? Maybe I'll get a second one meanwhile... the whole country is in the emergency mode, and reading news in this situation became really important.

**Comment by ilya-fedin** [comment]
> what's the other one and where can I read about it?

you can install org.telegram.desktop from flatpak or download static binary here, from github releases (or from desktop.telegram.org)

**Comment by omertuc** [comment]
The font you're seeing is called FreeMono, it has horrible Hebrew glyphs - a recent change in the way the snap package is made messed up the `/etc/fonts/fonts.conf` so it doesn't include the `/etc/fonts/conf.d` directory anymore (maybe on purpose). This directoryaids in font substitution. 

A quick fix would be to remove this font from your system (should be somewhere in `/usr/share/fonts`). This would make Telegram's fontconfig fallback to a different, more readable font.

**Comment by OrBin** [comment]
> The font you're seeing is called FreeMono, it has horrible Hebrew glyphs - a recent change in the way the snap package is made messed up the `/etc/fonts/fonts.conf` so it doesn't include the `/etc/fonts/conf.d` directory anymore (maybe on purpose). This directory aids in font substitution.
> 
> A quick fix would be to remove this font from your system (should be somewhere in `/usr/share/fonts`). This would make Telegram's fontconfig fallback to a different, more readable font.

Did removing FreeMono fix it for you?
I've deleted the font files, but now I have another unreadable font (see screenshot).

![image](https://user-images.githubusercontent.com/6897234/77588025-aef9c680-6ef1-11ea-8391-1bd7e91b6a1a.png)

**Comment by grreeenn** [comment]
@OrBin your font is readable to the one that I got *puke*

I have another thought: can I rename some readable font files to FreeMono.ttf and place them to the fonts folder? will it work, or the font files are self-aware?

**Comment by OrBin** [comment]
> @OrBin your font is readable to the one that I got (puke)
> ![image](https://user-images.githubusercontent.com/13204857/77688005-05294100-6fa8-11ea-8dfd-43caf446c3e9.png)
> 
> I have another thought: can I rename some readable font files to FreeMono.ttf and place them to the fonts folder? will it work, or the font files are self-aware? Another question is, what was the name of the font that was there before the update?

Oh god.
Anyway, none of the three satisfies me, so I removed Telegram Desktop and installed manually from the website.
I don't think that renaming the fonts will work - I guess they have some metadata... but it's really only a guess.

**Comment by OrBin** [comment]
Updated now to v2.0 and the monospace font is back...

**Comment by grreeenn** [comment]
> Updated now to v2.0 and the monospace font is back...

Snap updated now to v2.0, and the old readable font is back :)
