### ISSUE TITLE
🐞: Impossible to disable tray icon

### ISSUE THREAD

**Issue by bestwebua** [telegramdesktop/tdesktop#7418]
### Steps to reproduce
1. Settings > Advanced > System integration > Show tray icon > Checkbox disabled

### Expected behaviour
Telegram icon will never be displayed in tray.

### Actual behaviour
After some time it's shown again.

### Configuration
**Operating system:** Linux Ubuntu 19.10 64bit, Gnome 3.34.2

**Version of Telegram Desktop:** 1.9.21

**Used theme**: Classic

**Comment by ilya-fedin** [comment]
Where's the log?

**Comment by bestwebua** [comment]
@ilya-fedin Where can i get it?

**Comment by ilya-fedin** [comment]
~/.local/share/TelegramDesktop/log.txt
Grab the log only after you have reproduced the problem.

**Comment by bestwebua** [comment]
I uses snap version (from Ubuntu Snap Store), where I can find log for this version?

**Comment by ilya-fedin** [comment]
~/snap/telegram-desktop/current/.local/share/TelegramDesktop/log.txt

**Comment by bestwebua** [comment]
Log started when tray icon was disabled: [log.txt](https://github.com/telegramdesktop/tdesktop/files/4366309/log.txt)

**Comment by ilya-fedin** [comment]
@bestwebua thank you

**Comment by bestwebua** [comment]
@ilya-fedin Cheers!

**Comment by bestwebua** [comment]
@ilya-fedin, @john-preston nice job!
