### ISSUE TITLE
URL preview for RTL languages is a little buggy

### ISSUE THREAD

**Issue by ahmadalli** [telegramdesktop/tdesktop#742]
take a look at this screenshot:

![image](https://cloud.githubusercontent.com/assets/2167301/7766528/430346ee-007f-11e5-88aa-b6356669ca34.png)

![image](https://cloud.githubusercontent.com/assets/2167301/7766587/dfa0d8cc-007f-11e5-83fb-bca7ca6f25f2.png)

part of the text is inside the picture while it shoudn't!

![image](https://cloud.githubusercontent.com/assets/2167301/7766602/0d322d72-0080-11e5-8143-bbc8edd5d721.png)

**Comment by Aokromes** [comment]
This is fixed on 1.0.16?

**Comment by NabiKAZ** [comment]
I test it on Telegram Desktop version 1.1.2
![image](https://cloud.githubusercontent.com/assets/246721/26516381/be423e64-429a-11e7-9103-9881500298ef.png)
Seems no problem.

**Comment by ahmadalli** [comment]
yeah it seems ok :)
