### ISSUE TITLE
Cannot input Chinese with iBus Cangjie on GNOME 3.36, Linux

### ISSUE THREAD

**Issue by yookoala** [telegramdesktop/tdesktop#7421]
### Steps to reproduce
1. Install Fedora 32 Workstation Beta (I suspect this applies to any [GNOME 3.36](https://help.gnome.org/misc/release-notes/3.36/) based distro)
2. Install ibus-cangjie (or maybe other [CJK](https://en.wikipedia.org/wiki/CJK_characters) [ibus](https://github.com/ibus/ibus) input method?). Restart ibus if needed.
3. Install Telegram Desktop 1.9.21
4. Run Telegram Desktop and login.
5. Open contact and go to the message area.
6. Switch to Chinese (or whatever other input method applicable) then type any of the a-w keys.

### Expected behaviour
There should be regular Chinese character selection and normal ibus interaction.

Example,
![2020-03-20 16-29-44 的螢幕擷圖-cropped](https://user-images.githubusercontent.com/91274/77147490-4ca35f00-6ac8-11ea-9a28-7614f8d52946.png)

### Actual behaviour
The message box intercepted the input and display the English characters directly.

![2020-03-20 16-32-46 的螢幕擷圖](https://user-images.githubusercontent.com/91274/77147549-78bee000-6ac8-11ea-9471-72cbfaa0881b.png)

### Configuration
**Operating system:**
Fedora 32 Workstation (Beta)
GNOME 3.36
IBus 1.5.22

**Version of Telegram Desktop:**
1.9.21

**Used theme**:
Night mode / Dark theme

### Probably Relevant Bugs in the Past
* #573
* #688
* #978
* #2013 
* #6857
* #6769

**Comment by yookoala** [comment]
Just tried to use the UniEmoji input method. Same problem. So this is not CJK specific.

**Comment by yookoala** [comment]
Tried running Telegram like this:
```
QT_IM_MODULE=ibus /<path_to_executable>/Telegram/Telegram
```

This does not fix the issue.

**Comment by Aokromes** [comment]
it's the same #2013

**Comment by yookoala** [comment]
I've written up [a Chinese article about this issue and the fix](https://medium.com/hong-kong-linux-user-group/%E4%BF%AE%E6%AD%A3-telegram-desktop-%E5%8F%8A%E5%85%B6%E4%BB%96-qt-%E8%BB%9F%E4%BB%B6%E5%9C%A8-gnome-wayland-%E4%B8%8B%E7%9A%84-ibus-%E4%B8%AD%E6%96%87%E8%BC%B8%E5%85%A5%E5%95%8F%E9%A1%8C-797abc906c3d). For those who have similar issue, it might help solving your problem.
