### ISSUE TITLE
[Windows] Pasting an image from clipboard shows as an attachment

### ISSUE THREAD

**Issue by kaminskypavel** [telegramdesktop/tdesktop#7422]
### Steps to reproduce
1.  Copy an image
2.  Paste to a chat
3.  the image shows as an attachment instead of an inline image

### Expected behaviour
Tell us what should happen

### Actual behaviour
Pasting image from clipboard shows as an attachment, instead of an image.
this doesnt happen if you paste an image on the anrdoid client and wasnt happening on the previous version of tdesktop. 

### Configuration
**Operating system:**
Win 10

**Version of Telegram Desktop:**
1.9.21

**Used theme**:
Default Dark mode

<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by john-preston** [comment]
@kaminskypavel You can choose if you want to send an image as a file (uncompressed, looking like attachment?) or as a photo (compressed, large in-chat image).

**Comment by NoNameUserDev** [comment]
Wow, such thing is counts as a problem/issue? I wonder if the author has already passed away from such questions. Sorry for my rudeness... but I couldn't stop myself :)

**Comment by kaminskypavel** [comment]
@john-preston I'm aware you can do that, if you drag 'n' drop, not if you're pasting from clipboard.
the scenario is you're grabbing a screenshot and pasting it directly into the team's chat...

@NoNameUserDev - thanks for your feedback, now take a hike...

**Comment by john-preston** [comment]
@kaminskypavel The same with pasting from clipboard.

**Comment by kaminskypavel** [comment]
@john-preston got it! probably I've missed it. thanks for the clarification.
