### ISSUE TITLE
why cache to ~/.local dir instead of ~/.cache (on linux)

### ISSUE THREAD

**Issue by cypa** [telegramdesktop/tdesktop#7423]
### Is your feature request related to a problem?
~λ du -sh .local/share/TelegramDesktop/tdata/user_data/*cache*
6,2M	.local/share/TelegramDesktop/tdata/user_data/cache
47K	.local/share/TelegramDesktop/tdata/user_data/media_cache

while ~/.local is not proper path for cache!!!

### Describe the solution you'd like
move caching dir to ~/.cache/ please

for example, I'm using slow device as root fs so I have to move all caching to tmpfs in RAM, while Telegram hides caches in ~/.local, now Telegram-desktop client freezes for a few seconds every time  I'm typing

**Comment by cypa** [comment]
also found this 
./.local/share/TelegramDesktop/tdata/emoji/cache_24_0

**Comment by ilya-fedin** [comment]
https://github.com/telegramdesktop/tdesktop/issues/107#issuecomment-254517701
