### ISSUE TITLE
Telegram client on Linux hangs often / has high latency spikes when typing in the chat bar 

### ISSUE THREAD

**Issue by asg0451** [telegramdesktop/tdesktop#7425]
### Steps to reproduce
1. Open Telegram client
2. Open a chat group 
3. Type some text

### Expected behaviour
You should be able to type (or do any sort of interaction) without the client frequently hanging

### Actual behaviour
You can't :(
Even when mousing over menus the highlighting of the selected option is laggy.

### Configuration
**Operating system:**
Ubuntu v18.04.4
**Version of Telegram Desktop:**
1.9.12 1
**Used theme**:
Dark?
<details><summary><b>Logs</b>:</summary>
(where can i find the logs?)
</details>

**Comment by Aokromes** [comment]
can you try disabling spell checker temporally if it changes something?

**Comment by asg0451** [comment]
Just did so, no change.
Any more information I can provide?

**Comment by Aokromes** [comment]
ou havw gif panel open?

**Comment by ilya-fedin** [comment]
> 1.9.12

There are 1.9.21

**Comment by asg0451** [comment]
> Latest stable is 1.9.21
That's what I meant, sorry. 

I had the panel set to gif & closed. I tried setting it to emoji and closing it again, no change

**Comment by asg0451** [comment]
got some logs for you (from ~/.local/share/TelegramDesktop)
[tlogs.zip](https://github.com/telegramdesktop/tdesktop/files/4364363/tlogs.zip)

**Comment by ilya-fedin** [comment]
> Just did so, no change.

Even after client restart?

**Comment by asg0451** [comment]
yeah, restarted it after I changed it.

**Comment by Aokromes** [comment]
so, disabling spell checker reduces latency?

**Comment by asg0451** [comment]
Disabling the spell checker and switching the bar from gif to emoji and closing it and restarting all had no effect. The latency remains.

**Comment by asg0451** [comment]
This a relatively new bug I think. Maybe i could try out some old versions of the client and do a git bisect sort of thing for you guys?

**Comment by Aokromes** [comment]
try 1.9.20 or 1.9.19 betas from releases tab, go down till you find the issue gone.

**Comment by ilya-fedin** [comment]
>  Maybe i could try out some old versions of the client and do a git bisect sort of thing for you guys?

Would be awesome

**Comment by asg0451** [comment]
just got locked out for too many login "attempts" so here's what i found:

1.9.21 - lastest - has issue
1.9.8 - has issue
1.9.7 - cant open -- uses latest automatically
1.9.6 - no linux bin
1.9.4 - cant open -- uses latest automatically
1.9.3 - has issue
1.9.2 - better i think -- seems to hang more often when other users are replying
1.8.8 - does not have issue

obviously there are a lot of versions between 1.8.8 and 1.9.2 but i cant do anymore testing until i get unblocked ;)

hopefully this was helpful

**Comment by ilya-fedin** [comment]
But there are all the releases on gthub releases o_O

**Comment by ilya-fedin** [comment]
> but i cant do anymore testing until i get unblocked ;)

Hmm, I think you find the difference between 1.8.15 and 1.9.2

**Comment by asg0451** [comment]
yeah i just mean i cant log in anymore as i've logged in too many times, so i cant test anymore at the moment....

i'll take another look at other versions later today no no worries

**Comment by ilya-fedin** [comment]
> yeah i just mean i cant log in anymore

Yes, I got it. You can use `-testmode` argument to login to test server.

**Comment by john-preston** [comment]
@ilya-fedin 1.9 had Qt update from 5.6.2 to 5.12.5.

**Comment by ilya-fedin** [comment]
@asg0451 can you show the result of `echo $QT_IM_MODULE`?

**Comment by asg0451** [comment]
> Yes, I got it. You can use -testmode argument to login to test server.

ah cool, thanks

> @asg0451 can you show the result of echo $QT_IM_MODULE?

$ echo $QT_IM_MODULE

(blank)

just run from a regular terminal.

**Comment by asg0451** [comment]
that was without telegram running & signed in
with it running & signed in (with -testmode since im still blocked) i get:

$ echo $QT_IM_MODULE?
?

**Comment by asg0451** [comment]
is there someone i can text to with -testmode? the problem is still apparent in latest with -testmode just from laggy gui interaction but i'd like to be able to test sending messages too.

**Comment by ilya-fedin** [comment]
Hmm, what if you run telegram with `QT_IM_MODULE=xim ./Telegram -testmode`?
(You can write to Saved Messages)

**Comment by asg0451** [comment]
tried that. interestingly when running latest version with -testmode and writing only to saved messages i dont experience any lag. i still experience extreme lag in the gui though (mousing around menus, clicking things). i cant test against non-testmode saved messages though since i cant log in.

**Comment by ilya-fedin** [comment]
Can you tell your hardware? 🤔

**Comment by asg0451** [comment]
lenovo thinkpad x1 carbon 2019
Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (Intel UHD Graphics 620)

ubuntu 18.04.4
kernel 5.3.0-40-generic

fyi I AM affected by this kernel bug https://gitlab.freedesktop.org/drm/intel/issues/673
which could be related and is really annoying in other apps. however, this issue is not just that one, as i saw older versions of the telegram client did not have this behaviour and the symptoms of the kernel issue is on the order of once/twice per day whereas this is constant in the telegram client.

**Comment by asg0451** [comment]
output from inxi -Fzm:
(i am running Proton drivers for gaming during this corona shit, but i had this issue before i installed all that stuff)

System:    Host: frankelbot2 Kernel: 5.3.0-40-generic x86_64 bits: 64 Desktop: i3 4.14.1
           Distro: Ubuntu 18.04.4 LTS
Machine:   Device: laptop System: LENOVO product: 20KH002HUS v: ThinkPad X1 Carbon 6th serial: N/A
           Mobo: LENOVO model: 20KH002HUS v: SDK0J40697 WIN serial: N/A
           UEFI: LENOVO v: N23ET62W (1.37 ) date: 02/19/2019
Battery    BAT0: charge: 53.0 Wh 100.0% condition: 53.0/57.0 Wh (93%)
CPU:       Quad core Intel Core i7-8650U (-MT-MCP-) cache: 8192 KB
           clock speeds: max: 4200 MHz 1: 3878 MHz 2: 3893 MHz 3: 3734 MHz 4: 3788 MHz 5: 3838 MHz 6: 3799 MHz
           7: 3736 MHz 8: 4031 MHz
Memory:    Using dmidecode: root required for dmidecode
Graphics:  Card: Intel UHD Graphics 620
           Display Server: x11 (X.Org 1.20.4 ) driver: i915 Resolution: 1920x1080@59.96hz
           OpenGL: renderer: Mesa DRI Intel UHD Graphics 620 (KBL GT2) version: 4.6 Mesa 20.0.2 - kisak-mesa PPA
Audio:     Card Intel Sunrise Point-LP HD Audio driver: snd_hda_intel Sound: ALSA v: k5.3.0-40-generic
Network:   Card-1: Intel Ethernet Connection (4) I219-LM driver: e1000e
           IF: enp0s31f6 state: down mac: <filter>
           Card-2: Intel Wireless 8265 / 8275 driver: iwlwifi
           IF: wlp2s0 state: up mac: <filter>
Drives:    HDD Total Size: 1024.2GB (28.8% used)
           ID-1: /dev/nvme0n1 model: SAMSUNG_MZVLB1T0HALR size: 1024.2GB
Partition: ID-1: / size: 938G used: 275G (31%) fs: ext4 dev: /dev/nvme0n1p2
RAID:      No RAID devices: /proc/mdstat, md_mod kernel module present
Sensors:   System Temperatures: cpu: 68.0C mobo: N/A
           Fan Speeds (in rpm): cpu: 4084
Info:      Processes: 388 Uptime: 11 days Memory: 12137.4/15754.8MB Client: Shell (bash) inxi: 2.3.56

**Comment by ilya-fedin** [comment]
Maybe slow internet speed? :thinking:
#7432

**Comment by ilya-fedin** [comment]
> fyi I AM affected by this kernel bug

You can start system with `nomodeset` to exclude GPU bugs

**Comment by asg0451** [comment]
> Maybe slow internet speed?

my internet is OK. 
![2020-03-23-131849_909x389_scrot](https://user-images.githubusercontent.com/4358545/77343958-e1949b00-6d08-11ea-94dc-e19cd19e1fc7.png)


> You can start system with nomodeset to exclude GPU bugs

how do i do that? back in the GRUB days i could figure it out, but now that we're in a uefi world i'm not so sure..

**Comment by ilya-fedin** [comment]
> back in the GRUB days i could figure it out, but now that we're in a uefi world i'm not so sure..

If you're using systemd-boot, it supports menu item editing by `e` key, as grub

**Comment by asg0451** [comment]
okay, booted with nomodeset and the lagginess is completely gone
btw i managed to bypass the login lockout by scanning a qr code

**Comment by ilya-fedin** [comment]
Can you send Xorg logs with regular bot?

**Comment by asg0451** [comment]
[Xorg.0.log](https://github.com/telegramdesktop/tdesktop/files/4371080/Xorg.0.log)

**Comment by ilya-fedin** [comment]
Tyry to remove `xserver-xorg-video-intel` package. This should enable the `modesetting` driver. And check that you doesn't have any configs that forces `intel` driver(/etc/X11/xorg.conf, /etc/X11/xorg.conf.d/*).

**Comment by asg0451** [comment]
hmmmm can you explain what that would do and why you want me to do it? would this be similar to doing permanently what i did temporarily with nomodeset?
I still want to be able to run some games on this machine - Proton etc.

**Comment by ilya-fedin** [comment]
> would this be similar to doing permanently what i did temporarily with nomodeset?

No.
https://wiki.archlinux.org/index.php/Intel_graphics#Installation (look at the note)

> why you want me to do it?

To check if this problem is reproducible on other driver

**Comment by asg0451** [comment]
ok cool. let me get back to you a little later with the result. thanks!

**Comment by asg0451** [comment]
oookay so i ran sudo apt remove xserver-xorg-video-intel-hwe-18.04
and removed the line `Driver      "intel"` from /etc/X11/xorg.conf

....and it works perfectly!

is this a stable way to run?

looking at https://launchpad.net/ubuntu/bionic/+package/xserver-xorg-video-intel-hwe-18.04
they basically say don't use this on new hardware.... why is it the default then?

anyway thanks!

**Comment by ilya-fedin** [comment]
> is this a stable way to run?

Yes. I'm using this driver for multiple years on Arch and NixOS.

**Comment by asg0451** [comment]
solid. I'll close this issue then. There definitely was something introduced in a recent version that caused this, but on my machine this fix is adequate and seems like it would have been a good idea anyway. thanks guys!
