### ISSUE TITLE
macOS: Video player cause huge cpu usage

### ISSUE THREAD

**Issue by samfrm** [telegramdesktop/tdesktop#7426]
### Steps to reproduce
1. Simply play a video from a chat or channel (Saved/Stream)

### Actual behaviour
When I play even saved videos in a chat/channel it gets huge cpu usage. 

### Configuration
**Operating system:**
Macos Catalina
10.15.3

**Version of Telegram Desktop:**
v 1.9.21

**Used theme**:
Default Tinted

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/6312#issuecomment-525712797
