### ISSUE TITLE
Does not run in the background using GNOME Shell as DE (Desktop Environment)

### ISSUE THREAD

**Issue by b1thammer** [telegramdesktop/tdesktop#7428]
**### Steps to reproduce**
1. Open Telegram client
2. I write a message / check the messages
3. I close telegram client

**### Expected behaviour**
The client should be running in the background and receive the messages

**### Actual behaviour**
Client closes completely killing the PID (It did not happen with version 1.9.12)

**### Configuration**
Archlinux
DE: GNOME Shell 3.36

**Version of Telegram Desktop:**
1.9.14

**Used theme**:
Day

**Comment by xvitaly** [comment]
If you want to see tray icon, you must install legacy tray support extension. [AppIndicator Support](https://extensions.gnome.org/extension/615/appindicator-support/) for example.

**Comment by b1thammer** [comment]
Since I am using Telegram in GNOME Shell, it never showed an icon in the system tray, it always worked normally in the background when closing the app (PID is still active), receiving messages in my notification tray that when touched to the call to the app, that for me is a bug or some feature is missing

**Comment by ilya-fedin** [comment]
https://github.com/telegramdesktop/tdesktop/issues/7252#issuecomment-597681038

**Comment by xvitaly** [comment]
This is not a bug. If you need a tray icon, you **must** install extension for legacy tray icons support.
