### ISSUE TITLE
It is better to move the emoji button to the left side.

### ISSUE THREAD

**Issue by steadyoak** [telegramdesktop/tdesktop#7429]
Currently, each time I move my cursor to the "scroll to the bottom" button in the chat content list, my cursor will possibly touch the emoji button next to it. And it will expand a large panel which will cover the "scroll to the bottom" button. Which is very annoying.

Thank you for reading this.

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/2294
