### ISSUE TITLE
Provide mouse over text with description of the emojis

### ISSUE THREAD

**Issue by hieronymousch** [telegramdesktop/tdesktop#743]
Hi,

Small detail and extremely low urgency
It would be nice to get a small description or the name of the emoji when selecting an emoji with a mouse over text or something... This way we could see who the faces are in the stickers 

Feel free to close this ticket if this isn't the approriate way to suggest features.

**Comment by formatq** [comment]
+1

**Comment by dkasyanov** [comment]
+1

**Comment by cschanck** [comment]
+1
