### ISSUE TITLE
SHA256 checksum and/or GPG key

### ISSUE THREAD

**Issue by Coffee-Overflow** [telegramdesktop/tdesktop#7430]
### Is your feature request related to a problem?
**Yes**. There is currently:
- No **GPG signature** to verify vendor
- No Checksum  (**minimum SHA256**) to verify download

### Describe the solution you'd like
On the download page, a GPG key
On the download page, a SHA256 checksum 

### Describe alternatives you've considered
None but open to any suggestions that I haven't considered

### Additional context
This is a very important step that is missing. Not being able to verify that the same file that was uploaded by the vendor and then downloaded by the client is a **security flaw**

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/2063
