### ISSUE TITLE
[Feature Request] Schedule polls.

### ISSUE THREAD

**Issue by gregzhadko** [telegramdesktop/tdesktop#7433]
Telegram for Android has the ability to schedule polls.
Despite the fact that I can schedule usual messages, files, media, and images sending, I cannot schedule a poll sending on Telegram desktop.
It would be great to have this feature.

**Comment by 23rd** [comment]
Can't get your request. Perhaps you mean the [native Telegram for macOS](https://macos.telegram.org)? 
<details><summary><b>Screenshot.</b></summary>

![image](https://user-images.githubusercontent.com/4051126/77303190-8b712900-6d03-11ea-97a6-479c13d7e2d0.png)

</details>

**Comment by gregzhadko** [comment]
Sorry, I forgot to mention that it is in the scheduled messages section of the chat or channel.
When I add several messages that have to be sent later, I write them in this section. However, when I add polls, I have to switch back to the main chat.

<details>

<summary>Screenshot</summary>

![Screenshot_1](https://user-images.githubusercontent.com/747485/77305299-59be8900-6d28-11ea-99cf-0cfaed0c8d8b.png)

</details>
