### ISSUE TITLE
Can not mention newly joined users

### ISSUE THREAD

**Issue by melih** [telegramdesktop/tdesktop#7435]
### Steps to reproduce
1. Someone joins the group.
2. You try to mention him/her.

### Expected behaviour
You mention the user.

### Actual behaviour
There's no problem with mentioning old users but you can't mention any user newly joined.

### Configuration
Operating system: Windows 10

Version of Telegram Desktop: 1.9.7

Used theme: Tinted

**Comment by Aokromes** [comment]
update your telegram version to at least 1.9.21.

**Comment by melih** [comment]
Do you have any tips to update Telegram Desktop from Windows Store? Because I can't get updates for a long while although I click on **Get Updates** in the store.

**Comment by Aokromes** [comment]
idk, i don't use store version.
