### ISSUE TITLE
Trojan/Win32.Wacatac in tsetup.1.9.21.exe

### ISSUE THREAD

**Issue by anxxel** [telegramdesktop/tdesktop#7437]
### Steps to reproduce
1. download tsetup.1.9.21.exe for PC/Mac/Linux
2. upload the file to VirusTotal => https://www.virustotal.com
3. have a look at the results

### Expected behaviour
No trojans

### Actual behaviour
Trojan found

### Configuration
**Operating system: Windows 10**

**Version of Telegram Desktop: 1.9.21**

**Used theme> default**

https://www.virustotal.com/gui/file/8a0f9ec4e2844c9b0ebfdaedd83c43da0b4cf637838878135f7e3249c26223c6/detection

**Comment by xvitaly** [comment]
Typical false-positive from trash antivirus engine. There is nothing to worry about.

**Comment by john-preston** [comment]
This is a false positive, I guess not only tdesktop encountered that problem:

![image](https://user-images.githubusercontent.com/17900494/77338016-29381880-6d43-11ea-88c8-aeaef3e5ff59.png)

I've sent them an email, I hope they'll fix it.
