### ISSUE TITLE
No global menu, if added while Telegram running 

### ISSUE THREAD

**Issue by Akionka** [telegramdesktop/tdesktop#7438]
### Steps to reproduce
1. Open Telegram Desktop 
2. Add global menu panel
3. Observe the absence of any menus in the global menu
4. Close Telegram Desktop
5. Open Telegram Desktop
6. Observe the presence of menus in the global menu 

### Expected behaviour
Menus should be added to global menu without restarting telegram desktop.
For example, google chrome works perfectly fine.

### Actual behaviour
You have to restart telegram desktop

### Configuration
**Operating system:** `Manjaro KDE Plasma`

**Version of Telegram Desktop:** 1.9.21 stable

**Used theme**: Default

**Comment by ilya-fedin** [comment]
Konsole, for example, doesn't use global menu until it is restarted :thinking: 
I think this is enhancement rather than a bug

**Comment by Akionka** [comment]
So you won't "fix" it?

**Comment by ilya-fedin** [comment]
¯\_(ツ)_/¯
