### ISSUE TITLE
I cannot use Hangul in Ubuntu.

### ISSUE THREAD

**Issue by iyagicom** [telegramdesktop/tdesktop#7439]
### Steps to reproduce
1. On Ubuntu
2. Hangul is not written.
3. Korean is not written, so I can't chat in Korea.

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

### Configuration
**Operating system:**
ubuntu 20.04 + uim + uim-byeoru
**Version of Telegram Desktop:**
 1.9.21
**Used theme**:

<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/2013

**Comment by iyagicom** [comment]
> #2013

ibus and uim are different.
ibus has bugs, but Korean is used.

**Comment by iyagicom** [comment]
Hangul is written in ibus.
However,
It is not written at all in uim.

**Comment by iyagicom** [comment]
> #2013

Why do you think Ibus and Uim together?
Synchronous and asynchronous.
It's a completely different engine.

**Comment by ilya-fedin** [comment]
#6886 is about uim and nimf
