### ISSUE TITLE
memory leaks macos mojave

### ISSUE THREAD

**Issue by ibyteyou** [telegramdesktop/tdesktop#7442]
### Steps to reproduce
1. i has chats with over>70 users, and every day i load more stickers/gifs etc
2. every day my client eat RAM more 3gb (in a couple of hours)

### Expected behaviour
before updates ~one month old, all was good

### Actual behaviour
my telegram client ate RAM at 13gb

### Configuration
**Operating system:** macos 10.14.6

**Version of Telegram Desktop:** 1.9.21

**Used theme**: custom theme

<img width="280" alt="Снимок экрана 2020-03-24 в 13 28 01" src="https://user-images.githubusercontent.com/16253399/77411193-7664ca80-6dd5-11ea-8df1-d592efd075bd.png">

**Comment by Aokromes** [comment]
very likely the same as https://github.com/telegramdesktop/tdesktop/issues/7361

**Comment by ibyteyou** [comment]
some logs, tests? i can support at night

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/7361
