### ISSUE TITLE
Hebrew font unreadable on snap after PR #7387

### ISSUE THREAD

**Issue by omertuc** [telegramdesktop/tdesktop#7444]
### Steps to reproduce
1. Open the "Snap" version Telegrram
2. Write in Hebrew

### Expected behaviour
Font should look nice

### Actual behaviour
Font looks horrible (Hebrew defaults to FreeMono which has downright unreadable Hebrew glyphs)

This issue is caused by the new `fonts.conf` file (introduced in #7387) included in the snap builds. The old `fonts.conf` file had the line `<include ignore_missing="yes">conf.d</include>` which included all the configuration files from the snap-bundled-directory `/etc/fonts/fonts.d` (which are all symlinks to the configuration files found in the also-snap-bundled-directory `/etc/fonts/fonts.avail`).

The absence of this line causes the Hebrew font to fallback on FreeMono.

The new `fonts.conf` file is [this file, copied from the lib_ui repository](https://github.com/desktop-app/lib_ui/blob/master/qt_conf/fc-custom.conf)

The old `fonts.conf` file was from [here](https://gitlab.freedesktop.org/fontconfig/fontconfig/-/raw/master/fonts.conf.in)

The specific `/etc/fonts/fonts.avail` files needed to fix the Hebrew font are:
`49-sansserif.conf` and `60-latin.conf`. They make it so the following fonts get precedence over `FreeMono` (on my system, I believe `DejaVu Sans` gets chosen out of that list, because it's the only one I have on my system):
```
<family>DejaVu Sans</family>
<family>Bitstream Vera Sans</family>
<family>Verdana</family>
<family>Arial</family>
<family>Albany AMT</family>
<family>Luxi Sans</family>
<family>Nimbus Sans L</family>
<family>Nimbus Sans</family>
<family>Helvetica</family>
<family>Lucida Sans Unicode</family>
<family>BPG Glaho International</family> <!-- lat,cyr,arab,geor -->
<family>Tahoma</family> <!-- lat,cyr,greek,heb,arab,thai -->
```

### Configuration
**Operating system:**
Ubuntu 19.10, also happens on a Fedora I tried
**Version of Telegram Desktop:**
Snap 1.9.21
**Used theme**:

**Comment by ilya-fedin** [comment]
https://github.com/telegramdesktop/tdesktop/issues/5172#issuecomment-600590891

**Comment by omertuc** [comment]
Yeah I saw that comment, but this font is not just ugly - it's nearly impossible to read unless you're very careful, some letters look exactly the same and in Hebrew that makes reading very very hard.

Would `<include>`ing `49-sansserif.conf` and `60-latin.conf` specifically (found in `/etc/fonts/fonts.avail`, already bundled with the snap) inside `fonts.conf` still cause that crash that is mentioned?

**Comment by ilya-fedin** [comment]
It is not known what exactly the problem is, I believe that there is some conflict between snap fontconfig version and fontconfig cache from the host or fontconfig configs from the host. There may also be a problem with some fonts from the host. It is better not to touch the config.

**Comment by omertuc** [comment]
Alright, then please leave this open the issues of at #7144 are better understood so everyone can stay happy

**Comment by ilya-fedin** [comment]
But it is already discussed at #5172

**Comment by john-preston** [comment]
@omertuc Can you please check the latest edge version, will it still have bad fonts?

**Comment by omertuc** [comment]
Works great! Good job, thanks!

**Comment by OrBin** [comment]
@john-preston What do you mean by "edge version"? As I mentioned [here](https://github.com/telegramdesktop/tdesktop/issues/7416#issuecomment-605610097), I've installed Telegram Desktop directly from the website and it solved the issue, but then it was updated to version 2.0 and the the issue appeared again.

**Comment by MeridianExplorer** [comment]
@OrBin `sudo snap install --channel edge telegram-desktop`

**Comment by john-preston** [comment]
@OrBin I wanted you to check the latest snap build (you can try not edge now, but just the latest snap) so that I would know if my workaround has fixed the problem.

The version 2.0 from site is built incorrectly, fonts should be fixed in the upcoming 2.0.1

**Comment by OrBin** [comment]
> @OrBin I wanted you to check the latest snap build (you can try not edge now, but just the latest snap) so that I would know if my workaround has fixed the problem.
> 
> The version 2.0 from site is built incorrectly, fonts should be fixed in the upcoming 2.0.1

When do you expect to release 2.0.1?

**Comment by john-preston** [comment]
@OrBin I hope later today.

**Comment by OrBin** [comment]
Updated now to 2.0.1, but I still have FreeMono font...
