### ISSUE TITLE
Ignored zero-width joiner in emoji "Family: Man, Woman, Boy"

### ISSUE THREAD

**Issue by cypok** [telegramdesktop/tdesktop#7445]
### Steps to reproduce
1. Send the emoji 👨‍👩‍👦 (Family: Man, Woman, Boy, https://emojipedia.org/family-man-woman-boy/).

### Expected behaviour
It should be rendered as a single character. It works as expected on iOS: 
![photo_2020-03-25_09-34-19](https://user-images.githubusercontent.com/16010/77495715-e9c11780-6e7b-11ea-808e-c48a7f84cc8c.jpg)

### Actual behaviour
It is rendered as two characters: Man and Woman with a Boy. This is how it looks on desktop:
<img width="386" alt="Снимок экрана 2020-03-25 в 09 25 58" src="https://user-images.githubusercontent.com/16010/77495768-03625f00-6e7c-11ea-977f-f896daf42078.png">

### Configuration
**Operating system:** macOS 10.15.3

**Version of Telegram Desktop:** 1.9.21

**Used theme**: Classic

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/6959 generic bug.
