### ISSUE TITLE
[Question] Update Linux build instructions

### ISSUE THREAD

**Issue by ParrotBase** [telegramdesktop/tdesktop#7449]
Ubuntu 14.04 reached end of life on April 30, 2019. Would someone be able to get the [Linux build instructions](https://github.com/telegramdesktop/tdesktop/blob/dev/docs/building-cmake.md) updated?

**Comment by ilya-fedin** [comment]
> Would someone be able to get the [Linux build instructions](https://github.com/telegramdesktop/tdesktop/blob/dev/docs/building-cmake.md) updated?

tdesktop, probably, will use Ubuntu 14.04 anyway, to be able to run on Ubuntu 12.04+. In other words, instruction won't be updated in the near feature.
