### ISSUE TITLE
Reuse notifications when receiving multiple messages

### ISSUE THREAD

**Issue by WhyNotHugo** [telegramdesktop/tdesktop#7450]
### Is your feature request related to a problem?

I have notifications turned on, but "Show message preview" turned off.
When I get 4-5 messages, I also get a flow of 4-5 notifications.
They all say the same, and add a lot of clutter:

```
Some person
You have one new message.
```

### Describe the solution you'd like

Notifications support their content being replaced. For example, when I push my volume up, I get a notification saying "volume 10%". If I push it a bit more, the same notification updates to say "volume 13%".

I believe the same idea would make sense for notifications. Right now I get:
```
John Doe
You have one new message.
```

When I get a second message, just update this notification to:
```
John Doe
You have two new messages.
```

### Describe alternatives you've considered

I haven't really been able to think of any others.

### Additional context

I'm certain this is supported by libnotify on linux, since I've actually scripted to use this feature many times. macOS's notification system supports this too. I've no idea about windows, since the last version of windows I used didn't have support for notifications at all.

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/429

**Comment by WhyNotHugo** [comment]
#429 seems like something completely different. I'm not using sound notifications, nor are those relevant in this context.

**Comment by RememberTheAir** [comment]
Yes, this should be re-opened

**Comment by Aokromes** [comment]
if you realize

"
The solution: Merge new line-wise part-messages if they are still in a certain time threshold (e.g. 5 seconds) with the old message. Do not trigger a new sound notification.
"

it's more than simply merge messages. it's merge messages AND don't trigger notifications.

**Comment by RememberTheAir** [comment]
This issue is about merging them in the notification only, not in the chat (which is 429's proposal)

**Comment by WhyNotHugo** [comment]
>  The solution: Merge new line-wise part-messages if they are still in a certain time threshold (e.g. 5 seconds) with the old message. Do not trigger a new sound notification.

You're talking about merging the bubbles in the conversation.

I'm talking about upping the count in the notification.

These are different things:
- For the conversation, you want to do it time-based (messages within X seconds?).
- For the notification, you should only care if the previous one is still there. It doesn't matter if it's been 1 second or 1 minute, if I still haven't dismissed the "you have one new message", it should change to "you have two new messages".

> it's more than simply merge messages. it's merge messages AND don't trigger notifications.

But I _do_ want a notification. If I still haven't looked at the previous "you have one message" notification, I want that to switch to "you have two messages". It doesn't matter how much time has passed, why would you _not_ trigger the notification? I'd have no way of knowing I have a second message.
