### ISSUE TITLE
[Attention] Lack of report feasibility and terminations

### ISSUE THREAD

**Issue by ghost** [telegramdesktop/tdesktop#7451]
There is a serious issue about fast growing pornographic groups and channels in telegram however 
 desktop software does not show any option for report some groups as well (eg: below screenshot)

![image](https://user-images.githubusercontent.com/48867565/77677320-167f4700-6fc2-11ea-861b-72f0bd93db1e.png)

Will it be possible for telegram to offer dedicated way for volunteers to help for that? or consider to use self hosted recognition solution to make sense either. 
Unfortunately we see that default report method take time for effect also such channels, groups are expanding on the platform too faster than you guys terminate them.

Furthermore, we doubt that may leads to dark day for telegram 👮

**Comment by itsnotsaved** [comment]
bump

**Comment by itsnotsaved** [comment]
ping !telegram @john-preston @Aokromes

**Comment by john-preston** [comment]
I guess reports are disabled for private groups (but you can report messages in them anyway). I'll add report button for private groups as well.
