### ISSUE TITLE
Telegram closes after some time being minimized to tray

### ISSUE THREAD

**Issue by Garbulix** [telegramdesktop/tdesktop#7453]
# Steps to reproduce
1. Open app (installed via Flathub)  
2. Close app using "X" sign (top right corner) to minimize it to system tray.
3. After some time being minimized to "tray", app closes itself without any notification (icon just disappears).
4. When app isn't minimized to tray (it is shown in all-opened-apps view in GNOME), it stays open.

### Expected behaviour
Telegram shouldn't close. 

### Actual behaviour
When minimize, Telegram closes after less than ten minutes without any notification

### Configuration
**Operating system:** Fedora 31 with GNOME desktop and appindicators installed. 

**Version of Telegram Desktop:** 1.9.21

**Used theme**: vanilla GNOME 3.34 with Adwaita. In Telegram I have custom dark theme.

**Bash log (doesn't matter if Telegram is minimized or not - output is the same):**  
``` 
$ /usr/bin/flatpak run --branch=stable --arch=x86_64 --command=telegram-desktop --file-forwarding org.telegram.desktop -- @@u %u @@  
Qt: Session management error: None of the authentication protocols specified are supported  
error: : cannot open  
error: : cannot open  
error: : cannot open  
```

**Comment by ilya-fedin** [comment]
Can you reproduce with non-flatpak'ed version?

**Comment by Garbulix** [comment]
I've installed non-flatpaked version of Telegram (from rpmfusion repository) and it works fine. 
I've also checked if flatpak version works fine on Xorg session (Wayland is Fedora's default), but it also closes itself after couple minutes, so display server may not be a thing.. 
So I guess that is flatpak-related issue. Does it mean that Telegram has nothing to do about it?

**Comment by ilya-fedin** [comment]
> I've installed non-flatpaked version of Telegram (from rpmfusion repository) and it works fine.

Okay. Try to enable autostart in settings of flatpak'ed telegram. It should request permission to run in the background. After granting permission you can disable autostart, permission is persistent.

**Comment by Garbulix** [comment]
The problem is that I tried (in the past) to enable autostart option, but without effect (that function just didn't work - Telegram wasn't starting with the system), so I turned it off. Maybe that time system asked me about granting permission, but I missed that.
When I turned on autostart option now, I had no notification about app being in background also. 
Even after reinstalling an app with deleting hidden files related to Telegram in my home directory, I had no notification about being in background.
I want to make an issue about that, because that is frustrating - GNOME and Flatpak (so... just GNOME) want to make some things too simple. 
I also thing that the thing is some kind of permission management. I am angry, because I can't find an option about apps-in-backgorund in system settings nor dconf-editor. I also can't find any documentation about that.

**Comment by Garbulix** [comment]
I think my problem is solved now.
I accidently ran into a solution when being on flatpak docs website ([flatpak command reference](https://docs.flatpak.org/en/latest/flatpak-command-reference.html))
That was true Telegram didnt have permission to work in background (`flatpak permission-show org.telegram.desktop`), so I reset Telegram permissions (`flatpak permission-show org.telegram.desktop`) and when turning autostart option on, GNOME asked me about working in background. 
So it works now and I think issue is ready to close. I will talk with GNOME guys now.
