### ISSUE TITLE
Sound Recorder Disappeared

### ISSUE THREAD

**Issue by gengaralakazam** [telegramdesktop/tdesktop#7455]
In version 1.9.21 sound recorder button disappeared. 
![Screenshot_5](https://user-images.githubusercontent.com/62767426/77787860-518c8380-7071-11ea-9285-bf22b9110191.jpg)

**Comment by Aokromes** [comment]
it's there for me.
what os?

**Comment by gengaralakazam** [comment]
windows 10 pro

**Comment by Sasha-Sorokin** [comment]
Are you sure you don't have anything in your text field? The icon is only shown when there is no text in the field to sent, otherwise replaced with send button for obvious reasons.

**Comment by gengaralakazam** [comment]
yeah i'm sure sir.
![Screenshot_7](https://user-images.githubusercontent.com/62767426/77800160-43e1f880-7087-11ea-921f-564510df264e.jpg)

**Comment by gengaralakazam** [comment]
now i deleted and reinstalled my drivers and now i can see mic button. thank you for helping me.

![Screenshot_2](https://user-images.githubusercontent.com/62767426/77801662-53af0c00-708a-11ea-84f2-c9286aeaa6ac.jpg)

**Comment by Sasha-Sorokin** [comment]
So it was an issue with *microphone* on its own and that Telegram just didn't see it. And it's now resolved with that simple trick, nice. Don't forget to close the issue [with red button next to “Comment”] to keep the tracker clean :)
