### ISSUE TITLE
Hidden custom proxy

### ISSUE THREAD

**Issue by mymedia2** [telegramdesktop/tdesktop#7458]
When a user adds a first proxy, the list remains empty in UI, although Telegram Desktop connects to it.

### Prerequisites
1. Have empty proxy list.

### Steps to reproduce
1. Open proxy settings.
2. Click "Add proxy".
3. Type proxy address and port.
4. Click "Save".

### Expected behaviour
1. The new proxy will be seen in the list.

### Actual behaviour
1. The list is still empty.
2. Telegram Desktop can use the new proxy.

### Configuration
**Operating system:** GNU/Linux Ubuntu MATE 19.10

**Version of Telegram Desktop:** 1.9.22 beta

**Used theme**: Default

![TelegramDesktop_screencast.gif](https://user-images.githubusercontent.com/9163157/77802296-9cb39000-708b-11ea-85be-76b0142f35fe.gif)

[TelegramDesktop_workdir.tar.gz](https://github.com/telegramdesktop/tdesktop/files/4396032/TelegramDesktop_workdir.tar.gz)

**Comment by AliDjango** [comment]
I can confirm this happens but they appear out of blue in a minute or something.
Operating system: Raspbian buster on raspberry pi 3b/3b+
Version of Telegram Desktop: Snapcraft package version `1.9.22-beta-104-gdeb76f38d`
