### ISSUE TITLE
Folder with all types of chats minus read and archived shows the wrong chats

### ISSUE THREAD

**Issue by RememberTheAir** [telegramdesktop/tdesktop#7464]
### Steps to reproduce
1. create a new folder as follows:
  - included chats: contacts, non-contacts, groups, channels, bots (all types)
  - excluded chats: read, archived
2. open the folder

### Expected behaviour
The folder should contain only all unarchived chats with unread messages

### Actual behaviour
For some reasons, this folder contains my **archived pinned** chats that **don't** have any unread message. Very weird. The folder shows the correct chats from android

### Configuration
**Operating system:** Windows 10

**Version of Telegram Desktop:** 1.9.22

**Comment by decadence** [comment]
How can I create chat folder? I have 1.9.22 on Windows 10 but can't find any relevant menu item or button.

**Comment by omkarnathsingh** [comment]
Please try again, seems working fine for me in Windows 10, beta version.

**Comment by RememberTheAir** [comment]
I tried on Linux Mint and it doesn't happen. Will try to create a test folder on Windows and see if it's fixed on the machine where I've originally seen this and close the issue if it's fixed

**Comment by john-preston** [comment]
I couldn't reproduce as well.

**Comment by RememberTheAir** [comment]
Tried again, doesn't happen anymore. Closing
