### ISSUE TITLE
Dice stopped rolling though no network

### ISSUE THREAD

**Issue by NekoInverter** [telegramdesktop/tdesktop#7465]
### Steps to reproduce
1. Send a dice
2. Network gone

### Expected behaviour
Dice rolling forever

### Actual behaviour
Dice stopped rolling
![image](https://user-images.githubusercontent.com/42698724/77812316-7cabbd00-70db-11ea-8f41-835e6932acb4.png)

### Configuration
**Operating system:**Windows 10

**Version of Telegram Desktop:**1.9.22Beta

<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by omkarnathsingh** [comment]
the output of dice is decided by server, so if network is gone, this is expected to happen.

**Comment by NekoInverter** [comment]
> the output of dice is decided by server, so if network is gone, this is expected to happen.

They should keep rolling forever

**Comment by omkarnathsingh** [comment]
@NekoInverter no, its fine this way. Its not some sticker with set loop infinite. I don't believe this will be fixed ever.
