### ISSUE TITLE
wrong color for menu folder

### ISSUE THREAD

**Issue by MrMorteZw** [telegramdesktop/tdesktop#7466]
### Steps to reproduce
1. 
2. 
3. 

### Expected behaviour
Tell us what should happen

### Actual behaviour
![tel](https://user-images.githubusercontent.com/43701982/77815499-42412080-70d9-11ea-8475-558de6386481.png)

Tell us what happens instead

### Configuration
**Operating system:**Windows

**Version of Telegram Desktop:**1.9.22 beta

**Used theme**:Default light

<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by ilya-fedin** [comment]
#7460?

**Comment by omkarnathsingh** [comment]
@MrMorteZw which theme are you using?
