### ISSUE TITLE
Download a file multiple times and make duplicate copies when hit the "Open With" button in tdesktop for Windows

### ISSUE THREAD

**Issue by ziaa** [telegramdesktop/tdesktop#747]
After downloading a file, when I hit the "**Open With**" button TD re-download the file, Instead of opening it, and make **duplicate copies** (with added number at the end of the file name) in default download folder.

![duplicatefile](https://cloud.githubusercontent.com/assets/10724305/7780399/a7373df4-00f3-11e5-895c-1e170c5594c3.PNG)

![duplicate](https://cloud.githubusercontent.com/assets/10724305/7780401/a910ae80-00f3-11e5-89bc-2d25dfc2447d.PNG)
### Software versions
- Telegram Desktop  v0.8.17
- OS: Microsoft Windows 7 Home Premium v6.1.7601 Service Pack 1

**Comment by auchri** [comment]
Better than overriding some important documents

**Comment by auchri** [comment]
@telegramdesktop Maybe save the document in a temp folder, compare the checksum of the two documents and only create a new one, if the checksum don't match

**Comment by ziaa** [comment]
It seems acceptable For small files. But for large files  re-downloading a file, **Instead of opening**, is not acceptable and of course  it's annoying!

Additionally, I think that it's a `bug` rather than `enhancement`. Maybe I didn't describe the problem correctly.

**Comment by ali7739** [comment]
Same problem here on my desktop, very annoying partciularly for large files.

**Comment by Mistero5050** [comment]
Same problem here...

**Comment by Aokromes** [comment]
this bug is still valid on 1.9.8?

**Comment by Aokromes** [comment]
no answer after near 1 month, if this bug is still valid, open a new ticket with one updated telegram version downloaded from desktop.telegram.org or github.com
