### ISSUE TITLE
Forwarded dice takes more space

### ISSUE THREAD

**Issue by NekoInverter** [telegramdesktop/tdesktop#7472]
### Steps to reproduce
1. Send a dice
2. Forward it

![image](https://user-images.githubusercontent.com/42698724/77820276-09766b00-711c-11ea-9148-54e70a46f923.png)

### Configuration
**Operating system:**

**Version of Telegram Desktop:**1.9.22beta

**Used theme**:

<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by AliDjango** [comment]
he means it has more "padding" to the left side and they don't align:
![image](https://user-images.githubusercontent.com/13733900/77844178-696f1f00-71b9-11ea-9147-6793cafc2ffb.png)
