### ISSUE TITLE
Dice stopped rolling if switched to other chat while rolling

### ISSUE THREAD

**Issue by NekoInverter** [telegramdesktop/tdesktop#7473]
### Steps to reproduce
1. Send a dice
2. Switch to other chat while it's rolling
3. Switch back

### Expected behaviour
Get a number from dice

### Actual behaviour
Dice stopped rolling without giving any number

### Configuration
**Operating system:**

**Version of Telegram Desktop:**1.9.22Beta

**Used theme**:

<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by asiekierka** [comment]
Tried to reproduce on 2.0.0, the animation resets upon switching tabs, but does not freeze.

**Comment by NekoInverter** [comment]
I think this is fixed
