### ISSUE TITLE
[Feature Request] Automatic removal of offline proxies

### ISSUE THREAD

**Issue by BaseMax** [telegramdesktop/tdesktop#7474]
Hello,

### Is your feature request related to a problem?

I just wanted to report something which is really annoying in countries in which Telegram messenger is banned, 
Here we use MTProto proxies to access telegram, there are channels that provide new MTproto proxies everyday. 
Government keeps blocking them so we have to add new proxies everyday. 
And after a month, everybody has more than five hundred proxies saved on their Telegram, which causes the program to crash or get extremely slow when we tab on the proxy bar. 

Many people keep reinstalling telegram every month to avoid this problem.

### Describe the solution you'd like

In order to solve this issue I suggest a new option, which automatically removes proxies if they are offline for more than 24 hours for example.

There can be an optional check box in the proxy section, which is like **[ Remove proxies that has been offline for more than 24 hours ]**
and if the user checks this option, it will work for those who want it to work.

### Describe alternatives you've considered

I think it would be a very good feature to delete unavailable proxies all together in one click.

What's your idea?

Best wishes,
Max Base

**Comment by Aokromes** [comment]
na, proxies maybe off temporally auto remove them will make people to be angry because having to read them, maybe instead remove, disable them if down after 3 times. (or even one amount of times)
Like this but with disable.
https://i.imgur.com/HuXjvuy.png
