### ISSUE TITLE
[BUG] Telegram Desktop resetting after programm restart. 

### ISSUE THREAD

**Issue by GlowTimeHD** [telegramdesktop/tdesktop#7475]
After every restart, I need to relogin to Telegram and update the settings again to my defaults.
This happens since yesterday.
I tried reinstalling, but same behaviour.

**Comment by john-preston** [comment]
@GlowTimeHD Can you please contact me at t.me/preston? I would like to debug this.

**Comment by damianshrinivas** [comment]
I have that problem too, settings or any changes in the app are not saved.

**Comment by john-preston** [comment]
@damianshrinivas Is the authorization saved? Or you relogin each time?

**Comment by john-preston** [comment]
@damianshrinivas anyway, can you contact me at t.me/preston? I would like to debug this (perhaps with several test versions with additional logging).

**Comment by Aokromes** [comment]
@damianshrinivas your issue was fixed?

**Comment by damianshrinivas** [comment]
Yes, it's fixed
