### ISSUE TITLE
[Feature Request] CTRL + SHIFT + UP/DOWN to switch between folders

### ISSUE THREAD

**Issue by RememberTheAir** [telegramdesktop/tdesktop#7477]
### Is your feature request related to a problem?
A keyboard shortcut to navigate through folders would be very handy. Right now, to switch between folders, I have to use the mouse. 

### Describe the solution you'd like
CTRL + SHIFT + UP/DOWN is not used yet so it would be nice to bind it to folders navigation

### Describe alternatives you've considered
Also CTRL + SHIFT + PAGE UP/DOWN is also free

**Comment by jeffythedragonslayer** [comment]
Ctrl+ up/down scrolls through messages, but what about Shift + up/down?  It also appears to be unbound.

**Comment by RememberTheAir** [comment]
Implemented in tdesktop 2.0.0 (CTRL + SHIFT + UP/DOWN)
