### ISSUE TITLE
[Feature Request] Archived chats must be in archive in folders

### ISSUE THREAD

**Issue by andrew000** [telegramdesktop/tdesktop#7478]
Archived chats must be in archive in folders. 

Here are archived chats. But in PM folder they are not archived

![Screenshot_3](https://user-images.githubusercontent.com/11490628/77853586-773e9780-71ed-11ea-9e90-a8afac7b5112.png)

**Comment by jeffythedragonslayer** [comment]
Relevant screenshot, it currently appears under search bar:

<img width="456" alt="archived_chats" src="https://user-images.githubusercontent.com/13253146/77837722-549f7680-713a-11ea-9a8e-c99310817b32.png">

**Comment by AliDjango** [comment]
it is a must thing.we archive chats for a reason and it really bugs me to see those chats between more important stuff

**Comment by jeffythedragonslayer** [comment]
At the very least keep them at the bottom instead of the top.

**Comment by john-preston** [comment]
@AliDjango If you want a folder without archived chats, you just exclude archived chats when editing that folder.

**Comment by jeffythedragonslayer** [comment]
I think he means he doesn't like the 'Archived chats' taking up space in the main chat list, so it should should be an actual folder instead.

**Comment by AliDjango** [comment]
@john-preston what i mean is that for example i what to have a `channels only` folder that include  archived channels as well but inside a `archived chats` at the top of the list so they don't take space

yes that's what i mean @jeffythedragonslayer

**Comment by john-preston** [comment]
@AliDjango Sorry, this is not planned.

**Comment by AliDjango** [comment]
I think that's expected behavior when you include "channels" and "archived chats".because "archived chats" is getting filtered with "channels" so other kinds of chats get removed but archived chats are shown another list and maybe this should happen as well in folders

thanks for responding.maybe my logic is wrong but I really think this makes chats much better and organized and makes telegram easier to use.
I hope telegram team can rethink this in the future :)

**Comment by john-preston** [comment]
@AliDjango A lot of channels went to archive before folders were introduced to free space in the main list. Now you may want to read all your channels, like a feed, but still keep them in archive.

**Comment by AliDjango** [comment]
@john-preston that makes sense...will it be possible to add a toggle where we can put them in `archived chats` or put them with normal chats and read them like a feed then?

**Comment by andrew000** [comment]
Here are archived chats. But in PM folder they are not archived

![Screenshot_3](https://user-images.githubusercontent.com/11490628/77853517-2169ef80-71ed-11ea-9e51-9b1cc142040d.png)
