### ISSUE TITLE
Workmode disappeared 

### ISSUE THREAD

**Issue by vmorenomarin** [telegramdesktop/tdesktop#7483]
Hi.

Has disappeared work-mode in last beta update?

Work-mode is a good option to use Telegram Desktop in office.

**Comment by RememberTheAir** [comment]
It's not needed anymore. You can create a folder that behaves in the same way of workmode: include all types of chats (contacts, non-contacts, groups, channels, bots) and exclude read, muted and archived chats

**Comment by vmorenomarin** [comment]
> It's not needed anymore. You can create a folder that behaves in the same way of workmode: include all types of chats (contacts, non-contacts, groups, channels, bots) and exclude read, muted and archived chats

Excellent option. Thanks to developers.

**Comment by AlexByte** [comment]
Yes, goodbye channels.

**Comment by AlexByte** [comment]
it really is, you can exclude muted chats.
