### ISSUE TITLE
[Feature Request] Increase Folder Name Length

### ISSUE THREAD

**Issue by jeffythedragonslayer** [telegramdesktop/tdesktop#7484]
Currently folder names are limited to 12 characters.  Can this be increased, such that in the left folder sidebar, the name will either:

- be truncated with ellipses (...) like chat names (possibly allowing horizontal resizing of the folder sidebar just like the chat sidebar) or
- be rendered with newlines where spaces in the folder name are, and increasing the vertical size of that particular folder icon

**Comment by Aokromes** [comment]
very likely this needs to be api side.

**Comment by jeffythedragonslayer** [comment]
Really?  https://core.telegram.org/methods only mentions methods deleteFolder and editPeerFolders.  Are the docs incomplete?

**Comment by jeffythedragonslayer** [comment]
I don't know what the flags.13 refers to.  Could that be a char array including a null terminator?
