### ISSUE TITLE
New Folder not immediately appearing in sidebar

### ISSUE THREAD

**Issue by jeffythedragonslayer** [telegramdesktop/tdesktop#7485]
### Steps to reproduce
1. Click "Edit" in folder siderbar
2. Click "CREATE NEW FOLDER"
3. Type a folder name
4. Click "ADD CHATS" and select at least one
5. Click "Create"

Observe that New Folder window closes, but the newly created folder is not visible in the dimmed siderbar yet

6. Press ESC, closing the "Folders" editing window

Now the new folder is visible in the sidebar

### Expected behaviour
New  folder should be visible in dimmed sidebar immedately after clicking "Create"

### Configuration
**Operating system:**
Windows 10

**Version of Telegram Desktop:**
1.9.22 beta

**Used theme**:
Dark

**Comment by john-preston** [comment]
@jeffythedragonslayer All the changes in manage folders Settings section are applied only after closing the section. Those modifications are not very light, so they are done once you've finished editing the folders. Especially delete-restore would be problematic.

**Comment by jeffythedragonslayer** [comment]
@john-preston light on what, memory or CPU?  It sounds like you mean the folder changes are queued up and then done in a batch when exiting the Folders window in case someone is creating/editing/deleting a lot of folders as to not slow down the GUI of that window.  If this is the case then perhaps an "Apply changes" button at the bottom of the Folders window?

As a user, when I see two views of the same information (the folder sidebar and the "My folders" list in the Folders window) get out of sync because one of them updated but the other did not, I might think the operation failed.

**Comment by john-preston** [comment]
@jeffythedragonslayer Maybe "Done" could be renamed to "Apply" at the bottom of the box.

**Comment by jeffythedragonslayer** [comment]
I don't see a Done button in either the Folders window or New Folder window, so maybe we are not looking at the same one.  These are the two windows I see:

![image](https://user-images.githubusercontent.com/13253146/77843964-1a50cc00-7170-11ea-8691-68e4aab80568.png)
