### ISSUE TITLE
LZMA build trouble and x86 vs. x64

### ISSUE THREAD

**Issue by jeffythedragonslayer** [telegramdesktop/tdesktop#7486]
I tried following the Visual Studio 2019 build instructions as closely as possible (skipping setting up API keys as I don't want to talk to the servers right now) and am hitting these errors:

> D:\TBuild\Libraries\lzma\C\Util\LzmaLib>msbuild LzmaLib.sln /property:Configuration=Debug
> Microsoft (R) Build Engine version 16.5.0+d4cbfca49 for .NET Framework
> Copyright (C) Microsoft Corporation. All rights reserved.
> 
> Building the projects in this solution one at a time. To enable parallel build, please add the "-m" switch.
> Build started 3/28/2020 11:49:53 PM.
> Project "D:\TBuild\Libraries\lzma\C\Util\LzmaLib\LzmaLib.sln" on node 1 (default targets).
> D:\TBuild\Libraries\lzma\C\Util\LzmaLib\LzmaLib.sln.metaproj : error MSB4126: The specified solution configuration "Debug|x64" is invalid. Please specify a valid solution configuration using the Configuration and Platform properties (e.g.
>  MSBuild.exe Solution.sln /p:Configuration=Debug /p:Platform="Any CPU") or leave those properties blank to use the defa
> ult solution configuration. [D:\TBuild\Libraries\lzma\C\Util\LzmaLib\LzmaLib.sln]
> Done Building Project "D:\TBuild\Libraries\lzma\C\Util\LzmaLib\LzmaLib.sln" (default targets) -- FAILED.
>
>
> Build FAILED.
> 
> "D:\TBuild\Libraries\lzma\C\Util\LzmaLib\LzmaLib.sln" (default target) (1) ->
> (ValidateSolutionConfiguration target) ->
>   D:\TBuild\Libraries\lzma\C\Util\LzmaLib\LzmaLib.sln.metaproj : error MSB4126: The specified solution configuration "Debug|x64" is invalid. Please specify a valid solution configuration using the Configuration and Platform properties (e.
> g. MSBuild.exe Solution.sln /p:Configuration=Debug /p:Platform="Any CPU") or leave those properties blank to use the de
> fault solution configuration. [D:\TBuild\Libraries\lzma\C\Util\LzmaLib\LzmaLib.sln]
> 
>     0 Warning(s)
>     1 Error(s)
> 
> Time Elapsed 00:00:00.12

Opening LzmaLib.sln in Visual Studio and looking at the property pages, I have both Debug and Release configurations but only x86 platform.  Any ideas where I messed up?

**Comment by jeffythedragonslayer** [comment]
builds succeeded when I added "/property:Platform=x86" to the end of both msbuild commands, so I am unblocked for now.

**Comment by jeffythedragonslayer** [comment]
Opened #7487

**Comment by john-preston** [comment]
@jeffythedragonslayer Are you sure you perform all the commands from "x86 Native Tools Command Prompt"? 64 bit Windows build was not performed or tested, so please use x86 command shell.

**Comment by jeffythedragonslayer** [comment]
My bad, I was in the x64 shell, the muscle memory of typing 64 every time I see 86 is pretty strong. xd
