### ISSUE TITLE
[Feature Request] Focus Mode

### ISSUE THREAD

**Issue by powerfuldeveloper** [telegramdesktop/tdesktop#7490]
### Is your feature request related to a problem?
I have many different channels and groups which are mixed and some of them are
related to my work and some other tot Stock market , ... organizing all this channels,
groups, chats and other stuff can be time consuming and also sometimes destroys my focus
on my work  (consider where I work as a company which one of it's way of communication
with customers is Telegram).

### Describe the solution you'd like
It would be great if users could build an **environment**, **workspace** or maybe **space** in which they can add channels, groups or chats so they can say **when** or **where** they want to see **what**

### Describe alternatives you've considered
Nothing so far maybe different phone number or maybe using archive !

### Additional context
The Idea came from new android feature called focus mode.

**Comment by AliDjango** [comment]
This is added in beta and it is called folders:
![image](https://user-images.githubusercontent.com/13733900/77844029-fe711880-71b7-11ea-86b7-dc436f7b5e1c.png)

use the latest beta to test if you like:
https://github.com/telegramdesktop/tdesktop/releases/tag/v1.9.22

or wait for next stable update

**Comment by powerfuldeveloper** [comment]
@AliDjango 
Can you create your own folder too ?

**Comment by AliDjango** [comment]
@powerfuldeveloper yes you can name it whatever you want and add chats you like

make a folder name `work` and add your clients/company channel to it
make another folder `stocks` and add stock news and ... chats to it.
make another folder `family` and add your family members and personal chats to it
