### ISSUE TITLE
[Question] How to move suggested spellchecker back to right click menu ?

### ISSUE THREAD

**Issue by lacrimal** [telegramdesktop/tdesktop#7491]
Hi,
I'm on windows 10, telegram desktop 1.9.21.
Spellcheck results are now in sub menu 'Spelling' of right- click menu.
right_click -> Spelling -> <suggested words>
How to move back to right_click > <suggested words> so without sub menu 'Spelling'?

Thanks

**Comment by Aokromes** [comment]
you cannot.

**Comment by lacrimal** [comment]
Ok, thanks for brief response, now can you suggest is closing question and opening feature request will be right way to proceed ? Or you see some different options here ?

**Comment by Aokromes** [comment]
i don't think it will be back to old way.

**Comment by lacrimal** [comment]
I think it should be.

**Comment by lacrimal** [comment]
...added as feature request
