### ISSUE TITLE
[Question] Where are folders?

### ISSUE THREAD

**Issue by maxoku** [telegramdesktop/tdesktop#7493]
I've got a new update today to version 1.9.22 beta and got a changelog:
• Organize chats into Chat Folders if you have too many chats.

But I can't find anything that would manage or create folders. Could someone tell me how to access it?

**Comment by RememberTheAir** [comment]
The folders menu is not shown if you have less than 100 chats. To force-show it, open this link from within the app (eg. paste it to your saved messages and then open it): `tg://settings/folders`

**Comment by maxoku** [comment]
Thanks for the answer, it works now. Weird that there is such restriction. It's very useful even with far less chats than 100.
