### ISSUE TITLE
[Feature Request] Raise Folders Limit 

### ISSUE THREAD

**Issue by devcline** [telegramdesktop/tdesktop#7495]
I found that 10 limit folder is not enough for me, with all the functions, chats and groups i can create.
The feature that will be great its to put folders into folders like on _discord_. So the limit will be still 10 folders but for example another 5 folders inside each of the 10 folders, when you click on it, the folders expands.

**Comment by RememberTheAir** [comment]
It's an API limit, the server doesn't allow to create more than 10 folders or subfolders
