### ISSUE TITLE
Crash when clicking on image sent uncompressed

### ISSUE THREAD

**Issue by soren121** [telegramdesktop/tdesktop#750]
Using version 0.8.17. When a friend sends you an image as a file (i.e. uncompressed), clicking on the filename causes the client to crash. Clicking on the adjacent Download button works fine, though.

I was only able to reproduce this bug on Windows. The Linux client seems to be unaffected.

**Comment by rasubuntu** [comment]
Hi :)
I also have this problem.
Telegram version 0.8.17
(Linux) Kubuntu 14.04.2

**Comment by Walkman100** [comment]
> clicking on the filename causes the client to crash

Are you sure you have the filetype default set?

**Comment by soren121** [comment]
It's got nothing to do with the file handlers. This crash happens only when the file has not already been downloaded, and it crashes immediately upon starting the download. If you download the file using the right-click menu or the Download button, and then click on the filename to open it, it works fine.

**Comment by rasubuntu** [comment]
I downloaded pictures without problems.
But to open it, the telegram Crash.

**Comment by xandr0s** [comment]
+1
if run app from terminal `./Telegram`
>libs init..
>loading appindicator3 with version 1..
>loaded appindicator3 with version 1!
>loading gtk-3 with version 0..
>loaded gtk-3 with version 0!
>loaded gtk funcs!
>loaded appindicator funcs!
>status icon api loaded
>loading unity with version 9..
>loaded unity with version 9!
>unity count api loaded
>Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 70: non-double matrix element
>Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 70: non-double matrix element
>Fontconfig warning: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 78: saw unknown, expected number
>Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 70: non-double matrix element
>Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 70: non-double matrix element
>Fontconfig warning: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 78: saw unknown, expected number
>Ошибка сегментирования

**Comment by soren121** [comment]
Seems to be fixed as of 0.8.21.
