### ISSUE TITLE
[Feature Request]  UX suggestions for chat folders

### ISSUE THREAD

**Issue by sdns** [telegramdesktop/tdesktop#7500]
I updated the telegram desktop and I am using chat folders. It is a very good idea. I have some suggestion for the better UX:

**Ideas:**
- **important:** please add a setting to disable show count of the unread messages in the folders left column. (or a setting to show the only count of un-muted chats) The user gets confused by seeing so many numbers.
- please add more icons to folders. for example, I can't find a good icon for my "news" folder!
- when the user right-clicks on a chat, he should be able to add it to the folders. (or with drag-drop)
- please change the folders left column background-color to light color. (or add a setting that user can change it to light background)
- user should be able to drag the folder to the top of `All Chats`. for example, I want to drag my personal chats to the first item. or a better way is this: `All Chats` be a default folder and the user can remove or drag it.
- please add `archived chat` as a folder like `channels` or `groups` default folders. (or add menu `move to folders` like `move the main menu` in right-click)

**solved:**
- in the `edit folder` page, in the `included chats` section: `add chat` button is in the bottom of chats and if the chat list is long, the user should scroll down. please add this button to the top of the list. (**fixed** in v2.0.0 update)
- please show pinned chats in the top, in the folders too. (**fixed**: each folder has separate pinned chat)
- `workmode` not work. please return it in all chats. (**fixed**: #7483 you can create it by folders)

**Comment by john-preston** [comment]
@sdns Each folder has separate pinned chats list.

**Comment by RememberTheAir** [comment]
> workmode not work. please return it in all chats.

See #7483

> please change the folders left column background-color to light color. (or add a setting that user can change it to light background)

See #7460

> in the edit folder page, in the included chats section: add chat button is in the bottom of chats and if the chat list is long, the user should scroll down. please add this button to the top of the list.

Fair. In my opinion this should be a separate issue since also the mobile apps show the option at the top. It is sure unnecessarily hard to reach now, if you have many pinned chats/manually included chats in a folder

**Comment by TrDex** [comment]
I also suggest to make the ability to drag-and-drop chats into the folders, so it will behave more native.

**Comment by RememberTheAir** [comment]
@TrDex see #7463

**Comment by reallyuniquename** [comment]
> show folder unread count only for unmuted chats

It looks like a bug because we already have `Include muted chats in unread count` checkbox that doesn't affect folders. @Aokromes, should I create a separate issue for this?

**Comment by Nashev** [comment]
Also, when the user right-clicks on a chat, he should be able to REMOVE it to from the current folder (add them to "removed" list of folder)

**Comment by Nashev** [comment]
Also, allow rearranging folders by drag-drop not only in left bar, but also in a Folders editing window.

**Comment by Nashev** [comment]
And the possibility to view and manage list of folders in a chat info card, near media, shared links, files and so on.

**Comment by Nashev** [comment]
And possibility to choose, what folder's counter will be displayed over the tray icon.

By the way, counter over tray icon must be included in the hint message for this tray icon. Because over tray icon now I can see only one digit, while the counter is much longer.

**Comment by dreua** [comment]
Do we have keyboard shortcuts to switch between folders? If no, that would be great.

**Comment by yashpalgoyal1304** [comment]
@sdns can u please add the relavant issue id in the issue description (e.g. those given by @RememberTheAir): #7460 #7463 (since these are both earlier issues as well)

**Comment by JosXa** [comment]
Drag & Drop would be an absolute game changer. 90% of the time when I think "wow, this chat could really go into this or that folder" I am **way** too lazy to make what feels like 30 clicks just to get it there. Drag and drop would simplify this by a ton!

**Comment by RememberTheAir** [comment]
Just as a side note, when you are in your "all" main folder, the android app offers an option to select one+ chats and add them to a folder (without having to enter your folder's settings). Drag & drop (or an context menu option) from the main chats list would be a consistent UX with the Android app

**Comment by BTCAlchemist** [comment]
I also request **a feature the allows the user to right-click on a chat group, then have an option add it to a folder.** This would save users much time. Currently, when a user wants to add a chat group to a folder, he must click on the folder, click edit folder, click add chats, then find the chat group and add it. This takes time and interrupts the user flow.

In addition, **a feature to drag and drop chats to folders would be helpful** (see [7463](https://github.com/telegramdesktop/tdesktop/issues/7463)).

**Comment by kass-kass** [comment]
All amazing suggestions, hopefully will see this happen. Like count suggests it's a bunch of much needed improvements.

**Comment by gromov-io** [comment]
I tearfully ask..

Drag-drop chats to folders (Linux/Win)
Ability to set any default folder (Instead of "all chats"), and drag and drop "all chats" to any location

**Comment by mazunki** [comment]
+1 for Drag & Drop contacts/groups into folders.

I don't care much about reordering folders, but I would really want to **change which folder is the default one**.
I often press "back" or "escape" out of habit, and 90% of the reason I use folders is to avoid having to see all the groups/random people at all times, only those I feel are important. No, I don't want to archive these groups either, as I use them more often than that.

**Comment by Aokromes** [comment]
meta issues are bad, some of the requests here are part of other issues, if some feature lacks individual issue open a new issue.
