### ISSUE TITLE
Sometimes voice messages are not played

### ISSUE THREAD

**Issue by ivan-tretyak** [telegramdesktop/tdesktop#7501]
### Steps to reproduce
1. Open Telegram Desktop.
2. Open a chat room where there are people with a native client under the Mac OS.
3. Start listening to voice messages, some of them will not play.

### Expected behaviour
It's a pleasure to listen to all the voice messages.

### Actual behaviour
By clicking on the button, nothing happens.

### Configuration
OS: Fedora 32.

**Version of Telegram Desktop:**
telegram-desktop-1.9.21-4.fc32.x86_64 also this bug sometimes happening on official binary from site (I can try this on binary 1.9.21)

[telegram.log](https://github.com/telegramdesktop/tdesktop/files/4402308/telegram.log)

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/6710 ?

**Comment by ivan-tretyak** [comment]
Looks like it, but I have a different version and OS. It's more like  https://github.com/telegramdesktop/tdesktop/issues/7498
