### ISSUE TITLE
[Feature Request] Linux Arm build for mobile/glib

### ISSUE THREAD

**Issue by yarbelk** [telegramdesktop/tdesktop#7502]
### New Build Target
Not really a problem, just a missing build target

### Describe the solution you'd like

Arm Debian build targeting PureOS and Debian (with phosh as extra shiny, but thats a stretch)
It would also be nice to have a flatpak

### Describe alternatives you've considered

Alpine linux (PostmarketOS); but that would probably require tooling and library changes.

### Additional context

With the PinePhone, Librem 5 and the uptick in development of mobile friendly linux, it would be nice to have a arm build

**Comment by Aokromes** [comment]
snap?

**Comment by ilya-fedin** [comment]
> It would also be nice to have a flatpak

Emm
![image](https://user-images.githubusercontent.com/17829319/77944973-5f2f4c80-72af-11ea-8bb0-e047e6e8835b.png)

**Comment by ilya-fedin** [comment]
#1924
