### ISSUE TITLE
Night Mode doesn't adapted to folder sidebar

### ISSUE THREAD

**Issue by Konano** [telegramdesktop/tdesktop#7503]
### Expected behaviour
When open Night Mode, the folder sidebar background color should be changed.

### Actual behaviour
The folder sidebar background color is same as Day Mode.
![image](https://user-images.githubusercontent.com/22500116/77919768-2e134400-72d0-11ea-8b16-671c6220dbc0.png)  ![image](https://user-images.githubusercontent.com/22500116/77920299-e50fbf80-72d0-11ea-9cd8-19cc124f73b7.png)

### Configuration
**Operating system:**
Windows
**Version of Telegram Desktop:**
1.9.22 beta
**Used theme**:
Custom Theme: https://t.me/desktopThemes/295

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/7489

**Comment by Konano** [comment]
> #7489

I think the problem is caused by Custom Theme.
