### ISSUE TITLE
IOS Application crashes

### ISSUE THREAD

**Issue by 550550** [telegramdesktop/tdesktop#7505]
### Steps to reproduce
1. Install the update of 2020-03-30.
2. Try run the app - no success
3. Push notifications works fine
4. Reboot the device and repeat 2-3, the same result
5. Remove the app, install again - no push, no success

### Expected behaviour
Keep working after update

### Actual behaviour
White screen on app startup, desappearing at next second

### Configuration
on IOS 10.3.4

Latest update of 2020-03-30.

**Comment by RememberTheAir** [comment]
Wrong place. Report the issue to the in-app support or to [@tgiostests](https://t.me/tgiostests)
