### ISSUE TITLE
[Feature Request] Add tabs for folders (or subfolders)

### ISSUE THREAD

**Issue by Xambey** [telegramdesktop/tdesktop#7506]
### Is your feature request related to a problem?
#1107 

### Describe the solution you'd like
Add tabs for folders

### Describe alternatives you've considered
Add subfolders

### Additional context
![image](https://user-images.githubusercontent.com/17352479/77922563-e11c7700-72a9-11ea-9cf7-0e00a80c26da.png)

**Comment by RememberTheAir** [comment]
What's wrong with the sidebar?

**Comment by Xambey** [comment]
@RememberTheAir I have 100500 chats with various people, in various organizations. I agree that folders are cool, but as for me it’s not enough

**Comment by RememberTheAir** [comment]
I don't see how moving the sidebar above the chats list helps. Anyway, subfolders are not supported by the API so you should bring that to the in-app support or to [Twitter](https://twitter.com/telegram). Tdesktop can't do much if the API doesn't offer this feature

**Comment by Xambey** [comment]
@RememberTheAir I don’t mean moving the sidebar, I suggest just adding more additional filtering in the folders.

**Comment by RememberTheAir** [comment]
@Xambey ah, I see. Anyway, as I said, this need further API support and also they should figure out a good UI for mobile apps since, well... tabs are already used for folders there

**Comment by aiiskoplusaiist** [comment]
For me, the sidebar is a deviation from the design that both the mobile and Mac telegram clients are using: tabs. Without the option to hide the sidebar, the new minimum-width of the application is now larger and everyone is forced to live with the **huge** dark bar that is an insane waste of space. 

The folders feature should have _really_ been implemented using tabs, like every other client. The addition of this un-hidable sidebar has ruined my day. To live with it for the moment, I'm literally forced to drag half of the application off of the edge of my screen to hide it.

**Comment by Aokromes** [comment]
such feature belongs to https://bugs.telegram.org/
