### ISSUE TITLE
[Feature Request] Add the ability to mark a folder as read/unread

### ISSUE THREAD

**Issue by Xambey** [telegramdesktop/tdesktop#7507]
### Describe the solution you'd like
Add the ability to mark a folder as read/unread

### Describe alternatives you've considered
no

### Additional context
![image](https://user-images.githubusercontent.com/17352479/77923018-7e77ab00-72aa-11ea-8570-c335fd41b9c7.png)

**Comment by Xambey** [comment]
@john-preston why closed?

**Comment by john-preston** [comment]
@Xambey There will be a context menu on folders starting from today's release.

**Comment by Xambey** [comment]
> @Xambey There will be a context menu on folders starting from today's release.

Cool, thanks
