### ISSUE TITLE
CTRL+SHIFT+NUMBER doesn't work when using numpad

### ISSUE THREAD

**Issue by RememberTheAir** [telegramdesktop/tdesktop#7508]
### Steps to reproduce
1. have some folders
2. use the keyboard shortcut CTRL+SHIFT+any number (up to 9)

### Expected behaviour
The keyboard shortcut should let you jump to some specific folder based on the number you used

### Actual behaviour
The keyboard shortcut seems to ignore numpad keys. It correctly works with the numbers row above the qwerty keyboard

### Configuration
**Operating system:** Windows 10, Italian keyboard layout

**Version of Telegram Desktop:** 2.0.0

**Comment by 23rd** [comment]
I think it can be closed since `Ctrl+Shift+#` was removed.

**Comment by RememberTheAir** [comment]
Uh-oh. Okay. The relevant one becomes #7551 now
