### ISSUE TITLE
ability to schedule a message

### ISSUE THREAD

**Issue by zaxebo1** [telegramdesktop/tdesktop#751]
in gliph messenger, we can schedule a message to be send at a particular time in future.
Please implement it in telegram's TDesktop too.
This scheduling feature is very useful for scheduling a message to be sent on somebody's birthday etc

**Comment by rutja76** [comment]
+1

**Comment by auchri** [comment]
No api

**Comment by nazar2sfive** [comment]
yes please add this feature
