### ISSUE TITLE
Chinese font display aberrant

### ISSUE THREAD

**Issue by ygcaicn** [telegramdesktop/tdesktop#7510]
### Steps to reproduce
1. When i use beta version 1.9.22, all is well include the Chinese font display.
![image](https://user-images.githubusercontent.com/17684070/77929304-15a92680-72dc-11ea-8da3-b149280cd67b.png)

2. After upgrade to 2.0

![image](https://user-images.githubusercontent.com/17684070/77929982-de874500-72dc-11ea-8e41-56b536128c98.png)

I tyied to install all this fonts in <https://github.com/Sea-n/tdesktop-lib_ui/tree/master/fonts>, but can't resolve this problem.

### Configuration
**Operating system:**
Ubuntu 20.04 dev

**Version of Telegram Desktop:**
2.0

**Used theme**:

<details><summary><b>Logs</b>:</summary>

(base) jachin@hp-pavilion-laptop:~$ journalctl -f | grep tele
Mar 30 23:21:40 hp-pavilion-laptop telegramdesktop.desktop[66324]: error: : cannot open
Mar 30 23:21:40 hp-pavilion-laptop telegramdesktop.desktop[66324]: error: : cannot open
Mar 30 23:21:40 hp-pavilion-laptop telegramdesktop.desktop[66324]: error: : cannot open
Mar 30 23:21:46 hp-pavilion-laptop telegramdesktop.desktop[66324]:   OpenType support missing for "DAOpenSansRegular", script 11
Mar 30 23:21:48 hp-pavilion-laptop telegramdesktop.desktop[66324]:   OpenType support missing for "DAOpenSansSemibold", script 19
Mar 30 23:21:51 hp-pavilion-laptop telegramdesktop.desktop[66324]:   OpenType support missing for "DAOpenSansSemibold", script 12
Mar 30 23:22:06 hp-pavilion-laptop telegramdesktop.desktop[66324]:   OpenType support missing for "DAOpenSansSemibold", script 18
Mar 30 23:22:06 hp-pavilion-laptop telegramdesktop.desktop[66324]:   OpenType support missing for "hakuyoxingshu7000", script 18
Mar 30 23:22:15 hp-pavilion-laptop telegramdesktop.desktop[66324]:   OpenType support missing for "DAOpenSansSemibold", script 11

</details>

**Comment by ilya-fedin** [comment]
#5172

**Comment by DigitalPig** [comment]
I can confirm the same issue happens on my Telegram 2.0 today too.
