### ISSUE TITLE
[Feature Request] Integrate with the Windows People Bar

### ISSUE THREAD

**Issue by ktowen** [telegramdesktop/tdesktop#7511]
### Describe the solution you'd like
Windows have this people bar that allows to write your contacts and pin it to your taskbar. It would be really useful to integrate telegram with this.
![1](https://user-images.githubusercontent.com/17689932/77931016-9aaf2400-7279-11ea-9eca-d87f6fb77d06.png)

### Additional context
![2](https://user-images.githubusercontent.com/17689932/77930788-4efc7a80-7279-11ea-8742-1ea99feb704d.png)

**Comment by Aokromes** [comment]
https://www.pcworld.com/article/3453719/microsoft-plans-to-kill-off-windows-10s-my-people-app.html
i don't think it's worth
