### ISSUE TITLE
Crash when unarchive a pinned chat in folders

### ISSUE THREAD

**Issue by Sepehrtooz** [telegramdesktop/tdesktop#7512]
### Steps to reproduce
1. Right click on pinned chat in a folder
2. Select unarchive chat

### Expected behaviour
unarchive chat

### Actual behaviour
tdesktop crashes

### Configuration
**Operating system: Win7 32 Bit**

**Version of Telegram Desktop: 2.0**

**Used theme**:

<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by Sepehrtooz** [comment]
In addition when I archive a pinned chat in folder, it can't be archived and unpinned from folder

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/commit/2f7563767dc7214ec3c9a4d0c4d4b50e62c5927f
