### ISSUE TITLE
Problem counting the number of unread chats in archived chats

### ISSUE THREAD

**Issue by Sepehrtooz** [telegramdesktop/tdesktop#7514]
![Capture](https://user-images.githubusercontent.com/55192376/77935493-b856aa80-72c6-11ea-9ed8-bc27eebb5ae3.PNG)
When archived chats is collapse, one shows less than unread chats

**Comment by devgyn** [comment]
Same problem here using new feature "Folders". 
I have hidden the archive chat on my mobile client
![bug-7514](https://user-images.githubusercontent.com/8210737/77946107-32bc0600-7298-11ea-8e5f-900c365ee2c1.png)

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/6100
