### ISSUE TITLE
Bengali font is not rendering correctly after updating to 2.0

### ISSUE THREAD

**Issue by al-shakib** [telegramdesktop/tdesktop#7516]
### Steps to reproduce
1. Update Telegram Desktop to 2.0
2. Open Telegram Desktop
3. Write any Bengali text in the message box.

### Expected behaviour
Correct Bengali font/text like the screen shot bellow.
![Screenshot of 1.9.x](https://user-images.githubusercontent.com/13618519/77940938-391fa180-72db-11ea-93aa-cc0f367f8255.png)
_Screen shot of 1.9.x_

### Actual behaviour
Fonts are broken down like the screen shot bellow.
![Screenshot of 2.0](https://user-images.githubusercontent.com/13618519/77941073-65d3b900-72db-11ea-98a8-7a25b9897ccf.png)
_Screen shot of 2.0_

### Configuration
**Operating system:** Fedora 31 (Workstation Edition) x86_64

**Version of Telegram Desktop:** 2.0

**Used theme**: Classic

**Comment by ilya-fedin** [comment]
#5172
