### ISSUE TITLE
[Feature Request] Hide chat sorted nito folders from the All Chats list

### ISSUE THREAD

**Issue by sprite-1** [telegramdesktop/tdesktop#7517]
### Is your feature request related to a problem?
Not necesarily a problem.

### Describe the solution you'd like
Have there be an option so the chats that are already sorted into folders do not show up in All Chats.

### Describe alternatives you've considered
I archive the chats right now but that is very unmaintainable and my actual archived chats are now unorganized mess.

### Additional context
None

**Comment by norlin** [comment]
As a workaround, you can archive a chat, so it will not be shown in the main list but still shown in folders.

**Comment by sprite-1** [comment]
> As a workaround, you can archive a chat, so it will not be shown in the main list but still shown in folders.

That's exactly what I wrote above

**Comment by Aokromes** [comment]
i think this must be api.

**Comment by Sergey1011010** [comment]
what do you mean by "this must be api"?

**Comment by reallyuniquename** [comment]
I am going to copypaste my suggestion from #7528.

>Completely unfiltered "All chats" feed makes sense and obviously should stay.

>What I suggest is to add another inclusion filter for folders (similar to Muted, Archived, etc) that would select only orphaned chats and groups that are not assigned to any folder.

@Sergey1011010 
It means it should be supported by server first.

**Comment by Sergey1011010** [comment]
@reallyuniquename, well, yes, it's better to do this on server, but it can be done on client only as well :)

**Comment by sprite-1** [comment]
> It means it should be supported by server first.

I think it would work simply as a local flag to just hide the menu entry. I don't mind it not being synced across devices

**Comment by leonty** [comment]
This feature would be great! Because those chats that are unsorted (not in any other folder) I have to search in "All chats" mess of tens other chats. And there's no possibility to create sort of "unsorted" folder because of a lack of an appropriate filter (#7528 would help, but it's closed... why?).

**Comment by ilya-fedin** [comment]
#8326 can replace this I guess

**Comment by reallyuniquename** [comment]
Yes, not staled.

**Comment by krelly** [comment]
I find current behavior very confusing - currently, every time I add chat to the folder, I also need to archive it so it won't appear in the All chats section.

**Comment by Aokromes** [comment]
such feature belongs to https://bugs.telegram.org/
