### ISSUE TITLE
[Feature Request] Hide chat folders icons if the folder name is short / 1-symbol / emoji

### ISSUE THREAD

**Issue by norlin** [telegramdesktop/tdesktop#7518]
![image](https://user-images.githubusercontent.com/370803/77949017-f5269f80-72ce-11ea-9ef5-94928b889d67.png)

**Comment by DevAlone** [comment]
Even better would be to add the ability to choose the icon.

**Comment by Sepehrtooz** [comment]
Please add a Movie icon for folders

**Comment by chall3ng3r** [comment]
And set the emoji as folder icon.

**Comment by Sepehrtooz** [comment]
> And set the emoji as folder icon.

Big emoji is better
