### ISSUE TITLE
[Feature Request] Resumable export process

### ISSUE THREAD

**Issue by yfdyh000** [telegramdesktop/tdesktop#7520]
### Is your feature request related to a problem?
If an export is slow but I have to shut down the program or computer, it is a difficult choice.

### Describe the solution you'd like
Automatic resumable, or at least a fast basis.

### Describe alternatives you've considered
Report the dates that have been exported and provide a quick link to resume.

**Comment by hbh7** [comment]
Nope Mr. Bot it's just that the maintainers haven't fixed it yet... Still a concern, we didn't forget.
