### ISSUE TITLE
[Feature Request] Allow parallel exports

### ISSUE THREAD

**Issue by yfdyh000** [telegramdesktop/tdesktop#7521]
### Is your feature request related to a problem?
If you want to export multiple chats but they take a long time, it is difficult to remember and operate.

### Describe the solution you'd like
Queue or parallel multiple export tasks, and recoverable is valuable (#7520).

### Describe alternatives you've considered
None.

**Comment by hbh7** [comment]
Nope Mr. Bot it's just that the maintainers haven't fixed it yet... Still a concern, we didn't forget.
