### ISSUE TITLE
Bring back native notifications

### ISSUE THREAD

**Issue by mssdvd** [telegramdesktop/tdesktop#7523]
### Steps to reproduce
1. Update the app

### Expected behaviour
The native notification is still an option.

### Actual behaviour
I'd like to use the native notification system (mako) because the telegram ones doesn't integrate well with system (they are rendered as tiled window)

### Configuration
**Operating system:** Arch Linux Sway-git

**Version of Telegram Desktop:** 2

**Comment by mssdvd** [comment]
My fault, I opened Telegram without a running notification daemon

**Comment by vmorenomarin** [comment]
> My fault, I opened Telegram without a running notification daemon

Hi. How is that? I cannot see the  native notification option on Linux, Plasma 5.18.4. Thanks.

**Comment by mssdvd** [comment]
Maybe Telegram checks if there I  running notification daemon. And maybe
Plasma starts it on demand.


Il dom 5 apr 2020, 16:42 Víctor Moreno Marín <notifications@github.com> ha
scritto:
