### ISSUE TITLE
[Feature Request] Status messages

### ISSUE THREAD

**Issue by Hezkore** [telegramdesktop/tdesktop#7524]
I can't imagine I'm the first person to bring this up, but I'd really like some sort of status message.

It seems like the second I start a fullscreen application I'm bombarded with messages.
This could easily be solved if Telegram just said "Busy" any time there's a fullscreen app running, or when a user specified app was running, instead of saying "Last Seen" or "Online".
Perhaps the user should even be able to specify the message for the app.
For example if I play Half-Life: Alyx I could have it say "Busy", or "Playing `<App Title>`" or a custom title, like "Inside virtual reality!".

I'd also like to suggest some sort of "Slow mode" for when you're in "Busy" mode.
For example, any time I'm gaming I might only allow people to send me one message every minute, or whatever you set it to.
With a quick notice that "`<Name> is currently busy`".

Once again; I'm sorry if this has been brought up already, I couldn't find a related issue.

**Comment by slondr** [comment]
It sounds like you have very nosy friends

**Comment by vitya-ne** [comment]
I agree with @Hezkore, it is a good idea

**Comment by Hezkore** [comment]
Maybe one day. 🤷‍♂️

**Comment by slondr** [comment]
Indeed
