### ISSUE TITLE
Awful display of Persian font

### ISSUE THREAD

**Issue by H4medRostami** [telegramdesktop/tdesktop#7525]
After update to version 2.0 :

![Screenshot from 2020-03-31 05-40-20](https://user-images.githubusercontent.com/7020431/77976493-663b7680-7312-11ea-839f-9c86579492e2.png)

OS : Debian Buster 10
Installation method : Telegram official website [directly via Tarball]

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/5172

**Comment by H4medRostami** [comment]
well , to improve this issue you should find The master configuration file - usually /etc/fonts/fonts.conf  and copy its content to telegram font config file in :
~/.local/share/TelegramDesktop/tdata/fc-custom-1.conf
