### ISSUE TITLE
Folders panel styling bug

### ISSUE THREAD

**Issue by MaGaroo** [telegramdesktop/tdesktop#7526]
There's a styling(?!) bug in my folders panel. As you can see in the following image, the `ADD` button has covered a part of folder description.

Also I think it shouldn't show both translated and original text for this folder. (I'm not sure either it's about this project or the original data in Telegram server.)

![Screenshot from 2020-03-31 08-10-14](https://user-images.githubusercontent.com/16112582/77984662-76118580-7327-11ea-8843-9d793fb05e34.png)

### Configuration
**OS:**
Ubuntu 18.04
**Telegram Desktop Version:**
2.0
**Language:**
Persian

**Comment by xmha97** [comment]
Yes, There is this bug :(
![image](https://user-images.githubusercontent.com/23485114/78074516-1ca56700-73b8-11ea-94c9-fb7050aea83d.png)

**Comment by Aokromes** [comment]
translation needs to be aproved to get the english message removed.
