### ISSUE TITLE
[Feature Request] [Folders] Add a filter to select chats not assigned to any folder

### ISSUE THREAD

**Issue by reallyuniquename** [telegramdesktop/tdesktop#7528]
I think many users expected that adding chat to a folder would hide it from the main "All chats" feed.

Completely unfiltered "All chats" feed makes sense and obviously should stay.

What I suggest is to add another inclusion filter for folders (similar to Muted, Archived, etc) that would select only orphaned chats and groups that are not assigned to any folder.

This way users would be able to use folders as sorted archive AND have a clean feed without noise.

**Comment by pavanchaudhari** [comment]
> I think many users expected that adding chat to a folder would hide it from the main "All chats" feed.
> 
> Completely unfiltered "All chats" feed makes sense and obviously should stay.
> 
> What I suggest is to add another inclusion filter for folders (similar to Muted, Archived, etc) that would select only orphaned chats and groups that are not assigned to any folder.
> 
> This way users would be able to use folders as sorted archive AND have a clean feed without noise.

Came here to request same +1.

Title could be more direct.
"Hide chat from main window, once added to a folder"

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/7517

**Comment by DevAlone** [comment]
@Aokromes actually it's not the same

**Comment by leonty** [comment]
> @Aokromes actually it's not the same

true
