### ISSUE TITLE
Auto-scroll stops working when window loses focus.

### ISSUE THREAD

**Issue by tajonny07** [telegramdesktop/tdesktop#753]
As the titles says, my window isn't auto-scrolling correctly. As soon as my window loses focus, it stops scrolling as people continue to talk. Then every time I click back, I have to either scroll down a bunch of hold page down. 

I've consulted with multiple people and this issue is happening for everyone I've talked to.

**Comment by sander85** [comment]
AFAIK it's not a bug, it's a feature. What's the point to auto-scroll? So you would have to scroll back up to read what you were missing when the window was inactive?

**Comment by tajonny07** [comment]
I see where you're coming from, and with just 1-on-1 chats that would make sense, but I'm in a group chat with 20+ people and when I come back to my PC there may be 200-300+ new messages, so in this case I'd rather not read through them all but just have it auto-scroll. 

Is it possible for it to be enabled/disabled? If not, would you consider adding this feature? I know a bunch of people who would use it. :)

**Comment by ajnieminen** [comment]
This is really annoying. And this seems to be completely random (I have not figuret it out yet). Sometimes it scrolls and sometime it doesn't.

**Comment by ajnieminen** [comment]
Received images seems to have something to do with this issues when window is not in focus.

**Comment by JustERR** [comment]
Also on Windows if I scroll public chat's text using mouse wheel while Telegram window is out of focus then unread count wouldn't be changed and the next received message will make the text "jump" to the last "read" position.

**Comment by husolant** [comment]
I have TG on a second screen and if there are new messages it just displays "x unread messages" at the bottom of the chat. I can´t read what´s been written until ich click (focus) the window and manually scroll down which I think is unfortunate.
I would expect it to autoscroll at least until the chat is full with new messages so I can keep up with the conversation while doing something else on the main screen.
If it is considered a feature for single screen users, a optional setting would be an alternative.

**Comment by ComodoHacker** [comment]
Please add an option to autoscroll regardless of focus. There are scenarios where last messages are much more important than unread history:

- game chats
- chats coordinating ongoing events
- chats with text games
- data feeds

Such option could really help with multitasking and productivity.

**Comment by ilyag-x** [comment]
Scenario: You have dual monitors -- one has whatever it is you're actively engaged in (examples: a web browser, a game, a work-related project), and the other has Telegram. This scenario makes Telegram unusable, as you are unable to keep up with the latest posts in a conversation just by looking over at that window.

It's really baffling that the developers are so closed-minded as to not even comprehend that there are so many perfectly valid use-cases for a chat program where you DO want it to auto-scroll as the new messages arrive. Any other chat platform that has ever existed worked exactly like this. And now to hear from developers, "Why would you want that?" What rubbish.

**Comment by husolant** [comment]
Issue was opened in 2015 and multiple people have stated why this is an important feature. Should still be considered

**Comment by cuervelo** [comment]
Issue was opened in 2015 and multiple people have stated why this is an important feature. If people still needing this after 5 years, FIVE YEARS people!, it should still be considered and fixed adding an option to check or uncheck this feature as needed. I'm not a programmer and I'm not able to help on the development of it but I need this as much as all other guys are talking about around this since 2015.

**Comment by weblabio** [comment]
+1 
I really miss this option in order to follow the conversation without switching to the window

**Comment by timangus** [comment]
This is super annoying behaviour for large groups where you don't necessarily want to read every message. It should definitely be an option to disable it.

**Comment by Jmatt1408** [comment]
Another use case is playing a game that doesn't support borderless by having to click out whenever the messages stack

**Comment by Corosauce** [comment]
How is this not a feature yet, do telegram devs hate people with multiple monitors?

Are there alternative chat integration solutions that I can wire telegram protocal into to get around this? This not being a feature is just silly.

**Comment by flolege** [comment]
Please introduce this feature asap. the current behavior is really annoying!

**Comment by DDR0** [comment]
This is my no.1 least favourite thing about Telegram. I've got a window open keeping an eye on the group chat, and it just... stops scrolling unless I give it some attention. It's a needy little thing, so I usually just end up ignoring chats on it. I just want to keep an eye on how things are (d)evolving, I don't want to see every darn message those idiots send.

Especially because stickers are large, making the problem worse as I sometimes have to poke the window every few **seconds** to get it to keep up.

This works fine in IRC. Works fine in Discord. Works fine in Signal. Please remove the forced scroll pausing malfeature.

**Comment by nuclight** [comment]
Hey huys, you've broke work for many people including me who expect to not readed messages to stay such! Now we open #16188

**Comment by john-preston** [comment]
Ok, I'll revert for now. Maybe an option can be added later.

**Comment by LuisCRSousa** [comment]
This is the worst "feature" about telegram...

**Comment by erraineon** [comment]
i wrote a utility a while back to enable this behavior when needed https://github.com/erraineon/telegram-scroll

enjoy

**Comment by LuisCRSousa** [comment]
> i wrote a utility a while back to enable this behavior when needed https://github.com/erraineon/telegram-scroll
> 
> enjoy

You’re a genius! Thanks a lot

**Comment by DDR0** [comment]
That looks great! I'll have to get it working on Linux here. ☺

**Comment by RememberTheAir** [comment]
Don't know it it has already been mentioned but [kotatogram](https://github.com/kotatogram/kotatogram-desktop) (a fork of this app) has an option to keep scrolling when the window loses focus

**Comment by yusufpraditya** [comment]
> Don't know it it has already been mentioned but [kotatogram](https://github.com/kotatogram/kotatogram-desktop) (a fork of this app) has an option to keep scrolling when the window loses focus

how to enable this setting? can't find it

**Comment by kamild1996** [comment]
> how to enable this setting? can't find it

Settings > Kotatogram Settings > Unfocused auto-scroll

**Comment by DDR0** [comment]
Oh, thank you. This is perfect!

**Comment by taigah** [comment]
7 years and we still have to keep scrolling by hand all the time

**Comment by kamild1996** [comment]
> 7 years and we still have to keep scrolling by hand all the time

You can wait another 7 years, or just use alt clients like kotatogram or unigram 😊

**Comment by KodyWiremane** [comment]
Would appreciate optional unconditional autoscrolling so I could watch my friends chatting on the second monitor while I'm working on the main one^^

**Comment by 23rd** [comment]
A new related experimental option was presented in 3.7.6 version.

**Comment by n0bcoder** [comment]
i wrote autohotkey script to fix this issue
#IfWinActive, ahk_exe Telegram.exe
F8::MsgBox Active, F10 to run auto scroll, F9 to pause and resume
F9::pause
F10::
	Loop,
	{
	Send, {Pgdn}
	Sleep, 200 ; sleep 2 secs
	}
