### ISSUE TITLE
Lagging keyboard input on Linux

### ISSUE THREAD

**Issue by makkarpov** [telegramdesktop/tdesktop#7530]
### Steps to reproduce
1. Install tdesktop 2.0 on Fedora 29
2. Start typing something on keyboard

### Expected behaviour
1. Input should appear quickly all the time.

### Actual behaviour
1. Sometimes you have a 'lag spike': ~0.5-1 second delay before your input appears. But most of the time input appears with acceptable delay.
2. Issue didn't existed on version 1.8.9 built by RPMFusion
3. Enabling/disabling spellchecker does not affect this issue: in particular, it is still present with disabled spellchecker.

### Configuration
**Operating system:** Fedora 29
**Version of Telegram Desktop:** 2.0
**Used theme**: not relevant, I suppose

**Comment by xvitaly** [comment]
> Operating system: Fedora 29

Fedora 29 is no longer supported due to its EOL. Please upgrade to Fedora 31.

**Comment by ilya-fedin** [comment]
#7425

**Comment by makkarpov** [comment]
Additionally Telegram how sometimes hangs completely.

I will update Fedora distro, but I don't think that it has too much influence on a statically built binary.

**Comment by xvitaly** [comment]
> I will update Fedora distro, but I don't think that it has significant influence on a keyboard freezes, since Telegram is almost statically built.

Latest version 2.0.1 works fine with native D-Bus notifications.

**Comment by ilya-fedin** [comment]
> but I don't think that it has significant influence on a keyboard freezes

Check #7425 and try to do as well.

**Comment by makkarpov** [comment]
I had updated to F31, notifications are working fine now.

Chat input is still broken. Ticket #7425 does not help very much, since it is about Intel drivers, while I have nVidia card with proprietary drivers installed.

```
kmod-nvidia-5.5.15-200.fc31.x86_64-440.64-1.fc31.x86_64
xorg-x11-drv-nvidia-440.64-2.fc31.x86_64
nvidia-settings-440.64-1.fc31.x86_64
xorg-x11-drv-nvidia-kmodsrc-440.64-2.fc31.x86_64
akmod-nvidia-440.64-1.fc31.x86_64
xorg-x11-drv-nvidia-cuda-libs-440.64-2.fc31.x86_64
xorg-x11-drv-nvidia-libs-440.64-2.fc31.x86_64
```

**Comment by ilya-fedin** [comment]
> while I have nVidia card with proprietary drivers installed

Check with nomodeset

**Comment by xvitaly** [comment]
> Chat input is still broken

Can you try version from RPM Fusion? I use NVIDIA drivers on Fedora 32 too.

**Comment by makkarpov** [comment]
> Can you try version from RPM Fusion? I use NVIDIA drivers on Fedora 32 too.

Yeah, it's already from RPM Fusion. I will reboot to `nomodeset` later and report the results.

**Comment by xvitaly** [comment]
> Yeah, it's already from RPM Fusion.

Can you show result of the following commands:

```bash
echo $XDG_SESSION_TYPE
```

```bash
ps ax | grep [t]elegram
```

**Comment by makkarpov** [comment]
```
[makkarpov@desktop ~]$ echo $XDG_SESSION_TYPE
x11
[makkarpov@desktop ~]$ ps ax | grep [t]elegram
  10176 ?        Sl     6:53 /usr/bin/telegram-desktop --
```

**Comment by ilya-fedin** [comment]
`env | grep QT` and testing which exactly version introduced the issue would be also helpful

**Comment by makkarpov** [comment]
```
QT_IM_MODULE=xim
QT_AUTO_SCREEN_SCALE_FACTOR=0
QT_SCALE_FACTOR=1
```
Main desktop environment is MATE, by the way.

**Comment by ilya-fedin** [comment]
1. Completely quit from tdesktop
2. `env -u QT_IM_MODULE -u QT_AUTO_SCREEN_SCALE_FACTOR -u QT_SCALE_FACTOR telegram-desktop`

**Comment by ChadBailey** [comment]
For what it's worth, this appears to be isolated to Fedora. Not experiencing these symptoms on Mint (and this laptop is very slow)

```
chad@stretchypants:~$ neofetch
MMMMMMMMMMMMMMMMMMMMMMMMMmds+.        chad@stretchypants 
MMm----::-://////////////oymNMd+`     ------------------ 
MMd      /++                -sNMd:    OS: Linux Mint 19.3 Tricia x86_64 
MMNso/`  dMM    `.::-. .-::.` .hMN:   Host: X551CA 1.0 
ddddMMh  dMM   :hNMNMNhNMNMNh: `NMm   Kernel: 4.15.0-91-generic 
    NMm  dMM  .NMN/-+MMM+-/NMN` dMM   Uptime: 6 days, 3 hours, 9 mins 
    NMm  dMM  -MMm  `MMM   dMM. dMM   Packages: 2469 
    NMm  dMM  -MMm  `MMM   dMM. dMM   Shell: bash 4.4.20 
    NMm  dMM  .mmd  `mmm   yMM. dMM   Resolution: 1366x768 
    NMm  dMM`  ..`   ...   ydm. dMM   DE: Cinnamon 4.4.8 
    hMM- +MMd/-------...-:sdds  dMM   WM: Mutter (Muffin) 
    -NMm- :hNMNNNmdddddddddy/`  dMM   WM Theme: Mint-Y-Dark-Purple (Mint-Y-Dark 
     -dMNs-``-::::-------.``    dMM   Theme: Mint-Y-Dark-Purple [GTK2/3] 
      `/dMNmy+/:-------------:/yMMM   Icons: Mint-Y-Purple [GTK2/3] 
         ./ydNMMMMMMMMMMMMMMMMMMMMM   Terminal: gnome-terminal 
            .MMMMMMMMMMMMMMMMMMM      CPU: Intel i3-3217U (4) @ 1.800GHz 
                                      GPU: Intel Ivybridge Mobile 
                                      Memory: 2931MiB / 5846MiB 

```

**Comment by makkarpov** [comment]
> env -u QT_IM_MODULE -u QT_AUTO_SCREEN_SCALE_FACTOR -u QT_SCALE_FACTOR telegram-desktop

I'm not completely sure yet, but it feels like issue is still present

**Comment by ilya-fedin** [comment]
Well, then will waiting for nomodeset

**Comment by makkarpov** [comment]
```
$ ps ax | grep [t]elegram
   6259 ?        Sl     0:04 telegram-desktop
```

```
$ cat /proc/6259/environ | tr '\0' '\n'
IMSETTINGS_INTEGRATE_DESKTOP=yes
SHELL=/bin/bash
XDG_SESSION_PATH=/org/freedesktop/DisplayManager/Session0
HISTCONTROL=ignoredups
HISTSIZE=1000
HOSTNAME=desktop.karpov.local
XMODIFIERS=@im=none
DESKTOP_SESSION=mate
XDG_SEAT=seat0
PWD=/home/makkarpov
XDG_SESSION_DESKTOP=mate
LOGNAME=makkarpov
XDG_SESSION_TYPE=x11
XAUTHORITY=/run/lightdm/makkarpov/xauthority
SDL_VIDEO_MINIMIZE_ON_FOCUS_LOSS=0
XDG_GREETER_DATA_DIR=/var/lib/lightdm-data/makkarpov
HOME=/home/makkarpov
LANG=ru_RU.UTF-8
XDG_CURRENT_DESKTOP=MATE
XDG_SEAT_PATH=/org/freedesktop/DisplayManager/Seat0
IMSETTINGS_MODULE=X compose table
STEAM_FRAME_FORCE_CLOSE=1
XDG_SESSION_CLASS=user
TERM=dumb
LESSOPEN=||/usr/bin/lesspipe.sh %s
USER=makkarpov
DISPLAY=:0
SHLVL=0
XDG_VTNR=1
XDG_SESSION_ID=2
XDG_RUNTIME_DIR=/run/user/1000
PATH=/home/makkarpov/.local/bin:/home/makkarpov/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/sbin
GDMSESSION=mate
DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus
MAIL=/var/spool/mail/makkarpov
_=/usr/bin/mate-session
MATE_DESKTOP_SESSION_ID=this-is-deprecated
SESSION_MANAGER=local/unix:@/tmp/.ICE-unix/1858,unix/unix:/tmp/.ICE-unix/1858
GTK_OVERLAY_SCROLLING=0
```
```
$ cat /proc/cmdline 
<...> rhgb quiet rd.driver.blacklist=nouveau modprobe.blacklist=nouveau nvidia-drm.modeset=0 nomodeset
```

Issue is still present.

**Comment by ilya-fedin** [comment]
I have no idea

**Comment by ilya-fedin** [comment]
@makkarpov which filesystem are you using?

**Comment by Aokromes** [comment]
better ticket
https://github.com/telegramdesktop/tdesktop/issues/7952
