### ISSUE TITLE
Arabic Font is different and hard to read 

### ISSUE THREAD

**Issue by jawadalkassim** [telegramdesktop/tdesktop#7532]
### Steps to reproduce
1. Update to version  2.0
2.open telegram
3. Arabic Font style is different
### Expected behaviour
Readable font style like in the Version 1.9.21 

### Actual behaviour
Font Style is different and not the default Arabic font style

### Configuration
**Operating system: Linux Ubuntu 19.10

**Version of Telegram Desktop:2.0.1

**Used theme**: Dark

<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by jawadalkassim** [comment]
.

**Comment by jawadalkassim** [comment]
![Screenshot from 2020-03-31 13-23-52](https://user-images.githubusercontent.com/48631694/78021194-550a5e00-7342-11ea-855e-ef74cfcfb748.png)

**Comment by ygcaicn** [comment]
update to 2.0.1 and restart your system, I have solve the problem

**Comment by jawadalkassim** [comment]
Thanks

**Comment by john-preston** [comment]
@jawadalkassim Are you sure you try 2.0.1, not 2.0? I hoped it was fixed in 2.0.1 :(

**Comment by jawadalkassim** [comment]
> @jawadalkassim Are you sure you try 2.0.1, not 2.0? I hoped it was fixed in 2.0.1 :(

Yeah, it was fixed in 2.0.1, I haven't noticed that until I restarted the system,
Thanks for quick responding.
