### ISSUE TITLE
folders and archived chats???

### ISSUE THREAD

**Issue by patrickdrd** [telegramdesktop/tdesktop#7535]
hello,
what happens to archived chats with the new functionality and/or
those of us that use the archiving functionality?

I mean I tried to create a folder and fill it with a mix of archived and un-archived chats/channels and
the result was a mess: 
it was like I lost my archiving functionality at all..

I really don't  know what to do/ I couldn't figure it out,
but I deleted the folder and went back to the previous functionality because I like archiving,
I don't want them all mixed up in one folder

**Comment by Aokromes** [comment]
archived chats access is still there with folders enabled.

**Comment by patrickdrd** [comment]
I know, but I don't want archived chats shown in my newly created folders,
why would I want that?
so, where do that leaves us?

**Comment by Aokromes** [comment]
well, that will very likely will need api support.

**Comment by RadRussianRus** [comment]
@patrickdrd You can add "Archived" chats in folder exceptions.

**Comment by patrickdrd** [comment]
I just did and it doesn't work
