### ISSUE TITLE
Unread Counter lower than 0

### ISSUE THREAD

**Issue by mansouryaacoubi** [telegramdesktop/tdesktop#7537]
### Steps to reproduce
1. Read/Archive Chats

### Expected behaviour
When reading all chats, the unread counter should decrement until 0 is reached.

### Actual behaviour
When reading all chats, the unread counter is decrementing until -1 is reached.  
Counter is reset once Telegram has been restarted.

### Configuration
**Operating system:** Windows 10 Pro _(v10.0.18362.0 [Maj.Min.Bui.Rev])_

**Version of Telegram Desktop:** _2.0_

**Used theme**: _Day (Color: #687B98)_

<details><summary><b>Logs</b>:</summary>

[log.txt](https://github.com/telegramdesktop/tdesktop/files/4409141/log.txt)

![image](https://user-images.githubusercontent.com/6348858/78029000-3024e380-7360-11ea-8753-3082ea0ef99f.png)

</details>

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/6100
