### ISSUE TITLE
[Feature Request] Rename "All chats" folder

### ISSUE THREAD

**Issue by neesti** [telegramdesktop/tdesktop#7539]
Hello.
Please let user to rename "All chats" folder to his/her favorite name. For example I would like to reaneme this folder (All chats) to "همهٔ پیام‌ها" (A Persian name).

Thank you so much.

**Comment by Sergey1011010** [comment]
Your issue would be solved by just translating telegram interface to Persian

**Comment by xmha97** [comment]
Also I have this issue.
