### ISSUE TITLE
[Feature Request] Light style for folder bar

### ISSUE THREAD

**Issue by xmha97** [telegramdesktop/tdesktop#7544]
Hello, Folder bar is dark.

![image](https://user-images.githubusercontent.com/23485114/78075028-021fbd80-73b9-11ea-8fd3-99a865973fd0.png)

Please make the light theme for folder bar

![image](https://user-images.githubusercontent.com/23485114/78074988-f16f4780-73b8-11ea-9d2d-efb170e96f35.png)

**Comment by AliDjango** [comment]
#7460
