### ISSUE TITLE
Don't work spell checker on Windows 10 (1909)

### ISSUE THREAD

**Issue by unioneon** [telegramdesktop/tdesktop#7545]
![image](https://user-images.githubusercontent.com/14049525/78122429-2e255800-7426-11ea-8a98-74c39cdda1c6.png)

![image](https://user-images.githubusercontent.com/14049525/78122479-3c737400-7426-11ea-90ab-83dfca62e97d.png)

**Comment by 23rd** [comment]
If your word is correct, then the `Spelling` item will not be added to the menu.
