### ISSUE TITLE
JPG image is not applicable as chat background

### ISSUE THREAD

**Issue by maxnevans** [telegramdesktop/tdesktop#7548]
### Steps to reproduce
1. Navigate to "Settings"
2. Navigate to "Chat Settings"
3. Scroll to "Chat background" section
4. Click "Choose from file".
5. Select "sea-landscape.jpg"

### Expected behaviour
File explorer modal window "Choose an image" should close. Modal window "Background preview" should appear to apply chat background.

### Actual behaviour
File explorer modal window "Choose an image" should close. Modal window "Background preview" does not appear. "Chat Settings" modal window is active.

### Configuration
**Operating system:** Windows 10 x64 1909 OS Build 18363.752

**Version of Telegram Desktop:** 2.01

**Used theme**: Classic

<details>
<summary>Attachments</summary>

**Problem jpg image:**
![sea-landscape](https://user-images.githubusercontent.com/24874047/78140324-7ea2b280-7432-11ea-89d3-ef0417d21017.jpg)
</details>

**Comment by Aokromes** [comment]
it looks it's to big file.

**Comment by Aokromes** [comment]
generic bug:
https://github.com/telegramdesktop/tdesktop/issues/7598
