### ISSUE TITLE
sticker menu becomes blank

### ISSUE THREAD

**Issue by ahmadalli** [telegramdesktop/tdesktop#755]
this is what I see when I go to Stickers page. I've reinstalled the program but it happened again after awhile.

![image](https://cloud.githubusercontent.com/assets/2167301/7797345/fd4b78fa-02ff-11e5-8a4a-ae8856a12af9.png)

**Comment by auchri** [comment]
Whats your os?

**Comment by ahmadalli** [comment]
Windows 8.1
________________________________

**Comment by Advan721** [comment]
I have the same problem on Mac OS 10.8.5

**Comment by solbjorn** [comment]
Same on Linux (Arch, elementary OS) and Windows (7) builds. Stickers panel becomes blank after first launch of 0.8.17.

**Comment by Eternal-Sina** [comment]
Same problem here on Windows 7 ! There should be an update for fixing this Bug

**Comment by Katzen-Gott** [comment]
@ahmadalli , please re-check on v.0.8.19. Release notes say it should be fixed. And could you please close the issue if it's actually fixed?

**Comment by Advan721** [comment]
Problem was fixed for me in the last update.

**Comment by auchri** [comment]
Fixed with 0.8.21 

Close this please @ahmadalli
