### ISSUE TITLE
Ctrl+number no longer switches between pinned chats but rather between folders

### ISSUE THREAD

**Issue by SleeplessSloth** [telegramdesktop/tdesktop#7551]
### Steps to reproduce
1. Press Ctrl+1 or any other number 

### Expected behaviour
It should focus on the first pinned chat

### Actual behaviour
It focuses on the first folder which is "All chats"

### Configuration
**Operating system:** GNU/Linux
**Version of Telegram Desktop:** `2.0.1`

### My suggestion
Add another way to switch between chats, e.g. Alt+number. Otherwise there's no way to switch between chats without using the mouse which sucks, I try to avoid using the mouse at all costs. Maybe also add more hotkeys, for example, to send a sticker or an emoji only using the keyboard

**Comment by RememberTheAir** [comment]
Same on Windows. CTRL + NUMBER moves across folders and CTRL + SHIFT + NUMBER doesn't work anymore

**Comment by RadRussianRus** [comment]
Alt hotkeys usually works bad on Linux, AFAIK.

**Comment by SleeplessSloth** [comment]
Seems like the behavior was changed in  https://github.com/telegramdesktop/tdesktop/commit/c2ff27793a56241135fde194256a2ebf7bc5ec90 for some reason. I don't think there should be no shortcut to switch between folders but in my opinion switching between individual chats is way more frequent. I suggest to bind individual chats to Ctrl+num and folders to Ctrl+Shift+num, that'd be the best compromise.

**Comment by SonicoXD1** [comment]
> Alt hotkeys usually works bad on Linux, AFAIK.

It doesn't really have to do with Linux, check the keyboard shortcuts page on the wiki: the same shortcuts are used for moving between folders and pinned chats.
I also think Ctrl + num should be used for pinned chats, and Ctrl + Shift + num for folders. Switching between folders with only Ctrl + Shift + ↑ or ↓ is not inconvenient either, as folders are not that many.

**Comment by TiGR** [comment]
Currently you can select any chat, without going through all chats inbetween and resetting unread messages status by pressing first escape and then using arrow keys.

But yeah, [the wiki](https://github.com/telegramdesktop/tdesktop/wiki/Keyboard-Shortcuts) should be fixed in order to remove conflicting hotkeys.

**Comment by SleeplessSloth** [comment]
To be honest, that seems like a regression in my eyes. Previously all I had to do to switch between the first and third chats was Ctrl+1 <-> Ctrl+3, now it's ESC -> down -> down -> enter or ESC -> up -> up -> enter. Do people really switch between folders that often that it's considered to be more important than to switching between chats?
