### ISSUE TITLE
Telegram becomes unusable during large file downloads.

### ISSUE THREAD

**Issue by dsancheznet** [telegramdesktop/tdesktop#7552]
### Steps to reproduce
1. Download a big file
2. UI becomes unresponsive

### Expected behaviour
In previous versions, no matter how many or how large downloads there were, the UI never became unresponsive...

### Actual behaviour
...but since version 2.0.0, this problem happens whenever a big download is started.

### Configuration
elementary OS Linux.

**Version of Telegram Desktop:**
2.0.1

Best regards

**Comment by reallyuniquename** [comment]
UI lock up happens on older versions too.
