### ISSUE TITLE
[Feature Request] Upgrade to ffmpeg-4

### ISSUE THREAD

**Issue by alpham8** [telegramdesktop/tdesktop#7553]
### Is your feature request related to a problem?
Telegram Desktop is one of the last applications which uses ffpmeg-3 on my openSUSE 15.1. For now, I am running both versions of ffmpeg. If Telegram would upgrade to version 4, I can delete the older version.

### Describe the solution you'd like
Upgrade the library usage of ffmpeg to version 4.

### Describe alternatives you've considered
I would then use the web version of Telegram or maybe I consider to start using the Matrix Telegram Bridge client.

### Additional context
```
zypper rm ffmpeg-3
Installierte Pakete werden gelesen...
Paketabhängigkeiten werden aufgelöst...

Die folgenden 3 Pakete werden GELÖSCHT:
  ffmpeg-3 get_iplayer telegram-desktop

3 zu entfernende Pakete.
Nach dem Vorgang werden 41,2 MiB freigegeben.
```
I'm using telegram Desktop version 1.6.7 from this repo: https://software.opensuse.org/download/package?package=telegram-desktop&project=openSUSE%3ALeap%3A15.1

Related to that topic I only found this: https://github.com/telegramdesktop/tdesktop/pull/7348

**Comment by ilya-fedin** [comment]
Ask your package maintainer, no one here can help you.

**Comment by alpham8** [comment]
@ilya-fedin Why not? This seems for me to be an built-in lib into Telegram Desktop, so Telegram Desktop related, isn't it?

**Comment by ilya-fedin** [comment]
> @ilya-fedin Why not? This seems for me to be an built-in lib into Telegram Desktop, so Telegram Desktop related, isn't it?

If this were so, then ffmpeg would be a build-time dependency only

**Comment by alpham8** [comment]
@ilya-fedin What about this? https://github.com/telegramdesktop/tdesktop/tree/dev/Telegram/SourceFiles/ffmpeg

**Comment by ilya-fedin** [comment]
This is source code that uses ffmpeg. ffmpeg version is specified by package maintainer.
ffmpeg is bundled into binaries from github releases, but not in distribution packages, they are linked dinamically.

**Comment by alpham8** [comment]
Package maintainer confirmed that, thank you in advice.
