### ISSUE TITLE
Animated sticker often fails to send

### ISSUE THREAD

**Issue by joshsleeper** [telegramdesktop/tdesktop#7556]
### Steps to reproduce
1. install this sticker pack: https://t.me/addstickers/asdf_stickers
2. attempt to send this sticker in a chat
    ![image](https://user-images.githubusercontent.com/849941/78193392-6a69b000-7448-11ea-8d59-851c0bf6a664.png)

### Expected behaviour

The sticker should send, like any other!

### Actual behaviour

The sticker generally shows up on _my_ client, but with the little clock-looking icon that means it hasn't actually sent. Despite waiting, it never seems to send.

### Extra information

I _think_ I've only seen this behavior with this specific sticker, I've never seen this in the Android version, and if I successfully send the sticker to the same chat _from_ the Android version, Telegram Desktop shows it just fine.

### Configuration
**Operating system:** Windows 10 Pro 1909 (OS Build 18363.752)

**Version of Telegram Desktop:** 2.0.1

**Used theme**: Dark

<details><summary><b>Logs</b>:</summary>
I don't know how to retrieve log.txt
</details>

**Comment by john-preston** [comment]
@joshsleeper I can't reproduce this issue, it sends fine for me.

**Comment by joshsleeper** [comment]
Well drat, that's unfortunate, but thanks for checking so quick.
I promise I'm not making it up! 😆 

Are there any logs from Telegram Desktop that I could grab the next time I see the issue?
It really does happen frequently enough that I'll probably see it again in the next few days.

**Comment by Aokromes** [comment]
this issue is still valid?

**Comment by joshsleeper** [comment]
I'm fine closing it I guess, although it's funny to me that I was seeing it frequently enough to file an issue when I did, but basically haven't seen it since.
good ol' observer problems haha. ¯\\\_(ツ)\_/¯
