### ISSUE TITLE
RDP 4K Resolution - Telegram Desktop issue

### ISSUE THREAD

**Issue by S1AnGeR** [telegramdesktop/tdesktop#7559]
Hello , I have problem with Telegram Desktop , when I working from RDP ( Remote Desktop Access) with my laptop (Dell XPS 13 **with 4k resolution**). 

So , in my work PC (Win10 with resolution 1920x1080) I have installed and launched telegram desktop. And it works fine , but when I access my work pc from my laptop (without relaunch Telegram Desktop) - I have non-scalable view in Telegram, something like this:

### Steps to reproduce
1. Launch Telegram Desktop from PC with 1920x1080 resolution and don't close it.
2. Connect via RDP (Remote Desktop Access) from any device from different resolution ( 4k in my case) and open telegram
3. You have non-scalable Telegram Desktop:
![4K Problem](https://skr.sh/i/020420/16Eg14c1.png)
4. But if you close and launch app again - Telegram Desktop will autoscale it to 4K.
![4K relaunch app](https://skr.sh/i/020420/0UtQCEKY.png)

### Expected behaviour
autoscale Telegram Desktop when connecting via RDP with 4K display without restart app.

### Actual behaviour
Telegram Desktop non-scale when I connect via RDP. 

### Configuration
Windows 10

**Version of Telegram Desktop:**
2.0.1
**Used theme**:
Standart

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/1121
