### ISSUE TITLE
[Feature Request] Secret chat in the desktop client

### ISSUE THREAD

**Issue by ddobrev** [telegramdesktop/tdesktop#7563]
### Is your feature request related to a problem?
It is — your stubborn and senseless refusal to add secret chat to your desktop client.

### Describe the solution you'd like
The possibility to start and accept secret chat on the desktop.

### Describe alternatives you've considered
Not using Telegram.

### Additional context
I am deliberately impolite as many people have already asked politely to absolutely no avail — which means politeness doesn't work with you. Various users have asked [over](https://github.com/telegramdesktop/tdesktop/issues/118) and [over](https://github.com/telegramdesktop/tdesktop/issues/871) again for the second most basic feature (after text messages themselves) in a secure messenger. You have persistently and groundlessly refused and on top locked any discussions about the issue. And what is your reason? Impossible to synchronize across devices? Who do you think would believe this lie? The solution is the simplest of all — simply warn any user starting a secret chat that he wouldn't have it in his other devices. From then on anyone can make their choice. If it's so impossible as you claim, how come the alternative desktop client of https://github.com/overtake/TelegramSwift has it?
If you keep refusing to do this, your users are going to start suspecting you have ulterior motives for leaving their conversations unprotected — such as selling their data. Then we'll see what happens with the large user-base you claim and seem to be so proud of.

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/871

**Comment by ddobrev** [comment]
@Aokromes I've already linked that very same issue and I've made sure to mention it's locked.

**Comment by Aokromes** [comment]
it's still duplicate, having one issue locked and open don't means you must open a new ticket.

**Comment by ddobrev** [comment]
It does if you won't take action on it for years now.

**Comment by RememberTheAir** [comment]
@ddobrev it's useless, opening new issues !won't make them take action. The fact that the secret chats issue is locked clearly means that they have no plans to implement that anytime soon

**Comment by ddobrev** [comment]
@RememberTheAir I don't think it's useless because I believe that if enough users vent their frustration here over and over again, they might finally get it. And they would have had many of these people chosen not to abandon Telegram.

**Comment by RememberTheAir** [comment]
I can guarantee you that a github issue having a few hundreds of likes won't change their mind. Being vocal on twitter would guarantee you better results

**Comment by ddobrev** [comment]
@RememberTheAir it's perfectly possible that you're right but one doesn't preclude the other. 🙂  I don't use Twitter but if it would help, I might as well.
