### ISSUE TITLE
On Linux (Ubuntu/Fedora), Chinese Input doesn't work

### ISSUE THREAD

**Issue by antinucleon** [telegramdesktop/tdesktop#7565]
### Steps to reproduce
1. Install telegram from snap
2. Switch to Chinese input
3. Try to type Chinese

### Expected behaviour
Input will be called, Chinese can be typed

### Actual behaviour
Input is not called, only English chars are imputed 

### Configuration
Ubuntu 20.04 daily build, Fedora 31

**Version of Telegram Desktop:**
https://snapcraft.io/telegram-desktop

**Used theme**:
None

**Comment by yookoala** [comment]
Probably a duplication of #2013.

You mentioned 2 different OS (Ubuntu 20.04 and Fedora 31). Did you tried the snap package on both? Have you tried restarting your machine (because some friends told me that works for them)?

**Comment by yookoala** [comment]
You might want to try the [Flatpak package](https://flathub.org/apps/details/org.telegram.desktop) instead. It works on my Fedora 32 machine.
