### ISSUE TITLE
Build instructions for VS2019 doesnt work now

### ISSUE THREAD

**Issue by 411an** [telegramdesktop/tdesktop#7568]
Build instructions for VS2019 doesnt work now

After last update this instruction https://github.com/telegramdesktop/tdesktop/blob/dev/docs/building-msvc.md doesnt work.

It stops after line

cmake -G "Visual Studio 16 2019" -A Win32 -D LIBTYPE:STRING=STATIC -D FORCE_STATIC_VCRT:STRING=ON ..

with some messages about qt5 errors. And even if you run other instruction, at the end you will have errors. It maybe immediately after building with configure.bat or then if you try to open solution in VS2019

**Comment by foodornt** [comment]
same dude, it's just annoying
please if anyone finds the solution, post it here

**Comment by 411an** [comment]
Ok I try to do it again and have the same problem:

C:\TBuild\Libraries\openal-soft\build>cmake -G "Visual Studio 16 2019" -A Win32 -D LIBTYPE:STRING=STATIC -D FORCE_STATIC_VCRT:STRING=ON ..
-- Selecting Windows SDK version 10.0.18362.0 to target Windows 10.0.18363.
-- The C compiler identification is MSVC 19.25.28614.0
-- The CXX compiler identification is MSVC 19.25.28614.0
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.25.28610/bin/Hostx64/x86/cl.exe
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.25.28610/bin/Hostx64/x86/cl.exe - works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.25.28610/bin/Hostx64/x86/cl.exe
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.25.28610/bin/Hostx64/x86/cl.exe - works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for sys/types.h
-- Looking for sys/types.h - found
-- Looking for stdint.h
-- Looking for stdint.h - found
-- Looking for stddef.h
-- Looking for stddef.h - found
-- Check size of long
-- Check size of long - done
-- Check size of long long
-- Check size of long long - done
-- Performing Test HAVE_STD_C11
-- Performing Test HAVE_STD_C11 - Failed
-- Performing Test HAVE_STD_C99
-- Performing Test HAVE_STD_C99 - Failed
-- Performing Test HAVE_STD_CXX11
-- Performing Test HAVE_STD_CXX11 - Failed
-- Checking _FILE_OFFSET_BITS for large files
-- Checking _FILE_OFFSET_BITS for large files - not needed
-- Performing Test HAVE_RESTRICT
-- Performing Test HAVE_RESTRICT - Failed
-- Performing Test HAVE_INLINE
-- Performing Test HAVE_INLINE - Success
-- Performing Test HAVE_STRUCT_TIMESPEC
-- Performing Test HAVE_STRUCT_TIMESPEC - Success
-- Performing Test HAVE_LIBATOMIC
-- Performing Test HAVE_LIBATOMIC - Failed
-- Looking for __android_log_print in log
-- Looking for __android_log_print in log - not found
-- Performing Test HAVE_C99_BOOL
-- Performing Test HAVE_C99_BOOL - Success
-- Performing Test HAVE_C11_STATIC_ASSERT
-- Performing Test HAVE_C11_STATIC_ASSERT - Failed
-- Performing Test HAVE_C11_ALIGNAS
-- Performing Test HAVE_C11_ALIGNAS - Failed
-- Performing Test HAVE_C11_ATOMIC
-- Performing Test HAVE_C11_ATOMIC - Failed
-- Performing Test HAVE___BUILTIN_ASSUME_ALIGNED
-- Performing Test HAVE___BUILTIN_ASSUME_ALIGNED - Success
-- Performing Test HAVE_MSSE_SWITCH
-- Performing Test HAVE_MSSE_SWITCH - Failed
-- Performing Test HAVE_MSSE2_SWITCH
-- Performing Test HAVE_MSSE2_SWITCH - Failed
-- Performing Test HAVE_MSSE3_SWITCH
-- Performing Test HAVE_MSSE3_SWITCH - Failed
-- Performing Test HAVE_MSSE4_1_SWITCH
-- Performing Test HAVE_MSSE4_1_SWITCH - Failed
-- Performing Test HAVE_MFPU_NEON_SWITCH
-- Performing Test HAVE_MFPU_NEON_SWITCH - Failed
-- Performing Test HAVE_ARCH_SSE2
-- Performing Test HAVE_ARCH_SSE2 - Success
-- Performing Test HAVE_GCC_FORMAT
-- Performing Test HAVE_GCC_FORMAT - Failed
-- Looking for stdbool.h
-- Looking for stdbool.h - found
-- Looking for stdalign.h
-- Looking for stdalign.h - not found
-- Looking for malloc.h
-- Looking for malloc.h - found
-- Looking for dirent.h
-- Looking for dirent.h - not found
-- Looking for strings.h
-- Looking for strings.h - not found
-- Looking for cpuid.h
-- Looking for cpuid.h - not found
-- Looking for intrin.h
-- Looking for intrin.h - found
-- Looking for sys/sysconf.h
-- Looking for sys/sysconf.h - not found
-- Looking for fenv.h
-- Looking for fenv.h - found
-- Looking for float.h
-- Looking for float.h - found
-- Looking for ieeefp.h
-- Looking for ieeefp.h - not found
-- Looking for guiddef.h
-- Looking for guiddef.h - found
-- Looking for pow in m
-- Looking for pow in m - not found
-- Looking for dlopen in dl
-- Looking for dlopen in dl - not found
-- Looking for dlfcn.h
-- Looking for dlfcn.h - not found
-- Performing Test HAVE_CPUID_INTRINSIC
-- Performing Test HAVE_CPUID_INTRINSIC - Success
-- Performing Test HAVE_BITSCANFORWARD64_INTRINSIC
-- Performing Test HAVE_BITSCANFORWARD64_INTRINSIC - Failed
-- Performing Test HAVE_BITSCANFORWARD_INTRINSIC
-- Performing Test HAVE_BITSCANFORWARD_INTRINSIC - Success
-- Looking for sysconf
-- Looking for sysconf - not found
-- Looking for aligned_alloc
-- Looking for aligned_alloc - not found
-- Looking for posix_memalign
-- Looking for posix_memalign - not found
-- Looking for _aligned_malloc
-- Looking for _aligned_malloc - found
-- Looking for proc_pidpath
-- Looking for proc_pidpath - not found
-- Looking for lrintf
-- Looking for lrintf - found
-- Looking for modff
-- Looking for modff - found
-- Looking for log2f
-- Looking for log2f - found
-- Looking for cbrtf
-- Looking for cbrtf - found
-- Looking for copysignf
-- Looking for copysignf - found
-- Looking for _controlfp
-- Looking for _controlfp - found
-- Looking for __control87_2
-- Looking for __control87_2 - found
-- Looking for stat
-- Looking for stat - found
-- Looking for strtof
-- Looking for strtof - found
-- Looking for strcasecmp
-- Looking for strcasecmp - not found
-- Looking for _stricmp
-- Looking for _stricmp - found
-- Looking for strncasecmp
-- Looking for strncasecmp - not found
-- Looking for _strnicmp
-- Looking for _strnicmp - found
-- Looking for strnlen
-- Looking for strnlen - found
-- Looking for snprintf
-- Looking for snprintf - found
-- Looking for isfinite
-- Looking for isfinite - found
-- Looking for isnan
-- Looking for isnan - found
-- Looking for windows.h
-- Looking for windows.h - found
-- Looking for getopt
-- Looking for getopt - not found
-- Looking for xmmintrin.h
-- Looking for xmmintrin.h - found
-- Looking for emmintrin.h
-- Looking for emmintrin.h - found
-- Looking for pmmintrin.h
-- Looking for pmmintrin.h - found
-- Looking for smmintrin.h
-- Looking for smmintrin.h - found
-- Looking for arm_neon.h
-- Looking for arm_neon.h - not found
-- Could NOT find ALSA (missing: ALSA_LIBRARY ALSA_INCLUDE_DIR)
-- Could NOT find OSS (missing: OSS_INCLUDE_DIR)
-- Could NOT find AudioIO (missing: AUDIOIO_INCLUDE_DIR)
-- Could NOT find SoundIO (missing: SOUNDIO_LIBRARY SOUNDIO_INCLUDE_DIR)
-- Could NOT find QSA (missing: QSA_LIBRARY QSA_INCLUDE_DIR)
-- Looking for include files windows.h, mmsystem.h
-- Looking for include files windows.h, mmsystem.h - found
-- Looking for waveOutOpen in winmm
-- Looking for waveOutOpen in winmm - found
-- FindWindowsSDK: Detected Visual Studio 2012 or newer, not using the _xp toolset variant: including SDK versions that drop XP support in search!
CMake Warning (dev) at C:/TBuild/ThirdParty/cmake/share/cmake-3.17/Modules/FindPackageHandleStandardArgs.cmake:272 (message):
  The package name passed to `find_package_handle_standard_args` (WindowsSDK)
  does not match the name of the calling package (DSound).  This can lead to
  problems in calling code that expects `find_package` result variables
  (e.g., `_FOUND`) to follow a certain pattern.
Call Stack (most recent call first):
  cmake/FindWindowsSDK.cmake:467 (find_package_handle_standard_args)
  cmake/FindDSound.cmake:12 (include)
  CMakeLists.txt:1095 (FIND_PACKAGE)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Found WindowsSDK: C:/Program Files (x86)/Windows Kits/10
-- Found DSound: C:/Program Files (x86)/Windows Kits/10/Lib/10.0.18362.0/um/x86/dsound.lib
-- Looking for mmdeviceapi.h
-- Looking for mmdeviceapi.h - found
-- Could NOT find PortAudio (missing: PORTAUDIO_LIBRARY PORTAUDIO_INCLUDE_DIR)
-- Could NOT find PulseAudio (missing: PULSEAUDIO_LIBRARY PULSEAUDIO_INCLUDE_DIR)
-- Could NOT find JACK (missing: JACK_LIBRARY JACK_INCLUDE_DIR)
-- Looking for include files SLES/OpenSLES.h, SLES/OpenSLES_Android.h
-- Looking for include files SLES/OpenSLES.h, SLES/OpenSLES_Android.h - not found
-- Looking for pthread.h
-- Looking for pthread.h - not found
-- Found Threads: TRUE
-- Could NOT find SDL2 (missing: SDL2_LIBRARY SDL2_INCLUDE_DIR)
-- Found Git: C:/Program Files/Git/cmd/git.exe (found version "2.26.0.windows.1")
CMake Warning at utils/alsoft-config/CMakeLists.txt:15 (find_package):
  By not providing "FindQt5Widgets.cmake" in CMAKE_MODULE_PATH this project
  has asked CMake to find a package configuration file provided by
  "Qt5Widgets", but CMake did not find one.

  Could not find a package configuration file provided by "Qt5Widgets" with
  any of the following names:

    Qt5WidgetsConfig.cmake
    qt5widgets-config.cmake

  Add the installation prefix of "Qt5Widgets" to CMAKE_PREFIX_PATH or set
  "Qt5Widgets_DIR" to a directory containing one of the above files.  If
  "Qt5Widgets" provides a separate development package or SDK, be sure it has
  been installed.


-- Found unsuitable Qt version "" from NOTFOUND
-- Could NOT find SDL2 (missing: SDL2_LIBRARY SDL2_INCLUDE_DIR)
--
-- Building OpenAL with support for the following backends:
--      WinMM, DirectSound, WASAPI, WaveFile, Null
--
-- Building with support for CPU extensions:
--     Default, SSE, SSE2, SSE3, SSE4.1
--
-- Building with SSE2 codegen
--
-- Embedding HRTF datasets
--
-- Installing sample configuration
--
-- Installing HRTF definitions
--
-- Installing AmbDec presets
--
-- Building utility programs
--
-- Building test programs
--
-- Building example programs
-- Configuring done
-- Generating done
-- Build files have been written to: C:/TBuild/Libraries/openal-soft/build

C:\TBuild\Libraries\openal-soft\build>

**Comment by ilya-fedin** [comment]
> Ok I try to do it again and have the same problem:

But it is successful:

> -- Build files have been written to: C:/TBuild/Libraries/openal-soft/build

Btw, remember to use `code` tag

**Comment by nhan19899** [comment]
> Hướng dẫn xây dựng cho VS2019 không hoạt động ngay bây giờ
> 
> Sau lần cập nhật cuối cùng, hướng dẫn này https://github.com/telegramdesktop/tdesktop/blob/dev/docs/building-msvc.md không hoạt động.
> 
> Nó dừng lại sau dòng
> 
> cmake -G "Visual Studio 16 2019" -A Win32 -D LIBTYPE: STRING = STATIC -D FORCE_STATIC_VCRT: STRING = ON ..
> 
> với một số thông báo về lỗi qt5. Và ngay cả khi bạn chạy hướng dẫn khác, cuối cùng bạn sẽ có lỗi. Nó có thể ngay lập tức sau khi xây dựng với configure.bat hoặc sau đó nếu bạn cố mở giải pháp trong VS2019411an
