### ISSUE TITLE
[improvement] contacts width fixed for bigger window sizes

### ISSUE THREAD

**Issue by ozanyolyapar** [telegramdesktop/tdesktop#757]
The table of contents width is set in percent. But if the resolution is bigger than e.g. 1280 then width should be fixed. 
I attached an image of the problem.

![2015-05-26 15_02_00-](https://cloud.githubusercontent.com/assets/12610841/7816514/19fd3220-03cf-11e5-8242-999cbe7ffa8b.png)

**Comment by auchri** [comment]
Even better: #314
