### ISSUE TITLE
Folder panel should be visible only if chatlist is visible

### ISSUE THREAD

**Issue by seniorivn** [telegramdesktop/tdesktop#7571]
### Steps to reproduce
1. open tdesktop window
2. resize window to make chatlist dissapear
3. folders sidebar is still there

### Expected behaviour

Folders sidebar  should be visible only if chatlist is visible

### Actual behaviour
Tell us what happens instead

### Configuration
Linux x64

**Version of Telegram Desktop:**
2.0.1

**Comment by seniorivn** [comment]
That's how it looks when the window is very narrow!
![image](https://user-images.githubusercontent.com/5340859/78401233-f45c7900-7600-11ea-95fd-16d4e3b52682.png)
Side bar should've disappeared the same way client list does.

**Comment by Aokromes** [comment]
better https://github.com/telegramdesktop/tdesktop/issues/7644 as a setting. (autohide, allways show, allways hide)
