### ISSUE TITLE
Pictures have been sent

### ISSUE THREAD

**Issue by woytu** [telegramdesktop/tdesktop#7573]
### Steps to reproduce
When the program runs for too long, you must exit the program (end the process) and restart it, the picture can be sent successfully, Otherwise, the picture will not be sent

### Expected behaviour
Picture successfully sent

### Actual behaviour
Picture cannot be sent

### Configuration
**Operating system:**
Windows 10 profession 18363.720

**Version of Telegram Desktop:**
1.9.21
**Used theme**:
default

**Comment by Aokromes** [comment]
how much is "too long" also, update latest telegram desktop from github -> releases or desktop.telegram.org.
