### ISSUE TITLE
FQDN does not parsing in url

### ISSUE THREAD

**Issue by rnz** [telegramdesktop/tdesktop#7574]
### Steps to reproduce
Paste FQDN link (with dot).

### Actual behaviour
https://nextstrain.org./ncov?p=full
![image](https://user-images.githubusercontent.com/851927/78424918-6d97b280-7679-11ea-8e1c-8c7281ff050e.png)

### Expected behaviour
As this https://nextstrain.org/ncov?p=full
![image](https://user-images.githubusercontent.com/851927/78424943-99b33380-7679-11ea-9b93-f05ed835c611.png)

### Configuration
**OS:** Linux 5.3.0-45-generic #37-Ubuntu SMP Thu Mar 26 20:41:27 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
**Version of Telegram Desktop:** 2.0.1
**Used theme**: Night

**Comment by rnz** [comment]
Still present

**Comment by rnz** [comment]
Still present

**Comment by rnz** [comment]
Still present

**Comment by rnz** [comment]
Still present

**Comment by rnz** [comment]
Still present

**Comment by Aokromes** [comment]
this issue is also present on android, so very likely it's server side bug.

**Comment by Aokromes** [comment]
such issue belongs to https://bugs.telegram.org/
