### ISSUE TITLE
Letter-key-based keybindings don't work on non-US layout on Arch Linux.

### ISSUE THREAD

**Issue by NightH4nter** [telegramdesktop/tdesktop#7576]
### Steps to reproduce

1. Switch your layout to non-US (maybe Russian only?);

2. Try to use anything bound to letter keys, e.g.: Ctrl+a (select all), Ctrl+c (copy), Ctrl-v (paste), Ctrl+z (undo). 

### Expected behaviour
Select all, copy, paste, undo.
### Actual behaviour
Nothing.

### Configuration
**Operating system:** Arch Linux LTS 5.4.28-1.

**Version of Telegram Desktop:** 1.9.21-3.

**Used theme**: Night theme, Tinted, Purple color.

**Additional information**: No full-stack desktop environment, nor special clipboard manager, nor keyboard/layout manager installed. Window manager is i3-gaps. The functions mentioned above work with US layout. They also work with any layout in Chromium, Discord. They don't in LibreOffice, Alacritty.

**Comment by ilya-fedin** [comment]
https://github.com/telegramdesktop/tdesktop/issues/6645

**Comment by NightH4nter** [comment]
> #6645

I'm not using Wayland. I know it was fixed in Wayland for a long time.

**Comment by ilya-fedin** [comment]
I can't reproduce on X11.
btw, check that first layout is english, otherwise keybindings doesn't work in many apps.

**Comment by NightH4nter** [comment]
> I can't reproduce on X11.
> btw, check that the first layout is english, otherwise keybindings doesn't work in many apps.

First of all: do you use any clipboard/layout managers? I don't use anything like that, I just set the layouts with `setxkbmap`.

**Comment by ilya-fedin** [comment]
> First of all: do you use any clipboard/layout managers?

No

> I don't use anything like that, I just set the layouts with `setxkbmap`.

`setxkbmap -layout us,ru -option grp:win_space_toggle` - works perfectly

**Comment by NightH4nter** [comment]
> > First of all: do you use any clipboard/layout managers?
> 
> No
> 
> > I don't use anything like that, I just set the layouts with `setxkbmap`.
> 
> `setxkbmap -layout us,ru -option grp:win_space_toggle` - works perfectly

Okay, it seems like I was managing the keyboard layouts in another, way more crude way. Thanks for help.
