### ISSUE TITLE
Unable to send delayed message on GNU/Linux

### ISSUE THREAD

**Issue by Hi-Angel** [telegramdesktop/tdesktop#7577]
On Android since recently upon pressing and holding "send" button there's a pop up that allows one to delay sending the message, so you can e.g. write it on Saturday, but make it sent on Monday.

I searched various settings, but can't seem to find how to make it work on GNU/Linux client.

### Steps to reproduce
1. Open a dialog with someone.
2. Write "test", but don't send it just yet.
3. Press and hold the "send" icon on the right of the input field.

### Expected behaviour
A calendar should pop up that asks what time I want it to be sent at.

### Actual behaviour
Nothing happens. If you release the button, the text just gets sent.

### Configuration
**Operating system:** Archlinux

**Version of Telegram Desktop:** 2.0.1

**Used theme**: Classic, with "Night mode" on.

**Comment by ilya-fedin** [comment]
right click :smile:

**Comment by Hi-Angel** [comment]
> right click

Ha, thank you, that worked! I guess I gotta close the report
