### ISSUE TITLE
Client brakes

### ISSUE THREAD

**Issue by Rabb1tof** [telegramdesktop/tdesktop#7579]
### Steps to reproduce
1. Change the keyboard layout (change the language).
2. Write any message.
3. Repeat steps 1 and 2 several times.

### Expected behaviour
The client will slow down for a few seconds. If you continue to write during the frieze, the frieze will last longer.

### Actual behaviour
Read above.

### Configuration
**Operating system: Win 10 x64 (1809)**
**CPU: AMD R5 2600**
**RAM: 16GB**
**MB: AORUS B450 ELITE**

**Version of Telegram Desktop: 2.0.1**

**Used theme**: Custom (change colors and background only (background is photo, no gif).

**Comment by Aokromes** [comment]
better ticket
https://github.com/telegramdesktop/tdesktop/issues/7952
