### ISSUE TITLE
I dont have native notification in Arch Linux Version 2.0.1

### ISSUE THREAD

**Issue by kevinaltaf** [telegramdesktop/tdesktop#7584]
![Screenshot_20200406_160124](https://user-images.githubusercontent.com/47493498/78541576-0cf6aa00-7820-11ea-85ef-ad07dbcc402c.png)

Massage:
![Screenshot_20200406_160310](https://user-images.githubusercontent.com/47493498/78541619-1da72000-7820-11ea-8aa9-707f85713dc3.png)

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/7523#issuecomment-606283180

**Comment by kevinaltaf** [comment]
> [#7523 (comment)](https://github.com/telegramdesktop/tdesktop/issues/7523#issuecomment-606283180)

but my daemon is running with dunst and libnotify?

**Comment by kevinaltaf** [comment]
oh i see thanks,,
