### ISSUE TITLE
When I right-click on a message, menu pops-up on main monitor, not the monitor where Telegram is opened

### ISSUE THREAD

**Issue by alxkrylov** [telegramdesktop/tdesktop#7586]
### Steps to reproduce
1. Open Telegram Desktop for Windows on any monitor other than main.
2. Open any chat or channel.
3. Right-click on any message.
![2020-04-06 21_09_06-Telegram](https://user-images.githubusercontent.com/36798626/78591436-172e9d80-784c-11ea-989f-db406806e636.png)

### Expected behaviour
The pop-up menu should appear near the point I clicked at.

### Actual behaviour
The pop-up menu appears somewhere on the main monitor. 
![2020-04-06 21_10_09-Issues · telegramdesktop_tdesktop](https://user-images.githubusercontent.com/36798626/78591448-1d247e80-784c-11ea-87fc-b81c2aea224c.png)

### Configuration
**Operating system:**
Windows 10 Pro x64 version 1903 (OS Build 18362.720)
Display adapters: Radeon RX 570, Intel HD Graphics 4600.

**Version of Telegram Desktop:**
2.01 for Windows

**Used theme**:
None.

<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/7099
