### ISSUE TITLE
Freeze on local password input [wayland]

### ISSUE THREAD

**Issue by amiralies** [telegramdesktop/tdesktop#7588]
### Steps to reproduce
1. Set local password
2. Restart computer
3. Launch and enter password

### Expected behaviour
Should run

### Actual behaviour
Freezes

### Configuration
**Operating system:** Arch linux
Wayland 
Sway

**Version of Telegram Desktop:**
`2.0.1`

**Used theme**:
Dracula

It happens on first try / issue will go away if you launch telegram again

Edit: Updated version

**Comment by Aokromes** [comment]
we cannot know what version you are using with the provided data.

**Comment by amiralies** [comment]
@Aokromes `2.0.1`

**Comment by ilya-fedin** [comment]
> It happens on first try

a backtrace is neeeded to debug this

**Comment by ilya-fedin** [comment]
@amiralies

**Comment by amiralies** [comment]
How can i find backtrace?

**Comment by ilya-fedin** [comment]
> How can i find backtrace?

Run tdesktop with gdb, enter `run` and after freeze `bt full`

**Comment by amiralies** [comment]
Do i have to run a self compiled versionof tg?

**Comment by ilya-fedin** [comment]
> Do i have to run a self compiled versionof tg?

It is desirable since arch does not distribute debug symbols

**Comment by amiralies** [comment]
Ill try later

**Comment by amiralies** [comment]
I can confirm freeze goes away after some time.

**Comment by ilya-fedin** [comment]
What about backtrace?

**Comment by ilya-fedin** [comment]
@amiralies

**Comment by amiralies** [comment]
Oh sorry. Since i'm busy atm, can we close this and then re-open after i had time to build?

**Comment by ilya-fedin** [comment]
There are a package in flatpak with debug symbols
`flatpak install org.telegram.desktop org.telegram.desktop.Debug`

**Comment by ilya-fedin** [comment]
https://docs.flatpak.org/en/latest/debugging.html

**Comment by amiralies** [comment]
This is not happening on flatpak version

**Comment by ilya-fedin** [comment]
Do you use Kvantum?

**Comment by amiralies** [comment]
I don't use that. I think best way to debug is that I should compile w/ debug symbols. Feel free to close this I can open new issue when I had time to build manually.

**Comment by ilya-fedin** [comment]
> Feel free to close this I can open new issue when I had time to build manually.

It's ok to be open I believe

**Comment by amiralies** [comment]
I can confirm this is not happening anymore
