### ISSUE TITLE
[Question] about lib_crl\crl\commoncrl_common_utils.h

### ISSUE THREAD

**Issue by yukinjie** [telegramdesktop/tdesktop#7590]
finalizer &operator=(finalizer &&other) {
		_callable = std::move(other._callable);
		_disabled = std::exchange(other._disabled, true);
	}

line 51, need return *this ?

**Comment by john-preston** [comment]
Looks like that. I guess there is no instantiations of this method in existing code so it doesn't fail while compiling.

**Comment by john-preston** [comment]
Fix in the submodule, thanks.
