### ISSUE TITLE
Non-native notifications don't work on tiling window managers (Linux only)

### ISSUE THREAD

**Issue by WhyNotHugo** [telegramdesktop/tdesktop#7591]
Telegram re-implements notifications rather than use the OS one, but on Linux, these don't render properly on tiling window managers.

### Steps to reproduce
1. On a clean installation, just ask someone to send you a message.

### Expected behaviour
Ideally, Telegram should just use the OS's notifications. There's really no reason to override the user's established preference by default.

Regardless of the default, the notifications should render properly on tiling window managers.

### Actual behaviour
Notifications are a full-sized window, with their content inside a corner of this otherwise transparent window.

There were two windows before taking this screenshot, each taking up 50% screen space. Telegram's notification window is a third window, so now they each take up 33% scree space. You might get the impression that there's empty space in the middle -- the window is actually taking up all of that space, but only drawing on parts of it.

![2020-04-07T19:36:59,087346415+02:00](https://user-images.githubusercontent.com/730811/78702870-933aeb00-7909-11ea-8828-128f36d775ea.png)

For the following screenshot, I had my window layout set to tabbed, at which point, Telegram created a new window which, again, takes up as much space as it can (the background is just a transparent non-clickthrough area of this notification window).

![2020-04-07T19:37:04,175094266+02:00](https://user-images.githubusercontent.com/730811/78701893-09d6e900-7908-11ea-929f-f344aefd60e9.png)

Here's a final screenshot, capturing *only* the space occupied by the currently active window:

![2020-04-07T19:36:49,818025566+02:00](https://user-images.githubusercontent.com/730811/78702779-6be41e00-7909-11ea-9fae-b8c6f1352198.png)

### Configuration
**Operating system:** ArchLinux, running swaywm as a tiling window manager.
**Version of Telegram Desktop:** 2.0.1
**Used theme**: Tinted

**Comment by ilya-fedin** [comment]
This is a wayland issue, but not a tiling issue.
Non-native notification won't be placed right on any compositor under wayland (but maybe on Plasma's compositor it's OK)

**Comment by WhyNotHugo** [comment]
>  Non-native notification won't be placed right on any compositor under wayland (but maybe on Plasma's compositor it's OK)

So maybe it makes sense to use native notifications by default on Linux? Again, it makes sense to follow the user's preference, and double so if non-native won't work.

> This is a wayland issue, but not a tiling issue.

Notification daemons handle this somehow, so I'm sure clients can do _something_ to make them behave as expected (though the details are beyond me).

**Comment by Johnnynator** [comment]
> Plasma's compositor it's OK

last time i checked, it was also broken on Plasma.

**Comment by ilya-fedin** [comment]
> So maybe it makes sense to use native notifications by default on Linux?

Persuade Preston

> Again, it makes sense to follow the user's preference, and double so if non-native won't work.

What do you mean?

**Comment by WhyNotHugo** [comment]
> > Again, it makes sense to follow the user's preference, and doubl**y** so if non-native won't work.
> What do you mean?

I meant to say, it makes sense to follow the user's preference (use the notification daemon they've chosen for their system), and the fact that the non-native ones don't work just adds to that. (at least on Linux).

**Comment by ilya-fedin** [comment]
> I meant to say, it makes sense to follow the user's preference

If the user uses a DE, it doesn't mean that the notification daemon of the DE is his preference. I know a lot of people that love telegram notifications and using notification daemon only for system notifications.

**Comment by WhyNotHugo** [comment]
> If the user uses a DE, it doesn't mean that the notification daemon of the DE is his preference.

If a user has a notification daemon set up on their system, I'd assume it's for a reason. Apps should generally try to integrate with the environment they're in, much the same way they pick the user's language, or the desktop's scaling (these are all things Telegram picks up perfectly).

I think desktops would be a mess if every single application implements their own custom notification mechanism.

> I know a lot of people that love telegram notifications and using notification daemon only for system notifications.

A fair point, and there's no reason to remove the setting (I'm honestly curious though, as to why they don't change the system's notifications to behave they way the like, instead of just limiting that to Telegram, but that's getting off-topic).

The truth is that these notifications don't render properly on Linux, so having them as a default is just having a broken default, and I think that's the main point here: keeping a default that does not work is just a bad user experience.

**Comment by ilya-fedin** [comment]
> If a user has a notification daemon set up on their system, I'd assume it's for a reason.

No, all mainstream DEs run notification daemons by default. That's not a user choice.

> The truth is that these notifications don't render properly on Linux

The truth is that Wayland support in Qt is very ugly. And there are a lot of others problems beside notifications.

**Comment by ilya-fedin** [comment]
> keeping a default that does not work is just a bad user experience.

Qt uses X11 by default and that's for a reason. If you're enabling the Wayland backend - you should be ready for problems.

**Comment by WhyNotHugo** [comment]
> The truth is that Wayland support in Qt is very ugly. And there are a lot of others problems beside notifications.

Qt apps work just fine on Linux. I believe this is an exception case, because Telegram tries to do something funny with these notification-windows.

> Qt uses X11 by default and that's for a reason. If you're enabling the Wayland backend - you should be ready for problems.

I've don't think I've configured anything to force Qt to do that -- it just uses the default backend.
X11 doesn't support things like window scaling, so a high-dpi screen, so I can't really use it on my hardware. I suspect that's also the case for many people, given the dominance of high resolution displays nowadays.

And, honestly, but this kind of argument ("you should expect trouble using that, switch to another OS") doesn't contribute. I'm trying to point out a bug, and possible solutions. If you dislike my proposed solution, I'm happy to hear alternatives, but hinting that users should just switch to another OS isn't one -- especially given this is a supported platform (heck, even binaries are provided for it!).

**Comment by ilya-fedin** [comment]
> but hinting that users should just switch to another OS isn't one -- especially given this is a supported platform (heck, even binaries are provided for it!).

> another graphical backend
> another OS

Excellent word rewriting

**Comment by ilya-fedin** [comment]
> Qt apps work just fine on Linux.

Personally I experiencing a lot of problems with Qt apps on Wayland and not only with Telegram.

**Comment by WhyNotHugo** [comment]
> Excellent word rewriting

I don't quite follow.

> Personally I experiencing a lot of problems with Qt apps on Wayland and not only with Telegram.

I'm sorry to hear that. I encourage you to report these bugs and see if you can contribute to getting them fixed. But please, let's try to stay on topic here.

**Comment by ilya-fedin** [comment]
> I don't quite follow.

I said that the Wayland backend is unstable, you started talking about switching to another OS


> I'm sorry to hear that. I encourage you to report these bugs and see if you can contribute to getting them fixed. But please, let's try to stay on topic here.

Everything that I'm trying to say - do not expect normal operation from Wayland. It's still too far far way from finish, especially at Qt side.
And the latest news about Qt takes it even further.

**Comment by ilya-fedin** [comment]
For example, on every notification it's writes to stdout that requestActivated doesn't implemented yet on Wayland backend.

**Comment by ilya-fedin** [comment]
Just look there: https://github.com/telegramdesktop/tdesktop/labels/wayland

**Comment by WhyNotHugo** [comment]
I don't think I quite follow your point. I _do_ expect a normal operation. And, with the exception of these notification windows, everything works smoothly.

Since notification windows are problematic, I opened this ticket. I think the simplest fix is to just use the available notification daemon.

**Comment by WhyNotHugo** [comment]
> Just look there: https://github.com/telegramdesktop/tdesktop/labels/wayland

Yes, I understand that people have issues. That's what this issue tracker is for. macOS also has a bunch (10, as I can see). I'm sure all platform do.

But I don't understand what you're trying to say.

**Comment by ilya-fedin** [comment]
> And, with the exception of these notification windows, everything works smoothly.

Make the window fullscreen and right-click at the right edge

**Comment by WhyNotHugo** [comment]
> Maximize the window and right-click at the right edge in the chat area

It's interpreted as a click on the scrollbar. Is that a bug?

**Comment by ilya-fedin** [comment]
> It's interpreted as a click on the scrollbar.

Okay, slightly to the left

**Comment by WhyNotHugo** [comment]
Nothing happens when right clicking on that blank space. Further left I get a dropdown saying "select messages".

Sorry, but, this doesn't seem related to this issue, sound like you're tackling something different here, and adding noise to this issue. Can you open a separate one? Thanks!

**Comment by ilya-fedin** [comment]
> But I don't understand what you're trying to say.

There are some bugs with pointing on the screen in the toolkit. I wonder if it is possible to workaround them without fixing the toolkit. I guess the answer is no.

**Comment by ilya-fedin** [comment]
> Further left I get a dropdown saying "select messages".

It should be opened to the left from cursor. But it goes outside of the screen. This is a little another bug that demonstrates that the problem is in the toolkit.

**Comment by ilya-fedin** [comment]
> macOS also has a bunch (10, as I can see).

They are not related to such base things

**Comment by WhyNotHugo** [comment]
> There are some bugs with pointing on the screen in the toolkit. I wonder if it is possible to workaround them without fixing the toolkit. I guess the answer is no.

Well, Qt work "well enough", right? Sure, there are bugs that probably are too much of a pain to work around. But at the same time, I keep Telegram running permanently without issues. .

Lack of workarounds doesn't seem to be the case here though (fortunately); I've already suggested a potential workaround to avoid this problem hitting this problem out-of-the box. Especially first-time users.

> It should be opened to the left from cursor. But it goes outside of the screen. This is a little another bug that demonstrates that the problem is in the toolkit.

I can't reproduce it. It opens on the left of the cursor for me, and is visible on screen.
If you want to open an issue for it, I'd be happy to compare our environments and see why not -- maybe our setups differ on something else?

**Comment by ilya-fedin** [comment]
I just contacted some person from KDE. As he told me, there are no way to position windows on Wayland. KDE's native notifications are using a custom private kwin protocol. I think there are something similar with gnome. Don't know about sway, though.
I.e. there are no way to fix this bug.

**Comment by Aokromes** [comment]
so, close?

**Comment by WhyNotHugo** [comment]
There is a fix, which is to use the native notifications on Wayland, since these work.

Not sure how it works on `sway`, but I know `mako` (a notification daemon) runs fine on sway. I doubt the protocol is private, but it's probably sway-specific.

**Comment by ilya-fedin** [comment]
Looks like they use api that sets anchors: https://github.com/emersion/mako/blob/1071682a5ec0d7109688923da8848878244d1291/wayland.c#L536-L537
But there are no such api in QWindow: https://doc.qt.io/qt-5/qwindow.html
There are also low-level api with anchorEdge property: https://doc.qt.io/qt-5/qwaylandxdgpopup.html
But, I think, no one will rewrite notifications to a low-level api only for Wayland.

**Comment by ilya-fedin** [comment]
> so, close?

I don't know

**Comment by ilya-fedin** [comment]
> There is a fix, which is to use the native notifications on Wayland, since these work.

This is hiding the problem, not fixing it

**Comment by WhyNotHugo** [comment]
> This is hiding the problem, not fixing it

I'd say yes and no at the same time. I guess there's two problems:
1. Notifications are totally broken out of the box on wayland. This is more of a UX problem.
2. Custom notifications don't work on wayland.

Changing the default on wayland would only fix the first one, regrettably. However, the impact of the issue is pretty big: on a clean installation (eg: a new user), when receiving just one message, there's a huge broken window being shown. This is a very bad first impression, and that's kinda why I've been focusing more on this part of the issue.

The second one seems to be unfix-able (I doubt anyone will ever write Telegram-specific custom code for each individual compositor, although you never know!). It also seems like a somewhat minor issue in a way, since the feature overall continues to work (receiving a new message sends a notification).
