### ISSUE TITLE
Call window won't render properly on Linux

### ISSUE THREAD

**Issue by WhyNotHugo** [telegramdesktop/tdesktop#7595]
### Steps to reproduce
1. Initiate a call

### Expected behaviour
A normal window that can adapt its content to its size should be shown. If something with fixed-size is expected, it should probably just be part of the Telegram main window (like audio clips).

### Actual behaviour
Telegram creates a strange window; it doesn't seem to hint to the WM that it's a modal window, so it's treated as a normal window. On a tiling WM, this means it'll grow to occupy all available space:

![2020-03-25T21:18:53,937572672+01:00](https://user-images.githubusercontent.com/730811/78702364-c16bfb00-7908-11ea-8287-7376ab09c959.png)

If I make if a floating window, it apparently takes the size hints, and grows smaller. However, note that the encryption-verification emojis don't show -- they're left outside the window's visible space:

![2020-03-25T21:20:22,597470151+01:00](https://user-images.githubusercontent.com/730811/78702452-e496aa80-7908-11ea-892d-b14ae91a7ccf.png)

It's very likely that the issue is due to some hints missing -- floating window managers are a bit more forgiving with these, but tiling window managers behave quite differently depending on them.

It should be kept in mind that actually hinting that this should be a modal window would be problematic too -- modal windows are usually quickly dismissed (eg: a confirmation or file picker), but this window wouldn't, have having it float on top of the screen for the duration of the call means it covers up whatever other app one tries to use during the call.

### Configuration
Operating system: ArchLinux, running swaywm as a tiling window manager.
Version of Telegram Desktop: 2.0.1
Used theme: Tinted

**Comment by ilya-fedin** [comment]
This is flags for the call window. Can you say which are missed?
https://github.com/telegramdesktop/tdesktop/blob/dev/Telegram/SourceFiles/calls/calls_panel.cpp#L426

**Comment by WhyNotHugo** [comment]
This is not quite my area of expertise, so I did some researching/asking a bit:

Regarding the window being resizeable:

> Non-resizeable means that the application is calling set_min_size and set_max_size with the same non-zero values.

FWIW, an alternative to making it non-resizeable might be to just fill in the entire background with a solid colour (right now it default to "transparent, I assume this is due to nothing else being drawn?), and tweaking the alignment of the emojis when resizing.

Having the window be non-resizeable is a bit weird though, since this is usually just short-lived "ok/cancel" or password prompt windows.

Regarding it not being treated as a dialog/floating:

> There are a few ways, either of which is fine. One way is to have a *parent*, another is to be non-resizeable. Honestly, parent might be more appropriate for a dialog.

Hope this helps. I'm happy to try any potential patches if setting up a tiling compositor is something you'd rather skip. :)

**Comment by ilya-fedin** [comment]
> Having the window be non-resizeable is a bit weird though, since this is usually just short-lived "ok/cancel" or password prompt windows.

#6675 is fixed, probably non-resizable should be ok now

**Comment by ilya-fedin** [comment]
Also, it doesn't have any decorations, so it's already non-resizable for non-tiling users

**Comment by WhyNotHugo** [comment]
> Also, it doesn't have any decorations, so it's already non-resizable for non-tiling users

What do you mean? The lack of decorations doesn't make it non-resizeable (at least that's not a rule for i3 or sway, not sure about other tiling wms).

**Comment by ilya-fedin** [comment]
>  for non-tiling users

**Comment by WhyNotHugo** [comment]
Oh, sorry, my bad! :sweat_smile:

**Comment by ilya-fedin** [comment]
Can you test this artifact?
https://github.com/ilya-fedin/tdesktop/actions/runs/104838909

**Comment by WhyNotHugo** [comment]
Same behaviour: window is not treated as floating, and also a dialog/floating.

**Comment by ilya-fedin** [comment]
Then looks like setMinimumSize and setMaximum size doesn't work on Wayland with Qt

**Comment by ilya-fedin** [comment]
Looks like they added this only with Qt 5.13: https://github.com/qt/qtwayland/commit/5698f22afbd0e6be273f31cf8b934383e7b68cdb#diff-95711caecd2b60a9704dc74902f58167

E.g. if I PR this, it will fix the bug in packages on rolling release distros, but not in the official binary

**Comment by ilya-fedin** [comment]
Try with a parent set to the call window:
https://github.com/ilya-fedin/tdesktop/actions/runs/104931321

**Comment by WhyNotHugo** [comment]
> I.e. if I PR this, it will fix the bug only in packages on rolling release distros, but not in the official binary

That's fine, I guess the official releases will upgrade Qt eventually anyway.

> Try with a parent set to the call window:

This made the window floats as expected, but the default size / content isn't quite right:

![2020-05-14T21:14:11,516150834+02:00](https://user-images.githubusercontent.com/730811/81975920-0aaa1b80-9628-11ea-9314-67c1b5c9f174.png)

They're still resizeable too:

![2020-05-14T21:15:18,454130595+02:00](https://user-images.githubusercontent.com/730811/81975936-11d12980-9628-11ea-9363-8ebfd9041651.png)

**Comment by ilya-fedin** [comment]
Why did the decorations appear? :thinking:

**Comment by WhyNotHugo** [comment]
The 1px (or 2px?) borders? They've always been there. See the second screenshot in the original post. The first image has none because non-floating windows don't have borders except between windows.

**Comment by ilya-fedin** [comment]
Currently it builds, should finish in ~30m-1h, I hope margins will be fixed: https://github.com/ilya-fedin/tdesktop/actions/runs/104995367
(i also tried to do the same trick with notifications in this build)

**Comment by ilya-fedin** [comment]
It's built with the second try: https://github.com/ilya-fedin/tdesktop/runs/675925745?check_suite_focus=true

**Comment by WhyNotHugo** [comment]
![2020-05-15T00:13:51,396565217+02:00](https://user-images.githubusercontent.com/730811/81991215-fde5f180-9640-11ea-83d6-b71fcf31e03c.png)

Still same issues; window size is off, and window is resizeable.
However, window is floating by default now too.

**Comment by ilya-fedin** [comment]
> Still same issues; window size is off

But on your screenshot shadows aren't cropped now

**Comment by ilya-fedin** [comment]
> window is resizeable

It will be resizable until Qt update, I can't change it.

**Comment by WhyNotHugo** [comment]
Thanks for addressing this!

Would filling in that "transparent' area of the window with content break support for other window managers (where maybe, borders are not rendered by the WM?)

> But on your screenshot shadows aren't cropped now

True, I failed to notice that.
Not sure if shadows _should_ be there. I'm guessing that's a Qt-specific thing, though, right?

**Comment by ilya-fedin** [comment]
> Not sure if shadows _should_ be there.

WIndows has FramelessWindowHint, for some reason sway ignores that. Probably, sway misconfiguration or bug :man_shrugging:

**Comment by WhyNotHugo** [comment]
> WIndows has FramelessWindowHint, for some reason sway ignores that. Probably, sway misconfiguration or bug man_shrugging

Thanks! I'll follow up on the sway side and see if the problem is there or Qt.
