### ISSUE TITLE
Wrong UI concept, Folders shall work as EXclusion

### ISSUE THREAD

**Issue by VitRom** [telegramdesktop/tdesktop#7596]
## Steps to reproduce
1. Add in your ChatList a bunch of useful but rare used things like a narrow specific bots or channels.
2. Sort them out into Folders by their content and importance, for example "Github notifications" or "Interesting (but not important) News" etc. Mix but don't shake and leave it for a while, depending of their posts intensivity.
3. Open All chats or Unread standard lists.
4. Create new Folder and Edit it.

## Expected behaviour
See a subset of contacts/channels/bots only, that wasn't filtered out into specific folders already.

## Actual behaviour
A bunch of trash including these useful-but-tomorrow and already "categorized"/filtered out things.

## Configuration
**TD 2.0.1**

From the very first days Telegram UI was a kind of native SMS app on steroids. While even ancient ICQ did this contact grouping an ages ago. Even while turning step by step into a sort of communication _platform_ Telegram stills the same as before. And recently introduced Telegarm Folders did nothing with it.

At present Folders are like filtering/sorting by genre/year/artist in media players. This is handy for _re_organization of _always-the-same_ data set. While constantly growing platform-like usage requires a filtering things out, to make this set narrower.

I see the two ways to make things better, and may be somebody will add another one or pair:

A. Make Folders appear like a "regular" contacts to add them to include/exclude sets of Folder. It's nor foolproof nor easy to realize because of possible cycles.
B. Save the present behavior but make items added to folders disappear in other list(s). I.e. work as exclusion but not as OR-variant. Just like a previously introduced Archive but in multiple instances.

**Comment by hxss** [comment]
I also don't understand why folders added as new UI element with individual bulky panel. We already have "Archived chats" that looks like unfinished feature.

This 2 features now flow around real users needs - group and hide lots of chats by its content from main list.

I think best solution is to remove "Archived chats" and "Chat folders" as separate features and give to users possibility to create custom named folders that will looks like today's "Archived chats" - in the top of main list and work as real folder - one chat should be presented in one folder or main list.

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/7517
