### ISSUE TITLE
[Feature Request] Respect "Do Not Disturb" Setting of KDE/Plasma

### ISSUE THREAD

**Issue by erayerdin** [telegramdesktop/tdesktop#7597]
KDE/Plasma has a new feature called "Do not disturb" now, it's been a couple of months maybe. You can set it from notifications tray icon as below.

![image](https://user-images.githubusercontent.com/2399084/78842683-58b87780-7a09-11ea-9ec8-ab39be38b0b9.png)

I'd like Telegram desktop to respect "Do not disturb" setting of KDE/Plasma.

**Comment by ilya-fedin** [comment]
It's already since v1.9.20

**Comment by erayerdin** [comment]
Tested it with SkeddyBot. Sending myself a reminder in 1 minute while KDE was in "Do not disturb" mode. Telegram notifications still appear, probably due to it being not a native notification while other notification bubbles are suppressed.

**Comment by ilya-fedin** [comment]
It also works with non-native notificaitons. Check that you're not using telegram from snap, since snap sandbox doesn't support new plasma api yet and blocks dbus requests to Inhibited method.

**Comment by erayerdin** [comment]
That's quite strange. I receive it from official Manjaro repo. I guess I
should redirect this issue there.

**Comment by ilya-fedin** [comment]
So, if you're not the author of the issue and this feature already exists, issue can be closed?

**Comment by erayerdin** [comment]
> So, if you're not the author of the issue and this feature already exists, issue can be closed?

I *am* the author of this issue but it can be closed *for now*. I'll forward this to Manjaro side, have them review. Maybe they'd like to comment on this. 🤷‍♂️

**Comment by ilya-fedin** [comment]
> I _am_ the author of this issue but it can be closed _for now_.

Than you can check the logs. If there are any errors at requesting state of Don't Disturb mode, they should be logged.

**Comment by erayerdin** [comment]
Okay, so, if any googlers see this, there's a `telegram-qt` package in Manjaro official repos. I suspected maybe it's related to that, installed it and restarted Telegram. Now I have native notifications option. So, yeah, this issue is truly resolved.

**Comment by ilya-fedin** [comment]
> I suspected maybe it's related to that

lol, no, it's a library for telepathy-morse package.

**Comment by ilya-fedin** [comment]
> Now I have native notifications option.

Sounds like a race condition on autostart

**Comment by erayerdin** [comment]
Let me test it.

**Comment by ilya-fedin** [comment]
There are already was issues about the fact that native notifications don't work if the telegram was launched at system start. We tried to improve the notification daemon check, but it does not seem to help: the notification daemon starts working much later. And if so, it can only be fixed on the KDE side.

**Comment by erayerdin** [comment]
> Sounds like a race condition on autostart

You were right. I think running a custom script with sleep will do the trick for now. I will somehow send the logs to KDE I suppose. Thank you.

**Comment by ilya-fedin** [comment]
>  I think running a custom script with sleep will do the trick for now.

btw, there are *session restoring* feature and autostart. If you have activated the first, then it can start tdesktop, which was on your system shutdown. Then you can add tdesktop to exclusion list and look if only with autostart it would work properly (session restoring and autostart are performing on different starting stages).
