### ISSUE TITLE
Can't send higher-res images as images (only as document).

### ISSUE THREAD

**Issue by LeonardFiedrowicz** [telegramdesktop/tdesktop#7598]
# Steps to reproduce
1. Send higher resolution images whatever way you want (I tried 24MP photos), doesn't matter if you select "Send in a quick way" or "Send without compression")
2. Image gets uploaded as a document, uncompressed and without an image preview

### Expected behaviour
Images get send compressed with a bit image appearing in chat

### Actual behaviour
Image gets send as a document. Can't view the image in chat. Needs to be downloaded to open it, even though its already downloaded.
Works fine with lower resolution images. Still doesn't work when compressing a high-res image to below 1MB.
Also applies to images uploaded as uncompressed photos from before the issue appeared.

Still worked on the 25th of March (don't know the version but I usually have the most recent release).

### Configuration
**Operating system:**
Windows 10 1909
(happens Linux as well I think)

**Version of Telegram Desktop:**
2.0.1

**Used theme**:
Tinted

### Example Files
Image that works fine (5500 x 3667)
![IMG_9748_5500](https://user-images.githubusercontent.com/50417119/78846050-d3ce5d80-7a0a-11ea-8c33-c7f6c74826bf.JPG)

Image with a very slightly higher resolution that doesn't work (5550 x 3700)
![IMG_9748_5550](https://user-images.githubusercontent.com/50417119/78846070-e9438780-7a0a-11ea-9830-d388f304cbd1.JPG)

**Comment by rusins** [comment]
Just confirming that this bug is present on Linux as well.

**Comment by samij263** [comment]
This also happens on Windows 7 - latest release 2020

**Comment by upsoftt** [comment]
same here. on phone i can see this image normally. but on desktop imagaes like that i can't 
![image](https://user-images.githubusercontent.com/13884634/79217314-53b75600-7e57-11ea-9d53-db582f1a65ef.png)

**Comment by LeonardFiedrowicz** [comment]
Seems like this got fixed in Version 2.1.

**Comment by upsoftt** [comment]
i made screen shot on mine 2k monitor and sent it as foto to my favorives and then opened it. that what i see (with ctrl + 1 scrollup  zoom)
![image](https://user-images.githubusercontent.com/13884634/80264284-52c6c580-869c-11ea-97be-478d3c2e75be.png)
