### ISSUE TITLE
WORKMODE stopped working

### ISSUE THREAD

**Issue by stivens13** [telegramdesktop/tdesktop#7599]
### Steps to reproduce
1. Go to Preferences
2. Type `workmode`
3. Click `ok`

### Expected behaviour
Button `Hide all muted chats` appears on the top of chat list

### Actual behaviour
Nothing happens

### Configuration
**Operating system:**
MacOS 10.15.4 
**Version of Telegram Desktop:**
2.0.1
**Used theme**:

Comments:
This feature was a perfect solution to filter out garbage and keep only needed chats (contacts and interesting groups)
With introduction of folders, this feature disappeared. However, Folders are 1) cluttering interface 2) introduce complication 3) they don't filter out chats (pinned order breaks unlike with `workmode`.

Tried to download older versions of Telegram, but when typing `workmode` in settings and clicking `Ok`, Telegram restarts on log in screen and workmode not available after that.

**Comment by ilya-fedin** [comment]
#7515 #7483

**Comment by stivens13** [comment]
@ilya-fedin this doesn't solve the issue as people mentioned in #3515. Workmode is much superior to folders because it's convenient, minimalistic, and solves Folders issue for 90% of people while it also allows to work with main chat list. 

Meanwhile, Folders don't do the same as Workmode because main list is still `contaminated`. 

Still, this feature would be a great addition to Folders - people that group Contacts, Groups, and Channels can have Folders for them while main interface remains clean. This is not the case now

**Comment by stivens13** [comment]
In addition, at least allow usage of workmode on older versions for people who need it. When launching older versions of Telegram with workmode, it just restarts and updates, disabling the possibility of using this feature
