### ISSUE TITLE
[Linux] .desktop file recreated at startup even if unwanted

### ISSUE THREAD

**Issue by rmbleeker** [telegramdesktop/tdesktop#760]
I maintain a fair number of Linux desktop systems at a university. To keep the home directories of our users as clean as possible, especially from program binaries, we've installed Telegram desktop on a server in a directory that the clients mount as `/usr/local/` over NFS. We've also made sure all clients have an appropriate **.desktop** file in their local `/usr/share/applications/` folder. We do this with lots of software that isn't packaged with the distro (Debian stable x64). The users have _no write permissions_ to this `/usr/local/` directory.

**Issue:** Every time Telegram starts it creates a new `telegramdesktop.desktop` file in `~/.local/share/applications`. In our situation that is very unwanted and unnecessary. 

I propose to have Telegram desktop for Linux check if it has _write permissions_ to it's own binary when it starts and _if not_, skip creating the `~/.local/share/applications/telegramdesktop.desktop` file and perhaps also turn off the automatic update feature within the application itself.

**Comment by auchri** [comment]
Duplicate #306
