### ISSUE TITLE
[Feature Request] Follow system theme for default theme

### ISSUE THREAD

**Issue by MarcAnt01** [telegramdesktop/tdesktop#7600]
### Is your feature request related to a problem?
Windows 10 and MacOS have a system-wide option for the theme, TDesktop should follow it like the mobile apps (Telegram for Android/iOS) do on their platforms

### Describe the solution you'd like
Follow system theme

### Describe alternatives you've considered
None

### Additional context
None

**Comment by ilya-fedin** [comment]
#4918?

**Comment by MarcAnt01** [comment]
> #4918?

That covers only MacOS

**Comment by ilya-fedin** [comment]
> That covers only MacOS

No

**Comment by MarcAnt01** [comment]
> > That covers only MacOS
> 
> 
> 
> No

**Comment by MarcAnt01** [comment]
> > That covers only MacOS
> 
> No

![image](https://user-images.githubusercontent.com/43090263/78917901-d9ba5200-7a8f-11ea-9007-73370ecd32ae.png)

**Comment by ilya-fedin** [comment]
Look at comments and labels

**Comment by MarcAnt01** [comment]
> Look at comments and labels

Yeah, you're right, the labels mention Windows in spite of the description
