### ISSUE TITLE
"check for updates" button is not available if automatic updates disabled

### ISSUE THREAD

**Issue by xenolog** [telegramdesktop/tdesktop#7601]
### Steps to reproduce
1. Enter to the Advanced settings menu
2. look to updates section
3. try to enable/disable automatic updates

### Expected behaviour
"check for updates" button should be visible if automatic updates disabled

### Actual behaviour
"check for updates" button visible only if automatic updates enabled

### Configuration
MAC OS 10.15.2

**Version of Telegram Desktop: 2.0.1 **

**Used theme: dark**

related screenshots:
https://ibb.co/br5pWTr
https://ibb.co/Gv72Tkx

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/4643
