### ISSUE TITLE
When I copy a png, source image is altered

### ISSUE THREAD

**Issue by bport** [telegramdesktop/tdesktop#7602]
### Steps to reproduce
1. Copy https://upload.wikimedia.org/wikipedia/commons/thumb/7/75/2019-06-19_effet_dunning_kruger.png/1920px-2019-06-19_effet_dunning_kruger.png to telegram desktop

### Expected behaviour
PNG will be the same as source

### Actual behaviour
Left and bottom side are only black cf screenshot
![image](https://user-images.githubusercontent.com/4381811/78898493-2db73d80-7a74-11ea-9622-731e94188e9b.png)

### Configuration
**Operating system:** Linux

**Version of Telegram Desktop:** v2.0.1

**Comment by john-preston** [comment]
You copy it as image and paste as image data? Is it possible that "copy as image" doesn't copy alpha channel, only rgb?

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/7292 ?

**Comment by bport** [comment]
> You copy it as image and paste as image data? Is it possible that "copy as image" doesn't copy alpha channel, only rgb?

To test it I copy pasted to gimp and it's working.
But not working on Telegram

**Comment by ilya-fedin** [comment]
> But not working on Telegram

Could you try with any other Qt app (but not Krita, since it have custom code for clipboard managing)?

**Comment by bport** [comment]
Indeed bug is reproducible with KolourPaint and even Krita

**Comment by ilya-fedin** [comment]
then this is Qt bug :(

**Comment by ilya-fedin** [comment]
@bport

**Comment by bport** [comment]
Didn't had time to test, will try this week end, thanks :-)

**Comment by ilya-fedin** [comment]
Ok, I'll wait

**Comment by ilya-fedin** [comment]
@bport did you test?

**Comment by bport** [comment]
I did a test and it works on one computer, not on other one. I guess it's related to some gtk stuff
Do you know if there is a bug report upstream (Qt)

**Comment by ilya-fedin** [comment]
> Do you know if there is a bug report upstream (Qt)

https://bugreports.qt.io/browse/QTBUG-79656
![image](https://user-images.githubusercontent.com/17829319/84736337-23924d80-af95-11ea-9f05-8ff2bf7a4771.png)
looks like the issue exactly you getting

> I did a test and it works on one computer, not on other one. I guess it's related to some gtk stuff

Hmm, when I trying to paste with that artifact, I can't reproduce the issue (but I can with the release version). Maybe you don;t have gtk on that other computer and the artifact fallbacks to the Qt clipboard? :thinking:

**Comment by ilya-fedin** [comment]
Can't reproduce on 2.1.12 on none of my machines

**Comment by ilya-fedin** [comment]
Is this still valid?

**Comment by Aokromes** [comment]
@bport

**Comment by ilya-fedin** [comment]
@bport

**Comment by Aokromes** [comment]
1 month without answer, if this bug is still valid open a new ticket.
