### ISSUE TITLE
[Feature Request] Do not wrap lines inside code blocks

### ISSUE THREAD

**Issue by sand123** [telegramdesktop/tdesktop#7606]
### Is your feature request related to a problem?
Automatic line wraps inside code blocks should be disabled, because code snippets with long lines become mess

### Describe the solution you'd like
By default, line breaks inside code block remain untouched

### Additional context
Example
![image](https://user-images.githubusercontent.com/3256430/78961922-76bad080-7b0c-11ea-9602-193437fa8b99.png)

**Comment by Laiteux** [comment]
Then how would it look if not wrapped?

**Comment by sand123** [comment]
Line breaks should stay wherever I insert them - even if the line does not fit screen width.
It's just for code blocks

**Comment by Laiteux** [comment]
Are you saying lines should continue even when outside of a message block? That's weird..

**Comment by sand123** [comment]
release 2.1.5 - issue is solved with
`View messages containing long monospace texts in wide bubbles`
Thank you!
