### ISSUE TITLE
Cant show both folders and stickers at less than 1003px width

### ISSUE THREAD

**Issue by ZornTaov** [telegramdesktop/tdesktop#7607]
### Steps to reproduce
1. Show sticker panel
2. Show folder panel
3. (Optional) show/hide group names
4. Try to make window take up 1/2 of 1920x1080 (left or right side)

### Expected behaviour
Should show all 4 panels, folders/groups/text/stickers in a 960px wide window like it did before the folders update.

### Actual behaviour
Once the window goes below 1003px wide, the sticker panel auto-hides, leaving folders/groups/extra wide text area

### Configuration
**Operating system:**
Win 10 Home
**Version of Telegram Desktop:**
2.0.1
**Used theme**:
custom theme(shouldn't matter?), 100% interface scale

**Comment by john-preston** [comment]
@ZornTaov Well, folders have added 72px, so if before it was near the minimal width supporting three columns with 960px window, now it should be at least 1032px, if 980px was minimal, then 1052px is required.

**Comment by ZornTaov** [comment]
I did mean 960, as that's 1920/2 which is half the width of the screen.  I can't remember what the minimal width was before the folder update, but with telegram unable to show all panels at 960 or less and Discord refusing to go under 940px wide, I can't fit both programs on a screen and show the stickers panel in telegram which I constantly use.  That means there's a minimum of 23 pixels (940 + 1003 - 1920) that overlaps between the two programs.  This happens no matter if the groups panel is minimized to icons or not.

**Comment by Aokromes** [comment]
you can workaround it running it with 95% scalling from command line.
