### ISSUE TITLE
Crash when go back to history. 

### ISSUE THREAD

**Issue by mrbaranovskiy** [telegramdesktop/tdesktop#7609]
### Steps to reproduce
1. Open old chat with old history and huge amount of messages and images
2. Start scrolling up. 

You will notice that memory consumption has increased up to 2gb.
The application will crash with MemAllocation exception.

### Expected behavior
The user should have access to all history.

### Actual behavior
Application crashes. 

### Configuration
Windows 10

**Version of Telegram Desktop:**
2.0.1

**Used theme**:
Black

I 've sent a few crash reports. 

<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by Aokromes** [comment]
plz on next start press send crash report and put id here.

**Comment by mrbaranovskiy** [comment]
Your Report Tag: 8cbf5169-0ae1-41e8-bc17-7aaea3809551
Your User Tag: f268545da2e0cd31

**Comment by ilya-fedin** [comment]
#7361
