### ISSUE TITLE
[BUG] Empty sticker panel on windows

### ISSUE THREAD

**Issue by AlessandroBagnoli** [telegramdesktop/tdesktop#761]
In the latest version for windows the sticker panel is completely empty.
![1](https://cloud.githubusercontent.com/assets/6444474/7856194/716db986-0527-11e5-8bd0-c6bac13e3d59.png)
![2](https://cloud.githubusercontent.com/assets/6444474/7856195/72947264-0527-11e5-8d32-5cad0b08d5d3.png)

**Comment by solbjorn** [comment]
Same as #755.

**Comment by Katzen-Gott** [comment]
@AlessandroBagnoli , please re-check on v.0.8.19. Release notes say it should be fixed. And could you please close the issue if it's actually fixed?
