### ISSUE TITLE
[Bug] At Manjaro: "Failed to Open URI" in visual studio (code-oss)

### ISSUE THREAD

**Issue by DanielSkala** [telegramdesktop/tdesktop#7610]
I am trying to set up LiveSharing extension in visual studio in linux Manjaro.
I can successfully sign into my microsoft account but when I click on open xdg-open it shows me this message:
![screen0](https://user-images.githubusercontent.com/17952892/79006366-4baa9e00-7b59-11ea-9238-e93e433f7553.png)

I also checked the installation folder and there are no spaces in folder names
Thanks!

### Configuration
Linux Manjaro xfce
File manager: pacman
Installed insode visual studio as an extension

<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by ilya-fedin** [comment]
How tdesktop related to this? 😮

**Comment by DanielSkala** [comment]
Oh sorry, it is not related to telegram but it is related to the same
mistake that occured.
