### ISSUE TITLE
Windows Notifications Pop-Up While in Full-Screen Mode

### ISSUE THREAD

**Issue by karkason** [telegramdesktop/tdesktop#7611]
### Steps to reproduce
1. Open a YouTube video in full screen.
2. Receive a message in Telegram Desktop.

### Expected behaviour
There shouldn't be any pop-up that interferes with the full-screen content.

### Actual behaviour
There is a pop-up.

### Configuration
**Operating system:** Windows 10.

**Version of Telegram Desktop:** 2.0.1

**Used theme**: Normal.

It's important in particular during presentations when you don't want the notification to pop up.

**Comment by MasterGroosha** [comment]
You can right-click Telegram icon in Windows tray and click "Disable notifications", which will disable them on this app alone. It's like "Do not disturb" mode which won't affect Telegram on your other devices.

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/2290
