### ISSUE TITLE
[Feature Request] Collapse Long Messages by Default

### ISSUE THREAD

**Issue by CountZero1981** [telegramdesktop/tdesktop#7613]
Some people send long messages which I wouldn't like to read (e. g., they just copy full articles from the Web into Telegram group).

Would be nice to collapse such long posts by default, with a link "Read More" to expand them just like it is done in Telegram on Android.

**Comment by MasterGroosha** [comment]
There is no "Read More" on Android, really. There is "Instant View" button (which you might be mentioning), but that's completely another feature.
On the other hand, WhatsShit does have "Read more" and collapses long messages by default.

Of course I don't say that's a bad feature request, I just mention that no other official Telegram app has such feature.

**Comment by Snugface** [comment]
I think this is an alright request.
But please, do not make it a "default" option.
Make it so that users could choose, whether to have long messages shortened or not.
