### ISSUE TITLE
Telegram makes audio raise in pitch on Linux.

### ISSUE THREAD

**Issue by ajaydee** [telegramdesktop/tdesktop#7616]
When I start Telegram, if I'm playing audio, the pitch goes up. Any audio recorded with microphone is a lower pitch. When I quit Telegram, it stays like that. Is Telegram changing pulseaudio bitrate settings?

I'm probably going to have to run Telegram in Wine to avoid this. 

My soundcard is a Behringer UMC404HD

Edit: The wine version does this too. How?

**Comment by ilya-fedin** [comment]
#1548?

**Comment by ajaydee** [comment]
Thanks.
