### ISSUE TITLE
[Feature Request] Don't scroll to the bottom after sending a message.

### ISSUE THREAD

**Issue by NebulaNeko** [telegramdesktop/tdesktop#7617]
English is not my native language; please excuse typing errors.
<br>
### Is your feature request related to a problem?
No.

### Describe the solution you'd like
When I look at the message history, I don't want to automatically scroll to the bottom after sending a message.

### Describe alternatives you've considered
No.

### Additional context
Because this sets the unread message count to zero.

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/6295
