### ISSUE TITLE
[Bug] Valid number in Morocco considered as Invalid

### ISSUE THREAD

**Issue by kafiln** [telegramdesktop/tdesktop#7619]
### Steps to reproduce
1. Launch the application
2. Input number starting by ` 07{d}7` example `070820350` (valid new format in morocco ) when requested

### Expected behaviour
The number is should be valid

### Actual behaviour
I get the message that `Invalid phone number. Please try again` . See screeshot 👇👇
![Untitled](https://user-images.githubusercontent.com/15774583/79053992-72d89c80-7c39-11ea-857d-078c53454a39.png)
`
### Configuration
**Operating system:**
Windows 10
**Version of Telegram Desktop:**
2.0.1
**Used theme**:
Default

**Comment by Kafiil** [comment]
If you use an api to validate phone numbers, I guess that API is not outdated

**Comment by Kafiil** [comment]
To this day I still can't use telegram because he thinks my number is not valid

**Comment by john-preston** [comment]
@Kafiil Sorry, I'll ask.

**Comment by john-preston** [comment]
@Kafiil Could you please send those details to this email: sms@telegram.org

**Comment by Kafiil** [comment]
@john-preston  I just did, thank you for your concern 👍

**Comment by Kafiil** [comment]
Ant updates on this ? I still can't use telegram because it thinks my number is not valid

**Comment by kafiln** [comment]
I have not lost interest, nor resolved this problem on my own. Any help on this is more than welcome 👍

**Comment by Aokromes** [comment]
i am sure this doesn't belongs here, try mail again sms@telegram.org or try twiteer.

**Comment by Aokromes** [comment]
such feature belongs to https://bugs.telegram.org/
