### ISSUE TITLE
Newest Emoji panel sections have labels switched

### ISSUE THREAD

**Issue by benharri** [telegramdesktop/tdesktop#762]
Emoji sections Activity and Travel & Places have the icons switched. The airplane represents Activity and the running man represents Travel & Places. Unless I'm mistaken, those should be swapped.

**Comment by benharri** [comment]
![emoji](https://cloud.githubusercontent.com/assets/7453240/7860156/b27fccce-0546-11e5-8d74-79bb4b253f91.png)
Airplane for Activities
![emoji2](https://cloud.githubusercontent.com/assets/7453240/7860165/ce2d4578-0546-11e5-84f9-065353ac7412.png)
Running man for Travel & Places

**Comment by auchri** [comment]
Fixed with 0.8.21?
