### ISSUE TITLE
telegram tray notify ellipse

### ISSUE THREAD

**Issue by sorokaty** [telegramdesktop/tdesktop#7622]
telegram tray icon is black

and notify icon ellipse

how to fix it?

![2020-04-12_14-54](https://user-images.githubusercontent.com/3114580/79068258-3c009600-7cce-11ea-9e13-2d85f25cb62a.png)

**Comment by xvitaly** [comment]
Duplicate of #7399.

**Comment by sorokaty** [comment]
но он в виде эллипса, ладно чёрный но овальный
