### ISSUE TITLE
[Feature Request] User Default Colour Changing

### ISSUE THREAD

**Issue by FengTang2333** [telegramdesktop/tdesktop#7630]
Dear Developing Teams,

　I'm a new user of Telegram,and I like it VERY much!😀
　After using your application for a while,I found that every Telegram user will be appointed a default colour randomly,and it will be shown on your name while you are chatting in the group (it also shown on your profile if you don't have a profile photo),But i think the colour is not suitable for me and i want to change it,and I would appreciate it if you could add a function to change this colour!
　Again,I'm sincerely grateful for your contributions to Internet chatting,and I'm looking forward to your reply!😘

Yours Sincerely,
Maple Sugar
![Suggestion](https://user-images.githubusercontent.com/47599848/79119217-6469bc80-7dc2-11ea-9b1a-e27cb05325d2.png)

**Comment by yashpalgoyal1304** [comment]
things to consider: 
- either some pre-decided colors can be provided as option, 
- or if the spectrum is provided, then i would suggest locking the values in such a way to avoid very very bright colors (i think constraining saturation and lightness range will do the job).

i like the fact that current auto-assigned colors are very nice on eyes :) and i would hate to see biting colors offered as a choice.
