### ISSUE TITLE
[Question] Is telegram desktop have hw acceleration video decode?

### ISSUE THREAD

**Issue by abubaca4** [telegramdesktop/tdesktop#7635]
Telegram version: 
2.0.1
System: 
Win 10 1809
Ryzen 1600
1050ti
k-lite codec pack installed
In windows media player and MPC-HC all is fine
First video:
Video: MPEG4 Video (H264) 1920x1080 30fps 1900kbps [V: English [eng] (h264 high L4.0, yuv420p, 1920x1080, 1900 kb/s)]
Audio: AAC 48000Hz stereo 196kbps [A: SoundHandler [eng] (aac lc, 48000 Hz, stereo, 196 kb/s)]

Processor load 7-8%(near one core load). No lags.
Second video:
Video: HVC1 1920x1080 30fps 5623kbps [V: English [eng] (hevc main L4.0, yuv420p, 1920x1080, 5623 kb/s)]
Audio: AAC 48000Hz stereo 195kbps [A: SoundHandler [eng] (aac lc, 48000 Hz, stereo, 195 kb/s)]

Processor load 10%(a bit more then one core). Big Lags, frame drops.
In both case no video decode load in graphics card.(hwinfo64)

From this all I conclude that video decoded by cpu and in singlethread. The same problem was on  k53sv laptop(in that case h264 video also drop frames)

How can I solve this problem?

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/6312 no.

**Comment by john-preston** [comment]
@abubaca4 No hw accelerated video decode in tdesktop, sorry.
