### ISSUE TITLE
Add nick name in group[Feature Request] 

### ISSUE THREAD

**Issue by shuaixieca** [telegramdesktop/tdesktop#7636]
### Is your feature request related to a problem?
A clear and concise description of what the problem is.
Users want to use or display different name in different groups other than default username.

### Describe the solution you'd like
Users can add nickname or display name in each group to overwrite the default username. This is just like Wechat did for for group.

### Describe alternatives you've considered
Add feature to let user change display name in group setting.

**Comment by Aokromes** [comment]
very likely this will need api support.
