### ISSUE TITLE
Crash on start

### ISSUE THREAD

**Issue by timhok** [telegramdesktop/tdesktop#7637]
### Steps to reproduce
1. Open Telegram.exe (freshly installed)
2. Enter phone number
3. Recieve code, put it in field

### Expected behaviour
Telegram working

### Actual behaviour
After entering code i can see telegram (list of chats) for just a second, then it crashes without any message.
If already logged in - it crashes almost instantly after start.

### Configuration
**Operating system:** Windows Server 2012 (9600)
**Version of Telegram Desktop:** 2.0.1
also tried:
portable version of 2.0.1
2.0.0
1.9.21
1.9.14

<details><summary><b>Logs</b>:</summary>

> [2020.04.14 06:37:15] Launched version: 2000001, install beta: [FALSE], alpha: 0, debug mode: [FALSE], test dc: [FALSE]
> [2020.04.14 06:37:15] Executable dir: C:/Users/Administrator/AppData/Roaming/Telegram Desktop/, name: Telegram.exe
> [2020.04.14 06:37:15] Initial working dir: C:/Users/Administrator/AppData/Roaming/Telegram Desktop/
> [2020.04.14 06:37:15] Working dir: C:/Users/Administrator/AppData/Roaming/Telegram Desktop/
> [2020.04.14 06:37:15] Command line: C:\Users\Administrator\AppData\Roaming\Telegram Desktop\Telegram.exe
> [2020.04.14 06:37:15] Executable path before check: C:/Users/Administrator/AppData/Roaming/Telegram Desktop/Telegram.exe
> [2020.04.14 06:37:15] Logs started
> [2020.04.14 06:37:15] Connecting local socket to Global\d5c32825fb0463f894382b2b14a44928-{87A94AB0-E370-4cde-98D3-ACC110C5967D}...
> [2020.04.14 06:37:15] This is the only instance of Telegram, starting server and app...
> [2020.04.14 06:37:15] Moved logging from 'C:/Users/Administrator/AppData/Roaming/Telegram Desktop/log_start0.txt' to 'C:/Users/Administrator/AppData/Roaming/Telegram Desktop/log.txt'!
> [2020.04.14 06:37:15] Opened 'C:/Users/Administrator/AppData/Roaming/Telegram Desktop/tdata/working' for reading, the previous Telegram Desktop launch was not finished properly :( Crash log size: 462
> [2020.04.14 06:37:16] Update Info: MTP is unavailable.
> [2020.04.14 06:37:16] App Error: _basePath is empty in writeSettings()
> [2020.04.14 06:37:16] Primary screen DPI: 96
> [2020.04.14 06:37:16] App Info: reading settings...
> [2020.04.14 06:37:16] App Info: reading encrypted settings...
> [2020.04.14 06:37:16] Lang Info: Loaded cached, keys: 2654
> [2020.04.14 06:37:16] OpenAL Logging Level: (not set)
> [2020.04.14 06:37:16] Audio Playback Devices: 
> [2020.04.14 06:37:16] Audio Playback Default Device: 
> [2020.04.14 06:37:16] Audio Capture Devices: 
> [2020.04.14 06:37:16] Audio Capture Default Device: 
> [2020.04.14 06:37:16] Audio Error: Could not open capture device!
> [2020.04.14 06:37:16] App Info: reading map...
> [2020.04.14 06:37:16] App Info: reading encrypted map...
> [2020.04.14 06:37:16] App Info: reading encrypted user settings...
> [2020.04.14 06:37:16] App Info: encrypted user settings read.
> [2020.04.14 06:37:16] App Info: reading encrypted mtp data...
> [2020.04.14 06:37:16] MTP Info: read keys, current: 3, to destroy: 0
> [2020.04.14 06:37:16] Map read time: 21
> [2020.04.14 06:37:16] Export Info: Destroy top bar by controller removal.
> [2020.04.14 06:37:16] Window Shadow: 1, 1, 3, 4, 6, 9, 13, 18, 24, 31, 38, 46
> [2020.04.14 06:37:17] Assertion Failed! "updateIn >= 0" mainwidget.cpp:3558

</details>

There is no audio device, im using RDP

I have also tested it on other server with Windows Server 2019 (1809) and telegram desktop works just fine there

**Comment by Aokromes** [comment]
try 1.8.15.

**Comment by timhok** [comment]
> try 1.8.15.
tried this one and also 1.6.7
still crashing

**Comment by john-preston** [comment]
@timhok Is it like Windows 7 or before? I can try to look into the crash dump if you send me one (.dmp file from tdata/dumps folder near Telegram.exe, for the latest version).

**Comment by timhok** [comment]
> @timhok Is it like Windows 7 or before? I can try to look into the crash dump if you send me one (.dmp file from tdata/dumps folder near Telegram.exe, for the latest version).
More like Windows 8
I never had problems with telegram on this system before, and i cant figure out what causes this crash.

I can send dump file to you, can you add me on telegram (by same username) or tell me where i can upload it?

**Comment by john-preston** [comment]
@timhok You can send me them on t.me/preston
