### ISSUE TITLE
Drag & drop doesn't work from Firefox/Chrome

### ISSUE THREAD

**Issue by mbnoimi** [telegramdesktop/tdesktop#764]
Drag & drop doesn't work.
- Linux Mint 18.2 xfce x64
- Telegram 1.1.23

**Comment by masterandros** [comment]
the same at windows 8.1 x64 edition i open one issue

**Comment by telegramdesktop** [comment]
In Windows I think it is caused by launching app with admin privileges. It is some Windows security thing, that disables drag-n-drop anything inside an app, which was launched with admin rights, see:

http://blogs.msdn.com/b/patricka/archive/2010/01/28/q-why-doesn-t-drag-and-drop-work-when-my-application-is-running-elevated-a-mandatory-integrity-control-and-uipi.aspx

Don't know about Linux Mint, though :(

**Comment by mbnoimi** [comment]
> Don't know about Linux Mint, though :(

May some one tell us what if this bug occurs on other Linux desktop environment (ex. KDE, Cinnamon)

**Comment by bil-elmoussaoui** [comment]
@mbnoimi it's working for me in elementary OS using pantheon desktop (ubuntu 14.04.2), it's might be the default folder manager. Try using Nautilus instead of nemo? or just upgrade nemo to the latest version

**Comment by mbnoimi** [comment]
> it's might be the default folder manager

Oops I didn't mention that this issue occurs when I try to drag & drop from Firefox to Telegram... sorry (D&D from file manager works fine).

> Try using Nautilus instead of nemo

In xfce the default file manager is Thunar

> just upgrade nemo to the latest version

I'm using recent stable system packages... see the benchmark please.

```
System:    Host: mbnoimi-laptop Kernel: 3.13.0-37-generic x86_64 (64 bit, gcc: 4.8.2)
           Desktop: Xfce 4.11.8 (Gtk 2.24.23) Distro: Linux Mint 17.1 Rebecca
Machine:   System: TOSHIBA (portable) product: Satellite C50-A546 version: PSCGQV-00W001AR
           Mobo: TOSHIBA model: PT10S Bios: TOSHIBA version: 1.10 date: 11/20/2013
CPU:       Dual core Intel Core i5-4200M CPU (-HT-MCP-) cache: 3072 KB flags: (lm nx sse sse2 sse3 sse4_1 sse4_2 ssse3 vmx) bmips: 9977.16
           Clock Speeds: 1: 800.00 MHz 2: 2501.00 MHz 3: 800.00 MHz 4: 2501.00 MHz
Graphics:  Card: Intel 4th Gen Core Processor Integrated Graphics Controller bus-ID: 00:02.0
           X.Org: 1.15.1 drivers: (unloaded: fbdev,vesa) FAILED: nouveau,intel Resolution: 1366x768@60.0hz
           GLX Renderer: Mesa DRI Intel Haswell Mobile GLX Version: 1.4 (3.0 Mesa 10.1.3) Direct Rendering: No
Audio:     Card-1: Intel Xeon E3-1200 v3/4th Gen Core Processor HD Audio Controller driver: snd_hda_intel bus-ID: 00:03.0
           Card-2: Intel 8 Series/C220 Series Chipset High Definition Audio Controller driver: snd_hda_intel bus-ID: 00:1b.0
           Sound: Advanced Linux Sound Architecture ver: k3.13.0-37-generic
Network:   Card-1: Qualcomm Atheros QCA9565 / AR9565 Wireless Network Adapter driver: ath9k bus-ID: 03:00.0
           IF: wlan0 state: up mac: <filter>
           Card-2: Qualcomm Atheros QCA8172 Fast Ethernet driver: alx port: d000 bus-ID: 04:00.0
           IF: eth0 state: down mac: <filter>
Drives:    HDD Total Size: 4500.9GB (73.6% used) 1: id: /dev/sda model: HGST_HTS545050A7 size: 500.1GB
           2: USB id: /dev/sdc model: Expansion_Desk size: 4000.8GB
Partition: ID: / size: 89G used: 12G (15%) fs: ext4 ID: /home size: 362G used: 181G (53%) fs: ext4
RAID:      No RAID devices detected - /proc/mdstat and md_mod kernel raid module present
Sensors:   System Temperatures: cpu: 56.0C mobo: N/A
           Fan Speeds (in rpm): cpu: N/A
Info:      Processes: 218 Uptime: 8:43 Memory: 2374.2/3865.5MB Runlevel: 2 Gcc sys: 4.8.2 Client: Shell inxi: 1.8.4 
```

**Comment by bil-elmoussaoui** [comment]
Drag & drop from firefox is not working :)

**Comment by masterandros** [comment]
@telegramdesktop it doesnt work in windows 8.1 x64 like user dont work and if i execute telegram as a administrator equal.

**Comment by auchri** [comment]
Does not work with Google Chrome and Windows 8.1 too

**Comment by WillyWinkel** [comment]
Does not work from Photos 1.2 to Telegram 1.90.29673 on OS X El Capitan 10.11.1

**Comment by auchri** [comment]
@WillyWinkel see #914

**Comment by telegramdesktop** [comment]
@WillyWinkel Telegram 1.90 is another app :) not Telegram Desktop.

**Comment by vinimk** [comment]
Same problem with Firefox and 1.1.23 version

**Comment by ExecThTs** [comment]
The issue in a similar way is still present in TDesktop v1.2.6. Drag and drop works with Firefox, but `Copy image ` only works if the image is opened by a direct URL, otherwise the empty file error is shown.
Firefox is being ran with the same privileges as TDesktop -- user level. Running on Windows 10, 1709.

**Comment by john-preston** [comment]
@ExecThTs Does it work in alpha version from https://desktop.telegram.org/changelog#alpha-version?

**Comment by ExecThTs** [comment]
@john-preston Sorry, it does not. Choosing `Copy image` in FF and `Ctrl-V`ing into Telegram still results in the "Could not send an empty file: C:/Users/<username>/AppData/Local/Temp/<random filename>".  
Just as a note, this works in MSPaint.

**Comment by Red-Eyed** [comment]
I have the same issue with symbolic links on Ubuntu 18.04

**Comment by aydindemircioglu** [comment]
same here, symbolic link in ubuntu 18.04. give at least a proper warning, this "empty file" is irritating

**Comment by blackst0ne** [comment]
Same here.

**Comment by styleart** [comment]
Same problem on Linux Mint 19.1 (Cinnamon 4.0.10). Drag & Drop as well as copying in buffer doesn't work. Fails with PDF and PNG files (didn't try with other files).

**Comment by hakusaro** [comment]
I just wanted to chime in that this particular combination also creates the problem:
1. Pop! OS 20.04
2. Telegram desktop installed via Pop! Shop (Flatpak) (version 2.1.1)
3. Regolith Linux 1.4 / i3 installed

**Comment by ilya-fedin** [comment]
> Telegram desktop installed via Pop! Shop (Flatpak) (version 2.1.1)

You can't drag'n'drop with flatpak until you allow access to your home
