### ISSUE TITLE
GIFs from MP4 videos sent by Telegram Desktop don't play in Telegram Android or Telegram Web

### ISSUE THREAD

**Issue by ruanmed** [telegramdesktop/tdesktop#7641]
### Steps to reproduce
1. Create any MPEG-4 V2 video with no audio and codec ID mp42 (mp42/mp41/isom/iso2) with duration higher than 1 second;
2. Send this video via Telegram Desktop to any chat, channel or group;
3. Try to open/play the video (that is now a GIF) in Telegram Android or Telegram Web;

### Expected behaviour

Those no audio videos (GIFs) sent by Telegram Desktop should work in any other Telegram client or, if they can't be reproduced, they should offer a option to open in external player as happens when you send videos with audio in a "unsupported format".

Either that, or, if MPEG-4 V2 videos with no audio and codec ID mp42 (mp42/mp41/isom/iso2) are _unsupported_ by the main Telegram official clients as a GIF format, Telegram Desktop should not display them as supported GIFs.

### Actual behaviour
The no audio video (GIF) does not play at all in either Telegram Android or Telegram Web, stays either in a blank or black screen and no error is reported.

And I think might be a problem with Telegram Desktop, either of consistency across Telegram official supported formats for GIFs or some post-processing that should be done to those files, because when I send MPEG-4 videos with no audio and codec ID isom (isom/iso2/avc1/mp41) they work normally as GIFs in Telegram Android or Telegram Web.

### Configuration
**Operating system:** Linux Mint 19.3 Tricia

**Version of Telegram Desktop:** 2.0.1

**Installation source (Linux Only)** - the official website 

**Used theme**: Tinted (_Tingido_ in pt_BR)

**Comment by algspd** [comment]
+1

**Comment by Itja** [comment]
This is not stale and still an issue.

**Comment by Aokromes** [comment]
try on 2.4.8.

**Comment by Roboroads** [comment]
This is still an issue (on telegram web)
![image](https://user-images.githubusercontent.com/4398301/99058368-69336080-259d-11eb-9d7a-5dbae0b8b233.png)

**Comment by Fiercon** [comment]
Yep, still the same here on G-Chrome
![image](https://user-images.githubusercontent.com/9978390/99184489-8144e480-2743-11eb-8b16-586ed6f6a78c.png)

**Comment by teknoraver** [comment]
Same here

**Comment by teknoraver** [comment]
Request what? There are already enough information to reproduce it.

**Comment by teknoraver** [comment]
@Aokromes I confirm the bug is still in v2.5.8

**Comment by john-preston** [comment]
@teknoraver I'm not sure tdesktop should do anything about that.

Videos are just sent the same way as all other files, everybody shows them how they can. If some format isn't supported on mobile apps I'm not sure it should not be displayed as video with in-app playback in tdesktop, if tdesktop can play that format. It allows guys to share videos from desktop to desktop and view them without problems in-app. I think mobile apps should show correct error if they can't play the file.

**Comment by chainsaw-dev** [comment]
still a major issue ....

**Comment by susnux** [comment]
Notices this happens if the video is  `h264 (High 4:4:4 Predictive), yuv444p`
Instead of baseline

**Comment by mazzespazze** [comment]
Still an issue.

**Comment by eagle1maledetto** [comment]
Still an issue

**Comment by berzley** [comment]
Issue should be re-opened.

**Comment by teknoraver** [comment]
yes, reopen please

**Comment by susnux** [comment]
Only the @telegramdesktop team or @ruanmed can reopen

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/7641#issuecomment-781137844

**Comment by susnux** [comment]
> [#7641 (comment)](https://github.com/telegramdesktop/tdesktop/issues/7641#issuecomment-781137844)

They are not send as they are, but get converted to gif?
