### ISSUE TITLE
[Question] Black video preview

### ISSUE THREAD

**Issue by Khomyak-sibiryak** [telegramdesktop/tdesktop#7643]
Hello!

The videos that I download, by and large, have a black screen as a preview. It is not clear what kind of video this preview is. I watch this if the video starts from a black screen as a splash screen. Is it possible to change the creation of a preview to a random fragment, and not to the beginning of the video?

**Comment by ilya-fedin** [comment]
> Is it possible to change the creation of a preview to a random fragment, and not to the beginning of the video?

AFAIK, no, this is not possible
