### ISSUE TITLE
[Feature Request] Hide Folders

### ISSUE THREAD

**Issue by danialbehzadi** [telegramdesktop/tdesktop#7644]
Folders take a lot of horizontal space in tg-desktop. I always open Telegram and Firefox side by side, since telegram took a little space and I have plenty of space to work with browser. But with latest update, folders take a lot of space and there is not enough space for my browser.

I wish there was an option to hide folders bar in desktop.

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/7534
