### ISSUE TITLE
[Feature Request] Emotes color choice

### ISSUE THREAD

**Issue by Philoceratops** [telegramdesktop/tdesktop#7645]
Desktop Telegram keeps suggesting me emoticon's face skin color (for every single one). 
And I don't even know, whether I can unchoose, if I misclick it.

Can you please add an option in the settings to opt once for all emotes and change my at any time? 

It's relatively minor issue and if there's another solution I'll consider it, but for now it seems like I'll have to go through all of them manually.

**Comment by Philoceratops** [comment]
Still not solved, as far as I'm aware.

**Comment by ilya-fedin** [comment]
#3339
