### ISSUE TITLE
Warning when message arrives on a spesific channel or private session?

### ISSUE THREAD

**Issue by MohseniBigBoy** [telegramdesktop/tdesktop#7646]
When a message received on a group or private channel, I want play an Alarm on Linux OS. How to do this?

**Comment by RememberTheAir** [comment]
You can enable the notifications for these channels and groups

**Comment by MohseniBigBoy** [comment]
I want to play a long sound look like a music file or send an Email. Consider that I am asleep and a message arrives.

**Comment by ilya-fedin** [comment]
> How to do this?

Nohow
