### ISSUE TITLE
[Feature Request] Chat pinning in an order of descending importance

### ISSUE THREAD

**Issue by azat11** [telegramdesktop/tdesktop#7648]
Please make that when pinning chats to top they actually pin at the bottom of the pinned chats! Otherwise we have to, what, think of the most important chats last?!? It's logical that we pin things in order of importance starting from the most important, not backwards!

**Comment by Aokromes** [comment]
you can sort pinned things.

**Comment by azat11** [comment]
> 
> 
> you can sort pinned things.
> 
> https://mega.nz/#!9mITwaoa!b0-XBKXYKncqG-Xnrmk1MuPuRj0kyS-hyTm9oAnHEsM

How do I do that on desktop??

**Comment by Aokromes** [comment]
that's desktop.

**Comment by azat11** [comment]
> 
> 
> that's desktop. just click and drag and drop.

Thanks very much. I am a numpty. Partly. 'Cause it's still muuuch more convenient to pin chats automatically UNDER the already pinned ones.
Thus, still a feature request.
