### ISSUE TITLE
Memory RAM very loaded 

### ISSUE THREAD

**Issue by ImNexus** [telegramdesktop/tdesktop#7649]
Sorry my "English".

2.0.1 version telegram
Mac OS High Sierra 10.13.6 (17G65)

30 min usage:

![](https://user-images.githubusercontent.com/8022567/78329727-1d422700-758b-11ea-802c-2dc37eba8080.png)

I off in settings:

smiles, animations, autoload all files/images
I clear cache

Restart telegram

Slow scroll messages - high load RAM (Unlimited. RAM not clear. Sometimes, 30 min usage telegram = 10Gb RAM).

Video - https://cloud.mail.ru/public/5ie4/5MgambzAK

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/7361
