### ISSUE TITLE
[Unexpected behavior]Instagram preview not showing videos in specific case.

### ISSUE THREAD

**Issue by knomoseikei** [telegramdesktop/tdesktop#7652]
### Steps to reproduce
1. Receive a Instagram post with one photo and one video. Use this [link](https://www.instagram.com/p/B-gQj7KBOso/?igshid=pxo7mlqw7ccc) as example.
2. Check how it looks on your client.

### Expected behaviour
Show the preview of the photo and video. (taken from the mobile client)
![imagen](https://user-images.githubusercontent.com/7095013/79594598-ee57a500-80a2-11ea-91fd-deac0e0cdc73.png)

### Actual behaviour
Doesn't show the "1 of 2" advice neither the video as a second content.
![imagen](https://user-images.githubusercontent.com/7095013/79594741-3a0a4e80-80a3-11ea-9e3e-2f4fab150048.png)

### Configuration
**Operating system:**
Windows 10 Home Single Language
**Version of Telegram Desktop:**
2.0.1
**Used theme**: 
Tinted

**Comment by Aokromes** [comment]
pls supply the link to the instagram to save preston the time of hand type the whole url.

**Comment by Neurotoxin001** [comment]
Same with some tiktok videos, example:

https://www.tiktok.com/@zamik.official/video/6787695027138153733
https://www.tiktok.com/@asmr_ann_/video/6807848620306566405
![image](https://user-images.githubusercontent.com/39812401/79632675-8cae3e00-8169-11ea-98d3-d8a28f0a2111.png)

Not with all, some still can be downloaded:
https://www.tiktok.com/@gofetch/video/6815510962989288709
![image](https://user-images.githubusercontent.com/39812401/79632687-a2bbfe80-8169-11ea-9672-29eec2949c65.png)

**Comment by knomoseikei** [comment]
> ply the link to the instagram to save preston the time of ha

It's already on the Steps if you read carefully in the "link" word.

**Comment by Neurotoxin001** [comment]
Instagram seems like fine, but tiktok is still not showing videos

**Comment by Neurotoxin001** [comment]
> Instagram seems like fine, but tiktok is still not showing videos

**Comment by john-preston** [comment]
@Neurotoxin001 But this Is platform-wise anyway. I guess tik tok doesn't give its videos to crawlers.
