### ISSUE TITLE
[Bug] Dice expiration?

### ISSUE THREAD

**Issue by maxoku** [telegramdesktop/tdesktop#7659]
### Steps to reproduce
1. Go to saved message where you threw a dice

### Expected behaviour
I should see a big dice with a number

### Actual behaviour
I have a message that this message is not supported and should update to the latest version

### Configuration
**Operating system:** Windows 8.1
**Version of Telegram Desktop:** 2.0.1
**Used theme**: Day

I noticed this today, all dices from March 30 to April 15 are now unsupported messages.
Dices from April 16 (yesterday) and new throws are normally displayed.
![dice](https://user-images.githubusercontent.com/17256400/79642417-9fdb0100-819d-11ea-8e50-755754ec0c48.jpg)

**Comment by john-preston** [comment]
@maxoku What version exactly is shown in the left menu? Can you attach a screenshot of the bottom part of the left menu?

**Comment by maxoku** [comment]
@john-preston 
![telever](https://user-images.githubusercontent.com/17256400/79669132-b68f5100-81b9-11ea-8965-9319cd12cbeb.jpg)
Here, but why are you asking for it? 🧐

**Comment by maxoku** [comment]
Now in version 2.1 this old messages are invisible, but takes the same amount of space.

**Comment by Aokromes** [comment]
i supose the beta ones aren't supported anymore.

**Comment by maxoku** [comment]
But I can see them on mobile version.
