### ISSUE TITLE
Non standard appearance of Telegram window

### ISSUE THREAD

**Issue by guzszisvww** [telegramdesktop/tdesktop#7660]
Hello.

### Steps to reproduce
1. Launch the Telegram.

### Expected behaviour
The Telegram window should look like the windows of other programs.

### Actual behaviour
Why does the Telegram window not look like the windows of other programs? What should determine the appearance of the program window: OS settings or a violent non-standard fantasy of the developer?
Could you fix this, please?
![TelegramAppearance](https://user-images.githubusercontent.com/48548398/79681470-0c8be500-820a-11ea-92cd-04d69eceea43.png)

![photo_2020-04-09_20-03-19](https://user-images.githubusercontent.com/48548398/79681476-1281c600-820a-11ea-9299-b09938726cc9.jpg)

### Configuration
Windows 7, Windows 10 

**Version of Telegram Desktop:**
last

**Used theme**:
default

Thanks.

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/2958
