### ISSUE TITLE
Autostart does not work

### ISSUE THREAD

**Issue by msandres13** [telegramdesktop/tdesktop#7662]
### Steps to reproduce
1. Install Telegram using dnf
2. reboot
3. log in again

### Expected behaviour
Telegram-Desktop starts minimized and is visible in taskbar where Network, Bluetooth and so on is shown

### Actual behaviour
Telegram-Desktop seems to not start at all. When I check with ps aux I see the telegram-desktop process, anyways no sign on GUI.

### Configuration
**Operating system:**
Fedora 31 5.5.17-200.fc31.x86_64 Cinnemon Spin

**Version of Telegram Desktop:**
Version 2.01

**Installation source (Linux Only)** - the official website / GitHub releases / flatpak / snap / distribution package:
sudo dnf install https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm
sudo dnf install telegram

**Used theme**:
Standard Darktheme

Workaround:
edit file ~/.config/autostart/telegramdesktop.desktop 
add the following lines:
X-GNOME-Autostart-enabled=true
X-GNOME-Autostart-Delay=2

After log out / log in Telegram starts as expected minimized and icon shows in bar.

**Comment by ilya-fedin** [comment]
Can't reproduce, can you reproduce with a binary from github releases?

**Comment by Aokromes** [comment]
1 month without answer, if this bug is still valid open a new ticket.
