### ISSUE TITLE
[User Experience Improvement]

### ISSUE THREAD

**Issue by aminvahdatdm** [telegramdesktop/tdesktop#7663]
The caption editor or input text when sending pictures, is very small and limited. Actually, most users type the text in other places then copy and past it when sending pictures. Please change the picture caption editor and make it like the editors in chats.

![image](https://user-images.githubusercontent.com/63967901/79693522-242e9200-8239-11ea-9d98-b161eebe4e6c.png)

Also in groups there is no mention suggestion, when we send pics. We should memorize people's usernames and type it correctly!

![image](https://user-images.githubusercontent.com/63967901/79693572-68ba2d80-8239-11ea-86be-e5ea63e84ac1.png)

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/2060
