### ISSUE TITLE
[Feature Request] Notifications should respect full-screen applications

### ISSUE THREAD

**Issue by token0** [telegramdesktop/tdesktop#7665]
### Is your feature request related to a problem?
Telegram shows notification toast even if some full-screen application active (e.g. video game is running in full-screen mode). So, showing notification toast steals focus, and full-screen changes to desktop mode. It's very frustrating. (Yes, I know about "disable notifications", but TD should not steal focus anyway).

### Describe the solution you'd like
Add option to suppress notification toast and/or focus stealing if full-screen mode is detected (or if current mode differs from default desktop mode).

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/2290
