### ISSUE TITLE
Telegram for Windows can't open message with attached contact.

### ISSUE THREAD

**Issue by tackin** [telegramdesktop/tdesktop#7668]
### Steps to reproduce
1. attache a contact from your phone to a message.
2. send that message to a person
3. person opens message on his phone and can see the complete message with the contact-informations

### Expected behaviour
person see the attached contact in Telegram-Desktop same as on his telegram-app on android.

### Actual behaviour
person on Telegram-Desktop only sees a message with a phone-no. but not the hole contact-informations (like mail-addresses, private-tel, etc.)

### Configuration
**Operating system:**
Windows 8
**Version of Telegram Desktop:**
V 2.0.1

**Comment by john-preston** [comment]
@tackin Yes, sorry, v-card format is not supported in Telegram Desktop right now.
