### ISSUE TITLE
Adaptive layout for wide screens not possible with interface scale

### ISSUE THREAD

**Issue by set92** [telegramdesktop/tdesktop#7669]
### Steps to reproduce
1.  Go to Settings
2.  Set default interface scale to anything except 100%
3.  Go to Chat Settings and adaptive layout for wide screens would not appear in Chat background.

### Expected behaviour
Adaptive layout for wide screens should appear all the times, no? I have a dell xps 13 9350, which has a resolution of ~4k in a screen of 13", so I want the text bigger, hence the interface scale to 150%, but I want the adaptive layout for wide screens off.

### Actual behaviour
If I am in 150% interface scale and go to chat settings, I don't see the adaptive layout for wide screens on chat background.

### Configuration
**Operating system:** Windows 10

**Version of Telegram Desktop:** 2.0.1

**Used theme**: Default

**Comment by john-preston** [comment]
@set92 If you don't see the checkbox then the layout should not be enabled anyway, because the window is too small.

**Comment by yashpalgoyal1304** [comment]
thats nice. see: https://github.com/telegramdesktop/tdesktop/issues/1629#issuecomment-477859804
