### ISSUE TITLE
Stop replacing << and >> with « »

### ISSUE THREAD

**Issue by Noiwex** [telegramdesktop/tdesktop#767]
Just stop, please. It violates my text integrity, I didn't allow you to do so.

**Comment by Noiwex** [comment]
Sorry, but this thing just pissed me off right now when I was sharing some lines of code with my colleague.

**Comment by Walkman100** [comment]
Pisses me off too, you're not alone :confounded:

**Comment by cobalto** [comment]
Agreed

**Comment by pozimi** [comment]
and the character ~ will be replacerd with and -

**Comment by Mindstormer619** [comment]
:+1:

**Comment by Streppel** [comment]
:+1:

**Comment by Aokromes** [comment]
Maybe a setting to enable / disable this can be a good idea.

**Comment by lbguilherme** [comment]
+1

**Comment by Mindstormer619** [comment]
But really, why in the world would this be enabled? This is just not a good design choice.

**Comment by auchri** [comment]
Duplicate #522
