### ISSUE TITLE
[Feature Request] Implement control-a, control-e bindings

### ISSUE THREAD

**Issue by jroelofs** [telegramdesktop/tdesktop#7671]
It would be nice if the message box respected the normal unix convention where:

*  Control-A sends the cursor to the beginning of the line
*  Control-E sends the cursor to the end of the line

This is a pretty common UX thing among browsers and in the terminal.

**Comment by ilya-fedin** [comment]
But Ctrl+A already selects the text
And Ctrl+E does nothing in browsers, at least in firefox :thinking:

**Comment by jroelofs** [comment]
On Mac, Command-A is select-all. In browsers, I'm referring to input boxes (try it out on the addressbar too).

**Comment by ilya-fedin** [comment]
> try it out on the addressbar too

ctrl+a - select all
ctrl+e - nothing

**Comment by jroelofs** [comment]
Maybe this is a mac/unix-specific UX thing? What OS are you trying from?

**Comment by ilya-fedin** [comment]
Linux with MATE

**Comment by jroelofs** [comment]
Turns out this is a MacOS-specific behavior: https://en.wikipedia.org/wiki/Table_of_keyboard_shortcuts#Text_editing
