### ISSUE TITLE
Crash when trying to unpin chat in a folder after leaving or deleting another pinned chat

### ISSUE THREAD

**Issue by damnfella** [telegramdesktop/tdesktop#7674]
### Steps to reproduce
1. Use an existing channels folder or Create folder with the chat type "Channels" 
2. Pin 2 or more channels
3. Leave one of the pinned channel
4. Exit Tdesktop
5. Start Tdesktop
6. Try to unpin any other channel in that folder

### Expected behaviour
It should just unpin. 

### Actual behaviour
The tdesktop app crashes when you try to unpin any other chat in the same folder.

### Some other observations I noticed: 
- A screenshot of the left/deleted pinned channel when you edit the folder:
![image](https://user-images.githubusercontent.com/51771172/79826327-0a1bbd80-83b9-11ea-9157-752a69efcf09.png)

- If you try to remove the blank chat (refer screenshot above) from the edit folder dialog and save, it will crash. Crash also occurs when trying to remove other chats, while this blank entry is present.

- Rejoining all the "pinned" channels resolves the crash issue. 

- No crash if you unpin first and then leave.

### Configuration
**Operating system: Windows 10 (1803)**

**Telegram Desktop 2.0.1**

**Used theme**: Any, default

**Logs:** https://github.com/telegramdesktop/tdesktop/files/4507861/log.txt

**Comment by ilya-fedin** [comment]
Is this still valid?

**Comment by Aokromes** [comment]
@damnfella

**Comment by damnfella** [comment]
This issue appears to be fixed today. No more crashing.

**Comment by damnfella** [comment]
However, it appears that this related problem is not fixed:
![image](https://user-images.githubusercontent.com/51771172/99511074-b50c4e00-297f-11eb-9b0a-1c6df19f6319.png)

In some cases, the channel that I left, its icon and name are preserved in the folder's list of "included chats". But if you rejoin that channel, the channel is not pinned in the folder again.

The channel that I left is only removed from the folder's "included chats", if I pin another channel in that folder. After that, a restart of the app may be required to finally correct the folder's "included chats" list.
