### ISSUE TITLE
Exiting a tdesktop portable crashes another portable instance which is logged in with same account

### ISSUE THREAD

**Issue by damnfella** [telegramdesktop/tdesktop#7675]
### I can't exactly reproduce this:
If two portable tdesktop apps are running with the same account, somewhere after interaction similar to issue #7674, if you exit the 1st App, the 2nd App will also crash (settings sync ?). Note that the 2nd app is just left alone without user directly interacting with it. 

Try actions like unpin-leave, leave-unpin, etc in the 1st App. The 2nd App crashes after you exit the 1st App.

### Expected behaviour
The other Portable App shouldn't crash

### Configuration
- I am not using multi-account feature here. The portables are running from two different locations on the same machine.
**Operating system: Windows 10 (1803)**
**Version of Telegram Desktop: 2.0.1**
**Used Theme: Default, anything works**

**Comment by ilya-fedin** [comment]
Crash report tag is needed

**Comment by Aokromes** [comment]
@damnfella plz post crash id.

**Comment by Aokromes** [comment]
@damnfella

**Comment by damnfella** [comment]
Sorry, too lazy to reproduce this issue. I'll have to download that version again. And I don't know exactly how this issue takes place. Some uncertainty there. Idk if a different version of Telegram is required to reproduce the crash. Or if it has something to do with Windows. ¯\_(ツ)_/¯
