### ISSUE TITLE
[Feature Request] Inform "This file exceeds the default file size (50 Mb) to be automatically downloaded by peers." for large uploads

### ISSUE THREAD

**Issue by davidhedlund** [telegramdesktop/tdesktop#7676]
### Is your feature request related to a problem?
No.

### Describe the solution you'd like
If I upload a large animated GIF (say 35 Mb) in a channel it will be visible for me automatically but not for other people, they must download it manually. And I'm not informed that "This file must be downloaded by other people to play it." when I upload it. The point with animated GIFs is to automatically make the visible for other people. Not just GIFs, but all media formats can be played.

**Comment by davidhedlund** [comment]
Also, what is the file size limitation for files to not be played automatically?

**Comment by john-preston** [comment]
@davidhedlund Anyone can change those settings in their app Settings depending on their internet speed and price.

**Comment by davidhedlund** [comment]
Thanks. A message saying "This file is larger than the default file size (50 Mb), it will not be played automatically for most people." could still be useful to display.

**Comment by davidhedlund** [comment]
> @davidhedlund Anyone can change those settings in their app Settings depending on their internet speed and price.

Thanks. A message saying "This file is larger than the default file size (50 Mb), it will not be played automatically for most people." could still be useful to display.

**Comment by davidhedlund** [comment]
@Aokromes Thanks.
