### ISSUE TITLE
[Feature Request] More configuration options for folders creation

### ISSUE THREAD

**Issue by ElderOrb** [telegramdesktop/tdesktop#7677]
Now, when we've got folders (great feature btw, I can finally switch to telegram as the primary messenger) please introduce more options for configuring it. 

1. Would be great to get ability to create dynamic folder based on some criteria, like 'if title contains 'announce' - channel/chat/whatever should belong to 'news' folder'
2. Special folder for all 'mentioned' (people writing to me directly) cases.

**Comment by Aokromes** [comment]
very likely this will need api support.

**Comment by Ryder17z** [comment]
I would also like to see an "exclusive mode" - any chats/groups inside an "exclusive" folder wouldn't show in the list of chats that can be added to another folder.

**Comment by finalchild** [comment]
I suggest adding criterions like "if the description contains #my_team" or "if title starts with [My-Team]".

**Comment by Ryder17z** [comment]
stay away stalebot!

**Comment by ElderOrb** [comment]
Haha, good job @Ryder17z ;)

**Comment by Aokromes** [comment]
such feature belongs to https://bugs.telegram.org/
