### ISSUE TITLE
[Feature Request] Channel stats

### ISSUE THREAD

**Issue by Neurotoxin001** [telegramdesktop/tdesktop#7678]
### Is your feature request related to a problem?
It's little bit annoying to every time open iOS/Android app to view channel stats.

### Describe the solution you'd like
Make able users to see the channel stats on Telegram Desktop.

It's been released for mobile apps a month ago:
https://telegram.org/blog/folders

But there is still no channel stats on Telegram Desktop.

**Comment by samij263** [comment]
any update for stats??

**Comment by seth-rah** [comment]
Channel statistics still inaccessible on telegram desktop.

Version 2.1.12

**Comment by Neurotoxin001** [comment]
+

**Comment by Neurotoxin001** [comment]
![image](https://user-images.githubusercontent.com/39812401/97973368-0391e800-1dd7-11eb-8e3c-9111c9550914.png)

I hope TDesktop will get this too.

**Comment by Neurotoxin001** [comment]
Why there is still no channel stats? It's been released 10 months ago, come on

**Comment by MasterGroosha** [comment]
Commenting the issue to prevent it from being autolocked by GitHub bot. The feature request is still relevant

**Comment by Neurotoxin001** [comment]
You can also like it here:
https://bugs.telegram.org/c/1079

**Comment by john-preston** [comment]
@MasterGroosha Open issues won't be auto locked, only closed inactive ones are.

**Comment by alambertt** [comment]
> You can also like it here:
> https://bugs.telegram.org/c/1079

Done! This feature would be awesome for Desktop App

**Comment by Neurotoxin001** [comment]
Even web version have stats now, lol
https://web.telegram.org/z/

**Comment by RememberTheAir** [comment]
One of the reason I've always thought implementing chat statistics in tdesktop was that you needed a JS parser/renderer or an ambedded browser to properly display stats plottings & graphs. Has anything changed in the past year?

**Comment by ayebrian** [comment]
is there any chance it will be added this year?

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/releases/tag/v4.10.4
