### ISSUE TITLE
[Feature Request] Export - Import - Share chat folders

### ISSUE THREAD

**Issue by marcocastignoli** [telegramdesktop/tdesktop#7683]
### Is your feature request related to a problem?
Right now it's impossible to create "communities" formed by a series of channels/groups/chat

### Describe the solution you'd like
The ability to share a folder of chats would empower users to create communities on telegram. For example an open source project could group #development #general #questions channels into a folder, and then share that folder on their website, one a user click on that link telegram automatically creates the folder containing the channels.
It would be the first reliable alternative to closed source Discord and Slack.

**Comment by Aokromes** [comment]
that will need api support.

**Comment by marcocastignoli** [comment]
Then which one is the place to publish this feature request? :)

**Comment by Aokromes** [comment]
in app feature.

**Comment by MasterGroosha** [comment]
@Aokromes you mean in-app support?

**Comment by Aokromes** [comment]
yes.
