### ISSUE TITLE
Group links aren't opening properly in Telegram

### ISSUE THREAD

**Issue by NirvanaDraavon** [telegramdesktop/tdesktop#7685]
Title.

Whenever I open a group link on a web browser, the application comes up and does nothing.

Here is an example of the log file that gets produced:

[2020.04.22 10:00:38] Launched version: 2000001, install beta: [FALSE], alpha: 0, debug mode: [FALSE], test dc: [FALSE]
[2020.04.22 10:00:38] Executable dir: D:/Telegram Desktop/, name: Telegram.exe
[2020.04.22 10:00:38] Initial working dir: C:/Program Files/Mozilla Firefox/
[2020.04.22 10:00:38] Working dir: D:/Telegram Desktop/
[2020.04.22 10:00:38] Command line: D:\Telegram Desktop\Telegram.exe tg://join?invite=###################
[2020.04.22 10:00:38] Executable path before check: D:/Telegram Desktop/Telegram.exe
[2020.04.22 10:00:38] Logs started
[2020.04.22 10:00:38] Connecting local socket to Global\bacdea0964705717ba4509b541a84234-{87A94AB0-E370-4cde-98D3-ACC110C5967D}...
[2020.04.22 10:00:38] Socket connected, this is not the first application instance, sending show command...
[2020.04.22 10:00:38] Show command written, waiting response...
[2020.04.22 10:00:38] Show command response received, pid = 26360, activating and quitting...

**Comment by NirvanaDraavon** [comment]
Update...noticed a disparity when using Telegram on a different system...

When opening the link would work, the log line would read as follows:

[2020.04.22 10:00:38] Command line: D:\Telegram Desktop\Telegram.exe -- tg://join?invite=###################

The '--' is missing for some reason in the log of my original version...any clue why this occurs?

**Comment by NirvanaDraavon** [comment]
Update...there is a workaround for this, but it is very inconvenient.

Copying the web invite link and then pasting into a telegram chat, then clicking on it will auto default on Telegram and somehow forces it to open with the join chat prompt.

I don't understand this, but it works I guess. Very annoying though.

**Comment by bkamapantula** [comment]
thanks @NirvanaDraavon! that worked for me.

**Comment by txtsd** [comment]
Happening to me on linux too #8626

**Comment by squromiv** [comment]
The same problem. Last version of Telegram Desktop.

**Comment by txtsd** [comment]
@squromiv @bkamapantula @NirvanaDraavon  can you try changing the entry for tg:// links in firefox like here: https://github.com/telegramdesktop/tdesktop/issues/8626#issuecomment-720659161

**Comment by bkamapantula** [comment]
@txtsd I updated from "Always ask" to as below ("Use System handler (default)") and that worked

![image](https://user-images.githubusercontent.com/1143687/98370334-52878980-2032-11eb-8c86-1dabc472196b.png)

using "Use Telegram Desktop" didn't open any native app prompt.

**Comment by txtsd** [comment]
@bkamapantula Thanks for your feedback. Hopefully it'll help the devs pinpoint the issue.

**Comment by squromiv** [comment]
> can you try changing the entry for tg:// links in firefox
Yes, this half-decision works with FF.

But what about support of opening tg-links directly in Telegram-desktop, bypassing browser?

I set Tgdesktop as default application for files *.tg (contain tg-links). And I see the same behavior, opening them from OS Windows 8.1: application doesn`t switch to necessary channel. Is there any idea, how to force this feature?
![1](https://user-images.githubusercontent.com/15985877/98807945-77ae3a80-242c-11eb-8508-1a555d562fc3.png)
![2](https://user-images.githubusercontent.com/15985877/98807951-7aa92b00-242c-11eb-95f4-67416d7de7b9.png)
![3](https://user-images.githubusercontent.com/15985877/98807958-7e3cb200-242c-11eb-845f-d6ee70873ded.png)
![4](https://user-images.githubusercontent.com/15985877/98807960-80067580-242c-11eb-83b8-4c5b547d640f.png)

**Comment by ilya-fedin** [comment]
> But what about support of opening tg-links directly in Telegram-desktop, bypassing browser?

Just use the standard Windows way for this
![image](https://user-images.githubusercontent.com/17829319/99178503-9f8eee00-270b-11eb-8879-a92f41bfbd67.png)

**Comment by squromiv** [comment]
> Just use the standard Windows way for this
I know, how to create shortcuts. What is about opening them in telegram??? I see the same behavior, as described in the first message of this topic:
> the application comes up and does nothing

**Comment by ilya-fedin** [comment]
¯\_(ツ)_/¯ it works for me

**Comment by squromiv** [comment]
> ¯_(ツ)_/¯ it works for me

What version of Windows and TG?

**Comment by ilya-fedin** [comment]
TG versionis 2.4.7, Windows 10 LTSC in a virtual machine

**Comment by squromiv** [comment]
> TG versionis 2.4.7, Windows 10 LTSC in a virtual machine

Can you please upload video or GIF of opening tg-link directly in TG?

**Comment by ilya-fedin** [comment]
No, I just wanted to show you about this standard way since creating a .tg file with link seems like something weird for me

**Comment by squromiv** [comment]
@bot F*ck you

**Comment by ilya-fedin** [comment]
I believe it is firefox misconfiguration rather than a tdesktop bug. I'm sure if you try with Chromium, everything wil work properly.

**Comment by ilya-fedin** [comment]
@Aokromes can you add 'waiting for answer' to let the bot close the issue if no one refute my assumption?
