### ISSUE TITLE
Microphone is not working at all

### ISSUE THREAD

**Issue by vslynko** [telegramdesktop/tdesktop#7687]
### Steps to reproduce
1. Go to menu 'Calls' -> 'Call Settings'
2. Set Input Device -> Default
3. Click 'Test Microphone'
4. Talk to microphone

### Expected behaviour
I expect:
- Windows 10 notification area shows the mic sign, indicating that some app is using a mic
- Volume meter under the 'Test Microphone' button shows some input signal level

### Actual behaviour
- The microphone is not captured by the 'Telegram' application
- There is no audio input during testing microphone
- When in call the voice is not transmitted to the other side

### Configuration
**Operating system:**
- Windows 10 1909 - latest updates
- Microphone: Rode Podmic
- Audio Interface: Focusrite Scarlett Solo (3rd Gen); Firmware 1605
  * Sample rate: 48 kHz
  * Buffer size: 256
- Audio Interface is set as default recording device in windows 10

**Version of Telegram Desktop:**
2.0.1

**Installation source (Linux Only)** - the official website / GitHub releases / flatpak / snap / distribution package:

**Used theme**: Classic

<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/7296
