### ISSUE TITLE
Voice call not working

### ISSUE THREAD

**Issue by vslynko** [telegramdesktop/tdesktop#7688]
### Steps to reproduce
1. Receive a voice call from a contact
4. Talk to microphone

### Expected behaviour
I expect:
- Other party can hear me
- Windows 10 notification area shows the mic sign, indicating that some app is using a mic

### Actual behaviour
- Other party cannot hear me
- The microphone is not captured by the 'Telegram' application

### Configuration
**Operating system:**
- Windows 10 1909 - latest updates
- Microphone: Rode Podmic
- Audio Interface: Focusrite Scarlett Solo (3rd Gen); Firmware 1605
  * Sample rate: 48 kHz
  * Buffer size: 256
- Audio Interface is set as default recording device in windows 10

**Version of Telegram Desktop:**
2.0.1

**Used theme**: Classic

### Related
#7296 - due to this bug I cannot test the mic. But in #7296 - its mentioned that the voice call works. So, it's not a dublicate
#7687 - mentions this ticket and #7296 in one

**Comment by Aokromes** [comment]
try to click calls->settings and check what device is show there, maybe you have some other audio device stealing input.

**Comment by vslynko** [comment]
@Aokromes - input device is set as expected "Focusrite USB (Focusrite USB Audio)"

**Comment by sli** [comment]
I've also tried to switch to the specific input device I use to no avail. No functional way to input audio on v2.2 in Windows 10.

**Comment by ilya-fedin** [comment]
I guess this information would be helpful: https://github.com/telegramdesktop/tdesktop/issues/7562#issuecomment-673643903

**Comment by meucd** [comment]
> 
> 
> try to click calls->settings and check what device is show there, maybe you have some other audio device stealing input.

Where is this in the application? I cannot find it.

**Comment by Aokromes** [comment]
> > try to click calls->settings and check what device is show there, maybe you have some other audio device stealing input.
> 
> Where is this in the application? I cannot find it.

hamburger -> calls -> settings icon.

**Comment by zaid894** [comment]
I have the same problem 
the microphone is not working inside telegram calls only thought it is apppearing here 

![microphone](https://user-images.githubusercontent.com/37776063/92325564-88b98480-f054-11ea-9a0c-4f731d7279c6.PNG)

**Comment by ilya-fedin** [comment]
>     * Focusrite Scarlett Solo

This is a known problematic sound card, look #1548

**Comment by meucd** [comment]
> 
> 
> > > try to click calls->settings and check what device is show there, maybe you have some other audio device stealing input.
> > 
> > 
> > Where is this in the application? I cannot find it.
> 
> hamburger -> calls -> settings icon.


![nosuchoption](https://user-images.githubusercontent.com/16794562/92331619-fb166e80-f02c-11ea-947d-d170c152f7fa.png)

**Comment by ms-boom** [comment]
same problem on ubuntu 20.04
Telegram 2.4.4
Can send audio message.
Microphone is not working in calls and "Call Settings"
![image](https://user-images.githubusercontent.com/14200546/97594204-3e390080-1a24-11eb-83b6-cd5a86b1ce66.png)

**Comment by ilya-fedin** [comment]
Is this still valid?

**Comment by vslynko** [comment]
> 
> 
> Is this still valid?

It looks like it works now. Both in calls and in input device level indicator.
