### ISSUE TITLE
mic not working

### ISSUE THREAD

**Issue by rss9090** [telegramdesktop/tdesktop#7690]
### Steps to reproduce
1. Windows 7 PC
2. Telegram for desktop 2.01
 
### Expected behaviour
working microphone in app

### Actual behaviour
Microphone not working in Telegram for desktop while Skype for desktop and Viber for desktop installed on the same system are Ok with it.
Mic test in Telegram showing nothing. Selected input device correct.

### Configuration
Windows 7 x86 Ultimate

**Version of Telegram Desktop:**
Telegram 2.01 or latest

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/7688 ?
https://github.com/telegramdesktop/tdesktop/issues/7296 ?

**Comment by rss9090** [comment]
@Aokromes 
After sound card drivers reinstallation and Telegram for desktop client reinstallation mic become alive in Telegram too but mic test still not responding. So #7296 seems confirmed.
