### ISSUE TITLE
Status Bar Logo is missing on Ubuntu 20.04

### ISSUE THREAD

**Issue by komape** [telegramdesktop/tdesktop#7692]
### Steps to reproduce
1. Install Telegram Desktop on a Computer with Ubuntu 20.04
2. Start Telegram
3. Minimize Telegram

### Expected behaviour
The Telegram logo should appear in the status bar

### Actual behaviour
Only three dots appear

### Configuration
**Operating system:**
Ubuntu 20.04

**Version of Telegram Desktop:**
2.0.1

**Installation source (Linux Only)** - the official website / GitHub releases / flatpak / snap / distribution package:
https://ubuntu.com/download

**Used theme**:
Dark

Look for the three dots left from the wifi icon.
![Screenshot from 2020-04-24 10-02-52](https://user-images.githubusercontent.com/25869589/80189389-e05dd300-8612-11ea-9420-ba139b0b73de.png)

**Comment by komape** [comment]
Now, it's back there.

![Screenshot from 2020-04-24 10-35-02](https://user-images.githubusercontent.com/25869589/80192325-477d8680-8617-11ea-9312-1bbbdb3fff55.png)

**Comment by ilya-fedin** [comment]
> **Installation source (Linux Only)** - the official website / GitHub releases / flatpak / snap / distribution package:
> https://ubuntu.com/download

Very fun
