### ISSUE TITLE
Chat font doesn't support many unicode (that are otherwise supported on my system), doesn't fallback to other characters

### ISSUE THREAD

**Issue by increpare** [telegramdesktop/tdesktop#7693]
### Steps to reproduce
1. say "ꆰᱦↆ" in chat
2. observe lots of UTF-character-not-found squares

<img width="136" alt="Bildschirmfoto 2020-04-24 um 10 28 19" src="https://user-images.githubusercontent.com/465632/80191667-51eb5080-8616-11ea-97f0-93a7090c9b5d.png">

### Expected behaviour
Tell us what should happen

I should see the correct characters - it should probably fallback to a built-in-mac UTF-supporting font if characters aren't found in the telegram one.

Here's how it renders in Finder

<img width="69" alt="Bildschirmfoto 2020-04-24 um 10 28 03" src="https://user-images.githubusercontent.com/465632/80191644-4861e880-8616-11ea-926f-941226b55c34.png">

### Actual behaviour
Tell us what happens instead

I get UTF unknown character symbols.

### Configuration
**Operating system:**
MacOS 10.15.4 (19E287)

**Version of Telegram Desktop:**
Telegram Lite 2.0.1

**Used theme**:

Klassisch (Classic? I use it in German)

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/6056

**Comment by pguimier** [comment]
I got 
![janwileni_bug](https://user-images.githubusercontent.com/16780265/80192198-1ef58c80-8617-11ea-84fc-0109dfbf366f.png)

under Telegram desktop 2.0.1 under linux 64 with dark mode, in french.
