### ISSUE TITLE
Any working build for mac32?

### ISSUE THREAD

**Issue by e1z0** [telegramdesktop/tdesktop#7694]
I've been checking all official and unofficial builds for mac and it seems that all of them are 64bit only (Telegram: Mach-O 64-bit executable x86_64). The main question is there an official build for mac os x >=10.6 32bit?

Thanks!

**Comment by Aokromes** [comment]
https://updates.tdesktop.com/tmac32/tsetup32.1.8.15.dmg

**Comment by e1z0** [comment]
it's Mach-O 64-bit executable x86_64 too

**Comment by Aokromes** [comment]
strange, it's named "32" wtf.

**Comment by john-preston** [comment]
@Aokromes No, all macos version were always 64 bit, sorry.
