### ISSUE TITLE
[Feature Request] Add option to disable animated video preview

### ISSUE THREAD

**Issue by tarwirdur** [telegramdesktop/tdesktop#7695]
similar to #6234

### Is your feature request related to a problem?
Animation in chat is very annoying. And it can't be disabled in settings

### Describe the solution you'd like
Add option to disable video preview.

**Comment by tux93** [comment]
Autoplay can already be disabled in Settings -> Advanced -> Automatic media download
![Screenshot_2020-04-24_19-57-01](https://user-images.githubusercontent.com/1749593/80242639-f34dc300-8665-11ea-980d-f1d5d35da76d.png)
