### ISSUE TITLE
Mac does not download photos/files in chat

### ISSUE THREAD

**Issue by ValeryDubrava** [telegramdesktop/tdesktop#7698]
### Steps to reproduce
1. Receive a photo or file in the direct chat

### Expected behaviour
Photo should be downloaded and shown in the chat.

### Actual behaviour
Downloading is in progress infinity.

### Configuration
MacOS Mojave, 10.14.6

**Version of Telegram Desktop:** 2.1

**Used theme**: Tinted

I checked download folder - it exists. I changed it to temporary and custom - the same result. It happened only in one chat, but very important for me. There are 1755 photos and some of the photos are still unavailable in the desktop version. It works perfectly on mobile version.
I've checked hard drive - 100 GB is available on mac.

**Comment by Aokromes** [comment]
this issue is still valid?

**Comment by Aokromes** [comment]
no answer after more than 1 month, closing, if this bug is still valid open a new ticket using updated telegram version.
