### ISSUE TITLE
Telegram desktop linux closes when browsing stickers

### ISSUE THREAD

**Issue by rodoviario** [telegramdesktop/tdesktop#7699]
### Steps to reproduce
1. Start Telegram Desktop
2. Go to saved messages
3. Open the menu in the smiling face
4. Select stickers tab
5. Select the rounded plus sign to go to online library
6. Scroll down with mouse wheel to see the catalog
7. Before reaching the 20th entry, telegram will close

### Expected behaviour
Tell us what should happen
You should be able to see more that 10-20 sticker packs
### Actual behaviour
Tell us what happens instead
The program closes
### Configuration
**Operating system:**
Linux Mint 19.3 Tricia de 64-bit - based on Ubuntu 18.04.3 LTS
Kernel Linux 5.3.0-46-generic x86_64
MATE 1.22.2 desktop
AMD A10-7860K Radeon R7, 12 Compute Cores 4C+8G × 4 
RAM: 8Gb
Video Card: Nvidia GForce 210, closed source driver
**Version of Telegram Desktop:**
2.1 installed on April 24
**Installation source (Linux Only)** - the official website / GitHub releases / flatpak / snap / distribution package:
the official website / automatic update
**Used theme**:
Customized Sparking Blue / Night mode
<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by Sepehrtooz** [comment]
It also crashed for me (on Windows) when I saw all the new stickers, and after that, it didn't crash.

**Comment by Magnus512** [comment]
The same for me, Ubuntu 20.04... Go to stickers tab "+", and scrolling up and down just one moment, doesn't even reach 20 stickers.

**Comment by Aokromes** [comment]
> The same for me, Ubuntu 20.04... Go to stickers tab "+", and scrolling up and down just one moment, doesn't even reach 20 stickers.
> 
> Terminal output...
> `~/.local/share/Telegram$ ./Telegram error: : cannot open error: : cannot open error: : cannot open Abortado (`core' generado)`

plz, can you run it under gdb?

**Comment by Magnus512** [comment]
> > The same for me, Ubuntu 20.04... Go to stickers tab "+", and scrolling up and down just one moment, doesn't even reach 20 stickers.
> > Terminal output...
> > `~/.local/share/Telegram$ ./Telegram error: : cannot open error: : cannot open error: : cannot open Abortado (`core' generado)`
> 
> plz, can you run it under gdb?

It works now

**Comment by rodoviario** [comment]
I guess its working now in 2.1.1

Haven't been able to reproduce it again
