### ISSUE TITLE
VS 2010

### ISSUE THREAD

**Issue by Mercoolov** [telegramdesktop/tdesktop#770]
Hello!
Is it possible to compile the project with VS 2010?

**Comment by Aokromes** [comment]
Well readme shows instructions to compile with VS 2013, you can get VS 2013 community edition for free from https://www.visualstudio.com/en-us/products/visual-studio-community-vs.aspx

**Comment by Mercoolov** [comment]
The problem is I work with Windows XP and so I can't install VS 2013

**Comment by auchri** [comment]
You should consider to update to windows 8 or windows 10 :)

**Comment by soren121** [comment]
@Mercoolov Windows XP reached End-Of-Life status a year ago. Microsoft has not released any updates for it since. Why should Telegram support XP when Microsoft doesn't?
