### ISSUE TITLE
Ability to send messages in channel without being admin

### ISSUE THREAD

**Issue by KnorpelSenf** [telegramdesktop/tdesktop#7703]
### Steps to reproduce
1. Open a channel such as this one: https://t.me/tgbeta
2. Scroll to a bullseye or dice message such as this one: https://t.me/tgbeta/4047
3. Click it and watch the info tooltip appear
4. Hit SEND

### Expected behaviour
The send button is not visible (as is the case on all other platforms). After all, you're not an admin of the channel, so it makes no sense to display a send button.

### Actual behaviour
The send button is displayed. When clicked, a message is added to the channel, the icon idicating a pending delivery. Of course, the message is never actually sent, it just pollutes the channel. It is gone again after restarting the application.

### Configuration
**Operating system:** Linux/Debian Stretch (but probably all other platforms, too—haven't tested this, though) (**EDIT**: Windows 10 is affected as well)

**Version of Telegram Desktop:** 2.1

**Installation source (Linux Only)** - the official website / GitHub releases / flatpak / snap / distribution package: the official website (again, this most likely applies to all)

**Used theme**: night

**Comment by Aokromes** [comment]
i am sure this is duplicate.

**Comment by ilya-fedin** [comment]
No, this is about the new feature :)

**Comment by MasterGroosha** [comment]
I'm afraid the issue title is a bit confusing.

**Comment by KnorpelSenf** [comment]
> i am sure this is duplicate.

I skimmed through the past few hundred issues and I didn't find a related case. Moreover, it's a about a feature introduced in today's update.



> I'm afraid the issue title is a bit confusing.

I agree, it may sound like it's possible to actually deliver the message, I just couldn't come up with a concise wording for “you can trick the client into trying to send a message while not actually sending it but instead appending it to the local message log” … any suggestions?

**Comment by Aokromes** [comment]
> No, this is about the new feature :)

yeah but a ticket of you can send messages to channels even you aren't allowed used to exist.

**Comment by KnorpelSenf** [comment]
> > No, this is about the new feature :)
> 
> yeah but a ticket of you can send messages to channels even you aren't allowed used to exist.

The only thing I could find is #1247 which dates back to 2015. Were you talking about this?

**Comment by Aokromes** [comment]
i think it's another, the keywords to search are to common xd

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/4348

**Comment by KnorpelSenf** [comment]
I see your point, but that's a different issue IMO. I'm really just talking about hiding the send button in the info for the new message types ;)
