### ISSUE TITLE
A bug which you hasn't fixed it for a long time!

### ISSUE THREAD

**Issue by Sepehrtooz** [telegramdesktop/tdesktop#7704]
I have reported this bug seven months ago #6525
This gif explaines the bug:

![GIF 4-24-2020 17-48-52](https://user-images.githubusercontent.com/55192376/80244677-99a5c280-867e-11ea-8d34-8b67c08634ec.gif)

**Version of Telegram Desktop: 2.1**

**Comment by Aokromes** [comment]
don't re-report already opened issues.

**Comment by Sepehrtooz** [comment]
> don't re-report already opened issues.

Well, fix it so we won't report it again.

**Comment by Aokromes** [comment]
> > don't re-report already opened issues.
> 
> Well, fix it so we won't report it again.

that's not how a bug tracker works.

**Comment by Sepehrtooz** [comment]
> > > don't re-report already opened issues.
> > 
> > 
> > Well, fix it so we won't report it again.
> 
> that's not how a bug tracker works.

sorry, I didn't want to bother you

**Comment by ShiSHcat** [comment]
🤣
