### ISSUE TITLE
telegram desktop wont open attached files

### ISSUE THREAD

**Issue by pooya-shams** [telegramdesktop/tdesktop#7708]
### Steps to reproduce
1. open a channel or chat in telegram desktop
2. try to open a shared file in the chat or channel in the right panel by pressing on the file icon or "OPEN WITH" button (by *files* I mean attached files not images, videos or gifs which are shown in telegram itself.).
3. it wont open or do anything to ask for permission for opening the file

### Expected behaviour
ask for permission to open the file and then open it.

### Actual behaviour
does nothing.

### Configuration

**Operating system**
ubuntu 19.10.
`uname -a` output: Linux pooya-pc 5.3.0-46-generic \#38-Ubuntu SMP Fri Mar 27 17:37:05 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

**Version of Telegram Desktop:**
2.1

**Installation source (Linux Only)**
snap

**Used theme**:
tinted dark theme

**Comment by ilya-fedin** [comment]
Snap has been ported to xdg-desktop-portal, you must install xdg-desktop-portal
#7702 #7701
