### ISSUE TITLE
[Feature Request] Make the emoji window open on click not hover

### ISSUE THREAD

**Issue by madprops** [telegramdesktop/tdesktop#7709]
Right now it happens very often that I move the mouse and hover the emoji icon (the smiley face at the bottom right) and it will open the window to select emojis and stickers. This happens instantly. It blocks other content I'm trying to read and forces me to move the mouse around to close it. It would be a lot better in my opinion if it opened on click and not hover, and if it must be on hover then add a delay like at least 250ms

**Comment by ilya-fedin** [comment]
#1333
