### ISSUE TITLE
URLs overlap the time indicator [v 0.8.11]

### ISSUE THREAD

**Issue by dolftax** [telegramdesktop/tdesktop#771]
- Fedora 21 [xfce]

- Screenshot

![screenshot - 05292015 - 06 28 25 pm](https://cloud.githubusercontent.com/assets/4883668/7883022/e121e61c-0630-11e5-8850-9f4d60a8d1df.png)

**Comment by auchri** [comment]
Is this still the case? If yes, reopen the issue
