### ISSUE TITLE
GLib-GIO-ERROR : Settings schema 'org.cinnamon.desktop.interface' is not installed

### ISSUE THREAD

**Issue by Rutrus** [telegramdesktop/tdesktop#7711]
### Steps to reproduce
1. Using Telegram (attaching a picture)
2. Telegram crashes (maybe a snap update?)
So....
3. Execute `/snap/bin/telegram-desktop`
4. Get an error.

### Expected behaviour
Run.

### Actual behaviour
Snap crashes when I try to launch it. It shows:
`(telegram-desktop:30101): GLib-GIO-ERROR **: 01:31:27.647: Settings schema 'org.cinnamon.desktop.interface' is not installed`

### Configuration
**Operating system:**
```
No LSB modules are available.
Distributor ID:	LinuxMint
Description:	Linux Mint 19.1 Tessa
Release:	19.1
Codename:	tessa
```
**Version of Telegram Desktop:**
1557 and 1558

**Installation source (Linux Only)** - the official website / GitHub releases / flatpak / snap / distribution package:

**Used theme**:

<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/7697
