### ISSUE TITLE
HI res svreen shots looks auful when sent as photo

### ISSUE THREAD

**Issue by upsoftt** [telegramdesktop/tdesktop#7712]
### Steps to reproduce
1. take 2k screenshot and send it as photo 
2. click on photo in chat and Ctrl+ ScrollUP to zoom it once.
3. is that ok ?

### Expected behaviour
sharp text.

### Actual behaviour
need ability to read what on csreenshot.

### Configuration
win 10 telegram desktop v 2.1
![image](https://user-images.githubusercontent.com/13884634/80265094-134da880-869f-11ea-83ea-89da7196ec4f.png)

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/2206
