### ISSUE TITLE
Incorrect font fallback for Japanese characters after client update

### ISSUE THREAD

**Issue by msvprogs** [telegramdesktop/tdesktop#7715]
### Steps to reproduce
1. Install Japanese IME and fonts if not already installed (Just add JP keyboard layout)
2. Send "新塚さんは、正直なんだか変な字体と言いました" to any chat

### Expected behaviour
The message should be rendered with MS Gothic font and look like this:
![изображение](https://user-images.githubusercontent.com/28513129/80275535-8a5c5e80-86ea-11ea-8452-4a2888c82633.png)

### Actual behaviour
Message is displayed using some Chinese font and with Chinese form of some characters (underlined with red):
![изображение](https://user-images.githubusercontent.com/28513129/80275572-db6c5280-86ea-11ea-8d75-0dd1e39e5e44.png)

### Configuration
**Operating system:** Windows 10 (10.0.18362 Build 18362)

**Version of Telegram Desktop:** 2.1

**Used theme**: Standard

<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by ProfFan** [comment]
This happens for me as well on macOS 10.15:
![image](https://user-images.githubusercontent.com/5358374/80515258-aa408c00-894f-11ea-87d3-dbadb3f98500.png)

Interestingly, this only happens for No:
![image](https://user-images.githubusercontent.com/5358374/80515411-ebd13700-894f-11ea-8a85-c08039e3d676.png)

System TextEdit.app:
![image](https://user-images.githubusercontent.com/5358374/80515510-14593100-8950-11ea-84ee-dbc44bb47017.png)

**Comment by finalchild** [comment]
This also happens to Korean characters.
They are nearly unreadable because of too narrow font.

**Comment by Aokromes** [comment]
try on 2.1.1

**Comment by ilya-fedin** [comment]
> Message is displayed using some Chinese font and with Chinese form of some characters (underlined with red):

Now it should be rendered with Yu Gothic UI if you have a Japanese OS.

**Comment by finalchild** [comment]
@Aokromes My issue started in 2.1.1.
It seems that it uses the font that comes first in alphabetical order.
My workaround is to copy a font and change its name to '0day'.

**Comment by ilya-fedin** [comment]
@finalchild https://github.com/telegramdesktop/tdesktop/issues/7773#issuecomment-622665643

**Comment by msvprogs** [comment]
Fixed in 2.1.1, thanks!
