### ISSUE TITLE
Semibold font style lost after 2.1.0 on Linux

### ISSUE THREAD

**Issue by hexchain** [telegramdesktop/tdesktop#7717]
It was possible to override the default Open Sans font by using some fontconfig rules, e.g.:

```xml
<?xml version="1.0"?>
<!DOCTYPE fontconfig SYSTEM "fonts.dtd">
<fontconfig>
    <its:rules xmlns:its="http://www.w3.org/2005/11/its" version="1.0">
        <its:translateRule translate="no" selector="/fontconfig/*[not(self::description)]"/>
    </its:rules>

    <match target="pattern">
        <test name="prgname">
            <string>telegram-desktop</string>
        </test>
        <test name="family"><string>Open Sans</string></test>
        <edit name="family" mode="assign">
            <string>Roboto</string>
        </edit>
    </match>

    <match target="pattern">
        <test name="prgname">
            <string>telegram-desktop</string>
        </test>
        <test name="family"><string>Open Sans Semibold</string></test>
        <edit name="family" mode="assign">
            <string>Roboto</string>
        </edit>
        <edit name="weight" mode="assign">
            <const>semibold</const>
        </edit>
    </match>
</fontconfig>
```

However, after 2.1.0 all texts that should be in semibold are rendered with regular style.

### Steps to reproduce
Upgrade to v2.1.0.

### Expected behaviour
Texts are rendered correctly with their styles.

### Actual behaviour
All texts that should be in semibold are rendered with regular style:
![image](https://user-images.githubusercontent.com/529520/80277209-c218d580-86ed-11ea-92ee-1cfb3b9eb165.png)
IIRC the website name and the title of the preview should be in semibold.

### Configuration
**Operating system:**
Arch Linux

**Version of Telegram Desktop:**
2.1.0

**Installation source (Linux Only)** - distribution package: Arch Linux community repo

**Used theme**: Tinted

Also, see https://github.com/desktop-app/lib_ui/commit/74889b8c2131adcf2a370cfdd485303049c85b44#commitcomment-38735405.

The only workaround seems to be creating a separate font with only the semibold variant of the desired font and set it as an alias of "Open Sans Semibold" in fontconfig. There is probably no way to let it use the bold variant of any existing font.

**Comment by ayalhw** [comment]
Same problem.
And same environment.

**Comment by ilya-fedin** [comment]
Font changing is not supported by tdesktop. If you use any hacks, you're on your own.

**Comment by hexchain** [comment]
However, even if I use `ttf-opensans` without any fontconfig hack, the rendering is still wrong for characters not covered in Open Sans:

![image](https://user-images.githubusercontent.com/529520/80285456-6bc78900-8725-11ea-9fd9-edcdb582d6a9.png)

The message above has a default style while the one below has a bold style on all characters. Notice that bold style only applies to Latin characters, but Telegram is supposed to use bold style from fallback fonts (in this case, the CJK font) correctly.

**Comment by Samleo8** [comment]
Same issue, same environment (Arch Linux). 

Note that there is also a problem with monospace fonts for code blocks (wrapped in ` `)

![image](https://user-images.githubusercontent.com/2712664/80357978-55990480-88ae-11ea-9b46-9bddf39d0452.png)

I have no font config hacks, so this may be an internal Telegram font issue?

**Comment by ilya-fedin** [comment]
> Note that there is also a problem with monospace fonts for code blocks

Looks like a separate issue

**Comment by ilya-fedin** [comment]
Which DE are you using?

**Comment by Samleo8** [comment]
Gnome DE

> Which DE are you using?

Gnome

**Comment by ilya-fedin** [comment]
> Gnome

`echo $QT_QPA_PLATFORMTHEME`

**Comment by Samleo8** [comment]
> > Gnome
> 
> `echo $QT_QPA_PLATFORMTHEME`

`qt5ct` sorry

**Comment by ilya-fedin** [comment]
> `qt5ct` sorry

Please check qt5ct settings

**Comment by Samleo8** [comment]
Thanks! I have fixed the monospace problem by setting the "Fixed width font" to an appropriate mono font. For now the semibold font style hasn't been fixed yet, but that's probably due to the lack of an update on the AUR.
