### ISSUE TITLE
[Question] "Send as a file" selecting order

### ISSUE THREAD

**Issue by ar-va** [telegramdesktop/tdesktop#7718]
I have noticed a long time ago that when drag-and-dropping a picture using Telegram Desktop, "Send without a compression" is on the top, but when you select it, the choice is on the bottom. I was thinking if it is a mistake that is going to be fixed eventually?

![Screenshot (284)](https://user-images.githubusercontent.com/35546281/80286289-7ae41200-86f8-11ea-8d1f-9a67bc794e2e.png)
![Screenshot (285)](https://user-images.githubusercontent.com/35546281/80286288-7ae41200-86f8-11ea-95b4-dac6ce260bc2.png)

**Comment by Aokromes** [comment]
there is no send as file anymore.
