### ISSUE TITLE
 jom -j4 return "Error: File Makefile doesn't exist."

### ISSUE THREAD

**Issue by mugavri** [telegramdesktop/tdesktop#7719]
I'm following the build instructions for VS 2019 a [this part](https://github.com/telegramdesktop/tdesktop/blob/dev/docs/building-msvc.md#clone-source-code-and-prepare-libraries) and these commands return "Error: File Makefile doesn't exist."

> jom -j4
> jom -j4 install

I'm in this folder: `\Libraries\qt_5_12_5`

on last commit 7bc86cc9af28ba3d04a5cb69f6f7c16bfe7f8719

**Comment by Aokromes** [comment]
this issue is still valid?

**Comment by dehqan** [comment]
Hi,

This error happened for me today.
how can I solve it?

**Comment by natovan** [comment]
> no

How did you fix it?
