### ISSUE TITLE
Attempting to send too many emojis caused crash, cannot reopen the same dialogue window

### ISSUE THREAD

**Issue by not-much-io** [telegramdesktop/tdesktop#772]
Copy pasting some 100+ emojis (awesome pineapple) into the textbox of a contact and attempting to send, freezed the client and eventually crashed it. Upon reopening the Telegram client, everything else works, except for the contact I was sending emojis too. Clicking on their dialogue froze the client again. 

Reinstallation did not help. 

OS: Linux (Arch)
Telegram Version: 0.8.17

My guess, the content of the text box is cached, upon reopening the client tries to continue where I left off?
Probably it doesn't matter if it is emojis or text? Cannot test right now until I can get it to work..
The message did not go through, as I cannot see it android client.

**Comment by not-much-io** [comment]
On one attempt it hanged quite a while and then did not crash, but started to work. It did indeed bring back the long message, after removing it I can use Telegraph normally again.

Is the inability to properly send long messages a known limitation of Telegraph?

Relevant closed issue: https://github.com/telegramdesktop/tdesktop/issues/159

**Comment by soren121** [comment]
The character limit is 4096 UTF-8 characters. This doesn't sound like the same issue as the one you linked, though. I suspect the problem is in the emoji parser.

**Comment by auchri** [comment]
Happens on android too :smile:

**Comment by auchri** [comment]
I can't reproduce this any more.
