### ISSUE TITLE
error when build the projact on windows

### ISSUE THREAD

**Issue by mugavri** [telegramdesktop/tdesktop#7720]
this command filed with this log

`git apply ../../patches/qtbase_5_12_8.diff`

>error: patch failed: src/corelib/kernel/qcore_mac_objc.mm:140
error: src/corelib/kernel/qcore_mac_objc.mm: patch does not apply
error: patch failed: src/gui/kernel/qstylehints.cpp:374
error: src/gui/kernel/qstylehints.cpp: patch does not apply
error: patch failed: src/gui/painting/qbezier.cpp:400
error: src/gui/painting/qbezier.cpp: patch does not apply
error: patch failed: src/gui/painting/qbezier_p.h:222
error: src/gui/painting/qbezier_p.h: patch does not apply
error: patch failed: src/gui/painting/qpainter.cpp:6262
error: src/gui/painting/qpainter.cpp: patch does not apply
error: patch failed: src/gui/text/qinputcontrol.cpp:40
error: src/gui/text/qinputcontrol.cpp: patch does not apply
error: patch failed: src/gui/text/qtextcursor.cpp:510
error: src/gui/text/qtextcursor.cpp: patch does not apply
error: patch failed: src/gui/text/qtextengine.cpp:3028
error: src/gui/text/qtextengine.cpp: patch does not apply
error: patch failed: src/gui/text/qtextengine_p.h:622
error: src/gui/text/qtextengine_p.h: patch does not apply
error: patch failed: src/gui/text/qtextlayout.cpp:706
error: src/gui/text/qtextlayout.cpp: patch does not apply
error: patch failed: src/platformsupport/linuxaccessibility/constant_mappings.cpp:79
error: src/platformsupport/linuxaccessibility/constant_mappings.cpp: patch does not apply
error: patch failed: src/plugins/platforminputcontexts/compose/qcomposeplatforminputcontext.cpp:273
error: src/plugins/platforminputcontexts/compose/qcomposeplatforminputcontext.cpp: patch does not apply
error: patch failed: src/plugins/platforminputcontexts/platforminputcontexts.pro:2
error: src/plugins/platforminputcontexts/platforminputcontexts.pro: patch does not apply
error: patch failed: src/plugins/platforms/cocoa/qcocoaapplicationdelegate.mm:175
error: src/plugins/platforms/cocoa/qcocoaapplicationdelegate.mm: patch does not apply
error: patch failed: src/plugins/platforms/cocoa/qcocoakeymapper.mm:462
error: src/plugins/platforms/cocoa/qcocoakeymapper.mm: patch does not apply
error: patch failed: src/plugins/platforms/cocoa/qcocoasystemtrayicon.mm:96
error: src/plugins/platforms/cocoa/qcocoasystemtrayicon.mm: patch does not apply
error: patch failed: src/plugins/platforms/cocoa/qcocoawindow.mm:499
error: src/plugins/platforms/cocoa/qcocoawindow.mm: patch does not apply
error: patch failed: src/plugins/platforms/cocoa/qnsview_keys.mm:86
error: src/plugins/platforms/cocoa/qnsview_keys.mm: patch does not apply
error: patch failed: src/plugins/platforms/windows/qwindowsdialoghelpers.cpp:1179
error: src/plugins/platforms/windows/qwindowsdialoghelpers.cpp: patch does not apply
error: patch failed: src/plugins/platforms/windows/qwindowsservices.cpp:125
error: src/plugins/platforms/windows/qwindowsservices.cpp: patch does not apply
error: patch failed: src/plugins/platforms/windows/qwindowswindow.cpp:1351
error: src/plugins/platforms/windows/qwindowswindow.cpp: patch does not apply
error: patch failed: src/plugins/platforms/windows/qwindowswindow.h:353
error: src/plugins/platforms/windows/qwindowswindow.h: patch does not apply
error: patch failed: src/widgets/kernel/qwidget.cpp:5161
error: src/widgets/kernel/qwidget.cpp: patch does not apply
error: patch failed: src/widgets/util/qsystemtrayicon_qpa.cpp:93
error: src/widgets/util/qsystemtrayicon_qpa.cpp: patch does not apply
error: patch failed: src/widgets/widgets/qabstractscrollarea.cpp:655
error: src/widgets/widgets/qabstractscrollarea.cpp: patch does not apply

**Comment by chenyu1990** [comment]
me to

**Comment by chenyu1990** [comment]
@mugavri how to fix it. plz help me.
