### ISSUE TITLE
Image Preview Off-Screen when using vertical displays

### ISSUE THREAD

**Issue by mattburchett** [telegramdesktop/tdesktop#7724]
### Steps to reproduce
0. Have multiple monitors
1. Configure a display to be a vertical display
2. Move telegram desktop window to that display
3. Preview an image.

### Expected behaviour
Image preview should show on the display containing the Telegram Desktop application. 

### Actual behaviour
The telegram desktop client opens the image preview on a different screen than the window is active on, and the image is cut off. If you put it on the horizontal screens, the client works exactly as it's expected to. I can drag the telegram image preview back to the vertical monitor, but it doesn't stay on that screen afterwards. I think this is similar to #5048, but more exclusive to a vertical monitor situation. 

Below is a clip of the issue, showing it working fine then once it's dragged to the other screen, it's an issue. 

https://youtu.be/bQVJZzUTjHY

### Configuration
**Operating system:**

Arch Linux, MATE Desktop environment (this does NOT happen in KDE. Did not try other environments, but I would likely guess that this can be reproduced on any DE that isn't Qt based.)

**Version of Telegram Desktop:** 2.1, but also present in the latest available beta version from telegram.org.

**Installation source (Linux Only)** - the official website / GitHub releases / flatpak / snap / distribution package: Arch Distribution Package (also tried the standalone beta version and same issue)

**Used theme**: Night Mode, default theme otherwise.

**Comment by SkeLLLa** [comment]
The same bug appears not only on vertical displays, but on non-single display configurations.

I guess that it treats display as something "square", when it doesn't. And current behavior is something like:

1) Open picture on "primary" display and ignore when telegram app is actually open.
2) Calculate background size based on display, where main window is shown.
3) Apply those bounds and center image.
4) Open image view on *primary* display with size, calculated for different one.

So final picture looks like this. Green - primary screen, red - secondary with different resolution/size, blue - square - telegram main window, border - image view.

![Rectangle-#1](https://user-images.githubusercontent.com/2273103/80960937-8c24d100-8e12-11ea-9cda-bbdff0e54dd9.png)

**Comment by Aokromes** [comment]
this issue is still valid?

**Comment by SkeLLLa** [comment]
@Aokromes yes. It's still present.

**Comment by ilya-fedin** [comment]
> Arch Linux, MATE Desktop environment (this does NOT happen in KDE. Did not try other environments, but I would likely guess that this can be reproduced on any DE that isn't Qt based.)

That sounds like the window manager moves the media viewer window

**Comment by eXqxqxq** [comment]
found similar behavior, I think this is part of the same problem. I am using 2 horizontal monitors with different resolutions

![image](https://user-images.githubusercontent.com/9395374/99119064-b1886800-2609-11eb-8722-915877b6ea77.png)

**Comment by mvartanyan** [comment]
affects me as well, images and media are shown off-screen on an xrandr-defined 760x1440 virtual screen. Ubuntu 20.04, Regolith/i3wm

**Comment by ilya-fedin** [comment]
Is something changed with 2.5.7?

**Comment by TheCGCy** [comment]
Same issue with MacOS 10.15.7, also having a vertical screen on my left. Same steps to produce this. This issue occurs on telegram version 2.5.8, Mac App Store's V2.5.1 behaves normally though. I'm using a 4k Monitor as main screen with scaled resolution, and a secondary monitor with native scale and rotated 90 degree vertically.

<img width="720" alt="88545fc0b45ef7ecd38d7-f90900fa3db5e01af5" src="https://user-images.githubusercontent.com/10301646/107135091-d6ebf000-6932-11eb-904c-0feaf9bfae2c.png">
<img height="480" alt="88545fc0b45ef7ecd38d7-f90900fa3db5e01af5" src="https://user-images.githubusercontent.com/10301646/107135183-5c6fa000-6933-11eb-8c88-3634a25cb0f4.png">

**Comment by Krysiek** [comment]
I have this issue. Browsing media is not possible on monitor in portrait mode.
When I move Telegram to main horizontal screen it works fine.

My setup:
2 screens: primary horizontal 2560x1080, secondary vertical 1080x1920.
Windows 10 Pro version 10.0.19041 build 19041

https://user-images.githubusercontent.com/54168895/115777281-5e36f480-a3b5-11eb-9da8-8ef15cdd2c46.mp4

**Comment by ilya-fedin** [comment]
Just want to note that comments like "I have similar issue" won't help move the issue forward. Someone who have such hardware should debug this and find the cause to move the issue forward.
