### ISSUE TITLE
[Feature Request] Chose sound device to output sound

### ISSUE THREAD

**Issue by jfkz** [telegramdesktop/tdesktop#7725]
### Is your feature request related to a problem?
When I use this on windows 7, messenger can only translate all sounds to my default device. It can be problem if I have more than 1 device to listen music and communicate.

### Describe the solution you'd like
Settings have a parameter where I can chose device to output sound (both calls and message sounds).

### Describe alternatives you've considered
Use another OS =)

**Comment by TheNicker** [comment]
Please add to the title also INPUT devices.
In my case I have 3 microphones connected the PC.

**Comment by Aokromes** [comment]
> @jfkz
> Please add to the title also INPUT devices.
> In my case I have 3 microphones connected to the PC.

you can already choose input devices on calls.
