### ISSUE TITLE
[Feature Request] Possibility to mark a whole folder read

### ISSUE THREAD

**Issue by pantantrollo** [telegramdesktop/tdesktop#7728]
### Describe the solution you'd like

It could be added as a context menu to the existing folder menu, something like :

![Snipaste_2020-04-26_22-50-28_3](https://user-images.githubusercontent.com/49453082/80319788-af4bf100-8812-11ea-867e-e0359df32e41.png)

Un Saludo

**Comment by ilya-fedin** [comment]
#7507
