### ISSUE TITLE
export very broken. exports app assets "back@2x.png" instead of chat content

### ISSUE THREAD

**Issue by soundreactor** [telegramdesktop/tdesktop#7729]
### Steps to reproduce
try to export only images of a group to a custom folder.
yes i allowed export and i waited 24h

### Expected behaviour
telegram should start downloading all the images from the chat.

### Actual behaviour
telegram doesn't download any chat images but some weird asset images eg:
![back@2x](https://user-images.githubusercontent.com/4352735/80289816-df0dd280-8706-11ea-8a93-68adb7fc53e5.png)
the export screen:
![Screen Shot 2020-04-26 at 17 32 37](https://user-images.githubusercontent.com/4352735/80321602-f8d11780-87e3-11ea-88fb-ab193fdea00f.png)

### Configuration
tried mac and windows.

**Version of Telegram Desktop:**
newest

**Comment by john-preston** [comment]
The assets are for the HTML page, they are in "images" folder, while the photos are in the "photos" folder. The export result is supposed to be viewed from the "messages.html" file, there you will see the photos in the message history.

**Comment by soundreactor** [comment]
@john-preston yes. but it doesn't export the photos. 41 files are all assets. not a single photo was exported

**Comment by soundreactor** [comment]
the group has a couple of images 11k from before super group:   
![Screen Shot 2020-04-29 at 13 13 20](https://user-images.githubusercontent.com/4352735/80631434-4f746680-8a1b-11ea-9289-f7399c51c1b4.png)
those are the ones im most interested in.   
those are my settings:  
![Screen Shot 2020-04-29 at 13 13 42](https://user-images.githubusercontent.com/4352735/80631535-7c287e00-8a1b-11ea-8357-141c4c1ffe91.png)
the end date is around where super groups where introduced. so i suspect the export doesn't work on older than super group content. which is probably a bug.

**Comment by john-preston** [comment]
@soundreactor If you export single chat then only history after the conversion to supergroup is exported right now :( No way to get old legacy group export, only in whole account data export.
