### ISSUE TITLE
MP4 always sends as file now :(

### ISSUE THREAD

**Issue by Ryder17z** [telegramdesktop/tdesktop#7730]
### Expected behaviour
It used to ask if it should be sent as video or file

### Actual behaviour
"Send as document"

### Configuration
Windows

**Version of Telegram Desktop:**
Latest at the time of posting

**Comment by john-preston** [comment]
@Ryder17z What version do you try? 2.1 should send video files not larger than 4K as videos (and show them in chat as videos).

**Comment by Aokromes** [comment]
> ### Expected behaviour
> It used to ask if it should be sent as video or file
> 
> ### Actual behaviour
> "Send as document"
> 
> ### Configuration
> Windows
> 
> **Version of Telegram Desktop:**
> Latest at the time of posting

i tried myself, it shows the "send as file" dialog, but it's send as video.

https://mega.nz/#!tqBXUA6a!K8f3Q1vT2Ypb3M1TfCjzCbuXCzBLWTOg1D12uVvuTMM 

can you try if it's the case?

**Comment by Ryder17z** [comment]
> 
> 
> @Ryder17z What version do you try? 2.1 should send video files not larger than 4K as videos (and show them in chat as videos).

I'm sending 1440p or lower res but it still doesn't ask me like it should.

**Comment by Aokromes** [comment]
this issue is still valid?

**Comment by Ryder17z** [comment]
It's changed to "not quite fixed"
It always want to send as video instead now if audio is present and gif otherwise.

It should ask me like it did on an older version. 

Additionally; sometimes I want to share a video that has no audio, but without it being saved as a "gif" that I have to delete from my list of gifs

**Comment by john-preston** [comment]
@Ryder17z It never asked about videos anything. You can check old versions from https://github.com/telegramdesktop/tdesktop/releases

**Comment by RememberTheAir** [comment]
> Additionally; sometimes I want to share a video that has no audio, but without it being saved as a "gif" that I have to delete from my list of gifs

So, the "video sends as file" issue is solved now, right? mp4 without sound being sent as GIFs is the intended behavior (see the discussion at #2053)

**Comment by Ryder17z** [comment]
> 
> 
> @Ryder17z It never asked about videos anything. You can check old versions from https://github.com/telegramdesktop/tdesktop/releases

Again; it used to. maybe bug but it was better >.<

**Comment by kleuter** [comment]
2.1.10 (beta), 320x480 mp4 H264 aac always sent as file

**Comment by Ryder17z** [comment]
I suppose this can be closed.
