### ISSUE TITLE
Links from posts are not opening in browser anymore when cliking on them

### ISSUE THREAD

**Issue by ChinaraIsabaeva** [telegramdesktop/tdesktop#7731]
### Steps to reproduce
1. Open telegram desktop app
2. Open any chat/group 
3. Find any message that contains a link
4. Click link

### Expected behaviour
After I click the link I expect it will open in my browser.

### Actual behaviour
Just nothing. I staying in Telegram.

### Configuration
Ubuntu 18.04.3 LTS

**Version of Telegram Desktop:**
version 2.1

**Installation source (Linux Only)** - the official website / GitHub releases / flatpak / snap / distribution package:
the official website

**Used theme**:
Classic with a custom background from the gallery.

<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by ilya-fedin** [comment]
#7701

**Comment by ilya-fedin** [comment]
> the official website

Are you sure? This issue is snap-specific.

**Comment by ChinaraIsabaeva** [comment]
> > the official website
> 
> Are you sure? This issue is snap-specific.

Hm... I thought I installed from the website. Will reinstall then. Thanks
