### ISSUE TITLE
[Feature Request] Manage forward info in channels

### ISSUE THREAD

**Issue by EnriPv** [telegramdesktop/tdesktop#7734]
### Is your feature request related to a problem?
My request is connected with privacy and security on public channel.

### Describe the solution you'd like
I'd like to have the option to hide the info about from whom the post was forwaded by default and a switch to purge said information in previous post (as well as posts signatures)

**Comment by MasterGroosha** [comment]
Even though it's possible to remove "forward from" mark like in other apps (for example, Telegram X for Android), I think removing post signatures from already sent apps is not technically possible and is more like an API issue rather than TDesktop problem.
