### ISSUE TITLE
Two telegrams running after snap refreshed

### ISSUE THREAD

**Issue by julian-klode** [telegramdesktop/tdesktop#7737]
### Steps to reproduce
1. Snapd refreshes telegram snap, you open telegram again via hotkey / apps page in GNOME / GNOME dash, or I guess CLI though I never tested

### Expected behaviour
One Telegram should be running

### Actual behaviour
Two telegrams are running

### Configuration
**Operating system:** Ubuntu (various versions)

**Version of Telegram Desktop:** 2.1.0-5-ge149f10d4 (and earlier)

**Installation source (Linux Only)** - the official website / GitHub releases / flatpak / snap / distribution package: snap

**Used theme**: not relevant

<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by ilya-fedin** [comment]
It's ok since snap doesn't kill launched old versions of apps

**Comment by julian-klode** [comment]
No it's not OK at all. There's clearly an issue in uniqueness handling. Even if the snap was updated, it should not be launching a second Telegram instance, but pop up the running one.
