### ISSUE TITLE
Telegram resizes animated GIFs

### ISSUE THREAD

**Issue by Jasata** [telegramdesktop/tdesktop#7738]
### Steps to reproduce
1. Use Screen2Gif to make an instructional GIF video
2. Paste it into Telegram chat
3. It gets resized into unreadable / unusable size

### Expected behaviour
Tell us what should happen: This should NOT happen, unless I tell it to do so.

### Actual behaviour
Tell us what happens instead: This resizing happens and my old mother gets no help via Telegram...

### Configuration
**Operating system:** Win10

**Version of Telegram Desktop:**  2.0.2

**Installation source (Linux Only)** - the official website / GitHub releases / flatpak / snap / distribution package:

**Used theme**: N/A

<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

Possibly errornous behaviour intended for all those animated icons. Obviously should NOT mangle user content, especially without explicit permission to do so.

**Comment by SonicoXD1** [comment]
The server compresses gif files by default. As an alternative, you can either:
a) Convert the gif to mp4 and then upload it.
b) Record the instructional gif video directly as mp4.
MP4 files will be uploaded with no compression, and as an extra will have better quality and smaller file sizes than GIFs.

**Comment by nuc134r** [comment]
I think this should be configurable. 

I use a [tiny free utility](https://www.cockos.com/licecap/) to capture GIFs and it's very convenient. And it sucks when I send it and content becomes unreadable.

Any free and simple tools to capture mp4 screen recordings on Windows?

**Comment by Aokromes** [comment]
right click -> capture -> screen recording, you can also choose a shortcut for it xd

**Comment by Jasata** [comment]
> I think this should be configurable.
> 
> I use a [tiny free utility](https://www.cockos.com/licecap/) to capture GIFs and it's very convenient. And it sucks when I send it and content becomes unreadable.
> 
> Any free and simple tools to capture mp4 screen recordings on Windows?

Please take a loot at Screen2Gif. And I wholeheartedly agree - this resizing behavior  is so anti-useful that I was absolutely sure this was a mistake.

**Comment by Nigrimmist** [comment]
Unfortunately, faced with same issue and it is seems like a api bug, isn't it? My actions are : 
1) Send gif 600 x 413 (1.63mb) to bot from desktop/mobile (also, the same with @gif bot).
2) trying to get download by file_id.
3) Api always produce me main file_id and thumb with thumb_id. Sizes (width/height) are different (main contains real size), **but file_size are the same**. So, i can't download original gif (mp4), it is resizing on telegram servers, but thumb and main files - have the same size and looks the same. 

Seems, like result resolution can't be more than 320 pixels from one of sides. I did not find the description of this limitation in docs (only for thumbs), so reporting here. 
Issue not reproducing in case of convert this gif to mp4 and send to bot - i have ability to download the original mp4 in this case.


I can provide gifs if you need, but it is to reproduce using @gif bot with preview more than 320px of any side. 

Please, fix it, as my bot functionality can't work in valid way. Thank you!

**Comment by Nigrimmist** [comment]
The issue i described few posts above is still exist. Could you please fix it?

**Comment by Aokromes** [comment]
such feature belongs to https://bugs.telegram.org/
