### ISSUE TITLE
[Question] Showing Limited Number of chats

### ISSUE THREAD

**Issue by nyxs** [telegramdesktop/tdesktop#7740]
Hi,
Telegram Desktop for MacOS shows me only 9 chats in the sidebar, while, obviously, I have way more.

Here's a picture:
![image](https://user-images.githubusercontent.com/20337331/80479459-b892a600-8957-11ea-9c1e-542a99e08977.png)
There is no scrolling whatsoever or anything.
Just 9 chats (2 of them are pinned), this huge blank space and no scrolling.

**Comment by ilya-fedin** [comment]
On your screenshot is not Telegram Desktop
https://github.com/overtake/TelegramSwift
