### ISSUE TITLE
Inappropriate strikethrough view in buttons

### ISSUE THREAD

**Issue by sanberuzadre** [telegramdesktop/tdesktop#7749]
I have a menu with buttons, which can be strikethrough or usual
Before update to Telegram 2.1, it was looked like this:
![image](https://user-images.githubusercontent.com/26721736/80620793-1fdf5180-8a4f-11ea-94e3-67450b37bb9d.png)

After Telegram Update I understood that localization of these strikethrough numbers was changed and it isn't working appropriately.
![image](https://user-images.githubusercontent.com/26721736/80620988-5917c180-8a4f-11ea-8707-aa0552c436ee.png)

As we know, buttons are not maintaining strikethrough text directly via "\<s\>\<\/s\>", so I've used Unicode characters to make them as they should be:

Unicode Character 'COMBINING LONG STROKE OVERLAY' (U+0336)
0 -> "\u03360\u0336";
1 -> "\u03361\u0336";
2 -> "\u03362\u0336";
3 -> "\u03363\u0336";
4 -> "\u03364\u0336";
5 -> "\u03365\u0336";
...
etc.

But now it works inappropriately, bot outputs: <LONG_DASH>0<LONG_DASH>.

**OS:** Windows 10
**Version of Telegram Desktop:** 2.1

**Comment by ilya-fedin** [comment]
OS?

**Comment by sanberuzadre** [comment]
Windows 10

>

**Comment by sanberuzadre** [comment]
Thanks, bug isn't reproducing anymore on Desktop:
![image](https://user-images.githubusercontent.com/26721736/80837772-23660a80-8c00-11ea-9a70-0132e308ae92.png)
