### ISSUE TITLE
Bug with "eating" of text in chat text box

### ISSUE THREAD

**Issue by Demetri0** [telegramdesktop/tdesktop#7750]
### Steps to reproduce
1. Open any chat
2. try to fast input any text, switching language while a process
3. after some time part of text will be "eaten"

### Expected behaviour
No text should be eaten

### Actual behaviour
Sometimes (actually very often) telegram eats a part of text.

Before a bug:
![Screenshot from 2020-04-30 02-30-25](https://user-images.githubusercontent.com/6806547/80644730-f42e8c80-8a8b-11ea-85c5-c50f5f1bfd07.png)
After a bug (text was not erased by hand, it was eaten by telegram)
![Screenshot from 2020-04-30 02-30-30](https://user-images.githubusercontent.com/6806547/80644801-11635b00-8a8c-11ea-92b2-8436f72c698c.png)

### Configuration
**Operating system:**
`Linux demetrio 5.3.0-46-generic #38-Ubuntu SMP Fri Mar 27 17:37:05 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`
Actually all my friends notice this bug on different versions of ubuntu and different hardware

**Version of Telegram Desktop:**
`*` - `2.1`

**Installation source (Linux Only)** - the official website / GitHub releases / flatpak / snap / distribution package:
`snap` / official `telegram-desktop` package / official website tarball

**Used theme**:
`Night`

<details><summary><b>Logs</b>:</summary><pre>
QTextCursor::setPosition: Position '-1' out of range
Could not create AF_NETLINK socket (Permission denied)
Could not create AF_NETLINK socket (Permission denied)
QTextCursor::setPosition: Position '-1' out of range
QTextCursor::setPosition: Position '-1' out of range
QTextCursor::setPosition: Position '8388607' out of range
QTextCursor::setPosition: Position '8388607' out of range</pre>
</details>

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/5569 ?

**Comment by Demetri0** [comment]
> #5569 ?
No, absolutely different things. No popups covered text in my case, it totally erased from input in my case.

**Comment by Demetri0** [comment]
> @Demetri0 I think you already reported this in a comment to #4922

Oh... that's true, I didn't found it, so that's duplicate, I'll close it.
