### ISSUE TITLE
Please update the windows store version

### ISSUE THREAD

**Issue by IbarakiKasen** [telegramdesktop/tdesktop#7753]
### Steps to reproduce
1. Go to https://www.microsoft.com/en-us/p/telegram-desktop/9nztwsqntd0s
2. Install telegram desktop

### Expected behaviour
Get the latest telegram desktop 2.1.0 which is able to show the dart emoji.

### Actual behaviour
Got 2.0 which shows lots of unsupported messages in groups.

### Configuration
**Operating system:** Windows 10

**Version of Telegram Desktop:** telegram desktop 2.0 win store

**Comment by Aokromes** [comment]
for sure that needs microsoft to aprobe latest version.

**Comment by IbarakiKasen** [comment]
> for sure that needs microsoft to aprobe latest version.

The store certificate process usually only takes few hours. Considering the 2.1 release was made approximately a week ago, it could be that they forgot to submit it to store.

**Comment by Aokromes** [comment]
this issue is still valid?

**Comment by IbarakiKasen** [comment]
The current store version is 2.1.5 as of 2020-6-4, and the non-store version is 2.1.7. So it is still behind the non-store version, but not causing usability issue in my opinion.
