### ISSUE TITLE
Lagging keyboard input on win10

### ISSUE THREAD

**Issue by Griboedoff** [telegramdesktop/tdesktop#7755]
### Steps to reproduce
1. Install tdesktop 2.1 win10
2. Start typing something on keyboard

### Expected behaviour
Input should appear quickly all the time.

### Actual behaviour
Sometimes you have a 'lag spike': ~0.5-1 second delay before your input appears. But most of the time input appears with acceptable delay.
Issue didn't existed on version 2.0

### Configuration
**Operating system:** win10
**Version of Telegram Desktop:** 2.1

**Comment by Griboedoff** [comment]
issue looks similar to https://github.com/telegramdesktop/tdesktop/issues/7530

**Comment by Griboedoff** [comment]
![telegramSpike](https://user-images.githubusercontent.com/16411561/80686396-4fcf3900-8ad1-11ea-871e-01f8eba7e66d.gif)

here is the gif, im typing at almost same speed but you can see two spikes here

**Comment by dmayan-ss** [comment]
Happening to me now. I even deactivated animations and emoji auto replace.

Very annoying

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/7530 duplicate.
