### ISSUE TITLE
Public channel not visible in browser

### ISSUE THREAD

**Issue by Hrishikesh-K** [telegramdesktop/tdesktop#7757]
## Steps to reproduce
1. Open a web browser and try to look for channel: `@WinHackermanChannnel` (link: https://t.me/WinHackermanChannel/). 
2. Now try to open a post from the channel. (For example: https://t.me/WinHackermanChannel/100).

### Expected behaviour
Tell us what should happen

The 2nd link should show the post on that address in the web browser itself, just like other public channels (For example: https://t.me/durov/100).

### Actual behaviour
Tell us what happens instead

It gives an error `Channel with username @WinHackermanChannel not found`, however, if we click on the button `View in channel`, the post opens in the Telegram app all fine.

### Configuration
**Operating system:** Windows 10

**Version of Telegram Desktop:** 2.1

**Installation source (Linux Only):** Not applicable

**Used theme**: None

<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by MasterGroosha** [comment]
This is true not only for you channel but for some public channels too (even not restricted).
But that's not TDesktop issue, it's Telegram problem overall.

**Comment by Hrishikesh-K** [comment]
@MasterGroosha I know it's not TDesktop issue, but, I couldn't find any better way to report the problem. 

> This is true not only for you channel but for some public channels too

I did not know that. It's not a solution, but, at least I'm not the only one.

**Comment by MasterGroosha** [comment]
@Hrishikesh-K Well, creating TDesktop issues about Telegram overall is not a good way to report problems. You have several options, including:
1) Write a message to Telegram Support (any Telegram app -> Settings -> Ask a Question)
2) Ping Telegram in Twitter: https://twitter.com/telegram

This issue tracker is used for TDesktop-specific problems, sorry.

**Comment by Hrishikesh-K** [comment]
Apologies.
