### ISSUE TITLE
[Feature Request] Add possibility to enable sound notification per folder

### ISSUE THREAD

**Issue by ElderOrb** [telegramdesktop/tdesktop#7758]
Use case: I'd like to be notified if anybody from 'Personal' folder is writing me, but don't care about other folders. 

Also could be useful to get some if some activity is happening in other folders: like if amount of messages is rapidly increasing (should be configurable via rules). But this would require more work/discussions so just an idea for now.

**Comment by ElderOrb** [comment]
Possibility to specify different notification sounds for different folders would be great too.

**Comment by Aokromes** [comment]
it's more or less https://github.com/telegramdesktop/tdesktop/issues/6282 adding
