### ISSUE TITLE
Opening links or files no longer works on the snap version of the desktop application

### ISSUE THREAD

**Issue by SeSodesa** [telegramdesktop/tdesktop#7760]
### Steps to reproduce
1. Download the official Telegram Desktop from the snap store
2. Attempt to click a (link | file) to open it in your default (browser | file specific default application)
3. Fail

### Expected behaviour
Clicking on a link or a file should open it in the default browser or the default application chosen to open that type of file.

### Actual behaviour
Nothing happens.

### Configuration
**Operating system:** Ubuntu 18.04

**Version of Telegram Desktop:** 2.1.0-5-ge149f10d4, revision 1561

**Installation source (Linux Only)** - snap

**Used theme**: Day

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/7701
