### ISSUE TITLE
[Feature request] Tasker/Macrodroid supprt

### ISSUE THREAD

**Issue by lawson85** [telegramdesktop/tdesktop#7761]
I would like to be able to automatically call certain contact using Macrodroid or intent, which is then compatible with Macrodroid and Tasker. 

I would also like t be able t backup app settings using Macrodroid. 
Note, I cannot find where it is possible to backup app settings anyhow.

**Comment by lawson85** [comment]
This would be  for Android, sorry

**Comment by lawson85** [comment]
Why did you close it? You haven't said or implemented or anything

**Comment by RememberTheAir** [comment]
I guess it's because this issue tracker is about telegram desktop, and not the android app. You can suggest that to the in-app support or on Twitter

**Comment by lawson85** [comment]
Sorry
