### ISSUE TITLE
[Feature Request] Call recorder

### ISSUE THREAD

**Issue by lawson85** [telegramdesktop/tdesktop#7762]
It would be great if I could record my calls

**Comment by srulikuk** [comment]
second that

**Comment by glococo** [comment]
I really appreciate Voice and Video call recorder.
Very usefull to share with work groups and team members.

**Comment by srulikuk** [comment]
Why close it? has it been implemented?

**Comment by RememberTheAir** [comment]
> Why close it? has it been implemented?

It's still open
