### ISSUE TITLE
[solved] telegram desktop installed with snapd not work in raspeberry pi 3b+

### ISSUE THREAD

**Issue by cenosito** [telegramdesktop/tdesktop#7763]
### Steps to reproduce
1. Install telegram-desktop with snap
2. sudo apt install snapd
3. sudo snap install telegram-desktop
4. reboot system
5. launch with command telegram-desktop

### Expected behaviour
Start telegram-desktop through ssh or vnc.
Other apps like pcamfn, chromium, vlc, firefox, etc works perfecty with ssh.

### Actual behaviour
Show me this error:

X11 connection rejected because of wrong authentication.
qt.qpa.screen: QXcbConnection: Could not connect to display localhost:10.0
Could not connect to any X display.

### Configuration
**Operating system:**

Operating System: Raspbian GNU/Linux 10 (buster)
Kernel: Linux 4.19.118-v7+
Architecture: arm

openssh-server installed version openssh-server  1:7.9p1-10+deb10u2
config file of ssh only activated X11fordwared, rest in original state

**Version of Telegram Desktop:**
telegram-desktop   2.0.1                       1501 

**Installation source (Linux Only)** - the official website / GitHub releases / flatpak / snap / distribution package:
 snapd   2.37.4-1+rpi1  armhf

**Used theme**:

<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by ilya-fedin** [comment]
> X11 connection rejected because of wrong authentication.

sounds like you use ssh -X instead of ssh -Y

**Comment by cenosito** [comment]
> > X11 connection rejected because of wrong authentication.
> 
> sounds like you're using ssh -X instead of ssh -Y

Yes, but I tried now with command:
ssh -Y piuser@IP

And when a connect show same message only when launch telegram-desktop, with other apps work fine.

**Comment by ilya-fedin** [comment]
I have reproduced on amd64
But vlc snap also produces the same errors
This is not a tdesktop issue, but a snap sandbox issue

**Comment by cenosito** [comment]
> I have reproduced on amd64
> But vlc snap produces the same errors as well
> This is not a tdesktop issue, but a snap sandbox issue

Thanks, yes just I tested on amd64 processor with linux and same issue. I thought that my raspberry was the problem with telegram,  but is snap, not telegram.

Thanks

**Comment by ilya-fedin** [comment]
> I thought that my raspberry was the problem with telegram, but is snap, not telegram.

If you really want, you can disable snap sandbox by installing snap with `--devmode` argument

**Comment by cenosito** [comment]
> > I thought that my raspberry was the problem with telegram, but is snap, not telegram.
> 
> If you really want, you can disable snap sandbox by installing snap with `--devmode` argument

Oh my god, it works like a charm.
Yes, I need this and with devmode work with ssh.

Thanks very much

**Comment by ilya-fedin** [comment]
> cenosito changed the title telegram desktop installed with snapd not work in raspeberry pi 3b+ [solved] telegram desktop installed with snapd not work in raspeberry pi 3b+

You can just close the issue
