### ISSUE TITLE
Telegram Desktop crashes on some animated stickers

### ISSUE THREAD

**Issue by mbasaglia** [telegramdesktop/tdesktop#7767]
I've been able to reproduce this in a few different circumstances, I think the easiest to test is on uploading a tgs file containing an animated property with only one keyframe.

I've attached a file that should reproduce the issue

### Steps to reproduce
1. download [foo.gz](https://github.com/telegramdesktop/tdesktop/files/4563869/foo.gz)
2. rename it to `foo.tgs` (Github didn't like the file so I had to change the extension)
3. open telegram
4. select `foo.tgs` as a file to send
5. telegram crashes

### Expected behaviour
If it things the sticker is invalid, it should give an error or something, not just crash

I haven't tried but if telegram desktop crashes any time it tries to render such a file, it might be possible for someone to send the tgs using a different client, and cause other people's client to crash

### Actual behaviour
Crashes

### Configuration
**Operating system:** Ubuntu 20.04 LTS

**Version of Telegram Desktop:** 2.1

**Installation source (Linux Only)** - the official website

**Comment by mbasaglia** [comment]
By the way in the attached file, the problem is triggered by the "a" property of the transform in the only layer in the composition

**Comment by john-preston** [comment]
@mbasaglia Did you see it crash on some received stickers or only on sent ones? Because it is cool to fix the sending as well, but it is not such a big problem as the received ones.

I ask because I suppose (and hope) that server won't mark the message as a valid sticker if the rlottie library crashes while trying to render it.

**Comment by mbasaglia** [comment]
I only tried on sending as managing to send a sticker that breaks clients is tricky.
