### ISSUE TITLE
No one cares about syncing, but just enable secret chats on desktop

### ISSUE THREAD

**Issue by kgizdov** [telegramdesktop/tdesktop#777]
Hi,

(This is not a rant and please don't make it so.)

I have spent a long time reading the thread of issues on secret chats for desktop, only to see that a lot of issues were open and then closed, with only a hint of input from the devs.

More and more users want this feature as they expect the app will behave the same way cross-platform as promised on its website. There is not even a mention in the FAQ page that desktop clients do not support the main marketing feature for Telegram - Secret Chats. Users are just left to discover this exactly at the moment they need it - very frustrating.

From what I have seen, the feature has been postponed and issues dropped on the basis that most users don't understand the difficulty and un-advisability of even attempting syncing of secret chats. However, this is by far no reason why Secret Chats should not be implemented on desktop.

There are ready-made solutions for end-to-end encryption on desktops for decades. Moreover, the Telegram team has gracefully managed to cram all these technologies in a user-friendly self-contained mobile app that is consistent cross-platform. So the same team should have no trouble in implementing that feature in a self-contained desktop app.

And I would like to emphasize that I am not talking about syncing at all. Per-device, end-to-end encryption in the form of the familiar and established Secret Chat model is perfectly acceptable.

To all the Telegram Desktop team, thank you for a great app and please enable this feature for us so we can all move past moaning about it, get on with our lives and continue to use your awesome platform.

Regards.

**Comment by ifree** [comment]
+1

**Comment by brantje** [comment]
+1

**Comment by animalillo** [comment]
+1000

**Comment by luksi-reiku** [comment]
+9000

**Comment by animalillo** [comment]
wow, the number it's increasing so fast...

**Comment by franzalex** [comment]
I'd like to see this feature too.

I don't especially care about syncing secret chats. All I want is to be able to have secret chats with my friends and colleagues on the comfort of my computer.

**Comment by animalillo** [comment]
Telegram without secret chats it's almost pointless. Noone is asking for secret chat syncing, even in the same device you sometimes end with the secret chat messed up and have to create a new one, but why you dont even have a crappy version on tdesktop? noone knows.

**Comment by DerRidda** [comment]
Yes, no need to sync the secret chats, they are secret after all. This is a must have feature.

**Comment by auchri** [comment]
duplicate #871

**Comment by Brawl345** [comment]
Why are you closing older issues for newer issues? This makes no sense....

**Comment by auchri** [comment]
The other issue has a better title and less rant

**Comment by Xashyar** [comment]
@luksireiku @DerRidda @animalillo @franzalex @animalillo @ifree @kgizdov
Hi, 
May i Ask each of you guys that if you are looking for "secret chats" why do u even waste your time with the Telegram Guys?
They only have "syncing concerns" not privacy ones :)

Hint:
https://github.com/signalapp/Signal-Desktop
