### ISSUE TITLE
needAck is wrong?

### ISSUE THREAD

**Issue by Lonami** [telegramdesktop/tdesktop#7770]
`needAck` is implemented as follows:
https://github.com/telegramdesktop/tdesktop/blob/d506f10e9f976e23fdea9e666e32ce4ef809d371/Telegram/SourceFiles/mtproto/details/mtproto_serialized_request.cpp#L127-L144

But the [﻿Mobile Protocol: Detailed Description documentation](https://core.telegram.org/mtproto/description#content-related-message) reads (emphasis mine):

> #### Content-related Message
>
> A message requiring an explicit acknowledgment. […]
>
> #### Message Sequence Number (msg_seqno)
>
> A 32-bit number equal to twice the number of “content-related” messages […] *subsequently incremented by one if the current message is a content-related message*.

So there are two options:
* `tdesktop` is acknowledging things like `bad_server_salt` and `pong` when it shouldn't.
* the documentation is wrong and those do in fact need acknowledgement.

Which one is right?

**Comment by john-preston** [comment]
@Lonami Tdesktop may send some redundant acks indeed.

**Comment by Lonami** [comment]
Whether this is still relevant is up to the author of the application to determine, as I have not been keeping track of what commits they've done :)

But if it's not closed, it's either they didn't remember to close or it's fixed but forgot about this issue.
