### ISSUE TITLE
[Question] Search for Emojis based on keyword similarity

### ISSUE THREAD

**Issue by shahril96** [telegramdesktop/tdesktop#7772]
In Whatsapp, we have something like this,

![image](https://user-images.githubusercontent.com/2675341/80849135-6a77ee00-8c48-11ea-913f-ae22fd198a83.png)

Which is convenient for Desktop users, which I don't need to scroll down and trace where is emoji that I wanted.

I can't find the same thing in Telegram:

![image](https://user-images.githubusercontent.com/2675341/80849281-17526b00-8c49-11ea-876c-0f1b8dff722e.png)

**Comment by shahril96** [comment]
Ah nevermind, I should have searched first. 🤦 

https://twitter.com/telegram/status/893095290881945601?lang=en

Use ":<keyword>", which does exactly what I wanted.

**Comment by yashpalgoyal1304** [comment]
search is still helpful as it is in its own space. And also, it follows naturally from stickers search, and gif search.

trail: [tgbetachat (msg)](https://tx.me/tgbetachat/310456) > [TDesktopTalk (msg)](https://tx.me/TelegramDesktopTalk/40105)

**Comment by yashpalgoyal1304** [comment]
\open

**Comment by yashpalgoyal1304** [comment]
search is still helpful as it is in its own space. And also, it follows naturally from stickers search, and gif search.

@shahril96 can u please re-open this issue?

trail: [TgBetaChat (msg)](https://tx.me/tgbetachat/310456) > [TDesktopTalk (msg)](https://tx.me/TelegramDesktopTalk/40105) > this

**Comment by yashpalgoyal1304** [comment]
@shahril96

**Comment by shahril96** [comment]
@yashpalgoyal1304 I used Unigram (https://github.com/UnigramDev/Unigram) which they have this feature (and many more). So I don't have this issue anymore.

**Comment by yashpalgoyal1304** [comment]
but i have this issue. and i cant open a new one, as that will be closed as duplicate of this. so....

**Comment by yashpalgoyal1304** [comment]
thanks (: 👍

**Comment by shahril96** [comment]
Done.
