### ISSUE TITLE
Issue with tray icon ( Ubuntu 20.04 )

### ISSUE THREAD

**Issue by xpt1x** [telegramdesktop/tdesktop#7774]
### Steps to reproduce
1. Open Telegram, it will show the tray icon
2. Lock your screen
3. Unlock screen and check the tray icon

### Expected behaviour
Proper icon should be displayed
![Screenshot-20200502100840-480x40](https://user-images.githubusercontent.com/33655587/80855281-846ffb80-8c5d-11ea-9262-8b80ad2ef6d0.png)

- Another thing, notification count is getting overlapped with the icon itself, its better if it would be a dot instead like Discord's icon in this image

### Actual behaviour
Wifi connecting like icon shows instead of telegram
![Screenshot-20200502100815-547x40](https://user-images.githubusercontent.com/33655587/80855340-0102da00-8c5e-11ea-9d46-aa4005ce1bb4.png)

### Configuration
**Operating system:** Ubuntu 20.04

**Version of Telegram Desktop:** v2.0.1

**Installation source (Linux Only)** - the official website / GitHub releases / flatpak / snap / distribution package: Installed through apt ( distribution package )

**Used theme**: Dark [ Gnome: 3.36 - Orchis theme ]

**Comment by ilya-fedin** [comment]
>     * Another thing, notification count is getting overlapped with the icon itself

That means that your tray is 16x16 size. Increase it to 22x22 at least.

>     * its better if it would be a dot instead like Discord's icon in this image

https://github.com/telegramdesktop/tdesktop/wiki/Environment-variables
#6721

>     3\. Unlock screen and check the tray icon

Here we go again :cry:

**Comment by ilya-fedin** [comment]
> Installed through apt ( distribution package )

Debian maintainer replaces tray implementation with [other](https://salsa.debian.org/debian/telegram-desktop/-/tree/mymedia/master/debian/statusnotifieritem), could you check the binary from official website or GH releases?

**Comment by xpt1x** [comment]
Thanks @ilya-fedin 
I will check from GH releases and will let u knw

**Comment by ilya-fedin** [comment]
> Thanks @ilya-fedin
> Everything is good now, i like that discord style one, but is there really an option to change size of tray in gnome ?
> 
> I will check from GH releases and will let u knw

1) there are no notify when you editing your message
2) i don't know, but I know that gnome has multiple tray implementations in their extension store

**Comment by xpt1x** [comment]
Icon is fine with GH releases, just that through apt that thing happens

**Comment by xpt1x** [comment]
But the thing is, even my notifications are on, its showing on dock as you can see but no count on tray icon now, nothing in env vars
![image](https://user-images.githubusercontent.com/33655587/80923332-a625cb80-8da0-11ea-983b-d0209c9954e7.png)

**Comment by ilya-fedin** [comment]
> nothing in env vars

Are you sure? Please check in terminal with `env | grep TDESKTOP`

**Comment by xpt1x** [comment]
Hmm thanks for pointing out, its still present somewhere i checked many files /etc/environment
, /etc/profile. /.profile, /.bashrc didn't found it in any of these, is there any way to get path where it is stored ? Coz i tried to unset it and then it was gone but when i log out and log in again, it comes again in `env` list

**Comment by ilya-fedin** [comment]
Are you checked `/.pam_environment`?

**Comment by xpt1x** [comment]
Yes, its empty

**Comment by xpt1x** [comment]
@ilya-fedin instead of removing it i set it to ( 0 ) i even checked after log out and login ... its now set to 0 but still the same as in image https://github.com/telegramdesktop/tdesktop/issues/7774#issuecomment-623165377

**Comment by ilya-fedin** [comment]
> instead of removing it i set it to ( 0 ) i even checked after log out and login ... its now set to 0 but still the same as in image [#7774 (comment)](https://github.com/telegramdesktop/tdesktop/issues/7774#issuecomment-623165377)

It's not checked for 1 or not, it's checked for set or not. I.e. even if variable is set to empty value, it will be interpreted as `true`.

> Yes, its empty

Then maybe `~/.config/environment.d/*.conf`?

> ts so annoying now, i can unset it but whenever i log in it gets set automatically

I don't know how it is possible to set it and forget where you set it :thinking: 

You also can scan your home dir: `grep -r TDESKTOP_DISABLE_TRAY_COUNTER ~`

**Comment by xpt1x** [comment]
> I don't know how it is possible to set it and forget where you set it :thinking:

Its not like that, i knw i made changes in /etc/environment but when issue occurred so i removed that var from there but issue still persisted, so i commented here, then u told me to check `env` and it was present in env list, so i checked everywhere in all those files, but can't find it now !
I can unset it but its appearing on next login again

**Comment by ilya-fedin** [comment]
Are you tried reboot?

**Comment by xpt1x** [comment]
Finally its gone now ! Did a restart without checking through log out ( seriously dont knw why it was not changing though session log out, i was having knwledge that they get executed on session change )

Last thing @ilya-fedin , still ..is there a way to have a dot like notification option like in DISCORD image i shared above ?

**Comment by ilya-fedin** [comment]
> Last thing @ilya-fedin , still ..is there a way to have a dot like notification option like in DISCORD image i shared above ?

It is provided for me by system icon theme (Papirus)

**Comment by ilya-fedin** [comment]
static binary can't use system themes due to static Qt linking (but I hope it will be changed soon), but flatpak package can

Snaps, unfortunately, have a bad theme integration

**Comment by ilya-fedin** [comment]
> but is there really an option to change size of tray in gnome ?

According to https://github.com/ubuntu/gnome-shell-extension-appindicator/issues/215, there is no option in /gnome-shell-extension-appindicator extension
I guess, you can replace it with another

**Comment by ilya-fedin** [comment]
Also, there are will be qt5ct support with 2.1.2, so that you can set icon theme for telegram

**Comment by pvonmoradi** [comment]
@ilya-fedin I'm on 18.04. Tray icon has monochrome in 2.1.2 . How to revert it back to what it was? http://i.imgur.com/8iDjVMY.png

**Comment by ilya-fedin** [comment]
> How to revert it back to what it was?

Nohow

**Comment by ilya-fedin** [comment]
@xpt1x can the issue be closed?

**Comment by xpt1x** [comment]
Sure, thanks for all ur help @ilya-fedin
