### ISSUE TITLE
Bold doesn't work for CJK characters

### ISSUE THREAD

**Issue by Coxxs** [telegramdesktop/tdesktop#7775]
### Steps to reproduce
1. View https://t.me/cjk_test in Telegram Desktop (Windows)
2. No Bold Style in Telegram Desktop for CJK characters: 

### Expected behaviour
(Telegram for Android)
![image](https://user-images.githubusercontent.com/3007303/80856154-f48c7a80-8c79-11ea-936a-37bdde5a83ba.png)

### Actual behaviour
(Telegram Desktop 2.1.1)
![image](https://user-images.githubusercontent.com/3007303/80856113-ab3c2b00-8c79-11ea-8dbd-38898b79e2b5.png)

### Configuration
**Operating system:**
Windows 10 19041.207 (2004)
**Version of Telegram Desktop:**
2.1.1 (However, this issue has been around for a long time.)
**Used theme**:
Default

**Comment by ilya-fedin** [comment]
Please read: #5368 (TL;DR; it will broke arabic fonts)

**Comment by Coxxs** [comment]
Thank you for the link. It's true that CJK fonts in the system do not contain semi-bold style. Is it possible to use bold version of CJK fonts when semi-bold font is requested?

**Comment by ilya-fedin** [comment]
> Is it possible to use bold version of CJK fonts when semi-bold font is requested?

No, at least without patching of Open Sans :(

**Comment by ilya-fedin** [comment]
Is bold characters from this artifact readable for you?
https://github.com/ilya-fedin/tdesktop/actions/runs/94518612

**Comment by Coxxs** [comment]
Yes, looks pretty nice. It's a little too thick compared to semi-bold characters, but still better than no bold.

![image](https://user-images.githubusercontent.com/3007303/80921269-f5232f00-8da7-11ea-934b-4cb02a9fcd14.png)
![image](https://user-images.githubusercontent.com/3007303/80921339-5c40e380-8da8-11ea-818a-b3a928c04f61.png)

Before:
![image](https://user-images.githubusercontent.com/3007303/80921362-84304700-8da8-11ea-8bf9-362f692c3e46.png)

**Comment by Coxxs** [comment]
![image](https://user-images.githubusercontent.com/3007303/80928467-37179980-8dd7-11ea-9231-b7fde3371404.png)

Still have some minor issue, Telegram is using `Light Italic` to display `Regular Italic` text, and using `Regular Italic` to display `Bold Italic` text. This issue seems already exists in old versions, maybe it's better to open another issue after fixing bold font issue.

After testing several different system locales, it turns out it only happens on `Microsoft YaHei` font[1], not on `Malgun Gothic`, `Yu Gothic UI` or `Microsoft JhengHei UI`.

[1] First & third column on the picture is using `Microsoft YaHei`, as YaHei also includes some Japanese characters

**Comment by NekoInverter** [comment]
It's ugly for for me
Telegram: ![image](https://user-images.githubusercontent.com/42698724/80934226-c6ce3f80-8df9-11ea-9ea3-f3ca42b1f161.png)
Chrome :![image](https://user-images.githubusercontent.com/42698724/80934239-d77eb580-8df9-11ea-91d7-32a51a8d3a12.png)

**Comment by ilya-fedin** [comment]
> it turns out it only happens on `Microsoft YaHei` font

Maybe Telegram should use Microsoft YaHei UI? :thinking:
> It's ugly and not quite readable for me

@Coxxs looks like no bold font for you :(

**Comment by Coxxs** [comment]
I adjusted to 125% scaling (used to be 200%), here's the result:

Telegram 2.1.1:
![image](https://user-images.githubusercontent.com/3007303/80935191-1adb2300-8dfe-11ea-9e60-d1f51f450a8b.png)

`actions/runs/94518612`:
![image](https://user-images.githubusercontent.com/3007303/80935214-3c3c0f00-8dfe-11ea-93a4-7d5b6406af21.png)

Microsoft Word:
![image](https://user-images.githubusercontent.com/3007303/80935265-64c40900-8dfe-11ea-8bea-4ae846dc5617.png)

Chrome:
![image](https://user-images.githubusercontent.com/3007303/80935400-fd5a8900-8dfe-11ea-81b5-425b030a3aeb.png)

It seems that Chrome might has some sort of rendering optimize. Telegram just renders same as Microsoft does.

**Comment by ilya-fedin** [comment]
> Telegram just renders the same as Microsoft & Chrome does, when using exact same font size.

Yeah, I agree
@NekoInverter's Chrome screenshot looks for me more unreadable, than his Telegram screenshot

**Comment by ilya-fedin** [comment]
A try with Microsoft YaHei UI, I hope this will fix llight weightt issue
https://github.com/ilya-fedin/tdesktop/actions/runs/94904040https://github.com/ilya-fedin/tdesktop/actions/runs/94904040

**Comment by ilya-fedin** [comment]
it's built

**Comment by Coxxs** [comment]
![image](https://user-images.githubusercontent.com/3007303/80937910-88408100-8e09-11ea-9920-573a6e3be637.png)

Looks good now!

**Comment by ilya-fedin** [comment]
Ok, I added the fix for light weight to PR with korean fonts fix
And created a PR with bold fix: https://github.com/desktop-app/lib_ui/pull/12
But the final decision is up to @john-preston

**Comment by NekoInverter** [comment]
Chinese fonts are now broken on Windows 7🤦‍♂
![IMG_20200506_193732_235](https://user-images.githubusercontent.com/42698724/81172725-5bd76100-8fd1-11ea-8713-b9ff30161ca5.jpg)

**Comment by ilya-fedin** [comment]
> Chinese fonts are now broken on Windows 7man_facepalming

how are they then rendered in the rest of the system?

**Comment by NekoInverter** [comment]
> > Chinese fonts are now broken on Windows 7man_facepalming
> 
> how are they then rendered in the rest of the system?

Microsoft Yahei UI are introduced in Windows 8
I think that's the problem

**Comment by ilya-fedin** [comment]
> Microsoft Yahei UI was introduced in Windows 8 and doesn't exists on Windows 7

Oh, Ihought it Windows Vista+

**Comment by NekoInverter** [comment]
> > Microsoft Yahei UI was introduced in Windows 8 and doesn't exists on Windows 7
> 
> Oh, Ihought it Windows Vista+

Add fallback to Microsoft Yahei probably fix the issue

**Comment by ilya-fedin** [comment]
> Add fallback to Microsoft Yahei probably fix the issue

Does Microsoft JhengHei UI exist on Windows 7?

Which fonts are right, with UI or without?
Different Chinese people says different things.

**Comment by NekoInverter** [comment]
> Microsoft JhengHei UI is included with Windows 8 or later.  

From [Wikipedia](https://en.wikipedia.org/wiki/Microsoft_JhengHei)

**Comment by NekoInverter** [comment]
> > Add fallback to Microsoft Yahei probably fix the issue
> 
> Does Microsoft JhengHei UI exist on Windows 7?
> 
> Which fonts are right, with UI or without?
> Different Chinese people says different things.

> Microsoft JhengHei UI is included with Windows 8 or later.

 From [Wikipedia](https://en.wikipedia.org/wiki/Microsoft_JhengHei)

**Comment by ilya-fedin** [comment]
> From [Wikipedia](https://en.wikipedia.org/wiki/Microsoft_JhengHei)

This doesn't answer the second question, something like a table with default fons for different Windows versions (Vista-10) is needed

Also, what about Yu Gothic UI and Malgun Gothic?

**Comment by NekoInverter** [comment]
> you can use Qt 6's method (call WinApi SystemParametersInfo, https://github.com/qt/qtbase/blob/44e8c90ad4ae5a3d08651a61ac9f0937fb49d26b/src/platformsupport/fontdatabases/windows/qwindowsfontdatabasebase.cpp#L767) to get default GUI font, and set it as the fallback font.
https://github.com/desktop-app/lib_ui/pull/7#issuecomment-619034764

**Comment by ilya-fedin** [comment]
Looks like this is related to the new DirectWrite font database which is not ready yet. Sounds horrible.

**Comment by ilya-fedin** [comment]
Also, looks like this function only selects default font for application when custom font is not set (but tdesktop uses open sans) and doesn't manage fallback

**Comment by NekoInverter** [comment]
You can call SystemParametersInfo directly

**Comment by ilya-fedin** [comment]
I hope that no one will say "it is not so difficult to fix" about CJK font fallback anymore

**Comment by ilya-fedin** [comment]
> You can call SystemParametersInfo directly to get system default font and set it as fallback

Stop, this will not fix the fallback for non-CJK OS

**Comment by ilya-fedin** [comment]
Ok, I replaced all fonts with non-UI ones, so that they are shouldn't have diefferent weight and should be from WIndows Vista. For Japanese I also added Meiryo, since Yu Gothic is from Windows 10.

https://github.com/ilya-fedin/tdesktop/actions/runs/97374407

**Comment by Coxxs** [comment]
The [lightweight issue](https://github.com/telegramdesktop/tdesktop/issues/7775#issuecomment-623203106) for Italic seems to come back again in `runs/97374407`, maybe we could set tryFonts like this?
`
    ...
    "Microsoft YaHei UI",
    "Microsoft YaHei",
    "Arial",
    "Microsoft JhengHei UI",
    "Microsoft JhengHei",
    ...
`

**Comment by ilya-fedin** [comment]
> The [lightweight issue](https://github.com/telegramdesktop/tdesktop/issues/7775#issuecomment-623203106)

How it looks like? Japanese should be light too and there are shouldn't be difference :thinking:

**Comment by Coxxs** [comment]
`runs/97374407` with Chinese locale:
![image](https://user-images.githubusercontent.com/3007303/81218427-c3f96780-9010-11ea-90f3-fada97ae5bd8.png)

* Japanese (third column) is light because it's using Japanese characters included in `Microsoft YaHei`

`runs/97374407` with Japanese locale:
![image](https://user-images.githubusercontent.com/3007303/81218619-120e6b00-9011-11ea-958f-00023503998f.png)

* Seems even regular text are using light weight...

`2.1.2` with Japanese locale:
![image](https://user-images.githubusercontent.com/3007303/81218726-3ec28280-9011-11ea-827e-ffd1fd567434.png)

**Comment by ilya-fedin** [comment]
Ok, I'll try to add the UI ones

**Comment by ilya-fedin** [comment]
It's built

**Comment by Coxxs** [comment]
Telegram 2.1.2 / Windows 7 / Simplified Chinese locale / 100% scaling:
![image](https://user-images.githubusercontent.com/3007303/81226319-412ad980-901d-11ea-9697-bfa4685f7039.png)

`runs/97476086` / Windows 7 / Simplified Chinese locale / 100% scaling:
![image](https://user-images.githubusercontent.com/3007303/81226876-1a20d780-901e-11ea-93d5-611f1dad52fb.png)

`runs/97476086` / Windows 10 / Simplified Chinese locale / 200% scaling:
![image](https://user-images.githubusercontent.com/3007303/81226713-dc23b380-901d-11ea-8a42-4ff47428f9af.png)

**Comment by ilya-fedin** [comment]
> `runs/97476086` / Windows 7 / Japanese locale / 100% scaling:

What happend with italic? Is it the same on 2.1.2 with Japanese locale? 😨

**Comment by ilya-fedin** [comment]
Ah, it's Windows 7. So, this is Meiryo, probably :thinking:

**Comment by ilya-fedin** [comment]
```When italicized, only Latin characters are slanted, not CJK characters and kana. CJK characters use other methods of emphasis or quotation indication; thus differing from, for example, the typefaces of Romance languages (unrelated distinctions between cursive and non-cursive and other traditional writing styles do exist). Nowadays, however, italicization is used in advertising but usually combined with other, common forms of emphasis, such as bold weight, exclamation marks, and, in Japanese, katakana use. ```
https://en.wikipedia.org/wiki/Meiryo
So, this is OK :thinking:

**Comment by ilya-fedin** [comment]
> `runs/97476086` / Windows 7 / Traditional Chinese locale / 100% scaling:

Unfortunately, there are no Microsoft YaHei UI on Windows 7 to fix that. But this is better than nothing, right?

**Comment by Coxxs** [comment]
Microsoft YaHei Light is not introduced until Windows 8.1, so I think Qt is unable to pick a wrong font weight for YaHei in Windows 7 ;)

Vista (& Windows 7) also had [Meiryo UI](https://support.microsoft.com/en-us/help/975929/the-meiryo-ui-font-is-available-for-windows-vista-and-for-windows-serv) font, but I'm not sure if we should use it...

**Comment by ilya-fedin** [comment]
> Vista (& Windows 7) also had [Meiryo UI](https://support.microsoft.com/en-us/help/975929/the-meiryo-ui-font-is-available-for-windows-vista-and-for-windows-serv) font, but I'm not sure if we should use it...

But it is Japanese font, when Microsoft YaHei is Chinese font

**Comment by Coxxs** [comment]
`runs/97476086` / Windows 7 / Japanese locale / 100% scaling:
(using `Meiryo`)
![image](https://user-images.githubusercontent.com/3007303/81253957-668b0800-905c-11ea-9276-034315ece756.png)

`runs/97476086` / Windows 7 / Japanese locale / 100% scaling:
replace `Meiryo` with `Meiryo UI` using FontMod:
![image](https://user-images.githubusercontent.com/3007303/81253921-4eb38400-905c-11ea-8b4f-762db03a06be.png)

Perhaps only Japanese native speaker can tell which style is better...

**Comment by ilya-fedin** [comment]
Wow, Meiryo UI looks closer to Yu Gothic UI. Perhaps I should add it :)

**Comment by ilya-fedin** [comment]
> Microsoft YaHei Light is not introduced until Windows 8.1, so I think Qt is unable to pick a wrong font weight for YaHei in Windows 7 ;)

Then maybe Qt just renders Microsoft YaHei wrongly :(

**Comment by ilya-fedin** [comment]
https://github.com/ilya-fedin/tdesktop/actions/runs/97811194

**Comment by ilya-fedin** [comment]
@Coxxs can you say how do you check which font is used to help to debug #7823?

**Comment by Coxxs** [comment]
I'm only familiar with CJK font, and I checked commit history to find out which font is used... 

But I think #7823 is not a issue related to font, but a issue related to UI design. Actually if you look at Windows & Chrome, they do not use lots of bold fonts in software UI. The intention of this issue is to fix the bold support for chat content area, when opening this issue, I didn't consider that the UI would also changes.

**Comment by ilya-fedin** [comment]
> https://github.com/ilya-fedin/tdesktop/actions/runs/97811194

It's built

**Comment by Coxxs** [comment]
![image](https://user-images.githubusercontent.com/3007303/81260148-03a16d00-906c-11ea-8fa4-7b56c5a0f745.png)

According to https://github.com/microsoft/vscode/pull/79735, most Japanese people prefer narrow style for kana. I think the order of Japanese should be:
```"Yu Gothic UI", "Meiryo UI", "Yu Gothic", "Meiryo"```
or just:
```"Yu Gothic UI", "Meiryo UI"```

Windows 7 already has [Meiryo UI](https://docs.microsoft.com/en-us/typography/fonts/windows_7_font_list), Windows 8.1 shipped [Yu Gothic](https://docs.microsoft.com/en-us/typography/fonts/windows_81_font_list), Windows 10 **1507** shipped [Yu Gothic UI](https://docs.microsoft.com/en-us/typography/font-list/yu-gothic), change the order can provide user with different system version a consistent experience.

**Comment by ilya-fedin** [comment]
Ok, thanks

**Comment by Coxxs** [comment]
`runs/97476086`(#7823) / Windows 7 / Japanese locale / 100% scaling:
![image](https://user-images.githubusercontent.com/3007303/81265519-ce9a1800-9075-11ea-97dd-ea8989c6cdcc.png)

Not found any issues so far

**Comment by ilya-fedin** [comment]
I'll give other build when a solution for persian issue will be found

**Comment by ilya-fedin** [comment]
https://github.com/ilya-fedin/tdesktop/actions/runs/98306815 (it's already built)

**Comment by Coxxs** [comment]
> https://github.com/ilya-fedin/tdesktop/actions/runs/98306815 (it's already built)

Tested on Windows 7 & Windows 10 with different CJK locale, all looks good.

**Comment by ilya-fedin** [comment]
Ok, thanks
