### ISSUE TITLE
Failed Updating

### ISSUE THREAD

**Issue by Eternal-Sina** [telegramdesktop/tdesktop#778]
Hello

I'm using the version of 0.8.17 and niether from the application nor from the website , I can not update my Desktop Telegram to 0.8.20 . I'll be grateful for some help 

Thank you in advance :)

**Comment by auchri** [comment]
Maybe because 0.8.20 is "only" a developer version? :)
wait for the next version, which is 0.8.21 and which will be released soon!

**Comment by Eternal-Sina** [comment]
Oops! Didn't notice that . Thank you & I'm looking forward for that day :+1:
