### ISSUE TITLE
"View results" button for votes is greyed / not working

### ISSUE THREAD

**Issue by Laiteux** [telegramdesktop/tdesktop#7780]
I don't really know what exactly is causing this, but I'm unable to view a vote results on Telegram Desktop, while it works perfectly fine on iOS.

The "view results" button is grey. Behavior is the same when vote is running and vote is done.

![](https://share.laiteux.dev/qegzpq)

### Expected behaviour
Vote results should be shown, works perfectly fine on iOS

### Actual behaviour
Nothing happens when I click the button

### Configuration
**Operating system:** Windows 10

**Version of Telegram Desktop:** 2.1.1 (Latest)

**Comment by mymedia2** [comment]
same on GNU/Linux Debian (sid)
