### ISSUE TITLE
Telegram Desktop 2.1.1 in OS X Yosemite 10.10

### ISSUE THREAD

**Issue by versionzer0** [telegramdesktop/tdesktop#7786]
### Steps to reproduce
1. Install New Telegram Desktop  (Latest Version 2.1.1- Version grate than 1.8.5)
2. Open Telegram Desktop App

### Expected behaviour
Telegram Works fine without any problem.

### Actual behaviour
Telegram Crash and Show below Error:
`Dyld Error Message:
  Library not loaded: /System/Library/Frameworks/Metal.framework/Versions/A/Metal
  Referenced from: /Applications/Telegram.app/Contents/MacOS/Telegram
  Reason: image not found`

### Configuration
**Operating system: OS X Yosemite 10.10 pure without any update**

**Version of Telegram Desktop: Version Grate than 1.8.15 to latest 2.1.1**

**Used theme**:Dark

<details><summary><b>Logs</b>:</summary>
Process:               Telegram [37491]
Path:                  /Applications/Telegram.app/Contents/MacOS/Telegram
Identifier:            com.tdesktop.Telegram
Version:               ???
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           Telegram [37491]
User ID:               501

Date/Time:             2020-05-03 06:21:53.084 +0430
OS Version:            Mac OS X 10.10 (14A389)
Report Version:        11

Time Awake Since Boot: 510000 seconds
Time Since Wake:       2900 seconds

Crashed Thread:        0

Exception Type:        EXC_BREAKPOINT (SIGTRAP)
Exception Codes:       0x0000000000000002, 0x0000000000000000

Application Specific Information:
dyld: launch, loading dependent libraries

Dyld Error Message:
  Library not loaded: /System/Library/Frameworks/Metal.framework/Versions/A/Metal
  Referenced from: /Applications/Telegram.app/Contents/MacOS/Telegram
  Reason: image not found

Binary Images:
    0x7fff67451000 -     0x7fff67487837  dyld (353.2.1) <4696A982-1500-34EC-9777-1EF7A03E2659> /usr/lib/dyld
    0x7fff8b13c000 -     0x7fff8b13cfff  com.apple.Cocoa (6.8 - 21) <EAC0EA1E-3C62-3B28-A941-5D8B1E085FF8> /System/Library/Frameworks/Cocoa.framework/Versions/A/Cocoa
    0x7fff8d56f000 -     0x7fff8d56ffff  com.apple.CoreServices (62 - 62) <9E4577CA-3FC3-300D-AB00-87ADBDDA2E37> /System/Library/Frameworks/CoreServices.framework/Versions/A/CoreServices
    0x7fff8f5e8000 -     0x7fff8f67effb  com.apple.CoreMedia (1.0 - 1562.19) <F79E0E9D-4ED1-3ED1-827A-C3C5377DB1D7> /System/Library/Frameworks/CoreMedia.framework/Versions/A/CoreMedia
    0x7fff91000000 -     0x7fff91118ffb  com.apple.CoreText (352.0 - 454.1) <AB07DF12-BB1F-3275-A8A3-45F14BF872BF> /System/Library/Frameworks/CoreText.framework/Versions/A/CoreText
    0x7fff9175d000 -     0x7fff91760fff  com.apple.IOSurface (97 - 97) <D4B4D2B2-7B16-3174-9EA6-55E0A10B452D> /System/Library/Frameworks/IOSurface.framework/Versions/A/IOSurface
    0x7fff9287e000 -     0x7fff9288eff7  libbsm.0.dylib (34) <A3A2E56C-2B65-37C7-B43A-A1F926E1A0BB> /usr/lib/libbsm.0.dylib
    0x7fff92c37000 -     0x7fff92c83ff7  libcups.2.dylib (408) <9CECCDE3-51D7-3028-830C-F58BD36E3317> /usr/lib/libcups.2.dylib
    0x7fff933e9000 -     0x7fff9377ffff  com.apple.CoreFoundation (6.9 - 1151.16) <F2B088AF-A5C6-3FAE-9EB4-7931AF6359E4> /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation
    0x7fff96a78000 -     0x7fff972b1ff3  com.apple.CoreGraphics (1.600.0 - 772) <936D081F-37B3-3DA3-B725-118D0B07DDD2> /System/Library/Frameworks/CoreGraphics.framework/Versions/A/CoreGraphics

</details>

**Comment by john-preston** [comment]
Thanks. Looks like I've linked those non-supported frameworks although they are not used and Xcode didn't even warn me. I'll try removing them in the next version, thanks.

**Comment by john-preston** [comment]
Please check the version 2.1.2.

**Comment by versionzer0** [comment]
> Please check the version 2.1.2.

Thanks, It`s work like a charm.
