### ISSUE TITLE
The "Download path" option is not available for Telegram Desktop (Microsoft Store edition)

### ISSUE THREAD

**Issue by xmha97** [telegramdesktop/tdesktop#7788]
Hello,

The "Download path" option is available for Telegram Desktop (standard edition):
![image](https://user-images.githubusercontent.com/23485114/80905934-59061300-8d28-11ea-90db-315ba9a8f48b.png)

but it is not available for Telegram Desktop (Microsoft Store edition):
![image](https://user-images.githubusercontent.com/23485114/80905831-51466e80-8d28-11ea-8223-afd15f724a3e.png)

That's why I can't change the download path:
![image](https://user-images.githubusercontent.com/23485114/80907213-4096f800-8d2a-11ea-909f-68d714fadff8.png)

Now I want to store Telegram downloads in `%LocalAppData%\Packages\TelegramMessengerLLP.TelegramDesktop_t4vj0pshhgkwm\LocalCache\Roaming\Telegram Desktop UWP\tdata\tdld`
I don't like to see my Telegram downloads in the `%UserProfile%\Downloads\Telegram Desktop` folder.

Please fix this issue instead of closing it.
Thanks.

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/6086
cannot be fixed.
