### ISSUE TITLE
Korean font bug

### ISSUE THREAD

**Issue by lunamoth** [telegramdesktop/tdesktop#7789]
### Steps to reproduce
1. typing korean
2. 
3. 

### Actual behaviour
This is a 2.1.1 version bug for Telegram Desktop Windows.

When using Hangeul, Korean fonts come out as "Gungseo" and it is difficult to read. Please change to "Malgun Gothic" font.

### Configuration
**Operating system:**
Windows 10 

**Version of Telegram Desktop:**
2.1.1

**Installation source (Linux Only)** - the official website / GitHub releases / flatpak / snap / distribution package:
Windows

**Used theme**:
default

**Comment by ilya-fedin** [comment]
#7773
