### ISSUE TITLE
Prevent sleep when video is being played

### ISSUE THREAD

**Issue by mehdipourfar** [telegramdesktop/tdesktop#7790]
### Is your feature request related to a problem?
When I play a long video in Telegram, after five minutes my PC goes to stand by mode. Please prevent sleep when video is being played.

### Additional context
I use ubuntu.

**Comment by BLaDZer** [comment]
this issue still actual

**Comment by mehdipourfar** [comment]
Please fix before closing the issue:)

**Comment by Aokromes** [comment]
https://stackoverflow.com/questions/34836406/how-to-prevent-windows-from-going-to-sleep-when-my-c-application-is-running

**Comment by agurenko** [comment]
This would also apply to Video Calls as during the video call they power saving feature and lock screen kicks in
