### ISSUE TITLE
Can no longer paste a copied image with right-click > paste since 2.1.1

### ISSUE THREAD

**Issue by daniels1989** [telegramdesktop/tdesktop#7794]
### Steps to reproduce
1. Copy an image from the web.
2. Right-click the chatbox and try to paste the image, the option will be disabled.

(Note that on very rare occasions certain images can still be pasted through the contextmenu. However in these cases, when cancelling the send image dialog, the title attribute and url of the image are pasted into the textbox, which doesn't normally happen with other images.)

### Expected behaviour
It should open up the "send image" dialog as it did in 2.1.0, and as it still does using Ctrl V in 2.1.1

### Actual behaviour
The option to paste is disabled in the contextmenu

### Configuration
**Operating system:** Win10 x64 build 18363.778

**Version of Telegram Desktop:** 2.1.1

**Used theme**: Null

**Comment by Aokromes** [comment]
works for me taking:
https://russos.livejournal.com/ the image of aircraft.

**Comment by daniels1989** [comment]
I've no idea what the difference in the images would be, but if I go to, for example, Google Images, and take any random image from there I cannot paste it through the contextmenu, whereas in 2.1.0 there's no problems. Most, if not all, images from 9gag also don't work.

Here's a video showcasing the difference between 2.1.1 and 2.1.0, using the aircraft image from your livejournal, a random google image, and 2 random 9gag images: https://youtu.be/jWq5QHgt9kQ

**Comment by nfxpnk** [comment]
#7806
I have a same issue: https://gfycat.com/illustrioustestyjackrabbit

**Comment by Aokromes** [comment]
you need to wait for 2.1.2 release to get it fixed, or compile yourself.
