### ISSUE TITLE
Touch Bar style on Mac for video and audio seeking [Feature Request] 

### ISSUE THREAD

**Issue by glofru** [telegramdesktop/tdesktop#7795]
### Is your feature request related to a problem?
When you're playing a video with Mac, the Touch Bar is empty.

### Describe the solution you'd like
It would be useful a classic video playing Touch Bar style like this:
<img width="1004" alt="image" src="https://user-images.githubusercontent.com/33641238/80922314-8381bb80-8d7c-11ea-999d-0b1211e2a160.png">

### Describe alternatives you've considered
Showing at least the normal Touch Bar mode.

### Additional context
None.

**Comment by damnfella** [comment]
Please edit the title of this issue to:

`Touch Bar style on Mac for video and audio seeking`
