### ISSUE TITLE
[Feature Request] Hide folders panel in chat-only window.

### ISSUE THREAD

**Issue by Vista1nik** [telegramdesktop/tdesktop#7797]
### Is your feature request related to a problem?
No.

### Describe the solution you'd like
Hide folders panel in small chat-only window.

### Additional context
<img src="https://user-images.githubusercontent.com/16061243/80956844-b1addc80-8e0a-11ea-9107-ac51e8d60a71.png"  width="250" />

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/7534
