### ISSUE TITLE
[Feature Request] Send messages from inline bots without sound

### ISSUE THREAD

**Issue by AlexWayfer** [telegramdesktop/tdesktop#7798]
### Is your feature request related to a problem?

I want to use inline bots and send messages, suggested by them, without sound.

### Describe the solution you'd like

Context menu (RBM) on inline bot suggestions with the same options as for regular Send button.

### Describe alternatives you've considered

Nothing.

### Additional context

Regular context menu:

![image](https://user-images.githubusercontent.com/6510020/80967007-538af480-8e1e-11ea-8df7-e91fe784f00c.png)

There is no menu:

![image](https://user-images.githubusercontent.com/6510020/80967098-7917fe00-8e1e-11ea-847c-267faa2d4c96.png)

**Comment by damnfella** [comment]
It makes sounds when you click on inline messages? 🤔

**Comment by AlexWayfer** [comment]
> It makes sounds when you click on inline messages? 🤔

It's about notification sound for receiver.

https://telegram.org/blog/silent-messages-slow-mode

**Comment by AlexWayfer** [comment]
I see such functionality in version 2.4.3. Thank you!
