### ISSUE TITLE
OSX Shortcuts

### ISSUE THREAD

**Issue by edgard** [telegramdesktop/tdesktop#78]
It would be awesome if add the possibility to use the usual suspects for window management on OSX. Those for example:

Command-M: minimize window
Command-H: hide window (and lose focus)
Command-W: close window (but don't quit)
Command-Q: quit

**Comment by vahotm** [comment]
Cmd+Backspace (remove line) shortcut is very handy when editing messages, but it doesn't work. Nevertheless Alt+Backspace (remove word) works.
