### ISSUE TITLE
How do I make Telegram forget channels I left?

### ISSUE THREAD

**Issue by utmuk** [telegramdesktop/tdesktop#7800]
<img width="285" alt="01" src="https://user-images.githubusercontent.com/28525658/80997425-f60c9d00-8e49-11ea-9508-3cd5757e0a14.PNG">
<img width="523" alt="02" src="https://user-images.githubusercontent.com/28525658/80997435-f9a02400-8e49-11ea-8bb7-1c845c4872d0.PNG">

When you "export telegram data". You will see in the result not only the channels you are subscribed to now, but also channels, which you were subscribed to in the past. I didn't find a way to get rid of this information. Many people don't even know about this. They subscribe to a channel, which compromises them in some way. Then they leave it, but the information about you being subscribed in the past is still there.

I would like telegram app and servers completely forget channels which I left!

Or maybe some way to force forget them?

In any case it is not right to make the history of visited channels undeletable!!!

**Comment by RadRussianRus** [comment]
This repository is for Telegram Desktop app, not Telegram itself.

As stated in [Telegram Privacy Policy, section 12](https://telegram.org/privacy#12-questions-and-concerns), you can contact [@GDPRbot](https://t.me/gdprbot) with `/contact` command, if you have questions about this data.
