### ISSUE TITLE
Version 2.1.1 changes the display font, sometimes breaking the text altogether

### ISSUE THREAD

**Issue by FoxSays** [telegramdesktop/tdesktop#7801]
![Telegram_yTn1kpbf7r](https://user-images.githubusercontent.com/9268172/81037142-ad51f400-8edc-11ea-8f53-c7e923f319b0.png)
Font change after update to 2.1.1

![Telegram_1jTR6Bt38R](https://user-images.githubusercontent.com/9268172/81037208-cd81b300-8edc-11ea-906d-5bc070caa274.png)
Reference - screenshot from 2.1.0

![image](https://user-images.githubusercontent.com/9268172/81037245-eee29f00-8edc-11ea-9810-22e61ae5443d.png)
Broken text on my friend's computer after update to 2.1.1

### Steps to reproduce
None. Simply update to 2.1.1
Note: I have only seem text breaking on my friend's machine (Windows 10), but also was triggered by 2.1.1 update. 

### Expected behaviour
Display font should not change - the font from before was perfectly legible. 

### Actual behaviour
The changed display font breaks readability on Korean Windows machines. 
In my friend's case, it completely broke all Korean text so that it was unreadable. (Latin characters does not seem to be affected by this) 

### Configuration
**Operating system:**
Windows 10 Pro, Korean w/ most recent updates. 

**Version of Telegram Desktop:**
2.1.1 Portable (mine) and installed (friend). 

**Used theme**:
Default/Dark. Behavior does not change with themes. 

### Other information
It was proposed that this might be the solution,
https://github.com/telegramdesktop/tdesktop/commit/3c1c17ef80043fead409237c9c902d89110b3356
but changing the locale did nothing to aid the situation - nor does it seem like a good solution to change the system locale to fix the font display issue. My problem was temporarily fixed by altering registry "HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\FontSubstitutes\MS Shell Dlg 2". 
Nothing helped my friend, however, and he simply rolled back to 2.1.0, which does not have this issue.

**Comment by ilya-fedin** [comment]
#7773

**Comment by FoxSays** [comment]
Ah, sorry. Did not realize the issue was already solved.
