### ISSUE TITLE
[Feature Request] There should be an option to modify display font. 

### ISSUE THREAD

**Issue by FoxSays** [telegramdesktop/tdesktop#7802]
### Is your feature request related to a problem?
As is, Telegram Desktop simply uses system display font to display everything with no option to alter it in any way from within the application. 

This makes usage of Telegram troublesome for shared computer situations where one is not simply able to change the system display font to their liking. Furthermore, some languages require different fonts for optimal legibility. If one wished to communicate in a language other than the one their system is configured to, then they might wish to change 

Having it this way also creates Issues like #7773 and #5368.

### Describe the solution you'd like
There should be an option to change the display font of the messages. What font to use, and what size it should be displayed in.

**Comment by ilya-fedin** [comment]
#90

**Comment by FoxSays** [comment]
Holy hell this has been an issue this long and it was never addressed?
