### ISSUE TITLE
Use identical download directory structure as mobile app.

### ISSUE THREAD

**Issue by PanderMusubi** [telegramdesktop/tdesktop#7803]
### Steps to reproduce
1. Receive images, video, audio and documents in Telegram mobile app
2. Receive images, video, audio and documents in Telegram desktop

### Expected behaviour
Files in mobile app and desktop app should be downloaded in the folders:
* Telegram Audio
* Telegram Documents
* Telegram Images
* Telegram Video

### Actual behaviour
Files for desktop app are stored in simply:
* Telegram

When using e.g. Syncthing to synchronize files over smartphones, tablets, laptops and desktops, this is a problem. To compare, WhatsApp does use the same folder structure for all its apps and file synchronization works. Fixing this in Telegram's Desktop will enable easy file synchronization, backup, sorting of files and clearing up files.

### Configuration
**Operating system:** Ubuntu 20.04

**Version of Telegram Desktop:** 2.0.1

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/1359#issuecomment-590591567
