### ISSUE TITLE
[Feature Request] Nested formatting for HyperLinks

### ISSUE THREAD

**Issue by damnfella** [telegramdesktop/tdesktop#7804]
### Nested Hyperlinks
Such formatting currently might not be not supported by Telegram's APIs, but I wish to see at least some of them:
- Bold Hyperlink: <b>[hyperlink](http://duck.com)</b>
- Italic Hyperlink: _[hyperlink](http://duck.com)_
- Strikethrough Hyperlink: ~~[hyperlink](http://duck.com)~~

Note: Hyperlinks are underlined when hovered upon and would look weird for desktop users, so just forget what you thought.

**Comment by RememberTheAir** [comment]
> Such formatting currently might not be not supported by Telegram's APIs

They're all supported, underlined hyperlinks included

**Comment by damnfella** [comment]
@RememberTheAir Are you sure? Can you confirm you see the results on tdesktop or some other client?

**Comment by RememberTheAir** [comment]
![image](https://user-images.githubusercontent.com/16143208/81058474-cd7ab680-8ece-11ea-8d9e-755a7b2a2bc3.png)

can confirm

**Comment by damnfella** [comment]
Ok, I am going just close this issue, and include in #7805
