### ISSUE TITLE
[Feature Request] Nested Formatting (nested entities)

### ISSUE THREAD

**Issue by damnfella** [telegramdesktop/tdesktop#7805]
### Nested Formatting
Although TDesktop supports displaying of these nested entities which were composed on Telegram's Android client, **TDesktop users cannot compose the following nested entites:**

- Bold Italic: ![Hvjm8TRaNbP3J](https://user-images.githubusercontent.com/51771172/81051065-ba6fe280-8ede-11ea-82ba-8b66040b6dbf.png)
- Bold Underline: ![rty032oDwPpTc](https://user-images.githubusercontent.com/51771172/81051064-b8a61f00-8ede-11ea-8d76-2dfbe1eb54cb.png)
- Italic Underline: ![TFZOrfP4Vb](https://user-images.githubusercontent.com/51771172/81053030-1b4cea00-8ee2-11ea-9b34-53652f107df7.png)
- Bold Strikethrough: ![afegthewgf](https://user-images.githubusercontent.com/51771172/81051173-e8552700-8ede-11ea-8e88-06146d56f6aa.png)
- Italic Strikethrough: ![edrftgyuh](https://user-images.githubusercontent.com/51771172/81052575-51d63500-8ee1-11ea-8f34-52f35b8f6cec.png)
- Underline Strikethrough: ![09h3u4njf](https://user-images.githubusercontent.com/51771172/81052513-2e12ef00-8ee1-11ea-8cc3-bb4d074d9291.png)
- Bold Italic Underline: ![okkjnhbgv](https://user-images.githubusercontent.com/51771172/81052919-f0fb2c80-8ee1-11ea-9363-06d03eb43cb9.png)
- Bold Italic Strikethrough: ![bold italic strikethrough](https://user-images.githubusercontent.com/51771172/81060218-a385bc00-8eef-11ea-95a6-6cc696eb01ab.png)
- Bold Underline Strikethrough: ![bold underline strike](https://user-images.githubusercontent.com/51771172/81053550-e1c8ae80-8ee2-11ea-84c5-81794b2f4ce5.png)
- Italic Underline Strikethrough: ![9Enujaw1eq](https://user-images.githubusercontent.com/51771172/81052752-a7124680-8ee1-11ea-9a9d-cca2f3ae1e4f.png)
- Bold Italic Underline Strikethrough: ![awgghuijttg](https://user-images.githubusercontent.com/51771172/81052793-b6918f80-8ee1-11ea-8df9-9d5adfc15a8f.png)

***
### Nested Formatting for Hyperlinks
If supported by the API, please allow TDesktop users to format hyperlinks too:

- Bold Hyperlink: <b>[hyperlink](http://duck.com)</b>
- Italic Hyperlink: _[hyperlink](http://duck.com)_
- Strikethrough Hyperlink: ~~[hyperlink](http://duck.com)~~
- Bold Italic Hyperlink: <b><em>[hyperlink](http://duck.com)</em></b>
- Bold Strikethrough Hyperlink: ~~<b>[hyperlink](http://duck.com)</b>~~
- Italic Strikethrough Hyperlink: ~~<em>[hyperlink](http://duck.com)</em>~~
- Bold Italic Strikethrough Hyperlink: ~~<b><em>[hyperlink](http://duck.com)</em></b>~~

***
**Underlined hyperlinks**, can be ignored given that it looks weird for desktop users (mouse hover underlines links by default):
- Underline Hyperlink: <u>[hyperlink](http://duck.com)</u>
- Bold Underline Hyperlink: <b><u>[hyperlink](http://duck.com)</u></b>
- Italic Underline Hyperlink: <em><u>[hyperlink](http://duck.com)</u></em>
- Bold Italic Underline Hyperlink: <b><em><u>[hyperlink](http://duck.com)</u></em></b>
- Bold Underline Strikethrough Hyperlink: ~~<b><u>[hyperlink](http://duck.com)</u></b>~~
- Italic Underline Strikethrough Hyperlink: ~~<em><u>[hyperlink](http://duck.com)</u></em>~~
- Bold Italic Underline Strikethrough Hyperlink: ~~<b><em><u>[hyperlink](http://duck.com)</u></em></b>~~

SORRY, GITHUB DOES NOT RENDER UNDERLINED HYPERLINKS.

**Comment by Neurotoxin001** [comment]
Still need it.

**Comment by damnfella** [comment]
WE STILL NEED THIS !! @john-preston

**Comment by boingo-00** [comment]
Do it! Just do it!

**Comment by Neurotoxin001** [comment]
This issue should be №1 priority

**Comment by damnfella** [comment]
still needed

**Comment by boingo-00** [comment]
Bump

**Comment by Neurotoxin001** [comment]
https://github.com/telegramdesktop/tdesktop/commit/6b520ecc05604ab27a0f92caebd4ec7bf0ec8f20
