### ISSUE TITLE
Copied image in Google Chrome can't be pasted into chat with drop-down menu

### ISSUE THREAD

**Issue by nfxpnk** [telegramdesktop/tdesktop#7806]
### Steps to reproduce
1. Copy any image in Google Chrome
2. Try to paste copied image into chat with drop-down menu

### Expected behaviour
**Paste** option should be active in drop-down menu

### Actual behaviour
**Paste** option is inactive in drop-down menu (grayed)

### Configuration
**Operating system:** Windows 10.0.18363 N/A Build 18363

**Version of Telegram Desktop:** 2.1.1

**Installation source (Linux Only)** - the official website / GitHub releases / flatpak / snap / distribution package: the official website

**Used theme**: Default theme

Video of this bug: https://gfycat.com/illustrioustestyjackrabbit

**Comment by ilya-fedin** [comment]
#7794
