### ISSUE TITLE
[Feature Request] Possibility to download and open image via 1 click

### ISSUE THREAD

**Issue by mvxxx** [telegramdesktop/tdesktop#7807]
### Is your feature request related to a problem?
Currently, after opening photo in telegram desktop, we cannot do anything more due to blocked whole screen by image.
https://imgur.com/AWCQDEF
### Describe the solution you'd like
Possibility to download and open image via **1 click** or any other reasonable solution.

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/1710
