### ISSUE TITLE
Crash in "Edit folder" section

### ISSUE THREAD

**Issue by alessiocelentano** [telegramdesktop/tdesktop#7809]
### Steps to reproduce
1. Right click on a folder
2. Select "Edit folder"
3. Delete 2+ chats that no longer exist (deleted bot/channel)
4. Click on "Save" button

### Expected behaviour
It should remove the chats from the folder and return to the home

### Actual behaviour
It remove the chats but the app crashed. Moreover,when performing the first two steps, it still show chat that no longer exist (but not in the folder)

### Configuration
**Operating system:** Arch Linux

**Version of Telegram Desktop:** 2.1.1

**Installation source (Linux Only)** - Arch official repository (pacman)

**Used theme**: Night

**Comment by Aokromes** [comment]
try updating to 2.1.2

**Comment by alessiocelentano** [comment]
> try updating to 2.1.2

Mmm, it seems fixed now
