### ISSUE TITLE
Arabic/Persian chat titles are Bold in chat list - 2.1.2

### ISSUE THREAD

**Issue by samij263** [telegramdesktop/tdesktop#7813]
### Steps to reproduce
1. update
2. 
3. 

### Expected behaviour
Tell us what should happen
chat titles should be in normal format

### Actual behaviour
Tell us what happens instead
after updating to 2.1.2 version Arabic/Persian chat titles became bold

### Configuration
**Operating system:**
windows 7

**Version of Telegram Desktop:**
2.1.2

**Installation source (Linux Only)** - the official website / GitHub releases / flatpak / snap / distribution package:

**Used theme**:
tinted (dark)

<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by john-preston** [comment]
@samij263 Yes, the bold font is now bold for all characters, not only latin.

**Comment by ilya-fedin** [comment]
Also look at #7773

**Comment by Sepehrtooz** [comment]
After the last update I can't send ZWNJ anymore :(

**Comment by ilya-fedin** [comment]
> After the last update I can't send ZWNJ anymore :(

What do you mean?

**Comment by Sepehrtooz** [comment]
> > After the last update I can't send ZWNJ anymore :(
> 
> What do you mean?

![Capture](https://user-images.githubusercontent.com/55192376/81150563-55c38f00-8f95-11ea-94db-c6cd538beb70.PNG)

I could send links without any text with this character
![Capture2](https://user-images.githubusercontent.com/55192376/81150580-607e2400-8f95-11ea-8f04-9a28c6c88fab.PNG)

**Comment by ilya-fedin** [comment]
How does this related to the bold font?

**Comment by Sepehrtooz** [comment]
> How does this related to the bold font?

Changes in fonts

**Comment by ilya-fedin** [comment]
> Changes in fonts

Fonts can't control web preview

**Comment by Sepehrtooz** [comment]
I meant after these changes in fonts (all characters can be bold now, not only Latin), I can't send the ZWNJ character without any other character.
I used to hide links with this character

**Comment by ilya-fedin** [comment]
> I can't send the ZWNJ character without any other character

Font change can't prohibit you to send only specified characters

**Comment by Sepehrtooz** [comment]
> Font change can't prohibit you to send only specified characters

When I send this character, it remains like the attached image for a moment and after that, it's removed.

**Comment by ilya-fedin** [comment]
> When I send this character, it remains like the attached image for a moment and after that, it's removed.

This still is not related to fonts

**Comment by ilya-fedin** [comment]
@samij263 can you check which font is used by Firefox in your system for arabic?
https://github.com/telegramdesktop/tdesktop/issues/7823#issuecomment-625032943
