### ISSUE TITLE
Folder with set of channels minus read shows all set of channels

### ISSUE THREAD

**Issue by aavezel** [telegramdesktop/tdesktop#7814]
### Steps to reproduce

1. Subscribe a set of various news channels
2. Create a new folder
- included chats: add set of various channels from chats list
- excluded chats: read
3. Open the folder

### Expected behaviour

The folder should contain only unread channels (see unread folder)

### Actual behaviour

The folder contains all channels (read and unread). This makes it difficult to monitor news when the channel list does not fit in one screen and some channels with unread news are deep down.

### Configuration

Operating system: Ubuntu 18.04

Version of Telegram Desktop: 2.1.2

**Comment by RememberTheAir** [comment]
This is how the API works - exceptions don't apply to the chats you have manually included

**Comment by damnfella** [comment]
Let **Amanda (a), Bruno (b), Charlie (b)** be your "set of channels".
* _Amanda_ (a) contains UNREAD messages.
* _Bruno_ (b) and _Charlie_ (c) contain READ messages.

> Included chats: Set of Channels {a,b,c}
> Excluded chats: READ {b,c}

Thus, Folder should contain only Alpha {a}.

But you say:
> Expected behaviour: The folder contains all channels (read and unread).

Excuse me, but are you drunk? @aavezel

**Comment by aavezel** [comment]
If you think this is the expected behavior of the API, then is ok
