### ISSUE TITLE
[Question] Graceful shutdown in window managers without borders + icons?

### ISSUE THREAD

**Issue by electronblue** [telegramdesktop/tdesktop#7815]
I am using dwm and have yet to find a way to shut down telegram-desktop when one doesnt use  icons on ones DE/window manager (as in my case) in the statusbar. From inside tdesktop there is no way to quit the program, as far as I can tell? So far I have always had to kill the process, which obviously isn't ideal. Is there some way to quit the program that does not involve using the icon that you would use on normal desktop environments?

**Comment by ilya-fedin** [comment]
If there are no tray, the tdesktop should exit by window close
Check if you have the latest version, since there are was a bug with tray detection.

**Comment by mendelmaleh** [comment]
I do ctrl+q
