### ISSUE TITLE
Ugly UI font after 2.0.1

### ISSUE THREAD

**Issue by roytam1** [telegramdesktop/tdesktop#7816]
### Steps to reproduce
1. Update existing Telegram Desktop to versions newer than 2.0.1 on non-HiDPI system
2. Open updated Telegram

### Expected behaviour
Tidy Chinese characters can be displayed.
![image](https://user-images.githubusercontent.com/1192577/81185399-1e300380-8fe4-11ea-9d2e-7515be1a9491.png)

### Actual behaviour
distorted Chinese characters are shown instead.
![image](https://user-images.githubusercontent.com/1192577/81185279-fb055400-8fe3-11ea-9b40-0cbb344750b8.png)

### Configuration
**Operating system:**
Windows 7 SP1 x64 (Traditional Chinese edition)

**Version of Telegram Desktop:**
2.1.2

**Installation source (Linux Only)** - the official website / GitHub releases / flatpak / snap / distribution package:

**Used theme**:
https://t.me/addtheme/kWdJkey5DsHCxvAU

<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

I suspect this commit make display worse:
https://github.com/telegramdesktop/tdesktop/commit/3c1c17ef80043fead409237c9c902d89110b3356

**Comment by ilya-fedin** [comment]
Could you test this build?
https://github.com/ilya-fedin/tdesktop/actions/runs/97374407

**Comment by roytam1** [comment]
> Could you test this build?
> https://github.com/ilya-fedin/tdesktop/actions/runs/97374407

yes it is a lot better than official build:
![image](https://user-images.githubusercontent.com/1192577/81234224-f0ba7880-902a-11ea-94b2-35d88dcabf73.png)

**Comment by ilya-fedin** [comment]
Could you try this as well?
https://github.com/ilya-fedin/tdesktop/actions/runs/97476086

**Comment by roytam1** [comment]
> Could you try this as well?
> https://github.com/ilya-fedin/tdesktop/actions/runs/97476086

more or less same as https://github.com/telegramdesktop/tdesktop/issues/7816#issuecomment-624921819 : 
![image](https://user-images.githubusercontent.com/1192577/81304431-a29b8880-90af-11ea-8a25-09dc9fc054b8.png)

**Comment by ilya-fedin** [comment]
thanks

**Comment by oldherl** [comment]
https://github.com/telegramdesktop/tdesktop/issues/7837

**Comment by roytam1** [comment]
@Aokromes please tell me why this issue is closed?

**Comment by ilya-fedin** [comment]
Because it was fixed
