### ISSUE TITLE
Zero With Non-Joiner (ZWNJ) in name of groups and channels

### ISSUE THREAD

**Issue by neesti** [telegramdesktop/tdesktop#7817]
Dear Developers, 
It seems that Telegram Desktop 2.1.2 dose not support Zero With Non-Joiner (ZWNJ) character in name of groups and channels and even private messages!
Now this character is converted to space character.
There is not this bug in name of folders and content of groups, channels and private messages.

**Comment by john-preston** [comment]
@neesti "does not support .. and even private messages"
"not this bug in .. and private messages"

So are private messages good or no?

**Comment by neesti** [comment]
Oh sorry. I mean There is this bug in **contact name** of received private messages. 

Now I noticed there is this bug into **bio field** too.

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/6959

**Comment by neesti** [comment]
You linked this bug to #6959 but there was not this bug in Telegram **2.1.1**

**Comment by neesti** [comment]
In Persian language, We use Shift+Space for insert of ZWNJ character.

**Comment by neesti** [comment]
Dear @Aokromes 
Please attention to this act that there **was not** this bug in Telegram 2.1.1 even in **Linux Mint OS**.

**Comment by Aokromes** [comment]
> Dear @Aokromes
> Please attention to this act that there **was not** this bug in Telegram 2.1.1 even in **Linux Mint OS**.
> 
> I will thank if you reopen this bug report.

it's called regresion, if the bug was fixed somewhere bettween the report and this ticket, and that ticket is same bug, i leave older ticket for same bug opened.

**Comment by ilya-fedin** [comment]
> You linked this bug to #6959 but there was not this bug in Telegram **2.1.1**

Are you sure that this replace is not done by the server? Can you check on other clients?

**Comment by neesti** [comment]
@ilya-fedin 
I checked this bug in Web version of Telegram (Version 0.7.0) . 
There is this bug in it too!

**Comment by ilya-fedin** [comment]
So this is not a tdesktop bug :)

**Comment by john-preston** [comment]
@neesti This should be fixed soon from the server side.

**Comment by Aokromes** [comment]
so, i can close https://github.com/telegramdesktop/tdesktop/issues/6959 too?

**Comment by ilya-fedin** [comment]
> so, i can close #6959 too?

I'm not sure. There are was https://bugreports.qt.io/browse/QTBUG-42074, maybe preston's widget doesn't have the fix :(
Ask him.
