### ISSUE TITLE
crash when trying to select a file  to send (Ubuntu 20.04)

### ISSUE THREAD

**Issue by walidamriou** [telegramdesktop/tdesktop#7819]
### Steps to reproduce
1. Open Telegram
2. Click select a file button

### Expected behaviour
Tell us what should happen
Open Files manager to select a file to send 
### Actual behaviour
Tell us what happens instead
Telegram close

### Configuration
**Operating system:**
Ubuntu 20.04
**Version of Telegram Desktop:**
2.1.2

**Installation source (Linux Only)** - the official website / GitHub releases / flatpak / snap / distribution package: snap - snapcraft.io - Telegram FZ-LLC

**Used theme**:

<details><summary><b>Logs</b>:</summary>

</details>

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/7343 ?

**Comment by walidamriou** [comment]
@Aokromes Telegram close after click 'Attach file' button

**Comment by Aokromes** [comment]
> @Aokromes Telegram close after click 'Attach file' button

i am asking if it's same bug or diferent bug.

**Comment by ilya-fedin** [comment]
It is the same if Wayland is used

**Comment by ilya-fedin** [comment]
@walidamriou are you using wayland? what are you get in console on crash?

**Comment by walidamriou** [comment]
That's what happened when I clicked the button:
![Screenshot from 2020-05-06 21-46-54](https://user-images.githubusercontent.com/10174229/81285766-4b21fc00-9060-11ea-9c56-1218c7b3de1d.png)

**Comment by ilya-fedin** [comment]
maybe gtk-common-themes was update and broken :thinking:

**Comment by walidamriou** [comment]
That's what happened when I changed the theme by tweak and open telegram and clicked the button:
![Screenshot from 2020-05-07 12-56-17](https://user-images.githubusercontent.com/10174229/81286956-39415880-9062-11ea-92d3-4a3e535b0810.png)

**Comment by Aokromes** [comment]
@walidamriou plz run it under gdb.

**Comment by ilya-fedin** [comment]
> plz run it under gdb.

no sense

> That's what happened when I changed the theme by tweak and open telegram and clicked the button:

All themes are from gtk-common-themes :(

**Comment by walidamriou** [comment]
We should try to repeat the same conditions (Telegram from snap + Ubuntu 20.04 + last updates) to see if the bug only with me, or It's a general bug with all users.

**Comment by walidamriou** [comment]
The problem fixed in version 2.1.3.

**Comment by ilya-fedin** [comment]
But we didn't change anything related to file choose :thinking:

**Comment by walidamriou** [comment]
@ilya-fedin  I don't know how exactly the problem fixed, but I close telegram, and it updated to version 2.1.3, and I tested the button and it worked !!
