### ISSUE TITLE
Voice message - Shortcut and auto Play

### ISSUE THREAD

**Issue by brunobsouzac** [telegramdesktop/tdesktop#782]
How the same subject, I'll leave what I wrote in another post.

#22 

The new update 0.8.21 released the voice message, but it would be more convenient for those using the desktop a shortcut key to tighten and talk instead of using the mouse.

Something like Ctrl + Space (and a warning users about the function)

And finally, radio voice messages with auto play, so we would listen in real time as a Voxer / Zello / Radio. The Telegram iOS already have this option but it is not released to the Android or WP. To disable this feature if you want, an exposed button on the chat would be ideal.

It would be perfect for Desktop, iOS, Android and WP

![1](https://cloud.githubusercontent.com/assets/12419098/7948439/59f436ea-095a-11e5-9563-1f10ece14ec3.png)

Automated voice messages would be about the same as in Voxer:
https://www.youtube.com/watch?v=2HsZRxOavOU

**Comment by brunobsouzac** [comment]
@telegramdesktop

**Comment by mbnoimi** [comment]
+1

**Comment by phplego** [comment]
+1

**Comment by vmkazakoff** [comment]
+1 too

**Comment by chevi** [comment]
+1
