### ISSUE TITLE
Bold and ugly font after 2.1.2 update

### ISSUE THREAD

**Issue by javad94** [telegramdesktop/tdesktop#7823]
### Steps to reproduce
1. update
2. check contact or channel with Persian letters in the title of inline buttons.
3. 

### Expected behaviour
The font should be normal.

### Actual behaviour
The font is bold and ugly.

### Configuration
**Operating system:**
Windows 10
**Version of Telegram Desktop:**
2.1.2
**Installation source (Linux Only)** - the official website / GitHub releases / flatpak / snap / distribution package:
The official website
**Used theme**:
Any themes
<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>
<img width="388" alt="Telegram_Telegram_2020-05-07_08-34-50" src="https://user-images.githubusercontent.com/7765309/81253635-42b8c980-903e-11ea-85f6-dcd3d509e992.png">

**Comment by ilya-fedin** [comment]
#7813

**Comment by ilya-fedin** [comment]
> The font should be normal.

Why? It is should be bold.

> The font is bold and ulgy.

How then you use bold in the rest for the system, if it is ugly for you?

**Comment by javad94** [comment]
> How then you use bold in the rest for the system, if it is ugly for you?

No, it's not. Take for example "**مشاهده نظرات**". compare it with my screenshot. it's much better and more readable on Chrome than on Telegram. 

![image](https://user-images.githubusercontent.com/7765309/81255319-9e855180-9042-11ea-8f13-c7c38288e33d.png)

**Comment by ilya-fedin** [comment]
> No, it's not.

Can you say which font uses telegram and which chrome?

**Comment by ilya-fedin** [comment]
I can suggest to check MS Shell Dlg 2 and Arial Unicode MS, also Qt can grab the first font in alphabetical order which has these glyphs

**Comment by Raymonf** [comment]
@ilya-fedin The chat title changed for CJK too, unsurprisingly.

Not gonna lie, I noticed it and was wondering what happened, and then I realized it was just bold. It looks like a trash fire.

**Comment by ilya-fedin** [comment]
> It looks like a trash fire.

There are problems with WIndows 7, look at #7816

**Comment by javad94** [comment]
> Can you say which font uses telegram and which chrome?

Apparently Github on Chrome uses _Segoe UI_ for Persian font. I don't know about Telegram.

**Comment by ilya-fedin** [comment]
> Apparently Github on Chrome uses _Segoe UI_ for Persian font.

Definitely not. Look at #5368, when preston added Segoe UI fallback - persian fonts was even more ugly.

**Comment by javad94** [comment]
> Definitely not. Look at #5368, when preston added Segoe UI fallback - persian fonts was even more ugly.

May I ask which screenshot is Segoe UI?

**Comment by ilya-fedin** [comment]
> May I ask which screenshot is Segoe UI?

"new font"

**Comment by javad94** [comment]
> I can suggest to check MS Shell Dlg 2 and Arial Unicode MS, also Qt can grab the first font in alphabetical order which has these glyphs

I couldn't find MS Shell Dlg 2 on my PC. but Arial Unicode MS is ugly as hell.
![image](https://user-images.githubusercontent.com/7765309/81256295-4d2a9180-9045-11ea-8788-4942f845aa0a.png)

**Comment by ilya-fedin** [comment]
> but Arial Unicode MS is ugly as hell.

Can it be the font which telegram is used?

**Comment by javad94** [comment]
> "new font"

Interesting, I checked that using chrome dev tools and when I removed Segoe UI the font changed.

**Comment by javad94** [comment]
> Can it be the font which telegram is using?

Yeah, it looks like it. Why not add an option in setting to change Telegram font?

**Comment by ilya-fedin** [comment]
> and when I removed Segoe UI the font changed

Which font Chrome is using now? :thinking:

**Comment by javad94** [comment]
> Which font Chrome is using now? 🤔

It's definitely using Segoe UI.
![image](https://user-images.githubusercontent.com/7765309/81256664-5e27d280-9046-11ea-9011-c2f28850945b.png)

**Comment by ilya-fedin** [comment]
Maybe it fallback to an other font?

**Comment by javad94** [comment]
> Maybe it fallbacks to an other font?

In my last screenshot?

**Comment by ilya-fedin** [comment]
> In my last screenshot?

yes

**Comment by ilya-fedin** [comment]
For instance, Firefox allows me to check which font is actually used

![image](https://user-images.githubusercontent.com/17829319/81256866-48ec7d00-9021-11ea-906a-9aa6e3b8a7c2.png)

**Comment by javad94** [comment]
> > In my last screenshot?
> 
> yes

I have Segoe UI on my PC, so I'm sure it's not fell back to another font.

**Comment by ilya-fedin** [comment]
> I have Segoe UI on my PC, so I'm sure it's not fell back to another font.

The question is: *does Segoe UI has these glyphs, or GDI automatically fallbacks to another which have these glyphs?*

**Comment by javad94** [comment]
> For instance, Firefox allows me to check which font is actually used

I checked on Firefox and it also says the font is Segoe UI.

![image](https://user-images.githubusercontent.com/7765309/81257159-d0e57d80-9047-11ea-9025-c5162fc3bad1.png)

**Comment by ilya-fedin** [comment]
Oh, this is weird :\

**Comment by javad94** [comment]
> The question is: _does Segoe UI has these glyphs, or GDI automatically fallbacks to another which has these glyphs?_

That's far out of my knowledge. How we can find out?

**Comment by ilya-fedin** [comment]
> How we can find out?

Firefox did that, you're right, it's Segoe UI. But then #5368 goes into mystic :(

**Comment by ilya-fedin** [comment]
Can you check which font is used on Firefox under Windows 7?

**Comment by javad94** [comment]
> Firefox did that, you're right, it's Segoe UI. But then #5368 goes into mystic :(

Segoe UI is not exactly a pretty font for Persian letters but it's miles better than Arial Unicode MS.
Do you know Telegram used which font before 2.1.2 update?

**Comment by ilya-fedin** [comment]
> Do you know Telegram used which font before 2.1.2 update?

Font is not changed, just bold is enabled

**Comment by javad94** [comment]
> Can you check which font is used in Firefox under Windows 7?

Unfortunately, I don't have Windows 7 installed.

**Comment by ilya-fedin** [comment]
I'll try to do some Qt patching, I hope that it is possible to use Segoe UI correctly

**Comment by ilya-fedin** [comment]
This is test build, it should build in ~2 hours
https://github.com/ilya-fedin/tdesktop/actions/runs/97843908

**Comment by javad94** [comment]
> I'll try to do some Qt patching, I hope that it is possible to use Segoe UI correctly

Thanks, appreciate that.

**Comment by javad94** [comment]
> > Do you know Telegram used which font before 2.1.2 update?
> 
> Font is not changed for arabic languages, just bold is enabled

I checked all my fonts to find which font Telegram uses and I found that it uses Tahoma font. 

![image](https://user-images.githubusercontent.com/7765309/81258390-cd072a80-904a-11ea-8c26-96691d0a6e82.png)

![image](https://user-images.githubusercontent.com/7765309/81258423-e27c5480-904a-11ea-9129-c9e38567b3ac.png)

**Comment by ilya-fedin** [comment]
I wonder what [this](https://github.com/telegramdesktop/tdesktop/issues/5368#issuecomment-439308021) guy feels now xD

**Comment by javad94** [comment]
> I wonder what [this](https://github.com/telegramdesktop/tdesktop/issues/5368#issuecomment-439308021) guy feels now xD

Very bad taste of fonts :D

**Comment by ilya-fedin** [comment]
> https://github.com/ilya-fedin/tdesktop/actions/runs/97843908

It's built

**Comment by javad94** [comment]
> > https://github.com/ilya-fedin/tdesktop/actions/runs/97843908
> 
> It's built

How to install and use it?

**Comment by ilya-fedin** [comment]
> How to install and use it?

Unpack zip and start Telegram.exe. It will use data from the same directory where you place it.

**Comment by ilya-fedin** [comment]
@javad94 What is the result?

**Comment by Sepehrtooz** [comment]
> > https://github.com/ilya-fedin/tdesktop/actions/runs/97843908
> 
> It's built

it works for me and uses Segoe UI (windows 7) but it's still ugly

**Comment by ilya-fedin** [comment]
> but it's still ugly

why then this is not ugly in other applications?

**Comment by Sepehrtooz** [comment]
> why then it is not ugly in other applications?

I installed windows 10 Segoe UI font, now it's better, but it has a problem with showing the bottom of some letters like " پ "

![Capture5](https://user-images.githubusercontent.com/55192376/81289538-d78de800-907b-11ea-80cc-d467340789bc.PNG)

چپ : 

![Capture6](https://user-images.githubusercontent.com/55192376/81290038-99dd8f00-907c-11ea-99a5-c99039e58935.PNG)

**Comment by ilya-fedin** [comment]
> I installed windows 10 Segoe UI font

Which font is used in other applications for Persian on Windows 7?

**Comment by Sepehrtooz** [comment]
> Which font is used in other applications for Persian on Windows 7?

Windows10 Segoe UI

**Comment by ilya-fedin** [comment]
> Windows10 Segoe UI

I mean before you installed windows 10 segoe ui. I want to understand why other applications looks good and tdesktop is not by default.

**Comment by Sepehrtooz** [comment]
> I mean before you installed windows 10 segoe ui. I want to understand why other applications looks good and tdesktop is not by default

Before installing Windows 10 Segoe UI, [this tdesktop](https://github.com/ilya-fedin/tdesktop/actions/runs/97843908) (and all apps) was using Windows 7 Segoe UI and that font wasn't beautiful in Persian

**Comment by ilya-fedin** [comment]
You want to say that all apps has ugly font in Persian on Windows 7?

**Comment by Sepehrtooz** [comment]
yes, but now it's better with Windows 10 Segoe UI

**Comment by ilya-fedin** [comment]
Maybe add Vazir font to tdesktop :thinking:

**Comment by Sepehrtooz** [comment]
Yes. Vazir font is a good choice

**Comment by Sepehrtooz** [comment]
With Vazir font this problem will not happen again. Right?

> I installed windows 10 Segoe UI font, now it's better, but it has a problem with showing the bottom of some letters like " پ "
> 
> ![Capture5](https://user-images.githubusercontent.com/55192376/81289538-d78de800-907b-11ea-80cc-d467340789bc.PNG)
> 
> چپ :
> 
> ![Capture6](https://user-images.githubusercontent.com/55192376/81290038-99dd8f00-907c-11ea-99a5-c99039e58935.PNG)

**Comment by ilya-fedin** [comment]
> With Vazir font this problem will not happen again. Right?

I don't even know how they should look like :)

**Comment by ilya-fedin** [comment]
https://github.com/ilya-fedin/tdesktop/actions/runs/98210521

**Comment by ilya-fedin** [comment]
Looks like there are a breaking commit for emojis, I started a new action:
https://github.com/ilya-fedin/tdesktop/actions/runs/98227263

**Comment by ilya-fedin** [comment]
> https://github.com/ilya-fedin/tdesktop/actions/runs/98227263

I forgot to add LoadCustomFont call. There's right build and it's built already:
https://github.com/ilya-fedin/tdesktop/actions/runs/98306815
Waiting for feedback :)

**Comment by Sepehrtooz** [comment]
> https://github.com/ilya-fedin/tdesktop/actions/runs/98306815

Now it's beautiful and modern 👍🏼

![Capture7](https://user-images.githubusercontent.com/55192376/81322879-d5428280-90a9-11ea-9c42-03b8dc651406.PNG)

**Comment by javad94** [comment]
> https://github.com/ilya-fedin/tdesktop/actions/runs/98306815

That's great. Thank you. are you used Vazir font?

![image](https://user-images.githubusercontent.com/7765309/81325958-59970480-90ae-11ea-860e-237b04dfe7aa.png)

**Comment by ilya-fedin** [comment]
> Did you use Vazir font?

yep

**Comment by javad94** [comment]
> yep

Excellent choice 👌

**Comment by javad94** [comment]
> yep

When this change will be released to stable?

**Comment by ilya-fedin** [comment]
> When this change will be released to stable?

When preston will release new verson

**Comment by javad94** [comment]
> When preston will release new verson

I see. Thanks.

**Comment by Neurotoxin001** [comment]
Now it's too fat
![image](https://user-images.githubusercontent.com/39812401/81408186-716d9780-9145-11ea-94ff-cfa5bed85867.png)

**Comment by john-preston** [comment]
@Neurotoxin001 Not it is just normal bold font. Perhaps it's fine if we get used to it.

**Comment by Neurotoxin001** [comment]
Is there any way to get back semi-bold? Because "normal bold" still too fat.

**Comment by pongo** [comment]
Looks like too bold
![2020-05-08_162855](https://user-images.githubusercontent.com/142528/81412793-1049c200-914d-11ea-8392-af6fa277f849.png)

**Comment by sky93** [comment]
New Vazir font is very good ♥
