### ISSUE TITLE
Telegram does not properly handle localhost URLs

### ISSUE THREAD

**Issue by DASPRiD** [telegramdesktop/tdesktop#7827]
### Steps to reproduce
1. Send a message with a localhost URL: http://localhost

### Expected behaviour
Telegram should convert it to a clickable link like any other URL.

### Actual behaviour
Telegram is not converting it to a link. Since http://127.0.0.1 works, I assume the Telegram parser has a bug where it expects the hostname to have a TLD.

### Configuration
Any.

**Comment by brasofilo** [comment]
I reproduced the issue and noticed that for _a brief moment_ the link renders correctly and then is unlinked/converted to plain text. Maybe it's done on purpose (...?)

**Comment by Aokromes** [comment]
it looks api issue, android doesn't handle http://localhost/ too.

**Comment by DASPRiD** [comment]
The bug is still present.

**Comment by Aokromes** [comment]
such feature belongs to https://bugs.telegram.org/

**Comment by KES777** [comment]
Why this is a API issue? issue about how message is displayed. I successfully send a message formatted.

The issue about how this sent MarkdownV2 is displayed
