### ISSUE TITLE
[Feature Request]  Add the ability to appear in the alt + tab menu

### ISSUE THREAD

**Issue by kotfantazer** [telegramdesktop/tdesktop#7829]
Please add the ability to display telegram in the alt + tab menu when the telegram window is minimized to the tray

**Comment by Aokromes** [comment]
i don't think such thing is doable, idk a single windows program allowing this.

**Comment by kotfantazer** [comment]
Solution. 
Add setting: show the application window on the taskbar when an incoming message is received
