### ISSUE TITLE
Voice Messages - Change input device in settings

### ISSUE THREAD

**Issue by thijskuilman** [telegramdesktop/tdesktop#783]
First of all, I really like that the voice message feature is added to Telegram desktop! 

I would like to see an option in the settings to change the input device. That would be more convenient than having to change the default input device in the Windows settings. :)

Keep up the good work!

**Comment by brunobsouzac** [comment]
It would be great, I'm having problems with my dell vostro 3500. No one hears my voice mail, Skype had the same problem but it was enough to change the Skype settings and it worked, but in the Telegram even changing the windows can not.

**Comment by austrargentina** [comment]
Experiencing the same problem so adding this feature some time soon would be really nice! 

And thanks for the awesome work! Keep it up!

**Comment by TheAppService** [comment]
Maybe in the same run the control of the output device used while calling would be a nice thing ;)

**Comment by anfimovir** [comment]
Confirmed in latest version (1.2.1), if microphone - unvailable:

1. Hide icons for Call and Send Voice Messages.
2. Do not display information about incoming calls.

**Comment by KelvinShadewing** [comment]
I found a fix. In the Pulse Audio volume utility, go to input devices, and set the microphone you want to use as the fallback device (click the checkbox), then restart Telegram.

**Comment by senglory** [comment]
Telegram 1.6.7 on Win10 - where should I make a choice of the suitable mike for the Telegram instance? I see no options in TG settings.

**Comment by Aokromes** [comment]
this was implemented long time ago, you can change it on the hamburger->calls->settings.

**Comment by electronstudio** [comment]
Unfortunately that setting does not work.  It does not matter which device you select, the fallback device is still always the one used.

**Comment by maxim-uvarov** [comment]
hamburger->calls->settings doesn't change input device. At least camera

**Comment by Aokromes** [comment]
it does to me
https://i.imgur.com/hf8XYUp.png

**Comment by maxim-uvarov** [comment]
> it does to me
> https://i.imgur.com/hf8XYUp.png

@Aokromes, have you tried to record the video message?

**Comment by maxim-uvarov** [comment]
https://s3-eu-central-1.amazonaws.com/nfd/PublicSharebales/2020-11-17_20-24-09-1605619517.mp4

**Comment by Biithagoras** [comment]
Is it possibility to change the input device in pulseaudio while recording? I cant find a wayto record and use my mouse at the same time, because i have to hold the recording button.
