### ISSUE TITLE
2.1.2 win7 x64 stickers look smaller

### ISSUE THREAD

**Issue by imashxtyz** [telegramdesktop/tdesktop#7832]
Is this intentional behaviour? If so why so? What's the point in reducing size on desktop?

**Comment by john-preston** [comment]
@imashxtyz To be a little closer to other Telegram apps (all have even smaller size, including mobile, macOS native, web app).

**Comment by Aokromes** [comment]
in fact, this ticket complained about being to large
https://github.com/telegramdesktop/tdesktop/issues/735
