### ISSUE TITLE
Chat Tabs

### ISSUE THREAD

**Issue by specter78** [telegramdesktop/tdesktop#7834]
I NEED 2 chats open side-by-side which doesn't seem possible with the present version of the app. Please add a feature whereby multiple chats can be opened in tabs.

**Comment by RememberTheAir** [comment]
Kind of duplicate of #2105

**Comment by specter78** [comment]
Instead of multiple tabs, multiple instance of the same app can also be a solution.

**Comment by ilya-fedin** [comment]
Run tdesktop with different workdir
`Telegram -workdir path/to/workdir`

**Comment by specter78** [comment]
> Run tdesktop with different workdir
> 
> `Telegram -workdir path/to/workdir`

Thanks.
