### ISSUE TITLE
See chat when open telegram but not connected to internet

### ISSUE THREAD

**Issue by HamidRezaAshkiyan** [telegramdesktop/tdesktop#7836]
In telegram android if you open telegram you'll see chats even if your not connected to internet.
I would be great if we could have same functionality on telegram desktop thats happen to me so many times I want to just see something without connecting to internet specially when we dont have good connection or VPN.

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/1087
