### ISSUE TITLE
[Feature Request] Stop fighting over font choices and provide a font selection option

### ISSUE THREAD

**Issue by oldherl** [telegramdesktop/tdesktop#7837]
### Is your feature request related to a problem?
In recent versions, font names and weights are changing back and forth, because one font simply won't satisfy all people.

### Describe the solution you'd like
Add options to let users pick their preferred UI font (family, weight, size...) for messages, names, and everything else.
This way nobody would be arguing over this problem.

### Describe alternatives you've considered
Read custom CSS (or QSS) from some location on the filesystem.

### Additional context
This world is diverse. Trying to fit one font for all people is unfair for the minorities. Telegram is customizable by so-called "theme", but the font family and size are not changeable in the theme! This is ridiculous.

**Comment by oldherl** [comment]
FYI, some characters in different languages share the same codepoints in Unicode, but should appear differently. Forcing to use the same font would render them incorrect in some languages. And no. not everyone speaks only the language as the system locale. Don't make ignorant assumptions and provide options.

**Comment by ilya-fedin** [comment]
#90 :)

**Comment by oldherl** [comment]
@ilya-fedin OK, but that issue is locked, and I fail to see any progress or proposal to implement it.

**Comment by ilya-fedin** [comment]
Fallbacks should be OK now, just a little occasion with Open Sans

**Comment by AndydeCleyre** [comment]
> Fallbacks should be OK now, just a little occasion with Open Sans

What does this mean? How can one choose the fonts (other than breaking the included ones at build time)?

**Comment by ilya-fedin** [comment]
> What does this mean?

Font fallback for different writing systems are becoming better

> How can one choose the fonts (other than breaking the included ones at build time)?

Nohow AFAIK
