### ISSUE TITLE
Deletes parts of message while typing

### ISSUE THREAD

**Issue by JoshuaDietz** [telegramdesktop/tdesktop#7838]
### Steps to reproduce
1. Open a chat and start typing a message

### Expected behaviour
The text I typed is in the chat field and I can press enter to send it

### Actual behaviour
Sometimes out of nothing the last X (probably about 5) seconds of text I typed are deleted. I am pretty sure that the root cause is that an older draft of my message is pulled from the cloud and overwrites parts of my progress. This is not an issue that you only have once a month. I'd say it happens for every 5th (longer, at least two lines) message. As hotfix it should at least be possible to disable draft sync because losing the typing progress all the time is really anoying.

### Configuration
**Operating system:**
Debian 9 with i3 window manager

**Version of Telegram Desktop:**
2.1.2

**Installation source (Linux Only)** - the official website / GitHub releases / flatpak / snap / distribution package:
Official Website

**Comment by ilya-fedin** [comment]
#7178
#4364
#2229
