### ISSUE TITLE
Using wrong microphone / recording device

### ISSUE THREAD

**Issue by brunobsouzac** [telegramdesktop/tdesktop#784]
I'm having problems with my dell vostro 3500. No one hears my voice message, Skype had the same problem but it was enough to change the Skype settings and it worked, but in the Telegram even changing in the windows can not.

@telegramdesktop 

Thanks team

**Comment by zloster** [comment]
First, thanks for the great work of Telegram team. Continue with the good work.
I have similar problem with the new voice messages on the desktop version (0.8.21). I've tested the Linux version on Ubuntu 12.04.05: when I start to record a voice message I don't see change in the Ubuntu sound indicator desktop applet (when application is recording it has two sliders for the volume: one for the speakers, the other for the microphone) and the voice message is empty - no sounds in it.

**Comment by 24252411** [comment]
I cancel all thje accounts. tank you .so dont send my nothing

2015-06-03 2:29 GMT-05:00 Radoslav Petrov <notifications@github.com>:

**Comment by auchri** [comment]
Maybe because telegram desktop is using the wrong input device :( 
#783

**Comment by zloster** [comment]
Thanks for the update.

**Comment by auchri** [comment]
If operating system does not have a single microphone to record voice messages, then perhaps should not display an icon to send a voice message.

**Comment by UnAfraid** [comment]
I've notice that telegram still tries to use the first device it recognized on start.
I have speakers and headphones that i use from time to time, and if i plug my headphones they get new primary sound device for everything but telegram, it still uses the speakers.

**Comment by amiremami** [comment]
Microphone sends mute voice message in telegram.

**Comment by Lazek** [comment]
Confirmed in 1.0.6. 


If operating system does not have a single microphone to record voice messages, then perhaps should not display an icon to send a voice message.

To prevent sending empty messages.

**Comment by stek29** [comment]
@brunobsouzac @auchri What about changing the title then?

**Comment by lupinia** [comment]
This is still happening in version 1.0.14 of the Windows client; I have multiple microphones for multiple different types of recordings, but no matter what I do, I cannot get Telegram to use any of them other than my webcam.  I've tried setting the vocal mic to be the OS default, and disabling every input device/port except the vocal mic, and I still get empty audio files because, as far as I can tell, it's trying to use the webcam's microphone even when it's disabled (it's certainly not capturing audio from anywhere else).  

I know this is a relatively advanced setup, but on most PCs, you really can't make safe assumptions about which audio input device is the "right" one.  Most people have at least two (a headset and a webcam with built-in microphone).  And trying to record from a disabled device is a pretty severe problem on its own.  

So, could we please get something in the settings to show the audio devices detected by Telegram, and select the one we want to use?  Or, failing that, could the audio-device selection code be modified to use the operating system's default device?

**Comment by auchri** [comment]
Duplicate #783

**Comment by pietrondo** [comment]
same problem on my linux machine..

**Comment by MichaelDono** [comment]
Same here on Linux, try to use an otherwise fully functioning microphone, but Telegram tries to use the muted (in system settings) internal mic

**Comment by Rapti** [comment]
Telegram does not respect my default microphone settings (KDE on Arch Linux) and does not provide a way to select a microphone manually. This leaves me unable to send voice messages from my PC and needs to be fixed.

**Comment by Seikku** [comment]
Telegram Desktop 1.2.6 in Ubuntu 16.04.3 LTS. 
Voice calls work fine, but voice message records a silent message.
Could someone point me to the place where I could dig up the difference and patch?

**Comment by dariox2** [comment]
Temporary workaround:
Clean cache (as suggested by [Erusy](https://github.com/Erusy in [this thread](https://github.com/telegramdesktop/tdesktop/issues/2231):
`$ rm -r ~/.pulse ~/.pulse-cookie ~/.config/pulse`
Open pavucontrol and choose fallback device.
(effective only until next reboot).

**Comment by mmuruev** [comment]
Still no solution?? Have Yeti Pro external USB mic the same problem.

**Comment by mmuruev** [comment]
What about USB mic?

**Comment by KelvinShadewing** [comment]
I found a fix. In the Pulse Audio volume utility, go to input devices, and set the microphone you want to use as the fallback device (click the checkbox), then restart Telegram.

**Comment by dariox2** [comment]
I can confirm the solution proposed by @KelvinShadewing worked for me (Ubuntu 16.04, Telegram 1.5.15). Thanks!

**Comment by mmuruev** [comment]
New telegram client is able to select input devices. So the issue doesn't exist anymore.

**Comment by sarether** [comment]
> New telegram client is able to select input devices. So the issue doesn't exist anymore.

Where is it?
I want to specify a microphone device (hw:1,0).

**Comment by electronstudio** [comment]
> New telegram client is able to select input devices. So the issue doesn't exist anymore.

Unfortunately that setting does not work.  It does not matter which device you select, the fallback device is still always the one used.

**Comment by Jocho-Smith** [comment]
Yes, I have the same problem

**Comment by RubesWorld** [comment]
Hey just figured it out. It appears to select your DEFAULT computer microphone and headset for the voice chat. 

1. Side Menu
2. Calls
3. Settings Icon 
4. Others Settings -> Open System Sound Preferences
5. Choose Your Default
