### ISSUE TITLE
Linux Mint 19.3 & system tray icon

### ISSUE THREAD

**Issue by a-kurau** [telegramdesktop/tdesktop#7841]
### Steps to reproduce
Just run an application. And the system tray icon changed to this
https://i.imgur.com/qe4fJBa.png
TG 2.1.1 worked fine

### Configuration
**Operating system:** Linux Mint 19.3 Cinnamon x64

**Version of Telegram Desktop:** 2.1.3, 2.1.2

**Installation source (Linux Only)** - the official website

**Used theme**: Mint-Y-Dark

<details><summary><b>Logs</b>:</summary>
[log_start0.txt](https://github.com/telegramdesktop/tdesktop/files/4600281/log_start0.txt)
</details>

**Comment by ilya-fedin** [comment]
It's ok, icon is taken from your system theme

**Comment by a-kurau** [comment]
> It's ok, icon is taken from your system theme

So, why TG <= 2.1.1 did not use it ?
https://i.imgur.com/Nz07N2f.png

**Comment by ilya-fedin** [comment]
Because this is new feature

**Comment by ilya-fedin** [comment]
https://github.com/telegramdesktop/tdesktop/issues/7774#issuecomment-624712532
