### ISSUE TITLE
Bug with Switch Inline Query Current Chat + ForceReply

### ISSUE THREAD

**Issue by DO97** [telegramdesktop/tdesktop#7842]
Hello, I noticed a different behaviour on Telegram Desktop.

Every time a user presses on a button with "switch_inline_query_current_chat" he'll get the reply (to message) interface.
That should be False by default, as it is for any other version of Telegram. Also, I can't do anything about it, because it's impossible to use ForceReply(force_reply=False) with an inline keyboard.
This problem only happens in groups and supergroups, but not in private chats.

Windows 10 Home - Telegram Desktop 2.1.3

**Comment by ilya-fedin** [comment]
#6600?

**Comment by DO97** [comment]
Exactly. Only a few minutes ago I noticed that there's already a simple pull request to fix this issue. (#6619)
