### ISSUE TITLE
Timestamp font in messages is broken

### ISSUE THREAD

**Issue by L4vlet** [telegramdesktop/tdesktop#7843]
### Steps to reproduce
1. Open the app and/or any chat in it

### Expected behaviour
TImestamps have the regular font

### Actual behaviour
Font either got broken or was changed without any notificatrions

### Configuration
**Operating system:** Windowns 10

**Version of Telegram Desktop:** 2.13

**Used theme**: Night Mode

![Telegram_BI2B7m92JB](https://user-images.githubusercontent.com/46034951/81430577-4fd1d780-9168-11ea-9425-5748a8deb954.png)

**Comment by ilya-fedin** [comment]
How did you get this?
![image](https://user-images.githubusercontent.com/17829319/81432691-e98e8a00-9152-11ea-8028-118db7981e54.png)

**Comment by L4vlet** [comment]
¯\_(ツ)_/¯
It doesn't dissaper even after restart

**Comment by ilya-fedin** [comment]
Which OS locale you're using?

**Comment by L4vlet** [comment]
English (United States)

**Comment by ilya-fedin** [comment]
Is this valid for 2.1.6?

**Comment by L4vlet** [comment]
Yes, it's still here

**Comment by Aokromes** [comment]
cannot reproduce myself, maybe you have broken font?

**Comment by L4vlet** [comment]
Can we check it somehow?

**Comment by Coxxs** [comment]
This issue do exists in specific region, e.g., Hong Kong.

Version 2.1.14 beta / Windows 10 19041.239 (2004)
![image](https://user-images.githubusercontent.com/3007303/86190068-fb4e4580-bb75-11ea-917e-7505f2d91645.png)

**Comment by ilya-fedin** [comment]
> This issue do exists in specific region, e.g., Hong Kong.

:thinking: even though I set Hong Kong region, Windows doesn't have in Region format list anything except Russian and English format

**Comment by Coxxs** [comment]
> > This issue do exists in specific region, e.g., Hong Kong.
> 
> 🤔 even though I set Hong Kong region, Windows doesn't have in Region format list anything except Russian and English format

Seems true... Maybe you need to add a Language in `Settings -> Time & Language -> Language` first
