### ISSUE TITLE
Thai font are difficult to read

### ISSUE THREAD

**Issue by fordantitrust** [telegramdesktop/tdesktop#7845]
Hi, I updated Telegram to 2.1.3. Thai font are difficult to read.

[Example Screen](https://imgur.com/rvIdiAF)

Please return to use font version 2.1.2

**Comment by ilya-fedin** [comment]
Which font was before?

**Comment by fordantitrust** [comment]
Hi,
[Example Screen font in version 2.1.2](https://imgur.com/o27t0T9)

**Comment by ilya-fedin** [comment]
Why didn't you specified your OS?

**Comment by fordantitrust** [comment]
Ok,

I use on Windows 10 Pro (1909).

**Comment by ilya-fedin** [comment]
thanks
Which name of the font that was used before?

**Comment by fordantitrust** [comment]
I think Tahoma, because I haven't modified anything about default font on Windows 10.

**Comment by ilya-fedin** [comment]
Can you give some Thai characters?

**Comment by fordantitrust** [comment]
Ok, below this example.

> มนุษย์ทั้งหลายเกิดมามีอิสระและเสมอภาคกันในเกียรติศักดิ์และสิทธิ ต่างมีเหตุผลและมโนธรรม และควรปฏิบัติต่อกันด้วยเจตนารมณ์แห่งภราดรภาพ

**Comment by ilya-fedin** [comment]
Thanks!

**Comment by ilya-fedin** [comment]
Could you test this build?
https://github.com/ilya-fedin/tdesktop/actions/runs/99361613

**Comment by ilya-fedin** [comment]
Oh, looks like I forgot to enable artifact upload :(

**Comment by ilya-fedin** [comment]
That's a build with fix. Waiting for you to test :)
https://github.com/ilya-fedin/tdesktop/actions/runs/99474363

**Comment by DobaKung** [comment]
Thai texts are now displayed in Tahoma. Thanks!

[Screenshot](https://d.zartre.com/ZBtTI6)

**Comment by fordantitrust** [comment]
The Thai character display has returned. 

Thanks.

[Example Screen](https://imgur.com/naFjg4p)

**Comment by camlogical** [comment]
Khmer fonts also small. unreadble.

![Screenshot 2020-05-09 13 00 55](https://user-images.githubusercontent.com/57839516/81466395-a4726280-91fb-11ea-98e4-43a0a47e47cb.png)

**Comment by ilya-fedin** [comment]
> Khmer fonts also small. unreadble.

Is this release or the test build?

**Comment by fordantitrust** [comment]
> 
> 
> Khmer fonts also small. unreadble.
> 
> ![Screenshot 2020-05-09 13 00 55](https://user-images.githubusercontent.com/57839516/81466395-a4726280-91fb-11ea-98e4-43a0a47e47cb.png)

I'm not sure about language. I think is not thai language.

**Comment by camlogical** [comment]
@ilya-fedin  In release. Did you fixed most languages on test build?

**Comment by ilya-fedin** [comment]
> Did you fixed most languages on test build?

It should

**Comment by camlogical** [comment]
I got this error on test build.
![Screenshot 2020-05-09 14 17 00](https://user-images.githubusercontent.com/57839516/81467013-02a14480-9200-11ea-89a2-e25d27ad6cdc.png)

**Comment by ilya-fedin** [comment]
That's strange

**Comment by Aokromes** [comment]
follow here plz
https://github.com/telegramdesktop/tdesktop/issues/7851

**Comment by camlogical** [comment]
I hope telegram fix this fonts bug soon.

**Comment by gunnrcrakr** [comment]
> That's a build with a fix. Waiting for you to test :)
> https://github.com/ilya-fedin/tdesktop/actions/runs/99474363

This build have some little lag.

**Comment by ilya-fedin** [comment]
> This build have some little lag.

Maybe, this is debug build
