### ISSUE TITLE
[Feature Request] "Delete all from this user" requires no confirmation and not explicit enough

### ISSUE THREAD

**Issue by vforvoid** [telegramdesktop/tdesktop#7847]
Currently supergroup admin has an ability to remove all the messages of some particular user by setting corresponding checkbox in a popup window. No doubt it's a very destructive non-revertible action, but as of now desktop client doesn't show any additional popups asking for confirmation. Besides, "Delete all from this user" is not explicit enough and doesn't tell me if this messages will be removed only for me or for entire supergroup.

### Describe the solution you'd like
I would like to see an extra Yes/No confirmation popup that explicitly tells me what is exactly about to happen if I confirm the removal: it will irreversibly remove all the messages of particular user from the supergroup for all the other participants.

### Describe alternatives you've considered
It would be nice to have an ability to revert recent admin's actions, but I guess it's much harder to implement.

![image](https://user-images.githubusercontent.com/14206129/81457920-208f8a80-91a9-11ea-8d65-1193f9060727.png)

**Comment by Aokromes** [comment]
i think it's like that for every client.

**Comment by DO97** [comment]
It's right and it should be like this for all of them.

**Comment by Aokromes** [comment]
imho "delete all from this user" must warn how much messages is going to delete.

**Comment by vforvoid** [comment]
I think it's still requires both better explanation and confirmation dialog. I can un-ban some user, but if I remove this user's messages, they're gone for good.
