### ISSUE TITLE
Resizing Telegram Desktop is too slow or doesn't work

### ISSUE THREAD

**Issue by AlefPhard** [telegramdesktop/tdesktop#7848]
Hi
on Windows 10 1909 I try resizing Telegram Desktop with mouse but It stuck on fullscreen so after some clicks I am finally able to move it and resize its screen

Also, when I had smaller size set before, I click on fullscreen square button, but it makes Telegram small for a moment and instantly revert back to fullscreen, as if I have double clicked on square, but I haven't, and this repeats for some clicks.

so it is a trouble resizing Telegram Desktop Portable 2.1.4 for me. this issue has been around from version 1.9 up to know.

Thanks.

### Expected behaviour
Resizing Telegram Instantly with clicking Square button

### Actual behaviour
Telegram Desktop Stuck on fullscreen for many clicks on Square button
### Configuration
 Windows 10 1909

**Version of Telegram Desktop:**
2.1.4

**Installation source (Linux Only)** - the official website / GitHub releases / flatpak / snap / distribution package:

**Used theme**:

<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by Aokromes** [comment]
cannot reproduce myself.

**Comment by EdoaLive** [comment]
Same problem here with Telegram 2.1.12.
It's enough to single click on the window border (when the resize curosr appears) to hang it for ~3 seconds.
Funny thing: Windows' task manager hangs too during this period (I was trying to see what resources was it contuming).
I think it's something like video driver related. I'm on AMD Radeon with latest "optional" (non WDDM) official drivers (20.5.1).
