### ISSUE TITLE
Armenian font

### ISSUE THREAD

**Issue by NarekEVN** [telegramdesktop/tdesktop#7849]
In version 2.1.3 Armenian font was readable, but not well. After updating to 2.1.4 font is not readable, too small and ugly.
Here font after updating to latest 2.1.4 version.
![image](https://user-images.githubusercontent.com/42799361/81465244-a9beb580-91d9-11ea-95a5-adc7600a5d01.png)

Here is font before updates.
![image](https://user-images.githubusercontent.com/42799361/81465423-3322b780-91db-11ea-9cb0-a46e881dd6b7.png)

I think previous font was 'Tahoma'.
OS: Windows 7 64bit SP1

**Comment by Aokromes** [comment]
follow here plz
https://github.com/telegramdesktop/tdesktop/issues/7851
