### ISSUE TITLE
[Feature Request] Show user's own avatar next to message

### ISSUE THREAD

**Issue by beastarman** [telegramdesktop/tdesktop#785]
This could be totally optional, but I believe not showing the user's own avatar next to his messages nor anywhere on the chat window reduces too much it's importance. I recently changed mine, but not being able to see it at all makes me fell that it doesn't matter at all.

It's no wonder I have so many contacts without avatars, since they probably don't even know that. This becomes confusing on group chats, since the image next to the message lets you know right away who wrote that.

**Comment by Brawl345** [comment]
Oh yes, this would be a really good feature!

**Comment by luksi-reiku** [comment]
Hell yeah

**Comment by Sollex-21412** [comment]
Use Cutegram, it have such feature lol ;)

**Comment by mbnoimi** [comment]
+1

**Comment by stek29** [comment]
Isn't it added in 0.9.32 as optional? (When outgoing messages are in left side too)
