### ISSUE TITLE
Can't attach files from hidden folders

### ISSUE THREAD

**Issue by arrases** [telegramdesktop/tdesktop#7853]
### Steps to reproduce
First way:
1. From a hidden folder of the system, select one or more files
2. Drop them on a chat

Second way:
1. Click over de clip of a chat
2. Select a hidden folder (.myfolder)

### Expected behaviour
The file is attached to the chat

### Actual behaviour
First way: The file is not attached, indicates that the upload has failed
Second way: An error window is prompt: could not read the contents of "private folder", permission denied
The hidden folder is on my home user folder, with 775 permissions.

### Configuration
**Operating system:**
Xubuntu 18.04
(file manager: Thunar 1.6.15)
**Version of Telegram Desktop:**
2.1.4
**Installation source (Linux Only)** - the official website / GitHub releases / flatpak / snap / distribution package:
snap
**Used theme**:
dark
<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by gorghino** [comment]
Can't reproduce in Elementary OS and Telegram 2.1.4.
I'm using Elementary Files (https://github.com/elementary/files) 4.4.2

I can grab a file in a hidden folder (/home/myUser/.test/testFile) into a Telegram chat without any error.
I can also click on the CLIP from the chat, CTRL+H to show hidden folders, open an hidden folder and select a file inside it.

**Comment by ilya-fedin** [comment]
> snap

snap sandbox prohibits access to folders with names started with a dot. This is a snap issue and not a tdesktop issue. You can reinstall the package with `--devmode` to disable the sandbox or instal tdesktop with any other method.
