### ISSUE TITLE
[Windows] [Bug] Windows taskbar not appearing

### ISSUE THREAD

**Issue by yCatDev** [telegramdesktop/tdesktop#7854]
Hello, just installed Windows, but after fully configuring noticed a bug with the taskbar and Telegram Desktop app. 

### Steps to reproduce
1. Enable auto hide taskbar in Windows
2. Open telegram in full screen
3. Try to hover on taskbar place

### Expected behaviour
Taskbar should appear when you hovering on his place

### Actual behaviour
Nothing

### Configuration
**Operating system:**
Windows 10 1909

**Version of Telegram Desktop:**
2.1.4

**Used theme**:
Default, night-mode

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/3579
