### ISSUE TITLE
Telegram notifications don't disappear when watching full screen videos

### ISSUE THREAD

**Issue by nilsonsales** [telegramdesktop/tdesktop#7855]
### Steps to reproduce
1. Watch a video (Netflix/YouTube) on you browser (Firefox/Chrome) in full screen mode;
2. Receive a message with the notifications enabled;

### Expected behaviour
Notification should appear on the corner of the screen and fade away in a few seconds;

### Actual behaviour
Notification stays on the screen until you dismiss it by clicking 'x';

### Configuration
**Operating system:** Linux (Arch Linux - Plasma Desktop)

**Version of Telegram Desktop:** 2.1.4

**Installation source (Linux Only)** - the official website / GitHub releases / flatpak / snap / distribution package: downloaded from the Pacman 'Community' repository

**Used theme**: Default

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/2290
