### ISSUE TITLE
[Feature Request] Unique ID for right answers

### ISSUE THREAD

**Issue by bsde1234** [telegramdesktop/tdesktop#7857]
### Is your feature request related to a problem?
No

### Describe the solution you'd like
IDK

Hi, can you please add a unique identifier to right answers for quizes including quiz_bot quizes in export chat history option in telegram desktop mode? Thanks.

**Comment by Aokromes** [comment]
this very likely will need api support.

**Comment by bsde1234** [comment]
Can you please explain a little bit more. Is this feature already exists? Do I need to do anything from my end? If yes give a link to documentation. Thanks.

**Comment by Aokromes** [comment]
server side support to send the feature to all aplications.

**Comment by bsde1234** [comment]
Can you make it or where should I request it? Thanks.

**Comment by Aokromes** [comment]
in client "ask a question"

**Comment by bsde1234** [comment]
There is no option to raise an issue, see https://github.com/DrKLO/Telegram
