### ISSUE TITLE
[Crash on Linux] Fontconfig error

### ISSUE THREAD

**Issue by Ironil** [telegramdesktop/tdesktop#786]
After updating, Telegram won't start up, returning the following:

libs init..
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 70: non-double matrix element
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 70: non-double matrix element
Fontconfig warning: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 78: saw unknown, expected number
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 70: non-double matrix element
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 70: non-double matrix element
Fontconfig warning: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 78: saw unknown, expected number

On Xubuntu 64bits

**Comment by bil-elmoussaoui** [comment]
Try removing ```fontconfig``` in ```$HOME/.TelegramDesktop```
you can paste this on your terminal 
``` 
rm -rf $HOME/.TelegramDesktop/fontconfig
```

**Comment by Ironil** [comment]
Sorry, the problem didn't come from here, but from the program being blocked by the company firewall. Did the upgrade change anything regarding to ports? It went from working fine before updating to not at all after doing it, and there's at least another case in the same company

**Comment by auchri** [comment]
duplicate #517
