### ISSUE TITLE
[Feature Request] native multiple accounts

### ISSUE THREAD

**Issue by erfantkerfan** [telegramdesktop/tdesktop#7860]
Hello
Please add the feature to **simultaneously be logged in** in **Telegram Desktop** app.
the same strategy is implemented in **Android** devices and its pretty useful in many cases.

the **workaround** right now is using _portable_ version and duplicating the app but as I mentioned its a workaround like using _multiple instances_ of app running in different folders.
thanks for your very good messaging app

**Comment by Aokromes** [comment]
centuplicated.
