### ISSUE TITLE
Upgrade 2.1.1 => 2.1.4: font is TOO bold

### ISSUE THREAD

**Issue by Flowneee** [telegramdesktop/tdesktop#7861]
Hi!

I upgraded `telegram-desktop` (Arch Linux) from version `2.1.1` to `2.1.4` and bold font is TOO BOLD, it literally painful to read. 

Old:

![Screenshot_2020-05-10_16-15-20](https://user-images.githubusercontent.com/10746427/81500352-639d4b00-92da-11ea-98c3-2cc7527a4457.png)

New:

![Screenshot_2020-05-10_16-18-42](https://user-images.githubusercontent.com/10746427/81500360-6bf58600-92da-11ea-8439-9ab3d83d0406.png)

From reading previous issues I assume this might be expected change, but is there any way to roll back change or provide some way to customize fonts settings?

**Comment by ilya-fedin** [comment]
> I assume this might be expected change

This was reverted, but only for tdesktop 's own patched fonts. Distro maintainers are cutting out patched fonts.

**Comment by Flowneee** [comment]
> This was reverted, but only for tdesktop 's own patched fonts. Distro maintainers are cutting out patched fonts.

Arch package use this to build package

```bash
cmake -B build -G Ninja . \
        -DCMAKE_INSTALL_PREFIX="/usr" \
        -DCMAKE_BUILD_TYPE=Release \
        -DTDESKTOP_API_TEST=ON \
        -DDESKTOP_APP_USE_PACKAGED_RLOTTIE=OFF \
        -DDESKTOP_APP_USE_PACKAGED_VARIANT=OFF \
        -DDESKTOP_APP_USE_PACKAGED_GSL=OFF \
        -DTDESKTOP_DISABLE_REGISTER_CUSTOM_SCHEME=ON \
        -DTDESKTOP_USE_PACKAGED_TGVOIP=OFF \
        -DDESKTOP_APP_SPECIAL_TARGET="" \
        -DTDESKTOP_LAUNCHER_BASENAME="telegramdesktop"
ninja -C build
```

I am not familiar with CMake, but from https://github.com/desktop-app/cmake_helpers/blob/81a0fc7970a62e8c1b194bd8eb85890528366ca7/variables.cmake I see that `DESKTOP_APP_SPECIAL_TARGET=""` should, in the end, set `DESKTOP_APP_USE_PACKAGED_FONTS` to `true` (`ON` or whatever).

Can you, please, explain, am I wrong or not? And what variable should I set (in command above) to build app with packaged fonts?

**Comment by ilya-fedin** [comment]
> And what variable should I set (in command above) to build app with packaged fonts?

To get proper font, you need tdesktop's own patched fonts, e.g. DESKTOP_APP_USE_PACKAGED_FONTS should be set to false

**Comment by ilya-fedin** [comment]
DESKTOP_APP_SPECIAL_TARGET="" doesn't have sense

**Comment by ilya-fedin** [comment]
TDESKTOP_LAUNCHER_BASENAME="telegramdesktop" too, this is default value

**Comment by Flowneee** [comment]
> To get a proper font, you need tdesktop's own patched fonts, e.g. DESKTOP_APP_USE_PACKAGED_FONTS should be set to OFF

Okay, that was counterintuitive :)

Can this be fixed, if I somehow provide patched fonts (from https://github.com/desktop-app/lib_ui/tree/c9120970c25a279c371250fac746521e7447a69b/fonts , I suppose) manually? Just copy fonts to `~/.local/share/fonts` didin't work, but probably with right `fonts.conf` this could work? Or I am missing something?

**Comment by ilya-fedin** [comment]
> Okay, that was counterintuitive :)

packaged == provided by third-party == non-patched
not packaged == bundled == pathced

> Just copy fonts to `~/.local/share/fonts` didin't work, but probably with right `fonts.conf` this could work?

when PACKAGED_FONTS is enabled, tdesktop request non-patched Open Sans (they have different font families)

**Comment by Flowneee** [comment]
Okay, thx for help. Seems like build package myself is the easiest way. I'll try to write bug report to maintainers of arch package.

**Comment by ilya-fedin** [comment]
> I'll try to write bug report to maintainers of arch package.

there is no need, since bug actually in tdesktop codebase, fix will be in the new version

**Comment by ilya-fedin** [comment]
It just was unknown how the new approach affects packaged fonts

**Comment by Flowneee** [comment]
> there is no need, since bug actually in tdesktop codebase, fix will be in the new version

Ok, thx.
