### ISSUE TITLE
Closing context popup while sub-context menu is open causes Telegram to crash 

### ISSUE THREAD

**Issue by Bryophyllum** [telegramdesktop/tdesktop#7862]
### Steps to reproduce
1. Select text in the message box and right click it;
2. Hover over either "Formatting" or "Spelling" to open a corresponding sub-context menu;
3. Move the mouse cursor to Telegram window, without folding the sub-context menu, and press the left mouse button.

### Expected behaviour
The context popup should disappear. 

### Actual behaviour
The `telegram-desktop` process crashes and dumps core, and `The Wayland connection experienced a fatal error: Protocol error` is printed out when the client is run from a CLI. 

Clicking outside Telegram window closes the context popup, without triggering a crash.

### Configuration
**Operating system:** Fedora Silverblue 32 (GNOME 3.36 on **Wayland**)

**Version of Telegram Desktop:** 2.14

**Installation source (Linux Only)** - `flatpak` (+ `$ sudo flatpak override --env=QT_QPA_PLATFORM= org.telegram.desktop` to enable the **Wayland** backend for the flatpak)

**Used theme**: The vanilla night theme

<details><summary><b>Logs</b>:</summary>

```
May 10 16:49:54 fedora systemd-coredump[42337]: Process 42230 (telegram-deskto) of user 1000 dumped core.
                                                
Stack trace of thread 2:
#0  0x00007f055c05d605 n/a (/usr/lib/x86_64-linux-gnu/libc-2.30.so + >
#1  0x0000003000000018 n/a (n/a + 0x0)
```

</details>

**Comment by ilya-fedin** [comment]
This really sounds like a Qt bug

**Comment by ilya-fedin** [comment]
I can reproduce with weston on static binary, but errors like `The Wayland connection experienced a fatal error: Protocol error` are not fixable in client code :(

**Comment by ilya-fedin** [comment]
https://bugreports.qt.io/browse/QTBUG-81952
