### ISSUE TITLE
[Feature Request] An option to disable badge counter completely for muted chats

### ISSUE THREAD

**Issue by azat11** [telegramdesktop/tdesktop#7867]
### Is your feature request related to a problem?
I keep seeing counters near muted chats. When joining groups this can get out of hand fast. I want to remain in the group, but I don't wanna read everything everyone writes about there. And seeing these endless messages being posted in a group I open only to ask a question once in a while is really unnecessary for me.
Now I'm just keeping joining and leving groups once I'm done asking my questions. Or maybe I want to remain in a group to read it once in a while, but not to see thousands of messages I don't intend to read being racked up in there.

### Describe the solution you'd like
I want an option to disable badge counters for all muted chats. As a minimum. And as a maximum an option to enable/disable badge counter for every individual chat/group/channel. This is especially important for groups, as they amass huuge numbers of unread messages.
_EDIT:_ The best solution is to have an option to disable the counter for every chat/group/channel. Because disabling counter for all muted chats will create the problem that I want to see the counter for some muted channels, for example, like news channels.

### Describe alternatives you've considered
Can't think of one. My alternative for now is to leave every active group there is. But that's hardly a solution.

### Additional context
I hope I've been clear enough above.

**Comment by RememberTheAir** [comment]
I cope with this by archiving groups I might need once in a while, but that I really don't want to see in my chats list

**Comment by azat11** [comment]
> 
> 
> I cope with this by archiving groups I might need once in a while, but that I really don't want to see in my chats list

The badge counter is still shown on the Archived folder. I tried coping that way, but this is not really a solution.

**Comment by RememberTheAir** [comment]
If you find the archive's unread counter annoying, you can right-click on it and move it to the main menu, so you don't have it on your chats list anymore (you will find it in your side bar, and can use CTRL + 9 to quickly bring it up anytime)

**Comment by azat11** [comment]
> 
> 
> If you find the archive's unread counter annoying, you can right-click on it and move it to the main menu, so you don't have it on your chats list anymore (you will find it in your side bar, and can use CTRL + 9 to quickly bring it up anytime)

This is at the most an inconvenient workaround that stops working if I want to see the Archived folder, or if I want to use folders and put those groups in a separate folder. Definitely not a solution.
Trust me, I've tried everything there is to try. Badge counter should be optional for at least the muted chats, and the optimum for each individual chat.

**Comment by azat11** [comment]
Also, this goes for folders.
The best solution is to have an option to disable the counter for every chat/group/channel. Because disabling counter for all muted chats will create the problem that I want to see the counter for some muted channels, for example, like news channels.

**Comment by mmkulikov** [comment]
Полностью поддерживаю. Как-то очень сбивает с толку видеть в счетчике "новых" сообщений muted каналы. Это нонсенс. Тот-же вайбер так не делает. И вынести каналы которые muted из папки unread

**Comment by azat11** [comment]
Hey-hey, _not stale_ at all. This is still _**a very much**_ wanted feature.

**Comment by pomazanbohdan** [comment]
After adding the functionality of flexible configuration of folders, as well as the archive, this feature is very popular, as the counter of messages in the tray for chats, which are archived, I am very distracted and annoyed.

**Comment by pras92** [comment]
> After adding the functionality of flexible configuration of folders, as well as the archive, this feature is very popular, as the counter of messages in the tray for chats, which are archived, I am very distracted and annoyed.

Unread counter from archived chats in the notif tray is already handled by the existing Badge Counter settings. 
This issue talks about the counters displayed next to the "All Chats" and any other custom Folder names a user created. And it's sad to see almost 2 years have passed, without any acknowledgement to the issue.
