### ISSUE TITLE
[Feature Request] An option to hide "All Chats" from the list of folders

### ISSUE THREAD

**Issue by azat11** [telegramdesktop/tdesktop#7869]
### Is your feature request related to a problem?
It's an eyesore to see that despised mess of all chats in one place mixed together.

### Describe the solution you'd like
An option to hide "All Chats" from the list of folders would be very nice.

### Describe alternatives you've considered
An alternative would be to never open that "All Chats" folder. But it's right there, at the top, unnecessarily taking up space, even AFTER I arrange it all nice-and-tidy-like into separate folders.

### Additional context
Can't think of any.
_Edit:_ Here's some context. This system with folders combined with archiving chats/groups/channels is really confusing. That "All Chats" list is an unnecessary feature. If I archive a chat/group/channel I'd expect it to move out of the folder, but it stays right there where it was. What is archiving anymore? Maybe replace "All Chats" with one "Archived" folder at the end of the list, or add "Archived" to each folder, which makes much more sense.

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/7533
