### ISSUE TITLE
Voice calls

### ISSUE THREAD

**Issue by phplego** [telegramdesktop/tdesktop#787]
I can't get rid of the Skype just because it have "Voice call" feature and telegram do not. If we implement this feature trillions of their users could jump to the telegram's board. What do you guys think?

**Comment by kireledan** [comment]
That feature has nothing to do with this application. The telegram API does not have voice call capabilities.

**Comment by phplego** [comment]
They can enable these capabilites:

>**Q: Can I make calls or video calls via Telegram?**
>We may enable voice calls if we see significant demand in the future. The technology necessary for encrypted calls has indeed been created in our R&D dungeons.

Source: https://telegram.org/faq

**Comment by soren121** [comment]
Yes, but you should take this up with Telegram, not the developer of the desktop app. He doesn't have the power to add this feature.

**Comment by mbnoimi** [comment]
@soren121 
> you should take this up with Telegram, not the developer of the desktop app

Until now I don't know how to reach Telegram goddess!
Their website doesn't point to any way to reach them. Many feature requests need to send to them,

**Comment by soren121** [comment]
https://telegram.org/support

-----Original Message-----

**Comment by mbnoimi** [comment]
@soren121 Thanks

**Comment by ezdev128** [comment]
I think would be good to implement SIP/2.0 video with SRTP.
It would be standard as well and secure.

Without realtime voice and video features this messenger can't be a competitor to Vider and Skype for example. 
I can't remove this ugly Skype and move all of my clients and friends to Telegram because of no such features.

Hey Telegram Team, **please** work on those so demanded features and make us happy :-)

**Comment by mbnoimi** [comment]
@ezdev128 You asked this in the wrong place.

Unfortunately Telegram LLP dominate on Telegram server so Telegram isn't open source completely. But you can ask for this feature by the link @soren121 mentioned above.

**Comment by ezdev128** [comment]
@mbnoimi, @soren121 why it can't be implemented? If it is so related to server, SDP can go through STUN/TURN/ICE bypassing the server.

**Comment by phplego** [comment]
It is possible to establish peer to peer connection between two users. Isn't it?
Why the hell do we need their server?

**Comment by ezdev128** [comment]
@phplego no I don't think so. It seems all the traffic is walking through the server. 
Otherwise it could be a challenge to spy (I'm bet the server is being logged all messages) on people. That's why Microsoft has disabled P2P ;)

**Comment by WyRe** [comment]
+1

**Comment by fincatto** [comment]
+1

**Comment by kmare** [comment]
I totally agree... audio/video calls would let telegram take over any other app out there.. hopefully it'll be implemented soon.

**Comment by tjrhodes** [comment]
With voice calls Telegram takes over the world, kills skype first and then whatsapp

**Comment by buffovich** [comment]
+1
We need voice/video calls. I'm tired of Skype.

**Comment by alxzh** [comment]
+1 Must have!

**Comment by stek29** [comment]
@alxzh Please use [new GitHub reactions](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments) instead of writing "+1" comments.

**Comment by danger89** [comment]
@auchri Why is this issue closed? It's not solved. We got voice messages, but we want voice **Calling**. Let's try to beat Skype or Jitsi!!

**Comment by auchri** [comment]
![image](https://cloud.githubusercontent.com/assets/5092164/16085884/dca0fad6-331d-11e6-9d87-d8a20f113dae.png)

Read first, then ask.

**Comment by danger89** [comment]
Owow.. yea good point. @auchri Where can I create a feature request for Telegram as a whole?

 Because [this is not](https://play.google.com/store/apps/details?id=org.callgram.messenger) what we want right..?

**Comment by auchri** [comment]
![image](https://cloud.githubusercontent.com/assets/5092164/16086053/8151120a-331e-11e6-9563-d827b8b62808.png)

(or https://twitter.com/telegram)

Read first, then ask.

**Comment by danger89** [comment]
Excuse me... oef. I was already looking on https://telegram.org. This support link was just hidden and the post from 8 jun 2015 as well :).

**Comment by AchwaqKhalid** [comment]
"Does it have Audio/Video calls support ❔" 

That's what I hear everytime I recommend Telegram to someone 📞 📲 🎥

**Comment by BPeti** [comment]
+1

**Comment by FezVrasta** [comment]
> That feature has nothing to do with this application. The telegram API does not have voice call capabilities.

Instead a photo editor and a music player in-app have anything to do with the Telegram API?

**Comment by danger89** [comment]
Google Duo will steal Telegram users if you don't add a video feature.

**Comment by 3a4oT** [comment]
so true.

**Comment by woj-tek** [comment]
So I came here to voice my concern about the same issue. I know it's not related to Telegram.org per se but:
- it's impossible to contact them (their support is a joke and never answers, their twitter answers only sometimes)
- there is no alternative and I guess developer of Telegram Desktop have some sort of contact ability and/or discusses what's needed and/or what will be available...

Recently I've been forced to use more WhatsApp (sic!) because of the calls... and this is annoying...

**Comment by z3ntu** [comment]
Re-open please 😉  https://telegram.org/blog/calls

**Comment by danger89** [comment]
Ah yea! there we go.. This this you can't ignore us.

**Comment by Mistero5050** [comment]
Durov said they are working to bring it in this month
https://twitter.com/durov/status/847454932257001477

**Comment by stek29** [comment]
I guess TDekstop team will have to wait till [libtgvoip](https://github.com/grishka/libtgvoip) gets Windows/Linux/macOS support.

**Comment by mr-tron** [comment]
https://github.com/grishka/libtgvoip/commit/bfde1a4be3168341a5c1f9d43578efb83c4013dc
As I understood, this commit added support for windows/linux/macos.

**Comment by stek29** [comment]
@mr-tron Just for Windows/Linux, macOS support was added earlier.

**Comment by Milaine** [comment]
Then lets hope one dev here decides to integrate the libtgvoip into Telegram Desktop already so that we can finally enjoy calls via Telegram Desktop and get rid of Skype

**Comment by z3ntu** [comment]
Just calm down everyone. I am sure, they are working hard on it. See for example https://twitter.com/durov/status/853316362634223618

**Comment by phplego** [comment]
I feel the smell of dying Skype..
