### ISSUE TITLE
[Feature Request] When editing a media, there is very little space for edit long caption that is annoying.

### ISSUE THREAD

**Issue by NabiKAZ** [telegramdesktop/tdesktop#7870]
When editing a media, there is very little space for edit long caption that is annoying.

![Untitled](https://user-images.githubusercontent.com/246721/81616341-8f165780-93f8-11ea-93bf-503bce3b8fde.png)

**Comment by Neurotoxin001** [comment]
https://github.com/telegramdesktop/tdesktop/issues/5122
