### ISSUE TITLE
[Feature Request] In Media Caption, it is not possible to mention. But it's not a problem for normal text.

### ISSUE THREAD

**Issue by NabiKAZ** [telegramdesktop/tdesktop#7871]
In Media Caption, it is not possible to mention. But it's not a problem for normal text.

![image](https://user-images.githubusercontent.com/246721/81616780-62167480-93f9-11ea-83aa-da244eefaffe.png)

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/2158
