### ISSUE TITLE
mouse wheel scrolling not working 

### ISSUE THREAD

**Issue by deadwalker10s** [telegramdesktop/tdesktop#7872]
### Steps to reproduce
1. open a chat or a group in desktop
2. press the mouse wheel 
3. move the mouse up or down using the pressed mouse wheel

### Expected behaviour
movement in chats and chat conversation with the help of mouse wheel 
![image](https://user-images.githubusercontent.com/56349863/81744459-e41da080-94c0-11ea-9141-372617be2a87.png)

### Actual behaviour
no movement in chats and chat conversation with the help of mouse wheel 

### Configuration
**Operating system:**
Windows10 Home

**Version of Telegram Desktop:**
2.1.4

**Installation source (Linux Only)** - the official website / GitHub releases / flatpak / snap / distribution package:
official website

**Used theme**:
dark

<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by Aokromes** [comment]
works for me (TM)

**Comment by deadwalker10s** [comment]
the mouse wheel movement for the chats and the converstions 
doesn't works with desktop version of telegram 
it work fine with the telegram web

**Comment by MasterGroosha** [comment]
@Aokromes is this really a bug? That feature is primarly used in web browsers, isn't it?

**Comment by Aokromes** [comment]
> @Aokromes is this really a bug? That feature is primarly used in web browsers, isn't it?

and productivity tools :) (ie word) also rambox oh well

**Comment by FenixR** [comment]
I too have issues with this because at work my scroll wheel its broken (the middle button still works) and at home i use a steam controller and usually just use the middle click for scrolling documents.

Its certainly a nice enhancement to have in the app, specially since nowadays the fading and tiny small scroll bar its becoming prevalent in design nowadays making it a PITA to use.

**Comment by ilya-fedin** [comment]
#3161
