### ISSUE TITLE
[Folder Feature] Add/Remove chats present in another folder (tick a list of chats at once)

### ISSUE THREAD

**Issue by damnfella** [telegramdesktop/tdesktop#7875]
### Is your feature request related to a problem?
I want to include/exclude chats from another folder. I created a folder for `News channels`, where I've added news channels to it. There is also a `Channels` folder, from which I want to remove all the `News channels`, so I can keep my folders neat and tidy. It's painful to search and tick 15-30 news channels, one at a time. To add to the pain, few news channels don't have "news" in their channel name.

![qwertyuilkjhgf](https://user-images.githubusercontent.com/51771172/81701139-3b9f1a80-9487-11ea-8f90-36481db5b1c0.png)

### Describe the solution you'd like
1. Show an option to choose `chats from another folder`. 
2. Retrieve a list of chats from the `News` folder, and show a dialog to tick/untick the chats from the folder.
3. Add this final list of channels to the included/excluded chats. 
4. Save changes after adding the folder-list.

### Describe alternatives you've considered
Manually searching and ticking the chats, one by one.

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/7825

**Comment by damnfella** [comment]
Hi @Aokromes, this issue is not a copy of the issues you just mentioned. Please consider reopening this one.
