### ISSUE TITLE
[Feature Request] Allow image cropping before sending image

### ISSUE THREAD

**Issue by Megamiun** [telegramdesktop/tdesktop#7878]
### Is your feature request related to a problem?
We have no ways to edit a image, in this case, image cropping, before sending an image. It would simplify the life of someone that sends screenshots and images a lot, because instead of having to take a screenshot of only the desired fragment or using an online or local image cropper over an image, we could simply do that inside the Telegram app.

### Describe the solution you'd like
I would like to have a simple editor opening if the `send image as a photo is selected` option is selected, as we would have in the Android app.

### Describe alternatives you've considered
Another alternative would have a button of something like `edit before sending` so in case we don't want to edit it, the image would be send without extra steps.

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/1762
