### ISSUE TITLE
Be more specific about the name of who is typing

### ISSUE THREAD

**Issue by Caloni** [telegramdesktop/tdesktop#7879]
### Problem

I live in a group full os Rodrigo's. It is common to people in Brazil to call Rodrigo and to become programmers. So this group is full of them.

When someone is typing in the group, despite the fact each Rodrigo has different nicks and surnames, all the information we get is "Rodrigo is typing".

### Solution

It would be nice if instead of just using the person's first name Telegram Client use unambiguous combination for "User is typing". It could be the nickname, the surname, being a fixed setting.

### Alternatives

There is no alternative for the "User is typping" for Telegram Client for Desktop. We have to try to guess what kind of Rodrigo is typping, which is annoying.

### Additional context

Try to participate in a group as https://t.me/ccppbrasil and you will see as annoying is to have a bunch of Rodrigos in the same group.

**Comment by skhaz** [comment]
`Rodrigo, Rodrigo and Rodrigo are typing...`

**Comment by MasterGroosha** [comment]
> It could be the nickname, the surname, being a fixed setting.

Unfortunately, both fields you mentioned are optional in Telegram, unlike first name
