### ISSUE TITLE
[Bug] Limit on the total number of sticker packs

### ISSUE THREAD

**Issue by Mindstormer619** [telegramdesktop/tdesktop#788]
This issue is what I am facing after directly dealing with #758, which I faced *after* the latest stable update. Here are the details.

## Overview

Telegram Desktop seems to have a limit on the total **number of sticker packs** added to it (independent of the number of stickers in the pack). For me, this limit seems to be around **21 packs** (*EDIT:* 21 not 22) (including the default "Great Minds" pack). Upon trying to add more, I am faced with this error:

![](https://cloud.githubusercontent.com/assets/441849/7980937/2d1ece26-0ac9-11e5-84ba-671b348e980e.png)

I can add another pack by *removing* an already-added pack. This seems to create some "space" where I can add one more pack. I have verified this by removing two packs - this allows me to add two others.

## Steps I took

- Opened Telegram Android and saved a list of all the sticker pack URLs I had, one by one.
- Removed all the sticker packs from TDesktop which I had added
- Removed all the sticker packs from Telegram Android as well
- Logged out and exited both clients
- Started and logged in to Telegram Desktop (did not login to Android)
- Opened the list of URLs that I had sent myself and proceeded to add each one
- After a certain number of packs, encountered the above error
- Tried adding any packs from the rest of the un-added URLs: all show same error
- Removed one already added pack at random, was able to add exactly one other pack
- Removed two packs, was able to add two others

## Notes

The issue has only been present from today. Yesterday was when I got the latest update for the stable version. It was working perfectly fine till then. Today I see that some of my packs had disappeared as described in #758, and so I followed the above steps. However they led to this new error.

## Specs

- Telegram Desktop v0.8.21 (latest stable)
- OS: Windows 8.1

**Comment by Mindstormer619** [comment]
**UPDATE:** The error seems to exist in Telegram for Android as well, now that I logged back in and checked. It shows this *highly informative* (/s) toast under the same circumstances:

![image](https://cloud.githubusercontent.com/assets/441849/7983850/1ec0e0f8-0ae2-11e5-97f5-269f1b9b66ac.png)

**Comment by auchri** [comment]
It's a server limit: https://www.twitter.com/telegram/status/606457674558017536

**Comment by Mindstormer619** [comment]
Aaaand it's [fixed](https://mobile.twitter.com/telegram/status/606506502946451456!)!! Thanks for the help anyway. This scared the bricks out of me. I'll proceed to close this now.
