### ISSUE TITLE
[Linux 64bit] Sometimes I can't paste images copied from Chrome 

### ISSUE THREAD

**Issue by gorghino** [telegramdesktop/tdesktop#7880]
### Steps to reproduce
1. With **Chrome**, open a Whatsapp Web chat
2. Open an image and from the 'zoomed' view, right click on the image > Copy Image
3. Open a Telegram chat on Telegram Desktop
4. Ctrl+V (or right click on the chat and Paste)

### Expected behaviour
Telegram prompts the user how to paste the image

### Actual behaviour
Sometimes nothing happens, sometimes it prompts the user how to paste the image

### Configuration
**Operating system:** Elementary OS 5.1.4 Hera
**Linux version:** 4.15.0-99-generic
**GTK version:** 3.22.30

**Version of Telegram Desktop:** 2.1.4

**Installation source (Linux Only)** - the official website
distribution package:

**Used theme**: Daylight (Giorno in italian)

**Note:** It happens only from images pasted from Chrome (81.0.4044.129 at the moment)
I tried with Firefox 76.0.1 but Telegram always prompts the user.
I tried with ~/Telegram/Telegram -debug but it doesn't log any error when it can't (or can) paste the image

**Comment by ilya-fedin** [comment]
Is this reproducible with any other Qt program (KDE's Dolphin for example)?

**Comment by gorghino** [comment]
I tested with KDE's Dolphin but after copying a image file, I can paste it into Telegram without problems.

I found out that it's not limited to Whatsapp images but I could reproduce it with Facebook too:
Example:
1) Open this artist's post with Chrome: https://www.facebook.com/deadmau5/posts/10157010537351806:0
2) Copy the rounded profile picture and paste it multiple times into Telegram: it works.
3) Click on the rounded profile pic (new url: https://www.facebook.com/photo/?fbid=10157010536736806&set=a.442424616805) and try to copy/paste the squared big image: it works sometimes.

I tried Skype 8.60.0.76, copying a group chat image and I found the same problem pasting it into Telegram: sometimes it took 6 times CTRL+V to prompt me.

**Comment by ilya-fedin** [comment]
> I tested with KDE's Dolphin but after copying a image file, I can paste it into Telegram without problems.

Dolphin supports pasting from clipboard

**Comment by gorghino** [comment]
@ilya-fedin Oh did you suggest to use Dolphin as pasting target? Sorry I thought as image source.

I did the Facebook test on Dolphin and the two images in the clipboard have two different behaviours when pasted:
- Rounded profile picture is pasted with its name (99388011_10157010536741806_5935388191660965888_o.jpg) in the test folder all the time. I tried it deleting the pasted image and retrying CTRL+V.

- Big squared picture: Dolphins prompts with a dialog asking to create a name and a file format (png or HTML doc). This dialog happens all the time though

**Comment by ilya-fedin** [comment]
> Oh did you suggest to use Dolphin as pasting target?

Yes

> This dialog happens all the time though

Does the file appear after choosing a format?

**Comment by gorghino** [comment]
Yes it does

**Comment by vlad88sv** [comment]
I have this same issue, the same tests as @gorghino and I have the exact same results

This is my QT version
![image](https://user-images.githubusercontent.com/91489/82682507-974a7000-9c0c-11ea-8dbf-85889fd4cbd2.png)

I have the same erratic behavior in Telegram Desktop 2.0.1, I have to download the file from Chrome and then drag&drop the file from Dolphin to get the image options in TG

Thank you

**Comment by gorghino** [comment]
2.1.7 here and I still have problems pasting the squared image.

I don't confirm this issue on Windows 10+Chrome. There it always work.

**Comment by ilya-fedin** [comment]
#7223
