### ISSUE TITLE
[Regression] Media autodownload is broken in v2.1.5 for Windows

### ISSUE THREAD

**Issue by MasterGroosha** [telegramdesktop/tdesktop#7881]
### Steps to reproduce
1. Have media autodownload on
2. Update to 2.1.5

### Expected behaviour
Media autodownload should work as expected

### Actual behaviour
Media autodownload is broken on Windows (doesn't autodownload regardless of settings). On Linux it seems to be fine.
Several other users have also confirmed such problem.

### Configuration
**Operating system:** Windows 10
**Version of Telegram Desktop:** 2.1.5

**Comment by Neurotoxin001** [comment]
Did devs even test new versions before release? 

![image](https://user-images.githubusercontent.com/39812401/81853776-8f803100-9565-11ea-877b-0add73148a00.png)

**Comment by bitrate16** [comment]
In my case media autodownload and autoplay both is not working while being enabled.

**Comment by john-preston** [comment]
@bitrate16 Should be fixed in 2.1.6.

**Comment by Partizanin** [comment]
@MasterGroosha , @Aokromes  Already fixed in [v2.1.6](https://github.com/telegramdesktop/tdesktop/releases/tag/v2.1.6) , issue can be closed
