### ISSUE TITLE
Images won't load even with autoload enabled

### ISSUE THREAD

**Issue by Neurotoxin001** [telegramdesktop/tdesktop#7882]
### Steps to reproduce
1. update to 2.1.5
2. open channel with new posts that have images
3. images don't load and show blurred version until I press on download icon

### Configuration
**Operating system:** win 10 ltsc 1809

**Version of Telegram Desktop:** 2.1.5

**Used theme**: default dark

![image](https://user-images.githubusercontent.com/39812401/81852220-5a72df00-9563-11ea-8e74-3b931b3743b5.png)

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/7881
