### ISSUE TITLE
[Regression] U+2661 renders incorrectly in 2.1.5; works fine in 2.1.4

### ISSUE THREAD

**Issue by Zenexer** [telegramdesktop/tdesktop#7883]
### Steps to reproduce
1. Attempt to send or receive character U+2661 (♡)

### Expected behaviour

Should appear as a black-and-white (non-emoji) heart:

### Actual behaviour

A character containing three vertical lines appears instead:

![image](https://user-images.githubusercontent.com/504130/81858814-4e225e00-9532-11ea-9bbd-07dfb915a2fc.png)

### Configuration
**Operating system:** Windows 10, up-to-date

**Version of Telegram Desktop:** v2.1.5 (beta); can't reproduce in 2.1.4

**Used theme**: Default; happens in both normal and night mode

**Comment by Zenexer** [comment]
Per https://t.me/TelegramDesktopTalk/36813, U+2661 (♡) appears to render as U+2261 (≡).

**Comment by magnus-gross** [comment]
![Screenshot_20200515_112615](https://user-images.githubusercontent.com/21310755/82034774-eb020a00-969e-11ea-9485-cf42adf6eee0.png)

Cannot reproduce on Telegram 2.1.6 on Linux linked to Qt 5.14

**Comment by Zenexer** [comment]
It may be limited to Windows.  Someone reported it in https://t.me/TelegramDesktopTalk, and I was able to reproduce it; we were both on Windows 10.

**Comment by Zenexer** [comment]
I'm still able to repro it on 2.1.6.

**Comment by Zenexer** [comment]
Still able to repro in 2.1.10, currently no workaround.

**Comment by Zenexer** [comment]
Anyone know if this is resolved?  I don't have access to TDesktop at the moment.

**Comment by ilya-fedin** [comment]
> Anyone know if this is resolved?

This won't be solved since this issue is on Qt level. 2.1.4 was the one version that displayed this character due to the fonts experiments, current behavior is the right and won't be changed.

**Comment by Zenexer** [comment]
Thanks, @ilya-fedin.  We've been getting people asking about the issue in https://t.me/TelegramDesktopTalk.  Do you happen to have a link to the Qt issue to which we can point them?

**Comment by Zenexer** [comment]
Debug note: switching between FreeType and GDI doesn't fix the issue.

**Comment by ilya-fedin** [comment]
This is not a Qt issue, this is a Tahoma issue.

**Comment by Zenexer** [comment]
Thanks, that explains it.  I can confirm that the glyph in Tahoma is wrong, and I'm assuming that TDesktop falls back to that since Open Sans lacks a glyph for U+2661.  Case closed.
