### ISSUE TITLE
macOS version numbers of version 2.1.5 broken

### ISSUE THREAD

**Issue by core-code** [telegramdesktop/tdesktop#7884]
### Steps to reproduce
1. download version 2.1.5 for macOS here  https://github.com/telegramdesktop/tdesktop/releases/download/v2.1.5/tsetup.2.1.5.dmg
2. extract the app and inspect its version number with QuickLook or ColumnView

### Expected behaviour
i expect to see version number 2.1.5 for version 2.1.5

### Actual behaviour
it claims to be version 2.1.4 which is wrong

### Configuration
**Operating system:**
macOS

**Version of Telegram Desktop:**
2.1.5

**Additional Details:**
this bug happens *very* frequently ( https://github.com/telegramdesktop/tdesktop/issues/7075 https://github.com/telegramdesktop/tdesktop/issues/6610 ). 
it would be awesome if you could introduce some technical measures to prevent this from happening again.

**Screenshot**

<img width="714" alt="Screenshot 2020-05-13 at 22 26 26" src="https://user-images.githubusercontent.com/1261954/81862267-be000b00-9569-11ea-9cf2-a1ed6255a434.png">

**Comment by core-code** [comment]
cc @john-preston

**Comment by Aokromes** [comment]
this issue is still valid?

**Comment by core-code** [comment]
yes of course. nothing has been fixed.

since this issue comes up again and again and again i'd really advocate introducing some technical measures to prevent this. this takes like 10 seconds. i'd be happy to share some code here.

**Comment by Aokromes** [comment]
if you create one pull request for sure preston will merge it :)

**Comment by core-code** [comment]
fixed in 2.1.10
