### ISSUE TITLE
Telegram makes itself in focus when delivering notification

### ISSUE THREAD

**Issue by aaruni96** [telegramdesktop/tdesktop#7885]
### Steps to reproduce
1. Launch telegram
2. Switch focus to another window, wait for a message
3. When you get notification for message, telegram window is automatically brought into focus

### Expected behaviour
Notification must be issued while respecting whatever other window is in focus

### Actual behaviour
Focus is snatched back by telegram-desktop

### Configuration
**Operating system:**
Pop!_OS 20.04

**Version of Telegram Desktop:**
2.1.5

**Installation source (Linux Only)** - the official website / GitHub releases / flatpak / snap / distribution package:
Website

**Used theme**:
Default

**Comment by aaruni96** [comment]
For future reference : 
this update changes a notification setting which triggers this behaviour. 
Simply go to settings -> notifications , and uncheck "draw attention to the window"

**Comment by php4fan** [comment]
> this update changes a notification setting which triggers this behaviour.

That is a bug, or a wrong design decision.

This behavior shouldn't be the default. Upgrading to whatever version shouldn't change this setting (whether it existed before or not) to true.

It's nice to have the possibility to turn this on (any setting that gives you the freedom to do something more is always good), but having it turned on is not the correct default, because it's not the sensible behavior in most use cases.

**Comment by ilya-fedin** [comment]
> Upgrading to whatever version shouldn't change this setting (whether it existed before or not) to true.

It's always been true, just wasn't implemented on Linux

**Comment by aaruni96** [comment]
IMO, this setting should default to false. Any application snatching away focus from other apps is a rather big problem. For users who prefer this behaviour, you can always continue offering this setting as a user choice.

**Comment by ilya-fedin** [comment]
> Any application snatching away focus from other apps is a rather big problem.

The API should bounce icon. Blame your GNOME/Cinnamon/another GNOME-based DE if it acts in another way.

**Comment by php4fan** [comment]
> The API should bounce icon. Blame your GNOME/Cinnamon/another GNOME-based DE if it acts in another way.

Nope. 

Most DEs have an option for whether or not you want to give focus to windows that **require attention**. You can choose whether it bounces icon or steals focus.

That doesn't mean that an application should abuse the mechanism to require attention. An example of a correct use of drawing attention is when an application is performing some task and requires user input before it can continue (e.g. uploading some files, prompting the user whether or not to overwrite a given file; or installing software, issue detected, need user to decide what to do; etc). In those situation, it makes sense to steal focus (still one may prefer to never has focus stolen in which case they can tweak system settings).

It's great that you provide an option to choose, but the default behavior should be reasonable, and requiring attention for something that does not require attention is not reasonable behavior.
