### ISSUE TITLE
[Question] How can I change audio source input in Telegram Desktop (linux)?

### ISSUE THREAD

**Issue by onlymrleo** [telegramdesktop/tdesktop#7886]
How can I change audio source input in Telegram Desktop (linux) for voice messages?
I changed source input in Calls configuration, it's works only for calls, because source input still being same for voice messages. I have some problems with it, because I can't record voice messages.

**Comment by magnus-gross** [comment]
For me Telegram Desktop uses the default Pulseaudio device, so try opening `pavucontrol` and change your default Pulseaudio input device there

**Comment by onlymrleo** [comment]
Thanks @magnus-gross, I know that, but Telegram device is showing only in `pavucontrol` while I'm pressing the voice message button, when I release voice message button, Telegram device disappear, then I can't change the input device for Telegram voice messages

**Comment by ilya-fedin** [comment]
Only by setting the required device by default, probably
