### ISSUE TITLE
[Feature Request] download large files in sequence

### ISSUE THREAD

**Issue by ehsanonline** [telegramdesktop/tdesktop#7888]
### Is your feature request related to a problem?
not sure. maybe #809

### Describe the solution you'd like
we use telegram windows in our company to transfer files.
the problem is when i want to download multiple files (documents, videos,..) specially large files, i click on download for all of them and they all start to download at the same time, i like them to download in a sequence/queue way, not all together. so it saves my internet speed while i'm working and the files will get downloaded faster based on my experience. an option in settings for enable/disabling that will be more helpful. thank you.

**Comment by Aokromes** [comment]
it's not related, it's the same.
