### ISSUE TITLE
[Regression] Non-English input method doesn't work in 2.1.5 on Linux

### ISSUE THREAD

**Issue by mostlytranslucent** [telegramdesktop/tdesktop#7889]
### Steps to reproduce
1. Open Telegram Desktop (Linux 64bit, version 2.1.5 newest update).
2. Click on a conversation, ensure the cursor is blinking in the text box, and use the system key combination (Ctrl+Space for my system) to activate the input method.
3. The input method (FCITX Chinese input, in this case) does not activate and only English can be typed.
4. The same problem happens for all text boxes in the application, including the search field.

### Expected behaviour
In previous versions (including 2.1.4), I would use the system key combination to activate the input method and type in Chinese, the same as in any other application. 

### Actual behaviour
The input method doesn't activate and only English can be typed. 

### Configuration
**Operating system:** Devuan Linux 2.1 64bit

**Version of Telegram Desktop:** 2.1.5 64bit

**Installation source (Linux Only)** - the official website / GitHub releases / flatpak / snap / distribution package: Official website

**Used theme**: customized (day theme with other background image)

<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by falsetru** [comment]
I experience same with snap version. (version=2.1.5, revision=1625, channel=latest/stable)
It works as expected if I revert to 2.1.4(revision=1616, channel=latest/stable)

**Comment by Stealthmate** [comment]
I experience the same with Telegram installed via tar.xz archive and updated via the usual button below chats. This morning I updated to 2.1.5 and suddenly fcitx stopped working. My shortcut is C-\ an d appears to not be recognized

**Comment by ilya-fedin** [comment]
fcitx plugin has been updated to fcitx5. According to the author, it has backward compatibility.
https://github.com/fcitx/fcitx5-qt

**Comment by chenx97** [comment]
Looks like the textboxes in Telegram are no longer considered textboxes. Otherwise fcitx should automatically switch to one of your keyboards/schemes once you click on that textbox and make it active.

**Comment by yylzcom** [comment]
Some issue here:

Ubuntu 19.10
Telegram 2.5.1
Fcitx 0~20181128+ds1-1build1
GNOME Shell 3.34.3

**Comment by farseerfc** [comment]
> fcitx plugin has been updated to fcitx5. According to the author, it has backward compatibility.
> https://github.com/fcitx/fcitx5-qt

I believe the fcitx5 IME server have the backward compatibility with fcitx4/fcitx5/ibus im modules, but not the other way around. To make tdesktop work with fcitx 4 server, tdesktop need to have fctix 4 qt im module, and it can also work with fcitx5 server with the correct envvar settings.

**Comment by mostlytranslucent** [comment]
> > fcitx plugin has been updated to fcitx5. According to the author, it has backward compatibility.
> > https://github.com/fcitx/fcitx5-qt
> 
> I believe the fcitx5 IME server have the backward compatibility with fcitx4/fcitx5/ibus im modules, but not the other way around. To make tdesktop work with fcitx 4 server, tdesktop need to have fctix 4 qt im module, and it can also work with fcitx5 server with the correct envvar settings.

I am using fcitx 4. In previous Telegram versions, fcitx 4 worked, but now it doesn't. So I don't think the problem is with the input method, but rather with changes made to Telegram Desktop's input handling.

**Comment by iamlockon** [comment]
Same issue here with elementary OS 5.1.2 Hera/ fcits 4. Downgrade to 2.1.4 for the time being...

**Comment by hellojo011** [comment]
Same issue here

Ubuntu 18.04 LTS
Telegram 2.1.6

**Comment by wengxt** [comment]
here’s my suggestion for the im module compatible issue.

when I was asked to add support for flatpak to fcitx, a new dbus interface is added to fcitx and I took it as a chance to help to maintain compatibilty between im module.

Which means fcitx 4 and 5 im module are compatible in the sense that when they’re using the same new dbus interface for flatpak(it is just a regular dbus interface, just naming follows flatpak requirements.)

so here’s the thing, fcitx4 im module supports old 4 and 5 (with a tiny bit difference unless you use two X display server which is a uncommon setup nowadays).

fcitx 5 im module supports newer fcitx 4(from 4.2.9.7) and 5.

in order to cover the larger range of fcitx,4’s im module is probably a better choice since obviously a lot of people running latest tdesktop are still using old fcitx from the distro.

**Comment by ilya-fedin** [comment]
Can anyone try this build?
https://github.com/ilya-fedin/tdesktop/actions/runs/104829041
Should work both fcitx & fcitx5

**Comment by mostlytranslucent** [comment]
> Can anyone try this build?
> https://github.com/ilya-fedin/tdesktop/actions/runs/104829041
> Should work both fcitx & fcitx5

This one works on my system with fcitx 4 (I mean the Telegram one works, not the Telegram_DESKTOP_APP_DISABLE_DBUS_INTEGRATION; that one does not work).

**Comment by ilya-fedin** [comment]
Thanks

**Comment by commis** [comment]
Same issue here

Ubuntu 18.04 LTS
Telegram 2.1.6

Chinese input method can work in 2.1.4 on linux.

**Comment by icepie** [comment]
OS: Linux Mint 19.3 Tricia x86_64 
  TG: 2.1.5

fcitx can not work fine

**Comment by Kofi-Young** [comment]
I got the same issue described as above today. I was driven crazy!
Ubuntu 18.04 LTS
Telegram 2.1.6
fcitx doesn't work

**Comment by liangpu597** [comment]
I have same trouble.
My System is : Ubuntu 16.04 LTS
Telegram 2.1.5

**Comment by chaosrun** [comment]
Ubuntu 18.04.4 LTS
Telegram Desktop 2.1.5 `(installed from desktop.telegram.org)`
Input method **fcitx** does not work

**Comment by jnihil** [comment]
So the solution for now is to downgrade to 2.1.4?

**Comment by Aokromes** [comment]
> Downgraded to the version available in the 16.04 LTS Ubuntu repo and locked the package from updating.
> Now my Japanese input is working.

try https://github.com/ilya-fedin/tdesktop/actions/runs/104829041

**Comment by chenx97** [comment]
Viable mitigations/solutions for affected users:
- Upgrade fcitx to 4.2.9.7
- Downgrade tdesktop
- Try the build from the linked pull request

**Comment by Declarcall** [comment]
Same issue here

Ubuntu 18.04.4 LTS

Telegram 2.1.5

fcitx-pinyin、fcitx-sunpinyin、fcitx-googlepinyin、fcitx-sogoupinyin can not work fine

**Comment by Aokromes** [comment]
> Same issue here
> 
> Ubuntu 18.04.4 LTS
> 
> Telegram 2.1.5
> 
> fcitx-pinyin、fcitx-sunpinyin、fcitx-googlepinyin、fcitx-sogoupinyin can not work fine

again, try https://github.com/ilya-fedin/tdesktop/actions/runs/104829041

**Comment by Declarcall** [comment]
> > Same issue here
> > Ubuntu 18.04.4 LTS
> > Telegram 2.1.5
> > fcitx-pinyin、fcitx-sunpinyin、fcitx-googlepinyin、fcitx-sogoupinyin can not work fine
> 
> again, try https://github.com/ilya-fedin/tdesktop/actions/runs/104829041

Thanks, Chinese input method can work in 2.1.6 on linux.
