### ISSUE TITLE
[desktop] [windows] Clear history for groups

### ISSUE THREAD

**Issue by hpourjam** [telegramdesktop/tdesktop#789]
It is not possible to delete entire history in telegram desktop for a group. It is possible to select messages and delete them but messages like "x added y" or "x joined group via invite link" or "x kicked y" or "x left the group" does not remove and it is not possible to multiple select them. They can be removed just by right clicking them one by one and removing them and it is not user friendly at all.

**Comment by mbnoimi** [comment]
+1

**Comment by formatq** [comment]
+1

**Comment by Aokromes** [comment]
+1

**Comment by auchri** [comment]
Duplicate #113
