### ISSUE TITLE
[Feature Request] Do not see in the groups the messages of another blocked user

### ISSUE THREAD

**Issue by gmolledaj** [telegramdesktop/tdesktop#7892]
### Is your feature request related to a problem?
I have blocked a user that I do not like.
I am in a group where that user is
That user writes to the group
I want my application not to show the message of that user blocked by me.

### Describe the solution you'd like
The application puts on the screen a message such as "Message from a blocked user by you"
or
The application puts on the screen a message such as "Message from @username blocked by you."
It might be possible to click on the text to see the hidden message.

### Describe alternatives you've considered
Options in telegram for a blocked user:
Block in chat.
Block user in groups but show their name.
Block user in groups and not show their name.

### Additional context
Since the group messages are not on the mobile but on the server, it is the application that has to replace the message of the blocked user, because the message must remain available to other users who have not blocked him/her.

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/1025

**Comment by 411an** [comment]
OK I did it for all suffering people

https://sites.google.com/view/ignoram/

**Comment by RememberTheAir** [comment]
lol these issues about blocked users messages in groups are the best
