### ISSUE TITLE
[Feature Request] Hide empty conversations

### ISSUE THREAD

**Issue by Alchiadus** [telegramdesktop/tdesktop#79]
As the title says, it would be really nice to have an option to hide empty conversations in the conversation list on the left. This is the default behavior in Telegram's Android client and in almost every other chat client I have used. New conversations can still be initiated through the Contacts widget, while keeping the conversation list clean and tidy.

Personally, I use Telegram to stay in touch with a small number of people and the conversation list contains many contacts that I have never contacted via Telegram. I realize contacts can be deleted, but because they are automatically synced in the Android client I cannot delete them in Telegram Desktop to make them disappear in the conversation list.

**Comment by joebex** [comment]
+1

**Comment by bil-elmoussaoui** [comment]
+1

**Comment by risingballs** [comment]
+5 !!!

**Comment by auchri** [comment]
Added with 0.8.48, please close
