### ISSUE TITLE
Notification makes window instantly active

### ISSUE THREAD

**Issue by downfall109** [telegramdesktop/tdesktop#7900]
### Steps to reproduce
1. Install Telegram on Fedora 32 as a Flatpak
2. Receive a notification

### Expected behaviour
Receive a notification without Telegram becoming the active window straight away.

### Actual behaviour
A notification popup happens, then Telegram becomes the active window after every notification.

### Configuration
**Operating system:** Fedora 32, Gnome 3.36.2, X11

**Version of Telegram Desktop:**
2.1.6

**Installation source (Linux Only)** - the official website / GitHub releases / flatpak / snap / distribution package: Flatpak

**Used theme**:
Night mode

<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by downfall109** [comment]
It was an issue with Fedora - updating fixed it.

**Comment by downfall109** [comment]
It looks like there's a new setting for notifications: "Bring attention to the window", and this was on by default. Previously, I don't remember this being a feature.

**Comment by magnus-gross** [comment]
This is not a problem of Telegram. Either this is a Flatpak or Gnome issue. In either case what should happen (and what is happening for me on KDE X11) is that your application task bar should highlight Telegram - not activate it.

In my case the Telegram icon becomes orange highlighted and starts jumping for a few seconds:
![Screenshot_20200515_111415](https://user-images.githubusercontent.com/21310755/82033754-7aa6b900-969d-11ea-9560-51b578cfc98d.png)

I can activate it manually then by pressing Ctrl+Alt+A on KDE, but it does not get activated on its own.

**Comment by downfall109** [comment]
> This is not a problem of Telegram. Either this is a Flatpak or Gnome issue. In either case what should happen (and what is happening for me on KDE X11) is that your application task bar should highlight Telegram - not activate it.
> 
> In my case the Telegram icon becomes orange highlighted and starts jumping for a few seconds:
> ![Screenshot_20200515_111415](https://user-images.githubusercontent.com/21310755/82033754-7aa6b900-969d-11ea-9560-51b578cfc98d.png)
> 
> I can activate it manually then by pressing Ctrl+Alt+A on KDE, but it does not get activated on its own.

As I mentioned above, I was able to resolve the issue by turning off the Telegram setting "Draw attention to the window" which was turned on by default.

**Comment by ilya-fedin** [comment]
> Why is this on by default if the behaviour is inconsistent between platforms?

Because it was always by default, but just wasn't implemented on Linux
See #7887
