### ISSUE TITLE
[Feature Request] An option to remove "All Chats" folder completely

### ISSUE THREAD

**Issue by azat11** [telegramdesktop/tdesktop#7903]

**Comment by SurDno** [comment]
Yes! YES YES YES!
This is so damn needed. When you divide all your workflow into separate folders for each kind of chat, 'all chats' becomes a pure annoyance. Please let us remove it.

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/7533

**Comment by SurDno** [comment]
@Aokromes how is it a duplicate? The guy in the linked issue suggests setting a default folder, the guy here suggests removing All Chats.

**Comment by Aokromes** [comment]
"instead of showing all the chats"

**Comment by SurDno** [comment]
Yeah. Default folder. So that it open groups, and all chats are still in the list. No mention of removing or hiding all chats.

**Comment by RememberTheAir** [comment]
Side note: [Kotatogram](https://github.com/kotatogram/kotatogram-desktop) offers that option

![photo_2020-05-15_22-26-01](https://user-images.githubusercontent.com/16143208/82093267-174b7400-96fb-11ea-9c5f-af3333af97df.jpg)

**Comment by SurDno** [comment]
Why would one create their own fork instead of doing a pull request here is beyond me.

**Comment by RememberTheAir** [comment]
@SurDno because the pull request wouldn't be accepted

**Comment by azat11** [comment]
> 
> 
> Side note: [Kotatogram](https://github.com/kotatogram/kotatogram-desktop) offers that option
> 
> ![photo_2020-05-15_22-26-01](https://user-images.githubusercontent.com/16143208/82093267-174b7400-96fb-11ea-9c5f-af3333af97df.jpg)

This. Exactly. PLEASE.
