### ISSUE TITLE
[Question] The difference between #Hashtags, $CASHTAGS and the #_phrase_search ?

### ISSUE THREAD

**Issue by damnfella** [telegramdesktop/tdesktop#7908]
Can someone properly explain the difference between these 3 tags in Telegram??

$ANDROID
#ANDROID
#_ANDROID

**Comment by MasterGroosha** [comment]
as far as I know, cashtags currently serve the same role as hashtags: https://core.telegram.org/tdlib/docs/classtd_1_1td__api_1_1text_entity_type_cashtag.html
Though cashtags can only consist of capital latin letters and there are limits on cashtag length
