### ISSUE TITLE
Telegram App automaticaly unroll (active) when a new message received [Linux]

### ISSUE THREAD

**Issue by maxwell-hub** [telegramdesktop/tdesktop#7910]
### Steps to reproduce
1. Run Telegram App, rolle it to main toolbar ([https://i.imgur.com/d4kIVol.png](https://i.imgur.com/d4kIVol.png))
2. Wait until new message will not received
3. The telegram app become unrolled and active window

### Expected behaviour
App should be rolled and not active when new messages receive. It worked untill App was not auto updated to 2.1.4 version. I've tried to re-install app, but this issue has still reproduced

### Actual behaviour
When Telegram App rolled and placed to the menu bar or if App is not active window a new received message unroll telegram (window become active)

### Configuration
**Operating system:** Linux Mint 19.3
One extra monitor connected

**Version of Telegram Desktop:** 2.1.6

**Installation source (Linux Only):** distribution package (seems it flatpak build)

**Used theme**: default (night mode)

**Comment by Aokromes** [comment]
not a bug.
https://github.com/telegramdesktop/tdesktop/commit/6f760d513ea41b8017d4abd5f88e615fd5c0a10e
