### ISSUE TITLE
Message previews not loading

### ISSUE THREAD

**Issue by birykvlad** [telegramdesktop/tdesktop#7914]
### Steps to reproduce
1. Join to the "meduza_news" channel, and start receiving news
3. Fresh news will come without a preview when the old ones are displayed with it

### Expected behaviour
Fresh news should display previews.
If you restart Telegram, then the previews are displayed, but for new news it will not be again

### Actual behaviour
The news preview is not displayed, only the link to the news and its title

### Configuration
**Operating system:**
Windows 10 x64 Build 1909

**Version of Telegram Desktop:**
Telegram 2.1.6

**Installation source (Linux Only)** - the official website / GitHub releases / flatpak / snap / distribution package:

**Used theme**:
Default

<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by ilya-fedin** [comment]
#7091
