### ISSUE TITLE
Badge counter disappeared

### ISSUE THREAD

**Issue by Partizanin** [telegramdesktop/tdesktop#7915]
### Steps to reproduce
Steps to reproduce not known

probably it happened when i upload video to private chat and tried to open it, after that client crashed and badge counter disappeared

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

### Configuration
**Operating system:**
Windows 10 Pro  10.0.18363

**Version of Telegram Desktop:**
2.1.6 installed

**Installation source (Linux Only)** - the official website / GitHub releases / flatpak / snap / distribution package:
official website 
https://desktop.telegram.org/

**Used theme**:
https://t.me/addtheme/U6wnnKfRtTTOurhw

<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)

Unfortunately logs was removed  
</details>

**Comment by Partizanin** [comment]
Also after that crash i have lost opportunity to share any file

**Comment by Partizanin** [comment]
Found the solution, have installed app from Microsoft Store till that issue will be closed

**Comment by Aokromes** [comment]
try on 2.1.8.

**Comment by Partizanin** [comment]
> try on 2.1.8.

Sorry, cannot check it, because i have restored my os from backup, so you can close that issue
