### ISSUE TITLE
[bug] Telegram doesn't loads contacts or personal info when no network found

### ISSUE THREAD

**Issue by ezdev128** [telegramdesktop/tdesktop#792]
Telegram doesn't loads contacts or personal info when no network found.

LinuxMint, 64bit, LMDE MATE Edition.

![screenshot](http://s017.radikal.ru/i436/1506/05/21ea08f4f788.jpg)
![screenshot](http://s019.radikal.ru/i632/1506/35/e12ea6c60370.jpg)
![screenshot](http://s017.radikal.ru/i436/1506/1a/a21bbabb13e0.jpg)

**Comment by Mindstormer619** [comment]
On a fresh start of the client program, I think this is expected. Telegram stores the information on the cloud AFAIK.

**Comment by auchri** [comment]
Yes :) all the data is stored on the telegram servers. Without an internet connection the data can not be loaded.

**Comment by ezdev128** [comment]
I'm bet it was working before!
Dear developers, 
Please roll back this functionality. 
**An address book SHOULD BE ALWAYS ACCESSIBLE** independently of network.
Even on fresh start!

**Comment by auchri** [comment]
No, this never worked ;)

**Comment by Mindstormer619** [comment]
@ezdev128 I don't think it can work, really. Consider that one client can log in multiple accounts at various times. You can log out of Telegram and log in to a different account on the same PC. It would not make sense to keep the address book locally as the contacts will change.

**Comment by auchri** [comment]
And also the adress book is useless if you have no internet connection. You cannot send messages without internet.

**Comment by ezdev128** [comment]
I think it is not hard to have some local sqlite db or so and sync it when network works and just show the data from local storage.

**Comment by ezdev128** [comment]
@auchri it is useful for example to get some phone number from contact list and call to some user via cell phone (but no 2g/3g surface)

**Comment by auchri** [comment]
The numbers are also stored on your cell phone? :smile:

**Comment by Mindstormer619** [comment]
@auchri :laughing:

**Comment by ezdev128** [comment]
I know at least 5 persons from my contact list who do not use phone devices to use Telegram and only use desktop versions. How about them?

Ok, what about to read some message history when offline?

**Comment by Mindstormer619** [comment]
@ezdev128 It makes sense to copy the messages you want to read later to a different place. Telegram specifically cannot do this because it is a bit of a privacy issue. Storing data locally when it's pretty much not supposed to.

**Comment by auchri** [comment]
@ezdev128 @Mindstormer619 offline message history would be nice indeed

**Comment by ezdev128** [comment]
@Mindstormer619 it is not a correct way though. Sometimes you don't attend on some message and don't think it is so important but ... the the most important time your memory can joke on you unless you're a man with phenomenal memory!
Offline messages must have I think!

**Comment by ezdev128** [comment]
@Mindstormer619 also, if you wanna to keep it secure and do not store any messages, it should be secure chat, instead of plain.
I don't see any security reasons do not keep the contacts list to the drive (if possible).

**Comment by Mindstormer619** [comment]
@ezdev128 What you are describing (chats saved offline) is exactly what happens in SECURE chats. They are not saved in plaintext on the cloud. All normal chats are saved on the cloud only, because it is unknown how many people might log in to one client device. They are restored from the cloud when you log back in. However, secure chats are permanently deleted when you log out, as they are not present on the cloud (as I stated earlier).

**Comment by Mindstormer619** [comment]
@auchri Perhaps so, but looking at the way Telegram is used and the features it is providing, I doubt they'd move to that direction anytime soon. If you want to access your chat history while offline, I'd suggest not logging out, as the whole *point* of logging out is to make sure that no one else at your computer/phone is able to access your chats at all.

**Comment by ezdev128** [comment]
@Mindstormer619 ok, then it should be **an optional issue**. What if I do not care about security?
E.g. nobody can access on my PC and I don't want to keep it secure this way (e.g. I'm an advanced used and I know how to secure my PC).

**Comment by auchri** [comment]
@Mindstormer619 but it would be possible to store the "cloud" chat encrypted local. When another user logs in into the desktop client, the offline saved messages are deleted.
The offline message history is also available on android in on ios, it should be no problem to implement it into the desktop client

**Comment by Mindstormer619** [comment]
@ezdev128 Perhaps, but as I mentioned, I really doubt Telegram would have this functionality anytime in the future. Either way, that's no reason to file this as a bug. This is very much a feature request.

**Comment by ezdev128** [comment]
@Mindstormer619 it is no guarantee that an internet will be always accessible

**Comment by Mindstormer619** [comment]
@ezdev128 First off, Telegram is a **chat client**. I think the devs have made a reasonable assumption that you'd at least have an internet connection to use it. It's not an address book program. Often people make a lot more of this than it actually is.

**Comment by ezdev128** [comment]
@auchri by the way, yeah! E.g. iOS version keeps contacts and messages, even offline.

**Comment by Mindstormer619** [comment]
Even after you log out? That seems weird.

**Comment by auchri** [comment]
No of course not :smiley: 
It's only available when you are logged in and you have no internet connection.

**Comment by ezdev128** [comment]
@auchri no it is does. I just checked. Wanna screenshot?

**Comment by Mindstormer619** [comment]
@ezdev128 Sure. If the TG client on iOS keeps the user's information even **after** he logs out, it is a BUG in the iOS version and not a feature.

**Comment by ezdev128** [comment]
@Mindstormer619 IMHO it is not a bug but usability, instead of at the desktop. Any data could be secured anyways and store on local drive. Anyways it is possible to unlock them (via password key, pin, rsa key or whatever way).

**Comment by Mindstormer619** [comment]
![image](https://cloud.githubusercontent.com/assets/441849/7985382/f86f7944-0aed-11e5-8693-78c3dc849851.png)

\^This

**Comment by cobalto** [comment]
OMG. I can't believe on this issue. I'm laughing.

**Comment by Mindstormer619** [comment]
Yeah,pretty much my own reaction :joy:

**Comment by cobalto** [comment]
I think I found another bug somewhat related to this issue.

When I'm offline, none of my contacts answer me.
At first I thought they were just being stubborn, but then I tried talk with a buddy that I trust and the same issue happened.

Please fix it ASAP.

//// ============= ////

Seriously now, I've just discovered on another issue (#785) the existence of a client called "Cutegram".
I'm not saying it's trustworthy, never tried myself, but how can I say that... they store chat offline.
