### ISSUE TITLE
1.75 GB ram usage

### ISSUE THREAD

**Issue by specter78** [telegramdesktop/tdesktop#7920]
### Steps to reproduce
I had the app open constantly for about 3 days.

### Expected behaviour
Limited memory footprint.

### Actual behaviour
High memory usage

### Configuration
**Operating system:** macOS 10.15.4

**Version of Telegram Desktop:** 2.1.4

**Used theme**: Tinted

<details><summary><b>Screenshot</b>:</summary>
<img width="500" alt="Screenshot" src="https://user-images.githubusercontent.com/40606342/82488115-ffaa2c00-9afc-11ea-91c2-1bbbb48cc33a.png">

</details>

**Comment by r4v3n6101** [comment]
Ram's cache is enough when it's over

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/7361
