### ISSUE TITLE
Upon receipt of an event, the focus of an active window switches to Telegram window

### ISSUE THREAD

**Issue by oripio** [telegramdesktop/tdesktop#7922]
### Steps to reproduce
1. Receive any message

### Expected behaviour
Should be received notification about an event (e.g., new message)

### Actual behaviour
Focus of an active window switches to Telegram window

### Configuration
**Operating system:** Linux. Linux Mint Debian Edition (debian 9.3). 

**Version of Telegram Desktop:** 2.1.5.

**Installation source (Linux Only)** - the official website / GitHub releases / flatpak / snap / distribution package: official website

**Used theme**: Night

<details><summary><b>Logs</b>:</summary>
</details>

**Comment by Aokromes** [comment]
not a bug, disable feature.

**Comment by oripio** [comment]
> not a bug, disable feature. somewhere on notifications.

No such settings

**Comment by oripio** [comment]
Okay, in Russian the settings 'Подсветка окна' (Window highlight). I don't think it's correct description. In my understanding, this is the highlighting a Telegram window in the task list but not switch active window handle to Telegram window.
