### ISSUE TITLE
[Snap version] Telegram desktop constantly exits asking to connect to kde-frameworks-5-core18

### ISSUE THREAD

**Issue by virresh** [telegramdesktop/tdesktop#7923]
The snap version of telegram desktop is a bit buggy. I randomly encounter issues opening it, and sometimes restarting works. This time however, I'm not able to get it working even after restarts and the snap version asks for connection to some kde-framework, which is already installed and the connection command of snap doesn't do anything.

### Steps to reproduce
1. Open command line
2. Type telegram-desktop as usual to launch the snap version
3. The message pops up on command line

### Expected behaviour
Telegram Desktop app should get started

### Actual behaviour
The app doesn't open, and the only message on command line is 
```
You need to connect this snap to the kde-frameworks-5-core18 snap.

You can do this with those commands:
snap install kde-frameworks-5-core18
snap refresh kde-frameworks-5-core18
snap connect telegram-desktop:kde-frameworks-5-plug kde-frameworks-5-core18:kde-frameworks-5-core18-slot
```

### Configuration
**Operating system:** Ubuntu 18.04, Kernel 4.15.0-99-generic, Gnome Desktop Environment

**Version of Telegram Desktop:** 2.1.6
```
snap-id:      jpdoHqMd90M39DdH2JSZbeQxipqHtwLo
tracking:     latest/stable
refresh-date: 7 days ago, at 12:04 IST
channels:
  latest/stable:    2.1.6               2020-05-14 (1627) 72MB -
  latest/candidate: ^                                          
  latest/beta:      1.7.12-beta         2019-07-06  (834) 98MB -
  latest/edge:      2.1.6-11-g8d1db85a2 2020-05-20 (1630) 72MB -
installed:          2.1.6                          (1627) 72MB -
```

**Installation source (Linux Only):** Snap

**Used theme**: Dark Theme of Telegram

Here is what occurs when I try connecting it with the given commands:

<pre><font color="#8AE234"><b>viresh@viresh-pc</b></font>:<font color="#729FCF"><b>~</b></font>$ telegram-desktop 
You need to connect this snap to the kde-frameworks-5-core18 snap.

You can do this with those commands:
snap install kde-frameworks-5-core18
snap refresh kde-frameworks-5-core18
snap connect telegram-desktop:kde-frameworks-5-plug kde-frameworks-5-core18:kde-frameworks-5-core18-slot
<font color="#8AE234"><b>viresh@viresh-pc</b></font>:<font color="#729FCF"><b>~</b></font>$ snap install kde-frameworks-5-core18
snap &quot;kde-frameworks-5-core18&quot; is already installed, see &apos;snap help refresh&apos;
<font color="#8AE234"><b>viresh@viresh-pc</b></font>:<font color="#729FCF"><b>~</b></font>$ snap refresh kde-frameworks-5-core18
snap &quot;kde-frameworks-5-core18&quot; has no updates available
<font color="#8AE234"><b>viresh@viresh-pc</b></font>:<font color="#729FCF"><b>~</b></font>$ snap connect telegram-desktop:kde-frameworks-5-plug kde-frameworks-5-core18:kde-frameworks-5-core18-slot
<font color="#8AE234"><b>viresh@viresh-pc</b></font>:<font color="#729FCF"><b>~</b></font>$ telegram-desktop 
You need to connect this snap to the kde-frameworks-5-core18 snap.

You can do this with those commands:
snap install kde-frameworks-5-core18
snap refresh kde-frameworks-5-core18
snap connect telegram-desktop:kde-frameworks-5-plug kde-frameworks-5-core18:kde-frameworks-5-core18-slot
</pre>

Nothing is written inside `~/snap/telegram-desktop/current/.local/share/TelegramDesktop/log.txt`, not sure if there is another log-file though.

**Comment by virresh** [comment]
I switched over to the binary distribution for Linux x64, and it seems to be working well 
(2.1.5, not sure if new version is responsible for issues on snap or not though)

**Comment by ilya-fedin** [comment]
> which is already installed and the connection command of snap doesn't do anything.

Then, probably, only snap package re-installation can help

**Comment by ilya-fedin** [comment]
> I switched over to the binary distribution for Linux x64, and it seems to be working well

Do you plan to try snap reinstallation or the issue can be closed?

**Comment by virresh** [comment]
> snap package re-installation can help

My other snaps are working just fine, so not sure if I'll try reinstalling snap 
Please go ahead and close the issue.

**Comment by ilya-fedin** [comment]
> My other snaps are working just fine, so not sure if I'll try reinstalling snap

I mean tdesktop snap package, not snaps itself

**Comment by virresh** [comment]
Oh. I'd tried that before finally switching to the binary distribution. Didn't work for me.

**Comment by ilya-fedin** [comment]
> Oh. I'd tried that before finally switching to the binary distribution. Didn't work for me.

:thinking: that's strange

**Comment by ilya-fedin** [comment]
What version of snapd do you have?

**Comment by virresh** [comment]
snap    2.44.3
snapd   2.44.3
series  16
ubuntu  18.04
kernel  4.15.0-101-generic

(PS: I'd recently updated my kernel so the kernel version has changed)

**Comment by ilya-fedin** [comment]
`snap connections telegram-desktop`

**Comment by virresh** [comment]
Alright,
I'd uninstalled the snap version and symlinked telegram-desktop with the binary... so... 
It will probably be a long while before I get sufficient time to help you out more on triaging this one

**Comment by adasiko** [comment]
Same thing...
Does kde-frameworks-5-core18 is dependency requirement now?
I did not notice this earlier...

**Comment by ilya-fedin** [comment]
> Does kde-frameworks-5-core18 is dependency requirement now?

Yes

> Same thing...

https://github.com/telegramdesktop/tdesktop/issues/7923#issuecomment-636796352

**Comment by ilya-fedin** [comment]
There are no kde-frameworks-5-core18 dependency now
