### ISSUE TITLE
Enhancement: Add folder context menu options for quickly include or exclude chats

### ISSUE THREAD

**Issue by aleksusklim** [telegramdesktop/tdesktop#7927]
### Is your feature request related to a problem?

Sometimes I just want to put one chat to a folder. To do this, I have to open edition dialog for that folder, and then seek that chat again.

This is not convenient.

### Describe the solution you'd like

Add three more context menu options for folders, which will be visible if messages panel has any open chat:

- "Include this chat": visible if this chat is not included explicitly and there is a room for it to be added to include-list;
- "Remove this chat": visible if this chat was already explicitly included or excluded to this folder.
- "Exclude this chat": visible if this chat is not excluded explicitly and there is a room for it to be added to exclude-list;

(This way no more than two options will be shown simultaneously).

### Describe alternatives you've considered

Chat could have an option like "Add to folder" on any or its dedicated menus, which will bring another dialog box where you can choose one or more folders to include or exclude this chat.

But I think that this approach seems more complicated to implement, than adding a simple folder context menu entries.

### Configuration

**Operating system:** Windows 7 SP1
**Version of Telegram Desktop:** 2.1.6
**Used theme**: Classic

**Comment by RememberTheAir** [comment]
This is kinda included in #7500 but I think it doesn't make sense to have a single issue grouping all those different requests, so I would keep this one open

**Comment by aleksusklim** [comment]
Э, я те сча закрою, ага!

**Comment by nmahdi14** [comment]
yes. it's necessary

**Comment by Govi59** [comment]
Hello there, yes it would be very convenient to add this item in the context menu.
It would be great to do it with **right_click > Add to folder > Select the folder** instead of **Folders Settings > Select the folder > Add channel > Select channel**

**Comment by Ali7med** [comment]
its still in 2022 , this feature not available !!

**Comment by 23rd** [comment]
Can be closed?

**Comment by aleksusklim** [comment]
Yes, fixed in 3.7, thank you!

![image](https://user-images.githubusercontent.com/13969463/164153974-504787bd-1817-4d22-ac0f-3acda075965f.png)

**Comment by Ali7med** [comment]
finally ... thanks  .
