### ISSUE TITLE
Bug: Folder forgets last scroll position of chat list

### ISSUE THREAD

**Issue by aleksusklim** [telegramdesktop/tdesktop#7928]
### Steps to reproduce

1. Make at least two folders that will have more chats than height of screen.
2. Go to one folder and scroll chat list.
3. Click on different folder and then click to the first folder again.

### Expected behavior

Chat list scroll position should remain as it was left in each folder, just as each chat remembers its scroll position in messages panel.

Only after a second click to currently opened folder it should scroll to the top, just as each chat scrolls to the bottom when clicked in the second time.

### Actual behavior

Each folder always open its chat list scrolled to the top and never remembers user scroll state.

### Describe the solution you'd like

Chat list last scroll position should be stored for each folder separately and only reset after clicking "to the top of list" arrow-button at the bottom, or by clicking an active folder in the second time.

### Configuration

**Operating system:** Windows 7 SP1
**Version of Telegram Desktop:** 2.1.6
**Used theme**: Classic

**Comment by aleksusklim** [comment]
Э, я те сча закрою, ага!

**Comment by aleksusklim** [comment]
Убери от моих issues свой блестящий зад!

**Comment by aleksusklim** [comment]
3.1.7, still.

**Comment by aleksusklim** [comment]
Как вы оба достали, 4.2.4 на дворе, лучше пофиксите уже!

**Comment by ilya-fedin** [comment]
Why do you think it's a bug? I feel it works like it's supposed to.

**Comment by aleksusklim** [comment]
> Why do you think it's a bug? I feel it works like it's supposed to.

Because scroll position can be reset manually, by clicking the folder icon again.
Just as any chat position is reset after a second click to already active chat.

You don't say that chat messages panel should not retain scroll position, do you? So, why not to retain the position of the chat list itself?
Both of which can be easily reset by second click.

Moreover, this second click is ALREADY working on every folder, including "All chats"!

**Comment by ilya-fedin** [comment]
It may be intended behavior in fact, I'll ask preston. If he will confirm then this couldn't be a bug report. A feature request at most.

**Comment by ilya-fedin** [comment]
preston confirmed this is not a bug. @aleksusklim can you remove the 'Bug:' part from the title? (if not it would be easier for @Aokromes to close the issue as he doesn't have the right to change the title)

**Comment by aleksusklim** [comment]
Fuck you, fuck preston, fuck aokromes, fuck telegram, fuck bugs and fuck features too!

**Comment by john-preston** [comment]
@aleksusklim nice, it comes exactly while @23rd implemented the feature in a closed branch 🤣

**Comment by 23rd** [comment]
> Fuck you, fuck preston, fuck aokromes, fuck telegram, fuck bugs and fuck features too!

😰😰😰

**Comment by aleksusklim** [comment]
Fixed by 0dd45de254bc7b9696323100e5e0d06bfe42b0ed.

Now, the scroll position is reset when returning from topics (recent feature).
It shouldn't!

**Comment by ilya-fedin** [comment]
Please fix the title to illustrate the current situation (`[Feature Request] Remember last scroll position when returning from topics`)

**Comment by aleksusklim** [comment]
> Please fix the title to illustrate the current situation ([Feature Request] Remember last scroll position when returning from topics)

No, the current title `Bug: Folder forgets last scroll position of chat list` is still valid, especially because this is clearly a bug now.

**Comment by 23rd** [comment]
Please check the 4.3.1 version.

**Comment by aleksusklim** [comment]
> Please check the 4.3.1 version.

It works for forums and for all folders EXCEPT those which have "Excluded Chats → Remove chats → Chat types → Read". So, each folder where all read chats are hidden – does not store/recall its scroll position.

Does anybody know why? To see this, just add "Read" to "Excluded" filter for any folder: this folder will forget its scroll position from now on.
Other that this, the feature works as intended! But the bug is fixed only partially for now (it is even more confusing than before, especially because "Unread" folder is suggested by default as the first folder to create).

**Comment by 23rd** [comment]
> It works for forums and for all folders EXCEPT those which have "Excluded Chats → Remove chats → Chat types → Read".

Hmm, yes, I did an explicit exception for this type of folder. My thoughts were: folders with this chat type have a very dynamic chat list and there is no sense to save a scroll position for them. Do you think it should be changed?

**Comment by aleksusklim** [comment]
> I did an explicit exception for this type of folder. 

Well, it is still possible to pin chats there… But actually that's not very useful and contradictory to read exception (since it adds an explicit inclusion).

I've checked more and it appears that such folder is still correctly handles the case when the user return from a forum: it remembers its position! Otherwise that would be a major issue.

Concluding, the current behavior seems to be reasonable. It's more like "press here to see new messages" rather than a real folder to separate chats. Though I didn't consider other ways to use include-exclude filter for folders with "only unread" and consequences of not remembering scroll position.

Seems the issue is resolved and will not annoy anymore. Thanks!
