### ISSUE TITLE
Feature: Make chats not be 'read' after sending a Scheduled Message

### ISSUE THREAD

**Issue by aleksusklim** [telegramdesktop/tdesktop#7929]
### Steps to reproduce

1. Open a chat with many unread messages in it.
2. Write a message, but do not send it (note that your scroll position will be somewhere in the middle; all next messages will be still 'unread').
3. Use context menu on Send button and choose "Schedule message". Set any timer parameters and finally send it.
4. Return to the main chat panel from currently visible "Scheduled messages" panel.

### Expected behavior

Chat scroll position should remain as it was before sending a scheduled message.

All unread messages in this chat should not suddenly become 'read'.

### Actual behavior

Chat will be instantly scrolled to the bottom, and consequentially, all unread messages are lost, just as actual 'read position' in this chat.

Note that if you have used "Reply" function to send your scheduled message, then you can open Scheduled messages panel and click on a reply field of your message there. This will restore your 'read position' but does not save you from losing all unread messages so far.

### Describe the solution you'd like

It will be great if sending a scheduled message did not erase all unread messages in this chat, because it will allow using Scheduled messages feature as a way to, well, schedule your reply till the moment you actually read all of unread messages here. Then go to scheduled messages panel and press "Send now" for anything left scheduled.

### Configuration

**Operating system:** Windows 7 SP1
**Version of Telegram Desktop:** 2.1.6
**Used theme**: Classic

**Comment by ilya-fedin** [comment]
https://github.com/telegramdesktop/tdesktop/commit/d4feb1637852d629cee7c0a82bc259a909a50dcb
