### ISSUE TITLE
Go to a date directly in chat history

### ISSUE THREAD

**Issue by specter78** [telegramdesktop/tdesktop#7930]
### Is your feature request related to a problem?

To look up older chat messages, one has to scroll even when the date of conversation is known. 

Also, many times, chat position is not retained by app. In this case also, same thing applies. 

### Describe the solution you'd like

Option to go to a date in chat history. 

### Describe alternatives you've considered

NA

**Comment by Aokromes** [comment]
click search-> click calendar -> select desired date.
