### ISSUE TITLE
Activate the drawing tools (to crop, change luminosity, contrast,...) [Feature Request] 

### ISSUE THREAD

**Issue by mdan312** [telegramdesktop/tdesktop#7932]
I suggest to activate the drawing tools (to crop, change luminosity, contrast, masks,...) also for the desktop Telegram application
I suggest to have these tools available also for clipboard pictures (inserted through ctrl-V) or pictures shared from right clic / send to/Telegram or forwarded from another chat.

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/1762
