### ISSUE TITLE
Secret chat from Desktop app [Feature Request] 

### ISSUE THREAD

**Issue by mdan312** [telegramdesktop/tdesktop#7934]
Allow secret message also from desktop application (just indicate to the partner that this secret chat goes to a desktop computer so he knows that screenshots cannot be prevented)

We should anyway for secret chats systematically tell on which device both partners are located because if there is an hijack it is a way to know we are not talking to the right phone/tablet/computer!!

**Comment by Aokromes** [comment]
oh another ticket of secret chats, centuplicated.

**Comment by mdan312** [comment]
Yes it means it is an important one...
