### ISSUE TITLE
Where can we do a feature suggestion for the bot API [Question] 

### ISSUE THREAD

**Issue by mdan312** [telegramdesktop/tdesktop#7935]
I suggest to add to the bot API the method /getMessage?chat_id=313740241&message_id=2 that would simply return the JSON of the message (if the bot is allowed)

**Comment by mdan312** [comment]
Another feature suggestion: I propose to add the optional field language to the BotCommand object.
setMyCommands in the bot API is a great idea but there should be an option to attach to a language (to get the short explanations in the user's language)

It would also be interesting to be able to apply a new command list to a specific chatId => we could  propose various command sets depending on the profile of the user of the bot... So  I propose to add the optional parameter "scope" to setMyCommands with possible values:
- all (default)
- a language code
- a chatId

**Comment by Aokromes** [comment]
you must ask that in app ask a question.
