### ISSUE TITLE
Add a CLI mode to Telegram Desktop [Feature Request] 

### ISSUE THREAD

**Issue by mdan312** [telegramdesktop/tdesktop#7937]
I suggest to be able to launch Telegram from the command line with some parameters...

It could be to include telegram-cli? (There is no windows implementation)
See: https://gist.github.com/weibeld/281feed0b2f5d141fa7e85fc618dd7fc

**Comment by Aokromes** [comment]
you already have multiple command line commands for telegram desktop.

**Comment by ilya-fedin** [comment]
> It could be to include telegram-cli? (There is no windows implementation)

Windows applications can't be CLI and GUI at the same time

**Comment by mdan312** [comment]
> you already have multiple command line commands for telegram desktop.

Great news! Where can I find the reference about these commands ?

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/wiki/Command-Line-Switches

**Comment by ChanceNCounter** [comment]
Additional commands would be nice. I'm trying to integrate telephony with a voice assistant, and the most obvious way to place and answer Telegram calls would be via the command line, using whichever client the user is already running. Likewise, placing a call from a contact manager should ideally launch or call from the user's existing Telegram client. 

Most mobile Linux distros, at least for the time being, are just running (ideally resized) desktop clients, so the use case now extends well beyond desktop computers.
