### ISSUE TITLE
Telegram does not release handles of uploaded files

### ISSUE THREAD

**Issue by NullEnt1ty** [telegramdesktop/tdesktop#7938]
Duplicate of #2583 and #3901, I think. Both issues were closed long time ago, without resolving them.

### Steps to reproduce
1. Send a file
2. Wait for transmission to succeed
3. Try to delete that file without closing Telegram Desktop

### Expected behaviour
I should be able to delete the file after it was sent.

### Actual behaviour
Windows doesn't let me delete the file because at least one program is still using it. Closing Telegram fixes the issue.

### Configuration
**Operating system:** Windows

**Version of Telegram Desktop:** 2.1.6

**Used theme**: Classic

**Comment by Aokromes** [comment]
i am sure there is a 3rd still opened ticket about this xd

**Comment by NullEnt1ty** [comment]
Well... I tried to find them all beforehand 🙈 Can you link it so we can flag this issue as a duplicate?

**Comment by Aokromes** [comment]
i tried it, but cannot remind keywords.

**Comment by ilya-fedin** [comment]
#7818

**Comment by NullEnt1ty** [comment]
Thanks, @ilya-fedin! I'm gonna close this issue in favor of #7818.
