### ISSUE TITLE
Enhancement: Check for file's existence before downloading (for multiple-OS computers)

### ISSUE THREAD

**Issue by sadeghi-aa** [telegramdesktop/tdesktop#7939]
Hi.

I have Windows and Ubuntu on my laptop and I've got Telegram installed on both of them with the same account. I figured it would be a good idea to have a single download path on both OSs, so I set the download path manually for both of them to the same folder. The problem is when I download a file in, say, Windows, and switch to Ubuntu, the other client ignores that the exact file is already in that folder and re-downloads the file with a (2) in the file name. I know the download log is probably saved somewhere else in each OS to keep track of the files, but it would be nice and save a good amount of data if it checked the directory for the file (using hash, maybe?).

**Comment by ilya-fedin** [comment]
#1965
