### ISSUE TITLE
Hashtag - Index Needed Badly

### ISSUE THREAD

**Issue by squirrelboot** [telegramdesktop/tdesktop#794]
So with my friends, I have created several hashtags for important things. However, I realized recently that unless I remember them all.. I can't find them easily. I have also misspelled a few I think, and now I can't find them. 

**Request:** We need a way to see what #hashtags we have created, so that we may filter by that.

**Suggestion:** When clicking on a person's name in your list, where it shows 'Shared Media' and where you can clear history or check/uncheck 'Notifications' -- *Add an index of hashtags that have been used.* 

Thus, a simple way of tracking down commonly used hashtags, or the occasional accidental misspelled hashtags.

**Comment by auchri** [comment]
I think there is no api for that
