### ISSUE TITLE
Inertial scrolling support on Linux when using a touchpad

### ISSUE THREAD

**Issue by Pointedstick** [telegramdesktop/tdesktop#7941]
### Is your feature request related to a problem?
When using Telegram on Linux with a laptop touchpad, there is no inertial scrolling; touchpad scroll gestures result in the view scrolling at a constant speed and the scroll abruptly ends rather than decelerating and coming to a smooth stop.

### Describe the solution you'd like
Inertial scrolling when using a touchpad, as described above.

### Describe alternatives you've considered
Ditching Linux and using Telegram on macOS or Windows, where there is inertial scrolling (lol, just kidding)

**Comment by john-preston** [comment]
@Pointedstick I'm not sure I can do this, looks like it is on Qt side. If you have any Qt open source applications where it works and I can see how this is done, I'd like to take a look.

**Comment by Pointedstick** [comment]
QScroller has these features: https://doc.qt.io/qt-5/qscroller.html

At a naive level, it's as simple as:

```
QListView* listView = new QListView(this);
QScroller::grabGesture(listView->viewport(), QScroller::TouchGesture);
```

You can see how it's being implemented in KDE's Dolphin file manager here: https://invent.kde.org/system/dolphin/-/merge_requests/7/diffs

**Comment by ilya-fedin** [comment]
#6746?

**Comment by Pointedstick** [comment]
Yep, looks like a dupe.
