### ISSUE TITLE
Not able to search partial string of a word. Please consider enabling regular expression search.

### ISSUE THREAD

**Issue by ly4096x** [telegramdesktop/tdesktop#7942]
### Steps to reproduce

1. Send message `Telegram test. 中文测试。`.
2. Search for `gram` or `中`.
3. There are no search results.

### Expected behaviour

Shows the message `Telegram test. 中文测试。` as search result.

### Actual behaviour

Telegram search matches whole words only, and it seems that contributors don't want to make change to this behavior. See #564, [DrKLO/Telegram/pull/629](https://github.com/DrKLO/Telegram/pull/629), [Telegram-iOS/#35](https://github.com/TelegramMessenger/Telegram-iOS/issues/35).

If you don't want to implement partial word search, please consider adding a switch to allow advanced users search with regular expression. Then you can keep the default search behavior unchanged while making the search feature more usable.

### Configuration

**Operating system:** Windows 10 x64

**Version of Telegram Desktop:** v2.1.6

**Comment by Aokromes** [comment]
duplicate, api bug.

**Comment by ly4096x** [comment]
Sorry, what does `api bug` mean?

**Comment by Aokromes** [comment]
it belongs to telegram server and not clients.

**Comment by ly4096x** [comment]
Oh, that make sense... anyway, thank you for the explanation.

**Comment by themikesam** [comment]
> it belongs to telegram server and not clients.

so how we can report or this bug not gonna fix forever?

**Comment by Aokromes** [comment]
> > it belongs to telegram server and not clients.
> 
> so how we can report or this bug not gonna fix forever?

in client -> ask a question.

**Comment by themikesam** [comment]
Reported in client, hope can settle this.

**Comment by mgs20190702** [comment]
for the last 2 year , i've tried every possible way to contact Telegram's development team about "partial search in any language doesn't work" , but i didn't get any reply.

If anyone know other way to contact them , please try your way to let them know , this is a very very important feature

**Comment by themikesam** [comment]
@mgs20190702 Agree, hope can solve it asap.

**Comment by ron159** [comment]
> for the last 2 year , i've tried every possible way to contact Telegram's development team about "partial search in any language doesn't work" , but i didn't get any reply.
> 
> If anyone know other way to contact them , please try your way to let them know , this is a very very important feature

Hey, telegram has released the official bug platform.This question has already been submitted.Upvote it here:https://bugs.telegram.org/c/724
