### ISSUE TITLE
tdesktop from website cannot access xkbcommon Compose file on Plasma Wayland, causes loss of accents

### ISSUE THREAD

**Issue by herzenschein** [telegramdesktop/tdesktop#7944]
### Steps to reproduce
1. Enter a Plasma Wayland session
2. Download Telegram Desktop for Linux
3. Run Telegram
4. Try to input any word with accents

### Expected behaviour
When under locale that includes dead keys (accents like éóãõ etc), Telegram should accept type accents accordingly on Wayland. Meaning that, if I type "não é" when my locale is pt_BR.UTF-8, the result should be "não é".

### Actual behaviour
When under locale that includes dead keys (accents like éóãõ etc), Telegram does not accept type accents accordingly. Meaning that, if I type "não é" when my locale is pt_BR.UTF-8, the result is "nao e".

### Configuration
**Operating system:**
Operating System: openSUSE Tumbleweed 20200520 (Plasma from master)
KDE Plasma Version: 5.19.80
KDE Frameworks Version: 5.71.0
Qt Version: 5.15.0
Kernel Version: 5.6.12-1-default
OS Type: 64-bit
Processors: 4 × Intel® Core™ i5-7200U CPU @ 2.50GHz
Memory: 15,5 GiB of RAM
Graphics Processor: Mesa DRI Intel® HD Graphics 620 

**Version of Telegram Desktop:**
2.1.7
**Installation source (Linux Only)** - the official website / GitHub releases / flatpak / snap / distribution package: official website (this bug does not occur with flatpak)

**Used theme**: tinted

### WORKAROUND

I noticed Telegram Desktop from website on Plasma Wayland outputs the following in the terminal:
`xkbcommon: ERROR: couldn't find a Compose file for locale "pt_BR.UTF-8"`
After some search, I found the environment variable XCOMPOSEFILE, which makes telegram find the correct Compose file required for accent input, so by running:
`XCOMPOSEFILE=/usr/share/X11/locale/pt_BR.UTF-8/Compose telegram`
This issue no longer occurs. I don't even require QT_IM_MODULE=xim, as suggested in https://github.com/telegramdesktop/tdesktop/issues/1360, nor did I need Ibus. It is possible that the aforementioned issue and others could be fixed this way by setting something like
`XCOMPOSEFILE=/usr/share/X11/locale/$LANG/Compose telegram`

**Comment by ilya-fedin** [comment]
Why did you create a duplicate if you know that this issue already exists?

**Comment by ilya-fedin** [comment]
#1041

**Comment by herzenschein** [comment]
I must mention that this issue is not reproducible on Xorg for me, only on Wayland, so it's likely **not** a duplicate of #1041. I'll test this on other distros and DEs, though.
