### ISSUE TITLE
Add "Instant View" feature to Telegram Desktop [Feature Request] 

### ISSUE THREAD

**Issue by krunkerista** [telegramdesktop/tdesktop#7946]
### Is your feature request related to a problem?
At the moment, when someone sends you a link, it will be opened in the browser when you click on it.

### Describe the solution you'd like
A more convenient way would be to add "Instant View" option so that the webview of the website opens within the app. The mobile version of Telegram has this option.

**Comment by RememberTheAir** [comment]
Duplicate of #3492
