### ISSUE TITLE
Dock icon continues bouncing after new messages have been read [osx]

### ISSUE THREAD

**Issue by qgates** [telegramdesktop/tdesktop#7949]
### Steps to reproduce
1. Make sure tdesktop is not the foreground app (in our case it's locked)
2. Message arrives and dock icon correctly bounces, showing unread message count in red
3. Read message using telegram on another device

### Expected behaviour
Dock icon should stop bouncing and unread message count should disappear

### Actual behaviour
Though unread message count has cleared on the dock icon, it continues bouncing forever. It only stops bouncing if tdesktop is activated on the Mac.

Note. This problem seems to have appeared in recent builds of tdesktop. It started happening approximately one month ago. On our Mac tdesktop is set to install beta versions.

### Configuration
**Operating system:** osx el capitan

**Version of Telegram Desktop:** 2.1.5

**Installation source (Linux Only)** - the official website / GitHub releases / flatpak / snap / distribution package: official website, mac osx

**Used theme**: dark

<details>
</details>

**Comment by ilya-fedin** [comment]
> This problem seems to have appeared in recent builds of tdesktop.

There has never been cancellation of bouncing icon

**Comment by ilya-fedin** [comment]
#5280

**Comment by qgates** [comment]
1. Well, in the last 5+ years of using tdesktop, dock bouncing has always cancelled when new messages have been read on other devices. It started happening in the most recent builds which modified dock icon bounce behaviour. But maybe it's just me. 

2. In the event that I'm wrong, I still fail to see how this can be considered a non-issue and just closed. The current behaviour is clearly not helpful. If a new message is read on my phone I don't need the mac constantly bugging me that I haven't read it. Its confusing, intrusive (when watching a movie) and causes me to have to open tdesktop for no reason.

In the event that this isn't by design I'd appreciate at least reopening and marking this as an FR.

**Comment by ilya-fedin** [comment]
>     2\. In the event that I'm wrong, I still fail to see how this can be considered a non-issue and just closed.

Duplicate

**Comment by ilya-fedin** [comment]
>     1. It started happening in the most recent builds which modified dock icon bounce behaviour. But maybe it's just me.

You can install old version and recheck

**Comment by qgates** [comment]
> You can install old version and recheck

I took your advice, installed v2.0.1 to compare and the behaviour is different. With 'Desktop notifications' checked and 'senders name / play sound' unchecked (same config as my 2.1.5 installation) a new message causes the dock icon to bounce for 15 seconds or so then it stops bouncing. With 2.1.5, it keeps bouncing forever - even if the message is read on another device.

So the behaviour from 2.0.1 (March 31) to 2.1.5 is quite different, as pointed out above.

Perhaps this change is an unintended side effect of feature improvements to Mac integration. That's fine. But the current behaviour isn't helpful nor consistent with other telegram apps. I love the dock bouncing to indicate unread messages but it should stop, either after a time (as before) or whenever these messages are read on other devices. Perhaps you could reopen this as a FR, unless already in the process of improving this behaviour?

**Comment by ilya-fedin** [comment]
>  Perhaps you could reopen this as a FR

#5280

**Comment by qgates** [comment]
I think #5280 is a different issue. The behaviour I see on Windows with the current version is that if I get unread messages and read them on the phone, the unread message count, in red over the telegram systray icon, correctly disappears. I can't remember about the taskbar icon as I normally keep tdesktop closed on Windows (but running in the systray) so I'm not sure if there is any indication on the taskbar that's not clearing.

I will doublecheck on Windows, but what I see on the Mac is that the unread count correctly clears on the dock icon when I read the msg on the phone, but the icon keeps bouncing forever regardless - without any red unread msg indicator - until I activate the tdesktop window.

**Comment by john-preston** [comment]
@qgates Yes, this will be returned to the old way in the next version.

**Comment by qgates** [comment]
Hi @john-preston has this been been fixed in 2.1.10?
