### ISSUE TITLE
Search in history?

### ISSUE THREAD

**Issue by kleuterX** [telegramdesktop/tdesktop#795]
I'd really love to have a search-in-message-history feature.

**Comment by ezdev128** [comment]
Related to https://github.com/telegramdesktop/tdesktop/issues/364

**Comment by auchri** [comment]
Just write into the search field and it will search into the last messages

**Comment by ezdev128** [comment]
@auchri what search field? Above to contacts list?

**Comment by auchri** [comment]
yes :)

**Comment by ezdev128** [comment]
@auchri are you kidding? This is the contact list search input field, it doesn't related to any messages.

**Comment by auchri** [comment]
@ezdev128 lol no. It searches for contacts and messages

**Comment by bil-elmoussaoui** [comment]
@ezdev128 you have to press enter after writing the word you want to search.

**Comment by auchri** [comment]
@bil-elmoussaoui not really. You just write and it searches without pressing enter.

**Comment by ezdev128** [comment]
@bil-elmoussaoui hm, thanks for tip. Without Enter press the search does not start.

**Comment by bil-elmoussaoui** [comment]
when you don't press enter, the application will search only in the contact list!

**Comment by auchri** [comment]
No, for me it searches also in messages

**Comment by kleuterX** [comment]
Sorry can confirm that it also searches in history.
But this is really ODD in terms of UI... Contact widget displays search for history?...

**Comment by Katzen-Gott** [comment]
@kleuterX , could you please close the issue if all is fine with your request?

**Comment by kleuterX** [comment]
Done
