### ISSUE TITLE
"Go up" button in contacts list disappears if user scrolled to the end

### ISSUE THREAD

**Issue by PrographerMan** [telegramdesktop/tdesktop#7951]
### Steps to reproduce
1. Scroll contacts list to end 

### Expected behaviour
"Go up" button should not disappear

### Actual behaviour
"Go up" button disappears

### Configuration
**Operating system:** Windows 7

**Version of Telegram Desktop:** 2.1.6

**Used theme**: Night mode

**Comment by worm202** [comment]
I can confirm this. This is reproducible on the latest stable 2.1.6 in any folder.
The button is visible if scrolled to the middle of the list and disappears if you reach the end of it. My guess that it acts the same as the button in the chat window where it is expected behavior.

**Comment by john-preston** [comment]
@PrographerMan If it won't disappear you won't be able to see the message in the last dialog.
