### ISSUE TITLE
> Ok I try to do it again and have the same problem:

### ISSUE THREAD

**Issue by nhan19899** [telegramdesktop/tdesktop#7957]
> Ok I try to do it again and have the same problem:

But it is successful:

> -- Build files have been written to: C:/TBuild/Libraries/openal-soft/build

Btw, remember to use `code` tag

_Originally posted by @ilya-fedin in https://github.com/telegramdesktop/tdesktop/issues/7568#issuecomment-633314098_

**Comment by ilya-fedin** [comment]
WTF 🧐

**Comment by nhan19899** [comment]
> Ok tôi cố gắng làm lại và có cùng một vấn đề:
