### ISSUE TITLE
[Question] VS2019 build issue

### ISSUE THREAD

**Issue by sky4nvcoder** [telegramdesktop/tdesktop#7959]
there are tons of build failures

for example, the first few warnings/errors are:

2>cl : command line warning D9002: ignoring unknown option '/Zc:preprocessor'
2>cmake_pch.cxx
2>C:\TBuild\tdesktop\Telegram\ThirdParty\range-v3\include\concepts/concepts.hpp(890,13): error C2220: the following warning is treated as an error
2>C:\TBuild\tdesktop\Telegram\ThirdParty\range-v3\include\concepts/concepts.hpp(890,13): warning C4002: too many arguments for function-like macro invocation 'CPP_PP_FOR_EACH_1'

and I noticed below failure, the "palette.h" doesn't exist at all

18>C:/TBuild/tdesktop/Telegram/SourceFiles/stdafx.h(123,1): fatal error C1083: Cannot open include file: 'styles/palette.h': No such file or directory

for this:
15>C:\TBuild\tdesktop\Telegram\ThirdParty\range-v3\include\range/v3/detail/config.hpp(223,1): fatal error C1189: #error:  range-v3 requires Visual Studio 2019 with the /std:c++17 (or /std:c++latest) /permissive- and /experimental:preprocessor options. (compiling source file C:\TBuild\tdesktop\Telegram\lib_lottie\lottie\lottie_frame_renderer.cpp)

I tried to manually put the compile options in the project, but still see this failure.

does anyone know what's wrong?

My VS version:
Microsoft Visual Studio Enterprise 2019
Version 16.5.1

Windows 10 version:
Microsoft Windows [Version 10.0.18363.836]

**Comment by john-preston** [comment]
@sky4nvcoder Try updating VS to 16.6.0

**Comment by TeleFan777** [comment]
@sky4nvcoder can you clarify the hash of the commit which you can try to build?

**Comment by fynxiu** [comment]
@sky4nvcoder 
You could use '/experimental:preprocessor' instead of '/Zc:preprocessor'
