### ISSUE TITLE
[Feature Request] Pick up system dictionaries

### ISSUE THREAD

**Issue by WhyNotHugo** [telegramdesktop/tdesktop#7960]
### Is your feature request related to a problem?

I'm trying to set up spell checking. I'm bilingual, speaking English (GB) and Spanish (AR).
I've these dictionaries installed in my system, and apps pick them up just fine.

Telegram doesn't pick up system dictionaries, and is also missing "Spanish (AR)" in its builtin dictionary list. Plain "Spanish (ES)" is way too different, since all verbs are conjugated different amongst many other differences (while both languages are mutually intelligible, they're way too different).

### Describe the solution you'd like

Pick up system dictionaries. The dictionary package actually provides files in the following locations, and everything seems to pick them up (e.g.: Vim, Firefox, Chrome, LibreOffice, etc).

```
/usr/share/hunspell/es_AR.aff
/usr/share/hunspell/es_AR.dic
/usr/share/myspell/dicts/es_AR.aff
/usr/share/myspell/dicts/es_AR.dic
/usr/share/qt/qtwebengine_dictionaries/es_AR.bdic
```

Picking up system-installed dictionaries would also prevent me from having to install each dictionary twice -- once for every other app, and a second time for telegram (I've 4 languages I frequently use).

### Describe alternatives you've considered

I'm not sure where the built-in dictionaries are fetched from, maybe including es_ar would be an option too (are these fetch from a source you guys control, or a third party service? I'm not sure if adding dictionaries is trivial/possible).

**Comment by ilya-fedin** [comment]
First spellcheck implementation was using system dictionaries and was very unstable.
https://github.com/telegramdesktop/tdesktop/issues/7095
https://github.com/telegramdesktop/tdesktop/issues/7107
https://github.com/telegramdesktop/tdesktop/issues/7039
https://github.com/telegramdesktop/tdesktop/issues/7140
https://github.com/telegramdesktop/tdesktop/issues/7172
https://github.com/telegramdesktop/tdesktop/issues/7199
https://github.com/telegramdesktop/tdesktop/issues/7204
https://github.com/telegramdesktop/tdesktop/issues/7205
https://github.com/telegramdesktop/tdesktop/issues/6983

**Comment by WhyNotHugo** [comment]
Oh, I can imagine it's a pain to support systems that vary so much (especially on platform where packagers don't collaborate much users have to use upstream binaries).

Is loading system dictionaries but using builtin spellchecker an option?

What would the process be to get `es_AR` into the builtin dictionaries otherwise?

**Comment by ilya-fedin** [comment]
> Is loading system dictionaries but using builtin spellchecker an option?

Probably not. But you can compile tdesktop with `-DDESKTOP_APP_USE_ENCHANT=ON` and the old implementation will be used.

> What would the process be to get `es_AR` into the builtin dictionaries otherwise?

As far as I know, one of the core devs should upload the dictionary to some cloud...
