### ISSUE TITLE
Wrong date and time in filenames when saving

### ISSUE THREAD

**Issue by m-ehsan** [telegramdesktop/tdesktop#7963]
### Steps to reproduce
1. Try to save a "voice message" or "video message" or a "video" from a chat
2. When the save dialog pops up, the default name for the file would be audio_[Current DateTime] or doc_[Current DateTime] or video_[Current DateTime]

### Expected behaviour
It is expected that the default filename to contain the **DateTime when it was originally posted**.

### Actual behaviour
The default filename in the save dialog contains current date and time.

This problem once was true for saving photos for a period of time but it has been resolved thankfully.

### Configuration
**Operating system:** Windows 10

**Version of Telegram Desktop:** 2.1.6

**Used theme**:

**Comment by ilya-fedin** [comment]
#4951

**Comment by ilya-fedin** [comment]
What difference?

**Comment by m-ehsan** [comment]
by default saving photos uses the original time that they were sent as filename, but for voice messages the current time is used as filename.

**Comment by ilya-fedin** [comment]
> by default saving photos uses the original time that they were sent as filename

that's false, they named with the time they're downloaded

**Comment by m-ehsan** [comment]
> > by default saving photos uses the original time that they were sent as filename
> 
> that's false, they named with the time they're downloaded

I got it now. The file is named with the download time, except for one case... when viewing a photo in  "Media viewer" and using save as option from context menu. In that case file name contains the time when the photo was sent. And that makes sense because you can either save a photo with it's original time or the download time.
