### ISSUE TITLE
Messages sent by users are always left aligned

### ISSUE THREAD

**Issue by sachinkumarsingh092** [telegramdesktop/tdesktop#7970]
### Steps to reproduce
1. Open Telegram Desktop.
2. Send a message to another user or bot.

### Expected behaviour
The user's message should be placed on the right side of the chat windows. Others user's messages should be on the left side of the windows.

### Actual behaviour
All the messages are placed on the left side(see the image below).

### Configuration
**Operating system:**
Ubuntu 18.04.4 LTS x86_64

**Version of Telegram Desktop:**
Version 2.1.7

**Installation source (Linux Only)** - the official website / GitHub releases / flatpak / snap / distribution package:
the official website

**Used theme**:
Night

Below is a screenshot of a chat with a telegram bot. But this error is still there when chatting with other users whether in a group or direct messaging.
![Screenshot from 2020-05-30 17-16-12](https://user-images.githubusercontent.com/27863800/83327566-7502c300-a29a-11ea-83a9-d9eb9de0af57.png)

**Comment by Aokromes** [comment]
not a bug, make window smaller or disable adaptative layout on settins -> chat settings.
