### ISSUE TITLE
tdesktop is unusable on tablet mode

### ISSUE THREAD

**Issue by j4hangir** [telegramdesktop/tdesktop#7978]
I have a surface book, and there are two categorically big issues when using Telegram on `tablet mode`, firstly, whenever the touch keyboard slides up Telegram will resize itself weirdly to half-screen, and not only become unresizable, but also impossible to type, since the chat window would become hidden and impossible to activate.

The only way to fix it all is to disable `tablet mode`, use mouse to resize it and finally keyboard to send a message 😞

**Comment by WhyNotHugo** [comment]
Conventional tablets won't let you resize a keyboard, why would you expect that in _tablet mode_?

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/1995
