### ISSUE TITLE
An updater does nothing. Infinite update

### ISSUE THREAD

**Issue by ezdev128** [telegramdesktop/tdesktop#798]
The last time an updater does nothing.
I see 'Update ^' notification at the top-right corner very frequently the last week, I'm doing update but in fact nothing were updated. I did manual update, it says 'the last version' but the next check initiated new update download and again no new version was installed.
No md5 sums changed.

LinuxMint, 64Bit, LMDE MATE Edition

---------------------------------------------

ezdev128@ezdev128-linux:/opt/telegram$ md5sum *
e409dfc16a4ef17f071b8c810576a957  lang_ru.strings
md5sum: tdata: Это каталог
87db589909902d3de03a122c30f97a70  Telegram
b8fe54a77cf929eb499c6ad7430dec3d  Updater
ezdev128@ezdev128-linux:/opt/telegram$ /opt/telegram/Telegram -- %u
libs init..
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 70: non-double matrix element
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 70: non-double matrix element
Fontconfig warning: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 78: saw unknown, expected number
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 70: non-double matrix element
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 70: non-double matrix element
Fontconfig warning: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 78: saw unknown, expected number
ezdev128@ezdev128-linux:/opt/telegram$ libs init..
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 70: non-double matrix element
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 70: non-double matrix element
Fontconfig warning: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 78: saw unknown, expected number
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 70: non-double matrix element
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 70: non-double matrix element
Fontconfig warning: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 78: saw unknown, expected number

ezdev128@ezdev128-linux:/opt/telegram$ md5sum *
md5sum: fontconfig: Это каталог
e409dfc16a4ef17f071b8c810576a957  lang_ru.strings
md5sum: tdata: Это каталог
87db589909902d3de03a122c30f97a70  Telegram
b8fe54a77cf929eb499c6ad7430dec3d  Updater
ezdev128@ezdev128-linux:/opt/telegram$ ls -lah
итого 40M
drwxr-xr-x  5 ezdev128 ezdev128   98 июн  6 03:28 .
drwxrwxrwx 27 ezdev128 ezdev128 4,0K мар 14 01:49 ..
drwxr-xr-x  2 ezdev128 ezdev128 4,0K июн  6 03:28 fontconfig
-rw-r--r--  1 ezdev128 ezdev128  23K янв 18 18:27 lang_ru.strings
drwx------  2 ezdev128 ezdev128   20 дек 24 04:20 tdata
-rwxr-xr-x  1 ezdev128 ezdev128  40M май 27 22:19 Telegram
-rwxr-xr-x  1 ezdev128 ezdev128  38K июн  6 03:28 Updater
ezdev128@ezdev128-linux:/opt/telegram$

**Comment by bil-elmoussaoui** [comment]
well try doing this 
``` sudo chmod +x /opt/telegram ``` 
and then this 
``` 
sudo chown -R $whoami:$whoami /opt/telegram
```
this will fix the permissions for telegram to could update as your application is in ``` /opt/``` and to change files their you will need root permissions.

**Comment by ezdev128** [comment]
@bil-elmoussaoui try reading an above text again ;)
```
ezdev128@ezdev128-linux:/opt/telegram$ ls -lah
итого 40M
drwxr-xr-x 5 ezdev128 ezdev128 98 июн 6 03:28 .
drwxrwxrwx 27 ezdev128 ezdev128 4,0K мар 14 01:49 ..
drwxr-xr-x 2 ezdev128 ezdev128 4,0K июн 6 03:28 fontconfig
-rw-r--r-- 1 ezdev128 ezdev128 23K янв 18 18:27 lang_ru.strings
drwx------ 2 ezdev128 ezdev128 20 дек 24 04:20 tdata
-rwxr-xr-x 1 ezdev128 ezdev128 40M май 27 22:19 Telegram
-rwxr-xr-x 1 ezdev128 ezdev128 38K июн 6 03:28 Updater
ezdev128@ezdev128-linux:/opt/telegram$ 
```
If you see, an user ezdev128 has all permissions to /opt/telegram, no need to have root permissions to change any file inside this dir.

Also, this works during some months ago, nothing was changed.

**Comment by luvemil** [comment]
I had a similar problem: the updater did nothing. Moving both Telegram and Updater to my home folder solved the problem (however it was some time ago, so things might have changed in the meanwhile).

**Comment by auchri** [comment]
Duplicate #555
