### ISSUE TITLE
English spell check malfunction with contractions.

### ISSUE THREAD

**Issue by alisnichenko** [telegramdesktop/tdesktop#7980]
### Steps to reproduce
1. Open any chat on Telegram Desktop.
2. Type any English contraction, such as *aren't*, *isn't*, *should've*.
3. Observe the red underline appear under a portion of the contraction.

### Expected behaviour
Proper recognition of the English contraction.

### Actual behaviour
Spell check underlines in red a portion of the contraction: 

![image](https://user-images.githubusercontent.com/43276271/83425445-b494f080-a3fb-11ea-926a-093993a3a8f6.png)

### Configuration
**Operating system:**
Ubuntu 20.04 LTS

**Version of Telegram Desktop:**
Version 2.0.1

**Installation source (Linux Only)** - the official website / GitHub releases / flatpak / snap / distribution package:
Downloaded from the official website and installed using `dpkg`.

**Used theme**:
Default.

<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by Aokromes** [comment]
> **Version of Telegram Desktop:**
> Version 2.0.1
> 
> **Installation source (Linux Only)** - the official website / GitHub releases / flatpak / snap / distribution package:
> Downloaded from the official website and installed using `dpkg`.

latest telegram desktop for linux environment is 2.1.7 downloaded from official website.

**Comment by ilya-fedin** [comment]
> Downloaded from the official website and installed using `dpkg`.

How could you install a tarball with a binary with dpkg?

**Comment by alisnichenko** [comment]
I apologize for such a long reply. I don't remember why I said dpkg. In any case, I had to reinstall Telegram from [this](https://desktop.telegram.org/) link. Current version is 2.1.12 and no problems with the spellchecker. Thank you.
