### ISSUE TITLE
windows10 需要使用新应用以打开此 tg 链接

### ISSUE THREAD

**Issue by piaoyun** [telegramdesktop/tdesktop#7981]
![tY7AgA.jpg](https://s1.ax1x.com/2020/06/02/tY7AgA.jpg)
![tY7EjI.jpg](https://s1.ax1x.com/2020/06/02/tY7EjI.jpg)
![tY7k3d.jpg](https://s1.ax1x.com/2020/06/02/tY7k3d.jpg)

**Comment by ilya-fedin** [comment]
No one here knows chinese. Please, english only.

**Comment by kouhe3** [comment]
@ilya-fedin 
He means "tg://" can't be opened

**Comment by ilya-fedin** [comment]
did he try to type `registertg` in settings?

**Comment by Aokromes** [comment]
@piaoyun

**Comment by Aokromes** [comment]
1 month without answer, if this bug is still valid open a new ticket.
