### ISSUE TITLE
Telegram changes its window size after restart

### ISSUE THREAD

**Issue by Nufirdy** [telegramdesktop/tdesktop#7984]
### Steps to reproduce
1. Quit and reopen telegram app

### Expected behaviour
I expect telegram to be on the same place where it was when reopening it

### Actual behaviour
Its lower and right border shrink a little but enough to bother me a lot
https://puu.sh/FRPRz/fc4dbb5680.mp4
### Configuration
**Operating system:**
Windows 10
**Version of Telegram Desktop:**
2.1.6 
**Used theme**:
Night

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/1189
