### ISSUE TITLE
Linux Application Icon Actions

### ISSUE THREAD

**Issue by JayXT** [telegramdesktop/tdesktop#7987]
### Is your feature request related to a problem?
Many Linux apps for quite a while relied on Ayatana Indicator API to support application system tray icons. But because the project was deprecated since 2014, some desktop environments, e.g. GNOME, Pantheon stopped support for this API. The situation will exacerbate in the future.
Consequently Telegram Desktop tray icon is often not displayed on some Linux distributions and such options as "Close Telegram" and "Disable/Enable notifications" aren't available.

### Describe the solution you'd like
One way to deal with this limitation is to add support  for [additional application actions](https://specifications.freedesktop.org/desktop-entry-spec/desktop-entry-spec-latest.html#extra-actions) as recommended by freedesktop specification. Such approach allows to make application launchers that support context menu actions and as a result Telegram could have "Close Telegram" and "Disable/Enable notifications" menu items.

### Additional context
One [example](https://medium.com/elementaryos/developer-tips-backgrounding-system-integration-31c1f7226606) of the additional application actions is provided by elementary OS (QuickLists page section). 
Here are several examples of this feature implemented by other apps:

![image](https://user-images.githubusercontent.com/8045344/83634113-ab965180-a5aa-11ea-95f0-62f0a059dda4.png)

![image](https://user-images.githubusercontent.com/8045344/83634062-97525480-a5aa-11ea-8dfc-0350f6b6a2c2.png)

![image](https://user-images.githubusercontent.com/8045344/83634249-df717700-a5aa-11ea-8795-a9e076fa9ead.png)

![image](https://user-images.githubusercontent.com/8045344/83634309-fa43eb80-a5aa-11ea-8a5f-0e3692b5bf50.png)

**Comment by ilya-fedin** [comment]
> and such options as "Close Telegram" and "Disable/Enable notifications" aren't available.

If there are no tray icon, tdesktop closes by close button

**Comment by ilya-fedin** [comment]
> But because the project was deprecated since 2014, some desktop environments, e.g. GNOME, Pantheon stopped support for this API.

There are well-supported StatusNotifierItem API that can be used by these environments.
GNOME has a lot of extensions to restore tray icon support.

**Comment by JayXT** [comment]
> > and such options as "Close Telegram" and "Disable/Enable notifications" aren't available.
> 
> If there are no tray icon, tdesktop is closing by close button

Oh,I didn't know that. That's clever.

**Comment by ilya-fedin** [comment]
> One way to deal with this limitation is to add support for [additional application actions](https://specifications.freedesktop.org/desktop-entry-spec/desktop-entry-spec-latest.html#extra-actions) as recommended by freedesktop specification.

This api is very ugly and requires adding of command line arguments. How do you will feel if any malware script in your system will be able to change telegram settings?

**Comment by JayXT** [comment]
> > But because the project was deprecated since 2014, some desktop environments, e.g. GNOME, Pantheon stopped support for this API.
> 
> There are well-supported StatusNotifierItem API that can be used by these environments.
> GNOME has a lot of extensions to restore tray icon support.

The problem with extensions is that their compatibility is usually broken after each GNOME release. As for Pantheon, this workaround isn't possible:( By the way, elementary HID provides an interesting take on system tray role:
https://elementary.io/docs/human-interface-guidelines#system-indicators

> > One way to deal with this limitation is to add support for [additional application actions](https://specifications.freedesktop.org/desktop-entry-spec/desktop-entry-spec-latest.html#extra-actions) as recommended by freedesktop specification.
> 
> This api is very ugly and requires adding of command line arguments. How do you will feel if any malware script in your system will be able to change telegram settings?

I see some validity in your vision. I'm not sure if the API is ugly, but I know that Telegram Desktop already supports [command line interface](https://github.com/telegramdesktop/tdesktop/wiki/Command-Line-Switches), and adding one additional option to enable or disable notifications shouldn't be an issue in that case, is it correct or I'm missing something?
Besides, if the system is infected with malware disabling notifications doesn't look like the biggest problem to think of.

**Comment by JayXT** [comment]
Unfortunately, the underlying limitation hasn't been resolved yet: if support for the out-of-date Ayatana Indicator API is stopped by Linux distribution or DE, there's no quick way to disable all notifications from the app icon or Telegram Desktop application itself.

**Comment by ilya-fedin** [comment]
> if support for the out-of-date Ayatana Indicator API is stopped by Linux distribution or DE

Telegram doesn't use that API, it uses the actual StatusNotifierItem API. If some DE doesn't want to support that API, it's their choice, there's no plan to add support for application actions, sorry. I recommend to switch to a DE with any tray support since the lack of tray support is considered as a platform issue rather than a platform design choice here.
