### ISSUE TITLE
No areas for sending media as file or "as is" in Scheduled Messages

### ISSUE THREAD

**Issue by MasterGroosha** [telegramdesktop/tdesktop#7989]
### Steps to reproduce
1. Drag file above opened Scheduled Messages screen

### Expected behaviour
Two areas for sending media different ways should be shown (for example):
![изображение](https://user-images.githubusercontent.com/2780044/83661570-fc1fa600-a5ce-11ea-93bf-3e11b843b3d5.png)

### Actual behaviour
Nothing happens when you do in in Scheduled Messages screen
![изображение](https://user-images.githubusercontent.com/2780044/83661618-0a6dc200-a5cf-11ea-9e60-0770bd1dc91b.png)

As a workaround, one can drag and drop file into the input field, which does work, but it's still just a workaround, rather than a solution.

### Configuration
**Version of Telegram Desktop:** 2.1.8 beta

**Comment by Neurotoxin001** [comment]
You can drag&drop it here:
![image](https://user-images.githubusercontent.com/39812401/83946817-cb807c00-a81b-11ea-9ed5-c78ee01a9f9b.png)

But yeah, there is must be a more space.

Also after you enter text in that field and drop media and schedule it — text doesn't clear after that from this "write a message" box.

**Comment by ilya-fedin** [comment]
https://github.com/telegramdesktop/tdesktop/commit/42a22862304be04d0b19bd811ef16aa4eaa71ce6
