### ISSUE TITLE
[Feature request] Image panning and zooming

### ISSUE THREAD

**Issue by NXij** [telegramdesktop/tdesktop#799]
The current fullscreen way of viewing images lacks panning and zooming options.

Idea:
Space bar - Toggle between 100% (native image size) zoom 
Scroll wheel - Zoom the image in and out
Mouse 1 dragging - Panning

**Comment by Aokromes** [comment]
+1

**Comment by mbnoimi** [comment]
+1

**Comment by squirrelboot** [comment]
+1

**Comment by auchri** [comment]
You can zoom with ctrl and +/i, panning works with the left mouse button :)
