### ISSUE TITLE
Mark as read has been removed

### ISSUE THREAD

**Issue by thecneu** [telegramdesktop/tdesktop#7990]
The mark as read button has been removed and replace for the New Folder button when right clicking on chats on the osx app. Has this functionality been moved to a different spot on the desktop app?

**Comment by RememberTheAir** [comment]
What app version are you using?

**Comment by kifirkin** [comment]
I'm using version `v2.1.12 - 17.06.20`  and as I see, `mark as read` button disappeared when clicking on folders

**Comment by Aokromes** [comment]
it's there for me:
https://i.imgur.com/qY36lSE.png

**Comment by Aokromes** [comment]
no answer after 2 months, closing.
