### ISSUE TITLE
[Question] How I can share file to Telegram UWP using command line?

### ISSUE THREAD

**Issue by xmha97** [telegramdesktop/tdesktop#7992]
Hello,
How I can share a file with Telegram UWP using the command line?
I can share a file with Telegram Win32 easily using below command:
```
%Appdata%\Telegram Desktop\Telegram.exe -sendpath "C:\1.mp4"
```
But I can't share a file with Telegram UWP.
```
explorer shell:AppsFolder\TelegramMessengerLLP.TelegramDesktop_t4vj0pshhgkwm!Telegram.TelegramDesktop.Store -sendpath "C:\1.mp4"
```
```
%LocalAppData%\Microsoft\WindowsApps\Telegram.exe -sendpath "C:\1.mp4"
```
```
tg://msg_url?sendpath="C:\1.mp4"
```
```
tg://send?path="C:\1.mp4"
```
Please help me before closing this issue.
Thanks

**Comment by Aokromes** [comment]
i don't think such thing is doable.

**Comment by xmha97** [comment]
If Telegram UWP create below file, I can start telegram with parameters:
%LocalAppData%\Microsoft\WindowsApps\Telegram.exe
For example, you can run Windows Terminal with parameters:
%LocalAppData%\Microsoft\WindowsApps\wt.exe -d C:\
I need this feature:
%LocalAppData%\Microsoft\WindowsApps\Telegram.exe -sendpath "C:\1.mp4"

**Comment by ilya-fedin** [comment]
> i don't think such thing is doable.

\+1, I think that UWP sandbox doesn't allow to pass arguments
