### ISSUE TITLE
Wide chat option does not work on Windows 10

### ISSUE THREAD

**Issue by c-schmitz** [telegramdesktop/tdesktop#7993]
### Steps to reproduce
1.  Install Telegram Desktop Client on Windows 10
2.  Check on any existing chat.
3.  Notice that all chat messages only use 25 % of screen width even though 'Adaption layout for wide screens' is activated in settings. ( actually it does not make any difference if it is activated)

### Expected behaviour
I expect the chat window messages to use as much screen estate as possible.

### Actual behaviour
Width of chat messages is at about 25 %.

### Configuration
**Operating system:**
Windows 10 - fully updated

**Version of Telegram Desktop:**
2.1.6

**Used theme**:
Standard - Night mode

![wide_mode](https://user-images.githubusercontent.com/1364282/83746082-d93cd280-a65e-11ea-90cb-5abda1006e89.png)

**Comment by MasterGroosha** [comment]
This is expected behaviour. Only messages containing monospace font have variable bubble width.

**Comment by c-schmitz** [comment]
Why would you force linebreaks even though there is enough space? What is the reasoning behind this? 
At a minimum I would expect a setting  for this.

**Comment by ilya-fedin** [comment]
>     3\. Notice that all chat messages only use 25 % of screen width even though 'Adaption layout for wide screens' is activated in settings. ( actually it does not make any difference if it is activated)

It moves all the messages to the left

**Comment by c-schmitz** [comment]
> > 1. Notice that all chat messages only use 25 % of screen width even though 'Adaption layout for wide screens' is activated in settings. ( actually it does not make any difference if it is activated)
 
> It moves all the messages to the left and, as I can see on your screenshot, the option works

When that option is off the screen looks exactly the same  (so it makes no sense to post another screenshot) except for the date labels being aligned in the middle.

**Comment by ilya-fedin** [comment]
> When that option is off the screen looks exactly the same (so it makes no sense to post another screenshot) except for the date labels being aligned in the middle.

When this option is disabled your posts will be in the right side, when enabled - in the left side, just like posts of other people in the group

**Comment by c-schmitz** [comment]
Ah ok, I understand that part now - though the setting should probably be named 'Left-align all messages' because that is what it is doing. 

I still don't understand why the posts would not use more screen estate in general, because that is what I expected from that option.
I can understand if you want to keep left/right alignment to distinguish between your posts and others. But that would be also fine at 90% of window width (or a configurable setting).

**Comment by ilya-fedin** [comment]
> I still don't understand why the posts would not use more screen estate in general, because that is what I expected from that option.

I just leave it here
https://github.com/telegramdesktop/tdesktop/pull/7822

**Comment by c-schmitz** [comment]
All linked issues are closed by now (without resolve) so it would be good to keep this open.

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/2060
