### ISSUE TITLE
🐞: Is not the word "analytics" in the dictionary?

### ISSUE THREAD

**Issue by joe733** [telegramdesktop/tdesktop#7998]
## Steps to reproduce
1. Type the word analytics.
2. It is underlined in red.

## Expected behaviour
I think Analytics is pretty much an [English word](https://duckduckgo.com/?q=is+analytics+a+word&t=canonical&atb=v203-1&ia=definition). 

## Actual behaviour
Analytics is underlined in red.

## Configuration
**Operating system:**
elementary OS 5.1.4 Hera

**Version of Telegram Desktop:**
2.1.8 Beta

**Installation source (Linux Only)** 
AppImage

**Used theme**:
Night

<details><summary><b>Screenshot</b>:</summary>

![photo_2020-06-05_16-08-31](https://user-images.githubusercontent.com/38415384/83867880-bdf9c200-a747-11ea-9073-c0654a572d03.jpg)

</details>

**Comment by Aokromes** [comment]
no problem on windows, maybe elementary  bug.

**Comment by joe733** [comment]
Yeah, looks like that. Shows error even on Firefox, sorry to bother you.
> Closing as <kbd>out-of-scope</kbd>.

**Comment by ilya-fedin** [comment]
> no problem on windows, maybe elementary bug.

On Linux Hunspell dictionaries are used, they're provided by libreoffice AFAIK
https://cgit.freedesktop.org/libreoffice/dictionaries/tree/
