### ISSUE TITLE
Change cache folder

### ISSUE THREAD

**Issue by VadVergasov** [telegramdesktop/tdesktop#7999]
I what to store all Telegram data, not on drive C:/ , but changing download folder in settings doesn't change folder for the cache.

Add another option to change the location for the cache.

**Comment by xvitaly** [comment]
Use portable version. It will store `tdata` in its directory.

**Comment by VadVergasov** [comment]
Not so elegant solution, but it works.

**Comment by ilya-fedin** [comment]
There are also `-workdir` commandline argument
