### ISSUE TITLE
[bug] No systray icon in KDE Linux

### ISSUE THREAD

**Issue by javielillo** [telegramdesktop/tdesktop#80]
I use the latest KDE version of Ubuntu 14.04 (Kubuntu) and if I run Telegram I see there is no icon in the system tray like in WIndows. Consequently, if I close the window I close the program and of course I don't receive notifications.

Tested in 2 different computers with the same Kubuntu release.

**Comment by edubxb** [comment]
+1

I use GNOME 3

**Comment by Streppel** [comment]
:+1:

**Comment by JackHack96** [comment]
:+1:

**Comment by koukos** [comment]
Yes the ability to run it as service which remains active in the system tray would be great 

:+1:

**Comment by knetor** [comment]
i feel slighty insulted and recommend the telegram plugin for pidgin... nice tray icon it has and stuff ;>

**Comment by telegramdesktop** [comment]
Tray icon using libappindicator with fallback to gtk_status_icon, if libappindicator is not installed, will be added in 0.7.7. I don't know actually, will it work on your system.

**Comment by JackHack96** [comment]
@telegramdesktop: I've just updated to 0.7.7 and I have libappindicator installed, but no tray icon nor unity message counter :(
I'm using Ubuntu 14.04 64bit and Unity 7.2

**Comment by ItachiSan** [comment]
Works fine for me too!
I'm on ArchLinux (Antergos) with Gnome 3.14.2 updated to latest version, I'm using TopIcons (but works even without it, but
![schermata del 2015-01-17 12 24 45](https://cloud.githubusercontent.com/assets/1223421/5788655/466730f4-9e44-11e4-9a56-f83fb0688837.png)
 the icon is cropped)

**Comment by koukos** [comment]
For KDE it also requires libappindicator3-1 (In debian 8.0) which is the GTK 3 version in addition to libappindicator1. It seems to be working quite nice so far. Does anyone knows how can we start the application minimized to system tray? Is there any option to be included with the command so i can add to my startup script. Thanks a lot

**Comment by jalcine** [comment]
@JackHack96 This is about KDE using Plasma, not about Ubuntu's Unity. Odd that it doesn't work though.

**Comment by JackHack96** [comment]
@jalcine Yes I know. But I'm using different DEs on different computers, and since my main PC is using Unity I've got it working there first, then I've tried the others. My IT teacher is using Kubuntu with KDE Plasma and he's using the latest version of Telegram without libappindicator-dev :)

The only thing I miss is the startup option. I've added Telegram to the startup applications, but obviously it doesn't run minimized and I have to close it every time...

**Comment by telegramdesktop** [comment]
I've added some -startintray commandline argument, I'm not sure it does exactly what you want, but it minimizes the window on start.

**Comment by koukos** [comment]
That was exactly what was needed! :) And it indeed works.
Thanks a lot.

**Comment by Kernell** [comment]
> There is no support for systray icon in ubuntu and OS X right now
This is wrong. KDE supports this function perfectly.
For example, this can be seen in Wine, running Telegram for Windows through it and you will see your application's icon in the system tray.

**Comment by ItachiSan** [comment]
Using the *-startintray* option for me makes the app start normally, not getting in the traybar.
I'm on ArchLinux, using GNOME 3.
**Notice:** The app after being started has working trayicon; the just *starting-in-tray* is not working.

**Comment by rugebiker** [comment]
after installing  libappindicator and the devel libraries,., everything works awesome :) now it would be more awesome if you could open telegram desktop just by double clicking in the systray icon, and not having to right-click -> open telegram :)

**Comment by rugebiker** [comment]
after upgrading to kde plasma 5, there is no tray icon anymore =/

**Comment by KenetJervet** [comment]
Hi, I'm still having this issue. I'm running Arch Linux KDE Plasma 5. I've installed all the libraries that look related:
lib32-libappindicator-gtk2
lib32-libappindicator-gtk3
lib32-libappindicator-sharp
lib32-sni-qt
libappindicator-gtk2
libappindicator-gtk3
libappindicator-sharp
perl-gtk2-appindicator
sni-qt

**Comment by varlesh** [comment]
KDE 5 - No tray icon. Please fix it.

**Comment by Sidorr** [comment]
Please, fix tray icon in KDE5

**Comment by jalcine** [comment]
Please stop commenting on this issue -- it's been closed. Open a new issue pertaining to complications with using KDE5. I use it myself and plan to open an issue about it though I think the complication isn't with Telegram but more-so with how KDE's implementation non-KDE system tray items.

Thanks!

**Comment by SanKro** [comment]
thers no KDE5 -> Plasma 5!
however... you all should try http://aseman.co/en/products/cutegram/ .. because cutegram is a much better telegram client then this one here

**Comment by jalcine** [comment]
@SanKro that's dope; but that doesn't really fix the problem at hand :8ball:

**Comment by ErkanMDR** [comment]
+1
Arch Linux with GNOME 3

**Comment by EliaGeretto** [comment]
@ErkanMDR In Gnome the problem should be different. The Qt tray icon doesn't work but, if you install "libappindicator" from AUR, the icon should appear.
