### ISSUE TITLE
High pitched sound after using microphone 

### ISSUE THREAD

**Issue by Qik000** [telegramdesktop/tdesktop#8001]
### Steps to reproduce
1. Connect to a call or try to record a voice message
2. Notice the sound becomes high pitched
3. Opening pavucontrol fixes this

### Expected behaviour
Telegram shouldnt cause the sound ot become high pitched

### Configuration
**Operating system:**
Linux Ubuntu 18.04.4 LTS
Behringer umc204hd audio interface

**Version of Telegram Desktop:**
2.1.7

**Installation source (Linux Only)** - the official website / GitHub releases / flatpak / snap / distribution package: official website, also tried the version from snapd, same results

**Used theme**: Dark

**Comment by ilya-fedin** [comment]
#1548
