### ISSUE TITLE
[Feature Request] New chat setting: send emoji small

### ISSUE THREAD

**Issue by elw00d** [telegramdesktop/tdesktop#8004]
### Is your feature request related to a problem?
Currently there is no way to enforce emoji size on remote (receiver) side. I think there are many people want to control this, because defaults are not so good for readability, but vast majority of people doesn't change their settings.

### Describe the solution you'd like
I want an option like "send all emoji in small size" that can be switched on sender side. If option is on, all emojis sent by me will be displayed small for all receivers.

### Describe alternatives you've considered
Alternative (or/and the way to implement this) is: introduce additional syntax to control this behaviour. For example, `:hmm:small:` instead of `:hmm:`.

**Comment by Aokromes** [comment]
i think this must be suported by api.

**Comment by RememberTheAir** [comment]
@Aokromes why? :thinking: it's just graphical stuff

**Comment by Aokromes** [comment]
"Currently there is no way to enforce emoji size on remote (receiver) side."

**Comment by RememberTheAir** [comment]
Right, misread the OP. Definitely an API issue

**Comment by 23rd** [comment]
#6846.
