### ISSUE TITLE
Telegram goes on top on every notification (linux)

### ISSUE THREAD

**Issue by Behoston** [telegramdesktop/tdesktop#8006]
### Steps to reproduce
1. Run telegram
2. Run sth else, like web browser
3. Wait for notification

### Expected behaviour
Notification

### Actual behaviour
Telegram window goes on top of all other windows

### Configuration
**Operating system:** Linux Mint 19.3 Cinnamon

**Version of Telegram Desktop:** https://desktop.telegram.org/changelog#v-2-1-10-05-06-20

**Installation source (Linux Only)** - the official website / GitHub releases / flatpak / snap / distribution package: I don't remeber, probably downloaded from website.

**Used theme**: default with night mode

**Comment by Aokromes** [comment]
not a bug, disable setting, it's somewhere on notifications iirc.

**Comment by Behoston** [comment]
THX:
![obraz](https://user-images.githubusercontent.com/7823689/83945318-25784600-a80a-11ea-9792-2cbe513eea92.png)
why this stupid option becomes default enabled?

**Comment by amirsabeghi** [comment]
You can disable it in mint from:
setting => windows => behavior => (enable) Prevent windows which require attention from stealing focus
