### ISSUE TITLE
Mouse scroll wheel can't work if mouse pointer is on Telegram Desktop window scroll bar.

### ISSUE THREAD

**Issue by andrewwutw** [telegramdesktop/tdesktop#8007]
In most cases, if mouse pointer is on the chat window, using the mouse scroll wheel can scroll the chat window.

But, if mouse pointer is over the scroll bar of chat window, mouse scroll wheel can't work.

### Steps to reproduce
1. Move mouse pointer onto the scroll bar of chat window. (see the red circle)

![3](https://user-images.githubusercontent.com/4443713/83946225-fed60180-a841-11ea-94fb-62ad6940d7d9.png)

2. Use the mouse scroll wheel, or use MacBook touchpad two-finger scrolling.

### Expected behaviour

The window should be scrolled.

### Actual behaviour

The window is not scrolled.

### Configuration
**Operating system:**

Windows 7

macOS 10.14.6

**Version of Telegram Desktop:**

2.1.10  (Both Windows and macOS)

**Comment by andrewwutw** [comment]
PS : If mouse pointer is not on the scroll bar (see the red circle), scroll wheel can work.

![4](https://user-images.githubusercontent.com/4443713/83946413-427d3b00-a843-11ea-8698-5d0d15bf1019.png)

**Comment by shooash** [comment]
This issue shouldn't be closed. On Windows 10 I am unable to scroll chats and contacts lists with the mouse even after I select any contact or message. I can still scroll the windows by the scrollbar and with the keyboard arrows. I've had this issue for months. Now it's on ver. 2.4.11 beta

**Comment by ilya-fedin** [comment]
> This issue shouldn't be closed

Are you sure you're writing in the right issue? This issue is about scrolling with the wheel when the pointer is on scrollbar, not about scrolling at all.

**Comment by shooash** [comment]
> Are you sure you're writing in the right issue?

I guess you're right. Though I have the scrollbar wheel issue as well. Should I open another bug report for scrolling issues as they seem to be related?

**Comment by ilya-fedin** [comment]
> Should I open another bug report for scrolling issues as they seem to be related?

They're not related, scrolling on scrollbar is impossible since that's how the widget is implemented (this is intended and probably won't be changed). So if you won't open another issue, your problem will be just ignored since there's no known issues with scroll with the wheel.
