### ISSUE TITLE
[Feature Request] multi account for desktop

### ISSUE THREAD

**Issue by smaznet** [telegramdesktop/tdesktop#8008]
Please add multi account handling like telegram android and ios version 
i know there is a way and that is setting --workdir but it isn't good

please add a simple way to add multi account to telegram deskop

**Comment by MasterGroosha** [comment]
Duplicate of #4987 #4261 #4328 #4447 #4448 #4744 #4889 #5269 #5421 and #7134.
Is it so difficult to just type "Multi" in Search field?

**Comment by smaznet** [comment]
No it's no difficult i just created new to remember that 😅
