### ISSUE TITLE
Minor Bug - Double dash turns into long dash

### ISSUE THREAD

**Issue by luisalvarado** [telegramdesktop/tdesktop#801]
When sharing information like the following over the Ubuntu Telegram app it changes the double dashes into one long dash:

- ORIGINAL -
mysql --user=UserTest --password=Password123 --database=MyDataInfo --host=mysite.com --connect-timeout=30

- RESULT -
mysql —user=UserTest —password=Password123 —database=MyDataInfo —host=mysite.com —connect-timeout=30

**Comment by peterfarrell** [comment]
We are seeing this behavior as well on Ubuntu.  Makes sharing command line stuff very difficult  with a team.

**Comment by luisalvarado** [comment]
Thanks for confirming @peterfarrell . Am just glad and impressed on how well the developers take care of the issues and feature requests. Just an amazing job really. Unique to how typical developers handle requests of this type. Most probably this issue will be fixed real soon.

**Comment by auchri** [comment]
Duplicate #803
