### ISSUE TITLE
Massive Impersonation Security Vulnerability

### ISSUE THREAD

**Issue by Yowlen** [telegramdesktop/tdesktop#8011]
### Expected Behavior
Contacts are able to be confirmed via their username and/or avatar before being added to Telegram's contact list. Additionally, contacts aren't notified we're on the platform unless we explicitly confirm them first. Maybe additional secondary behavior of automatic notifications enabled via the settings, but confirmation still has to be manual to prevent fraudulent accounts from impersonating someone.

### Actual Behavior
Contacts are automatically matched based on phone number and automatically added regardless of consent from either user. Worse, contacts automatically use the avatar and name from my phone.

I've encountered two accounts that, after cleaning up old contacts on my phone, removing them from Telegram resulted in vastly different usernames and avatars from before, indicating they were not the person Telegram told me they were. Luckily, we hadn't communicated at all, but unluckily, if they're hostile, they know who I am while I have no idea who they are. (I panicked and deleted my account due to the scare it gave me. I do not remember the offending account names and therefore cannot provide them.)

Three changes need to happen to prevent this:

1. Disable that "X has joined Telegram" thing by default.

2. Don't automatically add them to Telegram's contacts.

3. Only use the avatar/username provided by the account creator at first. Once the user confirms to add them, only then should you use the custom avatar/name they have stored for that person. An option should also be provided to disable this functionality or maybe even have it disabled by default like with number 1.

### Configuration
**Operating system:** Android

**Version of Telegram:** 6.1.1 (assumed for contact deletion), as well as an unknown number of earlier versions going back at least 6 months for spoofing the account name/avatar

**Installation source:** F-Droid

**Secondary app:** Xubuntu, .deb format, same number of unknown versions going back several months

Secondary app is mentioned because it was displaying the same avatars and names as my phone, telling me it lifted it from there and stored it on the servers to keep things consistent. (Thanks for telling me ahead of time on that one too... :/ ) Anyway, this means there's no way to tell when someone's spoofing the account like this regardless of which platform is used so long as the mobile app has been used at least once and contact permissions granted.

**Comment by Aokromes** [comment]
i don't think this belongs here instead to in-app support application, even more when you state android client.

**Comment by Yowlen** [comment]
I can't do in-app stuff because I don't have an account anymore. Please actually read before commenting if you plan on being helpful.

**Comment by RememberTheAir** [comment]
@Yowlen bring this to security@telegram.org, what you're describing is the intended behaviour, Telegram is designed to work like that platform-wise and tdesktop is consistent with that

**Comment by Yowlen** [comment]
That's the problem. The intended behavior is making it impossible for people to detect spoof accounts. Are y'all even reading what I'm writing?

Look, I'm done trying to argue with y'all. If y'all don't wanna fix it, that's on y'all's head. And unfortunately, it'll be your userbase that pays the price. Do what you want, but I'm not gonna be participating in this report anymore because y'all are insistent on asking dumbass questions that are literally already answered in the original report.
