### ISSUE TITLE
Telegram won't start: QSystemTrayIcon::setVisible: No Icon set

### ISSUE THREAD

**Issue by GabTux** [telegramdesktop/tdesktop#8012]
Before last update, everything worked fine. Now the telegram won't start.

### Steps to reproduce
snap run telegram-desktop

### Expected behaviour
Telegram should start.

### Actual behaviour
It appears it is stuck in infinite loop.

### Configuration
**Operating system:**
:~$ uname -a
Linux GabossPC 5.6.0-2-amd64 #1 SMP Debian 5.6.14-1 (2020-05-23) x86_64 GNU/Linux

**Version of Telegram Desktop:**
:~$ snap list telegram-desktop
Name              Version  Rev   Tracking       Publisher         Notes
telegram-desktop  2.1.10   1666  latest/stable  telegram.desktop  -

**Installation source (Linux Only)** - the official website / GitHub releases / flatpak / snap / distribution package:
snap

<details><summary><b>Logs</b>:</summary>

:~$ snap run telegram-desktop
Qt: Session management error: Authentication Rejected, reason : None of the authentication protocols specified are supported and host-based authentication failed

(process:2798): Gtk-WARNING **: 10:49:18.733: Locale not supported by C library.
	Using the fallback 'C' locale.
/usr/share/libdrm/amdgpu.ids: No such file or directory
QSystemTrayIcon::setVisible: No Icon set
QSystemTrayIcon::setVisible: No Icon set
QSystemTrayIcon::setVisible: No Icon set
-- repeats forever....

[commad_log.txt](https://github.com/telegramdesktop/tdesktop/files/4741615/log.txt)
[log.txt](https://github.com/telegramdesktop/tdesktop/files/4741619/log.txt)

</details>

**Comment by ilya-fedin** [comment]
Log is in ~/snap/telegram-desktop/current/.local/share/TelegramDesktop

**Comment by ilya-fedin** [comment]
> [commad_log.txt](https://github.com/telegramdesktop/tdesktop/files/4741615/log.txt)
> [log.txt](https://github.com/telegramdesktop/tdesktop/files/4741619/log.txt)

Just a note: there are no notification when you edit your message

What desktop environment do you use?

**Comment by ilya-fedin** [comment]
And I can't see version of your distribution

**Comment by GabTux** [comment]
Noted, sorry. I use xfce 4.14 and debian is bullseye/sid.

**Comment by ilya-fedin** [comment]
What icon theme are you using?

**Comment by mcourteaux** [comment]
I can confirm this issue just started. I'm on i3.

**Comment by moroznah** [comment]
Same issue here. Ubuntu Focal with Cinnamon, gnome icon theme.
Attached log

**Comment by GabTux** [comment]
> What icon theme are you using?

Tango icon theme.

**Comment by ilya-fedin** [comment]
I can't reproduce :(

```
snap version
snap list | grep telegram-desktop
```

**Comment by mcourteaux** [comment]
```
❯ snap list | grep telegram
telegram-desktop         2.1.10                      1666  latest/stable    telegram.desktop  -

~
❯ snap version
snap    2.45
snapd   2.45
series  16
ubuntu  18.04
kernel  5.3.0-53-generic
```

**Comment by moroznah** [comment]
moroz@mws:~$ snap version
snap    2.45
snapd   2.45
series  16
ubuntu  20.04
kernel  5.4.0-33-lowlatency
moroz@mws:~$ snap list | grep telegram-desktop
telegram-desktop         2.1.10                      1666   latest/stable  telegram.desktop  -

**Comment by mcourteaux** [comment]
I'll drop this in here too:
```
❯ dpkg --list | grep qt5
ii  libaccounts-qt5-1:amd64                            1.15+17.04.20161104.1-0ubuntu1                   amd64        QT library for single sign on
ii  libdbusmenu-qt5-2:amd64                            0.9.3+16.04.20160218-1ubuntu1                    amd64        Qt implementation of the DBusMenu protocol
ii  libphonon4qt5-4:amd64                              4:4.10.0-2                                       amd64        multimedia framework from KDE using Qt 5 - core library
ii  libpolkit-qt5-1-1:amd64                            0.112.0-5                                        amd64        PolicyKit-qt5-1 library
ii  libpoppler-qt5-1:amd64                             0.62.0-2ubuntu2.10                               amd64        PDF rendering library (Qt 5 based shared library)
ii  libqca-qt5-2:amd64                                 2.1.3-2ubuntu2                                   amd64        libraries for the Qt Cryptographic Architecture
ii  libqca-qt5-2-plugins:amd64                         2.1.3-2ubuntu2                                   amd64        QCA plugins for libqca2
ii  libqt5concurrent5:amd64                            5.9.5+dfsg-0ubuntu2.5                            amd64        Qt 5 concurrent module
ii  libqt5core5a:amd64                                 5.9.5+dfsg-0ubuntu2.5                            amd64        Qt 5 core module
ii  libqt5dbus5:amd64                                  5.9.5+dfsg-0ubuntu2.5                            amd64        Qt 5 D-Bus module
ii  libqt5gui5:amd64                                   5.9.5+dfsg-0ubuntu2.5                            amd64        Qt 5 GUI module
ii  libqt5multimedia5:amd64                            5.9.5-0ubuntu1                                   amd64        Qt 5 Multimedia module
ii  libqt5network5:amd64                               5.9.5+dfsg-0ubuntu2.5                            amd64        Qt 5 network module
ii  libqt5opengl5:amd64                                5.9.5+dfsg-0ubuntu2.5                            amd64        Qt 5 OpenGL module
ii  libqt5opengl5-dev:amd64                            5.9.5+dfsg-0ubuntu2.5                            amd64        Qt 5 OpenGL library development files
ii  libqt5positioning5:amd64                           5.9.5+dfsg-0ubuntu2                              amd64        Qt Positioning module
ii  libqt5printsupport5:amd64                          5.9.5+dfsg-0ubuntu2.5                            amd64        Qt 5 print support module
ii  libqt5qml5:amd64                                   5.9.5-0ubuntu1.1                                 amd64        Qt 5 QML module
ii  libqt5quick5:amd64                                 5.9.5-0ubuntu1.1                                 amd64        Qt 5 Quick library
ii  libqt5quickcontrols2-5:amd64                       5.9.5-0ubuntu2                                   amd64        Qt 5 Quick Controls 2 library
ii  libqt5quickparticles5:amd64                        5.9.5-0ubuntu1.1                                 amd64        Qt 5 Quick particles module
ii  libqt5quicktemplates2-5:amd64                      5.9.5-0ubuntu2                                   amd64        Qt 5 Quick Templates 2 library
ii  libqt5quicktest5:amd64                             5.9.5-0ubuntu1.1                                 amd64        Qt 5 Quick Test library
ii  libqt5quickwidgets5:amd64                          5.9.5-0ubuntu1.1                                 amd64        Qt 5 Quick Widgets library
ii  libqt5script5:amd64                                5.9.5+dfsg-0ubuntu1                              amd64        Qt 5 script module
ii  libqt5sensors5:amd64                               5.9.5-0ubuntu1                                   amd64        Qt Sensors module
ii  libqt5sql5:amd64                                   5.9.5+dfsg-0ubuntu2.5                            amd64        Qt 5 SQL module
ii  libqt5sql5-sqlite:amd64                            5.9.5+dfsg-0ubuntu2.5                            amd64        Qt 5 SQLite 3 database driver
ii  libqt5svg5:amd64                                   5.9.5-0ubuntu1                                   amd64        Qt 5 SVG module
ii  libqt5test5:amd64                                  5.9.5+dfsg-0ubuntu2.5                            amd64        Qt 5 test module
ii  libqt5texttospeech5:amd64                          5.9.5-0ubuntu1                                   amd64        Speech library for Qt - libraries
ii  libqt5waylandclient5:amd64                         5.9.5-0ubuntu1                                   amd64        QtWayland client library
ii  libqt5waylandcompositor5:amd64                     5.9.5-0ubuntu1                                   amd64        QtWayland compositor library
ii  libqt5webchannel5:amd64                            5.9.5-0ubuntu1                                   amd64        Web communication library for Qt
ii  libqt5webkit5:amd64                                5.212.0~alpha2-7ubuntu1                          amd64        Web content engine library for Qt
ii  libqt5widgets5:amd64                               5.9.5+dfsg-0ubuntu2.5                            amd64        Qt 5 widgets module
ii  libqt5x11extras5:amd64                             5.9.5-0ubuntu1                                   amd64        Qt 5 X11 extras
ii  libqt5xml5:amd64                                   5.9.5+dfsg-0ubuntu2.5                            amd64        Qt 5 XML module
ii  libsignon-qt5-1:amd64                              8.59+17.10.20170606-0ubuntu1                     amd64        Single Sign On framework
ii  phonon4qt5:amd64                                   4:4.10.0-2                                       amd64        multimedia framework from KDE using Qt 5 - metapackage
ii  phonon4qt5-backend-vlc:amd64                       0.10.1-2                                         amd64        Phonon4Qt5 VLC backend
ii  qt5-default:amd64                                  5.9.5+dfsg-0ubuntu2.5                            amd64        Qt 5 development defaults package
ii  qt5-gtk-platformtheme:amd64                        5.9.5+dfsg-0ubuntu2.5                            amd64        Qt 5 GTK+ 3 platform theme
ii  qt5-qmake:amd64                                    5.9.5+dfsg-0ubuntu2.5                            amd64        Qt 5 qmake Makefile generator tool
ii  qt5-qmake-bin                                      5.9.5+dfsg-0ubuntu2.5                            amd64        Qt 5 qmake Makefile generator tool — binary file
ii  qt5-qmltooling-plugins:amd64                       5.9.5-0ubuntu1.1                                 amd64        Qt 5 qmltooling plugins
```

**Comment by GabTux** [comment]
$: snap version
snap    2.45
snapd   2.45
series  16
debian  -
kernel  5.6.0-2-amd64

$: snap list | grep telegram-desktop
telegram-desktop         2.1.10                   1666  latest/stable  telegram.desktop  -

$: dpkg --list | grep qt5
ii  libaccounts-qt5-1                             1.15-2                                   amd64        Accounts database access Qt version - Qt5 shared library
ii  libdbusmenu-qt5-2:amd64                       0.9.3+16.04.20160218-2+b1                amd64        Qt implementation of the DBusMenu protocol
ii  libphonon4qt5-4:amd64                         4:4.11.1-3                               amd64        multimedia framework from KDE using Qt 5 - core library
ii  libphonon4qt5-data                            4:4.11.1-3                               all          multimedia framework from KDE using Qt 5 - core library data
ii  libpolkit-qt5-1-1:amd64                       0.112.0-7.1+b1                           amd64        PolicyKit-qt5-1 library
ii  libpoppler-qt5-1:amd64                        0.71.0-6                                 amd64        PDF rendering library (Qt 5 based shared library)
ii  libqca-qt5-2:amd64                            2.2.1-2                                  amd64        libraries for the Qt Cryptographic Architecture
ii  libqca-qt5-2-plugins:amd64                    2.2.1-2                                  amd64        QCA plugins for libqca2
ii  libqt5concurrent5:amd64                       5.12.5+dfsg-10+b1                        amd64        Qt 5 concurrent module
ii  libqt5core5a:amd64                            5.12.5+dfsg-10+b1                        amd64        Qt 5 core module
ii  libqt5dbus5:amd64                             5.12.5+dfsg-10+b1                        amd64        Qt 5 D-Bus module
ii  libqt5designer5:amd64                         5.12.5-2+b2                              amd64        Qt 5 designer module
ii  libqt5gui5:amd64                              5.12.5+dfsg-10+b1                        amd64        Qt 5 GUI module
ii  libqt5help5:amd64                             5.12.5-2+b2                              amd64        Qt 5 help module
ii  libqt5multimedia5:amd64                       5.12.5-1+b1                              amd64        Qt 5 Multimedia module
ii  libqt5multimedia5-plugins:amd64               5.12.5-1+b1                              amd64        Qt 5 Multimedia module plugins
ii  libqt5multimediagsttools5:amd64               5.12.5-1+b1                              amd64        GStreamer tools for  Qt 5 Multimedia module
ii  libqt5multimediawidgets5:amd64                5.12.5-1+b1                              amd64        Qt 5 Multimedia Widgets module
ii  libqt5network5:amd64                          5.12.5+dfsg-10+b1                        amd64        Qt 5 network module
ii  libqt5opengl5:amd64                           5.12.5+dfsg-10+b1                        amd64        Qt 5 OpenGL module
ii  libqt5positioning5:amd64                      5.12.5+dfsg-5+b1                         amd64        Qt Positioning module
ii  libqt5printsupport5:amd64                     5.12.5+dfsg-10+b1                        amd64        Qt 5 print support module
ii  libqt5qml5:amd64                              5.12.5-5                                 amd64        Qt 5 QML module
ii  libqt5quick5:amd64                            5.12.5-5                                 amd64        Qt 5 Quick library
ii  libqt5quickcontrols2-5:amd64                  5.12.5+dfsg-2+b1                         amd64        Qt 5 Quick Controls 2 library
ii  libqt5quicktemplates2-5:amd64                 5.12.5+dfsg-2+b1                         amd64        Qt 5 Quick Templates 2 library
ii  libqt5quickwidgets5:amd64                     5.12.5-5                                 amd64        Qt 5 Quick Widgets library
ii  libqt5sensors5:amd64                          5.12.5-2+b1                              amd64        Qt Sensors module
ii  libqt5sql5:amd64                              5.12.5+dfsg-10+b1                        amd64        Qt 5 SQL module
ii  libqt5sql5-sqlite:amd64                       5.12.5+dfsg-10+b1                        amd64        Qt 5 SQLite 3 database driver
ii  libqt5svg5:amd64                              5.12.5-2                                 amd64        Qt 5 SVG module
ii  libqt5test5:amd64                             5.12.5+dfsg-10+b1                        amd64        Qt 5 test module
ii  libqt5texttospeech5:amd64                     5.12.5-1                                 amd64        Speech library for Qt - libraries
ii  libqt5waylandclient5:amd64                    5.12.5-2+b1                              amd64        QtWayland client library
ii  libqt5waylandcompositor5:amd64                5.12.5-2+b1                              amd64        QtWayland compositor library
ii  libqt5webchannel5:amd64                       5.12.5-2                                 amd64        Web communication library for Qt
ii  libqt5webengine-data                          5.12.5+dfsg-7                            all          Web content engine library for Qt - Data
ii  libqt5webengine5:amd64                        5.12.5+dfsg-7+b3                         amd64        Web content engine library for Qt
ii  libqt5webenginecore5:amd64                    5.12.5+dfsg-7+b3                         amd64        Web content engine library for Qt - Core
ii  libqt5webenginewidgets5:amd64                 5.12.5+dfsg-7+b3                         amd64        Web content engine library for Qt - Widget
ii  libqt5webkit5:amd64                           5.212.0~alpha4-1+b1                      amd64        Web content engine library for Qt
ii  libqt5widgets5:amd64                          5.12.5+dfsg-10+b1                        amd64        Qt 5 widgets module
ii  libqt5x11extras5:amd64                        5.12.5-1                                 amd64        Qt 5 X11 extras
ii  libqt5xml5:amd64                              5.12.5+dfsg-10+b1                        amd64        Qt 5 XML module
ii  libsignon-qt5-1:amd64                         8.59-2+b1                                amd64        Single Sign On framework - qt5 shared libraries
ii  phonon4qt5:amd64                              4:4.11.1-3                               amd64        multimedia framework from KDE using Qt 5 - metapackage
ii  phonon4qt5-backend-vlc:amd64                  0.11.1-1                                 amd64        Phonon4Qt5 VLC backend
ii  python3-pyqt5                                 5.14.2+dfsg-1+b1                         amd64        Python 3 bindings for Qt5
ii  python3-pyqt5.qtsvg                           5.14.2+dfsg-1+b1                         amd64        Python 3 bindings for Qt5's SVG module
ii  python3-pyqt5.qtwebchannel                    5.14.2+dfsg-1+b1                         amd64        Python 3 bindings for Qt5's WebChannel module
ii  python3-pyqt5.qtwebengine                     5.14.0-2+b1                              amd64        Python 3 bindings for Qt5's WebEngine module
ii  qt5-gtk-platformtheme:amd64                   5.12.5+dfsg-10+b1                        amd64        Qt 5 GTK+ 3 platform theme
ii  qt5-image-formats-plugins:amd64               5.12.5-1                                 amd64        Qt 5 Image

**Comment by ilya-fedin** [comment]
`sudo aa-status`

**Comment by GabTux** [comment]
> `sudo aa-status`

apparmor module is loaded.
47 profiles are loaded.
43 profiles are in enforce mode.
   /snap/core/9289/usr/lib/snapd/snap-confine
   /snap/core/9289/usr/lib/snapd/snap-confine//mount-namespace-capture-helper
   /usr/bin/evince
   /usr/bin/evince-previewer
   /usr/bin/evince-previewer//sanitized_helper
   /usr/bin/evince-thumbnailer
   /usr/bin/evince//sanitized_helper
   /usr/bin/man
   /usr/lib/cups/backend/cups-pdf
   /usr/lib/snapd/snap-confine
   /usr/lib/snapd/snap-confine//mount-namespace-capture-helper
   /usr/lib/telepathy/mission-control-5
   /usr/lib/telepathy/telepathy-*
   /usr/lib/telepathy/telepathy-*//pxgsettings
   /usr/lib/telepathy/telepathy-*//sanitized_helper
   /usr/lib/telepathy/telepathy-ofono
   /usr/lib/x86_64-linux-gnu/lightdm/lightdm-guest-session
   /usr/lib/x86_64-linux-gnu/lightdm/lightdm-guest-session//chromium
   /usr/sbin/cups-browsed
   /usr/sbin/cupsd
   /usr/sbin/cupsd//third_party
   libreoffice-senddoc
   libreoffice-soffice//gpg
   libreoffice-xpdfimport
   lsb_release
   man_filter
   man_groff
   nvidia_modprobe
   nvidia_modprobe//kmod
   snap-update-ns.acestreamplayer
   snap-update-ns.clion
   snap-update-ns.core
   snap-update-ns.hollywood
   snap-update-ns.spotify
   snap-update-ns.telegram-desktop
   snap-update-ns.vlc
   snap.acestreamplayer.acestreamplayer
   snap.acestreamplayer.engine
   snap.acestreamplayer.mpv
   snap.core.hook.configure
   snap.spotify.spotify
   snap.telegram-desktop.telegram-desktop
   snap.vlc.vlc
4 profiles are in complain mode.
   libreoffice-oopslash
   libreoffice-soffice
   snap.clion.clion
   snap.hollywood.hollywood
8 processes have profiles defined.
8 processes are in enforce mode.
   /usr/sbin/cups-browsed (809) 
   /usr/sbin/cupsd (755) 
   /usr/lib/cups/notifier/dbus (1471) /usr/sbin/cupsd
   /snap/spotify/41/usr/share/spotify/spotify (2702) snap.spotify.spotify
   /snap/spotify/41/usr/share/spotify/spotify (2865) snap.spotify.spotify
   /snap/spotify/41/usr/share/spotify/spotify (2910) snap.spotify.spotify
   /snap/spotify/41/usr/share/spotify/spotify (2916) snap.spotify.spotify
   /snap/spotify/41/usr/share/spotify/spotify (2934) snap.spotify.spotify
0 processes are in complain mode.
0 processes are unconfined but have a profile defined.

**Comment by ilya-fedin** [comment]
What happens if you move the snap data?

`mv ~/snap/telegram-desktop{,.bak}`

**Comment by GabTux** [comment]
It is successfully moved. After running it again, the telegram-desktop directory is created and result is the same - this error.

**Comment by ilya-fedin** [comment]
:thinking: what happens if you try to remove and install snap?

**Comment by GabTux** [comment]
It didn't help.

**Comment by ilya-fedin** [comment]
That's strange, I can't reproduce this on no one of my VMs: KDE Neon, Manjaro Xfce, Ubunttu MATE 18.04, Debian 10 MATE
Probably, you need to dig into your system and find that cause this error
The most strange thing that between the previous and the latest stable release were no changes with tray icon, only memory leak and crash fixes :see_no_evil:

**Comment by GabTux** [comment]
Ok, interesting. I reproduced this error on another computer - Ubuntu MATE 16.04. I am planning upgrade to 18.04, so I will keep you updated.

**Comment by ilya-fedin** [comment]
I just reproduced this after some actions on Manjaro Xfce

**Comment by GabTux** [comment]
So after upgrading ubuntu MATE from 16.04 to 18.04, Telegram starts wroking. The only difference is between QT packages I think (snap, telegram versions were same).
16.04:
ii  libqt5core5a:amd64                          5.5.1+dfsg-16ubuntu7.7                          amd64        Qt 5 core module
ii  libqt5dbus5:amd64                           5.5.1+dfsg-16ubuntu7.7                          amd64        Qt 5 D-Bus module
ii  libqt5gui5:amd64                            5.5.1+dfsg-16ubuntu7.7                          amd64        Qt 5 GUI module
ii  libqt5libqgtk2:amd64                        5.5.1+dfsg-16ubuntu7.7                          amd64        Qt 5 GTK2 platform theme
ii  libqt5network5:amd64                        5.5.1+dfsg-16ubuntu7.7                          amd64        Qt 5 network module
ii  libqt5sql5:amd64                            5.5.1+dfsg-16ubuntu7.7                          amd64        Qt 5 SQL module
ii  libqt5sql5-sqlite:amd64                     5.5.1+dfsg-16ubuntu7.7                          amd64        Qt 5 SQLite 3 database driver
ii  libqt5widgets5:amd64                        5.5.1+dfsg-16ubuntu7.7                          amd64        Qt 5 widgets module
ii  libqt5x11extras5:amd64                      5.5.1-3build1                                   amd64        Qt 5 X11 extras

18.04:
ii  libaccounts-qt5-1:amd64                1.15+17.04.20161104.1-0ubuntu1                      amd64        QT library for single sign on
ii  libqt5core5a:amd64                     5.9.5+dfsg-0ubuntu2.5                               amd64        Qt 5 core module
ii  libqt5dbus5:amd64                      5.9.5+dfsg-0ubuntu2.5                               amd64        Qt 5 D-Bus module
ii  libqt5gui5:amd64                       5.9.5+dfsg-0ubuntu2.5                               amd64        Qt 5 GUI module
ii  libqt5network5:amd64                   5.9.5+dfsg-0ubuntu2.5                               amd64        Qt 5 network module
ii  libqt5positioning5:amd64               5.9.5+dfsg-0ubuntu2                                 amd64        Qt Positioning module
ii  libqt5printsupport5:amd64              5.9.5+dfsg-0ubuntu2.5                               amd64        Qt 5 print support module
ii  libqt5qml5:amd64                       5.9.5-0ubuntu1.1                                    amd64        Qt 5 QML module
ii  libqt5quick5:amd64                     5.9.5-0ubuntu1.1                                    amd64        Qt 5 Quick library
ii  libqt5sensors5:amd64                   5.9.5-0ubuntu1                                      amd64        Qt Sensors module
ii  libqt5sql5:amd64                       5.9.5+dfsg-0ubuntu2.5                               amd64        Qt 5 SQL module
ii  libqt5sql5-sqlite:amd64                5.9.5+dfsg-0ubuntu2.5                               amd64        Qt 5 SQLite 3 database driver
ii  libqt5svg5:amd64                       5.9.5-0ubuntu1                                      amd64        Qt 5 SVG module
ii  libqt5webchannel5:amd64                5.9.5-0ubuntu1                                      amd64        Web communication library for Qt
ii  libqt5webkit5:amd64                    5.212.0~alpha2-7ubuntu1                             amd64        Web content engine library for Qt
ii  libqt5widgets5:amd64                   5.9.5+dfsg-0ubuntu2.5                               amd64        Qt 5 widgets module
ii  libqt5x11extras5:amd64                 5.9.5-0ubuntu1                                      amd64        Qt 5 X11 extras
ii  libqt5xml5:amd64                       5.9.5+dfsg-0ubuntu2.5                               amd64        Qt 5 XML module
ii  libsignon-qt5-1:amd64                  8.59+17.10.20170606-0ubuntu1                        amd64        Single Sign On framework
ii  qt5-gtk-platformtheme:amd64            5.9.5+dfsg-0ubuntu2.5                               amd64        Qt 5 GTK+ 3 platform theme
ii  qt5-style-plugins:amd64                5.0.0+git23.g335dbec-2build5                        amd64        Qt 5 extra widget styles

**Comment by ilya-fedin** [comment]
Snap packages can't use system libraries due to the sandbox
What can make difference is environment variables

**Comment by mcourteaux** [comment]
> Snap packages can't use system libraries due to the sandbox

Are you saying you ship the qt libraries again with every snap? That would be infuriating.

**Comment by ilya-fedin** [comment]
> Are you saying you ship the qt libraries again with every snap?

Yes, that's how snap packages works

**Comment by mcourteaux** [comment]
It is available through snap by now, although I don't know how to update a snap. I removed and installed it again.

**Comment by ilya-fedin** [comment]
> It is available through snap by now, although I don't know how to update a snap. I removed and installed it again.

It updates automatically by snapd + there are `snap refresh` command
