### ISSUE TITLE
Image get full screen on another monitor. Not in same monitor.

### ISSUE THREAD

**Issue by fareezMaple** [telegramdesktop/tdesktop#8017]
### Steps to reproduce
1. Open Telegram desktop in secondary display. (Display mode extended)
2. Open any chat. 
3. Click on image messages.

### Expected behaviour
Image going full screen should be in same monitor. 

### Actual behaviour
Image going full screen in main display, and leaving telegram alone in secondary display.

### Configuration
**Operating system: Windows 10**

**Version of Telegram Desktop: 2.1.10**

**Used theme** : Custom theme

View screenshot:
![Screenshot (784)](https://user-images.githubusercontent.com/60868965/83992797-16b59e80-a984-11ea-95ee-9ed5c9830bba.png)

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/5126
