### ISSUE TITLE
telegram-desktop killed by SIGABRT

### ISSUE THREAD

**Issue by qnxdev** [telegramdesktop/tdesktop#8018]
I'm running on Fedora 32.

Telegram Desktop unexpectedly crashes and is closed.

I simply open Telegram switch to another app window, then when I switch back to Telegram it simply crashes and I get a notification from GNOME that says..

telegram-desktop killed by SIGABRT

Is there any solution?
Is the problem with app or system?

Thanks in advance.

**Comment by Aokromes** [comment]
plz, run telegram under gdb and run:
https://github.com/TrinityCore/TrinityCore/blob/3.3.5/contrib/debugger/crashreport.gdb

(you may need to remove 
set style enabled off
on your linux distribution)

**Comment by ilya-fedin** [comment]
> I'm running on Fedora 32.

You have removed the entire template...

**Comment by xvitaly** [comment]
> Telegram Desktop unexpectedly crashes and is closed.

Please install debug symbols, run Telegram Desktop under gdb and get backtrace with `bt full`.

**Comment by Aokromes** [comment]
no answer over a month, closing, if this bug is still valid open a ticket with updated versions of your OS and telegram.
