### ISSUE TITLE
Inline sticker results appear blank

### ISSUE THREAD

**Issue by hmnd** [telegramdesktop/tdesktop#8020]
### Steps to reproduce
1. Search inline for anything (eg. Telegram) using @stickersearchbot or another inline bot that returns sticker results.

### Expected behaviour
A grid of stickers is returned, with a thumbnail displayed of each one. 

### Actual behaviour
An empty grid is returned, with no thumbnails shown. Clicking or clicking and holding on a stickers does show the full sticker. 

### Configuration
**Operating system:** Any. 

**Version of Telegram Desktop:** 2.1.10 (I believe it started in this ver. but not sure).

<details><summary><b>Screenshots:</b></summary>

![20200608_065032](https://user-images.githubusercontent.com/12853597/84038147-654b4480-a954-11ea-8916-7f1de7b493ae.jpg)
![20200608_065029](https://user-images.githubusercontent.com/12853597/84038149-65e3db00-a954-11ea-866c-57eba0116bfa.jpg)</details>

**Comment by Whew-Inc** [comment]
2.1.7 works for me, all versions after has the blank stickers issue.

**Comment by jh0ker** [comment]
Animated stickers seem to show up fine, by the way.
