### ISSUE TITLE
Telegram animations on second monitor cause stuttering on main monitor [Win10]

### ISSUE THREAD

**Issue by MrPeeperNumber** [telegramdesktop/tdesktop#8022]
I have a 2-monitor setup. When I have Telegram on my second monitor, it causes my main monitor's refresh rate to drop to match the refresh rate of my second monitor. I only have this problem when animations are playing, specifically when it says that someone is typing. I think this might have to do with the frame rate of the animations being below the refresh rate of my main monitor, but I'm not sure why that would affect my main monitor when it's on my secondary monitor. I have the same problem with Discord sometimes. When the desktop app is out of focus, it shouldn't play the full animation, maybe just change to "_Blank_ is typing..." without the animation. Discord does the same thing and I rarely have the same issue.

**Comment by ilya-fedin** [comment]
#4941
