### ISSUE TITLE
-- copies as —

### ISSUE THREAD

**Issue by AnderRasoVazquez** [telegramdesktop/tdesktop#803]
Sended message:
gpg --keyserver 
Received message:
gpg —keyserver

**Comment by auchri** [comment]
#801

**Comment by Streppel** [comment]
Does anybody knows why is this conversion done at all? I'm curious about it as it doesn't seem to be useful.

**Comment by formatq** [comment]
On winphone telegram too.

**Comment by auchri** [comment]
@telegramdesktop Please remove this lines of code: https://github.com/telegramdesktop/tdesktop/blob/master/Telegram/SourceFiles/historywidget.cpp#L3325-L3328

**Comment by auchri** [comment]
Duplicate #522
