### ISSUE TITLE
[Feature Request] Emojify folders

### ISSUE THREAD

**Issue by xmha97** [telegramdesktop/tdesktop#8032]
Hello,
I using Telegram Desktop (Windows Store Edition)
I have a suggestion for the folder feature.

I love Microsoft ToDo idea:
![image](https://user-images.githubusercontent.com/23485114/84139490-31137900-aa65-11ea-9297-754805beae18.png)

I want to set the beginning emoji of the folder name as the folders icon.
For example:

Current UI:
![Telegram](https://user-images.githubusercontent.com/23485114/84137045-5ef6be80-aa61-11ea-99b7-8f1185aa10d2.png)

My UI:
![Telegram](https://user-images.githubusercontent.com/23485114/84137037-5b633780-aa61-11ea-880b-92e3d6035304.png)

Current UI:
![Telegram](https://user-images.githubusercontent.com/23485114/84137881-94e87280-aa62-11ea-8e20-7c5d28ec9062.png)

My UI:
![Telegram](https://user-images.githubusercontent.com/23485114/84137861-8ac67400-aa62-11ea-9ea5-1858181b22d7.png)

Thanks.

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/7518
