### ISSUE TITLE
Telegram don't insert images from chromium

### ISSUE THREAD

**Issue by olegon-ru** [telegramdesktop/tdesktop#8035]
Source       : telegram-desktop-2.1.7-1.fc32.src.rpm
From repo    : rpmfusion-free-updates
5.6.14-300.fc32.x86_64, Fedora 32 Gnome, all updates included

Very annoying trouble with Telegram desktop. Sometimes it's impossible to paste image from Chromium/Chrome to Telegram. Suppose it's not Chrome issue, because it's no problem to paste to Gimp.

Steps to reproduce: 
1) open some image site, tested at photo.google.com
2) open some photo
3) right-click menu - Copy image
4) try to paste in Telegram-desktop by Ctrl-V, Shift-Ins or Paste menu.
nothing happens... no lines in log or stdin... I repeated step 4 continiously until photo pasted. May be about 15 seconds.

It's confirmed issue on 3 PCs, controlled by me. My PC with Gnome, my wife's notebook with Gnome, my notebook with KDE (the same version of tdesktop, Fedora). Sometimes (very rarely) it works well, but in 99% cases I clicking Ctrl-V repeately very long time and crying :) Sometimes (very rarely) it paste image URL instead of image itself.

Tried incognito in Chromium - no success. Tried copy to Gimp - without problem. Tried copy from Gimp to Telegram - crashed Gimp. Copy from tdesktop to itself - without problem.

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/7223
