### ISSUE TITLE
[BUG] Audio in 2X don't start immediately

### ISSUE THREAD

**Issue by Datalux** [telegramdesktop/tdesktop#8042]
### Steps to reproduce
1. Take audio 2X option enabled
2. Play an audio message

### Expected behaviour
Audio starts play

### Actual behaviour
Audio don't start. You need to disable and enable again the audio 2X option

### Configuration
**Operating system:**
Debian 10

**Version of Telegram Desktop:** 2.1.11

**Installation source (Linux Only)** - the official website

**Comment by ilya-fedin** [comment]
Can't reproduce, plays just fine for me

**Comment by Aokromes** [comment]
no answer over a month, closing, if this bug is still valid open a ticket with updated versions of your OS and telegram.
