### ISSUE TITLE
2.1.10 win7 64 Image/sticker timestamp visible

### ISSUE THREAD

**Issue by imashxtyz** [telegramdesktop/tdesktop#8045]
When your last sent message in a group is image or sticker, the timestamp in the bottom right corner always visible. It should only be visible on mouse hover. It disappears when another message is sent by you or someone else.

**Comment by MasterGroosha** [comment]
Can confirm on Windows 10, TDesktop 2.1.17 beta. Definitely looks like a bug.

**Comment by MasterGroosha** [comment]
Still valid as of 2.4.3

**Comment by MasterGroosha** [comment]
Still here: 2.7.1
