### ISSUE TITLE
Closing the profile panel brings all the messages to the left side of the screen.

### ISSUE THREAD

**Issue by krushnaj** [telegramdesktop/tdesktop#8047]
### Steps to reproduce
1. Open any chat with the profile open on the right side
2. Press the close side pane option from the chat screen
3. All the chats will now appear on the left side and it gets difficult to understand who has sent the message

### Expected behaviour
The profile panel should close as expected and the chats should show as they were the profile panel is open.
The chat should show like this when the profile panel is closed.
![Screenshot from 2020-06-11 15-40-05](https://user-images.githubusercontent.com/46159881/84373864-cc8a2280-abfa-11ea-965a-3ac1b65e7a41.png)

### Actual behaviour
Instead of the chats staying where they should be all the chat moves on the left side of the chat screen.
Instead the chats are shown like this.
![Screenshot from 2020-06-11 15-46-47](https://user-images.githubusercontent.com/46159881/84373930-e297e300-abfa-11ea-9782-8fe74499f716.png)

### Configuration
**Operating system:**
Ubuntu 19.10

**Version of Telegram Desktop:**
2.1.11

**Installation source (Linux Only)** - the official website / GitHub releases / flatpak / snap / distribution package:
snap

**Used theme**:
Night theme without any modification.

**Comment by ilya-fedin** [comment]
This is not a bug, but a feature
When the chat area is wide enough, all messages go to the left side

**Comment by krushnaj** [comment]
So is there any way I can keep the messages to like they are when the profile page is open?

**Comment by ilya-fedin** [comment]
> So is there any way I can keep the messages to like they are when the profile page is open?

Disable "Adaptive layout for wide screen" in "Chat Settings" in the app settings

**Comment by krushnaj** [comment]
Okay. Thanks.
