### ISSUE TITLE
[Feature Request] Timestamp for YouTube videos

### ISSUE THREAD

**Issue by FichteFoll** [telegramdesktop/tdesktop#8048]
### Is your feature request related to a problem?

In [this blog post](https://telegram.org/blog/silent-messages-slow-mode#timestamps-and-improved-scrubbing), clickable timestamps were advertised and introduced for videos, which also works on Telegram Desktop. However, this feature does not seem to work for YouTube videos, at least on Telegram Desktop.

### Describe the solution you'd like
A reply to a message with a youtube video with a timestamp or a link to a video with a timestamp in the same message should be clickable and open the video at that timestamp, just as advertised.

### Additional context
Using Telegram Desktop 2.1.11 on Arch Linux.

**Comment by RememberTheAir** [comment]
That work on the mobile apps because they use their internal webview player to reproduce the video. If from the mobile app you open the youtube url using an external browser/app, it will not open at the timestamp mentioned in the message - it is generally not a good idea to "hijack" an url before opening it in a browser

**Comment by FichteFoll** [comment]
> it is generally not a good idea to "hijack" an url before opening it in a browser

I would generally agree with this, but you're explcitly *not* clicking the URL when you click the timestamp, so I believe hijacking the URL is the expected behavior.

**Comment by RememberTheAir** [comment]
Oh right, it's the timestamp who is clickable, sorry, I forgot that

**Comment by FichteFoll** [comment]
Unless this was ghost-fixed, it's still valid.

**Comment by BANOnotIT** [comment]
Should it be closed?

**Comment by Aokromes** [comment]
@FichteFoll

**Comment by FichteFoll** [comment]
Indeed, it works as advertised now. Thanks for the heads-up.
