### ISSUE TITLE
Include unified newsfeed and timeline features with the ability to share posts and comments just like on facebook

### ISSUE THREAD

**Issue by freemangilgamesh** [telegramdesktop/tdesktop#8049]
I think the only missing feature that would make people ditch any other social media is the facebook-like unified newsfeed and video calling. People want to see what their friends are doing and thinking and interact with them.

**Comment by freemangilgamesh** [comment]
?

**Comment by Aokromes** [comment]
https://t.me/durov/139 it's not what you want? as for video calls, already implemented.

**Comment by freemangilgamesh** [comment]
what?!!
