### ISSUE TITLE
Support gtld's in url parsing

### ISSUE THREAD

**Issue by AngeloG** [telegramdesktop/tdesktop#805]
It sees "example.com" as a valid URL and turns it into a link, but it doesn't see "example.tools" or "example.world" as a valid URL:

![](http://i.imgur.com/tAuHjIp.png)

**Comment by Katzen-Gott** [comment]
It recognizes URL if you add 'http://'. And such behaviour looks fine for me, as I don't want any two words written like this (word1.word2) to be considered a link.

**Comment by AngeloG** [comment]
WhatsApp for example does have this behavior (`example.world` and `example.tools` are turned into clickable links). This is helpful because I have a couple gtld domains myself, and it just looks better without the `http://`, in my opinion.

**Comment by AngeloG** [comment]
In fact, the Android app also parses these as clickable URLs.

**Comment by auchri** [comment]
Links are now parsed on the server, so it's a server issue
