### ISSUE TITLE
Those who use Linux care most about privacy but don't have a secret chat option!

### ISSUE THREAD

**Issue by freemangilgamesh** [telegramdesktop/tdesktop#8050]
I think telegram devs should focus more on the linux client of their app. and include more features and make it on a par with the one availabe on android, and that includes video calling.

**Comment by RememberTheAir** [comment]
> and that includes video calling

There is no video calling for android

**Comment by freemangilgamesh** [comment]
I know but there's "secret chat"

**Comment by Aokromes** [comment]
centuplicated.

**Comment by aBARICHELLO** [comment]
`telegram-cli` supports secret chat: https://github.com/kenorb-contrib/tg
