### ISSUE TITLE
[Feature Request] - Toggle Telegram window from the notification icon

### ISSUE THREAD

**Issue by Sopor** [telegramdesktop/tdesktop#8053]
### Is your feature request related to a problem?
A clear and concise description of what the problem is.
As it is now it is only possible to open Telegram from the notification icon (systray), not minimize it.

### Describe the solution you'd like
I would like it to be possible to minimize Telegram by a single press on the notification icon.

This will make it easy to open Telegram and close it without even moving the mouse pointer. As it is now i have to move it to the X in the Telegram window.

**Comment by ilya-fedin** [comment]
#5600
