### ISSUE TITLE
TelegramDesktop seems to crash the source program of copied image in Xubuntu 16.04

### ISSUE THREAD

**Issue by danielenick89** [telegramdesktop/tdesktop#8054]
This is a very strange issue, not even sure it is a bug, but as far as I can understand it is indeed related to TelegramDesktop (TD). I'm using the lastest version of TD on Xubuntu 16.04. This issue has appeared in the last 6 months or so, and even if I can reproduce it quite reliably, it feels not deterministic. Here's what's happening:
When I copy an image to the clipboard from some programs (by Ctrl+C) and then paste it into TD, the source program I copied the image from crashes, and the image is not pasted into TD. This happens quite consistently when the copied image is large, and not with every program as a source: copying images from chrome or firefox never crashed, where instead GIMP and the screenshot utility of Ubuntu crash most of the times. If I copy the same large images to other programs (from GIMP to GIMP or from Screenshot tool to GIMP) this never happens, so I guess it is in some way TD related. I don't know exactly how copy/paste works in Ubuntu, and I feel this is hardly enough information for you to narrow down the problem, but I hope that you or someone else can reproduce the issue. The crashed program doesn't log anything on the terminal if I reproduce the problem when launching it from there. Also, if I copy small images this never happens. It usually happens to me with screenshots, because I use them a lot.

Also, it is mainly an impression, but it seems to happen most when I copy detail-rich images (like photos) and less with blank screens or simple charts - as if it something memory related (I guess the images are copied in a compressed fashion, but it's just a guess).

### Steps to reproduce
1. Copy a large image into the clipboard using GIMP or the native screenshot tools of xubuntu 16.04
2. Ctrl+v into TelegramDesktop

### Expected behaviour
A dialog to send the copied image as a message should appear

### Actual behaviour
1) The dialog to send the image does not appear, and TD looks stuck for some seconds (cursor is not blinking in the textbox, and generally it's not responding), then it resumes normal functioning (still without the image dialog)
2) The source program I copied the image from suddenly crashes

### Configuration
**Operating system:**
Xubuntu 16.04

**Version of Telegram Desktop:**
2.1.11 but it has been happening for months, I guess no more than 6 months 

**Installation source (Linux Only)** 
I think it was from the official website, but 2 years ago and regularly updated

**Used theme**:
Standard theme

[log.txt](https://github.com/telegramdesktop/tdesktop/files/4770597/log.txt)

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/6952
