### ISSUE TITLE
Tenor playback only works sometimes?

### ISSUE THREAD

**Issue by Ryder17z** [telegramdesktop/tdesktop#8055]
For tenor i haven't found what the difference is between a good link and a bad link
[Bad] https://tenor.com/view/piggy-watermelon-food-fruit-lunch-gif-17243344
[Good] https://media1.tenor.com/images/ebc7ca2874f87495f23ef70c11a98f53/tenor.gif?itemid=5414481
[Bad] https://media1.tenor.com/images/dcb8feaf68bb70ec0de639dcd2197eef/tenor.gif?itemid=11656951

### Expected behaviour
All 3 should play correctly

### Actual behaviour
??
Sometimes it plays the content correctly and sometimes not

### Configuration
Android or Windows client, doesn't matter.

**Version of Telegram Desktop:**
2.1.10

**Comment by Ryder17z** [comment]
stay away stalebot!

**Comment by Aokromes** [comment]
this is server side issue.

**Comment by Aokromes** [comment]
such feature belongs to https://bugs.telegram.org/
