### ISSUE TITLE
Freezes when logging in

### ISSUE THREAD

**Issue by torresjrjr** [telegramdesktop/tdesktop#8056]
### Steps to reproduce
1. shell: telegram-desktop
2. Either when entering lock pin, or re-logging in on fresh install with the 5 digit code, telegram-desktop freezes.

### Expected behaviour
When entering pin, user should be brought to normal screen.

### Actual behaviour
Freezes. Keyboard input ceases.

### Configuration
OS: Arch Linux x86_64
Host: VirtualBox 1.2
Kernel: 5.7.2-arch1-1
CPU: Intel i7-7500U (1) @ 2.904GHzM
GPU: 00:02.0 VMware SVGA II Adapter
Window Manager: i3-gaps
Memory: 3934MiB

**Version of Telegram Desktop:** 2.1.11-1

**Installation source (Linux Only)** - the official website / GitHub releases / flatpak / snap / distribution package: Arch Linux repository (pacman)

**Used theme**: Default theme.

Terminal output from <code>telegram-desktop</code>:
<pre><code>error: : cannot open
error: : cannot open
error: : cannot open</code></pre>

At moment of entering pin, I receive a notification from Telegram on my mobile client that they've detected a "New login", with my IP addr and all.

I'm also able to log in and out of other clients.

Screenshot of frozen telegram-desktop
![Screenshot of frozen telegram-desktop](https://user-images.githubusercontent.com/43079131/84516915-6e2a7600-acc6-11ea-955c-7dcb1e4ee94f.png)

**Comment by Aokromes** [comment]
try to download from github.

**Comment by torresjrjr** [comment]
I have NOT solved this issue. However, I've installed `telegram-desktop-bin` from the AUR (Arch User Repository), and this installation works.

NOTE: The "official"  `telegram-desktop` package still does NOT work. So please do try fix it for others.

**Comment by ilya-fedin** [comment]
> NOTE: The "official" `telegram-desktop` package still does NOT work

It is not official in any way
