### ISSUE TITLE
[Feature Request] Option to forbid voice messages

### ISSUE THREAD

**Issue by NeoTheFox** [telegramdesktop/tdesktop#8057]
Voice messages are a good feature, but there is also a very good amount of people who find them annoying or outright can't engage with them, this includes death people and people who want to be able to reliably search the chat history, etc.
I propose an option to forbid voice messages as a user setting, just like it currently is with calls. Simply being able to forbid certain groups or everyone from sending a voice message to you would be a great option to have.

**Comment by 23rd** [comment]
https://github.com/telegramdesktop/tdesktop/issues/6882#issuecomment-567504115
