### ISSUE TITLE
[Limitation/niche use] If the minimum vertical size were a tad smaller, Telegram would work a lot better on the PinePhone

### ISSUE THREAD

**Issue by ell1e** [telegramdesktop/tdesktop#8058]
I am trying to use Telegram on the [PinePhone](https://wiki.pine64.org/index.php/PinePhone) with an ARM64 build provided by [Alpine Linux](https://pkgs.alpinelinux.org/packages?name=telegram-desktop) which I believe runs this code base here.

When using it, there is a problem that even in portrait mode, vertically Telegram Desktop just about won't fit the screen which results in missing elements:

![test](https://user-images.githubusercontent.com/64124388/84539028-3e896700-ace2-11ea-933b-e8481780f046.png)

As you can see, with the virtual keyboard hidden the input bar comes back:

![test1](https://user-images.githubusercontent.com/64124388/84539487-059dc200-ace3-11ea-88a9-d8ce4d1cdfb6.png)

This is a bit sad since otherwise the layout is responsive enough that it works almost perfectly as a phone app. (Please note this may confuse you since obviously it's named "telegramdesktop", but the PinePhone is a Linux phone so it doesn't really distinguish anymore between phone and desktop apps.) So it would help a lot if this could be changed, since it otherwise works fine!

### Steps to reproduce
1. Install Telegram on a PinePhone, or just resize the window manually on your desktop to simulate
2. See that vertical space doesn't really go to very small, which on the PinePhone leads to the keybaord covering the input bar making typing almost impossible

### Expected behaviour
Telegram window resizes sufficiently to fit on screen, hiding elements as necessary.

### Actual behaviour
Telegram window *almost* resizes as needed, but with the virtual keyboard open the input bar is cut off.

### Configuration
**Operating system:** [postmarketOS (ARM64 Linux with Wayland-based desktop)](https://postmarketos.org)

**Version of Telegram Desktop:** 2.1.11-r0

**Installation source (Linux Only)** Alpine Linux Package

**Used theme**: "tinted"

<details><summary><b>Logs</b>:</summary>
(I don't think log is relevant)
</details>

**Comment by Aokromes** [comment]
use sub 100% scaling.

**Comment by ilya-fedin** [comment]
> As you can see, with the virtual keyboard hidden the input bar comes back:

If you know how to fix it, let's PR a fix.
#3274

**Comment by ell1e** [comment]
@ilya-fedin the window does resize, just not enough. (This shows when entering more than one line, which is when it becomes partially visible again - the window clearly has been sized smaller.) So the bug report you link might not be relevant, and the fix in this case is just to allow for a smaller vertical window size.

> use sub 100% scaling.

That's not really a fix, is it? The text is already pretty small, that would hurt usability quite a bit

**Comment by ilya-fedin** [comment]
> and the fix in this case is just to allow for a smaller vertical window size.

Oh, I guess such fix won't be accepted by core developers, similar change was already done and was reverted: https://github.com/a-wai/tdesktop/commit/862093e1dd1bfbd3be7826f02a75300962ae7324#diff-cb2dbc18bb8c3c9dbbc05626b81d39a2

I suggest you to contact alpine maintainer, since some patching for size already done: https://git.alpinelinux.org/aports/tree/community/telegram-desktop/small-sizes.patch

**Comment by ell1e** [comment]
It sounds like it was reverted due to issues elsewhere of UI not scaling enough. Maybe that could be addressed, and then a fix properly integrated?

**Comment by ilya-fedin** [comment]
> Maybe that could be addressed, and then a fix properly integrated?

Well, if someone make the widgets work fine on with small sizes, minimum width/height could be reduced
But AFAIK core developers have no interest in mobile devices and even in just touchscreen devices, e.g. you need to do that yourself.

**Comment by RussianNeuroMancer** [comment]
> AFAIK core developers have no interest in mobile devices and even in just touchscreen devices

Whoa, that sounds like giant oversight, if we take into account that millions of 2-in-1 and transformers get sold every year.

What is their rationale for intentional reducing Telegram usability on all these devices?

**Comment by ilya-fedin** [comment]
> What is their rationale for intentional reducing Telegram usability on all these devices?

Oh, as far as I know, they tried to support touchscreen, but that was too time consuming while there are too little users with touchscreen. After that they ignoring all issues about touchscreen. That's what I heard.

**Comment by ell1e** [comment]
I assume part of the problem is that many touch-first devices (tablets, phones) are mostly using Android and iOS, and sadly appears to maintain that quite separately for some reason. Now with things like the PinePhone or the more recent laptop-like Windows tablet trend this is slowly changing, but I kind of get it may not be significant enough. Still, I hope priorities will eventually change here

**Comment by RussianNeuroMancer** [comment]
> while there are too little users with touchscreen

@ilya-fedin overall or specifically Telegram Desktop users on devices with touchscreen?

> I assume part of the problem is that many touch-first devices (tablets, phones) are mostly using Android and iOS

Right, there is billions of ARM-based devices with Android and iOS, however millions of x86-based 2-in-1 and transformers didn't go anywhere. People still these devices daily and Lenovo, Dell, HP, Microsoft still sell such devices.

**Comment by ilya-fedin** [comment]
> overall or specifically Telegram Desktop users on devices with touchscreen?

i don't know what he meant ¯\_(ツ)_/¯

**Comment by RussianNeuroMancer** [comment]
@ilya-fedin where it was discussed exactly?

**Comment by Newbytee** [comment]
> use sub 100% scaling.

How do I do this?

**Comment by 23rd** [comment]
@Newbytee https://github.com/telegramdesktop/tdesktop/issues/6055#issuecomment-496599363.

**Comment by allnamesaretakeningithub** [comment]
This also affects Librem 5 phones

**Comment by ThatGeekZen** [comment]
As of phoc 0.4.0 it allows for auto scaling of apps that are too large. For telegram just run `scale-to-fit telgram-desktop on` and it will automatically scale the app appropriately.  I've tested this on PostmarketOS with Phosh and it works fine. I assume it will work on other distros with phosh and the Librem 5 as well. 

Source: [The Mobian wiki](https://wiki.mobian-project.org/doku.php?id=tweaks#automatic-app-scaling)

**Comment by ell1e** [comment]
While that is a helpful temporary band-aid, that leads to other accessibility issues (text too small, etc) so it's not ideal. But I guess any other users coming here via google could find this workaround helpful until it is properly fixed in telegram-desktop.

**Comment by ilya-fedin** [comment]
> until it is properly fixed in telegram-desktop

*never

**Comment by Newbytee** [comment]
> > until it is properly fixed in telegram-desktop
> 
> *never

Why do you say so?

**Comment by ilya-fedin** [comment]
> Why do you say so?

Because app needs a redesign for this (if you just decrease the size limits, some dialogs become corrupt and that's why these changes couldn't be upstreamed) and app developers are not interested in such niche use

**Comment by RussianNeuroMancer** [comment]
@ilya-fedin 

> app developers are not interested in such niche use

This break not only tablets/phones/convertibles support but also accessibility too, because people with eye disorders/diseases tend to increase desktop scaling which in consequence break Telegram Desktop - for example on 1280x800 screen with 160% scaling text input field does not fit the screen. 

I understand that accessibility is always "niche use" but I just want to ask you - do intentionally decided to exclude people with eye disorders and diseases, like elderly people, from Telegram Desktop user base, or you just forget about them? 

> never

Please, reconsider.

**Comment by Newbytee** [comment]
> > app developers are not interested in such niche use
> 
> This break not only tablets/phones/convertibles support but also accessibility too, because people with eye disorders/diseases tend to increase desktop scaling which in consequence break Telegram Desktop - for example on 1280x800 screen with 160% scaling text input field does not fit the screen.

Could you give an example of something that doesn't work properly in a such case? It may be that this is something no developer is aware of.

**Comment by ell1e** [comment]
Sadly programs not fitting the screen very well with large fonts is quite common, so doesn't seem entirely fair to single out Telegram here. Usual workaround is to use a built-in magnifier tool available in most modern desktops, but obviously it'd be nicer if more programs cared about this. However, on the PinePhone and Librem 5 it's really more of an issue of being usable at all, and of course the large font accessibility situation isn't exactly nice even if it's common. So as niche as these use cases are, it would still be cool to see some sort of improvement at some point.

Why is the Android version so separate anyway? Qt should at least in theory work on Android, it seems to me like some gains could be made by slowly moving to a shared code base here. Then there would also be an incentive to universally fix the scaling, and it would no longer be useful to just a niche audience but everyone would benefit.

**Comment by RussianNeuroMancer** [comment]
> Sadly programs not fitting the screen very well with large fonts is quite common, so doesn't seem entirely fair to single out Telegram here. 

Please note that I been talking not about font size increase but system wide screen scaling, which is more preferred than font size increase for this exact reason - it works better with more software, and with Teleram too, unless scaled resolution (in case of example from my previous comment: 1280x800 with 160% scaling is 800x500) is lower than supported by application.
