### ISSUE TITLE
[BUG] Can't click download

### ISSUE THREAD

**Issue by acg-moe** [telegramdesktop/tdesktop#8059]
Can't click download
![WV9PRG8D{BON`F({}8_ UZB](https://user-images.githubusercontent.com/52559903/84541368-de1e1800-ad29-11ea-8840-6c23ffc0b6fe.png)

**Comment by ilya-fedin** [comment]
You have deleted the entire template

**Comment by reallyuniquename** [comment]
Dupe #8043
