### ISSUE TITLE
Inline resuts from Bot API with InlineQueryResultVideo with YouTube link doesn't show

### ISSUE THREAD

**Issue by tuscen** [telegramdesktop/tdesktop#8060]
### Steps to reproduce
1. Start an inline query to a bot
2. Call `answerInlineQuery` request from Bot API with a youtube video, e.g.
```json
{
  "inline_query_id": "123456",
  "results": [
    {
      "video_url": "https://www.youtube.com/watch?v=1S0CTtY8Qa0",
      "mime_type": "text/html",
      "thumb_url": "https://www.youtube.com/watch?v=1S0CTtY8Qa0",
      "title": "Rocket Launch",
      "input_message_content": {
        "message_text": "[Rocket Launch](https://www.youtube.com/watch?v=1S0CTtY8Qa0)",
        "parse_mode": "Markdown"
      },
      "id": "youtube-video",
      "type": "video"
    }
  ],
  "cache_time": 0
}
```
3. Wait for the inline result with the video to appear

The same request works on official macOS and iOS clients.

### Expected behaviour
An inline result appears

### Actual behaviour
No inline result appears

### Configuration
**Operating system:** Windows 10 1909 18363.900

**Version of Telegram Desktop:** 2.1.10

**Used theme**: Classic

<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by hmnd** [comment]
Possibly related to #8020?

**Comment by tuscen** [comment]
Confirm, I too noticed that that stickers are blank, but forgot about it.
