### ISSUE TITLE
Edit caption is takes too long in channels

### ISSUE THREAD

**Issue by Neurotoxin001** [telegramdesktop/tdesktop#8061]
### Steps to reproduce
1. try to edit 2-3 posts in a row in channel
2. first post will be edited instantly, but next posts is will take too long time to save edited caption 

at the same time on ios tg app all is fine and editing is fast.

demonstration (may be NSFW):
desktop - https://i.imgur.com/DEQjNLC.mp4
ios 6.2.1 - https://i.imgur.com/ytKfgC6.mp4

### Configuration
**Operating system:** win 10 ltsc 1809

**Version of Telegram Desktop:** 2.1.10

**Used theme**: dark default

**Comment by john-preston** [comment]
@Neurotoxin001 Logs should be checked to see if server returns a flood wait error there.

**Comment by Neurotoxin001** [comment]
No errors about flood even if I spam "save" button, only these:
https://pastebin.com/Gnps4Lyj

**Comment by john-preston** [comment]
@Neurotoxin001 Yes, but in debug logs (you have to enable them in Settings by typing "debugmode" from the keyboard) we will be able to see how much time passes between sending the edit message request and the response that it was edited.

**Comment by Neurotoxin001** [comment]
```
[08:33:21.162 01-0011118] (dc:2) Recv: { core_message
  msg_id: 6837701322439197697 [LONG],
  seq_no: 433 [INT],
  bytes: 36 [INT],
  body: { rpc_result
    req_msg_id: 6837701322200113716 [LONG],
    result: { rpc_error
      error_code: 420 [INT],
      error_message: "FLOOD_WAIT_6" [STRING],
    },
  },
}
```

Seems like there is 10 sec antiflood timer.

But why on iOS different situation?

**Comment by john-preston** [comment]
@Neurotoxin001 I think it is just async.

**Comment by Neurotoxin001** [comment]
Can it be done in tdesktop? Or maybe showing a timer until I can press "save" again, like with "slow mode" in groups.

**Comment by john-preston** [comment]
@Neurotoxin001 There is a problem with async saving, if you think it was saved and close the app your changes will be lost, while iOS app possibly saves your changes and reattempts to send them on the server if you relaunch the app. Or maybe not 🙄

**Comment by Neurotoxin001** [comment]
Tested it right now.

Opened channel on iOS and desktop and then edit posts on iOS and see on them on desktop — they was instantly become edited
