### ISSUE TITLE
Telegram Desktop for Windows will convert image data in clipboard to jpg format

### ISSUE THREAD

**Issue by mzji** [telegramdesktop/tdesktop#8062]
### Steps to reproduce
1. Use [Snipaste 2.4 beta](https://www.snipaste.com/) to capture a screenshot into clipboard
2. Paste the screenshot to telegram and 'Send As Photo' in any channel
3. Some obvious noisy pixels can be seen in the sent image

### Expected behaviour
In the old version (maybe two or three minor versions ago, can't remember clearly) the image will be sent in png format (no noisy pixels exist)

### Actual behaviour
In Telegram Desktop version 2.1.10 images are sent after being converted into jpg format

### Configuration
**Operating system:**
Windows 10 64-bit Home 1809 / 17763.1039
**Version of Telegram Desktop:**
Telegram Desktop 2.1.10
**Installation source (Linux Only)** - the official website / GitHub releases / flatpak / snap / distribution package:
The version on official website
**Used theme**:
Day theme

<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by mzji** [comment]
Screenshot of a converted image:
![图片](https://user-images.githubusercontent.com/23279426/84562645-924e8b80-ad88-11ea-9aac-77fe572074e8.png)
The converted image in a larger scale:
![图片](https://user-images.githubusercontent.com/23279426/84562655-aa260f80-ad88-11ea-9cc2-57d020a69f78.png)

**Comment by john-preston** [comment]
@mzji They always worked that way. If you send them as photos, they're compressed, if as files - the original images are sent.

**Comment by mzji** [comment]
> 
> 
> @mzji They always worked that way. If you send them as photos, they're compressed, if as files - the original images are sent.

No. In version 2.1.9 or before，The captured images are **always** sent as png even if I use the `Send As Photo` option.

**Comment by mzji** [comment]
Also, png is also a compressed format - it is just loseless compression.

**Comment by mzji** [comment]
OK, seems like I got some confusion here -- in version 2.1.6 or before, after sent, the images in **my chat window** is **the original png images** instead of the converted jpg images; in version 2.1.7 or later, the images in my chat window will be replaced by the converted jpg images. Seems like this is an fixed bug or adjusted feature or something like that? It is not documented well I have to say.

**Comment by john-preston** [comment]
@mzji It may be a fixed bug. Photos are always sent, received and stored as .jpg in Telegram.

**Comment by mzji** [comment]
> 
> 
> @mzji It may be a fixed bug. Photos are always sent, received and stored as .jpg in Telegram.

Thanks for the clarification. I really hope tg desktop could provide a more detailed changelog. Close this issue for now.
