### ISSUE TITLE
[Feature Request] HTML5-based Telegram Mini Games

### ISSUE THREAD

**Issue by danieldanielecki** [telegramdesktop/tdesktop#8064]
It would've been fantastic to be able to publish HTML5-based mini games, such as WeChat Mini Games or Facebook Gaming. Given the fact that these games give an impression of being really instant, e.g. Facebook Gaming was called before Messenger Instant Games, where games can be played from the chat app.

It seems to me it'll be a big thing to have a small games within chat apps, like we can for past few years in WeChat already. Unfortunately, Facebook recently moved out from Messenger, but in practice it's very similar mechanism in their Facebook Gaming. Actually, from Messenger you can link to Facebook Gaming giving the impression it's happening within the Messenger app.

Definitely would've be a great way to socialize users, even in the [Telegram blog post](https://telegram.org/blog/games) I can see that there was some kind of idea for that. However, looks like these were developed by Telegram team games, without the possibility for developers to work on them.

How feasible is or not to make this kind of feature I can' say. For now, definitely would like to show it might be an upcoming trend and let see what the Community thinks about it.

**Comment by Aokromes** [comment]
you mean https://core.telegram.org/bots/games ? anyway, if it's not it doesn't belongs to telegram desktop bugtracker instead twiteer.

**Comment by danieldanielecki** [comment]
@Aokromes could you let me know where this feature should've been send to? I meant actually all the Telegram apps, but couldn't find any other Telegram's repos available to send an issue.
