### ISSUE TITLE
[Feature Request] A prompt asking if you want to keep the proxy after tapping "Connect to proxy"

### ISSUE THREAD

**Issue by sadeghi-aa** [telegramdesktop/tdesktop#8065]
### Is your feature request related to a problem?
I'm in Iran and use MTProto proxies available on some Telegram channels to use Telegram. Since they get blocked by the government on a regular basis (or otherwise shut down by the proxy provider), a lot of the proxies found on those channels don't work and there's no way to find this out but to try to connect to it. After a while, with all the unavailable proxies added only to be found not working, the proxy list in the app gets so huge and you have to clear it up from time to time to make it easier to find the available ones when you can't connect to Telegram.

### Describe the solution you'd like
I think it would make life a lot easier if after clicking on the proxy link and tapping "Connect to proxy",
a prompt would show up asking "Do you want to keep the proxy?" so you can say no if it doesn't get connected at that very moment.

### Describe alternatives you've considered
None really :D You just have to clean up regularly.

**Comment by ilya-fedin** [comment]
#7474?

**Comment by Aokromes** [comment]
yup

**Comment by sadeghi-aa** [comment]
I read [#7474](https://github.com/telegramdesktop/tdesktop/issues/7474) and that could also be good, but the problem with auto-remove is that sometimes there proxies do get available after some days for example and so if the auto-removes them, it could potentially remove one which would work a few days later. What I suggested, however, was a manual one right after you try the proxy.

**Comment by Aokromes** [comment]
notice my counter suggestion on that ticket.

**Comment by sadeghi-aa** [comment]
By disable do you mean they move to another list called, say, "Disabled Proxies"? Still, I guess these two ways could be implemented together. They have different purposes.
