### ISSUE TITLE
All the labels in the interface are in italics

### ISSUE THREAD

**Issue by saband** [telegramdesktop/tdesktop#8067]
### Steps to reproduce
1. Update to v. 2.1.10.
2. Run application.

### Expected behaviour
Normal labels as it was before.

### Actual behaviour
All the labels in the interface are in italics.

### Configuration
Linux Mint 19.2 Cinnamon

**Version of Telegram Desktop:**
v. 2.1.10 linux64

**Installation source (Linux Only)** - the official website / GitHub releases / flatpak / snap / distribution package: the official website and GitHub releases

**Used theme**: classic

<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by ilya-fedin** [comment]
Can't reproduce with 2.1.11 and Linux Mint 19.3 Cinnamon

**Comment by saband** [comment]
![Telegram_001](https://user-images.githubusercontent.com/32991188/84572695-1c541f80-ad9c-11ea-99a0-b0dea0cf2f21.png)
![Telegram_002](https://user-images.githubusercontent.com/32991188/84572697-1d854c80-ad9c-11ea-86dd-aabeb1d06631.png)

**Comment by ilya-fedin** [comment]
Which UI scaling do you have?

**Comment by saband** [comment]
> Which UI scaling do you have?

250%

**Comment by ilya-fedin** [comment]
Can't reproduce :(

**Comment by ilya-fedin** [comment]
Can you zip your /etc/fonts and ~/.config/fontconfig and attach here?

**Comment by saband** [comment]
I have tried to create a new user, downloaded and launched version 2.1.11 and everything is OK with this new user. It seems that the problem is due to some local settings.

> Can you pack your /etc/fonts and ~/.config/fontconfig with tar.gz and attach here?

I don't have ~/.config/fontconfig file or directory, are you sure that this path is correct?
/etc/fonts is attached. 

[fonts.tar.gz](https://github.com/telegramdesktop/tdesktop/files/4774902/fonts.tar.gz)

**Comment by ilya-fedin** [comment]
> I have tried to create a new user, downloaded and launched version 2.1.11 and everything is OK

Then /etc/fonts is unrelated :thinking: 

> are you sure that this path is correct?

yes, but it may not exist

Probably, you need to rename dotdirs until you find which exactly config causes the issue

**Comment by ilya-fedin** [comment]
I suggest to start with qt5ct

**Comment by ilya-fedin** [comment]
I can reproduce if I choose italic-styled font in qt5ct. But if you have the same, that's more system misconfiguration rather than tdesktop bug.

**Comment by saband** [comment]
Yes, qt5st settings changing solves the problem. I don't know why this problem didn't occur before, but I agree that's more system misconfiguration problem. Anyway, thank you for the help.
