### ISSUE TITLE
Telegram Secret Chat?

### ISSUE THREAD

**Issue by dm17** [telegramdesktop/tdesktop#8071]
Why did your developer ask a bunch of questions and then lock the thread?
https://github.com/telegramdesktop/tdesktop/issues/871

Why did he delete his GitHub account?

Are secret chats supported on Linux yet?

**Comment by dm17** [comment]
@Aokromes another anonymous user who works for Telegram? Can you at least let us know Telegram Messenger Inc's rationale on why we can't have secret chats on Linux when there's so many requests for it?

**Comment by Aokromes** [comment]
i don't work for telegram, i maintain bugtracker free of duplicate, already fixed bugs, this fits the 1st.

**Comment by dm17** [comment]
> i don't work for telegram, i maintain bugtracker free of duplicate, already fixed bugs, this fits the 1st.

Duplicate of which ticket? I referenced it and it is locked... And the account who made it is deleted... Can you see why this is confusing?

**Comment by Aokromes** [comment]
the ticket is still open, opening new duplicate tickets of one locked to post on it will end of close the duplicate ticket.
Also the account of the ticket opened still exists.

**Comment by dm17** [comment]
> the ticket is still open, opening new duplicate tickets of one locked to post on it will end of close the duplicate ticket.
> Also the account of the ticket opened still exists.

Sorry but that doesn't make sense:
1) The developer ended the locked thread with a bunch of questions and agreement with the purpose of the thread.
2) The developer has a stripped down github account that *has been deleted* - "Hi, I'm @ghost! I take the place of user accounts that have been deleted."

So now, how is anyone supposed to answer his questions if you close all "duplicate" threads and that original thread is locked?

**Comment by Aokromes** [comment]
the old "telegramdesktop-non-org account" was deleted on conversion to organization the account of ticket opener "vahid9" still exists, the account of the developer is right there.

**Comment by dm17** [comment]
That doesn't answer the more important question about the only thread that is allowed open on this issue is locked... And was ended with confirmation and a bunch of questions from the developer.

**Comment by aBARICHELLO** [comment]
`telegram-cli` supports secret chat: https://github.com/kenorb-contrib/tg

**Comment by dm17** [comment]
> `telegram-cli` supports secret chat: https://github.com/kenorb-contrib/tg

Thanks! Does that mean it shouldn't be hard to copy its functionality into telegram-destop?

**Comment by aBARICHELLO** [comment]
Yes but as you can see by #871 they aren't willing to cooperate. I hope someone forks and implements secret chats

**Comment by dm17** [comment]
> Yes but as you can see by #871 they aren't willing to cooperate. I hope someone forks and implements secret chats

They're acting weird. At the end of that thread the developer agreed that it should be done. Then he asked questions about it. Then he deleted his GitHub profile.
I hear that Telegram is trying to prevent it because of the potential of someone taking screenshots of secret chats using Linux... I don't have any source for it, so just considered hearsay at this point.

**Comment by aBARICHELLO** [comment]
'Taking screenshots' and 'the messages are stored locally' are stupid arguments agains secret chats. Even on mobile there are ways to bypass that. It's clearly not the main feature of Secret Chats

**Comment by RememberTheAir** [comment]
> At the end of that thread the developer agreed that it should be done. Then he asked questions about it. Then he deleted his GitHub profile.

Clarification: the developer is (at)john-preston and he did not delete his account

> I hear that Telegram is trying to prevent it because of the potential of someone taking screenshots of secret chats using Linux... I don't have any source for it, so just considered hearsay at this point.

I am in no way involved in Telegram, but as far as I know there are two main reasons secret chats are not implemented in the desktop client:
- the desktop app doesn't implement any kind of reliable/secure enough local messages storage, and implementing that would apparently require a huge refactoring of the codebase, apparently
- secret chats missing on desktop is kind of a feature, as per [Telegram words](https://tsf.telegram.org/manuals/e2ee-simple#one-device-secret-chats-are-a-feature)

**Comment by Aokromes** [comment]
> They're acting weird. At the end of that thread the developer agreed that it should be done. Then he asked questions about it. Then he deleted his GitHub profile.

Again he don't deleted the account, the profile was converted to a organization and that made the account to look deleted, preston is the developer account.

**Comment by dm17** [comment]
@john-preston Is it possible to open a new thread on this issue, considering that yours was locked (and I don't see why)? Your questions at the end were not answered & it seems you had agreed that it should be done (secret chats for the Linux app).

**Comment by john-preston** [comment]
@dm17 Where the idea that the ghost author of the "@telegramdesktop after reading the entire thread.." blabla message is the app developer? It is not. It is just some unknown guy.

**Comment by dm17** [comment]
> @dm17 Where the idea that the ghost author of the "@telegramdesktop after reading the entire thread.." blabla message is the app developer? It is not. It is just some unknown guy.

Thanks... I was led by @Aokromes & @RememberTheAir to believe it was you who was the developer who had been in charge of that thread.

**Comment by john-preston** [comment]
@dm17 I'm the developer, I've replied there several times. The fact that GitHub replaced the @telegramdesktop user to "ghost" when the account was changed to an organization — sucks. No easy way to divide it from other deleted users now.

**Comment by dm17** [comment]
> @dm17 I'm the developer, I've replied there several times. The fact that GitHub replaced the @telegramdesktop user to "ghost" when the account was changed to an organization — sucks. No easy way to divide it from other deleted users now.

Ya no problem with that... So great that you replied here... I'm just hoping to get the word straight from you: is it possible to get code that enables "secret chats" in the Linux desktop app merged?
Thanks.

**Comment by john-preston** [comment]
@dm17 I say that PR with a secret chat option won't be merged because I can't imagine anyone to produce such PR in such quality that it could be merged. It is a very big task that will have changes in almost all of the application logic and a huge amount of UI changes that should be discussed with the designer of the current interface, so I just don't see any reason to discuss the PR of secret chats in tdesktop — no one will do it.

For example, multiple accounts support is a much easier feature and it has a much less UI integration and still no one PR-ed it (and no one will, but I hope to implement it some day).

**Comment by dm17** [comment]
> @dm17 I say that PR with a secret chat option won't be merged because I can't imagine anyone to produce such PR in such quality that it could be merged. It is a very big task that will have changes in almost all of the application logic and a huge amount of UI changes that should be discussed with the designer of the current interface, so I just don't see any reason to discuss the PR of secret chats in tdesktop — no one will do it.
> 
> For example, multiple accounts support is a much easier feature and it has a much less UI integration and still no one PR-ed it (and no one will, but I hope to implement it some day).

It is so impossible that the policy should be to close & lock any threads about it to disincentivize folks from even trying? Can we at least leave an open thread for it?

Considering the amount of people using Telegram - and the fact that other platforms have multiple fully implemented clients (i.e. Telegram X)... I strongly suggest reconsidering - or at least allowing developers to congregate in a thread about it without it getting closed/locked.

Thanks.

**Comment by john-preston** [comment]
@dm17 The discussion in such threads usually falls somewhere between asking for the feature being implemented, declarations, that someone quits Telegram because of it not being implemented and advertising of some unrelated to Telegram Desktop products, that have e2e, but have their own problems.

Such discussions require moderation, there will always be offended by the moderation, that will start offending others even more, and no practical sense. I don't encourage them, because they'll draw attention and take time, but they won't produce anything, because it is too complicated.

I don't say that implementing secret chats is impossible — Telegram X or Unigram have them, they both are built on base of TDLib. I say that no one from the community will implement them in Telegram Desktop (because one of the easiest ways to do that for someone unrelated to Telegram Desktop codebase, I think, is to migrate Telegram Desktop to TDLib, and this means completely rewriting most part of it).

**Comment by dm17** [comment]
> , but they won't produce anything, because

OK since you just confirmed my comment about it being totally possible - just difficult - then perhaps you'll allow discussions here... Because where else could be better for a discussion helping promote TDLib rewrite be?

Your anticipation of negativity doesn't seem to match the sentiment, enthusiasm, and ingenuity of the Linux developer community.

**Comment by aBARICHELLO** [comment]
Ok, this gives enough context without having to read a 300 comment thread from years ago.  
Maybe link to this explanation when closing duplicate issues so people are on board with the situation.

**Comment by john-preston** [comment]
@dm17 I doubt that rewriting tdesktop on tdlib is much easier than borrowing some UI controls from here and writing a new app on tdlib from scratch. But sure, you can discuss it here.

**Comment by dm17** [comment]
Have you guys seen any progress on this topic?

**Comment by RememberTheAir** [comment]
Pavel durov said that they're planning to introduce "secret groups" on desktop too: https://t.me/durovschat/518625

As always, a Durov's "soon" might mean months or years, but maybe there's something moving

**Comment by ilya-fedin** [comment]
> Your anticipation of negativity doesn't seem to match the sentiment, enthusiasm, and ingenuity of the Linux developer community.

But tdesktop has nothing to do with Linux developer community :thinking: 
Everyone sees that tdesktop has proprietary-like developing process...

**Comment by dm17** [comment]
> > Your anticipation of negativity doesn't seem to match the sentiment, enthusiasm, and ingenuity of the Linux developer community.
> 
> But tdesktop has nothing to do with Linux developer community 
> Everyone sees that tdesktop has proprietary-like developing process...

Sure it does... Because that is who uses it... And Linux users are developers all over; I would imagine & hope at the Telegram company itself: or else what do they run on their servers ;)
Speaking of servers... It would be great if they released telegram-server (like wire-server) so we can run our own private instances.
