### ISSUE TITLE
Default interface scale doesn't adapt to the monitor's scale in Windows 10

### ISSUE THREAD

**Issue by Guibuu** [telegramdesktop/tdesktop#8072]
### Steps to reproduce
Hi!

In Windows 10 my principal monitor has text scaled at 150%. My secondary monitor has text scaled at 100%. When I open Telegram with the "Default interface scale" option enabled, the interface scales at 150%, even if the window appears at my secondary screen. This interface scale affects both the application and the menu in the tray icon.

### Expected behaviour
**"Default interface scale" option should adapt the application scale depending on the monitor where it is displayed**, as with other applications such as Windows Explorer. This includes the application window and the tray icon.

### Actual behaviour
"Default interface scale" option always scales the application and the tray icon to the principal screen scale.

### Workaround
Turn off "Default interface scale" and establish the application scale manually for both the window and the tray icon.

### Configuration
**Operating system:** Windows 10 ProN (10.0.18363)
**Version of Telegram Desktop:** 2.1.10
**Used theme:** Default

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/1121
