### ISSUE TITLE
Auto-correct when spellchecking

### ISSUE THREAD

**Issue by WhyNotHugo** [telegramdesktop/tdesktop#8073]
### Is your feature request related to a problem?

Telegram's spell checker is exceptionally good (kudos on that!). Close to 100% of the times, the errors detected are correct, and the first suggestion is the right choice. However, I've to move my hand away from typing to point-and-click to apply suggestions.

### Describe the solution you'd like

I'd definitely _love_ to have [probably optional] auto-correction; e.g.: if there's an error detected, apply the first suggestion.

I say "optional" since I'm sure so many people would completely hate to see this on by default.

### Describe alternatives you've considered

Having a hotkey to just "fix last error" would work perfect too. Or maybe other forms of keyboard-triggered spell-checking?

### Additional context

Not much to add. I've no idea if this is an extremely complicated feature, of if it's something easy to address; I'll admit I'm entirely ignorant of how the whole input/spellchecking works.

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/5268

**Comment by ilya-fedin** [comment]
> #5268

That ticket is about macOS' native autoreplacement feature and has nothing to do with the spellchecker
