### ISSUE TITLE
Notiifcation issues with GNOME Wayland

### ISSUE THREAD

**Issue by jacob-emery** [telegramdesktop/tdesktop#8074]
The bug described in the following link seems to be solved for sway.
https://github.com/telegramdesktop/tdesktop/issues/7591
https://github.com/telegramdesktop/tdesktop/pull/7898
However, the issue persist on GNOME Wayland.

Additionally, on Arch Linux there is a problem with native notifications: if you try to directly reply or click on "open telegram/conversation" button inside the notification bar, nothing should happen (it is just like you ignored the notification).
If you minimize Telegram (therefore close the window), the described above problem should not be present (but since I don't want apps to run in the background, this is a relevant issue).

OS: Arch Linux
DE: Gnome Wayland
Telegram Version: 2.1.11
Telegram is run on Wayland (therefore not with Xwayland)

The same happens also on a friend's machine running Fedora 32.

**Comment by ilya-fedin** [comment]
> The bug described in the following link seems to be solved for sway.

Only tiling of these notifications was solved. It is impossible to fix notifications position since Qt doesn't provide sufficient APIs. Sorry.

**Comment by jacob-emery** [comment]
Thank you for explaining this.

However, is it possible to fix native notifications on Gnome Wayland (if you enable native notifications in Telegram settings)? It would be better if the user could at least raise the Telegram window when clicking on them.

**Comment by ilya-fedin** [comment]
> However, is it possible to fix native notifications on Gnome Wayland (if you enable native notifications in Telegram settings)?

No, if you run tdesktop in terminal, you'll see `qt.qpa.wayland: Wayland does not support QWindow::requestActivate()`

**Comment by jacob-emery** [comment]
Yes, it is exactly like you said.
I guess all we can do is wait until it gets fixed.

**Comment by ilya-fedin** [comment]
> I guess all we can do is wait until it gets fixed.

As far as I know, there are no focusing API in Wayland for security reasons.
And there are no signs that it would be changed
Probably, GNOME devs should add focusing feature into the notification daemon since it uses private compositor API (e.g. by a click on the notification itself or by a click on a button with a predefined action name).

I don't know how that could be solved otherwise.

**Comment by ilya-fedin** [comment]
@jacob-emery can you remove gnome from the title to let the issue be "Notifications issues with Wayland"?
