### ISSUE TITLE
Reaching telegram for help

### ISSUE THREAD

**Issue by noxecane** [telegramdesktop/tdesktop#8076]
Sorry I have to do this here as I've run out of options. I found some telegram channels (actually a web of such) whose primary purpose is revenge porn or at least is part of their emo. I've been reporting them(not all of them at first) to the `abuse@telegram.org`  since the 7th of June. No lie they've banned 2 of them, but I don't know if it's due to my report or someone else because no one is replying and not all of them are banned. I understand the support team is volunteer-based so if there's anything else they'll need me to do to help I can help.

In case they don't know who asked, you can request for my Gmail account

**Comment by Aokromes** [comment]
this is only for telegram desktop client issues, not for abuse. no one here can help you.
