### ISSUE TITLE
Telegram on Flatpak doesn't show asian characters

### ISSUE THREAD

**Issue by veronikazaglotova** [telegramdesktop/tdesktop#8078]
### Steps to reproduce
1. Install Telegram Desktop via Flatpak
2. Paste Chinese/Korean/Japanese characters in any text field or send anyone a link to a Youtube video that contains a C/J/K character
3. See how every C/J/K character shows up as a rectangle [(example)](https://imgur.com/a/RV2jb54)

### Expected behaviour
It should show me C/J/K characters

### Actual behaviour
It shows me stupid rectangles

### Configuration
**Operating system:** NixOS

**Version of Telegram Desktop:** 2.1.7

**Installation source** - flatpak

**Used theme**: Default

**Comment by ilya-fedin** [comment]
flatpak can't use system fonts on NixOS due to the specific paths, this is not a tdesktop issue
