### ISSUE TITLE
[Feature Request] Better privacy settings/antispam

### ISSUE THREAD

**Issue by rdlrt** [telegramdesktop/tdesktop#8079]
### Is your feature request related to a problem?
Over past couple of years, Telegram has been attracting lot of spammers across various _public_ super groups - especially related to financial platforms. While we can prevent Messages typed in groups via bots, scammers have been able to utilise telegram's weaknesses in two ways:
1. A proxy account can join the group and download user's list in the group
2. Use another account to directly DM members of that group.

### Describe the solution you'd like
1. Option to restrict who can see members in a group to Administrators.
2. A default option to reduce who can privately message you to "My Contacts Only"

### Describe alternatives you've considered
- Making public group private is not an option. Even then, a user can still join the group and attract members.
- Making educational posts for users to beware and alerting every new joinee.
The above does not help much - as most of the users (annoyingly) dont read the warnings.

### Additional context
There have been thousands of cases where naive/noob users have been scammed of thousands/millions and its high time these limitations of the platform should be addressed.

**Comment by Aokromes** [comment]
sotty this doesn't belongs to telegram desktop instead to in app support.

**Comment by rdlrt** [comment]
@Aokromes - havnt received any replies from In-App support. Besides, I see that these are mainly volunteers - do we expect volunteers to implement feature requests?
I do not see this as a Q&A type of query that I can discuss with someone - if they get back to me

**Comment by ilya-fedin** [comment]
> do we expect volunteers to implement feature requests?

how volunteers can implement a server-side feature? :monocle_face:

**Comment by rdlrt** [comment]
@ilya-fedin exactly - thus, its a circle - We cannot get this feature implemented via In-App support, and opening issue in github is considered wrong because its not a telegram desktop query.

So the only hope is volunteers relaying the message if they deem fine, and it gets into a backlog that's not really visible to us(?)

**Comment by ilya-fedin** [comment]
Who do you call volunteers?

**Comment by rdlrt** [comment]
The In-App Support team that is supposed to handle our feature requests, which will be based on [tsf](https://tsf.telegram.org/manuals/feature_philosophy) manual

**Comment by ilya-fedin** [comment]
Oh, I misunderstood you

**Comment by Aokromes** [comment]
> @Aokromes - havnt received any replies from In-App support. Besides, I see that these are mainly volunteers - do we expect volunteers to implement feature requests?
> I do not see this as a Q&A type of query that I can discuss with someone - if they get back to me

from what i was told when i tell on "semi-official" groups they have access to internal bug tracker.

**Comment by rdlrt** [comment]
Hmm its a bit sad tho..it might take months/years at this rate to implement something that shouldnt cause a redesign or too big a breaking change (i.e. option # 2 in the suggestion)
`A default option to reduce who can privately message you to "My Contacts Only"`
I guess all I can do is rest my case with "at least we tried" :)

**Comment by Aokromes** [comment]
you may also can try twiteer, i am with you with more settings to stop spammers are needed, but they don't belong here.
