### ISSUE TITLE
[Feature Request]: Mentioned/Replied you chats folder

### ISSUE THREAD

**Issue by erfanium** [telegramdesktop/tdesktop#8082]
I have a lot of groups, It would be great if there was a folder where I could see the groups that I mentioned or replied there. so I can answer them quickly.

**Comment by RememberTheAir** [comment]
If you don't have unmuted groups, the following filters will do the job:

- inclusive filters: groups
- exclusive filters: muted, read

In this folder you'll see all the groups in which you have unread mentions (+ all your unmuted groups, if any)

**Comment by erfanium** [comment]
@RememberTheAir Thanks, but better to work with all groups (muted or unmuted)

**Comment by yashpalgoyal1304** [comment]
wow, smth similar is present after tdesk 2.4 (tgand 7.1) update. See the [changelog](https://t.me/tgbetachat/414294)

![hw5pUMiq8l](https://user-images.githubusercontent.com/19423063/95664353-bd918d80-0b64-11eb-8720-d532831d76bf.png)

**Comment by erfanium** [comment]
@yashpalgoyal1304 It doesn't work with mentions

**Comment by yashpalgoyal1304** [comment]
@erfanium I know. i mentioned that Reply bot feature in the sense that this
issue's request can be built upon or take inspiration from that.

**Comment by RememberTheAir** [comment]
Quick workaround: input "#m" or "@" in the search query to see all your mentions/replies in all your group chats
