### ISSUE TITLE
MalwareBytes treats Windows installer as malware

### ISSUE THREAD

**Issue by AisteruFire** [telegramdesktop/tdesktop#8083]
I know this might be due to MalwareBytes or even my setup, but I still wanted to report it if by any chance it is not.

### Steps to reproduce
1. Install MalwareBytes Premium 4.1.0
2. Go on https://desktop.telegram.org/
3. Download the installer for Telegram for Windows
4. Execute the .exe file

### Expected behaviour
The installer should start normally and install Telegram

### Actual behaviour
The installer is quarantined by MalwareBytes as Malware.Generic.753018032 and the installation never starts

### Configuration
**Operating system:**
Windows 10.0.19041.329

**Version of Telegram Desktop:**
2.1.10

**Comment by john-preston** [comment]
@AisteruFire

Please submit a false positive report here:

https://support.malwarebytes.com/hc/en-us/articles/360038523234-Report-false-positive-found-with-Malwarebytes-Endpoint-Security

They accept them only from their users :/

**Comment by bbpgrs** [comment]
In my case, I'm able to install it but MalwareBytes detects Updater.exe as malware and quarantines it.
