### ISSUE TITLE
Portion of text disappears when switching language during type

### ISSUE THREAD

**Issue by moosapour-arash** [telegramdesktop/tdesktop#8085]
### Steps to reproduce
*0. i think this is caused by save-draft feature so you need at least two active session on telegram account
1. you need at-least two input languages active on your machine
2. start typing with one of them then switch (ctrl+space) to the other one and go on 
3. try to frequently switch languages, after some tries you will see all the text after last language-switch is gone  (can be brought back by ctrl+z)

### Expected behavior
based on my findings there is onBlur-like event on the chat screens, when i switch from telegram app to another app the current typed draft will get synced across all sessions.(same happens in android if you switch activity or press the back button) cool feature.   
But it seems that switching language with ctrl+space  (default hot-key in gnome) is considered as a context switch and raises draft-sync event despite the fact you are still typing, so if you type fast enough before sync is complete you will get some text loss.    
**expected behaviour**  is to not sync the draft on language-switch or even on window switch immediately, maybe an small time-window like 1 sec or so would be enough 

### Configuration
**Operating system:**
Linux 5.6.16-1-MANJARO x86_64 20.0.3 Lysia
But for me happened in ubuntu too
**Version of Telegram Desktop:**
#v 2.1.10 05.06.20

**Comment by ilya-fedin** [comment]
#4922
