### ISSUE TITLE
[Feature Request] regular expression search in Telegram

### ISSUE THREAD

**Issue by pavel-the-best** [telegramdesktop/tdesktop#8087]
### Is your feature request related to a problem?
Sometimes search in Telegram Desktop outputs too many results or doesn't output anything at all. This could be solved by adding a feature-rich search variant.

### Describe the solution you'd like
I want a switcher in search field (which could be hidden by default): use regular expression search and usual search.

### Describe alternatives you've considered
Add an ability to configure search options (for example, should the plural form of the search term appear in search results).

**Comment by RememberTheAir** [comment]
Chat search is done server-side, so tdesktop cannot do anything about it :(

**Comment by pavel-the-best** [comment]
How should I pass this request to Telegram platform?

**Comment by RememberTheAir** [comment]
You should suggest this via the in-app support or on Twitter (tag @telegram)
