### ISSUE TITLE
Notification issues with KDE Plasma Wayland

### ISSUE THREAD

**Issue by pavel-the-best** [telegramdesktop/tdesktop#8088]
### Steps to reproduce
1. Open Plasma Wayland session.
2. Open Telegram Desktop
3. Configure to use non-native notifications at the bottom right corner.
4. Trigger a few non-native notifications

### Expected behaviour
Notifications should stack at the bottom right corner of the screen

### Actual behaviour
Notifications don't stack and appear at the top left corner of the screen

### Configuration
**Operating system:**
5.6.4-gentoo GNU/Linux

**Version of Telegram Desktop:**
2.1.7

**Installation source (Linux Only)** - Gentoo package `net-im/telegram-desktop`

**Used theme**:
Night

![image_2020-06-17_20-11-53](https://user-images.githubusercontent.com/38429428/84928376-f8177c00-b0d6-11ea-9aa2-c4243afc71a7.png)

**Comment by ilya-fedin** [comment]
Already fixed in dev branch
