### ISSUE TITLE
[Feature Request] Chat text with setting

### ISSUE THREAD

**Issue by kvishnivetsky** [telegramdesktop/tdesktop#8092]
### Is your feature request related to a problem?
My laptop display is "wide"(16:9). When I set Telegram application windows to a full screen, there is an unused space in chat window. But I often send/receive texts with rather long lines.

### Describe the solution you'd like
I want to have an opportunity to configure chat text filed width(line length) in application configuration. This setting will make possible to set chat area width in characters.

### Describe alternatives you've considered
Also it may be a feature of **Wrap text in chat: on/off/scroll**. So when ON: it behaves as in current state. In OFF: it use as much space for text as it possible whithout "scrolling". In SCROLLL: there will be horizontal scroller in chat window.

### Additional context
-

**Comment by ilya-fedin** [comment]
#2060 
#7993
