### ISSUE TITLE
[Feature Request]  Drag and Drop folder

### ISSUE THREAD

**Issue by benhacka** [telegramdesktop/tdesktop#8095]
### Idea
Hey, what is about releasing the "TG swift feature" - Drop'n'Drag folder as a zip archive? I think it's a handy feature for many people. 

### Swift realization

- [archive realization](https://github.com/overtake/TelegramSwift/blob/dcb31364f5f7ffdf04d14b4ec487d38030d8585c/Telegram-Mac/ArchiverContext.swift). They have used native swift Zip lib, but I think that it's not a problem to find cross-platform lib or wrapper for C++. ([libzip for example](https://libzip.org/))
- [file type realiztion](https://github.com/overtake/TelegramSwift/blob/3fdc53a43a7c832ed1dac7e643569eb92730f5e3/Telegram-Mac/SenderController.swift)
- [GUI wrapper realization](https://github.com/overtake/TelegramSwift/blob/3fdc53a43a7c832ed1dac7e643569eb92730f5e3/Telegram-Mac/ChatController.swift)

I think it's an excellent idea for ~steal~ borrowing

**Comment by ilya-fedin** [comment]
#5356
