### ISSUE TITLE
Telegram data exports freeze if there is broken/undownloadable media with no option to skip such media

### ISSUE THREAD

**Issue by gataria** [telegramdesktop/tdesktop#8098]
#### This behavior is difficult to reproduce, given that I can't *send* the broken media. However, the prerequisite to reproducing this behavior is to happen to have a broken image in a message.
1. Find a message with media that cannot be rendered in a Telegram client. See the following, captured on Telegram Desktop and Telegram X:
![image-not-rendering-tg-desktop](https://user-images.githubusercontent.com/26052518/85110216-2630b500-b1d8-11ea-9ec0-2e16bb602346.gif)
The media here is attempted to be downloaded, but clicking performs no action.
![image-not-rendering-tg-x](https://user-images.githubusercontent.com/26052518/85110225-29c43c00-b1d8-11ea-8bf4-1731e8df31e3.gif)
The media here is attempted to be downloaded, but the download is automatically stopped without user intervention.

2. Start the Telegram data export.
3. Wait for the export to reach the specific chat message.
### Expected behaviour
The inability to download an image (where it is impossible to be selective about what data is exported, such as what specific groups should be exported) should be met with a sort of timeout (as referenced in issue #6423), or the ability to skip a message containing problematic media (perhaps by substituting the media with a placeholder).

### Actual behaviour
The user is unable to progress with their data export, and they might be forced to delete certain messages (which is not always possible), or they're forced to leave a group/channel, rendering it unable to be backed up.

### Configuration
**Operating system:**
Windows 10, version 2004 (build 19041.329)

**Version of Telegram Desktop:**
Version 2.1.12

<details><summary><b>Logs</b>:</summary>
I will not attach my full log.txt, however, what I can mention is that my log.txt contains many instances of the line:

`<time and date> RPC Error: request <request number> got fail with code 400, error FILE_REFERENCE_EXPIRED`
There are hundreds of lines within the log that contain this line over the course of my entire data export, however, a large chunk of log messages following this format in the log are within the time range where the client attempted to retrieve the problematic media.
While, again, this message did appear in other places within the log, I saw the export process proceed without issue then, which might mean that the message isn't all-too-relevant. However, I think it's worth mentioning.
Also, if it is relevant, then I should note that this error [is referenced in Telegram's API documentation](https://core.telegram.org/api/file_reference), which might be of use.
</details>

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/6670
