### ISSUE TITLE
[Feature Request] Folders notification control

### ISSUE THREAD

**Issue by hazzus** [telegramdesktop/tdesktop#8099]
### The problem
That would be great to control notifications of the entire folder. Use case: I want only to get notifications from folder "Work" from 8.00 till 20.00 from Monday to Friday. Except mentions, of course

### Solution I'd like
At least a right-click option on folder "Disable notifications". At maximum - fully managed control of notifications for folders with exact time of notification disabling management.

**Comment by chachi85** [comment]
MR. RUBIN ALLEN
