### ISSUE TITLE
Enable more input methods

### ISSUE THREAD

**Issue by daobrien** [telegramdesktop/tdesktop#810]
Using Telegram on Fedora 21 I can't use any Chinese or Korean input methods. Italian and Spanish appear to work ok. I can use each of these langs ok in other applications.

**Comment by tramchamploo** [comment]
same here

**Comment by Katzen-Gott** [comment]
Please, check if problem is already reported before adding an issue.
There is already #529 #631 #343 #375 #831

**Comment by telegramdesktop** [comment]
Please check out 0.8.50 dev version, it should be fine there, I've added Qt plugins for IBus and Fctix.
