### ISSUE TITLE
Keyboard accessibility of Edit->Delete and Cancel Editing dialogues

### ISSUE THREAD

**Issue by Dessix** [telegramdesktop/tdesktop#8100]
### Steps to reproduce
1. Edit a message, deleting its contents 
2. Press enter
3. Try to tab between `cancel` and `delete` on the "Do you want to delete this message?" prompt 

### Expected behaviour
- One of `cancel` or `delete` should, by default, be highlighted as selected.
- `tab` and `shift-tab` should switch between them.
- Pressing `enter`, `return`, or `space` should accept the selected item.

### Actual behaviour
- `delete` seems to be selected based on behaviour, but tab 
- `tab` and `shift-tab` appear to have keyboard focus on the chat window, not the popup. This results in expanding the chat-contacts bar on the left as if you had pressed tab inside the message textbox.
- Pressing enter on an empty message seems to confirm the `delete`, but space types into the message textbox which still has focus.

### Configuration
**Operating system:**
Linux, but I've seen this issue on Windows builds as well.

**Version of Telegram Desktop:**
2.1.12

**Installation source (Linux Only)** - the official website / GitHub releases / flatpak / snap / distribution package:
Official website

**Used theme**:
Default theme in night mode

**Side note**: This UI keyboard-accessibility issue also occurs when attempting to cancel editing by pressing escape while editing a message, in the "Cancel editing?" prompt.

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/2109
