### ISSUE TITLE
[Feature Request] Easier to add conversations to folders

### ISSUE THREAD

**Issue by xmha97** [telegramdesktop/tdesktop#8101]
To manage folders, we need to enter the settings each time, and this is time-consuming.
Please add this feature:
![image](https://user-images.githubusercontent.com/23485114/85183632-9eaf7880-b2a1-11ea-9ae1-413f68dbebac.png)
It's also a good idea to drag and drop conversations to folders.
Thanks

**Comment by ilya-fedin** [comment]
#7927
