### ISSUE TITLE
"Update Telegram" doesn't update, merely shuts down the application

### ISSUE THREAD

**Issue by eyalroz** [telegramdesktop/tdesktop#8103]
### Steps to reproduce
1.  (Magic?)
2.  The "Update Telegram" notification appears
3.  Press "Update Telegram"
4. Wait
5. Start Telegram

### Expected behaviour
New version should be installed

### Actual behaviour
Old version comes up (checked at the bottom of the Left-hand-side menu)

### Configuration
**Operating system:** Devuan GNU/Linux Beowulf (= Debian Buster without systemd)

**Version of Telegram Desktop:** 2.1.2

**Installation source (Linux Only)** - package from the ataero Telegram PPA:
```
deb http://ppa.launchpad.net/atareao/telegram/ubuntu bionic main
```
mentioned also [here](https://askubuntu.com/questions/425716/how-to-install-telegram).

**Used theme**:
Default, I guess.

**Log:** Where's the log at?

**Comment by ilya-fedin** [comment]
> package from the ataero Telegram PPA:

You can't upgrade a package with in-app button
Contact package maintainer to disable autoupdates

**Comment by eyalroz** [comment]
@ilya-fedin : I realize I can't upgrade the package with the in-app button (although theoretically the upgrade mechanism could upgrade the app with files that are outside the package, but never mind that...)

The point is, that the app should not let you believe you can upgrade it when in fact you can't. That is, either the button should not appear at all, or there should be some notification about why an upgrade is impossible.

**Comment by ilya-fedin** [comment]
> That is, either the button should not appear at all

That's a work for the package maintainer

**Comment by eyalroz** [comment]
@ilya-fedin : Still, the "Update Telegram" tries to do something, and is failing. I believe you should make the update-related code more robust, so that either it doesn't propose the update, or gives some indication regarding how the update failed. I'm betting there are at least a few places where you're making certain assumptions which are partially unfounded, and you could perform "sanity checks" instead.

**Comment by ilya-fedin** [comment]
> . I believe you should make the update-related code more robust, so that either it doesn't propose the update

Package maintainer should disable autoupdate. He has all the tools for this.
