### ISSUE TITLE
Album preview support for Nitter.

### ISSUE THREAD

**Issue by arthurrasmusson** [telegramdesktop/tdesktop#8107]
Can we get album previews for https://nitter.net?
Nitter is a tracking sanitized front end for Twitter.
Here's the same Tweet preview in Telegram side by side via Twitter & Nitter (_as you can see one previews with the full album of images and the other only shows one image_):

![image](https://user-images.githubusercontent.com/47877520/85211649-300e0180-b319-11ea-9ebc-f55fa4e7f048.png)

**Comment by RememberTheAir** [comment]
You should bring that to the in-app support or on [Twitter](https://twitter.com/telegram), as webpage previews are rendered server-side (so tdesktop can do nothing about this)

**Comment by Aokromes** [comment]
such feature belongs to https://bugs.telegram.org/
