### ISSUE TITLE
Emoji popup closes unexpectedly in Synaptics touchpad and certain scroll settings

### ISSUE THREAD

**Issue by noquierouser** [telegramdesktop/tdesktop#811]
The issue happens with Synaptics touchpad and using edge scrolling, vertical and horizontal. Doesn't happen if two-finger scrolling is used.

https://www.youtube.com/watch?v=wVyCHfvDNzM

**Comment by angelbladex** [comment]
Telegram crash when i try choose a emoji on my Laptop =(
(Telegram 0.8.23 dev 32 bits on ArchLinux )

**Comment by angelbladex** [comment]
Checking... on Telegram 0.8.28 Dev, this problem is solved for me. =)
