### ISSUE TITLE
Saved messages disappeared!

### ISSUE THREAD

**Issue by yar72** [telegramdesktop/tdesktop#8110]
Hey there
My telegram "saved message" disappeared today. I didn't delete it. What's problem?

**Comment by yar72** [comment]
My saved messages were disappeared!
How can I recover them?

**Comment by yar72** [comment]
Can anybody help me?!

**Comment by Aokromes** [comment]
they are present on your android or ios device? if no, no one here can help you.

**Comment by Aokromes** [comment]
@yar72

**Comment by Aokromes** [comment]
no answer after more than 2 months, closing.
