### ISSUE TITLE
No sound in voice calls Windows 10 insider

### ISSUE THREAD

**Issue by ahmedflix25** [telegramdesktop/tdesktop#8112]
the default Output Device is set to default in the app
sounds in media play just fine but in voice call you can't hear the other person 
you need to go to call settings and change the Output Device yourself to the working one 

the other person also can hear you fine and even when Input Device is set to Default

### Steps to reproduce
1. Install Telegram from the Microsoft Store
2. Make sure that Output Device is set to Default
3. Make a voice call

### Expected behaviour
you can hear the other person and they can hear you

### Actual behaviour
you can't hear the other person but they can

### Configuration
Windows 10 Pro 2004 build 20150.1000

**Version of Telegram Desktop:**
2.1.10

**Used theme**:
Dark

**Comment by Aokromes** [comment]
maybe the bug is on the other side https://github.com/telegramdesktop/tdesktop/issues/7688

**Comment by ilya-fedin** [comment]
I guess this information would be helpful: https://github.com/telegramdesktop/tdesktop/issues/7562#issuecomment-673643903

**Comment by Aokromes** [comment]
@ahmedflix25

**Comment by ahmedflix25** [comment]
my problem is not the calls my telegram setup treat my microphone like it doesn't exist

trying the in-app microphone test doesn't work either but the microphone work everywhere else outside telegram and windows 10 can see that telegram accessed my microphone

**Comment by ilya-fedin** [comment]
> my telegram setup treat my microphone like it doesn't exist

What does this mean?

> trying the in-app microphone test doesn't work either

It is broken #7296

> my problem is not the calls

But your first message says that you problem is the calls

>  3\. Make a voice call

**Comment by ahmedflix25** [comment]
oh after you mentioned me i tried it again and the microphone test wasn't working so i thought the problem happens even before the call i will try another call again

**Comment by ilya-fedin** [comment]
Btw, according to screenshot a removed output device is set

**Comment by ahmedflix25** [comment]
it's like that only when i select "default" as output and even like that videos and other media play sound fine

**Comment by ahmedflix25** [comment]
i selected another device selected default again and now it show up as default

also i can still send voice messages but when i make i call and the other person answer it get cancelled and tells me i have a bad sound card

![image](https://user-images.githubusercontent.com/7858946/92461729-e4594e80-f1c9-11ea-96a0-81300e0091ec.png)

**Comment by ilya-fedin** [comment]
> also i can still send voice messages

Calls and voice messages are using different libraries

>  but when i make i call and the other person answer it get cancelled and tells me i have a bad sound card

Please get a log
https://github.com/telegramdesktop/tdesktop/issues/7562#issuecomment-673643903

**Comment by ahmedflix25** [comment]
that debug mode didn't work i re-installed the app from the store and everything works now

**Comment by ilya-fedin** [comment]
You can close the issue then
