### ISSUE TITLE
[Feature Request] Ability to search message replies

### ISSUE THREAD

**Issue by slawwan** [telegramdesktop/tdesktop#8113]
### Is your feature request related to a problem?
I want to search all replies for the message and navigate to them

### Describe the solution you'd like
Add one more item for the message context menu
 - for single reply: "go to reply"
 - for several replies: "view replies" to show them like search results on the left pannel with ability to navigate them

**Comment by RememberTheAir** [comment]
I'm all about this feature but this should be implemented server-side through a new search filter

**Comment by Aokromes** [comment]
such feature belongs to https://bugs.telegram.org/
