### ISSUE TITLE
After file upload (via drop) the file handle isn't closed until the chat is closed.

### ISSUE THREAD

**Issue by AgentFire** [telegramdesktop/tdesktop#8116]
### Steps to reproduce
1. Open chat with someone.
2. Drop some funny short mp4 video file and have a good laugh with your partner.
3. Try to delete the file from the OS - Windows (10x64) will say that it is open in Telegram
4. Switch to some other chat with any other person.
5. After the switch the OS can delete the file.
6. If you switch back, the file wouls still be deletable.

### Expected behaviour
The file handle should be closed right after the upload, and I should be able to do as I please with it.

### Actual behaviour
The file handle is not released right after the upload.

### Configuration
**Operating system:**
Microsoft Windows [Version 10.0.18363.836] (x64)

**Version of Telegram Desktop:**
2.1.2

**Used theme**:
Dark.

<details><summary><b>Logs</b>:</summary>
No useful details found in the log.
</details>

**Comment by ilya-fedin** [comment]
#7818

**Comment by john-preston** [comment]
@AgentFire If when you look at it in the chat it is still played then it's played from the hard disk :( It could be really moved to cache or smth, but this should be coded explicitly, no such code right now. If you close the chat, remove the file, and reopen the chat, it will start streaming from the cloud, there will be a lag / delay before it starts playing.
