### ISSUE TITLE
[Feature Request] Create Groups/Categories in contact list

### ISSUE THREAD

**Issue by WuglyakBolgoink** [telegramdesktop/tdesktop#8122]
### Is your feature request related to a problem?

My problem is - 

I have about 20+ groups/channels (for example - ios developers, android, angular, etc) and this groups are mixed together with my normal contact list.

### Describe the solution you'd like
A better case to have custom groups/categories which we can add manually. and move all channels into this custom groups. 

Same as Archive folder:
![image](https://user-images.githubusercontent.com/2271337/85376129-98d2c500-b537-11ea-9314-fcad2159f19d.png)

![image](https://user-images.githubusercontent.com/2271337/85376168-aab46800-b537-11ea-8135-9af04fb626cd.png)

For example:

what I have now:

  - @Max
  - @Tom
  - @iOS
  - @Android
  - ..
  - @js
  - @angular
  - ..
  - @Mom
  - @Dad
  - @other_unsorted_contact

What I will have:

- Work_Contacts
  - @Max
  - @Tom
- Mobile_DEV
  - @iOS
  - @Android
  - ..
- Web_DEV
  - @js
  - @angular
  - ..
- Home
  - @Mom
  - @Dad
- @other_unsorted_contact

**Comment by RememberTheAir** [comment]
Settings -> folders
