### ISSUE TITLE
Problem with displaying the sender's name in the chats list

### ISSUE THREAD

**Issue by sepehr-brj** [telegramdesktop/tdesktop#8125]
There's a problem with showing account names with special fonts. like this:

![Capture2](https://user-images.githubusercontent.com/55192376/85415403-89c53480-b582-11ea-8552-82f2e48e918b.JPG)

But there is no problem with his name when typing or when he sends media:

![Capture](https://user-images.githubusercontent.com/55192376/85415392-8762da80-b582-11ea-8171-0c9496066793.JPG)
### Configuration
**Operating system:** Windows 7

**Version of Telegram Desktop:** 2.1.12

**Used theme**: tined

**Comment by ilya-fedin** [comment]
#6056
