### ISSUE TITLE
MalwareBytes detects Updater.exe as malware and quarantines it

### ISSUE THREAD

**Issue by bbpgrs** [telegramdesktop/tdesktop#8131]
#8029 # Steps to reproduce
1. Have MalwareBytes installed
2. Have Telegram 2.1.12 installed
3. Run a MalwareBytes scan on the Telegram installation folder.

### Expected behaviour
Scan completes and does not find any threats

### Actual behaviour
Scan detects Updater.exe as Malware and quarantines it.

### Configuration
**Operating system:** Windows 10

**Version of Telegram Desktop:** 2.1.12

**Installation source (Linux Only)** - the official website / GitHub releases / flatpak / snap / distribution package:

**Used theme**:

<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/8083

**Comment by bbpgrs** [comment]
> #8083

Different version and file detected, but ok...
