### ISSUE TITLE
Bind UI mode to current system theme

### ISSUE THREAD

**Issue by KvanTTT** [telegramdesktop/tdesktop#8132]
### Is your feature request related to a problem?

Now it's possible switching between modes (Light, Dark) only manually.

### Describe the solution you'd like

Add the possibility to bind the current UI mode to the system theme.

### Additional context

A lot of programs have such a feature (Chrome, Skype)

![image](https://user-images.githubusercontent.com/1150330/85571002-7b3b5380-b63c-11ea-8ab3-8cf92c4fdf99.png)

**Comment by ilya-fedin** [comment]
#4918
