### ISSUE TITLE
Telegram window border visible when window minimized

### ISSUE THREAD

**Issue by berimor** [telegramdesktop/tdesktop#8133]
On my Windows PC (Windows 10, Microsoft Surface Pro 7) the Telegram window border sometimes remains visible, when Telegram Desktop window has been minimized. I cannot exactly reproduce when this happens, maybe when going into standby, or in other situations. Anyway, if I restore the window and then minimize it again, the border disappears.

See screenshot below. Any ideas?

![image](https://user-images.githubusercontent.com/6745832/85648794-deab9c80-b6a1-11ea-8a51-13d52eda8dc1.png)

**Comment by berimor** [comment]
No, it doesn't look so. The screenshot is different, and it doesn't happen on autostart. It rather happens (maybe) when I switch off the docking station or switch it on again (monotor switch), or maybe when going into sleep mode or back. I cannot really reproduce it, but it happens quite often. 
On 25.06.2020 10:41:44, ilya-fedin <notifications@github.com> wrote:
#7332 [https://github.com/telegramdesktop/tdesktop/issues/7332]?

**Comment by ilya-fedin** [comment]
> The screenshot is different

That's because Telegram has CSD on Windows, but doesn't have on Linux

> and it doesn't happen on autostart

Ok, then that's a different issue

**Comment by Coxxs** [comment]
Also happens pretty often for me. Just found a method to reproduce.

Windows 10 19041.329 (2004)

1. Open Telegram & close Telegram window.
2. Change `Settings -> System -> Display -> Change the size of text, apps, and other items` to another value
3. The Telegram window border will now appear.

**Comment by berimor** [comment]
Hi, the issue still exists, so please don't close. Is there any progress on it?
