### ISSUE TITLE
[Feature Request] Auto-convert text files coming from a platform to another platform (OS)

### ISSUE THREAD

**Issue by eaglebush** [telegramdesktop/tdesktop#8136]
### Is your feature request related to a problem?
I recently installed Ubuntu 20.04 on my old laptop. There, I edited some VBA macro for an interfacing application. I sent four text files from my Ubuntu system to my client that uses Windows OS. My client then installed it in their interfacing application and it failed to execute. It turned out to be a line feed problem. My system being Ubuntu, terminates line with only a line feed character, which made the client's computer reading errors in the file.

### Describe the solution you'd like
SFTP client and server have a Text/ASCII transfer mode. This feature automatically convert line terminators from LF to CRLF or vice versa while being sent. It would be nice if the Telegram client automatically handles this.

### Describe alternatives you've considered
None. The client will have to open the file in their own text file editor and save it

**Comment by RememberTheAir** [comment]
This sounds as something way too out of the scope of a messaging app, also something really trivial to do with any text editor/ide

**Comment by AlexGrump** [comment]
I agree with @RememberTheAir . Telegram should not change the contents of the transferred files.

**Comment by eaglebush** [comment]
> 
> 
> This sounds as something way too out of the scope of a messaging app, also something really trivial to do with any text editor/ide

Telegram functions as a file transfer too in a way. We use Telegram primarily for sending patch files.  The problem occurred to me when I used an OS other than on Windows.

**Comment by Aokromes** [comment]
save the files as lf on windows or convert them on linux / macos.

**Comment by ilya-fedin** [comment]
> This sounds as something way too out of the scope of a messaging app

+1, it would be strange if Telegram modified my files
If I want to send some script to a Windows user, then I change line ending in my editor
