### ISSUE TITLE
High CPU usage when offline

### ISSUE THREAD

**Issue by jvolker** [telegramdesktop/tdesktop#8138]
### Steps to reproduce
1. Open Telegram
2. Turn off Wifi / Internet

### Expected behaviour
CPU usage should be normal/low.

### Actual behaviour
CPU usage is much higher than usual.

### Configuration
**Operating system:**
macOS 10.14.6

**Version of Telegram Desktop:**
v 2.1.12

**Installation source (Linux Only)** - the official website / GitHub releases / flatpak / snap / distribution package:
Probably official website. Can't remember. Had it for really long time already.

**Used theme**:
Standard

**Comment by ilya-fedin** [comment]
#8068?
