### ISSUE TITLE
[Feature Request] Option to handle private messages  

### ISSUE THREAD

**Issue by azuwlaa** [telegramdesktop/tdesktop#8139]
### Is your feature request related to a problem?
Receiving unwanted "Private Messages" is really common in telegram especially when you're in group with thousands of members, Anyone who is in the group can Private message you any time. For people with username this issue is really common not all the users are comfortable with receiving private messages some of the messages are spams and really annoying.

### Describe the solution you'd like
I believe there's no permeant solution for this but we can implead a way to separate these private messages from our main chats we can have option to get a request for private message just like we do in secret chats. But we have to enable the feature via "settings" so we no longer receive private messages without getting a request in a separate bar from main chats. This can help telegram clients to manage these kinds of unwanted private messages easily.

**Comment by MasterGroosha** [comment]
There's no "request" in secret chats, by the way. If you're online, the other party can create a secret chat and spam you with messages.

**Comment by reallyuniquename** [comment]
>For people with username this issue is really common

Not having a username doesn't stop anyone from PMing you if both of you share a group.
