### ISSUE TITLE
Downloading more data than the given 332 MiB.

### ISSUE THREAD

**Issue by dipeshky** [telegramdesktop/tdesktop#8141]
I am downloading Telegram Desktop of flathub source and the size is given 332Mib but has already downloaded more than 500MiB. You guys should write the actual size.

**Comment by john-preston** [comment]
@dipeshky I have no idea what you're talking about.

**Comment by ilya-fedin** [comment]
> You guys should write the actual size.
> You guys

That writes flatpak, not tdesktop

**Comment by dipeshky** [comment]
My point is that in KDE Neon's discover the app name 'Telgram Desktop' was shown as the download size of 332MB. But when I started downloading, it actually consumes 700+ MB to download completely. 
I had connected my wifi to my mobile hotspot. And I was out of data and I had to purchase another pack to get the download completed.
I think it's a bug in Discover.

**Comment by dipeshky** [comment]
> @dipeshky I have no idea what you're talking about.

My point is that in KDE Neon's discover the app name 'Telgram Desktop' was shown as the download size of 332MB. But when I started downloading, it actually consumes 700+ MB to download completely. 
I had connected my wifi to my mobile hotspot. And I was out of data and I had to purchase another pack to get the download completed.
I think it's a bug in Discover.

**Comment by ilya-fedin** [comment]
> I think it's a bug in Discover.

I saw that bug even in command-line flatpak utility
But only in old versions (like the one that shipped with Ubuntu 18.04/KDE Neon)
Probably you should create an issue in ubuntu package bugtracker to backport a fix from the latest flatpak

**Comment by dipeshky** [comment]
> > I think it's a bug in Discover.
> 
> I saw that bug even in command-line flatpak utility
> But only in old versions (like the one that shipped with Ubuntu 18.04/KDE Neon)
> Probably you should create an issue in ubuntu package bugtracker to backport a fix from the latest flatpak

How to do that??

**Comment by ilya-fedin** [comment]
> How to do that??

https://launchpad.net/ubuntu/+source/flatpak/+bugs

**Comment by dipeshky** [comment]
> > How to do that??
> 
> https://launchpad.net/ubuntu/+source/flatpak/+bugs

Thank you!! 😊
