### ISSUE TITLE
app freeze while writing

### ISSUE THREAD

**Issue by Gokhlayeh92** [telegramdesktop/tdesktop#8142]
### Steps to reproduce
1. try writing a text message
2. very often (I'd say at least 8/10 times) the app freezes while typing

### Expected behaviour
you know...the message being written.

### Actual behaviour
the app freezes badly, for 10 second to a couple minutes.

### Configuration
**Operating system:**
windows 10 v1093 

**Version of Telegram Desktop:**
v2.1.13

**Used theme**:
any

<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by ilya-fedin** [comment]
#7952
