### ISSUE TITLE
[Question] How to build the telegraph desktop with visual studio 2019 as the installation version?

### ISSUE THREAD

**Issue by fish6688** [telegramdesktop/tdesktop#8143]
Use Visual Studio 2019 to build the telegraph desktop. After the successful construction, it is a green version. Open the EXE file and you can use it directly. How to build it as an installation version?

**Comment by zhangqingfeng0105** [comment]
Did you build it according to the official tutorial？is https://github.com/telegramdesktop/tdesktop/blob/dev/docs/building-msvc.md？
