### ISSUE TITLE
Sound problems on Linux

### ISSUE THREAD

**Issue by legendofa** [telegramdesktop/tdesktop#8144]
### Steps to reproduce
(I have checked my system input devices, they are working correctly.)
1. Select your microphone in the settings
2. Make a call or check microphone input in settings

### Expected behaviour
The other person can hear you loud and clear / microphone works.

### Actual behaviour
No microphone is detected.

### Configuration
**Operating system:**
 Linux x86_64
 5.7.5-arch1-1

**Version of Telegram Desktop:**
2.1.13

**Installation source (Linux Only)** - the official website / GitHub releases / flatpak / snap / distribution package:
pacman

**Used theme**:
Tinted

<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by ilya-fedin** [comment]
#726
