### ISSUE TITLE
NSFW flag

### ISSUE THREAD

**Issue by tbazadaykin** [telegramdesktop/tdesktop#8145]
There are situations when you send messages containing NSFW-content.

The recipient does not have the opportunity to check what kind of message it is without opening it. It is not always possible to maintain privacy (open space, video surveillance systems, workplace monitoring systems etc.)

It is assumed that the sender can mark the message as "NSFW". In this case, the recipient of such a message, to view it, must click on such a message.

Also, the text of such messages should be hidden in pop-up notifications, regardless of global privacy settings.

**Comment by MasterGroosha** [comment]
You can send self-destructing media files in one-to-one chats (dialogues), which will be blurry by default and will self-destruct at 60 seconds max. However this feature is not available with TDesktop.

**Comment by aNNiMON** [comment]
Use spoiler bots for this. **spoilerobot** for example
