### ISSUE TITLE
[Feature Request] Navigate calendar days with keyboard

### ISSUE THREAD

**Issue by dogancelik** [telegramdesktop/tdesktop#8147]
### Is your feature request related to a problem?
Changing date is not possible with with keyboard.

### Describe the solution you'd like
The days on the calendar should be focusable and navigatable by keyboard keys (up, down, left, right).

![navigate with keyboard](https://user-images.githubusercontent.com/486818/85897876-e84d1580-b803-11ea-9072-20a69f3b058b.gif)

I should be able to <kbd>Tab</kbd> to Close button and press <kbd>Enter</kbd> to close Calendar dialog.

#### Solution 2: Make calendar dialog optional, make input editable
So you can input text as usual like `18/07/2020`

Input format is detected by user's locale, I use `YYYY.MM.DD`, set in Windows locale settings.

![input with calendar icon](https://user-images.githubusercontent.com/486818/85901223-f56d0300-b809-11ea-8075-3ba1a55569b9.gif)

### Additional context
I provided example designs above.

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/7194

**Comment by dogancelik** [comment]
This is more related to #7954 but I understand if maintainers want to combine issues into one single issue.
