### ISSUE TITLE
[Feature Request] Move the call between apps without cancel it

### ISSUE THREAD

**Issue by walidamriou** [telegramdesktop/tdesktop#8148]
### Is your feature request related to a problem?
When we make a call in the desktop app and want to move it to the mobile app, we need to cancel the call in the desktop app and call again in the mobile app. 

### Describe the solution you'd like
Add a solution to move the call from different platforms without the need to cancel it.

**Comment by john-preston** [comment]
@walidamriou It's unlikely, the calls use end to end encryption, like a secret chat, and there is no way to transfer the encryption keys between the devices right now.

**Comment by walidamriou** [comment]
what about another scenario:
1- When you are in a call (put it as condition flag), click a button 
"Move call".
2- A small window open shows your devices connected now.
3- click on a device title in the window.
4- The call will move from your device 1 to 2 by canceling the call at device 1 and automatic recall and connect from device 2, without need to accepted the call by the other user (put a flag that if a user in a call with a person and this person cancel to move and recall, the app accepts automatically the call without need the permission).
This scenario supports the "end to end encryption" because when move and recall a new keys will create.

**Comment by walidamriou** [comment]
Any updates here?

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/8148#issuecomment-650482001

**Comment by Aokromes** [comment]
https://bugs.telegram.org/c/729
