### ISSUE TITLE
Telegram crashes when try to play 2k or 4k video

### ISSUE THREAD

**Issue by sergeyampo** [telegramdesktop/tdesktop#8151]
### Steps to reproduce
1. Open telegram
2. Open dialogue
3.  Start playing 4k video

### Expected behaviour
Video should be played

### Actual behaviour
Telegram instantly crashes

### Configuration
Windows 10
i7 7700 HQ
8 GB RAM

**Version of Telegram Desktop:**
2.1.13

**Installation source (Linux Only)** - the official website / GitHub releases / flatpak / snap / distribution package:

**Used theme**:

<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by Aokromes** [comment]
cannot reproduce on windows 10 21h1.

**Comment by Aokromes** [comment]
not instant for me and not every video.

but confirmed.
Your Report Tag: e1ee0c17-c85d-41ca-82a0-91495db66e5f

**Comment by Neurotoxin001** [comment]
I'm sure this is the same issue as https://github.com/telegramdesktop/tdesktop/issues/7055
Because of 32bit RAM limitation.

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/7839 ?
