### ISSUE TITLE
[Feature Request] Settings will be reset after cleaning the trash

### ISSUE THREAD

**Issue by BlueNeet** [telegramdesktop/tdesktop#8155]
### Is your feature request related to a problem?
After cleaning up computer trash and starting telegram,settings are restored to the state of first opening telegram.

### Describe the solution you'd like
Add the function of sync settings with the account.

**Comment by ilya-fedin** [comment]
Can't reproduce, need more info about the system

**Comment by BlueNeet** [comment]
> Can't reproduce, need more info about the system

windows 10 home 64-bit

**Comment by ilya-fedin** [comment]
> windows 10 home 64-bit

When I clearing trash, nothing happens with tdesktop (I wonder how that even can affect tdesktop in any way)

**Comment by BlueNeet** [comment]
I use third-party software to clearing trash,it will delete a cache folder under AppData\Roaming\Telegram Desktop\tdata\.So I hope to add sync settings with account.Otherwise after using some to clear trash and logging in on the new device, need to adjust the many settings again.
