### ISSUE TITLE
[Feature Request]  some features wanted

### ISSUE THREAD

**Issue by yichangshengwu** [telegramdesktop/tdesktop#8157]
内容为中文所写，后面有谷歌翻译的结果。
The content is written in Chinese, followed by the result of Google Translate.

- - - 

# 希望新增的特性

## 在右侧面板中添加 “返回顶部” 及 “直达底部” 按钮

例如，在浏览 群组/频道 中的 图片时，可以 “直达底部” 从头看起，也可以在中途快速地 “返回顶部”，在联系人列表也是如此

## 锁定右侧面板联系人列表中的搜索框

目前搜索框会随着滚动而“消失”在顶部，在浏览了一部分的情况下，要返回去搜索框中输入，还要拉动滚动条到顶部才行，略有不便

## emoji 列表的弹出速度控制

当鼠标经过 emoji 按钮时，会弹出列表，

但有些时候鼠标的目标并不是 emoji 按钮，而是滚动条的下部，只是经过 emoji 按钮时停顿了一下，此时要让列表缩回去便要移开鼠标等待，略有不便，

所以希望可以提供 “对 emoji 列表弹出速度” 的控制选项

## 对话可以拖拽至文件夹

现有的添加对话至自定义文件夹方式不够便捷，更便捷的方式可以是：

在对话上通过右键菜单“剪切”，点击自定义文件夹，列表中右键菜单通过“粘贴”；

或者，可以拖拽对话到目标文件夹图标，将对话移动到自定义文件夹

- - - 

# Wish to add new features

## Add "Back to Top" and "Direct to Bottom" buttons to the right panel

For example, when browsing pictures in a group/channel, you can "go straight to the bottom" from the beginning, or you can quickly "return to the top" halfway, and also in the contact list

## Lock the search box in the contact list on the right panel

At present, the search box will "disappear" at the top as you scroll. After browsing a part of it, you have to go back to the search box to enter, and you have to pull the scroll bar to the top, which is slightly inconvenient.

## Emoji list pop speed control

When the mouse passes the emoji button, a list will pop up,

But sometimes the target of the mouse is not the emoji button, but the lower part of the scroll bar, but it pauses when passing the emoji button. At this time, if you want to retract the list, you need to remove the mouse and wait, which is slightly inconvenient.

So I hope to provide the option to control the pop-up speed of the emoji list

## Conversation can be dragged to the folder

The existing way to add a conversation to a custom folder is not convenient enough. A more convenient way is:

In the dialogue, right-click menu "cut", click on the custom folder, the right-click menu in the list through "paste";

Or, you can drag the conversation to the target folder icon to move the conversation to a custom folder

**Comment by StephanoGeorge** [comment]
To top: https://t.me/xxx/1,  already has a button to go to bottom.

**Comment by yichangshengwu** [comment]
> To top: https://t.me/xxx/1, already has a button to go to bottom.

![截图_2020-11-18_05-47-01](https://user-images.githubusercontent.com/43059917/99454607-a020c200-2961-11eb-8141-efc0c532c481.png)

the button i want in the picture list
