### ISSUE TITLE
snap version don't start on debian

### ISSUE THREAD

**Issue by Ratio2** [telegramdesktop/tdesktop#8158]
fresh debian 9: ok
fresh debian 10: fail
fresh debian 10 + snap install kubectl --classic:  ok ;)

**Comment by ilya-fedin** [comment]
Yes, telegram-desktop snap doesn't work debian 10, it is not known what problem exactly is, but most likely debian 10 has a bugged snapd version that prohibits telegram-desktop to create single instance socket. When installing with `--devmode`, the package works.
There is nothing that anyone here can do about that.

**Comment by Ratio2** [comment]
@ilya-fedin But just after install kubectl snap all magically work. May be missing dependencies?

**Comment by ilya-fedin** [comment]
> But just after install kubectl snap all magically work. May be missing dependencies?

Missing dependencies couldn't be a problem for snap, since snap packages can use dependencies only from themselves

**Comment by Ratio2** [comment]
> Missing dependencies couldn't be a problem for snap, since snap packages can use dependencies only from themselves
Make some tests. Other apps (like hello-world) install core snap witch install apparmor security profiles. Telegram snap need be updated to install apparmor security profiles too.

**Comment by ilya-fedin** [comment]
> Telegram snap need to be updated to install apparmor security profiles too.

Packages don't offer apparmor profiles, snapd generates them on the fly. If this doesn't happen on debian 10, that's snapd issue of the version that distirbuted in debian 10
