### ISSUE TITLE
Promote Linux Snap Install Option

### ISSUE THREAD

**Issue by stephenjudge** [telegramdesktop/tdesktop#8159]
I wanted to install Telegram Desktop on my Xubuntu desktop so I visited the Telegram Desktop website. I was about to download and try and install Telegram Desktop from the Tar archive offered from the website. Just before I did I decided to search the Snapcraft repository to see if there was an official Snap build and to my delight there was. This saved me the hassle of having to figure out how to install the binary from the Tar archive and keep it updated. 

I was confused as to why the Snap option wasn't offered from the Telegram Desktop website. It would save others a lot of wasted time in the future if they knew they could install a Snap build if they wished instead of installing from a binary file.
I'd like to suggest you please promote the option of installing Telegram Desktop from the Snapcraft Store. You can embed an official Snapstore button on your page with this code:

`<iframe src="https://snapcraft.io/telegram-desktop/embedded?button=black" frameborder="0" width="100%" height="320px" style="border: 1px solid #CCC; border-radius: 2px;"></iframe>`

You can customize it on the Snapcraft webpage: https://snapcraft.io/telegram-desktop

Or just present the following terminal command for Ubuntu based distros, other terminal commands are offered on the Snapcraft page for the appropriate distro:

`sudo snap install telegram-desktop`

**Comment by ilya-fedin** [comment]
Snap is the ugliest installation method of tdesktop, which has bugs that other installation methods don't have :see_no_evil:

**Comment by javierin** [comment]
I would like to **DOWNVOTE** this proposal.
