### ISSUE TITLE
[Question] Isn't it possible to keep an account logged in when using the portable version?

### ISSUE THREAD

**Issue by aderchox** [telegramdesktop/tdesktop#8160]
Hi, I'm using an Asus UX310UQ laptop and I guess maybe it's because of my 13 inch screen size (or any other reason) that the main Telegram crashes and hangs on my laptop, so I opted out using it and thought the portable version might work without the hangings and not-respondings, and it does, it's working perfectly fine. Except when I turn off the laptop and turn it back on, it asks me to login once again! Which is quite boring. Is that normal (say, something related to security?) or I'm doing something wrong here? Thank you in advance.

**Comment by john-preston** [comment]
@aderchox It is not normal. Is it the latest version that does it? Can you provide a log.txt for the entire launch when you authorize + the log.txt for the launch after that, when it is not authorized again.

**Comment by aderchox** [comment]
@john-preston I'm sorry. For some reasons, it is working fine now! I cannot get the same behavior and I've re-tried the whole process twice. I don't know, maybe I made a terrible mistake previously when I encountered this issue, but this is fixed now anyways, so thanks.
