### ISSUE TITLE
[Feature Request]  Call all participants

### ISSUE THREAD

**Issue by Yaroslav08** [telegramdesktop/tdesktop#8163]
Call all participants in groups and supergroups via @everyone

**Comment by Aokromes** [comment]
it must be done by server.

**Comment by Bytezz** [comment]
This can be done also with a lato-client auto completion. You write "@e" and the suggest for "everyone" pops out, then clicking on it will auto write all participants tags to call at them. In this way can bypass the api limitation.
![Everyone example](https://user-images.githubusercontent.com/25850701/86131101-7ddaf480-bae5-11ea-9351-1cd8a0c6527b.jpg)

**Comment by Bytezz** [comment]
On telegram the minimum length for a username its 5 chars, then there isn't something or someone already using the tag "@e".
