### ISSUE TITLE
The testmode command not working

### ISSUE THREAD

**Issue by mugavri** [telegramdesktop/tdesktop#8167]
### Steps to reproduce
1. enter to the settings
2. type `testmode`
3. not working

### Configuration
**Operating system:**
windows 10 1909

**Version of Telegram Desktop:**
2.1.14 beta

**Comment by john-preston** [comment]
@mugavri Now you can add a secondary account from the test dc. Press Alt+Shift and right click on Add Account button, there will be a context menu.

**Comment by mugavri** [comment]
> @mugavri Now you can add a secondary account from the test dc. Press Alt+Shift and right click on Add Account button, there will be a context menu.

@john-preston not work for me (im log on same number on prod server)

**Comment by mugavri** [comment]
@john-preston  thanks
