### ISSUE TITLE
panels size and music volume settings reset upon reopening the app

### ISSUE THREAD

**Issue by alissonlauffer** [telegramdesktop/tdesktop#8168]
### Steps to reproduce
1. Resize the left/right panels.
2. Play some song and adjust its volume.
3. Exit the app completely.
4. Reopen it.
5. See the issue: settings are reseted.

### Configuration
**Operating system:** Linux

**Version of Telegram Desktop:** 2.1.14 beta

**Installation source:** GitHub releases

**Comment by john-preston** [comment]
@alissonlauffer Thanks!
