### ISSUE TITLE
[Feature Request] Window bar buttons position

### ISSUE THREAD

**Issue by Bytezz** [telegramdesktop/tdesktop#8169]
### Window bar buttons position should be customizable at least
Just updated Telegram Desktop to 2.1.14 beta on Linux, that introduced the new window bar buttons already seen on Windows. There are a big problem with that: All my other windows have that buttons on the left. This problem was inexistent using the default windows manager window bar.

### Possible solution
There should be at least an option to set the buttons to left/right or an option to turn on/off the native windows manager window bar.

### Pic of that
![Screenshot](https://user-images.githubusercontent.com/25850701/86080130-72aaa900-ba92-11ea-94fc-514f6ebcef10.jpg)
On top the new telegram's window bar and at the bottom an example window bar (of nautilus).

thanks in advance for attention. Let me know what you think.

**Comment by wierdbytes** [comment]
There should be checkbox to turn this behavior completely off and act like before. This looks terrible on i3wm:
![JLTesXpa](https://user-images.githubusercontent.com/54069885/86107406-73f7c800-baca-11ea-825d-163dffea0c0d.png)
![QuHAMa4O](https://user-images.githubusercontent.com/54069885/86107416-7823e580-baca-11ea-9dc1-d72c54999d49.png)

**Comment by efeciftci** [comment]
In its current version (2.1.14 beta), I can't say it fits well with other windows under KDE/KWin as well. Telegram Desktop should indeed provide an option to turn on/off CSD's on Linux.

**Comment by ilya-fedin** [comment]
> There should be checkbox to turn this behavior completely off and act like before.

#2958
