### ISSUE TITLE
[Feature request] Detached chat window

### ISSUE THREAD

**Issue by andrelrt** [telegramdesktop/tdesktop#817]
Some time you need to write in one screen, but also read another ones.
Could be a good idea to create multiwindow chat.

**Comment by Streppel** [comment]
What you have in mind is something like opening a new window which contains only the chat window, leaving the contacts bar off? Or something like splitting the chat window in the middle, like Terminator (the terminal emulator) does (which I think wouldn't be so trivial to manage from a users perspective)?

**Comment by ralesk** [comment]
:+1: I'd also like to have this on desktop.

**Comment by auchri** [comment]
Duplicate #533
