### ISSUE TITLE
[Feature Request] Drag accounts to reorder them

### ISSUE THREAD

**Issue by RememberTheAir** [telegramdesktop/tdesktop#8171]
### Is your feature request related to a problem?
As of now there is no way to reorder your accounts, except for logging out from all of them and login again in the correct order

### Describe the solution you'd like
A way to drag accounts to reorder them

### Describe alternatives you've considered
None

**Comment by RememberTheAir** [comment]
Whoops forgot to comment. @Aokromes can you reopen this issue?

**Comment by 23rd** [comment]
You can check the latest 3.5.1 version.

**Comment by RememberTheAir** [comment]
Awesome! Thank you for the heads up :)
