### ISSUE TITLE
Missing: option to make telegram full-screen on linux

### ISSUE THREAD

**Issue by peey** [telegramdesktop/tdesktop#8172]
### Steps to reproduce
1. Be on Ubuntu 20.04 
2. Press F11

### Expected behaviour
App should start occupying the entire screen

### Actual behaviour
Nothing

### Configuration
**Operating system:** Ubuntu 20.04

**Version of Telegram Desktop:** 2.1.1

**Installation source (Linux Only)** - flatpak

**Used theme**: -

**Comment by ilya-fedin** [comment]
Sounds strange for messenger...

**Comment by peey** [comment]
I suppose. But equally strange that I can't make full screen a desktop app. I think this is the only one in the apps I use often.

**Comment by ilya-fedin** [comment]
There is nothing strange here. I have a lot of applications that doesn't support fullscreen.

**Comment by peey** [comment]
Is this a choice of the project (to not allow full screen) or a limitation (which we're judging if it's worth fixing based on if it'll be useful to users)?
