### ISSUE TITLE
Use system window border/frame/header

### ISSUE THREAD

**Issue by mekras** [telegramdesktop/tdesktop#8173]
After last update on Linux Telegram started to use own window border instead of system one. This is an UX degradation because prevents users from using the management mechanisms provided by desktop/window managers, such as custom buttons, effects and etc.

![image](https://user-images.githubusercontent.com/192067/86112478-b58b7180-bad0-11ea-9c8c-739c5a50c022.png)

There should be an option to use a system border on Linux.

**Comment by ilya-fedin** [comment]
#2958

**Comment by electricduck** [comment]
This is not a duplicate at all. Up until this last update, Telegram Desktop on Linux has always used the native notification bar, but now its using the native one, with no option to change it.

**Comment by ilya-fedin** [comment]
> Use system window border/frame/header

> Set native windows frame

100% duplicate

> Up until this last update

This doesn't make this issue a non-duplicate, since it is the same decorations, just cross-platform now due to new Qt APIs

**Comment by jfsanchez-gh** [comment]
Please rollback that change. I want and I like my native KDE window decoration. Right now It's awful.

**Comment by ilya-fedin** [comment]
@jfsanchez-gh you're a little late ;)
https://github.com/telegramdesktop/tdesktop/commit/f10b2194e605cd0730c23da6472bbb1c12cd8aaf

**Comment by jfsanchez-gh** [comment]
"committed 22 hours ago" really? haha. 
Updated to v2.1.18, now I can switch back to my beautiful native KDE window decorations. Thx.

**Comment by hongquan** [comment]
Found the setting. Thanks.
