### ISSUE TITLE
[Feature Request] Save links rendered as buttons to exported HTML

### ISSUE THREAD

**Issue by Karasiq** [telegramdesktop/tdesktop#8175]
<img width="467" alt="Screenshot 2020-06-30 at 13 48 22" src="https://user-images.githubusercontent.com/7199719/86118072-ccce5d00-bad8-11ea-953b-638a07fbba3b.png">

It would also be nice if linked telegra.ph articles were also saved locally.

**Comment by reallyuniquename** [comment]
Valid.
