### ISSUE TITLE
"Use Windows notifications" stopped working on update until toggled off and on

### ISSUE THREAD

**Issue by nyuszika7h** [telegramdesktop/tdesktop#8176]
### Steps to reproduce
1. Have "Use Windows notifications" on in an earlier version.
2. Update to 2.1.14 beta.
3. Get a notification.

### Expected behaviour
It should respect the settings, when I go to check them "Use Windows notifications" is still ticked.

### Actual behaviour
It's not using native notifications, and I had to toggle that option off & on for it to be active again.

### Configuration
**Operating system:** Windows 10 2004

**Version of Telegram Desktop:** 2.1.14 beta

**Used theme**: Tinted

**Comment by john-preston** [comment]
@nyuszika7h Yeah, thanks. Will be fixed in the next version.

**Comment by ilya-fedin** [comment]
Is this still valid?

**Comment by Aokromes** [comment]
1 month without answer, if this bug is still valid open a new ticket.
