### ISSUE TITLE
[Feature Request] Keyboard shortcut to switch between accounts

### ISSUE THREAD

**Issue by RememberTheAir** [telegramdesktop/tdesktop#8179]
### Is your feature request related to a problem?
It would be nice to have a keyboard shortcut to swicth and jump between accounts

### Describe the solution you'd like
I think that right now the only keyboard shortcut left to loop through accounts would be SHIFT+ARROW UP/DOWN (or PAGE UP/PAGE DOWN).

~Alternatively, ALT +1/2/3 could be used to directly jump to an account~ nope, see comment below

### Describe alternatives you've considered
None

**Comment by PoMaKoM** [comment]
I really look forward to this change.

**Comment by erfanmola** [comment]
+

**Comment by nb1dev** [comment]
> Alternatively, ALT +1/2/3 could be used to directly jump to an account

Shortcut often used in Linux to change virtual desktop.
But your first proposal looks good, hope a shortcut soon :)

**Comment by SamixGroup** [comment]
Really important feature

**Comment by ratijas** [comment]
I propose `Ctrl+Tab` / `Ctrl+Shift+Tab` to switch back and forth. These shortcuts already worked for ages in various software and on different operating systems, like in browsers and document-oriented apps with tabs.

**Comment by vacekj** [comment]
Bumping this one.

**Comment by azurath** [comment]
Bumping issue. Highly needed.

**Comment by Programistich** [comment]
Any updates?

**Comment by DrMatters** [comment]
Bump

**Comment by Programistich** [comment]
I sync we need to create PR with changes ;D

**Comment by AlexanderMatveev** [comment]
Really need this feature 🐱

**Comment by foodornt** [comment]
Bumping issue. Highly needed.

**Comment by rainrisa** [comment]
guys i need this feature cause my mouse is broken

**Comment by naumov13** [comment]
That is highly needed feature which i wait for few years

**Comment by joerude** [comment]
bump

**Comment by Jain2098** [comment]
Highly Needed. I suggest this shortcut key **Ctrl+Shift+Tab**

**Comment by mdraevich** [comment]
Bump!

**Comment by Amomum** [comment]
Bump!
Although Ctrl+Tab/Ctrl+Shift+Tab are already used to switch between chats, so we need something different. Maybe even - ah! - configurable?

**Comment by milovtim** [comment]
Really missing feature

**Comment by wolandtel** [comment]
Need this.

**Comment by pony-v-oborone** [comment]
Hey everyone, I've found that this feature is already implemented. On Telegram Desktop client for Mac you can switch accounts by pressing control + 1, 2, 3 etc.

**Comment by wolandtel** [comment]
> Hey everyone, I've found that this feature is already implemented. On Telegram Desktop client for Mac you can switch accounts by pressing control + 1, 2, 3 etc.

On Linux it switches folders.

**Comment by Aokromes** [comment]
> > Hey everyone, I've found that this feature is already implemented. On Telegram Desktop client for Mac you can switch accounts by pressing control + 1, 2, 3 etc.
> 
> On Linux it switches folders.

very likely he is using telegram for macos, not telegram desktop.

**Comment by aCLr** [comment]
:pray:

**Comment by nguyenhieptn** [comment]
I need this feature.

**Comment by Crushtests** [comment]
me too :-)

**Comment by jaimindp** [comment]
Me as well!

**Comment by orthlus** [comment]
bump

**Comment by arsenty** [comment]
It works, try Control + Command (alt) + 1 or 2 or 3, etc.
macOS 13.0.1
Telegram 9.2.1

**Comment by orthlus** [comment]
> It works, try Control + Command (alt) + 1 or 2 or 3, etc. macOS 13.0.1 Telegram 9.2.1
telegram 9? here only 4.4.1 https://github.com/telegramdesktop/tdesktop/releases
well, on windows in 4.4.1 does'n work

**Comment by arsenty** [comment]
> > It works, try Control + Command (alt) + 1 or 2 or 3, etc. macOS 13.0.1 Telegram 9.2.1
> 
> telegram 9? here only 4.4.1 https://github.com/telegramdesktop/tdesktop/releases well, on windows in 4.4.1 does'n work

OMG, these apps are different 😅 I use Telegram 9, not "Desktop"

**Comment by dvygolov** [comment]
Up! This is really important for those who love using keyboard.

**Comment by ahbanavi** [comment]
Right now, the only time I reach my mouse in telegram is to switch between accounts; this feature is necessary.

**Comment by niksan93** [comment]
bump

**Comment by naumov13** [comment]
also still waiting...

**Comment by Crushtests** [comment]
New update brought interesting function:

• Open in New Window. Open chats or additional accounts in separate windows.

At least something, but we are still waiting for a shortcut, aren't we? :-)

**Comment by orthlus** [comment]
bump

**Comment by thegreat-vanderlinde** [comment]
bump

**Comment by yuis-ice** [comment]
bump

**Comment by xdevman** [comment]
Required feature ( :

**Comment by niksan93** [comment]
> well, this shortcut may not be available by default, but in the settings you can enable it and select keys there

Could you please specify where exactly are those settings and this option you are talking about? Because i cannot find it for my life :)

**Comment by alizera** [comment]
> It works, try Control + Command (alt) + 1 or 2 or 3, etc. macOS 13.0.1 Telegram 9.2.1

Thanks, it worked for me!
Saved million seconds of my rubbish life.

**Comment by orthlus** [comment]
bump

**Comment by ActivexDiamond** [comment]
Bump, yes please. Would love to have this.

**Comment by naumov13** [comment]
bump again

**Comment by acrossoffwest** [comment]
bump bump

**Comment by Samehadar** [comment]
WE NEED THIS FEATURE. 

I can't handle this anymore. I have to switch from my keyboard to my mouse, then to hover the mouse over the "menu" button, then click, then hover it again over the "account" button, then click again! Let alone I can misclick and collapse drop-down list of my accounts accidentally.

I am begging you, add this shortcut.

**Comment by orthlus** [comment]
what's wrong with my message? i have two telegram clients on windows for two accouns and it's work fine. not hard to install, just one install in system and another - unpack portable version.

**Comment by kennywasafk** [comment]
bump

how hard can this be, at least make it an option please, doesn't need to be a default hotkey assigned for this for everyone

**Comment by mkmtrd** [comment]
Bump!

**Comment by kaepsis** [comment]
bump

**Comment by kalandarovkemal** [comment]
bump

**Comment by shattl** [comment]
Bump

**Comment by john-preston** [comment]
Sorry that it's gonna be Ctrl+Shift+1,2,3,4,5,6.

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/commit/0f207faa3eac0ce4d3eb628a4e243050df069e53

**Comment by alinri** [comment]
Is there option to disable or change this shortcut? The thin space character in Arabic style languages is typed with Ctrl+Shift+2 and I can't type it anymore in telegram desktop.

**Comment by pwd491** [comment]
> Is there option to disable or change this shortcut? The thin space character in Arabic style languages is typed with Ctrl+Shift+2 and I can't type it anymore in telegram desktop.

You can change it in shortcuts-custom.json.

For Windows: %appdata%/Local/Telegram Desktop/tdata/shortcuts-custom.json
For Mac: ~/Library/Application Support/Telegram Desktop/tdata/
For Linux: ~/.local/share/TelegramDesktop/tdata/shortcuts-custom.json

**Comment by alinri** [comment]
This new shortcut is not in shortcuts-default.json; so I don't know what the key should be Also for the same reasonI think it may hardcoded.

> > Is there option to disable or change this shortcut? The thin space character in Arabic style languages is typed with Ctrl+Shift+2 and I can't type it anymore in telegram desktop.
> 
> You can change it in shortcuts-custom.json.
> 
> For Windows: %appdata%/Local/Telegram Desktop/tdata/shortcuts-custom.json For Mac: ~/Library/Application Support/Telegram Desktop/tdata/shortcuts-custom.json For Linux: ~/.local/share/TelegramDesktop/tdata/shortcuts-custom.json

This new shortcut is not in shortcuts-default.json; so I don't know what the key should be. Also for the same reason I think it may hardcoded at the moment.

**Comment by pwd491** [comment]
> This new shortcut is not in shortcuts-default.json; so I don't know what the key should be Also for the same reasonI think it may hardcoded.
> 
> > > Is there option to disable or change this shortcut? The thin space character in Arabic style languages is typed with Ctrl+Shift+2 and I can't type it anymore in telegram desktop.
> > 
> > 
> > You can change it in shortcuts-custom.json.
> > For Windows: %appdata%/Local/Telegram Desktop/tdata/shortcuts-custom.json For Mac: ~/Library/Application Support/Telegram Desktop/tdata/shortcuts-custom.json For Linux: ~/.local/share/TelegramDesktop/tdata/shortcuts-custom.json
> 
> This new shortcut is not in shortcuts-default.json; so I don't know what the key should be. Also for the same reason I think it may be hardcoded at the moment.

https://github.com/telegramdesktop/tdesktop/issues/27334#issuecomment-1883387138

**Comment by pwd491** [comment]
> This new shortcut is not in shortcuts-default.json; so I don't know what the key should be Also for the same reasonI think it may hardcoded.
> 
> > > Is there option to disable or change this shortcut? The thin space character in Arabic style languages is typed with Ctrl+Shift+2 and I can't type it anymore in telegram desktop.
> > 
> > 
> > You can change it in shortcuts-custom.json.
> > For Windows: %appdata%/Local/Telegram Desktop/tdata/shortcuts-custom.json For Mac: ~/Library/Application Support/Telegram Desktop/tdata/shortcuts-custom.json For Linux: ~/.local/share/TelegramDesktop/tdata/shortcuts-custom.json
> 
> This new shortcut is not in shortcuts-default.json; so I don't know what the key should be. Also for the same reason I think it may be hardcoded at the moment.

Unfortunately, the developers have not added a keyboard shortcut, let's hope that they will do it soon. You can use a slightly earlier patch:

https://github.com/telegramdesktop/tdesktop/releases/tag/v4.14.3

**Comment by mrakhgari** [comment]
The developers have removed this feature with the commit ac7958f33503d796e02ba5e364e5a04d762e73fa. You can modify the `shortcut-custom.json` file to use the feature or assign a new shortcut to it.

**Comment by kalandarovkemal** [comment]
> The developers have removed this feature with the commit [ac7958f](https://github.com/telegramdesktop/tdesktop/commit/ac7958f33503d796e02ba5e364e5a04d762e73fa). You can modify the `shortcut-custom.json` file to use the feature or assign a new shortcut to it.

I've added and try to update shortcut-custom.json however won't work

**Comment by milovtim** [comment]
Confirm: after last update `account*` commands stopped to work.
After editing _shortcut-custom.json_ + restart -- they're back!
Thank you for this flexibility. 😄

**Comment by kalandarovkemal** [comment]
> > > The developers have removed this feature with the commit [ac7958f](https://github.com/telegramdesktop/tdesktop/commit/ac7958f33503d796e02ba5e364e5a04d762e73fa). You can modify the `shortcut-custom.json` file to use the feature or assign a new shortcut to it.
> > 
> > 
> > I've added and try to update shortcut-custom.json however won't work
> 
> After set up need to restart app.
> 
> Please be sure that would be like this:
> 
> ![image](https://private-user-images.githubusercontent.com/68108301/297411692-9aef2ccb-efed-4cef-8ff0-19a892a375be.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU1NjUyMTksIm5iZiI6MTcwNTU2NDkxOSwicGF0aCI6Ii82ODEwODMwMS8yOTc0MTE2OTItOWFlZjJjY2ItZWZlZC00Y2VmLThmZjAtMTlhODkyYTM3NWJlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE4VDA4MDE1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWViNTVlNThmNDM3MTc4ZDk1YTdhMzQ3OGYzNmZhNDg3ZjYzNDI3YjQ4OTQ4MGMyZGUwYjk5MDJjYTAwMjg2M2UmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.T7qzw-MvLcMScslenMJ0ieEg0JecycE-k2qaJot4ytU)

Won't work on my Mac with Apple silicon chip. Is it possible that problem is Platform specific ?

**Comment by pwd491** [comment]
> > > > The developers have removed this feature with the commit [ac7958f](https://github.com/telegramdesktop/tdesktop/commit/ac7958f33503d796e02ba5e364e5a04d762e73fa). You can modify the `shortcut-custom.json` file to use the feature or assign a new shortcut to it.
> 
> > > 
> 
> > > 
> 
> > > I've added and try to update shortcut-custom.json however won't work
> 
> > 
> 
> > After set up need to restart app.
> 
> > 
> 
> > Please be sure that would be like this:
> 
> > 
> 
> > ![image](https://private-user-images.githubusercontent.com/68108301/297411692-9aef2ccb-efed-4cef-8ff0-19a892a375be.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU1NjUyMTksIm5iZiI6MTcwNTU2NDkxOSwicGF0aCI6Ii82ODEwODMwMS8yOTc0MTE2OTItOWFlZjJjY2ItZWZlZC00Y2VmLThmZjAtMTlhODkyYTM3NWJlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE4VDA4MDE1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWViNTVlNThmNDM3MTc4ZDk1YTdhMzQ3OGYzNmZhNDg3ZjYzNDI3YjQ4OTQ4MGMyZGUwYjk5MDJjYTAwMjg2M2UmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.T7qzw-MvLcMScslenMJ0ieEg0JecycE-k2qaJot4ytU)
> 
> 
> 
> Won't work on my Mac with Apple silicon chip. Is it possible that problem is Platform specific ?

On my Mac, this shortcuts is ctrl + [1-6]. Try it.

**Comment by kennethtxytqw** [comment]
Mine is `ctrl + [num]` 

About machine in screenshot
<img width="467" alt="Screenshot 2024-02-22 at 09 43 31" src="https://github.com/telegramdesktop/tdesktop/assets/16360559/c4498529-9518-49b3-bd07-999008d7095b">
