### ISSUE TITLE
[Multi Account] Chat Info Panel and Chat List Panel Dimensions Changed

### ISSUE THREAD

**Issue by michele-grifa** [telegramdesktop/tdesktop#8181]
**Steps to reproduce**

1. Switch between accounts in 2.1.14 Beta
2. Close telegram
3. Re-Open telegram
4. Chat List width and Chat Info visibility are changed

**Expected behaviour**
Switching between account should preserve width and visibility of the panels

**Actual behaviour**

Width and visibility are set to default

**Configuration**

Operating system: Windows 10
Version of Telegram Desktop: 2.1.14 Beta

**Comment by Aokromes** [comment]
fixed on https://github.com/telegramdesktop/tdesktop/commit/a95b756111eafa83886732c9ce17eed8d5251056
