### ISSUE TITLE
Invalid cursor on tray on Linux

### ISSUE THREAD

**Issue by vladislav805** [telegramdesktop/tdesktop#8184]
### Steps to reproduce
1. Run Telegram with "Show tray icon" setting turned on.
2. Start resizing the window by left mouse button, then release the button
3. Move cursor over icon in tray

### Expected behaviour
"Default" cursor when hovering over icon.

### Actual behaviour
"Resize-horizontal" cursor when hovering over icon.
![Screenshot_2020-06-30_23-26-51](https://user-images.githubusercontent.com/10882576/86174553-899cda00-bb2a-11ea-9dea-02e09305481e.png)

### Configuration
**Operating system:** Arch Linux, xfce4 4.14

**Version of Telegram Desktop:** 2.1.14 beta, crashed on attempt to restart and updated to 2.1.15 beta with same problem

**Installation source (Linux Only)**: the official website

**Used theme**: Tinted blue

<details><summary><b>Logs</b>:</summary>
not necessary
</details>

**Comment by ilya-fedin** [comment]
Already fixed in 2.1.15

**Comment by vladislav805** [comment]
@ilya-fedin, are you sure?

![tg-bug](https://user-images.githubusercontent.com/10882576/86176745-15fccc00-bb2e-11ea-89f3-322677e5378f.gif)
(sorry for quality, it's compressed by ffmpeg+gif)

**Comment by ilya-fedin** [comment]
I checked with export window, I can't check with tray icon since I have SNI tray, I tried to check in a VM, but tdesktop crashes at start :thinking:

**Comment by ilya-fedin** [comment]
Can't reproduce with 2.1.16 in a VM with Manjaro Xfce

[vokoscreen-2020-07-01_14-18-13.mp4.zip](https://github.com/telegramdesktop/tdesktop/files/4857215/vokoscreen-2020-07-01_14-18-13.mp4.zip)

**Comment by vladislav805** [comment]
And if you try to resize a little?

I'll try later make an VM, if I can reproduce it.

**Comment by ilya-fedin** [comment]
> And if you try to resize a little?

Can reproduce that way, but can't understand why that happens :thinking:

**Comment by ilya-fedin** [comment]
Looks like https://doc.qt.io/qt-5/qwidget.html#isAncestorOf reports main window as ancestor for any widget in any window after resizing :thinking:

**Comment by ilya-fedin** [comment]
I tried to compare the window of the widget, but no luck
Looks like a bug in Qt without possibility to workaround it.
