### ISSUE TITLE
telegram (snapcraft.io) gets stuck on Ubuntu doing video call with "Exchanging keys"

### ISSUE THREAD

**Issue by chovy** [telegramdesktop/tdesktop#8185]
I suddenly can't do calls from desktop on Ubuntu 20.04 today. When I try to call someone it just gets stuck at "Exchanging keys".

Works fine on iOS but not Ubuntu.

**Comment by Aokromes** [comment]
there are no videocalls on telegram desktop.

**Comment by Anankin12** [comment]
Except there are?
