### ISSUE TITLE
[bug] Call reduces Volume of everything [Win 10]

### ISSUE THREAD

**Issue by PloufsPuppet** [telegramdesktop/tdesktop#8192]
### Steps to reproduce
1. Usage of Windows 10 with a z390 Mainboard. Set Windows 10 settings in "sound-communications-"do nothing"
2. Start a call with telegram desktop
3. the volume of everything else will be reduced (firefox, music, whatever)

### Expected behaviour
Tell us what should happen:
The volume should not be reduced. Skype, Teamspeak, Discord act liek they should. Telegram doesn't. 
There is a little workaround that fix it temporary. While getting a call and the volume gets reduced, change the communicationsetting from "do nothing" to "reduce the volume of other sounds byXX%" and then turn it back to "do nothing". The volume should be normal now. Restarting the computer will get the bug back.

### Actual behaviour
A call reduces the volume of everything else.

### Configuration
Tested a lot, also in contact with Asus and Realtek. It really doesn't matter, but seems to be mostly on z390 Boards (Asus, Asrock).
Windows 10 1909
Asus z390-F

**Version of Telegram Desktop:**
Latest, Different versions does not affect here.

**Comment by SpriteOvO** [comment]
Same problem, but I don't think it has anything to do with the hardware.
I have used Windows 10 1803 1809 1903 recently and found that the problem only occurs on >= 1809.

Likewise, I did not have the problem when using other calling software.

**Comment by SpriteOvO** [comment]
Same problem, but I don't think it has anything to do with the hardware.
I have used Windows 10 1803 1809 1903 recently and found that the problem only occurs on >= 1809.

Likewise, I did not have the problem when using other calling software.

**Comment by PloufsPuppet** [comment]
What kind of hardware do you have? U have any solution or alternative?

**Comment by SpriteOvO** [comment]
> What kind of hardware do you have?
Asus z270

> U have any solution or alternative?
Same as yours

**Comment by SpriteOvO** [comment]
> What kind of hardware do you have?

Asus z270

> U have any solution or alternative?

Same as yours

**Comment by PloufsPuppet** [comment]
Okay, so your solution is no solution or just the workaround?
You got an alternative program? I found out, that the program Wire got the same problem

**Comment by SpriteOvO** [comment]
Just the workaround.

> There is a little workaround that fix it temporary. While getting a call and the volume gets reduced, change the communicationsetting from "do nothing" to "reduce the volume of other sounds byXX%" and then turn it back to "do nothing". The volume should be normal now. Restarting the computer will get the bug back.

> You got an alternative program?

I tried a calling software YY (similar to TeamSpeak) and the problem did not occur.

**Comment by PloufsPuppet** [comment]
Well i use Teamspeak with people, but Telegram with one friend. Also we send each other stuff, so teamspeak is not a option. How are you doing so far? Do u know if the devs will do something=?

**Comment by SpriteOvO** [comment]
#4236
I found early content about this issue.

**Comment by PloufsPuppet** [comment]
Well at least its not happening on my old pc (Asus Z97-Pro Gamer) with win 7. Very frustrating.
I got friends with different boards on windows 10 and 1909 and they dont got the problem.

**Comment by PloufsPuppet** [comment]
Oh, did u check Win 10 2004?

**Comment by SpriteOvO** [comment]
> Oh, did u check Win 10 2004?

no

**Comment by PloufsPuppet** [comment]
Has anyone contacted Telegram support? I tried several times but got not even one answer.

**Comment by Aokromes** [comment]
anyone can try mumble to see if they have the same bug? it uses also QT if the bug is reproducible it maybe 3rd party bug.

**Comment by ilya-fedin** [comment]
Is this bug still valid after replacing libtgvoip with webrtc?

**Comment by SpriteOvO** [comment]
I have just tested it and found that the problem still occurs in versions 2.2.0, 2.3.0, and 2.3.1.

But I found something else, the problem only happens within the client I re-downloaded, not within the client I've been using.
Following this lead, I found a setting that might be relevant to this problem.

Settings -> Advanced -> Call Settings -> Output device

If I switch it from Default to the name of the device I am using and restart Telegram once, the problem will not reappear.

Let me know if there's anything I can do to help, and I'm happy to contribute if I can. :)

**Comment by ilya-fedin** [comment]
> Let me know if there's anything I can do to help, and I'm happy to contribute if I can. :)

No one even know what causes that

**Comment by SpriteOvO** [comment]
> Is this bug still valid after replacing libtgvoip with webrtc?

@ilya-fedin  webrtc didn't completely replace libtgvoip, right? Is call rendering still implemented in libtgvoip?
If that's correct, I think I've found the cause of the problem and I'll open a PR at libtgvoip later.

**Comment by ilya-fedin** [comment]
> webrtc didn't completely replace libtgvoip, right?

it is used only when calling to old clients for backward compatibility, calling to new clients is done in pure webrtc AFAIK

**Comment by SpriteOvO** [comment]
@ilya-fedin Okay, thanks, but I think what I found at libtgvoip is still a bug and has been proven and relevant to this issue, I will open a PR there. Maybe tomorrow I will try to find something else from webrtc.

**Comment by ldeluigi** [comment]
Go to Settings > Sound > Sound Control Panel > Communications and select "Do nothing".


This should solve.

**Comment by SpriteOvO** [comment]
> Go to Settings > Sound > Sound Control Panel > Communications and select "Do nothing".
> 
> This should solve.

But the problem will reappear after you restart your computer.
Please reread the issue description carefully.

**Comment by ldeluigi** [comment]
> > Go to Settings > Sound > Sound Control Panel > Communications and select "Do nothing".
> > This should solve.
> 
> But for us, the problem will still reappear after restarting the computer.
> Please reread the issue description carefully.

Sorry for misunderstanding, I never noticed this bug

**Comment by SpriteOvO** [comment]
This problem no longer occurs for me with tdesktop 2.7.5 and Windows 20H2, it seems to be a bug in Windows and has been fixed.
