### ISSUE TITLE
weird behaviour when clicking on titlebar

### ISSUE THREAD

**Issue by PeterMX** [telegramdesktop/tdesktop#8194]
### Steps to reproduce
basically click one time on titlebar
1. when app windows lost focus it shows the control buttons darker
2. or click on the titlebar, now the control buttons don't respond to mouse hover
3. or click on the titlebar, now get the mouse out of the windows, then get it in again over one of the control buttons and it will stay highlighted while your mouse is inside the app window

### Expected behaviour
it will have the same behaviour when you do a click in the titlebar

### Actual behaviour
it has diferent behaviour when you click on titlebar, the cursor doesn't change when you hover over any of the buttons

### Configuration
**Operating system**: Ubuntu 20.04

**Version of Telegram Desktop**: 2.1.16

**Installation source (Linux Only)** - the official website

**Used theme**: build in "Tinted"

**Comment by ilya-fedin** [comment]
Looks like a bug in Qt xcb backend: after calling startSystemMove/startSystemResize, events are going to be processed in a weird way until you click somewhere in the window. Can't reproduce with wayland backend though.
