### ISSUE TITLE
Data export hangs during miscellaneous data export

### ISSUE THREAD

**Issue by ext4** [telegramdesktop/tdesktop#8197]
### Steps to reproduce
1. Open "Export Your Data" window
2. Uncheck all items except for "Miscellaneous Data"
3. Click "Export"

### Expected behaviour
An export should be created containing the miscellaneous data.

### Actual behaviour
The export starts, and then hangs. Similarly, starting an export of other data will hang if "Miscellaneous Data" is selected.

### Configuration
**Operating system:** Windows 10, Arch Linux

**Version of Telegram Desktop:** 2.1.13

<details><summary><b>Logs</b>:</summary>

```
[16:14:21.423 59-0001027] MTP Info: queueTryToReceive() - need to parse in another thread, 1 responses, 0 updates. (session_private.cpp : 1354)
[16:14:21.423 00-0001028] MTP Info: dcWithShift 50004 can wait for 10000ms from current 0 (session.cpp : 320)
[16:14:21.423 00-0001029] RPC Info: found parser for request 3305, trying to parse response... (mtp_instance.cpp : 1013)
[16:14:21.424 00-0001030] RPC Info: error received, code 500, type INTERNAL_SERVER_ERROR, description: NEED_MEMBER_INVALID (mtp_instance.cpp : 1018)
```

</details>

**Comment by john-preston** [comment]
@ext4 Does this error appear once in the log or a lot of times if you wait for some times? It should resend the query when it receives 500 errors.

**Comment by ext4** [comment]
It keeps reappearing and the export progress bar in the client does not advance. 

In the MTProto debug log a `invokeWithTakeout` `upload_getFile` query is made. The `NEED_MEMBER_INVALID` response is in reply to the `upload_getFile` query.

The export is being taken from dc4, and I have experienced the same issue for a few days.

**Comment by john-preston** [comment]
@ext4 Great, you've looked it up in debug logs. Can you please provide your user id ("id" field from the user with "self: YES" flag) and the full request for the file part?

**Comment by ext4** [comment]
I have sent you this information as a private message on Telegram.

**Comment by ext4** [comment]
Thanks for fixing this.
