### ISSUE TITLE
Tray icon ignores gtk-icon-theme

### ISSUE THREAD

**Issue by r5574** [telegramdesktop/tdesktop#8198]
### Steps to reproduce
1.  Install Telegram 2.1.13-1 from Manjaro repositories.
2.  Start Telegram

### Expected behaviour
Telegram-desktop should pick the corresponding icon from the gtk icon theme. This worked as it should in Telegram-Desktop 2.1.11-1 (also from Manjaro repos):
![telegram-2 1 11-1](https://user-images.githubusercontent.com/44871053/86391385-07332800-bc9a-11ea-894b-dae2d2eb5621.jpg)

### Actual behaviour
Telegram-desktop uses wrong (own?) Icon instead:
![telegram-2 1 13-1](https://user-images.githubusercontent.com/44871053/86391370-026e7400-bc9a-11ea-9176-9dbde97834fa.jpg)

### Configuration
Linux 5.7.6-1-MANJARO running i3wm.

~/.config/gtk-3.0/settings.ini
```
[Settings]
gtk-icon-theme-name=Papirus-Adapta-Nokto-Maia
```

**Comment by ilya-fedin** [comment]
Can't reproduce
![image](https://user-images.githubusercontent.com/17829319/86391874-0397a500-bc8a-11ea-83d0-df29cb8e86ad.png)
Probably you have some misconfiguration (Telegram is a Qt app and it doesn't use gtk-icon-theme until you use gtk platfotrmtheme plugin (`QT_QPA_PLATFORMTHEME=gtk3`))

**Comment by ilya-fedin** [comment]
Already fixed in 2.1.15

**Comment by r5574** [comment]
> Already fixed in 2.1.15
Alright, thanks!
Since you removed your last comment, I will answer here. 
Changing 
`export QT_QPA_PLATFORMTHEME="qt5ct"`
to
`export QT_QPA_PLATFORMTHEME="gtk3"`
in ~/.profile as you pointed out fixes the problem as well.
