### ISSUE TITLE
TDesktop not respecting GNOME's Do Not Disturb setting.

### ISSUE THREAD

**Issue by bosmichal** [telegramdesktop/tdesktop#8199]
I don't know if this behaviour is Wayland-specific, please correct me if I'm wrong.

### Steps to reproduce
1. Have TDesktop use native notifications with sound effects on.
2. Turn on DND in the Notifications tray.
3. A new notification comes in while DND is active.

### Expected behaviour
Pop-up is not shown and sound is not played while DND is on.

### Actual behaviour
Pop-up does not show, but the sound plays.

### Configuration
Fedora Silverblue
GNOME 3.36.3 running on Wayland
Telegram Desktop 2.1.13, Flatpak version, same pattern on AppImage

**Comment by Aokromes** [comment]
try 2.1.17 beta.

**Comment by ilya-fedin** [comment]
tdesktop can't respect gnome's do not disturb setting since gnome doesn't provide any api to get the state of this setting

**Comment by magnus-gross** [comment]
Also shouldn't the notification daemon itself hide notifications in DND mode? I don't think this would be Telegram's fault in any case anyway. KDE's DND mode is working fine for me for example.

**Comment by ilya-fedin** [comment]
> ### Actual behaviour
> 
> Pop-up does not show, but the sound plays.

**Comment by lunapivot** [comment]
I had this exact problem on KDE, too. You may want to disable the **Play sound** option under **Settings**→**Notifications**→**Notifications for chats**.

I wonder if it is because Telegram still plays a sound on its own when a message arrives, even when configured to use the “native notifications”.

**Comment by ilya-fedin** [comment]
> I had this exact problem on KDE, too.

tdesktop uses KDE's don't disturb API that exist in Plasma 5.18+
(but these requests could be denied by snap sandbox if you're using the snap package)

**Comment by ilya-fedin** [comment]
> I wonder if it is because Telegram still plays a sound on its own when a message arrives, even when configured to use the “native notifications”.

This is only cross-DE way. KDE doesn't support `sound` capability at all. GNOME gives no guarantee that codec needed by notification sound is installed and that the sound will be actually played.

**Comment by Tids** [comment]
> tdesktop can't respect gnome's do not disturb setting since gnome doesn't provide any api to get the state of this setting

But you can check dconf for it. It's the /org/gnome/desktop/notifications/show-banners key that is `false`, if DND is active, and `true`, if not.

**Comment by ilya-fedin** [comment]
> But you can check dconf for it.

meh, I don't want to add libraries to work with dconf

And DE-specific settings is not a way to go, this should be addressed in a DE-independent way.

**Comment by Tids** [comment]
I asked at the Forums about that and got an answer.
https://discourse.gnome.org/t/telegram-desktop-devs-have-some-trouble-to-support-gnomes-do-not-disturb-feature/4403/2?u=fabish

ebassi - Emmanuele Bassi - Foundation Staff:
> It’s entirely up the applications to integrate with the platform they are consuming. If Telegram does not want to integrate with GNOME, there’s nothing GNOME can do about it.
> 
> We provide an API—a well known, shared [setting](https://gitlab.gnome.org/GNOME/gsettings-desktop-schemas/-/blob/master/schemas/org.gnome.desktop.notifications.gschema.xml.in#L4-10), and [an API to retrieve its state](https://developer.gnome.org/gio/2.62/GSettings.html#g-settings-get-boolean).
> 
> The Telegram developers may want to have a “shared setting”, which is generally impossible to achieve at the desktop level because each and every desktop has its own configuration system; personally, I think they could implement per-desktop checks, but I’m not a Telegram developer, so they are entirely free not to care.

**Comment by ilya-fedin** [comment]
> If Telegram does not want to integrate with GNOME, there’s nothing GNOME can do about it.

Yeah, that's right. We don't want to integrate with GNOME (or any other DE), we want to integrate with cross-DE specifications or not to integrate at all.

[There are a good proposal of Inhibited property](https://gitlab.freedesktop.org/xdg/xdg-specs/-/merge_requests/24) to the notification spec that already supported by tdesktop.
