### ISSUE TITLE
[Feature Request] Integration with Facebook Messenger

### ISSUE THREAD

**Issue by arcanjoserra** [telegramdesktop/tdesktop#82]
Well, this actually is a request for integration with every messenger and chatting service possible. It feels like there is an urgent need for a universal communication hub and, personally, I feel like Telegram has the overall advantage for being an open source'd app.

Some of you may know https://crypto.cat/
Well, integration of that sort, being able to use Facebook Messenger from within the Telegram Desktop App, would rocket launch this App to the hundreds of millions of users overnight.

Does this make sense. Is it even possible?

**Comment by abs** [comment]
Just a heads up: [Sameroom](https://sameroom.io) now supports Telegram, so you can bridge it a bunch of other systems, including Facebook.

**Comment by mujeebcpy** [comment]
also Matrix supports integration with IRC, slack, twitter etc. also some custome homeservers of Matrix gives [Telegram integrations](https://medium.com/@mujeebcpy/bridging-of-riot-and-telegram-cccb16a955f1) too. so i  think it is possible to do with a bot
