### ISSUE TITLE
Images can't be sent as pictures when chat has slow mode enabled

### ISSUE THREAD

**Issue by Sominemo** [telegramdesktop/tdesktop#8200]
## Steps to reproduce 
1. Open a chat with slowmode
2. Try to insert an image using a clip button or clipboard

### Expected behavior
TD shows a popup with two radios to choose sending the image as a picture or a file

### Actual behavior
TD doesn't show the radios

### Configuration
**Operating system:**
Windows 10, build 2004

**Version of Telegram Desktop:**
2.1.13

![ezgif com-resize](https://user-images.githubusercontent.com/19842935/86414671-4d55af00-bccd-11ea-8bce-1b6142291643.gif)

<b>Logs</b>: [log.txt](https://github.com/telegramdesktop/tdesktop/files/4866871/log.txt)

**Comment by Sominemo** [comment]
Still present

**Comment by Aokromes** [comment]
try on 2.4.8 plz.

**Comment by Sominemo** [comment]
@Aokromes Works now, but new bug appeared: not whatever on what square I drop the file, the "Compress" flag is on.

**Comment by Aokromes** [comment]
i think that's not a bug.

**Comment by Sominemo** [comment]
![1](https://user-images.githubusercontent.com/19842935/98717381-ac22e780-2395-11eb-80e4-01bfcc10bfd7.gif)
![2](https://user-images.githubusercontent.com/19842935/98717391-b04f0500-2395-11eb-828b-f71dd77522f3.gif)
1 - no slowmode
2 - slowmode
