### ISSUE TITLE
[Question] CMake parsing error

### ISSUE THREAD

**Issue by TrueBober** [telegramdesktop/tdesktop#8203]
I'm trying to build the application using the instructions at https://github.com/telegramdesktop/tdesktop/blob/dev/docs/building-cmake.md 
But when I open the application in QtCreator I get a CMake parsing error:

loading initial cache file /tmp/QtCreator-nOKfpj/qtc-cmake-DJJNYwkj/qtcsettings.cmake
Version: 2.1.17.beta
-- The C compiler identification is GNU 8.4.0
-- The CXX compiler identification is GNU 8.4.0
-- Check for working C compiler: /usr/bin/gcc
-- Check for working C compiler: /usr/bin/gcc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/g++
-- Check for working CXX compiler: /usr/bin/g++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for lzma_auto_decoder in /usr/lib/x86_64-linux-gnu/liblzma.so
-- Looking for lzma_auto_decoder in /usr/lib/x86_64-linux-gnu/liblzma.so - found
-- Looking for lzma_easy_encoder in /usr/lib/x86_64-linux-gnu/liblzma.so
-- Looking for lzma_easy_encoder in /usr/lib/x86_64-linux-gnu/liblzma.so - found
-- Looking for lzma_lzma_preset in /usr/lib/x86_64-linux-gnu/liblzma.so
-- Looking for lzma_lzma_preset in /usr/lib/x86_64-linux-gnu/liblzma.so - found
-- Found LibLZMA: /usr/lib/x86_64-linux-gnu/liblzma.so (found version "5.1.0") 
CMake Error at cmake/external/expected/CMakeLists.txt:11 (find_package):
  Could not find a package configuration file provided by "tl-expected" with
  any of the following names:

    tl-expectedConfig.cmake
    tl-expected-config.cmake

  Add the installation prefix of "tl-expected" to CMAKE_PREFIX_PATH or set
  "tl-expected_DIR" to a directory containing one of the above files.  If
  "tl-expected" provides a separate development package or SDK, be sure it
  has been installed.

What could be the problem?

**Comment by ilya-fedin** [comment]
> What could be the problem?

You didn't set `-D DESKTOP_APP_USE_PACKAGED=OFF`

**Comment by TrueBober** [comment]
You're right. 
My carelessness let me down. thank
