### ISSUE TITLE
Application becomes unusable when window is maximized on Windows 10 with multiple monitor on surround setup

### ISSUE THREAD

**Issue by tobbacunningham** [telegramdesktop/tdesktop#8204]
### Steps to reproduce
1.  Open Application
2.  Press Maximise button

### Expected behaviour
Window will maximise

### Actual behaviour
blank screen only and becomes usable

### Configuration
OS: Windows 10 Pro
Triple monitors on surround setup
GTX 1060 GPU
32GB RAM

**Version of Telegram Desktop:**
2.1.17

**Installation source (Linux Only)** - the official website / GitHub releases / flatpak / snap / distribution package:
Downloaded from official website and installed

**Used theme**:
Night Mode

<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by ilya-fedin** [comment]
#3705?

**Comment by stamepicmorg** [comment]
i think my problen resolved by adding this awesome toggle with `2.1.18 beta`
![image](https://user-images.githubusercontent.com/1307229/87303837-7ae7f700-c51c-11ea-89ee-08697edf4783.png)
![image](https://user-images.githubusercontent.com/1307229/87303949-aec31c80-c51c-11ea-9a14-e7e2c8819860.png)
