### ISSUE TITLE
[Feature Request] Get "archive" icon to old place

### ISSUE THREAD

**Issue by Neurotoxin001** [telegramdesktop/tdesktop#8205]
2.1.17:
![7eTVfG3C82](https://user-images.githubusercontent.com/39812401/86475217-f98aaa80-bd4c-11ea-9001-6fe30f5ab843.png)

2.1.13:
![mbirw8s2KQ](https://user-images.githubusercontent.com/39812401/86475221-fa234100-bd4c-11ea-9377-a3d2965d18e1.png)

Users (including myself) are accustomed to opening the archive by clicking on a certain place where the archive icon used to be, but now it has been moved and this is terribly inconvenient.

**Comment by Aokromes** [comment]
i like more the new location :)

**Comment by Neurotoxin001** [comment]
Nvm I already get used to it
