### ISSUE TITLE
[Bug] Searching "@" doesn't show replies in personal chats or bots

### ISSUE THREAD

**Issue by reallyuniquename** [telegramdesktop/tdesktop#8207]
Telegram has a feature (#610 #4121) where searching for `#m` or `@` gives you a list of replies to your messages or mentions.

For some reason this feature doesn't cover personal 1-on-1 chats or bots. 

>Why would you want to search for mentions in personal chats?

Because it allows to quickly pull replies to my requests or questions from chat history. That would be especially useful with noisy bots that constantly dump text but make a reply to commands.

### Steps to reproduce
1. Open chat with a person or a bot
2. Verify that this chat has at least 1 reply to your message
3. Search for `@` or `#m`

### Expected behaviour
List of replies appears.

### Actual behaviour
No messages found.

**Version of Telegram Desktop:**
2.1.13

**Comment by reallyuniquename** [comment]
@john-preston could you take a look at this?

**Comment by RememberTheAir** [comment]
Doesn't work on mobile either and anyway search is done server-side, so tdesktop can't do much about it

**Comment by reallyuniquename** [comment]
@Aokromes is there a way to properly report API issues to devs?

**Comment by Aokromes** [comment]
in app ask a question
