### ISSUE TITLE
Can not scale beyond 150%

### ISSUE THREAD

**Issue by g00nix** [telegramdesktop/tdesktop#8208]
### Steps to reproduce
1. Install Telegram on any distribution running wayland
2. Set `QT_QPA_PLATFORM=wayland-egl` to be able to run telegram
3. Go to settings and try go scale beyond 150%

### Expected behaviour
You should be able to scale up to 250% or 300%

### Actual behaviour
You can scale only up to 150%

### Configuration
**Operating system:** ArchLinux

**Version of Telegram Desktop:** 2.1.13-1

**Installation source (Linux Only)** - pacman, official package on Arch

**Used theme**: Tinted

**Comment by ilya-fedin** [comment]
Can't reproduce on weston
![image](https://user-images.githubusercontent.com/17829319/86516005-c4de2800-be0c-11ea-8eaf-2c61a3b8931e.png)

**Comment by g00nix** [comment]
![image](https://user-images.githubusercontent.com/11086708/86517902-5e213480-be35-11ea-9f81-0618c38ba65d.png)

**Comment by ilya-fedin** [comment]
Maybe you already have a 2x compositor scale?

**Comment by g00nix** [comment]
> Maybe you already have a 2x compositor scale?

Yes, I use `output eDP-1 scale 2` which I need for all other apps. However Telegram doesn't scale with the other apps. It also does not scale with any of the following env vars:

- QT_AUTO_SCREEN_SCALE_FACTOR
- QT_WAYLAND_FORCE_DPI
- QT_FONT_DPI
- QT_SCALE_FACTOR

I also tried without the env vars. 150% is the max scale I get and the text is too small.

**Comment by ilya-fedin** [comment]
Telegram has custom scale engine that can scale up to 300%, if your compositor already scales Telegram 2x, than Telegram can scale only to 150% (i.e. the same 300% physically)

**Comment by g00nix** [comment]
> Telegram has custom scale engine that can scale up to 300%, if your compositor already scales Telegram 2x, than Telegram can scale only to 150% (i.e. the same 300% physically)

Yes, however the compositor does not scale Telegram 2x. :-) Telegram does not a scale as all other apps do. So I am actually stuck with 150%

**Comment by ilya-fedin** [comment]
> Yes, however the compositor does not scale Telegram 2x.

Why then it reports that it is scaled the window, wwhile actually didn't scale? Sounds like a compositor (or Qt) bug

**Comment by g00nix** [comment]
![image](https://user-images.githubusercontent.com/11086708/86519567-8ebc9a80-be44-11ea-885a-551e331d42e1.png)


Does this look like 2x scale?

**Comment by ilya-fedin** [comment]
> Does this look like 2x scale?

Definitely yes
![image](https://user-images.githubusercontent.com/17829319/86519691-c91a3d80-be2c-11ea-913f-b34a5dd299c7.png)

**Comment by g00nix** [comment]
> Definitely yes

In that case, is there any way to scale beyond this? Except hacking it by scaling sway to 1.9 and having Telegram on 300%.

**Comment by ilya-fedin** [comment]
> In that case, is there any way to scale beyond this?

Only if someone adopt Telegram to bigger scale. At least that would mean that additional graphics is needed, but I think only @john-preston what is needed

**Comment by g00nix** [comment]
I think this might be required. Even if your eyes are good enough to see text on a 4k laptop, your head will burn after a day of working with small fonts... And we are also starting to see 8k screens.
It's easy to get fooled by the resolution and leave your fonts/scaling too small.
