### ISSUE TITLE
Default Option for blocking direct and private messages 

### ISSUE THREAD

**Issue by 7h3v01c3** [telegramdesktop/tdesktop#8209]
### Is your feature request related to a problem?
We are getting inundated by Direct Message spam and solicitations or phishers. Blockchain users are losing millions of dollars in crypto because of fake apps or faux admins.

### Describe the solution you'd like
There should be an option to block direct and private messages for anyone, not in the contact list. This should at least be an option one could employ to prevent the above phishing and scamming technique.

### Describe alternatives you've considered
Most crypto communities use bot or announcement or pins to encourage users not to accept support, or updates or communications privately in telegram. But a certain amount of users are tricked into believing they are chatting with the real admin, bot or otherwise and unsuspectingly download or offer information they shouldn't. A default blocking mechanism employed would greatly reduce the attack surface of the user.

### Additional context

![image](https://user-images.githubusercontent.com/16604693/86515379-b58fb800-bdd5-11ea-8163-d6fc434398a2.png)

**Comment by 99darwin** [comment]
Yes, yes, and more yes! Please implement this!

**Comment by Encke** [comment]
Yes, please do! +1 this is a continual problem for the Technology industry too .. "Fake" users are able to send messages to our clients requesting personal information when it is not really us, the app has no internal method to verify that x person is really the person x that I have been speaking with.
This is not an API feature but should be a complete platform based with an option in every client.

**Comment by ArmeF97** [comment]
Something similar already is being implemented https://t.me/tgbeta/4115

**Comment by Brawl345** [comment]
Since usernames were added I got a pretty popular username and I'm getting spammed DAILY by 5-6 randos who want to "buy" my account. This should have been a day one feature!

**Comment by 7h3v01c3** [comment]
> 
> 
> This should have been a day one feature!

It should also be on by default

Allowing the user to turn off when they want to be wide open.

**Comment by 7h3v01c3** [comment]
I see the option coming in android soon. This should be adopted as default in Desktop

**Comment by RememberTheAir** [comment]
@7h3v01c3 the option that is going to be added on android is not the same thing described in this issue. It allows to automatically archive any new chat started by someone who's not in your Telegram contacts - and will be available only to those which the server deems at risk of spam and unwanted PMs. This option will be synced across sessions so enabling it from mobile will hide new chats on desktop too

**Comment by Aokromes** [comment]
such thing must be done api wide, i sugested on telegram beta chat few anti-spam measures, but no luck to get them implemented.

**Comment by ArmeF97** [comment]
Unigram lets you enable an option to auto mute and archive non contacts when they text you

I think that if you enable this on Unigram, it will affect all your telegram clients

**Comment by Aokromes** [comment]
such feature belongs to https://bugs.telegram.org/
