### ISSUE TITLE
[Feature Request] Pin chats in place

### ISSUE THREAD

**Issue by tumyeto** [telegramdesktop/tdesktop#821]
Edit:  Sorry, this is a duplicate of https://github.com/telegramdesktop/tdesktop/issues/601

It would be great if you could pin chats in place so they're not constantly going up and down in the list.  Occasionally this movement causes me to submit a comment into the wrong chat.  

ie, I go to click on the second chat listed but another chat updates at the exact same time, so the chat I wanted to click on got pushed down in the list.   I quickly make my comment and hit enter only to realize I posted it in the wrong chat.

The movement also makes it harder to find chats if you have a long list.  Pinning them in place and being able to rearrange them would make navigation much quicker.

Even if this only applied to group chats it would be nice.

**Comment by ScottRFrost** [comment]
:+1:

**Comment by khwiii** [comment]
Yes please!

**Comment by nevermindmine** [comment]
YES!

**Comment by AhmedDjoudi** [comment]
+\infty
