### ISSUE TITLE
[Feature Request] Allow scheduling of more than 100 messages at a time

### ISSUE THREAD

**Issue by Haulien** [telegramdesktop/tdesktop#8212]
Title says it all. When scheduling messages in groups and channels, telegram currently limits it to 100 items in the queue (be it messages, images, gifs, stickers, etc) at a time. A greater limit (or no limit at all) would be awesome.

**Comment by aemxn** [comment]
No wonder the app crashes while uploading the 101st image. Anyway, I've recorded the crash here if anyone interested:

https://www.youtube.com/watch?v=9V75Qmroi_Q

I was about to write a new issue about this before actually counted how many images I've uploaded. Not gonna waste it there.

**Comment by Aokromes** [comment]
such feature belongs to https://bugs.telegram.org/

**Comment by RememberTheAir** [comment]
Similar suggestion: https://bugs.telegram.org/c/1677
