### ISSUE TITLE
Auto track (mp3) switching does not work.

### ISSUE THREAD

**Issue by oldhowl** [telegramdesktop/tdesktop#8213]
### Steps to reproduce
1. Click to play mp3 file
2. Mp3 file finished

### Expected behaviour
Next track not playing

_Unlike the mobile version, when you click on the play button, the next track is not loaded into the cache and does not turn on automatically next._
### Configuration
**Operating system:** Windows 10

**Version of Telegram Desktop:** 2.1.13

<details><summary><b>Logs</b>:</summary>
No one line for this case
</details>

**Comment by reallyuniquename** [comment]
Autoplaying the next track is actually a great feature I use a lot. But I guess having an opt-out option would not hurt anyone.

>Unlike the mobile version, when you click on the play button, the next track is not loaded into the cache and does not turn on automatically next

Probably for the data consumption reason.

**Comment by oldhowl** [comment]
> Autoplaying the next track is actually a great feature I use a lot. But I guess having an opt-out option would not hurt anyone.
> 
> > Unlike the mobile version, when you click on the play button, the next track is not loaded into the cache and does not turn on automatically next
> 
> Probably for the data consumption reason.

what you meant opt-out? Autoplay not working on desktop. ＞︿＜

**Comment by reallyuniquename** [comment]
You put `Next track not playing` into `Expected behaviour` so I assumed you want Telegram to disable autoplay feature.

>Autoplay not working on desktop.

Are you sure? It does for me.

**Comment by oldhowl** [comment]
> Are you sure? It does for me.

I'm pretty shure. I can take a video, but I think it will be superfluous.
Logs is empty about this.
