### ISSUE TITLE
[Feature Request] Wiki Messages (Collaborative Editing)

### ISSUE THREAD

**Issue by fnetX** [telegramdesktop/tdesktop#8216]
### Is your feature request related to a problem?
Groups can have a way to edit its description. Users can edit their messages. There is no way that multiple users work on one message together. 

### Describe the solution you'd like
Many forum software allows messages or threads to be "wiki posts", so editing the message is allowed to many users. 
I'd love to see an option in Telegram (Desktop) that allows a message to be declared as wiki message and thus can be edited and improved by multiple users. 

### Describe alternatives you've considered
The most common alternative is referring to third-party services like Etherpad, CodiMD or non-FOSS alternatives. For static information, the group's description can be used.
For my use case we're usually copying the message and editing it which is prone to losing track of the many versions.

### Additional context
The use case I imagine is a group that is preparing a public post or a message that is about to be spread somewhere. Using tools like mentioned above is usually a bit overkill for quickly correcting spelling mistakes, adding some formatting or improving some expressions. 
Repeatedly copying and changing messages has other problems as mentioned above. 

I'd really love to see this feature implemented in Telegram. Thank you.

**Comment by GodSaveTheDoge** [comment]
a workaround could be making a channel and adding users as admins with edit permission (so they can edit all the messages, not only the ones from them)

**Comment by fnetX** [comment]
I'm still interested in a fix.

**Comment by ilya-fedin** [comment]
Let's transform Telegram to Wikipedia!

**Comment by fnetX** [comment]
@ilya-fedin This issue's purpose is not to create a new Wikipedia. The purpose of this feature is not to archive information long-term but to allow multiple users to prepare a message / posting etc, whether it's for a public channel or that to people tweak a message for their friend's birthday and add some smileys etc. 

I don't want this to be overkill, no complicated versioning, simply allow a message to be edited and offer the 'edit' option on right-click, may be with a lock to avoid editing conflicts. 

If this is hard to achieve with telegram's API it's okay to declare this as a wontfix. Further, I won't reopen it a second time if no one mentions his or her interest.

**Comment by Aokromes** [comment]
such feature belongs to https://bugs.telegram.org/

**Comment by fnetX** [comment]
I decided I don't actually care any more, I'm currently mostly writing messages on my own so no personal need anymore. 
Just as an info if someone reads this and is still interested, please report yourself.
