### ISSUE TITLE
[Feature Request] Don't update chat list while user interacts with it

### ISSUE THREAD

**Issue by futpib** [telegramdesktop/tdesktop#8217]
### Is your feature request related to a problem?
The problem is the chat list constantly jumps as new messages appear in chats. If you right-click or double-click you can miss the chat you hovered because an update comes in just in time for the list to update under your cursor.

### Describe the solution you'd like
Do not display updates of the chat list for some time after a mouse move or a click in it. This is similar to what Chrome does for it's tabs (they don't move until mouse leaves the tabbar).

### Describe alternatives you've considered
I considered leaving it as is and it sucks.

### Additional context

![Peek 2020-07-07 19-50](https://user-images.githubusercontent.com/4330357/86815492-64105300-c08b-11ea-817a-7dac2476f23d.gif)

**Comment by Aokromes** [comment]
i think you are on the incorrect bugtracker....

**Comment by ilya-fedin** [comment]
#1504
