### ISSUE TITLE
Telegram freezes entire desktop on Ubuntu MATE 15.04

### ISSUE THREAD

**Issue by dleslie** [telegramdesktop/tdesktop#822]
As the title states, Telegram freezes the entire desktop on Ubuntu MATE 15.04; Telegram version is the Linux 64-bit build latest as of the creation of this issue. Not even the mouse cursor can move.

Repro steps:
1. Launch Telegram Desktop
2. Sign in to Telegram
3. Witness Telegram briefly work, as the user list is populated and unread message notifications are present
4. Witness the entire desktop freeze, requiring a hard reboot

I'm running this on a Thinkpad X140e, proprietary AMD drivers but otherwise fairly stock Ubuntu MATE 15.04

**Comment by dleslie** [comment]
I just attempted with the FOSS AMD drivers and the same behaviour occurs.

**Comment by dleslie** [comment]
I just attempted with the Razor-QT desktop and the same behaviour occurs.

**Comment by dleslie** [comment]
The error disappeared after disabling the AMD MicroCode proprietary binaries. (!!!)

So I suppose that means there's a bug in the AMD MicroCode.

**Comment by dleslie** [comment]
... 10 minutes later it crashes in the same way. wut.

**Comment by auchri** [comment]
So I assume that's not a bug of telegram
