### ISSUE TITLE
Channels always appear in unread folder, even if no unread message.

### ISSUE THREAD

**Issue by Vince972** [telegramdesktop/tdesktop#8220]
When you modify the "unread" folder and you add a channel to it, it is always visible in that folder, even if you have read all the messages.
### Steps to reproduce
1. add a channel (include) to the "unread" folder
2. read all messages from that channel
3. the channel is still visible in the folder

### Expected behaviour
1. [...]
2. [...]
3. the channel should disappear from the "unread" folder

### Actual behaviour
The channel is always visible in the "unread" folder

### Configuration
**Operating system:** Linux (Ubuntu Mate)

**Version of Telegram Desktop:** 2.1.13 (**same behavior on the mobile version of Telegram**)
This issue has been present for a long time (I think since the beginning of the folder's fonctionnality.

**Installation source (Linux Only)** - the official website / GitHub releases / flatpak / snap / distribution package:

**Used theme**:

<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by john-preston** [comment]
@Vince972 If you specifically add some chats to the folder, they'll always be there. This is by design.

**Comment by Vince972** [comment]
Ok. But I don't understand as I thought the purpose was to show it only if there were unread messages, like groups or individual chats.

**Comment by RememberTheAir** [comment]
It's the same for individual and group chats. If you pin (or manually include) some of them, they will not be hidden even if you filter out unread chats

**Comment by john-preston** [comment]
@Vince972 Folders first include chat groups that you specify (like Groups / Channels / Contacts), then substract types of chats you don't want to see (like Read / Archived), then adds the exceptions (manually selected chats that are always included in the folder).

**Comment by Vince972** [comment]
Ok. Thank you, I understand now. In fact, my idea was (as I have subscribed to many channels) to configure the folder faster... Instead of exclude each channel one after the other, I excluded every channels and add only the ones that I wanted.

Is there another way ?

Thank you both.

Sorry for my unperfect english... I'm french. I hope everything I say is comprehensible.
