### ISSUE TITLE
Chats missing from chatlist

### ISSUE THREAD

**Issue by TrashAccount3424** [telegramdesktop/tdesktop#8221]
### Steps to reproduce
1. Export all you data with the integrated export function (choose HTML and skip files to speed this up)
2. Open Exported HTML file and search for a "deleted account" open the oldest deleted account you can find.
3. You shoudl be able to read the message you send and the one send by the deleted account.
4. Try to access these messages inside telegram.
5. You can't because the chat is not listed and can't be found trough search either.
5+. Its **important** to choose an old chat recently active/deleted account chats can be found for some reason.
5++. There may be other non-deleted accounts chats "missing" as well related to the same problem. This is just the simplest most likely successful way to reproduce the issue. It obviously needs to be done form an account that has been active for quite a while to find a old deleted account in the export. 

### Expected behaviour
Data is clearly on telegram. I should be able to access and if I wish delete these chats.

### Actual behaviour
Unable to access or delete data.

### Configuration
**Operating system:**
Win 10

**Version of Telegram Desktop:**
2.1.18
**Installation source (Linux Only)** - the official website / GitHub releases / flatpak / snap / distribution package:

**Used theme**:
Default
<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by TrashAccount3424** [comment]
This Problem still persist and absolutely no one at telegram cares.
This issue might be the wrong place for it since its possible api side although the export api can find these chats the UI doesn't show them.
Anyway there is no other meaningful place to report such things none of the or support people even bother to reply and I highly doubt they forwarded any of the information to the people who could actually fix this.

**Comment by Aokromes** [comment]
such feature belongs to https://bugs.telegram.org/

**Comment by reallyuniquename** [comment]
@Aokromes How so? It's not even a feature request. That's a bug.
