### ISSUE TITLE
"Save as" Not working on channel profiles

### ISSUE THREAD

**Issue by foremtehan** [telegramdesktop/tdesktop#8222]
Version : 2.1.13, Windows 10

Click on some profile image (full screen) then right click and press on Save as, Nothing happens.

**Comment by Aokromes** [comment]
works for me on 2.1.18 beta.

**Comment by foremtehan** [comment]
@Aokromes can you download profile pic of this channel ? https://t.me/laratools

**Comment by Aokromes** [comment]
yes https://i.imgur.com/cfYoGTF.png
