### ISSUE TITLE
Group with gps location does not appear in nearby groups

### ISSUE THREAD

**Issue by rainbyte** [telegramdesktop/tdesktop#8223]
### Steps to reproduce
1. Go to "Contacts / Find people nearby"
2. Click on "Create local group"
3. Save GPS location
4. Add people to the group
5. Check that GPS location is the correct one
6. Go to "Contacts / Find people nearby"
7. Look "Nearby groups" list

### Expected behaviour
Group appears in "Nearby groups" list

### Actual behaviour
Group does not appear in "Nearby groups" list

### Configuration
**Operating system:** Android

**Version of Telegram Desktop:** 6.2.0 (1988) arm64-v8a

**Used theme**: classic

**Comment by rainbyte** [comment]
Telegram for Android doesn't have issue tracker, so I reported here.
Please reopen or guide me to the correct issue tracker.

**Comment by Aokromes** [comment]
there is no android bugtracker, use in app ask a question.

**Comment by rainbyte** [comment]
> there is no android bugtracker, use in app ask a question.

I have done that on June 26, but didn't get any answer. I also asked on Twitter but got ignored too.

**Comment by Aokromes** [comment]
> > there is no android bugtracker, use in app ask a question.
> 
> I have done that on June 26, but didn't get any answer. I also asked on Twitter but got ignored too.

you may want to try https://t.me/tgbetachat but it's not official. follow pinned message rules.

**Comment by rainbyte** [comment]
> > > there is no android bugtracker, use in app ask a question.
> > 
> > 
> > I have done that on June 26, but didn't get any answer. I also asked on Twitter but got ignored too.
> 
> you may want to try https://t.me/tgbetachat but it's not official. follow pinned message rules.

Thanks, I will try there.
