### ISSUE TITLE
Can't switch to native window frame on Linux without system tray

### ISSUE THREAD

**Issue by GranPC** [telegramdesktop/tdesktop#8224]
### Steps to reproduce
1. Use a Linux distribution that does not support system tray icons (for example, elementary OS)
2. Open Settings > Advanced
3. Scroll down and look for the "Use native window frame" option

### Expected behaviour
The option is there

### Actual behaviour
The option is not there

### Configuration
**Operating system:** elementary OS 5.1

**Version of Telegram Desktop:** 2.1.18 beta

**Installation source (Linux Only)** - the official website / GitHub releases / flatpak / snap / distribution package: official website

**Used theme**: Tinted

### Proposed solution

Move this config widget out of the tray settings. 
https://github.com/telegramdesktop/tdesktop/blob/f10b2194e605cd0730c23da6472bbb1c12cd8aaf/Telegram/SourceFiles/settings/settings_advanced.cpp#L411

**Comment by ilya-fedin** [comment]
Is this valid on 2.2?

**Comment by GranPC** [comment]
Seems fixed as of 8c4e8212c. Thank you!
