### ISSUE TITLE
Native window frame in windows not switches when window was maximized.

### ISSUE THREAD

**Issue by MairwunNx** [telegramdesktop/tdesktop#8225]
# Steps to reproduce
1. Maximize telegram window.
2. Enable native window frame.
3. Enjoy.

### Expected behaviour
Native window frame must be displayed correctly.

### Actual behaviour
![image](https://user-images.githubusercontent.com/39625750/87043844-60510d80-c1fe-11ea-820f-7187e778a894.png)

As you see, I can't do anything with window, also that not works with `win + any arrow`.

### Configuration
**Operating system:** Windows 10 Home 20H2.

**Version of Telegram Desktop:** 2.1.18 Beta.

**Comment by Aokromes** [comment]
works for me on 21h1.

**Comment by MairwunNx** [comment]
Yeah, but in telegram with custom frame exist bug, when you "maximizing and late try to minimize" you still can't resize window and other stuff. That's random bug with window. I think a lot of users feeling that bug.

When I change the frame in not maximized window state it's change correctly.
![image](https://user-images.githubusercontent.com/39625750/87046115-685e7c80-c201-11ea-9d30-8300116ac04a.png)

But that problem still exist.

**Comment by Aokromes** [comment]
i have maximized window, enabled native windows, unmaximized, moved and resized around.
