### ISSUE TITLE
Heavy audio file without specified duration is missing controls

### ISSUE THREAD

**Issue by vlakam** [telegramdesktop/tdesktop#8226]
### Steps to reproduce
1. Upload mp3 audio via bot api with >10MB size and unspecified duration
2. Try to play this track

### Expected behaviour
As in mobile and swift client: 
Audio file is playable, and you can switch tracks back and forth and track is visible in playlist.
Swift client:
![image](https://user-images.githubusercontent.com/4447247/87047712-83ca8700-c203-11ea-803d-e957584a729d.png)
Telegram android:
![image](https://user-images.githubusercontent.com/4447247/87047852-b3798f00-c203-11ea-8c60-06561b4b3b75.png)

### Actual behaviour
In Telegram desktop audio is playable but buttons for switching back and forth is not available.
Also track is not visible in playlist when listening to other tracks.
![image](https://user-images.githubusercontent.com/4447247/87047414-27676780-c203-11ea-8337-4f54ef7d559a.png)

### Configuration
**Operating system:**
Archlinux
**Version of Telegram Desktop:**
2.1.13
**Installation source (Linux Only)** - the official website / GitHub releases / flatpak / snap / distribution package:
community repository
**Used theme**:
default night mode
<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by vlakam** [comment]
Audio metadata from bot api
`  "audio": {
   "duration": 0,
   "mime_type": "audio/mpeg",
   "title": "Reaching Perfection",
   "performer": "Biodrive",
   "file_id": "CQACAgIAAxkBAAEFVWFfByA9hgz7-8e9q7hJF44Vor1QcwACdQoAAtlJIEj45bA322lYehoE",
   "file_unique_id": "AgADdQoAAtlJIEg",
   "file_size": 12417611
  },`

**Comment by vlakam** [comment]
My current workaround: https://gist.github.com/vlakam/b03eb5c04928272c56f2eb701bb8f7cf
Reupload file and editmessagemedia with specified duration

**Comment by f242** [comment]
@john-preston 
we need **<< >>** buttons, it's very inconvenient bug

**Comment by antrophoss** [comment]
@john-preston 
bump

**Comment by jokerj40** [comment]
@john-preston 
Experiencing same issue

**Comment by fisher122** [comment]
I have the same problem

**Comment by john-preston** [comment]
This should be fixed in the next minor release.

**Comment by vlakam** [comment]
2.4.4
Still broken

**Comment by vlakam** [comment]
Fixed in 2.4.5
