### ISSUE TITLE
Short audio file posted by a link is treated as a document. 

### ISSUE THREAD

**Issue by Terenfear** [telegramdesktop/tdesktop#8227]
### Steps to reproduce
1. Get a direct link to a tiny mp3 file. [This one](http://soundbible.com/mp3/fire_bow_sound-mike-koenig.mp3), for example ([Free Shoot Arrow Sound by Mike Koenig](http://soundbible.com/2108-Shoot-Arrow.html)).
2. Send the link to some chat.

### Expected behaviour
An audio attachment is sent and it can be played by Telegram.

### Actual behaviour
A document attachment is sent. Clicking on it just downloads the file.

Interestingly enough, if you download this file and send it as a message, then it will be displayed in a chat as a proper audio file.

### Configuration
**Operating system:** Windows 10 Version 10.0.18362 Build 18362

**Version of Telegram Desktop:** 2.1.13

**Used theme**: Night

**Comment by john-preston** [comment]
@Terenfear This download and attach is done by server, not by the tdesktop app 😔

**Comment by Terenfear** [comment]
@john-preston Ah, that's what I was afraid of. Can you give me an advice, should I take a shot at the telegram support or there's another bugtracker-like thing for server-related issues?

**Comment by Aokromes** [comment]
in app ask a question.

**Comment by Terenfear** [comment]
@Aokromes Alright, thanks.
