### ISSUE TITLE
Massive lag spikes and graphical error when displaying skin tone modifier

### ISSUE THREAD

**Issue by GodSaveTheDoge** [telegramdesktop/tdesktop#8229]
### Steps to reproduce
1. Copy a skin tone modifier ( 🏽‍)
2. Paste it multiple times and send them in any chat
Note: as Akiyamka suggested, it'll work without spaces between the tone modifiers

### Expected behaviour
![image](https://user-images.githubusercontent.com/51802433/87080843-a4f19e80-c228-11ea-8007-0849897ebba1.png)
This should be shown

### Actual behaviour
![image](https://user-images.githubusercontent.com/51802433/87080875-b5a21480-c228-11ea-9641-939486739edf.png)
![image](https://user-images.githubusercontent.com/51802433/87080940-d36f7980-c228-11ea-9ffd-d5325d9b44c9.png)
This is shown and you can select either all of them or None

### Configuration
**Operating system**: Ubuntu 20.04

**Version of Telegram Desktop**: 2.1.12

**Installation source (Linux Only)**: snap

**Used theme**: Just changed the background from telegram settings (night mode)

It's not shown correctly on android too

**Comment by GodSaveTheDoge** [comment]
i forgot: this cause a lot of lag if you have many messages with them

**Comment by Akiyamka** [comment]
Reproduced for me
note - you need delete space between modifers first

**Comment by GodSaveTheDoge** [comment]
i noticed that in some forks this is fixed

**Comment by ilya-fedin** [comment]
#6416
