### ISSUE TITLE
how to record a long time voice in telegram desktop?[Question] 

### ISSUE THREAD

**Issue by nmadi14** [telegramdesktop/tdesktop#8232]
Hi. I need to record a long time voice by telegram desktop and I'm unwilling to hold the telegram voice icon for a long time. how to lock voice recording in telegram desktop to avoid holding record icon for a long time?

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/3208

**Comment by Aokromes** [comment]
you cannot.
