### ISSUE TITLE
Crashing when I want attach more than four files

### ISSUE THREAD

**Issue by thantez** [telegramdesktop/tdesktop#8235]
### Steps to reproduce
1. Click on attachment icon
2. Select some files (more than 4 items) with holding `Ctrl` key and selecting with mouse
3. Click on `open` buttton
4. Telegram will crash and I should kill it!

### Expected behaviour
Attachment all files at once.

### Actual behaviour
Crashing and not responding. Actually when I select 3 items or less, it doesn't crash.

### Configuration
**Operating system:**
OS: Manjaro 20.0.3 Lysia
Kernel: x86_64 Linux 5.6.16-1-MANJARO
DE: GNOME 3.36.3
**Version of Telegram Desktop:**
telegram-desktop-2.1.10-0.1
**Installation source (Linux Only)** - the official website / GitHub releases / flatpak / snap / distribution package:
pacman (arch package manager)
**Used theme**:
Telegram theme: Native night theme with color #d27570
WM theme: Ant-Dracula
GTK theme: Ant-Dracula-Slim [GTK2/3]
<details><summary><b>Logs (I see this lines in log.txt when crashing will happend)</b>:</summary>
[2020.07.11 13:16:41] HTTP Error: host not found - Host 2001:67c:4e8:f004::b not found

[2020.07.11 13:17:39] HTTP Error: host not found - Host 2001:67c:4e8:f004::a not found
</details>
<details><summary><b>Logs (I see this lines in terminal)</b>:</summary>

```
error: : cannot open
error: : cannot open
error: : cannot open
  OpenType support missing for "DAOpenSansSemibold", script 11

** (nemo:20336): WARNING **: 13:16:22.262: Current gtk theme is not known to have nemo support (Ant-Dracula-Slim) - checking...

** (nemo:20336): WARNING **: 13:16:22.313: The theme appears to have no nemo support.  Adding some...
  OpenType support missing for "DAOpenSansSemibold", script 14
zsh: terminated  telegram-desktop -debug
```

</details>

**Comment by ilya-fedin** [comment]
Can't reproduce on the official build from github releases. Can you reproduce on the official build?

**Comment by thantez** [comment]
> Can't reproduce on the official build from github releases (version 2.1.18). Can you reproduce on the official build?

No. I can't. This issue seems to have been fixed in later revisions.
Thanks.
