### ISSUE TITLE
[KDE] Telegram System Tray Icon Covering other items

### ISSUE THREAD

**Issue by siiikooo0743** [telegramdesktop/tdesktop#824]
I have Kubuntu 14.04 and sometimes Telegram is covering other system tray icons. I think it is when Telegram isn't the last icon to appear. Also Tg is the only icon that is visible when a wine window is moved over the system tray(that is no problem for me, but hints, that the icon is generated in a different way)

**Comment by bil-elmoussaoui** [comment]
duplicate of #424
