### ISSUE TITLE
Main window's shadow does not reset after changing to a monitor with different DPI scaling

### ISSUE THREAD

**Issue by Saxtus** [telegramdesktop/tdesktop#8240]
### Steps to reproduce
1. Start Telegram and have it minimized
2. Switch Windows desktop to another monitor that has different DPI scaling
3. Disconnect previous monitor (can do it from Display settings dialogue, section "Multiple displays")

### Expected behaviour
Telegram should behave itself and not pop up its shadow

### Actual behaviour
Enjoy seeing only the shadow of Telegram window appearing in the desktop, with the only way to hide it to be either exiting Telegram or restoring it and minimizing it again.

### Configuration
**Operating system:** Windows 10 Pro 1909 _(but happens for years, i.e. not a bug that was introduced lately)_

**Version of Telegram Desktop:** v2.1.13 _(but happens for years, i.e. not a bug that was introduced lately)_

**Used theme**: Default

**Comment by ilya-fedin** [comment]
#8133
