### ISSUE TITLE
Wrong day timestamp

### ISSUE THREAD

**Issue by IlyaSofronov** [telegramdesktop/tdesktop#8246]
### Expected behaviour
the days of the month go in sequence

### Actual behaviour
the days of the month go in reverse order
![Выделение_001](https://user-images.githubusercontent.com/26296741/87274639-6e58a400-c506-11ea-88b9-a159763d4fa4.png)

### Configuration
**Operating system:**
Linux Mint 19.3 Tricia
**Version of Telegram Desktop:**
2.1.13
**Installation source (Linux Only)** - the official website / GitHub releases / flatpak / snap / distribution package:

**Used theme**:

<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by seth-rah** [comment]
I've had this occur before, it relates to you changing the time on your own operating system while a telegram session is active.

I don't think this is an issue.

Newest received messages will always be displayed in order, you're not able to bump a message higher in a history.

Example:

![image](https://user-images.githubusercontent.com/2222634/87851607-a2fb9f80-c8fa-11ea-90d9-8c5dde48edd3.png)

Restarting your telegram client will mark the times correctly based on the real times messages were received.

![image](https://user-images.githubusercontent.com/2222634/87851627-ce7e8a00-c8fa-11ea-8a97-c3f86ae40895.png)
