### ISSUE TITLE
Search by mp3 file names does not work

### ISSUE THREAD

**Issue by Timz** [telegramdesktop/tdesktop#8247]
### Steps to reproduce
1. Upload in chat this files https://yadi.sk/d/sYRf-gwEnGs_lA
2. Search "Karlos".
3. 

### Expected behaviour
Both files should be found

### Actual behaviour
Only 1 file is searched

### Configuration
**Operating system:**
win 10
**Version of Telegram Desktop:**
last
**Installation source (Linux Only)** - the official website / GitHub releases / flatpak / snap / distribution package:

**Used theme**:
Dark
<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/6173
