### ISSUE TITLE
[Feature Request] More Advanced Settings (e.g. about:config)

### ISSUE THREAD

**Issue by mortezae** [telegramdesktop/tdesktop#8248]
### Is your feature request related to a problem?
Compared to mobile versions, TDesktop has less custom settings. For example I can change image quality when uploading in some mobile clients but in desktop version, hard-coded default compression ratio losses many image details in some cases.

### Describe the solution you'd like
A somehow hidden settings, or "default configs" like about:config in Firefox may be usable for advanced users.
If you like such feature please list your own favorite custom settings here.

**Comment by RememberTheAir** [comment]
> For example I can change image quality when uploading in most mobile clients but in desktop version

There is no official client that allows to do so 🤔

**Comment by mortezae** [comment]
@RememberTheAir then probably I saw it in plus messenger. btw it's one of useful features. anyway I edited it regarding your comment 🙏🏼

**Comment by ilya-fedin** [comment]
There are already hidden settings:
https://github.com/telegramdesktop/tdesktop/wiki/Command-Line-Switches
https://github.com/telegramdesktop/tdesktop/wiki/Hidden-modes
https://github.com/telegramdesktop/tdesktop/wiki/Environment-variables

**Comment by mortezae** [comment]
Thank you @ilya-fedin , I wasn't aware about ttem.
So I just ask developers to add more customizable constants (like [these](https://github.com/telegramdesktop/tdesktop/wiki/Environment-variables)), and close this issue for now.
