### ISSUE TITLE
Stickers error on Windows Telegram Dektop

### ISSUE THREAD

**Issue by willsnake** [telegramdesktop/tdesktop#825]
Hi!

There's a problem when trying to display the stickers on the destkop app for windows.
Instead of displaying the sticker, it only displays the file.
![evidencia](https://cloud.githubusercontent.com/assets/3495043/8145636/25cd0a26-11d5-11e5-93f2-bb966dcac1bc.png)

**Comment by auchri** [comment]
Duplicate #826

**Comment by willsnake** [comment]
Sorry
