### ISSUE TITLE
[Feature Request] export theme to file

### ISSUE THREAD

**Issue by iddq** [telegramdesktop/tdesktop#8250]
I would like to modify the built-in night time and export it to a file. Thank you.

**Comment by seth-rah** [comment]
In your telegram desktop client, you should be able to select the kebab menu in the chat settings page.

![image](https://user-images.githubusercontent.com/2222634/87852184-063c0080-c900-11ea-851c-167ba8c8ab84.png)

Your initial theme file will be based on the current theme profile.

![image](https://user-images.githubusercontent.com/2222634/87852212-4b603280-c900-11ea-864d-44f3d3a837c2.png)

In the theme editor, select the kebab menu followed by export.

![image](https://user-images.githubusercontent.com/2222634/87852221-69c62e00-c900-11ea-9ff1-aedb16285288.png)

**Comment by iddq** [comment]
Thank you.
