### ISSUE TITLE
[BUG] App crash after try to Save Image As

### ISSUE THREAD

**Issue by ExcpOccured** [telegramdesktop/tdesktop#8252]
### Steps to reproduce
1. Open any chat, it doesn't matter
2. Right click on the message with the image
3. Select the action - Save Image As...

### Expected behaviour
Opens modal window of the file provider

### Actual behaviour
Application ends, including the icon disappears from the tray

### Configuration
**Operating system:** Linux, Ubuntu 20.04 LTS

**Windowing system:** X11, GNOME 3.63.3

**Version of Telegram Desktop:** latest stable,  v 2.1.12

**Installation source:** - snap distribution package

**Used theme**: default, Night Mode is enabled.

**Comment by ExcpOccured** [comment]
I can be more useful if you give information about how I can provide logs 😀

**Comment by ilya-fedin** [comment]
I believe that terminal output would be more informative in that case rather than app logs

**Comment by ExcpOccured** [comment]
> I believe that terminal output would be more informative in that case rather than app logs

Yes, of course, no problem

![Screenshot from 2020-07-15 23-28-58](https://user-images.githubusercontent.com/55463070/87592759-10d57a80-c6f3-11ea-8106-95cf21846fda.png)

**Comment by ilya-fedin** [comment]
Looks like #7819, but it wasn't known what problem is, i had a guess that gtk-common-themes is broken, but it was solved on its own (maybe gtk-common-themes was updated). Maybe gtk-common-themes broken again :thinking: , I recommend to report that on the snapcraft forum.

**Comment by ExcpOccured** [comment]
### Update

The same error occurs for videos and gifs, in general for files with any format ( ͡° ʖ̯ ͡°)

**Comment by ilya-fedin** [comment]
> The same error occurs for videos and gifs, in general for files with any format

Of course, there are only one dialog for all files. But that doesn't move this issue forward, this is something strange that noone here know what it is...

**Comment by ExcpOccured** [comment]
> > The same error occurs for videos and gifs, in general for files with any format
> 
> Of course, there are only one dialog for all files. But that doesn't move this issue forward, this is something strange that noone here know what it is...

I think I can do a debug on my local environment and if successful, commit the fix / report the error in more detail

**Comment by ilya-fedin** [comment]
Would be awesome
