### ISSUE TITLE
App freezes frequently

### ISSUE THREAD

**Issue by GaurangTandon** [telegramdesktop/tdesktop#8253]
Telegram freezes very very frequently and inconsistently. Most of the time, when I am typing a message - even if I only just typed in like 5 words - it would freeze for an indefinite time. Sometimes it unfreezes within 3 seconds and sometimes within 30 seconds, but it is very baffling. It also freezes while searching for a chat, or just opening a picture, almost any action I try to take freezes it.

I have been facing this issue for more than two weeks now, I even tried web.telegram.org but it has too few features.

I know this is not a very helpful report, but I do not know how to generate logs for this, or any other information that would help debug this mysterious freezing behavior.

It should be noted that other apps on my system - that I keep running in the background/foregroud continuously and simultaneously (Firefox, Msft Teams, Discord) work fine without any issue - it is only tdesktop that exhibits this freezing behavior.

### Configuration

**Operating system:** Ubuntu 20.04 (same issue in Ubuntu 18.04)

**Version of Telegram Desktop:** 2.1.13

**Installation source (Linux Only)**: debian file from official website (same issue was in my previous snap installation on my previous 18.04)

**Used theme**: dark

**Comment by john-preston** [comment]
@GaurangTandon I’ll add some logs to the QSaveFile usage to see if this is the case of the problems. If so I can fix it, otherwise we’ll need to find out what is happening first.

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/7952
