### ISSUE TITLE
[Feature Request] Add option to specify an audio device

### ISSUE THREAD

**Issue by sarether** [telegramdesktop/tdesktop#8254]
An external microphone, for example:
`./Telegram -snd_capture=hw:1,0`
etc.

Thanks.

**Comment by Aokromes** [comment]
> An external microphone, for example:
> `./Telegram -snd_capture=hw:1,0`
> etc.
> 
> Thanks.

go to calls, there you can select the input.

**Comment by ilya-fedin** [comment]
#7725
