### ISSUE TITLE
There is a problem with telegram 2.1.10 in manjaro.

### ISSUE THREAD

**Issue by anspent** [telegramdesktop/tdesktop#8256]
Hello.
There is a problem with telegram 2.1.10 in manjaro. When you drag or copy more than 4 photos to telegram, the app freezes. You can only kill the process to make it fall off. Is there a solution to the problem? Noticed in several manjaro linux users.

**Comment by Aokromes** [comment]
latest stable version is 2.1.13, if you are using your distribution package it's outdated. download it from desktop.telegram.org.

**Comment by ilya-fedin** [comment]
#8235

**Comment by anspent** [comment]
Thanks
