### ISSUE TITLE
[Feature Request] Support for audio streams directly through ALSA (snd-aloop)

### ISSUE THREAD

**Issue by sarether** [telegramdesktop/tdesktop#8257]
Telegram (2.1.13) with ALSA without snd-aloop configuration (e. g. ~/.asoundrc) works fine (exept choosing audio devices in Call settings it hungs).

Telegram works with ALSA + snd-aloop configuration but microphone input (audio calls and voice messages) doesn't.

Other applications (e.g. Wire, SimpleScreenRecorder) capture and record from mic input in any cases.

I use ALSA only (w/o PulseAudio) and boot time loaded snd-aloop module for capture playback.

Sound Devices:
```
cat /proc/asound/cards
 0 [HDMI           ]: HDA-Intel - HDA ATI HDMI
                      HDA ATI HDMI at 0xfcba0000 irq 72
 1 [Generic        ]: HDA-Intel - HD-Audio Generic
                      HD-Audio Generic at 0xfcac0000 irq 74
 2 [Loopback       ]: Loopback - Loopback
                      Loopback 1
```
~/.asoundrc:
```
cat ~/.asoundrc
pcm.!default {
	type asym
	playback.pcm LoopAndReal
	capture.pcm LoopRec
	capture.pcm "hw:1,0"
}

pcm.LoopRec {
	type hw
	card Loopback
	device 1
	subdevice 0
}

pcm.LoopAndReal {
	type plug
	slave.pcm mdev
	route_policy duplicate
}

pcm.mdev {
	type multi
	slaves.a.pcm pcm.MixReal
	slaves.a.channels 2
	slaves.b.pcm pcm.MixLoopback
	slaves.b.channels 2
	bindings.0.slave a
	bindings.0.channel 0
	bindings.1.slave a
	bindings.1.channel 1
	bindings.2.slave b
	bindings.2.channel 0
	bindings.3.slave b
	bindings.3.channel 1
}

pcm.MixReal {
	type dmix
	ipc_key 312465
	slave {
		pcm "hw:1,0"
		rate 44100
		periods 128
		period_time 0
		period_size 1024
		buffer_size 8192
	}
}

pcm.MixLoopback {
	type dmix
	ipc_key 327451
	slave {
		pcm "hw:Loopback,0,0"
		rate 44100
		periods 128
		period_time 0
		period_size 1024
		buffer_size 8192
	}
}
```

Run Telegram directly (w/o PulseAudio API emulation):
```
./Telegram
qt5ct: using qt5ct plugin
AL lib: (WW) alc_initconfig: Failed to initialize backend "pulse"
qt5ct: D-Bus system tray: no
error: : cannot open
error: : cannot open
error: : cannot open
```
Telegram has started.
When answering a call the connection breaks. "There is no microphone" like message.

Testing:
mic device is "default" (there are 2 devices: "default" and "default_source_name").
Press "Test microphone".
Telegram hungs.

Run Telegram via apulse:
```
apulse ./Telegram
qt5ct: using qt5ct plugin
[apulse] [error] do_connect_pcm: can't set channel count to 1 for capture device "default". Error code -22 (Invalid argument)
[apulse] [error] do_connect_pcm: failed to open ALSA device. Apulse does no resampling or format conversion, leaving that task to ALSA plugins. Ensure that selected device is capable of playing a particular sample format at a particular rate. They have to be supported by either hardware directly, or by "plug" and "dmix" ALSA plugins which will perform required conversions on CPU.
AL lib: (EE) ALCpulseCapture_connectStream: Stream did not connect: Oops.
qt5ct: D-Bus system tray: no
error: : cannot open
error: : cannot open
error: : cannot open
```
Mic is "default"
Press "Test microphone":
```
E/tgvoip: snd_pcm_open failed: Device or resource busy
[apulse] [error] do_connect_pcm: can't open capture device "default". Error code -16 (Device or resource busy)
[apulse] [error] do_connect_pcm: failed to open ALSA device. Apulse does no resampling or format conversion, leaving that task to ALSA plugins. Ensure that selected device is capable of playing a particular sample format at a particular rate. They have to be supported by either hardware directly, or by "plug" and "dmix" ALSA plugins which will perform required conversions on CPU.
E/tgvoip: pa_stream_connect_record failed: Oops.
W/tgvoip: PulseAudio available but not working; trying ALSA
ALSA lib pcm.c:2660:(snd_pcm_open_noupdate) Unknown PCM
E/tgvoip: snd_pcm_open failed: Device or resource busy
```

Change to "default_source_name".
Press "Test microphone":
```
[apulse] [error] do_connect_pcm: can't open capture device "default". Error code -16 (Device or resource busy)
[apulse] [error] do_connect_pcm: failed to open ALSA device. Apulse does no resampling or format conversion, leaving that task to ALSA plugins. Ensure that selected device is capable of playing a particular sample format at a particular rate. They have to be supported by either hardware directly, or by "plug" and "dmix" ALSA plugins which will perform required conversions on CPU.
E/tgvoip: pa_stream_connect_record failed: Oops.
W/tgvoip: PulseAudio available but not working; trying ALSA
ALSA lib pcm.c:2660:(snd_pcm_open_noupdate) Unknown PCM
E/tgvoip: snd_pcm_open failed: Device or resource busy
```

Press "Microphone icon button" for voice message:
```
[apulse] [error] do_connect_pcm: can't open capture device "default". Error code -16 (Device or resource busy)
[apulse] [error] do_connect_pcm: failed to open ALSA device. Apulse does no resampling or format conversion, leaving that task to ALSA plugins. Ensure that selected device is capable of playing a particular sample format at a particular rate. They have to be supported by either hardware directly, or by "plug" and "dmix" ALSA plugins which will perform required conversions on CPU.
AL lib: (EE) ALCpulseCapture_connectStream: Stream did not connect: Oops.
AL lib: (WW) alcSetError: Error generated on device (nil), code 0xa004
```

~/.asoundrc:
```
cat ~/.asoundrc
defaults.pcm.card 1
```
In this case mic input works:

```
./Telegram
qt5ct: using qt5ct plugin
AL lib: (WW) alc_initconfig: Failed to initialize backend "pulse"
qt5ct: D-Bus system tray: no
error: : cannot open
error: : cannot open
error: : cannot open
```
Choosing audio devices in Call settings it hungs.

Through apulse:

```
apulse ./Telegram
qt5ct: using qt5ct plugin
qt5ct: D-Bus system tray: no
error: : cannot open
error: : cannot open
error: : cannot open
```

Test passed. Choosing audio devices work.

**Comment by ilya-fedin** [comment]
> Telegram works with ALSA + snd-aloop configuration but microphone input (audio calls and voice messages) doesn't.

Telegram uses a separate library for calls, you should choose a dmix/dsnoop device, otherwise one of the libraries will grab the device exclusively and another library won't be able to grab the device. That's how ALSA works.

**Comment by sarether** [comment]
> you should choose a dmix/dsnoop device

I asked about it there: https://github.com/telegramdesktop/tdesktop/issues/8254
not about GUI settings.

**Comment by ilya-fedin** [comment]
> I asked about it there: #8254

There's nothing to do with gui option. You just need to configure dmix/dsnoop over aloop with pcm.!default.

**Comment by sarether** [comment]
OK. I'll try it.
Thanks.

**Comment by Aokromes** [comment]
@sarether

**Comment by sarether** [comment]
It's me.

**Comment by ilya-fedin** [comment]
> It's me.

Can we close the issue? A month has passed.

**Comment by sarether** [comment]
No. Problem is present.

**Comment by sarether** [comment]
I still haven't experimented with the ALSA settings.
I think that such simple behavior should not be based on PulseAudio.

**Comment by ilya-fedin** [comment]
> I still haven't experimented with the ALSA settings.

How long we should wait?

> I think that such simple behavior should not be based on PulseAudio.

It is not based on pulseaudio

**Comment by sarether** [comment]
> It is not based on pulseaudio

OK. So apulse is not PulseAudio emulation for ALSA..

**Comment by ilya-fedin** [comment]
What does apulse have to do with it?

**Comment by sarether** [comment]
With apulse Telegram doesn't crash while answer the call. This crashes happened after adding video calls to Telegram.
I just booted from Linux Mint 20 live USB stick and Telegram works (with PulseAudio).
Telegram crash when answering a call after uninstalling PulseAudio.
"apulse ./Telegram" works fine.

**Comment by ilya-fedin** [comment]
I don't know about the state with video calls, I know that versions before video calls are working fine with alsa for calls

**Comment by sarether** [comment]
No matter. The bottom line is that Telegram uses PA.

**Comment by ilya-fedin** [comment]
Of course it uses PA if you're using apulse. But tdesktop works with pure ALSA too.

**Comment by sarether** [comment]
Telegram crashes after the last update with video calls. Before it Telegram worked without apulse.

**Comment by ilya-fedin** [comment]
>  don't know about the state with video calls, I know that versions before video calls are working fine with alsa for calls

**Comment by ilya-fedin** [comment]
Well, I can confirm that webrtc doesn't support fallback to ALSA.
And that means that tdesktop doesn't support ALSA for calls anymore, sorry, please use pulseaudio.

**Comment by john-preston** [comment]
@ilya-fedin I hope to fix the calls with alsa in the upcoming release. Webrtc has alsa backend, it just doesn’t use it by default.

**Comment by ilya-fedin** [comment]
> Webrtc has alsa backend, it just doesn’t use it by default.

Yeah, and it uses alsa only if compiled without pulseaudio that will broke device choosing for the pulse users

**Comment by john-preston** [comment]
@ilya-fedin But you can try to init default device, and if failed, try to unit alsa explicitly.

**Comment by ilya-fedin** [comment]
> But you can try to init default device, and if failed, try to unit alsa explicitly.

Why they didn't implement auto-fallback :thinking:

**Comment by sarether** [comment]
> > I asked about it there: #8254
> 
> There's nothing to do with gui (or not) option. You just need to configure dmix/dsnoop over aloop with pcm.!default.

Hello.
Can you show an example based on my configuration?

**Comment by ilya-fedin** [comment]
No, I'm too lazy for this, sorry.

**Comment by sarether** [comment]
Telegram 2.4.7 works fine directly through ALSA + snd-aloop.

**Comment by ilya-fedin** [comment]
That quite weird since calls don't support ALSA at all now

**Comment by sarether** [comment]
> That quite weird since calls don't support ALSA at all now

I dont know. The fact is that I've nothing but ALSA only.
