### ISSUE TITLE
[Feature Request] Automatic dark/light theme switching according to OS

### ISSUE THREAD

**Issue by xmha97** [telegramdesktop/tdesktop#8258]
Hello,
Please add below feature:
* Automatic dark/light theme switching according to OS
![Windows 10 Settings](https://user-images.githubusercontent.com/23485114/87549520-2a5ece00-c6c3-11ea-9952-d58f3367ccbb.png)
![Telegram Desktop](https://user-images.githubusercontent.com/23485114/87549297-e5d33280-c6c2-11ea-8da4-07a76d97a39b.png)
Thanks

**Comment by xmha97** [comment]
This feature available on iOS and Android.
# iOS
![Telegram on iOS](https://user-images.githubusercontent.com/23485114/87550256-1d8eaa00-c6c4-11ea-8d7f-6f74055a0ccf.jpg)
# Android
![Telegram on Android](https://user-images.githubusercontent.com/23485114/87550274-241d2180-c6c4-11ea-96ed-66121a48b95d.jpg)

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/4918
