### ISSUE TITLE
Some stickers sets are not sent properly

### ISSUE THREAD

**Issue by codefuhrer** [telegramdesktop/tdesktop#826]
Like that: 
![1434219994544328](https://cloud.githubusercontent.com/assets/2178368/8145630/d06a8264-1217-11e5-84b3-8559ffa15b30.jpeg)

This happens only on TDesktop. For example, iOS (this is the same message as on the first screenshot viewed on the telegram for ios):
![photo18009133335820413](https://cloud.githubusercontent.com/assets/2178368/8145638/40a33878-1218-11e5-8878-3d1f6f8b016c.jpg)

Set (made with @stickers bot): https://telegram.me/addstickers/Kanalja

Other stickers are OK.

**Comment by Mates** [comment]
This happens to me too for new stickers I add to an existing pack. Older stickers (added to the pack in previous versions) are displayed just fine.

**Comment by zackpollard** [comment]
Can we have a fix for this, can confirm it is still happening months later. http://www.zackpollard.pro/at-screenshots/ZJKFpF52.png

**Comment by auchri** [comment]
@zackpollard Please provide a link to the sticker pack ;)

**Comment by zackpollard** [comment]
https://telegram.me/addstickers/SASSAS @auchri

**Comment by auchri** [comment]
@zackpollard The stickers you mentioned:
![image](https://cloud.githubusercontent.com/assets/5092164/11730788/8f3d32c4-9f97-11e5-8376-52193bf29399.png)
have no transparency layer

**Comment by zackpollard** [comment]
I disagree, if you open those stickers you are presented with this.
http://www.zackpollard.pro/at-screenshots/NDuUAMBw.png
http://www.zackpollard.pro/at-screenshots/pWE~PAcP.png
http://www.zackpollard.pro/at-screenshots/6iJopoSX.png
http://www.zackpollard.pro/at-screenshots/ewc~_qTA.png
The last one is the only one without a transparency layer, the first three all have one it's just not shown in that file preview. Also that should not stop them sending as stickers in my opinion.

**Comment by zackpollard** [comment]
http://www.zackpollard.pro/at-screenshots/qlpHRPOM.png
Also from the android client for comparison
