### ISSUE TITLE
Telegram on wayland + hiRes overscale media in lightbox 

### ISSUE THREAD

**Issue by Akiyamka** [telegramdesktop/tdesktop#8261]
### Steps to reproduce
1. Install telegram in system with wayland
2. Run telegram
3. Open any video or image from chat

### Expected behaviour
User can see whole image

### Actual behaviour
Fullscreen:
![image](https://user-images.githubusercontent.com/6587585/87675391-fac1cb80-c77f-11ea-9c3d-97175750134e.png)

### Configuration
**Operating system:**
Fedora 32 (Workstation Edition) 5.7.7-200.fc32.x86_64 
DE: GNOME 
Resolution: 2560x1440 
```
loginctl show-session 2 -p Type
Type=wayland
```

**Version of Telegram Desktop:**
```
2.1.13
```
**Installation source (Linux Only)** - the official website / GitHub releases / flatpak / snap / distribution package:
[rpmfusion](https://fedora.pkgs.org/32/rpmfusion-free-updates-x86_64/telegram-desktop-2.1.13-1.fc32.x86_64.rpm.html)

**Used theme**:
Default night theme, 100% scale
<details><summary><b>Logs</b>:</summary>
> telegram-desktop

```
QSocketNotifier: Can only be used with threads started with QThread
error: : cannot open
error: : cannot open
error: : cannot open
```

When I open media in telegram

```
qt.qpa.wayland: Wayland does not support QWindow::requestActivate()
qt.qpa.wayland: Wayland does not support QWindow::requestActivate()
qt.qpa.wayland: Wayland does not support QWindow::requestActivate()
qt.qpa.wayland: Wayland does not support QWindow::requestActivate()
qt.qpa.wayland: Wayland does not support QWindow::requestActivate()
qt.qpa.wayland: Wayland does not support QWindow::requestActivate()
```

Sometimes I see
```
[swscaler @ 0x7f277c5f0a80] deprecated pixel format used, make sure you did set range correctly
```
</details>

**Comment by Akiyamka** [comment]
Interesting detail:
- open image, you see bug as in description
- press left/right arrow for switching between images and starting from that moment **everything looks normal** (until preview not closed)

**Comment by ilya-fedin** [comment]
> rpmfusion

Please check if issue presents on official builds

**Comment by Akiyamka** [comment]
@ilya-fedin I'm surprised to see that the official build is working as expected

**Comment by ilya-fedin** [comment]
> I'm surprised to see that the official build is working as expected

:thinking: then it is better to report to the package maintainer, I suppose
