### ISSUE TITLE
[Feature Request] Multiple Accounts Support for Desktop Version

### ISSUE THREAD

**Issue by rizmut** [telegramdesktop/tdesktop#8262]
I would love to see multiple accounts support in Telegram Desktop version just like in mobile (Android in my case) since I have two accounts for work and for personal stuff.

**Comment by Aokromes** [comment]
update to beta.

**Comment by rizmut** [comment]
> update to beta.

so this feature will available in future?

**Comment by RememberTheAir** [comment]
@rizmut yes. You can use it right know from the beta, or wait for the stable release

**Comment by rizmut** [comment]
> @rizmut yes. You can use it right know from the beta, or wait for the stable release

Ah good. Thank you
