### ISSUE TITLE
Cancelling sending pasted image from Chrome leads to text in input field

### ISSUE THREAD

**Issue by MasterGroosha** [telegramdesktop/tdesktop#8265]
### Steps to reproduce
0.  Open Google Chrome (cannot reproduce on Firefox)
1.  Go to https://www.reddit.com/r/gaming/comments/hst78q/yeah_im_learning_new_skills/ and copy image to clipboard (right click -> copy image)
2.  Go to Telegram and press Ctrl+V
3.  Cancel sending image by pressing Escape

### Expected behaviour
Image sending cancelled, no other side-effects

### Actual behaviour
Text `r/gaming - yeah I'm learning new skills%0Ahttps://i.redd.it/f0p35i5u7eb51.jpg` (looks like page title on Reddit or smth like that) appears in text input field

### Configuration
**Operating system:** Windows 10
**Version of Telegram Desktop:** 2.1.20 beta
**Web Browser**: Google Chrome 84.0.4147.89 (doesn't reproduce on Firefox 78.0.2)

**Comment by MasterGroosha** [comment]
This is still an issue, btw. TDesktop 2.4.8 beta

**Comment by MasterGroosha** [comment]
WTF

**Comment by ilya-fedin** [comment]
> WTF

If the bot hasn't removed the label, then it hasn't processed your post and will close the issue anyway.

**Comment by Remu-rin** [comment]
Still relevant.
