### ISSUE TITLE
LINUX: Steals focus every time I get a message

### ISSUE THREAD

**Issue by php4fan** [telegramdesktop/tdesktop#8268]
On Ubuntu 20.04 with Cinnamon,

If I leave  Telegram Desktop open and unfocused, it steals focus every time it gets a new incoming message in any chat.

Let's say for example I'm typing this bug report, and I'm writing "This is fucking outrageous!" and while I'm almost finished typing that, I receive a message in Telegram.

Telegram will steal my focus, and it may take me a fraction of a second to realize, during which I'll finish typing my sentence and hit Enter, and hence I end up writing a message that says "outrageous!" and sending it to a random chat (whichever I happened to have left open, not necessarily the one where I received a message). This is a serious issue.

Focus stealing is almost ALWAYS wrong, under almost no circumstances should an application ever steal focus from another one, and if there are some extreme circumstances where that is acceptable, receiving a text in a messaging application is _not_ one of them. You are already generating a popup notification with a sound, that's enough.

I know there is a system setting "prevent window which require attention from stealing focus", it's turned off and I haven't tried turning it on. But regardless of whether that works, Telegram **should not be "requiring attention"** when it receives a new message. This situation does not fall into the scope of "requiring attention". 

I wasn't observing the issue before I switched from Gnome 3 to Cinnamon. I have no idea whether that's a coincidence (an update in telegram installed at the same time as switching from Gnome to Cinnamon) or due to a difference in the way Gnome and Cinnamon handle an application "request for attention", but either way  Telegram clearly is at fault here whether or not it's the only culprit. Thunderbird doesn't still my focus when I get a new email.

**Comment by Aokromes** [comment]
not a but, instead a setting you can disable.

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/7885#issuecomment-628268069
