### ISSUE TITLE
Telegram doesn't honor direction of mouse scrolling

### ISSUE THREAD

**Issue by giordano** [telegramdesktop/tdesktop#827]
If one inverts direction of mouse scrolling, e.g. on GNU/Linux systems with 

    $ xinput set-button-map 12 1 2 3 5 4 7 6 8 9 10 11 12

Telegram doesn't respect it.  I'm not sure this is a bug with Telegram itself or a limitation of Qt5 though (applications with Qt<5 work as expected).

**Comment by hobarrera** [comment]
Actually, telegram explicitly inverts the scroll direction, so it works just the opposite of what's expected by the user, regardless of OS configuration. I've failed to find the code that does this, regrettably.

FWIW, this has already been reported on #508.

**Comment by hobarrera** [comment]
Correction: it works inverted with my mouse, but as expected with my trackpad. I've no idea what to think. o.O

**Comment by auchri** [comment]
So it's not a issue of tdesktop? :smile:

**Comment by hobarrera** [comment]
Why is it not a tdesktop issue?

**Comment by auchri** [comment]
Because I'm pretty sure it's an issue of Qt (as stated in the initial post)

**Comment by hobarrera** [comment]
Is there an upstream issue for this? Or what's the status on the issue?
