### ISSUE TITLE
Separate download folder for each channel under common download folder

### ISSUE THREAD

**Issue by gitaddk** [telegramdesktop/tdesktop#8273]
### Is your feature request related to a problem?
Currently files get download for each channel under one common channel. This is annoying. under common download folder application should create folder for each channel. This way each channel will have it's own download folder. 

### Describe the solution you'd like
Each channel download should go to it's own folder. like 
..\download\channel1
..\download\channel2

### Describe alternatives you've considered
as of now no alternative

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/5788
