### ISSUE TITLE
[Question] Do any tests exist for tdesktop code?

### ISSUE THREAD

**Issue by ashellunts** [telegramdesktop/tdesktop#8274]
I am interested to know if any kind of tests (unit, integration, UI) exist? I can't find any test in source code.

There is a mention of tests in .gitignore and build scripts.
![Screenshot_20200718-110748_Chrome](https://user-images.githubusercontent.com/2046305/87849349-2fe92d80-c8e8-11ea-9964-5674d2bf79f8.jpg)
I see that google test library is also cloned in build scripts.

Is it possible at all to write such a complex software without automated tests?

**Comment by ilya-fedin** [comment]
AFAIK, there was an attempt to write tests, but there are no tests :thinking:

**Comment by ashellunts** [comment]
Thank you the answer. Do Telegram team has extensive manual regression testing?

I would understand (though still this is _very_ difficult) if only one person writes code without tests and he remembers all the situations and corner cases in his head. But with so many features in Telegram (and the fact that there are now more contributors) I can't understand how it is possible to have a stable and quality application (on 3 platforms!)  without any tests.

So either @john-preston and other contributors write code that works and doesn't introduce regressions (never seen such developers before 😄) or there exists extensive manual testing and bug fixes before a release.

**Comment by ilya-fedin** [comment]
There are closed alpha-testing AFAIK

**Comment by ashellunts** [comment]
> AFAIK, there was an attempt to write tests, but there are no tests 🤔

It is curious for me to know why it was not developed further. Does development team not see benefits of having tests or writing tests is not a priority.
 
cc @john-preston
