### ISSUE TITLE
[Feature Request] More than 3 accounts

### ISSUE THREAD

**Issue by ArmeF97** [telegramdesktop/tdesktop#8276]
### Is your feature request related to a problem?
There is a limit for accounts: 3, it's too low

### Describe the solution you'd like
Raise the limit (50, for example)

**Comment by Aokromes** [comment]
it's very likely a "won't fix" i don't think no one other than spammers needs  more than 2-3 accounts.

**Comment by ilya-fedin** [comment]
@Aokromes it's not an api issue, the limit is due to resource consumption AFAIK

**Comment by catSIXe** [comment]
I just prefer having multiple Accounts for OPSEC.

**Comment by catSIXe** [comment]
> @Aokromes it's not an api issue, the limit is due to resource consumption AFAIK

Plus Messenger can do more than 3 Accounts on mobile, so this is literally just nonsense on a desktop. And "Spammers" would prob. just use Docker for starting multiple Desktop Clients... or simpler... use multiple Portable Versions in different folders.

**Comment by ilya-fedin** [comment]
> Plus Messenger can do more than 3 Accounts on mobile, so this is literally just nonsense on a desktop.

That's because multi-account implemented in different ways. Currently, almost all data is not share between accounts and each new added account doubles the memory consumption. And since tdesktop has only 32-bit version on Windows, it will crash after htting the 1 GB limit.

**Comment by catSIXe** [comment]
I thought 32bit can only address 4GB of memory, why is then hitting "the 1GB limit"?

**Comment by ilya-fedin** [comment]
The limit is 2 GB virtual memory per process. In most cases, when Telegram virtual memory reaches 2 GB, task manager shows 1 GB
