### ISSUE TITLE
File extension changed for attachments

### ISSUE THREAD

**Issue by stefan-oskamp** [telegramdesktop/tdesktop#8277]
### Steps to reproduce
1. Send a PocketEarth document in Telegram Desktop (e.g. `xyz.pocketearth_archive`)
2. Check the received document

### Expected behaviour
File should be shared without changing its name.

### Actual behaviour
Telegram Desktop changes `*.pocketearth_archive` to `*_pocketearth`, i.e. the dot is replaced by an underscore and everything from the last underscore is removed. Telegram for iOS does the same.

### Configuration

**Version of Telegram Desktop:**
2.1.13 on Windows 10

**Used theme**:
Day

**Comment by ilya-fedin** [comment]
> Telegram for iOS does the same.

Sounds like the server does this
