### ISSUE TITLE
Increase font size for messages

### ISSUE THREAD

**Issue by matheusfillipe** [telegramdesktop/tdesktop#8278]
### Is your feature request related to a problem?
Just the scaling option isn't enough for making the messages visible. I am already on 150% on a hidpi screen and setting it  to 200% makes the interface weird, but at 150% the text is too small. It would be nice to have it to resize according to a font size. Why not use the system the system font settings for example?

### Describe the solution you'd like
Settings->Chat->Fonts & Font Size.

**Comment by Aokromes** [comment]
#90
