### ISSUE TITLE
[Feature Request] don't show messages from blocked users in group chat

### ISSUE THREAD

**Issue by iddq** [telegramdesktop/tdesktop#8279]
don't show messages from blocked users in group chat. thank you.

**Comment by RememberTheAir** [comment]
Duplicate of #1025, #1281, #5492

**Comment by iddq** [comment]
Why do you close it if it is not implemented?

**Comment by RememberTheAir** [comment]
@iddq because it's an API issue and needs to be implemented in the API first

**Comment by gmsantos** [comment]
@RememberTheAir do the backend have a roadmap, issues, discussions, whatever, for these kinds of issues?

**Comment by RememberTheAir** [comment]
Nope, you can only suggest things to the in-app support or [on Twitter](https://twitter.com/telegram)
