### ISSUE TITLE
How to add stickers in tdesktop for linux?

### ISSUE THREAD

**Issue by dm17** [telegramdesktop/tdesktop#8280]
When I find links like this, then how do I open them in telegram-desktop?
tg://addstickers?set=setname

**Comment by PeterMX** [comment]
copy it and send it to your saved messages, then click on it and you will get a pop up to add them
other option is to open your browser inspector and edit it to be https://t.me/addstickers/setname save and then click on it and it will open tdescktop to add it

**Comment by dm17** [comment]
@PeterMX Helpful - thanks!

**Comment by ilya-fedin** [comment]
> other option is to open your browser inspector and edit it to be https://t.me/addstickers/setname save and then click on it and it will open tdescktop to add it

pasting link of `tg://addstickers?set=setname` format into address bar and pressing enter is enough. At least with Firefox.
