### ISSUE TITLE
[Feature Request] Stop asking for skin color on every emoji

### ISSUE THREAD

**Issue by a14219** [telegramdesktop/tdesktop#8283]
### Is your feature request related to a problem?
After a fresh install, every time you use an emoji with skin color variants, you're prompted to select which skin color you want.
![imagen](https://user-images.githubusercontent.com/64659987/88019138-62359d80-cb29-11ea-9f0e-889d3206aea2.png)

### Describe the solution you'd like
Disable it at all and only choose skin color on right click or long click, or at least save it for all emojis instead doing it one by one (iirc TelegramX on Android had this feature).

**Comment by yashpalgoyal1304** [comment]
https://t.me/designers/146
<script async src="https://telegram.org/js/telegram-widget.js?9" data-telegram-post="designers/146" data-width="100%"></script>

The said design can be experienced at [RocketChat](https://rocket.chat/) (u can try https://chat.inkscape.org/channel/inkscape_user instance of that).

**Comment by yashpalgoyal1304** [comment]
It would be very graceful if 
- all emojis with skin tones could be separated (i.e Smileys vs People). Ref: Win 10 Emoji Panel `Win + . (dot)`
Related with: https://github.com/telegramdesktop/tdesktop/issues/6398#issuecomment-664050789 
- skin tones can be chosen at one global place. Ref: https://t.me/designers/146

Combined ref for both of above: Win 10 emoji panel
![image](https://user-images.githubusercontent.com/19423063/88376646-75f83280-cdbb-11ea-8e8d-33af4f89139e.png)

<details>
<summary>Other similar refs</summary>

Another example of second point: [RocketChat](https://rocket.chat/) (u can try https://chat.inkscape.org/channel/inkscape_user instance of that).

</details>

**Comment by yashpalgoyal1304** [comment]
haha, another one on the list: https://unicode-table.com/en/emoji/#link-component

**Comment by yashpalgoyal1304** [comment]
**update (2020.10.01):** https://gitlab.com/gitlab-org/gitlab/-/issues/15744 mentions the standard unicode emoji order: http://unicode.org/emoji/charts/emoji-ordering.html#people_&_body which also distinguishes people and body.

**Comment by ilya-fedin** [comment]
#7645

**Comment by yashpalgoyal1304** [comment]
i think that one should have been closed as it hadn't any other comments. I know that generally newer ones are closed as duplicates, but this issue has got many comments and that got none, so, this case is exception.

**Comment by yashpalgoyal1304** [comment]
see this for example: https://gitlab.com/inkscape/inbox/-/issues/946#note_259122887

**Comment by edward-pedestrian** [comment]
This is really annoying. It would be very much nicer if they are separated or only shown on right click, etc.
