### ISSUE TITLE
Text blinking when running on GNOME with Wayland

### ISSUE THREAD

**Issue by nikgaevoy** [telegramdesktop/tdesktop#8287]
### Steps to reproduce
1. Start the application.
2. Move cursor, do anything.

### Expected behaviour
Work as usual.

### Actual behaviour
Everything is blinking (see gif below). The gif is cropped to upper left corner in order to hide sensitive data, but the effect remains for the whole window.
![bug](https://user-images.githubusercontent.com/4622305/88119769-11c24c80-cbca-11ea-8c6f-1177e6170ff6.gif)

### Configuration
**Operating system:** Debian 10 (buster), GNOME 3.30.2, Wayland.

**Version of Telegram Desktop:** 2.1.12-2-g0b939e72c                  (1708) 158MB -

**Installation source (Linux Only):** snap

**Used theme:** Night

<details><summary><b>stderr</b>:</summary>
$ telegram-desktop

Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
QSocketNotifier: Can only be used with threads started with QThread
Using Wayland-EGL
EGL not available
Cannot find EGLConfig, returning null config
error: : cannot open
error: : cannot open
error: : cannot open
Using the 'xdg-shell' shell integration
Cannot find EGLConfig, returning null config
</details>

Seems like the bug is somehow connected to Wayland since it does not appear on my second desktop with the same operating system except for X11 instead of Wayland.

**Comment by ilya-fedin** [comment]
You can enable XWayland with DISABLE_WAYLAND=1 if qtwayland works badly for you

**Comment by nikgaevoy** [comment]
Seems like it helped, thanks!
But anyway I think there is a bug, since telegram-desktop is the only app in my system with this issue (weak evidence, but still).

**Comment by ilya-fedin** [comment]
> But anyway I think there is a bug, since telegram-desktop is the only app in my system with this issue (weak evidence, but still).

I think it is only Qt aplplications that tried to work with native wayland on your system. And if you try to run another Qt applications, you will see the same avisual glitches.

**Comment by Aokromes** [comment]
so, 3rd party bug?

**Comment by nikgaevoy** [comment]
> I think it is only Qt aplplications that tried to work with native wayland on your system. And if you try to run another Qt applications with native Wayland, you will see the same visual glitches.

Possible, not probable. I checked clementine to be sure and it works perfectly. Moreover, the bug appeared only after the last update (about a month ago), so I believe it is a tdesktop problem.

**Comment by ilya-fedin** [comment]
> Moreover, the bug appeared only after the last update

previously XWayland was used by default

>  I checked clementine to be sure and it works perfectly.

Are you sure that you started it with native Wayland?

**Comment by nikgaevoy** [comment]
> Are you sure that you started it with native Wayland?

Yes. But I re-checked and found a similar artifact. It somehow appears only inside the tab with album covers and not anywhere else, so I just haven't spotted it. So, yes, it seems to be a third-party bug.

**Comment by ilya-fedin** [comment]
btw, if you can, I recommend to upgrade GNOME version, since old versions of mutter doesn't work well with Qt on Wayland
