### ISSUE TITLE
[Feature Request] Set custom avatars to chats

### ISSUE THREAD

**Issue by baterflyrity** [telegramdesktop/tdesktop#8289]
### Is your feature request related to a problem?
People without avatar (profile photo)  or with bad ones are displayed like letters on random color background. On different platforms this colors are different so visual associations become corrupted.

### Describe the solution you'd like
I suggest to add option to set custom avatar for each chat user is participant in. In case user don't use this feature standard chat avatar (firstly buddy's, secondly generated) is displayed instead.

### Additional context
E.g. my friend has orange avatar with "G" on web but on desktop this one has my boss so I can accidentally send him some strange photos

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/430
