### ISSUE TITLE
Image loading is lagging

### ISSUE THREAD

**Issue by gromoleg** [telegramdesktop/tdesktop#829]
![06152015](https://cloud.githubusercontent.com/assets/9316141/8166364/0211b0a6-13a0-11e5-90fc-eb2a4198b494.png)
![06152015_2](https://cloud.githubusercontent.com/assets/9316141/8166385/33d61c76-13a0-11e5-94e1-e0e795c31e71.png)
Progress bar doesn't move

**Comment by auchri** [comment]
Works fine for me
![loading](https://cloud.githubusercontent.com/assets/5092164/9687893/3f187d4c-532c-11e5-9773-a7b798f3700b.gif)

**Comment by telegramdesktop** [comment]
Perhaps this are some temp server-side problems, can't say for sure.

**Comment by gromoleg** [comment]
seems like that (it was about 15-20 minutes)
but I think progress bar should move while server is not responding, shouldn't it?

**Comment by auchri** [comment]
@gromoleg I agree with you, it should move.

**Comment by telegramdesktop** [comment]
Yeah, that will be fixed in the next version
