### ISSUE TITLE
[Feature Request] Display in a "centralized" location when downloads have completed successfully

### ISSUE THREAD

**Issue by illusoryOne** [telegramdesktop/tdesktop#8292]
Currently, when you download and queue many sizable files consecutively via Telegram Desktop, there is no central place to track if the downloads have successfully completed; one must go to each particular message in Telegram where the download was originally posted, which can be quite tedious in active groups.

I propose that partially downloaded files have their filenames appended with the text ".part", per the convention of many other applications. Then, once the download is finished, renaming the file to its intended filename (eliminating the ".part" extension). This solution is not a truly centralized one as the download completion status would only be visible within one directory at a time via one's file manager, but I imagine in most cases the number of directories one would saving bulk downloads to would be relatively low, or likely even one directory total.

Another more grandiose and truly centralized option would to be to include a downloads tab of some sort in the GUI with progress indicators, but I personally feel this is overkill and resources could be better spent elsewhere.

Cheers :)

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/809
