### ISSUE TITLE
[Question] [Linux] How to change windows title bar to system theme?

### ISSUE THREAD

**Issue by Samleo8** [telegramdesktop/tdesktop#8293]
I'm using Manjaro Linux, Gnome desktop environment 3.36.4 (Arch distribution). 

Currently, my Telegram desktop title bar looks like this:
![image](https://user-images.githubusercontent.com/2712664/88252089-85a24900-ccdf-11ea-9800-579bf121772a.png)
 
But I want it to be similar to my system theme like this (Firefox):
![image](https://user-images.githubusercontent.com/2712664/88252159-c8642100-ccdf-11ea-8067-2a47c64ac219.png)

How do I change it, or is the title style locked in telegram? I'm not used to closing from the right hand side of the screen, and so this has become a bit annoying.

**Things tried:**
Before this update, when there were issues with my window styling, I changed it via qt5ct settings, and it worked. However, it does not work now. 

Similar issue: #6388

**Comment by ilya-fedin** [comment]
> or is the title style locked in telegram?

telegram implements custom titlebar

**Comment by kagestonedragon** [comment]
Settings -> Advanced -> System Integration -> Use system window frame

**Comment by Samleo8** [comment]
thanks @kagestonedragon that was the solution.. closing issue! :D
