### ISSUE TITLE
Not possible to build Telegram using build instructions for Visual Studio

### ISSUE THREAD

**Issue by ashellunts** [telegramdesktop/tdesktop#8294]
> This is not a telegram bug, but a problem with [build instuctions](https://github.com/telegramdesktop/tdesktop/blob/dev/docs/building-msvc.md).

Hello,

I wanted to work on https://github.com/telegramdesktop/tdesktop/issues/6312.
So I followed build instructions. But I have a problem building QT.

```git clone git://code.qt.io/qt/qt5.git qt_5_12_8
cd qt_5_12_8
perl init-repository --module-subset=qtbase,qtimageformats
git checkout v5.12.8
git submodule update qtbase qtimageformats
cd qtbase
for /r %i in (..\..\patches\qtbase_5_12_8\*) do git apply %i
cd ..

configure -prefix "%LibrariesPath%\Qt-5.12.8" -debug-and-release -force-debug-info -opensource -confirm-license -static -static-runtime -I "%LibrariesPath%\openssl_1_1_1\include" -no-opengl -openssl-linked OPENSSL_LIBS_DEBUG="%LibrariesPath%\openssl_1_1_1\out32.dbg\libssl.lib %LibrariesPath%\openssl_1_1_1\out32.dbg\libcrypto.lib Ws2_32.lib Gdi32.lib Advapi32.lib Crypt32.lib User32.lib" OPENSSL_LIBS_RELEASE="%LibrariesPath%\openssl_1_1_1\out32\libssl.lib %LibrariesPath%\openssl_1_1_1\out32\libcrypto.lib Ws2_32.lib Gdi32.lib Advapi32.lib Crypt32.lib User32.lib" -mp -nomake examples -nomake tests -platform win32-msvc
```

QT is checkout out inside `qt_5_12_8 ` folder, but in `configure` command, `-prefix` option uses another folder name `%LibrariesPath%\Qt-5.12.8`.  Is it expected?

When I run `configure` command, it fails beacuse it tries to run `Libraries\Qt-5.12.8\bin\syncqt.exe` , but `Qt-5.12.8` folder is empty.
There is no `syncqt.exe` also in this folder `Libraries\qt_5_12_8\bin`.

```
D:\telegram_build\ThirdParty\jom\jom.exe -f Makefile.Debug
Project MESSAGE: D:\telegram_build\Libraries\Qt-5.12.8\bin\syncqt.exe -module QtZlib -version 5.12.8 -outdir D:/telegram_build/Libraries/qt_5_12_8/qtbase -builddir D:/telegram_build/Libraries/qt_5_12_8/qtbase D:/telegram_build/Libraries/qt_5_12_8/qtbase
The system cannot find the path specified.
Project ERROR: Failed to run: D:\telegram_build\Libraries\Qt-5.12.8\bin\syncqt.exe -module QtZlib -version 5.12.8 -outdir D:/telegram_build/Libraries/qt_5_12_8/qtbase -builddir D:/telegram_build/Libraries/qt_5_12_8/qtbase D:/telegram_build/Libraries/qt_5_12_8/qtbase
```

So I copied `Libraries\qt_5_12_8\qtbase\bin` (with `syncqt.exe`) and put to `Libraries\Qt-5.12.8\bin`, where `configure `expects it.
But now it fails in some other place. Looks like here:
```
 D:\telegram_build\ThirdParty\jom\jom.exe -f Makefile.Release
        link /NOLOGO /DYNAMICBASE /NXCOMPAT /DEBUG /OPT:REF /INCREMENTAL:NO /SUBSYSTEM:CONSOLE "/MANIFESTDEPENDENCY:type='win32' name='Microsoft.Windows.Common-Controls' version='6.0.0.0' publicKeyToken='6595b64144ccf1df' language='*' processorArchitecture='*'" /VERSION:5.12 /MANIFEST:embed /OUT:..\..\..\bin\qlalr.exe @C:\Users\shell\AppData\Local\Temp\qlalr.exe.10292.0.jom
LINK : fatal error LNK1181: ?? ??????? ??????? ??????? ???? "D:\telegram_build\Libraries\qt_5_12_8\qtbase\lib\qtpcre2.lib"
```
And I don't see error message (question marks instead), something wrong with terminal and character set.

Can someone please help me to resolve these issues? Thank you.

**Comment by ilya-fedin** [comment]
>  Is it expected?

Of course, it is installation folder, while you're in source folder

> So I copied `Libraries\qt_5_12_8\qtbase\bin` (with `syncqt.exe`) and put to `Libraries\Qt-5.12.8\bin`

I don't think this is a good idea...

> D:\telegram_build\Libraries\Qt-5.12.8\bin\syncqt.exe

Want to take a look at the full log. Without any manual copying of files.

**Comment by john-preston** [comment]
> When I run configure command, it fails beacuse it tries to run Libraries\Qt-5.12.8\bin\syncqt.exe , but Qt-5.12.8 folder is empty.

configure should not run anything from the -prefix folder, it is the folder, where Qt will be installed after you build it. First is configure step, then build step (jom -j8, for example) then install step (jom -j8 install), the last one will copy everything needed to Libraries/Qt-5.12.8.

**Comment by ashellunts** [comment]
Thank you for responses @john-preston @ilya-fedin 

> > When I run configure command, it fails beacuse it tries to run Libraries\Qt-5.12.8\bin\syncqt.exe , but Qt-5.12.8 folder is empty.
> 
> configure should not run anything from the -prefix folder, it is the folder, where Qt will be installed after you build it. First is configure step, then build step (jom -j8, for example) then install step (jom -j8 install), the last one will copy everything needed to Libraries/Qt-5.12.8.

I got it, but this is output from configure:

```
D:\telegram_build\ThirdParty\jom\jom.exe -f Makefile.Debug
Project MESSAGE: D:\telegram_build\Libraries\Qt-5.12.8\bin\syncqt.exe -module QtZlib -version 5.12.8 -outdir D:/telegram_build/Libraries/qt_5_12_8/qtbase -builddir D:/telegram_build/Libraries/qt_5_12_8/qtbase D:/telegram_build/Libraries/qt_5_12_8/qtbase
The system cannot find the path specified.
Project ERROR: Failed to run: D:\telegram_build\Libraries\Qt-5.12.8\bin\syncqt.exe -module QtZlib -version 5.12.8 -outdir D:/telegram_build/Libraries/qt_5_12_8/qtbase -builddir D:/telegram_build/Libraries/qt_5_12_8/qtbase D:/telegram_build/Libraries/qt_5_12_8/qtbase
```

As you see, configure fails to find syncqt.exe here
**Project ERROR: Failed to run: D:\telegram_build\Libraries\Qt-5.12.8\bin\syncqt.exe**

I will send full configure log in a moment.

**Comment by ashellunts** [comment]
Here are full logs of configure and jom. Configure succeeded but jom failed.

[jom.log](https://github.com/telegramdesktop/tdesktop/files/4965065/jom.log)
[qt.configure.log](https://github.com/telegramdesktop/tdesktop/files/4965066/qt.configure.log)

**Comment by ashellunts** [comment]
I am using VS2019 preview.

**Comment by ilya-fedin** [comment]
Maybe you cloned the repository wrong, it can't find syncqt binary in the repository and tries to find it in the installation path? :thinking:

**Comment by ashellunts** [comment]
I think I messed it up when changed prefix option in configure. I did `git reset --hard` and `git clean -fd` on repo and submodules, but probably some ignored files still remained and affected the build.

Clean clone of repo worked. Closing issue. Thanks.
