### ISSUE TITLE
update it please.

### ISSUE THREAD

**Issue by huezo** [telegramdesktop/tdesktop#8298]
update it please.

![2020-07-23_17-46](https://user-images.githubusercontent.com/15940634/88349367-12afc700-cd0d-11ea-8dac-145086653ccc.png)

https://github.com/telegramdesktop/tdesktop/releases/tag/v2.1.13

https://snapcraft.io/telegram-desktop

**Comment by Aokromes** [comment]
it will be updated when a new stable version is released, for now if you want latest, use edge.

**Comment by WaleedaliAjeebi** [comment]
```
``
```

**Comment by ilya-fedin** [comment]
> it will be updated when a new stable version is released,

no, launchpad integration is broken due to the lack of core20 support (and there are no information when/if it will be). preston need to promote manually every update now (actual stable is 2.1.13 while snap has 2.1.12), what he forgets to do...

**Comment by huezo** [comment]
> > it will be updated when a new stable version is released,
> 
> no, launchpad integration is broken due to the lack of core20 support (and there are no information when/if it will be) now. preston need to promote manually every update now (actual stable is 2.1.13 while snap has 2.1.12), what he forgets to do...

yes that's what I was requesting upgrade to the new stable version which is v2.1.13
https://github.com/telegramdesktop/tdesktop/releases/tag/v2.1.13
and snap has 2.1.12

https://snapcraft.io/telegram-desktop

Why were issues closed? haha!

**Comment by huezo** [comment]
> > it will be updated when a new stable version is released,
> 
> no, launchpad integration is broken due to the lack of core20 support (and there are no information when/if it will be) now. preston need to promote manually every update now (actual stable is 2.1.13 while snap has 2.1.12), what he forgets to do...

Thank you. :+1:  :+1:
