### ISSUE TITLE
Forbid running shell scripts from telegram-desktop, it's not safe

### ISSUE THREAD

**Issue by luntik2012** [telegramdesktop/tdesktop#8301]
![image](https://user-images.githubusercontent.com/8270543/88464953-6ebe4b00-cec7-11ea-92f3-5e9ca6b26121.png)

User must read shell script before execution. Please, add an option to preview script using $VISUAL/$EDITOR or just remove such functionality. Also, I think "Don't ask me again" is unacceptable in this case.

**Comment by ilya-fedin** [comment]
In fact they're opened via xdg-open, I have no idea why this confusing dialog is showing
