### ISSUE TITLE
Suddent data loss on Telegram Desktop 2.1.13

### ISSUE THREAD

**Issue by S-trace** [telegramdesktop/tdesktop#8302]
### Steps to reproduce
1. Receive message with the picture attached as a file
2. Ask your chat parthner to remove tthe message with the attached file
3. The picture is removed from the your device storage without any permission request (!)

### Expected behaviour
The client requests your permission to remove the message and the attached file and don't remove any files from your device without your direct user permission.

### Actual behaviour
The client removed the message and the attached file received earlier (!!!) without any permission request from the user.

### Configuration
**Operating system:**
Kubuntu 20.04 AMD64
**Version of Telegram Desktop:**
2.1.13

**Installation source (Linux Only)** - the official website / GitHub releases / flatpak / snap / distribution package:

**Used theme**:

<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by Aokromes** [comment]
not a bug, intended.
