### ISSUE TITLE
[Feature Request] Specific profile pics for each group

### ISSUE THREAD

**Issue by danivalls** [telegramdesktop/tdesktop#8306]
Currently all users have a profile pic gallery, where the last picture you uploaded is the current profile pic.
Having this feature already developed, wouldn't it make sense to be able to choose a picture from your profile pic gallery to be used on a specific group?

Since the internet seem to love cats, I'll put an example with that:

If I'm member of a telegram group chat "Cat lovers", with this feature I'd be able to have a "normal" picture of myself as general profile pic, but for that group chat I'd be able to use a picture of my cat and me from my profile pic gallery while keeping my "normal" picture as default profile pic for everything else.
So if my boss sends me a message on telegram he'll se a regular profile picture of me, but people inside the Cat Lovers chat would see a derp picture of me playing with my cat.

This feature wouldn't even need to use the profile pic gallery (that was just an starting point for the idea).
Each group could just have a "set profile pic to use inside this group" option.

**Comment by Aokromes** [comment]
https://bugs.telegram.org/c/753
