### ISSUE TITLE
[Question] Telegram apps Github structure

### ISSUE THREAD

**Issue by yashpalgoyal1304** [telegramdesktop/tdesktop#8313]
1. i was wondering why arent all the official clients under one common group (say Telegram project or organization or company or whatever) on GitHub? that way, the different apps would have became different sub[-](https://tx.me/tgbetachat/347443)groups, and hence, the current organisation of things wont change.
I am not proposing it. I understand it might be cumbersome to do that now. just wondering why they werent made that way from start!!

2. what effect would it have or how will the things in that structure different from current structure? would that be better or worse or mixed in any way?

3. is it possible to do so now (possible as in at any cost)? if yes, then what would be the cost/efforts required to do that?

category: meta

**Comment by Aokromes** [comment]
i sugest you to ask on twiter, i told durov to put then into https://github.com/TelegramOrg/ but no luck.
