### ISSUE TITLE
Telegram desktop issue when using in combination with gXNeur

### ISSUE THREAD

**Issue by MikePooh** [telegramdesktop/tdesktop#8317]
There is a problem after update to version 2.2 when using Telegram desktop for Linux (Linux Mint 20, 64bit) in combination with automatic keyboard layout switch program - gXNeur (0.20.0). If the gXNeur is running there is simply impossible to put any text to any text input of the Telegram Desktop. Typing has no effect. gXNeur is kind of old program, last release was in 2016, but there is no issue or same effect in other software.

When gXNeur is running:
Behavior - no text appears in text input after typing
Expected behavior - text appears in focused text input after typing

**Comment by ilya-fedin** [comment]
this is a xneur issue, it doesn't work even with yakuake for me

**Comment by MikePooh** [comment]
There was no such issue on last week when TG Desktop was older version, however I have update some other packages. I will go through last updates and check which package may affect this.

**Comment by ilya-fedin** [comment]
> There was no such issue on last week when TG Desktop was older version

yes, new APIs are used. Unfortunately, you can't stop the progress...
