### ISSUE TITLE
TDesktop 2.2 ignores system windows decoration settings on Linux 

### ISSUE THREAD

**Issue by VBelozyorov** [telegramdesktop/tdesktop#8318]
### Steps to reproduce
1. Open TDesktop

### Expected behaviour
TDesktop's window decoration should looks like other apps' windows

### Actual behaviour
It has some custom title bar which looks against configured system theme and lacks controls for some functionality of my system windows manager.

![изображение](https://user-images.githubusercontent.com/860208/88511816-2cdbf480-cfee-11ea-8663-9181e6dd1cc9.png)
TDesktop's title bar (red) VS Healthy man's title bar (green)
The last one has additional buttons which I've configured in system windows manager's settings for all windows. Also it allows me much more WM's options via context menu (change window behavior, move it between desktops and virtual rooms and so on…). Custom tdesktop's bar allows me nothing of it.

TDesktop is great, thank you for making it! 
I ask you consider to make this custom bar optional to allow user decide what exactly they need.

### Configuration

Operating System: openSUSE Tumbleweed 20200717
KDE Plasma Version: 5.19.3
KDE Frameworks Version: 5.72.0
Qt Version: 5.15.0
Kernel Version: 5.7.7-1-default
OS Type: 64-bit
Graphics Processor: Mesa DRI Intel® HD Graphics 620

**Version of Telegram Desktop:**
2.2

**Installation source (Linux Only)** - the official website / GitHub releases / flatpak / snap / distribution package:
the official website

**Used theme**: classic

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/8310#issuecomment-664049383
