### ISSUE TITLE
Telegram aborts when switching displays in multi-display environment

### ISSUE THREAD

**Issue by vladon** [telegramdesktop/tdesktop#832]
Telegram simply exits when doing anything with desktops in multi-desktop environment.

For example, when switching from "Extend these displays" to "Show desktop only on 1" and vice versa.

![image](https://cloud.githubusercontent.com/assets/477109/8183062/eaf22e16-143d-11e5-89b2-7567b41a7da7.png)

**Comment by Streppel** [comment]
#796

**Comment by Foodfast** [comment]
Seems that isn't only Unix-like OS problem. As I say in that topic, I think problem araund QT freamwork, IMHO.

**Comment by Foodfast** [comment]
Yeah, similar [bug](https://bugreports.qt.io/browse/QTBUG-38650) on win in Qt bugtracker.
