### ISSUE TITLE
[Feature Request] Abbility to react with Emojis to Messages

### ISSUE THREAD

**Issue by ni-oschachtschneider** [telegramdesktop/tdesktop#8322]
### Is your feature request related to a problem?
I want to show my friends that I like there message without writing an real answer

### Describe the solution you'd like
Similiar to the whatsapp favourite or the heart action on instagram a user should be able to quickly like a message

### Describe alternatives you've considered
An alternative I have been using is answering to the message with a emoji

### Additional context
Would also be cool if you could choose the emoji you want to react with

**Comment by ilya-fedin** [comment]
#6277

**Comment by yashpalgoyal1304** [comment]
> Similiar to the whatsapp favourite

unless talking about a recent development which i have not heard of, WhatsApp doent have a favourite (talking literally and not in fancy names acc to app) feature. the star-ing feature in WA is more comparable to bookmark.

**Comment by Aokromes** [comment]
this must be done api wide.

**Comment by yashpalgoyal1304** [comment]
since the other issues are being  closed as a duplicate of this one, can the title be changed to be more accurate - & include "Reactions". 

So, t'd become "Chat reactions" or "Emoji Reactions" or "Emoji reactions in chat". Current title is very confusing and and vague and not precise.

**Comment by Aokromes** [comment]
https://bugs.telegram.org/c/23
