### ISSUE TITLE
[Q] TDesktop v2.2 Linux + Fluxbox + CSD

### ISSUE THREAD

**Issue by ja-koci** [telegramdesktop/tdesktop#8323]
With the update of Telegram Desktop to 2.2 (Linux), the I lost server-side window decorations on the client. This change is breaking most of advanced window manager (Fluxbox) features (no rolling, no grouping with other windows; pinning and setting layer is only available in taskbar). 

1. Is there a way to turn this CSD thing off?
2. Is there a plan to do so? (E.g. Google Chrome has the option to use system decorations)
3. Why is CSD the default? Why not let the window manager do it's job and take care about the client parts? As you can see in the attached screenshot, not only is Telegram stripped of window manager features, but it looks very un-systematic.
![tele-unsys](https://user-images.githubusercontent.com/65960274/88544217-59593600-d019-11ea-81b2-888a1335bb5a.png)

Thank you for your reply & help.

**Comment by ja-koci** [comment]
Here comes Murphy. There is setting in Settings > Advanced > System integration. But my question (3) still holds.

**Comment by Aokromes** [comment]
to make it to look the same crossplatform?

**Comment by ilya-fedin** [comment]
> 3. but it looks very un-systematic

The point is to make the window look consistent with its content, not with other parts of system
