### ISSUE TITLE
Files sharing menu [bug]

### ISSUE THREAD

**Issue by jawadalkassim** [telegramdesktop/tdesktop#8328]
### Steps to reproduce
1. Open Telegram
2. Open chat
3. press send files icons

### Expected behaviour
file explorer menu to choose which file you should send in-front of telegram window

### Actual behaviour
Menu appears behind Telegram Desktop App

### Configuration
OS: Linux Fedora 32

**Version of Telegram Desktop:**
2.2
**Installation source (Linux Only)** - the official website / GitHub releases / flatpak / snap / distribution package:
The official website
**Used theme**:
Tinted
![Screenshot from 2020-07-27 23-51-24](https://user-images.githubusercontent.com/48631694/88591549-2e94cf00-d065-11ea-99e8-b2a1ddef0a8f.png)

**Comment by ilya-fedin** [comment]
Does the issue exist on this binary?
https://github.com/ilya-fedin/tdesktop/actions/runs/187324958

**Comment by xvitaly** [comment]
> Does the issue exist on this binary?

This is known bug with GTK dialogs. I got lots of bug reports for this issue. That's why I decided to drop GTK support.

**Comment by jawadalkassim** [comment]
Yeah, I've installed telegram Flatpak every thing works fine

**Comment by ilya-fedin** [comment]
> Yeah, I've installed telegram Flatpak every thing works fine

What about the binary that I sent?

**Comment by ilya-fedin** [comment]
@jawadalkassim why are you ignoring me?

**Comment by jawadalkassim** [comment]
@ilya-fedin I'm really sorry,this is not on purpose but before I'm getting any answers here, I've already switched to flatpak, and then i left home so I'm using data on my phone and the binary you mentioned is like 220 mb 😂😂

**Comment by ilya-fedin** [comment]
I.e. you won't test?

**Comment by jawadalkassim** [comment]
@ilya-fedin I'll test it when I can download the binary.sorry for late respond

**Comment by jawadalkassim** [comment]
> Does the issue exist on this binary?
> https://github.com/ilya-fedin/tdesktop/actions/runs/187324958
@ilya-fedin 
I've tested this binary and it works fine and this bug is fixed in this release
