### ISSUE TITLE
Promote libtgvoip from fork to independent repository?

### ISSUE THREAD

**Issue by ars3niy** [telegramdesktop/tdesktop#8329]
The original maintainer of https://github.com/grishka/libtgvoip seems to have stepped aside, but this library is still useful and needed. I seems to me your fork of it (https://github.com/telegramdesktop/libtgvoip) has the best claim on being the new upstream on the basis of it having by far the most grandchildren sub-forks. Also, among the forks that have sub-forks, it's the only one to have any pull requests at all (and then full 30 of them, at that).

However, since it's a fork, it's not possible to report issues there, only submit pull requests (which is, incidentally, why I'm submitting this one here on the main project instead). So, how about changing it from a fork in formal github sense to a de-facto fork but which one can submit issues on? Not sure if it's possible without re-creating the repository but even so, if I were in your shoes I would probably go for it.

**Comment by Aokromes** [comment]
i sugested durov to put all projects inside a single organization, no answer.

https://github.com/TelegramOrg

**Comment by xvitaly** [comment]
> Not sure if it's possible without re-creating the repository but even so

It is possible. GitHub support can help.
