### ISSUE TITLE
Telegram crushes with my locale

### ISSUE THREAD

**Issue by JustPieceOfMeat** [telegramdesktop/tdesktop#8331]
### Steps to reproduce
1. aaply locale: t.me/setlanguage/be-beta

### Expected behaviour
Telegram had to continue working after restart

### Actual behaviour
I appied belarussian locale and now I can't start telegram

### Configuration
**Operating system:** Fedora 32

**Version of Telegram Desktop:** 2.1.13-1.fc32

**Installation source (Linux Only):** RPM Fusion

**Used theme**:

<details><summary><b>Logs</b>:</summary>
IDK where I can find log.txt, but when I start telegram-desktop from terminal, it returns

```
QSocketNotifier: Can only be used with threads started with QThread
error: : cannot open
error: : cannot open
error: : cannot open
/usr/include/c++/10/bits/stl_vector.h:1045: std::vector<_Tp, _Alloc>::reference std::vector<_Tp, _Alloc>::operator[](std::vector<_Tp, _Alloc>::size_type) [with _Tp = int; _Alloc = std::allocator<int>; std::vector<_Tp, _Alloc>::reference = int&; std::vector<_Tp, _Alloc>::size_type = long unsigned int]: Assertion '__builtin_expect(__n < this->size(), true)' failed.
zsh: abort (core dumped)  telegram-desktop
```
video: https://vimeo.com/442244186
</details>

**Comment by ilya-fedin** [comment]
> IDK where I can find log.txt

~/.local/share/TelegramDesktop

**Comment by JustPieceOfMeat** [comment]
http://ix.io/2svq

**Comment by ilya-fedin** [comment]
> **Installation source (Linux Only):** RPM Fusion

Check with official binary

**Comment by JustPieceOfMeat** [comment]
Downloaded binaries from desktop.telegram.org, but couldn't run:
```
$ ./Telegram                        
Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.

$ QT_QPA_PLATFORM=wayland ./Telegram
Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
QSocketNotifier: Can only be used with threads started with QThread

$ export QT_QPA_PLATFORM=wayland; ./Telegram 
Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
QSocketNotifier: Can only be used with threads started with QThread

$ echo $QT_QPA_PLATFORM                     
wayland
```

**Comment by ilya-fedin** [comment]
Are you sure that no other instances of telegram desktop running? Wayland doesn't have APIs to focus windows, so that window of the other instance won't show when you trying to launch the binary.

**Comment by JustPieceOfMeat** [comment]
Yes, I forgot to kill Telegram fro RPMFusion.
With official binary all works, thanks.

**Comment by xvitaly** [comment]
Please try the latest version from Koji:

```
sudo dnf install http://koji.rpmfusion.org/kojifiles/packages/telegram-desktop/2.2.0/1.fc32/x86_64/telegram-desktop-2.2.0-1.fc32.x86_64.rpm
```

**Comment by JustPieceOfMeat** [comment]
No, that didn't help. Still crushes with be-beta locale.

**Comment by xvitaly** [comment]
> No, that didn't help. Still crushes with be-beta locale.

Yes, Glibc assertions `-Wp,-D_GLIBCXX_ASSERTIONS` in progress.

It looks like a bug in Telegram Desktop's code: range check for vector failed.

Please show us full backtrace of crash (don't forget to install debug symbols).

**Comment by xvitaly** [comment]
Install debug symbols for version 2.2.0 like this:

```
sudo dnf install http://koji.rpmfusion.org/kojifiles/packages/telegram-desktop/2.2.0/1.fc32/x86_64/telegram-desktop-debuginfo-2.2.0-1.fc32.x86_64.rpm http://koji.rpmfusion.org/kojifiles/packages/telegram-desktop/2.2.0/1.fc32/x86_64/telegram-desktop-debugsource-2.2.0-1.fc32.x86_64.rpm
```

**Comment by JustPieceOfMeat** [comment]
So, and I should just run telegram-desktop with that packages installed?

**Comment by xvitaly** [comment]
> So, and I should just run telegram-desktop with that packages installed?

1. Install telegram-desktop 2.2.0 from Koji.
2. Install debug symbols.
3. Run gdb:
```
gdb /usr/bin/telegram-desktop 2>&1 | tee ~/backtrace.log
```

Enter `handle SIGPIPE nostop noprint`, then `run`.

Cause the crash, then run `bt full` and upload `~/backtrace.log` file to this ticket.

**Comment by JustPieceOfMeat** [comment]
I started with english locale, changed to be-beta and got that: [backtrace.log](https://github.com/telegramdesktop/tdesktop/files/4999174/backtrace.log)

When I stared telegram this way in second time, it didn't crushed, but it wasn't responing and gnome suggested to kill process. After that, I got that: [backtrace2.log](https://github.com/telegramdesktop/tdesktop/files/4999175/backtrace2.log)

**Comment by Aokromes** [comment]
do what it's sugested after 
"
[Inferior 1 (process 54084) exited normally]
"

**Comment by xvitaly** [comment]
> I started with english locale, changed to be-beta and got that: backtrace.log

No crashes here.

> After that, I got that: backtrace2.log

Exception raised from glibc due to `-Wp,-D_GLIBCXX_ASSERTIONS`.

I will try to reproduce this crash on my system.

**Comment by JustPieceOfMeat** [comment]
> do what it's suggested after
> "
> [Inferior 1 (process 54084) exited normally]
> "
[backtrace.log](https://github.com/telegramdesktop/tdesktop/files/4999946/backtrace.log)

**Comment by xvitaly** [comment]
I cannot reproduce. Changed multiple times from EN to BE-beta and got no crashes/assertions.

**Comment by xvitaly** [comment]
@JustPieceOfMeat Maybe you are using some custom themes? Can you try the default theme?

**Comment by JustPieceOfMeat** [comment]
Just installed Fedora 32 on VM, telegram desktop crushes with be-beta. In settings I changed only screen resolution.

**Comment by JustPieceOfMeat** [comment]
Tried `LANG=en_US.UTF-8 LC_ALL=en_US.UTF-8 telegram-desktop`, that's works. My current locale settings:
```
$ locale
LANG=be_BY.UTF-8
LC_CTYPE="be_BY.UTF-8"
LC_NUMERIC="be_BY.UTF-8"
LC_TIME="be_BY.UTF-8"
LC_COLLATE="be_BY.UTF-8"
LC_MONETARY="be_BY.UTF-8"
LC_MESSAGES="be_BY.UTF-8"
LC_PAPER="be_BY.UTF-8"
LC_NAME="be_BY.UTF-8"
LC_ADDRESS="be_BY.UTF-8"
LC_TELEPHONE="be_BY.UTF-8"
LC_MEASUREMENT="be_BY.UTF-8"
LC_IDENTIFICATION="be_BY.UTF-8"
LC_ALL=
```

**Comment by xvitaly** [comment]
> Just installed Fedora 32 on VM, telegram desktop crushes with be-beta. In settings I changed only screen resolution.

No crashes on laptop, desktop and 2 VMs.

Please try X11, not Wayland.

**Comment by xvitaly** [comment]
Tried `LANG=be_BY.UTF-8 LC=be_BY.UTF-8 /usr/bin/telegram-desktop` - no crashes.

**Comment by JustPieceOfMeat** [comment]
https://paste.centos.org/view/e2fd8e62

So, without internet or login telegram works. It crushes only after messages loading

**Comment by ilya-fedin** [comment]
> crushes
> u

😕

**Comment by JustPieceOfMeat** [comment]
Oops

**Comment by xvitaly** [comment]
> So, without internet or login telegram works. It crashes only after messages loading

Still cannot reproduce.

> 5.6.6-300.fc32.x86_64

Ancient kernel. Can you try to install all available updates for Fedora by running `sudo dnf upgrade --refresh`?

After installation restart your computer and try to run Telegram Desktop again.

**Comment by JustPieceOfMeat** [comment]
So, that was VM with just reinstalled fedora. After updates: https://paste.centos.org/view/d7a8fbbe

And from my main Fedora: https://paste.centos.org/view/bfbebce9

**Comment by JustPieceOfMeat** [comment]
> Still cannot reproduce.
May be I somehow can send you VM image, where I can reproduce it?
