### ISSUE TITLE
Incorrect calculated result in opened poll

### ISSUE THREAD

**Issue by komnotmr** [telegramdesktop/tdesktop#8333]
### Steps to reproduce
1. Create poll with 2 choices - A, B
2. Do 6 votes for A and 1 vote for B
3. See result - 86% vs 14% in dialog
4. Open the poll
5. See result - 85% vs 14%

### Expected behaviour
86% vs 14% in opened Poll

### Actual behaviour
85% vs 14% in opened Poll

### Configuration
**Operating system:** Ubuntu 18.04.4 TLS
**Version of Telegram Desktop:** Version 2.2
**Used theme**: default

![2020-07-28 14-17-57](https://user-images.githubusercontent.com/20460576/88632441-c7ffc780-d0dd-11ea-9a81-d5e48c1b4bc2.png)
![2020-07-28 14-18-03](https://user-images.githubusercontent.com/20460576/88632445-c930f480-d0dd-11ea-81d7-0c81db8e9169.png)

**Comment by oleg-sysoev** [comment]
I have the same problem.
**Operating system**: Windows 10 Home Version 2004
**Telegram Desktop**: Version 2.3.1
![image](https://user-images.githubusercontent.com/12149508/91019397-96552000-e5f9-11ea-8e66-7ed6c2043645.png)
