### ISSUE TITLE
New "close" bar on top

### ISSUE THREAD

**Issue by WhyNotHugo** [telegramdesktop/tdesktop#8334]
### Steps to reproduce
1.  Run telegram

### Actual behaviour

Since the latest update (v2.2.0), there's a new bar on top with just a close button.
It takes up a lot of space, and honestly, provides no real value [at least to me].

It's also very confusing, since it visually looks like the tab bar my WM shows in the exact same place, with the same colours, and extremely similar height.

### Expected behaviour

Don't show this bar, just like previous versions of Telegram, and like any other desktop application.

### Configuration
**Operating system:** ArchLinux

**Version of Telegram Desktop:** 2.2.0

**Installation source (Linux Only)** - the official website / GitHub releases / flatpak / snap / distribution package: Distribution package

**Used theme**: Tinted

### Screenshot:

**v2.2.0**

![2020-07-28T10:25:09,206402419+02:00](https://user-images.githubusercontent.com/730811/88639070-e056ee80-d0ab-11ea-96a9-d3fce451c995.png)

**v2.1.13**

![2020-07-28T10:26:48,750190528+02:00](https://user-images.githubusercontent.com/730811/88639303-2a3fd480-d0ac-11ea-8ce8-6acfa5b64ca9.png)

I've checked other Qt apps, and no other app has this behaviour; it seems to be Telegram-specific.

**Comment by ilya-fedin** [comment]
https://github.com/telegramdesktop/tdesktop/issues/8310#issuecomment-664049383

**Comment by WhyNotHugo** [comment]
Ah, thanks!

Can this be the default value? Why does Telegram need to behave differently from **all** other applications on this aspect?

**Comment by ilya-fedin** [comment]
> Can this be the default value?

I don't think that different default value for linux is possible.

> Why does Telegram need to behave differently from **all** other applications on this aspect?

Teoegram uses custom decorations on all platforms by default, I think this is a part of design :thinking:

**Comment by Aokromes** [comment]
> Ah, thanks!
> 
> Can this be the default value? Why does Telegram need to behave differently from **all** other applications on this aspect?

application wide standard.

**Comment by WhyNotHugo** [comment]
> application wide standard.

Uhm, I can understand that might might render something that makes sense on macOS or Windows, but on Linux I just get a huge, useless bar with a tiny button in a corner.

There's also no examples of any other app doing anything similar on Linux, I don't see how this is "by design" rather than a plain bug

**Comment by ilya-fedin** [comment]
> Uhm, I can understand that might might render something that makes sense on macOS or Windows

It is a copy of the Telegram's titlebar from Windows.

**Comment by WhyNotHugo** [comment]
This issue has worsened. The useless bar (I mean, it takes up a ridiculous amount of space, just to show an exit button) has suddenly returned.

As per the link above, the workaround for this issue was:

> go settings, advanced, change "use system windows frame"

However, this setting is now gone. I'm getting the Windows title bar on Linux again, and there seems to be no way of disabling it...?

**Comment by WhyNotHugo** [comment]
Oh, it seems that the bug has re-arisen due to my changing `XDG_CURRENT_DESKTOP=sway` to `XDG_CURRENT_DESKTOP=sway:gnome`.

However, this setting is **required** for GTK applications to use their antialiasing.

**Comment by WhyNotHugo** [comment]
It seems there's a few others reporting this same bug. Is it really going to be a `WONTFIX`?

While I understand this behaviour may be desireable for window users so that Telegram looks like other Windows applications, it really does not make sense on Linux, where we _don't_ expect applications to behave like other Windows applications.

**Comment by ilya-fedin** [comment]
> However, this setting is **required** for GTK applications to use their antialiasing.

WTF, I have antialiasing without such hacks

**Comment by WhyNotHugo** [comment]
Sorry, "This setting is required for GTK applications to use their antialiasing when **running via flatpak**." This is further discussed [here](https://github.com/flatpak/flatpak/issues/2861).

**Comment by ilya-fedin** [comment]
It works for me without any XDG_CURRENT_DESKTOP changes, xdg-desktop-portal automatically fallback to xdg-desktop-portal-gtk as a Settings portal provider for me

Anyway, you really can't override XDG_CURRENT_DESKTOP and think that applications will behave right, since they assume that you're running GNOME.

**Comment by WhyNotHugo** [comment]
> It works for me without any XDG_CURRENT_DESKTOP changes, xdg-desktop-portal automatically fallbacks to xdg-desktop-portal-gtk as a Settings portal provider

I think this is getting a bit tangential, but anyway:

Previously, my setting was `XDG_CURRENT_DESKTOP=sway`. This makes screen sharing work on various applications, but GTK applications don't render properly on flatpak. Ever. Setting `XDG_CURRENT_DESKTOP=sway:gnome` makes GTK apps render properly. 

This is because GTK applications rely on this portal -- it's not actually a just a "gnome" portal, but includes requirements for GTK applications. To quote one of the devs on the above thread:

> xdg-desktop-portal-gtk must always be run in order to ensure the availability of the settings portal

That is, even on non-gnome desktops.

---

> Anyway, you really can't override XDG_CURRENT_DESKTOP and think that applications will behave right, since they assume that you're running GNOME.

Yeah, I get that. The problem is that there seems to be no way for Telegram to work without breaking other things.

- The **real** bug here is: Telegram renders the "close-button bar" even on Linux by default. I still don't understand why that's a WONTFIX. Again, what's the point of an entire bar on top of the application, to show one single icon?
- Telegram assumes I'm running GNOME when `XDG_CURRENT_DESKTOP=sway:gnome`. It should probably assume that my desktop is _the first_ value, not the last. `XDG_CURRENT_DESKTOP` is used to determine which portal**s** are to be run, not necessarily a single one. I'd argue that assuming that the _last_ value is the current desktop is also a bug.
- Additionally, disabling it is not possible when it _thinks_ I'm running gnome. I don't have strong opinions about this; that's for gnome users to decide.

**Comment by ilya-fedin** [comment]
> This is because GTK applications rely on this portal -- it's not actually a just a "gnome" portal, but includes requirements for GTK applications. To quote one of the devs on the above thread:

You shouldn't change XDG_CURRENT_DESKTOP in order to have xdg-desktop-portal-gtk work

>     * I still don't understand why that's a WONTFIX

Telegram aims to looks on all the platforms identically. Telegram doesn't aim to be a native-looking application.

>     * It should probably assume that my desktop is _the first_ value, not the last

If assumes that your desktop is all values. E.g. if you specify XDG_CURRENT_DESKTOP=KDE:GNOME, both KDE and GNOME hacks will be activated. The behavior is undefined when XDG_CURRENT_DESKTOP reports two different desktops with any application.

>     * Additionally, disabling it is not possible when it _thinks_ I'm running gnome. I don't have strong opinions about this; that's for gnome users to decide.

The setting is hidden on GNOME since GNOME doesn't support xdg-decoration protocol and there's just no 'system window frame'

**Comment by ilya-fedin** [comment]
>     * to show one single icon?

Decoration layout is read from gtk-decoration-layout property.

**Comment by WhyNotHugo** [comment]
> You shouldn't change XDG_CURRENT_DESKTOP in order to have xdg-desktop-portal-gtk work

That's pretty much what the `xdg-desktop-portal` documentation indicates. It's also what's been confirmed in the above linked flatpak thread by one of the devs. 

`xdg-desktop-portal-gtk` will not run magically by itself. And if `XDG_CURRENT_DESKTOP=sway` **it will** not run. I need to change `XDG_CURRENT_DESKTOP` for the gtk portal to be executed by `xdg-desktop-portal`.

This is all expected and described behaviour by all the involved apps.

> Telegram aims to looks on all the platforms identically. Telegram doesn't aim to be a native-looking application.

There's a difference between style choices, and just rendering an empty bar on top of the application. I'm not asking for it to be native, I'm just asking for an empty bar to be removed.

Why is this bar so important anyway?

I think the discussion has gotten too much into technicalities, and we're honestly skipping the important facts: the bar provides no value whatsoever, takes up space, and is just confusing. It's a technical side-effect of some feature on another OS, but there's really no reason for it to be there.

> If assumes that your desktop is all values. E.g. if you specify XDG_CURRENT_DESKTOP=KDE:GNOME, both KDE and GNOME hacks will be activated. The behavior is undefined when XDG_CURRENT_DESKTOP reports two different desktops with any application.

I understand this is the current behaviour. Given that [Flatpak requires that `XDG_CURRENT_DESKTOP=whatever:gnome`](https://github.com/flatpak/flatpak/issues/2861#issuecomment-735476004), the latter must always be present. Well, it can be absent, but GTK applications will misbehave.

It seems that Flatpak and telegram have conflicting expectations of this variables: Flatpak expects `gnome` to be present in _any_ environment, whereas Telegram assumes it will only be present in Gnome environments.

**Comment by WhyNotHugo** [comment]
> Decoration layout is read from gtk-decoration-layout property.

Do you mean the gsettings property?  
This value is not present in my system. Since I'm not running GNOME, I don't have gnome's schemas, so I cannot set this property either.

**Comment by ilya-fedin** [comment]
> `xdg-desktop-portal-gtk` will not run magically by itself. And if `XDG_CURRENT_DESKTOP=sway` **it will** not run. I need to change `XDG_CURRENT_DESKTOP` for the gtk portal to be executed by `xdg-desktop-portal`.

https://github.com/flatpak/xdg-desktop-portal/blob/dbbe2180384154c642f837cc50a1ff0b1b5a6a34/src/portal-impl.c#L208-L218
I don't know about sway, it successfully runs on Weston for me. Thanks to this logic.

>  I'm just asking for an empty bar to be removed.

It's not empty.

> Why is this bar so important anyway?

I don't understand this question.

> Do you mean the gsettings property?

No, I mean [a property of GtkSettings object](https://developer.gnome.org/gtk3/stable/GtkSettings.html#GtkSettings--gtk-decoration-layout). I don't know which GNOME gsettings key it's mapped to. On MATE it's /org/mate/desktop/interface/gtk-decoration-layout.

> In other words: this is a gnome-specific setting. It can't be set without gnome installed.

This is how GTK works on Wayland, it reads GNOME gsettings keys instead of the XSettings protocol ¯\_(ツ)_/¯

**Comment by ilya-fedin** [comment]
> Flatpak expects `gnome` to be present in _any_ environment

It's not flatpak expects, it's GTK developers vendor locks on GNOME... Qt is able work on any environment in Flatpak without any issues, but GTK requires their daemon and they made it in a way that it assumes that it always runs on GNOME.

**Comment by WhyNotHugo** [comment]
> https://github.com/flatpak/xdg-desktop-portal/blob/dbbe2180384154c642f837cc50a1ff0b1b5a6a34/src/portal-impl.c#L208-L218
> I don't know about sway, it successfully runs on Weston for me. Thanks to this logic.

Again, I **need** to set `XDG_CURRENT_DESKTOP=sway:gnome`.

- Without setting `XDG_CURRENT_DESKTOP`, screensharing and similar features that rely on the sway-specific portal fail on various applications. This breakage is the expected behaviour, and matches the documentation of `xdg-desktop-portal` and `xdg-desktop-portal-wlr`.
- `XDG_CURRENT_DESKTOP=sway` fixes screen sharing. However, GTK flatpak applications misbehave, as discussed in the linked issue...
- `XDG_CURRENT_DESKTOP=sway:gnome` fixes both screen sharing, and GTK applications. I came to this fix in the above linked issue, which explains that this is required for flatpak.

If `XDG_CURRENT_DESKTOP` is set, it **must** include `:gnome` at the end, or GTK flatpak applications will misbehave. It probably works on your system because you only have one portal and are only relying on one portal.

> > Why is this bar so important anyway?
>
> I don't understand this question.

Why is keeping this bar so important? It feels like a bug, or a visual glitch, what makes it so important? What motivates you to stretch this discussion, instead of just addressing the issue?

> In other words: this is a gnome-specific setting. It can't be set without gnome installed.
> This is how GTK works on Wayland, it reads GNOME gsettings keys instead of the XSettings protocol ¯_(ツ)_/¯

**WHAT**? You said that this "decoration layout" is read from this key. I assume by "decoration layout", you meant this decoration-bar that telegram has on top.
If I wanted to remove this bar, do I need to install gnome, just to get the right setting schema so I can configure it?

>> Flatpak expects gnome to be present in any environment
>
> It's not flatpak expects, it's GTK developers vendor locks on GNOME

I agree on this, and also hate this attitude on behalf of GTK. (Thank you for using Qt).

Running GTK applications on Flatpak expects me to include `XXX:gnome` in `XDG_CURRENT_DESKTOP` and have specific gnome dependencies installed. It's absurd, but I can't just "stop using GTK apps", regrettably.

**Comment by ilya-fedin** [comment]
> It probably works on your system because you only have one portal and are only relying on one portal.

That's wrong, I have two portals: KDE and GTK. I configured them in a way that FileChooser is used from KDE one, while all other is from GTK one.

> If `XDG_CURRENT_DESKTOP` is set, it **must** include `:gnome` at the end

I have XDG_CURRENT_DESKTOP set and it doesn't include `:gnome' at the end and it works just like a charm for me.

> Why is keeping this bar so important?

This is a subjective thing. A lot of users like the custom titlebar.

>  I assume by "decoration layout", you meant this decoration-bar that telegram has on top.

No, I mean the layout of the buttons on the decoration (titlebar).

> If I wanted to remove this bar, do I need to install gnome, just to get the right setting schema so I can configure it?

If you want to remove this bar, you **shouldn't** install gnome, if you want to configure it, then you should configure it via gtk since Qt doesn't provide the same functionality. On X11 gtk defaults to `menu:minimize,maximize,close`, on Wayland it uses GNOME's standard `appmenu:close`

**Comment by WhyNotHugo** [comment]
I understand that not setting `XDG_CURRENT_DESKTOP` somehow works for you.

That's it not the case for me. The documentation for my desktop portal very clearly indicates that without setting the variable it won't work. The feedback from the Flatpak developers is that things  won't work without setting it. Many weekends of experimentation have proved that my setup only works when following this advise. There is no clear reason why it _should_ work.

Your setup _somehow_ works, however, this is not by design. It doesn't matter how much you insist on "it work for me": this repetition won't make my setup work. I've no idea _why_ things like screen sharing work for you without a dedicated portal implementation. Maybe talking back to the first one luckily matches a compatible implementation due to your combination of installed portals and compositor?

It doesn't for other desktops, however, and all the involved applications confirm that it is expected that it shouldn't work. The fact that it somehow works for you sounds like a mere coincidence.

> This is a subjective thing. A lot of users like the custom titlebar.

It's an odd design choice: a mostly empty, flat large bar covering the entire width of the application. I can't say I've seen anything alike in any other application. But I'll respects others aesthetic choices, it's a matter of taste, ultimately.

Given that it's only decorational, and serves no functional purpose, I do continue wishing it could be disabled, regardless of what desktop Telegram may assume I'm using.

**Comment by ilya-fedin** [comment]
> Given that it's only decorational, and serves no functional purpose, I do continue wishing it could be disabled, regardless of what desktop Telegram may assume I'm using.

It should check for actual xdg-decoration presence, but I don't know how to work with libwayland and QtWayland doesn't provide any API for that, so checking for XDG_CURRENT_DESKTOP is currently the only way to avoid Qt's ugly dummy decoration be presented to the user.

**Comment by WhyNotHugo** [comment]
Oh, I thought a bit more about https://github.com/flatpak/xdg-desktop-portal/blob/dbbe2180384154c642f837cc50a1ff0b1b5a6a34/src/portal-impl.c#L208-L218, and figured out why this works [by coincidence] for you but not for me.

This code is reached when non of the explicitly configured portals implement the required interface. In your case, you have no explicitly configured portals.

So, when an application requires [for example] screensharing, this loop will return the first portal that implements this interface:

- I'd guess in your case, a weston-compatible portal is found and returned. It exposes the screensharing API, and works fine.
- However, in my case, the gtk-portal is found first, and returned. This portal, internally, tries to use mutter's API for screensharing. I'm not running mutter, so it fails, and hence, screen sharing doesn't work.

The above loop has not pre-defined order. It also has not way of confirming that the returned implementation is compatible with the current desktop. The portals are iterated in arbitrary order, and things will only work properly if the first one is the one that's right for your desktop.

It seems that you're just lucky and the portals are looped in the right order for you. However, this is not by design.

**Comment by ilya-fedin** [comment]
I edited /usr/share/xdg-desktop-portal/portals/*.portal files in order to have right portals for each portal interface

**Comment by WhyNotHugo** [comment]
> I edited /usr/share/xdg-desktop-portal/portals/*.portal files in order to have right portals for each portal interface

Altering system-owned packages so that Telegram doesn't render a weird bar on top seems like a bit of a stretch. Sure, I can make (and maintain) customised variants of the packages that provide these files, but that's quite a bit of a stretch, plus I don't want to have to start building all these packages myself -- I rely on the ones my distribution provides.

I don't think all users of telegram can be expected to deal with such complexity.

---

Back on topic though, it seems that Qt has support for the xdg-decoration procotol added [here](https://github.com/qt/qtwayland/commit/845839b971f6af017be77dbe1ee1541453d12c23#diff-f7f5dc2f19eee9a4eabcdef8a71ee0b19792d9db6f19ea4de8241214bda76600R65). I wish I could contribute more than that, but my cpp is terrible and I can't really follow all of it.

Do you think that might be usable to avoid making assumptions based on `XDG_CURRENT_DESKTOP`?

Alternately, do you think it would make sense to trigger gnome-specific workarounds only if `$XDG_CURRENT_DESKTOP == gnome`?

**Comment by ilya-fedin** [comment]
> Altering system-owned packages so that Telegram doesn't render a weird bar on top seems like a bit of a stretch.

Altering system-owned packages so that there's no need to report wrong DE to applications. This will make a lot of apps work wrongly, not to mention the mess with file associations.

> Back on topic though, it seems that Qt has support for the xdg-decoration procotol added [here](https://github.com/qt/qtwayland/commit/845839b971f6af017be77dbe1ee1541453d12c23#diff-f7f5dc2f19eee9a4eabcdef8a71ee0b19792d9db6f19ea4de8241214bda76600R65).

Qt's xdg-decoration support has nothing to do with that. We need a way to determine if **compositor** supports xdg-decoration. The problem is that no one here know how to work with libwayland.

> Alternately, do you think it would make sense to trigger gnome-specific workarounds only if `$XDG_CURRENT_DESKTOP == gnome`?

Distributions prepend its name if they customize gnome session. For example, Ubuntu has `ubuntu:GNOME`. The current behavior is the most correct: if the variable contains a DE, we on it. The variable should be never overridden not matter if flatpak doesn't work without that or something like that, that's flatpak/GTK problem.

**Comment by WhyNotHugo** [comment]
> Altering system-owned packages so that there's no need to report wrong DE to applications.

Sure. I can use a patch/modified xdg-desktop-portal. I can also use a patched telegram-desktop.

However, I'd rather abstain from that. My intent in extending this discussion isn't to just fix the issue for myself on this single system. I'd like to find a solution that end up working for anyone having the same issues. I want to find a solution where it's possible to have flatpak **and** telegram both work on the same system without any extra patching or low-level tinkering.

> Distributions prepend its name if they customize gnome session. For example, Ubuntu has ubuntu:GNOME. The current behavior is the most correct: if the variable contains a DE, we on it.

Fair enough.

Once again, looks like a big part of the problem here is GTK applications depending on a gnome-specific deamon to even render text properly. :disappointed: 

---

How about just _always_ showing the "use system windows frame", even on GNOME? Why deny gnome users the option to remove that bar? There's really no reason why they should be able to.  
Removing the gnome-specific exception would also imply that setups like my own (e.g.: setups that want to run GTK flatpak too) would be able to uncheck that box.

Does that sound reasonable?

**Comment by ilya-fedin** [comment]
> Why deny gnome users the option to remove that bar?

If a GNOME user have used GNOME on X11 (or GNOME on Wayland and tdesktop with XWayland, what is the default for Qt on GNOME) with this option enabled and switched to Wayland, he would get Qt's dummy decoration that is impossible to theme. Even if the entire system is dark and Telegram itself uses night mode, the bar will be white. This is bad UX.

**Comment by WhyNotHugo** [comment]
Whoever has a problem with it being bad UX on gnome can turn it off. It's a gnome issue, after all.

It's also bad UX that it's not possible on other desktops to turn if off.

Especially when, again, no other application has any similar bar.

**Comment by ilya-fedin** [comment]
> It's also bad UX that it's not possible on other desktops to turn if off.

It's not possible only on GNOME. If you report that you're on GNOME, it's your problem ¯\_(ツ)_/¯

**Comment by ilya-fedin** [comment]
> Whoever has a problem with it being bad UX on gnome can turn it off. It's a gnome issue, after all.

Users don't know (and shouldn't) about these technical details. All that their see is that there was a good titlebar and after switching to Wayland they getting an ugly white titlebar. And then some of them report, report, report to GitHub.
