### ISSUE TITLE
Not suggesting emojis when using a colon (:)

### ISSUE THREAD

**Issue by AminTaheri23** [telegramdesktop/tdesktop#8335]
### Steps to reproduce
1. open a chat
2. type the colon symbol ( : )
3. type a word (e.g. smile) 

### Expected behaviour
it should open a pop-up menu with related emojis

### Actual behaviour
Nothing happens

### Configuration
**Operating system:** Windows 10 Home - Version 1909

**Version of Telegram Desktop:** 2.2

**Used theme**: default Tinted

**Comment by Aokromes** [comment]
works for me ™️ 
https://i.imgur.com/eD4CXzr.png

**Comment by AminTaheri23** [comment]
sry, my bad, I didn't check every setting before opening this issue, I accidentally must've disabled the corresponding option in the settings. sry again.
