### ISSUE TITLE
[Feature Request] Forbid voice messages for group or contact

### ISSUE THREAD

**Issue by steaze** [telegramdesktop/tdesktop#8337]
### Is your feature request related to a problem?
It will decide problem with stupid people and it will be unique function which absent, for example, in whatsapp.

### Describe the solution you'd like
For example, you would add additional item to context menu like "Disable notifications": "Disable voice messages".

**Comment by ilya-fedin** [comment]
![image](https://user-images.githubusercontent.com/17829319/88665960-f033fa00-d0ce-11ea-9ad0-4e534d3d127b.png)

**Comment by steaze** [comment]
I meant "voice messages", not notifications, sorry for my english.

**Comment by TrashAccount3424** [comment]
@steaze Telegram Desktop can't do that. Permissions are server side. However you can simply make a rule in your group that voice messages are not allowed. Put that in the description or in a pinned message so everyone can see. Then use a bot to enforce it. Bots can not block voice messages directly either but they can simply remove them if someone breaks the rule. There are many group management bots out there that can filter specific content. If you only want to automatically remove voice messages. You may wanna try AntiVoiceMessageBot It does just that and needs no settings. Just add it to your group and make it admin.
I hope that helps you solve your problem.

**Comment by Aokromes** [comment]
this must be done api-wide.

**Comment by Aokromes** [comment]
such feature belongs to https://bugs.telegram.org/
