### ISSUE TITLE
Top bar with close, minimize, window buttons appear on fullscreen

### ISSUE THREAD

**Issue by rafalbednarczuk** [telegramdesktop/tdesktop#8338]
### Steps to reproduce
1. Open telegram desktop

### Expected behaviour
There shouldn't be top bar on fullscreen.

### Actual behaviour
There is top bar on fullscreen -- Close, Minimize, Windows button on top of telegram window.
![](https://i.imgur.com/3DkwcLn.png)

### Configuration
**Operating system:**
OS: Ubuntu 18.04 bionic
Kernel: x86_64 Linux 5.4.0-42-generic
DE: Unity 7.5.0

**Version of Telegram Desktop:**
2.2

**Installation source (Linux Only)** - the official website / GitHub releases / flatpak / snap / distribution package:
Snap store from Ubuntu Software Center

**Used theme**:
Error occurs no mattar what's theme is used

**Comment by Aokromes** [comment]
another... cannot use search?

go settings, advanced, disable windows thing
