### ISSUE TITLE
Telegram pops into view on every notification on Cinnamon

### ISSUE THREAD

**Issue by sidnoway** [telegramdesktop/tdesktop#8339]
### Steps to reproduce
1. Open Telegram
2. Wait for a notification
3. Telegram pops open

### Expected behaviour
Telegram should stay in the background

### Actual behaviour
Telegram pops into view

### Configuration
**Operating system:** Linux Mint 20

**Version of Telegram Desktop:** 2.2 Beta

**Installation source (Linux Only)** - Official Site

**Used theme**: Default Dark Theme

**Comment by ilya-fedin** [comment]
https://github.com/telegramdesktop/tdesktop/issues/7885#issuecomment-628268069

**Comment by sidnoway** [comment]
I didn't see that. My bad.
