### ISSUE TITLE
Interface Improvement suggestion - Change location of [about] menu link 

### ISSUE THREAD

**Issue by chaosdrop** [telegramdesktop/tdesktop#834]
When the window is re-sized very small the only place you can grab the window to move the window around is a tiny area between the "about" link and the Minimize link. 

The About link could easily be moved into settings since it provides no useful common features. (Other programs it's your entry point to updates in this case it's not.) However it's removal would give a much needed boost in grab space.

**Comment by f242** [comment]
+1

**Comment by chaosdrop** [comment]
Can we get some input or acknowledgment from a dev on this one? 
The lack of title bar and the lack of drag space has been causing me all kinds of .... Lately and there's really no reason for it.
Either we need an option to enable a title bar, or we need to move the about menu into settings.
Either one should be quite simple and make life a lot easier for those of us using small screens at low resolutions, and multi-task.

Please & Thank you

**Comment by Aokromes** [comment]
What resolution you use? because for me not even the smaller sized windows makes me unable to see about (maybe it can be changed to ?)
