### ISSUE TITLE
[Feature Request] Option to send one`s screenshot (part of screen) to chat/channel

### ISSUE THREAD

**Issue by necros2k7** [telegramdesktop/tdesktop#8341]
### Is your feature request related to a problem?
Usability actually

### Describe the solution you'd like
Built-in win snippingtool-like option

### Describe alternatives you've considered
Maybe button to call snippingtool.exe on win version?

**Comment by sepehr-brj** [comment]
I think it's better to create a shortcut key for SnippingTool.exe

**Comment by necros2k7** [comment]
too many click , you have to call snippingtool- save screen region to some folder- then add file to chat from that folder, screenshot from inside the app would be more comfortable

**Comment by Aokromes** [comment]
or use sharex to capture things intercepting impr pant and having more shortcuts and paste to telegram

**Comment by ilya-fedin** [comment]
> save screen region to some folder

save it to clipboard

**Comment by NXij** [comment]
This is definitely not something Telegram as a client should handle.

Just use win+shift+s on windows and ctrl+v
