### ISSUE TITLE
[Question] Disable multi account (Multiaccount)

### ISSUE THREAD

**Issue by svdaru** [telegramdesktop/tdesktop#8342]
Is there way to disable multi account feature at the client?

**Comment by john-preston** [comment]
@svdaru Why? You can simply not use it.

**Comment by svdaru** [comment]
> @svdaru Why? You can simply not use it.

I would like to restrict user (staff at corp) from multi logins.

**Comment by john-preston** [comment]
@svdaru No way to do that, sorry.

**Comment by svdaru** [comment]
It would be nice to be able to set some parameters from windows PC registry.
