### ISSUE TITLE
Client side window decorations can't be disabled properly

### ISSUE THREAD

**Issue by mzanetti** [telegramdesktop/tdesktop#8343]
Since the latest update, telegram uses client side window decorations. I find that *very* annoying and alienating the application to the desktop so obviously first thing I do is to go to the settings and disable that. However, in Ubuntu for instance, a maximized application does not paint a title bar as the top panel already holds that. Even with client side decorations disabled in Telegram, it will still paint a second title bar around the window which gives the impression of the application not being maximized while it actually is and causes to user to unmaximize it frequently while actually wanting to maximize it.

![grafik](https://user-images.githubusercontent.com/102573/88802742-c7cdfd80-d1ab-11ea-9dd2-8159058521ae.png)

Please fix the option to disable client side window decorations so that it integrates properly into the desktop environment again.

### Configuration
**Operating system:**
Ubuntu 20.04

**Version of Telegram Desktop:**
2.2

**Installation source (Linux Only)** - the official website / GitHub releases / flatpak / snap / distribution package:
Website

**Comment by ilya-fedin** [comment]
> Please fix the option to disable client side window decorations

The option just removes FramelessWindowHint from the window, there's nothing that can be done on tdesktop side to fix that. I can only suggest you to restart client after disabling client-side decorations.

**Comment by mzanetti** [comment]
ugh... yeah, a restart of the app actually does fix it... Can't believe I didn't restart it for so long... Sorry for the noise.

**Comment by Aokromes** [comment]
https://i.imgur.com/KdU3dLa.png cannot reproduce on fresh install.

**Comment by MetalDroid** [comment]
That doesn't seem like standard Ubuntu.

Are you using any gnome extension to hide the topbar?

**Comment by Aokromes** [comment]
> That doesn't seem like standard Ubuntu.
> 
> Are you using any gnome extension to hide the topbar?

it's fresh installed ubuntu 20.04 without any modification the only change i did is change screen resolution.

**Comment by ilya-fedin** [comment]
> it's fresh installed ubuntu 20.04 without any modification the only change i did is change screen resolution.

He meant reporter's Ubuntu installation, I guess

**Comment by mzanetti** [comment]
Right... seems the Unite extension is installed which I thought came with the default ubuntu. But as I said in an earlier comment, everything is fine after a rstart of the telegram app... So this can be closed IMO
