### ISSUE TITLE
Telegram window comes to focus whenever a message is received notification

### ISSUE THREAD

**Issue by TheChuckster** [telegramdesktop/tdesktop#8346]
This is not ideal behavior, if I am typing or browsing the web in another app, the Telegram window immediately comes to focus whenever a message is received even though it is in the background, causing my typing in another application (whether it's code I'm writing in vim or a search query in Firefox) to be jarringly / immediately diverted mid-sentence into the Telegram window's chat text box even though I do not intend to be typing there or even using Telegram in the first place.

**Comment by Aokromes** [comment]
duplicate, disable it somewhere on settings.
your DE is culprit of it..
