### ISSUE TITLE
No longer support for GTK app bar and window buttons

### ISSUE THREAD

**Issue by CraftCoderr** [telegramdesktop/tdesktop#8348]
### Steps to reproduce
1. Launch Telegram on Linux (for example, manjaro)

### Expected behaviour
App bar and window buttons (minimize, full screen, close) should be styled according to system gtk theme

### Actual behaviour
App bar and windows buttons not styled

### Configuration
**Operating system:**
DISTRIB_ID=ManjaroLinux
DISTRIB_RELEASE=20.0.3
DISTRIB_CODENAME=Lysia
DISTRIB_DESCRIPTION="Manjaro Linux"

Kernel: 5.7.9-1-MANJARO

**Version of Telegram Desktop:**
2.1.18 - beta

**Installation source (Linux Only)** - the official website / GitHub releases / flatpak / snap / distribution package:
Arch official repository

**Used theme**:
Default

**Comment by ilya-fedin** [comment]
> App bar and window buttons (minimize, full screen, close) should be styled according to system gtk theme

No, it shouldn't, Telegram is not a gtk app

**Comment by CraftCoderr** [comment]
Why it was working until recent update?

**Comment by ilya-fedin** [comment]
> Why it was working until recent update?

Why was working? It is working now. Now you see the right titlebar.

**Comment by CraftCoderr** [comment]
I can confirm, that version 2.1.10-0.1 looks fine:


![screenshot_20200730_214549](https://user-images.githubusercontent.com/7105938/88961488-c8e75380-d2ad-11ea-81da-c3f98c7a5437.png)

**Comment by Aokromes** [comment]
no it doesn't, it doesn't follows telegram application standard.

**Comment by CraftCoderr** [comment]
It's a pity!

**Comment by CraftCoderr** [comment]
Solution found! 
Settings -> Advanced -> Use system window frame
