### ISSUE TITLE
There should be no copy option when the image hasn't downloaded

### ISSUE THREAD

**Issue by sepehr-brj** [telegramdesktop/tdesktop#8349]
There shouldn't be copy image option in the right click menu when the image has not been downloaded.
When I select copy image, the image doesn't copy to the clipboard.

![Capture](https://user-images.githubusercontent.com/55192376/88913108-9588d280-d275-11ea-9949-cfcda66b7c86.JPG)
![Capture2](https://user-images.githubusercontent.com/55192376/88913117-9883c300-d275-11ea-9aa1-8016d2f6b3e7.JPG)

**Version of Telegram Desktop:**
2.2

**Comment by ilya-fedin** [comment]
And "Save image As..." too :thinking:

**Comment by sepehr-brj** [comment]
The problem has not been solved yet...
