### ISSUE TITLE
Feature - `Disable media autodownload' option

### ISSUE THREAD

**Issue by sovietspaceship** [telegramdesktop/tdesktop#835]
I'm with a limited data plan with my laptop and when users in my group send a large amount of pictures I have to delete them all during download or my internet connection literally dies. Anyone that know this may put down my internet connection by sending huge amount of pictures to waste my bandwidth, and a couple of times my connection went down. Needless to say, I can't use Telegram Desktop anymore, nor my internet connection in general. The Android client has already that feature, but you cannot assume that desktops have unlimited data plans.

**Comment by ahmadubuntu** [comment]
I have same problem

**Comment by TotalKrill** [comment]
yeah, this should be added

**Comment by auchri** [comment]
#940

**Comment by Heeere-GittyGitty** [comment]
this is very important.. is there a priority queue or ETA?

**Comment by amiripars** [comment]
Hello
Please consider adding an option to Telegram Desktop in order to make it possible to prevent pictures from being loaded automatically. Though this feature is available on mobile, lack of it can be felt on Desktop version and we'd really appreciate it if you could add this option to Desktop version as well. Thank

**Comment by siamakgoudarzi** [comment]
I need it too +1:

**Comment by telegramdesktop** [comment]
@siamakgoudarzi It is available in settings.

**Comment by gusdudu** [comment]
Yes PLEASE, i need MANUAL DOWNLOAD content.

**Comment by MohammadHeydari** [comment]
In where ? could you mentioned it directly ?

**Comment by averwind** [comment]
@telegramdesktop where exactly is it in the settings menu on browser version? Or is it not available for browser version

**Comment by yusef-sheypoor** [comment]
yup, I have the similar requirement in mac Desktop, this is optional in windows desktop and andorid which user can turn off auto download images video etc but in mac desktop images always load and waste my bandwidth.

**Comment by seyedrezafar** [comment]
I have similar problem @yusef-sheypoor , do you find any solution ? we should wait until official decide to add this feature to mac desktop :(

**Comment by tuytoosh** [comment]
That feature should be added, in our country internet traffic price is too expensive and probably most people need to block unnecessary downloads...

**Comment by john-preston** [comment]
@tuytoosh There is a setting for that.

**Comment by tuytoosh** [comment]
@john-preston what is your solution?

**Comment by john-preston** [comment]
@tuytoosh Main Menu -> Settings -> Automatic media download settings. (in Telegram Desktop).

**Comment by tuytoosh** [comment]
@john-preston This option is available on windows and android version, but it removed in new version of telegram on mac os.

**Comment by john-preston** [comment]
@tuytoosh It is available on Telegram Desktop on macOS, you can download it from https://desktop.telegram.org

**Comment by tuytoosh** [comment]
@john-preston Can you show me, where are that option?

![photo_2017-12-29_13-12-21](https://user-images.githubusercontent.com/8298095/34434258-131d4d12-ec9a-11e7-9841-e251789e8846.jpg)

**Comment by john-preston** [comment]
@tuytoosh This is not Telegram Desktop. You can download Telegram Desktop from https://desktop.telegram.org

**Comment by tuytoosh** [comment]
@john-preston 
Ok, thanks for your attention, I downloaded this version from telegram.org host in https://macos.telegram.org/ subdomain, what is this?

**Comment by john-preston** [comment]
@tuytoosh https://macos.telegram.org is another version for macOS, see https://telegram.org/faq#q-why-do-you-have-two-apps-in-the-mac-app-store
