### ISSUE TITLE
Disable Voice Messages in groups

### ISSUE THREAD

**Issue by ePfirsich** [telegramdesktop/tdesktop#8350]
### Is your feature request related to a problem?
no

### Describe the solution you'd like
It would be great, when you can add a new option to groups, where I can deactivate only voice messages.

**Comment by ilya-fedin** [comment]
Why didn't you look even into first page of issue?..

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/8337
