### ISSUE TITLE
Unable to view the media file

### ISSUE THREAD

**Issue by J-Arun-Mani** [telegramdesktop/tdesktop#8352]
### Steps to reproduce
1. Open Telegram Desktop and go to https://t.me/programmer_humor/25418
2. The media posted is not downloadable.

### Expected behaviour
The media should be downloadable like any other file.

### Actual behaviour
The media file has irresponsive download icon on a black background. There is no thumbnail or preview.

### Configuration
**Operating system:**
Debian 10
**Version of Telegram Desktop:**
2.2
**Installation source (Linux Only)** - the official website / GitHub releases / flatpak / snap / distribution package:
Flatpak
**Used theme**:
Telegram's built-in Night theme.

**Comment by ilya-fedin** [comment]
I downloaded a 1x1 image

**Comment by J-Arun-Mani** [comment]
> I downloaded a 1x1 image
For me Save Image As is also not working for that media.

**Comment by ilya-fedin** [comment]
It works for me. I guess this media is just broken.

**Comment by J-Arun-Mani** [comment]
I checked with some other desktop users (Telegram 2.2, Linux), they also faced the issue.

**Comment by ilya-fedin** [comment]
> they are also facing the issue

How this can be an issue if the file is broken? :thinking:

**Comment by J-Arun-Mani** [comment]
> How this can be an issue if the file is broken?
Oh, then fine. Thanks for the info.
I hope this ProgrammerHumor meme issue ends with a post in r/ProgrammerHumor :joy:
