### ISSUE TITLE
[Bug] Iranian users are asking me why I have restricted them

### ISSUE THREAD

**Issue by ArmeF97** [telegramdesktop/tdesktop#8353]
![immagine](https://user-images.githubusercontent.com/6240983/88975260-2d101480-d2ba-11ea-8cf1-9f94f68d8ad6.png)

As you can read at the bottom "Group admins have restricted you from messaging"
That sentence is false, it's telegram that restricted iranian users, and it's a bug that the blame is on us admins

To fix the bug: change the string

### Configuration
**Operating system:** win 10

**Version of Telegram Desktop:** 2.2

**Comment by Aokromes** [comment]
it doesn't belongs here instead in app support or twiteer.

**Comment by ArmeF97** [comment]
@Aokromes  why not? It's telegram desktop that it's showing the wrong message, so it has to be fixed. Admins are not the ones who are restricting that user

**Comment by Aokromes** [comment]
it's cloud translation and platform wide.

**Comment by ArmeF97** [comment]
And how to report a bug to the cloud translation platform?

**Comment by Aokromes** [comment]
i already said it, twiteer or in app ask a question.

**Comment by ArmeF97** [comment]
Both of them do not reply when I ask something
