### ISSUE TITLE
[Feature Request] Notify user upload status 

### ISSUE THREAD

**Issue by HamidRezaAshkiyan** [telegramdesktop/tdesktop#8354]
Sometimes I upload multiple file (images) with telegram and I should constantly check how much left. 

It is a good idea to have some kind of notify percentage left and completed alarm. both for me and my friend.

**Comment by HamidRezaAshkiyan** [comment]
No I didnt lost my interest and i still need this feature! Someone in charge please check here.

**Comment by ilya-fedin** [comment]
#6145
