### ISSUE TITLE
[Question] When is data export coming out of Beta?

### ISSUE THREAD

**Issue by Otto-AA** [telegramdesktop/tdesktop#8356]
Currently data export is possible on Telegram Desktop v2.2 via Settings -> Advanced -> Export Telegram Data

However, this feature is still in the Beta, as pointed out by the created export:

> You are using the beta version of the data exporting feature. Unfortunately, this version does not support displaying the data from this section in a more human-friendly way. This will be supported in the next updates of Telegram Desktop.

> We may collect data such as your IP address, history of username and phone number changes to prevent spam, abuse, and other violations of our Terms of Service. If collected, this data can be kept for 12 months maximum.\n\nUnfortunately, the data presented below this notice may not be complete. The full set will become available when you export data using one of the next versions of Telegram Desktop, within a month. We apologize for the delay.

Considering that this feature was implemented two years ago (#126 ), I doubt that the "within a month" description is still accurate. Taking into account that "the data presented [...] may not be complete" it is questionable if the current version is even GDPR compliant.

**Comment by Otto-AA** [comment]
GDPR data export is still in Beta, so this shouldn't be closed due to inactivity

**Comment by Otto-AA** [comment]
bip bop

**Comment by john-preston** [comment]
Well, what's wrong with being beta? Gmail was beta for years.

**Comment by Otto-AA** [comment]
What's wrong is that the GDPR is enforced since about 4 years, but from my point of view Telegram still doesn't follow it with this beta implementation. As stated in [GDPR Art. 15 / 3](https://gdpr-info.eu/art-15-gdpr/):

> The controller shall provide a copy of the personal data undergoing processing.

However the GDPR bot only partially covers the processed personal data. Some of it (e.g. stored IP addresses; see my initial post) are explicitly not included in the export.

Apart from the legal requirements, I would also personally like to see this feature. And the "within a month" statement is kinda ridiculous to be still here (at least some months ago, I didn't check now).

**Comment by Otto-AA** [comment]
bop bip once again

**Comment by Otto-AA** [comment]
bip bop ignoring the bot

**Comment by Croydon** [comment]
Hi! This is my generic reply for every issue which is still relevant and is on the edge of getting closed by a stale bot.

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/8356#issuecomment-824556885

**Comment by ilya-fedin** [comment]
This issue tracker is no more a place for questions. Questions should now be asked in https://t.me/TelegramDesktopTalk.

**Comment by ilya-fedin** [comment]
There's a bulk change to all the questions that were recently un-staled as this is no more a place for questions due to the lack of interest to answer to them in generally. The group is way better for this. Now you can only report bugs and request for features what is actionable.

**Comment by Otto-AA** [comment]
@ilya-fedin Imo this issue is not a question that makes sense on the telegram chat, but rather is a bug report / enhancement report. While the framing makes it a question ("when is this issue going to be fixed?" rather than "this is an issue") you could do the same with any issue. From my point of view it is better suited here than in the telegram chat, where it will be forgotten after one day. Feel free to adjust the label, as I can't do that.

At least the "within a month" description is wrong, arguably missing legal compliance (to 5 year old laws) is also a bug.

**Comment by ilya-fedin** [comment]
@Otto-AA if this is not a question then why you created it with question type? Well, you can open a new one with the right type.

**Comment by Otto-AA** [comment]
@ilya-fedin Because back the description said it is going to come out of beta, so I expected that there are plans to implement the rest and wanted to know when this is the case. But apparently there are no plans for it, so it changed to a missing feature / bug report. Should I open a new one, or can you reopen this one?

**Comment by ilya-fedin** [comment]
Yes, please open a new one

**Comment by ilya-fedin** [comment]
Note that this issue tracker is community-maintained by the tdesktop project and is likely unofficial to Telegram as a company. The only official places where you can report bugs are in-app support and bugs.telegram.org.

**Comment by Croydon** [comment]
> @ilya-fedin Imo this issue is not a question that makes sense on the telegram chat, but rather is a bug report / enhancement report. While the framing makes it a question ("when is this issue going to be fixed?" rather than "this is an issue") you could do the same with any issue. From my point of view it is better suited here than in the telegram chat, where it will be forgotten after one day. Feel free to adjust the label, as I can't do that.


I fully agree. I don't think this issue should have been closed. But alright, we have now the new one #26270.



> Note that this issue tracker is community-maintained by the tdesktop project and is likely unofficial to Telegram as a company. The only official places where you can report bugs are in-app support and https://bugs.telegram.org.

What does that mean? Is the entire GitHub repository and organization unofficial?

**Comment by ilya-fedin** [comment]
> What does that mean? Is the entire GitHub repository and organization unofficial?

Well, the repository as a place where you can get the code is likely official. The issue tracker here is not. That is, no personal is looking here, only the developer who owns the repository. The issues are managed by folks who is not hired by Telegram like @Aokromes or me.
