### ISSUE TITLE
Telergram.exe - Bad Image

### ISSUE THREAD

**Issue by Kaktus1911** [telegramdesktop/tdesktop#8358]
### Steps to reproduce
1. Start Telegram
2. Windows Error:

Telegram.exe - Bad Image. C:\Windows\System32\amdhdl32.dll is either not designed to run on Windows or it contains an error. Try installing the program again using the original installation media or contact your system administrator or the software vendor for support. Error status 0xc000012f.

3. Click OK - Program runs fine until next start of the exe (reboot or user login)

### Actual behaviour

I am getting a Telegram.exe - Bad Image error since the last update....

### Configuration
**Operating system:**

Win 10 1909 64 bit

**Version of Telegram Desktop:**

2.2

**Installation source (Linux Only)** - the official website / GitHub releases / flatpak / snap / distribution package:

**Used theme**:

Standard

<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by john-preston** [comment]
@Kaktus1911 Hmm.. I have no idea what that .dll is :( Is it possible that this .dll is indeed broken / corrupt? What if you just rename it to math? 🙈

**Comment by Aokromes** [comment]
from what i read it can be bugged gfx drivers.

**Comment by Kaktus1911** [comment]
ok will try to renew them - thx

**Comment by Kaktus1911** [comment]
Didn't help :( - i guess it is time for a repairinstall...

**Comment by Kaktus1911** [comment]
Ok so i found the solution:

Tried to reinstall all versions of Visual C++ and new NVIDIAGraphics driver - no change

An Old AMD graphicsdriver caused the problem...- hence the "amdhdl32.dll" error message!
Last AMD Card i had installed in this system dates back more than 5 years - so why now this trouble ;)
Used DDU do erase all AMD leftovers - now it works like a charme :)
Thx for you imput guys
