### ISSUE TITLE
Display faded out in full screen mode when watching long video

### ISSUE THREAD

**Issue by paul23093** [telegramdesktop/tdesktop#8359]
### Steps to reproduce
1. Click on long video file
2. Switch to full screen mode
3. Enjoy you viewing

### Expected behaviour
Tell us what should happen
Display should stay active for all the video file
### Actual behaviour
Tell us what happens instead
Display faded out according to os settings, like after 15 mins
### Configuration
**Operating system:**
Windows 10
**Version of Telegram Desktop:**
2.2
**Installation source (Linux Only)** - the official website / GitHub releases / flatpak / snap / distribution package:

**Used theme**:
Classic
<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by ilya-fedin** [comment]
#7790

**Comment by john-preston** [comment]
@paul23093 I wonder how can I do that..

**Comment by paul23093** [comment]
I'm not sure, but seems qt dbus may help to do that.

https://stackoverflow.com/questions/31498114/how-to-programmatically-prevent-linux-computer-from-sleeping-or-turning-on-scree

**Comment by ilya-fedin** [comment]
> I'm not sure, but seems qt dbus may help to do that.

Windows doesn't have dbus
