### ISSUE TITLE
Gnome noticifications

### ISSUE THREAD

**Issue by saoudsalah** [telegramdesktop/tdesktop#836]
I would like to ask you to integrate the telegram notifications as part of gnome default notifications system. I just attached two images to show you what I'm talking about. It would be something like this : 

![screenshot from 2015-06-17 22-47-33](https://cloud.githubusercontent.com/assets/5074490/8219670/8f495ee8-1543-11e5-9ebd-c17ef55da64b.png)
![screenshot from 2015-06-17 22-49-34](https://cloud.githubusercontent.com/assets/5074490/8219671/8f523b58-1543-11e5-8d48-c318729b9ac4.png)

That would make it really awesome,

**Comment by hobarrera** [comment]
Actually, this is not gnome-specific, and it's the [de facto] standard notification daemon spec for Xorg. Implementing this would greatly improve desktop integration on all Xorg-based distributions. The behavirous is currently quite alien on most desktops, and notifications on the lower-right corner are rather awkward too.

**Comment by lucafavario** [comment]
Xorg notification would be a great feature! or at least be able to choose the position of notifcations.

**Comment by davcri** [comment]
Please search between issues before opening other ones: 
https://github.com/telegramdesktop/tdesktop/issues/91

**Comment by trsrm** [comment]
+1
