### ISSUE TITLE
Windows Sounds become silent when I make a call

### ISSUE THREAD

**Issue by BartMitTyp** [telegramdesktop/tdesktop#8360]
I'm running telegram client version 2.2 and always, when I'm receiving or making a call, all my other sounds turn silent. My windows settings on sound is not set to turn down volume but not to do anything.
Specifically, Minecraft turns silent.

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/8192

**Comment by BartMitTyp** [comment]
Thank you - I'm sorry, I only searched for "sound", not for "volume", my mistake

**Comment by PloufsPuppet** [comment]
Well got the same problem. I wrote the telegram support but i dont get an answer. Seems like telegram doesnt care.

**Comment by BartMitTyp** [comment]
> 
> 
> Well got the same problem. I wrote the telegram support but i dont get an answer. Seems like telegram doesnt care.
That's what Github is for. Problems are collectedas Issues and Aokromes linked #8192 which is this exact problem. The team can only do so much, so be patient and maybe follow the other issue to be updated when they start working on it.
