### ISSUE TITLE
[Feature Request] WebM support 

### ISSUE THREAD

**Issue by ooguz** [telegramdesktop/tdesktop#8363]
Hello everyone,

Telegram Desktop lacks of WebM support, and so many short video content on web uses WebM by default. When we tried to send WebM's to anybody, it is sent as an ordinary file. An in-app WebM player should be good.

Sincerely,

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/2842#issuecomment-272990768

**Comment by 800147** [comment]
> [#2842 (comment)](https://github.com/telegramdesktop/tdesktop/issues/2842#issuecomment-272990768)

Looks like all issues about WebM support are closed but feature is still absent. Is there any way to subscribe on updates on that (issue on backend side tracker) or maybe some answer that Telegram will never support WebM?
