### ISSUE TITLE
Client crashes after closing media player in a channel

### ISSUE THREAD

**Issue by hexa29** [telegramdesktop/tdesktop#8366]
### Steps to reproduce
1.  Open a channel
2.  Play a video
3.  Close the player

### Expected behaviour
Media player closes and the channel can be browsed again.

### Actual behaviour
The client crashes, terminal output shows:
` segmentation fault (core dumped)  telegram-desktop`
OR, less frequently:
`corrupted double-linked list`
`abort (core dumped) telegram-desktop`
The problem exists under both Wayland and X.

### Configuration
**Operating system:**
Arch Linux x86_64
**Version of Telegram Desktop:**
2.2.0-2
**Installation source (Linux Only)** - the official website / GitHub releases / flatpak / snap / distribution package:
telegram-desktop package from Arch community repository
**Used theme**:
stock tinted

**Comment by ilya-fedin** [comment]
> telegram-desktop package from Arch community repository

Check on the official binary

**Comment by hexa29** [comment]
Official binary works fine. There is a very brief freeze instead of the crash when closing the player but no errors are produced.

**Comment by ilya-fedin** [comment]
Seems to be a packaging issue, report to arch linux bugtracker

**Comment by ilya-fedin** [comment]
I think the bug is in ffmpeg 4.3 that your distro supplies. ffmpeg should be downgraded to 4.2 by repo maintainers to fix the issue.
