### ISSUE TITLE
[Bug] Telegram Desktop will Crash when Playing Video

### ISSUE THREAD

**Issue by whriedplanck** [telegramdesktop/tdesktop#8369]
### Steps to reproduce
1. Find a video in the chat;
2. Play it;
3. After about 30 seconds (sometimes 1 min and still fine), the program will crash and exit.

### Expected behaviour
The video should finish normally, and the program will not crash and exit.

### Actual behaviour
The program crashed and exited before the video was finished.

### Configuration
**Operating system:**
Arch Linux, KDE Plasma 5.19.4
**Version of Telegram Desktop:**
2.2
**Installation source (Linux Only)** - the official website / GitHub releases / flatpak / snap / distribution package:
Distribution package
**Used theme**:
Classic
<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)

[log.txt](https://github.com/telegramdesktop/tdesktop/files/5014291/log.txt)
</details>

**Comment by ilya-fedin** [comment]
> Distribution package

Check on the official binary

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/8366 ?

**Comment by ilya-fedin** [comment]
Well, since there are only complains from arch & manjaro users, the issue seems to be in a new buggy ffmpeg update in arch & manjaro repos, not a tdesktop issue. #8366 and this could be closed I guess.

**Comment by ilya-fedin** [comment]
And 6c52b4630cbc117d74c8eafedd488c99f8f8731e could be reverted to fix #7839

**Comment by whriedplanck** [comment]
@Aokromes @ilya-fedin Thanks for the answer!
