### ISSUE TITLE
[Bug] Send photo without compression, does not work.

### ISSUE THREAD

**Issue by theelectricsoul** [telegramdesktop/tdesktop#8371]
[2020.08.03_16.11.20.zip](https://github.com/telegramdesktop/tdesktop/files/5016471/2020.08.03_16.11.20.zip)

### Steps to reproduce
See video file in attachments

### Expected behaviour
Pictures should not be compressed, when I choose to.

### Actual behaviour
Pictures get compressed, no matter if I chose not to.

### Configuration
**Operating system:**
Win 10 

**Version of Telegram Desktop:**
2.2

**Installation source
https://telegram.org/dl/desktop/win

**Comment by ilya-fedin** [comment]
you changed the mode on popup, therefore it sent compressed.
Photo == compressed
Files == uncompressed

**Comment by 1265578519** [comment]
选择文件才不会压缩文件
