### ISSUE TITLE
Telegram  appears on message instead of simple notification. Linux Mint 20

### ISSUE THREAD

**Issue by anzhurov** [telegramdesktop/tdesktop#8372]
Steps to reproduce
1. Run Telegram
2. Go to another app to make telegram minimize
3. Get a message on telegram

Expected behaviour
Simple notification appears (in a corner)

Actual behaviour
Telegram window (the main window with dialogs list) appears

Configuration
Linux Mint 20 Ulyana
Telegram version 2.2
Instalation source: linux software manager

**Comment by Aokromes** [comment]
disable setting on advanced.

**Comment by anzhurov** [comment]
@Aokromes which one ?

**Comment by ilya-fedin** [comment]
> which one ?

you can find in any of a lot of duplicates

**Comment by anzhurov** [comment]
@ilya-fedin "telegram appears on message linux mint" gets nothing relatable

**Comment by ilya-fedin** [comment]
"telegram focus"

**Comment by anzhurov** [comment]
@ilya-fedin i found nothing besides this https://github.com/telegramdesktop/tdesktop/issues/8346

but there no appropriate setting name

**Comment by ilya-fedin** [comment]
![image](https://user-images.githubusercontent.com/17829319/89224107-6fda3100-d5c7-11ea-8de8-cf54f0193010.png)
