### ISSUE TITLE
Unreaded message count for archive channel supply to nonarchived channel

### ISSUE THREAD

**Issue by Kirill** [telegramdesktop/tdesktop#8374]
In tray I see all unreaded message (for archive and normal channel or private messages). Can you add option to see count of unreaded messages only for normal channels, private groups and personal chats not archived?
I put to archive non interesting (for this momment) channels and badge with unreaded messages take my mind and time from working process.

**Comment by ilya-fedin** [comment]
> Can you add option to see count of unreaded messages only for normal channels, private groups and personal chats not archived?

There are an option to don't include muted chats in the counter
