### ISSUE TITLE
Microphone does not work in Telegram

### ISSUE THREAD

**Issue by inyutin-maxim** [telegramdesktop/tdesktop#8375]
### Steps to reproduce
1. Call any contact
2. Sound does not transfer for contact

Also:
1. Open Settings | Advanced |  Call Settings | Microphone
2. Change all Input devices
3. All devices do not work

### Expected behaviour
Microphone correct work

### Actual behaviour
Microphone does not work

### Configuration
**Operating system:**
Windows 10 pro x64 version 2004 Build 19041.388
CPU: i5 9600K
RAM: 32Gb
**Version of Telegram Desktop:**
2.2
**Installation source (Linux Only)** - the official website / GitHub releases / flatpak / snap / distribution package:

**Used theme**:

<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by ilya-fedin** [comment]
#7688
