### ISSUE TITLE
Choose file dialog opens in background

### ISSUE THREAD

**Issue by RafaelLinux** [telegramdesktop/tdesktop#8376]
### Steps to reproduce
1. Select a message with any attached file (video, photo, audio)
2. Right click on attached file, "Save as"

### Expected behaviour
To show file dialog OVER Telegram window (as always was)

### Actual behaviour
The file dialog is put is put in background. User must look for dialog window to put in front Telegram window

### Configuration
OpenSUSE 15.2 x64
Telegram 2.2 desktop from the official website
No theme

**Comment by ilya-fedin** [comment]
#8382
Please test the binary posted in that issue

**Comment by RafaelLinux** [comment]
Well, the "Telegram_DESKTOP_APP_DISABLE_DBUS_INTEGRATION" binary works like always did, but not the simply "Telegram" file in same page.

**Comment by ilya-fedin** [comment]
> Well, the "Telegram_DESKTOP_APP_DISABLE_DBUS_INTEGRATION" binary works like always did, but not the simply "Telegram" file in same page.

Oh, then you have a different issue. Most likely you have xdg-desktop-portal-gtk, which is known to be opened in background. This is not a tdesktop issue.

**Comment by RafaelLinux** [comment]
I forgot to say I'm using KDE Plasma

**Comment by RafaelLinux** [comment]
Will this version "autoupdate" as the "normal" version?

**Comment by ilya-fedin** [comment]
no, it is a debug version

**Comment by RafaelLinux** [comment]
So, what's the fix for my issue? I even uninstalled xdg-desktop-portal-gtk, but that doesn't solve the issue. My OpenSUSE 15.2 is just recent installed, but with 15.1 version was happening too - as I wrote - some versions of Tdesktop ago (2 or 3 versions ago).

**Comment by ilya-fedin** [comment]
Well, we can't fix portals.

**Comment by RafaelLinux** [comment]
I'm not a developer, but can report a bug/issue to KDE if you can give me more info about what's "portals" and what info I'll need to supply.

Thank you

**Comment by ilya-fedin** [comment]
> I'm not a developer, but can report a bug/issue to KDE

As far as I see, this is already fixed in latest versions, but you're using a release distro, so that you have old versions with bugs

**Comment by RafaelLinux** [comment]
Well .... I'm using a release distro, but I'm using latest KDE repositories, that's why I didn't understand the issue. I wish in a month or two those repositories had the fixed versions of QT libraries. Meanwhile, I need to use the "DISABLE_DBUS_INTEGRATION" version to avoid the issue.

Thank you

**Comment by ilya-fedin** [comment]
> I need to use the "DISABLE_DBUS_INTEGRATION" version to avoid the issue.

It uses test API ID and test API HASH, i really don't recommend to use it for a long time (more than multiple hours), you may encounter into issues with your account or connecting to Telegram servers

**Comment by RafaelLinux** [comment]
:( 

Ok, I'll follow your recommendation and delete it from my desktop. 

Thank you very much ilya-fedin

**Comment by ilya-fedin** [comment]
Btw, you always can disable KDE dialog like with any other app:
`env -u XDG_CURRENT_DESKTOP -u DESKTOP_SESSION -u KDE_FULL_SESSION ./Telegram`

You also can point Telegram to a wrong dbus socket and get the same behavior like with DESKTOP_APP_DISABLE_DBUS_INTEGRATION build option:
`env DBUS_SESSION_BUS_ADDRESS=lalala ./Telegram`
