### ISSUE TITLE
[Feature Request] Let user select "File dialog"

### ISSUE THREAD

**Issue by RafaelLinux** [telegramdesktop/tdesktop#8377]
### Is your feature request related to a problem?
Actual file dialog (I presume Gnome based) doesn't let user to type folders names (to include hidden Linux folders, as configuration folders) or to access large paths copying and pasting the path text.

### Describe the solution you'd like
Some applications, like QMMP player for Linux/Windows, let user to select the "File dialog" window to avoid this trouble.

### Describe alternatives you've considered
To use the most versatile file dialog (I think is QT file dialog)

### Additional context
In fact, I just reported a bug #8376 that maybe is related to this feature request.

**Comment by ilya-fedin** [comment]
tdesktop 2.2 uses gtk file dialog only on gtk-based DEs or if QT_QPA_PLATFORMTHEME is set to gtk3 or gtk2.

**Comment by RafaelLinux** [comment]
I'm using Plasma (OpenSUSE 15.2) and as you wrote, "File dialog" window is QT based, so is correct, but no way to enable/disable to show hidden folders. I know that's possible, like "Kate" (QT text editor) let user do using "CTRL + H" (or clicking on the wheel upper right on "Open file" dialog window.

**Comment by ilya-fedin** [comment]
Check that you have both xdg-desktop-portal and xdg-desktop-portal-kde installed, but doesn't have xdg-desktop-portal-gtk (it may always get priority for some reason) installed

**Comment by RafaelLinux** [comment]
In my case, I have both installed. So, will the 
```
zypper se -si xdg-desktop

E  | Nombre                      | Tipo    | Versión            | Arquitectura | Repositorio
---+-----------------------------+---------+--------------------+--------------+-----------------------
i+ | xdg-desktop-portal          | paquete | 1.6.0-lp152.3.3    | x86_64       | Main Repository
i+ | xdg-desktop-portal-gtk      | paquete | 1.6.0-lp152.1.3    | x86_64       | Main Repository
i+ | xdg-desktop-portal-gtk-lang | paquete | 1.6.0-lp152.1.3    | noarch       | Main Repository
i+ | xdg-desktop-portal-kde      | paquete | 5.19.4-lp152.149.1 | x86_64       | (Paquetes del sistema)
i+ | xdg-desktop-portal-kde-lang | paquete | 5.19.4-lp152.149.1 | noarch       | (Paquetes del sistema)
i+ | xdg-desktop-portal-lang     | paquete | 1.6.0-lp152.3.3    | noarch       | Main Repository

```

**Comment by ilya-fedin** [comment]
> In my case, I have both installed.

That's why you getting gtk dialog instead of kde dialog. Remove gtk one and relogin.

**Comment by RafaelLinux** [comment]
Done. Now  it's the Plasma QT file dialog, but some option on calling
window file dialog is necessary to show the "Hide/Show" hidden
files/folders, as Kate and other QT based applications do (see screenshot).

[image: imagen.png]

**Comment by ilya-fedin** [comment]
> see screenshot

it is broken

**Comment by RafaelLinux** [comment]
My fault. I "overwrite" the previous one pasted screenshot and somthing went wrong with github editor. Now it's right:
![imagen](https://user-images.githubusercontent.com/13048959/89292262-5cc57080-d65c-11ea-9756-0ccd84ed5e89.png)

**Comment by ilya-fedin** [comment]
I have the option:
![image](https://user-images.githubusercontent.com/17829319/89292980-b4f47680-d64c-11ea-838e-768fe05d27db.png)

Probably you have too old xdg-desktop-portal-kde

**Comment by RafaelLinux** [comment]
This is a madness. As you can see previously (https://github.com/telegramdesktop/tdesktop/issues/8377#issuecomment-668547205) my version is xdg-desktop-portal-kde 5.19.4 and the screenshot was took in same OpenSUSE where I'm using Telegram. That's to say, Kate and TDesktop shows different file dialogs user available options in my same OpenSUSE 15.2 (I'm using Telegram_DESKTOP_APP_DISABLE_DBUS_INTEGRATION).

Please, any other suggestion?

**Comment by ilya-fedin** [comment]
>  That's to say, Kate and TDesktop shows different file dialogs user available options in my same OpenSUSE 15.2

Kate is installed via package manager and can use plasma integration libraries. tdesktop is a static binary, it can't use plasma integration libraries, since they linked to the system Qt and static binary has it's own Qt. So that the only option for tdesktop is to use portals, there are no alternative when tdesktop installed via static binary.

**Comment by ilya-fedin** [comment]
Just checked on openSUSE Tumbleweed in a VM: no issues, the option for hidden files is here, dialog opens in foreground
![image](https://user-images.githubusercontent.com/17829319/89294717-6c8a8800-d64f-11ea-9707-1ce36d5433c3.png)

**Comment by RafaelLinux** [comment]
So I guess that, as you told, it will work with a version greater than 5.19.4. Anyway, with your info, I'll ask in KDE bugtracker. Thank you for all your support and QUICK answers.
