### ISSUE TITLE
App getting crashed if we try to attach files

### ISSUE THREAD

**Issue by bhanumarri** [telegramdesktop/tdesktop#8378]
Actually After getting latest Update for Telegram Desktop, i updated my telegram desktop on my Laptop with Debian Operating System. After this update when I am trying to attach a file in a chat using the symbol on left of the typepad, the telegram window is automatically getting closed. This is happening right now from the update. Tried Many times but the window suddenly getting closed.

### Steps to reproduce
1. Is that a bug on update 2.2?
2. I tried uninstalling the desktop application and installed again but of no use.
3. Is there any option to revert back to previous update?

### Expected behaviour
The Telegram window is automatically getting closed.

### Actual behaviour
A new Window opens for attaching files.

### Configuration
**Operating system:** Debian 10 Buster

**Version of Telegram Desktop:** 2.2

**Installation source (Linux Only)** - the official website 

**Used theme**:

<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by Aokromes** [comment]
plz use search before posting more duplicate bugs
https://github.com/telegramdesktop/tdesktop/issues/8336
