### ISSUE TITLE
Folders sidebar doesn't use colors from the Day theme

### ISSUE THREAD

**Issue by olehmisar** [telegramdesktop/tdesktop#8379]
### Steps to reproduce
1. Go to Settings -> Chat Settings
2. Select the "Day" theme
3. Select green color

### Expected behaviour
The folders sidebar should use green color for icons and text.

### Actual behaviour
The folders sidebar uses blue color for icons and text.
![image](https://user-images.githubusercontent.com/29802592/89329897-2574b500-d698-11ea-99a0-3a5e8d428a66.png)

### Configuration
**Operating system:** Windows 10

**Version of Telegram Desktop:** 2.2

**Used theme**: Day

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/7460
