### ISSUE TITLE
FEATURE: Webcamera and screenshot support

### ISSUE THREAD

**Issue by corb06** [telegramdesktop/tdesktop#838]
It would be nice if we could use our Webcams to capture pics in the Telegram PC client.

Also even cooler if we can capture a selected area for screenshot. Like if I want to send just a small portion of my desktop to the user on Telegram via screenshot. No need to go to paint and copy cut and paste and save and attach picture file.

**Comment by Aokromes** [comment]
#414

**Comment by Walkman100** [comment]
Screenshot? you mean what <kbd>Print Screen</kbd> then <kbd>Ctrl</kbd> + <kbd>V</kbd> does?

**Comment by Walkman100** [comment]
For selected area, use your OS's screen capture tool (`Snipping Tool` on Windows) and just copy the image, then paste it into Telegram's chat box. no need to save file.

**Comment by corb06** [comment]
Yeah I almost never want to send my entire screen to contacts, but a selected area is very useful. 
This capture area function is working very well on Trillian desktop client, so would be cool if Telegram got it too. 
I will try the Snipping Tool, never heard of that before.

**Comment by mirhl** [comment]
To be fair, you can select currently active window with ALT + Print Screen

**Comment by Aokromes** [comment]
With alt you can only capture specific window not specific areas of a window.

**Comment by Walkman100** [comment]
> With alt you can only capture specific window not specific areas of a window.

...
> To be fair, you can select currently active window with ALT + Print Screen

I can't believe I didn't know that. With multiple monitors, <kbd>Print Screen</kbd> takes a huge image which then has to be cropped if you don't want all your screens... thanks for telling us that.

**Comment by auchri** [comment]
Duplicate #781
