### ISSUE TITLE
Classic and Day themes use dark colors for the folders sidebar

### ISSUE THREAD

**Issue by olehmisar** [telegramdesktop/tdesktop#8380]
### Steps to reproduce
1. Go to Settings -> Chat Settings
2. Select either "Classic" or "Day" theme

### Expected behaviour
The folders sidebar should use light color(white?) similarly to other UI elements.

### Actual behaviour
The folders sidebar is dark.
![image](https://user-images.githubusercontent.com/29802592/89330544-19d5be00-d699-11ea-9a55-6c868fe37569.png)

### Configuration
**Operating system:** Windows 10

**Version of Telegram Desktop:** 2.2

**Used theme**: Classic or Day

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/7460
