### ISSUE TITLE
System-wide installer

### ISSUE THREAD

**Issue by twanvanbalen** [telegramdesktop/tdesktop#8382]
Hi,

This is not really a issue but more a request.

A customer wants to use Telegram on their Citrix environment, but because the installer is only installing at the userprofile we cannot deploy this in the image. Also we use ManageEngine Desktop Central to get the latest updates. So our question is if you can also build a system-wide installer ? 

Best Regards,

Twan

**Comment by ilya-fedin** [comment]
#5718
