### ISSUE TITLE
Crashed call on TDesktop blocks new calls on all other devices!

### ISSUE THREAD

**Issue by rsunde** [telegramdesktop/tdesktop#8384]
### Decription of BUG
An incoming call crashed or something on tdesktop on the home computer,
**_tdesktop was never closed or restarted for a long while_** 

no calls possible due to tdesktop on the home computer "blocking" all new incoming calls on all other devices...

Personally I never want to receive calls on desktop, _**this feature #3594 is related.**_

### Steps to reproduce
1. No idea
2. 
3. 

### Expected behaviour
Calls work!

### Actual behaviour
Calls didnt work

### Configuration
**Operating system:**
Windows 10 64bit

**Version of Telegram Desktop:**
v2.2

**Installation source (Linux Only)** - the official website / GitHub releases / flatpak / snap / distribution package:

**Used theme**:

<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by ilya-fedin** [comment]
> ### Steps to reproduce
> 
>     1. No idea

best issue ever :clap:

**Comment by ilya-fedin** [comment]
@rsunde does #8531 describe your bug?

**Comment by Aokromes** [comment]
more than 1 month without answer, if this bug is still valid open a new ticket.
read also #8531 before.
