### ISSUE TITLE
Volume of audio files vs video files has a great level difference (Linux)

### ISSUE THREAD

**Issue by RafaelLinux** [telegramdesktop/tdesktop#8385]
### Steps to reproduce
1. Play an audio file (with normal audio levels)
2. Reduce (inside Telegram) the audio to be near inaudible
3. Play a video file (with the audio track from the previous audio file)

### Expected behaviour
Audio output level should be perceived same with playing any of mentioned media files.

### Actual behaviour
Video audio track is always playing at much higher leven thant audio files.

### Configuration
OpenSUSE 15.2
Telegram 2.2 desktop

**Installation source (Linux Only)** 
the official website

**Comment by ilya-fedin** [comment]
Can you link example audio and video files with the same audio stream?

**Comment by RafaelLinux** [comment]
The video and audio volume sliders are independent, but even putting them at same level the "minimum" and "maximum" level are not the same (Linux), so when listening with earphones, switch from video to audio files is sometimes a headache, so user must change volume each time he play one or other media.

https://fromsmash.com/media-files-volume

**Comment by ilya-fedin** [comment]
> https://fromsmash.com/media-files-volume

This site tries to get my IP via some strange third-party site and leaves me with blank page after uBlock blocks that attempt:
![image](https://user-images.githubusercontent.com/17829319/89477111-efa8fc80-d77b-11ea-9cdd-219567840574.png)

> so user must change volume each time he play one or other media.

I need a way to reproduce, please send test audios and videos

**Comment by RafaelLinux** [comment]
In fact, I needed to disable uBlock to use Smash, so that's why you can't download the links if do not disable uBlock too.

Anyway, I tried for myself and think that my issue is related to some kind of videos (I suspect that with some audio specific codec) cause I can't reproduce with the media files I sent you.

I'll close this issue, I'm sorry for the incoveniences

**Comment by ilya-fedin** [comment]
> In fact, I needed to disable uBlock to use Smash, so that's why you can't download the links if do not disable uBlock too.

Sorry, no way that i disable uBlock on that site after a such attempt of violating my privacy

> Anyway, I tried for myself and think that my issue is related to some kind of videos (I suspect that with some audio specific codec) cause I can't reproduce with the media files I sent you.

Yeah, that's what I wanted to check. In most cases transcoding changes the audio level.

**Comment by RafaelLinux** [comment]
THANK YOU VERY MUCH
