### ISSUE TITLE
[Feature Request] Possibility to create more than 10 folders and make subfolders

### ISSUE THREAD

**Issue by necros2k7** [telegramdesktop/tdesktop#8386]
### Is your feature request related to a problem?
Can`t create more personal categories

Like I have main folder say "Work" - conveniet subfolders should include "Suppliers" , "Contractors", "Electricity", "Gardeners" as an example

**Comment by ilya-fedin** [comment]
#7006

**Comment by necros2k7** [comment]
How it`s related to compilation issue above?

**Comment by ilya-fedin** [comment]
Oops, fixed the number
