### ISSUE TITLE
[Feature Request] Option to disable wide monospace bubbles

### ISSUE THREAD

**Issue by Neurotoxin001** [telegramdesktop/tdesktop#8389]
### Is your feature request related to a problem?
https://github.com/telegramdesktop/tdesktop/commit/07e3671ca8e61e2d9a972c19c520d16077b89aa0
Because of this text is too wide. 

### Describe the solution you'd like
Make option to disable wide monospace bubbles

### Additional context
Just look at this nightmare and compare it with simple text:
![image](https://user-images.githubusercontent.com/39812401/89523094-0175b880-d7eb-11ea-9853-30acba9df9e9.png)

**Comment by john-preston** [comment]
@Neurotoxin001 This is not the intended use case for the monospace font :(

**Comment by Neurotoxin001** [comment]
> @Neurotoxin001 This is not the intended use case for the monospace font :(

I know, but many channels (at least russians) use this very often.

**Comment by Neurotoxin001** [comment]
I still need it

**Comment by Neurotoxin001** [comment]
Just look at this channel
https://t.me/lenta_ru_news

It's awful without that option.

**Comment by john-preston** [comment]
@Neurotoxin001 Somebody uses the monospace text tags in a not supposed way..
