### ISSUE TITLE
[Feature Request] Add Russian comment in .desktop file

### ISSUE THREAD

**Issue by RDL-28** [telegramdesktop/tdesktop#8393]
Hi.
Would you to add a Russian comment in the .desktop file?

`Comment[ru]=Официальная настольная версия приложения для обмена сообщениями Telegram`

**Comment by john-preston** [comment]
@RDL-28 What for? And why only russian, what about other supported languages?

**Comment by RDL-28** [comment]
**@john-preston**
So that the shortcut would be displayed in Russian in Linux with Russian locale
If desired, people can ask to add a comment in their language

**Comment by RDL-28** [comment]
I'm sorry, will this be implemented?

**Comment by ilya-fedin** [comment]
> I'm sorry, will this be implemented?

There was a PR and it was rejected.
https://github.com/telegramdesktop/tdesktop/pull/8263
