### ISSUE TITLE
Keyboard shortcut for marking chats as read

### ISSUE THREAD

**Issue by alvarotroya** [telegramdesktop/tdesktop#8394]
Could just someone please clarify the following quick question? 

Is there a keyboard shortcut for marking a chat as read?

Thank you!

**Comment by kaafivikrant** [comment]
COMMAND | SHORTCUT
Move to next chat | Ctrl + Tab
Move to next chat | Ctrl + PageDown
Move to next chat | Alt + Arrow Down
Move to previous chat | Ctrl + Shift + Tab
Move to previous chat | Ctrl + PageUp
Move to previous chat | Alt + Arrow Up
Search selected chat | Ctrl + F
Exit selected chat and search Telegram | Esc
Exit display of current chat/channel | Alt + Arrow Up
Delete currently selected message | Delete
Quit Telegram | Ctrl + Q
Lock Telegram (if Local Password is set) | Ctrl + L
Iconify (Minimize) Telegram | Ctrl + M
Iconify (Minimize) Telegram to System Tray | Ctrl + W
Edit Previous Message | Arrow Up

I hope this helps

**Comment by 23rd** [comment]
In the latest (2.4) version you have ability to mark the selected (by arrow keys) chat as read with `Ctrl + R` shortcut.

**Comment by MasterGroosha** [comment]
Can this issue be closed now?
