### ISSUE TITLE
All settings lost when downgrade version and upgrade again

### ISSUE THREAD

**Issue by oxalica** [telegramdesktop/tdesktop#8396]
### Steps to reproduce
1. Run v2.1.22, login, and modify some settings.
2. Upgrade to v2.2.0. It works well and settings are preserved.
3. Exit v2.2.0 and run v2.1.22 (In case of accidentally running the old version). All settings are lost and it asks for a login.
4. Do nothing and exit v2.1.22. Run v2.2.0 again, settings are still lost and it asks for a login.

### Expected behaviour
The old version may or may not work, but should not break the new database.
When we run the new version again, settings should be preserved.

### Actual behaviour
Seems the new-version database is corrupted by the old-version tdesktop. After running the new version and login again, all settings are lost and reset to the default.

### Configuration
**Operating system:** NixOS 20.09 (nixpkgs-unstable channel)

**Version of Telegram Desktop:** v2.1.22 and v2.2.0 (Not checked for older versions)

**Installation source (Linux Only)** - the official website / GitHub releases / flatpak / snap / distribution package: Build from source from GitHub (packaged by nixpkgs, see [here](https://github.com/oxalica/nixpkgs/blob/f9fe53f549cf67ff7249b36fd28d33b504296f63/pkgs/applications/networking/instant-messengers/telegram/tdesktop/default.nix)).

**Used theme**: /

<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by Aokromes** [comment]
i don't think downgrading scenario is supported.

**Comment by ilya-fedin** [comment]
https://github.com/telegramdesktop/tdesktop/issues/2854#issuecomment-272680635

**Comment by oxalica** [comment]
@Aokromes No need to support downgrading. I'm just asking for a check for "database version", which can be simply a text file. We can reject unsupported version, warn user (maybe a choice for immediately exit), instead of silently break data.
