### ISSUE TITLE
[Feature Request] Drag and drop the channel title to the folder and add the option to remove it.

### ISSUE THREAD

**Issue by qg0** [telegramdesktop/tdesktop#8399]
**Drag and drop the title channel to the category folder.**

![Screenshot_20200808_061522-1](https://user-images.githubusercontent.com/919099/89696024-47906080-d940-11ea-8766-80ebafe75cc9.png)

**Add the option "Delete from the folder".**

![Screenshot_20200808_062919](https://user-images.githubusercontent.com/919099/89696156-cb4a4d00-d940-11ea-9b63-646f6af8a578.png)

**Comment by ilya-fedin** [comment]
#7463
