### ISSUE TITLE
Images in inline mode are broken until loaded on phone if photo_width and photo_height are not set

### ISSUE THREAD

**Issue by OctoNezd** [telegramdesktop/tdesktop#8400]
### Steps to reproduce
1. Run the bot script (https://gist.github.com/ee1b55a41b8caed1d26e45027a9ca75f), set the TGTOKEN env variable to your bot token
2. Try using the bot from inline, type any query

### Expected behaviour
Images should appear

### Actual behaviour
Telegram desktop shows "No results" until the bot is used from phone/other client (https://www.youtube.com/watch?v=ME3ZQioMTqM) and chat re-opened

### Configuration
**Operating system:** Windows 10 1909

**Version of Telegram Desktop:** 2.2

**Used theme:** Classic

**Comment by OctoNezd** [comment]
This issue also doesn't happen if there is only one image

**Comment by ilya-fedin** [comment]
#4580

**Comment by OctoNezd** [comment]
Closing issue as duplicate, I guess
