### ISSUE TITLE
[Feature Request] Disable Audio messages

### ISSUE THREAD

**Issue by Spider84** [telegramdesktop/tdesktop#8404]
Not all people like audio messages. And I one of them. Or some people send only audio messages - I hate them :)

I think Telegram can add option in setting to disable Audio messages accepting. For example I has disabled Audio messages and when some one open chat with me - he haven't audio message button in interface. Or button is disabled.

**Comment by ilya-fedin** [comment]
#8337

**Comment by Spider84** [comment]
This all about groups. But I ask about Profile settings. For disabling voice messages in private chats.

**Comment by Aokromes** [comment]
> This all about groups. But I ask about Profile settings. For disabling voice messages in private chats.

that's groups OR contacts.
