### ISSUE TITLE
[Question] Previous Admin left and current admin has no permission to add new admins

### ISSUE THREAD

**Issue by ModMaamari** [telegramdesktop/tdesktop#8405]
Previous Admin left and current admin has no permission to add new admins.
I have an irritating issue; the issue is described in the next points:
1- My brother created our family group here in telegram
2- He designated me as an admin (but not a super admin, that is why I cannot designate other users as admins)
3- He deleted his telegram account
4- Now I want to give other users admin permissions but I do not have the ability to do so

The question is: How can I make other users admins?

**Comment by Aokromes** [comment]
you cannot.

**Comment by ModMaamari** [comment]
Can I make another group and import messages from an old group to the new one ?

**Comment by RememberTheAir** [comment]
@ModMaamari nope. You can only start a new group

**Comment by ModMaamari** [comment]
Does this mean that there is no possible solution for my issue?
Can't you think of any workaround that would help me to save my group?

**Comment by RememberTheAir** [comment]
You can always export the chat history from Telegram Desktop (three dots menu -> Export chat history), but there's no way to "migrate" the chat history to a new group. Anyway, it's not going anywhere, so the current members will still be able to access the chat content. You just have to create a new chat

**Comment by ModMaamari** [comment]
> You can always export the chat history from Telegram Desktop (three dots menu -> Export chat history), but there's no way to "migrate" the chat history to a new group. Anyway, it's not going anywhere, so the current members will still be able to access the chat content. You just have to create a new chat. What's your concern?

My concern is when I delete my Telegram account there will be no admin to the group.

Another question : 
Why when an admin of a group leaves it, Telegram dosen't automatically give admin permissions to the first member added by the old admin.

**Comment by RememberTheAir** [comment]
> My concern is when I delete my Telegram account there will be no admin to the group.

So what's the issue with that? You can remove all the members before deleting your account. I mean, where's the problem? The member that are left being able to access the chat history? What are you afraid it will happen, without any admin? It's a family chat after all. You can create the new account and add your family to a new chat

> Why when an admin of a group leaves it, Telegram dosen't automatically give admin permissions to the first member added by the old admin.

Nobody knows. They still have to make up their mind on this, and for now it works like that
