### ISSUE TITLE
Resuming from standby makes it unable to use GIFs

### ISSUE THREAD

**Issue by MartinX3** [telegramdesktop/tdesktop#8406]
### Steps to reproduce
1. Use Telegram Desktop
2. Put the PC into standby over night
3. At the next day, wake it up / resume it from sleep and use telegram.

### Expected behaviour
The GIF should get send to my communication partner.

### Actual behaviour
The GIF loads and loads and loads and never arrive its destination.
A restart of the app which fixes this problem also removed my eternity loading messages.

### Configuration
**Operating system:** Arch with kernel 5.4 LTS

**Version of Telegram Desktop:** 2.3.2

**Installation source (Linux Only)** - the official website / GitHub releases / flatpak / snap / distribution package: Arch community repository

**Used theme**: Default Black

Maybe connected to https://github.com/telegramdesktop/tdesktop/issues/5181

**Comment by MartinX3** [comment]
sdfg

**Comment by MartinX3** [comment]
G

**Comment by Aokromes** [comment]
this bug is still valid?

**Comment by e2e0** [comment]
> this bug is still valid?

Yep, the bug is still valid (Env: Windows 10, Telegram v. 3.6.1)
