### ISSUE TITLE
Telegram desktop on linux uses custom window decorations

### ISSUE THREAD

**Issue by mareg** [telegramdesktop/tdesktop#8407]
### Steps to reproduce
1. Install latest telegram-desktop
2. Starts with grey title bar and red highlight colour

### Expected behaviour
Should use existing desktop decorations (gtk-window-decorator or emerald) like other applications

### Actual behaviour
Uses grey for title bar and red for highlight, different icons and has no title.

### Configuration
**Operating system:**

Fedora 32 Mate Desktop spin (64bit)

**Version of Telegram Desktop:**

$ rpm -qa | grep telegram
telegram-desktop-2.2.0-1.fc32.x86_64

**Installation source (Linux Only)** - the official website / GitHub releases / flatpak / snap / distribution package:

https://rpmfusion.org/

**Used theme**:

Compiz + emerald (for windows decorations)

![screenshot75](https://user-images.githubusercontent.com/533217/89779231-ce8f3580-db06-11ea-8469-297303a26cd1.png)

**Comment by tur1ngb0x** [comment]
Telegram Settings > Advanced > System Integration > **Use System Window Frame** > **Enable**

**Comment by Aokromes** [comment]
not a bug.
