### ISSUE TITLE
Incorrect direction for RTL texts + new emojis

### ISSUE THREAD

**Issue by alisentinel** [telegramdesktop/tdesktop#8410]
### Steps to reproduce
1. Type some new emojis
2. Type in a right to left directed language

### Expected behaviour
The text should starts from right and ends in left

### Actual behaviour
The text starts from left and ends in right!

I took a screenshot to understand easier (This happens in bot buttons too)
![screenshot](https://user-images.githubusercontent.com/21295774/89803405-05397000-db48-11ea-9e7d-540d7666542d.png)

**Comment by alisentinel** [comment]
Not fixed yet

**Comment by rezazoom** [comment]
+1
