### ISSUE TITLE
[Question] How does Telegram afford paying for the used servers ?

### ISSUE THREAD

**Issue by ModMaamari** [telegramdesktop/tdesktop#8411]
We all know that Telegram is the best chatting application that will ever be made, but now and then I have some questions :
- Telegram allows users to upload large files up to 2 GB.
- Users can upload as many files as they want (as far as I know)
- It is completely free.
- There are no ads in Telegram.
- Telegram is much faster than other chatting apps (ex: Whatsapp)
The questions are : 
1- How does Telegram afford paying for the used servers ?   
2- How does Telegram earn money ?

**Comment by Aokromes** [comment]
1 word: durov.

**Comment by RadRussianRus** [comment]
Quoting Telegram FAQ, ["How are you going to make money out of this?"](https://telegram.org/faq#q-how-are-you-going-to-make-money-out-of-this):

> We believe in fast and secure messaging that is also 100% free.
> 
> Pavel Durov, who shares our vision, supplied Telegram with a generous donation, so we have quite enough money for the time being. If Telegram runs out, we will introduce non-essential paid options to support the infrastructure and finance developer salaries. But making profits will never be an end-goal for Telegram.

**Comment by ModMaamari** [comment]
Thank you all for your answers, they answered my questions clearly.
