### ISSUE TITLE
Telegram freezes when typing into the window

### ISSUE THREAD

**Issue by dana-mb** [telegramdesktop/tdesktop#8416]
### Steps to reproduce
1. Open Telegram Desktop.
2. Place pointer into a chat window or any other text window.
3. Type at least 1 character.

### Expected behaviour
The characters are typed into the text field.

### Actual behaviour
The window is now frozed.

### Configuration
**Operating system:** Windows 10 2004

**Version of Telegram Desktop:** 2.2.0

**Installation source (Linux Only)** - the official website / GitHub releases / flatpak / snap / distribution package:

**Used theme**: Dark

<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by ilya-fedin** [comment]
#7952
