### ISSUE TITLE
problem to run command : configure.bat -D TDESKTOP_API_ID=YOUR_API_ID -D TDESKTOP_API_HASH=YOUR_API_HASH -D DESKTOP_APP_USE_PACKAGED=OFF 

### ISSUE THREAD

**Issue by Nima-ghaferi** [telegramdesktop/tdesktop#8417]
hi 
thanks for the instructions
but i have a issue when running :
`configure.bat -D TDESKTOP_API_ID=YOUR_API_ID -D TDESKTOP_API_HASH=YOUR_API_HASH -D DESKTOP_APP_USE_PACKAGED=OFF `

here is the error:
```
CMake Error at cmake/external/qt/package.cmake:23 (find_package):
By not providing "FindQt5.cmake" in CMAKE_MODULE_PATH this project has asked CMake to find a package configuration file provided by "Qt5", but CMake did not find one.

Could not find a package configuration file provided by "Qt5" with any of the followning names:
      Qt5Config.cmake
      qt5-config.cmake
Add the installation prefix of "Qt5" to CMAKE_PREFIX_PATH or set "Qt5_DIR" to a directory containing one of the above files. If "Qt5" provides a separate development package or SDK, be sure it has been installed.
Call Stack (most recent call first):
CMakeLists.txt:37 (include)
```

**Comment by ilya-fedin** [comment]
That error can be only if `-D DESKTOP_APP_USE_PACKAGED=OFF` is not specified

**Comment by Nima-ghaferi** [comment]
thanks , so how can I specify that?

**Comment by ilya-fedin** [comment]
> configure.bat -D TDESKTOP_API_ID=YOUR_API_ID -D TDESKTOP_API_HASH=YOUR_API_HASH -D DESKTOP_APP_USE_PACKAGED=OFF

That way. I guess that you made some mistake and the command was cropped when you executed it.

**Comment by Nima-ghaferi** [comment]
this is what I exactly copy and paste:

 

> configure.bat -D TDESKTOP_API_ID=17349 -D TDESKTOP_API_HASH=344583e45741c457fe1862106095a5eb -D DESKTOP_APP_USE_PACKAGED=OFF

**Comment by Nima-ghaferi** [comment]
Is there any possibility that I ran it before incorrectly and some cache or something stopped it to run it correctly now?

**Comment by ilya-fedin** [comment]
:thinking: Show the result of `dir ..\Libraries\Qt-5.12.8` from the root of the repository

**Comment by Nima-ghaferi** [comment]
Here it is :
![1](https://user-images.githubusercontent.com/7546105/89976527-dcb39200-dc7d-11ea-8ff6-aa25b6d03d1f.png)
![2](https://user-images.githubusercontent.com/7546105/89976529-df15ec00-dc7d-11ea-9ea1-800117262d72.png)

**Comment by ilya-fedin** [comment]
Qt-5.12.8, not qt_5_12_8

**Comment by ilya-fedin** [comment]
If you followed the instruction, you should have Qt sources in qt_5_12_8 and compiled Qt libraries in Qt-5.12.8
