### ISSUE TITLE
Failed to build Telegram.sln project on Visual Studio 2019

### ISSUE THREAD

**Issue by huypn12** [telegramdesktop/tdesktop#8419]
I followed steps from
https://github.com/telegramdesktop/tdesktop/blob/dev/docs/building-msvc.md

All good until open Telegram.sln with Microsoft Visual Studio 2019 v6.7.1. Visual Studio failed to build with the following error

![image](https://user-images.githubusercontent.com/2792821/90083457-d9b6b100-dd12-11ea-8bed-bdea8ce9a518.png)

**Comment by ilya-fedin** [comment]
MSVC bug.
https://github.com/telegramdesktop/tdesktop/issues/8415#issuecomment-672080415
