### ISSUE TITLE
crashed when try to attach something

### ISSUE THREAD

**Issue by bengoshii** [telegramdesktop/tdesktop#8420]
### Steps to reproduce
1. click on clip symbol
2. telegram client close at once

### Expected behaviour
should give the possibily to attach something :)

### Actual behaviour
application crash

### Configuration
**Operating system:**
debian 10.5
**Version of Telegram Desktop:**
2.2
**Installation source (Linux Only)** - the official website / GitHub releases / flatpak / snap / distribution package:
official website
**Used theme**:
night theme

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/8336
