### ISSUE TITLE
unicode symbol Ƀ not shown correct in messages from Bots - OSX 

### ISSUE THREAD

**Issue by sobelman** [telegramdesktop/tdesktop#8422]
### Steps to reproduce
1. Send an inline keyboard with symbol Ƀ as text to OS X client. 
2. Symbol looks faulty
3. When copying this symbol manually to the chat window - it looks good. 
4. When trying to see the faulty symbol via mobile or web version it looks good as well.

### Expected behaviour
To see correct symbol like in telegram web / telegram app / windows / ubuntu 

### Actual behaviour
Telegram is converting symbol to faulty font - sort sort of "square"

### Configuration
**Operating system:**
OS X (Catalina 10.15.5)

**Version of Telegram Desktop:**
2.2 

faulty:
<img width="114" alt="Screen Shot 2020-08-13 at 16 22 07" src="https://user-images.githubusercontent.com/10270857/90139860-93e50180-dd81-11ea-898f-8dd13e4f0b2b.png">

Correct: 
<img width="143" alt="Screen Shot 2020-08-13 at 16 26 27" src="https://user-images.githubusercontent.com/10270857/90140011-cb53ae00-dd81-11ea-9810-44342f59e9b5.png">

**Comment by ilya-fedin** [comment]
#6056
