### ISSUE TITLE
Edited Text in the midst of typing spontaneously reset to older version from a few seconds ago.

### ISSUE THREAD

**Issue by prof7bit** [telegramdesktop/tdesktop#8423]
### Steps to reproduce
Have it installed on Android **AND** on Desktop (not sure whether this is relevant)
Join a crowded chat room with lots of activity and start writing a long text.

### Expected behaviour
Text editing working flawlessly

### Actual behaviour
Sometimes when I have been editing the text for a few minutes suddenly the entire contents of the input field is replaced with an older version of what I have been editing from just a few seconds ago. For example I have written 3 sentences, then I wait a moment, maybe rearrange the wording in the first sentence, then suddenly in the midst of typing it will restore the contents of the entire text field to the state it was 20 seconds ago, recently typed parts of the text disappearing (for example the last of my 3 sentences disappears along with the half finished edit further up that I just have been doing right at this moment).

### Configuration
Kubuntu 20.04 (also happened on previous Kubuntu versions) 
Telegram 2.2
Downloaded binary from official Telegram website (but also happens with snap version, has been happening since months, at least once or twice a day)
Theme: dark.

**Comment by ilya-fedin** [comment]
#4922 (btw, there are a lot of duplicates, why didn't you search before opening new issue?)
