### ISSUE TITLE
[Feature Request] "reply in thread" functionality

### ISSUE THREAD

**Issue by vindex10** [telegramdesktop/tdesktop#8424]
Hello all!

There is a possible way out with a present API (I guess, although I'm not an expert in it), following the solution discussed in the Mattermost community:
https://mattermost.atlassian.net/browse/MM-8457

Basic idea is to allow collapsing messages by hash tag through UI. Maybe an option to do it automatically (as a switch). Can be integrated seamlessly with a customized "reply in thread" button that will append relevant hashtag to the new message. Can be done explicitly, so that telegram desktop won't modify user messages under the hood.

Similar question has been closed without references here:
https://github.com/telegramdesktop/tdesktop/issues/6657

I'm wondering Is there a way to leave or look at existing API feature requests?

Please, let me know if this question has been answered, I could bring up my suggestion there :)

Thank you!

**Comment by Aokromes** [comment]
in app ask a question is the way to request such things.

**Comment by vindex10** [comment]
where in app? you mean: telegram desktop > about > ask a question > ask volonteer?

**Comment by Aokromes** [comment]
yes.

**Comment by vindex10** [comment]
Ok. Thank you. I'll share the reply here if you don't mind.
