### ISSUE TITLE
[Feature Request] more than 3 Accounts on TDesktop

### ISSUE THREAD

**Issue by catSIXe** [telegramdesktop/tdesktop#8425]
### Is your feature request related to a problem?
There is really no reason to limit the Desktop Telegram Client to only 3 Accounts

### Describe the solution you'd like
Remove the Limit, because there is no real reason for it in the first place. "Saving Battery"

### Additional context
Plus Messenger can do it on Android to, its just a stupid Softwarelimit

**Comment by ilya-fedin** [comment]
#8276

**Comment by catSIXe** [comment]
then im gonna fork this, fix this issue...
