### ISSUE TITLE
[Question] Multi-Account Limited

### ISSUE THREAD

**Issue by Lordemax** [telegramdesktop/tdesktop#8429]
I try to **login** more than three Account and I was not enble to see the adds button again,
I  just don't know maybe i am doing something wrong Or maybe its limited to only **Three Accounts**
Need to know please.

**Comment by magnickolas** [comment]
As I can see, there is the **kMaxAccounts** variable that limits the number of accounts you can login into. It means you're doing nothing wrong.
https://github.com/telegramdesktop/tdesktop/blob/5cc7c2b6c6ecdce1ab4067549c4e7acd299dd5d5/Telegram/SourceFiles/main/main_domain.h#L33

**Comment by Aokromes** [comment]
it's limited because resources ussage.

**Comment by aemxn** [comment]
@Lordemax if you wish to use more than 3 accounts (max for one client), use the portable version of tdesktop and clone the folder to how many as you like.

**Comment by Lordemax** [comment]
Thanks 👍 everyone for your response
I appreciate.
I am closing thread now
