### ISSUE TITLE
Camera requirement even for voice calls only

### ISSUE THREAD

**Issue by borshpro** [telegramdesktop/tdesktop#8430]
# Telegram refuses to start **voice only** call without Camera access permission
### Steps to reproduce
0. Enable Microphone access permission for Telegram. Result: Telegram **has access to Microphone**.
1. Start Telegram voice call
2. Telegram requests Camera access permission.
3. Deny Telegram to access Camera. Result: Telegram has **no access to Camera**.
4. Telegram refuses to start voice call without Camera access permission with message "Telegram needs access to your microphone so that you can make calls and record voice messages".

### Expected behaviour
Telegram should allow voice only call without Camera access permission enabled.

### Actual behaviour
Telegram refuses to start or accept voice only call without Camera access permission enabled

### Configuration
- **Operating system:** macOS `10.14.6`
- Microphone access permission enabled for Telegram
- Camera access permission disabled for Telegram

**Version of Telegram Desktop:**
[`2.3`](https://desktop.telegram.org/changelog#v-2-3-14-08-20)

### Sources to inspect
- [settings_calls.cpp](https://github.com/telegramdesktop/tdesktop/blob/a95b756111eafa83886732c9ce17eed8d5251056/Telegram/SourceFiles/settings/settings_calls.cpp), [`Calls::requestPermissionAndStartTestingMicrophone`](https://github.com/telegramdesktop/tdesktop/blob/a95b756111eafa83886732c9ce17eed8d5251056/Telegram/SourceFiles/settings/settings_calls.cpp#L324)
- [calls_instance.cpp](https://github.com/telegramdesktop/tdesktop/blob/bc7925985c06b6eafec9000edc0e02b553c00cad/Telegram/SourceFiles/calls/calls_instance.cpp), [`Instance::requestPermissionOrFail`](https://github.com/telegramdesktop/tdesktop/blob/bc7925985c06b6eafec9000edc0e02b553c00cad/Telegram/SourceFiles/calls/calls_instance.cpp#L321)

**Comment by john-preston** [comment]
@borshpro Yeah, I'll need to fix that. Thanks!

**Comment by borshpro** [comment]
@john-preston do you have a roadmap of fixing issues?
Problem still exists in latest Telegram Desktop version.
