### ISSUE TITLE
telegram custom ringtones (songs...)

### ISSUE THREAD

**Issue by freemangilgamesh** [telegramdesktop/tdesktop#8431]
I suggest you add the option to set custom ringtones for audio/video calls.

**Comment by ilya-fedin** [comment]
There are already an "option"
https://github.com/telegramdesktop/tdesktop/wiki/Hidden-modes

**Comment by freemangilgamesh** [comment]
I'm running it on Linux Mint (tdesktop) so how can I enable these features?

**Comment by ilya-fedin** [comment]
> I'm running it on Linux Mint (tdesktop) so how can I enable these features?

The page describes that
