### ISSUE TITLE
The call don't connect using VPN/proxy

### ISSUE THREAD

**Issue by sepehr-brj** [telegramdesktop/tdesktop#8432]
### Steps to reproduce
1. Connect to the system proxy or VPN (I have to use VPN because Telegram is blocked in Iran)
2. Call someone

### Expected behaviour
The call connect and the other person receives the call.

### Actual behaviour
The call don't connect and it just writes "waiting..."
But when someone calls me (with an Android phone), I can accept the call and there is no problem.
This problem has existed for me from previous versions.

### Configuration
**Operating system:** Windows 7 x86

**Version of Telegram Desktop:** 2.3

**Installation source (Linux Only)** - the official website / GitHub releases / flatpak / snap / distribution package:

**Used theme**:

<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by ilya-fedin** [comment]
#3911?

**Comment by sepehr-brj** [comment]
> #3911?

No, the person I call won't receive my call to answer it.

**Comment by sepehr-brj** [comment]
The problem seems to be fixed
