### ISSUE TITLE
Arabic fonts do not support all letters of Arabic scripts

### ISSUE THREAD

**Issue by MuratKaribay** [telegramdesktop/tdesktop#8433]
Is it possible to change fonts to fully support Arabic scripts or add letters to the Vazir font used by Telegram?

![image](https://user-images.githubusercontent.com/40431755/90313101-97b48780-df2b-11ea-9ae0-15552a8fef49.png)

Operating system: Windows 10
Version of Telegram Desktop: 2.3

**Comment by Aokromes** [comment]
request the 2nd at https://github.com/rastikerdar/vazir-font

**Comment by MuratKaribay** [comment]
> request the 2nd at https://github.com/rastikerdar/vazir-font

I wrote but the font author didn't respond
https://github.com/rastikerdar/vazir-font/issues/164

Is it possible to speed up the process of adding support for Arabic letters in Vazir fonts?

**Comment by MuratKaribay** [comment]
@Aokromes recently the Vazir font was updated please update Telegram

**Comment by Aokromes** [comment]
> @Aokromes recently the Vazir font was updated please update Telegram

it's @john-preston who must do :)

**Comment by MuratKaribay** [comment]
@john-preston can you add Vazir 27.1.0 in the next telegram update?
