### ISSUE TITLE
build on Windows fail due to webrtc

### ISSUE THREAD

**Issue by kirsan31** [telegramdesktop/tdesktop#8434]
When running `gclient sync --no-history` on windows 7 I've got an error:
```
line 246, in convert_osc
    for match in self.ANSI_OSC_RE.finditer(text):
TypeError: cannot use a string pattern on a bytes-like object
```
I think this is known issue:
https://groups.google.com/a/chromium.org/forum/#!topic/chromium-discuss/Ej4m7eckUhQ
https://groups.google.com/forum/#!topic/discuss-webrtc/P6Zzm3H05s4
So tdesktop need some workaround or drop windows 7 support in [build instructions for Visual Studio 2019](https://github.com/telegramdesktop/tdesktop/blob/dev/docs/building-msvc.md)?

**Comment by john-preston** [comment]
@kirsan31 I'm afraid the second, I've never tried to build it on Windows 7, only on 10.

**Comment by 23rd** [comment]
I would suggest you to build WebRTC library with Github CI and download it as an artifact.

**Comment by kirsan31** [comment]
As a result, I upgraded to Win10 :)
After that I've got:

> No downloadable toolchain found. In order to use your locally installed version of Visual Studio to build Chrome please set DEPOT_TOOLS_WIN_TOOLCHAIN=0.

After adding `SET DEPOT_TOOLS_WIN_TOOLCHAIN=0`:

> call gclient sync --no-history
> Syncing projects: 100% (40/40), done.
> Running hooks: 100% (23/23), done.
> error: patch failed: BUILD.gn:335
> error: BUILD.gn: patch does not apply
> error: patch failed: api/test/video/BUILD.gn:8
> error: api/test/video/BUILD.gn: patch does not apply
> error: patch failed: audio/utility/channel_mixer.cc:10
>......

Google say that building webrtc on Win it;s not as simple as in TD docs, and some variables must be set like  `DEPOT_TOOLS_WIN_TOOLCHAIN,GYP_DEFINES,GYP_GENERATORS,GYP_MSVS_VERSION`... Also many topics about x64 only :confused:
Any advice?

**Comment by 23rd** [comment]
> error: patch failed: BUILD.gn:335

You have to resave these `diff` files with the Unix EOL.

**Comment by c0re100** [comment]
If git apply not work, use `patch -p1 < ....../xxxx.diff`

**Comment by kirsan31** [comment]
Thanks guys - it's working.

**Comment by kirsan31** [comment]
Guys after `Use webrtc from a custom-built fork.`  build process fail again :)  I have following errors:

```
[1/1572] Building CXX object CMakeFiles/libyuv.dir/src/third_party/libyuv/source/scale_argb.cc.obj
FAILED: CMakeFiles/libyuv.dir/src/third_party/libyuv/source/scale_argb.cc.obj
D:\save\projects\TBuild\ThirdParty\Strawberry\c\bin\c++.exe  -DABSL_ALLOCATOR_NOTHROW=1 -DHAVE_JPEG -DHAVE_SCTP -DHAVE_SSE2 -DHAVE_WINSOCK2_H -DNOMINMAX -DWIN32_LEAN_AND_MEAN -I../../../qt_5_12_8/qtbase/src/3rdparty/libjpeg -I../../../qt_5_12_8/qtbase/src/3rdparty/libjpeg/src -I../../src/third_party/libyuv/include -g   /W1 /wd4715 /wd4244 /wd4838 /wd4305 /MP /EHsc /Zc:wchar_t- /Zi -std=gnu++17 -MD -MT CMakeFiles/libyuv.dir/src/third_party/libyuv/source/scale_argb.cc.obj -MF CMakeFiles\libyuv.dir\src\third_party\libyuv\source\scale_argb.cc.obj.d -o CMakeFiles/libyuv.dir/src/third_party/libyuv/source/scale_argb.cc.obj -c ../../src/third_party/libyuv/source/scale_argb.cc
c++.exe: error: /W1: No such file or directory
c++.exe: error: /wd4715: No such file or directory
c++.exe: error: /wd4244: No such file or directory
c++.exe: error: /wd4838: No such file or directory
c++.exe: error: /wd4305: No such file or directory
c++.exe: error: /MP: No such file or directory
c++.exe: error: /EHsc: No such file or directory
c++.exe: error: /Zc:wchar_t-: No such file or directory
c++.exe: error: /Zi: No such file or directory
[2/1572] Building CXX object CMakeFiles/libyuv.dir/src/third_party/libyuv/source/rotate_gcc.cc.obj
FAILED: CMakeFiles/libyuv.dir/src/third_party/libyuv/source/rotate_gcc.cc.obj
D:\save\projects\TBuild\ThirdParty\Strawberry\c\bin\c++.exe  -DABSL_ALLOCATOR_NOTHROW=1 -DHAVE_JPEG -DHAVE_SCTP -DHAVE_SSE2 -DHAVE_WINSOCK2_H -DNOMINMAX -DWIN32_LEAN_AND_MEAN -I../../../qt_5_12_8/qtbase/src/3rdparty/libjpeg -I../../../qt_5_12_8/qtbase/src/3rdparty/libjpeg/src -I../../src/third_party/libyuv/include -g   /W1 /wd4715 /wd4244 /wd4838 /wd4305 /MP /EHsc /Zc:wchar_t- /Zi -std=gnu++17 -MD -MT CMakeFiles/libyuv.dir/src/third_party/libyuv/source/rotate_gcc.cc.obj -MF CMakeFiles\libyuv.dir\src\third_party\libyuv\source\rotate_gcc.cc.obj.d -o CMakeFiles/libyuv.dir/src/third_party/libyuv/source/rotate_gcc.cc.obj -c ../../src/third_party/libyuv/source/rotate_gcc.cc
c++.exe: error: /W1: No such file or directory
c++.exe: error: /wd4715: No such file or directory
c++.exe: error: /wd4244: No such file or directory
c++.exe: error: /wd4838: No such file or directory
c++.exe: error: /wd4305: No such file or directory
c++.exe: error: /MP: No such file or directory
c++.exe: error: /EHsc: No such file or directory
c++.exe: error: /Zc:wchar_t-: No such file or directory
c++.exe: error: /Zi: No such file or directory
```

and so on...

The problem with `/`compiler switches. Sorry, I am not familiar with all of this scripting and  google was unable to help here :(

**Comment by john-preston** [comment]
@kirsan31 It looks like you are using not the Visual C++ compiler. It uses "ThirdParty\Strawberry\c\bin\c++.exe" instead 🤔 I wonder how it got in your PATH and in your cmake configuration.

**Comment by kirsan31** [comment]
Ah - thank you very much! How did I not notice that??? :man_facepalming:
![image](https://user-images.githubusercontent.com/17767561/91292714-955df300-e79f-11ea-9488-e176e3e748df.png)
I think Strawberry puts it in `Path` during installation...

**Comment by ilya-fedin** [comment]
> I think Strawberry puts it in `Path` during installation...

MSVC should get preference if you're in the Visual C++ build prompt

**Comment by kirsan31** [comment]
> MSVC should get preference if you're in the Visual C++ build prompt

It theory yeas, but on practices I've got those errors unless I removed it from Path...

**Comment by Aokromes** [comment]
so, this can be closed?

**Comment by kirsan31** [comment]
> so, this can be closed?

I think no, the main goal of this issue was _unable to build tdesktop on Win7 any more_. And as @john-preston [said ](https://github.com/telegramdesktop/tdesktop/issues/8434#issuecomment-674402494) we need to adress this in the docs...

**Comment by 23rd** [comment]
I have successfully built `tg_owt` lib files on Windows 7 and I don't see any barriers for building tdesktop on Windows 7.

**Comment by kirsan31** [comment]
> I have successfully built `tg_owt` lib files on Windows 7 and I don't see any barriers for building tdesktop on Windows 7.

It's a good news. Then there were only problems with the first version of the webrtc build (not custom `tg_owt`).
