### ISSUE TITLE
Selected output device is ignored for calls

### ISSUE THREAD

**Issue by giladgd** [telegramdesktop/tdesktop#8435]
### Steps to reproduce
1. Go to Settings > Advanced > Call Settings (under System integration) > Output device
2. Select a different output device than the default one
3. Start a call

### Expected behaviour
The audio output should come out of the selected output device

### Actual behaviour
The audio output comes out of the default output device

### Configuration
**Operating system:**
Tested on both Windows and macOS
**Version of Telegram Desktop:**
2.3
**Installation source (Linux Only)** - the official website / GitHub releases / flatpak / snap / distribution package:
the official website
**Used theme**:
Builtin dark theme

# Notes
BTW, an option to select a camera device to use for video calls could be handy,
And making `Settings > Advanced > Show tray icon (under System integration)` a switch button instead of a checkbox could make finding `Call Settings` much easier, as there are no other checkboxes in that screen, and this checkbox makes `Call Settings` look like a title rather than a button to another settings screen, maybe even move this button to the main settings screen.

**Comment by olliefr** [comment]
I had been experiencing the same symptoms for a while until I made an interesting discovery, almost by accident:

It appears that there are two _types_ of "default" output devices in Windows 10, the ordinary **Default Device** and the **Default Communications Device**. The only place in the interface where I've seen them mentioned (and managed) separately is the **Sound** component of the good old **Control Panel**.

The next two screenshots show how my system was set up when audio from Telegram calls was not routed to the correct output device. The Telegram output settings as well as _Windows 10 Settings_ audio section had the correct devices selected. Only the **Sound** component of the **Control Panel**, displayed in the screenshots had a different setting which seems to have been overriding everything else.

![sound1](https://user-images.githubusercontent.com/967105/91108072-de625a00-e66e-11ea-9225-e35c858e6993.png)
![sound2](https://user-images.githubusercontent.com/967105/91108078-e28e7780-e66e-11ea-9adb-fa679604dfb5.png)

I assigned the **Default Communications Device** to the correct output device and now Telegram behaves as I would expect.

![sound3](https://user-images.githubusercontent.com/967105/91108725-ab20ca80-e670-11ea-9d2c-90efaf246a0e.png)

**Comment by Bookrage001** [comment]
Would this be something like facebook has where on the call you can choose to change your audio output device and microphone. Discord also allows the same thing ?
Then remembering that choice ? rather than just using the default system communication device

**Comment by ilya-fedin** [comment]
@Bookrage001 there are call settings in advanced settings

**Comment by olliefr** [comment]
> Would this be something like facebook has where on the call you can choose to change your audio output device and microphone. Discord also allows the same thing ?
> Then remembering that choice ? rather than just using the default system communication device

I don't think so because I use the same bluetooth headphones with my PC. It's just sometimes they are connected and sometimes they are not. I have found that I (often) need to restart TGM after (dis)/connecting them because it does not pick up the change. I had a different pair of bluetooth headphones before and it was the same. 

For me, this feels like an intermittent problem, because I never know whether I'll need to restart it after having connected or disconnected the headphones.

**Comment by olliefr** [comment]
> @Bookrage001 there are call settings in advanced settings

And they don't work for me. As in the right devices are selected when I open the settings, but there is no sound. Restarting TG helps.

I've noticed that TG writes detailed logs, I conjecture it would be very simple to diagnose (and possibly) solve the issue for someone who actually knows how TG handles sound. I conjecture (pure guess) that it relies on some cross-platform library which is just not that good for bluetooth devices which come on and off all the time.

**Comment by chernyaknikita** [comment]
Same problem, I use Manjaro Linux (official package, version 2.4.11-0.1).

**Comment by GarlandM** [comment]
Same issue, Windows 10.

Unable to hear voice calls, listening to audio messages is fine.

**Comment by ilya-fedin** [comment]
> Unable to hear voice calls, listening to audio messages is fine.

This issue is about changing output device, it is not about output not working at all

**Comment by GarlandM** [comment]
> > Unable to hear voice calls, listening to audio messages is fine.
> 
> This issue is about changing output device, it is not about output not working at all

Right, I can hear voice messages because Telegram is using my default device, but I cannot hear calls because it is ignoring my device.

**Comment by ilya-fedin** [comment]
> ... I can hear ... but I cannot hear ...

WTF?

**Comment by GarlandM** [comment]
You seem to be confused, so let's break this down.

This issue is about CALL SETTINGS, not AUDIO SETTINGS.

My AUDIO SETTINGS work as intended.

My CALL SETTINGS do not.

Playing AUDIO works.

Hearing CALL AUDIO does not.

**Comment by ilya-fedin** [comment]
But you still should hear on the default device even if you can't change to another.

**Comment by sergstesh** [comment]
So, is this issue, as well as the one I've filed ( #10411 ) considered to be confirmed bug ? It appears the problem was first reported on Aug.15 2020, i.e. more than 6 months old.

**Comment by ilya-fedin** [comment]
> So, is this issue, as well as the one I've filed ( #10411 ) considered to be confirmed bug ?

looks like not

**Comment by sergstesh** [comment]
> looks like it isn't

According to this report people have the same issue on Windows. MacOS and on various versions of Linux. Also, the issue migrated from version to version of the desktop client.

Any additional info is necessary to consider this bug to be confirmed ?

Again, as I wrote in the issue I've filed ( #10411 ), output audio device selection works as expected in Skype.

**Comment by john-preston** [comment]
@sergstesh Starting with version 2.5.7 (January 28) it should work. At least I tested on Windows and macOS.

**Comment by sergstesh** [comment]
> Starting with version 2.5.7 (January 28) it should work. At least I tested on Windows and macOS.

@john-preston ,I am on version 2.5.8, i.e. later than 2.5.7, and I am on Linux, and it doesn't work for me.

**Comment by Aokromes** [comment]
> > Starting with version 2.5.7 (January 28) it should work. At least I tested on Windows and macOS.
> 
> @john-preston ,I am on version 2.5.8, i.e. later than 2.5.7, and I am on Linux, and it doesn't work for me.

from where you have downloaded it?

**Comment by sergstesh** [comment]
> from where you have downloaded it?

I installed it via 'flatpak' the usual way:

`flatpak --verbose install flathub org.telegram.desktop`
.

**Comment by Aokromes** [comment]
try downloading from desktop.telegram.org or releases on github.

**Comment by sergstesh** [comment]
> try downloading from desktop.telegram.org

I have just downloaded the client from desktop.telegram.org , the version happens to be 2.5.9, the problem persists.

By the way, how about implementing echo test call ? Because I feel uncomfortable bothering friends with test calls.

**Comment by Sherriador** [comment]
Windows 10 20H2 x64
Telegram desktop 2.7.4 х64
The same issue
Telegram ignores "Default communication device" setting and routes call audio to "Default audio device" instead.

**Comment by ilya-fedin** [comment]
> Telegram ignores "Default communication device" setting and routes call audio to "Default audio device" instead.

There were a lot of complains that using default communication device is unexpected, so Telegram uses the common default device and this issue is not about that, but about manual selected device in Telegram settings.

**Comment by Sherriador** [comment]
Если не сложно, напишите по-русски, пожалуйста 🙏 я не смог точно перевести Ваш ответ 😔

**Comment by ilya-fedin** [comment]
Эта ишью про ручной выбор устройства в настройках tdesktop. Не про устройство по-умолчанию.

**Comment by Sherriador** [comment]
Хмм, тут не совсем ручной.
У меня так настроено: устройство воспроизведения - колонки, а устройство связи - уши.
И телеграм вместо ушей направляет голосовой звонок на колонки и микрофон вебки 😭

**Comment by ilya-fedin** [comment]
Повторяюсь, эта ишью про ручной выбор устройства в настройках tdesktop. Если у вас проблемы с устройством по-умолчанию, вы пишите не в той ишью.

**Comment by Sherriador** [comment]
Подскажите, пожалуйста, куда написать 🙏🤝

**Comment by ilya-fedin** [comment]
Никуда, текущее поведение сделано специально, большинство людей не понимают, что существует default communication device, поэтому tdesktop использует обычное устройство по-умолчанию.

**Comment by sergstesh** [comment]
By the way, Telegram behavior is still broken. On startup Telegram routs output to default device. Then I redirect it to the device of my choosing:  "USB PnP Sound Device Analog Stereo". The output gets rerouted as expected.

However, on next startup Telegram again routs output to default device. As I wrote in https://github.com/telegramdesktop/tdesktop/issues/10411 , I would like to see the same behavior as in Skype, i.e. I want Telegram to respect my device choices once and for all.

**Comment by ilya-fedin** [comment]
@sergstesh you have to wait until someone interested will reproduce and fix your case or dig and fix yourself. Personally I have only one output device, so I can't reproduce.

**Comment by Sherriador** [comment]
Всё бы ничего, но вот какой интересный момент: если мне звонят с Telegram X, то всё нормально!
То есть проблема со звуком только когда мне звонят с обычного клиента телеграм.
Проверено на разных людях , с разными платформами, а также я проверил на разных компьютерах.

**Comment by ilya-fedin** [comment]
Видимо, Telegram X использует старое API звонков, тогда используется libtgvoip, который больше не развивается, он использует default communication device по-умолчанию.

**Comment by Sherriador** [comment]
Обратите внимание: вызов идёт с Х на обычный
И проблема на обычном Телеграм.
Получается, обычный телеграм выбирает протокол в зависимости от вызывающего клиента? И при работе со старым апи выбирает аудиоустройство корректно?

**Comment by ilya-fedin** [comment]
Если обе стороны звонка поддерживают новое API, то используется webrtc с новым кодом, соответственно решение не использовать default communication device в силе.
Если одна из сторон не может использовать новое API, то используется старый libtgvoip, который уже никто не будет изменять, чтобы он не использовал default communication device

**Comment by Sherriador** [comment]
Спасибо большое за исчерпывающий ответ 🤝🙏

**Comment by maper256** [comment]
> Никуда, текущее поведение сделано специально, большинство людей не понимают, что существует default communication device, поэтому tdesktop использует обычное устройство по-умолчанию.

Я не могу понять, зачем  игнорировать устройство связи по умолчанию, даже если какой-то пользователь из большинства людей, которые такого устройства не знают.
Если это баг, то почему он так долго не исправляется. Если это фича, то зачем это сделано и как жить квалифицированному пользователю, который хочет говорить через телеграм десктоп по компьютерной гарнитуре?

**Comment by sergstesh** [comment]
> Если это баг, то почему он так долго не исправляется. Если это фича, то зачем это сделано и как жить квалифицированному пользователю, который хочет говорить через телеграм десктоп по компьютерной гарнитуре?


Exactly. Вот именно.

**Comment by ilya-fedin** [comment]
> Если это фича, то зачем это сделано и как жить квалифицированному пользователю, который хочет говорить через телеграм десктоп по компьютерной гарнитуре?

Выбрать нужное устройство в настройках телеграма

**Comment by maper256** [comment]
> > Если это фича, то зачем это сделано и как жить квалифицированному пользователю, который хочет говорить через телеграм десктоп по компьютерной гарнитуре?
> 
> Выбрать нужное устройство в настройках телеграма

Я не нашел в настройках телеграм десктоп версия 2.7.4 х64 под windows 10 кнопок управления выбором аудиоустройств. Если можно, подскажите.

**Comment by maper256** [comment]
> > > Если это фича, то зачем это сделано и как жить квалифицированному пользователю, который хочет говорить через телеграм десктоп по компьютерной гарнитуре?
> > 
> > 
> > Выбрать нужное устройство в настройках телеграма
> 
> Я не нашел в настройках телеграм десктоп версия 2.7.4 х64 под windows 10 кнопок управления выбором аудиоустройств. Если можно, подскажите.

Нашел. Просто CALL SETTINGS не сразу понимаешь, что туда можно нажать - оно черное, а не синее. Все заработало. Две небольших проблемы.
1. Входящий звонок идет только в гарнитуру.
2. Ответить кнопкой на гарнитуре не удается, приходится нажимать мышкой зеленую кнопку на компе. Гарнитура Plantronics Savi W710. Программный телефон например BRIA вполне реагирует на кнопку на гарнитуре - можно этой кнопкой принять или завершить звонок.
Если эти проблемы имеют решение, подскажите, плиз.

**Comment by ilya-fedin** [comment]
>     2\. Ответить кнопкой на гарнитуре не удается, приходится нажимать мышкой зеленую кнопку на компе.

Полагаю, для этого надо импелментить какое-нибудь API, без понятия какое.
