### ISSUE TITLE
Bugged thumbnails in album view

### ISSUE THREAD

**Issue by Remu-rin** [telegramdesktop/tdesktop#8439]
### Steps to reproduce
1. Open album of 10 pictures
2. Look at previews at the bottom
3. Step through pictures

### Actual behaviour
1. Stepping animation is not smooth, or there is no animation
2. Thumbnails look weird. If current picture has horizontal orientation, it can overlap part of the next picture, or space before next picture is too small. For some images it makes it hard to see what thumbnails are showing. When current picture has vertical orientation it's the opposite, too much space before next picture.
3. There are bugged artifacts, for example when opening https://t.me/varlamov_news/19129 from any picture of album except last, and then going to last picture, you see (most times) some artifact of thumbnail right to the last thumbnail, when there should be nothing:
![image](https://user-images.githubusercontent.com/28995228/90325829-ff092080-df99-11ea-9b63-0fbe9a63b7c3.png)

### Expected behaviour
1. In old versions (i.e. 1.8.1, I don't know when exactly those things degraded, probably in a several last months) stepping animation is smooth.
2. In old versions current thumbnail were not overlapping part of the next picture, and space between current thumbnail and other (to left and to right) looked the same for pictures with different orientation.
3. In old versions there were no artifacts like this.

### Configuration
**Operating system:** Windows

**Version of Telegram Desktop:** 2.3

**Used theme**: Night

**Comment by ilya-fedin** [comment]
#8392

**Comment by Remu-rin** [comment]
8392 is only about last of 3 things. 1 and 2 is not duplicate. Reopen please.

**Comment by ilya-fedin** [comment]
There are no reasons to colletcing issues which are almost the same. You can write a comment to that issue with 1 and 2 things.
