### ISSUE TITLE
Disclosed Vulnerability Update - Storing Chats in Plain Text Locally

### ISSUE THREAD

**Issue by vlkz** [telegramdesktop/tdesktop#844]
Does anyone have an update on this vulnerability that was discovered and disclosed earlier this year?
http://blog.zimperium.com/telegram-hack/

What's with that?

**Comment by omyno** [comment]
Telegram Desktop does not support secret chats and the developer [does not plan](118#issuecomment-72011592) to implement encryption. You should ask the [Android app](https://github.com/DrKLO/Telegram) developers about this or [send out a tweet](https://twitter.com/telegram).
