### ISSUE TITLE
Size Scaling

### ISSUE THREAD

**Issue by kown7** [telegramdesktop/tdesktop#8441]
### Steps to reproduce
1.  Open Telegram on 4K (HiDPI) Monitor
2.  Plug in external Monitors (disables 4K Monitor)
3.  Telegram doesn't scale, everything's way too big

### Expected behaviour
Should scale to have "normal" scaling.

### Actual behaviour
Size of everything doesn't scale. Closing (terminating) the application will solve the problem.

### Configuration
**Operating system: Win10**

**Version of Telegram Desktop: 2.3**

**Used theme**: default(?)

**Comment by kown7** [comment]
PS: Is there some sort of 100% Button that fixes the issue?

**Comment by ilya-fedin** [comment]
#1121

**Comment by kown7** [comment]
Duplicate
