### ISSUE TITLE
Telegram close after closing call

### ISSUE THREAD

**Issue by michele-grifa** [telegramdesktop/tdesktop#8442]
### Steps to reproduce
1. Answer a call or a video call
2. End call
3. Telegram is closed

### Expected behaviour
Telegram should remain open

### Actual behaviour
Telegram close

### Configuration
**Operating system:** Windows 10 1909

**Version of Telegram Desktop:** 2.3

**Used theme**: Default

**Comment by ArmeF97** [comment]
This happens only if the main window is closed (to the tray)

It's a bug

**Comment by michele-grifa** [comment]
> 
> 
> This happens only if the main window is closed (to the tray)
> 
> It's a bug

Yes, i have done another test and it close when the window is closed in tray

**Comment by Zloi78** [comment]
Version 2.4.3. The same problem. The program crashes when minimized in the tray.

**Comment by john-preston** [comment]
Will be fixed in 2.4.4 later today.
