### ISSUE TITLE
Segmentation fault on Linux whenever I try to attach any media

### ISSUE THREAD

**Issue by Loara** [telegramdesktop/tdesktop#8448]
Hi,
I'm using version 2.3 of Telegram Desktop on Linux systems, and every time I click the paper clip (whether in private chats or in groups) the application crashes. I have Debian 10 (Buster) 64 bit and GNOME v. 3.30.2

### Steps to reproduce
1. Open Telegram Desktop v. 2.3 on Linux system
2. Open any chat
3. Click the Paper Clip

### Expected behaviour
No crashes.

### Actual behaviour
Telegram Desktop crashes. I ran it on gdb and I obtained this error message:

    Thread 1 "Telegram" received signal SIGSEGV, Segmentation fault.
    0x0000000003a11c2a in ?? ()

### Configuration
**Operating system:** Linux Debian 10 (Buster) 64 bit

**Version of Telegram Desktop:** 2.3

**Installation source (Linux Only)** - the official website / GitHub releases / flatpak / snap / distribution package: Official Telegram Desktop website

**Used theme**: Dark theme

<details><summary><b>Logs</b>:</summary>
Thread 1 "Telegram" received signal SIGSEGV, Segmentation fault.
0x0000000003a11c2a in ?? ()
</details>

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/8336
