### ISSUE TITLE
White blink when opening Telegram window in dark theme

### ISSUE THREAD

**Issue by natovan** [telegramdesktop/tdesktop#8451]
### Steps to reproduce
1. Switch to night theme in Telegram
1. Close and open Telegram Desktop window
2. See the white blink

### Expected behaviour
No white blink

### Actual behaviour
White blink

### Configuration
Win10 64bit
Version 2.3
Night theme

Also noticeable sometimes in light theme

**Comment by typex-code** [comment]
Doesn't happen to me

**Comment by kaafivikrant** [comment]
It is happening but not much considerable.

**Comment by natovan** [comment]
If this issue will be fixed, Telegram will become perfect!

**Comment by hookzof** [comment]
Also found in Google Chrome for example, but not in Spotify.

**Comment by ilya-fedin** [comment]
Which white blink are you talking about? :thinking:

**Comment by hookzof** [comment]
> Which white blink are you talking about? 🤔

Short-term white when unfolding the window, very nasty especially at night.

**Comment by ilya-fedin** [comment]
> Short-term white when unfolding the window, very nasty especially at night.

This doesn't explain anyway :(
Can you make a screencast?

**Comment by Aokromes** [comment]
@hookzof also, can you try updating your drivers before?

**Comment by hookzof** [comment]
> @hookzof also, can you try updating your drivers before?

Yes, and same thing remains.

**Comment by kke** [comment]
![Sep-24-2020 11-44-27](https://user-images.githubusercontent.com/224971/94122577-651b7a00-fe5b-11ea-8363-be4f709f8cb3.gif)

Are you talking about this blink? In dark mode all colors of the window blink in sync with the cursor.

**Comment by hookzof** [comment]
If "Use system window frame" enabled in "Advanced" then "White blink" not observed.
@natovan @ilya-fedin @Aokromes

**Comment by ilya-fedin** [comment]
I believe this is a gfx drivers bug

**Comment by Aokromes** [comment]
> If "Use system window frame" enabled in "Advanced" then "White blink" not observed.
> @natovan @ilya-fedin @Aokromes

what's your gfx? maybe amd?

**Comment by natovan** [comment]
> If "Use system window frame" enabled in "Advanced" then "White blink" not observed.
> @natovan @ilya-fedin @Aokromes

This fixed for me!
