### ISSUE TITLE
Camera selection function in Telegram

### ISSUE THREAD

**Issue by MuratKaribay** [telegramdesktop/tdesktop#8452]
Is it possible to add a camera selection function to Telegram?
My laptop automatically selects the built in camera and I would like to select a virtual external camera that is connected via usb.
As in the screenshot

![image](https://user-images.githubusercontent.com/40431755/90558837-8c2cbf00-e1be-11ea-8079-c2dad669004d.png)

**Comment by john-preston** [comment]
@MuratKaribay Yes, I'll add that in an upcoming release.

**Comment by MuratKaribay** [comment]
> Yes, I'll add that in an upcoming release.

Thank you

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/commit/4672e3d0687849e3c169fa97ea3d79730c6b52f7

**Comment by rdlmda** [comment]
Has this been shipped?

**Comment by Aokromes** [comment]
21 august.

**Comment by rdlmda** [comment]
Sorry, has this been shipped on a binary release? I'm running v2.4.2 (Linux) and this is my "Call Settings" screen:

![Captura de tela de 2020-10-05 19-50-49](https://user-images.githubusercontent.com/4602525/95139981-22ec1580-0744-11eb-9959-d6c366325cc3.png)

**Comment by Aokromes** [comment]
> Sorry, has this been shipped on a binary release? I'm running v2.4.2 (Linux) and this is my "Call Settings" screen:
> 
> ![Captura de tela de 2020-10-05 19-50-49](https://user-images.githubusercontent.com/4602525/95139981-22ec1580-0744-11eb-9959-d6c366325cc3.png)

yes, at least on a windows tablet i own it shows camera selection.

**Comment by john-preston** [comment]
@rdlmda Looks like there is no camera available to tdesktop in your case =(

**Comment by Aokromes** [comment]
> Sorry, has this been shipped on a binary release? I'm running v2.4.2 (Linux) and this is my "Call Settings" screen:
> 

you use flakpak, snap, or download from github or desktop.telegram.org ?

**Comment by MuratKaribay** [comment]
Is it possible to add a function for selecting the aspect ratio format such as 16:9 and 9:16, etc?

P.S. My camera when making a video call, the camera is cropped to 9:16

**Comment by CtrInt** [comment]
I'm using Telegram Desktop 2.4.14 beta on Windows 10 and there is no such option to choose the camera to be used.
