### ISSUE TITLE
Camera permission without need

### ISSUE THREAD

**Issue by Merujan99** [telegramdesktop/tdesktop#8456]
### Steps to reproduce
1.  Open Telegram
2. Call someone

### Expected behaviour
If microphone access was given, it will call normally

### Actual behaviour
For call telegram wants camera access

### Other Info
I don't want to make videocall, just call, and don't want to give application camera permission, so if I don't give camera permission application need to be able to make call

### Configuration
**Operating system:** macOs Catalina 10.15.6

**Version of Telegram Desktop:** 2.3

**Comment by Merujan99** [comment]
I close this as it is duplicate.

**Comment by Merujan99** [comment]
Duplicate of #8430

**Comment by john-preston** [comment]
@Merujan99 Yeah, I'll need to fix that.
