### ISSUE TITLE
[Feature Request] Telegram Stories

### ISSUE THREAD

**Issue by FiberesimaJoseph** [telegramdesktop/tdesktop#8458]
### Is your feature request related to a problem?
Need  of newer features on telegram should be added

### Describe the solution you'd like
Need Telegram Stories  and status 

### Describe alternatives you've considered
telegram should consider added stories and status to the platform which will make it more proficient for users. 

### Additional context
<img width="341" alt="yu" src="https://user-images.githubusercontent.com/52601802/90639769-65857d00-e1ec-11ea-8a1f-ffbfa34b3c79.png">

![na](https://user-images.githubusercontent.com/52601802/90639481-f3ad3380-e1eb-11ea-8d03-c1aab76140ca.png)

**Comment by FiberesimaJoseph** [comment]
if this is done i believe telegram will do much more better that some other social media platform.

**Comment by RememberTheAir** [comment]
Related platform-wise suggestion: https://bugs.telegram.org/c/83
