### ISSUE TITLE
[Feature Request] Hide that separate call window

### ISSUE THREAD

**Issue by fcore117** [telegramdesktop/tdesktop#8459]
Please allow permanently hiding that separate call window like it was before, very distracting and disrupts work.

Telegram 2.3.0

**Comment by fcore117** [comment]
> Try this?
> https://postimg.cc/1V1mHJS4

Sorry but i do not mean this but i want to hide call main window completley and only keep chat window with small call bar on top of it.

Want call only be here like it was before 2.3
![old_way](https://user-images.githubusercontent.com/1313813/91050862-f367ca80-e627-11ea-91c3-e7f3f8b36ba3.PNG)

Ghost tray when minimizing, bug?
![tray](https://user-images.githubusercontent.com/1313813/91050874-f6fb5180-e627-11ea-810a-8be275a9b463.PNG)

**Comment by tormit** [comment]
I'm having the same annoiyng UI bug. Telegram 2.3.1, Windows 10 Pro.

**Comment by KES777** [comment]
old interface looks better

**Comment by fcore117** [comment]
Reverted back to good working 2.2 and using until i can close window without closing call.

**Comment by fcore117** [comment]
Latest Telegram 2.4.1 and still cannot get rid of that separate window, again i have to revert to older that have no separate window when calling. Very distracting.

**Comment by john-preston** [comment]
@fcore117 Why not simply minimize it? 🤔

**Comment by fcore117** [comment]
> @fcore117 Why not simply minimize it? 🤔

I need only Telegram main window when in conversation just like older ones and call status is running on top of Telegram itself, i exchange files and stuff in telegram and i do not need second useless window there. I reverted to older already and waiting until option or fix will arrive.

**Comment by john-preston** [comment]
@fcore117 I don't understand why you can't minimize the "second useless window", it will minimize to taskbar and you will "exchange files and stuff in telegram", like before.

**Comment by tormit** [comment]
Problem is not the window itself, but the ghost tray slot. It just taking up useful tray space and is really disturbing work.
Also, when you accidentaly close it, call is canceled.

**Comment by KES777** [comment]
@john-preston Why I should spent time to create useless second window and why users also should spent time to  minimize it? Also, as noticed by others, this second useless window makes useless noise by taking space in status bar.

Also this second useless window has poor design in compare how call is made in old version. Even more the useless window with poor design has no photo of user which I am calling. I <3 when calling window have photo

**Comment by Serverkill** [comment]
+1. 
This pointless separate call window is making me crazy, please take time to remove this or atleast make it optional if someone should for some (weird) reason really like it.

Thanks! I really hope you can make it the simple way it used to be.

**Comment by Noammac** [comment]
The second window makes alt-tabbing to Telegram more tedious, as well as navigating to it with Meta+Number. I get why it's useful for video calls, but allowing it to be closed and hidden in the program without ending the call (like the old window used to work), would still allow for that functionality without sacrificing user experience.

**Comment by fcore117** [comment]
There are second group of users too who use Telegram for hours on gaming or for basic calls and continue using other things same time but constantly hit that horrible window and close it and then call closes too. It should stay within Telegram window itself. Telegram is best of every IM app for every purpose, from work to gaming and even in industry as it is secure, comfortable and helluva fast thanks to C++

PS: If someone here wants to revert back to 2.2 then download 2.2, disconnect internet, launch telegram and disable updates then connect internet again and start using until fix comes. If you need video then sadly you have to endure secondary window.

Best solution would me move both Video and Audio to user chat window so it is one piece again.

**Comment by fcore117** [comment]
Anyone knows is 2.5.1 fixed that secondary ghost window hiding problem without call closing? Changelog talks about improvements but i am not sure.

**Comment by RememberTheAir** [comment]
> Anyone knows is 2.5.1 fixed that secondary ghost window hiding problem without call closing?

Not for 1-to-1 calls. For voice chats, on the other hand, you can close it without disconnecting from the voice chats

**Comment by fcore117** [comment]
> > Anyone knows is 2.5.1 fixed that secondary ghost window hiding problem without call closing?
> 
> Not for 1-to-1 calls. For voice chats, on the other hand, you can close it without disconnecting from the voice chat

Thanks for info, waiting until fix arrives and then i can finally upgrade too and keep voice conferencing and working without this distracting secondary window.

**Comment by Helderjfl** [comment]
> Problem is not the window itself, but the ghost tray slot. It just taking up useful tray space and is really disturbing work.
> Also, when you accidentaly close it, call is canceled.

Yeah, that's really annoying. I keep accidentally closing the call because its expected to be able to close the window, and only closing the call when clicking on hang up button.

**Comment by Lordvader81** [comment]
It's been two years since this feature request was opened! Why hasn't it been addressed? As paying users of the premium service, we'd appreciate a response from the developers, something that makes us feel like progress is being made, at the very least. While I acknowledge the various aesthetic updates and features implemented during this time, this particular request is a quality-of-life improvement that requires immediate attention!

**Comment by fcore117** [comment]
Progress should not made against people like this horrible call window. Same thing is with disabling Stories especially in phones. In short, please do not plan any more annoying features and-OR give option instantly with together with feature to disable it. Avoid excessive bloating up Telegram as it is only sane C++ communication tool left in world where lazy programmers make Nodejs and Electron bloat apps everywhere. Pretty please for disable option, and still thanks to all because of being written right way.

**Comment by Lordvader81** [comment]
No comments from the devs ??????????????

**Comment by 23rd** [comment]
Feel free to test v4.15.3.

**Comment by fcore117** [comment]
> Feel free to test v4.15.3.

Changelog do not mention hiding call window like it was old times? hidden feature?

**Comment by tormit** [comment]
Finally!
