### ISSUE TITLE
mov,mp4,m4a,3gp,3g2,mj2 formats  crackle

### ISSUE THREAD

**Issue by TheMaxMur** [telegramdesktop/tdesktop#8460]
### Steps to reproduce
1. start telegram-desktop on terminal
2. play video or music.m4a
3. check your terminal

### Expected behaviour
Telegram play video/music without crackles

### Actual behaviour
Music and video playing with crackles, it's infuriates

### Configuration
**Operating system: Kali Linux 2020.3**

**Version of Telegram Desktop: 2.2**

**Installation source (Linux Only):  distribution package**

<details><summary><b>Logs</b>:</summary>
maxmur@mbox:~$ telegram-desktop </br>
error: : cannot open</br>
error: : cannot open</br>
error: : cannot open</br>
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x7f2b9c004f00] Packet corrupt (stream = 0, dts = 5349376).</br>
[mp3 @ 0x7f2b98004d80] Estimating duration from bitrate, this may be inaccurate</br>
Invalid return value 0 for stream protocol</br>
Invalid return value 0 for stream protocol</br>
</details>

**Comment by ilya-fedin** [comment]
Can you reproduce on the official binary?

**Comment by TheMaxMur** [comment]
> Can you reproduce on the official binary?

from the site? I testing, situation not change.

**Comment by ilya-fedin** [comment]
> from the site?

yes

> I testing, situation not change.

Are you sure that the problem is not with the soundtrack that you trying to listen or with sound card drivers?

**Comment by TheMaxMur** [comment]
> > from the site?
> 
> yes
> 
> > I testing, situation not change.
> 
> Are you sure that the problem is not with the soundtrack that you trying to listen or with sound card drivers?

yes, in other devices this tracks sound normal. When i change sound card this situation not change.

**Comment by ilya-fedin** [comment]
> yes, in other devices this tracks sound normal.

What about other tracks? The track might be mailformed and then it wouldn't play in all apps (and then this is not a tdesktop issue).

> When i change sound card this situation not change.

Well, you can have all sound cards on your system affected. You should check this by playing something with other application.

**Comment by TheMaxMur** [comment]
> What about other tracks? The track might be malformed and then it wouldn't play in all apps (and then this is not a tdesktop issue).
mp3 tracks play normal.
> Well, you can have all sound cards on your system affected. You should check this by playing something with other application.
In other apps music playing goof (spotify, browser)

**Comment by ilya-fedin** [comment]
> mp3 tracks play normal.

Well, if you're saying that only one track doesn't playing, then this is an issue with this track and not with tdesktop.

**Comment by TheMaxMur** [comment]
> Well, if you're saying that only one track isn't playing, then this is an issue with this track and not with tdesktop.

m4a formats tracks playing not correctly. Video playing not correctly

**Comment by ilya-fedin** [comment]
> Video playing not correctly

All mp4 videos playing correctly for me

**Comment by TheMaxMur** [comment]
> All mp4 videos playing correctly for me

You use kali 2020.3? Can test this on virtual machine

**Comment by ilya-fedin** [comment]
> You use kali 2020.3?

No

> Can test this on virtual machine

I have Debian in a VM which Kali based on and it plays videos perfectly.

**Comment by TheMaxMur** [comment]
> I have Debian in a VM which Kali is based on and it plays videos perfectly.

I can record video for you

**Comment by ilya-fedin** [comment]
> I can record video for you

Let's record

**Comment by TheMaxMur** [comment]
> Let's record

Hmm, on video this problem can't hear

**Comment by ilya-fedin** [comment]
Then problem is on audio drivers level

**Comment by TheMaxMur** [comment]
> Then problem is on audio drivers level

Hm, in other apps sound normal, maybe problem in some depends?

**Comment by ilya-fedin** [comment]
> maybe problem in some depends?

I don't understand this question.

**Comment by TheMaxMur** [comment]
> I don't understand this question.

sorry, miss, maybe problem in some dependencies?

**Comment by ilya-fedin** [comment]
> maybe problem in some dependencies?

If problem can be reproduce only on live playing and can't be reproduced on record of the playing, then something wrong with alsa drivers for your sound card or pulseaudio processes something wrong. There are a lot of problems with mixing of stream in drivers for professional usb audio cards. If you have that one, then problem 100% in kernel audio drivers.

**Comment by TheMaxMur** [comment]
> > maybe problem in some dependencies?
> 
> If the problem can be reproduced only on live playing and can't be reproduced on record of the playing, then something wrong with alsa drivers for your sound card or pulseaudio processes something wrong. There are a lot of problems with mixing of stream in drivers for professional usb audio cards. If you have that one, then problem is 100% in kernel audio drivers.

Ok, I use usb sound card, how i can solve this problem?

**Comment by ilya-fedin** [comment]
> Ok, I use usb sound card, how I can solve this problem?

pray for kernel developers to fix the bug or buy a simple PCI audio card

**Comment by TheMaxMur** [comment]
> pray for kernel developers to fix the bug or buy a simple PCI audio card (or change OS)

Can we continue this issue in other place? (telegram chat)

**Comment by ilya-fedin** [comment]
There are t.me/TelegramDesktopTalk at telegram
