### ISSUE TITLE
[Feature Request] Toggle off global search

### ISSUE THREAD

**Issue by AntonVonDelta** [telegramdesktop/tdesktop#8461]
### Is your feature request related to a problem?
Global search results - no disable option in settings.

### Describe the solution you'd like
A disable button in the settings.

### Describe alternatives you've considered
There's no alternative

### Additional context
I don't think I am the only one with a small friend list. When I search for a word I would like to search it in my conversations and not Global Search which at a distance seems to be spam-filled.
I know there are many more important things to be done but the beauty of telegram are the small things.

**Comment by RememberTheAir** [comment]
Just open the chat -> click on the lens near the three dots menu (or CTRL + F)

**Comment by AntonVonDelta** [comment]
True but what about searching in all conversations? From what I see there is no way to disable global search. This is very inconvenient for me. If I were to add the functioanality in the Advanced Settings would the changes be added to the base?
