### ISSUE TITLE
[Feature Request] Space to write in captions

### ISSUE THREAD

**Issue by meiko87** [telegramdesktop/tdesktop#8465]
### Is your feature request related to a problem?
When I add a caption to a picture, the space to write don't expand, making difficult to edit the text.

![caption](https://user-images.githubusercontent.com/66200725/90752428-aa3a1280-e2d7-11ea-9b0f-86fbd4a52c90.png)

### Describe the solution you'd like
I will like to have more space. At least like when you are writing a text. That let you see 12 lines of text

**Comment by ilya-fedin** [comment]
#5122
