### ISSUE TITLE
Can't change camera on Surface tablet for video call

### ISSUE THREAD

**Issue by Moldoteck** [telegramdesktop/tdesktop#8468]
### Steps to reproduce
Call somebody with video. Default camera is rear camera, but there is no option to switch to front camera, like on phones

### Expected behaviour
There should be a button for switching camera sources
### Actual behaviour
There is no button for switching camera sources and this make video call unusable on desktop windows tablets

### Configuration
Windows 10, Surface Go
Tg version 2.3

<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/8452
