### ISSUE TITLE
option to save all photo or media shared in a chat

### ISSUE THREAD

**Issue by franciskittu** [telegramdesktop/tdesktop#847]
It could be a very useful feature to have an option to save all photos shared within a chat in your PC.

I think it is a need of many user to backup media shared in a chat on a PC because of constraints on phone memory, internet connection and archive pourpose.

Now, the only thing that one can do is to show every picture in full screen and then click "download" one by one that is very boring and time consuming.

Hope this could be easy to implement and useful to your project.

**Comment by auchri** [comment]
Duplicate #732
