### ISSUE TITLE
Unable to change Public group Share Link even when Available.

### ISSUE THREAD

**Issue by BittBurger** [telegramdesktop/tdesktop#8470]
### Steps to reproduce
1. I am owner of @icontraderslounge public group.
2. I take standard path to change share link:  Edit > Group Type
3. I change chare link and text says its "available".  
4. On mobile when I click "Done" it says "An error occurred.  Please try again later"
5. On Desktop when I click Done it allows this, but when I click "Save", nothing happens.  The name change wont take.

### Expected behaviour
If the name is "available" the share link should change and it should allow me to save.

NOTE:  The only "unique" thing here is that I as the owner have not been in the channel for several weeks and just returned about 2 hours ago.   Not sure if its limiting me because of this.  If so, exactly how long will I be limited?  I am not limited in any other way as Owner that I can tell.   

### Actual behaviour
See above.

### Configuration
IOS latest and Windows 10 latest.

**Version of Telegram Desktop:**
2.3
**Installation source (Linux Only)** - the official website / GitHub releases / flatpak / snap / distribution package:

**Used theme**:
Not relevant as it happens on multiple platforms.
<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by ilya-fedin** [comment]
Oh, it is better to ask in-app support, there are just tdesktop bugtracker.

**Comment by BittBurger** [comment]
Its been fixed just now!  Not sure why its working.  :)

**Comment by ilya-fedin** [comment]
![source](https://user-images.githubusercontent.com/17829319/90835153-5b25c900-e33b-11ea-9634-9a78a61468ab.gif)

Close the issue then :)
