### ISSUE TITLE
Calls stop to work and telegram crashes

### ISSUE THREAD

**Issue by KES777** [telegramdesktop/tdesktop#8472]
### Steps to reproduce
1. Just ask some one to call you
2. When incoming call occur telegram: crash or you just not hear

This occurs after upgrading telegram to version with video calls

### Expected behavior
Telegram should not crash

### Actual behavior
Telegram crash or I am not hear

### Configuration
Linux Mint 19.3

**Version of Telegram Desktop:**
2.3 (was 2.2 before upgrading)
Is this possible to downgrade telegram?

**Installation source (Linux Only)** - the official website / GitHub releases / flatpak / snap / distribution package:
update button in telegram

**Used theme**:
Default

<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>
Where I can get it? in my folder where telegram is installed `~/Apps/Telegram` I see only two files:
Telegram and Updater

**Comment by KES777** [comment]
[log.txt](https://github.com/telegramdesktop/tdesktop/files/5107754/log.txt)

I found =)

**Comment by KES777** [comment]
When crash occur I will send new `log.txt`

**Comment by KES777** [comment]
> You can download old versions from Github releases. Note that you have to disable auto-updating in app settings.

Yeah, I did that. That was very hard, because to login I need internet. When I log in it instantly updated to 2.3. I have no time to disable auto-upgrading.

So I quickly turnoff internet after logging in. It was complicated...

**Comment by malyshkin-vitali** [comment]
I have a cracking sound in system when the call starts in Telegram release with video calls. I use ArchLinux, the same in Ubuntu 20.04. I have the same bug with firefox and speech-dispatcher. Does anybody have the same?

**Comment by ilya-fedin** [comment]
> I have the same bug with firefox and speech-dispatcher.

I guess the bug is in pulse/alsa then

**Comment by malyshkin-vitali** [comment]
> > I have the same bug with firefox and speech-dispatcher.
> 
> I guess the bug is in pulse/alsa then

See https://bugs.launchpad.net/ubuntu/+source/speech-dispatcher/+bug/1736222

**Comment by ilya-fedin** [comment]
> See https://bugs.launchpad.net/ubuntu/+source/speech-dispatcher/+bug/1736222

Your link says that your bug is in pulse

**Comment by malyshkin-vitali** [comment]
> > See https://bugs.launchpad.net/ubuntu/+source/speech-dispatcher/+bug/1736222
> 
> Your link says that your bug is in pulse

I don't understand, why 2.2 version works fine (

**Comment by malyshkin-vitali** [comment]
I found some patch. See https://gitlab.freedesktop.org/pulseaudio/pulseaudio/-/issues/871
But I don't know how to use it. Can anybody help?

**Comment by ilya-fedin** [comment]
> Can anybody help?

I don't think so, this ticket has nothing to do with your issue.

**Comment by powerman** [comment]
I've same issue with 2.3.0 on Gentoo Linux with ALSA (no pulseaudio installed). 2.2.0 and previous works fine.
Log from stdout/stderr (since beginning of a call and crash):
```
D/tgvoip: === Updating voip config ===
D/tgvoip: {"enable_vp8_encoder":true,"enable_vp8_decoder":true,"enable_vp9_encoder":true,"enable_vp9_decoder":true,"enable_h265_encoder":true,"enable_h265_decoder":true,"enable_h264_encoder":true,"enable_h264_decoder":true,"audio_frame_size":60,"jitter_min_delay_60":2,"jitter_max_delay_60":10,"jitter_max_slots_60":20,"jitter_losses_to_reset":20,"jitter_resync_threshold":0.5,"audio_congestion_window":1024,"audio_max_bitrate":20000,"audio_max_bitrate_edge":16000,"audio_max_bitrate_gprs":8000,"audio_max_bitrate_saving":8000,"audio_init_bitrate":16000,"audio_init_bitrate_edge":8000,"audio_init_bitrate_gprs":8000,"audio_init_bitrate_saving":8000,"audio_bitrate_step_incr":1000,"audio_bitrate_step_decr":1000,"use_system_ns":true,"use_system_aec":true,"force_tcp":false,"jitter_initial_delay_60":2,"adsp_good_impls":"(Qualcomm Fluence)","bad_call_rating":true,"use_ios_vpio_agc":false,"use_tcp":false,"audio_medium_fec_bitrate":20000,"audio_medium_fec_multiplier":0.1,"audio_strong_fec_bitrate":7000}


#
# Fatal error in: ../../media/engine/adm_helpers.cc, line 39
# last system error: 0
# Check failed: 0 == adm->Init() (0 vs. -1)
# Failed to initialize the ADM.[1]    9281 abort      telegram-desktop
```

The workaround is to run `apulse telegram-desktop`, but please fix it and make it work without pulseaudio again, because apulse emulation isn't perfect and usually it breaks at some moment.

**Comment by ilya-fedin** [comment]
> Log from stdout/stderr (since beginning of a call and crash):

Please read prevoius messages about how to get a log.

**Comment by powerman** [comment]
@ilya-fedin Let me know if you'll need other logs too.

[last_call_log.txt](https://github.com/telegramdesktop/tdesktop/files/5180003/last_call_log.txt)

**Comment by ilya-fedin** [comment]
Looks like webrtc doesn't support auto fallback to ALSA, maybe ALSA should be defined as not supported officially :thinking:

**Comment by powerman** [comment]
I hope before making such a decision you'll take in account the fact a lot of people hate and try hard to avoid installing pulseaudio… and nearly all existing software works with ALSA just fine. (E.g. on my system right now only telegram needs apulse.)

**Comment by ilya-fedin** [comment]
> I hope before making such a decision you'll take in account the fact a lot of people hate and try hard to avoid installing pulseaudio…

> a lot

They are minorities, just like wayland lilbraries haters
