### ISSUE TITLE
windows link error: not found tg_owt.lib

### ISSUE THREAD

**Issue by IndiaZhangSan** [telegramdesktop/tdesktop#8475]
IDE:VS2019    
reference : https://github.com/telegramdesktop/tdesktop/blob/dev/docs/building-msvc.md
what should I do?

**Comment by ilya-fedin** [comment]
> what should I do?

give more info

**Comment by IndiaZhangSan** [comment]
> > what should I do?
> 
> give more info

Thank you
Has been resolved
