### ISSUE TITLE
[Question] What is the file with the name "8-byte hexstring + s" in "\Telegram\tdata"?

### ISSUE THREAD

**Issue by fresco305** [telegramdesktop/tdesktop#8476]
Hello!

What file exists in "\Telegram\tdata" with the name "8-byte hexstring + s"? Which part of the source code should I look for related information?

**Comment by ilya-fedin** [comment]
https://github.com/telegramdesktop/tdesktop/blob/d34eabdc111c9d8c1440c5b4dfe19884e854507e/Telegram/SourceFiles/storage/details/storage_file_utilities.cpp#L253-L255
