### ISSUE TITLE
Unable to use video calls on Arch Linux

### ISSUE THREAD

**Issue by jedi2light** [telegramdesktop/tdesktop#8478]
### Steps to reproduce
1. Open Telegram Desktop on Arch Linux
2. Start a call with some person / accept call from some person
3. Toggle a "Camera" button in order to achieve video call mode

### Expected behaviour
Not sure how it should work, but maybe I should see a person behind the call?

### Actual behaviour
Literally nothing happens.

### Configuration
Arch Linux x86_64 with latest updates

Telegram Desktop 2.3

Installed from repositories

Dark

**Comment by vitlav** [comment]
Check if your build used -DDESKTOP_APP_DISABLE_WEBRTC_INTEGRATION:BOOL=ON to disable WebRTC support.

**Comment by jedi2light** [comment]
https://github.com/archlinux/svntogit-community/blob/packages/telegram-desktop/trunk/PKGBUILD

**Comment by jedi2light** [comment]
There  is no such an flag

**Comment by malyshkin-vitali** [comment]
ArchLinux telegram 2.3.0 doesn't have a video calls, only a 2.3.1

**Comment by malyshkin-vitali** [comment]
Rename topic to Unable to use video calls on Linux. I ve tested in Ubuntu 20.04.

**Comment by jedi2light** [comment]
Looks strange...  Because after all, static build works.

**Comment by ilya-fedin** [comment]
I think this issue should be closed, since a packaging issue
