### ISSUE TITLE
Block/Disable Image Previews 

### ISSUE THREAD

**Issue by Dimtar** [telegramdesktop/tdesktop#848]
The desktop version of Telegram really needs a toggle switch for the disabling of inline image previews. When you are communicating with others you can never be sure if an image they send will be NSFW or NSFL. You can be viewing chats in a public place or an office or other place where certain images could be frowned upon or even grounds for dismissal.

The image preview is appealing as a feature but if people are avoiding chats because of the risk then that makes Telegram less fun and also less useful. People need a simple control mechanism to protect themselves from any un-wanted images. Having the user click images to load them in a reactive manner might be a better way for some users. AKA Load on demand.

**Comment by jamesrcotter** [comment]
Agreed. This feature would be very useful for when using Telegram as a workplace tool.

**Comment by Deemize** [comment]
+1
I use telegram at work for multiple reasons, this would be a much welcomed feature.

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/687#issuecomment-106904698

**Comment by armaganguven** [comment]
How can I use it? Also want to use for mobile.

**Comment by 23rd** [comment]
@armaganguven You can try to disable automatic media download.

**Comment by armaganguven** [comment]
> 
> 
> @armaganguven You can try to disable automatic media download.

This is the simplest method. Thanks.
