### ISSUE TITLE
Version 2.3.1 crashes on OSX 10.11

### ISSUE THREAD

**Issue by palehub** [telegramdesktop/tdesktop#8481]
Updated from v2.2 to v2.3.1 on OSX 10.11 (El Capitan).
App keeps crashing at start.

**Comment by palehub** [comment]
> @palehub Is there a folder with some .dmp files here:
> 
> ~/Library/Application Support/Telegram Desktop/tdata/dumps/completed
> 
> ? If there is, can you please .zip all of them together and attach them here?

Sorry. When I had those issues I deleted everything related with this app with CleanMyMac X, reinstalled (rolled-back) to  v2.2 and that is the one I'm using now.

I have downloaded it again, and v2.3.1 keeps crashing. Here I attach a .zip with two dumps after two crashes.

[completed.zip](https://github.com/telegramdesktop/tdesktop/files/5114585/completed.zip)

**Comment by aog2000a** [comment]
> Similar (possibly related, due to similarity between MacOS/Unix/Linux?) issue on KDE/Kubuntu 18.04 (and apparently 20.04 according to at least one other person).
> 
> On Kubuntu, i'm getting a complete desktop freeze on starting latest Telegram Desktop v2.3.1 which I've only been able to unfreeze by switching to a terminal and `killall`ing Telegram. I've tried deleting the `tdata` folder in `$HOME/.local/share/TelegramDesktop` (suspecting some incompatibility in there), but that didn't get the job done.
> 
> Only fix I've found to work thus far is to downgrade to the most recent previous available Telegram Desktop download I can find (v2.1.22.beta).

Same here on Debian buster. I had to downgrade from 2.3.1 since unusable

**Comment by Aokromes** [comment]
> > Similar (possibly related, due to similarity between MacOS/Unix/Linux?) issue on KDE/Kubuntu 18.04 (and apparently 20.04 according to at least one other person).
> > On Kubuntu, i'm getting a complete desktop freeze on starting latest Telegram Desktop v2.3.1 which I've only been able to unfreeze by switching to a terminal and `killall`ing Telegram. I've tried deleting the `tdata` folder in `$HOME/.local/share/TelegramDesktop` (suspecting some incompatibility in there), but that didn't get the job done.
> > Only fix I've found to work thus far is to downgrade to the most recent previous available Telegram Desktop download I can find (v2.1.22.beta).
> 
> Same here on Debian buster. I had to downgrade from 2.3.1 since unusable

linux version must be fixed on 2.3.2

**Comment by blooalien** [comment]
> linux version must be fixed on 2.3.2

Can confirm that on *my* Kubuntu 18.04 system at least, v2.3.2 is indeed running without issue.

@palehub — Can confirm same for Mac?

**Comment by palehub** [comment]
> > linux version must be fixed on 2.3.2
> 
> Can confirm that on _my_ Kubuntu 18.04 system at least, v2.3.2 is indeed running without issue.
> 
> @palehub — Can confirm same for Mac?

No. I can not see any Telegram v2.3.2 binary for OSX 10.11

**Comment by john-preston** [comment]
@palehub 2.3.2 only fixes a Linux problem, OS X problem is not related to that.

**Comment by john-preston** [comment]
@palehub Can you contact me at t.me/preston so I could send you a test version to see if it works.

**Comment by aog2000a** [comment]
> linux version must be fixed on 2.3.2

2.3.2 is also fixed on Debian 10/Buster + KDE. Thanks @john-preston

**Comment by Aokromes** [comment]
plz stop spamming linux here, the linux ticket is already closed because fixed.

**Comment by aog2000a** [comment]
> plz stop spamming linux here, the linux ticket is already closed because fixed.

Sorry @Aokromes  ... you should have replied with the "linux ticket" number when @blooalien posted about Ubuntu the first time, that would have avoided all the "spam".

**Comment by blooalien** [comment]
> > plz stop spamming linux here, the linux ticket is already closed because fixed.
> 
> Sorry @Aokromes ... you should have replied with the "linux ticket" number when @blooalien posted about Ubuntu the first time, that would have avoided all the "spam".

Agree.  My apologies also @palehub for derailing his original Mac-related issue.  My bad.  I made the mistake of thinking it sounded like a related issue.

**Comment by norbekaiser** [comment]
> Updated from v2.2 to v2.3.1 on OSX 10.11 (El Capitan).
> App keeps crashing at start.

I'm on OSX 10.15.6 (Catalina) Started without any noticeable Problems with Telegram Desktop 2.3.1

**Comment by john-preston** [comment]
@norbekaiser OS X 10.11 has a different build, I hope to fix it in the next release.

**Comment by palehub** [comment]
> @norbekaiser OS X 10.11 has a different build, I hope to fix it in the next release.

It seems you have fixed it. V2.3.2 working good on my OSX 10.11 now. Thanks.

**Comment by palehub** [comment]
@john-preston It seems you have fixed it. V2.3.2 working good on my OSX 10.11 now. Thanks.
