### ISSUE TITLE
Screen Flickering

### ISSUE THREAD

**Issue by daniel-lucio** [telegramdesktop/tdesktop#8482]
With the following PC setup:
- Linux
- Video card AMD Radeon R9 290, doesn' t matter if using radeon or amdgpu module

Start X, start Telegram

### Expected behaviour
No flickering

### Actual behaviour
The screen start flickering, as soon as I close telegram the issue is gone.

### Configuration
**Operating system:**
5.7.14-desktop-1.mga7 #1 SMP Fri Aug 7 14:45:09 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
Xorg 1.20.8
Mageia 7

**Version of Telegram Desktop:**
2.3.1

**Installation source (Linux Only)** - the official website / GitHub releases / flatpak / snap / distribution package:
https://telegram.org/dl/desktop/

**Used theme**:

<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by robots4life** [comment]
This bug cost me at least a dozen reboots, uff..

**Comment by brandyn** [comment]
Do we have to download and install the update manually or can we just run Updater?  (I tried the latter and it just launched the broken/flickering version, but wondering if I just need to wait a bit and try again...)
