### ISSUE TITLE
Name overflows message bubble

### ISSUE THREAD

**Issue by d-Rickyy-b** [telegramdesktop/tdesktop#8488]
Using certain names leads to the name overflowing the message bubble.

![grafik](https://user-images.githubusercontent.com/5798157/90981660-a837b400-e562-11ea-8c39-b9effcd22470.png)

### Steps to reproduce
0. The issue was first spotted within [a group](https://t.me/BotTalk/318324)
1. Set your first name to 
`⃝⃝⃝⃝⃝⃝⃝⃝⃝⃝⃝⃝⃝⃝⃝⃝⃝⃝⃝⃝⃝⃝⃝⃝⃝⃝⃝⃝⃝⃝⃝⃝⃝⃝⃝⃝⃝⃝⃝⃝⃝⃝⃝⃝⃝⃝⃝⃝⃝⃝⃝⃝⃝⃝⃝⃝⃝⃝⃝⃝⃝⃝⃝⃝`
2. (optionally?) set your last name to
`ꠋꠋꠋꠋꠋꠋꠋꠋꠋꠋꠋꠋꠋꠋꠋꠋꠋꠋꠋꠋꠋꠋꠋꠋꠋꠋꠋꠋꠋ ꠋꠋꠋꠋꠋꠋꠋꠋꠋꠋꠋꠋꠋꠋꠋꠋꠋꠋꠋꠋꠋꠋꠋꠋꠋꠋꠋ`

### Expected behaviour
The name will be truncated with ellipsis and stay within boundaries. 

### Actual behaviour
The name overflows the message bubble (see screenshot above)

### Configuration
**Operating system:** Windows 10 Version 2004 (Build 19041.450)

**Version of Telegram Desktop:** 2.3.1

**Installation source (Linux Only)** - the official website

**Used theme**: Any / Not relevant for the issue

<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by d-Rickyy-b** [comment]
The issue still persists

**Comment by ilya-fedin** [comment]
#6416
