### ISSUE TITLE
Windows desktop version 2.3.1 always crash

### ISSUE THREAD

**Issue by yayan19** [telegramdesktop/tdesktop#8491]
### Steps to reproduce
1. Uninstall existing version
2. Install new version 2.3.1
3. Open telegram desktop
4. Enter Login code
5. Enter Cloud password

### Expected behaviour
Open the telegram window

### Actual behaviour
Always crash.
Tried using Unigram for Windows and no issue.

### Configuration
**Operating system:**
Windows 10 Professional 2004

**Version of Telegram Desktop:**
2.3.1

**Used theme**:
Default

<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

[log.txt](https://github.com/telegramdesktop/tdesktop/files/5115738/log.txt)

**Comment by ilya-fedin** [comment]
> log.txt

Looks like you don't have access to the data folder

```
[2020.08.24 10:59:44] Storage Error: Could not open 'C:/Users/[username]/AppData/Roaming/Telegram Desktop/tdata/D877F783D5D3EF8C/configs' for writing.
[2020.08.24 10:59:44] Storage Error: Could not open 'C:/Users/[username]/AppData/Roaming/Telegram Desktop/tdata/D877F783D5D3EF8C/config0' for writing.
[2020.08.24 10:59:45] Storage Error: Could not open 'C:/Users/[username]/AppData/Roaming/Telegram Desktop/tdata/D877F783D5D3EF8C/configs' for writing.
[2020.08.24 10:59:45] Storage Error: Could not open 'C:/Users/[username]/AppData/Roaming/Telegram Desktop/tdata/D877F783D5D3EF8C/config0' for writing.
```

**Comment by yayan19** [comment]
The user has all the permission checked. Please see attached images.

![2020-09-21_09-00-43](https://user-images.githubusercontent.com/9264473/93728231-35653b80-fbe9-11ea-955b-90b2ddd19dd4.png)

Also, the folders are shown as Files by Windows, so I can't go and check the subfolders.

![2020-09-21_08-59-50](https://user-images.githubusercontent.com/9264473/93728241-41e99400-fbe9-11ea-9af5-3392d7dbc143.png)

**Comment by ilya-fedin** [comment]
> The user has all the permission checked.

> Permissions for SYSTEM

This can't be your user (until you hacked entire your system and if this is true, this is a problem with your system rather than with Telegram)

**Comment by ilya-fedin** [comment]
> Also, the folders are shown as Files by Windows, so I can't go and check the subfolders.

It can't open D877F783D5D3EF8C, while on your screenshot D877F783D5D3EF8C**s** is shown

**Comment by yayan19** [comment]
Yes, but I can't find D877F783D5D3EF8C folder. It's supposed to be created by the Telegram, right?
I already enable "Show hidden folders".

![2020-09-21_10-07-22](https://user-images.githubusercontent.com/9264473/93730514-300cee80-fbf3-11ea-8141-e900d8f6fb32.png)

I also tried created the D877F783D5D3EF8C folder and /configs and /config0 subfolders manually but still get the same errors.

**Comment by ilya-fedin** [comment]
> Yes, but I can't find D877F783D5D3EF8C folder. It's supposed to be created by the Telegram, right?

Yes, but I guess tdesktop can't create them since you're using the SYSTEM account

**Comment by yayan19** [comment]
No, I use my own user, but it has Administrators rights. I also installed it using that user (tried uninstall/reinstall). The screenshot display SYSTEM because it was selected. If I selected my username, it has the same rights/permissions.

**Comment by ilya-fedin** [comment]
Well, you need to check permissions on the tdata folder rather than on files in it to check why the folder couldn't be created

**Comment by yayan19** [comment]
So, I just tried using the portable version and extracted the files inside C:\Users\[username]\Telegram..
Still got the same errors.

The permission is okay I think..

![image](https://user-images.githubusercontent.com/9264473/93732144-3d79a700-fbfa-11ea-8c21-984e30a301d7.png)

**Comment by ilya-fedin** [comment]
> So, I just tried using the portable version and extracted the files inside C:\Users[username]\Telegram..

Maybe some sandbox or antivirus software prevent Telegram to create the folder?

**Comment by yayan19** [comment]
I already disabled the antivirus software (BitDefender 2020), but no effect. 

When I first unzip the portable version, it only contain 1 Telegram.exe, without any other files/folders.
But, on the first run it CAN create many files, folders and subfolders (../tdata, ../tdata/dumps, ../tdata/emoji, etc), except those D877F783D5D3EF8C, etc which is shown by Windows as D877F783D5D3EF8C**s**.

**Comment by yayan19** [comment]
I tried using the 2.3.0 and 2.2.0 versions, but it seems Telegram is automatically downloading and running the latest version. So it also get the same errors.

**Comment by ilya-fedin** [comment]
>  which is shown by Windows as D877F783D5D3EF8C**s**

It is not shown by Windows that way, it is just other file

**Comment by ilya-fedin** [comment]
> I already disabled the antivirus software (BitDefender 2020), but no effect.

Something is definitely prevent Telegram to create the folder

**Comment by ilya-fedin** [comment]
> I tried using the 2.3.0 and 2.2.0 versions, but it seems Telegram is automatically downloading and running the latest version. So it also get the same errors.

You can check version in the log

**Comment by yayan19** [comment]
> 
> Something is definitely prevent Telegram to create the folder

Hmm.. usually if the antivirus is blocking the creation of folders/files it will log the event. But there's no such events.

Here's the log for 2.2.0
[log.txt](https://github.com/telegramdesktop/tdesktop/files/5253465/log.txt)

And 2.3.0
[log.txt](https://github.com/telegramdesktop/tdesktop/files/5253468/log.txt)

In the firs line it shows (or similar):

> Launched version: 2003000, install beta: [FALSE], alpha: 0, debug mode: [FALSE]

But later it seems loading the updated version (CMIIW):

> Update Info: Starting loading 'D:/Software/Internet/tportable.2.3.0/Telegram/tupdates/tupdate2003001' from 0 offset.
> Update Info: Loading using HTTP from 'https://updates.tdesktop.com/tsetup/tupdate2003001'.

**Comment by ilya-fedin** [comment]
> Hmm.. usually if the antivirus is blocking the creation of folders/files it will log the event. But there's no such events.

I've seen situations when antivirus doesn't log it actions. It could be something other in the end.

> But later it seems loading the updated version (CMIIW):

But logs are still from older versions, tdesktop rewrites log on restart

This confirms that source of the problem is outside telegram

**Comment by yayan19** [comment]
Just want to update here. Installed the new version 2.4.0 and Telegram can run successfully. No other changes made.
