### ISSUE TITLE
Does WebRTC used for video call reveal real IP of user even if using VPN/Proxy ? [Question] 

### ISSUE THREAD

**Issue by Nokia808** [telegramdesktop/tdesktop#8492]
Hi. As the title saying.

We were waiting for video call feature to be added for Telegram. But we see that it depend on WebRTC protocol which is dangerous unless it treated in specific way. WebRTC unhide real user IP even if using VPN/Proxy ! It need special implementation so that not leaking real IP. For example, on Firefox there is an add-on "uBlock Origin" has an option to prevent WebRTC from reveal real user IP if she/he using WebRTC. Currently, I'm using this option of "uBlock Origin" when I make video conference using Jitsi from within Firefox .....

What about new feature in Telegram, taking in mind Telegram has proxy setting so it is unbelievable to has feature break other feature within it !

Thank you.

**Comment by john-preston** [comment]
@Nokia808 You can turn off the p2p in settings, then no IPs would be revealed, even without VPN/proxy.

**Comment by Nokia808** [comment]
@john-preston 
There is no such option "p2p" ! I searched under "advanced" & under "Privacy & security" & under other section but did not find "p2p" option ! I'm on Linux & installed Telegram desktop from FlatHub.

**Comment by RememberTheAir** [comment]
@Nokia808 settings -> privacy & security -> voice calls. At the bottom of the widget there's a peer-to-peer option

**Comment by Nokia808** [comment]
@RememberTheAir 
I see it. Thank you.

But @john-preston @RememberTheAir  this is only a harsh workaround ! I mean - please correct to me if wrong - in the version before implementation video call feature when user use VPN or proxy & enable p2p connection then the VPN or proxy IP will be revealed but not real IP. But after implementation of video call feature then using p2p connection will reveal real IP even if using VPN or proxy ... Do you see the downside ? Before video calls, p2p was did not reveal real IP IF USER USE VPN OR PROXY, but after video calls now p2p reveal real IP IF USING VPN OR PROXY. 

My point is that Telegram should treat this problem so that using video call while p2p is enabled will reveal the VPN or proxy IP if user use VPN or proxy instead of heir/his real IP. This will be better from enforce user to use Telegram servers & causing further decrease in quality of connection beyond that resulted from using VPN or proxy .....

Is is now suitable to change label of this issue from "Question" to "Bug" or "Feature request" ?

**Comment by john-preston** [comment]
@Nokia808 I honestly have no idea if the behavior regarding revealing of the IP behind VPN / proxy has changed, it should be tested by someone.

**Comment by ilya-fedin** [comment]
> Before video calls, p2p was did not reveal real IP IF USER USE VPN OR PROXY

Are you sure? libtgvoip used pieces of webrtc, I guess that IP detection mechanism is the same.
