### ISSUE TITLE
telegram desktop (V2.3.2) keeps showing my phone number (linux mint)

### ISSUE THREAD

**Issue by freemangilgamesh** [telegramdesktop/tdesktop#8494]
even if i tell telegram to not show my number to anyone, it keeps showing it no matter what. (OS: Linux Mint)

**Comment by RememberTheAir** [comment]
How do you know? This report lacks a lot of information to understand what's the issue with your phone number

**Comment by freemangilgamesh** [comment]
i set it to hide my phone number but my chatmates still can see my number and so d I

**Comment by Aokromes** [comment]
if they already have your phone number it won't be hidden.

**Comment by PeterMX** [comment]
> i set it to hide my phone number but my chatmates still can see my number and so d I

the app shows you this message _"Users who have your number saved in their contacts will also see it on Telegram"_ so not a bug
