### ISSUE TITLE
Storage Error causes system crash

### ISSUE THREAD

**Issue by EugeneLesnov** [telegramdesktop/tdesktop#8495]
### Steps to reproduce
1. Using Telegram Desktop binaries for Linux 64-bit run ./Telegram
2. User does not have write rights to the directories (or subdirectories) /home/USER/.local/share/TelegramDesktop/
3. Telegram and shell (KDE in this particular case) freezes.

The first time I got this bug and the KDE stopped loading after rebooting the device.
I was able to load Linux with nosplash mode, to save my files and reinstall Debian.
After installing fresh Debian bug was there again. But after the crash, the shell was loaded and I was able to see the logs.

### Expected behaviour
Expected login process

### Actual behaviour
Freezes

### Configuration
OS: Debian GNU/Linux 10 (buster) x86_64
Kernel: 4.19.0-10-amd64
DE: KDE

Telegram Desktop v2.3.2

Installation source - the official website, binaries.

[log.txt](https://github.com/telegramdesktop/tdesktop/files/5119496/log.txt)

**Comment by ilya-fedin** [comment]
Sounds like a KDE bug rather then a Telegram bug
