### ISSUE TITLE
Video calls

### ISSUE THREAD

**Issue by damixxx** [telegramdesktop/tdesktop#8498]
On my Samsung Tablet GT-P3100
Android version 4.1.2
Core version 3.0.31-1084989

I have installed telegram version 7.0.1 (2065) arm-v7a

I don't have the option to initiate a video call. (Only normal call)

When I try (from another telegram account) from the Desktop app to initiate a video call to my tablet, I get message
the the app on my tablet does not support video calls and I have to update the app.

Where might be the problem. For an instance, I can make video calls with Viber, so the cameras on my tablet work.

**Comment by Aokromes** [comment]
this is for telegram desktop, not telegram android, anyway, android 4.3 or higher is needed for telegram android.
I sugest you to search for cyanogenmod or lineageos for your tablet.

**Comment by Aokromes** [comment]
You have updated lineageos builds here:
https://androidfilehost.com/?w=files&flid=209384&sort_by=date&sort_dir=DESC
