### ISSUE TITLE
License incompatible between GPLv3 and OpenSSL

### ISSUE THREAD

**Issue by czchen** [telegramdesktop/tdesktop#850]
According to [GNU document](https://www.gnu.org/licenses/license-list.html#OpenSSL), the GPLv3 is not compatible with OpenSSL. The license shall change to "GPLv3 with OpenSSL exception" or use GNUTLS instead of OpenSSL.

**Comment by wRAR** [comment]
Of course changing the license requires agreement of all contributors.
Also, currently distributing tdesktop binaries is illegal because of this issue.
