### ISSUE TITLE
[Question] How much of the public group chat history is available to new members?

### ISSUE THREAD

**Issue by azat11** [telegramdesktop/tdesktop#8501]
AFAIR it wasn't the whole history. If that's the case then it does not serve my purposes. I need it to be the whole history for all the members. And I never saw an option to somehow change that.

**Comment by RememberTheAir** [comment]
If a group is a supergroup: by default it's the whole history. There's an option to decide how much of the chat history to show the chat history to new members (all/none).

If the group is a normal group, as far as I know, it depends on the client from where the inviter invited the new member. If invited from telegram desktop, the new member will probably see the 100-300 most recent messages. The android app has an option to decide whether to show the most recent 100 messages or not. If the user joined via the invite link, I think he will see only the messages sent after the moment he joined

**Comment by RememberTheAir** [comment]
Also telegram for the love of god just fix your shit will all these small confusing differences between normal groups and supergroups. It's so confusing that I'm getting annoyed at people asking me why sometimes things work in a way and some other times not. It's been _years_ and I still have to keep a list in my saved messages of what works and what doesn't in normal/supergroups

**Comment by azat11** [comment]
> If a group is a supergroup: by default it's the whole history. There's an option to decide how much of the chat history to show the chat history to new members (all/none).

So I created a group, how do I know if it is a supergroup or a normal group?

**Comment by RememberTheAir** [comment]
@azat11 by default, when you create a chat, you create a normal group. There are some action, though, that will upgrade it to supergroup. [These](https://t.me/tgbeta/3424) are the actions that will trigger the conversion to supergroup. [These](https://github.com/telegramdesktop/tdesktop/issues/7961#issuecomment-638140256) are some details that can tell you whether your group is a normal group, or has already been converted to supergroup

**Comment by azat11** [comment]
@RememberTheAir So if I created a public group it is automatically a supergroup and the whole chat history will be available to each new member??

**Comment by RememberTheAir** [comment]
@azat11 yes, if you set a group username, it is now a supergroup. In supergroups, you can decide whether new members can see past messages or not

**Comment by azat11** [comment]
@RememberTheAir I have a private group where I can decide if the history is visible or hidden, and a public group where there's no such option appears (this public group has a custom link, which I suppose you mean by a username). What does this mean?

**Comment by RememberTheAir** [comment]
@azat11 in public groups (public =with an username) the chat history is always visible

**Comment by azat11** [comment]
> @azat11 in public groups (public =with an username) the chat history is always visible

@RememberTheAir But is it the whole history?? I need to test this.
Thanks a lot for the replies.

**Comment by RememberTheAir** [comment]
> But is it the whole history?? I need to test this.

Yes
