### ISSUE TITLE
Emoji in libnotify notification is wrong (one off in the list)

### ISSUE THREAD

**Issue by Photon89** [telegramdesktop/tdesktop#8502]
### Steps to reproduce
1. Launch Telegram
2. Minimize it or put the window to background such that notifications are shown on new messages
3. Let a contact send a message including an emoji

### Expected behaviour
The emoji in the notification should be the same as in the message itself

### Actual behaviour
The emoji is wrong (looks like it is the neighbouring emoji to the correct one)

### Configuration
**Operating system:** Manjaro Linux

**Version of Telegram Desktop:** 2.2.0

**Installation source (Linux Only)** -  distribution package: https://github.com/archlinux/svntogit-community/commit/fe3e7f3102e38ba140e1b3ec2d116f019188debc#diff-8d0411b338c83cd8cd8ad9d9db127101

**Used theme**: Day

I can test version 2.3.1 as well, if necessary, please let me know!

**Comment by ilya-fedin** [comment]
1. libnotify is not used for native notifications
2. Telegram Desktop renders emojis with pixmaps, native notifications are displayed by your system and are using the system emoji font.

This is not a bug and tdesktop can't influence that. If you want Telegram emoji, you should use Telegram notifications that are controlled by Telegram.

**Comment by Photon89** [comment]
Thanks for the hint, indeed, for Telegram's own notifications the problem doesn't appear! However, in native notifications (which I'd prefer to use because they better fit into the desktop) it looks like the same font is used (at least the emojis look the same) but the displayed emoji is one off compared to the actually received one. Is it really a font issue or, possibly, something gets scrambled on the way to the notification bubble?

**Comment by ilya-fedin** [comment]
> it looks like the same font is used

Tekegran doesn't use fonts to display emojis, Telegram uses pixmaps.

> Is it really a font issue or, possibly, something gets scrambled on the way to displaying the notification bubble?

If there something gets scrumbling, it should be on DE side.
