### ISSUE TITLE
White-red-white flag of Belarus

### ISSUE THREAD

**Issue by m1e20** [telegramdesktop/tdesktop#8503]
### Steps to reproduce
1. Put two or more (red-green) flags of Belarus (from emoji) as a separate message.

### Expected behaviour
I expect them to be displayed in white-red-white colors as it takes place with a single flag.

### Actual behaviour
The flags are kept intact

### Configuration
Android, Linux, iOS

**Version of Telegram Desktop:**
2.3.2 installed from github

**Used theme**:

<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by malyshkin-vitali** [comment]
I think it's not a bug. (I'm Belarusian)
