### ISSUE TITLE
Search on Google feature 

### ISSUE THREAD

**Issue by iqfareez** [telegramdesktop/tdesktop#8504]
### Is your feature request related to a problem?
No. 

### Describe the solution you'd like
It would be great if there is option for 'Search on Google'

### Describe alternatives you've considered
I know I can just copy and paste to search on my web browser. However, I'm a bit of lazy ass person.

### Additional context (refer screenshot below)
For example, I've selected the word `laravel`, then I right-click on it so that it opens the context menu. 
What I'm talking about is adding `Search 'laravel' on Google` option in between the options there.

Thank you and please consider this feature.

![image](https://user-images.githubusercontent.com/60868965/91268774-7adc4780-e7a8-11ea-9a53-6a654695f711.png)

**Comment by MintBoy97** [comment]
im a beginer in this repository, i will see what can i do

**Comment by curious0101** [comment]
This option is totally unnecessary for all the people for doesn't use Google, like me.

**Comment by Aokromes** [comment]
> This option is totally unnecessary for all the people for doesn't use Google, like me.

nothing forces you to use it.

**Comment by curious0101** [comment]
> > This option is totally unnecessary for all the people for doesn't use Google, like me.
> 
> nothing forces you to use it.

It would clutter right click menu for EVERY user, with proprietary search engine which censors websites, countries and people. Seems like a st*pid move.
