### ISSUE TITLE
Crashing with XWayland 1.20.9

### ISSUE THREAD

**Issue by alosarjos** [telegramdesktop/tdesktop#8506]
### Steps to reproduce
1. Install latest XWayland/Xorg Packages (Or just have an updated Arch install)
2. Login with a wayland session
3. Run the app

### Expected behaviour
The app should open

### Actual behaviour
App crashes

### Configuration
**Operating system:** Arch Linux / Gnome 3.36.5 on Wayland

**Version of Telegram Desktop:** 2.3.2

**Installation source (Linux Only)** - The Official site

**Used theme**: Default

While I could blame latest Xorg update for this, other apps using XWayland (VScode, Brave, Chromium, Steam) are working fine. So maybe there is something here?

**UPDATE**: Getting this output when launching from Terminal:

```
error: : cannot open
error: : cannot open
error: : cannot open
The X11 connection broke (error 2). Did the X11 server die?
```

The `log.txt` is not showing anything related to the crash.

**Comment by abdulocracy** [comment]
Prepending `QT_QPA_PLATFORM=wayland` to the command seems to make it launch, but there are mouse cursor issues.

**Comment by alosarjos** [comment]
> Prepending `QT_QPA_PLATFORM=wayland` to the command seems to make it launch, but there are mouse cursor issues.

While this is true. It's not a environment variable that is enabled by default on most cases. For now most of Arch users on Gnome that use Telegram Desktop will start having issues. But since this XWayland update is a minor update it will probably end up on another distributions soon.

**Comment by abdulocracy** [comment]
> Prepending `QT_QPA_PLATFORM=wayland` to the command seems to make it launch, but there are mouse cursor issues.

My cursor issues are fixed by using `XCURSOR_SIZE=24`.

**Comment by Tids** [comment]
Official Telegram was able to create a report.telegramcrash

```
./Telegram
Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
Telegram-Message: 20:59:06.964: You can disable tray icon counter with TDESKTOP_DISABLE_TRAY_COUNTER and make it look better if it is monochrome.
error: : cannot open
error: : cannot open
error: : cannot open
The X11 connection broke (error 2). Did the X11 server die?
```

[report.telegramcrash.log](https://github.com/telegramdesktop/tdesktop/files/5132268/report.telegramcrash.log)

**Comment by Taijian** [comment]
OK, I can confirm that using `env QT_QPA_PLATFORM=wayland XCURSOR_SIZE=24` allows Telegram to launch and function normally.

**Comment by ilya-fedin** [comment]
> While I could blame latest Xorg update for this, other apps using XWayland (VScode, Brave, Chromium, Steam) are working fine.

None of them are Qt applications. You should check other Qt applications.

**Comment by alosarjos** [comment]
> > While I could blame latest Xorg update for this, other apps using XWayland (VScode, Brave, Chromium, Steam) are working fine.
> 
> None of them are Qt applications. You should check other Qt applications.

You are right! It's happening with the Android Emulator too (The only QT app that I remember having)... Will see if this is reported somewhere else...

**Comment by ilya-fedin** [comment]
> Will see if this is reported somewhere else...

Since Qt version can't be changed on its own in static binary, the problem should be in GNOME

**Comment by alosarjos** [comment]
My bad. The Android Emulator crash was coming from something else. Launching the emulator like this:

`QT_QPA_PLATFORM="" emulator -avd 29 -noaudio`

Works nicely.

PD: The emulator still returns this message: 

`emulator: INFO: QtLogger.cpp:68: Info: Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway. ((null):0, (null))`

**Comment by gavrilyak** [comment]
telegram-desktop  2.1.7 works with both wayland 1.20.9 and 1.20.8
telegram-desktop   2.2.0, 2.3.0 and 2.3.2 works with wayland 1.20.8 but crashes on 1.20.9

**Comment by Tids** [comment]
@ilya-fedin same problem is with sway. The problem looks for me either on xwayland/xorg or Qt/telegram site of things.
 
Nextcloud, Qt-Designer/Assist/Linguist, OBS, Calamares (all Qt apps I have installed) do work with xwayland 1.20.9.

**Comment by ilya-fedin** [comment]
I have no idea why it may crash with XWayland :man_shrugging:

**Comment by malyshkin-vitali** [comment]
I have the same problem. ArchLinux. System is up-to-date

**Comment by kaseiwang** [comment]
I reverted https://github.com/freedesktop/xorg-xserver/commit/5c20e4b834145f590c68dbc98e33c7d3d710001a and telegram works again. But I'm not sure which part of codes should be fixed.

**Comment by ilya-fedin** [comment]
> I reverted [freedesktop/xorg-xserver@5c20e4b](https://github.com/freedesktop/xorg-xserver/commit/5c20e4b834145f590c68dbc98e33c7d3d710001a) and telegram works again.

This commit makes XWayland crash somehow when tdesktop asks xcb-screensaver probably
https://github.com/telegramdesktop/tdesktop/blob/d34eabdc111c9d8c1440c5b4dfe19884e854507e/Telegram/SourceFiles/platform/linux/specific_linux.cpp#L301-L334

I don't know why it crashes just on a request and how to fix it however.

**Comment by alosarjos** [comment]
I reported this on the Xorg Gitlab, they seem to be looking into it based on the info gathered here. You probably want to keep an eye on it too.

https://gitlab.freedesktop.org/xorg/xserver/-/issues/1072

Hoping this helps.

**Comment by bananapoweruser** [comment]
> 
> 
> Prepending `QT_QPA_PLATFORM=wayland` to the command seems to make it launch, but there are mouse cursor issues.
Being a noob, I wonder where I can edit this command?

**Comment by qelix** [comment]
> > Prepending `QT_QPA_PLATFORM=wayland` to the command seems to make it launch, but there are mouse cursor issues.
> 
> Being a noob, I wonder where I can edit this command?

They're environment variables you can define in a lot of places. The most straightforward way is to just prepend your command with them. Enter the following in your terminal:

``
QT_QPA_PLATFORM=wayland XCURSOR_SIZE=24 telegram-desktop
`` 

If you want a more permanent solution, you may want to edit your .desktop file for Telegram. I don't know whether it's DE specific, but for GNOME it's under `/usr/share/applications/telegramdesktop.desktop`. Then, edit the line containing `Exec=` like so:

``
Exec=env QT_QPA_PLATFORM=wayland XCURSOR_SIZE=24 telegram-desktop -- %u
``

For me, this messes up the full screen image gallery however, so you'll probably want to change it back when the issue is resolved.

**Comment by tiagobugarin** [comment]
> `Exec=env QT_QPA_PLATFORM=wayland XCURSOR_SIZE=24 telegram-desktop -- %u`
> 
> For me, this messes up the full screen image gallery however, so you'll probably want to change it back when the issue is resolved.

It also messes with support for special characters like `á` and `õ` used in latin languages.
For now I am running my Gnome session with X11 and Telegram runs correctly as far as I could see.

**Comment by renaldofreire** [comment]
Same error here.

**Comment by dupondje** [comment]
I've debugged this a bit further, and it seems like its the following call that causes the segfault:
```        const auto cookie = xcb_screensaver_query_info(connection, screen->root);
```

If we skip this, it works fine!

**Comment by ilya-fedin** [comment]
XWayland devs did something really weird if just an query crashes the whole app

**Comment by dupondje** [comment]
It prints the following in debug btw:
`qt.qpa.xcb: xcb_shm_create_segment() failed for size 1920000`

**Comment by ilya-fedin** [comment]
Doesn't tell anything to me

**Comment by ilya-fedin** [comment]
Can anyone check if the issue is reproducible on dev branch?

**Comment by dupondje** [comment]
@ilya-fedin: seems to work fine! (just replaced the specific_linux.cpp in 2.3.2 with the one from dev branch btw)

**Comment by bananapoweruser** [comment]
> 
> 
> > > Prepending `QT_QPA_PLATFORM=wayland` to the command seems to make it launch, but there are mouse cursor issues.
> > 
> > 
> > Being a noob, I wonder where I can edit this command?
> 
> They're environment variables you can define in a lot of places. The most straightforward way is to just prepend your command with them. Enter the following in your terminal:
> 
> `QT_QPA_PLATFORM=wayland XCURSOR_SIZE=24 telegram-desktop`
> 
> If you want a more permanent solution, you may want to edit your .desktop file for Telegram. I don't know whether it's DE specific, but for GNOME it's under `/usr/share/applications/telegramdesktop.desktop` (it also depends on how you installed Telegram). Then, edit the line containing `Exec=` like so:
> 
> `Exec=env QT_QPA_PLATFORM=wayland XCURSOR_SIZE=24 telegram-desktop -- %u`
> 
> For me, this messes up the full screen image gallery however, so you'll probably want to change it back when the issue is resolved.

Thank you for clarifying. For me, this does absolutely nothing tho, telegram still crashes after I enter the login code.

**Comment by ilya-fedin** [comment]
The fixed version from dev branch could be installed via snap edge channel
`snap install --edge telegram-desktop`

**Comment by ilya-fedin** [comment]
> https://gitlab.freedesktop.org/xorg/xserver/-/issues/1072

@alosarjos i think you can close that issue

**Comment by alosarjos** [comment]
> > https://gitlab.freedesktop.org/xorg/xserver/-/issues/1072
> 
> @alosarjos i think you can close that issue

Will ask them... While it can be fixed on this side. A "bugfixing" update shouldn't break apps.

I guess the fix will hit the beta channel instead of going directly to stable?

**Comment by ilya-fedin** [comment]
> A "bugfixing" update shouldn't break apps.

It was a bug in tdesktop, there wasn't a check if XScreenSaver is present, but it is mandatory.

> I guess the fix will hit the beta channel instead of going directly to stable?

I don't know :man_shrugging:, there are no plans for any releases yet

**Comment by velitasali** [comment]
FYI, downgrading to **2.1.7** worked for me on **ArchLinux**.

https://archive.archlinux.org/packages/t/telegram-desktop/telegram-desktop-2.1.7-2-x86_64.pkg.tar.zst

```sh
wget https://archive.archlinux.org/packages/t/telegram-desktop/telegram-desktop-2.1.7-2-x86_64.pkg.tar.zst
sudo pacman -U telegram-desktop-2.1.7-2-x86_64.pkg.tar.zst
```

ArchLinux version archive:
https://archive.archlinux.org/packages/t/telegram-desktop/

**Comment by alosarjos** [comment]
Since this is fixed I'm closing the issue. Thanks a lot to all of you who have helped figure out what was it. Hoping the bugfix is released soon.

**Comment by marcosps** [comment]
> The fixed version from dev branch could be installed via snap edge channel
> `snap install --edge telegram-desktop`

@ilya-fedin  Do you plan to release the dev branch into the flathub's beta channel? Thanks

**Comment by ilya-fedin** [comment]
> Do you plan to release the dev branch into the flathub's beta channel?

No, it is only for beta releases
