### ISSUE TITLE
[bug] Not answering call (hang pressed) - will close tdesktop if no main window opened

### ISSUE THREAD

**Issue by kirsan31** [telegramdesktop/tdesktop#8507]
### Steps to reproduce
1. Enable sys tray icon in settingts.
2. Close main window.
3. Make a call to yourself (from someone other acc) .
4. Press hung (red button) on call window.

### Expected behaviour
tdesktop remain running in sys tray.

### Actual behaviour
tdesktop exit.

### Configuration
Win 7 and 10.

**Version of Telegram Desktop:**
2.3.1+

**Comment by ilya-fedin** [comment]
#8442
