### ISSUE TITLE
Locationgroups - Coordinate links open to GMaps without warning

### ISSUE THREAD

**Issue by AngryLasagna** [telegramdesktop/tdesktop#8510]
### Steps to reproduce
1. Create location based group
2. Set location
3. Click locationlink in groupinfo

### Expected behaviour
Integrated Mapview opens (where at least some builds replaced the map with osm)

### Actual behaviour
It links straight to the google maps website.

### Configuration
Fedora 32 x86_64
**Version of Telegram Desktop:**
2.2
**Installation source (Linux Only)** - the official website / GitHub releases / flatpak / snap / distribution package:
Fedora RPMFusion
**Used theme**:
Tinted
<details>Logs are unneccessary here. This is an unexpected privacy risk. Yes I know this sounds weak but there is a specific case where it matters. 
</details>

**Comment by ilya-fedin** [comment]
#6789
