### ISSUE TITLE
There's no sounds during video/audio call

### ISSUE THREAD

**Issue by metkram** [telegramdesktop/tdesktop#8511]
### Steps to reproduce
1. Got video call update 2.3
2. Use external audio interface Focusrite 2i4 with Samson c03 mic

### Expected behaviour
When I call to someone or get call from someone I have to hear him/her and they have to hear me

### Actual behaviour
There is no sounds during video/audio call, but I can listen to and send audio messages

### Configuration
**Operating system:**
Windows 10 Pro N 1903

**Version of Telegram Desktop:**
2.31

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/8443
