### ISSUE TITLE
Telegram-desktop crash

### ISSUE THREAD

**Issue by Arup65** [telegramdesktop/tdesktop#8514]
Telegram desktop version 2.3.2-1 on fresh install of Arch Gnome Wayland crashes the moment verification code is entered.

**Comment by Aokromes** [comment]
try with the version downloaded from releases.
https://github.com/telegramdesktop/tdesktop/releases

**Comment by Arup65** [comment]
Thanks for your reply but its the same version that is on Arch.

**Comment by Aokromes** [comment]
arch is 2.3.2-1 the -1 means it's distribution only build

**Comment by ilya-fedin** [comment]
> Thanks for your reply but its the same version that is on Arch.

No, it isn't.

**Comment by Arup65** [comment]
Just tried the 64bit binary and same story, on entering the verification code it crashes right away.

**Comment by ilya-fedin** [comment]
send crash report tag

**Comment by Arup65** [comment]
`The X11 connection broke (error 2). Did the X11 server die?`

This is the message I get.

**Comment by ilya-fedin** [comment]
#8506

**Comment by Arup65** [comment]
Thank you so I will wait for future upgrades to Wayland for Telegram desktop to function.

**Comment by ilya-fedin** [comment]
> Thank you so I will wait for future upgrades to Wayland for Telegram desktop to function.

Usually such issues are fixing on Qt level. What means it would take months.

**Comment by Arup65** [comment]
Yes its more of a Gnome Wayland issue so I will report it to Gnome as well as use Telegram with the suffix, its working fine with that.

**Comment by ilya-fedin** [comment]
Suffix? :thinking:

**Comment by Arup65** [comment]
Sorry prefix env QT_QPA_PLATFORM=wayland XCURSOR_SIZE=24
