### ISSUE TITLE
button pressed while typing number with bot

### ISSUE THREAD

**Issue by giuseppeM99** [telegramdesktop/tdesktop#8515]
I was using a bot with a reply keyboard and had to send a message, when i enter a number a keyboard button gets pressed.
### Steps to reproduce
1.  Open a bot with reply keyboards
2.  Type a number

### Expected behaviour
The numbers goes in the message i'm writing

### Actual behaviour
A button gets pressed and the number doesn't go in the message
![immagine](https://user-images.githubusercontent.com/8383704/91566752-68971080-e944-11ea-9670-5497775bfa3a.png)

### Configuration
**Operating system:**
Linux 5.7.9-1-MANJARO

**Version of Telegram Desktop:**
2.3.2 (beta enabled)

**Installation source (Linux Only)** - the official website

**Comment by ilya-fedin** [comment]
What numbers are you talking about?

**Comment by giuseppeM99** [comment]
in that specific bot 1 - 3 (each click the respective 3 buttons in the first row)

**Comment by ilya-fedin** [comment]
> in that specific bot 1 - 3 (each click the respective 3 buttons in the first row)

I can't parse that, I don't understand what the problem is...

**Comment by RememberTheAir** [comment]
You activated one of the hidden modes that allow you to use reply keyboards with numbers. One of those hidden stuff that you activate by typing something in the settings screen. I don't remember the name

**Comment by Aokromes** [comment]
not a bug?

**Comment by giuseppeM99** [comment]
not a bug lol
