### ISSUE TITLE
[Bug/Regression] Long chat logs can't be deleted directly on both sides

### ISSUE THREAD

**Issue by Protonator** [telegramdesktop/tdesktop#8516]
### Steps to reproduce

1.) Use "Delete chat" or "Clear history" on an old and long chat history and mark "Also delete for (other contact)"
2.) Exit Telegram Desktop
3.) Restart Telegram Desktop
4.) The chat log of the contact appears again and was not completely deleted

### Expected behaviour

The chat log should be completely vanished on both sides.

### Actual behaviour

I recently tried to delete the chat logs of all my Telegram Desktop contacts on both (!) sides. It worked flawlessly with the exception of two of my oldest contacts. The chat logs with them reached way back to 2016. When I tried to delete the logs on both sides (no matter if I use "Delete chat" or "Clear history"), it seems to work on first sight, but after I restart the client, the logs were back again. Clearing the local storage/cache didn't help.

I examined this further and saw that "Delete chat" or "Clear history" sometimes deleted only around one month from the past and sometimes nothing. Then I had to manually delete some messages (up to 100 max) and use "Delete chat" or "Clear history" again until the whole chat history was finally gone. This was an exhausting pile of click work:

– Use "Delete chat" or "Clear history" on both sides
– Restart client
– Check if deletion worked or not by switching to the beginning of the chat calendar
– If not, delete 100 messages from the beginning manually
– Then use "Delete chat" or "Clear history" on both sides again
– Restart client
– …

It would be nice if this long known bug (there are closed bug reports from 2016) could finally getting fixed on client or server side (or again if it's a new regression).

### Configuration
**Operating system:** Windows 10 Pro x64 Version 2004

**Version of Telegram Desktop:** 2.3 and 2.3.1

**Comment by ilya-fedin** [comment]
>  on client or server side

This is a client side only bugtracker, no one here forwards issues to server developers

> Clearing the local storage/cache didn't help.

tdesktop doesn't have local storage, it requests all data from server at start.

**Comment by Protonator** [comment]
> tdesktop doesn't have local storage, it requests all data from server at start.

No, it does. Look under "Settings -> Advanced -> Data and storage -> Manage locale storage".

**Comment by ilya-fedin** [comment]
> No, it does.

No, it doesn't.

> Look under "Settings -> Advanced -> Data and storage -> Manage locale storage".

It's just media cache. There are no storage for chat data and etc.

**Comment by Protonator** [comment]
> It's just media cache. There are no storage for chat data and etc.

Sure, but it perhaps could've been a workaround for the problem. That's why I tried and mentioned it.
