### ISSUE TITLE
Video calling and screen sharing

### ISSUE THREAD

**Issue by draklowell** [telegramdesktop/tdesktop#8518]
### Steps to reproduce
1. Open Telegram
2. Try to video call some

### Expected behaviour
I would like to be able to video call people and screen share with them like Hangouts, Slack, Discord, etc.

### Actual behavior
I can only send recorded video clips and use audio in calls, with no support for video calling.

### Reason
I am trying to get my friends to adopt Telegram for it's great features in other areas. They say they need video calling support. I don't absolutely need it right now, but IMO it should be a priority at this point.

It would make Telegram a lot more competitive and speed up adoption. I would assume that internally this is discussed a lot more heavily, but an updated roadmap or call for developers would help provide some transparency.

### P.S
It is copy of https://github.com/telegramdesktop/tdesktop/issues/4270, but in 2020 in telegram there is video calls

**Comment by ilya-fedin** [comment]
Video calls are there, what the point of this issue?

**Comment by malyshkin-vitali** [comment]
Is it trolling?

**Comment by ilya-fedin** [comment]
no

**Comment by malyshkin-vitali** [comment]
I asked the reporter.
