### ISSUE TITLE
Maximised Telegram Desktop blocks access to auto-hidden taskbar on Windows

### ISSUE THREAD

**Issue by nofishonfriday** [telegramdesktop/tdesktop#8519]
Steps to reproduce
1. Enable "Auto-hide the taskbar" in Windows
2. Maximise Telegram Desktop via the 'maximise' button in the top right
3. Hover the mouse where the taskbar usually appears

### Expected behaviour
The taskbar should appear

### Actual behaviour
The taskbar doesn't appear

### Configuration
**Operating system:**
Win 8.1

**Version of Telegram Desktop:**
2.3.1

**Used theme**:
default

**Summary:**
When Telegram Desktop is maximised and the Windows taskbar is set to "automatically hide the taskbar" in the taskbar settings, T D stops the taskbar from appearing when the mouse is moved to the bottom of the screen, stopping access to other running applications/shortcuts.

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/3579
