### ISSUE TITLE
Telegram-WARNING: possible Qt, Gtk and Font issues

### ISSUE THREAD

**Issue by renaldofreire** [telegramdesktop/tdesktop#8521]
### Steps to reproduce
Open telegram desktop on arch linux.

### Expected behaviour
Application should open normally.

### Actual behaviour
It closes without even starting.

### My OS
Arch Linux x86_64 with with DE Gnome.

**Version of Telegram Desktop:**
telegram-desktop 2.3.2-1

**Installation source (Linux Only)** - the official website / GitHub releases / flatpak / snap / distribution package: Community Repo in Arch Linux [here](https://www.archlinux.org/packages/community/x86_64/telegram-desktop/).

**Used theme**:
Dracula.

<details><summary><b>Logs</b>:</summary>
<pre>(process:6580): Telegram-<font color="#FFB86C"><b>WARNING</b></font> **: <font color="#8BE9FD">02:29:23.337</font>: Unfortunately, GTK integration conflicts with qgtk2 platformtheme and style. Therefore, QT_QPA_PLATFORMTHEME and QT_STYLE_OVERRIDE will be unset.
Telegram-<font color="#50FA7B"><b>Message</b></font>: <font color="#8BE9FD">02:29:23.339</font>: This can be ignored by setting TDESKTOP_I_KNOW_ABOUT_GTK_INCOMPATIBILITY environment variable to any value, however, if qgtk2 theme or style is used, this will lead to a crash.
Telegram-<font color="#50FA7B"><b>Message</b></font>: <font color="#8BE9FD">02:29:23.339</font>: GTK integration can be disabled by setting TDESKTOP_DISABLE_GTK_INTEGRATION to any value. Keep in mind that this will lead to clipboard issues and tdesktop will be unable to get settings from GTK (such as decoration layout, dark mode &amp; more).

(process:6580): Telegram-<font color="#FFB86C"><b>WARNING</b></font> **: <font color="#8BE9FD">02:29:23.339</font>: Application was built without embedded fonts, this may lead to font issues.
Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
Telegram-<font color="#50FA7B"><b>Message</b></font>: <font color="#8BE9FD">02:29:23.427</font>: You can disable tray icon counter with TDESKTOP_DISABLE_TRAY_COUNTER and make it look better if it is monochrome.
Fontconfig error: &quot;/etc/fonts/conf.d/75-noto-color-emoji.conf&quot;, line 1: no element found
error: : cannot open
error: : cannot open
error: : cannot open
The X11 connection broke (error 2). Did the X11 server die?
</pre>
</details>

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/8506
