### ISSUE TITLE
No accelerated colorspace conversion found from yuv420p to bgra. Aborted (core dumped)

### ISSUE THREAD

**Issue by sunjam** [telegramdesktop/tdesktop#8523]
`Version 2.3` on `5.8.3-2-MANJARO-ARM` on Pinebook Pro running KDE Plasma

### This has been a constant problem with Telegram-desktop on the Pinebook Pro.
1. Access any Telegram room with a Sticker
2.  Telegram crashes 

```
$ telegram-desktop
Icon theme "gnome" not found.

** (telegram-desktop:39677): WARNING **: 10:31:32.817: Error loading plugin: libnuspell.so.3: cannot open shared object file: No such file or directory

QTextCursor::setPosition: Position '8388607' out of range
QTextCursor::setPosition: Position '8388607' out of range
  OpenType support missing for "Open Sans", script 11
[swscaler @ 0xffff44039f60] No accelerated colorspace conversion found from yuv420p to bgra.
Aborted (core dumped)
```

**Comment by ilya-fedin** [comment]
This is a ffmpeg bug, it is workarounded by disabling neon optimizations in official snap builds. No one here can help with third-party builds.

**Comment by sunjam** [comment]
@ilya-fedin this bug does break telegram-desktop entirely.  Is it possible to disable Sticker support within telegram-desktop in order to mitigate the crashes?

**Comment by Aokromes** [comment]
> @ilya-fedin this bug does break telegram-desktop entirely. Is it possible to disable Sticker support within telegram-desktop in order to mitigate the crashes?

i suggest you to download official telegram desktop from releases.

**Comment by ilya-fedin** [comment]
> i suggest you to download official telegram desktop from releases.

There are no ARM binaries, only snap package

> Is it possible to disable Sticker support within telegram-desktop in order to mitigate the crashes?

No, the only way to wrokaround them is to build ffmpeg without neon optimizations. Even without stickers the bug will affect all other media.
