### ISSUE TITLE
Add subtitles for voice messages

### ISSUE THREAD

**Issue by inferrna** [telegramdesktop/tdesktop#8525]
Please, dublicate voice messages with auto recognized subtitles. It may be implemented as usual text message with 🔊 ("listen") button
It needeed for:
1. Easy voice chat history overview
2. For ones, who temporally unable to listen

**Comment by ilya-fedin** [comment]
There are bots for this

**Comment by inferrna** [comment]
Bots has some disadvantages.
1. It's insecure.
2. Requires to do a lot of actions: find a bot, add it to each conversation, etc
3. Each message come and notify twice - with voice and text
4. Most users have no idea about bots

**Comment by ilya-fedin** [comment]
I guess this should be server-side, but this tracker only fro client-side issues.

**Comment by RomanJos** [comment]
When we will have local speech recognition it would be great to have the word appear as they are said on the recipient's phone

**Comment by DevAlone** [comment]
@ilya-fedin it doesn't have to be server side, it's easy to implement on the client

**Comment by DevAlone** [comment]
Agree that bots aren't a solution, I don't want to send friends' messages to a random untrusted bot.

**Comment by ilya-fedin** [comment]
> it doesn't have to be server side, it's easy to implement on the client

Never seen a quality multilingual opensource voice engine

**Comment by DevAlone** [comment]
But server side can be easier since Telegram has a lot of clients

**Comment by ilya-fedin** [comment]
> But server side can be easier since Telegram has a lot of clients

It's the only way actually, since developers of official clients doesn't have right to implement features on their own afaik.

**Comment by RememberTheAir** [comment]
@DevAlone there are three possible solutions:

- Telegram finds a quality multilingual opensource voice speech recognition engine, which, as of now, as ilya said, we don't have any afaik
- Telegram makes use of some third-party service (possibly with a reputation and mission similar to theirs'), with all the related issues (costs, third-party failures, risk of the service being bought by Facebook or Microsoft & co (see Giphy))
- Telegram develops its own speech recognition engine, which is a really complex task and likely needs some quality dedicated engineers working on it to produce a competitive outcome

All these three solutions don't seem to be really viable for Telegram

**Comment by inferrna** [comment]
@RememberTheAir 
There is fourth possible solution: SpeechRecognizer on Android devices and SFSpeechRecognizer on iOS. It may be something like optional recognition on receiver side: if receiver wants to see text, there would be special button 🅃 for it.

**Comment by ilya-fedin** [comment]
> There is fourth possible solution: SpeechRecognizer on Android devices and SFSpeechRecognizer on iOS. It may be something like optional recognition on receiver side: if receiver wants to see text, there would be special button 🅃 for it.

You are in tdesktop bugtracker

**Comment by DevAlone** [comment]
@RememberTheAir, telegram can go with some decent engine or just something that works at least most of the time instead of not having the feature at all

**Comment by Aokromes** [comment]
such feature belongs to https://bugs.telegram.org/
