### ISSUE TITLE
No option to auto toggle dark mode in Linux.

### ISSUE THREAD

**Issue by pedrofleck** [telegramdesktop/tdesktop#8526]
### Steps to reproduce
- Open settings > chat settings.

### Expected behaviour
I expect to have an option to enable auto toggle of dark mode based on OS settings.

### Actual behaviour
The option to auto toggle is missing.

### Configuration
**Operating system:**
Fedora 32
**Version of Telegram Desktop:**
2.2
**Installation source (Linux Only)**
RPM Fusion for Fedora 32
**Used theme**:
Default

**Comment by ilya-fedin** [comment]
RPM Fusion maintainer disables GTK integration that is required for auto night mode, not a tdesktop bug.
