### ISSUE TITLE
WebRTC missing when compiling Telegram Desktop on Windows

### ISSUE THREAD

**Issue by kkouptsov** [telegramdesktop/tdesktop#8527]
I am trying to compile Telegram Desktop for Windows following these instructions:
https://github.com/telegramdesktop/tdesktop/blob/dev/docs/building-msvc.md

However, when running configure.bat to create Telegram.sln, I am getting an error from CMake:

```
CMake Error in Telegram/CMakeLists.txt:
  Imported target "external_webrtc" includes non-existent path
```

Indeed, `webrtc` component is not mentioned in the instructions at all, so it is indeed missing. Furthermore, when I simply check out WebRTC using:

```
git clone https://webrtc.googlesource.com/src webrtc/src
```

I still get an error:

```
  Imported target "external_webrtc" includes non-existent path
    "Z:/TelegramBuild/Libraries/webrtc/src/third_party/abseil-cpp"
```

so it seems to be missing more than that.

What is the proper way of dealing with these errors?

**Comment by john-preston** [comment]
@kkouptsov You need to be sure the tg_owt was built correctly.

**Comment by ilya-fedin** [comment]
> You need to be sure the tg_owt was built correctly.

I have a feel that he tries to build an old version with instructions for the latest version

**Comment by kkouptsov** [comment]
> > You need to be sure the tg_owt was built correctly. 
> I have a feel that he tries to build an old version with instructions for the latest version

I started from empty directories and simply follow the instructions. So, whatever gets checked out is being used.

**Comment by ilya-fedin** [comment]
You're told that you have this error:
> "Z:/TelegramBuild/Libraries/webrtc/src/third_party/abseil-cpp"

But cmake_helpers from the latest version has another path:
https://github.com/desktop-app/cmake_helpers/blob/9b1ed3965b836131fe08b1090a8b5788a04066b8/external/webrtc/CMakeLists.txt#L13

You're obviously trying to build an old version with latest instructions.

**Comment by kkouptsov** [comment]
> @kkouptsov You need to be sure the tg_owt was built correctly.

I went through all steps starting with empty directories, and got tg_owt build with no errors:
`-- Build files have been written to: Z:/TelegramBuild/Libraries/qt_5_12_8/tg_owt/out/Release`

Should tg_owt be inside qt directory,`Libraries\qt_5_12_8\tg_owt\`, or in the Libraries, `Libraries\tg_owt\` ?

**Comment by john-preston** [comment]
@kkouptsov 

![image](https://user-images.githubusercontent.com/17900494/92093249-2f4b1e80-ede4-11ea-9d8c-d7494f986dbc.png)

If I understand correctly, here you should get `tg_owt` folder in `Libraries` (which is correct), not in `qt_5_12_8`. Looks like you didn't `cd ..` from `qt_5_12_8` after `jom install`.
