### ISSUE TITLE
[Feature Request]  Anonymity in groups 

### ISSUE THREAD

**Issue by olo81** [telegramdesktop/tdesktop#8529]
### Is your feature request related to a problem?
I have a work group and I would like it to be more anonymous. It happens that someone will make a screen and send the message along with the sender's identification data.

### Describe the solution you'd like
Adding an option in the group so that, even though we have someone, the contact from the telegram is displayed in the contacts and not from the contact book.
Option to disable avatars in the group.
And the most interesting thing would be to completely animate the users of the group, so that despite the fact that we have contact in the book, it is not known who it is. So the ability to set a separate nickname in the silence and no access to the group user's data even if we have him in contacts.
Option to disable taking screenshots

### Describe alternatives you've considered
Any of the features that improve anonymity to be an option

**Comment by Aokromes** [comment]
this looks api side to me.

**Comment by Aokromes** [comment]
such feature belongs to https://bugs.telegram.org/
