### ISSUE TITLE
A way to get last sent message inside "Write a message.." box

### ISSUE THREAD

**Issue by abderrahmane-tj** [telegramdesktop/tdesktop#853]
Hi there, this is not an issue, more like asking if the feature exists, and if not, would it be possible to have this feature ? Just like pressing [Up] on a terminal.

This could help with bots, instead of rewriting /start /wolfram /stop /cancel manually, having a shortcut to get the last message that has been sent.

Thank You.

**Comment by auchri** [comment]
Added to #1060
