### ISSUE TITLE
[Question] Export chat history

### ISSUE THREAD

**Issue by Learner-Victor** [telegramdesktop/tdesktop#8533]
Telegram export chat history， it will read and display 100 200 ... and so on when you export a exact day. But i found that some telegram can run 100 200 ... with a fast speed,  other can run with a slow speed.

for example, I create a telegram desktop II folder and put the telegram.exe into it for running another telegram account. 

Telegram A: 100 . 200 . 300 . 400 . and so on
Telegram B: 100 ... 200 ... 300 ... 400 ... and so on
'.' means read quickly. Telegram A takes only 18 seconds to read 10000 messages.
'...' means read slowly. Telegram B  takes 34 seconds to read 10000 messages.

Please tell me how to keep a fast read speed to export history.

**Comment by Learner-Victor** [comment]
![image](https://user-images.githubusercontent.com/46842998/91912159-21fb3a80-ece5-11ea-8967-30c313251f32.png)
And i don't know why telegram A can remain the previous operation records but telegram B not.

**Comment by ilya-fedin** [comment]
> Please tell me how to keep a fast read speed to export history.

I guess there is no way if this happens without any system

**Comment by Learner-Victor** [comment]
> > Please tell me how to keep a fast read speed to export history.
> 
> I guess there is no way if this happens without any system

Sorry, i found that all of telegram keep a slow speed when export history today, maybe it happens by accident.
When the speed keep slow and fast, i will record the screen and feedback.

**Comment by ilya-fedin** [comment]
> maybe it happens by accident

most likely

**Comment by Learner-Victor** [comment]
![8uu76-eie1t](https://user-images.githubusercontent.com/46842998/92019176-c5e9f200-ed88-11ea-82a3-1b03d381e4b3.gif)
export the same group  history, with different read speed.

**Comment by ilya-fedin** [comment]
And? :thinking:

**Comment by Learner-Victor** [comment]
> And? 🤔

I think it may depend on which Data Center the telegram account belong and which agency you choose.
I am sorry to bother you.
Thanks.
