### ISSUE TITLE
[Feature Request] User-created chats with himself (notes)

### ISSUE THREAD

**Issue by offstate** [telegramdesktop/tdesktop#8536]
### Is your feature request related to a problem?
Now we have only one Saved Messages chat, I need several on different topics - todo-lists, work and personal specific questions and so on.

### Describe the solution you'd like
I managed to create groups with only one member (me). This is almost what is needed. I just cannot edit my messages for unlimited time and I receive some group-specific dialogs.
It will be great to create several chats like Saved Messages

**Comment by RememberTheAir** [comment]
You should create a channel instead of a group. Administrators there can edit messages with no time limit

**Comment by offstate** [comment]
Thank you, I'll use it
