### ISSUE TITLE
Bad window placement when using windows tablet mode

### ISSUE THREAD

**Issue by razorness** [telegramdesktop/tdesktop#8540]
### Steps to reproduce
1. Install Telegram Desktop on Windows 10 machine with touchscreen
2. Use Windows Tablet Mode regularly

### Expected behaviour
The window should always fit perfectly in fullscreen of windows tablet mode

### Actual behaviour
The window does not fit windows fullscreen/display screen randomly. Sometimes the input box is out of screen, sometimes the application window is placed very weird out of screen and does only fit some part of the screen.
This happens very often after an update of telegram desktop.
It is difficult to number how often this happens, sometimes it works for weeks, sometimes it happens twice a day.

A workaround is to leave tablet mode, click on maximize/resize button a few times and enter tablet mode again.

### Configuration
**Operating system:**
Windows 10 x64 Home 2004 (Build 19041.450) with Windows Feature Experience Pack 120.2212.31.0

**Version of Telegram Desktop:**
Telegram Desktoüp v2.3.1

**Installation source (Linux Only)** - the official website / GitHub releases / flatpak / snap / distribution package:
Installed version from official website to achieve autostart on windows logon.

**Used theme**:
Default.

**Comment by ilya-fedin** [comment]
That means that you screen is too small for tdesktop window

**Comment by Aokromes** [comment]
you may want to try to use smaller scalling (if you are using 100% use command line to get 90% or less)

**Comment by razorness** [comment]
Are you sure? We are talking about this hardware: [HP ENVY X360 - 13-ar0003ng](https://support.hp.com/us-en/document/c06302701/) with 1080p display at 13.3" and system wide scaling set to 125 % (1,536 x 864 pixels).
So, if the app works perfectly except the case it is resetting, recalculating any window related stuff, you really think, the display resolution and scaling is the problem? I would think, the app has a minor problem which could drive old or unexperienced user crazy by requested repetitive and intransparent tasks: leave tablet mode, click resize/maximize couple of times, enter tablet mode again.

What is the minimum resolution needed by the desktop client?

Here is photo made by an user:

![image](https://user-images.githubusercontent.com/684302/92267815-94386e80-eee1-11ea-9d6f-5151ecadd280.png)

**Comment by ilya-fedin** [comment]
> Here is photo made by an user:

Oh, the text explanation was very unclear :(

Looks like #3705, is this nVidia Surround?

**Comment by razorness** [comment]
The notebook has only its integrated AMD Radeon Vega 6 graphics card with AMD Ryzen 3 3300U CPU.

I doubt, this problem is related to windows tablet mode. More often, the app window is as large as or larger as the whole screen and not recognizing the taskbar, so the input field is hidden by taskbar. Switching to desktop mode and resizing/maximizing fixes the app window until it reaches this state again. For me it looks like it's related to tasks within app updates.

**Comment by ilya-fedin** [comment]
I have no idea what can cause this behavior :man_shrugging:

**Comment by razorness** [comment]
Thank you for your feedback. 

Do I need to enable debug mode as described [here](http://tsfkb.wikidot.com/tips:tdesktop:debug) to collect log entries made in
https://github.com/telegramdesktop/tdesktop/blob/dev/Telegram/SourceFiles/window/main_window.cpp#L374 ?
May it will help, when I am able to gather some log output. These logs will be available in `%appdata%\Telegram Desktop`, right?

**Comment by ilya-fedin** [comment]
I don't think that app logs will help, something is wrong with rendering

**Comment by john-preston** [comment]
@razorness Does it still happen in tablet mode? I've fixed the screen size at least at launch in the middle of January.
