### ISSUE TITLE
Core Dump on Image Paste

### ISSUE THREAD

**Issue by shtirlic** [telegramdesktop/tdesktop#8542]
### Steps to reproduce
1. Copy image from Chrome 
2. Paste to to TG chat

### Expected behaviour
Paste working normal

### Actual behaviour
Crash woth core dump

### Configuration
**Operating system:**
Clear Linux latest

**Version of Telegram Desktop:**
2.3.2

**Installation source (Linux Only)** - the official website / GitHub releases / flatpak / snap / distribution package:
flatpak

**Used theme**:

<details><summary><b>Logs</b>:</summary>

Process 47083 (telegram-deskto) of user 1000 dumped core.

Stack trace of thread 2:
#0  0x000055925fc3bcd2 n/a (/app/bin/telegram-desktop.bin + 0x1a4acd2)
#1  0x000003fe0000021b n/a (n/a + 0x0)

</details>

**Comment by ilya-fedin** [comment]
#8509

**Comment by shtirlic** [comment]
While I understand that is upstream chrome project bug, so why TG desktop is core dumping?

**Comment by ilya-fedin** [comment]
No idea, something is wrong on the toolkit level
