### ISSUE TITLE
Send file or photo

### ISSUE THREAD

**Issue by Learner-Victor** [telegramdesktop/tdesktop#8544]
It seems that send 1920*18 size image could not send as a photo

**Comment by Aokromes** [comment]
cannot reproduce on 2.3.1 under windows 10.

**Comment by Learner-Victor** [comment]
> cannot reproduce on 2.3.1 under windows 10.

yes, what i mean is that image which is small like 1920*18, it could not send as a photo, but if it is bigger , it could send as photo and file.
![image](https://user-images.githubusercontent.com/46842998/92147244-6b669980-ee4d-11ea-83d8-a6be318226d9.png)

![image](https://user-images.githubusercontent.com/46842998/92147296-7f120000-ee4d-11ea-8bde-e7badc89c741.png)

**Comment by ilya-fedin** [comment]
> It seems that send 1920*18 size image could not send as a photo

Yeah, you can't since it doesn't fix in the limit and this is not a bug

**Comment by Learner-Victor** [comment]
ok, my fault
