### ISSUE TITLE
error when compiling tg_owt on Windows

### ISSUE THREAD

**Issue by sudo-jonathan** [telegramdesktop/tdesktop#8545]
I am trying to compile Telegram Desktop for Windows and when I want to compile tg_owt I get an error...

### Expected behaviour
error when compiling tg_owt

### Actual behaviour
c++  , ninja error

### Configuration
**Operating system:** Windows 10

**Version of Telegram Desktop:** 2.3.2

**Installation source (Linux Only)** - GitHub releases
**Gcc Version:** - gcc version 8.3.0 (x86_64-posix-seh, Built by strawberryperl.com project)

<details><summary><b>Logs</b>:</summary>
F:\Telegram\Libraries\tg_owt\out\Debug>cmake -G Ninja ^
More? -DCMAKE_BUILD_TYPE=Debug ^  <br>
More? -DTG_OWT_SPECIAL_TARGET=win ^ <br>
More? -DTG_OWT_LIBJPEG_INCLUDE_PATH=%cd%/../../../qt_5_12_8/qtbase/src/3rdparty/libjpeg ^<br>
More? -DTG_OWT_OPENSSL_INCLUDE_PATH=%cd%/../../../openssl_1_1_1/include ^<br>
More? -DTG_OWT_OPUS_INCLUDE_PATH=%cd%/../../../opus/include ^<br>
More? -DTG_OWT_FFMPEG_INCLUDE_PATH=%cd%/../../../ffmpeg ../..<br>
-- The C compiler identification is GNU 8.3.0<br>
-- The CXX compiler identification is GNU 8.3.0<br>
-- Check for working C compiler: F:/Telegram/ThirdParty/Strawberry/c/bin/gcc.exe<br>
-- Check for working C compiler: F:/Telegram/ThirdParty/Strawberry/c/bin/gcc.exe - works<br>
-- Detecting C compiler ABI info<br>
-- Detecting C compiler ABI info - done<br>
-- Detecting C compile features<br>
-- Detecting C compile features - done<br>
-- Check for working CXX compiler: F:/Telegram/ThirdParty/Strawberry/c/bin/c++.exe<br>
-- Check for working CXX compiler: F:/Telegram/ThirdParty/Strawberry/c/bin/c++.exe - works<br>
-- Detecting CXX compiler ABI info<br>
-- Detecting CXX compiler ABI info - done<br>
-- Detecting CXX compile features<br>
-- Detecting CXX compile features - done<br>
-- Configuring done<br>
-- Generating done<br>
-- Build files have been written to: F:/Telegram/Libraries/tg_owt/out/Debug<br>

F:\Telegram\Libraries\tg_owt\out\Debug>ninja<br>

[1/1572] Building CXX object CMakeFiles/libyuv.dir/src/third_party/libyuv/source/scale.cc.obj<br>
FAILED: CMakeFiles/libyuv.dir/src/third_party/libyuv/source/scale.cc.obj<br>
F:\Telegram\ThirdParty\Strawberry\c\bin\c++.exe  -DABSL_ALLOCATOR_NOTHROW=1 -DHAVE_JPEG -DHAVE_SCTP -DHAVE_SSE2 -DHAVE_WINSOCK2_H -DNOMINMAX -DWIN32_LEAN_AND_MEAN -I../../../qt_5_12_8/qtbase/src/3rdparty/libjpeg -I../../../qt_5_12_8/qtbase/src/3rdparty/libjpeg/src -I../../src/third_party/libyuv/include -g   /W1 /wd4715 /wd4244 /wd4838 /wd4305 /MP /EHsc /Zc:wchar_t- /Zi -std=gnu++17 -MD -MT CMakeFiles/libyuv.dir/src/third_party/libyuv/source/scale.cc.obj -MF CMakeFiles\libyuv.dir\src\third_party\libyuv\source\scale.cc.obj.d -o CMakeFiles/libyuv.dir/src/third_party/libyuv/source/scale.cc.obj -c ../../src/third_party/libyuv/source/scale.cc
c++.exe: error: /W1: No such file or directory<br>
c++.exe: error: /wd4715: No such file or directory<br>
c++.exe: error: /wd4244: No such file or directory<br>
c++.exe: error: /wd4838: No such file or directory<br>
c++.exe: error: /wd4305: No such file or directory<br>
c++.exe: error: /MP: No such file or directory<br>
c++.exe: error: /EHsc: No such file or directory<br>
c++.exe: error: /Zc:wchar_t-: No such file or directory<br>
c++.exe: error: /Zi: No such file or directory<br>
[2/1572] Building CXX object CMakeFiles/libyuv.dir/src/third_party/libyuv/source/scale_argb.cc.obj<br>
FAILED: CMakeFiles/libyuv.dir/src/third_party/libyuv/source/scale_argb.cc.obj<br>

ninja: build stopped: subcommand failed.
</details>
[build.ninja.txt](https://github.com/telegramdesktop/tdesktop/files/5171499/build.ninja.txt)

**Comment by ilya-fedin** [comment]
Use MSVC on Windows

**Comment by sudo-jonathan** [comment]
> This won't work, use MSVC on Windows

How?
I followed the [Build instructions for Visual Studio 2019](https://github.com/telegramdesktop/tdesktop/blob/dev/docs/building-msvc.md)
![image](https://user-images.githubusercontent.com/56518785/92239589-87f7e580-eed0-11ea-87d9-e89e9e52e4a6.png)

**Comment by ilya-fedin** [comment]
This shouldn't happen if you follow the instruction

**Comment by john-preston** [comment]
@sudo-jonathan Maybe some paths are not conflicting in the instructions 🤔 Can you try to launch fresh x86 native tools command prompt, go to Libraries and try to build only tg_owt by instructions, will it work?

**Comment by sudo-jonathan** [comment]
> @sudo-jonathan Maybe some paths are not conflicting in the instructions 🤔 Can you try to launch fresh x86 native tools command prompt, go to Libraries and try to build only tg_owt by instructions, will it work?

I did it again
But there is still the same error
![image](https://user-images.githubusercontent.com/56518785/92247505-8e8c5a00-eedc-11ea-8357-54a0fea145ca.png)

**Comment by sudo-jonathan** [comment]
referenced to #8434
problem solved.

tip: Strawberry add own c++ path compiler to env ...
