### ISSUE TITLE
[Feature Request] Inhibit screen dimming during videocalls

### ISSUE THREAD

**Issue by emilio-aburto** [telegramdesktop/tdesktop#8546]
### Is your feature request related to a problem?
The problem is that during a videocall you have to constantly move the mouse to avoid the screen dimming or even the system suspending itself.

### Describe the solution you'd like
The app could inhibit the power management during videocalls.

Thanks in advance

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/7790
