### ISSUE TITLE
Opening URL bug in Telegram

### ISSUE THREAD

**Issue by cergo666** [telegramdesktop/tdesktop#8548]
**Steps to reproduce**
Click on a link in dialogs

**Expected behaviour**
The link will open in the default browser.

**Actual behaviour**
The link opens in Firefox browser.

The problem appears only in Telegram. In other QT programs(Virtualbox, Teamviewer, etc) problem is not reproduced.

**UPD:** Not all links are opened incorrectly. 
For example, https://www.google.com.tw/maps/place/Realtek+Semiconductor+Corp./@24.7809981,120.9954638,3a,75y,90t/data=!3m8!1e2!3m6!1sAF1QipM_zBGv6dPow0mi3_ec38ratoIMfJ3uH_tsunJM!2e10!3e12!6shttps:%2F%2Flh5.googleusercontent.com%2Fp%2FAF1QipM_zBGv6dPow0mi3_ec38ratoIMfJ3uH_tsunJM%3Dw203-h270-k-no!7i3456!8i4608!4m8!1m2!2m1!1sNo.+2,+Innovation+Road+II,+Hsinchu+Science+Park,+Hsinchu+300,+Taiwan!3m4!1s0x34683604781bbd13:0x902205423d985ba5!8m2!3d24.7805598!4d120.9955064 opens in firefox but  https://www.google.com.tw/ opens in chrome.
**Configuration
Operating system:** Manjaro 20.1

**Version of Telegram Desktop**: 2.3.0-2
**Installation source:** https://www.archlinux.org/packages/community/x86_64/telegram-desktop/

**Comment by ilya-fedin** [comment]
Are you that other Qt programs doesn't operate in the same way?

**Comment by cergo666** [comment]
Okay, I corrected first post. If you need any more information, let me know about it.

**Comment by ilya-fedin** [comment]
You're skipped the most important part of the template - installation source

**Comment by ilya-fedin** [comment]
> For example, https://www.google.com.tw/maps/place/Realtek+Semiconductor+Corp./@24.7809981,120.9954638,3a,75y,90t/data=!3m8!1e2!3m6!1sAF1QipM_zBGv6dPow0mi3_ec38ratoIMfJ3uH_tsunJM!2e10!3e12!6shttps:%2F%2Flh5.googleusercontent.com%2Fp%2FAF1QipM_zBGv6dPow0mi3_ec38ratoIMfJ3uH_tsunJM%3Dw203-h270-k-no!7i3456!8i4608!4m8!1m2!2m1!1sNo.+2,+Innovation+Road+II,+Hsinchu+Science+Park,+Hsinchu+300,+Taiwan!3m4!1s0x34683604781bbd13:0x902205423d985ba5!8m2!3d24.7805598!4d120.9955064 opens in firefox but https://www.google.com.tw/ opens in chrome.

How did you check that link in Virtualbox or TeamViewer?

**Comment by cergo666** [comment]
I wrote this when I did not know that not all links do not open. 
Do you think the problem is with QT? If so, is there an application that can check it out?

**Comment by ilya-fedin** [comment]
> Do you think the problem is with QT?

Qt uses xdg-open under the hood, if there is a problem, it is with xdg-open

gtk programs are using custom implementation of this standard from glib.

**Comment by ilya-fedin** [comment]
Can the issue be closed?
