### ISSUE TITLE
Telegram Bot - One-time keyboard not showing up

### ISSUE THREAD

**Issue by matteocontrini** [telegramdesktop/tdesktop#855]
Hello,
I'm trying to set up a Telegram Bot. A simple request for `sendMessage` with these parameters doesn't work correctly.

```
chat_id=[...]
text=Test
disable_web_page_preview=true
reply_markup={"keyboard":[["Line 1], ["Line 2"]], "one_time_keyboard": true}
```

The keyboard is not shown at all. If I remove the `one_time_keyboard` parameter, the keyboard is shown but it stays there and I have to remove it manually with another command.

Can this be checked?
Thank you.

**Comment by auchri** [comment]
Because you have a typo in your reply_markup, it should be `{"keyboard":[["Line 1"], ["Line 2"]], "one_time_keyboard": true}`

(just checked and it works)
![image](https://cloud.githubusercontent.com/assets/5092164/9687490/0bf951ae-532a-11e5-8ec5-8796e1915ad8.png)
