### ISSUE TITLE
System Window Frame decorations reset on sleep or idle machines running Wayland session on Linux

### ISSUE THREAD

**Issue by aia832003** [telegramdesktop/tdesktop#8550]
### Steps to reproduce
1. enable system window frame in Advanced settings
2. window frames change to system fonts and theme
3. let the device go to sleep or force sleep
4. System frame reverts back default Telegram UI elements
5. Completely closing Telegram and relaunches allows system setting to be reapplied for GTK Theme

### Expected behaviour
Changing the setting for System Window Frame should respect the system GTK Theme and decorations even after app has been minimized to background processes or system sleep. This is only an issue on Wayland. X11 sessions seem to hold the setting regardless.

### Actual behaviour
At some point while running as a non-focused window and/or device goes to sleep the Window Frame reverts back to Telegram default until app is completely closed or reboot.

### Configuration
**Operating system:**
Fedora 32 and Pop_OS! 20.04
**Version of Telegram Desktop:**
2.3.2
**Installation source (Linux Only)** - the official website / GitHub releases / flatpak / snap / distribution package:
Flatpak 
**Used theme**:
Adwaita on Fedora and Pop default theme
![Screenshot from 2020-09-04 11-01-01](https://user-images.githubusercontent.com/11007827/92261179-a349fd00-ee9e-11ea-9993-2813bc8096bb.png)
![Screenshot from 2020-09-04 11-01-33](https://user-images.githubusercontent.com/11007827/92261182-a3e29380-ee9e-11ea-94cf-2ce2e95eff5d.png)

<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by ilya-fedin** [comment]
Gnome Wayland [doesn't support the XDG-Decoration protocol](https://gitlab.gnome.org/GNOME/mutter/-/issues/217), so that there are no way to get native decorations: the compositor just doesn't give them.

On your second screenshot XWayland is used.

**Comment by ilya-fedin** [comment]
And your first screenshot doesn't have Telegram decorations, it is Qt's dummy decorations for compositors that doesn't support the XDG-Decoration protocol.

**Comment by aia832003** [comment]
Thanks for the feedback. I guess I'm not fully understanding. The setting initially works under Wayland. The screenshots are on the same system but one was before the app was completely closed and the other after the app was relaunched? Wouldn't they being using the same window frame tools?

**Comment by ilya-fedin** [comment]
> The setting initially works under Wayland.

No, the second screenshot is definitely XWayland. You're launching Telegram with native Wayland at one time and with XWayland at another time somehow. I guess some of .desktop files of tdesktop in your system have override of QT_QPA_PLATFORM variable, another doesn't have.

**Comment by aia832003** [comment]
Not sure if this helps but here's the terminal output:

(process:2): Telegram-WARNING **: 12:44:09.565: Unfortunately, GTK integration conflicts with qgtk2 platformtheme and style. Therefore, QT_QPA_PLATFORMTHEME and QT_STYLE_OVERRIDE will be unset.
Telegram-Message: 12:44:09.568: This can be ignored by setting TDESKTOP_I_KNOW_ABOUT_GTK_INCOMPATIBILITY environment variable to any value, however, if qgtk2 theme or style is used, this will lead to a crash.
Telegram-Message: 12:44:09.568: GTK integration can be disabled by setting TDESKTOP_DISABLE_GTK_INTEGRATION to any value. Keep in mind that this will lead to clipboard issues and tdesktop will be unable to get settings from GTK (such as decoration layout, dark mode & more).
Qt: Session management error: None of the authentication protocols specified are supported
Gtk-Message: 12:44:09.673: Failed to load module "appmenu-gtk-module"
Gtk-Message: 12:44:09.787: Failed to load module "canberra-gtk-module"
Gtk-Message: 12:44:09.787: Failed to load module "canberra-gtk-module"
Telegram-Message: 12:44:09.800: You can disable tray icon counter with TDESKTOP_DISABLE_TRAY_COUNTER and make it look better if it is monochrome.
error: : cannot open
error: : cannot open
error: : cannot open

**Comment by ilya-fedin** [comment]
> Not sure if this helps but here's the terminal output

This is ok

**Comment by ilya-fedin** [comment]
I guess this issue could be closed since you're opened the same issue on https://github.com/flathub/org.telegram.desktop/issues/189

**Comment by aia832003** [comment]
Yes
