### ISSUE TITLE
Noisy sound when listening media (including voice msgs) through external audio interface

### ISSUE THREAD

**Issue by PandaTheSlayer** [telegramdesktop/tdesktop#8553]
### Steps to reproduce
1. Plug in external audio interface 
2. Listen to some media
3. Hear noise over the original sound

### Expected behaviour
No noise over the original sound

### Actual behaviour
Noice over original sound

### Configuration
**Operating system:**
Windows 10 Pro

**Version of Telegram Desktop:**
2.3.1

**Audio device**
Focusrite Scarlett Solo 3rd gen

**Installation source (Linux Only)** - the official website / GitHub releases / flatpak / snap / distribution package:
Official website

**Comment by ilya-fedin** [comment]
This is a known problematic sound card, look #1548
