### ISSUE TITLE
Unchecking "Use system window frame" causes Telegram to be 'Always on Top' window

### ISSUE THREAD

**Issue by curious0101** [telegramdesktop/tdesktop#8554]
Telegram: 2.3.2 (running via Telegram binary file)
Telegram theme: Classic

on:
System: Debian GNU/Linux 10 (buster) x86_64
DE: MATE
WM: Metacity (Marco)

Unchecking option in Settings/Advanced: "Use system window frame" causes Telegram to be 'Always on Top', all other programs' windows are underneath. It took me a while to figure out what happened and why Telegram is always on top, unasked.

**Comment by ilya-fedin** [comment]
Can't reproducre with MATE 1.24 on NixOS.

Anyway, there is nothing to fix on Telegram side, this is done by removing FramelessWindowHint, I can only suggest to restart the application.

**Comment by curious0101** [comment]
Checking this option and unchecking again fixed it, I can't reproduce it anymore. Weird. I will keep experimenting to figure out what happened, but for not issue it gone :)

**Comment by ilya-fedin** [comment]
Can the issue be closed?

**Comment by curious0101** [comment]
Closed, thanks for help.
