### ISSUE TITLE
telegram 2.3.1 crashed on audio call after other side has answered

### ISSUE THREAD

**Issue by vitlav** [telegramdesktop/tdesktop#8555]
telegram 2.3.1 crashed on audio call after other side has answered.

**Operating system:** Linux

**Version of Telegram Desktop:** 2.3.1

**Installation source (Linux Only)** - distribution package

**Used theme**: regular

<details><summary><b>Logs</b>:</summary>
...
D/tgvoip: === Updating voip config ===
D/tgvoip: {"enable_vp8_encoder":true,"enable_vp8_decoder":true,"enable_vp9_encoder":true,"enable_vp9_decoder":true,"enable_h265_encoder":true,"enable_h265_decoder":true,"enable_h264_encoder":true,"enable_h264_decoder":true,"audio_frame_size":60,"jitter_min_delay_60":2,"jitter_max_delay_60":10,"jitter_max_slots_60":20,"jitter_losses_to_reset":20,"jitter_resync_threshold":0.5,"audio_congestion_window":1024,"audio_max_bitrate":20000,"audio_max_bitrate_edge":16000,"audio_max_bitrate_gprs":8000,"audio_max_bitrate_saving":8000,"audio_init_bitrate":16000,"audio_init_bitrate_edge":8000,"audio_init_bitrate_gprs":8000,"audio_init_bitrate_saving":8000,"audio_bitrate_step_incr":1000,"audio_bitrate_step_decr":1000,"use_system_ns":true,"use_system_aec":true,"force_tcp":false,"jitter_initial_delay_60":2,"adsp_good_impls":"(Qualcomm Fluence)","bad_call_rating":true,"use_ios_vpio_agc":false,"use_tcp":false,"audio_medium_fec_bitrate":20000,"audio_medium_fec_multiplier":0.1,"audio_strong_fec_bitrate":7000}

...

Thread 50 "telegram-deskto" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fff13669700 (LWP 2631811)]
0x00007ffff7e58e97 in webrtc::AudioProcessingImpl::noise_suppression (this=0x7fff13667e50) at /usr/include/c++/8/bits/unique_ptr.h:345
345	      get() const noexcept
(gdb) bt
#0  0x00007ffff7e58e97 in webrtc::AudioProcessingImpl::noise_suppression (this=0x7fff13667e50) at /usr/include/c++/8/bits/unique_ptr.h:345
#1  0x0000000001a243cf in cricket::WebRtcVoiceEngine::ApplyOptions(cricket::AudioOptions const&) ()
#2  0x0000000001a24895 in cricket::WebRtcVoiceMediaChannel::SetOptions(cricket::AudioOptions const&) ()
#3  0x0000000001a252bc in cricket::WebRtcVoiceMediaChannel::SetSendParameters(cricket::AudioSendParameters const&) ()
#4  0x00000000018188a6 in tgcalls::MediaManager::MediaManager(rtc::Thread*, bool, tgcalls::MediaDevicesConfig const&, std::shared_ptr<tgcalls::VideoCaptureInterface>, std::function<void (tgcalls::Message&&)>, std::function<void (tgcalls::Message&&)>, std::function<void (int)>, float, bool) (this=0x7ffee8000b80, thread=<optimized out>, isOutgoing=<optimized out>, devicesConfig=..., videoCapture=..., sendSignalingMessage=..., sendTransportMessage=..., signalBarsUpdated=..., 
    localPreferredVideoAspectRatio=<optimized out>, enableHighBitrateVideo=false) at /usr/include/c++/8/bits/unique_ptr.h:345
#5  0x00000000018123f0 in tgcalls::Manager::<lambda()>::operator() (__closure=<optimized out>) at /usr/include/c++/8/bits/std_function.h:87
#6  tgcalls::ThreadLocalObject<tgcalls::MediaManager>::<lambda()>::operator() (this=<optimized out>) at /usr/src/debug/telegram-desktop-2.3.1/Telegram/ThirdParty/tgcalls/tgcalls/ThreadLocalObject.h:23
#7  rtc::rtc_thread_internal::MessageWithFunctor<tgcalls::ThreadLocalObject<T>::ThreadLocalObject(rtc::Thread*, Generator&&) [with Generator = tgcalls::Manager::start()::<lambda()>; <template-parameter-2-2> = void; T = tgcalls::MediaManager]::<lambda()> >::Run(void) (this=<optimized out>) at /usr/src/libowt-tg/rtc_base/thread.h:62
#8  0x00000000019aa34e in rtc::(anonymous namespace)::MessageHandlerWithTask::OnMessage(rtc::Message*) ()
#9  0x00000000019aab2e in rtc::Thread::Dispatch(rtc::Message*) ()
#10 0x00000000019abaf7 in rtc::Thread::ProcessMessages(int) ()
#11 0x00000000019ab05b in rtc::Thread::PreRun(void*) ()
#12 0x00007ffff7d1fed3 in start_thread (arg=<optimized out>) at pthread_create.c:463
#13 0x00007ffff326085f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
(gdb) l
340		return get();
341	      }
342	
343	      /// Return the stored pointer.
344	      pointer
345	      get() const noexcept
346	      { return _M_t._M_ptr(); }
347	
348	      /// Return a reference to the stored deleter.
349	      deleter_type&

</details>

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/8472
