### ISSUE TITLE
Microphone not working in calls after "video calls" update

### ISSUE THREAD

**Issue by zaid894** [telegramdesktop/tdesktop#8556]
### Steps to reproduce
1. try a normal telegram call on windows 10
2. 
3. 

### Expected behaviour
start your call normally 

### Actual behaviour
a new window opens, and my voice is not being sent though I can send voice notes so the microphone is working and accessible from telegram.

### Configuration
**Operating system:**
windows 10
**Version of Telegram Desktop:**
2.3.1
**Installation source (Linux Only)** - the official website / GitHub releases / flatpak / snap / distribution package:

**Used theme**:
Dark theme 
<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/7688

**Comment by zaid894** [comment]
no solutions is provided and the case is not closed

**Comment by ilya-fedin** [comment]
> #7688

This issue is about Focusrite soundcard (which is a known problematic soundcard) and create before video calls were introduced, I think #8443 is a more appropriate bug report.
