### ISSUE TITLE
Spell check uses US locale instead of language set in Windows 10 Settings

### ISSUE THREAD

**Issue by miiichael** [telegramdesktop/tdesktop#8559]
### Steps to reproduce
1. Configure Windows 10 with locale appropriate for en_AU
2. spell words correctly in Telegram, such as "colour", "analyse", "apologise"
3. note that spell check wants to correct them to the mispelt versions

### Expected behaviour
Use the correct spellcheck language

### Actual behaviour
Uses the wrong spellcheck language

### Configuration
**Operating system:**
Win10 1909

**Version of Telegram Desktop:**
2.3.1

**Used theme**:
(custom)

**Comment by ilya-fedin** [comment]
>     2\. spell words correctly in Telegram, such as "colour", "analyse", "apologise"

Are you sure that this is not windows 10 spellchecker's fault?

**Comment by miiichael** [comment]
To be honest, it's hard to tell for certain.

In Settings, there's Region (set to Australia), Regional Format (English (Australia)), Windows Display Language (English (US), but it says that that's only for Windows features like Settings and File Explorer).

Elsewhere, there's Language for non-Unicode programs (pretty sure not applicable here).

Outside of autocorrect, Windows doesn't seem to have any options specific to spellcheck. Within Telegram there is the "Use system spell checker", which is of course enabled. Deselecting it turns off spellcheck altogether.

**Comment by ilya-fedin** [comment]
> To be honest, it's hard to tell for certain.

I guess windows spellchecker just doesn't have special dictionaries for different English variants

**Comment by miiichael** [comment]
Personally I'd recommend giving up on system spellchecking on windows, and instead consider something (libhunspell?) more similar to Linux. At least then there'd be cross-platform consistency, and users could actually choose which languages (plural!) to spell-check with. But not my call to make, of course. 😅

**Comment by miiichael** [comment]
I haven't lost interest!

**Comment by ilya-fedin** [comment]
@Aokromes why we need a open issue about a Windows bug?

**Comment by Aokromes** [comment]
https://techcommunity.microsoft.com/t5/enterprise/setting-a-language-in-spell-check-does-not-install-the-language/m-p/1132444 maybe this can help you.
