### ISSUE TITLE
Feature request: Editing previous messages

### ISSUE THREAD

**Issue by dipu** [telegramdesktop/tdesktop#856]
I really miss the ability to fast fix typo & other errors in last few messages by pressing "Up" arrow for edit last message.

Is this in the consideration already ? If not can you guys consider it ?

Thank you

**Comment by Katzen-Gott** [comment]
I'm afraid, telegram server doesn't support this feature...

**Comment by Mindstormer619** [comment]
I don't think any messaging service does. It isn't supposed to.
