### ISSUE TITLE
Crash after sending video to contact while exporting channel history [crash]

### ISSUE THREAD

**Issue by necros2k7** [telegramdesktop/tdesktop#8560]
### Steps to reproduce
1.  Start exporting channel history 
2.  Send video file to some contact
3. 

### Expected behaviour
Tell us what should happen
No crash

### Actual behaviour
Tell us what happens instead
App crashed
### Configuration
**Operating system:**
win10x64 2004
**Version of Telegram Desktop:**
2.3.1
**Installation source (Linux Only)** - the official website / GitHub releases / flatpak / snap / distribution package:

**Used theme**:
Night mode
<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by ilya-fedin** [comment]
Crash report tag?

**Comment by Aokromes** [comment]
@necros2k7

**Comment by Aokromes** [comment]
1 month without answer, if this bug is still valid open a new ticket.
