### ISSUE TITLE
[Feature Request] JPGs optimized in quick send mode can be further lossy/losslessly optimized

### ISSUE THREAD

**Issue by necros2k7** [telegramdesktop/tdesktop#8562]
### Is your feature request related to a problem?
A clear and concise description of what the problem is.

### Describe the solution you'd like
Optimization toolchain can be improved to shrink files further
### Describe alternatives you've considered
If authors are interested some opensource tools can be advised

**Comment by ilya-fedin** [comment]
???

**Comment by ilya-fedin** [comment]
> Optimization toolchain can be improved to shrink files further

Compression is done server-side

**Comment by necros2k7** [comment]
So it can`t be imporved or where to report?

**Comment by ilya-fedin** [comment]
> So it can`t be improved

yeah

**Comment by Aokromes** [comment]
such feature belongs to https://bugs.telegram.org/
