### ISSUE TITLE
[Feature Request] select people when forwading instead of only one

### ISSUE THREAD

**Issue by RomanJos** [telegramdesktop/tdesktop#8563]
### Is your feature request related to a problem?
Yes, I want to forward a message to multiple people without doing the action 4 times

### Describe the solution you'd like
That the user I click on are selected like in the privacy setting when you choose always share your number with for example

### Additional context
![image](https://user-images.githubusercontent.com/42180076/92406206-b9261f00-f137-11ea-81c3-789374038f7d.png)

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/1841
