### ISSUE TITLE
[Question] Window without shadows in KDE?

### ISSUE THREAD

**Issue by ykmnkmi** [telegramdesktop/tdesktop#8565]
![image](https://user-images.githubusercontent.com/53435297/92434436-9e988800-f1c1-11ea-8755-1c8c08d1744b.png)

**Comment by ykmnkmi** [comment]
![image](https://user-images.githubusercontent.com/53435297/92434480-c1c33780-f1c1-11ea-8fa1-c21df6af1008.png)

**Comment by ilya-fedin** [comment]
Yeah, kwin doesn't add shadows to windows with custom decorations like all other window managers doing, not a Telegram bug
