### ISSUE TITLE
Option to edit message missing on channels where @DiscussBot is active, on posts that have comment button

### ISSUE THREAD

**Issue by jvlianodorneles** [telegramdesktop/tdesktop#8567]
### Steps to reproduce
1. Send a message on a channel that has @DiscussBot active;
2. Try to edit messages that have the comment button.

### Expected behaviour
Allow editing the message.

### Actual behaviour
No message editing option appears in the context menu (right click).
The edit option appears on posts that don't have the comment button.

### Configuration
**Operating system**: Linux (Fedora 32).

**Version of Telegram Desktop**: 2.3.2 beta.

**Installation source (Linux Only)**: GitHub releases.

**Used theme**: Default.

**Comment by ilya-fedin** [comment]
Are you sure this is a client issue? I guess server just doesn't allow to edit these posts.

**Comment by jvlianodorneles** [comment]
Telegram Desktop allowed editing until the end of last week ... and other
oficial clients continue to allow it without any problems. 🤷‍♂️

Em ter, 8 de set de 2020 11:53, ilya-fedin <notifications@github.com>
escreveu:

**Comment by ilya-fedin** [comment]
> Telegram Desktop allowed editing until the end of last week ... and other oficial clients continue to allow it without any problems. man_shrugging

Are you sure? Messages that are posted via a bot never were allowed for editing AFAIK

**Comment by jvlianodorneles** [comment]
I'm absolutely sure it always worked. Suddenly the option stopped
appearing. At least four more people were surprised that the editing option
disappeared and came to ask me what could have happened. 👍

Em ter, 8 de set de 2020 12:32, ilya-fedin <notifications@github.com>
escreveu:

**Comment by SamejSpenser** [comment]
> Are you sure? Messages that are posted via a bot never were allowed for editing AFAIK

Like @jvlianodorneles, I have exactly the same problem. I'm even one of the four people he mentioned above!

### Configuration

- **Operating system:** Linux Mint 19.3 Cinnamon (32-bit).

- **Telegram Desktop version:** 2.3.2 beta.

- **Installation source (Linux only):** official website.

- **Theme used:** Default.

**Comment by david-lev** [comment]
I have the same problem https://telegra.ph/file/f54f72ade2e1dd2bd19e5.mp4
