### ISSUE TITLE
telegram-desktop crashes after changing Interface Scale

### ISSUE THREAD

**Issue by David-J-White** [telegramdesktop/tdesktop#8568]
### Steps to reproduce
1. If you navigate to **Setting - Default Interface Scale** and change from 100% to 125%.
2. Accept setting.
3. Start using telegram.

### Expected behaviour
Scale changes.

### Actual behaviour
Scale changes but shortly after it crashes. 

### Configuration
```
System:    Host: ddocu-web-01 Kernel: 5.4.59-1-MANJARO-ARM aarch64 bits: 64
           parameters: coherent_pool=1M 8250.nr_uarts=0 snd_bcm2835.enable_compat_alsa=0 snd_bcm2835.enable_hdmi=1
           snd_bcm2835.enable_headphones=1 video=HDMI-A-1:1360x768M@60 smsc95xx.macaddr=DC:A6:32:BD:8D:68
           vc_mem.mem_base=0x3ec00000 vc_mem.mem_size=0x40000000 root=LABEL=ROOT_MNJRO rw rootwait console=ttyS0,115200
           console=tty1 selinux=0 plymouth.enable=0 smsc95xx.turbo_mode=N dwc_otg.lpm_enable=0 kgdboc=ttyS0,115200
           elevator=noop usbhid.mousepoll=8 snd-bcm2835.enable_compat_alsa=0

Desktop: i3 4.18.2 Distro: Manjaro ARM

Machine:   Type: ARM Device System: Raspberry Pi 4 Model B Rev 1.4 details: BCM2835 rev: d03114 serial: <filter>

CPU:       Topology: Quad Core model: N/A variant: cortex-a72 bits: 64 type: MCP family: 8 model-id: N/A stepping: 3
           microcode: N/A
           Speed: 600 MHz min/max: 600/1500 MHz Core speeds (MHz): 1: 600 2: 600 3: 600 4: 600
           Vulnerabilities: Type: itlb_multihit status: Not affected
           Type: l1tf status: Not affected
           Type: mds status: Not affected
           Type: meltdown status: Not affected
           Type: spec_store_bypass status: Vulnerable
           Type: spectre_v1 mitigation: __user pointer sanitization
           Type: spectre_v2 status: Vulnerable
           Type: srbds status: Not affected
           Type: tsx_async_abort status: Not affected

Graphics:  Device-1: bcm2711-vc5 driver: vc4_drm v: N/A
           Device-2: bcm2711-hdmi0 driver: N/A
           Device-3: bcm2711-hdmi1 driver: N/A
           Display: x11 server: X.Org 1.20.8 driver: fbturbo resolution: 1360x768~N/A
           Message: Unable to show advanced data. Required tool glxinfo missing.

Audio:     Device-1: bcm2835-audio driver: bcm2835_audio
           Device-2: bcm2711-hdmi0 driver: N/A
           Device-3: bcm2711-hdmi1 driver: N/A
           Sound Server: ALSA v: k5.4.59-1-MANJARO-ARM

Network:   Message: No ARM data found for this feature.
           IF-ID-1: eth0 state: down mac: <filter>
           IF-ID-2: wlan0 state: up mac: <filter>

Drives:    Local Storage: total: 89.20 GiB used: 6.13 GiB (6.9%)
           ID-1: /dev/mmcblk0 model: SR64G size: 59.48 GiB block size: physical: 512 B logical: 512 B
           ID-2: /dev/sda type: USB model: Mass Storage Device size: 29.72 GiB block size: physical: 512 B logical: 512 B

Partition: ID-1: / raw size: 59.24 GiB size: 58.26 GiB (98.34%) used: 6.08 GiB (10.4%) fs: ext4 dev: /dev/mmcblk0p2
           ID-2: /boot raw size: 213.6 MiB size: 213.4 MiB (99.89%) used: 45.5 MiB (21.3%) fs: vfat dev: /dev/mmcblk0p1

Sensors:   System Temperatures: cpu: 49.2 C mobo: N/A
           Fan Speeds (RPM): N/A

Info:      Processes: 169 Uptime: 2h 18m Memory: 7.71 GiB used: 1.50 GiB (19.4%) gpu: 64.0 MiB Shell: bash inxi: 3.0.37
```

<details><summary><b>Logs</b>:</summary>

Sep 08 14:41:20 ddocu-web-01 systemd[1]: systemd-coredump@0-2065-0.service: Succeeded.
Sep 08 14:41:19 ddocu-web-01 systemd-coredump[2066]: Process 2025 (telegram-deskto) of user 1000 dumped core.

                                                     Stack trace of thread 2032:
                                                     #0  0x0000007f852a96c8 raise (libc.so.6 + 0x376c8)
                                                     #1  0x0000007f852961cc abort (libc.so.6 + 0x241cc)
                                                     #2  0x0000005581037460 n/a (telegram-desktop + 0x3e3460)
                                                     #3  0x000000558142b220 n/a (telegram-desktop + 0x7d7220)
                                                     #4  0x0000005581416154 n/a (telegram-desktop + 0x7c2154)
                                                     #5  0x0000005581416610 n/a (telegram-desktop + 0x7c2610)
                                                     #6  0x0000005581416fd8 n/a (telegram-desktop + 0x7c2fd8)
                                                     #7  0x0000005581418f18 n/a (telegram-desktop + 0x7c4f18)

...skipping 1 line
                                                     #9  0x00000055813e5174 n/a (telegram-desktop + 0x791174)
                                                     #10 0x00000055813e54b4 n/a (telegram-desktop + 0x7914b4)
                                                     #11 0x0000007f869a96e8 n/a (libQt5Core.so.5 + 0xcc6e8)
                                                     #12 0x0000007f869a5480 n/a (libQt5Core.so.5 + 0xc8480)
                                                     #13 0x0000007f87f9ef44 start_thread (libpthread.so.0 + 0x7f44)
                                                     #14 0x0000007f8534595c thread_start (libc.so.6 + 0xd395c)

                                                     Stack trace of thread 2026:
                                                     #0  0x0000007f8533be64 __poll (libc.so.6 + 0xc9e64)
                                                     #1  0x0000007f86295288 n/a (libxcb.so.1 + 0xc288)
                                                     #2  0x0000007f8629732c xcb_wait_for_event (libxcb.so.1 + 0xe32c)
                                                     #3  0x0000007f7fe88de8 n/a (libQt5XcbQpa.so.5 + 0x6fde8)
                                                     #4  0x0000007f869a5480 n/a (libQt5Core.so.5 + 0xc8480)
                                                     #5  0x0000007f87f9ef44 start_thread (libpthread.so.0 + 0x7f44)
                                                     #6  0x0000007f8534595c thread_start (libc.so.6 + 0xd395c)

                                                     Stack trace of thread 2027:
                                                     #0  0x0000007f8533be64 __poll (libc.so.6 + 0xc9e64)
                                                     #1  0x0000007f85717a28 n/a (libglib-2.0.so.0 + 0x5ca28)
                                                     #2  0x0000007f85717bb4 g_main_context_iteration (libglib-2.0.so.0 + 0x5cbb4)
                                                     #3  0x0000007f86c3602c _ZN20QEventDispatcherGlib13processEventsE6QFlagsIN10QEventLoop17ProcessEventsFlagEE (
libQt5Core.so.5 + 0x35902c)
                                                     #4  0x0000007f86bc7314 _ZN10QEventLoop4execE6QFlagsINS_17ProcessEventsFlagEE (libQt5Core.so.5 + 0x2ea314)
                                                     #5  0x0000007f869a3b78 _ZN7QThread4execEv (libQt5Core.so.5 + 0xc6b78)
                                                     #6  0x0000007f869a5480 n/a (libQt5Core.so.5 + 0xc8480)
                                                     #7  0x0000007f87f9ef44 start_thread (libpthread.so.0 + 0x7f44)
                                                     #8  0x0000007f8534595c thread_start (libc.so.6 + 0xd395c)

                                                     Stack trace of thread 2038:
                                                     #0  0x0000007f8533be64 __poll (libc.so.6 + 0xc9e64)
                                                     #1  0x0000007f85717a28 n/a (libglib-2.0.so.0 + 0x5ca28)
                                                     #2  0x0000007f85717bb4 g_main_context_iteration (libglib-2.0.so.0 + 0x5cbb4)
                                                     #3  0x0000007f86c3602c _ZN20QEventDispatcherGlib13processEventsE6QFlagsIN10QEventLoop17ProcessEventsFlagEE (
libQt5Core.so.5 + 0x35902c)
                                                     #4  0x0000007f86bc7314 _ZN10QEventLoop4execE6QFlagsINS_17ProcessEventsFlagEE (libQt5Core.so.5 + 0x2ea314)
                                                     #5  0x0000007f869a3b78 _ZN7QThread4execEv (libQt5Core.so.5 + 0xc6b78)
                                                     #6  0x0000007f869a5480 n/a (libQt5Core.so.5 + 0xc8480)
                                                     #7  0x0000007f87f9ef44 start_thread (libpthread.so.0 + 0x7f44)
                                                     #8  0x0000007f8534595c thread_start (libc.so.6 + 0xd395c)

                                                     Stack trace of thread 2042:
                                                     #0  0x0000007f87fa574c pthread_cond_wait@@GLIBC_2.17 (libpthread.so.0 + 0xe74c)
                                                     #1  0x0000007f432cb424 n/a (swrast_dri.so + 0x76f424)
                                                     #2  0x0000007f432cb20c n/a (swrast_dri.so + 0x76f20c)

...skipping 1 line
                                                     #4  0x0000007f8534595c thread_start (libc.so.6 + 0xd395c)

                                                     Stack trace of thread 2040:
                                                     #0  0x0000007f8533be64 __poll (libc.so.6 + 0xc9e64)
                                                     #1  0x0000007f85717a28 n/a (libglib-2.0.so.0 + 0x5ca28)
                                                     #2  0x0000007f85717bb4 g_main_context_iteration (libglib-2.0.so.0 + 0x5cbb4)
                                                     #3  0x0000007f86c3602c _ZN20QEventDispatcherGlib13processEventsE6QFlagsIN10QEventLoop17ProcessEventsFlagEE (
libQt5Core.so.5 + 0x35902c)
                                                     #4  0x0000007f86bc7314 _ZN10QEventLoop4execE6QFlagsINS_17ProcessEventsFlagEE (libQt5Core.so.5 + 0x2ea314)
                                                     #5  0x0000007f869a3b78 _ZN7QThread4execEv (libQt5Core.so.5 + 0xc6b78)
                                                     #6  0x0000007f869a5480 n/a (libQt5Core.so.5 + 0xc8480)
                                                     #7  0x0000007f87f9ef44 start_thread (libpthread.so.0 + 0x7f44)
                                                     #8  0x0000007f8534595c thread_start (libc.so.6 + 0xd395c)

                                                     Stack trace of thread 2031:
                                                     #0  0x0000007f8533be64 __poll (libc.so.6 + 0xc9e64)
                                                     #1  0x0000007f85717a28 n/a (libglib-2.0.so.0 + 0x5ca28)
                                                     #2  0x0000007f85717ee0 g_main_loop_run (libglib-2.0.so.0 + 0x5cee0)
                                                     #3  0x0000007f82fb1d44 n/a (libgio-2.0.so.0 + 0x158d44)
                                                     #4  0x0000007f8574769c n/a (libglib-2.0.so.0 + 0x8c69c)
                                                     #5  0x0000007f87f9ef44 start_thread (libpthread.so.0 + 0x7f44)
                                                     #6  0x0000007f8534595c thread_start (libc.so.6 + 0xd395c)

                                                     Stack trace of thread 2045:
                                                     #0  0x0000007f87fa574c pthread_cond_wait@@GLIBC_2.17 (libpthread.so.0 + 0xe74c)
                                                     #1  0x0000007f432c84a4 n/a (swrast_dri.so + 0x76c4a4)
                                                     #2  0x0000007f432c8414 n/a (swrast_dri.so + 0x76c414)
                                                     #3  0x0000007f87f9ef44 start_thread (libpthread.so.0 + 0x7f44)
                                                     #4  0x0000007f8534595c thread_start (libc.so.6 + 0xd395c)

                                                     Stack trace of thread 2041:
                                                     #0  0x0000007f87fa574c pthread_cond_wait@@GLIBC_2.17 (libpthread.so.0 + 0xe74c)
                                                     #1  0x0000007f432cb424 n/a (swrast_dri.so + 0x76f424)
                                                     #2  0x0000007f432cb20c n/a (swrast_dri.so + 0x76f20c)
                                                     #3  0x0000007f87f9ef44 start_thread (libpthread.so.0 + 0x7f44)
                                                     #4  0x0000007f8534595c thread_start (libc.so.6 + 0xd395c)

                                                     Stack trace of thread 2028:
                                                     #0  0x0000007f8533be64 __poll (libc.so.6 + 0xc9e64)
                                                     #1  0x0000007f85717a28 n/a (libglib-2.0.so.0 + 0x5ca28)
                                                     #2  0x0000007f85717bb4 g_main_context_iteration (libglib-2.0.so.0 + 0x5cbb4)
                                                     #3  0x0000007f86c3604c _ZN20QEventDispatcherGlib13processEventsE6QFlagsIN10QEventLoop17ProcessEventsFlagEE (
libQt5Core.so.5 + 0x35904c)
                                                     #4  0x0000007f86bc7314 _ZN10QEventLoop4execE6QFlagsINS_17ProcessEventsFlagEE (libQt5Core.so.5 + 0x2ea314)

...skipping 1 line
                                                     #5  0x0000007f869a3b78 _ZN7QThread4execEv (libQt5Core.so.5 + 0xc6b78)
                                                     #6  0x0000007f8759fa88 n/a (libQt5DBus.so.5 + 0x16a88)
                                                     #7  0x0000007f869a5480 n/a (libQt5Core.so.5 + 0xc8480)
                                                     #8  0x0000007f87f9ef44 start_thread (libpthread.so.0 + 0x7f44)
                                                     #9  0x0000007f8534595c thread_start (libc.so.6 + 0xd395c)

                                                     Stack trace of thread 2037:
                                                     #0  0x0000007f8533be64 __poll (libc.so.6 + 0xc9e64)
                                                     #1  0x0000007f8634d71c n/a (libopenal.so.1 + 0x7771c)
                                                     #2  0x0000007f676bf278 pa_mainloop_poll (libpulse.so.0 + 0x29278)
                                                     #3  0x0000007f676bf99c pa_mainloop_iterate (libpulse.so.0 + 0x2999c)
                                                     #4  0x0000007f676bfa90 pa_mainloop_run (libpulse.so.0 + 0x29a90)
                                                     #5  0x0000007f8634e338 n/a (libopenal.so.1 + 0x78338)
                                                     #6  0x0000007f855890dc execute_native_thread_routine (libstdc++.so.6 + 0xd20dc)
                                                     #7  0x0000007f87f9ef44 start_thread (libpthread.so.0 + 0x7f44)
                                                     #8  0x0000007f8534595c thread_start (libc.so.6 + 0xd395c)

                                                     Stack trace of thread 2046:
                                                     #0  0x0000007f87fa574c pthread_cond_wait@@GLIBC_2.17 (libpthread.so.0 + 0xe74c)
                                                     #1  0x0000007f432c84a4 n/a (swrast_dri.so + 0x76c4a4)
                                                     #2  0x0000007f432c8414 n/a (swrast_dri.so + 0x76c414)
                                                     #3  0x0000007f87f9ef44 start_thread (libpthread.so.0 + 0x7f44)
                                                     #4  0x0000007f8534595c thread_start (libc.so.6 + 0xd395c)

                                                     Stack trace of thread 2044:
                                                     #0  0x0000007f87fa574c pthread_cond_wait@@GLIBC_2.17 (libpthread.so.0 + 0xe74c)
                                                     #1  0x0000007f432cb424 n/a (swrast_dri.so + 0x76f424)
                                                     #2  0x0000007f432cb20c n/a (swrast_dri.so + 0x76f20c)
                                                     #3  0x0000007f87f9ef44 start_thread (libpthread.so.0 + 0x7f44)
                                                     #4  0x0000007f8534595c thread_start (libc.so.6 + 0xd395c)

                                                     Stack trace of thread 2030:
                                                     #0  0x0000007f8533be64 __poll (libc.so.6 + 0xc9e64)
                                                     #1  0x0000007f85717a28 n/a (libglib-2.0.so.0 + 0x5ca28)
                                                     #2  0x0000007f85717bb4 g_main_context_iteration (libglib-2.0.so.0 + 0x5cbb4)
                                                     #3  0x0000007f85717c2c n/a (libglib-2.0.so.0 + 0x5cc2c)
                                                     #4  0x0000007f8574769c n/a (libglib-2.0.so.0 + 0x8c69c)
                                                     #5  0x0000007f87f9ef44 start_thread (libpthread.so.0 + 0x7f44)
                                                     #6  0x0000007f8534595c thread_start (libc.so.6 + 0xd395c)

                                                     Stack trace of thread 2033:
                                                     #0  0x0000007f87fa5ad4 pthread_cond_timedwait@@GLIBC_2.17 (libpthread.so.0 + 0xead4)
                                                     #1  0x0000007f869ad1d4 _ZN14QWaitCondition4waitEP6QMutex14QDeadlineTimer (libQt5Core.so.5 + 0xd01d4)
                                                     #2  0x0000007f869a9908 n/a (libQt5Core.so.5 + 0xcc908)

...skipping 1 line
                                                     #4  0x0000007f87f9ef44 start_thread (libpthread.so.0 + 0x7f44)
                                                     #5  0x0000007f8534595c thread_start (libc.so.6 + 0xd395c)

                                                     Stack trace of thread 2049:
                                                     #0  0x0000007f8533be64 __poll (libc.so.6 + 0xc9e64)
                                                     #1  0x0000007f85717a28 n/a (libglib-2.0.so.0 + 0x5ca28)
                                                     #2  0x0000007f85717bb4 g_main_context_iteration (libglib-2.0.so.0 + 0x5cbb4)
                                                     #3  0x0000007f86c3602c _ZN20QEventDispatcherGlib13processEventsE6QFlagsIN10QEventLoop17ProcessEventsFlagEE (
libQt5Core.so.5 + 0x35902c)
                                                     #4  0x0000007f86bc7314 _ZN10QEventLoop4execE6QFlagsINS_17ProcessEventsFlagEE (libQt5Core.so.5 + 0x2ea314)
                                                     #5  0x0000007f869a3b78 _ZN7QThread4execEv (libQt5Core.so.5 + 0xc6b78)
                                                     #6  0x0000007f869a5480 n/a (libQt5Core.so.5 + 0xc8480)
                                                     #7  0x0000007f87f9ef44 start_thread (libpthread.so.0 + 0x7f44)
                                                     #8  0x0000007f8534595c thread_start (libc.so.6 + 0xd395c)

                                                     Stack trace of thread 2050:
                                                     #0  0x0000007f8533be64 __poll (libc.so.6 + 0xc9e64)
                                                     #1  0x0000007f85717a28 n/a (libglib-2.0.so.0 + 0x5ca28)
                                                     #2  0x0000007f85717bb4 g_main_context_iteration (libglib-2.0.so.0 + 0x5cbb4)
                                                     #3  0x0000007f86c3602c _ZN20QEventDispatcherGlib13processEventsE6QFlagsIN10QEventLoop17ProcessEventsFlagEE (
libQt5Core.so.5 + 0x35902c)
                                                     #4  0x0000007f86bc7314 _ZN10QEventLoop4execE6QFlagsINS_17ProcessEventsFlagEE (libQt5Core.so.5 + 0x2ea314)
                                                     #5  0x0000007f869a3b78 _ZN7QThread4execEv (libQt5Core.so.5 + 0xc6b78)
                                                     #6  0x0000007f869a5480 n/a (libQt5Core.so.5 + 0xc8480)
                                                     #7  0x0000007f87f9ef44 start_thread (libpthread.so.0 + 0x7f44)
                                                     #8  0x0000007f8534595c thread_start (libc.so.6 + 0xd395c)

                                                     Stack trace of thread 2039:
                                                     #0  0x0000007f8533be64 __poll (libc.so.6 + 0xc9e64)
                                                     #1  0x0000007f85717a28 n/a (libglib-2.0.so.0 + 0x5ca28)
                                                     #2  0x0000007f85717bb4 g_main_context_iteration (libglib-2.0.so.0 + 0x5cbb4)
                                                     #3  0x0000007f86c3602c _ZN20QEventDispatcherGlib13processEventsE6QFlagsIN10QEventLoop17ProcessEventsFlagEE (
libQt5Core.so.5 + 0x35902c)
                                                     #4  0x0000007f86bc7314 _ZN10QEventLoop4execE6QFlagsINS_17ProcessEventsFlagEE (libQt5Core.so.5 + 0x2ea314)
                                                     #5  0x0000007f869a3b78 _ZN7QThread4execEv (libQt5Core.so.5 + 0xc6b78)
                                                     #6  0x0000007f869a5480 n/a (libQt5Core.so.5 + 0xc8480)
                                                     #7  0x0000007f87f9ef44 start_thread (libpthread.so.0 + 0x7f44)
                                                     #8  0x0000007f8534595c thread_start (libc.so.6 + 0xd395c)

                                                     Stack trace of thread 2064:
                                                     #0  0x0000007f87fa574c pthread_cond_wait@@GLIBC_2.17 (libpthread.so.0 + 0xe74c)
                                                     #1  0x0000007f855815d8 __gthread_cond_wait (libstdc++.so.6 + 0xca5d8)
                                                     #2  0x0000005582a2c5e0 n/a (telegram-desktop + 0x1dd85e0)
                                                     #3  0x0000007f855890dc execute_native_thread_routine (libstdc++.so.6 + 0xd20dc)

...skipping 1 line
                                                     #5  0x0000007f8534595c thread_start (libc.so.6 + 0xd395c)

                                                     Stack trace of thread 2043:
                                                     #0  0x0000007f87fa574c pthread_cond_wait@@GLIBC_2.17 (libpthread.so.0 + 0xe74c)
                                                     #1  0x0000007f432cb424 n/a (swrast_dri.so + 0x76f424)
                                                     #2  0x0000007f432cb20c n/a (swrast_dri.so + 0x76f20c)
                                                     #3  0x0000007f87f9ef44 start_thread (libpthread.so.0 + 0x7f44)
                                                     #4  0x0000007f8534595c thread_start (libc.so.6 + 0xd395c)

                                                     Stack trace of thread 2054:
                                                     #0  0x0000007f8533be64 __poll (libc.so.6 + 0xc9e64)
                                                     #1  0x0000007f85717a28 n/a (libglib-2.0.so.0 + 0x5ca28)
                                                     #2  0x0000007f85717bb4 g_main_context_iteration (libglib-2.0.so.0 + 0x5cbb4)
                                                     #3  0x0000007f86c3602c _ZN20QEventDispatcherGlib13processEventsE6QFlagsIN10QEventLoop17ProcessEventsFlagEE (
libQt5Core.so.5 + 0x35902c)
                                                     #4  0x0000007f86bc7314 _ZN10QEventLoop4execE6QFlagsINS_17ProcessEventsFlagEE (libQt5Core.so.5 + 0x2ea314)
                                                     #5  0x0000007f869a3b78 _ZN7QThread4execEv (libQt5Core.so.5 + 0xc6b78)
                                                     #6  0x0000007f869a5480 n/a (libQt5Core.so.5 + 0xc8480)
                                                     #7  0x0000007f87f9ef44 start_thread (libpthread.so.0 + 0x7f44)
                                                     #8  0x0000007f8534595c thread_start (libc.so.6 + 0xd395c)

                                                     Stack trace of thread 2063:
                                                     #0  0x0000007f87fa574c pthread_cond_wait@@GLIBC_2.17 (libpthread.so.0 + 0xe74c)
                                                     #1  0x0000007f855815d8 __gthread_cond_wait (libstdc++.so.6 + 0xca5d8)
                                                     #2  0x0000005582a2c5e0 n/a (telegram-desktop + 0x1dd85e0)
                                                     #3  0x0000007f855890dc execute_native_thread_routine (libstdc++.so.6 + 0xd20dc)
                                                     #4  0x0000007f87f9ef44 start_thread (libpthread.so.0 + 0x7f44)
                                                     #5  0x0000007f8534595c thread_start (libc.so.6 + 0xd395c)

                                                     Stack trace of thread 2061:
                                                     #0  0x0000007f87fa574c pthread_cond_wait@@GLIBC_2.17 (libpthread.so.0 + 0xe74c)
                                                     #1  0x0000007f855815d8 __gthread_cond_wait (libstdc++.so.6 + 0xca5d8)
                                                     #2  0x0000005582a2c5e0 n/a (telegram-desktop + 0x1dd85e0)
                                                     #3  0x0000007f855890dc execute_native_thread_routine (libstdc++.so.6 + 0xd20dc)
                                                     #4  0x0000007f87f9ef44 start_thread (libpthread.so.0 + 0x7f44)
                                                     #5  0x0000007f8534595c thread_start (libc.so.6 + 0xd395c)

                                                     Stack trace of thread 2047:
                                                     #0  0x0000007f87fa574c pthread_cond_wait@@GLIBC_2.17 (libpthread.so.0 + 0xe74c)
                                                     #1  0x0000007f432c84a4 n/a (swrast_dri.so + 0x76c4a4)
                                                     #2  0x0000007f432c8414 n/a (swrast_dri.so + 0x76c414)
                                                     #3  0x0000007f87f9ef44 start_thread (libpthread.so.0 + 0x7f44)
                                                     #4  0x0000007f8534595c thread_start (libc.so.6 + 0xd395c)

...skipping 1 line
                                                     #0  0x0000007f87fa5ad4 pthread_cond_timedwait@@GLIBC_2.17 (libpthread.so.0 + 0xead4)
                                                     #1  0x0000007f869ad1d4 _ZN14QWaitCondition4waitEP6QMutex14QDeadlineTimer (libQt5Core.so.5 + 0xd01d4)
                                                     #2  0x0000007f869a9908 n/a (libQt5Core.so.5 + 0xcc908)
                                                     #3  0x0000007f869a5480 n/a (libQt5Core.so.5 + 0xc8480)
                                                     #4  0x0000007f87f9ef44 start_thread (libpthread.so.0 + 0x7f44)
                                                     #5  0x0000007f8534595c thread_start (libc.so.6 + 0xd395c)

                                                     Stack trace of thread 2034:
                                                     #0  0x0000007f864f9de0 AES_encrypt (libcrypto.so.1.1 + 0x85de0)
                                                     #1  0x0000007f865e81b8 CRYPTO_ctr128_encrypt (libcrypto.so.1.1 + 0x1741b8)
                                                     #2  0x00000055813ebd54 n/a (telegram-desktop + 0x797d54)
                                                     #3  0x00000055813e9f00 n/a (telegram-desktop + 0x795f00)
                                                     #4  0x00000055813ea714 n/a (telegram-desktop + 0x796714)
                                                     #5  0x00000055813eadd4 n/a (telegram-desktop + 0x796dd4)
                                                     #6  0x0000005581408d84 n/a (telegram-desktop + 0x7b4d84)
                                                     #7  0x000000558140a1c8 n/a (telegram-desktop + 0x7b61c8)
                                                     #8  0x00000055813faf70 n/a (telegram-desktop + 0x7a6f70)
                                                     #9  0x00000055813e5190 n/a (telegram-desktop + 0x791190)
                                                     #10 0x00000055813e54b4 n/a (telegram-desktop + 0x7914b4)
                                                     #11 0x0000007f869a96e8 n/a (libQt5Core.so.5 + 0xcc6e8)
                                                     #12 0x0000007f869a5480 n/a (libQt5Core.so.5 + 0xc8480)
                                                     #13 0x0000007f87f9ef44 start_thread (libpthread.so.0 + 0x7f44)
                                                     #14 0x0000007f8534595c thread_start (libc.so.6 + 0xd395c)

                                                     Stack trace of thread 2025:
                                                     #0  0x0000007f8533be64 __poll (libc.so.6 + 0xc9e64)
                                                     #1  0x0000007f85717a28 n/a (libglib-2.0.so.0 + 0x5ca28)
                                                     #2  0x0000007f85717bb4 g_main_context_iteration (libglib-2.0.so.0 + 0x5cbb4)
                                                     #3  0x0000007f86c3602c _ZN20QEventDispatcherGlib13processEventsE6QFlagsIN10QEventLoop17ProcessEventsFlagEE (
libQt5Core.so.5 + 0x35902c)
                                                     #4  0x0000007f86bc7314 _ZN10QEventLoop4execE6QFlagsINS_17ProcessEventsFlagEE (libQt5Core.so.5 + 0x2ea314)
                                                     #5  0x0000007f86bd15f0 _ZN16QCoreApplication4execEv (libQt5Core.so.5 + 0x2f45f0)
                                                     #6  0x00000055819e29d4 n/a (telegram-desktop + 0xd8e9d4)
                                                     #7  0x00000055819cf654 n/a (telegram-desktop + 0xd7b654)
                                                     #8  0x00000055819cf8d0 n/a (telegram-desktop + 0xd7b8d0)
                                                     #9  0x000000558102d204 n/a (telegram-desktop + 0x3d9204)
                                                     #10 0x0000007f85296538 __libc_start_main (libc.so.6 + 0x24538)
                                                     #11 0x0000005581036678 n/a (telegram-desktop + 0x3e2678)
                                                     #12 0x0000005581036678 n/a (telegram-desktop + 0x3e2678)
Sep 08 14:41:09 ddocu-web-01 systemd[1]: Started Process Core Dump (PID 2065/UID 0).
Sep 08 14:41:09 ddocu-web-01 systemd[1]: Created slice system-systemd\x2dcoredump.slice.
Sep 08 14:26:28 ddocu-web-01 systemd[1]: Finished Cleanup of Temporary Directories.
Sep 08 14:26:28 ddocu-web-01 systemd[1]: systemd-tmpfiles-clean.service: Succeeded.
Sep 08 14:26:28 ddocu-web-01 systemd[1]: Starting Cleanup of Temporary Directories...

...skipping 1 line
Sep 08 14:25:27 ddocu-web-01 telegram-desktop[1734]: qt.gui.icc: fromIccProfile: failed minimal tag size sanity
Sep 08 14:25:12 ddocu-web-01 telegram-desktop[1734]: qt.gui.icc: fromIccProfile: failed minimal tag size sanity
Sep 08 14:25:12 ddocu-web-01 telegram-desktop[1734]: qt.gui.icc: fromIccProfile: failed minimal tag size sanity
Sep 08 14:24:43 ddocu-web-01 telegram-desktop[1734]: qt.gui.icc: fromIccProfile: failed minimal tag size sanity
Sep 08 14:24:43 ddocu-web-01 telegram-desktop[1734]: qt.gui.icc: fromIccProfile: failed minimal tag size sanity

</details>

**Comment by ilya-fedin** [comment]
ARM is not supported officially, if you need a fix, you should contribute it yourself

**Comment by ilya-fedin** [comment]
Is this your thread https://forum.manjaro.org/t/telegram-desktop-crashes-randomly-its-unusable/22190?
If yes, then according to `[swscaler @ 0x7f68083500] No accelerated colorspace conversion found from yuv420p to bgra.`, then this is a duplicate of #8523

**Comment by David-J-White** [comment]
Ok. Thank you.
I'll put it on ix86.
