### ISSUE TITLE
webview unable to play peertube videos

### ISSUE THREAD

**Issue by test2a** [telegramdesktop/tdesktop#8569]
### Steps to reproduce
1. open any peertube video and share link on telegram
2. video does not work
3. https://devtube.dev-wiki.de/videos/watch/a8493008-a9b9-4de6-8e8a-5aac70f6e45a 
try this link
4. what i am asking for is, is the support for playing peertube videos need to be implemented in telegram or in peertube software instead to support some standard protocol. i tried to look up core.telegram.org but i could not find any documentation on how video player supports which format and else

### Expected behaviour
video should play just like youtube video plays

### Actual behaviour
no video plays. only cover photo gets downloaded

### Configuration
**Operating system:**

**Version of Telegram Desktop:**
android

**Installation source (Linux Only)** - the official website / GitHub releases / flatpak / snap / distribution package:

**Used theme**:

<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by ilya-fedin** [comment]
This bugtracker only for telegram desktop
