### ISSUE TITLE
[Feature Request] Icon tray just like Skype (shows connection status)

### ISSUE THREAD

**Issue by kokizzu** [telegramdesktop/tdesktop#857]
It would be great if current status of internet connection can be seen through the color of the Telegram's system tray icon, just like Skype (green = connected, gray = not connected).

**Comment by cobalto** [comment]
As seen on #632 and #341 and never ever released :(

**Comment by ralesk** [comment]
+1 would be very nice to have

**Comment by Mindstormer619** [comment]
You can actually click the icon and Telegram says "Connecting..." at the bottom if not connected.

**Comment by ralesk** [comment]
@Mindstormer619 yes, but that's kind of a mystery meat operation, much easier to just glimpse at the icon and immediately know what's up.

**Comment by cobalto** [comment]
@Mindstormer619 no, no, no, the issue here is exactly the oposite of that.
We don't want to CHECK if it's connected or not.
We want to be advised that it's not connected anymore.

**Comment by auchri** [comment]
Duplicate #470
