### ISSUE TITLE
[Feature Request] Forward message without quote

### ISSUE THREAD

**Issue by AmirHosseinKarimi** [telegramdesktop/tdesktop#8571]
### Is your feature request related to a problem?
No.

### Describe the solution you'd like
A feature which provide the ability to forward messages without quote the original sender

### Describe alternatives you've considered
It has implemented in Plus messenger.

### Additional context
It just like the Forward message option in the context menu of the message, But does not quote the original sender and just forward the message content, like use copied the message content and paste, and send it again.

**Comment by Aokromes** [comment]
i doub this will be implemented.

**Comment by AmirHosseinKarimi** [comment]
@Aokromes Why?

**Comment by mbnoimi** [comment]
I've multiple channels, so I need to upload files to them but upload process a bit complicated to fix this issue I upload all the files to one private channel then I distribute the uploaded files to the channels using Plus Messenger because all official Telegram clients doesn't support "forward without quote" feature.

I consider it a vital feature for millions of the publishers.

**Comment by RememberTheAir** [comment]
> ll official Telegram clients doesn't support "forward without quote" feature

Side note: Telegram X does

**Comment by mbnoimi** [comment]
> Side note: Telegram X does

First it's a mobile based app while I always prefer the desktop one. Secondly; The update process is very slow by comparing to the default official clients,

**Comment by Nirzak** [comment]
I also support this. It will be beneficial for those who like to use telegram from the desktop. I know it's an implemented feature on Plus Messenger and Telegram X. But they are only mobile clients. Hope, @john-preston will consider this one.

**Comment by RememberTheAir** [comment]
By the way, this isn't going to be added on the desktop app as long as other Telegram apps don't have this option too

We should upvote the suggestions on the official suggestions platform:
- https://bugs.telegram.org/c/1377
- https://bugs.telegram.org/c/3342

**Comment by Nirzak** [comment]
> By the way, this isn't going to be added on the desktop app as long as other Telegram apps don't have this option too
> 
> We should upvote the suggestions on the official suggestions platform:
> 
> * https://bugs.telegram.org/c/1377
> * https://bugs.telegram.org/c/3342

But Telegram X is an official Telegram app though and it have this option as "Send as a copy"

**Comment by RememberTheAir** [comment]
Telegram X's developer is given the freedom to experiment and test different approaches to UX and standard telegram features. TGX is not supposed to be as strictly consistent to a standard features set and UX as other official clients, so it has some features that its dev thought that might be convenient that other official apps don't
