### ISSUE TITLE
JSON Exports quotation marks incorrectly

### ISSUE THREAD

**Issue by Daan1241** [telegramdesktop/tdesktop#8573]
### Steps to reproduce
1. Go to Settings > Advanced > Export Telegram Data
2. Select any of the chat export options
3. Change Location and format export type to "Machine-readable JSON"
4. After exporting, open the "results.json" file in a text editor

### Expected behaviour
The exported JSON should properly escape all quotation marks

### Actual behaviour
I noticed that messages that include double quotation marks are not properly escaped.

A message should appear like this:
```json
      {
      "id": XXXX,
      "type": "message",
      "date": "2019-05-31T21:28:30",
      "from": "Daan",
      "from_id": XXXXXXXXX,
      "text": "This message has \"Quotation Marks\" that are properly escaped"
      },
```

However, the exported JSON contains messages this way:

```json
      {
      "id": XXXX,
      "type": "message",
      "date": "2019-05-31T21:28:30",
      "from": "Daan",
      "from_id": XXXXXXXXX,
      "text": "This message has "Quotation Marks" that are improperly escaped, and will cause errors"
      },
```

### Configuration
**Windows 10**
v10.0.18363 Build 18363

**Version of Telegram Desktop:**
v2.3.1

**Used theme**:
Tinted

**Comment by 23rd** [comment]
Unfortunately, I can't reproduce your problem.

**Comment by Aokromes** [comment]
@Daan1241 can you try on 2.4.2?

**Comment by Daan1241** [comment]
The problem does not occur anymore with version 2.4.2.

```json
{
   "id": XXXXXX,
   "type": "message",
   "date": "2020-10-05T13:15:39",
   "from": "Daan",
   "from_id": XXXXXXXXXX,
   "text": "\" '"
  }
```

**Comment by afwn90cj93201nixr2e1re** [comment]
@Aokromes remove label
