### ISSUE TITLE
Cropped screenshots "uncrop" when sent.

### ISSUE THREAD

**Issue by itsmemarius** [telegramdesktop/tdesktop#8577]
### Steps to reproduce
1. Take a screenshot 
2. Crop it
3. Send 

### Expected behaviour
After saving the cropped screenshot it shouldn't restore when sent.

### Actual behaviour
The sent screenshot restores to the previous edit.

### Configuration
**Operating system:**
Windows 10

**Version of Telegram Desktop:**
 2.3.1
**Installation source (Linux Only)** - the official website / GitHub releases / flatpak / snap / distribution package:

**Used theme**:
Night Mode
<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by ilya-fedin** [comment]
What do you mean?

**Comment by itsmemarius** [comment]
On Wed 9. Sep 2020 at 23:50, ilya-fedin <notifications@github.com> wrote:

>
>
> What do you mean?
>
> If take a screenshot, then crop  and save it, i send it.The problem is
> that even if the photo has been edited(cropped) telegram somehow undoes the
> last edit.

P.S other messaging apps do not do that.

**Comment by ilya-fedin** [comment]
> If take a screenshot, then crop and save it, i send it.The problem is that even if the photo has been edited(cropped) telegram somehow undoes the last edit.

I guess you just forgetting to copy it, that's impossible

**Comment by Aokromes** [comment]
1 month without answer, if this bug is still valid open a new ticket.
