### ISSUE TITLE
Linux : GtK theme is not being Reflecting

### ISSUE THREAD

**Issue by Xanaxus** [telegramdesktop/tdesktop#8578]
### Steps to reproduce
1. Use the Linux Desktop app
2. 
3. 

### Expected behaviour
The app should take the theme applied to the entire system.
![image](https://user-images.githubusercontent.com/53279068/92677524-af700780-f341-11ea-86e5-9452b0856dbf.png)

### Actual behaviour
I get the default theme
![image](https://user-images.githubusercontent.com/53279068/92677575-cdd60300-f341-11ea-8e07-5f8a4ed09ff8.png)

### Configuration
**Operating system:** Linux : popOs

**Version of Telegram Desktop:** the latest 

**Installation source (Linux Only)** - the official website / GitHub releases / flatpak / snap / distribution package: 
https://pop.system76.com/

**Used theme**:
mac os  https://github.com/vinceliuice/Mojave-gtk-theme

**Comment by ilya-fedin** [comment]
Telegram doesn't aim to have look&feel like the rest of the system, this is not a bug.
