### ISSUE TITLE
Cannot record voice message using Kinect v1 USB Microphone Array while it works fine in calls settings

### ISSUE THREAD

**Issue by barfin** [telegramdesktop/tdesktop#8579]
### Steps to reproduce
1. Use the official drivers with kinect v1: https://www.microsoft.com/en-us/download/details.aspx?id=40278
2. Try recording a voice
3. Fail

### Expected behaviour
It should start recording

### Actual behaviour
Tell us what happens instead

### Configuration
**Operating system: Windows 10 version 2004**

**Version of Telegram Desktop: 2.3.1**

<details><summary><b>Logs</b>:</summary>
Logs:
[log.txt](https://github.com/telegramdesktop/tdesktop/files/5199409/log.txt)
</details>

<details><summary><b>Video</b>:</summary>
Video:
[](https://www.youtube.com/watch?v=dc985nAsABQ)
</details>

**Comment by ilya-fedin** [comment]
Please get openal log
https://github.com/kcat/openal-soft/blob/master/docs/env-vars.txt

**Comment by barfin** [comment]
> 
> 
> Please get openal log
> https://github.com/kcat/openal-soft/blob/master/docs/env-vars.txt

Are you sure this is supposed to work in windows 10?
I've tried them like this, and it doesn't provide any log
![image](https://user-images.githubusercontent.com/37030489/92693014-3e891980-f35a-11ea-92a8-d48b7284a732.png)

**Comment by ilya-fedin** [comment]
Oh, you don't need to set these variables here

You should set them in command line like that:
```
set ALSOFT_LOGLEVEL=3
set ALSOFT_LOGFILE=C:\Users\%USER%\telegram_openal.log
```
And start telegram from the same command line (don't forget to fully close telegram before this)

**Comment by barfin** [comment]
> 
> 
> Oh, you don't need to set these variables here
> 
> You should set them in command line like that:
> 
> ```
> set ALSOFT_LOGLEVEL=3
> set ALSOFT_LOGFILE=C:\Users\%USER%\telegram_openal.log
> ```
> 
> And start telegram from the same command line (don't forget to fully close telegram before this)

[telegram.txt](https://github.com/telegramdesktop/tdesktop/files/5200076/telegram.txt)

**Comment by ilya-fedin** [comment]
`AL lib: (EE) ALCwasapiCapture_resetProxy: Failed to get matching format, wanted: Mono Signed Short 48000hz, got: 4 channels 32-bit 16000hz`

looks like driver can't switch to the mode requested by Telegram

**Comment by barfin** [comment]
> 
> 
> `AL lib: (EE) ALCwasapiCapture_resetProxy: Failed to get matching format, wanted: Mono Signed Short 48000hz, got: 4 channels 32-bit 16000hz`
> 
> looks like driver can't switch to the mode requested by Telegram, maybe you need to switch it manually

![image](https://user-images.githubusercontent.com/37030489/92787071-0287a000-f3be-11ea-9a48-506ba31ef049.png)
it can't be changed, why can't telegram just support this mode instead?

**Comment by ilya-fedin** [comment]
> why can't telegram just support this mode instead?

Because it will require a lot of work I guess

**Comment by barfin** [comment]
> 
> 
> > why can't telegram just support this mode instead?
> 
> Because this will require a lot of work I guess

but it's already working in calls

**Comment by ilya-fedin** [comment]
> but it's already working in calls

Calls are using google's webrtc library that does a lot of things on its own, including audio output.
