### ISSUE TITLE
Telegram updates even when autoupdate is off

### ISSUE THREAD

**Issue by KES777** [telegramdesktop/tdesktop#8580]
### Steps to reproduce
1.  Turn off autoupdate
2. Wait few weeks

### Expected behaviour
Telegram should not updated

### Actual behaviour
Telegram occasionally updates (probably because it downloads new version earlier, before turning autoupdate off)

### Configuration
**Operating system:**
Linux Mint 19.3

**Version of Telegram Desktop:**
2.2

**Installation source (Linux Only)** - the official website / GitHub releases / flatpak / snap / distribution package:
tar.gz

**Used theme**:
default

I already downgrade telegram [here](https://github.com/telegramdesktop/tdesktop/issues/8472#issuecomment-678943860) and turn off autoupdate
![image](https://user-images.githubusercontent.com/799021/92701477-b6564480-f358-11ea-9a9d-81c9df314b28.png)

But it occasionally updated again.... How?? I do not press update button, autoupdate is turned off alse!

**Comment by KES777** [comment]
Can you tell me please where telegram downloads new versions and stores locally. I will delete them all

**Comment by john-preston** [comment]
@KES777 Maybe this happens after a crash.

**Comment by KES777** [comment]
Not always. Telegram sometimes craches. But I just run telegram again and all.

Today when user with is calling me, telegram crashed and starts to download. After that it starts to download new version

![_](https://user-images.githubusercontent.com/799021/92919951-18d34180-f43a-11ea-95e8-6e42a55e85d6.jpg)

For what I disable automatic updates? new version does now work at all. I can not hear users

**Comment by KES777** [comment]
hrrrr..... it even updates when I just close current 2.2 version it and start again.

**Comment by KES777** [comment]
How to reproduce:
I extract 2.2 version. 
run it
![image](https://user-images.githubusercontent.com/799021/92921279-749eca00-f43c-11ea-971a-1eb098842fa8.png)
when telegram started it suggest to update telegram
Without pressing "Update" go to setting and turn off updating
Turn off telegram
Run telegram

Actual: Telegram is updated
Expected: Telegram should not update

**Comment by fcore117** [comment]
I too have to revert to older version as new version brought annoyng unclosable call window when closed then call closes too.
https://github.com/telegramdesktop/tdesktop/issues/8459#issuecomment-680187353

Telegram should not automatically start downloading but there sould be option to ask. Maybe everyday users need auto update but pro users should have a choice.

**Comment by ilya-fedin** [comment]
#7215
