### ISSUE TITLE
Crashes with large message in draft

### ISSUE THREAD

**Issue by zennydance** [telegramdesktop/tdesktop#8586]
### Steps to reproduce
1. Put large message into message field (i used one with a lot of email addresses)
2. Telegram instantly crashes

### Expected behaviour
Nothing, just send a message.

### Actual behaviour
Telegram instantly crashed

### Configuration
Windows 10 1809

**Version of Telegram Desktop:** 2.3.1

**Installation source (Linux Only)** - the official website

**Used theme**: Default

<details><summary><b>Logs</b>:</summary>
Log file contains nothing related to this issue.
</details>

**Comment by ilya-fedin** [comment]
Crash report tag?

**Comment by Aokromes** [comment]
@zennydance

**Comment by Aokromes** [comment]
1 month without answer, if this bug is still valid open a new ticket.
