### ISSUE TITLE
Support Emacs keyboard shortcuts in macOS version

### ISSUE THREAD

**Issue by f-squirrel** [telegramdesktop/tdesktop#8587]
### Is your feature request related to a problem?
macOS supports Emacs keyboard shortcuts for editing text by default.
Many popular applications such as Google Chrome support this mode too.
For example `^-A` jumps at the beginning of the line, `^-E` to the end, `^-K` deletes the current line, etc.

### Describe the solution you'd like
I'd like Telegram for macOS to support Emacs keyboard shortcuts for text editing that are supported by macOS.
The list of available shortcuts:
https://www.hcs.harvard.edu/~jrus/site/system-bindings.html

**Comment by ilya-fedin** [comment]
This is a bugtracker for Telegram Desktop, Telegram for macOS is there: https://github.com/overtake/TelegramSwift

**Comment by f-squirrel** [comment]
@ilya-fedin , @Aokromes maybe I miss something but I use the macOS version of Telegram Desktop, not the separate application for macOS.
The application's about page has a link to this repository.

**Comment by ilya-fedin** [comment]
> I use the macOS version of Telegram Desktop

Oh, there are a lot of people that confusing the apps, sorry
