### ISSUE TITLE
Window position and size remembered incorrectly Xorg vs Wayland

### ISSUE THREAD

**Issue by kode54** [telegramdesktop/tdesktop#8588]
### Steps to reproduce
1. Open the app in a Gnome Xorg session on a 200% or larger scaled desktop.
2. Size it how you want.
3. Log out.
4. Open the app again in a Wayfire session with the same desktop scale.

### Expected behaviour
The app should remember its size and position independent of desktop scaling settings.

### Actual behaviour
The app stores Xorg window position and size pre-scaled, so when switching to a Wayland session, the window becomes huge and often overflows the screen. This is as a result of the Wayland session expecting window position and size in unscaled coordinates. Conversely, when switching back from Wayland to Xorg, the window is half as large (at 200% scale) as it was under Wayland.

### Configuration
**Operating system:** Arch Linux

**Version of Telegram Desktop:** 2.3.2-2

**Installation source (Linux Only)** - the official website / GitHub releases / flatpak / snap / distribution package: Official Arch Linux package.

**Used theme**: Under Gnome, Adwaita Dark. Under Wayfire, it's using the KDE theme I think? Or whatever native client decorations TDesktop uses.

**Comment by ilya-fedin** [comment]
There are in-app scaling, if you set it to 200% manually, it will be 200% until you set 100% and this is not a bug.

And there is no API to set or get position on Wayland, so position is not a Telegram bug.

**Comment by kode54** [comment]
I don't know about that, but there is an API to set the window size. And the scale is set to 200% in both cases, because Telegram is scaling itself to match the system settings.
