### ISSUE TITLE
[Feature Request] Export doesn't include the current day, even when selected

### ISSUE THREAD

**Issue by 64kramsystem** [telegramdesktop/tdesktop#8589]
### Is your feature request related to a problem?

It's not possible to make an export of the current day. While it's possible to select the current day as upper limit, the export won't include messages for it.

### Describe the solution you'd like

It's not clear if:

- the upper limit date should be included in general, or
- the widget should be allowed to include the day after the current date, so that exported messages will include thos in the current date

### Describe alternatives you've considered

There's no way to export the current day, unfortunately.

### Additional context

(no context, the issue is very simple)

**Comment by RememberTheAir** [comment]
**
![image](https://user-images.githubusercontent.com/16143208/92878013-fe826f00-f40b-11ea-9e94-5b87013ccd3a.png)
**

This works (from: current date; to: present)

**Comment by saveriomiroddi** [comment]
> ![image](https://user-images.githubusercontent.com/16143208/92878013-fe826f00-f40b-11ea-9e94-5b87013ccd3a.png)
> 
> This works (`from: current date, to: present` will export only today's messages)

Hello! Sorry, I made some confusion. I've rectified the title and description to describe the problem accurately.

The issue is not that the present day is not included, but that the messages for the present day are not included in the export.

**Comment by NightMachinary** [comment]
[**@Saverio Miroddi**](https://github.com/saveriomiroddi) commented on [Sep 11, 2020, 10:42 AM GMT+4:30](https://github.com/telegramdesktop/tdesktop/issues/8589#issue-698886745 "2020-09-11T06:12:16Z - Replied by Github Reply Comments"):
> ### Is your feature request related to a problem?
> 
> It's not possible to make an export of the current day. While it's possible to select the current day as upper limit, the export won't include messages for it.
> 
> ### Describe the solution you'd like
> 
> It's not clear if:
> 
> *   the upper limit date should be included in general, or
> *   the widget should be allowed to include the day after the current date, so that exported messages will include thos in the current date
> 
> ### Describe alternatives you've considered
> 
> There's no way to export the current day, unfortunately.
> 
> ### Additional context
> 
> (no context, the issue is very simple)

I just tried this, and it included today's messages for me.

**Comment by saveriomiroddi** [comment]
I've just verified it with a different chat, and still happens. Specifically, I set the export interval from yesterday (Sep/17 2020) to today (Sep/18/2020), and only the messages from yesterday have been exported.

I'm on Linux, with the up to date client version (2.3.2).

**Comment by afwn90cj93201nixr2e1re** [comment]
It's not a bug i guess @Aokromes, it's mostly seems like feature request, coz logicaly range FROM - TO is exactly FROM - TO, but guy need FROM - TO + 1, like including this day too, so, yeah, 'present' should stay as TODAY + 24hr. to fix the problem, i guess in GUI present should be presented as new key in calendar.

**Comment by saveriomiroddi** [comment]
> It's not a bug i guess @Aokromes, it's mostly seems like feature request, coz logicaly range FROM - TO is exactly FROM - TO, but guy need FROM - TO + 1, like including this day too, so, yeah, 'present' should stay as TODAY + 24hr. to fix the problem, i guess in GUI present should be presented as new key in calendar.

This being a bug or a feature request depends ultimately on the option to export the present day being a requirement or not. I personally don't see any reason why a user should not be able to export the present day.

I've checked other clients with similar concepts, google mail and thunderbird, and:

1. instead of "from/to", they use the unambiguous "after/before"; this in not necessarily better or wrong, but reduces the ambiguity
2. they use open intervals on both sides
3. they don't limit the dates on the right side (before)

Interestingly, point 2. reveals another, separate, bug - the Telegram client is inconsistent. The interval is closed on the left (after) and open on the right (before).

**Comment by afwn90cj93201nixr2e1re** [comment]
Im not against at all.

**Comment by afwn90cj93201nixr2e1re** [comment]
Im not against at all. Coz after writing this comment i faced with same stuff, LMAO.
