### ISSUE TITLE
[Question] How do I increate tray icons size in Ubuntu 20.04

### ISSUE THREAD

**Issue by teverus** [telegramdesktop/tdesktop#8590]
Dear @ilya-fedin , in this bug report https://github.com/telegramdesktop/tdesktop/issues/7774 you wrote
> That means that your tray is 16x16 size. Increase it to 22x22 at least.

Could you please tell me how can I increate the size of my tray icons from 16x16 to 22x22?

**Comment by ilya-fedin** [comment]
> Could you please tell me how can I increate the size of my tray icons from 16x16 to 22x22?

I don't know, ask other extension users
