### ISSUE TITLE
sended and recerved messages in one collumn

### ISSUE THREAD

**Issue by SmOkEnksp** [telegramdesktop/tdesktop#8593]
how to setup theme for sended and recerved messages in one collumn?

**Comment by ilya-fedin** [comment]
this bugtracker is english only

**Comment by SmOkEnksp** [comment]
> this bugtracker is english only

edited.

**Comment by ilya-fedin** [comment]
> how to setup theme for sended and recerved messages in one collumn?

Window size should be wide enough for this (i don't know what "enough" is though)

**Comment by SmOkEnksp** [comment]
> > how to setup theme for sended and recerved messages in one collumn?
> 
> Window size should be wide enough for this (i don't know what "enough" is though)

oh thank you so much. i resized window and it's work's. Have a good day!
