### ISSUE TITLE
Draft sync across devices leading to data loss

### ISSUE THREAD

**Issue by kshitijpurwar** [telegramdesktop/tdesktop#8595]
### Steps to reproduce
1. Open Telegram in 2 devices (Desktop, D & Mobile, M)
2. Write a draft in "Saved Messages" (I guess, would work for any chat though) on D, it would sync on M in a couple of seconds 
3. **BUG** Sometimes it takes time to sync & the draft written on D is not yet on M. In this while, if you type a new draft on M, the sync kicks in & delete the old draft on D!
4. The old draft on D, gets replaced by the new draft from M & message is lost forever

### Expected behaviour
The data should not be ideally overwritten/replaced & the old draft should be retained in case the drafts are different

### Actual behaviour
Creation of draft on the other device can in some cases, where sync is lagging, can lead to deletion of draft on another device.

### Configuration
**Operating system:**
Mac OS Catalina, V 10.15.6

**Version of Telegram Desktop:**
2.3.1

**Installation source (Linux Only)** - the official website / GitHub releases / flatpak / snap / distribution package:

**Used theme**:
Tinted

<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by ilya-fedin** [comment]
#4922

**Comment by kshitijpurwar** [comment]
Shouldn't be closed!

@ilya-fedin @Aokromes Not a duplicate issue as #4922 as it does not mention the bug with drafts. The problem I mentioned is with sync-algo when it sees conflicting content.

**Comment by ilya-fedin** [comment]
@kshitijpurwar the cause is draft in that issue too, there is no sense to leave open two almost exact issues
