### ISSUE TITLE
Opening images in default monitor

### ISSUE THREAD

**Issue by jamesRUS52** [telegramdesktop/tdesktop#8596]
### Steps to reproduce
1. Two or more installed monitors (I have laptop with 3 additional monitors connected via dock station)
2. One of these monitor installed as default in Windows 10
3. Telegram Desktop open in default monitor
4. Open attached image in any chat
5. Image window appears in laptop (NON default monitor)

### Expected behaviour
Image window should appears in default monitor (or where Telegram desktop currently opened)

### Actual behaviour
Image window appears in monitor which not included current instance of Telegram desktop

### Configuration
Windows 10

2.3.1

**Comment by ilya-fedin** [comment]
Media viewer is created on the same screen where the main window is placed: https://github.com/telegramdesktop/tdesktop/blob/e009ac026d32b39b96899badb71da1350db3457c/Telegram/SourceFiles/media/view/media_view_overlay_widget.cpp#L406-L413

**Comment by ilya-fedin** [comment]
#5126
