### ISSUE TITLE
Telegram does not care about VPNs.

### ISSUE THREAD

**Issue by Master811129** [telegramdesktop/tdesktop#8600]
### Steps to reproduce
1. Start a VPN like <a href="https://getlantern.org/en_US/index.html" target= "_blank" >lantern</a> 
2. Telegram does not care about VPN. and does not connect (I can connect with a MTProto Proxy.).

### Actual behaviour
Telegram must work with VPN when you set it on use system proxy settings.

### Configuration
**Operating system:**

**Version of Telegram Desktop:*2.2*

**Installation source (Linux Only)** -  snap / distribution package: Ubuntu

**Used theme**:dark

PS: I do not have this problem in Windows 10 or even <a href="https://www.winehq.org/" target="_blank">Wine</a>XTelegram.exe in Linux.

**Comment by ilya-fedin** [comment]
#8432?

**Comment by NightMachinary** [comment]
How you set the proxy settings correctly in Telegram? It works for me on macOS with HTTP, SOCKS, and MTPROTO.
