### ISSUE TITLE
Call Pop-ups still appear and play a load ringtone even if you disable notifications and mute the contact

### ISSUE THREAD

**Issue by H-A-L-I-S** [telegramdesktop/tdesktop#8601]
### Steps to reproduce
1. Disable Notifications
2. Mute a contact
3. Ask that contact to call you

### Expected behaviour
-No notifications and no sounds/ringtones, when notifications are disabled
-No notifications and no sounds/ringtones, when contact is muted

### Actual behaviour
-Call Pop-ups still appear and and play a loud ringtone even if you:
-disable notifications and 
-mute the contact

### Configuration
**Operating system:**
Kubuntu 20.04

**Version of Telegram Desktop:**
2.1.7 (distribution package) and 2.2 (snap)

**Installation source (Linux Only)**
distribution package and snap

**Used theme**:
The standard one

### Suggestions
-Add Option to disable/mute calls as it is requested in other issues
-How to fix:  Ask for permission to copy the code from [kirsan31](https://github.com/kirsan31/tdesktop)
-#3382 #3594 #8199 #4002 (deleted)

**Comment by ilya-fedin** [comment]
Mute option doesn't block calls, there are privacy settings for that

**Comment by H-A-L-I-S** [comment]
> Mute option doesn't block calls, there are privacy settings for that

On android client you get:
- no notification or loud ringtone, if notifications are muted
- no notification or loud ringtone, if you have muted the contact

While in desktop client you get:
- pop up notification, that you can not minimize, because it is `always on top`, even if you mute the contact & disable notifications
- loud ringtone playing, even if you mute the contact & disable notifications
- no matter what you do, there is no way to silence or hide telegram desktop unless you close telegram or disable calls entirely

**Comment by ilya-fedin** [comment]
> no matter what you do, there is no way to silence or hide telegram desktop unless you close telegram or disable calls entirely

That's a lie, you can block calls in privacy settings

**Comment by H-A-L-I-S** [comment]
> > no matter what you do, there is no way to silence or hide telegram desktop unless you close telegram or disable calls entirely
> 
> That's a lie, you can block calls in privacy settings

Sorry, I think, I made a misunderstanding. I mean with disable=block. Here is the correct version:
- there is no way to silence or hide telegram desktop unless you close telegram or disable/block _incomming_ calls entirely

It is no big problem for me, because I close Telegram very fast if someone is calling me, but I think for other people, this can be a big problem, if Telegram pops-up in the middle of a meeting or a conference. Just wanted to mention it, because there are many reddit threads about it, but no open issue in Telegram

**Comment by ilya-fedin** [comment]
Hmm, no, there are already present an issue for this: #3594
This is a duplicate.

**Comment by H-A-L-I-S** [comment]
That's true. However #3594 does not contain the information, that muted contacts can disturb you with telegram calls.
#3594 is a feature request
#8601 (this) is a bug report

**Comment by ilya-fedin** [comment]
> However #3594 does not contain the information, that muted contacts can disturb you with telegram calls.

Add theb

> (this) is a bug report

This is not a bug, so should be a feature request anyway

**Comment by H-A-L-I-S** [comment]
> This is not a bug, so should be a feature request anyway

Are you sure about that: _a muted chat is **not** muted_

It is your project, not my, so you decide, what you classify as bug. I am just reporting what seems to be a bug for me :)
