### ISSUE TITLE
[Feature Request] Long pressing the command in mobile

### ISSUE THREAD

**Issue by SmartManoj** [telegramdesktop/tdesktop#8603]
It will paste the command in the message box without sending.

### Describe the solution you'd like
Use ctrl+click to simulate the feature

**Comment by ilya-fedin** [comment]
Already present, choose the command and press tab.

**Comment by SmartManoj** [comment]
@ilya-fedin When in a message.

**Comment by ilya-fedin** [comment]
> When it a part of a message text.

I didn't understand what you want to say

**Comment by SmartManoj** [comment]
![image](https://user-images.githubusercontent.com/7231077/93693000-b0f6b800-fb17-11ea-96f3-3159e9821030.png)
For /newfed command, there is no use in clicking it. @ilya-fedin

**Comment by ilya-fedin** [comment]
I was thinking you're talking about this
![image](https://user-images.githubusercontent.com/17829319/93717306-7a935a00-fb64-11ea-8544-be54ab52d4fa.png)
