### ISSUE TITLE
Exception 0xc000041d at any moment, the reason is unknown

### ISSUE THREAD

**Issue by sngrl** [telegramdesktop/tdesktop#8606]
### Steps to reproduce
Just using Telegram Desktop in regular mode. It is not possible to identify the cause or dependence of the error.

### Expected behaviour
The application should work stably, without crashes.

### Actual behaviour
The application crashes for no apparent reason, at any time. Happens several times a day.
Lines from Windows Events Viewer:

> Имя сбойного приложения: Telegram.exe, версия: 2.3.1.0, метка времени: 0x5f40efab
> Имя сбойного модуля: unknown, версия: 0.0.0.0, метка времени: 0x00000000
> Код исключения: 0xc000041d
> Смещение ошибки: 0x8c001400
> Идентификатор сбойного процесса: 0x380c
> Время запуска сбойного приложения: 0x01d68d06d0e9feb3
> Путь сбойного приложения: C:\Soft\Telegram Desktop\Telegram.exe
> Путь сбойного модуля: unknown
> Идентификатор отчета: 351c42af-52a2-458f-b34e-df570f01fedb
> Полное имя сбойного пакета: 
> Код приложения, связанного со сбойным пакетом: 

### Configuration
**Operating system:**
Windows 10, last update

**Version of Telegram Desktop:**
2.3.1

**Used theme**:
Classic

**Link to dump file from Telegram Desktop/tdata/dumps/:**

[e3e0ffcb-5a11-4464-a229-2bac95cabdfe.zip](https://github.com/telegramdesktop/tdesktop/files/5240772/e3e0ffcb-5a11-4464-a229-2bac95cabdfe.zip)

**Comment by john-preston** [comment]
I see this in the crash dump debugging:

![image](https://user-images.githubusercontent.com/17900494/93504862-1fc2ee00-f92b-11ea-97b7-77cb93849893.png)

Unfortunately, I have no idea, what could be a cause of such crash :(

**Comment by ilya-fedin** [comment]
Maybe OOM crash?
