### ISSUE TITLE
[Feature Request] XML layout for each language

### ISSUE THREAD

**Issue by MuratKaribay** [telegramdesktop/tdesktop#8607]
Hi, is it possible to add an XML layout for each language?
At the moment, I am translating Telegram into Kazakh and faced the problem that when translating the word "Unread" into Kazakh "Оқылмаған", one letter moved down, as shown in the screenshot below.
Can this problem be solved?

![image](https://user-images.githubusercontent.com/40431755/93518212-5827f380-f94e-11ea-84d7-9a77924507f0.png)

**Comment by ilya-fedin** [comment]
> Hi, is it possible to add an XML layout for each language?

What do you mean?

**Comment by MuratKaribay** [comment]
> What do you mean?

Add xml files with interface parameters for each language

**Comment by ilya-fedin** [comment]
> Add xml files with interface parameters for each language

What XML file are you talking about?

**Comment by MuratKaribay** [comment]
> What XML file are you talking about?

Is it possible to add a function to change the interface when changing the language?
Because as shown in the screenshot above, sometimes transfers do not fit into the telegram interface.
Is it possible to add such a function?

**Comment by MuratKaribay** [comment]
> What XML file are you talking about?

As shown in the screenshot above, some translation lines do not fit into the telegram interface.
Is it possible to add a function that will change the interface when changing the language?

**Comment by ilya-fedin** [comment]
> Is it possible to add such a function?

no, i don't think so

**Comment by MuratKaribay** [comment]
> no, i don't think so

Now what do you advise me to do with a letter that doesn't fit?
