### ISSUE TITLE
Crash on opening dialog with bunch of same naming media

### ISSUE THREAD

**Issue by zepkano** [telegramdesktop/tdesktop#8608]
Hi! I am using Saved Messages as little media storage for my video/gif/etc draft-media. Time to time I render video with naming kind of "0001_{frames}" and drag'n'drop it to my dialog. Telegram starts crashing after I repeat this process 3 or 4 times with same-naming-videos.

Cleared cache preventing crash for first time opening, but after reopening TG it crashes again.  

Btw, this "broken" Saved Messages works just fine with android build. 

### Steps to reproduce
1. Drag'n'drop video in Saved Messages from storage
2. Take another shot of video with same naming
3. Drag'n'drop new video 
4. Reload Telegram
5. Open Saved messages
6. Repeatly open uploaded before media

### Expected behaviour
No crashes.

### Actual behaviour
Crash after opening one of the videos. Dumps empty.

### Configuration
**Operating system: Win10 2004

**Version of Telegram Desktop:** 2.3.1

**Used theme**: Dark

<details><summary><b>Logs</b>:</summary>
[TGlogsWithFilePath.txt](https://github.com/telegramdesktop/tdesktop/files/5241699/TGlogsWithFilePath.txt)
[TGlogsWithoutFilePath.txt](https://github.com/telegramdesktop/tdesktop/files/5241719/TGlogsWithoutFilePath.txt)
</details>

**Comment by ilya-fedin** [comment]
#7361
