### ISSUE TITLE
Unable to download/Export Telegram data.

### ISSUE THREAD

**Issue by ukistoxic** [telegramdesktop/tdesktop#8609]
![Screenshot (13)](https://user-images.githubusercontent.com/71468315/93528412-e94f9800-f957-11ea-912e-5b2054aa48a9.png)

### Steps to reproduce
1. Go to Telegram Desktop> Settings> Advance> Export telegram data
2. Approve the request using mobile. then Wait for 24 hours 
3. after 24 hours download the data using same step above

### Expected behaviour
I requested for an export of my telegram data one night using my laptop on telegram windows application. I use windows 10. according to the rules I had to wait for 24 hours to download/export my data using the device which i used while requesting. so the next day when I was trying to download the data by following the steps. But it did not happened. After certain moment of initialization a dialogue box appeared which showed the message as seen in the screenshot provided with this submission. 

### Actual behaviour
when I clicked on the option to export data. then After certain moment of initialization a dialogue box appeared which showed the message as seen in the screenshot provided with this submission. that's all. Hence, now i am unable to download or export the data. help me.

### Configuration
**Operating system:** Windows 10 pro

**Version of Telegram Desktop:** version 2.3.1

**Installation source (Linux Only)** - the official website / GitHub releases / flatpak / snap / distribution package:

**Used theme**: Dark

<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by john-preston** [comment]
@ukistoxic Does this happen if you export it again?

**Comment by ukistoxic** [comment]
> @ukistoxic Does this happen if you export it again?

Yes. It does.

**Comment by ukistoxic** [comment]
Issue fixed. The reason why it was showing error because I had selected those group and channels chats as well in which were private and I wasn't the admin of that group. So, I unchecked all the channels and groups then when proceeded I successfully exported the data.
