### ISSUE TITLE
Search chat history strict to current conversation

### ISSUE THREAD

**Issue by kokizzu** [telegramdesktop/tdesktop#861]
Is there any search history feature?

**Comment by Katzen-Gott** [comment]
Yeah. Search box above contacts list performs history search.

**Comment by kokizzu** [comment]
Ah i see, but the search is not strict to current (private/group)
conversation.

On 29 June 2015 at 15:55, Alissa Kvashina <notifications@github.com> wrote:

> Yeah. Search box above contacts list performs history search.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/telegramdesktop/tdesktop/issues/861#issuecomment-116534929>
> .
>



-- 
Best Regards,
Kiswono P
GB

**Comment by auchri** [comment]
Added in 0.8.48
