### ISSUE TITLE
Add option to not crop frame in video call

### ISSUE THREAD

**Issue by Moldoteck** [telegramdesktop/tdesktop#8610]
Now, on video call, video from laptop is cropped as in smartphones. This can be a problem if there are more than one person in the frame. Please, add an option to avoid cropping the video

**Comment by turcandan** [comment]
It seems that other platforms do not crop the field of view at all, so it is possible not to crop the content.

**Comment by s-light** [comment]
my feeling is that Telegram on Linux Desktop *thinks* there are only *Vertical* Videos out there ;-)
or something similar...

**Comment by s-light** [comment]
anybody any more detailed information?

**Comment by s-light** [comment]
ping

**Comment by s-light** [comment]
just tested this.
i think it is now working - and the full view is visible.
#close

**Comment by khunpoum** [comment]
v. 4.3.1
my USB Video camera is 16:9 ratio landscape
Initial video is no cropped
if stop and start video - then video is strange cropped 
need to option in settings for have ability to select how exactly need cropped or rotate video - for example if i want rotate camera from landscape to portrait orientation
