### ISSUE TITLE
Link preview sometimes not working

### ISSUE THREAD

**Issue by Gollam** [telegramdesktop/tdesktop#8611]
### Steps to reproduce
1. Paste this link in TG desktop: https://www.facebook.com/torok.szilard/videos/10224698497315183/
2. wait for preview to load

### Expected behaviour
Video preview should be shown

### Actual behaviour
No preview is being loaded

### Configuration
**Operating system:**
Windows 10

**Version of Telegram Desktop:**
2.3.1

**Used theme**:
Classic

Working link: https://www.facebook.com/nifzrt/videos/670968320189828/
Not working link: https://www.facebook.com/torok.szilard/videos/10224698497315183/

I have checked the source code for both URL-s, and they contain exactly the same kind of OG tags, so I think it is not a server side problem.

![image](https://user-images.githubusercontent.com/765342/93562877-254e2180-f987-11ea-9a8f-c0c1c139f71f.png)

**Comment by john-preston** [comment]
@Gollam If you send this link, does the preview appear after you send it?

**Comment by Gollam** [comment]
@john-preston no, I cannot make the preview show, no matter how hard I try. I even used webpage bot to update the preview, it can update for the first one, but nothing is shown for the second one.

![image](https://user-images.githubusercontent.com/765342/93565157-2bde9800-f98b-11ea-8703-118f2b809aee.png)

**Comment by tibberg** [comment]
@john-preston doesn't work for me either

**Comment by klonwar** [comment]
Same problem with Yandex Music. It worked for a while, then it stopped

![image](https://user-images.githubusercontent.com/12374932/107176540-b8443280-69e0-11eb-802c-76ae7762f091.png)

**Comment by MalikDE** [comment]
Same here with multiple Facebook previews.
+ previews that were working and currently displayed, stopped being displayed if link is copy/paste somewhere in Telegram.

**Comment by New-dev0** [comment]
Is `cdn(1/any).telesco.pe` is suppose to show preview? 
or will be better? 
since t.me/ urls uses it internally in web

**Comment by Gollam** [comment]
There are still many links which cannot be previewed properly.

**Comment by Gollam** [comment]
There are still many links which cannot be previewed properly.

**Comment by john-preston** [comment]
If you write a message, send it and no link preview (or incorrect link preview) appears - the Telegram Desktop (or any other client) app can't do anything about that. Everything is done by the server (links parsing, choosing a link, generating a preview), the client only sends a flag whether the server should _not_ add a preview or should do what it can.

So this looks like a bug for https://bugs.telegram.org, not for this issue tracker.
