### ISSUE TITLE
[BUG] Typing lots of periods (.) in chats causes CPU usage to skyrocket.

### ISSUE THREAD

**Issue by Mirsario** [telegramdesktop/tdesktop#8612]
My friend just noticed this hilarious bug, and we reproduced it on ~4 PCs in total. I searched through issues, and haven't found a similar report. Only periods seem to trigger this, no other symbol.

# Steps to reproduce
1. Type periods (........) in any chat. No need to send the messages.

### Expected behaviour
Typing should not affect performance.

### Actual behaviour
The CPU usage skyrockets up to 100% and stays there for a minute. While it's up, no stickers, avatars or other images load.

### Video
If you can open streamable (it's blocked in Russia and India), here's a video: **https://streamable.com/iwhdvp**

### Configuration
**Operating system:** `Windows 10 x86_64`

**Version of Telegram Desktop:** `2.3.1`

**Used theme**: `Tinted`

Logs don't seem to matter, I'm sure that everyone can reproduce this, at least on Windows.

**Comment by ilya-fedin** [comment]
#7952
