### ISSUE TITLE
Primary selection clipboard broken on wayland

### ISSUE THREAD

**Issue by danog** [telegramdesktop/tdesktop#8615]
### Steps to reproduce
1. Select text inside of tdesktop
2. Inspect the selection buffer with `wl-clip -o -selection`

### Expected behaviour
`wl-clip` returns the selected text

### Actual behaviour
`wl-clip` returns the text last selected in an app that supports the selection buffer wayland protocol.

By the way, it seems [qtwayland#5ec182df699041699f514d164a161c299fde5d19](https://github.com/qt/qtwayland/commit/5ec182df699041699f514d164a161c299fde5d19) has a fix for this.

### Configuration
**Operating system:** Arch Linux

**Version of Telegram Desktop:** 2.3.2

**Installation source (Linux Only)** - distribution package:

**Comment by ilya-fedin** [comment]
> By the way, it seems [qtwayland#5ec182df699041699f514d164a161c299fde5d19](https://github.com/qt/qtwayland/commit/5ec182df699041699f514d164a161c299fde5d19) has a fix for this.

I you're using distribution package, tdesktop can't influence on your Qt

If you want to use Qt with patches from tdesktop, you should download the official binary.

**Comment by ilya-fedin** [comment]
I don't think primary selection is important enough to backport it to tdesktop's Qt though

**Comment by ilya-fedin** [comment]
Should be fixed on 2.4.8 due to Qt update

**Comment by danog** [comment]
Yep, works nicely.
Thanks!
