### ISSUE TITLE
[Question] How to create a spell checker dictionary  in TD ?

### ISSUE THREAD

**Issue by Mohammed-Laith** [telegramdesktop/tdesktop#8616]
Hello!
How to create a spell checker dictionary for Telegram Desktop ?
I've seen several ones, but I can't see any for the Arabic language, there's a one for Farsi, although these two languages are not identical, but they use the (mostly) same alphabet and are somehow related, but again, not identical, so, we can't use the Farsi one for the Arabic language, ofcourse.
So, how to create a dictionary for the Arabic language ?
Thanks in advance.

**Comment by 23rd** [comment]
I'm sorry, but there is no such possibility at the moment.
There is one tricky way to replace the dictionary file, but it may not be safe to use.
I think in the future one of the next versions will have an ability to use your own dictionaries.

**Comment by Mohammed-Laith** [comment]
> I'm sorry, but there is no such possibility at the moment.
> There is one tricky way to replace the dictionary file, but it may not be safe to use.
> I think in the future one of the next versions will have an ability to use your own dictionaries.

I would like to participate to make an official version of the Arabic language dictionary that come with future versions of TD, I don't want it to be something "own", I want it to be just like any other language; like the English, Hebrew, German or any other of those that we see them on the dictionaries list. Could you allow me to do such thing please?
