### ISSUE TITLE
[Linux] [Snap] Cannot Add Dictionary.

### ISSUE THREAD

**Issue by ghost** [telegramdesktop/tdesktop#8617]
-->
### Steps to reproduce
1. Open the snap install of Telegram Desktop.
2. Go to the 'Manage Dictionaries' option.
3. Add an additional dictionary.

### Expected behaviour
The selected dictionary should be added and the number beside 'Manage Dictionaries' should change to '2'.

### Actual behaviour
The selected dictionary isn't added at all and the shown number remains unchanged (1).

### Configuration
**Operating system: Linux**

**Version of Telegram Desktop: 2.2.0-1-gfe639078a**

**Installation source (Linux Only)** - snap

**Used theme**: Night

**Comment by 23rd** [comment]
Unfortunately, I can't reproduce your problem on fresh install of Ubuntu.

**Comment by ilya-fedin** [comment]
> The selected dictionary isn't added at all and the shown number remains unchanged (1).

did you click "save" or "close" button in the dialog?

**Comment by 23rd** [comment]
Well, the author has turned into the ghost user…
