### ISSUE TITLE
[BUG] Telegram doesn't use his own Monospaced font

### ISSUE THREAD

**Issue by r3mis** [telegramdesktop/tdesktop#8619]
### Steps to reproduce
1. Open Telgeram
2. Open a Chat
3. Type something in Monospaced 

### Expected behaviour
The Monospaced Font should look like this:
![image](https://user-images.githubusercontent.com/52204908/93664731-60c51a80-fa71-11ea-9883-03d7c0ac7997.png)

### Actual behaviour
The Monospaced Font looks like this:
On Writing Bar
![image](https://user-images.githubusercontent.com/52204908/93664759-9d911180-fa71-11ea-9f66-6d7c0428122e.png)
In chat
![image](https://user-images.githubusercontent.com/52204908/93664776-b39ed200-fa71-11ea-93fe-7044a016df78.png)

### Configuration
**Operating system:** Artix Linux with Gnome 3.36.6 with X11 

**Version of Telegram Desktop:** 2.3.2

**Installation source (Linux Only)**: [telegram-desktop-bin on Arch Linux User Repository](https://aur.archlinux.org/packages/telegram-desktop-bin/)

**Used theme**: Telegram's default Night Mode Theme.

**Comment by ilya-fedin** [comment]
The second one is the right, this is not a bug

**Comment by r3mis** [comment]
Not really, Looks bad to me. Even the position is wrong:

![Screenshot from 2020-09-19 15-04-43](https://user-images.githubusercontent.com/52204908/93667970-e0f77a00-fa89-11ea-8294-8743254b76c4.png)

**Comment by ilya-fedin** [comment]
> Looks bad to me.

This is your opinion :man_shrugging:, but this is intended, Consolas is the preferred monospace font and the font on your screenshot is definitely Consolas

**Comment by r3mis** [comment]
But this doesn't resolve the Position Problem.

**Comment by ilya-fedin** [comment]
I guess this is your system's font rendering settings
