### ISSUE TITLE
Feature Request: Add the ability to ban users from groups

### ISSUE THREAD

**Issue by niklas-heer** [telegramdesktop/tdesktop#862]
This function absolutely crucial to operate a large Telegram group. The invitation link makes it possible for trolls to rejoin the group. There should really be an option to ban a user permanently from rejoining a group even tough he/she is invited again or clicks on the invite link.
Simply generating a new invite link does not help, because we publish the url in our forum.

**Comment by kenniki** [comment]
The API doesn't expose this, this isn't something that can be done in the client.
A bot (not using the bot API) might work for this.

Close this issue it's misplaced.

**Comment by niklas-heer** [comment]
Sorry my fault. I'll close this issue.
