### ISSUE TITLE
links with emojis have parsing problems

### ISSUE THREAD

**Issue by mrbesen** [telegramdesktop/tdesktop#8620]
### Steps to reproduce
1.  send this link to some one using tdesktop : ```http://🍞.thies-block.de/```
2. klick on the link

### Expected behaviour
It should convert the link to its punycode (protects the user against scams) (```http://xn--4i8h.thies-block.de/```)
and ask you, if you want to open it

### Actual behaviour
The link got converted to this: ```http://http//🍞.thies-block.de/``` (note the double http)

![image](https://user-images.githubusercontent.com/8640309/93669075-9b3eaf80-fa91-11ea-81c5-eefc2f649494.png)

### Configuration
**Operating system:**
Linux Mint 20 Cinnamon

**Version of Telegram Desktop:**
2.3.2

**Installation source (Linux Only)**:
the official website

**Used theme**:
not important

**Comment by ilya-fedin** [comment]
#2832
