### ISSUE TITLE
tg:// link in firefox focuses telegram but does nothing

### ISSUE THREAD

**Issue by txtsd** [telegramdesktop/tdesktop#8626]
### Steps to reproduce
1. Click on a tg:// link in firefox to join a group

### Expected behaviour
Telegram should focus and join the group

### Actual behaviour
Telegram focuses, but the group is neither opened nor joined

### Configuration
**Operating system:** Arch Linux

**Version of Telegram Desktop:** 2.3.2

**Installation source (Linux Only)** - the official website / GitHub releases / flatpak / snap / distribution package: https://www.archlinux.org/packages/community/x86_64/telegram-desktop/

**Used theme**: Night Mode

<details><summary><b>No Logs Yet</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by ilya-fedin** [comment]
Are you sure that link that you trying to open is supported in tdesktop?

**Comment by ilya-fedin** [comment]
They disabled the functionality to install URL handler, so it is expected if it doesn't work
https://github.com/archlinux/svntogit-community/blob/packages/telegram-desktop/trunk/PKGBUILD#L43

**Comment by txtsd** [comment]
> Are you sure that link that you trying to open is supported in tdesktop? Mobile clients have links that aren't supported by tdesktop afaik.

Yes, it opens in Bettergram correctly.

> They disabled the functionality to install URL handler, so it is expected if it doesn't work
> https://github.com/archlinux/svntogit-community/blob/packages/telegram-desktop/trunk/PKGBUILD#L43

So if I toggle that flag it'll work as expected?

**Comment by ilya-fedin** [comment]
> So if I toggle that flag it'll work as expected?

Yes, it should

**Comment by ilya-fedin** [comment]
But it updates the handler only when detects app update, so you will should trigger handler registration by entering `registertg` like a cheat code in settings (it won't do anything in the current build due to the flag)

**Comment by txtsd** [comment]
What does `registertg` actually do? Does it add an entry in mimeapps.list so xdg-open can correctly open `x-scheme-handler/tg` links?

**Comment by ilya-fedin** [comment]
> What does `registertg` actually do?

calls glib and it does some magic

**Comment by txtsd** [comment]
Elaborate please

**Comment by ilya-fedin** [comment]
> Elaborate please

I don't know what glib does under the hood exactly, but it works and other applications are using it too

**Comment by ilya-fedin** [comment]
Maybe this define should be removed :thinking:

**Comment by txtsd** [comment]
That's a good idea.

**Comment by AndydeCleyre** [comment]
@txtsd 

If you are willing and able to reproduce this issue on Arch with tdesktop 2.4.5 I would be very interested in figuring it out. If you can reproduce, please:

1. Show the output of

```console
$ find ~/.local/share/applications -iname '*telegram*'
$ xdg-mime query default x-scheme-handler/tg
$ grep -i telegram ~/.config/mimeapps.list
$ grep -iEo '[^;]*telegram[^;]*' ~/.local/share/applications/mimeapps.list
```

2. In firefox navigate to `about:config` and see if a preference named `network.protocol-handler.expose.tg` exists

**Comment by txtsd** [comment]
So for me it started to work after I switched the Application entry for opening tg links. If I switch it back to 'Use Telegram Desktop' it stops working just like originally reported. If I switch it to `Use Telegram Desktop (default)` it starts working as intended.

Entries are shown in this screenshot:
![2020-11-03-001820_1920x1080_scrot](https://user-images.githubusercontent.com/768728/97906921-75801800-1d6a-11eb-9c27-f3bcd0d63416.png)

**Comment by AndydeCleyre** [comment]
@txtsd Thanks! Can you please provide the info requested in my previous message?

**Comment by txtsd** [comment]
```
λ find ~/.local/share/applications -iname '*telegram*'

λ xdg-mime query default x-scheme-handler/tg
telegramdesktop.desktop                     

λ grep -i telegram ~/.config/mimeapps.list
x-scheme-handler/tg=telegram.desktop

λ grep -iEo '[^;]*telegram[^;]*' ~/.local/share/applications/mimeapps.list

λ 
```
The entry in mimeapps.list was added manually.

And that pref does not exist in my `about:config`

**Comment by AndydeCleyre** [comment]
Thanks @txtsd!

---

The `.desktop` file should be called `telegramdesktop.desktop`, not `telegram.desktop` as you have manually specified. Do you actually have a `telegram.desktop` file lurking somewhere? Please remove that from your `mimeapps.list` and restart firefox.

---

If that's not the issue, the extra entry is defined somewhere . . . possibly:
- some glib/gsettings/dconf entry that tdesktop has unfortunately added to your system in the past
- in firefox settings -- anything in `about:config` matching `.tg`?
- another file that firefox checks -- any output from `grep -i telegram ~/.local/share/applications/mimeinfo.cache` ?

**Comment by txtsd** [comment]
You're right about `telegramdesktop.desktop`. I removed the entry from `mimeapps.list` and restarted firefox.
Nothing in my `about:config` matches `.tg`
```
λ grep -i telegram ~/.local/share/applications/mimeinfo.cache

λ 
```
I don't know how to check these -> glib/gsettings/dconf
I don't use a gnome DE, just openbox.

**Comment by AndydeCleyre** [comment]
Yeah I'm not sure about what tdesktop might have done, as "does some magic" is the official explanation.

The extra entry in Firefox remains?

**Comment by txtsd** [comment]
Yes, it's still there. Is there anyone more knowledgeable that you can consult?

**Comment by AndydeCleyre** [comment]
Maybe @john-preston can enlighten us as to where that extra entry might be defined.
