### ISSUE TITLE
Already sent messages stay on message bar when switching accounts (sticky draft)

### ISSUE THREAD

**Issue by NinoM4ster** [telegramdesktop/tdesktop#8629]
### Steps to reproduce
1. Have at least two logged-in Telegram accounts
2. Write a message for someone on account A
3. Let the message be saved as draft by clicking on another chat **(important)**
4. Send the message
5. Immediately switch to account B
6. Switch back to account A

### Expected behaviour
When switching back, the message bar should be empty since the message was already sent.

### Actual behaviour
The message bar retrieves the contents from the draft, even though the message has already been sent.
Erasing the message bar contents and switching to B then back to A makes the draft reappear.

### Workaround
If you delete the text on the message bar and click on another chat, the draft refreshes and the message doesn't come back.

### Configuration
**Operating system:** Windows 10 (1903)

**Version of Telegram Desktop:**  2.3.1

**Used theme:** Classic

**Comment by HeCorr** [comment]
bump. bug still present.

**Comment by HeCorr** [comment]
Excuse me? This wasn't supposed to be closed, as the issue is still present.

**Comment by HeCorr** [comment]
activity.

**Comment by HeCorr** [comment]
activity.

**Comment by NinoM4ster** [comment]
Just tested this again and it seems to have been fixed.
