### ISSUE TITLE
Path problem when compile Telegram.pro on Ubuntu Kylin 15.04

### ISSUE THREAD

**Issue by jiangcaiyang** [telegramdesktop/tdesktop#863]
This problem happens on commit ef9aaf659c993ae3ed3f6b2044117ebc2c04e35e 
This is mainly due to path problem.

Could not make target: Telegram/Resources/style.txt, stop ( error message like that ). To resolve this problem, replace the following line:
./../../Telegram/Resources/style.txt
to 
./../Telegram/Resources/style.txt

Delete a separator, and in that make compilation success.

**Comment by jiangcaiyang** [comment]
Well, the path problem may be caused by Ubuntu build, Qt with MSVC and Qt with gcc treat path in differenent ways.

**Comment by Aokromes** [comment]
#117 ?
