### ISSUE TITLE
[Feature Request] [idea] delete files across the cloud

### ISSUE THREAD

**Issue by VaGNaroK** [telegramdesktop/tdesktop#8631]
function to be able to delete files from the cloud and disappear completely even for those who forwarded this file sharing with others, we often have a large file and we no longer need it, and when deleting it is still in the cloud because it still appears to people who forwarded this file, this would help freeing up space used in the cloud.

ex: Delete file only in your cloud
delete files in your cloud and in all contacts.

**Comment by Mohammed-Laith** [comment]
No one can do anything here (i think), pass it to the support or Telegram/Durov on Twitter.

**Comment by Aokromes** [comment]
such feature belongs to https://bugs.telegram.org/
