### ISSUE TITLE
[Feature Request] Animated profile picture in the chat

### ISSUE THREAD

**Issue by FinecoFinit** [telegramdesktop/tdesktop#8633]
### Describe the solution you'd like
Add button in settings to animate profile pictures in chat

**Comment by Genglxy** [comment]
Agreed, and I think there will also be a lot of people who want Animated profiles to be displayed not only on their profile.

**Comment by Neurotoxin001** [comment]
Disagreed. Just imagine bunch of people with flashing avatars in large chat. Rip eyes.

**Comment by NightMachinary** [comment]
[**@Neurotoxin001**](https://github.com/Neurotoxin001) commented on [Sep 29, 2020, 4:01 PM GMT+3:30](https://github.com/telegramdesktop/tdesktop/issues/8633#issuecomment-700670829 "2020-09-29T12:31:43Z - Replied by Github Reply Comments"):
> Disagreed. Just imagine bunch of people with flashing avatars in large chat. Rip eyes.

It can be an option turned off by default.

**Comment by Genglxy** [comment]
> Disagreed. Just imagine bunch of people with flashing avatars in large chat. Rip eyes.

A lot of IM apps, like discord, already support animate profile pictures within chat, and the experience is pretty good.I suppose if some users don't like it, they can turn it off themselves, or the developers can decide to play it only once or several times, or activate it only when the mouse slides over a conversation bubble, all of which are good solutions and don't result in dazzling blinking.

**Comment by FinecoFinit** [comment]
> 
> 
> Disagreed. Just imagine bunch of people with flashing avatars in large chat. Rip eyes.

In optional animation can be played on mouse hover

**Comment by Aokromes** [comment]
such feature belongs to https://bugs.telegram.org/
