### ISSUE TITLE
Call modal problem

### ISSUE THREAD

**Issue by MarouaneMan** [telegramdesktop/tdesktop#8635]
### Steps to reproduce
1. Call someone
2. Call modal shows up, a blank entry is added to the taskbar
3. No way to get rid of it

### Expected behaviour
Anyway to close the call modal without hanging up ?

### Actual behaviour
When i reduce the modal the blank entry is still shown, when i close it, it hang up !

### Configuration
Windows 10 1903
Telegram desktop 2.3.1

![telegram_problem](https://user-images.githubusercontent.com/6729798/94168754-3ec30200-fe8e-11ea-8e9c-42485bb9011d.jpg)

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/8459
