### ISSUE TITLE
Linux: Picture-saving dialogue removes file-type.

### ISSUE THREAD

**Issue by Glitchy-Tozier** [telegramdesktop/tdesktop#8638]
### Steps to reproduce
0. Use Linux Mint and the Flatpak, v.2.3.2
1. Open Telegram
2. Right-click on any picture that got sent to you or that you sent.
3. Click on "Save image as..."
4. The saving-dialogue will pop up.
5. The file name and the file-identifier will both be missing.
(saving the file without adding the .jpeg to the end doesn't trigger the file-format automatically getting added. It's just a type-less file now.)
![Telegram-wrongDialogue](https://user-images.githubusercontent.com/59611881/94271641-6dde7f80-ff31-11ea-9530-0b89559d7f38.png)

### Expected behaviour
In the saving-dialogue, there's a couple of viable options to make it easier for users to save files.
1. Add the file-extention to the file name so that the user can change it, if desired. Highlight the text in front of the ".jpeg" to make it easier to type in the name. The highlighted text should be the original file's name.
![Telegram_optimal](https://user-images.githubusercontent.com/59611881/94271694-7e8ef580-ff31-11ea-8f18-59cfe71f4d93.png)

2. Don't immediately, visibly add the file extention. Only after the user saves, if he didn't specify a file-type, use the format in the dropdown-menu. Again, insert the original picture's name to make it easier to type in a new one.
![Telegram_almost_optimal](https://user-images.githubusercontent.com/59611881/94272004-f9f0a700-ff31-11ea-8c4d-5a00aa153e51.png)

### Actual behaviour
None of these two things happen. The name-field, by default, is completely blank, and no file-type gets automatically added, making the dropdown-menu appear kind of useless.
(Additionally, Telegram always suggests the same inconvenient location for saving the file; a random folder burried deep within Telegrams file structure instead of remembering that, for example, I want to save all telegram-pictures in home/pictures/telegramstuff)

### Configuration
**Operating system:** Linux Mint 20 Cinnamon

**Version of Telegram Desktop:** 2.3.2.

**Installation source (Linux Only)**flatpak

**Used theme**: Uh... Desktop theme or Telegram-theme?

**Comment by ilya-fedin** [comment]
This is not a Telegram bug
https://github.com/flatpak/xdg-desktop-portal-gtk/issues/191

**Comment by Glitchy-Tozier** [comment]
I see. Should I close this bug then?
