### ISSUE TITLE
Telegram closes when call is ended

### ISSUE THREAD

**Issue by malyshkin-vitali** [telegramdesktop/tdesktop#8639]
### Steps to reproduce
1. Open Telegram Desktop 2.3.2 on Linux distributives(I've tested on Arch Linux and Ubuntu with GNOME DE) 
2. Call somebody or somebody can call you,
3. Close a windows with telegram(where you see chats). You also can close a windows with call but it is not necessary. Telegram works and there is an icon in tray. Good!
4. Ask your call member end the call. Telegram closed(and there is not an icon in tray)! 

### Expected behaviour
Telegram shouldn't close

### Actual behaviour
Telegram closes (See steps to reproduce)

### Configuration
Arch Linux up-to-date with GNOME DE, Ubuntu 20.04 LTS with GNOME DE

**Version of Telegram Desktop:**
2.3.2

**Installation source (Linux Only)** - the official website / GitHub releases / flatpak / snap / distribution package:
community repository in Arch, official website in Ubuntu.

**Used theme**:
default
<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by ilya-fedin** [comment]
#8442
