### ISSUE TITLE
Some images not present whereas being referenced.

### ISSUE THREAD

**Issue by jiangcaiyang** [telegramdesktop/tdesktop#864]
This happens on commit ef9aaf659c993ae3ed3f6b2044117ebc2c04e35e
For example, art/sprite_125x.png and art/sprite_150x.png not present, but it is being referenced, so it is result in this error:
RCC: Error in '../Telegram/SourceFiles/telegram.qrc': Cannot find file 'art/sprite_125x.png'
RCC: Error in '../Telegram/SourceFiles/telegram.qrc': Cannot find file 'art/sprite_150x.png'
Try deleting those references on telegram.qrc resolve the problem.

**Comment by auchri** [comment]
I think it's fixed
