### ISSUE TITLE
Incompatible with mobile

### ISSUE THREAD

**Issue by SmartManoj** [telegramdesktop/tdesktop#8640]
### Steps to reproduce
1. Set username as dont_ask_to_ask
2. 
3. 

### Expected behaviour

![image](https://user-images.githubusercontent.com/7231077/94332302-ba898f80-fff1-11ea-9e66-4f3467f3b88c.png)

### Actual behaviour

![image](https://user-images.githubusercontent.com/7231077/94332307-c2e1ca80-fff1-11ea-8db2-d5a137ef0d34.png)

### Configuration
**Operating system:** Win 

**Version of Telegram Desktop:** 2.3.1

**Comment by aleksusklim** [comment]
"This link is invalid" is shown on links that were used for banned users/channels, which are already deleted (for scam, etc.)
So, there is no entity with this link, but the link itself is banned on the server.
