### ISSUE TITLE
Enhancement: Show the exact number of messages to be deleted when deleting all from one user in a chat

### ISSUE THREAD

**Issue by aleksusklim** [telegramdesktop/tdesktop#8642]
### Is your feature request related to a problem?

When you are a chat admin, you have an option to delete all messages from the specific user. To do this, you need to right click any message from that user (without selecting the message), choose "Delete Message" and check "Delete all from this user".

But in this case, you have no hints for how many messages are about to be deleted. And you have no way to undo this action if you accidentally choose the wrong user!

### Describe the solution you'd like

Telegram Desktop should show the number of messages from the user, when you check "Delete all from this user". For example, this can be shown in round brackets after the label:

![proposal_1](https://user-images.githubusercontent.com/13969463/94338505-3abcee80-000c-11eb-93e3-d904a7d9be95.png)

### Describe alternatives you've considered

Alternatively, after selecting the checkbox, Telegram Desktop could hide buttons "CANCEL" and "DELETE" until it counts the actual number of messages from the user. Then, that number will be added in parentheses after the "DELETE" button:

![proposal_2](https://user-images.githubusercontent.com/13969463/94338510-401a3900-000c-11eb-87bd-001a28880580.png)

### Configuration

**Operating system:** Windows 7 SP1
**Version of Telegram Desktop:** 2.3.0
**Used theme**: Classic

**Comment by Aokromes** [comment]
imho this must be done api side.

**Comment by RememberTheAir** [comment]
What do you mean? There's an api to ask the server how many messages an user has ever sent in a chat. Probably quite heavy on the server btw

**Comment by aleksusklim** [comment]
When you pick a chat member in "Show messages from" modal window (after selecting Serach), Telegram Desktop shows the number of messages from that user almost immediately. Actually, after a 1 sec. delay.

So, I believe that the function to delete all messages from a user will be less frequent than just a search from a user. Such extra API call would not be noticeable on the server-side.

Moreover, the checkbox in question is disabled by default, and TDesktop may count messages only after selecting it.

**Comment by aleksusklim** [comment]
Э, я те сча закрою!

**Comment by aleksusklim** [comment]
That's you again?

**Comment by RememberTheAir** [comment]
unstale

**Comment by 23rd** [comment]
Guess should be closed.

**Comment by aleksusklim** [comment]
Yes, fixed in 3.7, thank you!

![image](https://user-images.githubusercontent.com/13969463/164154363-ccb09efe-4ae0-4544-84ae-aa47c5b1f175.png)
