### ISSUE TITLE
Malware: Account gets banned after clicking t.me link

### ISSUE THREAD

**Issue by futuremihai** [telegramdesktop/tdesktop#8644]
Hi,

My Telegram account of 3 years has been banned today and I couldn't figure out what it is, until I figured out more users had the same issue... My phone number got banned within about an hour of clicking that link. 

![image](https://user-images.githubusercontent.com/51002703/94364212-b2832b80-0095-11eb-84c1-223e9b7c2db9.png)

I would obviously like to get unbanned but not posting phone number publicly.

**Comment by Aokromes** [comment]
i am sorry, but this is not the place to get account unbanned, you need to mail recover@telegram.org

**Comment by futuremihai** [comment]
![image](https://user-images.githubusercontent.com/51002703/94369200-4533c280-00b6-11eb-92a2-414fd5a6fa0b.png)
Okay, however, this is a common thing happening right now if you look Twitter you will see hundreds of people who went on that link also got banned.

**Comment by fcore117** [comment]
Telegram accounts should not be easily bannable at all, what if there are urgent chaos in some country and you would not have time to debate about banning or email is unaccessible and no time to debate. Telegram accounts should be most robust of them all.

**Comment by Aokromes** [comment]
> Telegram accounts should not be easily bannable at all, what if there are urgent chaos in some country and you would not have time to debate about banning or email is unaccessible and no time to debate. Telegram accounts should be most robust of them all.
> 
> I hope once there is some sort of p2p backup and you still can continue communication. Banning should work only per people who do not want to see someone else or only per channel but whole account ban should be out of question.

i suggest you to suggest that on twiteer.

**Comment by john-preston** [comment]
AFAIK it was resolved.
