### ISSUE TITLE
[Question] Path tray icon in  the snap-package

### ISSUE THREAD

**Issue by slideray** [telegramdesktop/tdesktop#8649]
In the snap-package edition, where do I put the tray icon file so that the program uses it instead of the default icon?

In the normal version, I use the following path:

`~/.icons/Theme_name/scalable/apps/telegram.svg`

But where to put the "telegram.svg" file in the snap-package edition

**Comment by ilya-fedin** [comment]
There is no such path, snap packages doesn't support icon themes, say thank you to canonical
