### ISSUE TITLE
send contact

### ISSUE THREAD

**Issue by mxa** [telegramdesktop/tdesktop#865]
If i want to introduce one contact to another it would be useful to be able to send a contact to another user. Now I need to send a user a phone number, the user adds this to her/his address book and then it will show up after the next synchronization in Telegram. Works too but could be easier.

**Comment by auchri** [comment]
It's already possible. Open the contact and click on "Share contact".

**Comment by mxa** [comment]
oh, cool. I didn't find it there, I expected it where you can send a location, image and other stuffs.
