### ISSUE TITLE
Click on tray icon behaves not as expected

### ISSUE THREAD

**Issue by dziaineka** [telegramdesktop/tdesktop#8650]
### Steps to reproduce
1. You have to have extension [AppIndicator and KStatusNotifierItem Support](https://extensions.gnome.org/extension/615/appindicator-support/) installed and to have telegram in tray.
2. Have telegram window visible on desktop.
3. Open another window and make it active (telegram window become inactive)
4. Doubleclick (it single click equivalent in gnome) on telegram in tray.

### Expected behaviour
Telegram window becomes active.

### Actual behaviour
Telegram window hides to tray. Need extra doubleclick to unhide telegram window and make it active.

### Configuration
**Operating system: Fedora 32, Gnome, Wayland**

**Version of Telegram Desktop: 2.3.2**

**Installation source (Linux Only)** - : https://www.rpmfind.net/linux/RPM/rpmfusion/free/fedora/updates/32/x86_64/t/telegram-desktop-2.3.2-1.fc32.x86_64.html

**Comment by ilya-fedin** [comment]
Wayland doesn't allow to check if a windows is active, so it is not possible

**Comment by dziaineka** [comment]
I've made issue in wayland repo and they [provided](https://gitlab.freedesktop.org/wayland/wayland/-/issues/180#note_648380) the way to do it:

> Checking if a toplevel is active can be done by looking at the activated xdg-shell state:
https://gitlab.freedesktop.org/wayland/wayland-protocols/-/blob/6be6e00c0294e075e7b689167e08b52bf55ffccb/stable/xdg-shell/xdg-shell.xml#L802

**Comment by ilya-fedin** [comment]
tdesktop doesn't communicate with Wayland on its own, that does Qt and that means that Qt doesn't support that

**Comment by ilya-fedin** [comment]
The second problem remains - there are no way to focus a window
