### ISSUE TITLE
"Use proxy for calls" doesn't work with Socks5 proxy

### ISSUE THREAD

**Issue by VasiliPupkin256** [telegramdesktop/tdesktop#8651]
It doesn't even try to send UDP ASSOCIATE request to the proxy. I've checked this with wireshark.

I am really curious why it wasn't reported yet.

**Comment by ilya-fedin** [comment]
#8432

**Comment by VasiliPupkin256** [comment]
@ilya-fedin the issue #3911 doesn't even mention proxy in description but it can be the proxy issue. In the issue #8432 author doesn't reach the other side of the call, in my case everything is stopped on key exchange phase when a UDP connection should've been esteblished.

PR #27 seams to be addressing my issue but it was merged Jun 29 and either doesn't work or is not included in the client still.

**Comment by ilya-fedin** [comment]
> the issue #3911 doesn't even mention proxy in description but it can be the proxy issue

Look at discussion in the issue.

> In the issue #8432 author doesn't reach the other side of the call, in my case everything is stopped on key exchange phase when a UDP connection should've been esteblished.

#8432 doesn't have technical details, it could have the same cause.

**Comment by ilya-fedin** [comment]
> PR [telegramdesktop/libtgvoip#27](https://github.com/telegramdesktop/libtgvoip/pull/27) seams to be addressing my issue but it was merged Jun 29 and either doesn't work or is not included in the client still.

You removed entire issue template, so it is hard to say

**Comment by VasiliPupkin256** [comment]
> You have removed the entire issue template

The client is the most recent version for windows 10, it updates automatically. Should it include this fix?

**Comment by ilya-fedin** [comment]
> The client is the most recent version for windows 10, it updates automatically.

There are multiple Windows 10 versions, it is still hard to tell :see_no_evil: 

Just check version in the sidebar

**Comment by VasiliPupkin256** [comment]
@ilya-fedin version 2.3.1

**Comment by ilya-fedin** [comment]
>  version 2.3.1

libtgvoip was replaced by webrtc in version 2.3.0, libtgvoip is used only for backward compatibility with old clients

**Comment by VasiliPupkin256** [comment]
Ok. I should probably close this issue and describe all this findings in #3911

**Comment by ilya-fedin** [comment]
Yeah, it is definitely a duplicate

**Comment by VasiliPupkin256** [comment]
@ilya-fedin wait, but does webrtc itself support MTPROTO proxies too? Who is actually responsible for connection to proxy?

**Comment by ilya-fedin** [comment]
I don't know :(

**Comment by ilya-fedin** [comment]
As I can see, it is limited to socks5:
https://github.com/telegramdesktop/tdesktop/blob/f128665f6b6d1761f0153a42e185447c8f0b401b/Telegram/SourceFiles/calls/calls_call.cpp#L796-L807

And I see that it is used with libtgvoip:
https://github.com/TelegramMessenger/tgcalls/blob/b906b5a955f1e6e195cb91c4513d4cb7b3620ea6/tgcalls/legacy/InstanceImplLegacy.cpp#L81-L83

But is not used with webrtc:
https://github.com/TelegramMessenger/tgcalls/blob/b906b5a955f1e6e195cb91c4513d4cb7b3620ea6/tgcalls/InstanceImpl.cpp#L27-L43
https://github.com/TelegramMessenger/tgcalls/blob/b906b5a955f1e6e195cb91c4513d4cb7b3620ea6/tgcalls/Manager.cpp#L99-L140

But is there support for socks in webrtc? That's a question.

**Comment by VasiliPupkin256** [comment]
So the proxy isn't even set for webrtc? How it was accepted as a new backend then if it is ignoring proxy settings?

**Comment by ilya-fedin** [comment]
> How it was accepted as a new backend then if it is ignoring proxy settings?

It is not considered a mandatory feature I guess

**Comment by VasiliPupkin256** [comment]
Should we ask @john-preston then? Considering all the bans telegram go through, ignoring proxy settings looks like a bad idea.
