### ISSUE TITLE
[Linux] [Flatpak] [version 2.3.2] severe limitations on directories when uploading files

### ISSUE THREAD

**Issue by ktaherig** [telegramdesktop/tdesktop#8652]
### Steps to reproduce
1. While using the Linux version of Telegram Desktop, try to upload a file of any type.
2. It only allows "Recent", "Home", "Desktop", "Downloads", and "TelegramDesktop".
3. There's no option to go to "Pictures", "Videos", etc. Not even if I go to "home" and then "<username>". All it allows is ".config", ".local", ".var", and "Downloads".

### Configuration
**Operating system:**
Linux

**Version of Telegram Desktop:**
2.3.2

**Installation source (Linux Only)** - the official website / GitHub releases / flatpak / snap / distribution package:
Flatpak

**Comment by ilya-fedin** [comment]
Flapak applications are running in a sandbox, this is not a issue
