### ISSUE TITLE
High power consumption on Windows

### ISSUE THREAD

**Issue by kastal** [telegramdesktop/tdesktop#8653]
### Steps to reproduce
1. Start Telegram
2. Turn off animations
3. Use **powercfg -energy duration 5** or ClockRes or whatever to check the timer resolution.

### Expected behaviour
The app should not increase the timer resolution permanently, not even if animations are turned on. There is no need, this is not a high fps game!

### Actual behaviour
Increases the global timer resolution, making the whole system to run wild, resulting in very very high power usage.

### Configuration
**Operating system:**
Windows 10 Pro
**Version of Telegram Desktop:**
2.3.1

**Comment by Aokromes** [comment]
generic bug
https://github.com/telegramdesktop/tdesktop/issues/4854

**Comment by kastal** [comment]
> 
> 
> generic bug
> #4854

More than 2 years have passed since that "generic bug", wow...
I know that this bug comes from Chromium, but it was fixed (thanks to Microsoft Edge?). Every chromium based product ditched the timeBeginPeriod bullshit, so it shouldn't be a problem.
You should really update you libraries.

**Comment by Aokromes** [comment]
telegram desktop doesn't uses chromium.

**Comment by ilya-fedin** [comment]
> #4854

#5436 is the more right bug

**Comment by kastal** [comment]
Then it's maybe Qt's or something else's fault. I can't find any call to timeBeginPeriod or NtSetTimerResolution in the source code. Microsoft is literary yelling at developers DO NOT INCREASE TIMER RESOLUTION, but I guess no one gives a fck. I really miss plain old win32 gui's

**Comment by ilya-fedin** [comment]
> Then it's maybe Qt's or something else's fault.

Look the message just above yours

**Comment by kastal** [comment]
> Look at the message just above yours
So every detail is known about the bug and there is still hope :)
I found a temporary solution: https://github.com/rustyx/nobuzz/releases
Animations are not as smooth with it, but I don't care about that, I just turn it off (that should alone solve the problem). I don't recommend it on gaming PC's.
