### ISSUE TITLE
Feature Request: Chatheads

### ISSUE THREAD

**Issue by eckcon** [telegramdesktop/tdesktop#866]
Pushbullet just introduced Chatheads for their desktop-app:
https://www.youtube.com/watch?v=FJq4pJwKV1M

I think that would be very usefull for Telegram, too. (I don't like chatheads on mobile, because of the limited screenspace, but on desktop they are great!)

**Comment by dozz-a** [comment]
Agreed! +1

**Comment by skferret** [comment]
This would be awesome because right now its really clunky to respond to people while playing a game. Especially since I only have one monitor so I have to squeeze stuff around. :)

**Comment by JakariaAmin** [comment]
Yes, very important features, plz add ASAP. Thanks

**Comment by auchri** [comment]
#533
