### ISSUE TITLE
[Feature Request] Open With option

### ISSUE THREAD

**Issue by Lvceo** [telegramdesktop/tdesktop#8660]
### Is your feature request related to a problem?
No choice a part the system default browser to open an URL.

### Describe the solution you'd like
Would be nice to select the browser you want to use to open a link depending on the channel you are in.
Having an "Open With" option in each channel setting (or general setting) to allow opening personal URL with Firefox, and professional URL with Chrome for example.
By default the default System Browser is used, but can be changed to a specific one if required.

### Describe alternatives you've considered
N/A

### Additional context
N/A

**Comment by ilya-fedin** [comment]
#2385
