### ISSUE TITLE
[Feature Request] Link Multiple Channels To A Group

### ISSUE THREAD

**Issue by grravity** [telegramdesktop/tdesktop#8661]
### Is your feature request related to a problem?
As an example, If a user runs 3 different channels, and wishes to have one central group for discussion, you currently can only linkone groupas a discussion for a channel.

### Describe the solution you'd like
I am suggesting the ability to link multiple channels to a group.
For example, user runs 3 channels and wishes to have one centralized group for discussion.

Channel 1, Channel 2, Channel 3 > Central

### Describe alternatives you've considered
Creating a link and posting it in each channel or bio of each channel. However, this is not ideal, and users are more likely to click the Discuss button on a linked channel.

**Comment by MasterGroosha** [comment]
Unfortunately, this is an API issue (not only TDesktop-related)

**Comment by grravity** [comment]
@MasterGroosha Figured, I was unsure how to properly go about suggesting this as issues are closed on the main repo. I figured this would be the next best place, and if not I would be redirected.

**Comment by Aokromes** [comment]
in app ask the question or twiteer, android repo ain't the place for it too.

**Comment by MasterGroosha** [comment]
For general suggestions and feature requests please ping Telegram in Twitter (twitter.com/telegram) or open any official Telegram app: Settings -> Ask a Question.

**Comment by Aokromes** [comment]
such feature belongs to https://bugs.telegram.org/
