### ISSUE TITLE
Clicking on comments lead to closed emoji bar

### ISSUE THREAD

**Issue by ProtoChuz** [telegramdesktop/tdesktop#8663]
### Steps to reproduce
1. Click on comments from channel post (tested from this post https://t.me/OppaiSSH/6569)

### Expected behaviour
Emoji bar should still be open

### Actual behaviour
Emoji bar is closed after clicking on channel post's comment

### Configuration
**Operating system:** 
Ubuntu 18.04

**Version of Telegram Desktop:** 
2.4

**Installation source (Linux Only)** - the official website / GitHub releases / flatpak / snap / distribution package: 
the official website

**Used theme**: 
No Theme

<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by ilya-fedin** [comment]
Does it look like #8674?

**Comment by ilya-fedin** [comment]
Is this valid with 2.4.1?

**Comment by ProtoChuz** [comment]
Fixed with 2.4.1
