### ISSUE TITLE
Conflict between Comments feature and Inline Keyboards

### ISSUE THREAD

**Issue by frisbeegrammer** [telegramdesktop/tdesktop#8664]
### Steps to reproduce
1. I use t.me/ReactBot in my channel that sends reaction buttons to every post and now that buttons override comments section.
2. in my Android(6.0.1) phone comment section disappear completely but in TelegramDesktop both remain togather(neither works) until reopen tdesktop and then just reactions button remains and works.

### Expected behaviour
Use buttons and comment feature togather

### Actual behaviour
Inline Keyboards override new comment section

### Configuration
**Operating system:**
Windows 10.0.18362 Build 18362

**Version of Telegram Desktop:**
2.4

**Used theme**:
No Theme

<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Android :** 

![image](https://user-images.githubusercontent.com/30555691/94753823-4ad22680-039c-11eb-9f5e-eefaba368d47.png)
**Telegram Desktop :**

![image](https://user-images.githubusercontent.com/30555691/94753630-ab149880-039b-11eb-909b-7a4914bd9427.png)
 **Telegram Desktop after reopen:**

![image](https://user-images.githubusercontent.com/30555691/94753667-c54e7680-039b-11eb-9833-69c07ff74af2.png)

**Comment by john-preston** [comment]
I'll fix the sync with server, but for now messages with inline keyboard don't support commenting on the server side.

If server starts allowing comments for them, the button will appear. For now I'll hide it (it was generated locally).
