### ISSUE TITLE
Backspace no longer works in Linux (when a 5th level modifier key is set up) after updating to 2.4

### ISSUE THREAD

**Issue by Tynach** [telegramdesktop/tdesktop#8665]
### Steps to reproduce
1. Open a chat.
2. Type some letters into the 'Write a message...' field.
3. Press the Backspace key.

### Expected behaviour
The character that is immediately to the left of the text cursor should be deleted, placing said text cursor at the position the deleted character previously occupied.

### Actual behaviour
Absolutely nothing happens, as if I'm not pressing the Backspace key.

### Configuration
**Operating system:**  
KDE Neon (based on Ubuntu 20.04)

**Version of Telegram Desktop:**
2.4

**Installation source (Linux Only)** - the official website / GitHub releases / flatpak / snap / distribution package:  
The version from the website, though it updated via it's own automatic updater.

**Used theme**:  
Classic

**Input method**:  
xim

## Additional Information
I can press Ctrl+Backspace to delete the entire previous word just fine. No other apps are affected, only Telegram. I have already tried restarting Telegram, and there has been no improvement.

Do note that I use the XIM input method because it lets me have custom compose key sequences. Compose key sequences (including custom ones) still work just fine in Telegram. However, it's noteworthy that I remap my CapsLock key to act as a Compose key.

I see 2 rather old bug reports of the backspace key being disabled while CapsLock is on, but it is literally impossible for me to turn CapsLock on. However, I wonder if something weird is causing whatever that old bug's cause was to act up again on a system which doesn't *have* a CapsLock key, or where said CapsLock key is mapped to something other than CapsLock (in this case, Compose).

**Comment by ilya-fedin** [comment]
I guess that the fix for #2199 caused that issue

**Comment by Tynach** [comment]
@ilya-fedin Maybe. I just tried disabling my compose key, and restarting Telegram afterward. No change in behavior (except that Compose is now CapsLock). Enabling and disabling CapsLock works and I can type in all-caps in Telegram, but backspace does not work with or without CapsLock engaged. Nothing lets backspace work.

**Comment by ilya-fedin** [comment]
:man_shrugging: I can't reproduce, backspace works just fine for me

**Comment by Tynach** [comment]
@ilya-fedin

I've done some testing, and found that it happens because I have a '5th level modifier' key set. In my case, I use the right 'Win' key for level 5. If I disable that, I can use backspace within Telegram.

This is.. Acceptable to me, because I set that mostly in case I ever find a use for it, but I don't actually use any characters on the 5th level (and I'm not even sure there are any set in the keyboard layout I use).

However, I can imagine that anyone who *does* use a keyboard layout with 5th level characters will absolutely want to be able to backspace, so I'd say this is still a valid (if low priority) bug.

**Comment by ilya-fedin** [comment]
If there wouldn't be more affected users, I think it is better to keep this bug rather than reverting the fix

**Comment by Tynach** [comment]
Agreed, @ilya-fedin — I would not recommend reverting the fix (backspacing when in CapsLock mode is probably WAY more common than having a 5th level modifier key). However, I'd say still keep this bug open and hopefully find a solution to both problems.

**Comment by AlexanderAmelkin** [comment]
@Tynach thank you so much for investigating this! I hit this just now and was really frustrated. Had to revert back to 2.3.2.
I don't want to give up my 5th level modifier setup, so I guess I'll wait for a fix

**Comment by xel-x** [comment]
Same Issue on my side. Guess its because of the German NEO-Layout I am using… having no ability to backspace is a major issue for me and changing to a different layout is no option… so I'll downgrade too
