### ISSUE TITLE
PageUp/PageDown scrolling is not working in comments

### ISSUE THREAD

**Issue by andreymal** [telegramdesktop/tdesktop#8666]
Steps to reproduce:
1. Open comments on any message from any channel <sub><em>(but there should be enough comments to scroll of course)</sup></em>
2. Try to PgUp/PgDown
3. Be sad because it doesn't work

Mouse scrolling works fine.

Configuration: Arch Linux, Telegram 2.4, official build from the website

**Comment by mymedia2** [comment]
Arrow keys are also not working. Both ordinary ones and from NumPad.
