### ISSUE TITLE
Thread in group without channel

### ISSUE THREAD

**Issue by profyt** [telegramdesktop/tdesktop#8668]
### Steps to reproduce
1. Create channel & group
2. Link channel on group
3. Start thread in group
4. Drop link on group or drop channel
5. Open context menu on reply in thread and see "View Thread" button, but this button doing nothing.

### Expected behaviour
When drop link on group/ channel, in group clear all threads.

### Actual behaviour
Threads are present in the group, but they cannot be viewed.

### Configuration
**Operating system:**
Kernel: 4.20.17-042017-generic x86_64 bits: 64 compiler: gcc v: 8.3.0 
Desktop: Cinnamon 4.0.10 wm: muffin dm: LightDM Distro: Linux Mint 19.1 Tessa 
base: Ubuntu 18.04 bionic 

**Version of Telegram Desktop:**
2.4
**Installation source (Linux Only)** - the official website / GitHub releases / flatpak / snap / distribution package:
Uhmm, only update last year.

**Used theme**:
Default (night mode)

**Comment by john-preston** [comment]
This should be fixed by https://github.com/telegramdesktop/tdesktop/commit/415990c9133b93b7d201cdd0e4affae4e1580bb9

**Comment by Aokromes** [comment]
2.4.1
