### ISSUE TITLE
2.4 win7 64 | "admin" title not always displaying

### ISSUE THREAD

**Issue by imashxtyz** [telegramdesktop/tdesktop#8669]
it is only displayed on some particular posts of admins, sometimes it is not displayed at all, or it can appear/disappear after relaunch.
it seems like the "admin" title only appears when admin's post is last in the group, but also disappears after relaunch.

**Comment by MasterGroosha** [comment]
lol, you're 2 minutes faster than me :) 
Also related: #8671 (with screenshots)
