### ISSUE TITLE
[Feature Request] Info box for user

### ISSUE THREAD

**Issue by Akamaru** [telegramdesktop/tdesktop#867]
It would be great if users have also an info field. Just as the bots
![2015-06-30_19-37-22](https://cloud.githubusercontent.com/assets/8063440/8437642/acb52ecc-1f60-11e5-8521-36097e578a31.png)

**Comment by kenniki** [comment]
This would need to be exposed by the Telegram API, which it isn't.
This feature cannot be implemented in the client without an additional server infrastructure.

It's misplaced here, please close this issue and instead request it at Telegram Support.

**Comment by Mindstormer619** [comment]
Yeah, status messages are the one useful feature on WhatsApp which telegram has not implemented yet.
