### ISSUE TITLE
[v2.4] Admin titles are missing in group chat and group profile

### ISSUE THREAD

**Issue by MasterGroosha** [telegramdesktop/tdesktop#8671]
### Expected behaviour
Admin titles for non-anonymous admins should be visible in group chat and group profile (where participants are shown)
For example, screenshot from Android:
![изображение](https://user-images.githubusercontent.com/2780044/94788407-2eee7500-03dc-11eb-849b-f925040670d4.png)

### Actual behaviour
TDesktop 2.4 doesn't show such titles neither in group chat nor in profile:
![изображение](https://user-images.githubusercontent.com/2780044/94788589-7412a700-03dc-11eb-8d5b-4dbb11cd269f.png)
![изображение](https://user-images.githubusercontent.com/2780044/94788473-44fc3580-03dc-11eb-8a30-844d388bd37c.png)

### Configuration
**Operating system:** Windows 10
**Version of Telegram Desktop:** 2.4

**Comment by Aokromes** [comment]
#8669
