### ISSUE TITLE
Comments button is not shown for posts with buttons attached

### ISSUE THREAD

**Issue by Brawaru** [telegramdesktop/tdesktop#8677]
### Steps to reproduce

0. You have a bot that automatically or manually attaches reaction buttons to posts in the channel. You have also enabled discussions for your channel.
1. Publish a post on your channel

### Expected behaviour

The post is published and buttons are attached to it, alongside with comments button being displayed.

<p align=center>
<img src="https://user-images.githubusercontent.com/10401817/94803837-1d28c400-0414-11eb-8a9f-66150cbb027d.png" alt="Screenshot of the post with both comments button shown and reactions buttons attached">
</p>

### Actual behaviour

The post is published, but the moment reaction buttons are attached, the comments button is gone.

<p align=center>
<img src="https://user-images.githubusercontent.com/10401817/94805284-56623380-0416-11eb-81cf-5a27ee08c73b.png" alt="Screenshot of the same post, but only reaction buttons are shown">
</p>

### Additional details

I'm not sure whether this is intended behaviour or a bug, but I'd consider it as bug priority because it is very infuriating, considering the change completely removed ‘Discuss’ button (‘moved in “less visible” place’), thus making comments useless at its best, forcing authors to rely on good ol' bots.

Stickers can have both buttons and comments button attached to it, why posts cannot too? As you can see in the [‘expected behaviour’](#expected-behaviour) concept, it doesn't hurt the design at all, because the comments button is seamlessly attached to the post body.

### Configuration

**Version of Telegram Desktop:** 2.4.

**Comment by john-preston** [comment]
@Brawaru Right now this is intended behaviour, controlled from the server side. Sorry.

**Comment by SmartManoj** [comment]
![image](https://user-images.githubusercontent.com/7231077/95008207-6c9a0a80-0635-11eb-83a1-e2f633b08e00.png)
Is this bug?

**Comment by SmartManoj** [comment]
https://t.me/joinchat/AAAAAEqq220BJcHwItuIIQ
https://t.me/c/1252711277/39

**Comment by SmartManoj** [comment]
Why banned in @TelegramDesktopTalk?

**Comment by Brawaru** [comment]
@SmartManoj it's definitely a bug, buttons are not clickable. To repro, just attach buttons to a post with comments button.
