### ISSUE TITLE
Comments not working on some posts

### ISSUE THREAD

**Issue by Neurotoxin001** [telegramdesktop/tdesktop#8678]
# Steps to reproduce
1. Go to https://t.me/rhymestg/33981 or https://t.me/rhymestg/33982
2. Try to click on "Leave a comment"
3. Nothing happens

In logs is no errors etc

### Configuration
**Operating system:** win 10 ltsc 1809

**Version of Telegram Desktop:** 2.4

**Used theme**: Dark default

**Comment by Neurotoxin001** [comment]
Seems like I found why – these posts was deleted from the connected chat

**Comment by MasterGroosha** [comment]
By the way, "vanilla" Android app gives more precise message when you tap "Comment": "This post was deleted from discussion group". It doesn't remove "Comment" button, though, but at least letting user know that comments are not available for this post would be really nice

**Comment by Neurotoxin001** [comment]
Now comments button just disappears, seems like fine
