### ISSUE TITLE
[Feature Request] Enable/disable autostart on startup

### ISSUE THREAD

**Issue by kokizzu** [telegramdesktop/tdesktop#868]
it would be nice if telegram could enable/disable autostart just like Skype's option:

![image](https://cloud.githubusercontent.com/assets/1061610/8445650/2bca15f6-1fca-11e5-96da-6094e2422047.png)

I'm using Linux and XFCE btw.

**Comment by kokizzu** [comment]
that could be done using:
http://linux.chrissweeney.co.uk/topic.php?t=2

**Comment by Aokromes** [comment]
At least windows version suports this, maybe it's diferent on linux?

**Comment by bil-elmoussaoui** [comment]
+1 
not supported on linux

**Comment by auchri** [comment]
It's supported on windows, linux duplicate #948
