### ISSUE TITLE
Audio message is not being sent

### ISSUE THREAD

**Issue by Cussa** [telegramdesktop/tdesktop#8684]
### Steps to reproduce
1.  Open a chat
2.  Try to record an audio message

### Expected behaviour
Audio message sent correctly

### Actual behaviour
The recorder finishes, but the message is not sent

### Configuration
**Operating system:** Windows

**Version of Telegram Desktop:** 2.4

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/8673
