### ISSUE TITLE
Part of window becomes transparent when opening comments

### ISSUE THREAD

**Issue by YaBoiBurner** [telegramdesktop/tdesktop#8687]
![Screenshot from 2020-10-01 08-51-42](https://user-images.githubusercontent.com/10004812/94818382-99f47780-03ed-11eb-8cda-66e822e97846.png)
### Steps to reproduce
1. Open channel
2. Resize window so that the "Channel Info" section is visible
3. Open the comments for a post

### Expected behaviour
Either it should display something in the info box, or it should get rid of the info box.

### Actual behaviour
The info box becomes transparent and gains a shadow inside of the window.

### Configuration
**Operating system:** Fedora Linux (5.8.12-200.fc32.x86_64)

**Version of Telegram Desktop:** 2.4

**Installation source (Linux Only)** - the official website / GitHub releases / flatpak / snap / distribution package: flatpak

**Used theme**: Night (builtin)

<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by ilya-fedin** [comment]
#8674
