### ISSUE TITLE
 I can no longer send voice messages after updating to tdesktop v 2.4.0 on Windows 10

### ISSUE THREAD

**Issue by nicosaon** [telegramdesktop/tdesktop#8688]

**Comment by ilya-fedin** [comment]
#8673

**Comment by ilya-fedin** [comment]
There is no sense to have multiple issues

**Comment by nicosaon** [comment]
> 
> 
> There is no sense to have multiple issues

As I said, I don't know if it's the same version for Linux and Windows. As far as I know it is not. So, that's the reason why I report it.
