### ISSUE TITLE
Messages do not keep their ordering

### ISSUE THREAD

**Issue by Gollam** [telegramdesktop/tdesktop#8689]
### Steps to reproduce
1. Write multiple number of messages on a fairly bad internet connection, for example "A", then "B" and then "C"

### Expected behaviour
The messages should keep their ordering, so "A" should be sent first, then "B", then finally "C"

### Actual behaviour
What I observed is there is a race condition in the sending of messages, they were sent in a random order. After the internet connection got better, message "B" got the green light first, it was sent and got the double pipe, then "A", then "C". The displaying order of the messages remained the same in the chat window ("A" "B" "C"), but actually they were sent in the wrong order. I pulled my phone to verify it, and I saw that the messages were indeed in the order "B" "A" "C", which of course didn't make any sense to the person I wrote it to. Then I restarted the desktop client, so it synchronised the conversation from the server, and now it showed the bad order as well ("B" "A" "C").

### Configuration
**Operating system:**
Windows 10

**Version of Telegram Desktop:**
2.4

**Installation source (Linux Only)** - the official website / GitHub releases / flatpak / snap / distribution package:

**Used theme**:
Classic

<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/2797 ?

**Comment by Gollam** [comment]
Yes, seems like it's the same. Didn't find it. Thanks.
