### ISSUE TITLE
[Regression / New Bug] Hotkeys don't work in Discussion view

### ISSUE THREAD

**Issue by JosXa** [telegramdesktop/tdesktop#8692]
### Steps to reproduce
1. In channel post, click "Comments" to enter Discussion view
2. Press any of the usual keyboard shortcuts:
- Ctrl+Up for replying to the last message in chat
- Up for editing your last outgoing message
- Probably more...

### Expected behaviour
Hotkeys should behave the same way as in regular chats.

### Actual behaviour
No-op.

### Configuration
**Operating system:**
Windows 10

**Version of Telegram Desktop:**
2.4

**Comment by Vilmodao** [comment]
Also spell check doesn't work for comments section. I guess that's same kind of problem.

**Comment by MasterGroosha** [comment]
Valid as of 2.4.3

**Comment by AtilioA** [comment]
> Valid as of 2.4.3
Experiencing this on 2.4.7 as well (Mint 20)

**Comment by Henriquelay** [comment]
Also on 2.4.8 beta (windows 10)
