### ISSUE TITLE
Voice message bug in v2.4

### ISSUE THREAD

**Issue by ramtinak** [telegramdesktop/tdesktop#8693]
### Steps to reproduce
1.  Press and hold recording voice button
2.  After a few seconds release it 

### Expected behaviour
Voice recorder should working !

### Actual behaviour
I've updated my Telegram desktop today, and after that I can't send any voice messages.
After I've recorded a voice when I release the pointer inside of Voice Recoder Button, it will cancel it. 

### Configuration
Windows 10 Enterprise - 64bit - version 2004 build 19041.208

Telegram version 2.4 (downloaded from official website)

**Comment by ilya-fedin** [comment]
#8673
