### ISSUE TITLE
Audio not being sent

### ISSUE THREAD

**Issue by luisalvarado** [telegramdesktop/tdesktop#8694]
### Steps to reproduce
1. Update to latest 2.4
2. Try to send an audio to ANYONE
3. Audio is not sent

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

### Configuration
**Operating system:**
Ubuntu
**Version of Telegram Desktop:**
2.4
**Installation source (Linux Only)** - the official website / GitHub releases / flatpak / snap / distribution package:
Using the official Telegram package form the site
**Used theme**:
![image](https://user-images.githubusercontent.com/29236/94840326-7cb3af00-03d5-11eb-80db-6e413970017f.png)

<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by Aokromes** [comment]
fixed on 2.4.1

**Comment by luisalvarado** [comment]
Confirmed. JESUSSSSS YOU FAST!
