### ISSUE TITLE
Can't send audio messages from Windows

### ISSUE THREAD

**Issue by ldeluigi** [telegramdesktop/tdesktop#8695]
### Steps to reproduce
1. Keep the mouse pressed while recording an audio message
2. Try to send it.

### Expected behaviour
Should be able to send my audio message.

### Actual behaviour
The audio is canceled.

### Configuration
**Operating system:** Windows 10

**Version of Telegram Desktop:** 2.4

**Installation source (Linux Only)** - the official website

**Used theme**: custom

**Comment by Aokromes** [comment]
centuplicated. will be fixed on 2.4.1
