### ISSUE TITLE
Lag when playing video

### ISSUE THREAD

**Issue by aminya** [telegramdesktop/tdesktop#8696]
In the recent versions, I experience lag when I play a video. I have attached a screen capture.

### Steps to reproduce
1.	Install Telegram 2.4.0 or 2.4.1
2.  Play a video 

### Expected behaviour
Play smoothly like in other versions of Telegram. I tested with Telegram 2.2.0 portable, and it did not have this issue.

### Actual behaviour
Excessive lag when playing video
[New video.zip](https://github.com/telegramdesktop/tdesktop/files/5314535/New.video.zip)

### Configuration
**Operating system:**
Windows 10

**Version of Telegram Desktop:**
2.4.0

**Used theme**: Default night mode

**Comment by anon5114** [comment]
Same problem, when playing music or video

**Comment by aminya** [comment]
This is fixed in 2.4.4. 

@Aokromes I am closing this.
