### ISSUE TITLE
[Question] is file size limit approximated?

### ISSUE THREAD

**Issue by SmartManoj** [telegramdesktop/tdesktop#8700]
https://desktop.telegram.org/changelog

In v 2.2, is it really 2000MB or just approximated?

**Comment by john-preston** [comment]
@SmartManoj It is exactly 2000 MB.

**Comment by SmartManoj** [comment]
It's wrong there?
https://telegram.org/blog/profile-videos-people-nearby-and-more#dev_page_content:~:text=to%202%20Gigabytes%20per

**Comment by RememberTheAir** [comment]
2 gb is way more straightforward than 2000 MB for most of the end users that blogpost is targeted to, most people won't ever notice or care about the small difference. The actual limit is 2000 MB as Preston said, there's no reason to reopen the issue
