### ISSUE TITLE
[Regression] Cannot change input method on Linux

### ISSUE THREAD

**Issue by Stealthmate** [telegramdesktop/tdesktop#8701]
### Steps to reproduce
1. Start Telegram
2. Press IME change shortuct

### Expected behaviour
IME should change, in my case I'm using fcitx, the shortcut is `C-\` and the IME is Mozc.

### Actual behaviour
Nothing. **However**, if I run Telegram from the terminal with

```
LC_CTYPE=ja_JP.utf-8 Telegram
```

it works normally. I borrowed this idea from Emacs, since it has the same problem, but I never needed to do this until now, which is why I flagged this as a regression.
### Configuration
**Operating system:** Linux Mint 19

**Version of Telegram Desktop:** 2.4.1

**Installation source (Linux Only)** - GitHub releases

**Used theme**: Default, night mode

<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by ilya-fedin** [comment]
I don't know what "IME change shortuct" is, but tdesktop chooses IME by QT_IM_MODULE variable, like all other Qt applications.

**Comment by Stealthmate** [comment]
This appears to have resolved itself. I tested with both 2.4.1 and 2.4.2 and it seems that it was a problem on my machine. Sorry for raising a false alarm.

By the way, the IME change shortcut is the shortcut you use to switch between IMEs. In my case I'm using `C-\` to switch between the normal English keyboard and Mozc for Japanese.
