### ISSUE TITLE
[Feature Request] Do not allow to read public group without join

### ISSUE THREAD

**Issue by hardhub** [telegramdesktop/tdesktop#8703]
### Is your feature request related to a problem?
Yes, we cannot be sure that public group is read by joined users only.  
In some scenarios it is very important. Admins should know who can read their groups (even if join itself is free).  

### Describe the solution you'd like
Add option to not show content of group until user is connected. Like it is for private groups.

### Describe alternatives you've considered
Alternative is not very good.. It is public alias for private group (predefined invite link).
But I do not think it is so clear as simple option regarding content availability.

**Comment by RememberTheAir** [comment]
Why not just making the group private groups instead? Public groups are _public_ because they have an username and the chat history is accessible even if you are not part of the group

**Comment by hardhub** [comment]
> 
> 
> Why not just making the group private groups instead? Public groups are _public_ because they have an username and the chat history is accessible even if you are not part of the group

We cannot make it private, in this case group is not accessible via well-known URL.

**Comment by RememberTheAir** [comment]
@hardhub you can use that username for a public channel and post the private invite link there

**Comment by hardhub** [comment]
> 
> 
> @hardhub you can use that username for a public channel and post the private invite link there

Which username?

You cannot use well-known short URL:

![image](https://user-images.githubusercontent.com/4306334/94969411-598b1b80-050b-11eb-897e-15641603cacc.png)

**Comment by Aokromes** [comment]
bit.ly or co.

**Comment by hardhub** [comment]
> 
> 
> bit.ly or co.

It is not an option.. it should be well-known predefined link like for public group.

Please read original post carefully.

**Comment by reallyuniquename** [comment]
@hardhub 
>Which username?

The one you use for your chat.

**Comment by RememberTheAir** [comment]
@hardhub as @reallyuniquename said, the idea is to create a channel and give it the username you are currently using for your group chat. Then turn the group private and post the private invite link in the channel. In this way, people around the internet will still be able to find out your group (they will find a channel containing only one message with the invite link to your chat) and your group can stay private

**Comment by hardhub** [comment]
> 
> 
> @hardhub as @reallyuniquename said, the idea is to create a channel and give it the username you are currently using for your group chat. Then turn the group private and post the private invite link in the channel. In this way, people around the internet will still be able to find out your group (they will find a channel containing only one message with the invite link to your chat) and your group can stay private

OK, now it is clear. You suggest to create channel. It will work but not for us. For us it is bad idea.. We will lose a lot of users, most of them use telegram first time.  

So it should be easy as much as possible - type name (for example _bikers70_) or press equal link and then just press Join (2 very simple actions). New users do not know anything about those "channels, groups, public, private, etc". They do not know how to go to group from channel, they even will not know that they need to do that.   

So we just want to avoid link with random token, and want to have nice one, the same as well-known name in real life.. only group, not channel... It is crucial no additional steps for non IT-related persons.

**Comment by Tids** [comment]
> We will lose a lot of users, most of them use telegram first time.

On the other hand you will not gain new users on an empty group, that hides the text before join.
I'd also vote against close down public groups. They are public for a good reason and should stay visible without exception.

> They do not know how to go to group from channel, they even will not know that they need to do that.

If they where able to find the bumper-group, they are able to click on button to join the real group. Just explain in bumper-group why its managed this way and all is good. You could even do that with a welcome-bot. Like in

```
Hi %USER,
You have joined %GROUPNAME. This group is to manage new user and 
protect us against bots. To see other users please click here
[ Button to real group ]
```

**Comment by hardhub** [comment]
> They are public for a good reason and should stay visible without exception.

First of all it can be an option and can be fully visibile by default. But if it is crucial for you to keep it as it is now then alternative way is specified in original post - allow to type invite link (or set well-known alias for invite link) for private group.

**Comment by hardhub** [comment]
I think public/private is also related to this one: https://github.com/telegramdesktop/tdesktop/issues/8702

Private group allow to clean history.  
I am sure it is big mistake to split groups to public and private.  
In general it is much better to have all configurable in group options.

**Comment by Aokromes** [comment]
such feature belongs to https://bugs.telegram.org/
