### ISSUE TITLE
[Feature Request]  Tagging messages

### ISSUE THREAD

**Issue by codemeleon** [telegramdesktop/tdesktop#8704]
### Is your feature request related to a problem?
Yes. Many times, we failed to find the exact messages we are looking for.

### Describe the solution you'd like
I would like to request a feature allowing users to add hashtags to other people messages in their chats and these hashtags should be searchable. Personal hashtags autosuggestion in search will be beneficial.

**Comment by Aokromes** [comment]
such feature belongs to https://bugs.telegram.org/
