### ISSUE TITLE
[gnome] [wayland] Automatic resize on window-activation (focus) since tdesktop 2.4

### ISSUE THREAD

**Issue by Tids** [telegramdesktop/tdesktop#8705]
### Steps to reproduce
1. Startup gnome on wayland
2. load tdesktop wayland native
3. switch betwen 2 windows

### Expected behaviour
Windowsize should stay the same

### Actual behaviour
tdesktop window shrinks itself on every activation

### Configuration
**Operating system:**
Archlinux

**Version of Telegram Desktop:**
2.4

**Installation source (Linux Only)** - the official website / GitHub releases / flatpak / snap / distribution package:
native from site
flatpak

**Used theme**:
gnome adwaita (default)
telegram default

**Video**:
[https://streamable.com/4w76is](https://streamable.com/4w76is)
This behavior is new since 2.4. We now also have a shadow around the window, that might be the cause for miscalculation of the window size.

**Comment by Aokromes** [comment]
update to 2.4.1

**Comment by ilya-fedin** [comment]
Yeah, this already fixed on 2.4.1
