### ISSUE TITLE
Failing to Open Telegram

### ISSUE THREAD

**Issue by minutesinch** [telegramdesktop/tdesktop#8709]
### Steps to reproduce
1. make sure you have GTK based Linux and pin  Telegram binary in Dock and add passcode.
2. update Telegram to 2.4.x and close.
3. try open telegram binary and enter passcode.

### Expected behaviour
Tell us what should happen
in version 2.3.x of telegram, there is no problem and when i opend telegram from dock and enter passcode and submit, telegram window immediately open and like other eailer telegram version later version must open after entering passcode and click submit
### Actual behaviour
after opening Telegram from dock  i tried enter passcode and click submit, telegram window closed and you must click agian on telegram in dock to open

### Configuration
**Operating system:**
elementary os 5.1.7 GTK 3.22.30
**Version of Telegram Desktop:**
2.4.x
**Installation source (Linux Only)** - the official website / GitHub releases / flatpak / snap / distribution package:
github, officail website
**Used theme**:
default
<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/8697
