### ISSUE TITLE
Crash when select "Attached Stickers"

### ISSUE THREAD

**Issue by sepehr-brj** [telegramdesktop/tdesktop#8710]
### Steps to reproduce
1. Download a photo that has attached sticker(s)
2. Open that photo
3. From the right-click or three-dots menu select "Attached Stickers"

### Expected behaviour
Show sticker pack

### Actual behaviour
Crash

### Configuration
**Operating system:** Windows7 x86

**Version of Telegram Desktop:** 2.4.1

**Installation source (Linux Only)** - the official website / GitHub releases / flatpak / snap / distribution package:

**Used theme:** Tined

<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by ilya-fedin** [comment]
Crash report tag?

**Comment by sepehr-brj** [comment]
Yes, it does crash but it happens every time and for eveyone. it's more like a bug.

**Comment by john-preston** [comment]
@sepehr-brj Can you please:
- enable "install beta versions" in Settings > Advanced
- then crash the app
- then relaunch it, it should offer you to send crash report
- then copy the "your report tag" field here (many letters-digits string)
- then send the report
- then send the report tag here

**Comment by sepehr-brj** [comment]
Report Tag: 252d915e-81e9-4f3a-b3ba-23171bd8cea4

![Capture](https://user-images.githubusercontent.com/55192376/94936986-de5e4100-04db-11eb-90e4-0bdab6f643f1.JPG)
