### ISSUE TITLE
给一个人发文件的时候，无法给其他联系人发图片

### ISSUE THREAD

**Issue by 1265578519** [telegramdesktop/tdesktop#8712]
给一个人发文件的时候，无法给其他联系人发图片
![1](https://user-images.githubusercontent.com/6442439/94949320-4f6d1b00-0513-11eb-8d91-cb9f4f6669b9.png)
![2](https://user-images.githubusercontent.com/6442439/94949324-509e4800-0513-11eb-9947-3d1939d7d414.png)

**Comment by wuyudi** [comment]
When we send someone a big file, during its uploading, we can't send photos.

**Comment by ilya-fedin** [comment]
Yeah, you can send only one file or photo by time, this is intended.
