### ISSUE TITLE
Window Size Msg Formatting Bug

### ISSUE THREAD

**Issue by dm17** [telegramdesktop/tdesktop#8725]
On any message thread, the other person & you have messages on opposite sides of telegram-desktop's window. Other person: left, us on the: right.

When expanding the telegram-desktop window beyond a certain width, both you and the other person's chats end up on the same side (left side).

I've tested in a variety of situations. Using latest (2.3.2) telegram-desktop on Linux.

**Comment by ilya-fedin** [comment]
This is not a bug, this is a feature called "Adaptive layout"

**Comment by dm17** [comment]
> This is not a bug, this is a feature called "Adaptive layout"

Thanks! But why would it work that way? Adaptive layout should act that way for very narrow screens only, right?

**Comment by ilya-fedin** [comment]
> Adaptive layout should act that way for very narrow screens only, right?

narrow sceens - left&right, wide screens - only left.

**Comment by dm17** [comment]
> > Adaptive layout should act that way for very narrow screens only, right?
> 
> narrow sceens - left&right, wide screens - only left.

OK, I didn't realize. Any idea why?

**Comment by dm17** [comment]
Oh to reduce how far left & right your eyes have to move when reading a thread? Never considered that... So, since I have your expertise at my disposal right now: which software / library determines this distance (and behavior)? :)
Thanks!

**Comment by ilya-fedin** [comment]
> which software / library determines this distance (and behavior)? :)

tdesktop code

**Comment by dm17** [comment]
> > which software / library determines this distance (and behavior)? :)
> 
> tdesktop code

You say it like it is such a common thing that it would be pulled from a library... Not everyone is familiar with every code base they run... So perhaps this is a bug: I'm suggesting the width is too narrow before switching modes. 

@ilya-fedin 
Easy to test: Take a small telegram-desktop window and then slowly drag/adjust the window wider until it switches modes. It does it too early, right?
Thanks.

**Comment by ilya-fedin** [comment]
> You say it like it is such a common thing that it would be pulled from a library...

All tdesktop UI is implemented in custom widgets, no third-party libraries are used for UI

> So perhaps this is a bug

No, this is still a feature

> It does it too early, right?

What do you mean by "too early"?

**Comment by dm17** [comment]
> > You say it like it is such a common thing that it would be pulled from a library...
> 
> All tdesktop UI is implemented in custom widgets, no third-party libraries are used for UI
> 
> > So perhaps this is a bug
> 
> No, this is still a feature
> 
> > It does it too early, right?
> 
> What do you mean by "too early"?

Nevermind. I can now cope with it. If you fullscreen the telegram-desktop app (even if you have a 4:3 display), then you should still see it change modes to be on the left side.

**Comment by ilya-fedin** [comment]
Yes, it doesn't checks aspect ratio, there are just width limit.
