### ISSUE TITLE
Opposite behaviour of #8677

### ISSUE THREAD

**Issue by SmartManoj** [telegramdesktop/tdesktop#8730]
### Live Demo
https://t.me/joinchat/AAAAAEqq220BJcHwItuIIQ
https://t.me/c/1252711277/39

![image](https://user-images.githubusercontent.com/7231077/95010535-b1c73800-0647-11eb-92e1-a5e7d0dcd8f1.png)

### Configuration
**Operating system:** Win

**Version of Telegram Desktop:** 2.4.2

**Installation source (Linux Only)** - the official website / GitHub releases / flatpak / snap / distribution package:

**Used theme**: Dark

<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by SmartManoj** [comment]
Commenting on closed issues have a lower impact than creating a new issue?

**Comment by ilya-fedin** [comment]
Please stop creating weird issues

**Comment by SmartManoj** [comment]
@ilya-fedin Could you please explain how it is weird?

**Comment by Aokromes** [comment]
better issue #8748
