### ISSUE TITLE
Can't access group after getting banned twice

### ISSUE THREAD

**Issue by SmartManoj** [telegramdesktop/tdesktop#8732]
### Steps to reproduce
Got a ban and lifted and joined using desktop
After the second ban, joined using mobile when checking the bots in this group

### Actual behaviour
![image](https://user-images.githubusercontent.com/7231077/95010822-17b4bf00-064a-11eb-86af-67a9d98cc2af.png)
But on desktop, can't access the group even after restarting the app.

### Configuration
**Operating system:** Win

**Version of Telegram Desktop:** 2.4.2

**Installation source (Linux Only)** - the official website / GitHub releases / flatpak / snap / distribution package:

**Used theme**:

<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by tcreek** [comment]
That is not a software client issue, but backend problem. You will probably need to contact the same address in which you did to remove the ban.

**Comment by SmartManoj** [comment]
Seems fine now
