### ISSUE TITLE
Cannot mention users without usernames in Messages containing a file

### ISSUE THREAD

**Issue by MaxMatti** [telegramdesktop/tdesktop#8733]
### Is your feature request related to a problem?
Currently there is no way (that I know of) to mention a user that does not have a username while sending a file. In the text box that pops up after selecting a file there is no autocompletion for users like in the main chat box and when editing the message after sending it there's the same problem. I also tried copying the text (including the mention) from the main chat box to the other text boxes, but when doing that the mention is lost and just the plain text is copied.

### Describe the solution you'd like
Menu to mention people in the other text boxes mentioned above or way to copy mentions when the user does not have a username.

### Describe alternatives you've considered
Getting rid of the popup when sending files and instead have the file displayed in a similar way to the message you're replying to, when using the reply-to functionality.

### Additional context
The text box that I'm talking about:
![image](https://user-images.githubusercontent.com/1584478/95010962-7586de00-062d-11eb-8d6c-b4ccb019d85a.png)

**Comment by MaxMatti** [comment]
Writing the message first and then attaching the file works, but it's not really intuitive that one has to do it in that order.

**Comment by ldeluigi** [comment]
This should have been solved years ago.. but it's still there.

**Comment by ldeluigi** [comment]
Writing message first is needed for users with a username too if you need the autocomplete feature.

**Comment by ilya-fedin** [comment]
#2158
