### ISSUE TITLE
Restore "Use system window frame" option

### ISSUE THREAD

**Issue by amivaleo** [telegramdesktop/tdesktop#8734]
Hi,

After the latest update (now I have telegra-desktop v. 2.4.2) the "Use system window frame" option is gone and I can't find it anywhere.

I use Fedora 32. The flat titlebar that I'm now forced to use (1) has no shadows like all the other applications, as you can see:

![Schermata da 2020-10-04 13-43-11](https://user-images.githubusercontent.com/24316547/95014628-6bbea400-0648-11eb-972c-71b77df3d610.png)

(2) the draggable area around the entire window is maybe only 1 pixel thick, making it quite difficult to resize it.

(3) the window menu is not accessible by right-click on the titlebar.

(4) pretty ugly non-integrated gui...

Can you please consider to re-integrate the option to make telegram follow the system "rules", please?

Thank you!

**Comment by ilya-fedin** [comment]
GNOME Wayland doesn't support xdg-decoration protocol, there is no sense to have this checkbox.

**Comment by amivaleo** [comment]
> GNOME Wayland doesn't support xdg-decoration protocol, there is no sense to have this checkbox on GNOME Wayland, it just activates Qt's dummy decorations.

I can only speak as an end-user, and for me that checkbox activated the CSD, so it made a lot of sense.

It worked fine, so... How to have CSD again, even if by some command in the terminal...?

**Comment by ilya-fedin** [comment]
> The flat titlebar that I'm now forced to use (1) has no shadows like all the other applications, as you can see

None of wayland decorations are had shadows. I guess you had XWayland previously, flatpak package is switched to native Wayland oin the latest version, for instance. You can move backward by `flatpak override org.telegram.desktop --env=QT_QPA_PLATFORM=xcb`

**Comment by amivaleo** [comment]
> > The flat titlebar that I'm now forced to use (1) has no shadows like all the other applications, as you can see
> 
> None of wayland decorations are had shadows. I guess you had XWayland previously, flatpak package is switched to native Wayland in the latest version, for instance. You can move backward by `flatpak override org.telegram.desktop --env=QT_QPA_PLATFORM=xcb`

I've been using Wayland for a few years by now

```
$ loginctl show-session 2 -p Type
Type=wayland
```

Windows do have dectorations in wayland, as you can see in the screenshot in my first message.

> You can move backward by `flatpak override org.telegram.desktop --env=QT_QPA_PLATFORM=xcb`

Thank you. This is at least a workaround to keep using the application in its latest version.


Oh, I see the "wontfix" label.
Got it. I "wontuse" the very same application as soon as this "workaround" stops working.

Thank you for your kindness.

**Comment by ilya-fedin** [comment]
> Windows do have dectorations in wayland, as you can see in the screenshot in my first message.

I guess these windows are windows of gtk applications or qt applications with XWayland. Qt applications doesn't and can't have proper decorations with native Wayland on GNOME since GNOME [doesn't support xdg-decortaion](https://gitlab.gnome.org/GNOME/mutter/-/issues/217) protocol. And until it start to support, things won't change, only gtk applications will look natively with native Wayland on GNOME.

**Comment by amivaleo** [comment]
> > Windows do have dectorations in wayland, as you can see in the screenshot in my first message.
> 
> I guess these windows are windows of gtk applications or qt applications with XWayland. Qt applications doesn't and can't have proper decorations with native Wayland on GNOME since GNOME [doesn't support xdg-decortaion protocol](https://gitlab.gnome.org/GNOME/mutter/-/issues/217). And until it start to support, things won't change, only gtk applications will look natively with native Wayland on GNOME.

Ok.

Much better, nicer and more integrated now.

![Schermata da 2020-10-04 14-37-04](https://user-images.githubusercontent.com/24316547/95015772-205bc400-064f-11eb-93a7-d50ada6c6e6a.png)

Thank you!
