### ISSUE TITLE
(Linux) Very strong incoming sound distortion since 2.3.1 due voice call

### ISSUE THREAD

**Issue by AndreiRch** [telegramdesktop/tdesktop#8736]
Since version 2.3.1 (with video calls) I have very strong incoming sound distortion (voice of my interlocutor) due to voice call that make in impossible to talk. In other side, my voice sound good to my interlocutor (he have no problem). Video calls not use.
Version 2.2 work fine.

### Steps to reproduce
Make voice call

### Expected behaviour
Incoming sound due voice call should be clear, as it was in version 2.2 and older.

### Actual behaviour
Very strong incoming sound distortion (voice of my interlocutor)

### Configuration
KDE Neon 18.04, 20.04
2.3.1 and newer
Fltpak
Breeze default

**Comment by ilya-fedin** [comment]
Focusrite soundcard?

**Comment by AndreiRch** [comment]
I use Radeon RX 560 Series with sound via DisplayPort (my monitor have built-in speakers)

**Comment by AndreiRch** [comment]
I make some additional research - problem exactly in sound card (that built-in in video card).
When I try use different sound card - all work OK, sound clear.

**Comment by Aokromes** [comment]
can you try on 2.4.4?

**Comment by Aokromes** [comment]
have you tried with another applications? ie discord.

**Comment by ilya-fedin** [comment]
> have you tried with another applications? ie discord.

I guess this is due to the fact that tdesktop uses webrtc's example ADM

**Comment by AndreiRch** [comment]
Hello! Now, with 2.5.8 (or may be few version earlier) I have not this bug. Probably, it resolved.
