### ISSUE TITLE
Can't save GIF in discussion

### ISSUE THREAD

**Issue by Neurotoxin001** [telegramdesktop/tdesktop#8739]
### Steps to reproduce
1. Open https://t.me/mudak/42782?comment=11467915
2. Try to save GIF
3. You can't, because there is no "Save GIF" in discussion:
![image](https://user-images.githubusercontent.com/39812401/95018349-dfbc7480-0667-11eb-8a2f-3d5696801d8f.png)
4. But you can do it in chat https://t.me/savemdk/11467915
![image](https://user-images.githubusercontent.com/39812401/95018362-f1058100-0667-11eb-81ba-9ac898f59abb.png)

### Configuration
**Operating system:** win 10 ltsc 1809

**Version of Telegram Desktop:** 2.4.2

**Used theme**: dark default

**Comment by kiarashgl** [comment]
Ping! Since the discussion section is a great resource of gifs, I think fixing this bug could be useful.
