### ISSUE TITLE
Tray icon has a white background

### ISSUE THREAD

**Issue by hobarrera** [telegramdesktop/tdesktop#874]
The tray icon seems to have a white background (instead of a transparent one). It should be transparent.
Sample:

![sample image](https://cloud.githubusercontent.com/assets/730811/8492378/29a3f476-211f-11e5-96c1-2dfcc3be85a9.png)

**Comment by nixi-awoo** [comment]
Agreed, the tray icon should have a transparent background.

![telegram-tray](http://i.imgur.com/wAdTsuA.png)

**Comment by Aokromes** [comment]
Strange, i am using Telegram with a quite dark theme and my icon have transparent background.

http://i.imgur.com/35geMcW.png

**Comment by hobarrera** [comment]
@Aokromes Is that an xorg tray icon, or an appindicator?

**Comment by nixi-awoo** [comment]
I have found a fix. Enabling display composing removes the white background. Other icons work ok wothout composing though, so this is still an issue.

**Comment by hobarrera** [comment]
> Enabling display composing removes

Do you mean, using a compositing window manager? Or is this some telegram tweak you did?

**Comment by nixi-awoo** [comment]
@hobarrera 
I am using XFCE4 withhout any desktop compositor enabled. The icon becomes transparent upon enabling the default XFCE compositor and restarting telegram. It works with Compton as well.

**Comment by Aokromes** [comment]
@hobarrera no, it's windows 10, maybe only linux is afected.

**Comment by hobarrera** [comment]
@nixi-awoo So changing the WM to a compositing one is a workaround, interesting. But this is far from applicable for a lot of people.

@Aokromes It seems to be an xorg-only bug, yes.

This is a duplicate of #492. Since that issue is a bit older I'll close this one and move discussion over there.
