### ISSUE TITLE
[Question] How to paste an embed link?

### ISSUE THREAD

**Issue by SmartManoj** [telegramdesktop/tdesktop#8740]

**Comment by ilya-fedin** [comment]
Please, provide detailed descriptions for each issue that you creating, your issues are incomprehensible.

**Comment by SmartManoj** [comment]
An embedded link is in the current format in telegram. hi (http://a.com)

But if we paste in this format, it just pastes as text.

**Comment by ilya-fedin** [comment]
This format is not supported by tdesktop, that was discussed in #4737

**Comment by SmartManoj** [comment]
We can copy an embedded link and paste in Telegram.
How it works?

**Comment by ilya-fedin** [comment]
> We can copy an embedded link and paste in Telegram.

clipboard protocol magic
