### ISSUE TITLE
Request auto-connection on camera and other interfaces for the snap

### ISSUE THREAD

**Issue by 3v1n0** [telegramdesktop/tdesktop#8742]
### Is your feature request related to a problem?

Video calls don't work straight away in the snap unless the user doesn't use:

`snap connect telegram-desktop:camera`

### Describe the solution you'd like

You should request auto-connection of camera interface (at least) in the snapcraft forum: https://forum.snapcraft.io/c/store-requests

**Comment by john-preston** [comment]
https://forum.snapcraft.io/t/interface-auto-connect-request-for-the-telegram-desktop-snap-camera/20383

**Comment by ilya-fedin** [comment]
> https://forum.snapcraft.io/t/interface-auto-connect-request-for-the-telegram-desktop-snap-camera/20383

Looks like the discussion is slowed down

**Comment by ilya-fedin** [comment]
Oh, two weeks without reply in the thread
![image](https://user-images.githubusercontent.com/17829319/96535333-1659d800-1281-11eb-9b89-fb7c5bb15efc.png)

**Comment by john-preston** [comment]
They've granted some.
