### ISSUE TITLE
[Bug] Not able to delete the profile photo/video in TD v2.4.2

### ISSUE THREAD

**Issue by Mohammed-Laith** [telegramdesktop/tdesktop#8743]
### Steps to reproduce
1. go to settings. 
2. go to edit profile.
3. click at your profile photo/video
4. now right-click.
5. click delete

### Expected behaviour
it should delete it.

### Actual behaviour
it cancels without deleting it

### Configuration
win7sp1 build 7061 (but not related)

**Version of Telegram Desktop:**
2.4.2 stable

**Used theme**:
default (also not related)

see this video (from a friend tested it) :
https://t.me/testtotestprofile/2

**Comment by ilya-fedin** [comment]
#8720
