### ISSUE TITLE
[Feature Request] Add Telegram Version Number To Download Page in Website

### ISSUE THREAD

**Issue by toni1elias** [telegramdesktop/tdesktop#8750]
Please Add Telegram Version Number To Download Page in Website:
https://desktop.telegram.org/

Example: Telegram v2.4.2

Thank you.

**Comment by Mohammed-Laith** [comment]
They won't do this i bet. And when you click download, the file will go to the downloads stack, so you can see the file name which also contains the version. :)

**Comment by toni1elias** [comment]
> They won't do this i bet. And when you click download, the file will go to the downloads stack, so you can see the file name which also contains the version. :)

Thank you, Mr. Mohammed. The version number is known on pressing download, but it would be faster to check the version number on the webpage for archiving
