### ISSUE TITLE
Telegram Desktop executes *.sh files on Windows 10 on mouse click without any confirmation or warning

### ISSUE THREAD

**Issue by Pymancer** [telegramdesktop/tdesktop#8753]
### Steps to reproduce
1. Just click on any .sh file received from one of your contacts.

### Expected behaviour
In my opinion the app should warn about the potential danger of running executable files and allow to abort the execution

### Actual behaviour
Windows tries to run the file and closes the terminal

### Configuration
**Operating system:**
Windows 10 Pro
**Version of Telegram Desktop:**
2.4.2

**Installation source (Linux Only)** - the official website / GitHub releases / flatpak / snap / distribution package:

**Used theme**:

<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by reallyuniquename** [comment]
In my opinion Telegram should ask explicit user permission before openning literally any file. 

Right now clicking filename instead of arrow button would launch a file, see #2924. There is additional warning but only for some extenstions and that's not the way such things should be done as it clearly would never cover everything.

**Comment by john-preston** [comment]
@reallyuniquename No, right now if the file isn't downloaded (and you see the arrow for download) first click anywhere will download the file and won't open it.

If you have the file downloaded, then click on it (anywhere) will try to open it.

**Comment by reallyuniquename** [comment]
@john-preston 
Well I stand corrected, I guess something has been patched as I remember that's how it worked few versions ago. 

Still, there should be explicit popup. Telegram Desktop already does that for URLs but not for downloaded files.

![image](https://user-images.githubusercontent.com/10516120/95186346-92104b00-07d2-11eb-995c-05cfc7aa5ee7.png)

I mean users are 1 misclick away from launching potential malware.
