### ISSUE TITLE
Error when trying to send file with Drag and Drop: "Could not send an empty file /path_to_file"

### ISSUE THREAD

**Issue by cube-flow** [telegramdesktop/tdesktop#8754]
### Steps to reproduce
1. Send file or picture via Drag and Drop to the chat window.

### Expected behaviour
Tell us what should happen

File or picture should be send successfully 

### Actual behaviour
Tell us what happens instead
Error: Could not send an empty file /path_to_file

### Configuration
**Operating system:**
Endless OS 3.8.6 (200831-151843)

**Version of Telegram Desktop:**
2.4.2

**Installation source (Linux Only)** - the official website / GitHub releases / flatpak / snap / distribution package:
flatpak

**Used theme**:

<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by ilya-fedin** [comment]
You need to allow access to home folder in order to drag'n'drop files

**Comment by cube-flow** [comment]
Could you please clarify more on it. I have same access for all home folders 
drwxr-xr-x 3 user1 user1      4096 Oct  5 10:20  Documents
drwxr-xr-x 5 user1 user1      4096 Oct  5 10:13  Downloads
drwxr-xr-x 2 user1 user1      4096 Apr  6 13:07  Music
drwxr-xr-x 2 user1 user1      4096 Oct  5 10:20  Pictures
drwxr-xr-x 3 user1 user1      4096 May 13 05:27  Videos

I only able to Drag-and-Drop from the Downloads folder. What specific permissions are need?

**Comment by ilya-fedin** [comment]
https://github.com/flathub/org.telegram.desktop/issues/23

**Comment by cube-flow** [comment]
Thanks for the hint.
