### ISSUE TITLE
Only few formats available when editing media in album

### ISSUE THREAD

**Issue by Neurotoxin001** [telegramdesktop/tdesktop#8756]
### Steps to reproduce
1. Post any single media and press "edit" to replace it with another media
2. You will see that you can chose "All files"
![image](https://user-images.githubusercontent.com/39812401/95137106-0ebe0d80-0770-11eb-8a7f-f597e7b5c3b9.png)
3. Now post album (for example 2 photos) and press "edit" on one of them
4. You will see that you can chose only png, jpg, mp4 and jpeg **and there is no option to show "All files"**
![image](https://user-images.githubusercontent.com/39812401/95137414-afacc880-0770-11eb-894d-4db29be5c9fa.png)

This is the problem when you have .mov video file and it needs to be replaced

### Configuration
**Operating system:** win 10 ltsc 1809

**Version of Telegram Desktop:** 2.4.2

**Used theme**: dark default

**Comment by 23rd** [comment]
Well, until the next release, you can use drag'n'drop to replace your album item with a `*.mov` file.

**Comment by Neurotoxin001** [comment]
@23rd I see you made a commit
https://github.com/telegramdesktop/tdesktop/commit/7e9695b213b719f3046abc428f0db80c9b6ed6ce

But there is a lot more video formats that TDesktop support, for example https://t.me/Cbpub/19342 *.m4v

**Comment by Neurotoxin001** [comment]
+

**Comment by Neurotoxin001** [comment]
https://github.com/telegramdesktop/tdesktop/commit/9c7fee0bfe196b37726635c8e401e4826142ab0b
