### ISSUE TITLE
Voice message recording doesn't work

### ISSUE THREAD

**Issue by e2e4l1** [telegramdesktop/tdesktop#8757]
If I want to record a voice message in the new version of Telegram, the recording is empty. There are no problems on version 2.3. At the same time, sound level indicator in recording device selection menu reacts to sound. I have Windows 10 Pro (2004). Soundcard is M-Audio Delta 44. Recording voice messages on AC'97 works without problems with new version of Telegram.

**Comment by ilya-fedin** [comment]
#8719
