### ISSUE TITLE
Can't select sticker in discussions

### ISSUE THREAD

**Issue by Neurotoxin001** [telegramdesktop/tdesktop#8759]
### Steps to reproduce
1. Enter into the discussion and try to select the sticker
2. You can't
3. But you can do it in connected chat 

https://i.imgur.com/z23ZclQ.mp4

### Configuration
**Operating system:** win 10 ltsc 1809

**Version of Telegram Desktop:** 2.4.2

**Used theme**: dark default

**Comment by john-preston** [comment]
Fixed by https://github.com/telegramdesktop/tdesktop/commit/5a3733b5b67212d9bcb088f98cb78dc611a74b5f
