### ISSUE TITLE
Error 107

### ISSUE THREAD

**Issue by matinbeigi** [telegramdesktop/tdesktop#876]
tdesktop with Visual 2012 opens.
But there Runtime Error 107.

**Comment by Aokromes** [comment]
It looks VS 2013 is needed.
https://github.com/telegramdesktop/tdesktop/blob/master/MSVC.md
You can get Visual Studio 2013 community edition for free from https://www.visualstudio.com/en-us/products/visual-studio-community-vs.aspx
