### ISSUE TITLE
[Feature Request] Add the ability to set a nickname for each chat separately

### ISSUE THREAD

**Issue by islamsav** [telegramdesktop/tdesktop#8760]
Add the ability to set a nickname for each chat separately, otherwise, if he does not assign one, then the default nickname is used. I am qa and personal groups and workers are mixed in the telegram. In workers, I would like to set the nickname conditionally _Alex QA_, and in personal groups, just _Alex_

**Comment by islamsav** [comment]
I am a member of various telegram groups. For work chat I want to give myself a specific name, but for personal groups I want to be seen under a different name

**Comment by Aokromes** [comment]
https://bugs.telegram.org/c/753
