### ISSUE TITLE
[Feature Request] Deleting multiple chats at the same time option

### ISSUE THREAD

**Issue by Arunachala-Ramana** [telegramdesktop/tdesktop#8761]
Hello!

I see that Telegram Desktop doesn't have the option of selecting multiple chats and then deleting them at a single click. This feature has been added lately for android version. I wish these features can be added to the desktop version too. 

Thank you.

**Comment by ilya-fedin** [comment]
#4079

**Comment by Arunachala-Ramana** [comment]
Has this issue been already resolved?
