### ISSUE TITLE
Last seen time error discrepancies

### ISSUE THREAD

**Issue by Arunachala-Ramana** [telegramdesktop/tdesktop#8762]
![1](https://user-images.githubusercontent.com/68316708/95195822-b3822e80-07f4-11eb-81d5-f6d088320738.png)

See the attached image. There is a lot of discrepancies in the way in which the last seen time is shown. For example one contact shows seen 10hours ago other contact shows yesterday at 10:28 P.M. I hope there is a uniformity maintained. Please do rectify this issue. 

Thank you.

Operating System : Ubuntu 20.04 LTS
Telegram  Version : 2.4.2

**Comment by Aokromes** [comment]
It's sorted by name, not by last seen.

**Comment by Aokromes** [comment]
I suppose you want to see sorted by last seen.

**Comment by RememberTheAir** [comment]
He means that sometimes tdesktop show people's last seen as "n hours ago" and sometimes it shows the exact date & time

@Arunachala-Ramana I think that it's based on how much time has passed from when the user was last online. Probably if someone's last seen was before today's date, its shows the exact time
