### ISSUE TITLE
[Question] Why emoji 🔥 has default shortcode as flame?

### ISSUE THREAD

**Issue by SmartManoj** [telegramdesktop/tdesktop#8763]
[Emojipedia](https://emojipedia.org/fire/#:~:text=Emoji%20Meaning,lit%20(%E2%80%9Cexcellent%E2%80%9D).)

Which shortcodes does Telegram use?

**Comment by Mohammed-Laith** [comment]
https://translations.telegram.org/en/emoji

**Comment by SmartManoj** [comment]
![image](https://user-images.githubusercontent.com/7231077/95221634-45019880-0815-11eb-8b5e-957fffa76e3f.png)

**Comment by SmartManoj** [comment]
Even here, fire comes first. SO it is not updated here?

**Comment by Mohammed-Laith** [comment]
> Even here, fire comes first. So it is not updated here?

idk

**Comment by SmartManoj** [comment]
🥰 - This doesn't have short_code

**Comment by SmartManoj** [comment]
https://github.com/k3a/telegram-emoji-list/issues/1
