### ISSUE TITLE
[Bug] [Crash] TD crashes when sending a scheduled message after its deadline has passed 

### ISSUE THREAD

**Issue by Mohammed-Laith** [telegramdesktop/tdesktop#8764]
### Steps to reproduce
1. Send any file as a scheduled message, the file can be of any type, but it should be big. _(And big is a relative word, varies as the connection speed varies; for me, 3 MB is big enough, for example)_
2. Set the scheduled time in the very near future. _(For example, and with my connection speed of 16 KB, if I did this at X i will set the scheduled time at X + 1 minute)_
3. Now, within the conditions I mentioned, the time will go beyond X + 1 minute, and the file is yet not uploaded, it's being uploaded.
4. Let's say that the time now is X + 10 minutes, and the file got uploaded just now, but remember, the scheduled time was X + 1 minute.
5. TD will instantly crash! _(But the file will be uploaded and sent correctly)_
This happened because (obviously) the time the file got uploaded is greater than the scheduled time. X + 10 > X + 1.

### Expected behaviour
TD shouldn't crash, the file gets uploaded anyways?!?!
_(However, this is better than Android's client, Android's client never lets you to send the file in this case, you have to re-upload)._

### Actual behaviour
TD successfully uploaded the file and immediately sent it to the receiver, but it crashed, this is the problem :(

### Configuration
Windows 7 Service Pack 1 (build 7061)
Telegram Desktop 2.4.2 stable

**Used theme**:
Default.

@john-preston , I just sent you all the necessary files. but this is the log.txt if anyone wants to see it.
[log.txt](https://github.com/telegramdesktop/tdesktop/files/5335259/log.txt)

EDIT:
The same crash can be reproduced for a full text message; that is, contains no media.
How ? Just schedule a message to be sent in the very near future, cut the Internet connection, after some time -the deadline has been passed- reconnect, TD crashes :/

**Comment by 23rd** [comment]
Thank you for your report.

**Comment by Mohammed-Laith** [comment]
> Thank you for your report.
It's my pleasure. :)
