### ISSUE TITLE
All forwarded messages except the first one lack "Leave a comment" button. 

### ISSUE THREAD

**Issue by aalekseevx** [telegramdesktop/tdesktop#8765]
### Steps to reproduce
1. Write several messages to "Saved messages"
2. Forward 2 or more of them to a channel with enabled comments (all together)

### Expected behaviour
Every message has "Leave a comment button"

<img width="902" alt="Screenshot 2020-10-06 at 20 20 29" src="https://user-images.githubusercontent.com/23260308/95237986-8e4fe900-0811-11eb-8523-715236e64b2c.png">

### Actual behaviour
Only the first message has the desired button.

<img width="911" alt="Screenshot 2020-10-06 at 20 22 17" src="https://user-images.githubusercontent.com/23260308/95238061-a6276d00-0811-11eb-8d38-0032e22de094.png">

### Configuration
**Operating system:** macOS Catalina 10.15.6

**Version of Telegram Desktop:** 2.4.2

**Used theme**: Night

**Comment by Neurotoxin001** [comment]
It's api issue, on iOS same problem
![image](https://user-images.githubusercontent.com/39812401/95241388-59926080-0816-11eb-9559-02f1a9b777d3.png)

**Comment by Aokromes** [comment]
such feature belongs to https://bugs.telegram.org/
