### ISSUE TITLE
Phone number can only be changed on the phone

### ISSUE THREAD

**Issue by WhyNotHugo** [telegramdesktop/tdesktop#877]
This is a pretty **critical** issue.

The option to change the phone number, is only available on the phone client. Nor the web client, nor the desktop client have this option.

My main motivation to make sure I can change my number was "what happens if I lose my phone (or get mugged)".
As-is, if I lose my phone, I also lose the _only_ was to change the number for my account.

**Comment by ezdev128** [comment]
Very interested question. I'll add my questions:
1. How to access to account without sms (but internet access)?
2. How to recover account without cell phone access (when cell phone was stolen)?
3. How to terminate ASAP all sessions without cell phone access?
4. How to destroy all chat logs and sent/received documents remotely in case of stolen phone?

**Comment by hobarrera** [comment]
```
2. How to recover account without cell phone access (when cell phone was stolen)?
```

The FAQ states that you can change your number, however, the option is missing from the desktop and web client, so it invalidates what the FAQ says, and it's currently impossible to recover your account (unless you recover your phone or its SIM).

**Comment by hobarrera** [comment]
Slightly on-topic: Is it possible to create an account if someone previously owned my new number and had set a password for it? If not, this will create a growing list of "unusable" numbers.

**Comment by auchri** [comment]
@hobarrera Your account will be deleted after 6 months if it's unused

**Comment by Nachtalb** [comment]
This feature was implemented but this Issue never closed.
