### ISSUE TITLE
[Feature Request] Smaller comments button

### ISSUE THREAD

**Issue by Neurotoxin001** [telegramdesktop/tdesktop#8771]
### Is your feature request related to a problem?
Comments button under regular posts is too big and ugly. Comments button under stickers is much better:
![image](https://user-images.githubusercontent.com/39812401/95319705-f1d52780-08a0-11eb-9f75-f041869a7d0e.png)

### Describe the solution you'd like
Make comments button like under stickers on regular posts too, or give users setting to choice it

**Comment by reallyuniquename** [comment]
#8670
