### ISSUE TITLE
Not expected behaviour if use Clip to send a file. 

### ISSUE THREAD

**Issue by cube-flow** [telegramdesktop/tdesktop#8772]
### Steps to reproduce
1. Use Clip for sending files

### Expected behaviour
Tell us what should happen

When we use Clip to send a file it should open file manager(portal) in active window on top of other windows including Telegram window.

### Actual behaviour
Tell us what happens instead

File manager(portal) opens on back plane. 
 
### Configuration
**Operating system:**
Endless OS 3.8.6

**Version of Telegram Desktop:**
2.4.2

**Installation source (Linux Only)** - the official website / GitHub releases / flatpak / snap / distribution package:
flatpak

**Used theme**:

<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by ilya-fedin** [comment]
This is not an application area of responsibility in Flatpak, file a bug against xdg-desktop-portal-gtk.

**Comment by cube-flow** [comment]
It seems such type of problem was already mentioned here:
https://github.com/flatpak/xdg-desktop-portal-gtk/issues/306

**Comment by ilya-fedin** [comment]
Yes, not a Telegram issue

**Comment by cube-flow** [comment]
Is there any way to consider to use other than xdg-desktop-portal-gtk implementation for file dialog?

**Comment by ilya-fedin** [comment]
> Is there any way to consider to use other than xdg-desktop-portal-gtk implementation for file dialog?

This is not in application area of responsibility as well.

**Comment by cube-flow** [comment]
I meant for Telegram's implementation of file dialog, since other messengers apps don't have such issue.

**Comment by ilya-fedin** [comment]
> I meant for Telegram's implementation of file dialog

Telegram doesn't have "implementation of file dialog" for flatpak, that does Qt.

> since other messengers apps don't have such issue

I guess they are based on Electron, while Telegram on Qt.
