### ISSUE TITLE
[Feature Request] Mark Folder as read

### ISSUE THREAD

**Issue by mrdimfox** [telegramdesktop/tdesktop#8773]
Folders in Telegram are awesome but have a lack of some basic features. One of these is a feature of marking all chats inside of Folder as read by clicking "Mark as read" in a context menu of a Folder. It is exactly like "Mark as read" in a chat context menu but for Folder.

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/commit/bdce2d5e25835324b30d766a58ab4b6094dd23ff
