### ISSUE TITLE
Add keyboard shortcut for contact search

### ISSUE THREAD

**Issue by maximal** [telegramdesktop/tdesktop#8775]
Native MacOS Telegram has `Cmd+K` shortcut which shows a dialog similar to Menu → Contacts.

I didn’t find any similar hotkey in the [corresponding list](https://github.com/telegramdesktop/tdesktop/wiki/Keyboard-Shortcuts). Surely, we have a global search called with `Esc` but it isn’t contact-specific. 

It would be perfect if Telegram Desktop has a quick way to show this dialog. `Ctrl+N` (new) or something like that.

**Comment by maximal** [comment]
@john-preston, I think `Ctrl+Shift+N` is not so convenient to press with one hand. I'd choose something more handy.

Anyway, thanks!

**Comment by Loskir** [comment]
![image](https://user-images.githubusercontent.com/21295738/97077910-3de9d100-15f0-11eb-9e62-72c8436aa7b2.png)
It also overrides the "Plain text" formatting option
