### ISSUE TITLE
Bash is not recognizeable. Building for Visual Studio 2019. 

### ISSUE THREAD

**Issue by natovan** [telegramdesktop/tdesktop#8777]
Command **bash --login ../../tdesktop/Telegram/Patches/build_ffmpeg_win.sh** from provided build instructions for msvc returned **'bash' is not recognized as an internal or external command, operable program or batch file.**
Things I've tried:
1. Cygwin
2. Win bash
3. Git bash

All ThirdParty is download and installed. I'm running x86 Native Tools Command Prompt for VS 2019

**Comment by ilya-fedin** [comment]
Use msys2 bash

**Comment by natovan** [comment]
msys2 servers are down

**Comment by ilya-fedin** [comment]
then wait until they up

**Comment by natovan** [comment]
Now msys is not compiling executable. I'm giving up on this.
