### ISSUE TITLE
It seems such type of problem was already mentioned here:

### ISSUE THREAD

**Issue by cube-flow** [telegramdesktop/tdesktop#8779]
It seems such type of problem was already mentioned here:

_Originally posted by @cube-flow in https://github.com/telegramdesktop/tdesktop/issues/8772#issuecomment-704969302_

**Comment by ilya-fedin** [comment]
WTF?

**Comment by Mohammed-12345** [comment]
????????????????????????
؟؟؟؟؟؟؟؟؟؟؟؟؟؟؟؟؟؟؟؟؟؟؟؟؟؟
????????????????????????
What the DUCK?
