### ISSUE TITLE
Block unknown contact images

### ISSUE THREAD

**Issue by Christilut** [telegramdesktop/tdesktop#878]
So anyone can messages anyone which is really nice and open. But people tend to be rather mean and may send disturbing images to others... Perhaps all images from unknown contacts should be blocked until the user is in the contact list?
Or maybe the receiving user has to allow the first image for the next images to also be allowed.

**Comment by auchri** [comment]
You can block the unknown users

**Comment by Christilut** [comment]
I can't find that option on tdesktop or the Android app, where should it be?

Also that is only a partial solution since I would like to stay approachable over Telegram, that's what I like about it.

**Comment by Mindstormer619** [comment]
It's present in the android app under more options after clicking on the user profile. 

Not yet there on desktop. This is another hotly requested feature.

**Comment by auchri** [comment]
Blocking users was implemented
