### ISSUE TITLE
Gboard stickers shows as .webp files

### ISSUE THREAD

**Issue by spectraldani** [telegramdesktop/tdesktop#8780]
### Steps to reproduce
1. Open Gboard on an Android smartphone
2. Send a Gboard sticker to a Telegram chat
3. Notice that it displays as a Telegram sticker in Telegram for Mac and Android but not in Telegram Desktop

### Expected behaviour
Gboard sticker appears as a Telegram sticker in chat, just like in Telegram for Mac and phone apps.
![image](https://user-images.githubusercontent.com/6686762/95383855-27d6d380-08c2-11eb-9aab-3582f57ccaf8.png)

### Actual behaviour
The message appears as a .webp file with filename that matches the following regular expression: `-[0-9]+_-[0-9]+\.webp`
![image](https://user-images.githubusercontent.com/6686762/95383770-04ac2400-08c2-11eb-91ae-5e1b09da6efd.png)

### Configuration
**Operating system:** Windows 10

**Version of Telegram Desktop:** 2.2.4

**Used theme**: Night

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/8284
