### ISSUE TITLE
[Feature Request] Max. joining / subscriptions per hour (subscribers limit)

### ISSUE THREAD

**Issue by ZanudaZanudnaya** [telegramdesktop/tdesktop#8781]
### Is your feature request related to a problem?
I know, that it's not exactly server-side suggestion git for all platforms, but I'll try. Bad people kill channels / groups with massive fake subscribers spam and a lot of channels have been removed from global search after attacks.

### Describe the solution you'd like
Add in "Members" / "Subscribers" sections:

- Max. joining / subscriptions per hour (if the limit will be exceeded - new subs will have notification window "Sorry, but right now the load on the group / channel is too heavy, try again later."
- Notifications limit (administrators with the "Ban users" / "Add member" flag will be notified if the limit is exceeded

<img src="https://user-images.githubusercontent.com/21275896/95404144-e32c5600-091c-11eb-907d-aa41702afbbd.jpg" width="400">

### Describe alternatives you've considered
Also if it is possible, give opportunity for owners to see the whole list of members / subscribers in web-client

**Comment by envoleon** [comment]
Sad, but true, lost my channels from global search after spam(

**Comment by petrolingus** [comment]
need to be fixed guys!

**Comment by chezirish** [comment]
same happend to me, someone spamming with arabic subs to my channels...

**Comment by Aokromes** [comment]
this must be implemented server side, not telegram desktop, use in app ask a question or twiteer.

**Comment by Aokromes** [comment]
go to bugs.telegram.org
