### ISSUE TITLE
tdesktop modifies copied to clipboard text , adds link in brackets

### ISSUE THREAD

**Issue by errogaht** [telegramdesktop/tdesktop#8782]
![image](https://user-images.githubusercontent.com/6324265/95427277-f573b780-094f-11eb-82fe-29cffbff097e.png)
abc_d.zendesk.auth.email: 123
zendesk.auth.domain: 123

copied text becomes as:
abc_d.zendesk.auth.email (http://abc_d.zendesk.auth.email)

We glad to use telegram as main corporate chat, but recently telegrram added some strange algo that adds spam in brackets to copied text. please stop it! we dont want to wrap all in `

**Comment by john-preston** [comment]
🤔  It should wrap only URLs that are hidden like "random text with a link".

I'll try to fix that for such links.
