### ISSUE TITLE
[BUG] Insert link (Ctrl+K) doent't work if the link is not available from current device

### ISSUE THREAD

**Issue by ovcharenko-di** [telegramdesktop/tdesktop#8783]
### Steps to reproduce
1. Copy link to clipboard. The link to any resouce that is not available directly from current device
2. In a chat, hit Ctlr+K
3. Fill caption and insert copied link
4. Send message
5. Link in the message is gone

### Expected behaviour
Link should remain in sent message

### Actual behaviour
Link is gone

### Configuration
Win 10

**Version of Telegram Desktop:**
2.4.3

**Comment by MasterGroosha** [comment]
I don't understand what you mean by "link to any resouce that is not available directly from current device", but I've experienced the same bug recently with Telegram Desktop 2.4.3 (at least on Windows), when link becomes unclickable plain text

**Comment by ovcharenko-di** [comment]
My case: 
I've got self-hosted Gitlab instance that is accessible only in my RDP session. I can not access this Gitlab instance directly on my laptop where Telegram Desktop runs. And when I insert such link in Telegram Desktop it becomes unclickable plain text.

**Comment by MasterGroosha** [comment]
@ovcharenko-di hmm... I've encountered the same issue even with "reachable" links (for example, some publicly available news website)
