### ISSUE TITLE
possible bug in the feature : clicking on a forwarded message from channel scrolls to that message

### ISSUE THREAD

**Issue by mortezae** [telegramdesktop/tdesktop#8786]
In latest version it seems gone away. Is it intentionally disabled and why?
#2693

**Comment by RememberTheAir** [comment]
It still works for me. What version are you using?

**Comment by Mohammed-Laith** [comment]
It works for me, it's not gone. The latest version is 2.4.3, and I use it, download it from desktop.telegram.org
If you're using forks, this is something else, in that case, tell the fork's developer to look into that.

**Comment by mortezae** [comment]
@RememberTheAir Linux 64, I use latest version but from recent 5-6 releases I got aware about this problem.

**Comment by mortezae** [comment]
I tested it right now, it seems the problem is happening with "some" photo posts. Like [this one](https://t.me/DrMAschtiani/149). Does it work for you?

**Comment by RememberTheAir** [comment]
@mortezae I tried to forward that post to a private channel and clicked on the forward header, and tdesktop brings me to the correct message (Linux Mint based on ubuntu 18.10 and Pop!OS based on 20.04)

**Comment by mortezae** [comment]
@RememberTheAir then this seem a special case, as this problem happens sometimes (I tested it right now again and surprisingly worked)
Then I'm going to close this issue for now, If no team member comments about it.
