### ISSUE TITLE
Scheduled message: Right-clicking on caption area while photos are uploading, crashes the app

### ISSUE THREAD

**Issue by aemxn** [telegramdesktop/tdesktop#8788]
### Steps to reproduce
1. Upload _more than 1 images_ in Scheduled Message
2. Choose **Send as Album**
2. Write any text in the caption area
3. While the photo is uploading, **right-click in the caption area** will crash the app

> Note:
> Only crashes when Send as Album is selected. Haven't tried other files besides images.

### Expected behaviour
Popup a context menu (Cancel Upload, etc.) and continue the upload.

### Actual behaviour
Crashes/exits the app without notice.

### Configuration
**Operating system:** Windows 10 64-bit, ver 1909, build 18363.1082

**Version of Telegram Desktop:** 2.4.3

**Used theme**: Stock (Tinted)

<b>Logs</b>:
[fcd476f6-18a3-442b-99d1-9ab1a99517b8.zip](https://github.com/telegramdesktop/tdesktop/files/5353057/fcd476f6-18a3-442b-99d1-9ab1a99517b8.zip)

EDIT: Just knew I can send bug report on beta mode.

Your Report Tag: 078b221d-b2c5-4504-9e94-cc9a3ac71b3c
Your User Tag: 604427b8c0c233f0
[report.zip](https://github.com/telegramdesktop/tdesktop/files/5353069/report.zip)

**Comment by Mohammed-Laith** [comment]
not reproducible for files with captions, or any other things. Just for images with captions.
