### ISSUE TITLE
Media playback not working

### ISSUE THREAD

**Issue by auchri** [telegramdesktop/tdesktop#879]
Hi,

since the latest update 0.8.38 the media playback is not working:
![media playback](https://cloud.githubusercontent.com/assets/5092164/8507799/b94c83e2-2253-11e5-9a92-cbd7d339f971.gif)

Windows 8.1, 64 Bit

**Comment by Mindstormer619** [comment]
Need to check this to confirm. I had no idea telegram could play media in the app itself. 

Off topic: how did you make that gif? It's intriguing.

**Comment by auchri** [comment]
@Mindstormer619: https://screentogif.codeplex.com

**Comment by Mindstormer619** [comment]
Omg thanks a lot @auchri, I'm finding this utility more useful than the media playback in the first place :grin:

**Comment by Mindstormer619** [comment]
@auchri How do you get media to play within Telegram in the first place? I cannot seem to find this option or screen. It just downloads and plays with VLC for me.

**Comment by auchri** [comment]
Update to the latest version :)

**Comment by auchri** [comment]
fixed
