### ISSUE TITLE
Attempt to open file fails - path is split by space in folder name

### ISSUE THREAD

**Issue by navferty** [telegramdesktop/tdesktop#8792]
### Steps to reproduce
1. Default download folder is set
2. Try to open received pdf file in chat by single mouse click

### Expected behaviour
File is opened in default browser (Chrome)

### Actual behaviour
Two tabs with broken location are opened in Chrome - seems like the full path was split by space in folder name `Telegram desktop`:

`file:///C:/Users/navfe/Downloads/Telegram` and 
`http://desktop/cmd_report.pdf`

![image](https://user-images.githubusercontent.com/20906347/95571070-8ae67880-0a30-11eb-960d-45bad6bbe18a.png)

![image](https://user-images.githubusercontent.com/20906347/95571146-a3ef2980-0a30-11eb-9dc5-f2b1c22006b5.png)

The existing file is located at `file:///C:/Users/navfe/Downloads/Telegram%20desktop/cmd_report.pdf`

### Configuration
**Operating system:**

Windows 10 Pro 1909 18363.1082

**Version of Telegram Desktop:**

2.4.3

**Installation source (Linux Only)** - the official website / GitHub releases / flatpak / snap / distribution package:

official website

**Used theme**:

default

**Comment by Aokromes** [comment]
cannot reproduce myself with pdf files associated to sumatrapdf on windows 10 21h1 + telegram desktop 2.4.8.
