### ISSUE TITLE
[Feature Request] No spell checker in Scheduled Messages

### ISSUE THREAD

**Issue by M299792458** [telegramdesktop/tdesktop#8793]
### Is your feature request related to a problem?
No, it's just that there's a spell checker in any chat, but not while typing in the scheduled messaging mode.
I will say it in a different way: there's no spell checker system in the Scheduled Messages mode/section.

### Describe the solution you'd like
Please extend your implementation of the spell checker system, so that we can use it in the Scheduled Messages.

### Describe alternatives you've considered
Alternatives? Ah, there are alternatives; some OSes have spell checker system that works in every part in the system, and any app (afaik). But no! Some other OSes do not have such things, like Windows 7, for example. It's not dead yet. :) (and many other systems)

### Additional context
No context. Just that, and thanks in advance.

P.S: sorry if this is a duplicate, but I searched before, and I didn't find such thing.

**Comment by rondevous** [comment]
Use this title: "No spell checker in Scheduled Messages"

**Comment by Mohammed-Laith** [comment]
> Use this title: **No spell checker in Scheduled Messages**

Ok thanks. :)
