### ISSUE TITLE
Right-click menu disappears immediately 

### ISSUE THREAD

**Issue by laurin1** [telegramdesktop/tdesktop#8794]
Doesn't happen every time, but about 70% of the time. The issue started occurring within the last week. 

https://drive.google.com/file/d/1iFhFlvz0elBvE37F0ptOI2_Z7XEGHXLe/view?usp=sharing

Telegram Desktop Version 2.4.3
Windows 10 2004

Verified this occurs on more than one machine.

**Comment by ilya-fedin** [comment]
Maybe videodrivers update is the cause? There were no changes for context menu code.

**Comment by laurin1** [comment]
As I said, I can verify this on 2 different machines - one is on an older Nvidia driver that has not been updated in some time and the other is a current Nvidia driver.

**Comment by ilya-fedin** [comment]
Can you bisect with old versions and check on which version exactly the issue is appeared?

**Comment by laurin1** [comment]
I tried version 2.3.1 (Aug 22) and the issue still exists. Also, it's very inconsistent. Sometimes it happens on every try, other times not at all for a while. I don't have this issue in any other application, but I agree that it seems like a system issue. I'll keep digging.

**Comment by Aokromes** [comment]
any new on this?

**Comment by laurin1** [comment]
I apologize for not updating this issue, but as it turns out, it was a failing mouse that was actually doing a double-click at times I clicked the right-mouse button - strange though, only showed up in a couple of applications.
