### ISSUE TITLE
[Feature Request] Different Group features for different uses

### ISSUE THREAD

**Issue by yashpalgoyal1304** [telegramdesktop/tdesktop#8797]
### Is your feature request related to a problem?
Inefficiencies in the support forums groups (i.e. those having lots of traffic) currently.\
Example group: [tgbetachat](https://tx.me/tgbetachat) or [TG Party](https://t.me/PublicTestGroup)

### Describe the solution you'd like
There can be option of setting the privilege/flexibility level of the group.\
I am thinking that there can be 3 modes which will cover most (if not all) the use cases (referred to as **Setting** below):

1. Forums mode:
   - ability to edit messages forever.
   - [**stretch goal**] #8798 ability to change the message replied to.
   - Reactions would make it even better
   + **Reference:** RocketChat
   + **Setting:** Forums & support groups

2. Normal mode:
   - The current mode

3. Formal/Official mode:
   - No ability to edit messages.
   - No ability to delete other person's message (in individual chats that is - if this feature is extended to those)
   - Deleting leaves a trace/remnant message (Msg deleted by the user)
   + **Reference:** GreenApp (WA)
   + **Setting:** Formal and official use
   - It was criticised in the chat with reference of MS teams (with edit, and un-traced deletion features) being used in company settings.

discussed initially at (tgbetachat thread) :
- https://tx.me/tgbetachat/422305
- {if cant access the thread: the last reply is: https://tx.me/tgbetachat/425985?thread=422305 }

### Describe alternatives you've considered
The alternate can be to EITHER give these settings as individually set-able (i.e. rather than being in a preset) OR going the one size fits all route. If some other alternate came to my mind, i'll add.

### Additional context

---
P.S.
Thanks a lotttt for giving "[View replies feature](https://tx.me/tgbetachat/406834)" 💝🤩
![image](https://user-images.githubusercontent.com/19423063/95661837-1b67aa80-0b50-11eb-89af-406f98e99d99.png)
 ![image](https://user-images.githubusercontent.com/19423063/95661829-0db22500-0b50-11eb-8cba-19e58bf15b92.png)

**Comment by Aokromes** [comment]
such feature belongs to https://bugs.telegram.org/
