### ISSUE TITLE
[Feature Request] supercharging Replies

### ISSUE THREAD

**Issue by yashpalgoyal1304** [telegramdesktop/tdesktop#8798]
### Is your feature request related to a problem?
Currently:
- the replies cant be added later
- even the existing replies cant be modified
- the messages from other (public) source {group or channel} cant be
   - replied to in other chat
   -  forwarded as a reply in some chat\
see these: \
https://tx.me/tgbetachat/423004?thread=422971 \
https://tx.me/tgbetachat/423000?thread=422963

### Describe the solution you'd like
If thought, then reply is just like a message's short preview.\
So, in [rocket.chat](https://rocket.chat/) platform, the reply is actually just the message's link pasted as `[<space>](link)` in the starting of the message.\
If this is adopted, then all the above problems can be solved.

[**stretch goal**] ability to reply to multiple messages can be set as a stretch/extension goal

### Describe alternatives you've considered
No elegant solution coming to my mind which will satisfy all the foll:
- doesnt require any change in front end UI
   + so, no confusion on designs or some such
   +  the tg android ui cant handle even the existing functionality in a nice way, so it cant bear yet another ui based functionality while inputting text
   + and wont require any new shortcuts (for desktop) too
- intuitive
- solves/satisfies all three problems/use cases at same time

The messages mentioned in third point of problem were asking for some forwarding thing, which flew over my head right away. That can be considered as an alternate, but it wont satisfy any of the above points afaict.

**Comment by yashpalgoyal1304** [comment]
aint there a todo list feature here in gh?? i wanted to add todo (for adding rocketchat ss)

**Comment by Aokromes** [comment]
no, "api" things are handled internaly.

**Comment by yashpalgoyal1304** [comment]
i meant in the description. but anyways, thanks for clarification (:

**Comment by Aokromes** [comment]
such feature belongs to https://bugs.telegram.org/
