### ISSUE TITLE
[Feature Request] Dead or ignored chats

### ISSUE THREAD

**Issue by yashpalgoyal1304** [telegramdesktop/tdesktop#8799]
### Is your feature request related to a problem?
In the high traffic public channels (like OT chat groups, or support channels), the continuous updates are not relevant to every other person involved. But since there's no way to mute that, it becomes really distracting and so frustrating, and ultimately i feel forced to leave the groups.

### Describe the solution you'd like
I'd propose something like 'dead/ignored chats' {on the lines of muted chats}. This solution (all foll steps) would be applicable to individual chats too. This solution can be achieved in multiple steps:
1. setting the notifications to mentions/replies only (if not already muted)
2. stopping the chat to come to top of chat list {hereafter referred to as "list"} : #2590 \
which is currently done according to the recent activity level
3. hiding number count badges on the chat item in list {hereafter as "list item"}, 
4. hiding previews on list item (like 'xyz is typing' , 'xyz sent abc' , etc)\
I am saying this as last step, as if above 3 are done, these (previews) can be left enabled/visible even\
But personally, i'd like these to be hidden too.
5. [**stretch goal**] the seen status can be revoked when used in individual chats (inspired from instagram). \
But dont know if this fits with tg's design and philosophy.

For quick indication, 
- some icon (for example 🚫)  can be used\
at the same place where the :mute: icon goes currently.
- the list item can be made a bit grayed/faded \
(not recommended though: as will require additional work on themeing - in either case: be it manual or automatic)

tgbetachat thread:\
https://tx.me/tgbetachat/425786?thread=425695

### Describe alternatives you've considered
- i was gonna say notify only on mentions, but then i realised that there is no [existing issue](https://github.com/telegramdesktop/tdesktop/issues?q=is%3Aissue+is%3Aopen+notifications+on+mention) for this, so i included it as step 1. \
(t'was brought up on tgbetachat then i guess). 
- #2590 mentions this too, but it is all mingled up.

**Comment by magicgoose** [comment]
Is this something that can already be covered by "Archived Chats" feature?
