### ISSUE TITLE
Unicode characters not displayed on linux

### ISSUE THREAD

**Issue by jtojnar** [telegramdesktop/tdesktop#88]
Thanks to 0.5.12 I can use compose key now. Another problem arises though:

On my linux machine [→](http://codepoints.net/U+2192) and other higher code points can’t be displayed. CJK is replaced with rectangles as well (no wonder when even simple arrow isn’t supported).

On windows, my friend can see them though.

![arrow](https://cloud.githubusercontent.com/assets/705123/3748880/6e1cca28-17e4-11e4-93b5-c28252e81d8d.png)

Note the font is the same on both platforms.

**Comment by giyyapan** [comment]
Any update?

**Comment by acgtyrant** [comment]
I am amazing that it has passed half a year, the bug is still not fixed!

**Comment by juvevood** [comment]
please fix this bug

**Comment by vipjeffreylee** [comment]
Eagerly waiting to solve this bug.

**Comment by alinajafi** [comment]
Please check again with the latest version. I found almost all problems with Persian characters solved on the version 0.7.16. I also tried some symbols as well as CJK ideographs. It works.

**Comment by shouya** [comment]
@alinajafi Confirmed it worked (version 0.7.16). Thanks.

But there is still a tiny problem, that XIM cannot be enabled within tdesktop. Therefore I cannot use an input method. See https://github.com/telegramdesktop/tdesktop/issues/442

**Comment by acgtyrant** [comment]
@alinajafi Confirmed, thank you! But I am very disturbing with #442 too,

**Comment by giyyapan** [comment]
Since this bug is confirmed to be fixed, this issue should be closed :)

**Comment by 1kko** [comment]
Confirmed working from 0.7.16
and @acgtyrant yes now cannot write foreign characters using xim (fcitx, scim, nabi, etc) #442

**Comment by telegramdesktop** [comment]
Please check out 0.8.50 dev version, it should be fine there, I've added Qt plugins for IBus and Fctix.

**Comment by jtojnar** [comment]
You are right CJK is now working, sorry for keeping this open, I wasn’t getting notifications for some reason.

I don’t have IBus on current computer so I can’t test that one, but that’s a different issue anyways. Thanks for the fix, though.
