### ISSUE TITLE
[BUG] Emoji disabled

### ISSUE THREAD

**Issue by MrMorteZw** [telegramdesktop/tdesktop#8802]
### Steps to reproduce
1. Open telegram
2. Open a chat
3. select emoji

### Expected behaviour
send emoji 

### Actual behaviour
i click on emoji but nothing happend

### Configuration
**Operating system:*Windows 8.1*

**Version of Telegram Desktop:*2.4.3*

**Installation source (Linux Only)** - the official website / GitHub releases / flatpak / snap / distribution package:

**Used theme*Night mode*:

<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by RememberTheAir** [comment]
The first time you click on an emoji that support skin tones, the app asks you what skin tone to use. Are you sure it's not the case? Sometimes when you click on the emoji it's difficult to see the skin tone popup

**Comment by MrMorteZw** [comment]
> The first time you click on an emoji that support skin tones, the app asks you what skin tone to use. Are you sure it's not the case? Sometimes when you click on the emoji it's difficult to see the skin tone popup

there is no skin tones for laugh emoji
