### ISSUE TITLE
Change audio settings

### ISSUE THREAD

**Issue by fakeologist** [telegramdesktop/tdesktop#8804]
Are there any audio settings for mic/speaker in windows app?

**Comment by ilya-fedin** [comment]
There are only such settings for calls in the "advanced" menu in settings

**Comment by fakeologist** [comment]
I don't see it.
![image](https://user-images.githubusercontent.com/66537018/95748337-d3d44200-0c67-11eb-9c26-fe51d456ad61.png)
![image](https://user-images.githubusercontent.com/66537018/95748372-e2baf480-0c67-11eb-8965-56065d8d662f.png)

**Comment by RememberTheAir** [comment]
There should be a "System integration" category there, but you don't see it, I guess it depends on where you installed the app from. An alternative way of accessing the calls settings is side menu -> "calls" -> settings icon in the widget's header. But I'm not sure you'll see it

![image](https://user-images.githubusercontent.com/16143208/95749186-7eb22380-0c9b-11eb-8f40-f41405e04847.png)

**Comment by fakeologist** [comment]
> 
> 
> There should be a "System integration" category there, but you don't see it, I guess it depends on where you installed the app from. An alternative way of accessing the calls settings is side menu -> "calls" -> settings icon in the widget's header. But I'm not sure you'll see it
> 
> ![image](https://user-images.githubusercontent.com/16143208/95749186-7eb22380-0c9b-11eb-8f40-f41405e04847.png)

ok that was it. Thanks for the quick reply!
