### ISSUE TITLE
Crash in Calls

### ISSUE THREAD

**Issue by Nesty92** [telegramdesktop/tdesktop#8809]
### Steps to reproduce
1. Send the app to background
2. Make a call
3. Decline the call

### Expected behaviour
The app don't crash

### Configuration
Operating System: Manjaro Linux
KDE Plasma Version: 5.19.5
KDE Frameworks Version: 5.74.0
Qt Version: 5.15.1
Kernel Version: 5.8.9-2-MANJARO
OS Type: 64-bit

**Version of Telegram Desktop:**
2.4.3
**Installation source (Linux Only)** - the official website / GitHub releases / flatpak / snap / distribution package:
oficial website

**Used theme**:

<details><summary><b>Logs</b>:</summary>
`D/tgvoip: === Updating voip config ===
D/tgvoip: {"enable_vp8_encoder":true,"enable_vp8_decoder":true,"enable_vp9_encoder":true,"enable_vp9_decoder":true,"enable_h265_encoder":true,"enablecoder":true,"audio_frame_size":60,"jitter_min_delay_60":2,"jitter_max_delay_60":10,"jitter_max_slots_60":20,"jitter_losses_to_reset":20,"jitter_resynrate":20000,"audio_max_bitrate_edge":16000,"audio_max_bitrate_gprs":8000,"audio_max_bitrate_saving":8000,"audio_init_bitrate":16000,"audio_init_bitrate_saving":8000,"audio_bitrate_step_incr":1000,"audio_bitrate_step_decr":1000,"use_system_ns":true,"use_system_aec":true,"force_tcp":false,"jitter_incall_rating":true,"use_ios_vpio_agc":false,"use_tcp":false,"audio_medium_fec_bitrate":20000,"audio_medium_fec_multiplier":0.1,"audio_strong_fec_bitra

QCoreApplication::postEvent: Unexpected null receiver
`
</details>

**Comment by ilya-fedin** [comment]
#8585
