### ISSUE TITLE
Doesn't launch window on GNOME 3.38 but launches after suspend

### ISSUE THREAD

**Issue by compliment** [telegramdesktop/tdesktop#8811]
[log.txt](https://github.com/telegramdesktop/tdesktop/files/5374290/log.txt)

### Steps to reproduce
1. Launch tdesktop
2. Wait 
3. Suspend and wake up

### Expected behaviour
Tell us what should happen
tdesktop should launch it's window. 
### Actual behaviour
Tell us what happens instead
tdesktop's window doesn't launch immediately but runs in the background. Although, the window does show everytime after suspend.
### Configuration
**Operating system:**
Archlinux 
**Version of Telegram Desktop:**
2.4.3
**Installation source (Linux Only)** - the official website / GitHub releases / flatpak / snap / distribution package:
I have tried packages from 
- official website
- GitHub releases
- distribution's repository 
Same behavior throughout.
**Used theme**:
Default. 
<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
No useful info here because tdesktop runs as expected in background, just the window doesn't show up. 
</details>

**Comment by ilya-fedin** [comment]
I can't understand what's wrong by the description, can you provide a more detailed description?

**Comment by Mohammed-12345** [comment]
> I don't understand what's wrong by the description, can you provide a more detailed description?

Isn't this a duplicate? I guess

**Comment by ilya-fedin** [comment]
@compliment looks like you ignored "Logs" section in the template

**Comment by compliment** [comment]
> @compliment looks like you ignored "Logs" section in the template

Sorry, added. https://github.com/telegramdesktop/tdesktop/files/5374290/log.txt

**Comment by ilya-fedin** [comment]
Is this a log before the window is opened or after?

**Comment by compliment** [comment]
@ilya-fedin Upto the line `[2020.10.14 02:59:37] OpenAL Logging Level: (not set)` it's before suspend and before the window show up.
I have attached the log with before the suspend only. 
[log.txt](https://github.com/telegramdesktop/tdesktop/files/5374364/log.txt)

**Comment by ilya-fedin** [comment]
Try to launch tdesktop with `ALSOFT_DRIVERS=null`

**Comment by compliment** [comment]
> Try to launch tdesktop with `ALSOFT_DRIVERS=null`

It launches fine.

**Comment by ilya-fedin** [comment]
> It launches fine.

Something is wrong with your sound setup, device enumerating blocks tdesktop launching

**Comment by compliment** [comment]
Ah. ALSOFT_DRIVERS is not set, maybe it got removed while configuring pipewire.
Although, tdesktop launches with any value but not while it's unset. 

I'll close this since I don't it had anything to do with tdesktop. Thanks for your help.
