### ISSUE TITLE
[Feature Request] Add some way for external applications to interact with the music playing functionality

### ISSUE THREAD

**Issue by NightMachinary** [telegramdesktop/tdesktop#8813]
### Is your feature request related to a problem?
I use Telegram as my main music player, and I like to be able to get the name of the currently playing song, and start/pause the music, from a bash script.

### Possible solutions

- Add support for Applescript, but that only works for macOS.
- Support URL schemes, but that, too, might only work reliably on macOS? (Idk.)
- Using a web server that listens on the localhost
- A simple Unix socket can work as well, though not on Windows?

**Comment by Mohammed-12345** [comment]
The idea is that Telegram is -unfortunately- not a music player, it can play them, but it's main purpose is messaging.

**Comment by ilya-fedin** [comment]
I guess @NightMachinary asking for MPRIS

**Comment by chekoopa** [comment]
Yes, MPRIS, sure it is. Dups #3960.

**Comment by NightMachinary** [comment]
> Yes, MPRIS, sure it is. Dups #3960.

Is MPRIS crossplatform, or is it Linux-only? 

Btw, MPRIS might be too big to implement. My proposed solutions seem very simpler.

**Comment by ilya-fedin** [comment]
> Is MPRIS crossplatform, or is it Linux-only?

Yes, but all of your proposals are too specific. Web server in a messenger? Really?

**Comment by NightMachinary** [comment]
> > Is MPRIS crossplatform, or is it Linux-only?
> 
> Yes, but all of your proposals are too specific. Web server in a messenger? Really?

Sorry, does “yes” mean it is Linux-only or not?

I think the webserver solution is quite practical. Telegram already takes around 800MB of my ram, and a webserver will add what, 50MB of ram? The CPU usage should be negligible as well. There are lots of libraries for implementing the HTTP API, too.

**Comment by ilya-fedin** [comment]
> Sorry, does “yes” mean it is Linux-only or not?

Yes, it means.

**Comment by ilya-fedin** [comment]
> Telegram already takes around 800MB of my ram, and a webserver will add what, 50MB of ram?

The fact that a messenger contains a web server is still a nonsense
