### ISSUE TITLE
building: gyp patch does not applying

### ISSUE THREAD

**Issue by a-x-** [telegramdesktop/tdesktop#8821]
### Steps to reproduce
1. git clone https://github.com/desktop-app/patches.git && patches && git checkout ddd4084 && cd ..
1. git clone https://chromium.googlesource.com/external/gyp && cd gyp
2. git checkout 9f2a7bb1
3. git apply ../patches/gyp.diff

### Expected behaviour
gyp installed, build prepared, tdesktop builded

### Actual behaviour

```
HEAD is now at 9f2a7bb1 Add flake8 checks to travis configuration.
error: patch failed: pylib/gyp/MSVSVersion.py:268
error: pylib/gyp/MSVSVersion.py: patch does not apply
error: patch failed: pylib/gyp/generator/cmake.py:1078
error: pylib/gyp/generator/cmake.py: patch does not apply
error: patch failed: pylib/gyp/generator/xcode.py:74
error: pylib/gyp/generator/xcode.py: patch does not apply
```

### Configuration
**Operating system:** macOS Catalina 10.15.6

**Version of Telegram Desktop:** master (2.4.3)

**Installation source (Linux Only)** - dev build

**Comment by a-x-** [comment]
manual I use: https://github.com/telegramdesktop/tdesktop/blob/dev/docs/building-xcode.md#clone-source-code-and-prepare-libraries

**Comment by xvitaly** [comment]
GYP is no longer required. Telegram Desktop now uses Cmake.

**Comment by a-x-** [comment]
Oh, jesus,
Hm, can you update the manual? 
Might be some other updates are there

**Comment by a-x-** [comment]
https://github.com/telegramdesktop/tdesktop/pull/8829

**Comment by a-x-** [comment]
Hey, @xvitaly, 
@ilya-fedin says:
> Telegram uses gyp [...] to build tdesktop dependencies.

**Comment by ilya-fedin** [comment]
@xvitaly is a Fedora maintainer, they building Telegram in another way

**Comment by a-x-** [comment]
I built all dependencies w/o gyp.

But I have an error after a while of Resulting xCode Telegram compilation:
```
ld: in /Users/ruafjxn/xp/TBuild/Libraries/macos/ffmpeg/libavcodec/libavcodec.a(aacpsdsp.o), building for macOS, but linking in object file built for free standing, file '/Users/ruafjxn/xp/TBuild/Libraries/macos/ffmpeg/libavcodec/libavcodec.a' for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by a-x-** [comment]
I'm new in xCode, but I have some Qt experience

<img width="1076" alt="Screenshot 2020-10-16 at 01 27 03" src="https://user-images.githubusercontent.com/6201068/96192447-b694c180-0f4e-11eb-8d78-45b8b7634736.png">

**Comment by ilya-fedin** [comment]
> But I have an error after 10–30 minutes of final xCode Telegram compilation

Because it tries to link to libraries that you didn't compile

**Comment by a-x-** [comment]
Error says, I do have library (it's really true), but it's not properly pre-compiled.
I tried to re-compile it in some ways, also

**Comment by a-x-** [comment]
<img width="773" alt="Screenshot 2020-10-16 at 10 34 40" src="https://user-images.githubusercontent.com/6201068/96226396-3ba5c800-0f9b-11eb-8234-6b2ccbf2cdc8.png">


<img width="640" alt="Screenshot 2020-10-16 at 10 32 35" src="https://user-images.githubusercontent.com/6201068/96226189-f1244b80-0f9a-11eb-97a0-c511d132bb71.png">

**Comment by a-x-** [comment]
@ilya-fedin, share please you working build script.

Also, scripts should be make files, copy-pasting from browser is not so good idea

**Comment by a-x-** [comment]
I dont understand what a problem, looks like library compiled correctly:
```sh
ar -x ffmpeg/libavcodec/libavcodec.a
file aac_ac3_parser.o
    aac_ac3_parser.o: Mach-O 64-bit object x86_64
```

**Comment by a-x-** [comment]
@ilya-fedin, готов заплатить за час консультации =)

мне нужна работающая конфигурация билда, 
за одно и в репу положим актульную в мейк-файл, 
Необходимо чтобы все использовали этот скрипт по возможности, чтобы он вегда был актуальным,
такое себе хранить их в md.

**Comment by 23rd** [comment]
> ld: in /Users/ruafjxn/xp/TBuild/Libraries/macos/ffmpeg/libavcodec/libavcodec.a(aacpsdsp.o), 
> building for macOS, but linking in object file built for free standing, 
> file '/Users/ruafjxn/xp/TBuild/Libraries/macos/ffmpeg/libavcodec/libavcodec.a' for architecture x86_64
> 
> clang: error: linker command failed with exit code 1 (use -v to see invocation)

Most likely you just ignored the first four variables at the moment you built ffmpeg.

**Comment by a-x-** [comment]
> Most likely you just ignored the first four variables at the moment you built ffmpeg.

hm, I even re-declare them several times...

Ok, I'll try more accurately

**Comment by a-x-** [comment]
```
ffmpeg: ./configure ...

...
install prefix            /usr/local/macos
source path               .
C compiler                gcc
C library
ARCH                      x86 (generic)
big-endian                no
runtime cpu detection     yes
standalone assembly       yes
x86 assembler             yasm
```

**Comment by a-x-** [comment]
@23rd, It ok now! Thank you

I don't understand how I missed envs...

**Comment by a-x-** [comment]
@ilya-fedin 
So, I didn't install gyp here and everything looks ok!

**Comment by a-x-** [comment]
платная консультация всё ещё актуальна

в xCode с телеграмом как-то очень избирательно работают брекпоинты и не пишутся логи, хотя я везде насильно выставил `Logs::DebugEnabled(true)`

я хочу сделать форк [IDE для менеджера](https://www.notion.so/thsm/IDE-91b81120fb364a4c81b7fcd7fc9dcb76) [Чат (Telegram) с тасками (e.g. Asana), файлами (e.g. G Drive) и браузером].

а в основной версии починить или сделать что-нибудь несложное если нужно
