### ISSUE TITLE
App crashes on MacOS when video call starts with Windows user

### ISSUE THREAD

**Issue by kartpick** [telegramdesktop/tdesktop#8822]
### Steps to reproduce
1. Open Telegram Desktop app on mac.
2. Start Video call with Windows OS user (actually Windows 10);
3. User gets your call and Telegram app closes on mac. But call on the windows side is not closing.

### Expected behaviour
Telegram Desktop app should not close on macOS when video call starts.

### Actual behaviour
App crashes when video call starts, and call on Windows user side not finishing. And no crashing message shows when I restart Telegram Desktop.

### Configuration
**System configuration:**
MacBook Pro (16-inch, 2019)
macOS Catalina 10.15.7 (19H2)
**Version of Telegram Desktop:**
2.4.3 (downloaded package from web, not from AppStore)

At first time I thought that person I call uses broken virtual video drivers, but I tried to call to another person, and bug repeated. And, after that I tried to call to mobile with video, and everything worked well.

**Comment by ilya-fedin** [comment]
#8585
