### ISSUE TITLE
Notification sound doesn’t respect setting

### ISSUE THREAD

**Issue by jurf** [telegramdesktop/tdesktop#8824]
### Steps to reproduce
1. Disable ‘Play sound’ in Settings → Notifications → Notifications for chats
2. Switch to another window
3. Recieve a message.

### Expected behaviour
A notification sound should not play.

### Actual behaviour
The notification sound plays.

### Configuration
**Operating system:** Fedora Silverblue 32

**Version of Telegram Desktop:** 2.4.3

**Installation source (Linux Only)**: Flatpak

**Used theme**: Day

**Comment by ilya-fedin** [comment]
When you disable notification sound, tdesktop stops setting `suppress-sound` hint and gnome may play notification sound on its own.
