### ISSUE TITLE
Some users can't be mentioned

### ISSUE THREAD

**Issue by M299792458** [telegramdesktop/tdesktop#8826]
Unlike Android, as the title says, some users can't be mentioned using the '@' if they have a special (not really special) character as the first letter of their names.
I didn't try everything, but from what i tried the case is with these characters:
'.'  (A dot)
'#' (A hashtag)
',' (A comma)
'@' (the "at" symbol/sign)
'!' (the exclamation mark)
And I suspect that the issue can be reproduced with many other characters. And as I said up, Android client can mention those without problems, in contrary to TD. :(
For example, i can't mention someone who has the name (not username): '@blabla' or '#blabla'.
Telegram Desktop 2.4.3
Please fix that.
Thanks!

**Comment by BLUE-DEVIL1134** [comment]
well there is a better way of mention
links!!
lets say y name is "@xyz" including "@"
you can mention me like [Name](https://t,.me/USERNAME)
or this way
[Name](tg://USER_ID)

**Comment by RememberTheAir** [comment]
@BLUE-DEVIL1134 that doesn't work if the user doesn't have an username

**Comment by Mohammed-12345** [comment]
Thanks for your comment @BLUE-DEVIL1134, that's well known. but nah, as @RememberTheAir said: it won't work without a username.
But i also have to disagree with Remember the Air, because there are always ways, like for example [this](https://t.me/tg_x64/156), but that's obviously an unofficial client. Since we are using (talking about) the official client here I wouldn't disagree with Remember The Air :)

**Comment by BLUE-DEVIL1134** [comment]
we can use id

tg://user_id

**Comment by Mohammed-12345** [comment]
> we can use id
> 
> tg://user_id

are you sure? and if so, where? (Android, iOS, Desktop)
for example, this:
tg://openmessage?user_id=914597
opens a chat with Mike Ravdonikas. And it works with Android client.
And this one:
t.me/@id914597
works in iOS.
But neither of can be used to mention users, that is wrong.
Only the way that I talked about up works with id, and as i said it's only for td x64.
Simply, TD can't mention users with those characters by typing '@' in the input field in a group chat. No workarounds.
And moreover, the format you mentioned is wrong.

**Comment by BLUE-DEVIL1134** [comment]
> > we can use id
> > tg://user_id
> 
> are you sure? and if so, where? (Android, iOS, Desktop)
> for example, this:
> tg://openmessage?user_id=914597
> opens a chat with Mike Ravdonikas. And it works with Android client.
> And this one:
> t.me/@id914597
> works in iOS.
> But neither of them can be used to mention users, that is wrong.
> Only the way that I talked about up works with id, and as i said it's only for td x64.
> Simply, TD can't mention users who have those characters as the first character in their names by typing '@' in the input field in a group chat. No workarounds.
> And moreover, the format you mentioned is wrong.

u are understanding it wrong
i will tell the correct way today

**Comment by BLUE-DEVIL1134** [comment]
@Mohammed-12345 

I found It
it works everywhere..

tg://user?id=THE_USER_ID

Replace THE_USER_ID with the user's user_id

**Comment by Mohammed-12345** [comment]
> @Mohammed-12345
> 
> I found It
> it works everywhere..
> 
> tg://user?id=THE_USER_ID
> 
> Replace THE_USER_ID with the user's user_id

It doesn't, i tried it in tdesktop, android and asked a friend of mine who has an iOS to try it and he said that it doesn't. But he added more information, he said that it does work with bot api. But anyways, we are talking about normal use case here, between the members of a group, without bots, and without any extra thing.
I would like to see a screencast from your side Mr. Blue so that I can clearly see how it works to mention users/members in a group, because, unfortunately, neither me nor my friends could make it works in any environment, we couldn't use it to mention members in a group. Could you?

**Comment by BLUE-DEVIL1134** [comment]
Well In My Groups All Have Proper-names
Still If You Say..
I Will Search For A Better Way Of Solving Ur Problem

**Comment by Mohammed-12345** [comment]
> Well In My Groups All Have Proper-names
> Still If You Say..
> I Will Search For A Better Way Of Solving Ur Problem

Thanks for your cooperation.
I guess this problem can't be solved without someone who has a good understanding of TD's code. Unfortunately, I'm a non coder, if I were a programmer who has a good knowledge in C++, I would solve it as soon as possible.
I hope Preston will look into this.

**Comment by BLUE-DEVIL1134** [comment]
> Thanks for your cooperation.
> I guess this problem can't be solved without someone who has a good understanding of TD's code. Unfortunately, I'm a non coder, if I were a programmer who has a good knowledge in C++, I would solve it as soon as possible.
> I hope Preston will look into this.

tg://user?id=THE_USER_ID
Replace THE_USER_ID with the user's user_id

This Is working for me if used n markdown
like this 

```
[Akash](tg://user?id=1003250439)
```

**Comment by Mohammed-12345** [comment]
Okay. Thanks.

**Comment by SharkPoor** [comment]
### RSP

**Comment by BLUE-DEVIL1134** [comment]
can this be closed now?
