### ISSUE TITLE
Window has its own style, doesn't use window manager or match the OS look

### ISSUE THREAD

**Issue by teo1978** [telegramdesktop/tdesktop#8827]
### Steps to reproduce
1.  open Telegram

### Expected behaviour

Telegram is an application that runs in a window, and I expect its window to have the same look-and-feel and the same interface as all the other windows in the OS it's in.

### Actual behaviour

I am using OpenSUSE linux which comes with KDE Plasma; previously on another computer I was using Ubuntu with Gnome and then with Cinnamon. In all cases, I observed the same problem.

The OS and the Desktop Environment (in my case currently KDE Plasma) provide their own window system and a common interface and look-and-feel for all windows. All applications use that window system and look the same.

But Telegram does not. It has its own design which doesn't match the OS.

Examples:

Google Chrome:
![image](https://user-images.githubusercontent.com/542107/96007166-86f69400-0e3e-11eb-95a5-3c1c96c1700a.png)

Terminal:
![image](https://user-images.githubusercontent.com/542107/96007266-9bd32780-0e3e-11eb-8e9b-5ec282f0bf02.png)

Telegram:
![image](https://user-images.githubusercontent.com/542107/96007342-b0afbb00-0e3e-11eb-98a7-651ab63dd7ec.png)

### Configuration
**Operating system:** OpenSUSE Tumbleweed

**Version of Telegram Desktop:** I don't know, downloaded today

**Installation source (Linux Only)** - the official website 

**Used theme**: no idea, the default one.

**Comment by RememberTheAir** [comment]
Under settings -> advanced -> system integration, there should be a "use system window frame" option.

> Version of Telegram Desktop: I don't know, downloaded today

It's in the sidebar

**Comment by ilya-fedin** [comment]
This is not a bug, Telegram has its own style.

**Comment by teo1978** [comment]
> Under settings -> advanced -> system integration, there should be a "use system window frame" option.

Oh great.

That should be the default.

> This is not a bug, Telegram has its own style.

Ok it's a design flaw then. Something wrong that needs fixing, either way.

**Comment by ilya-fedin** [comment]
> Ok it's a design flaw then. Something wrong that needs fixing, either way.

That's just your opinion. Window decorations are a part of application and should be in application style.

**Comment by teo1978** [comment]
> Window decorations are a part of application and should be in application style.

Would you imagine if all applications applied that reasoning?? Every application with its own style, and not only that, ones with the close button on the right and others on the left. Some with thicker title bars and others thinner. That would be madness.

But of course, as long as you are the only one that does it, then it's fine. Except that if you think like that then everybody else is entitled to do the same.

**Comment by teo1978** [comment]
That we even have to be discussing this in 2020 🤦

**Comment by ilya-fedin** [comment]
> Would you imagine if all applications applied that reasoning??

You don't need to imagine, this is already the case with most of GTK3 applications.

**Comment by Aokromes** [comment]
> > Window decorations are a part of application and should be in application style.
> 
> Would you imagine if all applications applied that reasoning?? Every application with its own style, and not only that, ones with the close button on the right and others on the left. Some with thicker title bars and others thinner. That would be madness.
> 
> But of course, as long as you are the only one that does it, then it's fine. Except that if you think like that then everybody else is entitled to do the same.

it's called cross platform universal look, they want the application to look the same on every os you run it, like a lot of cross platform applications.

**Comment by teo1978** [comment]
>  like a lot of cross platform applications.

Name a few.
I know you will, but I want to see how many of them are major applications used by most people every day.

> they want the application to look the same on every os you run it

Of course they do! I would want that too if I were developing an application. The problem is, users want all the applications to look the same in the os they run them.

**Comment by ilya-fedin** [comment]
Oh, looks like you want to start a holiwar, I don't want to.
I'm already told my position, it won't change based on how behave other applications that you are using, sorry.

**Comment by teo1978** [comment]
> Oh, looks like you want to start a holywar, I don't want to.

Not at all. I just asked you to name some examples of the "most of GTK applications" or "a lot of cross platform applications"  because I'm curious.
