### ISSUE TITLE
Window sticks over to adjacent monitors when maximized

### ISSUE THREAD

**Issue by littleme02** [telegramdesktop/tdesktop#883]
Screenshot
http://i.imgur.com/Yzh1SL5.jpg

**Comment by Walkman100** [comment]
:+1: i find this incredibly annoying, but usually I just close the window to the tray 
Windows 7 SP1

**Comment by dozz-a** [comment]
Happens to me too, pretty annoying but nothing major.
Win 7 SP1

**Comment by auchri** [comment]
Duplicate #373
