### ISSUE TITLE
Channel To Discussion Link Bug

### ISSUE THREAD

**Issue by BLUE-DEVIL1134** [telegramdesktop/tdesktop#8830]
its the latest update and 

you see, when i posted a message on channel it didnt went to the disscussion
and yes, i was waiting for 10 mins and it didnt came, so deleted the message and posted again still the same...

i doubt its a server slow issue or somethng else..

Windows : 10 (Latest Version)
I dont think it needs my version

![example gif](https://user-images.githubusercontent.com/55914808/96111140-6db51c80-0efe-11eb-8e18-635d67002690.gif)

**Comment by MasterGroosha** [comment]
Please choose more specific issue title so that it can be searchable
