### ISSUE TITLE
"Save File as..." etc. do not seem to work

### ISSUE THREAD

**Issue by Tianmaru** [telegramdesktop/tdesktop#8831]
# Steps to reproduce
1. Select a chat where a file (for example an image) was sent
2. Right click the image to open the context menu
3. Select "Save Image as..."

### Expected behaviour
A file selection dialogue window should pop up, that allows the user to select a destination to store the file to.

### Actual behaviour
Nothing.

### Configuration
**Operating system:** Debian 10 (Buster) + KDE

**Version of Telegram Desktop:** 2.4.3

**Installation source (Linux Only)** - the official website / GitHub releases / flatpak / snap / distribution package: The official website

**Used theme**: Light

**Comment by ilya-fedin** [comment]
Maybe you have `xdg-desktop-portal` package instaled, but don't have any of its backends (`xdg-deskto-portal-gtk`, `xdg-desktop-portal-kde`) installed? It's a distro issue if it allows to install xdg-desktop-portal without any backends.

**Comment by Tianmaru** [comment]
Wow, thanks, you were absolutely correct. I installed xdg-desktop-portal-kde and now it's working as intended. I will close this issue.
May I ask you, just because I am curious: How did you know instantly what was wrong? I always feel kind of stupid when that happens :sweat_smile:

**Comment by ilya-fedin** [comment]
> How did you know instantly what was wrong?

This is not the first issue about that :new_moon_with_face:
