### ISSUE TITLE
[Feature Request] Keyboard shortcut to account switch

### ISSUE THREAD

**Issue by Alveona** [telegramdesktop/tdesktop#8836]
### Is your feature request related to a problem?
TG Desktop is almost fully usable via keyboard only with [this](https://github.com/telegramdesktop/tdesktop/wiki/Keyboard-Shortcuts) shortcuts, but you can't change accounts instantly to see other dialogs.

### Describe the solution you'd like
Add a shortcut to change accounts. (Cmd-P, which is from "Profile"?)

### Describe alternatives you've considered
None

### Additional context
None

**Comment by 23rd** [comment]
#8179.

**Comment by Alveona** [comment]
Yep, my bad.
