### ISSUE TITLE
Always +1 unread message (Macos)

### ISSUE THREAD

**Issue by alexkuzmin** [telegramdesktop/tdesktop#8837]
About last 6 Months i see always +1 unread message, i.e. when all messages are read, it shows "1" as unread message near Telegram icon. When 1 message is unread, it shows "2" and so on. Any updates or reinstallations don't help. The problem is only on Mac Desktop app.

**Comment by 23rd** [comment]
Please provide a version you use.

**Comment by alexkuzmin** [comment]
Version 2.4.3
