### ISSUE TITLE
Wrong Mic for Audio Record

### ISSUE THREAD

**Issue by Wyzp** [telegramdesktop/tdesktop#8842]
```
System: Manjaro Linux
Kernel:  5.8.11-1
Laptop : OMEN HP Laptop 15-ce0xx
Telegram Desktop Version: 2.4.3
```

Not sure if it happens only to me, but In call mic works normal, but not for Audio record. Checking in Pulse Audio I got that when I press to record audio mic falls back to "Monitor of Built-in Audio Analog Stereo" instead default mic "Built-in Audio Analog Stereo" (also selected in Settings>Advanced>Call Settings).

Note: Audio Record works normal using Telegram Web on Mozilla Firefox.

**Comment by ilya-fedin** [comment]
Telegram uses alcCaptureOpenDevice with nullptr, what means "default device":
https://github.com/telegramdesktop/tdesktop/blob/2aa0b674cde819d4b84ccf1e7778de440ab573e9/Telegram/SourceFiles/media/audio/media_audio_capture.cpp#L234

All what going next is openal responsibility and there is nothing that tdesktop can do about that.
