### ISSUE TITLE
KDE removed option "Autostart only in Plasma" from autostart settings so now the telegram is starting crashed.

### ISSUE THREAD

**Issue by qg0** [telegramdesktop/tdesktop#8843]
Telegram 2.4.3
Linux acer 5.8.14-1-default #1 SMP Wed Oct 7 06:23:04 UTC 2020 (cea47bb) x86_64 x86_64 x86_64 GNU/Linux
Operating System: openSUSE Tumbleweed 20201014
KDE Plasma Version: 5.20.0
KDE Frameworks Version: 5.75.0
Qt Version: 5.15.1
Kernel Version: 5.8.14-1-default
OS Type: 64-bit

KDE removed the option "Autostart only in Plasma" from autostart settings so now the Telegram is starting crashed. Telegram is starting before Plasma.

![image](https://user-images.githubusercontent.com/919099/96348125-9725a200-10d0-11eb-8f45-a32a0d842368.png)

**Comment by ilya-fedin** [comment]
I don't understand, what the issue is?

**Comment by qg0** [comment]
If the telegram is starting before Plasma, then it's crashed and asks to send a crash report.
There was an option in austostart KDE settings "autostart only in Plasma" and the telegram started normally.
Now I don't see this option in the KDE settings and telegram is starting crashed.
I guess the reason is that in started before Plasma.
If I make a script in autostart like "sleep 30; ~/bin/telegram --u", then it started normally.

**Comment by ilya-fedin** [comment]
Then send a crash report and post a crash report tag here.

**Comment by ilya-fedin** [comment]
@qg0 will you provide a crash report tag or the issue could be closed?

**Comment by qg0** [comment]
There are no problem now.

**Comment by ilya-fedin** [comment]
I asked for crash report tag, this backtrace is useless since you don't have debug symbols.

**Comment by qg0** [comment]
I see only "telegram-cli-debuginfo" and "telegram-cli-debugsource". Are these packages are needed?

**Comment by ilya-fedin** [comment]
No, if you are running official binary, you should just give the crash report tag
