### ISSUE TITLE
MacOS Client Does Not Correctly Send Video

### ISSUE THREAD

**Issue by roryhardy** [telegramdesktop/tdesktop#8844]
### Steps to reproduce
1. Send video in a call from the MacOS client

### Expected Behavior
Receiver sees senders video

### Actual Behavior
No video is shown. However, the receiver does see video when sent from the iOS client

### Configuration
**Operating system:**

Tested on both MacOS Mojave and Catalina

**Version of Telegram Desktop:**

Both on 2.4.3

**Used theme**: Tinted

**Comment by Hypfer** [comment]
I can confirm that this issue is still happening on Catalina with 2.4.7
