### ISSUE TITLE
Image and video preview shows always in the first monitor of a multi monitor setup

### ISSUE THREAD

**Issue by amatas** [telegramdesktop/tdesktop#8845]
### Steps to reproduce
1. Use a setup with more than 1 monitor. In my case I use 3 monitors (laptop + two 4k monitor) in Linux with wayland)
2. Move Telegram to other than the first monitor
3. Click on an image
4. The preview of the image shows always in the first monitor with the resolution of the monitor where the Telegram app is.

### Expected behaviour
Open the preview in the same monitor where the application is, with the resolution of such monitor.

### Actual behaviour
 The preview of the image shows always in the first monitor with the resolution of the monitor where the Telegram app is. So if the application is in a monitor with 4k resolution and the first monitor uses 2k you can only see the first 1/4 of the image in the 2k monitor.

### Configuration
**Operating system:**

Linux 5.8.14-arch1-1 #1 SMP PREEMPT Wed, 07 Oct 2020 23:59:46 +0000 x86_64 GNU/Linux
Gnome 3.38 + Wayland 1.18.0 + QT 5.15.1

**Version of Telegram Desktop:**

2.4.3

**Installation source (Linux Only)** - the official website / GitHub releases / flatpak / snap / distribution package:

Archlinux binary package

**Used theme**:

Dark

**Comment by ilya-fedin** [comment]
#5126
