### ISSUE TITLE
Cannot send file on Ubuntu

### ISSUE THREAD

**Issue by H4kt** [telegramdesktop/tdesktop#8847]
### Steps to reproduce
Open any chat
Find your file on your preferred file manager
Drag & drop file to the chat window

### Expected behaviour
File should upload as normal

### Actual behaviour
File upload fails

### Configuration
**Operating system:** Ubuntu 20.04.1 LTS
**Version of Telegram Desktop:** 2.4.3
**Installation source (Linux Only)**: snap store

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/8831#issuecomment-709421414 ?

**Comment by H4kt** [comment]
Nope, I've got `xdg-desktop-portal-gtk` installed

**Comment by ilya-fedin** [comment]
> File upload fails

Maybe you're trying to drag'n'drop a file outside your home directory? Snap sandbox prevents such attempts.

**Comment by H4kt** [comment]
Yeah, the file is outside my home dir. I've got multiple hard drives, so is there any workaround with that issue?

**Comment by ilya-fedin** [comment]
You can copy files to the home dir or install Telegram in a way without sandbox, the binary from desktop.telegram.org for example.
