### ISSUE TITLE
[Feature Request] An option to display exact time of user's last online presence, instead of "... ago".

### ISSUE THREAD

**Issue by azat11** [telegramdesktop/tdesktop#8848]
At least in Android app the exact time is still displayed. And I hate this "... ago" sh*t. It is SO UNINFORMATIVE.
My request is to give the choice to users on how it'll be displayed.

The only alternative is stop using official Telegram clients, and choose the ones that suit me (if they even exist).

**Comment by Mohammed-12345** [comment]
breaks privacy, and no, Android client can't do that, it shows the same:
_last seen recently_, _last seen a long time ago_ etc.
this is the same as how Telegram Desktop shows it.
and lastly, no, there isn't any unofficial client that can do that.
this is something that is done by the server-side not the client-side, if you really want that, try talking with the in-app support, or with Telegram in Twitter. but no, as i said up, this breaks privacy, they will never do that. I understand that, _maybe_ in your case, it doesn't break anyone's privacy, but it does when applying that to the whole client which are used by millions of people.
so in other word: no.

**Comment by azat11** [comment]
> breaks privacy, and no, Android client can't do that, it shows the same:
> _last seen recently_, _last seen a long time ago_ etc.
> this is the same as how Telegram Desktop shows it.
> and lastly, no, there isn't any unofficial client that can do that.
> this is something that is done by the server-side not the client-side, if you really want that, try talking with the in-app support, or with Telegram in Twitter. but no, as i said up, this breaks privacy, they will never do that. I understand that, _maybe_ in your case, it doesn't break anyone's privacy, but it does when applying that to the whole client which are used by millions of people.
> your assumption is correct "_if they even exist_", they don't.
> 
> so in another word: no.

I think you misunderstood me. I meant "1 hour ago" and the like.
Here's a screen from Android app that shows the exact time the user's been seen online: https://ibb.co/rFdzjq4

**Comment by azat11** [comment]
@Aokromes Can you reopen this, please??

**Comment by Mohammed-12345** [comment]
> > breaks privacy, and no, Android client can't do that, it shows the same:
> > _last seen recently_, _last seen a long time ago_ etc.
> > this is the same as how Telegram Desktop shows it.
> > and lastly, no, there isn't any unofficial client that can do that.
> > this is something that is done by the server-side not the client-side, if you really want that, try talking with the in-app support, or with Telegram in Twitter. but no, as i said up, this breaks privacy, they will never do that. I understand that, _maybe_ in your case, it doesn't break anyone's privacy, but it does when applying that to the whole client which are used by millions of people.
> > your assumption is correct "_if they even exist_", they don't.
> > so in another word: no.
> 
> I think you misunderstood me. I meant "1 hour ago" and the like.
> Here's a screen from Android app that shows the exact time the user's been seen online: https://ibb.co/rFdzjq4


I think your words changed, but anyways, there's incomplete comprehension of the case here.
It shows what you want. The images here show that  what you want is already here. :) 
And please, understand, this is just a case, an example, feel free to try it with different users.

![٢٠٢٠١٠٢٠_١٤٢٤٠٧](https://user-images.githubusercontent.com/71488567/96598971-16e18580-12f8-11eb-93ff-021124b418bc.jpg)

![٢٠٢٠١٠٢٠_١٤٢٣٤٣](https://user-images.githubusercontent.com/71488567/96599084-38db0800-12f8-11eb-8562-ab6780960324.jpg)

**Comment by Mohammed-12345** [comment]
> @Aokromes Can you reopen this, please??

No need.

**Comment by azat11** [comment]
@Aokromes In the desktop client it always shows me "1/2/3 hour(s) ago" version, and never for any chat shows the exact time, like your example on the screen "last seen today at 11:45". But in Android app it shows me exact time for those same chats. Why??

![tg_screen_desk](https://user-images.githubusercontent.com/20098838/97020893-cd44a500-155a-11eb-8577-d351fb2b3fdb.jpg)
![tg_screen_andr](https://user-images.githubusercontent.com/20098838/97020907-d2095900-155a-11eb-9ce9-3654750e0579.jpg)

**Comment by RememberTheAir** [comment]
>  like your example on the screen "last seen today at 11:45"

You have to open the contact's profile (click on the name)
