### ISSUE TITLE
[Question] How do I upload GIFs uncompressed???

### ISSUE THREAD

**Issue by azat11** [telegramdesktop/tdesktop#8849]
Telegram's compression messes up these GIFs making them look terrible, unlike originals.

**Comment by sepehr-brj** [comment]
send mp4 without audio

**Comment by ilya-fedin** [comment]
there is no way

**Comment by azat11** [comment]
> there is no way

That is terrible.

**Comment by azat11** [comment]
> send mp4 without audio

That's not really a solution. I can not turn all of my gifs into mp4 just for Telegram.
