### ISSUE TITLE
Limit on the number of stickers

### ISSUE THREAD

**Issue by rezatorabi** [telegramdesktop/tdesktop#885]
There seems to be a limit of 20 custom stickers packs. If I add one sticker pack more than 20, one of the previous packs disappears.
People had the same problem as you see in issue #788 but the difference was that the client gave an error when they tried to add more than 20 sticker packs but now it doesn't give an error and just one of the previous packs disappears.
https://twitter.com/telegram/status/606457674558017536
https://twitter.com/telegram/status/606506502946451456

The issue #788 was addressing the same problem but I don't know why it was closed. The problem is still there.
If it is a server limit the client should show a proper error message and not just making one of the previous packs disappear.

**Comment by auchri** [comment]
It's a server limit. You can open a new issue for the error message
