### ISSUE TITLE
[Question]Is there any documentation on the modules for this project? 

### ISSUE THREAD

**Issue by glaush** [telegramdesktop/tdesktop#8851]
I am a beginner developer, it is hard for me to understand what exactly is happening in some parts of the program. Is there any documentation at the moment: how exactly the application works, how the application modules are linked, etc. 

If there is such a document, can you see it somehow?

**Comment by ilya-fedin** [comment]
there are no such documentation

**Comment by hughes123b** [comment]
> there are no such documentation

You must wing it young jet eye
