### ISSUE TITLE
[Linux] Two entires in GNOME's notification panel if using native notification.

### ISSUE THREAD

**Issue by AlynxZhou** [telegramdesktop/tdesktop#8853]
### Steps to reproduce
1. Enable native notification.
2. Ask some one to send a message to you.
3. Two notification pop up, one with avatar, username and content, and then another with Telegram icon, "Telegram" as title and "Telegram (PID) is ready".

### Expected behaviour

Only the one with avatar, username and content should popup because we are using native notification to show message.

### Actual behaviour

The one with avatar, username and content quickly disappears because another with Telegram icon, "Telegram" as title and "Telegram (PID) is ready" pops up, which is annoying.

### Configuration
**Operating system:** Arch Linux, GNOME 3.38.

**Version of Telegram Desktop:** 2.4.3

**Installation source (Linux Only)** - the official website / GitHub releases / flatpak / snap / distribution package: Distribution package from Arch's official repo.

**Used theme**: Not sure, I use default with night mode for telegram, and Arc-Dark for GTK.

<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

I got a screenshot here:

![Screenshot from 2020-10-19 16-10-04](https://user-images.githubusercontent.com/8444615/96419390-a7e82c00-1226-11eb-8de2-4fe3b1c23238.png)

The first one comes latter, it also pop up when I am not using native notification, I am not sure why it pops up, I never minimize telegram or close it. Also, applications like thunderbird only send one notification with title and content, but Rocket.Chat has the same behavior as Telegram, which is annoying too.

**Comment by AlynxZhou** [comment]
![Screenshot from 2020-10-19 16-31-21](https://user-images.githubusercontent.com/8444615/96421179-06160e80-1229-11eb-83be-3c185aaa8804.png)

I read some GNOME Shell code, "%s is ready" is shown when application triggered `window-demands-attention` signal, and disable "Draw attention to the window" solved for me, but I am not sure if there are any side effects.

**Comment by gabrc52** [comment]
I don't think this issue should be closed. Thanks for finding a workaround for users! However, I think it shouldn't have this bug out of the box and require users to Google this issue and find it (or open a new one since closed ones don't appear on the search).

A possible solution could be disabling "draw attention to the window" by default on GNOME.

**Comment by ilya-fedin** [comment]
If GNOME decided to add a weird behavior on QApplication::alert, it is GNOME who should to fix this.

**Comment by AlynxZhou** [comment]
> If GNOME decided to add a weird behavior on QApplication::alert, it is GNOME who should fix this.

Actually not a bug for both GNOME and Telegram, even if GNOME allow window to jump out, some users (like me) would like to prevent it from drawing attention, so this option is enough for me.
