### ISSUE TITLE
Using alt codes for combining accents doesn't work

### ISSUE THREAD

**Issue by Deilan** [telegramdesktop/tdesktop#8856]
### Steps to reproduce
1. Open any chat
2. Write "O" letter using keyboard
3. Enable Num Lock on keyboard
4. Enter Alt+0769 on keyboard

### Expected behaviour
"O" becomes "О́"

### Actual behaviour
"O" stays "O"

### Configuration
**Operating system:** Windows 10 x64

**Version of Telegram Desktop:** 2.2

**Comment by Deilan** [comment]
Not a duplicate of https://github.com/telegramdesktop/tdesktop/issues/1041, because this one is not about linux.

**Comment by ilya-fedin** [comment]
The input is handled by Qt entirely, I don't think it is possible to do anything on applications side.

**Comment by Deilan** [comment]
Maybe it's reasonable to file an upstream issue? So that Qt would support that sometime.

**Comment by ilya-fedin** [comment]
You can if you want to

**Comment by Deilan** [comment]
Unfortunately I am personally not qualified to prepare a proper issue for that. 😕

**Comment by Deilan** [comment]
Nope

**Comment by Deilan** [comment]
Not a chance
