### ISSUE TITLE
[Question] Why does global search not display all of the relevant results??

### ISSUE THREAD

**Issue by azat11** [telegramdesktop/tdesktop#8857]
Here's what I ran into.
I am using the search and global search results display 7 relevant groups and channels. Then I join one of the groups. After that the same search query displays only ONE result, and all of the others are not shown. And I can not see those previously shown results unless I LEAVE the group I joined.
Why is this happening?? Is it just a design shortcoming?? Is there any other way to see all relevant global search results without leaving groups and channels I joined??

**Comment by curious0101** [comment]
+1

Global search results are garbage! Popular phrase should return hundreds of results, of my conversation and many public groups and channels, but sometimes I get like one or two groups/channel results.

**Comment by M299792458** [comment]
I also have the same questions (but i didn't encounter your case (yet)), there should be some option to limit what number of results we want to appear, but, unfortunately, this is done server-side, so nothing can be done here. :(

**Comment by azat11** [comment]
This _REALLY_ limits discovery of channels and groups. Basically it's stupid.

**Comment by github12101** [comment]
This is not fixed at all. Global search is totally broken. Do not close this issue.

**Comment by john-preston** [comment]
@github12101 unless mobile apps show something different, all the global search mechanics are server side, tdesktop just shows what it received from the server.

**Comment by RememberTheAir** [comment]
I think this should be discussed on https://bugs.telegram.org, keeping it here will not give this issue the visibility people would like it to have
