### ISSUE TITLE
"QCoreApplication::postEvent: Unexpected null receiver" on close

### ISSUE THREAD

**Issue by curious0101** [telegramdesktop/tdesktop#8858]
### Steps to reproduce
1. Open Telegram from terminal
2. Wait for it to open
3. Close Telegram by clicking X

### Expected behaviour
No errors logged in terminal

### Actual behaviour
Terminal output:
```
Telegram-Message: 21:34:00.577: You can disable tray icon counter with TDESKTOP_DISABLE_TRAY_COUNTER and make it look better if it is monochrome.
error: : cannot open
error: : cannot open
error: : cannot open
QCoreApplication::postEvent: Unexpected null receiver
```

### Configuration
OS: Debian GNU/Linux 10 (buster) x86_64

**Version of Telegram Desktop:**
2.4.3

**Installation source (Linux Only)** - the official website / GitHub releases / flatpak / snap / distribution package:
GitHub release, which updates itself

**Used theme**:
Classic, normal "day mode"

**Comment by ilya-fedin** [comment]
It's ok, generic warning

**Comment by curious0101** [comment]
Why is it there then?
