### ISSUE TITLE
The "online" circle near avatar does not disappear when user goes offline.

### ISSUE THREAD

**Issue by azat11** [telegramdesktop/tdesktop#8859]
### Steps to reproduce
1. Open chat with user online.
2. Wait until user goes offline.
3. The circle near the avatar of user remains there, until mouse cursor touches the chat in the list.

### Expected behaviour
The circle should disappear immediately after user goes offline.

### Actual behaviour
The circle stays.

### Configuration
**Operating system:** Win 7

**Version of Telegram Desktop:** 2.4.3

**Used theme**: Tinted

This is a small bug, but a bug nonetheless. Thought I's share it. It's a minor annoyance.

**Comment by ilya-fedin** [comment]
#6410
