### ISSUE TITLE
[Bug][Visual]Linux on Wayland, window button on title (only close)

### ISSUE THREAD

**Issue by ruslan-gennadievich** [telegramdesktop/tdesktop#8860]
![Снимок экрана от 2020-10-20 01-27-49](https://user-images.githubusercontent.com/7937933/96518529-c9bbd000-1273-11eb-8e32-d244e250fcc0.png)

And i can't resize window too...

### Configuration
Operating system: Ubuntu 20.04.1
Version of Telegram Desktop: 2.4.3
Installation source (Linux Only): snap
GNOME: 3.36.3
Used theme: dark

**Comment by ilya-fedin** [comment]
`gsettings set org.gnome.desktop.wm.preferences button-layout 'appmenu:minimize,maximize,close'`

**Comment by ruslan-gennadievich** [comment]
![Снимок экрана от 2020-10-20 20-47-57](https://user-images.githubusercontent.com/7937933/96624673-b9f4c800-1315-11eb-8e92-36fa44eaa904.png)

**Comment by ilya-fedin** [comment]
Looks like additional logging is needed in order to debug this

**Comment by ruslan-gennadievich** [comment]
How i can do it?

**Comment by ilya-fedin** [comment]
You can't, logging should be added in source code

**Comment by ilya-fedin** [comment]
Hmm, I have an idea.

If Ubuntu overrides upstream default, this is done in gschema overrides and is not visible by snap packages. Thus, if the key is set to default, tdesktop uses gnome upstream default, which is `menu:close`.

Try to disable "Use default value" switch of this setting.

**Comment by ruslan-gennadievich** [comment]
Yes, you are right!
Thank you!
![Снимок экрана от 2020-10-21 16-40-37](https://user-images.githubusercontent.com/7937933/96727999-5b365980-13bc-11eb-905e-487121fa3a7f.png)
