### ISSUE TITLE
Could not find a package configuration file provided by "Qt5"

### ISSUE THREAD

**Issue by ahmedalsaadi17** [telegramdesktop/tdesktop#8861]
I have a problem in building telegram desktop, when I compile it after putting the api_id and api_hash, and run it that message appears on below picture. How to fix this problem? I saw some solutions on a lot of websites, some of them didn't work and the other I couldn't understand it.

![Screenshot (113)](https://user-images.githubusercontent.com/73148531/96530332-38d5fc00-1255-11eb-83a1-624abaf7cecc.png)

**Comment by ilya-fedin** [comment]
Check that C:\BuildPath\Qt-5.12.8\lib\cmake\Qt5\Qt5config.cmake exist

**Comment by ahmedalsaadi17** [comment]
I didn't find Qt5Config.cmake  in the path you sent, and I looked for it among the files and I didn't find it. By the way, my bath differs than yours.

**Comment by ilya-fedin** [comment]
> I didn't find Qt5Config.cmake in the path you sent,

So, you didn't compile all the dependencies by the instruction.

> By the way, my bath differs than yours.

"my bath"?

**Comment by ahmedalsaadi17** [comment]
Sorry, I meant Path is different than the one you gave me to check this file Qt5Config.cmake if it is existed. I installed all libraries that in the instructions.

**Comment by ilya-fedin** [comment]
> I installed all libraries that in the instructions.

That's false, otherwise there should be C:\BuildPath\Libraries\Qt-5.12.8\lib\cmake\Qt5\Qt5Config.cmake

**Comment by ahmedalsaadi17** [comment]
What should I do in this case?

**Comment by ilya-fedin** [comment]
Check that C:\BuildPath\Libraries contains all needed libraries and check what's wrong with ones that didn't build.

If you are can't understand which libraries are built and which are not, you can start the whole process from the begginning, carefully reading everything that every command returns to you.

**Comment by ilya-fedin** [comment]
Could the issue be closed?
