### ISSUE TITLE
fake "unread messages"

### ISSUE THREAD

**Issue by f242** [telegramdesktop/tdesktop#8865]
### Steps to reproduce
1) i read all chat messages and switch to another chat or channel
2) back to previous chat with new messages after some time 
3) i see section "unread messages" and messages that i alredy read
4) i press round button to go to true unread messages
bug does not appear immediately, need some uptime, in my case about 2-3 days

video in attachment
[2020-10-20-15-55-09.zip](https://github.com/telegramdesktop/tdesktop/files/5408872/2020-10-20-15-55-09.zip)

v 2.4.3
windows 10 x64 2004

**Comment by Mohammed-12345** [comment]
This is a duplicate, but in another form, it differs a little bit previous similar reports.

**Comment by minutesinch** [comment]
yes i have same situation but for me affect phone, i read in desktop but in phone show not read!

**Comment by minutesinch** [comment]
any review?
