### ISSUE TITLE
Crash when rescheduling posted message

### ISSUE THREAD

**Issue by Neurotoxin001** [telegramdesktop/tdesktop#8867]
### Steps to reproduce
1. schedule some post
2. press "reschedule" and **wait until it's posts**
3. after it's posts press "schedule"
![image](https://user-images.githubusercontent.com/39812401/96617966-f4a63280-130c-11eb-9c7b-388498825eb1.png)
4. crash

Crash id: 1571d1cc-27a8-40e9-bf0e-ccec02948313
e0b37273-682d-4f0a-9f33-afd888814616

### Configuration
**Operating system:** win 10 ltsc

**Version of Telegram Desktop:** 2.4.3

**Used theme**: dark default

**Comment by 23rd** [comment]
Thanks for your report.
