### ISSUE TITLE
Image preview opens on wrong monitor

### ISSUE THREAD

**Issue by tophattom** [telegramdesktop/tdesktop#8873]
Telegram window on primary monitor. Clicking on image opens image preview on separate monitor instead on the primary monitor where Telegram window is. Using GNOME with Wayland. Primary monitor scaled to 125% other one 100%.

### Expected behaviour
Image preview should open on top of Telegram window

### Actual behaviour
Image preview opens on top second monitor. Either fullscreen or part of the screen.

### Configuration
**Operating system:** Arch Linux 5.9.1

**Version of Telegram Desktop:** 2.4.3

**Installation source (Linux Only)** - the official website / GitHub releases / flatpak / snap / distribution package: Arch repos

**Used theme**:
- GNOME: Arc Darker
- Telegram: Tinted

**Comment by ilya-fedin** [comment]
#5126
