### ISSUE TITLE
(macOS) Background images not working properly.

### ISSUE THREAD

**Issue by ikonastilya** [telegramdesktop/tdesktop#8875]
When setting a background image it crops the picture so it doesn't fit the screen and looks pixelated.

**Comment by 23rd** [comment]
Please provide a version you use.

**Comment by ikonastilya** [comment]
> Please provide a version you use.

App Store version.
On a Desktop version that is similar to a Windows background images look as they have to.

**Comment by 23rd** [comment]
So, you are using the Mac native client, not the Telegram Desktop.
https://github.com/telegramdesktop/tdesktop/issues/5921#issuecomment-483126605

**Comment by ikonastilya** [comment]
> So, you are using the Mac native client, not the Telegram Desktop.
> [#5921 (comment)](https://github.com/telegramdesktop/tdesktop/issues/5921#issuecomment-483126605)

Downloaded TDesktop from https://desktop.telegram.org/ and my background image looks right as I wanted.
But it's missing a lot of stuff which Swift version has so I wanted to know how to fix the issue with background images.

**Comment by 23rd** [comment]
> You can report issues in the app you're using at https://t.me/macswift, or at https://github.com/overtake/TelegramSwift.

This repository is not related to the macOS native Telegram application.
