### ISSUE TITLE
Downloads are slow!

### ISSUE THREAD

**Issue by darkRaspberry** [telegramdesktop/tdesktop#8876]
### Steps to reproduce
1. Open telegram app in linux
2. Download any big media file in any channel.
3. Wait till download are finished 

### Expected behaviour
Downloads are smooth.

### Actual behaviour
Sometime downloads of media is just slow. Means 200KB/s only And continue to indefinite time.

### Configuration
**Operating system:** Ubuntu 20.04

**Version of Telegram Desktop:** 2.4.3

**Installation source (Linux Only)** - the official website

**Used theme**: Night with default shade

<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by ilya-fedin** [comment]
Sounds like a connection issue

**Comment by M299792458** [comment]
At least provide information about your connection, what is your typical download speed, uploading speed...... maybe it's just a connection difficulties, as @ilya-fedin said.

**Comment by darkRaspberry** [comment]
I'm on different network it differ from 2 MB/s minimum to 5MB/s. I don't think it is a connection issue. I think it cause due to some small glitch. The speed recover as i remove config files form my computer.  But this makes me logout.

I seriously know connection issue is not to report in github issue. There are 1.2k issue already there why would i report connection issue.

Can u tell me how to collect log. will upload it

**Comment by M299792458** [comment]
> Can u tell me how to collect log. will upload it

Logs are put in log.txt next to the application. In other words, in /Telegram Desktop folder. But I'm unsure if such thing will be logged or not.

**Comment by darkRaspberry** [comment]
@M299792458 can't i generate log when such event occurs again.

**Comment by M299792458** [comment]
> @M299792458 can't i generate log when such event occurs again.

See the commands here:
https://github.com/telegramdesktop/tdesktop/wiki/Hidden-modes
Those can be initiated by typing them while the settings dialog is opened.

**Comment by darkRaspberry** [comment]
Closing this Issue. As may be new update address it. Indirectly.
