### ISSUE TITLE
how to recover the local code in the telegram desktop?

### ISSUE THREAD

**Issue by zloishax** [telegramdesktop/tdesktop#8880]
Hey guys, I can not restore my telegram. it has a virtual number. 
https://github.com/openwall/john/blob/bleeding-jumbo/run/telegram2john.py i tried it through it fails gives an error

**Comment by M299792458** [comment]
Hello, is your issue that you forgot your local pass-code?
If it is, try this:
https://github.com/telegramdesktop/tdesktop/issues/8882

**Comment by M299792458** [comment]
@zloishax Is your problem solved? If yes, kindly close this issue.

**Comment by zloishax** [comment]
> Hey guys, I can not restore my telegram. it has a virtual number. 
> https://github.com/openwall/john/blob/bleeding-jumbo/run/telegram2john.py i tried it through it fails gives an error

No, it doesn't work, ask for a password.  When I output an incorrect password, the password is incorrect

**Comment by zloishax** [comment]
```
john --wordlist=/usr/share/wordlists/nmap.lst 1.txt
Using default input encoding: UTF-8
No password hashes loaded (see FAQ)
```

**Comment by john-preston** [comment]
The whole idea of a local passcode is that you should not be able to do that (other than a really time consuming brute force, impossible for a strong local passcode).

**Comment by john-preston** [comment]
About the brute-force python script you mentioned, I suggest you ask about it in it's repository, not here.
