### ISSUE TITLE
[Meta] Github issues stale bot

### ISSUE THREAD

**Issue by reallyuniquename** [telegramdesktop/tdesktop#8881]
I got hit with about 50 notifications by stale bot for Telegram Desktop repo. 

Do I really have to reply with `Issue is still valid` to every one of them to keep issues opened?

**Comment by MasterGroosha** [comment]
People tend to open issues and not close them even if related problem is resolved

**Comment by reallyuniquename** [comment]
That's rare. I went through half of my notifications and there was not a single one fixed or implemented.

**Comment by Aokromes** [comment]
what master said.
