### ISSUE TITLE
A security threat?

### ISSUE THREAD

**Issue by M299792458** [telegramdesktop/tdesktop#8882]
I understand that it's dangerous to put something like this now, especially that dev has just finished hard work. But, I have to say it, because it's dangerous and needs urgent action and attention.
/
/
/
/
/
/
/
/You have to cut the Internet connection entirely
/in order to be able to reproduce. (See steps below)
/
/
/
/
/
/
/
I think I found a security issue.
There's this folder D877F783D5D3EF8C (ofcourse 
it differs alot) under /tdata folder, I guess it contains the settings of the account. The idea is that if we deleted it (moved it to somewhere else), then tried to open TD, TD will request the passcode, when we enter it, wrong or true, it will act as it was opened for the first time.... This is 100% expected and normal, but..... if we returned that folder back to its place (after closing TD), everything will be back to normal, and the passcode has been erased!!!!!
So the account can be accessed without the passcode!
So, I wil try to write a how-to-reproduce section.
How to reproduce:
- 1. Set a local passcode.
- 2. Close TD. (And reopen it if you wish, then close)
- 3. Go to /Telegram Desktop/tdata/**************
- 4. Delete/Move that folder.
- 5. Open TD, it will ask for the local passcode, no matter if you write it wrong or right it will go to the welcome screen.
- 6. Close TD after that.
- 7. Return the folder back to where it was.
- 8. Open TD.
- 9. No local passcode, you just destroyed it!!!!!!!
- 10. Now reconnect to the Internet again.

(Predicted) F.A.Q:
• This is not a security issue.
--> Yes, it is, undoubtedly.

• This requires attacker's physical access to the computer.
--> True. But it can be done with malware and viruses too, I guess it's easy.

• Well, Telegram can't protect you against everything; as stated here:
https://telegram.org/faq#e7
Didn't you know that?
--> Of course it can't, that's well known. Who said that essentially? 
But at least, there should be a method to mitigate that, or, better, to prevent it. The data is encrypted, true, but in this way, encryption doesn't make any sense.
TD should remember that there's a passcode, or, to auto logout, if it discovers such malicious activity.

I tried this more than once to ensure if it's valid or not, and I can confirm that it's valid.

Telegram Desktop v.2.4.4
Windows 7 Service Pack 1 (build 7061)
Please fix it very soon. 

Sorry, if this is a duplicate, but I searched for "security" and found many many, I didn't really have time to check them.

**Comment by john-preston** [comment]
I tried what you said and I couldn't reproduce it.

1. I've taken a clean install, logged in, set a local passcode, quit tdesktop with Ctrl+Q, relaunched to check the passcode, quit again.
2. Renamed the folder, launched tdesktop, it asked for the passcode - I've entered wrong passcode, it said "Wrong passcode". I've entered right passcode, it showed the welcome screen. I quit tdesktop, renamed the folder back, launched again - and saw welcome screen.

Maybe some steps should be done differently?

**Comment by M299792458** [comment]
I will try to make a screencast.

**Comment by M299792458** [comment]
@john-preston I'm so sorry for the delay, this is the video:
https://t.me/An_isue_In_Teilgram_Desktop

**Comment by john-preston** [comment]
@M299792458 Yes, I see the video and it has a problem indeed. But I still didn't see you open someones session without having access to his passcode - because when you've disabled the network access and opened passcoded tdesktop (after you moved the folder with data files to the Desktop), you've entered the correct passcode (!), not "no matter if you write it wrong or right it will go to the welcome screen" - it matters. Without the correct passcode you have no way to decrypt the local encryption key that is used in the data folder you moved, so it should not work without knowing the correct passcode.

**Comment by M299792458** [comment]
> @M299792458 Yes, I see the video and it has a problem indeed. But I still didn't see you open someones session without having access to his passcode - because when you've disabled the network access and opened passcoded tdesktop (after you moved the folder with data files to the Desktop), you've entered the correct passcode (!), not "no matter if you write it wrong or right it will go to the welcome screen" - it matters. Without the correct passcode you have no way to decrypt the local encryption key that is used in the data folder you moved, so it should not work without knowing the correct passcode.

Okay, okay. My mistake. My apologies. But anyways, you said "it has a problem indeed", I hope it get fixed next updates.

**Comment by M299792458** [comment]
@john-preston I would like to add something, if we didn't cut the Internet connection, TD will act normally, means it will auto logout.

**Comment by john-preston** [comment]
Yes, thanks for your report.
