### ISSUE TITLE
tdesktop for ubuntu can not start after update on 2.4.4

### ISSUE THREAD

**Issue by lenvk** [telegramdesktop/tdesktop#8883]
### Steps to reproduce
1. update desktop telegram to the version 2.4.4 on ubuntu 20.04
2. run it
3. see how nothing happens :D

### Expected behaviour
some magic of communication

### Actual behaviour

```
user@moon:~$ telegram-desktop

(process:12539): Telegram-WARNING **: 02:21:41.268: Unfortunately, GTK integration conflicts with qgtk2 platformtheme and style. Therefore, QT_QPA_PLATFORMTHEME and QT_STYLE_OVERRIDE will be unset.
Telegram-Message: 02:21:41.268: This can be ignored by setting TDESKTOP_I_KNOW_ABOUT_GTK_INCOMPATIBILITY environment variable to any value, however, if qgtk2 theme or style is used, this will lead to a crash.
Telegram-Message: 02:21:41.268: GTK integration can be disabled by setting TDESKTOP_DISABLE_GTK_INTEGRATION to any value. Keep in mind that this will lead to clipboard issues and tdesktop will be unable to get settings from GTK (such as decoration layout, dark mode & more).
Qt: Session management error: None of the authentication protocols specified are supported
```

### Configuration
**Operating system:**
Ubuntu 20.04.1 LTS

**Version of Telegram Desktop:**
2.4.4

**Installation source (Linux Only)** - the official website / GitHub releases / flatpak / snap / distribution package:
Developer: Telegram FZ-LLC
Source: snapcraft.io

**Used theme**:
sorry, don't remember

<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by abitmore** [comment]
The same on Ubuntu 18.04.5 LTS.

**Comment by ArtCore13** [comment]
Yes I can confirm this issue on my Laptop with Zorin OS 15.3,
Kernel: 5.4.0-52-generic 
WM Theme: ZorinGrey-Dark 
Theme: ZorinGrey-Dark [GTK2/3] 
Icons: Punk-Gamma [GTK2/3]
CPU: Intel i7-8550U (8) @ 4.000GHz
GPU: AMD Radeon RX 550/550X

(process:25599): Telegram-WARNING **: 04:30:59.054: Unfortunately, GTK integration conflicts with qgtk2 platformtheme and style. Therefore, QT_QPA_PLATFORMTHEME and QT_STYLE_OVERRIDE will be unset.
Telegram-Message: 04:30:59.054: This can be ignored by setting TDESKTOP_I_KNOW_ABOUT_GTK_INCOMPATIBILITY environment variable to any value, however, if qgtk2 theme or style is used, this will lead to a crash.
Telegram-Message: 04:30:59.054: GTK integration can be disabled by setting TDESKTOP_DISABLE_GTK_INTEGRATION to any value. Keep in mind that this will lead to clipboard issues and tdesktop will be unable to get settings from GTK (such as decoration layout, dark mode & more).
Qt: Session management error: None of the authentication protocols specified are supported

**Comment by Spurlos** [comment]
Ubuntu 20.10, also fails to start.

**Comment by axlord-ryumaoh** [comment]
Another one for ubuntu 20.10, updated about an hour ago

(process:17824): Telegram-WARNING **: 21:04:37.925: Unfortunately, GTK integration conflicts with qgtk2 platformtheme and style. Therefore, QT_QPA_PLATFORMTHEME and QT_STYLE_OVERRIDE will be unset.
Telegram-Message: 21:04:37.925: This can be ignored by setting TDESKTOP_I_KNOW_ABOUT_GTK_INCOMPATIBILITY environment variable to any value, however, if qgtk2 theme or style is used, this will lead to a crash.
Telegram-Message: 21:04:37.925: GTK integration can be disabled by setting TDESKTOP_DISABLE_GTK_INTEGRATION to any value. Keep in mind that this will lead to clipboard issues and tdesktop will be unable to get settings from GTK (such as decoration layout, dark mode & more).
Qt: Session management error: None of the authentication protocols specified are supported

**Comment by LonerX** [comment]
Confirmed.
Kubuntu 20.04.1 LTS

**Comment by haemtee** [comment]
Same here. Ubuntu 20.04

**Comment by github-raiyan** [comment]
I have also the same issue.
$ telegram-desktop

(process:23721): Telegram-WARNING **: 10:33:37.569: Unfortunately, GTK integration conflicts with qgtk2 platformtheme and style. Therefore, QT_QPA_PLATFORMTHEME and QT_STYLE_OVERRIDE will be unset.
Telegram-Message: 10:33:37.569: This can be ignored by setting TDESKTOP_I_KNOW_ABOUT_GTK_INCOMPATIBILITY environment variable to any value, however, if qgtk2 theme or style is used, this will lead to a crash.
Telegram-Message: 10:33:37.569: GTK integration can be disabled by setting TDESKTOP_DISABLE_GTK_INTEGRATION to any value. Keep in mind that this will lead to clipboard issues and tdesktop will be unable to get settings from GTK (such as decoration layout, dark mode & more).
Qt: Session management error: None of the authentication protocols specified are supported

**Comment by katian** [comment]
Hello, same here
latest/stable:    2.4.4
Ubuntu  20.04.1 LTS
Thanks for your work

**Comment by Ataxia123** [comment]
telegram rugged

**Comment by profitraff** [comment]
Yes! There is a problem!

`(process:6402): Telegram-WARNING **: 10:41:02.774: Unfortunately, GTK integration conflicts with qgtk2 platformtheme and style. Therefore, QT_QPA_PLATFORMTHEME and QT_STYLE_OVERRIDE will be unset.
Telegram-Message: 10:41:02.774: This can be ignored by setting TDESKTOP_I_KNOW_ABOUT_GTK_INCOMPATIBILITY environment variable to any value, however, if qgtk2 theme or style is used, this will lead to a crash.
Telegram-Message: 10:41:02.774: GTK integration can be disabled by setting TDESKTOP_DISABLE_GTK_INTEGRATION to any value. Keep in mind that this will lead to clipboard issues and tdesktop will be unable to get settings from GTK (such as decoration layout, dark mode & more).
Qt: Session management error: None of the authentication protocols specified are supported
`

**Comment by lenvk** [comment]
@ilya-fedin @john-preston can you please tell us when will the version with the fix be ready?

**Comment by huezo** [comment]
@profitraff ` sudo snap refresh`

**It is fixed!**

**Comment by huezo** [comment]
> @ilya-fedin @john-preston can you please tell us when will the version with the fix be ready?

`sudo snap refresh
`
It is fixed!

**Comment by shkhaksar** [comment]
I had this problem and it's fixed after updating with `sudo snap refresh`

**Comment by lenvk** [comment]
> > @ilya-fedin @john-preston can you please tell us when will the version with the fix be ready?
> 
> `sudo snap refresh `
> _It is fixed!_

thank you! problem solved :)

**Comment by katian** [comment]
> > @ilya-fedin @john-preston can you please tell us when will the version with the fix be ready?
> 
> `sudo snap refresh `
> _It is fixed!_

thanks a lot ! :smile:

**Comment by 1597gaurav** [comment]
> > @ilya-fedin @john-preston can you please tell us when will the version with the fix be ready?
> 
> `sudo snap refresh `
> _It is fixed!_

thanks it worked

**Comment by jpaniagualaconich** [comment]
i'm on 2.4.6 and this is happening. 
No, `sudo snap refresh` doesn't fix it.
```
(process:434465): Telegram-WARNING **: 16:55:30.387: Unfortunately, GTK integration conflicts with qgtk2 platformtheme and style. Therefore, QT_QPA_PLATFORMTHEME and QT_STYLE_OVERRIDE will be unset.
Telegram-Message: 16:55:30.387: This can be ignored by setting TDESKTOP_I_KNOW_ABOUT_GTK_INCOMPATIBILITY environment variable to any value, however, if qgtk2 theme or style is used, this will lead to a crash.
Telegram-Message: 16:55:30.387: GTK integration can be disabled by setting TDESKTOP_DISABLE_GTK_INTEGRATION to any value. Keep in mind that this will lead to clipboard issues and tdesktop will be unable to get settings from GTK (such as decoration layout, dark mode & more).
Failed to create wl_display (Connection refused)
Using Wayland-EGL
failed to initialize EGL display
qt.qpa.plugin: Could not load the Qt platform plugin "wayland-egl" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, wayland-egl, wayland, wayland-xcomposite-egl, wayland-xcomposite-glx, xcb.

Aborted (core dumped)
```
Why is it trying to use Wayland-EGL? I'm on an X11 session.

**Comment by ilya-fedin** [comment]
As far as I know, QT_QPA_PLATFORM is forced in the snapcraft desktop helpers: https://github.com/ubuntu/snapcraft-desktop-helpers/blob/1c04184cce644acd07cc01f5255a6405eb89893b/qt/launcher-specific#L35-L46
And the only way is to set the helpers-specific `DISABLE_WAYLAND=1` variable.

**Comment by ilya-fedin** [comment]
> Why is it trying to use Wayland-EGL?

I don't know, probably somethng is wrong on your system, that's how snapcraft helpers detect wayland:
https://github.com/ubuntu/snapcraft-desktop-helpers/blob/1c04184cce644acd07cc01f5255a6405eb89893b/common/desktop-exports#L222-L246
