### ISSUE TITLE
Introduce at least basic automated testing for linux compatibility [Feature Request] 

### ISSUE THREAD

**Issue by matkoniecz** [telegramdesktop/tdesktop#8885]
### Is your feature request related to a problem?
2.4.4 was released despite Telegram being unable to start at all on many systems (#8883)

### Describe the solution you'd like
It should be caught by an automatic testing.

### Describe alternatives you've considered
Manual testing whatever anything at all works on systems claimed to be supported.

### Additional context
Snap is obnoxious and upgraded Telegram on its own without any user interaction, making it even more confusing. Also, Telegram failed to provide any info on startup, sole logs in console were

```
mateusz@grisznak:~$ telegram-desktop 

(process:2575): Telegram-WARNING **: 07:49:22.630: Unfortunately, GTK integration conflicts with qgtk2 platformtheme and style. Therefore, QT_QPA_PLATFORMTHEME and QT_STYLE_OVERRIDE will be unset.
Telegram-Message: 07:49:22.630: This can be ignored by setting TDESKTOP_I_KNOW_ABOUT_GTK_INCOMPATIBILITY environment variable to any value, however, if qgtk2 theme or style is used, this will lead to a crash.
Telegram-Message: 07:49:22.631: GTK integration can be disabled by setting TDESKTOP_DISABLE_GTK_INTEGRATION to any value. Keep in mind that this will lead to clipboard issues and tdesktop will be unable to get settings from GTK (such as decoration layout, dark mode & more).
```

**Comment by ilya-fedin** [comment]
Snap package is not tested at all AFAIK, only static binary builds are tested

**Comment by matkoniecz** [comment]
Yes, it is obvious that nothing was tested on Ubuntu before a release.

**Comment by matkoniecz** [comment]
Is static binary build also unable to start on Ubuntu?

**Comment by ilya-fedin** [comment]
No, this is a snap-specific problem

**Comment by matkoniecz** [comment]
Then it would be nice to change

> Snap package is not tested at all AFAIK

especially given that for some reason Snap updates stuff on its own, without notifying user.

**Comment by matkoniecz** [comment]
Closing per #9018
