### ISSUE TITLE
Crash after close watched video

### ISSUE THREAD

**Issue by Neurotoxin001** [telegramdesktop/tdesktop#8887]
### Steps to reproduce
1. open any video
2. close it
3. crash

crash id:
c0e04212-a377-4faa-965a-edf27cfd77df
f7f9b30f-050d-43c0-bf24-b63a2209c23b

Clearing media cache helped but for how long...

### Configuration
**Operating system:** win 10 ltsc 1809

**Version of Telegram Desktop:** 2.4.4

**Used theme**: Dark default

**Comment by Neurotoxin001** [comment]
Clearing media cache helped not for long

new crash id 4227fa48-8138-47e8-a93e-8944e93536c7

**Comment by Assasin291** [comment]
I face the same issue after I switched to Manjaro Linux. And it seems, video speed makes the difference. The greater speed multiplayer used, the higher risk of crash

<details>
  <summary>Configuration</summary>
  <pre>
    Operating System: Manjaro Linux
    KDE Plasma Version: 5.19.5
    KDE Frameworks Version: 5.74.0
    Qt Version: 5.15.1
    Kernel Version: 5.4.72-1-MANJARO
    OS Type: 64-bit
    Processors: 4 × Intel® Core™ i7-6600U CPU @ 2.60GHz
    Memory: 15,5 GiB of RAM
    Graphics Processor: Mesa Intel® HD Graphics 520

    Telegram: 2.3.2 (from official Manjaro repository)
    Theme: Night (default dark theme with green highlight)
    Total size limit: 200 MB
    Media cache limit: 100 MB
    Clear files older than: 1 week

    Media cache used already: 93.2 MB
  </pre>
</details>

<details>
  <summary>Logs (might be useful)</summary>
  <pre>
2020-10-24 13:43	systemd-coredump	Process 434035 (telegram-deskto) of user 1000 dumped core.

Stack trace of thread 434035:
#0  0x00007fa0a65250e1 unlink_chunk.constprop.0 (libc.so.6 + 0x880e1)
#1  0x00007fa0a65259cb _int_free (libc.so.6 + 0x889cb)
#2  0x00007fa0a8d71e6d n/a (libopenal.so.1 + 0x34e6d)
#3  0x00007fa0a8d775d6 alcDestroyContext (libopenal.so.1 + 0x3a5d6)
#4  0x000055ce9a8fdbb6 n/a (telegram-desktop + 0x1373bb6)
#5  0x000055ce9a90035e n/a (telegram-desktop + 0x137635e)
#6  0x000055ce9af32002 n/a (telegram-desktop + 0x19a8002)
#7  0x00007fa0a827b71f _ZN7QObject5eventEP6QEvent (libQt5Core.so.5 + 0x2e071f)
#8  0x00007fa0a7906752 _ZN19QApplicationPrivate13notify_helperEP7QObjectP6QEvent (libQt5Widgets.so.5 + 0x15a752)
#9  0x000055ce9a2fcc5f n/a (telegram-desktop + 0xd72c5f)
#10 0x00007fa0a824ecda _ZN16QCoreApplication15notifyInternal2EP7QObjectP6QEvent (libQt5Core.so.5 + 0x2b3cda)
#11 0x00007fa0a82a6cc5 _ZN14QTimerInfoList14activateTimersEv (libQt5Core.so.5 + 0x30bcc5)
#12 0x00007fa0a82a7572 n/a (libQt5Core.so.5 + 0x30c572)
#13 0x00007fa0a6b38bfc g_main_context_dispatch (libglib-2.0.so.0 + 0x52bfc)
#14 0x00007fa0a6b8a1f9 n/a (libglib-2.0.so.0 + 0xa41f9)
#15 0x00007fa0a6b37421 g_main_context_iteration (libglib-2.0.so.0 + 0x51421)
#16 0x00007fa0a82a7941 _ZN20QEventDispatcherGlib13processEventsE6QFlagsIN10QEventLoop17ProcessEventsFlagEE (libQt5Core.so.5 + 0x30c941)
#17 0x00007fa0a824d65c _ZN10QEventLoop4execE6QFlagsINS_17ProcessEventsFlagEE (libQt5Core.so.5 + 0x2b265c)
#18 0x00007fa0a8255af4 _ZN16QCoreApplication4execEv (libQt5Core.so.5 + 0x2baaf4)
#19 0x000055ce9a2fb7e5 n/a (telegram-desktop + 0xd717e5)
#20 0x000055ce9a2ec19f n/a (telegram-desktop + 0xd6219f)
#21 0x000055ce9a2ec2fd n/a (telegram-desktop + 0xd622fd)
#22 0x000055ce99a717a7 n/a (telegram-desktop + 0x4e77a7)
#23 0x00007fa0a64c5152 __libc_start_main (libc.so.6 + 0x28152)
#24 0x000055ce99a7a10e n/a (telegram-desktop + 0x4f010e)

Stack trace of thread 434044:
#0  0x00007fa0a659246f __poll (libc.so.6 + 0xf546f)
#1  0x00007fa0a6b8a188 n/a (libglib-2.0.so.0 + 0xa4188)
#2  0x00007fa0a6b37421 g_main_context_iteration (libglib-2.0.so.0 + 0x51421)
#3  0x00007fa0a6b37472 n/a (libglib-2.0.so.0 + 0x51472)
#4  0x00007fa0a6b65a91 n/a (libglib-2.0.so.0 + 0x7fa91)
#5  0x00007fa0a922d3e9 start_thread (libpthread.so.0 + 0x93e9)
#6  0x00007fa0a659d293 __clone (libc.so.6 + 0x100293)

Stack trace of thread 434046:
#0  0x00007fa0a92339c8 pthread_cond_timedwait@@GLIBC_2.3.2 (libpthread.so.0 + 0xf9c8)
#1  0x00007fa0a806f058 _ZN14QWaitCondition4waitEP6QMutex14QDeadlineTimer (libQt5Core.so.5 + 0xd4058)
#2  0x00007fa0a806cfc4 n/a (libQt5Core.so.5 + 0xd1fc4)
#3  0x00007fa0a8068e8f n/a (libQt5Core.so.5 + 0xcde8f)
#4  0x00007fa0a922d3e9 start_thread (libpthread.so.0 + 0x93e9)
#5  0x00007fa0a659d293 __clone (libc.so.6 + 0x100293)

Stack trace of thread 434037:
#0  0x00007fa0a659246f __poll (libc.so.6 + 0xf546f)
#1  0x00007fa0a770163b n/a (libxcb.so.1 + 0xc63b)
#2  0x00007fa0a770337b xcb_wait_for_event (libxcb.so.1 + 0xe37b)
#3  0x00007fa09fe17f61 n/a (libQt5XcbQpa.so.5 + 0x5df61)
#4  0x00007fa0a8068e8f n/a (libQt5Core.so.5 + 0xcde8f)
#5  0x00007fa0a922d3e9 start_thread (libpthread.so.0 + 0x93e9)
#6  0x00007fa0a659d293 __clone (libc.so.6 + 0x100293)

Stack trace of thread 434045:
#0  0x00007fa0a659246f __poll (libc.so.6 + 0xf546f)
#1  0x00007fa0a6b8a188 n/a (libglib-2.0.so.0 + 0xa4188)
#2  0x00007fa0a6b38163 g_main_loop_run (libglib-2.0.so.0 + 0x52163)
#3  0x00007fa0a6d71fe8 n/a (libgio-2.0.so.0 + 0x101fe8)
#4  0x00007fa0a6b65a91 n/a (libglib-2.0.so.0 + 0x7fa91)
#5  0x00007fa0a922d3e9 start_thread (libpthread.so.0 + 0x93e9)
#6  0x00007fa0a659d293 __clone (libc.so.6 + 0x100293)

Stack trace of thread 434053:
#0  0x00007fa0a659246f __poll (libc.so.6 + 0xf546f)
#1  0x00007fa0a6b8a188 n/a (libglib-2.0.so.0 + 0xa4188)
#2  0x00007fa0a6b37421 g_main_context_iteration (libglib-2.0.so.0 + 0x51421)
#3  0x00007fa0a82a7941 _ZN20QEventDispatcherGlib13processEventsE6QFlagsIN10QEventLoop17ProcessEventsFlagEE (libQt5Core.so.5 + 0x30c941)
#4  0x00007fa0a824d65c _ZN10QEventLoop4execE6QFlagsINS_17ProcessEventsFlagEE (libQt5Core.so.5 + 0x2b265c)
#5  0x00007fa0a8067ca2 _ZN7QThread4execEv (libQt5Core.so.5 + 0xccca2)
#6  0x00007fa0a8068e8f n/a (libQt5Core.so.5 + 0xcde8f)
#7  0x00007fa0a922d3e9 start_thread (libpthread.so.0 + 0x93e9)
#8  0x00007fa0a659d293 __clone (libc.so.6 + 0x100293)

Stack trace of thread 434051:
#0  0x00007fa0a659246f __poll (libc.so.6 + 0xf546f)
#1  0x00007fa0a8db6ba7 n/a (libopenal.so.1 + 0x79ba7)
#2  0x00007fa08c083059 pa_mainloop_poll (libpulse.so.0 + 0x1b059)
#3  0x00007fa08c08d301 pa_mainloop_iterate (libpulse.so.0 + 0x25301)
#4  0x00007fa08c08d3b1 pa_mainloop_run (libpulse.so.0 + 0x253b1)
#5  0x00007fa0a8db749e n/a (libopenal.so.1 + 0x7a49e)
#6  0x00007fa0a6897c24 execute_native_thread_routine (libstdc++.so.6 + 0xcfc24)
#7  0x00007fa0a922d3e9 start_thread (libpthread.so.0 + 0x93e9)
#8  0x00007fa0a659d293 __clone (libc.so.6 + 0x100293)

Stack trace of thread 434054:
#0  0x00007fa0a659246f __poll (libc.so.6 + 0xf546f)
#1  0x00007fa0a6b8a188 n/a (libglib-2.0.so.0 + 0xa4188)
#2  0x00007fa0a6b37421 g_main_context_iteration (libglib-2.0.so.0 + 0x51421)
#3  0x00007fa0a82a7941 _ZN20QEventDispatcherGlib13processEventsE6QFlagsIN10QEventLoop17ProcessEventsFlagEE (libQt5Core.so.5 + 0x30c941)
#4  0x00007fa0a824d65c _ZN10QEventLoop4execE6QFlagsINS_17ProcessEventsFlagEE (libQt5Core.so.5 + 0x2b265c)
#5  0x00007fa0a8067ca2 _ZN7QThread4execEv (libQt5Core.so.5 + 0xccca2)
#6  0x00007fa0a8068e8f n/a (libQt5Core.so.5 + 0xcde8f)
#7  0x00007fa0a922d3e9 start_thread (libpthread.so.0 + 0x93e9)
#8  0x00007fa0a659d293 __clone (libc.so.6 + 0x100293)

Stack trace of thread 434074:
#0  0x00007fa0a659246f __poll (libc.so.6 + 0xf546f)
#1  0x00007fa0a6b8a188 n/a (libglib-2.0.so.0 + 0xa4188)
#2  0x00007fa0a6b37421 g_main_context_iteration (libglib-2.0.so.0 + 0x51421)
#3  0x00007fa0a82a7941 _ZN20QEventDispatcherGlib13processEventsE6QFlagsIN10QEventLoop17ProcessEventsFlagEE (libQt5Core.so.5 + 0x30c941)
#4  0x00007fa0a824d65c _ZN10QEventLoop4execE6QFlagsINS_17ProcessEventsFlagEE (libQt5Core.so.5 + 0x2b265c)
#5  0x00007fa0a8067ca2 _ZN7QThread4execEv (libQt5Core.so.5 + 0xccca2)
#6  0x00007fa0a8068e8f n/a (libQt5Core.so.5 + 0xcde8f)
#7  0x00007fa0a922d3e9 start_thread (libpthread.so.0 + 0x93e9)
#8  0x00007fa0a659d293 __clone (libc.so.6 + 0x100293)

Stack trace of thread 440385:
#0  0x00007fa0aa1a89d3 n/a (libavcodec.so.58 + 0x94b9d3)
  </pre>
</details>

**Comment by ilya-fedin** [comment]
@Assasin291 your trace is useless, install the version from desktop.telegram.org, reproduce on it, send a crash report and post crash report tag here

**Comment by Assasin291** [comment]
@ilya-fedin, well, I've downloaded and launched app from desktop.telegram.org and it seems that issue doesn't appear on original build, so my case resolved.

**Comment by Neurotoxin001** [comment]
Seems like fixed in 2.4.5

**Comment by Neurotoxin001** [comment]
No, not fixed

new crash id 4583e9a5-958b-4e56-a2c2-ac0724c720b9

Still after watching video on x2 speed and then close it

**Comment by ilya-fedin** [comment]
@Neurotoxin001's case is https://github.com/kcat/openal-soft/issues/486
@Assasin291's case is a bugged ffmpeg version in manjaro repos I guess (there were multiple reports about this in the past, but we can we do?)
