### ISSUE TITLE
[Feature Request] Changing spelling language in the right-click menu

### ISSUE THREAD

**Issue by Maelep** [telegramdesktop/tdesktop#8888]
### Is your feature request related to a problem?
I'm french speaker but I prefer to use english software and it's boring to use Windows Telegram because all my text are red underlined because it tries to correct my French word into English...

### Describe the solution you'd like
Make something similar to Web Browser: right-clicking one the misspelling word suggest the correct word and allow you to change the language of the spell checker. (cf. this image: [https://prnt.sc/v5v1c8](https://prnt.sc/v5v1c8) )

### Describe alternatives you've considered
At least, allow us to disable spell checking but it isn't a good solution...

**Comment by ilya-fedin** [comment]
Telegram uses Windows system spellchecker, you should change your Windows preferences

**Comment by ilya-fedin** [comment]
> At least, allow us to disable spell checking

You already can disable spellchecking in Telegram settings

**Comment by Maelep** [comment]
Thank you for your answers!
