### ISSUE TITLE
Export data stucks on media

### ISSUE THREAD

**Issue by FirKys** [telegramdesktop/tdesktop#8890]
### Steps to reproduce
1. Select any contact
2. Open menu contact
3. Open export data and select all options (video, voice, etc.)
4. Push button export!

### Expected behaviour
Finish exporting data successfully

### Actual behaviour
Stucks at the same stage of data download.
Stucks on a large amount of data, always !! on the same message (video, voice) !!.
Stucks are also observed with other contacts, also on a certain audio or video, the files are available for viewing.
![image](https://user-images.githubusercontent.com/9483682/97071239-cc0d8980-15e7-11eb-8e4f-e2ee2a92ca34.png)
**The export of messages without media files succeeds.**

### Configuration
**Operating system:** win 10

**Version of Telegram Desktop:** 2.4.4

**Used theme**:
White

<b>Logs</b>:
[logs.txt](https://github.com/telegramdesktop/tdesktop/files/5432599/logs.txt)

**Comment by Julia-Gammel** [comment]
I have the same problem

**Comment by TheYarin** [comment]
I, too, have this problem.

**Comment by john-preston** [comment]
In case of a non-loading media files - fixed by 03a868a

Will be available in the next version.

It should not appear on media files that are successfully loaded in-app.
