### ISSUE TITLE
Media viewer no longer in fullscreen on tiling window managers

### ISSUE THREAD

**Issue by penma** [telegramdesktop/tdesktop#8891]
### Steps to reproduce
Open any kind of media viewer, e.g. enlarge some image or video, right click on a GIF and select "Open GIF", ...

### Expected behaviour
Media viewer should create a fullscreen window that overlays all other windows, as it is done on other platforms and as it was before 2.4.4

### Actual behaviour
When using a tiling window manager such as dwm, the media viewer gets managed by the tiling window manager, i.e. it is not a fullscreen window, gets resized to (e.g.) half the screen size etc.

This behaviour was (likely) introduced with commit 245d644cd7dd3c00e4bf9e380c6d60342d5c7141 with the addition of the Qt::WindowStaysOnTopHint flag. Removing this flag from this line makes the media viewer behave as expected.

### Configuration
**Operating system:** Debian unstable, using dwm as window manager

**Version of Telegram Desktop:** 2.4.4

**Installation source (Linux Only)** - the official website

**Used theme**: (no idea? default)

**Comment by ilya-fedin** [comment]
Why it doesn't interpret the flag right? This sounds like a dwm issue, since this forces to choice on which window managers we want the right behavior (and I want to choice kwin rather than dwm).

**Comment by penma** [comment]
Well my initial report just pinpointed to the commit that caused the regression, without judging who is at fault here or how it should be fixed.

However, according to the QT documentation https://doc.qt.io/qt-5/qt.html , the Qt::WindowStaysOnTopHint flag has the following remark: "Note that on some window managers on X11 you also have to pass  Qt::X11BypassWindowManagerHint for this flag to work correctly."

And in fact, if I add not only WindowStaysOnTopHint but also X11BypassWindowManagerHint, this also produces the expected behaviour on dwm.

**Comment by ilya-fedin** [comment]
> Bypass the window manager completely. This results in a borderless window that is not managed at all (i.e., no keyboard input unless you call QWidget::activateWindow() manually).

This is not acceptable, request dwm to process WindowStaysOnTopHint without X11BypassWindowManagerHint

**Comment by penma** [comment]
After some more poking around: because dwm apparently does not handle multiple _NET_WM_STATEs well. If it has only _NET_WM_STATE_FULLSCREEN then it respects that (in fact, before 2.4.4 the media viewer had only that state set).
If it has multiple ones (2.4.4 media viewer has _NET_WM_STATE_ABOVE, _NET_WM_STATE_FULLSCREEN, _NET_WM_STATE_MODAL, _NET_WM_STATE_STAYS_ON_TOP) then it does not properly make the window fullscreen, even though it is supposed to.
(Must be related to the fact that there are multiple ones instead of just one, because dwm doesn't even support the other ones)

So yep, it is a dwm bug (not sure if I get around to properly fix this or if I just keep the exception for the combination of class and title). Anyway, thanks for investigating this issue!

**Comment by sqwoteg** [comment]
> not sure if I get around to properly fix this

Hey, dude, did you manage to do that? I have the same problem after telegram update..

**Comment by penma** [comment]
> > not sure if I get around to properly fix this
> 
> Hey, dude, did you manage to do that? I have the same problem after telegram update..

Not yet, using this one so far in `config.h`:

```
static const Rule rules[] = {
        /* class             instance    title           tags mask     isfloating   monitor */
        { "TelegramDesktop", NULL,       "Media viewer", 0,            True,        -1 },
};
```

**Comment by sqwoteg** [comment]
I solved it by adding the field "isfullscreen" to the "Rule" and setting floating+fullscreen if it is set. 
It seems to work normally.
