### ISSUE TITLE
"open contacts" shortcut overriding "clear formatting/plain text" shorcut

### ISSUE THREAD

**Issue by JasonKhew96** [telegramdesktop/tdesktop#8896]
https://github.com/telegramdesktop/tdesktop/issues/8775#issuecomment-715884182
https://github.com/telegramdesktop/tdesktop/commit/7de9bcad03959faa6eaa48aa0dc1df9907252f22

### Steps to reproduce
1. Highlight a text
2. Try to format the text with anything.
3. Press `ctrl + shift + n` shortcut to clear formatting

### Expected behaviour
Clear selected text formatting

### Actual behaviour
Contact window displayed

### Configuration
**Operating system:**
Ubuntu 20.04.1 LTS

**Version of Telegram Desktop:**
2.4.4

**Installation source (Linux Only)** - the official website / GitHub releases / flatpak / snap / distribution package:
GitHub releases

**Used theme**:
none

<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by 23rd** [comment]
Yeah, sorry, this is a known problem.

**Comment by maximal** [comment]
I'd choose something more handy and/or convenient to press with one hand. `Ctrl+Shift+N` is either stretchier or two-handed.
