### ISSUE TITLE
Show associated stickers on emoji (like Android version)

### ISSUE THREAD

**Issue by Mindstormer619** [telegramdesktop/tdesktop#890]
Little feature request to increase usefulness: could you guys do the same thing the Android client does with stickers currently? Basically display all the stickers associated with a particular emoticon when the emoticon is the only thing typed in the chat message box.

Associated image:  
![image](https://cloud.githubusercontent.com/assets/441849/8542772/8412bcbe-24b5-11e5-8cc8-a642200c7ef0.png)

**Comment by leeola** [comment]
Which OS? This works on OSX, but unfortunately #894 means that you cannot type them - you have to use the popup box to pick an Emoji. For example, this is what it looks like on OSX: http://take.ms/EaiYh

**Comment by Mindstormer619** [comment]
Forget typing them in, picking them from the box is more than sufficient for me.

The OS is Windows. I think OSX has a different client. But the fact that it's present in another client just makes this more infuriating. Why are features not consistent?

**Comment by leeola** [comment]
Not sure, i'm quite new to the platform. I have OSX, Windows and Android clients installed - and OSX is far better than the Windows installation in my opinion. Everything from the UI _(resize-able split, for example)_, to the settings _(way more settings on OSX)_ - and apparently the features like this.

**Comment by marcocatelli** [comment]
+1 on this. I have a lot of sticker packs and choosing stickers on desktop is very frustrating. Many times when I'm chatting on desktop I end up taking the smartphone just to find a particular sticker starting from the relative emoji

**Comment by DaFri-Nochiterov** [comment]
:+1: +1

**Comment by Noise47** [comment]
+1 on this. it's bothering me too.

**Comment by Mindstormer619** [comment]
Any updates on this?

**Comment by Mindstormer619** [comment]
This got finally put in. _Months_ later, but better late than never :)

Thanks TG Team!
