### ISSUE TITLE
Building on Ubuntu 20.04

### ISSUE THREAD

**Issue by Wesxdz** [telegramdesktop/tdesktop#8904]
Current build instructions for Ubuntu 14.04
https://github.com/telegramdesktop/tdesktop/blob/dev/docs/building-cmake.md

I'm seeking assistance building Telegram Desktop for the latest long term supported version of Ubuntu (and hopefully updating the documentation to help others). I've managed to solve a few preliminary issues but ultimately have hit up against a QT related build error that I'm unsure how to solve.

```
make[1]: *** [CMakeFiles/Makefile2:3102: Telegram/codegen/codegen/numbers/CMakeFiles/codegen_numbers.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
make[2]: *** No rule to make target '/usr/local/desktop-app/Qt-5.12.8/plugins/wayland-graphics-integration-client/libdmabuf-server.a', needed by 'Telegram/codegen/codegen/lang/codegen_lang'.  Stop.
```

The main issue is that QT is not producing the libdmabuf-server.a file when building, I'm not sure at what stage of the build process this library is typically output, but there were a few places I diverged from the standard build instructions.

1. Replace python-xcbgen with python3-xcbgen (xcbgen for Python 2 is not available by default)
2. When installing Breakpad I encountered an error due to using the https://github.com/google/breakpad/commit/bc8fb886 HEAD (From my understanding this issue was resolved by https://github.com/google/breakpad/commit/7e3c1650, therefore I followed the instructions on https://chromium.googlesource.com/breakpad/breakpad to setup Breakpad and ignored the linux-syscall-support for now)

I haven't been able to find any documentation in the qtwayland README or elsewhere about the libdmabuf-server library. Any help would be greatly appreciated.

**Comment by ilya-fedin** [comment]
You can't use anything across Ubuntu 14.04 due to glibc wraps. Use virtual machine with Ubuntu 14.04 or something other.
