### ISSUE TITLE
2.4.4 media viewer bug in Linux

### ISSUE THREAD

**Issue by cyberpunkrocker-zero** [telegramdesktop/tdesktop#8908]
The 2.4.4 release on Linux introduced a curious little bug:

When I click a picture in discussion, the media viewer launches as a full screen window _WITH_ full window decorations (borders, titlebar etc). When I close it and click the same picture again, the media viewer window opens as a full screen window _WITHOUT_ decorations (like it used to work in pre-2.4.4 versions). Next time it opens again with decorations, next time without etc for ever, that is, the media viewer window alternates between decorated and undecorated versions.

That happens in Arch Linux, telegram-desktop-2.4.4-1 and Awesome WM (Might be Yet Another Awesome-only-related bug...)

**Comment by ilya-fedin** [comment]
Only WindowStaysOnTopHint was added, I guess your window manager process window hints wrongly [just like dwm](https://github.com/telegramdesktop/tdesktop/issues/8891) and you should file a bug against it.
