### ISSUE TITLE
Google doesn’t recognize my device. 

### ISSUE THREAD

**Issue by hughes123b** [telegramdesktop/tdesktop#8909]
### Steps to reproduce
1. 
2. 
3. 

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

### Configuration
**Operating system:**

**Version of Telegram Desktop:**

**Installation source (Linux Only)** - the official website / GitHub releases / flatpak / snap / distribution package:

**Used theme**:

<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by hughes123b** [comment]
> ### Steps to reproduce
> 
> ### Expected behaviour
> Tell us what should happen
> 
> ### Actual behaviour
> Tell us what happens instead
> 
> ### Configuration
> **Operating system:**
> 
> **Version of Telegram Desktop:**
> 
> **Installation source (Linux Only)** - the official website / GitHub releases / flatpak / snap / distribution package:
> 
> **Used theme**:
> 
> Logs:

It keeps logging me out and loading instead of going to password command prompt.

**Comment by AhyaH-YHWH** [comment]
Here is for Desktop, not Telegram Android
try installing a clone of Telegram, in Parallel Space (find in Google Play), 
if your device has login issue, 

also try opening web.telegram.org , to see If you can connect to Telegram at all.
