### ISSUE TITLE
Special fonts not rendering properly

### ISSUE THREAD

**Issue by NicKoehler** [telegramdesktop/tdesktop#8910]
### Steps to reproduce
1. Open telegram
2. See the font in [this public group](https://t.me/ZexynosLounge) name (𝖅𝕰𝖃𝖄𝖓𝖔𝖘 𝕷𝖔𝖚𝖓𝖌𝖊)

### Expected behaviour
The font is rendered as 𝖅𝕰𝖃𝖄𝖓𝖔𝖘 𝕷𝖔𝖚𝖓𝖌𝖊

### Actual behaviour
![image](https://user-images.githubusercontent.com/53040044/97276796-f6558600-1837-11eb-9ba1-488e20e8dddf.png)

### Configuration
**Operating system:**
OS: Pop!_OS 20.10 x86_64 
Kernel: 5.8.0-7625-generic 
DE: GNOME 
WM: Mutter

**Version of Telegram Desktop:**
2.4.4

**Installation source:**
Appimage from the official website

**Used theme**:
Night

**Comment by ilya-fedin** [comment]
#6056
