### ISSUE TITLE
Font in Mac

### ISSUE THREAD

**Issue by alabotski** [telegramdesktop/tdesktop#8912]
There is some problem with font display on Mac
I changed the style of the name
https://qaz.wtf/u/convert.cgi?text=ALIAKSEI

It is displayed normally in the settings, but in the side menu, squares
Everything works great in Windows

![image](https://user-images.githubusercontent.com/439337/97296841-45181580-1862-11eb-958f-3d94e55dd7cc.png)
![image](https://user-images.githubusercontent.com/439337/97297005-81e40c80-1862-11eb-86ff-813c4b4f3116.png)

**Comment by ilya-fedin** [comment]
Is this a marathon of creating duplicates of this bug? Previous duplicate #8910 was closed 3 hours ago
