### ISSUE TITLE
please make secret chats in android version screenreader accessible

### ISSUE THREAD

**Issue by ilyapashuk** [telegramdesktop/tdesktop#8913]
I'm know that this is a desktop version page, but anyway writing hear because doesn't got any answers by recommended way.
if you don't want to get sutch messages, please enable public github issue tracker on your android app github repo instead your very closed system.

in secret chats, accessibility services is not allowed to access message contents, only footer and header of the window.
this is correct behavior in most cases, but not for screenreader users.
please add setting for disabling this protection in app's settings page to make them accessible as normal chats.

**Comment by RememberTheAir** [comment]
3rd party issue?

**Comment by Aokromes** [comment]
yeah he is asking for telegram android, not telegram desktop.

**Comment by RememberTheAir** [comment]
I thought third-party issue was used to label issues with qt or anyway with libraries tdesktop uses, not other official Telegram app. I don't think the android app can be considered "third-party" to tdesktop

**Comment by ilyapashuk** [comment]
formerly it is 3rd party issue, but I simply can't find any other working communication method. I repeat: open issue tracker in android app repo if you don't want to get such messages.
and I think that allowing developers to disable issue tracker on active repos is not good idea at all, because your official supporters are simply not responding.

**Comment by Aokromes** [comment]
someone requested it here https://t.me/tgbetachat but i don't think it's easy to make secret chats secret and compatible with screen readers.

**Comment by M299792458** [comment]
Ask Nick to open the bug tracker in his repository.

**Comment by Aokromes** [comment]
i did long time ago, suggesting him to be ticket administrator he said no.
