### ISSUE TITLE
[Feature Request] Remember last save path for save file dialog

### ISSUE THREAD

**Issue by Gepar** [telegramdesktop/tdesktop#8915]
It's kinda annoying when you save a few images from telegram to desktop and you need every time switch save folder from default. It will be convenient if desktop client will remember last save path.

**Comment by ilya-fedin** [comment]
As I can see, this feature already exists for ~6 years
https://github.com/telegramdesktop/tdesktop/blob/6e42d546328050d10a3efbdf53553579228be3ea/Telegram/SourceFiles/core/file_utilities.cpp#L365-L372

**Comment by Aokromes** [comment]
works for me (TM) windows 10 21h1.

**Comment by Gepar** [comment]
> works for me (TM) windows 10 21h1.
Save file as works, but "save file" menu (or press ctrl+s) - doesn't.
Just open any image in telegram and press ctrl+s and you will always see default path.

**Comment by ilya-fedin** [comment]
> but "save file" menu

I don't understand which menu are you talking about

**Comment by Gepar** [comment]
When you open some image file and with opened image press "ctrl+s" or select "save file" menu you will always get default folder
![Capture](https://user-images.githubusercontent.com/5103892/98163467-8b691680-1eeb-11eb-8fb7-8d427f9132aa.PNG)

**Comment by ilya-fedin** [comment]
Both Ctrl+S and "Save As" item restoring the last path for me

**Comment by Gepar** [comment]
> Both Ctrl+S and "Save As" item restoring the last path for me
That's strange, i have two desktops with windows 10 and last tg client and both has same behavior.

**Comment by ilya-fedin** [comment]
I'm on Linux, maybe @Aokromes can test on WIndows

**Comment by Aokromes** [comment]
like i said, save as forks for me.
