### ISSUE TITLE
The "🥺" emoji does not appear to be quickly writeable with the colon shortcut

### ISSUE THREAD

**Issue by Aiku1** [telegramdesktop/tdesktop#8923]
### Is your feature request related to a problem?
Other emojis (such as 😡) are easily written by using `:anger:` or similar keywords.  🥺 (and possibly other emojis) appears to be missing that.

### Describe the solution you'd like
Update the list of the emoji shortcuts.

**Comment by ilya-fedin** [comment]
#780
