### ISSUE TITLE
[BUG] Window is ready notification on GNOME desktop

### ISSUE THREAD

**Issue by gabrc52** [telegramdesktop/tdesktop#8924]
### Steps to reproduce
1. Use the GNOME desktop.
2. Receive a message from a non-muted group (or user)

### Expected behaviour
Either:
1. Only the customized notification appears
2. Only a native notification appears, but with the content of the message, sender and picture.

### Actual behaviour
I get a customized notification as expected, but also a native notification saying "Telegram ({number of unread messages}) is ready"

### Context
I use an extension (Steal my Focus) that puts the window that "is ready" on focus, so every time I get a notification, Telegram gets focus. Getting an extra notification is still redundant, even if I didn't.

### Configuration
**Operating system:**
Fedora 33

**Version of Telegram Desktop:**
2.4.3

**Installation source (Linux Only)** - the official website / GitHub releases / flatpak / snap / distribution package:
RPM fusion

**Used theme**:
Default (dark)

_No log provided, but I can generate one if needed._

**Comment by ilya-fedin** [comment]
#8853
