### ISSUE TITLE
Inactive links in channel info

### ISSUE THREAD

**Issue by Neurotoxin001** [telegramdesktop/tdesktop#8926]
### Steps to reproduce
1. Go to `https://t.me/joinchat/AAAAAETO5esghXb1FdanNg` (**NSFW**) and open channel info
2. Links are inactive
<details><summary><b>Screenshot</b>:</summary>

![image](https://user-images.githubusercontent.com/39812401/97563786-9fe17680-19f4-11eb-9b6f-9081ec5e72f0.png)

</details>

At the same time on iOS links are active:

<details><summary><b>Screenshot</b>:</summary>

![image](https://user-images.githubusercontent.com/39812401/97563774-96f0a500-19f4-11eb-8975-2e782da07ade.png)

</details>

And this channel is not banned on iOS for porn:
`https://tgstat.ru/channel/AAAAAETO5esghXb1FdanNg`

<details><summary><b>Screenshot</b>:</summary>

![7vj6XT3Y6O](https://user-images.githubusercontent.com/39812401/97564012-fb136900-19f4-11eb-9b04-e62d13f47cac.png)

</details>

There is no "Channel access is restricted in some Telegram clients" message like for banned on iOS channels, for example:
`https://tgstat.ru/channel/@ru2ch_ban`
<details><summary><b>Screenshot</b>:</summary>

![i8DxAtJfGV](https://user-images.githubusercontent.com/39812401/97564005-f8b10f00-19f4-11eb-944c-3201170918f2.png)

</details>

### Configuration
**Operating system:** win 10 ltsc 1809

**Version of Telegram Desktop:** 2.4.4

**Used theme**: dark default

**Comment by ilya-fedin** [comment]
#7101

**Comment by Neurotoxin001** [comment]
@ilya-fedin it's different issue. There is even @ links is inactive.

Here is another channel with @ links for example, and they active:
![image](https://user-images.githubusercontent.com/39812401/97575445-c8ba3980-19fd-11eb-90d5-f92d0b64d344.png)

**Comment by Neurotoxin001** [comment]
after this https://github.com/telegramdesktop/tdesktop/commit/c35b6e12096b21f7dcbedf5b68ed9786bc3ea3fc
links become active, but not all

![image](https://user-images.githubusercontent.com/39812401/97818640-91c17d80-1cb4-11eb-81c1-f78cc181108e.png)

And question is still actual - why links in this channel was inactive

**Comment by john-preston** [comment]
@Neurotoxin001 This exact link (rhymesthrash) is not active because it doesn't have space between it and the emoji after. Others are fine now.

The description links are highlighted by each client and my regexp needs some delimeter between the mention and emoji.

**Comment by Neurotoxin001** [comment]
But can you please answer, why before this https://github.com/telegramdesktop/tdesktop/commit/c35b6e12096b21f7dcbedf5b68ed9786bc3ea3fc

Links was inactive in this channel and active in other?

https://user-images.githubusercontent.com/39812401/97563786-9fe17680-19f4-11eb-9b6f-9081ec5e72f0.png - inactive
https://user-images.githubusercontent.com/39812401/97575445-c8ba3980-19fd-11eb-90d5-f92d0b64d344.png - active
Channel was not banned or something

**Comment by john-preston** [comment]
@Neurotoxin001 This mention that finishes with emoji was not only "not highlighted" itself, but broke the regular expression for parsing the next links.

The commit you mentioned didn't fix that. That one fixed:

https://github.com/desktop-app/lib_ui/commit/54a8c62bf5dea5e381526a4b25aa5482e140b26c

**Comment by Neurotoxin001** [comment]
Ahhh now I understand it, thanks
