### ISSUE TITLE
[Feature Request] Show Attached Stickers in context menu, for Gif/Video

### ISSUE THREAD

**Issue by AhyaH-YHWH** [telegramdesktop/tdesktop#8927]
#Visual
When you edit Photo or Video, on Telegram Android, adding sticker to them
"Attached Stickers", only shows for Static Photos edited with Static Stickers, 
in right click menu on that Photo, to see used sticker Packs.

For Gif or Videos edited by Sticker packs, "Attached Stickers" doesn't appear on menu.
https://t.me/TelegramDesktopTalk/49387

Thanks.

**Comment by Neurotoxin001** [comment]
https://github.com/telegramdesktop/tdesktop/issues/1677
https://github.com/telegramdesktop/tdesktop/pull/8489
