### ISSUE TITLE
use internet settings from internet explorer

### ISSUE THREAD

**Issue by goofyas007** [telegramdesktop/tdesktop#893]
It would be very convenient to have telegram use the settings from internet explorer. This would prevent turning on & off the proxy settings within Telegram.
Because if you turn off the proxy, eg leave a proxied environment, there's no problem, but if you return to your proxied environment you'll have to fill in all the settings again. So that would mean proxy address & if  there is a username / password setting in the proxy that also.

Kind regards

**Comment by auchri** [comment]
#178
