### ISSUE TITLE
Resizing the image preview window doesnt resize the image with it

### ISSUE THREAD

**Issue by teoet6** [telegramdesktop/tdesktop#8934]
![image](https://user-images.githubusercontent.com/48878678/97692743-0ec3db80-1a98-11eb-9073-2e8d78978664.png)

Click on an image to open its preview
Resize the preview's window
The image is not resized

### Configuration
**Operating system:**
Linux

**Version of Telegram Desktop:**
2.4.4-1

**Installation source (Linux Only)** - the official website / GitHub releases / flatpak / snap / distribution package:
pacman

**Used theme**:
Day

**Comment by ilya-fedin** [comment]
Already fixed on dev branch
