### ISSUE TITLE
[Feature Request] Allow group chat moderators to dismiss pins (instead of just unpinning)

### ISSUE THREAD

**Issue by inacioisback** [telegramdesktop/tdesktop#8937]
### Is your feature request related to a problem?
Group chat moderators can't dismiss pins. They can only unpin.

### Describe the solution you'd like
Allow group chat moderators to dismiss pins (like on mobile).

**Comment by ilya-fedin** [comment]
#1790

**Comment by inacioisback** [comment]
> #1790

Thanks, actually searched beforehand but couldn't find it.
