### ISSUE TITLE
[Feature Request] Show Associated Stickers on Emoji Shortcut

### ISSUE THREAD

**Issue by leeola** [telegramdesktop/tdesktop#894]
On OSX, if you select an Emoji, it shows the associated stickers. Unfortunately, this does not work when you **type** an emoji. Eg, `:ok:` or `:thumbsup:`.

**Comment by auchri** [comment]
duplicate #627

**Comment by spiritualcoach** [comment]
As I understand it's not a duplicate since TS talks about showing associated sticker to each emoji. Anyways #2886 is more important imho.

**Comment by stek29** [comment]
@spiritualcoach #627 fixes this issue, because TDesktop already has associated stickers on emoji, but doesn't have emoji from text.
