### ISSUE TITLE
no comment is displayed but in another client they are shows

### ISSUE THREAD

**Issue by f242** [telegramdesktop/tdesktop#8940]
### Steps to reproduce
1. click "Comments"

### Expected behaviour
show comments

### Actual behaviour
nothing appears

### Configuration
win 10 x64 2004

**Version of Telegram Desktop:**
2.4.4

video
[2020-10-30-20-23-54.zip](https://github.com/telegramdesktop/tdesktop/files/5466679/2020-10-30-20-23-54.zip)

**Comment by Aokromes** [comment]
try on 2.4.8.
