### ISSUE TITLE
"Compress images" checkbox did not work as expected

### ISSUE THREAD

**Issue by SpriteOvO** [telegramdesktop/tdesktop#8943]
### Steps to reproduce
1. Drag and drop a picture into the chat box.
2. Uncheck "Compress images" and click "Send".
3. Drag and drop a picture into the chat box again.
4. You will see that "Compress images" is still checked.
5. Click "Send", but the image sent is uncompressed.

### Expected behaviour
Whether the sent image is compressed or not should depend on whether "Compress images" is checked.

### Actual behaviour
Whether the sent image is compressed or not does not depend on whether "Compress images" is checked.

### Configuration
**Operating system:** Windows 10

**Version of Telegram Desktop:** 2.4.5

**Used theme**: Night mode

### Gif
![2](https://user-images.githubusercontent.com/33660554/97749523-29469500-1b2a-11eb-96e6-1c2225657728.gif)

**Comment by reallyuniquename** [comment]
Same. I can no longer post image as full featured image, only as general file.

**Comment by SpriteOvO** [comment]
> Same. I can no longer post image as full featured image, only as general file.

Here's a workaround: using Ctrl+V to paste the image will not be affected by this problem.

**Comment by reallyuniquename** [comment]
No, this affects all images including those I paste from clipboard. 

I tried other buttons on the image upload form and somehow it got fixed. Anyway this is not how it's supposed to work.

**Comment by AtilioA** [comment]
The double drag area is not working properly with the checkbox, it seems

**Comment by imashxtyz** [comment]
same for me

**Comment by zampa00** [comment]
Adding something to this:
selecting "attach file" and browsing to an image open the same panel with the checkbox "Compress image", and it's working as intended.
BUT, if you try to drag and drop an image, no matter if the box is checked or not, it will always send it in the same manner you chose earlier during the "attach file"

**Comment by Begetosha** [comment]
Same story with GIF. But this
> Here's a workaround: using Ctrl+V to paste the image will not be affected by this problem.

or

> selecting "attach file" and browsing to an image open the same panel with the checkbox "Compress image", and it's working as intended.

doesn't work

**Comment by zsmax** [comment]
Same problem with JPG in revert option - I can't send JPG without compression.

**Comment by MasterGroosha** [comment]
Drag and Drop is really broken on Linux, for me it always sends a "compressed" image, not even as file. Even if I drag-and-drop it on "Send without compression" field

**Comment by fareezMaple** [comment]
Prefer the old method :(
