### ISSUE TITLE
Can't set caption to album of files when sending them

### ISSUE THREAD

**Issue by Neurotoxin001** [telegramdesktop/tdesktop#8944]
### Steps to reproduce
1. Send 2+ files with "group items" checkbox enabled
2. Try to write caption before sending:
![image](https://user-images.githubusercontent.com/39812401/97748697-ee7b3780-1afe-11eb-80f3-0c57dea68808.png)
3. After you send it - caption will be sended first and all files will be without any caption, but after they will be uploaded you can set 1 caption per 1 file:
![image](https://user-images.githubusercontent.com/39812401/97748766-0b176f80-1aff-11eb-83ff-8f5c3fee8457.png)

So you must do something with "caption" text field when sending files, because it's useless and sending caption before files.

### Configuration
**Operating system:** win 10 ltsc 1809

**Version of Telegram Desktop:** 2.4.5

**Used theme**: dark default

**Comment by AtilioA** [comment]
I had the same problem for a moment when pasting one or more images from the clipboard (not when selecting an image through the browser). I was about to open an issue but couldn't reproduce it anymore. I have experience this with the exact same configuration as OP.

**Comment by john-preston** [comment]
@Neurotoxin001 The field will be called "Comment", not "Caption" in this case. Adding one caption to an album of several files (or music files) is strange, because there is no way to specify, which element of the album will get that caption.

**Comment by SmartManoj** [comment]
albums have individual captions
