### ISSUE TITLE
Cannot pin message in "service notifications" chat

### ISSUE THREAD

**Issue by TheCGDF** [telegramdesktop/tdesktop#8945]
![Telegram_qTfqgBhOls](https://user-images.githubusercontent.com/17256673/97761719-c664f600-1b49-11eb-922c-d1475fbc7230.jpg)

Cannot pin message in "service notifications" chat.

As it says——"Pin several messages in **any** chat". 

This is obviously a chat because we can see "Delete **chat**" in the right-menu.

Even we can send message in "service notifications" chat.

**Version of Telegram Desktop:**
2.4.5

**Comment by RadRussianRus** [comment]
It's a local message, so it can't be pinned server-side, and pins are server-side. Message with login code are cloud, and they can be pinned.

**Comment by TheCGDF** [comment]
> It's a local message, so it can't be pinned server-side, and pins are server-side. Message with login code are cloud, and they can be pinned.

If I send message in "service notifications" chat, will someone see it?
