### ISSUE TITLE
[Feature Request] Open Discussion chat by clicking at the arrow icon

### ISSUE THREAD

**Issue by AtilioA** [telegramdesktop/tdesktop#8946]
### Is your feature request related to a problem?
For now, users can only open a discussion chat in a group by clicking the first message of the discussion and then selecting 'View X replies'. This is already cumbersome since the user needs to go all the way up to the first message.

### Describe the solution you'd like
This could be improved by making the little arrow icon clickable or clickable with a modifier key such as Ctrl or Shift, leading the user to the discussion chat directly.
 
### Describe alternatives you've considered
The only alternative is to right-click the first message of the thread then select 'View X replies';

**Comment by reallyuniquename** [comment]
https://github.com/telegramdesktop/tdesktop/issues/8675

**Comment by AtilioA** [comment]
Great, I hadn't see that
