### ISSUE TITLE
Old delete confirmation for "unsend message" when deleting Randomly Generated Emojis

### ISSUE THREAD

**Issue by rondevous** [telegramdesktop/tdesktop#8947]
![image](https://user-images.githubusercontent.com/67483423/97767433-fad4b400-1b41-11eb-9f56-47d0782f8529.png)

### Steps to reproduce:
1. Send any of these types of emojis 🎲 🎰 🏀🎯 to another person.
2. Select **two or more** messages including the randomly generated emoji
3. Proceed to delete them.
4. Observe the confirmation dialog.

### Expected Behavior:
"Also delete for {user}" confirmation box.

### Actual Behavior:
"Unsend message" confirmation box.

### Additional Info:
Can be reproduced in private 1-1 chats, except bot chats.

### Configuration
**Operation System** - Linux Mint 20 Cinnamon
**TDesktop Version** - v2.4.5
**Installation source** - Official Website
**Used theme**: https://t.me/addtheme/TidalGreen

<details><summary><b>Snippet from Logs</b>:</summary>
[2020.10.31 06:19:48] Skipping message, because it is already in blocks!
[2020.10.31 06:29:44] Skipping message, because it is already in blocks!
[2020.10.31 06:29:48] Message Info: bad message notification received (error_code 33) for msg_id = 6889582754619772076, seq_no = 977
[2020.10.31 06:29:48] Message Info: bad message notification received, msgId 6889582754619772076, error_code 33
[2020.10.31 06:29:50] Skipping message, because it is already in blocks!
</details>

**Comment by john-preston** [comment]
@rondevous This is intended. You can’t revoke this message for a day or two.

**Comment by M299792458** [comment]
@john-preston Hi, could you please tell me why? What is the reason behind such decision?

**Comment by john-preston** [comment]
@M299792458 So you won’t generate new outcomes and quickly delete them until you have your six on the dice or 777 on the slot machine :)

**Comment by M299792458** [comment]
> @M299792458 So you won’t generate new outcomes and quickly delete them until you have your six on the dice or 777 on the slot machine :)

Oh, thanks. :+1:
