### ISSUE TITLE
[Feature Request] allow multiple forwarded messages be combined

### ISSUE THREAD

**Issue by ericclose** [telegramdesktop/tdesktop#8948]
### Is your feature request related to a problem?

Currently forwarded multiple messages will seem to take up too much space.

### Describe the solution you'd like

Send multiple forwarded messages (preview) in one chat bubble. And if you click the chat bubble, it will show the full content, it's a bit like the current **channel comments screen**.

**Comment by ilya-fedin** [comment]
4660?

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/4660
