### ISSUE TITLE
Going from 1080p monitor to 4K screen, telegram doesn't reset resolution

### ISSUE THREAD

**Issue by Somiac** [telegramdesktop/tdesktop#8949]
### Steps to reproduce
1. Have 4K laptop to 1080p resolution external monitor (with laptop screen off)
2. unplug the HDMI
3. Telegram is now super tiny on your 4K monitor

### Expected behaviour
Telegram should scale to the resolution of the screen it is appearing on

### Actual behaviour
Telegram doesn't adjust

### Configuration
Windows 10
Latest as of today
Default dark theme

**Comment by ilya-fedin** [comment]
#1121
