### ISSUE TITLE
is not posible to delete a collection of stickers

### ISSUE THREAD

**Issue by sstebann** [telegramdesktop/tdesktop#895]
Hello I'm using Telegram Desktop Version 0.8.38, and I tried to delete a collection of stickers, with right click of the mouse but it's not possible

**Comment by auchri** [comment]
Next to the pack name appears a delete icon if you hover it

**Comment by sstebann** [comment]
found it, thank you

**Comment by sstebann** [comment]
Take the world's best courses, online. Coursera envisions a world where 
anyone, anywhere can transform their life by accessing the world’s best 
learning experience.
[Ready to learn something new?]
<https://eventing.coursera.org/redirectSigned/eyJrZXkiOiJlbWFpbC5saW5rLm9wZW4iLCJ2YWx1ZSI6eyJ1cmwiOiJodHRwczovL3d3dy5jb3Vyc2VyYS5vcmcvP3V0bV9tZWRpdW09ZW1haWwmdXRtX3NvdXJjZT1pbnZpdGF0aW9ucyZ1dG1fY2FtcGFpZ249bm90aWZpY2F0aW9ucy5hdXRvLjQ1QXg3ZHZMRWVXUUl3cUNFT3Q1YVEiLCJ0cmFja2luZyI6eyJ1c2VySWQiOi0xLCJ1c2VyRW1haWwiOiJyZXBseSswMGFmNTZhMjdiMWJjYjY4NWY5MDNmMzM5ZmZhNGY5NTgxYWZhNjM0NTI5ODZiYzI5MmNmMDAwMDAwMDExMWU2MWIzYTkyYTE2OWNlMDU5ODc2MjRAcmVwbHkuZ2l0aHViLmNvbSIsIm5vdGlmaWNhdGlvblR5cGUiOiJncm93dGguaW52aXRhdGlvbiIsImNhbXBhaWduSWQiOiJub3RpZmljYXRpb25zLmF1dG8uNDVBeDdkdkxFZVdRSXdxQ0VPdDVhUSJ9fSwidXNlcklkIjotMX0.WWeleBD2DkBwjvwG7kWqyHRAPiPUhQ1CpnMOMDIXZSo> 	
My Courses
<https://eventing.coursera.org/redirectSigned/eyJrZXkiOiJlbWFpbC5saW5rLm9wZW4iLCJ2YWx1ZSI6eyJ1cmwiOiJodHRwczovL3d3dy5jb3Vyc2VyYS5vcmcvP3V0bV9tZWRpdW09ZW1haWwmdXRtX3NvdXJjZT1pbnZpdGF0aW9ucyZ1dG1fY2FtcGFpZ249bm90aWZpY2F0aW9ucy5hdXRvLjQ1QXg3ZHZMRWVXUUl3cUNFT3Q1YVEiLCJ0cmFja2luZyI6eyJ1c2VySWQiOi0xLCJ1c2VyRW1haWwiOiJyZXBseSswMGFmNTZhMjdiMWJjYjY4NWY5MDNmMzM5ZmZhNGY5NTgxYWZhNjM0NTI5ODZiYzI5MmNmMDAwMDAwMDExMWU2MWIzYTkyYTE2OWNlMDU5ODc2MjRAcmVwbHkuZ2l0aHViLmNvbSIsIm5vdGlmaWNhdGlvblR5cGUiOiJncm93dGguaW52aXRhdGlvbiIsImNhbXBhaWduSWQiOiJub3RpZmljYXRpb25zLmF1dG8uNDVBeDdkdkxFZVdRSXdxQ0VPdDVhUSJ9fSwidXNlcklkIjotMX0.WWeleBD2DkBwjvwG7kWqyHRAPiPUhQ1CpnMOMDIXZSo> 
Course Catalog
<https://eventing.coursera.org/redirectSigned/eyJrZXkiOiJlbWFpbC5saW5rLm9wZW4iLCJ2YWx1ZSI6eyJ1cmwiOiJodHRwczovL3d3dy5jb3Vyc2VyYS5vcmcvY291cnNlcz91dG1fbWVkaXVtPWVtYWlsJnV0bV9zb3VyY2U9aW52aXRhdGlvbnMmdXRtX2NhbXBhaWduPW5vdGlmaWNhdGlvbnMuYXV0by40NUF4N2R2TEVlV1FJd3FDRU90NWFRIiwidHJhY2tpbmciOnsidXNlcklkIjotMSwidXNlckVtYWlsIjoicmVwbHkrMDBhZjU2YTI3YjFiY2I2ODVmOTAzZjMzOWZmYTRmOTU4MWFmYTYzNDUyOTg2YmMyOTJjZjAwMDAwMDAxMTFlNjFiM2E5MmExNjljZTA1OTg3NjI0QHJlcGx5LmdpdGh1Yi5jb20iLCJub3RpZmljYXRpb25UeXBlIjoiZ3Jvd3RoLmludml0YXRpb24iLCJjYW1wYWlnbklkIjoibm90aWZpY2F0aW9ucy5hdXRvLjQ1QXg3ZHZMRWVXUUl3cUNFT3Q1YVEifX0sInVzZXJJZCI6LTF9.L8jxxH8R3zmc5RvdWetoMdZJDAfqhqH8_6hkHDl0OFE>


Esteban Ruiz thinks you'll love learning on Coursera

We envision a world where anyone, anywhere can transform their life by 
accessing the world’s best learning experience. We offer hundreds open 
online courses, in dozens of subject areas, all from top universities and 
institutions.

Course topics range from business and management, to computer science, to 
medicine, music, education, and more.

Millions of our learners have advanced their careers, discovered new 
passions, and built lasting friendships through their Coursera courses. We 
hope you'll join us in learning without limits!

The Coursera Team

Explore Coursera
<https://eventing.coursera.org/redirectSigned/eyJrZXkiOiJlbWFpbC5saW5rLm9wZW4iLCJ2YWx1ZSI6eyJ1cmwiOiJodHRwczovL3d3dy5jb3Vyc2VyYS5vcmcvb25ib2FyZGluZy8_dG9rZW49MGJmMWEwZjE0Y2E4MmNiMWU1ODQ5ZGI0MDdjZDkwMjkmZW1haWw9cmVwbHkrMDBhZjU2YTI3YjFiY2I2ODVmOTAzZjMzOWZmYTRmOTU4MWFmYTYzNDUyOTg2YmMyOTJjZjAwMDAwMDAxMTFlNjFiM2E5MmExNjljZTA1OTg3NjI0QHJlcGx5LmdpdGh1Yi5jb20mbmFtZT10ZWxlZ3JhbWRlc2t0b3AvdGRlc2t0b3A_dXRtX21lZGl1bT1lbWFpbCZ1dG1fc291cmNlPWludml0YXRpb25zJnV0bV9jYW1wYWlnbj1ub3RpZmljYXRpb25zLmF1dG8uNDVBeDdkdkxFZVdRSXdxQ0VPdDVhUSIsInRyYWNraW5nIjp7InVzZXJJZCI6LTEsInVzZXJFbWFpbCI6InJlcGx5KzAwYWY1NmEyN2IxYmNiNjg1ZjkwM2YzMzlmZmE0Zjk1ODFhZmE2MzQ1Mjk4NmJjMjkyY2YwMDAwMDAwMTExZTYxYjNhOTJhMTY5Y2UwNTk4NzYyNEByZXBseS5naXRodWIuY29tIiwibm90aWZpY2F0aW9uVHlwZSI6Imdyb3d0aC5pbnZpdGF0aW9uIiwiY2FtcGFpZ25JZCI6Im5vdGlmaWNhdGlvbnMuYXV0by40NUF4N2R2TEVlV1FJd3FDRU90NWFRIn19LCJ1c2VySWQiOi0xfQ.h15cRrQDb050jlD_W7yDznSPglcNrjfmVIRpUfeWKIE>
Download our App:  iOS
<https://eventing.coursera.org/redirectSigned/eyJrZXkiOiJlbWFpbC5saW5rLm9wZW4iLCJ2YWx1ZSI6eyJ1cmwiOiJodHRwczovL2l0dW5lcy5hcHBsZS5jb20vYXBwL2FwcGxlLXN0b3JlL2lkNzM2NTM1OTYxP2N0PU1vYmlsZSUyMFByb21vJTIwRW1haWwmdXRtX3NvdXJjZT1pbnZpdGF0aW9ucyZtdD04JnB0PTIzMzQxNTAmdXRtX2NhbXBhaWduPW5vdGlmaWNhdGlvbnMuYXV0by40NUF4N2R2TEVlV1FJd3FDRU90NWFRJnV0bV9tZWRpdW09ZW1haWwiLCJ0cmFja2luZyI6eyJ1c2VySWQiOi0xLCJ1c2VyRW1haWwiOiJyZXBseSswMGFmNTZhMjdiMWJjYjY4NWY5MDNmMzM5ZmZhNGY5NTgxYWZhNjM0NTI5ODZiYzI5MmNmMDAwMDAwMDExMWU2MWIzYTkyYTE2OWNlMDU5ODc2MjRAcmVwbHkuZ2l0aHViLmNvbSIsIm5vdGlmaWNhdGlvblR5cGUiOiJncm93dGguaW52aXRhdGlvbiIsImNhbXBhaWduSWQiOiJub3RpZmljYXRpb25zLmF1dG8uNDVBeDdkdkxFZVdRSXdxQ0VPdDVhUSJ9fSwidXNlcklkIjotMX0.X0krfbifyOyf40Ny2lu50Z3yV8IRMSxrTq8cX3wveZk> 
  |  Android
<https://eventing.coursera.org/redirectSigned/eyJrZXkiOiJlbWFpbC5saW5rLm9wZW4iLCJ2YWx1ZSI6eyJ1cmwiOiJodHRwczovL3BsYXkuZ29vZ2xlLmNvbS9zdG9yZS9hcHBzL2RldGFpbHM_aWQ9b3JnLmNvdXJzZXJhLmFuZHJvaWQmdXRtX21lZGl1bT1lbWFpbCZ1dG1fc291cmNlPWludml0YXRpb25zJnV0bV9jYW1wYWlnbj1ub3RpZmljYXRpb25zLmF1dG8uNDVBeDdkdkxFZVdRSXdxQ0VPdDVhUSIsInRyYWNraW5nIjp7InVzZXJJZCI6LTEsInVzZXJFbWFpbCI6InJlcGx5KzAwYWY1NmEyN2IxYmNiNjg1ZjkwM2YzMzlmZmE0Zjk1ODFhZmE2MzQ1Mjk4NmJjMjkyY2YwMDAwMDAwMTExZTYxYjNhOTJhMTY5Y2UwNTk4NzYyNEByZXBseS5naXRodWIuY29tIiwibm90aWZpY2F0aW9uVHlwZSI6Imdyb3d0aC5pbnZpdGF0aW9uIiwiY2FtcGFpZ25JZCI6Im5vdGlmaWNhdGlvbnMuYXV0by40NUF4N2R2TEVlV1FJd3FDRU90NWFRIn19LCJ1c2VySWQiOi0xfQ.zaehfnplapRazhDm1dECPO0vUocgNh4HFL2VTrhmbm4>
Learner Help Center
<https://eventing.coursera.org/redirectSigned/eyJrZXkiOiJlbWFpbC5saW5rLm9wZW4iLCJ2YWx1ZSI6eyJ1cmwiOiJodHRwczovL2xlYXJuZXIuY291cnNlcmEuaGVscC8_dXRtX21lZGl1bT1lbWFpbCZ1dG1fc291cmNlPWludml0YXRpb25zJnV0bV9jYW1wYWlnbj1ub3RpZmljYXRpb25zLmF1dG8uNDVBeDdkdkxFZVdRSXdxQ0VPdDVhUSIsInRyYWNraW5nIjp7InVzZXJJZCI6LTEsInVzZXJFbWFpbCI6InJlcGx5KzAwYWY1NmEyN2IxYmNiNjg1ZjkwM2YzMzlmZmE0Zjk1ODFhZmE2MzQ1Mjk4NmJjMjkyY2YwMDAwMDAwMTExZTYxYjNhOTJhMTY5Y2UwNTk4NzYyNEByZXBseS5naXRodWIuY29tIiwibm90aWZpY2F0aW9uVHlwZSI6Imdyb3d0aC5pbnZpdGF0aW9uIiwiY2FtcGFpZ25JZCI6Im5vdGlmaWNhdGlvbnMuYXV0by40NUF4N2R2TEVlV1FJd3FDRU90NWFRIn19LCJ1c2VySWQiOi0xfQ.XkWXc8ww_3E9UOV859g4tCfOERyl9MOKpAm0ausx3kQ> 
  | Please do not reply directly to this email
To no longer receive invitations from your friends on Coursera, 
Unsubscribe
<https://eventing.coursera.org/redirectSigned/eyJrZXkiOiJlbWFpbC5saW5rLm9wZW4iLCJ2YWx1ZSI6eyJ1cmwiOiJodHRwczovL3d3dy5jb3Vyc2VyYS5vcmcvYWNjb3VudC91bnN1YnNjcmliZS9tcEo4YlVYUllDakh4bHBBV1l4T2o2Sk9mTjktU2Z1UHBIcS14Y2JtN0k5dl91VjRrYkpNWmlRcDBMeXV5bUptOVhYVnF2OTFIWTQzSXpYZHlVOXdOQS5MU250LUc1ZDltQ0lnaEFlMHRDVzBRLklXdWY0TnBUWjgxYmFfOUdIRVlIdlBNeC1lTlZORDN5QTIxNHdSU21QQUYydm5hUk5YQTVuUWNGTUNfY1ZZeWhtU3JpRjUwc2czNWtmdnVtRkNQV01wMEFRbEtodkpobkhsYlJ5MXA2MldNQnpYQVlHeGgxYUtSS0ZpajJJcjhCSGM3UHYyRXZ6QjJjVlpzS2VqaTRiUVdXaTdJUWJaZ3haV2Nfdi1vTGdLdFd1RmczVmRpTzdZVUlzWFliM0pRR0VJLS1Sb2F0dzVKMWFiWXZIRFYwSVIyYjZpcDJrUnh0RnZ6NEFJV2lsZGdwYVBheVRsQkdST19qdjBKbGQ4UkIwZlliVUpuU1pXQ2JXakRtdEZNNWt0ajN4d21uMWpSb1NDUGVqSGVYb3VuREFpSF8wR1FORnFZODhhTjkxZXZaP3V0bV9tZWRpdW09ZW1haWwmdXRtX3NvdXJjZT1pbnZpdGF0aW9ucyZ1dG1fY2FtcGFpZ249bm90aWZpY2F0aW9ucy5hdXRvLjQ1QXg3ZHZMRWVXUUl3cUNFT3Q1YVEiLCJ0cmFja2luZyI6eyJ1c2VySWQiOi0xLCJ1c2VyRW1haWwiOiJyZXBseSswMGFmNTZhMjdiMWJjYjY4NWY5MDNmMzM5ZmZhNGY5NTgxYWZhNjM0NTI5ODZiYzI5MmNmMDAwMDAwMDExMWU2MWIzYTkyYTE2OWNlMDU5ODc2MjRAcmVwbHkuZ2l0aHViLmNvbSIsIm5vdGlmaWNhdGlvblR5cGUiOiJncm93dGguaW52aXRhdGlvbiIsImNhbXBhaWduSWQiOiJub3RpZmljYXRpb25zLmF1dG8uNDVBeDdkdkxFZVdRSXdxQ0VPdDVhUSJ9fSwidXNlcklkIjotMX0.FSw0MMHwEUGfMHpIhqFJOWEPR57LlHD16cn-l9cr-S8>
Copyright © 2016, Coursera Inc. | 381 E. Evelyn Ave, Mountain View, CA 
94041 USA
