### ISSUE TITLE
Caption select not showing under albums

### ISSUE THREAD

**Issue by Neurotoxin001** [telegramdesktop/tdesktop#8950]
### Steps to reproduce
1. Post 2+ images to create album and write some caption
2. Try to select this caption after you post it
3. You can do it but visually there is no selection

https://i.imgur.com/w3lhWPp.mp4

### Configuration
**Operating system:** win 10 ltsc 1809

**Version of Telegram Desktop:** 2.4.5

**Used theme**: dark default

**Comment by hookzof** [comment]
The same and a profile avatar is missing from the group.
