### ISSUE TITLE
photos are send as files

### ISSUE THREAD

**Issue by magowjzeta** [telegramdesktop/tdesktop#8951]
### Steps to reproduce
1. 
2. 
3. 

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

### Configuration
**Operating system:**
Windows 7, Windows 10
**Version of Telegram Desktop:**
2.45
**Installation source (Linux Only)** - the official website / GitHub releases / flatpak / snap / distribution package:
Official website
**Used theme**:
Black
<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>
Big problem with the 2.4.5 update : photos are send as files
Non gif animated with 🎰

**Comment by Aokromes** [comment]
works for me on windows 10 20h1.

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/8943
