### ISSUE TITLE
[Feature Request] Let admins decide for themselves about "remain anonymous"

### ISSUE THREAD

**Issue by imashxtyz** [telegramdesktop/tdesktop#8953]
As of right now, it is only possible for admins of the group to be anonymous if the creator of the group enables that option for them. Better way would be to allow every admin to switch this option on and off whenever they like. It may be very important in some cases.
![image](https://user-images.githubusercontent.com/46919076/97783881-55bfe700-1be6-11eb-8e7f-e1b919b8b23f.png)

**Comment by Aokromes** [comment]
i think this must be done api side.

**Comment by MasterGroosha** [comment]
This might break the hierarchy of admins. As a workaround, a bot may be implemented which will add/revoke the specific ability to/from admin on demand

**Comment by imashxtyz** [comment]
@MasterGroosha could you please explain how it breaks hierarchy of admins? or were you answering for api tweak suggestion?
