### ISSUE TITLE
[Manjaro KDE] https links get open in a different browser, not the default one

### ISSUE THREAD

**Issue by Mrcuve0** [telegramdesktop/tdesktop#8954]
### Steps to reproduce
1. Write in `Saved messages` three messages, each message is a different link: 
* the first link like `https://www.youtube.com`
* the second like `www.youtube.com`
* the third one like `http//www.youtube.com`

2. By clicking on the links, all of them should open in the default browser (expected behavior), in my case the `https://` one gets open in Brave, my secondary browser (actual behavior)

3. Try to open the links in the `about` section. They are all opened in Brave (actual behavior)

### Expected behaviour
Every link (in a chat or in the app itself, for example links in the `about` section) should be opened in Firefox, which in my case is my default browser, which gets launched using the following command:
![Screenshot_20201031_184934](https://user-images.githubusercontent.com/36898760/97786137-d6142700-1ba9-11eb-9852-ee363722b77f.png)
(I also tested setting only `/usr/bin/firefox` as default browser, without all the env vars, same behavior)

### Actual behaviour
* Links having the `https://` schema (like `https://www.youtube.com`) get open in Brave, which is not my default browser (this can be probably extended to all Chromium Browsers).

* Links having just the URL (like `www.google.com`) or the `http://` schema (like `http://www.google.com`) get open in the default browser (Firefox in my case).

You can also test with the links in the `about` section: in my case all of them get open in Brave (should be opened in Firefox)

### Additional tests
Here some tests done with other applications:

1) w/ `xdg-open`
* `xdg-open https://www.google.com` --> gets open in Firefox, ok ✅
* `xdg-open www.google.com` --> gets open in Firefox, ok ✅
* `xdg-open https://www.trenitalia.com` --> gets open in Firefox, ok ✅
* `xdg-open www.trenitalia.com` --> gets open in Firefox, ok ✅

2) Within Konsole (Ctrl-LeftClick on link)
* `https://www.google.com` --> gets open in Firefox, ok ✅
* `www.google.com` --> gets open in Firefox, ok ✅
* `https://www.trenitalia.com` --> gets open in Firefox, ok ✅
* `www.trenitalia.com` --> gets open in Firefox, ok ✅

3) Link in a PDF, opened w/ Okular
* `https://www.google.com` --> gets open in Firefox, ok ✅
* `www.google.com` --> gets open in Firefox, ok ✅
* `https://www.trenitalia.com` --> gets open in Firefox, ok ✅
* `www.trenitalia.com` --> gets open in Firefox, ok ✅

Issue seems limited to Telegram Desktop only, at least for now

### Configuration
**Operating system:**
Operating System: Manjaro Linux
KDE Plasma Version: 5.19.5
KDE Frameworks Version: 5.74.0
Qt Version: 5.15.1
Kernel Version: 5.9.1-1-MANJARO
OS Type: 64-bit

**Version of Telegram Desktop:**
Version 2.4.5

**Installation source (Linux Only)** - the official website / GitHub releases / flatpak / snap / distribution package:
Official Website

**Used theme**:
Theme "Day" (The issue is theme independent, tested)

<details><summary><b>Logs</b>:</summary></details>

[log.txt](https://github.com/telegramdesktop/tdesktop/files/5469615/log.txt)

However, the "click link" action doesn't seem to get recorder, as it happened at around 19:33, and the log terminate at around 19:32

**Comment by ilya-fedin** [comment]
`gio mime x-scheme-handler/https`

**Comment by Mrcuve0** [comment]
```
(gio mime:402236): GLib-GIO-WARNING **: 21:20:37.535: /etc/xdg/kde-mimeapps.list contains a [Added Associations] group, but it is not permitted here.  Only the non-desktop-specific mimeapps.list file may add or remove associations.
Default application for ?x-scheme-handler/https?: brave-browser.desktop
Registered applications:
        brave-browser.desktop
Recommended applications:
        brave-browser.desktop
```

**Comment by ilya-fedin** [comment]
Well, that's why brave opens

**Comment by Mrcuve0** [comment]
Thank you for your help, I'm trying finding some documentation on how to set it. 
BTW, so this is not related to the latest update right? Never had this problem before today, quite a strange coincidence

**Comment by ilya-fedin** [comment]
Related, I've replaced xdg utils calls with glib methods calls. xdg utils have a lot of bugs, they even doesn't respect their own spec in part of `Terminal` key of desktop files. In any way, library calls should be preferable rather than launching an external binary.

**Comment by Mrcuve0** [comment]
Oh, I see, thank you for the explanation! I'm quite ignorant on this, sadly. Thank you for your work and your help.
For those interested that may read this, the following solved my issue:

`xdg-mime default firefox.desktop x-scheme-handler/https`

(you can close when you feel to, thank you once again!)

**Comment by ilya-fedin** [comment]
> (you can close when you feel to, thank you once again!)

I can't close issues since I'm a third-party contributor, but you can
