### ISSUE TITLE
Audio calls microphone don't work (audio messages work)

### ISSUE THREAD

**Issue by Nesos-ita** [telegramdesktop/tdesktop#8961]
### Steps to reproduce
1.  open telegram desktop and call someone
2. they can't hear you

### Expected behaviour
The mic should work

### Actual behaviour
window opens as ususal but mic doesn't work (people can't hear me) 
note that audio messages work on telegram (people can hear my messages), only audio calls don't.  
other programs like audacity work.

### Configuration
win10 build 1909
telegram 2.4.5 portable (latest right now)

it is not a win 10 permission issue or mic sensitivity problem because it works both on other apps and on telegram if you send an audio message, only audio calls are affected by the problem.  
windows control panel calls the device realtek "Microphone array" i don't know if this can be the problem...

**Comment by ilya-fedin** [comment]
#8443
