### ISSUE TITLE
[Feature Request] Hiding/unhiding pinned chats

### ISSUE THREAD

**Issue by ivanburak** [telegramdesktop/tdesktop#8962]
v 2.4.5 30.10.20

Please add to Telegram a possibility to easy **hide/unhide pinned chats**

For example it could be shown in a chat list with 2 groups:
**Pinned >
Others >**
and each group could be shown as opened or closed on the screen.

Folders is a good thing for chat grouping but an user usually lives with the flat chat list in Telegram.

Thanks
ib

**Comment by fareezMaple** [comment]
In my opinion. It defies the purpose of **Pinned message**. It supposed to be it like usual, make the user keep focused.
