### ISSUE TITLE
Rendering glitch

### ISSUE THREAD

**Issue by JuniorJPDJ** [telegramdesktop/tdesktop#8966]
### Steps to reproduce
1. send message similar to one from screenshot
2. reply to this message like on screenshot

### Expected behaviour
This text should be inside of "bubble"

### Actual behaviour
![image](https://user-images.githubusercontent.com/7334549/97807746-e3d9b300-1c62-11eb-913b-80c34aae729a.png)

### Configuration
**Operating system:** Arch Linux

**Version of Telegram Desktop:** 2.4.4

**Installation source (Linux Only)** - the official website / GitHub releases / flatpak / snap / distribution package: arch repository package

**Used theme**: stock `Night`

**Comment by ilya-fedin** [comment]
tdesktop UI is designed to work only with Open Sans, if it is not installed with tdesktop package in your distro, this is a packaging issue.

**Comment by john-preston** [comment]
@JuniorJPDJ I can't reproduce that in the official binary, the text get's elided with "...":

![image](https://user-images.githubusercontent.com/17900494/97849326-d298b100-1d0b-11eb-8bff-c2e19feddffe.png)
