### ISSUE TITLE
[Feature Request] Different WM_CLASS or window type for video calls

### ISSUE THREAD

**Issue by OJFord** [telegramdesktop/tdesktop#8969]
### Is your feature request related to a problem?
I want to be able to set video calls to floating windows (in i3wm), while still using a normal tiled window for the main chat/contacts list.

However, both the main window and the video call window have the following (excerpt from `xprop`):
```
WM_STATE(WM_STATE):
		window state: Normal
		icon window: 0x0
WM_NAME(STRING) = "Telegram"
_NET_WM_NAME(UTF8_STRING) = "Telegram"
_NET_WM_WINDOW_TYPE(ATOM) = _NET_WM_WINDOW_TYPE_NORMAL
WM_CLASS(STRING) = "telegram-desktop", "TelegramDesktop"
WM_PROTOCOLS(ATOM): protocols  WM_DELETE_WINDOW, WM_TAKE_FOCUS, _NET_WM_PING, _NET_WM_SYNC_REQUEST
```

so there's nothing I can use to target only video call windows.

### Describe the solution you'd like

`WM_CLASS` to have a different `res_name` in video call windows, e.g. `'Telegram video call'` or whatever.

### Describe alternatives you've considered
I had a look at the available `_NET_WM_WINDOW_TYPE`s, but none really seems more appropriate, it's not a splash, pop-up, tooltip, etc.

`WM_NAME` could change, but it might be desired to include even more information here (as it's used for window title bars) such as `video call with <name>` which couldn't be matched on so cleanly. (Off the top of my head I'm not even sure if wildcard/regex matches are supported at all in i3.)

**Comment by ilya-fedin** [comment]
I'm afraid this is not possible Qt handles this application-wide.
