### ISSUE TITLE
Add option to disable bouncing app icon while receiving notification

### ISSUE THREAD

**Issue by livelazily** [telegramdesktop/tdesktop#897]
bouncing app icon is so anoying

**Comment by auchri** [comment]
@telegramdesktop:
https://developer.apple.com/library/mac/documentation/Cocoa/Reference/ApplicationKit/Classes/NSApplication_Class/#reference_container

### Methods to Override
> Override [requestUserAttention](https://developer.apple.com/library/mac/documentation/Cocoa/Reference/ApplicationKit/Classes/NSApplication_Class/#//apple_ref/occ/instm/NSApplication/requestUserAttention:): if you want to modify how your app attracts the attention of the user (for example, offering an alternative to the bouncing app icon in the Dock).

See also: [cancelUserAttentionRequest](https://developer.apple.com/library/mac/documentation/Cocoa/Reference/ApplicationKit/Classes/NSApplication_Class/#//apple_ref/occ/instm/NSApplication/cancelUserAttentionRequest:)

**Comment by ryush00** [comment]
:+1:

**Comment by stek29** [comment]
Just comment out [`psFlash();`](https://github.com/telegramdesktop/tdesktop/blob/master/Telegram/SourceFiles/window.cpp#L1567) and build it

**Comment by joonaskokko** [comment]
This feature would be super awesome. The bouncing is really unnecessary.

**Comment by koolkhel** [comment]
Yes, it's not quite correct to ignore "Please, do not notify me at all" settings with this bouncing icon. With several multiuser chats it's getting unbearable :-(

**Comment by stek29** [comment]
@koolkhel wait, icon bounces when notifications are disabled?

**Comment by koolkhel** [comment]
Yes. All possible notifications (both inside Telegram and in macOS notification center) are disabled yet the icon bounces every received message.

**Comment by stek29** [comment]
Then it should be a [bug], not an [enhancement] IMO.

**Comment by niko-lay** [comment]
Confirm, in Telegram Desktop v0.10.19 from Appstore this bug is repeated

**Comment by joonas-exove** [comment]
Still exists in version 1.0.

**Comment by hesna** [comment]
please fix this one, it makes the app unusable. the other mac client does not have this problem.

**Comment by tulushev** [comment]
From [macOS Human Interface Guidelines](https://developer.apple.com/library/content/documentation/UserExperience/Conceptual/OSXHIGuidelines/Dock.html)
> **Use bouncing to notify users of serious information that requires their attention**. A bouncing Dock icon is very noticeable, so you should use this method only when the user really needs to know about something. Also, make sure you disable bouncing as soon as the user has addressed the problem.

This bouncing should be deleted entirely, it's violating guidelines(what users expect from UI|UX)

**Comment by joonaskokko** [comment]
Please do something about this. It's REALLY driving me nuts.

**Comment by ArtsiomSadyryn** [comment]
I subscribe to all the aforesaid. Developers, please! At least make an option to disable this.
P.S. I love client "Telegram Desktop" more than only macOS-client "Telegram". And it became very important.

**Comment by Dabendorf** [comment]
I agree with the others. Telegram is a great app, but **it is unusable** without deactivating that bouncing shit.

**Comment by stek29** [comment]
I can't reproduce icon bouncing for muted chats.

I like the fact icon bounces tbh. But for anyone who does not, here's the patch:
```diff
diff --git a/Telegram/SourceFiles/platform/mac/notifications_manager_mac.mm b/Telegram/SourceFiles/platform/mac/notifications_manager_mac.mm
index c6a61cbac99a..ac7e18a10f12 100644
--- a/Telegram/SourceFiles/platform/mac/notifications_manager_mac.mm
+++ b/Telegram/SourceFiles/platform/mac/notifications_manager_mac.mm
@@ -139,8 +139,7 @@ std::unique_ptr<Window::Notifications::Manager> Create(Window::Notifications::Sy
 	return nullptr;
 }
 
-void FlashBounce() {
-	[NSApp requestUserAttention:NSInformationalRequest];
+inline void FlashBounce() {
 }
 
 void CustomNotificationShownHook(QWidget *widget) {
```

**Comment by antonakv** [comment]
Enjoy
$ defaults write com.apple.dock no-bouncing -bool TRUE

**Comment by stek29** [comment]
@antonakv I don't want to disable bouncing completely, I just want Telegram to match Apple's guidelines and don't bounce.

**Comment by Aokromes** [comment]
#1184 ?

**Comment by laiti** [comment]
Please, please fix this one. It is very annoying and not along the Apple guidelines.

**Comment by reallyuniquename** [comment]
Any updates? Flashing taskbar icon is incredibly annoying on Windows.

**Comment by mxs42** [comment]
@reallyuniquename since devs ignore this for years, I wrote hacky console tool to patch executable and get rid of this stupid flashing.
Check it out, no issues with it if you don't want to maintain your own fork with flashing disabled
https://github.com/mxs42/mutegram

**Comment by enricll** [comment]
@mxs42 Sorry if it's a stupid question, but I'm very interesting in fixing that bug and I don't know how to proceed once I've downloaded your tool. I read the readme but I don't see an executable file inside the folder. Could you tell me the steps in a little bit more of detail? Thanks!

**Comment by mxs42** [comment]
@enricll download archive from Releases section.

**Comment by reallyuniquename** [comment]
@mxs42 Incredible job, thank you so much for your universal patch. I've built your tool with VS and successfully patched Telegram binary. 
> As you can see, there is no way to disable that «flashbounce» without disabling notifications completely.

Is it true though? Even if you completely disable Telegram notifications it still flashes its icon.

In case someone uses old VS version: you have to switch project's toolset to earlier version and add `#include <cstdint>` line to `main.cpp`.

**Comment by mxs42** [comment]
@reallyuniquename idk, I don't even want to test it again xD
Glad that it helped you.

**Comment by AaronMeyers** [comment]
well i guess this is never going to get fixed because the devs dgaf, but i would just like to register my opinion: the bouncing dock icon is extremely annoying!

**Comment by GuiSim** [comment]
What's the reasoning for keeping this? I started using Telegram recently and that's one of the most annoying aspect of the native macos app

**Comment by inDigiNeous** [comment]
Please disable the bouncing. Modern macOS apps don't really use this bouncing effect anymore. Why be different ? Thank you!

**Comment by asorokoumov** [comment]
Please, turn this annoying bouncing off

**Comment by oluwasayo** [comment]
I've visited this ticket many times and I'm very surprised it's getting no attention from the developers. I'm genuinely interested in knowing why.

**Comment by reallyuniquename** [comment]
@oluwasayo I am pretty sure this issue is waaaaay down the bug queue. Forget about it for year or two and either build your own version of Telegram client or use external patching tools to remove blinking.

**Comment by ihorinki** [comment]
Stopped using desktop version because of that.

**Comment by antonakv** [comment]
sudo defaults write com.apple.dock no-bouncing -bool TRUE

**Comment by testdevmm** [comment]
Have the same problem with version v.2.0.1
I`ve disabled notifications and counters, but cant disable the bouncing
<img width="641" alt="Screen Shot 2020-04-01 at 14 10 01" src="https://user-images.githubusercontent.com/25170458/78111739-1ac4bd80-7423-11ea-9f90-86379a0af062.png">
The Icon bounce if I`m staying in another window/display (even now, when I`m writing this)

![ezgif com-optimize](https://user-images.githubusercontent.com/25170458/78112193-e1408200-7423-11ea-8d5b-f2f639b3d109.gif)

Macos version 10.15.3
Telegram version v.2.0.1

**Comment by ilya-fedin** [comment]
You should disable notifications in _telegram_ settings

**Comment by Merlin2001** [comment]
On Windows, the taskbar still flashes if notifications are disabled entirely _in Telegram_. So I guess this could be related to the issue on macOS.

**Comment by p5ydn0** [comment]
So this function is not planned to improve? Telegram is really one of the very few software that still has this annoying function.

**Comment by antonakv** [comment]
@p5ydn0 There is the same approach as with Helm 3 package manager. They don't care if there is workaround. The style...

**Comment by Husterknupp** [comment]
@antonakv @p5ydn0 (and all the others who complain in this thread)


Stop whining. Have you tried writing up a fix and submitting a pull request?

I’m sorry that this app isn’t providing you with the expected value despite all the money that you have paid for being able to use it and have code insights

**Comment by p5ydn0** [comment]
> @antonakv @p5ydn0 (and all the others who complain in this thread)
> 
> Stop whining. Have you tried writing up a fix and submitting a pull request?
> 
> I’m sorry that this app isn’t providing you with the expected value despite all the money that you have paid for being able to use it and have code insights

Your logic is really strange.

According to what you mean, when anyone who uses a certain software encounters a certain problem or a function they do n’t like, they should shut up and write the code quietly to solve it? So if someone encounters a bug while using the software, and he doesn't program, he can just shut up and suffer?

One reason everyone complains is that we are using this software; since we are using this software, it means that we likes this software at least. Everyone discussing here is also making comments, hoping this software is getting better and better.

It's you, instead, saying something strange and useless.

**Comment by mxs42** [comment]
> @antonakv @p5ydn0 (and all the others who complain in this thread)
> 
> Stop whining. Have you tried writing up a fix and submitting a pull request?
> 
> I’m sorry that this app isn’t providing you with the expected value despite all the money that you have paid for being able to use it and have code insights

Clueless.
People report a problem with the app, it doesn't make any sense to talk about money in context of this topic. 
I didn't pay money to use Telegram but I still can report problems I encountered while using their service.
Telegram is not a someone's personal pet project, it is somewhat bigger and if Telegram want to compete with other solutions they have to take in account what their users say AND users can say whatever they find useful about Telegram, that's how you improve your software.

This issue in particular has a UX problem for some users so they report about it.

For future Windows users reading this topic:
One year ago I have created a tool to patch Telegram code to get rid of this taskbar flashing, you can find it in this repo https://github.com/mxs42/mutegram

**Comment by Aokromes** [comment]
> > @antonakv @p5ydn0 (and all the others who complain in this thread)
> > Stop whining. Have you tried writing up a fix and submitting a pull request?
> > I’m sorry that this app isn’t providing you with the expected value despite all the money that you have paid for being able to use it and have code insights
> 
> Clueless.
> People report a problem with the app, it doesn't make any sense to talk about money in context of this topic.
> I didn't pay money to use Telegram but I still can report problems I encountered while using their service.
> Telegram is not a someone's personal pet project, it is somewhat bigger and if Telegram want to compete with other solutions they have to take in account what their users say AND users can say whatever they find useful about Telegram, that's how you improve your software.
> 
> This issue in particular means that there is a UX problem for some users so they report about it.
> 
> For future Windows users reading this topic:
> Two years ago I have created a tool to patch Telegram code to get rid of this taskbar flashing, you can find it in this repo [mxs42/mutegram](https://github.com/mxs42/mutegram)

why instead make a tool you don't make a pull request to add the setting

**Comment by mxs42** [comment]
> why instead make a tool you don't make a pull request to add the setting

Because for me it was easier to make a tool and I never worked with QT.

**Comment by antonakv** [comment]
Yahooo!!!

**Comment by nesimtunc** [comment]
https://www.macworld.com/article/1138403/dockbounce.html
