### ISSUE TITLE
Telegram -autostart sometimes ignores the set scaling value and uses default (100%)

### ISSUE THREAD

**Issue by ShrirajHegde** [telegramdesktop/tdesktop#8970]
### Steps to reproduce
1. Place Telegram binaries in home folder and enable autostart in telegram
2. Set custom scaling other than 100%
3. Reboot and let telegram launch on startup

### Expected behaviour
Display scaling shouldn't get reset

### Actual behaviour
Display scaling gets reset to 100%

### Configuration
**Operating system:**
Ubuntu 20.04
**Version of Telegram Desktop:**
2.4.5 (I am a regular telegram user, and this appeared in 2.4.5 for sure)
**Installation source (Linux Only)** - the official website / GitHub releases / flatpak / snap / distribution package:
Official website (https://telegram.org/dl/desktop/linux)

**Used theme**:
Tinted (default night mode)
<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by ilya-fedin** [comment]
I can't reproduce, scaling doesn't reset for me...

**Comment by ShrirajHegde** [comment]
Okay, Let me check in subsequent updates

**Comment by ShrirajHegde** [comment]
For now adding 5 second sleep before executing ```Telegram -autostart``` seems to solve the problem

**Comment by ShrirajHegde** [comment]
> I can't reproduce, scaling doesn't reset for me...

Also,@ilya-fedin it doesn't actually **reset** the value, the launched process just ** ignores** the _set value_, relaunching solves the problem too. 


Let me rename the issue for now, in case someone else faces it

**Comment by ilya-fedin** [comment]
Wayland or Xorg?

**Comment by ShrirajHegde** [comment]
Xorg

**Comment by ilya-fedin** [comment]
Can't reproduce, at least with 125% scaling.

I will ask for sure: are you sure that you set the scaling and not the auto-observed value is used ("Default interface scale" will be enabled in that case)?

**Comment by ShrirajHegde** [comment]
On autostart :
![image](https://user-images.githubusercontent.com/66936172/97898993-ae19f480-1d5e-11eb-9a0c-5dc7a33045da.png)

Without touching anything, I use quit telegram from the tray, then relaunch telegram manually:

![image](https://user-images.githubusercontent.com/66936172/97899118-dc97cf80-1d5e-11eb-91cc-0858a5d9c714.png)


The same thing doesn't happen if I do `sleep 5 && Telegram -autostart`

**Comment by ilya-fedin** [comment]
Disable "Default interface scale" option, I guess your DE starts applications from autostart before it sets scaling (this is a DE issue then)

**Comment by ShrirajHegde** [comment]
Ok, let me try

**Comment by ShrirajHegde** [comment]
Unable to disable that option

(Once I disable it and go back to settings again, I see it enabled)

**Comment by ilya-fedin** [comment]
> Once I disable it and go back to settings again, I see it enabled

I can't reproduce that, it disables just fine for me

**Comment by ilya-fedin** [comment]
Well, I can reproduce that if I set non-100% scale system wide

**Comment by ilya-fedin** [comment]
Well, looks like this is a visual bug, it disables in the fact and that is visible after app restart

**Comment by ShrirajHegde** [comment]
> Well, I can reproduce that if I set non-100% scale system wide
It happens to me only on 125% scale, I think it is intended, What I suspect now is Gnome problem,just waiting 5 seconds solves the issue.

**Comment by ShrirajHegde** [comment]
> Well, looks like this is a visual bug, it disables in the fact and this is visible after app restart

I am unable to disable it for 125% at all, even after the app restarts.

**Comment by ilya-fedin** [comment]
> I am unable to disable it for 125% at all, even after the app restarts.

As you can see, I removed that post

**Comment by ilya-fedin** [comment]
Looks like I found an older report of this: https://github.com/telegramdesktop/tdesktop/issues/6773
