### ISSUE TITLE
[CRASH] Fast/Slow Video Scrolling Trouble

### ISSUE THREAD

**Issue by BlackYuzia** [telegramdesktop/tdesktop#8971]
### Steps to reproduce

1. Open any channel with too many videos
2. Scroll like crazy mon**key** :eyes:
    1. Scroll up
    2. Scroll down
    3. Then scroll up
    4. Then scroll down
3. Repeat scrolls...
4. Scroll on one position (fast down, fast up ,.., down, up but FAST)
5. Get crash.

### Crash IDs

e3694349-4726-441a-87dd-146297500fe9
1d0d9eb8-23fc-44b9-aa77-695617527191
e108965f-4abf-4419-8218-745ac6d0e7cd

### Expected behaviour

When I scroll videos desktop app shouldn't crash.

### Actual behaviour

When I scroll videos too fast or too many times (mb not) I get app crash.

### Configuration

**Operating system:** Win 7

**Version of Telegram Desktop:** 2.4.5

**Used theme**: Tested on default themes (the same bug exist)

**Comment by ilya-fedin** [comment]
#7361
