### ISSUE TITLE
[Feature Request]  Telegram desktop login with bot token

### ISSUE THREAD

**Issue by mktcockpit** [telegramdesktop/tdesktop#8972]
Any plans on telegram desktop login with bot token ?..

So that we can know who is using the bot in a more user-friendly interface, say we have bot hosted as per our requirement.. and we know many of bot subscribers are using it.. now to have more user-friendly interface if we get an option to log as a bot, it makes bot owner know what exactly users are facing issues while using it, or we will come to know the way we can improve...

**Comment by Aokromes** [comment]
if you mean login without phone number, nope, that doesn't belongs here. and i seriously doub it will be implemented.
