### ISSUE TITLE
Profile avatar disappears when sending group items

### ISSUE THREAD

**Issue by hookzof** [telegramdesktop/tdesktop#8974]
### Steps to reproduce
1. Add two any images and select group items (+compress):
![image](https://user-images.githubusercontent.com/22233835/97865127-c405c600-1d1a-11eb-9edd-756127e5e994.png)

2. Any or no caption

### Expected behaviour
Profile avatar should be displayed
![image](https://user-images.githubusercontent.com/22233835/97865461-4bebd000-1d1b-11eb-9684-e29baf2fc6d5.png)

### Actual behaviour
Profile avatar disappears
![image](https://user-images.githubusercontent.com/22233835/97865523-645bea80-1d1b-11eb-802b-c5e0db6b7a69.png)

### Configuration
**Operating system:** Windows 10 Pro ver. 2004

**Version of Telegram Desktop:** 2.4.6

**Used theme**: Dark (Tinted)

<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by john-preston** [comment]
It looks like those are outgoing messages in a group, why should they have profile avatar near them?

**Comment by hookzof** [comment]
When sending non-group items - avatar is shown 🤷‍♂️. If this was intended, then the issue has been resolved.

**Comment by john-preston** [comment]
hmm..

**Comment by john-preston** [comment]
@hookzof Can you show a full chat screenshot (with a bit wider window) of a non-group photo and a grouped photos. Because it look like I didn't understand how exactly I should reproduce the problem.

**Comment by hookzof** [comment]
> @hookzof Can you show a full chat screenshot (with a bit wider window) of a non-group photo and a grouped photos. Because it look like I didn't understand how exactly I should reproduce the problem.

1. The first message in this example is group items:
![image](https://user-images.githubusercontent.com/22233835/97875727-e3f1b580-1d2b-11eb-9ea0-3b2abd6f07f0.png)

2. Second example - non-group items first:
![image](https://user-images.githubusercontent.com/22233835/97875891-17344480-1d2c-11eb-9012-7a1e9f8beaea.png)
