### ISSUE TITLE
[Question] Why is it not possible to send images as photos (not files) uncompressed???

### ISSUE THREAD

**Issue by azat11** [telegramdesktop/tdesktop#8976]
No option to send photos saving the quality??

**Comment by Aokromes** [comment]
update to 2.4.6

**Comment by ilya-fedin** [comment]
> No option to send photos saving the quality??

Yeah, that always been this way: send as file == uncompressed, send as photo == compressed. If you send a file with the photo api, it will be compressed by the server in any way and you can't control that.

**Comment by dag7dev** [comment]
@ilya-fedin I guess you can safely close this.
