### ISSUE TITLE
Snap version of Telegram doesn't have media read/write permissions

### ISSUE THREAD

**Issue by asorel1942** [telegramdesktop/tdesktop#8977]
### Steps to reproduce
1. Attempt to save media in a custom location OR attempt to change default download location in settings

### Expected behaviour
Save location is picked through file browser and media is saved

### Actual behaviour
File browser gives error "Could not read the contents of media. Error opening directory 'media': Permission denied"

### Configuration
![image](https://user-images.githubusercontent.com/33983895/97907343-28248c00-1d13-11eb-96f6-ec98d1c3d7ef.png)

**Version of Telegram Desktop:**
2.4.5
**Installation source (Linux Only)** - the official website / GitHub releases / flatpak / snap / distribution package:
Snap.

**Used theme**:
Tinted.

<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by ilya-fedin** [comment]
> 2.4.5

Current latest version is 2.4.6
