### ISSUE TITLE
[Feature Request] More informative names of exported voice messages

### ISSUE THREAD

**Issue by viktor02** [telegramdesktop/tdesktop#8978]
### Is your feature request related to a problem?
When exporting data with a choice of voice messages (I have not tested other options), they are exported without any meaningful names other than the date. Voice messages of two interlocutors are indistinguishable from each other. I suggest naming not only by the date of the post, but also by the id of the speaker. In its current form, it looks like audio_1@02-11-2019_15-54-41.ogg, which is not very informative.

### Describe the solution you'd like
I suggest making the filenames like audio_1_id999999999@02-11-2019_15-54-41.ogg or something like that.

### Describe alternatives you've considered
Perhaps you can make separate folders for the dialogue participants, and the path will look like .\chats\chat_01\voice_messages\id111111111\audio_1@02-11-2019_15-54-41.ogg

### Additional context
What it looks like in its current form - voice messages of two interlocutors are indistinguishable from each other
![01513](https://user-images.githubusercontent.com/19672960/97906574-f7654680-1d54-11eb-8a52-56f7f66807d1.png)

How it can be improved. _In subfolders_ or _with more informative names_
![01514](https://user-images.githubusercontent.com/19672960/97906576-f7fddd00-1d54-11eb-84b9-7787db399c0c.png)

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/1359#issuecomment-590591567

**Comment by viktor02** [comment]
> 
> 
> [#1359 (comment)](https://github.com/telegramdesktop/tdesktop/issues/1359#issuecomment-590591567)

As I understand it, there is a little bit about something else, and his proposal has already been implemented
![01515](https://user-images.githubusercontent.com/19672960/97916607-4797d500-1d64-11eb-89c3-21b7f95197f5.png)

His suggestion is to put files in separate folders. My suggestion is to rename voice message files to readable names

**Comment by afwn90cj93201nixr2e1re** [comment]
@Aokromes should be opened as different.
