### ISSUE TITLE
Telegram on Linux opens PDFs in strictly Firefox

### ISSUE THREAD

**Issue by MicroDroid** [telegramdesktop/tdesktop#8981]
### Steps to reproduce
1. Click a PDF

### Expected behaviour
Telegram should open the PDF in Google Chrome, the default PDF viewer I have set.

### Actual behaviour
Telegram launches Firefox and presents the PDF there.

### Configuration

```
$ xdg-mime query default application/pdf
/usr/share/applications/google-chrome.desktop
```

**Operating system:** Arch Linux

**Version of Telegram Desktop:** 2.3.2

**Installation source (Linux Only)** - the official website / GitHub releases / flatpak / snap / distribution package: AUR

**Used theme**: Dark

<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/8982

**Comment by ilya-fedin** [comment]
`gio mime application/pdf`

**Comment by ilya-fedin** [comment]
> 2.3.2

Current latest version is 2.4.6

**Comment by MicroDroid** [comment]
@Aokromes For normal links, it's opening Chrome fine for me, plus:

```
$ xdg-settings get default-url-scheme-handler http
google-chrome.desktop
$ xdg-settings get default-url-scheme-handler https
google-chrome.desktop
```

@ilya-fedin Just updated to 2.4.4, the latest version at the AUR, the issue is still there.

**Comment by ilya-fedin** [comment]
> Just updated to 2.4.4, the latest version at the AUR, the issue is still there.

You can install latest version from desktop.telegram.org

**Comment by MicroDroid** [comment]
I'd rather with the AUR for updates, unless you're certain the issue is fixed at 2.4.6.

By the way:

```
$ gio mime application/pdf
Default application for “application/pdf”: google-chrome.desktop
Registered applications:
	google-chrome.desktop
	libreoffice-draw.desktop
	firefox-nightly.desktop
	...
Recommended applications:
	google-chrome.desktop
	libreoffice-draw.desktop
	firefox-nightly.desktop
	...
```

**Comment by ilya-fedin** [comment]
> I'd rather with the AUR for updates, unless you're certain the issue is fixed at 2.4.6.

Please check on the current latest version or the issue will be closed

**Comment by MicroDroid** [comment]
@ilya-fedin Clicking the download button at desktop.telegram.org takes me to `https://telegram.org/dl/desktop/linux` which downloads 2.4.5, is this fine to test against?

**Comment by ilya-fedin** [comment]
No, but it will offer you to update to 2.4.6 after you launch it.

**Comment by MicroDroid** [comment]
Seems to work fine on 2.4.6 :+1:
