### ISSUE TITLE
Links open in Firefox instead of Chrome (Linux)

### ISSUE THREAD

**Issue by LatinSuD** [telegramdesktop/tdesktop#8982]
### Steps to reproduce
1. Click on a link from a chat

### Expected behaviour
Link should open with default browser (Chrome)

### Actual behaviour
It opens with Firefox

### Configuration
**Operating system:**
Debian 10

**Version of Telegram Desktop:**
2.4.6

**Installation source (Linux Only)** - the official website / GitHub releases / flatpak / snap / distribution package:
From website (iirc)

**Comment by LatinSuD** [comment]
In my case I fixed it with these commands.

```
xdg-settings set default-url-scheme-handler http google-chrome.desktop
xdg-settings set default-url-scheme-handler https google-chrome.desktop

```

But I think there was a better fix, if you are using KDE. Go to System Settings -> Applications -> Web Browser and choose Chrome again.

**Comment by teo1978** [comment]
Why is this closed?

My default browser is Chrome and all other applications on my system except for Telegram open links in Chrome.

Yet Telegram insists in opening them in Firefox.

```
$ xdg-settings get default-web-browser 
google-chrome.desktop
$ xdg-settings get default-url-scheme-handler http
google-chrome.desktop
$ xdg-settings get default-url-scheme-handler https
google-chrome.desktop
```

**Comment by ilya-fedin** [comment]
> My default browser is Chrome and all other applications on my system except for Telegram open links in Chrome.

I'm definitely sure it is more than Telegram since that means that your system is misconfigured. You could try to open a link in any gtk app and most likely it will be opened in Firefox.

**Comment by szc126** [comment]
Remarkably (in a horrifying way), I have precisely the opposite problem, with links opening in Chromium instead of Firefox.

````
$ xdg-settings get default-web-browser
firefox.desktop
$ xdg-settings get default-url-scheme-handler http
firefox.desktop
$ xdg-settings get default-url-scheme-handler https
firefox.desktop
$ LANG=C update-alternatives --display gnome-www-browser
gnome-www-browser - auto mode
  link best version is /***/firefox
  link currently points to /***/firefox
  link gnome-www-browser is /usr/bin/gnome-www-browser
/***/firefox - priority 90
/usr/bin/chromium - priority 40
$ LANG=C update-alternatives --display x-www-browser
x-www-browser - auto mode
  link best version is /***/firefox
  link currently points to /***/firefox
  link x-www-browser is /usr/bin/x-www-browser
/***/firefox - priority 90
/usr/bin/chromium - priority 40
````

**Comment by 0cjs** [comment]
This should not be closed; I have the same issue in Debian 9 which started with a Telegram update in the last month or two, I believe. Both `sensible-browser` and `xdg-open` open links in `google-chrome-stable`; Telegram alone instead uses `chromium`.

```
$ xdg-settings get default-web-browser
google-chrome.desktop
$ xdg-settings get default-url-scheme-handler http
xdg-settings: default-url-scheme-handler not implemented for xfce
3 $ xdg-settings get default-url-scheme-handler https
xdg-settings: default-url-scheme-handler not implemented for xfce
3 $ update-alternatives --display x-www-browser
x-www-browser - auto mode
  link best version is /usr/bin/google-chrome-stable
  link currently points to /usr/bin/google-chrome-stable
  link x-www-browser is /usr/bin/x-www-browser
  slave x-www-browser.1.gz is /usr/share/man/man1/x-www-browser.1.gz
/usr/bin/chromium - priority 40
/usr/bin/firefox-esr - priority 70
  slave x-www-browser.1.gz: /usr/share/man/man1/firefox-esr.1.gz
/usr/bin/google-chrome-stable - priority 200
```
Removing the `chromium` package is a workaround; Telegram then starts opening links in chrome.
