### ISSUE TITLE
[Feature Request] Tabs like internet browsers for chats

### ISSUE THREAD

**Issue by axone13** [telegramdesktop/tdesktop#8983]
### Is your feature request related to a problem?
No.

### Describe the solution you'd like
It could be better to open chats in tabs like chrome and firefox. Sometimes we need two or more chats to be opened and this feature could be very useful.

### Describe alternatives you've considered
Have the ability to open two or more chats at the same time. Or keep chats open so we can switch between them.

**Comment by ilya-fedin** [comment]
#2897
