### ISSUE TITLE
Crash when capturing video from camera in latest release

### ISSUE THREAD

**Issue by SSDpreowner** [telegramdesktop/tdesktop#8984]
### Steps to reproduce
It crashes immediately after opening camera. When I press a camera icon in a call or open a "call settings" dialog.

### Configuration
**Operating system:** Windows 10

**Version of Telegram Desktop:** 2.4.5-2.4.6 (the release 2.4.4 works fine)

There is nothing in the logs. It crashes momentarily not leaving any sign of failure in logs.

**Comment by Izumiko** [comment]
I have the same issue.

**Comment by SSDpreowner** [comment]
This seems to be fixed in 2.4.7. What was that? I don't see a commit fixing the issue in the history. But whatever.

**Comment by john-preston** [comment]
@SSDpreowner ABI incompatibility, I didn't rebuild tg_owt library when moved to mozjpeg from libjpeg.
