### ISSUE TITLE
telegram crash when i open call setitngs

### ISSUE THREAD

**Issue by haikosan** [telegramdesktop/tdesktop#8985]
### Steps to reproduce
1. Settings
2. Advanced
3. Call Settings

### Expected behaviour
Tell us what should happen
to open call settings, I want to choose different input device
### Actual behaviour
Tell us what happens instead
when I open the call settings the app close without errors, just crash
### Configuration
**Operating system:**
Windows 10
**Version of Telegram Desktop:**
2.4.6
**Installation source (Linux Only)** - the official website / GitHub releases / flatpak / snap / distribution package:

**Used theme**:
Night
<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by ilya-fedin** [comment]
#8984
