### ISSUE TITLE
Linux build error: opus fail to linking to tg_owt?

### ISSUE THREAD

**Issue by c0re100** [telegramdesktop/tdesktop#8986]
It's only happening with tdesktop 2.4.6, and no problem with 2.4.4.
I even tried to use docker build, but noluck, failed too :(

error logs:
```
/usr/src/Libraries/tg_owt/out/Release/libtg_owt.a(opus_interface.cc.o): In function `DecodeNative(WebRtcOpusDecInst*, unsigned char const*, unsigned long, int, short*, short*, int)':
opus_interface.cc:(.text+0x80): undefined reference to `opus_multistream_decode'
/usr/src/Libraries/tg_owt/out/Release/libtg_owt.a(opus_interface.cc.o): In function `WebRtcOpus_DecoderFree':
opus_interface.cc:(.text+0xa82): undefined reference to `opus_multistream_decoder_destroy'
/usr/src/Libraries/tg_owt/out/Release/libtg_owt.a(opus_interface.cc.o): In function `WebRtcOpus_DecoderInit':
opus_interface.cc:(.text+0xae4): undefined reference to `opus_multistream_decoder_ctl'
/usr/src/Libraries/tg_owt/out/Release/libtg_owt.a(opus_interface.cc.o): In function `WebRtcOpus_MultistreamDecoderCreate':
opus_interface.cc:(.text+0xf88): undefined reference to `opus_multistream_decoder_create'
opus_interface.cc:(.text+0x10c4): undefined reference to `opus_multistream_decoder_destroy'
collect2: error: ld returned 1 exit status
gmake[2]: *** [Telegram/CMakeFiles/Telegram.dir/build.make:8064: bin/Telegram] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:2249: Telegram/CMakeFiles/Telegram.dir/all] Error 2
gmake: *** [Makefile:104: all] Error 2
```

**Comment by ilya-fedin** [comment]
Hmm, the same error is magically appeared in action, while seems that @john-preston is able to build without any issue. Can't figure out why it happens.

**Comment by Gerrrard** [comment]
Maybe this error is somehow connected to the issue. Got it few days ago.

`[ 51%] Linking CXX static library liblib_tgcalls.a[ 51%] Built target lib_tgcalls
[ 52%] Built target lib_tgcalls_legacy
[ 52%] Automatic MOC for target Telegram
[ 52%] Built target Telegram_autogen
make[2]: *** No rule to make target `/home/mikado/Desktop/td/Libraries/tg_owt/out/Release/libtg_owt.a', needed by `bin/Telegram'.  Stop.
make[1]: *** [Telegram/CMakeFiles/Telegram.dir/all] Error 2
make: *** [all] Error 2
`

**Comment by ilya-fedin** [comment]
@Gerrrard no, you just didn't build tg_owt (or built on wrong path)

**Comment by Gerrrard** [comment]
Well, now I have same error, but one line before that logs

/home/mikado/Desktop/td/Libraries/ffmpeg/libavcodec/libavcodec.a(mpegvideo.o): In function `memset':
/usr/include/x86_64-linux-gnu/bits/string3.h:81: warning: memset used with constant zero length parameter; this could be due to transposed parameters

**Comment by john-preston** [comment]
@Gerrrard You can fix this by adding:

![image](https://user-images.githubusercontent.com/17900494/98235551-645a2580-1f7b-11eb-8e90-d21ea9ce3a53.png)

In tdesktop/cmake.

**Comment by c0re100** [comment]
> @Gerrrard You can fix this by adding:
> 
> ![image](https://user-images.githubusercontent.com/17900494/98235551-645a2580-1f7b-11eb-8e90-d21ea9ce3a53.png)
> 
> In tdesktop/cmake.

Thanks!!
