### ISSUE TITLE
connectivity problem since 2.4.5 on linux mint 20

### ISSUE THREAD

**Issue by freemangilgamesh** [telegramdesktop/tdesktop#8987]
since version 2.4.5  telegram desktop is slow to connect at startup and even after

**Comment by ilya-fedin** [comment]
If you downgrade to 2.4.4, will the issue disappear?

**Comment by freemangilgamesh** [comment]
yes

**Comment by freemangilgamesh** [comment]
problem persists

**Comment by Aokromes** [comment]
try on 2.4.8
