### ISSUE TITLE
Telegram closes randomly when typing accented keys or double quotes

### ISSUE THREAD

**Issue by PeGa** [telegramdesktop/tdesktop#899]
Using telegram desktop binary on Gentoo GNU/Linux, with keyboard US International.

Sometimes typing accented keys sometimes (with no reproducible pattern) closes telegram with no error. 

Besides of being extremely annoying, the issue cannot be reproducible, because typing randomly accented characters combining with space and caps or shift doesn't close telegram. It just does it in the middle or beginning of a message, without any evident key combination to be found guilty of this behavior.

Thanks.

**Comment by Aokromes** [comment]
I suggest you to compile telegram on debug mode and run gdb to get proper crashlog.

**Comment by auchri** [comment]
Is this still happening?

**Comment by dansouza** [comment]
I can confirm this happens here on my setup - Telegram Desktop 0.9.18 on Linux. Sometimes I'll be typing a message and include a double-quote (") and Telegram will crash. After I restart it (and it partially recovers the message I was typing after the crash) typing " again won't crash it.

I have my keyboard set as "English (US International with dead keys)" on XFCE (Ubuntu 15.10).

I can try and get a crashlog if I can download and use a debug-enabled Telegram binary, let me know.

**Comment by pozzifante** [comment]
This happens to me too, on version 0.9.18, I'm using the UK extended keyboard layout on Debian, so i input the accented keys by pressing ` followed by the letter I want to accent. Telegram crashes after the second key is pressed.

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/1074 I sugest you to post there if it's the same issue.
