### ISSUE TITLE
Could not find static library libbreakpad_client.a 

### ISSUE THREAD

**Issue by ahmedalsaadi17** [telegramdesktop/tdesktop#8990]
![Screenshot from 2020-11-04 06-14-31](https://user-images.githubusercontent.com/73148531/98104903-1a7f1b80-1e65-11eb-957a-568337d8e78d.png)

I had this message during building telegram on ubuntu

**Comment by ilya-fedin** [comment]
Did you build breakpad successfully by the instruction?

**Comment by ahmedalsaadi17** [comment]
Yes it was built successfully

**Comment by ilya-fedin** [comment]
Looks like this is false

**Comment by ahmedalsaadi17** [comment]
What should I do?

**Comment by ilya-fedin** [comment]
You should check if /usr/local/lib/libbreakpad_client.a exist, if not, then it wasn't built successfully

**Comment by ahmedalsaadi17** [comment]
I didn't find it

**Comment by ilya-fedin** [comment]
So, breakpad wasn't built sucessfully

**Comment by ahmedalsaadi17** [comment]
How to build breakpad?

**Comment by ilya-fedin** [comment]
This was a part of the instruction. Looks like you didn't follow it carefully, again.

**Comment by ahmedalsaadi17** [comment]
I did the build more the three times to solve a lot of errors, I followed all instruction but I installed ubuntu 20.04 that's the only thing that's different than instruction.

**Comment by ilya-fedin** [comment]
The instruction is only for Ubuntu 14.04, you can't build tdesktop on any other Ubuntu version, it has strongly dependency on libraries versions and paths.

**Comment by ahmedalsaadi17** [comment]
Maybe, that's the problem why I had a lot of errors previously. But Do you advice me to install Ubuntu 14.04?

**Comment by ilya-fedin** [comment]
> But Do you advice me to install Ubuntu 14.04?

Yes, you must install it in order to build tdesktop
