### ISSUE TITLE
cmake_minimum_required:   CMake 3.16 or higher is required.  You are running version 2.8.12.2

### ISSUE THREAD

**Issue by ahmedalsaadi17** [telegramdesktop/tdesktop#8993]
![Screenshot (8)](https://user-images.githubusercontent.com/73148531/98191186-ab4a0b80-1ee6-11eb-88c3-6874556a7669.png)

**Comment by ahmedalsaadi17** [comment]
What should I do?

**Comment by Johnnynator** [comment]
Upate to a newer cmake version ofc.

**Comment by ilya-fedin** [comment]
> What should I do?

I don't understand how you reading the instruction, I want to say that tdesktop building is not what you able to do at this point.
![image](https://user-images.githubusercontent.com/17829319/98258284-961dbd00-1f78-11eb-8b5a-15bcae2ef14d.png)
