### ISSUE TITLE
Crash when selecting many files

### ISSUE THREAD

**Issue by Neurotoxin001** [telegramdesktop/tdesktop#8994]
### Steps to reproduce
1. Select 1000+ photos/videos and drop them into the "saved messages" for example
2. Wait until they "count" in upload box
3. After ~300 files counting will start rewind very fast and then crash

Crash id:
2bb9426a-7d07-4c75-8b60-3f649f7d65b6
5c8acce0-2817-4101-b3c3-e120014e9742
95ff79e4-6ddf-4ed3-a16d-3a955c75cc36

### Configuration
**Operating system:** win 10 ltsc 1809

**Version of Telegram Desktop:** 2.4.6

**Used theme**: dark default

**Comment by ilya-fedin** [comment]
#8364

**Comment by Neurotoxin001** [comment]
#8364 is created before https://github.com/telegramdesktop/tdesktop/commit/86612f0a677d1fe9e9bfb06bd819f8cc13779545

**Comment by ilya-fedin** [comment]
> #8364 is created before [86612f0](https://github.com/telegramdesktop/tdesktop/commit/86612f0a677d1fe9e9bfb06bd819f8cc13779545)

And? It is still an Out-Of-Memory crash, I guess

**Comment by c0re100** [comment]
> > #8364 is created before [86612f0](https://github.com/telegramdesktop/tdesktop/commit/86612f0a677d1fe9e9bfb06bd819f8cc13779545)
> 
> And? It is still an Out-Of-Memory crash, I guess

Yes. It's OOM crash.
I tried to upload 33 video, and tdesktop memory reach to >1.5GB and crash.
