### ISSUE TITLE
[Feature Request] please add screenshot

### ISSUE THREAD

**Issue by ykla** [telegramdesktop/tdesktop#8995]
Please add screenshot for telegram-desktop.

**Comment by ilya-fedin** [comment]
What?

**Comment by ykla** [comment]
Take a screen shot.

**Comment by ilya-fedin** [comment]
Elaborate please

**Comment by ykla** [comment]
I want to add the function of screenshots, and use the mouse to freely take screenshots of the content on the screen.

**Comment by ilya-fedin** [comment]
Well, you have tons of screenshot apps

**Comment by ykla** [comment]
Not easy to take a screenshot on linux or FreeBSD.

**Comment by ilya-fedin** [comment]
This is not a tdesktop problem, sorry

**Comment by Aokromes** [comment]
use print screen.
