### ISSUE TITLE
How to decrease the release package size of Telegram

### ISSUE THREAD

**Issue by qiu198022** [telegramdesktop/tdesktop#8996]
I have compile the telegram successfully by the xcode 11.3 on the Mac. Finally the release package size is 242M and my debug package is more than 1G. But I found the office releasing package of Mac is only 80M. How can I decrease the release package size of Telegram?
![屏幕快照 2020-11-05 下午6 30 11](https://user-images.githubusercontent.com/51344/98229558-06d2d280-1f95-11eb-8ee3-80e323cd5a2a.png)

**Comment by john-preston** [comment]
You can `strip` the `Telegram.app/Contents/MacOS/Telegram` binary and then sign it again.

**Comment by ilya-fedin** [comment]
> How can I decrease the release package size of Telegram?

Official builds use LTO: https://github.com/desktop-app/cmake_helpers/blob/a7e73ebc036fdf32cdca56b62405bf9dcd8f8f09/init_target.cmake#L42-L47
