### ISSUE TITLE
Sending picture menu diappeared

### ISSUE THREAD

**Issue by GladilovDmitry** [telegramdesktop/tdesktop#8998]
1) Make PrtScn
2) press ctrl+v
Earlier there appeared a choice: send as a file/ send as a picture
Now there`s no choice, but switch compress/not compress. If not compress - screen sghot will be send as a file.
It is absolutely unconvenient and not obsious behavior of the program.

**Comment by john-preston** [comment]
@GladilovDmitry This is absolutely the same option, just instead of two radiobuttons there is one checkbox.
