### ISSUE TITLE
Window size and position are not remembered correctly after Snapping

### ISSUE THREAD

**Issue by Dahgoth** [telegramdesktop/tdesktop#8999]
### Steps to reproduce
1. Snap windows to the side either via drag'n'drop window to the edge of the screen or hotkeys (default Win+Arrow(s))
2. Minimize or Close to system tray
3. Open by clicking an icon in system tray

### Expected behaviour
Should remember snaped size and position

### Actual behaviour
Restores previos state before snapping

### Temp work-around
1. Snap window
2. Quit Telegram via right-click tray icon
3. Re-launch

### Configuration
**Operating system:**
Windows 10 version 2004 build 19041.450

**Version of Telegram Desktop:**
2.4.7 from Microsoft Store

**Used theme**:
Default Night theme

Same issues was #1693 and #4475

**Comment by ilya-fedin** [comment]
Well, just like you mentioned, duplicate of #1693

**Comment by ilya-fedin** [comment]
I can reproduce this with any other Qt application (qBittorrent for example), this is a Qt bug

**Comment by ilya-fedin** [comment]
Found a Qt report: https://bugreports.qt.io/browse/QTBUG-59668
