### ISSUE TITLE
[Feature Request] Option to alter "close telegram" behavior for the main window. 

### ISSUE THREAD

**Issue by frenchiveruti** [telegramdesktop/tdesktop#9000]
### Is your feature request related to a problem?
No sir.

### Describe the solution you'd like
I'd like to have a toggleable option to be able to "minimize to tray" and "close on close" so when the user "Closes" telegram pressing the X, telegram doesn't go into the tray but instead closes completely, and if the uses minimizes telegram, telegram goes into the tray.

### Describe alternatives you've considered
Does not apply.

### Additional context
Right now telegram only has "close to tray" and "minimize to taskbar"

**Comment by ilya-fedin** [comment]
#8941

**Comment by frenchiveruti** [comment]
Thanks, I'll close this one.
