### ISSUE TITLE
"@gif" shortcut no longer working?

### ISSUE THREAD

**Issue by til-jmac** [telegramdesktop/tdesktop#9008]
I'm using version 2.4.7 of this Desktop app, and I'm no longer able to use the @gif shortcut in the text bar to search for GIFs. 

Has this been removed or is it a problem with my install? I can still get to a gif search by clicking on the emoji icon and the gifs tab.

**Comment by ilya-fedin** [comment]
gif is a bot, working on servers, you filed an issue for a client...

**Comment by til-jmac** [comment]
Aha, got it, thanks for pointing me in the right direction
