### ISSUE TITLE
Add --help command line parameter

### ISSUE THREAD

**Issue by hashworks** [telegramdesktop/tdesktop#901]
Currently there is no way to get an overview of parameters like "-startintray".

**Comment by hashworks** [comment]
This is still an issue.

**Comment by ilya-fedin** [comment]
I think the help is not needed as tdesktop doesn't really have user-facing arguments. Even -startintray is not supposed to be used, the checkbox in settings should be used instead.

**Comment by hashworks** [comment]
While this is of course your call, I would say that even an "empty" `--help` response holds information value. When users get a "there are no options beside `-startintray`, and you shouldn't use that" response, they know they don't need to look further. Without any `--help` option they're just confused.

**Comment by ilya-fedin** [comment]
tdesktop is a GUI application, why should it have `--help`? It won't work on Windows anyway
