### ISSUE TITLE
[Feature Request] Option to require 2FA password for clearing any chats / deleting groups,channels.

### ISSUE THREAD

**Issue by ShrirajHegde** [telegramdesktop/tdesktop#9011]
### Is your feature request related to a problem?
In telegram android, it is somewhat easy to accidentally click on clear chat and mindlessly/accidentally clicking confirm

### Describe the solution you'd like
Ability to either undo the clean up to a certain amount of time (1hr /1 day) or requiring 2FA password if added 

### Describe alternatives you've considered
ability to undo until a time/something to prevent just two misclicks from happening (maybe typing clear or confirm) or ability to turn on any of these protections in settings

**Comment by ilya-fedin** [comment]
> In telegram android,

This bugtracker is only for telegram desktop
