### ISSUE TITLE
Thumbnail of uploaded PDF files.

### ISSUE THREAD

**Issue by vangquan** [telegramdesktop/tdesktop#9014]
Pictures link: https://imgur.com/a/YUmJZ0C

Thumbnail of uploaded PDF files.

**Problem:**
- Telegram for macOS and iOS/iPadOS allow you to upload PDF files with a preview pictures (thumbnail-like) of the content of that PDF file. That preview picture is seeable on Telegram for Android, Telegram Web, Telegram React, Telegram Desktop, and the Telegram for macOS and iOS/iPadOS.
- But if you use Telegram Desktop to upload those PDF files, you just see a dull icon.

**Request:**
- Allow all the Telegram client to upload PDF files with thumbnails the way Telegram for MacOS and Telegram for iOS/iPadOS do.

**Comment by ilya-fedin** [comment]
Qt's PDF plugin is a part of QtWebEngine: https://github.com/qt/qtwebengine/blob/dev/src/plugins/imageformats/pdf/qpdfiohandler.cpp
Since QtWebEngine couldn't be built statically, this is not possible, unfortunately.

**Comment by magnus-gross** [comment]
BTW the code for this is already place in Telegram Desktop, so if you use a dynamically linked Telegram Desktop, this feature already works: 
![Screenshot_20201108_132516](https://user-images.githubusercontent.com/21310755/98464866-ff464000-21c5-11eb-9d29-50746d992dca.png)

This pdf was sent from Telegram Desktop in the Arch Linux repositories with qt5-webengine installed on the system.

Regardless of the problem of statically bundling QtWebengine, i think it is safe to say that it is utter nonsense to bundle the huge QtWebengine module with any bundled Telegram Desktop release just for this small feature. Imagine using Qt to avoid the huge Electron footprint just to end up bundling Chromium anyway. :P

**Comment by ilya-fedin** [comment]
> i think it is safe to say that it is utter nonsense to bundle the huge QtWebengine module with any bundled Telegram Desktop release just for this small feature. I

If it is were possible to link QtWebEngine statically, it is would be possible to implement a lot of features, like instant view: https://github.com/telegramdesktop/tdesktop/issues/3492

**Comment by Aokromes** [comment]
i have got one pdf on my telegram desktop (windows, official build) and already shows thumbnail.

**Comment by vangquan** [comment]
Thanks for your information. Currently, to have this feature, I can use:
* Telegram for macOS (https://macos.telegram.org)
* Unigram for Windows (https://github.com/UnigramDev/Unigram)
* Telegram Desktop on Linux with Qt WebEngine as vimposter said https://github.com/telegramdesktop/tdesktop/issues/9014#issuecomment-723570928
* Telegram for iOS/iPadOS
* no ways on Android and ChromeOS
