### ISSUE TITLE
[Feature Request] Being able to mark a folder as default, so that Telegram always starts with it open

### ISSUE THREAD

**Issue by dlight** [telegramdesktop/tdesktop#9015]
### Is your feature request related to a problem?

I often don't notice that Telegram starts with the "All chats" open. I have to click my preferred default folder every time I open the app (on both desktop and mobile)

### Describe the solution you'd like

I would like to select a "Make this the default folder when Telegram starts" option in one of my folders. Only one folder can have it. Removing this option reverts the "All chats" the default.

### Describe alternatives you've considered

An alternative is to have a setting to always open the last opened folder when restarting Telegram. That way, the starting folder depends on what you had selected when you closed the app.

### Additional context

Expanding on this theme, it would be nice if "All chats" could be treated more like a special folder that can't be deleted. For example, this would enable dragging from the top, etc. But this is not a prerequisite for this feature.

**Comment by ilya-fedin** [comment]
#7533

**Comment by dlight** [comment]
Okay, this is a duplicate! Closing.
