### ISSUE TITLE
[Question] How to create more folders than the folder limit?

### ISSUE THREAD

**Issue by dlight** [telegramdesktop/tdesktop#9016]
I'm getting the "Sorry, you can't create more folders" message when I try to have more than 10 folders. It would be nice if the limit were raised to 20 or more.

But failing that, is there some hidden setting that enables creating more folders? On telegram-desktop specifically.

Would this require recompiling Telegram?

**Comment by ilya-fedin** [comment]
You can't, this is a server-side limit

**Comment by dlight** [comment]
Okay so.. consider this a feature request to increase the limit to at least 20 please!

**Comment by ilya-fedin** [comment]
@dlight server developers don't read client issues and no one forwards issue to them

**Comment by M299792458** [comment]
No way, as @ilya-fedin said, to reach them through this tracker. 
Try talking with Telegram in Twitter, or with the in-app support through:
_Settings --> ask a question --> proceed to the volunteers._
To be honest with you, they don't answer (in my experience, they never did), but try your luck. ¯\_(ツ)_/¯
There is no other way, as far as I know.
