### ISSUE TITLE
[Feature Request] Saving Profile Video as mp4

### ISSUE THREAD

**Issue by AhyaH-YHWH** [telegramdesktop/tdesktop#9017]
When trying to save a Profile Video
Telegram 2.4.7 Windows, save a JPG of its cover instead

Please save Profile video as mp4 files
Thanks.

(Probably Copying a screenshot of Photo or something like that, 
instead of decrypting local video file, for profile video)

**Comment by Neurotoxin001** [comment]
https://github.com/telegramdesktop/tdesktop/issues/8304
