### ISSUE TITLE
Yet another snap bug: attachments are not working

### ISSUE THREAD

**Issue by matkoniecz** [telegramdesktop/tdesktop#9018]
### Steps to reproduce
1. have account with at least one channel
2.   `sudo snap install telegram-desktop` on Linux
3. go through login process
4.  select channel
5. select attachment icon

### Expected behaviour
You can select an attachment to attach

### Actual behaviour
Nothing whatsoever

### Configuration
**Operating system:** 20.04

**Version of Telegram Desktop:** 2.4.7

**Installation source (Linux Only)** - the official website / GitHub releases / flatpak / snap / distribution package: snap

**Used theme**: default

<details><summary><b>Logs from terminal where Telegram was started</b>:</summary>

```
You can disable tray icon counter with TDESKTOP_DISABLE_TRAY_COUNTER and make it look better if it is monochrome.
error: : cannot open
error: : cannot open
error: : cannot open
propsReply "An AppArmor policy prevents this sender from sending this message to this recipient; type=\"method_call\", sender=\":1.256\" (uid=1000 pid=49473 comm=\"telegram-desktop \" label=\"snap.telegram-desktop.telegram-desktop (enforce)\") interface=\"org.freedesktop.DBus.Properties\" member=\"GetAll\" error name=\"(unset)\" requested_reply=\"0\" destination=\"org.freedesktop.NetworkManager\" (uid=0 pid=862 comm=\"/usr/sbin/NetworkManager --no-daemon \" label=\"unconfined\")"
nmReply "An AppArmor policy prevents this sender from sending this message to this recipient; type=\"method_call\", sender=\":1.256\" (uid=1000 pid=49473 comm=\"telegram-desktop \" label=\"snap.telegram-desktop.telegram-desktop (enforce)\") interface=\"org.freedesktop.NetworkManager\" member=\"GetDevices\" error name=\"(unset)\" requested_reply=\"0\" destination=\"org.freedesktop.NetworkManager\" (uid=0 pid=862 comm=\"/usr/sbin/NetworkManager --no-daemon \" label=\"unconfined\")"
"Object path cannot be empty"
```

</details>

**Comment by ilya-fedin** [comment]
You should have xdg-dekstop-portal and one of: xdg-desktop-portal-gtk/xdg-desktop-portal-kde installed

**Comment by matkoniecz** [comment]
> You should have xdg-dekstop-portal and one of: xdg-desktop-portal-gtk/xdg-desktop-portal-kde installed

Snap install should install its dependencies, the whole point of such software is to avoid manual dependency handling by users.

Flatpak install works fine.

**Comment by ilya-fedin** [comment]
> Snap install should install its dependencies

Sandbox doesn't allow installing packages on user's system

**Comment by ilya-fedin** [comment]
> Flatpak install works fine.

flatpak packages won't work without portals as well...

**Comment by matkoniecz** [comment]
> Sandbox doesn't allow installing packages on user's system

If snap cannot be made to work in sane way then it should not be listed as valid install option.

Or at least problem should be mentioned in https://github.com/telegramdesktop/tdesktop#supported-systems or https://snapcraft.io/telegram-desktop or on attempt to use this broken functionality

> flatpak packages won't work without portals as well...

I followed Snap install instruction, it is not capable of using attachments and no error with an explanation is provided.

I followed Flatpak install instruction, it is capable of using attachments.

(I would be even happier about simply using PPA, but Flatpak at least works for now while Snap is broken again...)

**Comment by ilya-fedin** [comment]
If snapd doesn't install xdg-desktop-portal with it, it is snapd problem, we can't fix snapd or its packaging

**Comment by ilya-fedin** [comment]
> I followed Snap install instruction, it is not capable of using attachments and no error with an explanation is provided.
> 
> I followed Flatpak install instruction, it is capable of using attachments.

If you want just blaming instead of being constructive, then I think the issue could be closed

**Comment by matkoniecz** [comment]
> If snapd doesn't install xdg-desktop-portal with it, it's snapd problem, we can't fix snapd or its packaging

Snap can be removed from recommended install methods or have some warning that it is broken due to upstream deficiencies.

**Comment by ilya-fedin** [comment]
@Aokromes close this nonconstructive issue please

**Comment by matkoniecz** [comment]
If you consider bug reports as nonconstructive I can close it on my own.
