### ISSUE TITLE
[Feature Request] User dropdown to help mentioning when uploading a file

### ISSUE THREAD

**Issue by Laiteux** [telegramdesktop/tdesktop#9020]
### Is your feature request related to a problem?
When uploading something in a group, a popup shows up where you can add a caption.

However, writing an `@` won't show the list of members like it would do in the "normal" message bar, which makes you basically having to mention BEFORE attaching a file/photo/whatever, unless you know someone's username by heart and can manually type it.

![](https://share.laiteux.dev/hurdrrnn)

### Describe the solution you'd like
It would be really nice to have a dropdown with the list of users, like when you would write an `@` in the usual text bar.

![](https://share.laiteux.dev/qthbfjey)

**Comment by Aokromes** [comment]
i think this must be api side.

**Comment by Laiteux** [comment]
Hey, no request is sent when entering an `@` in the usual message box, I strongly believe mentions are stored locally which means they basically could be used anywhere. All we should need to be added is a dropdown to the file upload caption input.

**Comment by RememberTheAir** [comment]
un-stale

**Comment by Laiteux** [comment]
🤞

**Comment by php4fan** [comment]
Still an issue 2 years later, pathetic.

**Comment by Laiteux** [comment]
Not pathetic but would be great, yeah. Would probably be an easy add for @john-preston too argh

**Comment by Laiteux** [comment]
There we go it seems like

![image](https://github.com/user-attachments/assets/4945b051-5798-450a-9888-e4336adfbdd3)
