### ISSUE TITLE
Freetype mode always uses RGB subpixel antialiasing on Windows

### ISSUE THREAD

**Issue by gfody** [telegramdesktop/tdesktop#9021]
### Steps to reproduce
1. disable Cleartype in Windows (run the Cleartype wizard (cttune.exe) and uncheck the box labeled "Turn on ClearType" - the setting takes effect immediately, you don't have to complete the wizard)
2. enable Freetype mode in Telegram (type "freetype" into the settings dialog, or create a file in the tdata folder named "withfreetype" with contents "1")

### Expected behaviour
expected Telegram to render text using grayscale antialiasing

### Actual behaviour
Telegram renders text using RGB subpixel antialiasing

### Configuration
**Operating system:** Windows 10 (Version 2004, Build 19041.572)

**Version of Telegram Desktop:** 2.4.7

**Used theme**: Tinted, Night mode

fwiw adding this line to `lib_ui/ui/style/style_core_font.cpp` looks good to me (my monitor's subpixel layout isn't RGB or BGR so I only attest to quality of grayscale):
```diff
	auto appFont = QApplication::font();
	appFont.setStyleStrategy(QFont::PreferQuality);
+	appFont.setStyleStrategy(QFont::NoSubpixelAntialias);
	QApplication::setFont(appFont);
```

possibly related QT bugs: [QTBUG-49428](https://bugreports.qt.io/browse/QTBUG-49428), [QTBUG-88225](https://bugreports.qt.io/browse/QTBUG-88225)

**Comment by ilya-fedin** [comment]
FreeType mode is only for developers to debug font bugs. That's why it is a cheat code, after all. Sorry, but I don't think overriding Qt defaults is a good idea, it is better to leave it as is to allow Qt autodetect user preferences, otherwise a lot of users will start complaining.

**Comment by gfody** [comment]
ah I thought freetype mode might've been destined to become the new default in the future.
agree it's better that they fix this in Qt if this is a Qt issue - it looks like it's QTBUG-49428 there's a patch in the comments that sets the subpixel layout based on the registry setting.

**Comment by ilya-fedin** [comment]
> ah I thought freetype mode might've been destined to become the new default in the future.

No way that Windows users accept the Linux font rendering engine :D
