### ISSUE TITLE
Telegram desktop crash upon selecting a TIFF file to be sent

### ISSUE THREAD

**Issue by apenpixel** [telegramdesktop/tdesktop#9023]
### Steps to reproduce
1. Select TIFF file to be sent
2. CRASH

### Expected behaviour
Select TIFF file, the preview window opens allowing me to compress it or not.

### Actual behaviour
The following crash:
Telegram: tif_jpeg.c:1017: JPEGSetupDecode: Assertion `sp->cinfo.comm.is_decompressor' failed.
Aborted

### Configuration
Debian bullseye/sid 
Telegram desktop app v.2.4.7 (xz archive dowloaded from https://desktop.telegram.org)
Night theme

**Comment by Aokromes** [comment]
plz next time you have a crash plz post crash id here.

**Comment by apenpixel** [comment]
I found out how to supposedly send the crash report (by installing the beta version, right?). Trouble is that when i re-launch the app i only see a windows briefly popping up and then nothing else. Sorry.

**Comment by Aokromes** [comment]
try to run it under gdb.

**Comment by ilya-fedin** [comment]
But official binaries aren't linked to libtiff, how that could be?

**Comment by ilya-fedin** [comment]
I just checked with 2.4.7 from desktop.telegram.org and tiff successfully sends as a file

**Comment by apenpixel** [comment]
I agree there shouldn't be, the problematic file is a 2.6MB 4000x7200px TIFF which has been generated by xsane-0.999. What else can i do to improve this bug report?

I have little experience with building/compiling applications and running GDB but i can try if https://github.com/telegramdesktop/tdesktop/blob/dev/docs/building-cmake.md is still somewhat valid (says it's outdated).

**Comment by Aokromes** [comment]
can you attach the tiff file here?

**Comment by apenpixel** [comment]
There you go: it is redacted but it still manages to crash my
[crashfile.tiff.zip](https://github.com/telegramdesktop/tdesktop/files/5540383/crashfile.tiff.zip)
 tdesktop.

**Comment by Aokromes** [comment]
https://i.imgur.com/6as4zAm.png no crash for me on windows 10...

**Comment by apenpixel** [comment]
I said Debian bullseye/sid...

**Comment by Aokromes** [comment]
yes,, ik you said debian, but at least on windows it doesn't crashes for me.

**Comment by ilya-fedin** [comment]
> I said Debian bullseye/sid...

Can't reproduce on Lniux either. I assume you're using some third-party build of tdesktop, since official builds are built without libtiff and such crash just impossible even in theory.

**Comment by apenpixel** [comment]
Nope, no third party crap here. I guess it must be a DE problem then. Thank you for your time
