### ISSUE TITLE
Telegram opens links in Firefox, despite default browser being Chrome

### ISSUE THREAD

**Issue by teo1978** [telegramdesktop/tdesktop#9024]
### Steps to reproduce
1. Click on a url in a messge in Telegram Desktop

### Expected behaviour
Should open the link in the default browser.
My default browser is Chrome. All applications in my system open links in Chrome except Telegram.

### Actual behaviour
Opens the link in Firefox.

I have searched the settings in Telegram and I can't find one for what browser to use as default.

### Configuration
**Operating system:**

OpenSUSE Linux

**Version of Telegram Desktop:**

2.4.7

**Installation source (Linux Only)** - the official website

**Comment by ilya-fedin** [comment]
#8982
