### ISSUE TITLE
Unable to send pictures while I could only send them in files in .exe version 2.4.7

### ISSUE THREAD

**Issue by hereMK** [telegramdesktop/tdesktop#9026]
### Steps to reproduce
1. copy and paste a photo in telegram Windows .exe version
2. Unable to send pictures while I could only send in files
3. I also tested in telegram UWP version 2.4.7

### Expected behaviour
Tell us what should happen
The photos should be sent as photos instead of files 
### Actual behaviour
Tell us what happens instead
The photos were sent as files 
### Configuration
**Operating system:**
windows 10 20H2
**Version of Telegram Desktop:**
.exe version 2.4.7
**Installation source (Linux Only)** - the official website / GitHub releases / flatpak / snap / distribution package:

**Used theme**:

<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by ilya-fedin** [comment]
#8976

**Comment by hereMK** [comment]
> #8976

Thanks so much!
