### ISSUE TITLE
Telegram spontaneously removes last typed in charachters during typing the message (on Ubuntu)

### ISSUE THREAD

**Issue by vak** [telegramdesktop/tdesktop#9027]
### Steps to reproduce
1. Ubuntu 20.04 (x86_64)
2. install Telegram via snap 
3. type your messages and see how the last characters are being spontaneously removed from time to time.

It happens only on my Ubuntu machines

### Expected behaviour
What I type in should remain! :)

### Actual behaviour
the last typed in characters are being spontaneously removed from time to time.

### Configuration
**Operating system:**
Ubuntu 20.04.1

**Version of Telegram Desktop:**
2.4.7

**Installation source (Linux Only)** - the official website / GitHub releases / flatpak / snap / distribution package:
snap
telegram-desktop         2.4.7                       2198   latest/stable    telegram.desktop  -

**Used theme**:
Default. Never changed theme.

The bug is like 1 year old :-/

P.S. intuitively, I guess the bug has something to do with sync of the draft message to/from the server

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/4922
