### ISSUE TITLE
Links in group descriptions are not clickable

### ISSUE THREAD

**Issue by Griboedoff** [telegramdesktop/tdesktop#9028]
### Steps to reproduce
1. Create group
2. Add link in description

### Expected behaviour
Link should be clickable

### Actual behaviour
Link isn't clickable
![image](https://user-images.githubusercontent.com/16411561/98533505-210df880-2294-11eb-8e73-89712bbc9323.png)

### Configuration
**Operating system:**
Win 10

**Version of Telegram Desktop:**
2.4.8 beta, but reproduces for two weeks at least

**Comment by Aokromes** [comment]
i think it's intended.

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/8926

**Comment by Griboedoff** [comment]
hm, it works for long time.
Maybe make it as feature request?
