### ISSUE TITLE
Can't search through musics' filenames

### ISSUE THREAD

**Issue by brauliobo** [telegramdesktop/tdesktop#9029]
### Steps to reproduce
1. Join https://t.me/so_kiirtans
2. Search using any filename part
3. No music file is found

### Expected behaviour
Find music files using search through their filenames

### Actual behaviour
No music filename is indexed or can be found through their filename

### Configuration
**Operating system:**
Archlinux

**Version of Telegram Desktop:**
2.4.7

Also happens with the Telegram Android app

**Comment by RememberTheAir** [comment]
Media search is performed by the server, the clients shows you the list of results returned by the server. I don't think tdesktop can do anything about this

**Comment by brauliobo** [comment]
@RememberTheAir where to report this server issue?

**Comment by RememberTheAir** [comment]
You can suggest it to the in-app support, or ping Telegram [on Twitter](https://twitter.com)

**Comment by Aokromes** [comment]
such feature belongs to https://bugs.telegram.org/

**Comment by brauliobo** [comment]
reported at https://bugs.telegram.org/c/2361
