### ISSUE TITLE
[Feature-Request] Please fix poorly implemented history

### ISSUE THREAD

**Issue by ache** [telegramdesktop/tdesktop#903]
1) History should be accompanied with calendar block allowing to choose date (or even time) range. Imagine searching with many years of history or conference with thousand messages withing few hours. /Offtop: are mobile versions always load full history? We are in danger here to overflow memory. Clearing history is not a way, it can be valuable./
2) Add history export ability to work with history as the text in any text processing tool. Offline history and contacts info (synced with the cloud one) could be nice too for browsing it without Internet.
3) History search is very poor, it searches only by the word boundary and can't search half-words, which is especially bad for languages with complex endings like Russian or Chinese without spaces. Even Notepad searches better. Exported history + text editor can be workaround here.

**Comment by auchri** [comment]
1) No api for that
2) Already suggested
3) That's how the api works

**Comment by AndydeCleyre** [comment]
I think it's relevant to note here that this has been implemented in the OS X native app. Does that mean it's now possible in this one? Is it enough to re-open this issue?

**Comment by auchri** [comment]
@AndydeCleyre what exactly was implemented in the native OS X app?

**Comment by AndydeCleyre** [comment]
@auchri Now when you scroll up within a chat, a calendar icon is overlaid in the lower right corner. Upon clicking the calendar, a month-view calendar is shown, and the dates which feature activity in that chat are shown as a solid black, while others are lighter (I think). Clicking a particular date jumps the chat scroll view to that date.

**Comment by auchri** [comment]
Screenshots please :)

**Comment by AndydeCleyre** [comment]
![calendar-closed](https://cloud.githubusercontent.com/assets/1787385/13795631/5c251a0a-ead8-11e5-9a3a-3b6a9a451dac.jpg)

![calendar-open](https://cloud.githubusercontent.com/assets/1787385/13795632/5ffd3478-ead8-11e5-89f1-a1b0ef4033bd.jpg)

**Comment by stek29** [comment]
You can now click on date bubble in chat (or when scrolling) to go to date
