### ISSUE TITLE
Characters are not shown

### ISSUE THREAD

**Issue by chsnt** [telegramdesktop/tdesktop#9030]
### Steps to reproduce
1. Open Telegram Desktop

### Expected behaviour
Want to see all characters 

### Actual behaviour
Some characters are not shown

### Configuration
**Operating system:**
OS Windows 10
**Version of Telegram Desktop:**
[https://i.imgur.com/qHEIWYU.png](https://i.imgur.com/qHEIWYU.png)
**Used theme**:
Dark
**Screenshot**
[https://freeimage.host/i/F2D5jn](https://freeimage.host/i/F2D5jn)

**Comment by ilya-fedin** [comment]
Looks like something is wrong with your system

**Comment by chsnt** [comment]
> Looks like something is wrong with your system
buti don't have this problem in any other application

**Comment by ilya-fedin** [comment]
> but i don't have this problem in any other application

Maybe none of you other applications are Qt applications

**Comment by chsnt** [comment]
> > but i don't have this problem in any other application
> 
> Maybe none of your other applications are Qt applications

Илья, ничего страшного если по-русски?) 
Как мне проверить наличие таких приложений?

**Comment by ilya-fedin** [comment]
> Илья, ничего страшного если по-русски?)
> Как мне проверить наличие таких приложений?

Ну, например, qBittorrent. Можно было бы VLC, но он юзает Qt 4 под виндой до сих пор вроде, что не очень подходит.
В любом случае, даже если все окажется ок, ни у кого и нигде больше такое не проявляется, не говоря уже о том, что рендеринг шрифта - полностью задача Qt и мы вряд ли сможем что-то сделать

**Comment by chsnt** [comment]
> > Илья, ничего страшного если по-русски?)
> > Как мне проверить наличие таких приложений?
> 
> Ну, например, qBittorrent. Можно было бы VLC, но он юзает Qt 4 под виндой до сих пор вроде, что не очень подходит.
> В любом случае, даже если все окажется ок, ни у кого и нигде больше такое не проявляется, не говоря уже о том, что рендеринг шрифта - полностью задача Qt и мы вряд ли сможем что-то сделать

Т.е. мне лучше написать в репозиторий [Qt](https://github.com/qt)? Сама эта библиотека она обновляется вместе с Telegram'ом или отдельно?

**Comment by ilya-fedin** [comment]
Вместе с телеграмом. Последнее обновление Qt было в версии 2.4.8, до этого в 1.9.0. Насчет написать в репозиторий не уверен... Потребуют шаги для воспроизведения, но даже мы тут воспроизвести не можем, так что скорее всего просто закроют. Могу посоветовать только переустановить систему.

**Comment by Aokromes** [comment]
you may want to try to run repair system before reinstall. or maybe try on a virtual machine to see if it works properly.

**Comment by ilya-fedin** [comment]
> you may want to try to run repair system before reinstall. or maybe try on a virtual machine to see if it works properly.

This could be even a bug in gfx drivers

**Comment by ilya-fedin** [comment]
He could try the freetype cheatcode to check is this a GDI-specific issue or not

**Comment by chsnt** [comment]
>  freetype cheatcode
What is it? Give me a plan for action please

**Comment by ilya-fedin** [comment]
Go to settings and enter `freetype` like a cheat code in a game

**Comment by chsnt** [comment]
> Go to settings and enter `freetype` like a cheat code in a game, a dialog should appear.

[https://i.imgur.com/JmoHXIk.png](https://i.imgur.com/JmoHXIk.png)

I selected Ok and telegram restarted with the correct display of symbols. Thanks.
freetype - code for hardreset settings?

**Comment by ilya-fedin** [comment]
No, it changes the font engine to the Linux one
