### ISSUE TITLE
second save-as hangs ubuntu telegram-desktop

### ISSUE THREAD

**Issue by gordd** [telegramdesktop/tdesktop#9032]
### Steps to reproduce
1. Invoke telegram-desktop as per normal application->internet menu. Choose a chat. Choose an image. Choose save-as. fill in the filename. save. verify file saved correctly.
2. Choose a second image and save-as again. choose a different filename. save.....
3. Verify file not created, telegram-desktop hung, process stat is SLl (sleeping on an event, Locked pages)

### Expected behaviour
Tell us what should happen
The second (and subsequent save-as ) should create/overwrite the file if possible, and telegram should continue to be responsive.
### Actual behaviour
Tell us what happens instead
Telegram is hung waiting for the second save event to complete. It must be sent a signal from the shell, 'kill -1' is a sufficient event.
### Configuration
**Operating system:**
ubuntu 18.04.5 64b gnome 3.28.2, upgraded on an i7.
**Version of Telegram Desktop:**
2.4.7
**Installation source (Linux Only)** - the official website / GitHub releases / flatpak / snap / distribution package:
ubuntu uses snap nowadays...
**Used theme**:
gnome-session-flashback (lightdm)
<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary) (there is not much in /var/log/syslog. Perhaps there is a debug flag needed?
</details>

**Comment by ilya-fedin** [comment]
I can't reproduce and I don't think that app debug mode will help you, since file dialog is something toolkit takes care of

**Comment by gordd** [comment]
Downloaded the 2.4.7.zx and ran it. No longer able to reproduce the problem, therefore, I conclude it is an ubuntu/SNAP problem. Thank you very much.
