### ISSUE TITLE
How to remove unwanted language profile from translation platform?

### ISSUE THREAD

**Issue by KizunaH** [telegramdesktop/tdesktop#9036]
Few months ago i added new language to telegram translation platform due unaware about existing community-driven translation profile.
1. Is there way to remove or leave from that added new language profile by mistake?
(because it's annoying to me that side panel display duplicate entries. currently it seems only option to delete my account)
2. Does telegram may able to address that issue by setting it (community-driven profile) to display in "Start Translating" language list? https://translations.telegram.org/ (they've completed nearly entire translations for some apps) and it'll helpful for new volunteers to find the correct language profile then join easily also prevent start duplicates translation tasks for same language

The default procedure for inform or get support related translation through @TelegramAuditions but it seems doesn't get reviewed (haven't noticed/read for months) by telegram however open issues in this repository bit irrelevant but if you may able to help then please let me know, i'll share necessary details

**Comment by ilya-fedin** [comment]
This bugtracker is for tdesktop only...
