### ISSUE TITLE
[Question] How to have more than 3 accounts same time

### ISSUE THREAD

**Issue by totaltomg** [telegramdesktop/tdesktop#9038]
Hi. I want to have more that 3 telegram accounts same time in one client. I have many different accounts for customer service.

I looking for alternative telegram clients, but find nothing which implements this feature. Also I found solutions like ManyChat but I dont like that in some reasons.

So I think that if telegram desktop client is open source then I can modify it to support more accounts same time. Especially you already have support of 3 accounts at same time. So I looked to the code and find constant which responsible for that: kMaxAccounts https://github.com/telegramdesktop/tdesktop/blob/5cc7c2b6c6ecdce1ab4067549c4e7acd299dd5d5/Telegram/SourceFiles/main/main_domain.h#L33

Should it be enough to modify that line to have more telegram account same time. And which troubles that change can give. 

Thank you so much for answer and for good job on telegram client. Thats really awesome app.

**Comment by AhyaH-YHWH** [comment]
It will have more ram usage, when multi Account , and since it is a 32 bit app it will crash, 
if you modify it to have more than 3 Accounts

instead, using multiple copy of Telegram Desktop Portable, for Windows 
and logging in to each of them, is a better solution

**Comment by ilya-fedin** [comment]
> And which troubles that change can give.

Each account instance creates a copy of the most data, so each account should nearly to double RAM usage. If you using Windows, there are only a 32-bit build that has the limit of 2 GB virtual memory (~1GB of the resident memory), as soon as the app reach the limit, it will crash with OOM.
