### ISSUE TITLE
[Feature Request] Allow multi tasking, when opening a Photo/Video in TDesktop

### ISSUE THREAD

**Issue by AhyaH-YHWH** [telegramdesktop/tdesktop#9040]
Currently if you open a Photo/Video inside TDesktop 2.4.7
It will go straight Full screen, 
instead of being limited to Frame size of TDesktop
to open other programs, you have to first close the Media

so I suggest adding option, if users want all media open in full screen, 
or just take frame size of Telegram Desktop,
to allow going to other programs while Media is open in Telegram

(There is still option of full screen , on corner of Photos, like video player of Telegram has it)

Thanks.
![image](https://user-images.githubusercontent.com/73444508/98667731-0f942180-2364-11eb-97f7-46a6ba5a278a.png)

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/1710
