### ISSUE TITLE
hide/show app upon left click on tray icon

### ISSUE THREAD

**Issue by vbenes** [telegramdesktop/tdesktop#9041]
### Steps to reproduce
1. left click on tray icon in wayland in RHEL (flatpak installation - 2.4.7 )

### Expected behaviour
App should hide and show (like pidgin does), right click should offer menu

### Actual behaviour
left and right click both do the same, they offer menu, this can be further improved or maybe configured in settings

### Configuration
**Operating system:**
RHEL8.3

**Version of Telegram Desktop:**
2.4.7
**Installation source (Linux Only)** - the official website / GitHub releases / flatpak / snap / distribution package:
Flatpak

**Used theme**:
Adwaita

<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>
using KStatusNotifierItem/AppIndicator Support extension in GNOME Shell

**Comment by ilya-fedin** [comment]
This is managed by your tray extension, install another. What about pidgin, I guess it uses the old XEmbed protocol and your extension unable to force it to show menu on left click.
