### ISSUE TITLE
[Feature Request] Ability to zoom in photo viewer

### ISSUE THREAD

**Issue by cecurin** [telegramdesktop/tdesktop#9045]
### Is your feature request related to a problem?
No

### Describe the solution you'd like
I can't zoom the pictures on the desktop app, this is not ideal because I have a tiny screen and bad vision, and it is complicated to see the pictures that contain tiny letters.

### Describe alternatives you've considered
An alternative is save the picture and open it with the native photo viewer.

Thanks

**Comment by ilya-fedin** [comment]
There are Ctrl++/Ctrl+-/Ctrl+0 hotkeys

**Comment by Aokromes** [comment]
also control + mouse wheel.
