### ISSUE TITLE
[Feature Request] Recording voice messages on one click instead of holding

### ISSUE THREAD

**Issue by veronikazaglotova** [telegramdesktop/tdesktop#9047]
### Is your feature request related to a problem?
Yes! Sometimes I want to record a long message, or record myself playing the guitar/recorder on my computer. In first case, holding the mouse button for one minute or longer is just annoying, in the second case it's downright impossible because my hands are busy playing the instrument.

### Describe the solution you'd like
With Telegram on Android (and probably iOS) you can just hold down the mic button, then drag it up, then it records without you needing to hold down the mouse button. There's also a lock and an arrow pointing up to make it easy for new users to find out about that. I think it's the best way.
One click starts recording (second click stops), but holding down records while you hold is also good. In fact, I think that single click is what most people try to do when they try to record an audio message for the first time.

### Describe alternatives you've considered
A shortcut would be useful (for me at least, I use shortcuts a lot), but it isn't intuitive because people have to find out about the shortcut. You can show the shourtcut on a popup when you hover your cursor on the record button, but not many people (in my experience) ever hover their cursors over buttons to find out about such things, they just click on the button. I'm not against a shortcut, but make sure you have a way to do the same thing with the mouse.
Right-clicking seemed like a good idea at first, but it's not intuitive and it's not clear how you can tell about such functionality. Also, MacOS doesn't support two-button mice, it will make telegram behave differently on different systems, which is bad for people who use several OSs or are migrating to another OS.

**Comment by ilya-fedin** [comment]
#3208

**Comment by veronikazaglotova** [comment]
Me stupid
