### ISSUE TITLE
Disabling "Play sound" option has no effect

### ISSUE THREAD

**Issue by dimsuz** [telegramdesktop/tdesktop#9049]
### Steps to reproduce
1. Open Settings -> Notifications
2. Disable "Play sound" option
3. Wait for a message to arrive

Notification settings:
![image](https://user-images.githubusercontent.com/42920/98841857-5dd31e80-2451-11eb-9633-a75be4fb6b12.png)

### Expected behaviour
No sound on incoming messages

### Actual behaviour
I can hear a Telegram incoming message sound (piano note).

### Configuration
**Operating system:**
Arch Linux 5.9.4-arch1-1 #1 SMP PREEMPT Wed, 04 Nov 2020 21:41:09 +0000 x86_64 GNU/Linux
I Use GNOME 3.38.1 on Xorg

**Version of Telegram Desktop:**
2.4.7

**Installation source (Linux Only)** - the official website / GitHub releases / flatpak / snap / distribution package:
Official Arch Linux package

**Used theme**:
Light

**Comment by ilya-fedin** [comment]
As far as I know GNOME plays a notification sound by itself, you should disable sound somewhere in GNOME settings as well

**Comment by dimsuz** [comment]
Oh, wow, indeed. It's suprising because somehow I heard it only in Telegram messages, although similar setting is enabled for all apps. I turned it off for telegram and that checkbox in tg settings is now the single source of truth. 

Thank you, closing this bug.
