### ISSUE TITLE
Window shadow on multiple desktops under Windows 10

### ISSUE THREAD

**Issue by jknvv13** [telegramdesktop/tdesktop#905]
I noticed that in Windows 10 the window makes a shadow that repeats on every desktop.

Open Telegram and then change to a new desktop, you will notice the shadow.

**Comment by Nidonocu** [comment]
Also have this same issue on Windows 10 RTM, seems to only occur if the Windows is on Desktop 1 and you then view another desktop, not if the window is moved to a second desktop and you switch back to desktop 1.

**Comment by mparkms** [comment]
I have this bug on Windows 10 Pro official release. In addition, when Telegram is not the active window and you create a new desktop or switch to another desktop, it immediately switches back to the original desktop and makes Telegram the active window. This also only occurs when Telegram is on Desktop 1. This actually makes it impossible to switch to another desktop through the task view; you have to use the keyboard shortcut and make sure that Telegram is the active window when you switch.

**Comment by auchri** [comment]
Fixed with 0.8.45
