### ISSUE TITLE
Scaling not adjusting with 2 screens of different resolution

### ISSUE THREAD

**Issue by dickreuter** [telegramdesktop/tdesktop#9050]
### Steps to reproduce
1.  Setup up two screens, one a normal laptop screen and one external monitor with a higher resolution
2. Move the telegram window from the main window to the secondary one
3. font will be unreadably small

### Expected behaviour
Scaling should adapt automatically, same as Whatsapp is doing

### Actual behaviour
Scaling does not adjust

### Configuration
Windows 10
**Version of Telegram Desktop:**
2.4.7

**Installation source (Linux Only)** - the official website / GitHub releases / flatpak / snap / distribution package:
Standard installation via binary

**Used theme**:
All themes

**Comment by Aokromes** [comment]
... https://github.com/telegramdesktop/tdesktop/issues/1121
