### ISSUE TITLE
Broken taskbar/status bar integration after recent update

### ISSUE THREAD

**Issue by mareg** [telegramdesktop/tdesktop#9054]
### Steps to reproduce
1. Start telegram-desktop - it takes ages to start (30-60 seconds)
2. Close the telegram-desktop (stays in the systray)
3. Click on the telegram-desktop icon in the taskbar (plank),

### Expected behaviour
Nothing happens
30-60 seconds later Telegram window opens stealing focus

### Actual behaviour
Telegram window should open without delay

### Configuration
**Operating system:**

Fedora MATE-Desktop with Compiz

**Version of Telegram Desktop:**

$ rpm -qa | grep telegram-desktop
telegram-desktop-2.4.7-1.fc33.x86_64

**Installation source (Linux Only)** - the official website / GitHub releases / flatpak / snap / distribution package:

Official Fedora repository

**Used theme**:

Classic

Advanced configuration:

Yes - show tray icon
Yes - show taskbar icon
Yes - use system window frame
No - launch Telegram when system starts

**Comment by ilya-fedin** [comment]
This is a known issue and https://github.com/telegramdesktop/tdesktop/pull/9037 fixes this
