### ISSUE TITLE
[Feature Request] Accept call that started ringing before Telegram started

### ISSUE THREAD

**Issue by OJFord** [telegramdesktop/tdesktop#9055]
### Is your feature request related to a problem?
Sometimes Telegram on my phone rings, and I'd rather answer on my desktop, but Telegram isn't open there. Once open, even if phone still ringing it doesn't ring and so I can't accept the call.

Workaround is to decline the call on the phone or wait for it to ring out or accept and explain and hang up, then call back from desktop.

### Describe the solution you'd like
I'd like the desktop app to ring on opening if there is already an incoming call.

### Describe alternatives you've considered
N/A

### Additional context
N/A

**Comment by ilya-fedin** [comment]
#7735

**Comment by OJFord** [comment]
Oops, thanks.
