### ISSUE TITLE
Add a setting to disable taskbar icon flash

### ISSUE THREAD

**Issue by lf-** [telegramdesktop/tdesktop#906]
I usually have telegram open on another screen while playing a game. If anyone pings me, they will interrupt the game I'm playing.

If it was possible to disable the taskbar icon flash, it wouldn't cause any issues.

**Comment by Aokromes** [comment]
#897 ?

**Comment by stek29** [comment]
macOS?

**Comment by LucasMetal** [comment]
I have the same problem in Windows 7.
I use the Windows taskbar with auto-hide option, but everytime someone writes the taskbar button flashes and keeps the taskbar open until I go and read the message, it's really annoying. 
An option to disable taskbar flashing would be awesome!

**Comment by Logerfo** [comment]
This is also a problem for people who use multiple desktops on windows 10, since the flashing taskbar icon will show up across all desktops. I'm currently using a [workaround](https://github.com/mxs42/mutegram), but I don't think it would be hard to implement a proper setting for this.

**Comment by alessio-cpt** [comment]
This also affects negatively whoever is auto-hiding the taskbar, as the taskbar will raise up and cover UI elements of the program being used. At the very least, maybe you can find a way to let the taskbar hide again without having to open telegram to check the notification.

**Comment by Merlin2001** [comment]
Worst thing about this behavior is, that even with notifications disabled _entirely_ the taskbar will still flash!
