### ISSUE TITLE
[Feature Request] Customized per-chat user profiles

### ISSUE THREAD

**Issue by ElderOrb** [telegramdesktop/tdesktop#9060]
### Is your feature request related to a problem?
No

### Describe the solution you'd like
I'd like to get a way to override user profile for particular chats/groups: change bio, name / nickname, privacy settings

**Comment by MasterGroosha** [comment]
I'm pretty sure this is API issue, not TDesktop-related.

**Comment by Aokromes** [comment]
https://bugs.telegram.org/c/406
