### ISSUE TITLE
[Question] Why size of uploading file is different?

### ISSUE THREAD

**Issue by ivmazurenko** [telegramdesktop/tdesktop#9064]
![Снимок экрана от 2020-11-13 19-23-11](https://user-images.githubusercontent.com/34516127/99102067-36fa2100-25e6-11eb-900a-7eb8f0dc9f53.png)

Hello, i have tried to upload mp3 song to self, but, as I can see, the size is different on the filesystem and on the telegram interface

As I can see, the real size is 8.2 (SI) or 7.8 megabytes, but I see 7.7 in telegram interface

$ du -h --si The\ Strumbellas\ -\ \ Spirits.mp3 
8,2M	The Strumbellas -  Spirits.mp3

$ du -h  The\ Strumbellas\ -\ \ Spirits.mp3 
7,8M	The Strumbellas -  Spirits.mp3

**Comment by Aokromes** [comment]
maybe du -h rounds up and telegram rounds down.

**Comment by ilya-fedin** [comment]
Creating an issue just due to a difference in 0,1M? 😕

**Comment by ivmazurenko** [comment]
@ilya-fedin 1 byte is a significant difference.
