### ISSUE TITLE
[Feature Request] 

### ISSUE THREAD

**Issue by Sachin9600** [telegramdesktop/tdesktop#9065]
sir we want text size enlarge features in quiz bot. During quiz it very difficult to see the question continuously for long time.
so plz provide this feature text size enlargement feature in quiz bot section to get relief for our eyes during quiz.
and during quiz we facing speed issue ...... so for this provide a feature like one group is active for a particular period and giving much more speed during quiz ..... and provide a control that which groups is active  right now to get fast access for that period such that not facing any lag for that period....

**Comment by Sachin9600** [comment]
as soon as possible plz provide this features.

**Comment by ilya-fedin** [comment]
#90
