### ISSUE TITLE
Images don't fit screen when opne

### ISSUE THREAD

**Issue by expl0r3rgu1** [telegramdesktop/tdesktop#9066]
#5706 # Steps to reproduce
1. Open Telegram Desktop
2. Go into a chat
3. Click on an image or video

### Expected behavior
The image should just fit the screen size

### Actual behavior
The image shows in the bottom-right corner of the display as in this image:
![Screenshot from 2020-11-13 20-13-58](https://user-images.githubusercontent.com/35142289/99111771-fc47b700-25ec-11eb-9868-95431d61c5fc.png)

### Configuration
**Operating system:** Pop!_OS 20.10

**Version of Telegram Desktop:** 2.4.7

**Installation source (Linux Only)** - flatpak

**Used theme**: Night mode

**Comment by ilya-fedin** [comment]
#8818

**Comment by expl0r3rgu1** [comment]
> #8818

Ohw It's a duplicate, I see.
