### ISSUE TITLE
some emojies don't have names ☹

### ISSUE THREAD

**Issue by Hassan-Fa** [telegramdesktop/tdesktop#9068]
### Expected behaviour
typing :name_of_emojie should suggest the emojy

### Actual behaviour
white_heart and brown_heart seem to be the only emojies which don't have names(like the :orange_heart in the image). 
![image](https://user-images.githubusercontent.com/39556293/99131977-e1dffe80-2629-11eb-8f3f-f56b39510457.png)

### Configuration
windows10 2.4.8 Beta

**Comment by sq179** [comment]
It's sad.

**Comment by yuri0r** [comment]
i found a few more that have missing names

`🦶🦵🦿🦻👩‍🦰👨‍🦱🧑‍🦱👩‍🦱🧑‍🦰👨‍🦰👨‍🦳🧑‍🦳👩‍🦳👨‍🦲🧑‍🦲👩‍🦲`

very likely not complete

**Comment by yuri0r** [comment]
well the bug des still persists. its till bothering.

**Comment by yuri0r** [comment]
brown and white heart still are missing names. and likely a few more. this issue is not resolved.

**Comment by Hassan-Fa** [comment]
not resolved yet.

**Comment by yuri0r** [comment]
this still is not resolved. and very inconvienient.
