### ISSUE TITLE
Video player window is smaller when open video from album

### ISSUE THREAD

**Issue by Neurotoxin001** [telegramdesktop/tdesktop#9069]
### Steps to reproduce
1. Upload 1 video and album of 2 videos (or 1 video and 1 photo)
2. If video without album - player is bigger

<details>
  <summary>Screens</summary>
  
![1](https://user-images.githubusercontent.com/39812401/99140130-f1723e00-264f-11eb-92aa-382f24b04158.png)
![2](https://user-images.githubusercontent.com/39812401/99140131-f2a36b00-264f-11eb-8835-1badb038ec1d.png)
  
</details>

Example posts:
https://t.me/oijasdioasojidjioasd

### Configuration
**Operating system:** win 10 ltsc 1809

**Version of Telegram Desktop:** 2.4.8

**Used theme**: dark default

**Comment by Neurotoxin001** [comment]
Is this https://github.com/telegramdesktop/tdesktop/commit/cd67cb1c62637dae2d00fdc87746c6b5f1365cd1 related to my issue? On 2.4.10 beta when I open video from album it's large now, but when I open photo it's too large and borders is out of screen, for example:
https://t.me/dvachannel/60076

And also when I open first video then scroll to next media in album and scroll back - first video is again become small like before 2.4.10 beta

**Comment by Neurotoxin001** [comment]
+

**Comment by Neurotoxin001** [comment]
+

**Comment by ilya-fedin** [comment]
On your second screenshot album pictures take additional space, so the video is smaller. This is not a bug.
