### ISSUE TITLE
EXIF orientation bug

### ISSUE THREAD

**Issue by nkruglikov** [telegramdesktop/tdesktop#907]
When sending a photo, EXIF orientation is not considered.
There is a [good article on subject](http://www.daveperrett.com/articles/2012/07/28/exif-orientation-handling-is-a-ghetto/).

It is important because when you send a photo which is displayed in photo viewer in a portrait orientation, it would be displayed in Telegram in album orientation.

[Sample image](https://yadi.sk/i/9IuIHaHXhpjvf)
![useful_screenshot](https://cloud.githubusercontent.com/assets/8327627/8640218/12687eec-290a-11e5-9b33-64a1a23a47f5.png)

**Comment by Mithgol** [comment]
I've just tried saving https://yadi.sk/i/9IuIHaHXhpjvf and then dropping to “Saved messages”.

This bug seems fixed.

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/2874#issuecomment-310810139
