### ISSUE TITLE
Text input displays wrong length & emoji bug

### ISSUE THREAD

**Issue by morethanwords** [telegramdesktop/tdesktop#9070]
### Steps to reproduce
1. Edit any input (e.g. bio) with emoji (🎵)

### Expected behaviour
1. Length counter should count emoji as single character
2. The last emoji should not appear as unknown character

![ezgif-1-c1d56efccf77](https://user-images.githubusercontent.com/25210241/99151547-2791db00-26ad-11eb-9f03-a5a42457b22a.gif)

### Configuration
**Operating system:** Windows 10 Pro, 20H2

**Version of Telegram Desktop:** 2.4.7

**Comment by kamrano123** [comment]
This is expected behaviour, some emojis count as 2 characters
