### ISSUE TITLE
[Feature Request] Mutliple Proxy Remove at Once

### ISSUE THREAD

**Issue by MrT3acher** [telegramdesktop/tdesktop#9071]
### Is your feature request related to a problem?
Yes. The problem is that removing a lot of proxies, one by one, is so hard!

### Describe the solution you'd like
You can add some checkbox in the proxy list and the feature of selecting multiple proxies and `delete all selected` at once!

### Describe alternatives you've considered
null

### Additional context
null

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/5028
