### ISSUE TITLE
Transparent Menu Bar app icon on MacOS Big Sur

### ISSUE THREAD

**Issue by chernykhV** [telegramdesktop/tdesktop#9072]
### Steps to reproduce
1. Set `Dark mode` in MacOS: `System Preferences` -> `General` -> `Appearance` -> `Dark`
2. Change "Desktop Background" to white or something similar
3. Into Telegram app turn on `Show Icon in Menu Bar` switcher in `Preferences` -> `General`

### Expected behaviour
Telegram app icon must be the same (black) colour like any other icons in a row

### Actual behaviour
Telegram app icon is "transparent" or white, not like other icons

How it looks like:
<img width="135" alt="Screenshot 2020-11-15 at 06 49 19" src="https://user-images.githubusercontent.com/41281612/99162438-e03c3680-270e-11eb-920e-7f0f09ef4e13.png">
When click on it:
<img width="164" alt="Screenshot 2020-11-15 at 06 49 26" src="https://user-images.githubusercontent.com/41281612/99162446-ed592580-270e-11eb-917e-5e7b60bdf579.png">

But, all is right with `Light mode` and the same white desktop background:
<img width="156" alt="Screenshot 2020-11-15 at 07 16 44" src="https://user-images.githubusercontent.com/41281612/99162790-90f80500-2712-11eb-85ea-696d722301b2.png">
<img width="159" alt="Screenshot 2020-11-15 at 07 16 08" src="https://user-images.githubusercontent.com/41281612/99162783-72920980-2712-11eb-895c-ad1ebed53dc4.png">

### Configuration
**Operating system:** MacOS Big Sur 11.0.1 (20B29)

**Version of Telegram Desktop:** 7.2 (207038) AppStore

**Used theme**: `System`

**Comment by john-preston** [comment]
@chernykhV This is not Telegram Desktop, but another Telegram macOS app. You can try Telegram Desktop from https://desktop.telegram.org

**Comment by farhadh** [comment]
Hi!

I have installed Telegram Desktop from https://desktop.telegram.org and still have the same issue.

**Comment by albagonzalez** [comment]
Oh Wow I have this icon also in my menu bar and i don't have a lcue where it came from but it appear out of nowhere and I can't remove it, I have searched any option in google and nothing. What is this icon from, do you know the app? I found this thread searching a screenshot of the icon in google images... Please help!

<img width="31" alt="Screenshot 2021-02-08 at 23 31 19" src="https://user-images.githubusercontent.com/54865441/107290090-3eef2300-6a66-11eb-9b6b-e4367329f7e0.png">

**Comment by albagonzalez** [comment]
@chernykhV

**Comment by chernykhV** [comment]
> @chernykhV

This is VPN status icon, you can manage it in `System Preferences` -> `Network`, then tap on any VPN connection, you should see this checkbox bellow:
<img width="658" alt="Screenshot 2021-02-09 at 22 44 33" src="https://user-images.githubusercontent.com/41281612/107419041-63abcf00-6b28-11eb-93f1-1110a74c4cf1.png">

**Comment by chernykhV** [comment]
> > Oh Wow I have this icon also in my menu bar and i don't have a clue where it came from but it appeared out of nowhere and I can't remove it, I have searched every option in google and nothing. What is this icon from, do you know the app? I found this thread searching a screenshot of the icon in google images... Please help!
> 
> @albagonzalez
> 
> It's not an third party app or something, this is VPN status icon, you can manage it in `System Preferences` -> `Network`, then tap on any VPN connection, you should see this checkbox bellow:
> <img alt="Screenshot 2021-02-09 at 22 44 33" width="658" src="https://user-images.githubusercontent.com/41281612/107419041-63abcf00-6b28-11eb-93f1-1110a74c4cf1.png">

Also you can just remote it by the holding `Command` + `Hold the mouse over the icon and drag it from the menu bar`
