### ISSUE TITLE
The font become bold on Mac OSX 11.0.1

### ISSUE THREAD

**Issue by ComputerPers** [telegramdesktop/tdesktop#9078]
Look like an issue https://github.com/telegramdesktop/tdesktop/issues/5205 reappear with new OSX 11.0.1

I'm using 2K (2560x1440) monitor.

![изображение](https://user-images.githubusercontent.com/74526227/99218085-9032a200-27ea-11eb-840c-48147cfe959b.png)

**Comment by ilya-fedin** [comment]
Please restore the issue templeate.
