### ISSUE TITLE
Sticker are not working in Ubuntu 18.04

### ISSUE THREAD

**Issue by muhammadsemeer** [telegramdesktop/tdesktop#9080]
### Steps to reproduce
1. Sticker are not showing
2. 
3. 

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

### Configuration
**Operating system:** Ubuntu 18.04

**Version of Telegram Desktop:** v 2.4.5 30.10.20

**Installation source (Linux Only)** - the official website / GitHub releases / flatpak / snap / distribution package: the offical website

**Used theme**: DarkTheme

<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by ilya-fedin** [comment]
What do you mean by 'Sticker Like Emoji'?

**Comment by muhammadsemeer** [comment]
I mean stickers

**Comment by ilya-fedin** [comment]
How exactly they don't work? You should provide a very detail description of the issue, with screenshots.

**Comment by muhammadsemeer** [comment]
Now the Stickers are working properly
