### ISSUE TITLE
Sideways video call - contact rotated counter-clockwise 90deg

### ISSUE THREAD

**Issue by OJFord** [telegramdesktop/tdesktop#9083]
### Steps to reproduce
1. Start or accept a video call

(Every time, not an occasional occurrence.)

### Expected behaviour
Contact appears oriented right side up.

(As in Slack, Discord, on the same machine.)

### Actual behaviour
Contact appears rotated counter-clockwise 90deg, i.e. (assuming a 'normal' arrangement..!) the top of their head is to the left.

I appear to them correctly oriented.

### Configuration
**Operating system:**
Arch Linux

**Version of Telegram Desktop:** 2.4.7

**Installation source (Linux Only)** - the official website / GitHub releases / flatpak / snap / distribution package:
Distribution package

**Used theme**: ?

<details><summary><b>Logs to follow next time</b>:</summary>
</details>

**Comment by arrufat** [comment]
I have the same problem with latest version (2.5.1 from Arch Linux) but only when placing calls to iPhone devices. Calling Android devices or other Telegram Desktop on Windows machines works well.

**Comment by OJFord** [comment]
Yes, I can second that, it occurs for me with one (of one total) iPhone-using contact, but not when the same contact uses their Mac instead.

**Comment by allnightlong** [comment]
same issue here

**Comment by brianmsm** [comment]
Same issue here, from Manjaro.

**Comment by Tkd-Alex** [comment]
Same for me on Arch Linux with iPhone users

**Comment by arrufat** [comment]
I can confirm v2.5.8 fixed the issue for me. Thank you so much!
