### ISSUE TITLE
Menu bar icon doesn't match system theme on MacOS Big Sur

### ISSUE THREAD

**Issue by vimmerru** [telegramdesktop/tdesktop#9085]
### Steps to reproduce
1. Launch TD on Big Sur 11.0.1
2. See icon on topbar
3. It looks very different and unnatural in comparison with other icons

<img width="537" alt="image" src="https://user-images.githubusercontent.com/16944801/99364162-b299ed80-28c6-11eb-9339-350f0d214151.png">

### Configuration
**Operating system**: MacOS Big Sur 11.0.1

**Version of Telegram Desktop**: 7.2.1

**Used theme**: Doesn't matter. Icon is the same with any theme or Night Mode setting

**Comment by ilya-fedin** [comment]
#9072
