### ISSUE TITLE
[Feature Request] Show Send and Cancel button after a voice message was recorded

### ISSUE THREAD

**Issue by Cosmotan01** [telegramdesktop/tdesktop#9088]
Windows Desktop Version

Hi,
after i have finish speak my voice message i will like to have a choice to send or to cancle it. Sometimes you have say something bad and so you will have the chance to cancle it. 
thx
cheers

![telegram](https://user-images.githubusercontent.com/70658006/99382554-04de0d00-28cd-11eb-9e91-c53b295731bf.jpg)

**Comment by ilya-fedin** [comment]
You already have a chance to cancel it, just release the mouse button outside of the recording area

**Comment by Cosmotan01** [comment]
Yeah now i have see the little text "Release outside to cancel" :) Thx
