### ISSUE TITLE
[2.4.10] "Closed" app window stays on screen

### ISSUE THREAD

**Issue by MasterGroosha** [telegramdesktop/tdesktop#9089]
### Steps to reproduce
1.  Open Telegram Desktop
2a.  Try closing it with Ctrl+W hotkey
2b.  Try closing it with **x** button in top right corner

### Expected behaviour
Window is closed to tray

### Actual behaviour
Inactive and non-interactive "screenshot" of TDesktop window stays on screen
It doesn't happen 100% of time though, but very often

### Configuration
**Operating system:** Windows 10
**Version of Telegram Desktop:** 2.4.10

**Comment by MasterGroosha** [comment]
Also wtf is this and why is this failed? 
https://github.com/telegramdesktop/tdesktop/actions/runs/368760173/workflow

**Comment by 23rd** [comment]
I don't know why Github emailed to you, but thanks for noticing it.

**Comment by MasterGroosha** [comment]
@23rd this is the second time honestly.

**Comment by Taxom** [comment]
I have same Issues.
 Windows 10
Telegram Desktop: 2.4.10

**Comment by ilya-fedin** [comment]
> I don't know why Github emailed to you

Because GitHub emails the author of the issue/PR an action was failed on
