### ISSUE TITLE
[2.4.10] Visual issues after recent update

### ISSUE THREAD

**Issue by MasterGroosha** [telegramdesktop/tdesktop#9090]
First of all, I'm sorry that I have to provide photos, not screenshots.

### Expected behaviour
Everything should be fine

### Actual behaviour
Window control buttons are not properly aligned in fullscreen (restarted app several times, doesn't fix)
![изображение](https://user-images.githubusercontent.com/2780044/99435394-1bae4f00-2921-11eb-9053-bc933facc44b.png)

A part of window gets moved to the adjacent display in fullscreen
![изображение](https://user-images.githubusercontent.com/2780044/99435443-3254a600-2921-11eb-8955-e9a8f7ee7236.png)

### Configuration
**Operating system:** Windows 10
**Version of Telegram Desktop:** 2.4.10
**Installation source (Linux Only)** - the official website / GitHub releases / flatpak / snap / distribution package: GH releases

**Comment by ChaosPaladin** [comment]
Can confirm, same issue. For me temp solution resolve it - turn on in Settings -> Advanced -> Use system window frame

**Comment by mp-pinheiro** [comment]
Having the same problem. Also, the window when maximized on my secondary monitor, "leaks" into the primary one:

![image](https://user-images.githubusercontent.com/17935077/99445929-01fb1080-28fd-11eb-85c8-a047450c94dd.png)

Here's how it looks on the displays, you can see a good chunk, about half the cursor size, "leaking" from the left display into the right display:

![image](https://user-images.githubusercontent.com/17935077/99446132-5acaa900-28fd-11eb-923b-316285e89307.png)

> Can confirm, same issue. For me temp solution resolve it - turn on in Settings -> Advanced -> Use system window frame

This seems to fix the issue, although I prefer the Telegram window frame.

**Comment by atis** [comment]
Another visual/sizing issue, that seems related in 2.4.10: if clicking on any photo in chat, it first photo is opened zoomed in. Scrolling to next photo resets zoom, and scrolling back shows photo normal.

Ubuntu 16.04.7 
Mate desktop
tdesktop 2.4.10 (on 2nd display maximized)


Examples (first view)
![Selection_556](https://user-images.githubusercontent.com/1108226/99473905-3c43cc80-2954-11eb-8955-be6dbb29c73e.png)

Example (after scrolling)
![Selection_557](https://user-images.githubusercontent.com/1108226/99473914-406fea00-2954-11eb-8fca-df7f26bf97db.png)

**Comment by ilya-fedin** [comment]
@atis no, this is not related, this is a completely different issue
