### ISSUE TITLE
Cannot select alternate download location in Ubuntu 20.04

### ISSUE THREAD

**Issue by Garfsfield** [telegramdesktop/tdesktop#9098]
### Steps to reproduce
1. Settings / Advanced / Download path
2. Select Custom folder / Navigate to selected folder / Select the "Open" button
3. There is no Choose option, Cancel is the only way to return to the Settings

### Expected behaviour
The Chosen Folder should become the selected folder and the folder dialog should close.

### Actual behaviour
There is no Choose option, only an Open option, no folder can actually be selected.

### Configuration
**Operating system: Ubunto 20.04.1**

**Version of Telegram Desktop: 2.4.7**

**Installation source (Linux Only)** - Ubuntu distribution package:

**Used theme**: Tinted

<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by ilya-fedin** [comment]
> **Version of Telegram Desktop: 2.4.7**
> 
> **Installation source (Linux Only)** - Ubuntu distribution package:

Some error there, Ubuntu contains 2.0.1 in its repos: https://packages.ubuntu.com/focal/telegram-desktop

**Comment by Garfsfield** [comment]
I have a brand new install of Ubuntu 20.04.1 which was done in the last 24 hours.
No other repos are installed apart from what is shown here.

![Screenshot from 2020-11-18 14-07-39](https://user-images.githubusercontent.com/48473892/99528881-991ca280-29a7-11eb-9373-126f35636007.png)
![Screenshot from 2020-11-18 14-09-38](https://user-images.githubusercontent.com/48473892/99529055-e567e280-29a7-11eb-8f02-936bd1905195.png)
![Screenshot from 2020-11-18 14-10-00](https://user-images.githubusercontent.com/48473892/99529064-ea2c9680-29a7-11eb-873a-a5b62172a89a.png)
![Screenshot from 2020-11-18 14-10-35](https://user-images.githubusercontent.com/48473892/99529082-ef89e100-29a7-11eb-8675-90ccd99d18c2.png)

**Comment by ilya-fedin** [comment]
That means that you installed tdesktop not from distro repos and you need to provide the correct installation source to move issue forward.

**Comment by Garfsfield** [comment]
Going through the logs I see that the following as the path name.
comm="telegram-deskto" 
exe="/snap/telegram-desktop/2198/usr/bin/telegram-desktop"

Does this help, since I have no other installation sources, nor have I 
downloaded anything either.

Thanks

**Comment by ilya-fedin** [comment]
Yeah, you're using a snap package. This is fixed on 2.4.8 in snap.

**Comment by Garfsfield** [comment]
okay thanks,

A search for snap commands gave me the command for this.
snap info telegram-desktop

   - telegram-desktop
summary:   Official desktop client for the Telegram messenger
publisher: Telegram FZ-LLC (telegram.desktop)
store-url: https://snapcraft.io/telegram-desktop
contact:   https://github.com/telegramdesktop/tdesktop/issues
license:   unset
description: |
.......
snap-id:      jpdoHqMd90M39DdH2JSZbeQxipqHtwLo
tracking:     latest/stable
refresh-date: yesterday at 20:26 SAST
channels:
   latest/stable:    2.4.7                      2020-11-05 (2198) 187MB -
   latest/candidate: ↑
   latest/beta:      2.1.21-beta-63-g5655ad25b  2020-07-24 (2054) 160MB -
   latest/edge:      2.4.10-beta-115-g91b8ad171 2020-11-17 (2234) 187MB -
installed:          2.4.7                                 (2198) 187MB -

When will 2.4.8 become available as a non beta release?

Thanks

**Comment by ilya-fedin** [comment]
It won't. tdesktop release scheme doesn't have multiple parallel versions, stable versions are out with different number.
