### ISSUE TITLE
[2.4.10] Photo viewer zooms in on first view

### ISSUE THREAD

**Issue by atis** [telegramdesktop/tdesktop#9100]
### Steps to reproduce
1. Click on photo

### Expected behaviour
Photo shows full-screen
![Selection_557](https://user-images.githubusercontent.com/1108226/99523477-c9f8d980-299f-11eb-9583-fd798e978527.png)

### Actual behaviour
Photo shows full-screen, zoomed in
Scrolling (mouse wheel/arrows does reset zoom until photo view is closed)
![Selection_556](https://user-images.githubusercontent.com/1108226/99523488-cf562400-299f-11eb-9aa8-c1fcae30a6fd.png)

### Configuration
**Operating system:**
Ubuntu 16.04.7
Mate desktop
Dual monitor
**Version of Telegram Desktop:**
2.4.10 

**Installation source (Linux Only)** - the official website / GitHub releases / flatpak / snap / distribution package:
Official website
**Used theme**:
Classic

<details><summary><b>Logs</b>:</summary>
</details>

**Comment by ilya-fedin** [comment]
Already fixed by https://github.com/telegramdesktop/tdesktop/commit/b2047c955853c2b7a412625373a1ef9b6f0af423
