### ISSUE TITLE
App crashes when sending a command to the bot via the command menu

### ISSUE THREAD

**Issue by Koldef** [telegramdesktop/tdesktop#9101]
### Steps to reproduce
1. Open chat with bot
2. Open command menu (slash button)
3. Send command via this menu

### Expected behaviour
Sending message with command

### Actual behaviour
App crash

### Configuration
**Operating system:** Windows 10

**Version of Telegram Desktop:** 2.4.10 beta

**Used theme:** Day
<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by ilya-fedin** [comment]
Already fixed in dev branch

**Comment by Koldef** [comment]
@ilya-fedin Oh, good. Thanks for answer
