### ISSUE TITLE
[Feature Request] Allow the selection of the app icon in Settings

### ISSUE THREAD

**Issue by alazarolop** [telegramdesktop/tdesktop#9102]
### Is your feature request related to a problem?
A new icon is shown in macOS after the last update matching the new style of rounded squares. 

### Describe the solution you'd like
Allow the selection of the app icon as it happens in iOS apps, e.g. between Default, Classic and Filled icons.

![iOS](https://user-images.githubusercontent.com/19190130/99563076-32a87c00-29c9-11eb-92e2-e696fa6ced50.jpeg)

**Comment by ilya-fedin** [comment]
> A new icon is shown in macOS after the last update matching the new style of rounded squares.

Are you that you're talking about Telegram Desktop, not about https://github.com/overtake/TelegramSwift?

**Comment by alazarolop** [comment]
You are right. Sorry, my mistake.
