### ISSUE TITLE
[Feature Request] check list and Confirm

### ISSUE THREAD

**Issue by KoryChiu** [telegramdesktop/tdesktop#912]
Hi Great Telegram Team,
Hopes add following functions :
1) Check List function in Chat Group, it can helps most pepople to mark to do.
2) People can select memsage and mark it "needs confirm".

**Comment by joshery420** [comment]
I'd love this, actually.
I've always wanted a way to personally mark messages for later viewing (for example, when I see something on my phone but decide I want to look at it and reply when I get home), and a group-wide "needs confirmation" fits right in with that mentality of marking messages with some requested action or intent.

**Comment by auchri** [comment]
Not client related

**Comment by joshery420** [comment]
@auchri so it's server related, I won't disagree, but I'm pretty sure the server isn't hosted on GitHub. Where might we make a suggestion to add to the service itself that isn't client-related then?

**Comment by auchri** [comment]
True, the server isn't on github ...  you can try it on twitter: https://twitter.com/telegram or use the build in support feature (which will be implemented in the next version of telegram desktop too)

**Comment by joshery420** [comment]
Alright, maybe that's the way to go then. It'd be nice if the server was hosted here though. Not sure if you're in contact with the actual developer (or dev team, not sure how many) for Telegram's core service, but it's been brought up before (#807) that Telegram is only partially "open-source" as it claims to be. If Telegram really wants to claim it's open-source, it needs to be ALL open source, not just the client. Not that you necessarily have any control over that, mind you. 

Also, just noticed you actually mentioned offering to help @telegramdesktop in that thread too haha. Glad he finally got back to you so we've got another contact point! :smile:
