### ISSUE TITLE
Mac OS X: pasting images copied from new "Photos" app doesn't work

### ISSUE THREAD

**Issue by marcbou** [telegramdesktop/tdesktop#914]
On MacOS X (10.10.4), selecting a picture in Apple's new "Photos" app  followed by "Edit->Copy" to clipboard, then going to Telegram Desktop and doing a "Paste" causes the file-reference URL to appear as text instead of the image itself.

Doing the same "Paste" im Apple's "Messages" app results in the image appearing as expected.

Would be great if this issue could be fixed soon.

**Comment by zhovner** [comment]
Read this https://github.com/telegramdesktop/tdesktop/issues/2392

**Comment by stek29** [comment]
Can't reproduce on Sierra with 1.1.19

**Comment by stek29** [comment]
Oh, it was probably fixed with chrome/firefox related issues
