### ISSUE TITLE
Having issues compiling Telegram.pro with Qt Creator

### ISSUE THREAD

**Issue by Shikib** [telegramdesktop/tdesktop#916]
I'm trying to build the Telegram.pro file but I'm getting the following error

../DebugIntermediate/stdafx.o: In function `StaticQWebpPluginPluginInstance::StaticQWebpPluginPluginInstance()':
/home/shikib/TBuild/tdesktop/build-Telegram-Desktop_Qt_5_4_0-Debug/../Telegram/SourceFiles/stdafx.cpp:38: undefined reference to `qt_static_plugin_QWebpPlugin()'
collect2: error: ld returned 1 exit status
make: *** [../Linux/DebugIntermediate/Telegram] Error 1
00:23:34: The process "/usr/bin/make" exited with code 2.
Error while building/deploying project Telegram (kit: Desktop Qt 5.4.0)
When executing step "Make"
00:23:34: Elapsed time: 04:42.

Not sure what the problem might be. I've followed the instructions pretty carefully up to this point. I changed a number of things in the Telegram.pro file, as there seemed to be errors with the paths that references files in the Telegram directory. Here is a pastebin of what my Telegram.pro looks like right now: http://pastebin.com/kAEp3BVM

Any help would be greatly appreciated.

**Comment by xuzhao9** [comment]
Seems this is because in your build environment, both dynamic linked Qt5 so file and static linked .a file coexists. As a result, the linker choose the dynamically linked version hence the qt_static_plugin symbol does not exist.
Hope it helps.
