### ISSUE TITLE
[Feature Request] Display actions with /me

### ISSUE THREAD

**Issue by AerysBat** [telegramdesktop/tdesktop#917]
Other instant messaging clients commonly implement the old IRC /me syntax for displaying text as an action.  This might look like moving the text to the middle of the screen and displaying it in italics. It could also be left for the user to configure.

**Comment by wrincewind** [comment]
I just came here to ask about this as a possibility. It would certainly be appreciated!

**Comment by AltarBeastiful** [comment]
:+1:

**Comment by auchri** [comment]
I close this because of #1165 (includes also a screenshot)
