### ISSUE TITLE
[Feature requests] Mark Unread | Play button | Switch speakers for voice message

### ISSUE THREAD

**Issue by poooch** [telegramdesktop/tdesktop#918]
• mark as unread
• play button for mp3 files
• switch speaker for playing voice message
(to listen with close to ear speaker, but not with the loud speaker)

• attach frontal photo (like in facebook messenger)

**Comment by auchri** [comment]
* Not possible (no api for that)
* Added
* Another issue exists for that
* Another issue exists for that
