### ISSUE TITLE
[Feature Request] Keep incoming messages as unread if idle

### ISSUE THREAD

**Issue by codemonkey85** [telegramdesktop/tdesktop#919]
Basically I'd like the same thing Hangouts does - if I have a chat window open and focused, and I receive a message, the message is kept as 'unread' until I do something with the chat window. This is to prevent me from missing new messages if, say, I keep a chat window open on my desktop but walk away from it for a while.

**Comment by Aokromes** [comment]
I see this request related to #775 :)

**Comment by codemonkey85** [comment]
I could see that as being related from a high-level perspective, but I am asking for something specifically different from that.

**Comment by ahmadalli** [comment]
it has been added somewhere.

**Comment by codemonkey85** [comment]
@ahmadalli What do you mean?

**Comment by ahmadalli** [comment]
@codemonkey85 I mean I don't know since when, but in current version, if you're idle, it keeps incoming message unread.

**Comment by codemonkey85** [comment]
@ahmadalli Oh, I hadn't noticed. I'll look for that behavior today, and I'll close this issue if it works.
