### ISSUE TITLE
segfault with telegram-desktop-dev 0.8.40

### ISSUE THREAD

**Issue by sl1pkn07** [telegramdesktop/tdesktop#922]
gets segfault when launch

libs init..
static QPlatformTheme* QKdeTheme::createKdeTheme(): Unable to determine KDE dirs
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 70: non-double matrix element
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 70: non-double matrix element
Fontconfig warning: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 78: saw unknown, expected number
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 70: non-double matrix element
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 70: non-double matrix element
Fontconfig warning: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 78: saw unknown, expected number
Violación de segmento (`core' generado)

Telegram[16146]: segfault at 0 ip 0000000001462a83 sp 00007ffd330efcb0 error 4 in Telegram[400000+2230000]

in gdb:

#0  0x000000000043d250 in main ()

**Comment by telegramdesktop** [comment]
Should be fixed in 0.8.41.dev
