### ISSUE TITLE
UI/Notification caused intense frame drop on DX games running in other screen

### ISSUE THREAD

**Issue by darristan** [telegramdesktop/tdesktop#924]
Like title. When Telegram UI is at a screen, it will cause an unreasonable amount of frame drop on other heavy graphical application and games. It shouldn't demand so much power just for the flat UI.

i5 4670k @ 4.4 / R9 280x 15.7

Will upload framerate graphs and screenshots asap.

**Comment by auchri** [comment]
So where are your graphs and your screenshot?
