### ISSUE TITLE
[Feature Request] Add contact by username.

### ISSUE THREAD

**Issue by namoplasta** [telegramdesktop/tdesktop#925]
If is possible create username in telegramdesktop, what not is possible add contact in the same? Is a good feature for members that no have cellphone device.

Other feature is not remove contact after clear conversation history, is ridiculous remove contact after this action, because not is possible restore and not waiting this.

**Comment by formatq** [comment]
+1

**Comment by Ham3D** [comment]
+1

**Comment by harchus** [comment]
We need this.

**Comment by auchri** [comment]
Look at this conversation on twitter: https://twitter.com/Kortney/status/628946082412670976

**Comment by namoplasta** [comment]
>Look at this conversation on twitter: https://twitter.com/Kortney/status/628946082412670976

"Muuh aps mobilie, what apps mobile is your using, hurr aps mobile"

Fuck aps-mobile,  we nothing have modern cell-phones, It is incredible, several people asking the featur needed and telegram-team simply wants to impose its choice. Telegram It is focused to cell? Then lost time in developing for desktop, then nothing different from WhatsApp. If are to keep this garbage on the desktop version, better if it had not done.
