### ISSUE TITLE
Temporarily mute chats

### ISSUE THREAD

**Issue by klyonrad** [telegramdesktop/tdesktop#926]
On iOS I can temporarily (from 1h to 2d) mute chats, but on the desktop client there is only the option to disable notifications permanently.

**Comment by Aokromes** [comment]
#151

**Comment by kosciak9** [comment]
some VIP or special message to bypass quiet hours would be good, and probably would make it even more viable

**Comment by flippinger** [comment]
#2512, #2011

**Comment by stek29** [comment]
@flippinger Temporarily mute is individual for chats, and DnD's are global.

**Comment by stek29** [comment]
Fixed in #3678.
