### ISSUE TITLE
Minor Bug - File Browser not finding files without extension

### ISSUE THREAD

**Issue by luisalvarado** [telegramdesktop/tdesktop#929]
I have a file without any extension (don't need them on Linux anyway) and was going to upload it to a friend but the File Browser does not show it on the list. you can see the missing file below as well as the file itself to the right.

![screenshot from 2015-07-19 17 50 44](https://cloud.githubusercontent.com/assets/29236/8768477/1fd73f34-2e3f-11e5-9728-7943994eb808.png)

Additionally to this, the File Browser looks a lot older, so it's not using the default theme styles.

**Comment by ppparadox** [comment]
Wow that's actually true! What a shame!
+1

**Comment by nmaggioni** [comment]
+:100:

**Comment by john-preston** [comment]
This should be fine in 0.10.1 version.
