### ISSUE TITLE
Qt translation not loaded

### ISSUE THREAD

**Issue by tuxmaster** [telegramdesktop/tdesktop#930]
When an Qt dialogue is show, it is always English.
I think, the Qt translations are not loaded.

**Comment by tuxmaster** [comment]
See picture for more.
![bildschirmfoto von 2015-07-21 13 13 14](https://cloud.githubusercontent.com/assets/6240474/8799471/90cc6bc6-2faa-11e5-90ce-8ad0688cba56.png)

**Comment by Aokromes** [comment]
@tuxmaster this bug is still valid?

**Comment by tuxmaster** [comment]
Tested with 0.10.19.
Now it works.

**Comment by Aokromes** [comment]
You can close the ticket yourself :)
