### ISSUE TITLE
Shows error while "buid" of Packer project in solution.

### ISSUE THREAD

**Issue by futuretechsoft** [telegramdesktop/tdesktop#937]
Error : cannot open source file "../../../../TelegramPrivate/packer_private.h"
I can't find this file in any directory.
Can anyone help ?
![packererrorintelegramdesktop](https://cloud.githubusercontent.com/assets/13481994/8872186/6b18344e-3218-11e5-9e5a-70599e192568.PNG)

**Comment by telegramdesktop** [comment]
This project does not need to be built. It is used to deploy the release version of Telegram Desktop through desktop.telegram.org, not needed for custom builds.
