### ISSUE TITLE
add diffutils to ffmpeg pre-install commands

### ISSUE THREAD

**Issue by nasservb** [telegramdesktop/tdesktop#939]
i try to install ffmpeg on windows 8.1 for 2 day and on all version my configure stop by this error : 
Creating config.mak, config.h, and doc/config.texi...
./configure: line 1314: cmp: command not found
./configure: line 1314: cmp: command not found
./configure: line 1314: cmp: command not found

i search on net and find install diffutils  to solve this problem . 
add this command to  ffmpeg pre-install commands 

pacman -S msys/make
pacman -S mingw64/mingw-w64-x86_64-opus
pacman -S diffutils
pacman -S pkg-config

**Comment by nasservb** [comment]
compile  ffmpeg on my system  always return 

AR      libavcodec/libavcodec.a
LINK : fatal error LNK1181: cannot open input file 'libavcodec/x86/dct32.o'
library.mak:39: recipe for target 'libavcodec/libavcodec.a' failed
make: *** [libavcodec/libavcodec.a] Error 157

**Comment by telegramdesktop** [comment]
I've added it, thanks.
