### ISSUE TITLE
Package tdesktop on RPM

### ISSUE THREAD

**Issue by Jzarecta** [telegramdesktop/tdesktop#94]
You can use the Open Build Service.

http://openbuildservice.org/

It would be able to package for varios distros like Fedora, OpenSuSE, Ubuntu, Mageia, etc.

**Comment by edgard** [comment]
this. 100 times this. please, pleeeasse release rpm versions :)

**Comment by goarvic** [comment]
+1 rpm for openSUSE

**Comment by auchri** [comment]
Merged into #253
