### ISSUE TITLE
Option in preferences to auto play as well as auto download

### ISSUE THREAD

**Issue by brightbits** [telegramdesktop/tdesktop#940]
This would be awesome

**Comment by TotalKrill** [comment]
this is needed, prefferably per chat. Cant use telegram anywhere where people can see because of a groupchat using the imagebot. Also it eats data when on the move.

**Comment by Heeere-GittyGitty** [comment]
Is there any predicted ETA for this?

**Comment by TotalKrill** [comment]
Could i get any info on where to look then maybe i could give it a crack and do a pull request
