### ISSUE TITLE
App has to be restarted after suspend/resume (sleep/wake) on OSX

### ISSUE THREAD

**Issue by ben-xo** [telegramdesktop/tdesktop#941]
App has to be restarted after suspend/resume (sleep/wake) on OSX.

Expected:
* opening my Mac presents me with the same messages that I can see on other instances of Telegram (e.g. my phone)

Actual:
* last messages seen before suspend are still visible, clicking around inside app does not restore new messages. Have to kill and and restart it.

Experience this once or twice a day as I move between work and home.

version: 0.8.38

**Comment by ben-xo** [comment]
I realise this may be a dupe of #607 but that issue seems to focus on Linux and I'm sure the implementation of a fix is different on different platforms.

**Comment by auchri** [comment]
Duplicate #886
