### ISSUE TITLE
Unexpected behaviour when sending a message with spaces in it

### ISSUE THREAD

**Issue by AJ-Conradie** [telegramdesktop/tdesktop#942]
NB - this only happens in the desktop version...

I copied some code to show a friend and found the following:
I reproduced it with this easy example.

I typed in : 'a     ', and pressed the send button - it removed the spaces and made it: 'a '
BUT - on our mobile(android) versions it displayed correctly.

I would prefer nothing to be changed when I submit it.

![telegram1](https://cloud.githubusercontent.com/assets/13539805/8933321/6bce42c0-3542-11e5-919e-8114e8342c01.png)
![telegram2](https://cloud.githubusercontent.com/assets/13539805/8933320/6bce18ae-3542-11e5-8543-86da34234765.png)

**Comment by auchri** [comment]
Multiple spaces are removed in the desktop version
