### ISSUE TITLE
Emojis are yellow by default.

### ISSUE THREAD

**Issue by Noiwex** [telegramdesktop/tdesktop#943]
I think that emojis should be white by default, not silly yellow, cause it just doesn't match to them.

**Comment by auchri** [comment]
Yellow is the standard, defined by The Unicode Consortium
http://blog.emojipedia.org/os-x-10103-emoji-refinements

**Comment by Noiwex** [comment]
Ah, so tolerance came to this. I'm downgrading.

**Comment by ralesk** [comment]
Emoticons have always been yellow, rather than human coloured... not sure what's so surprising about that.

**Comment by Noiwex** [comment]
Smileys representing real humans (like cop, or hand gestures) were white

**Comment by dielsonsales** [comment]
That's discrimination. Emoticons shouldn't favor one ethnicity over all others.

**Comment by Noiwex** [comment]
Well I ain't wanna be a yellow smiley, you got to know that. Besides, black
smileys are so dark you can see nothing but a darkness here.
