### ISSUE TITLE
[Feature request] Add syntax highlighting in chat window

### ISSUE THREAD

**Issue by completit** [telegramdesktop/tdesktop#947]
Would be nice to have **syntax highlighting** in the chat window. Some of us devels (not all) like to paste code in the Telegram chat instead of using external browser services like pastie or pastebin etc...
![feature_teleg](https://cloud.githubusercontent.com/assets/5355219/8956803/f64f616c-3601-11e5-8492-3abca743e22a.png)

**Comment by auchri** [comment]
duplicate #250 #636
