### ISSUE TITLE
"~" Tilde, not showing. 

### ISSUE THREAD

**Issue by Glenn324** [telegramdesktop/tdesktop#950]
The special character "~" is showing as "-". 
But message in phone is recognizing it properly as a tilde.

**Comment by ralesk** [comment]
A Freetype font hinting issue (or an issue with the font you use).  I prefer slight hinting as well, but there are sadly a lot of fonts where Freetype will render tilde or combining tilde as a straight line.

**Comment by Glenn324** [comment]
Don't think it's the font I use, HAHA! As all other programs are fine.  Any hope of having this fix/changed/amended? Lol

Sent from my Windows Phone
________________________________

**Comment by ralesk** [comment]
See also: https://savannah.nongnu.org/bugs/?23537
Sadly, nobody's working on that bug since 2008 when it was reported.

**Comment by ralesk** [comment]
Ah, well, Telegram uses a font it ships, not a system font.  And I guess even on Windows it uses Freetype to render the font (it's possible to ask Qt to do that, IIRC) — in any case I've seen the ~ issue on Windows too, not just on my Linux box.

FWIW, I left a comment on the FT bug, maybe they pick it up finally.

**Comment by auchri** [comment]
duplicate #27 #537
