### ISSUE TITLE
Start a group chat

### ISSUE THREAD

**Issue by Geobert** [telegramdesktop/tdesktop#951]
On one hand, the "start a chat" flow is quite cumbersome (search for a contact, click on it to get its profile page, click on "send message") but it exists, on the other hand, it seems no way to start a group chat at all.

**Comment by TotalKrill** [comment]
There is a way. the button next to the search screen starts a group chat.

**Comment by Geobert** [comment]
wow, never seen it before, maybe a tooltip can help :)
