### ISSUE TITLE
[Bug] Unwanted clickable string !

### ISSUE THREAD

**Issue by esajjad** [telegramdesktop/tdesktop#953]
if a string start with "/http" is clickable and immediately sent !
![c1](https://cloud.githubusercontent.com/assets/4344360/9025967/2bc46e3c-3931-11e5-82b4-9826f8d0fd6c.PNG)
!

**Comment by telegramdesktop** [comment]
Any /string is clickable in any chat that has bots in it, because it is a bot command syntax.

**Comment by esajjad** [comment]
Even string that's not defined in bot commands?
