### ISSUE TITLE
new versions not connecting with http proxy (with authentication)

### ISSUE THREAD

**Issue by ngrcld** [telegramdesktop/tdesktop#954]
The last stable version of Telegram Desktop (0.8.43) doesn't connect with http proxy (with authentication). I tried with version 0.8.44 dev, but it has the same issue.
Version 0.8.38 (with automatic updates disabled) works perfectly.
Using Windows XP Professional SP3 (Italian).

**Comment by Xiphan** [comment]
I just noticed this issue as well except mine seems to be able to connect intermittently then randomly lose the connection.

**Comment by ngrcld** [comment]
Mine connected intermittently at the beginning. After some time, no connection at all.
Once I found a binary of version 0.8.38 (tough work), it immediately worked perfectly.

**Comment by ngrcld** [comment]
Same problem with version 0.8.45.

**Comment by telegramdesktop** [comment]
0.8.38 is on Qt 5.4, while the later versions are on Qt 5.5.. I don't know what they've broken in proxy support :(

**Comment by ngrcld** [comment]
Same problem with version 0.8.48.
I have found this bug: https://bugreports.qt.io/browse/QTBUG-46492

**Comment by Xiphan** [comment]
Why has this issue been closed? I still cannot connect via an http proxy in version 0.8.52. :(

**Comment by auchri** [comment]
Qt issue

**Comment by ngrcld** [comment]
The last stable version of Telegram Desktop (0.9.13) now WORKS with http proxy (with authentication).
I haven't tested previous versions.

**Comment by telegramdesktop** [comment]
@ngrcld Interesting :) Perhaps Qt 5.5.1 has fixed something.. Thank you for your information.

**Comment by ngrcld** [comment]
The last stable version of Telegram Desktop (0.9.15) now doesn't connect. Maybe something changed about proxy.
Version 0.8.38 (with automatic updates disabled) works perfectly.
Using Windows XP Professional SP3 (Italian).
