### ISSUE TITLE
Remember http proxy settings incl username and password

### ISSUE THREAD

**Issue by Xiphan** [telegramdesktop/tdesktop#955]
I often switch between two connections where the one connection uses an authenticated proxy for internet access and the other one is a direct connection. The problem I have is when I switch back to an HTTP proxy in Telegram I have to re-enter all the proxy details. Thus could you please add an option to remember proxy settings so it's easier to switch between a direct or proxy connection. Thanks.

**Comment by mi-volodin** [comment]
I'd rather ask for some kind of connection profiles. Like in ... putty or winscp. It would be comfortable to store this information and just switch between accounts when there is a need for that.

**Comment by Xiphan** [comment]
To be honest, I'd be happy with any kind of implementation so long as I don't have to re-enter my proxy details every time I change my connection. Sigh, not that proxy settings are working at the moment (Issue  #954).

**Comment by maxbeltra** [comment]
+1 for this request. I have to switch every day....very annoying.
Thanks

**Comment by ppparadox** [comment]
+1

**Comment by dsamersoff** [comment]
+1

**Comment by dveeden** [comment]
It should save the proxy settings and if a connection with proxy doesn't work it should try without proxy automatically.

**Comment by themegabyte** [comment]
+1
I switch all the time, and this is a must have feature.
It does actually have an automatic system that detects direct or HTTP (routed through system proxy) but it drops connection too often, breaks conversation tempos..

**Comment by auchri** [comment]
make a new one doesn't make any sense.

**Comment by jagun** [comment]
+1

**Comment by omkarnathsingh** [comment]
v1.2.18 fixes this. This issue can be closed now :).
