### ISSUE TITLE
Main window doesn't show anymore on Windows 10 with latest update

### ISSUE THREAD

**Issue by peterschen** [telegramdesktop/tdesktop#958]
The main window is not displayed anymore after the latest update on Windows 10. Notifications are displayed properly but opening them doesn't work.

**Comment by telegramdesktop** [comment]
Does work for me, the main system is Win10. Could you try reinstall? Could you try launch last portable version from https://desktop.telegram.org in a separate window?

**Comment by peterschen** [comment]
Reinstalled with the latest version and works again. I cleaned my \AppData\Roaming\Telegram folder though before I reinstalled.
