### ISSUE TITLE
[X][linux] xclipboard not working when selecting messages from message window.

### ISSUE THREAD

**Issue by fjfalcon** [telegramdesktop/tdesktop#961]
In linux, so as in any X server there is clipboard that works when you select text by mouse. After selection can be pasted anywhere by middle click on mouse. 
Problem here: 

in telegram desktop if you select your message, while you typing it - xclipboard gets text from it. 
When you select text in messages - nope.

**Comment by Quarx2k** [comment]
Same problem on Ubuntu 15.04 + Unity

**Comment by aluminiumgeek** [comment]
+1

**Comment by auchri** [comment]
Duplicate of #530

**Comment by chernomyrdin** [comment]
+1
