### ISSUE TITLE
Application crash when sending WEBP image

### ISSUE THREAD

**Issue by mi-volodin** [telegramdesktop/tdesktop#962]
In 0.8.45 win8 x64 found out that sending webp image to someone leads to application crash.
![1](https://cloud.githubusercontent.com/assets/8374532/9084057/b82975e2-3b80-11e5-9031-0381f11901ab.png)
![2](https://cloud.githubusercontent.com/assets/8374532/9084058/b9c911d2-3b80-11e5-83fa-f742bdabcd55.png)
![3](https://cloud.githubusercontent.com/assets/8374532/9084060/bb327c20-3b80-11e5-9c46-b5e86f6c8d0c.png)
![4](https://cloud.githubusercontent.com/assets/8374532/9084062/bd15eaf4-3b80-11e5-8182-a17a5c1c559f.png)

That's from windows events:
Exception code: 0xc0000005

It's maybe important that the image is actually not sent, since after reopening this message was not in the chat.

**Comment by telegramdesktop** [comment]
Thanks for your report! Fixing in 0.8.46 within an hour.
