### ISSUE TITLE
Suggestion: Option allowing user to confirm sending voice message.

### ISSUE THREAD

**Issue by vulcan25** [telegramdesktop/tdesktop#966]
I am using the desktop client v0.8.45 on OS X 10.10.4 (14E46).

**Background**: When sending a voice message I click down on the microphone icon, speak, and on release the message is sent.  To cancel I am able to move the pointer away from the microphone icon, release, and the message will be discarded.

**Problem**: This method works, however all it takes is the user to accidentally release the mouse button, without dragging away, and a message may be sent unintentionally.  

**Solution**: Perhaps implement an option within Preferences, which allows the user to be presented with another level of confirmation prior to sending a voice message.  The user will then be required to click Send or Discard specifically.

**Comment by diazbastian** [comment]
Using the raise-to-speake functionality can preview and listen to voice messages on Android before sending, perhaps using a similar interface activated from the preferences would be a great improvement.

**Comment by diazbastian** [comment]
Another interface to consider is the one that Wire uses, which allows to send the message directly (drag up) or to reproduce it before sending.

![screenshot_2017-04-04-13-49-55](https://cloud.githubusercontent.com/assets/5126124/24676572/8135e33a-1951-11e7-9ade-8585a2e4480a.png)
