### ISSUE TITLE
bad sending png

### ISSUE THREAD

**Issue by Akiyamka** [telegramdesktop/tdesktop#968]
png to jpg files are converted when sending, and as a result lost an alpha channel (no transparency)

**Comment by dielsonsales** [comment]
I guess the right way to send PNG's would be as a document instead of image. There was a discussion about this in Telegram for Android and apparently they just won't change this behavior: https://github.com/DrKLO/Telegram/issues/536

**Comment by auchri** [comment]
Yes, send them as documents :)
