### ISSUE TITLE
URL parser misses trailing exclamation mark

### ISSUE THREAD

**Issue by Robadob** [telegramdesktop/tdesktop#969]
When sending or receiving a URL such as http://example.com/! the exclamation mark will not be parsed as part of the URL, it appears if the exclamation mark is in the middle of the URL it parses the whole thing fine. Whilst uncommon for URLs to trail with !, it is completely valid as part of rfc1738.

Ironically, it appears GitHubs automatic url detection fails in this regard to.

**Comment by auchri** [comment]
Fixed :)
