### ISSUE TITLE
Feature request: Autofocus search input on pressing Ctrl/Cmd+F

### ISSUE THREAD

**Issue by emitstop** [telegramdesktop/tdesktop#97]
It'd be great if I could hit ctrl+f and have it autofocus the search input.
Just a bit of nice UX polish that I think would be nice to have!

**Comment by joshery420** [comment]
Trying to get a single thread for this feature request.
Maybe mark this as a duplicate of Issue #364 since that one has recent attention.

**Comment by auchri** [comment]
Added
