### ISSUE TITLE
no option for background in osx

### ISSUE THREAD

**Issue by loctauxphilippe** [telegramdesktop/tdesktop#970]
hello,
I have telegram dekstop from the mac app store.
I wanted to add a picture for the background in the chats like on mobile, but I see that I can't do that on telegram desktop.
Is it normal? Or maybe it's a feature that is not live yet?

**Comment by auchri** [comment]
It's possible in the settings

**Comment by loctauxphilippe** [comment]
@auchri could you send me a screenshot please?
I looked again but I don't see anything... :(

**Comment by auchri** [comment]
![image](https://cloud.githubusercontent.com/assets/5092164/9138952/4de06dfa-3d27-11e5-9c39-3bb3380f4c02.png)

**Comment by NicoKnoll** [comment]
I can't find it in the settings... which version was it added or which submenu is it in?

**Comment by stek29** [comment]
@NicoKnoll just open settings and scroll down

**Comment by jbfriedrich** [comment]
I think there is a misunderstanding here. Is it possible that @ploctaux has Telegram for MacOS and @nicoknoll has Telegram Desktop for MacOS? The two clients are confusing. One is only for OS X and is also available over the Mac App Store, the other one is the all-platform client, only available over the website.

- Telegram for MacOS (available on the web site and Mac App store, an app optimized for Mac OS) does not have a setting for the background, which is very annoying as it is bright white. This is what I guess is meant in this issue.
- Telegram Desktop (available on the web site for all Operating Systems) is greyish in color and has an option to change the background to something easier for my eyes, is not meant with this issue.

Am I correct?

**Comment by john-preston** [comment]
@jbfriedrich Telegram Desktop is available on the MacAppStore as well. This issue tracker is only about Telegram Desktop and it does have the background option.

**Comment by jbfriedrich** [comment]
Oh I did not know that Telegram Desktop was also available in the Mac App Store. But otherwise exactly the point I meant. Issue in the wrong project 😃. Do you know why there is an additional client for MacOS? Two clients is a bit confusing.

**Comment by HeadSpaceDude** [comment]
Why has it to be on both platforms web download and the Mac app store? And why have it show backgrounds on mobile (iOS) and not on Mac?

**Comment by Hellbringher** [comment]
for use background on Mac, you should:

- open settings
- go to appearence
- change "chat view" from "Minimalist" to "Bubbles", this will make appears bellow "chat preview" on this page the option "Chat Background"

choose yours.... enjoy!

![image](https://user-images.githubusercontent.com/38701792/39205813-24717c76-47d2-11e8-9871-fb61dd7cd540.png)

**Comment by margge** [comment]
I also don't find the option in the `4.5.1` version

<img width="1057" alt="not option" src="https://user-images.githubusercontent.com/770971/48160359-674fac00-e2b6-11e8-86d9-d152db5b9870.png">
