### ISSUE TITLE
Looks ugly under Linux

### ISSUE THREAD

**Issue by Yanpas** [telegramdesktop/tdesktop#971]
Right click menu over textbox, file browser etc. looks ugly (doesn't use system qt style).

**Comment by dielsonsales** [comment]
I've been wondering: is there a specific reason why Telegram doesn't use the native file browser just like Qt widgets does? It's pretty difficult, for example, to choose a profile picture without the "preview" that Nautilus offer in Gnome 3.

**Comment by auchri** [comment]
Duplicate #987

**Comment by ManuelSchneid3r** [comment]
I am the author of #987. Note that #987 is *not* about the filechooser. #987 is about the *application style* in general. Check #982 for native filechooser.

**Comment by john-preston** [comment]
In the latest 0.9.57 version gtk file chooser should be used if it is available. Please check.
