### ISSUE TITLE
Use system-default file-browser in linux

### ISSUE THREAD

**Issue by Yanpas** [telegramdesktop/tdesktop#972]
File attachment browser under linux is awful (ugly(no cerning, win95 style), doesn't show files without extensions, does't support user bookmarks, cyrillic fonts looks ugly too)

**Comment by auchri** [comment]
Duplicate #438

**Comment by ManuelSchneid3r** [comment]
I am the author of #987. Note that #987 is *not* about the filechooser. #987 is about the *application style* in general. Check #982 for native filechooser.

**Comment by john-preston** [comment]
In the latest 0.9.57 version gtk file chooser should be used if it is available. Please check.
