### ISSUE TITLE
Cann't type Chinese under ubuntu version

### ISSUE THREAD

**Issue by Stephen-Chen** [telegramdesktop/tdesktop#973]
I am a Chinese user.I used use telegram on ubuntu 64bit.But I cannot type any Chinese in it.

**Comment by auchri** [comment]
Duplicate #831 #810 #375 #275 #106 

Please use search before creating a new issue

**Comment by Stephen-Chen** [comment]
@auchri Thank you.

**Comment by guoyunhe** [comment]
Have waited for too long until this simple problem is solved. If the author accepts pull request, it has already been fixed.

**Comment by telegramdesktop** [comment]
Please check out 0.8.50 dev version, it should be fine there, I've added Qt plugins for IBus and Fctix.
