### ISSUE TITLE
'GLIBC_2.15' not found 

### ISSUE THREAD

**Issue by drunkwolfs** [telegramdesktop/tdesktop#974]
how to fix?
``
./Telegram: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.15' not found (required by ./Telegram)
./Telegram: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.14' not found (required by ./Telegram)
``
Linux Kali 1.1.0a x64

**Comment by x09** [comment]
I try to install on CentOS 6.6 Final..

    [ay@p6 Telegram]$ ./Telegram                               
    ./Telegram: /lib64/libc.so.6: version `GLIBC_2.15' not found (required by ./Telegram)
    ./Telegram: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by ./Telegram)

    [ay@p6 Telegram]$ cat /etc/redhat-release                                 
    CentOS release 6.6 (Final)         

    [ay@p6 Telegram]$ getconf -a | grep -i GNU_LIBC_VERSION
    GNU_LIBC_VERSION                   glibc 2.12

Only web?

**Comment by auchri** [comment]
To install glib on CentOS/RedHat/Fedora:

1. Login as root user via command prompt/shell
2. Execute following command:
    `yum install glib*`
    The above command will install all the packages and dependencies required for glib , glibc.

3. Once installation gets complete successfully, try installing the application.

(From http://geeksterminal.com/how-to-install-glib-glibc/1392/)

**Comment by x09** [comment]
2.12 is max for CentOS 6.x, RedHat Enterprise Linux 6.x, Scientific Linux 6.x , Oracle Enterpise Linux 6.x

**Comment by auchri** [comment]
If 2.15 is not available, it's not possible to use Telegram Desktop on CentOS

**Comment by abeersaqib** [comment]
Download pre-compiled binaries from  [here](https://jlison.github.io/bin/centos6/soichih/mirror/gcc-4.7.2.tar.gz)

Extract the binaries in /opt/gcc-4.7.2 
and run the following commands 

glibpath=/opt/glib/  (path where you have extracted glib )

export LD_LIBRARY_PATH=$glibpath/glib-2.49.4-kgesagxmtbemim2denf65on4iixy3miy/lib:$LD_LIBRARY_PATH

export LD_LIBRARY_PATH=$glibpath/libffi-3.2.1-wk2luzhfdpbievnqqtu24pi774esyqye/lib64:$LD_LIBRARY_PATH

export LD_LIBRARY_PATH=$glibpath/pcre-8.39-itdbuzevbtzqeqrvna47wstwczud67wx/lib:$LD_LIBRARY_PATH

export LD_LIBRARY_PATH=$glibpath/gettext-0.19.8.1-aoweyaoufujdlobl7dphb2gdrhuhikil/lib:$LD_LIBRARY_PATH
