### ISSUE TITLE
Stickers are too small in the preview panel [suggested solution]

### ISSUE THREAD

**Issue by focuz** [telegramdesktop/tdesktop#975]
Please consider the following for a major usability improvement...

Many stickers come out very small in the preview panel and it is therefore often hard to distinguish between them.

For a graceful solution, please take a look at LINE messenger;

There, on first click on a sticker, it is zoomed, then a second click [on the zoomed sticker] sends it. If the sticker was not the one of choice, a click outside of the zoomed area would un-zoom the sticker and show the preview panel again [or a tap on the undo button in case of android and the likes]. This is also a safeguard against unintended sending of stickers.

I would very much like to see this feature implemented for a major UX/UI improvement in Telegram.

Anyone agree?

**Comment by gFreezer** [comment]
How about a hover preview?

**Comment by focuz** [comment]
A hover preview is a well proven concept for desktop UIs and is exactly how LINE's desktop version deals with this. Devs takes notice please.

**Comment by Sushubh** [comment]
Right. The mobile app gives me a bigger preview on long press I believe. I have accidentally sent stickers because I kept trying to locate the option to get a preview.

**Comment by balboag** [comment]
Probably the reason is that making emojis bigger will add more Mb to the binary.

**Comment by Sushubh** [comment]
Stickers are different from Emoji. 
They are loaded on demand. 
They are mostly added from third party sources. Only one package comes preloaded in the core app and that too appears to be loaded on demand inside the app.
This is not a request for larger stickers. This is a request for larger preview of the stickers.

**Comment by balboag** [comment]
Oops, sorry, i read 'emojis' instead of 'stickers' :see_no_evil: 

You're right, a sticker preview feature would be great. It was already added to mobile apps.

**Comment by egabrum** [comment]
I'd say this is high priority. Using stickers is like defusing a bomb...

**Comment by ralesk** [comment]
Or maybe make stickers not auto-send?

**Comment by joshery420** [comment]
Came here looking to ask for exactly this.
Ever since long-press was added to preview a sticker on the Android app I've been wanting something similar on the desktop side.

Long-left-click, right-click, or mouseover all seem like viable options here.
Another option would be to just offer a toggle in the settings for a larger emoji/sticker panel, maybe one that scales up to whatever size your chat window is, or one that overlays the chat window when open?

**Comment by maxslayer** [comment]
you can preview the stickers even bigger if you click on the name of the stickers in the "stickers" tab
http://i.imgur.com/fSYqIPy.jpg

**Comment by auchri** [comment]
Added with v 0.9.15 stable

**Comment by joshery420** [comment]
Awesome, thanks so much @auchri and @telegramdesktop! The Desktop App is looking better every day. :)

**Comment by gorsash** [comment]
Currently press and hold gives you preview of a sticker. But I agree that preview on hover is a better solution

**Comment by almaceleste** [comment]
it would be nice if this solution worked in a web telegram
