### ISSUE TITLE
OS X autocorrection not working

### ISSUE THREAD

**Issue by Karlheinzniebuhr** [telegramdesktop/tdesktop#976]
On OS X, the automatic spelling correction is not working, would be awesome if that gets fixed

**Comment by telegramdesktop** [comment]
I'm not sure it is possible to do in Qt application.

**Comment by 24252411** [comment]
SI ES POSIBLE CANCELAR MI CUENTA EN GITHUB , CUANDO YO QUIERA , POR QUE ES
A FREE ACCOUNT . ES UN ABUSO QUE LO HE HECHO DESDE HACE RATO Y ME SIGUEN
LLEGANDO CORREOS DE ESTE DESTINATARIO. REPITO Cncelo por siempre respeten
mi desicion .

2015-08-07 14:15 GMT-05:00 telegramdesktop <notifications@github.com>:

> I'm not sure it is possible to do in Qt application.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/telegramdesktop/tdesktop/issues/976#issuecomment-128798749>
> .
>



-- 
QUIERO CANCELAR DEFINITIVAMENTE MI CUENTA DE GitHub , esto fue un error . ,
la cancelo por siempre.

**Comment by auchri** [comment]
@24252411 write englisch please

**Comment by Karlheinzniebuhr** [comment]
laughed way to hard at that comment

**Comment by auchri** [comment]
duplicate #96
