### ISSUE TITLE
Read messages stay marked unread

### ISSUE THREAD

**Issue by nim4n** [telegramdesktop/tdesktop#977]
hi
I'm using 0.8.46 and my OS is ubuntu, in the recently versions I have some problem with marking  message as read, some times I have to close the application and reopen  and click on the message to mark them as read.

**Comment by auchri** [comment]
Fixed?

**Comment by nim4n** [comment]
I have still the same problem in new version!

**Comment by auchri** [comment]
do you have a bad internet connection?

**Comment by nim4n** [comment]
no It's ok, I have this problem in recent version and before that every thing was ok

**Comment by virtualdj** [comment]
I noticed the same only recently with Telegram Desktop v0.9.49.
It happened after updating Tdesktop: I was "kicked" from the application and I had to re-login (with a new SMS, never happened before); now I have a bunch of conversations where on the phone I have two 2 marks, while on the Desktop only 1 mark appear (unread).

![comp](https://cloud.githubusercontent.com/assets/3251704/15437482/9ba66f6c-1ec7-11e6-990d-77b7b162d600.png)

However the last access time seems correct; restarting Telegram Desktop does not solve.
Some recent chats seem not to be synchronized, though (see the last two).

**Comment by virtualdj** [comment]
UPDATE: I've tried to clear the cache, uninstalling Telegram and reinstalling and the wrong check mark issue persists.

**Comment by auchri** [comment]
> This should be fixed now (a server-side bug). Please check.

**Comment by virtualdj** [comment]
Yes, fixed. Thank you!

**Comment by danielfilho** [comment]
I'm afraid this problem is back.

I'm facing this problem right now for a while (currently updating the client).

Still, this only happens in a mac client from home. The mac client from work is ok. I've tried to uninstall, logout, restart and every simple possible solution.

**Comment by stek29** [comment]
Do you have multiple display setup?

**Comment by danielfilho** [comment]
No

**Comment by sssemil** [comment]
Looks like it's back again.

**Comment by SavKS** [comment]
This bug is regularly seen on Linux systems
