### ISSUE TITLE
Telegram doesn't use the correct Roaming folder when it has been moved

### ISSUE THREAD

**Issue by tarper24** [telegramdesktop/tdesktop#9772]
### Steps to reproduce
1. Go to `%APPDATA%\..`
2. Right click > Properties > Location
3. Move...
4. Select a different location
5. Telegram continues to use the default location

### Expected behaviour
Telegram should use the new location which is accessible via `%APPDATA%` still

### Actual behaviour
Telegram uses the old location which is no longer accessible via `%APPDATA%`

### Configuration
**Operating system:** Windows 10 Pro v1909 18363.1082

**Version of Telegram Desktop:** 2.4.7

**Comment by ilya-fedin** [comment]
Telegram creates its data in the working directory (the same folder where binary is placed usually).
