### ISSUE TITLE
Cannot use backspace, delete and arrow keys with Korean

### ISSUE THREAD

**Issue by hottestchilipepper** [telegramdesktop/tdesktop#9773]
### Steps to reproduce
1. Put Korean Hangul with ibus
2. Press backspace key or delete key or left arrow key

### Expected behaviour
Tell us what should happen
If we press backspace key, the character right before should be removed.
If we press delete key, the character right after should be removed.
If we press left arrow key, the indicator should move left.

### Actual behaviour
Tell us what happens instead
If we press backspace key, the character '（' is added.  not '('
If we press delete key, nothing happened.
If we press left arrow key, the character 'ｑ' is added. not 'q'
Even if we press right arrow key, the character 'ｓ' is added. not 's'

### Configuration
**Operating system:**
Ubuntu 20.04

**Version of Telegram Desktop:**
2.4.7

**Installation source (Linux Only)** - the official website / GitHub releases / flatpak / snap / distribution package:
snap

**Used theme**:
default

<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by ilya-fedin** [comment]
IBus support is on Qt level, if you don't like how it works, file an issue for Qt.
