### ISSUE TITLE
Telegram slow/unresponsive on MacOS Catalina & BigSur

### ISSUE THREAD

**Issue by c0d3x** [telegramdesktop/tdesktop#9774]
So I have an issue with unresponsive Telegram app, it hangs and load really slow when you open application.
I have had this issue on MacOS Catalina and Big Sur.

The Telegram desktop app worked fine on Catalina a couple of versions back, so something introduced last couple of months have slowed it down a whole lot.

**Comment by Aokromes** [comment]
restore the template.

**Comment by c0d3x** [comment]
> restore the template.

How do I restore template?

**Comment by ilya-fedin** [comment]
> How do I restore template?

Create a new issue without removing the template
