### ISSUE TITLE
[Feature Request] Add Emoji 13.0

### ISSUE THREAD

**Issue by ArmeF97** [telegramdesktop/tdesktop#9775]
I ask tdesktop to add the new emojis (13.0 standard)

https://emojipedia.org/emoji-13.0/

They are standard and have been added in the new public ios version (14.2)

So if an iPhone user send it to a tdesktop user, the tdesktop user can't see the emoji

**Comment by ShrirajHegde** [comment]
So this isn't going to be addressed even though there are so many requests from multiple users and 5 months after the first issue?

**Comment by ShrirajHegde** [comment]
@john-preston [🥲-this](https://emojipedia.org/smiling-face-with-tear/) was released more than a year ago https://emojipedia.org/unicode-13.0/

I am mentioning you because the last commits related to emojis were made by you. 

Please look into it, Thank you

**Comment by ilya-fedin** [comment]
7f20cc7b44390574bb71251dfdcd3e2705f436c7
