### ISSUE TITLE
Wrong position of context menu on multi monitor setup

### ISSUE THREAD

**Issue by WURMiL** [telegramdesktop/tdesktop#9778]
### Steps to reproduce
1. Move Telegram to secondary monitor (on different GPU than primary monitor)
2. Open any context menu (with mouse right click) or hover mouse on message timestamp

### Expected behaviour
Context menu or tooltip is displayed next to mouse cursor

### Actual behaviour
Context menu or tooltip is displayed on right coordinates X,Y, but on wrong monitor (primary display)

### Configuration
**Operating system: Windows 10 Pro 2004

**Version of Telegram Desktop: 2.4.7

**Comment by ilya-fedin** [comment]
#7099
