### ISSUE TITLE
[Feature Request] Secret Chat Limbo

### ISSUE THREAD

**Issue by danielteles** [telegramdesktop/tdesktop#9779]
### Secret chats notifications
I've recently switched my smartphone and since I had some secret chats (which are not uploaded on the cloud), I've had to start new ones. Not a problem, the real problem is that if I don't start a new secret chat or explicitly let people know that I'm no longer logged in that device, they might never know it and keep trying to contact me in that conversation, which I will never be notified of because to me it doesn't exist.

### Possible solution
Identify that the user is no longer active in the session and disable the secret chats for the other person (something similar to what happens when you're trying to start a secret chat and it only gets enabled when the other user comes online) and/or send a notification to whom is involved informing that the other user is no longer active in that context (in which that secret chat exists).

### Additional context
This request may be somehow related to this one: [1871](https://github.com/telegramdesktop/tdesktop/issues/1871)

**Comment by ilya-fedin** [comment]
But there's no secret chats in the app at all, are you sure you're talking about tdesktop?

**Comment by danielteles** [comment]
It's not on the desktop version indeed, but I can't open issues at the mobile repo. I imagined that given the relation between the applications, I could register the issue here and it would be properly addressed. What should I do instead?

**Comment by ilya-fedin** [comment]
> What should I do instead?

Report to the In-App Support
