### ISSUE TITLE
Japanese/anthy input does not work

### ISSUE THREAD

**Issue by user2589** [telegramdesktop/tdesktop#978]
Telegram Desktop for Linux, 0.8.46
Ubuntu 14.04 x64, Gnome desktop
Japanese input installed, ibus-anthy

In all text entry fields Japanese input does not work, English characters printed instead. 
Something like [this](https://youtu.be/BkwgyevmSGk?t=245) expected. Copy-and-paste works fine.

When typing in Japanese, you actually input roman literals (i.e. English letters), that are translated into alphabet or kanji by ibus input handler. It looks like ibus doesn't work in Telegram, so problem might affect other ibus input methods, like Chinese or Korean. Unfortunately, I don't have any means to check Pinyin or Hangul right now.

**Comment by auchri** [comment]
Duplicate #937 #831 #810 #375 #275 #106

Please use search before creating a new issue

**Comment by user2589** [comment]
Not sure how I could find any of these, since they don't have a single word in common. Also, #937 looks irrelevant.
However, I agree it is a duplicate issue.

**Comment by telegramdesktop** [comment]
Please check out 0.8.50 dev version, it should be fine there, I've added Qt plugins for IBus and Fctix.

**Comment by user2589** [comment]
just checked, works great. Thank you!
