### ISSUE TITLE
Deleting entire chat history is too easy

### ISSUE THREAD

**Issue by PaulBol** [telegramdesktop/tdesktop#9781]
This week I lost all my saved messages recorded over several years. The last thing I remember doing is deleting the latest message. I could not figure out how the history got deleted and I suspect there's no way restore it (any pointers welcome if I'm wrong). However, I wanted to share an idea to make the accident less likely by removing the option to confirm with Return key and potentially even by clicking.

### Steps to reproduce
1. Open saved messages
2. Enter message
3. Right click on message > Delete Message
4. See dialog "Do you want to delete this message?" with *blue* DELETE button
5. Hit Return key to confirm
6. Click on options > Clear history
7. See dialog "*Are your sure*... *This action cannot be undone*." with *red* DELETE button &ndash; all indications that continuing might be really bad and not what the user intended to do
8. Hit Return key -> deletion is executed with no option to undo

### Expected behaviour
Do not accept Return key to confirm the action. E.g. require checking a box or entering a specific text. Some application for instance ask for entering the name of the object to delete.

### Actual behaviour
Everything is gone :-(

### Configuration
**Operating system:** Windows 10

**Version of Telegram Desktop:** 2.4.7

**Used theme**:  Regular

**Comment by john-preston** [comment]
@PaulBol I guess Enter could be removed indeed, but click should be enough. A lot of users delete chat histories pretty often.

**Comment by PaulBol** [comment]
Thanks for the feedback @john-preston. Removing Enter to me seems like the equivalent of making the clickable button red. Would be great if you'd consider this.

You surely have a broader perspective on the user base. I'd consider myself an active Telegram user for 5+ years. I still can't explain how I could have ever deleted all my saved messages. Therefore was thinking about options for making this happen by accident close to impossible for other user. Especially since Telegram's appreciable privacy approach means there's no recovery option.
