### ISSUE TITLE
My cell phone it's appears if i add a contacts only in my side!!! Huge BUG ?? Desktop 2.4.7....

### ISSUE THREAD

**Issue by DjDiabolik** [telegramdesktop/tdesktop#9783]
### Steps to reproduce
1. I have add a member of a group on my contacts. This member it's not have my cell phone number on his contacts list (or address book) on his phone but he told me he sees my number in my profile!!!
On Security setting i have set to see my number to my contact but it is clearly written that users will see my number if users have saved it in their address book
2. 
3. 

### Expected behaviour
This setting working good or it's bad explanation....

### Actual behaviour
Already descripted..

### Configuration
**Operating system: Windows 10

**Version of Telegram Desktop:2.4.7 Portable

**Installation source (Linux Only)** - the official website / GitHub releases / flatpak / snap / distribution package:Site

**Used theme**: The Default

<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by Aokromes** [comment]
not a bug,

**Comment by ilya-fedin** [comment]
#1096?

**Comment by DjDiabolik** [comment]
@Aokromes oh it's not a bug.... yeah problably a poorly explained feature?

**Comment by Aokromes** [comment]
yeah, and it's the same on android, i suggest you to contact in app "ask a question" to tell them to reword it.

**Comment by DjDiabolik** [comment]
it's not easy for me :) I can't speak english not very well and even here I thought I was not able to explain it well .... :)

**Comment by ilya-fedin** [comment]
> I can't speak english not very well and even here I thought I was not able to explain it well .... :)

Telegram Support is multilingual, there are a chance that they speaking on your native language.

**Comment by DjDiabolik** [comment]
Oh interesting... i try to this later tonight.

**Comment by Aokromes** [comment]
such feature belongs to https://bugs.telegram.org/
