### ISSUE TITLE
[Feature Request] Play a sound when someone disconnect from a call with me.

### ISSUE THREAD

**Issue by Ago1896** [telegramdesktop/tdesktop#9784]
While in a voice call with **Telegram Desktop for Windows** I've noticed that there no sound when the other person turns off the call, while when I close a call there's a clear sound to let me know the call ended.
So if I don't have the Telegram window on screen I can not know if the other person is still online or not.

An easy solution is to play the same sound of end call, present when I close the call, also when the other person disconnects from the call.

**Comment by ilya-fedin** [comment]
#6142
