### ISSUE TITLE
Cannot adapt multiple screen density on Windows with multi display setup

### ISSUE THREAD

**Issue by ericksli** [telegramdesktop/tdesktop#9785]
### Steps to reproduce
1. Connect to two monitors with different density: the main monitor is set to 150% scale and the another one with the normal density (set the scale to 100%)
2. Right click to the Telegram Desktop shortcut > Properties > Compatibility > Change high DPI settings, uncheck all two checkboxes
3. Set the Telegram Desktop to use default interface scale and pick 150%
4. Drag the Telegram Desktop window between different monitors

### Expected behaviour

Telegram Desktop should be able to adapt different screen density and it should set to correct interface scale when dragging between monitors with different scale.

### Actual behaviour

Telegram Desktop can only adapt to one screen density. Either adapte to the 150% scale monitor or the 100% scale monitor. When you drag the window to another monitor, the window scale will become too big or too small.

Using Windows Compatibility settings will cause Telegram Desktop UI blurry and viewing image lightbox malfunction which is not desirable.

### Configuration
**Operating system:**

Windows 10 version 2004 build 19041.630

**Version of Telegram Desktop:**

2.4.7

**Installation source (Linux Only)** - the official website / GitHub releases / flatpak / snap / distribution package:

N/A

**Used theme**:

Classic

<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by ilya-fedin** [comment]
#1121
