### ISSUE TITLE
Telegram Desktop Launch Failure

### ISSUE THREAD

**Issue by ProblyPuck** [telegramdesktop/tdesktop#9786]
Hello folks, I joined GitHub in hopes y'all might help me figure out an issue I've been having with telegram's desktop app for Windows.

Over the past few months, I haven't been able to get Telegram to launch despite running as admin, completely uninstalling and doing a fresh reinstall, and even checking that Win7 was still Telegram compatible.  When I click to start the application, absolutely nothing happens; I get no processes for telegram, and no changes to active applications.

I'm not the best at troubleshooting stuff like this, so I hope y'all might give me a hand. Thank you in advance!

**Comment by ilya-fedin** [comment]
Go to the folder where Telegram.exe is placed, grab log.txt and send here.
