### ISSUE TITLE
Flathub Telegram - No drag and drop

### ISSUE THREAD

**Issue by Brin-o** [telegramdesktop/tdesktop#9788]
### Steps to reproduce
1. Install telegram via flatpak on linux
2. Attempt to drag and drop a gif into the chat from nautilous file explorer

### Expected behaviour
The client should accept the gif as an attachment to the message

### Actual behaviour
The cilent says that the file is empty "could not empty file *file location here"

### Configuration
**Operating system: Pop OS 20.04**

**Version of Telegram Desktop: 2.4.7**

**Installation source (Linux Only)** - the official website / GitHub releases / flatpak / snap / distribution package: Flatpak

**Used theme**: Night mode

<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by Aokromes** [comment]
for sure sandbox doesn't allows you to do that from certain locations.

**Comment by ilya-fedin** [comment]
this is not a place for flatpak specific issues.
https://github.com/flathub/org.telegram.desktop/issues
