### ISSUE TITLE
[BUG] when trying to add a new contact

### ISSUE THREAD

**Issue by TiagoDanin** [telegramdesktop/tdesktop#979]
![gif](https://cloud.githubusercontent.com/assets/5731176/9151173/ed791efe-3dcf-11e5-9bc9-3b75b5d2d17e.gif)
He sends me to the old contact, and also not in the contact list

**Comment by 24252411** [comment]
LAR TODOS LOS CONTACTOS

2015-08-08 11:23 GMT-05:00 Tiago Danin <notifications@github.com>:

> [image: gif]
> <https://cloud.githubusercontent.com/assets/5731176/9151173/ed791efe-3dcf-11e5-9bc9-3b75b5d2d17e.gif>
> He sends me to the old contact, and also not in the contact list
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/telegramdesktop/tdesktop/issues/979>.
>



-- 
QUIERO CANCELAR DEFINITIVAMENTE MI CUENTA DE GitHub , esto fue un error . ,
la cancelo por siempre.

**Comment by 24252411** [comment]
rpor siempre

2015-08-08 11:23 GMT-05:00 Tiago Danin <notifications@github.com>:

> [image: gif]
> <https://cloud.githubusercontent.com/assets/5731176/9151173/ed791efe-3dcf-11e5-9bc9-3b75b5d2d17e.gif>
> He sends me to the old contact, and also not in the contact list
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/telegramdesktop/tdesktop/issues/979>.
>



-- 
QUIERO CANCELAR DEFINITIVAMENTE MI CUENTA DE GitHub , esto fue un error . ,
la cancelo por siempre.

**Comment by TiagoDanin** [comment]
Please, publish in English '-'

**Comment by telegramdesktop** [comment]
Please give full description in English.
