### ISSUE TITLE
[Feature Request] Active Group Hours

### ISSUE THREAD

**Issue by cihanyakar** [telegramdesktop/tdesktop#9790]
### Is your feature request related to a problem?
I manage some Telegram groups; some members send messages at night.
### Describe the solution you'd like
As a group admin, I should be able to suspend the group activities manually or automatically.

**Comment by Aokromes** [comment]
imho you must teach them to use scheduled messages.

**Comment by aemxn** [comment]
There are bots who manage this. Forgot the name but there is.

**Comment by Aokromes** [comment]
such feature belongs to https://bugs.telegram.org/
