### ISSUE TITLE
Crash when displaying a sticker: swscaler colorspace conversion error

### ISSUE THREAD

**Issue by tobip** [telegramdesktop/tdesktop#9799]
### Steps to reproduce
1. Open a chat in Telegram where someone sent a sticker.
2. Watch it crash.

### Expected behaviour
Show the sticker :-)

### Actual behaviour
The animation of the sticker will play exactly once, then Telegram will crash. Sometimes Telegram crashes immediately, without showing the animation at all.

Terminal gives following output:
```
[swscaler @ 0xffff6c107860] No accelerated colorspace conversion found from yuv420p to bgra.
Aborted (core dumped)
```

### Configuration
**Operating system:** Linux Manjaro ARM Sway edition (Hardware: PineBook Pro)

**Version of Telegram Desktop:** 2.3.0-1

**Installation source (Linux Only)**: Official Repositories

**Used theme**: Default

**Comment by ilya-fedin** [comment]
ffmpeg asm optimizations bug
https://gitlab.alpinelinux.org/alpine/aports/-/issues/11722
