### ISSUE TITLE
Doesn't notify of new messages when windows starts

### ISSUE THREAD

**Issue by superbonaci** [telegramdesktop/tdesktop#98]
It happens I've received some telegram messages overnight, and in the morning I start the computer. Telegram for windows is set to autostart, minimized, and desktop notifications are enabled. The icon in the system tray shown the red counter, buy no popup is shown. Would like an option for this.

**Comment by superbonaci** [comment]
Can't test anymore not using windows. but hey it's been some time.

**Comment by ArmeF97** [comment]
So.. shall we close this? @superbonaci

**Comment by superbonaci** [comment]
yes
