### ISSUE TITLE
[bug] Hidden contact issue on Windows 8.48 update for desktop

### ISSUE THREAD

**Issue by Pejii** [telegramdesktop/tdesktop#980]
There is a bug with the hidden contacts that won't let the user to start a conversation on the new desktop update (8.48) for windows (tested on windows 8.1) with the contacts they never had a conversation with before.

When searching for hidden contacts via the search bar on top of contact list, or via the contact menu and after finding and clicking on the contact to start a conversation, the application closes search/contact window pop-up but instead of opening the conversation window and redirecting the user to conversation mode, it goes back into showing only the contacts with conversation and hides the newly searched hidden contact, making it impossible to start a conversation with contacts you never had a conversation with before.

**Comment by auchri** [comment]
Related to #979

**Comment by telegramdesktop** [comment]
It does not work like that for me in 0.8.50.dev, when you click on a contact without messages it is displayed like an empty conversation for me.
