### ISSUE TITLE
Telegram interface does not automatically adapt to different screen resolutions and scaling (with external monitor)

### ISSUE THREAD

**Issue by MeepoAII** [telegramdesktop/tdesktop#9800]
### Steps to reproduce
1. Windows 10 laptop
2. External monitor (hdmi, or vga is ok)  
3. Set different resolutions and scaling for the two displays(this is common in daily work)
4. Drag the telegram from one screen to another.

### Expected behaviour
Should be able to automatically adapt to different display resolutions and scaling. 
See Chrome and edge for switching between different displays.

### Actual behaviour
Telegram can only fit one display scale, and usually the larger one
For example, a laptop monitor is scaled at 200% (higher resolution) and an external monitor is scaled at 100%, but the telegram can only be displayed at 100% on both screens and is not auto-adapted. This makes it a bit difficult to view telegram on a laptop.

### Configuration
**Operating system:**
windows 10 professional 2004

**Version of Telegram Desktop:**
version 2.4.7

**Used theme**:
Default theme

**Comment by ilya-fedin** [comment]
#1121

**Comment by MeepoAII** [comment]
emmm all right。。。。
