### ISSUE TITLE
I can't hear neither talk in telegram desktop app

### ISSUE THREAD

**Issue by MuktadaCreations** [telegramdesktop/tdesktop#9801]
### Expected behaviour
When calling on my phone I can't hear anything from the desktop software and neither talk in it, Same goes for the phone 'And yeah I tried the phone with a different number already it worked' I think its just that the desktop app isn't able to hear from the default mice and cant take out the audio that's coming from the other call

### Actual behaviour
Don't know?

### Configuration
Windows 8.1

**Version of Telegram Desktop:**
2.4.11 beta

**Used theme**:
 Night

I tried already doing the calls setting and changing the default devices (Playback/Record) Didnt work, And no my mice works fine in discord so it should work with telegram as normal

**Comment by ilya-fedin** [comment]
#8443
