### ISSUE TITLE
[Feature Request] Make Possible for chat owner to disable downloading media files

### ISSUE THREAD

**Issue by Maiky-R** [telegramdesktop/tdesktop#9804]
### Describe the solution you'd like
I'd like to have a possibility to prohibit exporting media files via export data button and via common download
from particular private chats and from particular bots that I created

### Describe alternatives you've considered
I've tried to collect the program using the code but for now, I ran into some problem with qt5 files

I found some topics about this problem but I didn't find the solution yet
after doing all the steps of the instruction I still do not have all the proper files and folders that provides proper thing
there is no folders like: Libraries\Qt-5.12.8
but there are: 
F:\Visual\TBuild\Libraries\patches\qtbase_5_12_8
F:\Visual\TBuild\Libraries\patches\qtbase_5_15_1
F:\Visual\TBuild\Libraries\patches\qtwayland_5_12_8

what should I do to make it work?

P.S. it's my first touch for C++ and this is why I can really miss some important thing
my language is python
please, don't blame me

### Error code:
CMake Error at cmake/external/qt/package.cmake:23 (find_package):
  By not providing "FindQt5.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "Qt5", but
  CMake did not find one.

  Could not find a package configuration file provided by "Qt5" with any of
  the following names:

    Qt5Config.cmake
    qt5-config.cmake

  Add the installation prefix of "Qt5" to CMAKE_PREFIX_PATH or set "Qt5_DIR"
  to a directory containing one of the above files.  If "Qt5" provides a
  separate development package or SDK, be sure it has been installed.
Call Stack (most recent call first):
  CMakeLists.txt:37 (include)

**Comment by ilya-fedin** [comment]
> I found some topics about this problem but I didn't find the solution yet
> after doing all the steps of the instruction I still do not have all the proper files and folders that provides proper thing
> there is no folders like: Libraries\Qt-5.12.8

I guess you copy-pasted all the commands from instructions at once instead of executing command-by-command and carefully reading the output

**Comment by Maiky-R** [comment]
![Screenshot_3](https://user-images.githubusercontent.com/64254454/100156898-c7741380-2eba-11eb-8d01-5a10ea8b3b54.jpg)

I started re-doing step by step as you suggested and Visual Studio caught these problems

**Comment by ilya-fedin** [comment]
Looks like you cloned the not like specified in the instruction
![image](https://user-images.githubusercontent.com/17829319/100162134-c9ce7180-2eaa-11eb-8096-9dee7d2f9eed.png)

**Comment by Maiky-R** [comment]
![Screenshot_4](https://user-images.githubusercontent.com/64254454/100182389-8517fa00-2eed-11eb-99ee-69704b1f1fa4.jpg)

**Comment by Maiky-R** [comment]
![Screenshot_5](https://user-images.githubusercontent.com/64254454/100186148-826dd280-2ef6-11eb-9cc2-78901906ee83.jpg)

how exactly I should do this part ?

I tried to type line by line, but the result wasn't right...

**Comment by Maiky-R** [comment]
![Screenshot_7](https://user-images.githubusercontent.com/64254454/100186372-e8f2f080-2ef6-11eb-8083-ba6bf1cd82d8.jpg)

**Comment by ilya-fedin** [comment]
`^` is an escape character, this is a multiline command and should be copy-pasted at once.

**Comment by Maiky-R** [comment]
![Screenshot_8](https://user-images.githubusercontent.com/64254454/100186907-fd83b880-2ef7-11eb-8685-b34af88c6979.jpg)

**Comment by ilya-fedin** [comment]
F. I'm not a WIndows user, wait for @john-preston

**Comment by ret394** [comment]
If u're trilingual, use English US locales. Other English locales are stupid.

Especially on Windows and non Windows OS.

---

incompetent noobs do use the caret in scripts. But I talked with some legends that help people become SolutionsArchitect Developers. Then the SolutionsArchitect  devs become SecOps heads at trivial companies like Alphabet.

Anyways, point is there is never a good reason to use carets or these classes of characters. At least with puny one liners like the cmake invocations.

you're welcome, as always. all the best. 👍
don't say nasty stuff or do rude stuff to folks on Github or other sites.

[ret394](https://github.com/ret394)

**Comment by ret394** [comment]
>chat owner to disable downloading media files

the complement to that feature which must be released in one stable release is - allow users to exit the chat room without letting the admins know. Lets me escape from insane chats. 
(✿◡‿◡)

And if u do that in chats, you'd better be a nice kid and use Discord. So I cannot see ur irrelevant life's magnum opus. Yes, I'm sure you're a big shot hacker, but shut up and use Discord or IRC.

**Comment by Maiky-R** [comment]
> incompetent noobs do use the caret in scripts.

thanks
write command in a single line and it works now

**Comment by Maiky-R** [comment]
> point is there is never a good reason to use carets or these classes of characters.

write command in a single line and it works now

**Comment by Maiky-R** [comment]
![Screenshot_10](https://user-images.githubusercontent.com/64254454/100207713-f6b96d80-2f18-11eb-963a-0ad4a1985a54.jpg)

what should I do?

**Comment by Maiky-R** [comment]
![Screenshot_11](https://user-images.githubusercontent.com/64254454/100214160-94646b00-2f20-11eb-9ead-bd1baafd508a.jpg)

**Comment by Maiky-R** [comment]
![Screenshot_12](https://user-images.githubusercontent.com/64254454/100219518-27080880-2f27-11eb-87a8-e8c2d0980534.jpg)

**Comment by Maiky-R** [comment]
is it okay if JOM have been processing for about 80 minutes....
