### ISSUE TITLE
[Feature Request] Messages with rounded corners

### ISSUE THREAD

**Issue by Koldef** [telegramdesktop/tdesktop#9805]
### Is your feature request related to a problem?
Partly Yes. This will help the messenger look better and also look the same on all devices

### Describe the solution you'd like
In the Android version, the user can choose how rounded the message bubbles will be. I think this is a great option, as it allows you to customize the app's appearance more flexibly

**Comment by M299792458** [comment]
Wow! I didn't notice that we don't have that. 🤣🤭

**Comment by Koldef** [comment]
Oh, thanks! 🎉
