### ISSUE TITLE
[Question] Do u even know what the issue is?

### ISSUE THREAD

**Issue by ret394** [telegramdesktop/tdesktop#9807]
https://github.com/telegramdesktop/tdesktop/issues/9804#issuecomment-733551211

Poor Maiky-R, seems you're new here. Please don't reply to a thread if you don't understand it. You narrowly dodged a blessing which would seem like bullying or rudeness to u. But most people reading that thread will get it, I mean like 99.0% of the people at min.

Even Github staff, some of them have a masters degree or a postdoc in CS,  need a couple of months to understand what I mean in a single comment. If I changed my style, it would be like using a broken bullock cart when you got a faster than light transporter.

I hope u understand my helplessness.

---

References - https://github.com/github/hub/issues/2650
Thread signal - 'a lotta info!' and 'hella lotta damage to stupidity!'

**Comment by ret394** [comment]
sorry I cannot post every one of the over 10,000 threads on Github.
And those on Gitlab. I'll make a tool in my first GP DS language when my Patreon blows up in 2021.

**Comment by Maiky-R** [comment]
I'm really sorry

**Comment by ret394** [comment]
No need bro, I aint from STack Oerlfow. Or SOverflow,

**Comment by ret394** [comment]
u should have seen how much I used to mess up. u ain't got nothing on me compared to that, not in a million years.

not even if you randomly bash your keyboard interface.

**Comment by ret394** [comment]
sorry I forgot cat pics.

<details><summary>CLICK ME</summary>
<p>

relax!

![external-content duckduckgo com](https://user-images.githubusercontent.com/63034930/100211435-25900d80-2f32-11eb-851b-9651c39275dc.jpg)

</p>
</details>
