### ISSUE TITLE
Bug: Incorrect  Bowling (dice) result in Desktop version

### ISSUE THREAD

**Issue by AlexMercier** [telegramdesktop/tdesktop#9812]
### Steps to reproduce
1. Send bowling emoji 🎳
2. When you get result with value, for example, 5  then in Mobile (ios, android) version you can see that 1 pin left, but desktop show strike.
But in mobile only value 6 - strike. 
All incorrect values:
dice value "1": on Mobile - no pins, on desktop - 1 pin (incorrect).
dice value "2": on Mob - 1 pin, on desktop - 3 pins  (incorrect).
dice value "3": on Mob - 3 pins, on desktop - 4 pins  (incorrect).
dice value "4": on Mob - 4 pins, on desktop - 5 pins  (incorrect).
dice value "5": on Mob - 5 pins, on desktop - 6 pins (win)  (incorrect).
dice value "6": on Mob - 6 pins(win) and on desktop - 6 pins (win).

This is bowl with 5 value screenshot:
And how it displayed in Desktop:
![2020-11-26_140307](https://user-images.githubusercontent.com/6580198/100343219-24251a80-2ff0-11eb-9289-7aa873531b3b.png)

And on mobile, Android:
![photo_2020-11-26_13-55-19](https://user-images.githubusercontent.com/6580198/100343461-71a18780-2ff0-11eb-9b28-6e8439c99707.jpg)

iOS:
![photo_2020-11-26_14-18-50](https://user-images.githubusercontent.com/6580198/100344780-68191f00-2ff2-11eb-952e-c3e414e8f5e6.jpg)

json result:
```
{
 "update_id": 926230501,
 "message": {
  "message_id": 456765,
  "from": {
   "id": <>,
   "is_bot": false,
   "first_name": "<>",
   "username": "<>",
   "language_code": "ru"
  },
  "chat": {
   "id": <>,
   "first_name": "<>",
   "username": "<>",
   "type": "private"
  },
  "date": 1606387906,
  "forward_from": {
   "id": <>,
   "is_bot": false,
   "first_name": "Maxim",
   "last_name": "<>",
   "username": "mbelebekha"
  },
  "forward_date": 1606387763,
  "dice": {
   "emoji": "🎳",
   "value": 5
  }
 }
}
```

### Configuration
**Operating system:** Windows 10

**Version of Telegram Desktop:** 2.4.7

**Comment by john-preston** [comment]
@AlexMercier Thanks! I hope this will be fixed on the server side, the special sticker pack has different emoji mapping than the previous emoji-games.
