### ISSUE TITLE
"Could not send empty file" error

### ISSUE THREAD

**Issue by asorel1942** [telegramdesktop/tdesktop#9816]
### Steps to reproduce
1. Copy file to clipboard or drag and drop onto chat window

### Expected behaviour
File (specifically picture) is properly recognized by Telegram and uploaded to chat

### Actual behaviour
Receive "Could not send an empty file" error message, followed by directory path of the image I am trying to upload.

### Configuration
**Operating system:**
Linux Manjaro KDE 64-bit
**Version of Telegram Desktop:**
2.4.7
**Installation source (Linux Only)** - the official website / GitHub releases / flatpak / snap / distribution package:
Snap repository
**Used theme**:
Tinted.
<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by ilya-fedin** [comment]
Drag'n'Drop is not supported in confined environments neither by GTK nor by Qt, not a Telegram bug
