### ISSUE TITLE
[Linux] Hide window header it tiling window manager

### ISSUE THREAD

**Issue by agentgoblin** [telegramdesktop/tdesktop#9817]
In latest versions of Telegram I see custom window header and buttons. But I have tiling window manager and that's not need for me. Can I hide that?

[Link to screenshot at imgur.](https://imgur.com/TQWbYuQ)

**Comment by agentgoblin** [comment]
Main point - many software with custom window header just replaces system header. But looks like Telegram just draw it in borderless window, which bad in my opinion.

**Comment by ilya-fedin** [comment]
advanced settings -> use system window border

**Comment by agentgoblin** [comment]
Big thanks for quick answer. I miss this option. :)
