### ISSUE TITLE
non-ASCII characters in downloaded files are removed

### ISSUE THREAD

**Issue by PoisonousJohn** [telegramdesktop/tdesktop#9819]
Possible regression of https://github.com/telegramdesktop/tdesktop/issues/557

### Steps to reproduce
1. send file with non-ASCII name
2. try to open it

### Expected behaviour

When the file is saved on the disk, it has the same name as the original.

### Actual behaviour

The system fails to open the file because in the actual file name non-ASCII characters are removed.
For example
`Доп №3 на покраску.pdf` is saved as ` 3   .pdf`

### Configuration
**Operating system:** arch linux

**Version of Telegram Desktop:** 2.4.7

**Installation source (Linux Only)** - the official website / GitHub releases / flatpak / snap / distribution package:
aur/telegram-desktop-bin 2.4.7-1
    Official desktop version of Telegram messaging app - Static binaries

**Used theme**:

<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by ilya-fedin** [comment]
`locale -a`

**Comment by PoisonousJohn** [comment]
```
locale -a
C
en_GB.utf8
en_US.utf8
POSIX
ru_RU.utf8
```

```
➜ locale -a
C
en_GB.utf8
en_US.utf8
POSIX
ru_RU.utf8
```

**Comment by ilya-fedin** [comment]
LC_MESSAGES is empty, i think it is the cause.

**Comment by PoisonousJohn** [comment]
Thanks, it helped, sorry, was not aware of LC_MESSAGES
