### ISSUE TITLE
[Feature Request] Move Call Settings to the Settings tab

### ISSUE THREAD

**Issue by nahakiole** [telegramdesktop/tdesktop#9821]
When I as a new user am looking for the call settings I'd be looking for them by clicking on settings and not on call, as I would only expect the call tab to show me my latest calls, but not the video and audio settings.
![image](https://user-images.githubusercontent.com/4542479/100474805-c2dd7400-30e1-11eb-9135-253d39f29891.png)

![image](https://user-images.githubusercontent.com/4542479/100474908-0d5ef080-30e2-11eb-9eae-6ccc6a718074.png)

So I'd suggest to move at least a link to the video and audio settings inside the settings.

![image](https://user-images.githubusercontent.com/4542479/100474789-b9540c00-30e1-11eb-9834-b9ab3e1b9b03.png)

![image](https://user-images.githubusercontent.com/4542479/100474996-3b443500-30e2-11eb-8871-b2ba0f389bc7.png)

**Comment by ilya-fedin** [comment]
Settings -> Advanced -> Call Settings

**Comment by nahakiole** [comment]
I didn't find it there right away, so I think it should be moved to the main settings list. 
As calling is a major feature it should be in that list as a setting.

**Comment by s-light** [comment]
i also did not notice the *Call Settings* Link in the Advanced Settings..

**Comment by dratzinger** [comment]
The placement of this menu is **really** counter-intuitive. I gave up looking for this multiple times, before googling it and finding a github-issue to point me there.

**Comment by s-light** [comment]
this feature request is still valid.

**Comment by Aokromes** [comment]
implemented on 3.6.1.
