### ISSUE TITLE
Some large images (as files) cause telegram to freeze when copied (ctrl+c) in media viewer

### ISSUE THREAD

**Issue by ShrirajHegde** [telegramdesktop/tdesktop#9822]
### Steps to reproduce
1. Send some large images without compression
2. Open it to get media viewer
3. Use Ctrl+c to copy to clipboard

### Expected behaviour
The image file should get copied to clipboard 

### Actual behaviour
Telegram app freezes and doesn't recover

### Configuration
**Operating system:** Ubuntu 20.04

**Version of Telegram Desktop:** 2.4.7

**Installation source (Linux Only)** - the official website / GitHub releases / flatpak / snap / distribution package:Official Website

**Used theme**: "Tinted" (Default night mode)

<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by ilya-fedin** [comment]
Can't reproduce with a 5000x5000 image created in GIMP

**Comment by ShrirajHegde** [comment]
![1m4](https://user-images.githubusercontent.com/66936172/100741608-0bf23880-3400-11eb-91cf-c3d0b0eff6f6.jpg)

Can you test with this image?

**Comment by ilya-fedin** [comment]
Can't reproduce, I press Ctrl+C and able to close the media viewer

**Comment by chevi** [comment]
Version 2.4.13 beta
Telegram is freezed, but after ctrl+V pasting image file
OS: Ubuntu 16.04 LTS

**Comment by ilya-fedin** [comment]
@chevi another bug
