### ISSUE TITLE
Telegram Resize Issue with Nvidia Drivers

### ISSUE THREAD

**Issue by Prateek64X** [telegramdesktop/tdesktop#9823]
Whenever I need to resize telegram window, I can't resize it at all, All I can do is snap on a side and maximize. 
I have system (below) and I believe it is Nvidia issue because yesterday when I updated drivers it got correct again and today again it got broke.

And I had this problem in many old versions of Nvidia driver, just I didn't knew if it was my pc issue or a bug.

System:
OS: Windows 10 2012
GPU: Nvidia GTX 1050 ti 4gb
Nvidia Driver version: 457.30 and I had problem is many old versions also just I didn't knew if it was my pc issue or a bug.
Display: 1080p @ 75 hz

**Comment by ilya-fedin** [comment]
Why did you remove the template? Restore it. If you don't know how to, just close the issue an fill new one without removing the template.

**Comment by Prateek64X** [comment]
> Why did you remove the template? Restore it. If you don't know how to, just close the issue an fill new one without removing the template.

Sorry for that, It's my first time here
