### ISSUE TITLE
Linux change micro don't work

### ISSUE THREAD

**Issue by malyshkin-vitali** [telegramdesktop/tdesktop#9826]
### Steps to reproduce
1. Open Telegram Call settings
2. Try to change micro.

### Expected behaviour
Settings should be saved.

### Actual behaviour
Nothing has been saved.

### Configuration
**Operating system: ArchLinux

**Version of Telegram Desktop: 2.4.7

**Installation source (Linux Only)** - the official website / GitHub releases / flatpak / snap / distribution package: arch pacman

**Used theme**:

I have a webcam Logi c270 and an audioint. Focusrite Solo with micro AT2020 XLR. The problem that telegram uses only webcam micro but in Linux settings I use AT2020 default. I try to change micro in Telegram settings but nothing saved. If I off webcam from PC, telegram uses AT2020 but I want to use webcam with AT2020.

**Comment by ilya-fedin** [comment]
#8435
