### ISSUE TITLE
Does not empty ~/.local/share/TelegramDesktop/tdata/temp_data folder when restart

### ISSUE THREAD

**Issue by centosup** [telegramdesktop/tdesktop#9828]
TD does not delete ~/.local/share/TelegramDesktop/tdata/temp_data and ~/.local/share/TelegramDesktop/tdata/tdld folders when app is closed and this potentially exposes secure user data

I suggest clearing this directory when starting the application for delete old data if app was crashed before
i suggest encrypting the data in the directory

Ubuntu 16.04 4.15.0-123-generic #126~16.04.1-Ubuntu SMP Wed Oct 21 13:48:05 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

**Comment by ilya-fedin** [comment]
Both temp_data/tdld are not used in the actual code base, I gues you're using a very ancient version of tdesktop

**Comment by centosup** [comment]
Sorry, but I I reproduce the problem with temp_data now

e:~/.local/share/TelegramDesktop/tdata/temp_data$ ls -l
итого 1224
-rw-rw-r-- 1 user user 1252212 ноя 29 12:37 IMG_4751.JPG

This file was not deleted when I restart app (

And I have lasted version TelegramDesktop 2.4.7

![im068a558](https://user-images.githubusercontent.com/11453103/100533475-d0107500-323f-11eb-86aa-bc4ecc4d1df5.png)

**Comment by ilya-fedin** [comment]
#6806
