### ISSUE TITLE
[Feature Request] Export both! json and html at same time!

### ISSUE THREAD

**Issue by gwpl** [telegramdesktop/tdesktop#9829]
If somebody would like to have both : html and json, why to export two times?
Especially as text is lightweight comparing to media (photos, video etc). Why not export json and html at once? (therefore make it a new default or checkboxes allowing to select both formats)

**Comment by karstenw** [comment]
+1

I just wanted to start that feature request.

**Comment by gwpl** [comment]
I still believe that it's simple to add low hanging fruit for those familiar with codebase

**Comment by gwpl** [comment]
Hey!

I am still looking forward this feature ! :)

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/commit/29bfe4338629be950e0dd32f5a77d00771fca4ea

**Comment by gwpl** [comment]
I still believe that it's simple to add low hanging fruit for those familiar with codebase

**Comment by gwpl** [comment]
I should be reopened

**Comment by andreymal** [comment]
@gwpl why? It is implemented

**Comment by gwpl** [comment]
No I am checking on my Telegram Desktop: export chat history, settings, and "choose export format" is 
* html
* json
only one, not two at the same time 
(i.e. via checkboxes or * html + json third option).
So I can not export both "at the same time". I need to run export two times and change setting (and then they maybe out of sync against each other... )

**Comment by andreymal** [comment]
@gwpl your Telegram Desktop is probably too old
![telegram-desktop-export-both](https://github.com/telegramdesktop/tdesktop/assets/3236464/53d07f55-1731-47fb-ba0b-4829263d2016)

**Comment by gwpl** [comment]
![Screenshot_20231023_223708](https://github.com/telegramdesktop/tdesktop/assets/221403/89a32e37-6f33-4ca4-8b99-fc4b9d55d259)

![Screenshot_20231023_223751](https://github.com/telegramdesktop/tdesktop/assets/221403/27d3060b-1bb0-4c48-ad57-e62a02b4e743)

From which version is it supposed to be availble?

https://desktop.telegram.org/changelog

**Comment by andreymal** [comment]
@gwpl version 4.8.10 released 3 months ago, it is too old

![tdesktop-about](https://github.com/telegramdesktop/tdesktop/assets/3236464/ec551c40-9387-49b9-b691-dde09b6805d7)

**Comment by gwpl** [comment]
Thank you! It turned out I had to fix my VM. Now I have new version there and both exports are available!
