### ISSUE TITLE
Version 0.8.48 of the Windows desktop client allows keyboard to move focus to conversations that are hidden due to having no messages

### ISSUE THREAD

**Issue by tkuismin** [telegramdesktop/tdesktop#983]
I'm using 64bit Windows 7 SP1. When a conversation is focused in the conversation list, and the [Down] key is repeatedly pushed, the focus moves down. If there are hidden conversations (no messages in them), the focus disappears. Pressing [Down] multiple times and then pressing [Up] the same number of times brings the focus back. Also pressing [Enter] when the focus has disappeared confirms that one of the hidden conversations was focused.

**Comment by auchri** [comment]
Related to #980

**Comment by telegramdesktop** [comment]
Fixed in 0.8.51
