### ISSUE TITLE
Telegram Desktop crashes when an animated sticker is shown on a Raspberry Pi 4

### ISSUE THREAD

**Issue by the-real-cyberpatrol** [telegramdesktop/tdesktop#9831]
### Steps to reproduce
1. Start Telegram Desktop on a Raspberry Pi 4 with 4 GB.
2. Read a channel or group in which an animated sticker is shown or write a message and try to include an animated sticker.

### Expected behaviour
Telegram keeps working and the channel or group and the sticker are displayed correctly.

### Actual behaviour
Telegram Desktop crashes as soon as an animated sticker is displayed. It's not possible to read a channel or group when such a sticker was posted.

### Configuration
**Operating system:**
Arch Linux ARM (armv7h) with Xfce on a Raspberry Pi 4.

**Version of Telegram Desktop:**
2.2.0

**Installation source (Linux Only)** - the official website / GitHub releases / flatpak / snap / distribution package:
Distribution package: community/telegram-desktop 2.2.0-2

**Used theme**:
Classic

<details><summary><b>Console output</b>:</summary>
$ telegram-desktop<br>
[ALSOFT] (EE) Failed to set real-time priority for thread: Operation is not permitted (1)<br>
error: : cannot open<br>
error: : cannot open<br>
error: : cannot open<br>
qt.svg: Error while inflating gzip file: SVG format check failed<br>
qt.svg: Error while inflating gzip file: SVG format check failed<br>
[swscaler @ 0x95ae2200] No accelerated colorspace conversion found from yuv420p to bgra.<br>
Aborted (memory dump written)
</details>

**Comment by ilya-fedin** [comment]
ffmpeg asm optimizations bug
https://gitlab.alpinelinux.org/alpine/aports/-/issues/11722
