### ISSUE TITLE
[macOs Big Sur, 2.4.7] Can't record video messages

### ISSUE THREAD

**Issue by SaintNK** [telegramdesktop/tdesktop#9835]
### Steps to reproduce
1. Open tg desktop
2. One time click on microphone icon at "Write a message..." field
![image](https://user-images.githubusercontent.com/17924803/100702523-66759f80-33d4-11eb-948a-7f1f23686db3.png)

### Expected behaviour
Microphone icon should be replaced by camera icon and I should be able to record video messages

### Actual behaviour
Nothing happens, there is microphone icon and I can only record voice messages

 **N.B.** Telegram app has permission to use camera, if I start a call - I can turn on camera and people see me, but functionality to record a video message disappeared

### Configuration
**Operating system:** macOs Big Sur 11.0.1

**Version of Telegram Desktop:** 2.4.7

**Used theme**: Dark

**Comment by john-preston** [comment]
@SaintNK There was no such option in Telegram Desktop :( There is one in another macOS Telegram app, you can find it here: https://macos.telegram.org/

**Comment by SaintNK** [comment]
@john-preston wow, sorry then, but it would be cool to add such a function to this application
