### ISSUE TITLE
[Feature Request] Ability to hide folders column

### ISSUE THREAD

**Issue by FrdsAlm** [telegramdesktop/tdesktop#9839]
I like to keep the chat apps small on my desktop. Telegram folders doesn't look good when the windows is at it minimum size. It occupies a lot of space and ruins the clean aesthetics. 

Ability to hide the folders column from the left side of the window. Which can be brought back by clicking on a small arrow or a keyboard shortcut

Alternatively folders can be moved to the top like mobile app which can be scrolled using mouse wheel.
![image](https://user-images.githubusercontent.com/38285719/100823024-7eebc580-3479-11eb-8bd6-fb9f2a0960f1.png)

**Comment by ilya-fedin** [comment]
#7534
