### ISSUE TITLE
Option for disable libappindicator usage

### ISSUE THREAD

**Issue by ngleb** [telegramdesktop/tdesktop#984]
Since last update to 0.8.48 on Xubuntu 14.04 Telegram started to use libappindicator which is the worst thing I can imagine. Now if I want to open the window, I press the button, then choose menu item insted of just clikcing on tray icon (also known as notification icon). Is it possible to disable such feature and use regular notification icon which is simpler?

**Comment by auchri** [comment]
You can uninstall libappindicator and tdesktop will use the Qt-Icon

**Comment by ngleb** [comment]
Actually, it will break some packages in the system. I already tried it. For example, NetworkManager GUI won't work without libappindicatior (also transmission), so sometimes I have no choice.

**Comment by Aokromes** [comment]
this issue is still valid on 1.9.8?

**Comment by ngleb** [comment]
Is it possible to build telegram with Gtk3 integration but without appindicator? I moved to gentoo and their ebuild requires appindicator when gtk3 is used, not sure why.

**Comment by ilya-fedin** [comment]
> I moved to gentoo and their ebuild requires appindicator when gtk3 is used, not sure why.

gtk integration does nothing when telegram is linked to qt dinamically. Just activate gtk3/gtk2 file dialog in qt5ct.

**Comment by Johnnynator** [comment]
> > I moved to gentoo and their ebuild requires appindicator when gtk3 is used, not sure why.
> 
> gtk integration does nothing when telegram is linked to qt dinamically. Just activate gtk3/gtk2 file dialog in qt5ct.

Someone should document that somewhere. A.g. Arch has it enabled.

**Comment by ilya-fedin** [comment]
There are no appindicator anymore...
