### ISSUE TITLE
Gnome Wayland desktop crashes after clicking on a second YouTube link

### ISSUE THREAD

**Issue by dmp1ce** [telegramdesktop/tdesktop#9841]
### Steps to reproduce
1. Click on YouTube link.
2. Click on a second YouTube link
3. Notice entire Gnome Wayland desktop crashes.

### Expected behaviour
The second YouTube link should open in browser.

### Actual behaviour
Gnome desktop crashes and I have to restart the entire Gnome session.

### Configuration
**Operating system:** Arch Linux running Gnome with Wayland

**Version of Telegram Desktop:** 2.4.7

**Installation source (Linux Only)** Community repository of Arch Linux https://www.archlinux.org/packages/community/x86_64/telegram-desktop/ `pacman -S telegram-desktop` 

**Used theme**: Tinted theme

**Comment by ilya-fedin** [comment]
Please check with the official binary, arch repos contain bugged ffmpeg 4.3.

**Comment by ilya-fedin** [comment]
And if the WHOLE session crashes, that feels like a gnome bug.
