### ISSUE TITLE
Default speaker does not broadcast on audio calls with secondary monitor connected

### ISSUE THREAD

**Issue by BTCAlchemist** [telegramdesktop/tdesktop#9842]
### Steps to reproduce
1. Install Telegram on Windows 10 with default speaker for audio (default speaker set on the OS as computer speaker).
2. Connect a secondary monitor (with audio speaker) via HDMI cable.
3. Initiate a Telegram voice call.

### Expected behaviour
Voice call audio should broadcast from the default speaker, which is my computer speaker.

### Actual behaviour
Voice call audio broadcasts from the external monitor speaker.

### Configuration
**Operating system:**
Windows 10
**Version of Telegram Desktop:**
2.4.7

<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by ilya-fedin** [comment]
Are you sure that external monitor speak doesn't become the new default communications device?

**Comment by BTCAlchemist** [comment]
Yes, my sound comes from the main computer speaker in all other programs.

**Comment by ilya-fedin** [comment]
> Yes, my sound comes from the main computer speaker in all other programs.

This doesn't mean that main computer speaker is default **communications** device

**Comment by BTCAlchemist** [comment]
> This doesn't mean that main computer speaker is default **communications** device

Hm. What is the difference between the default device and the default communications device?

![image](https://user-images.githubusercontent.com/56145569/100979171-4fc86900-34f8-11eb-9bbf-e0455f9e41ef.png)

**Comment by ilya-fedin** [comment]
> Hm. What is the difference between the default device and the default communications device?

The first is anything except of calls, the second is for calls

**Comment by BTCAlchemist** [comment]
In the Sound control panel, I set the computer speaker as the default communications device, and it works in Telegram now. Thanks, @ilya-fedin!
