### ISSUE TITLE
Crash on memory allocation on audio call

### ISSUE THREAD

**Issue by vlad-lukyanov** [telegramdesktop/tdesktop#9845]
### Steps to reproduce
1. Call from Telegram for Android to Telegram Desktop
2. Answer call on Telegram Desktop

### Expected behaviour
Call started

### Actual behaviour
Telegram Desktop crashed

### Configuration
Calculate Linux Desktop with latest updates, KDE on X11
Calculate Linux is based on Gentoo and uses Gentoo portage tree as package source, but most of packages are build on calculate linux side and installed as binary packages
**Version of Telegram Desktop:**
2.4.11 beta
Telegram for Android version: 7.2.1(2139) arm64-v8a
**Installation source (Linux Only)** - the official website / GitHub releases / flatpak / snap / distribution package:
Gentoo package
On Calculate Linux Desktop
USE flags: +X +dbus +gtk +hunspell +pulseaudio +spell +wayland +webrtc -enchant -libressl -lto
**Used theme**:
default
<details><summary><b>Logs</b>:</summary>
D/tgvoip: === Updating voip config ===
D/tgvoip: {"enable_vp8_encoder":true,"enable_vp8_decoder":true,"enable_vp9_encoder":true,"enable_vp9_decoder":true,"enable_h265_encoder":true,"enable_h265_decoder":true,"enable_h264_encoder":true,"enable_h264_decoder":true,"audio_frame_size":60,"jitter_min_delay_60":2,"jitter_max_delay_60":10,"jitter_max_slots_60":20,"jitter_losses_to_reset":20,"jitter_resync_threshold":0.5,"audio_congestion_window":1024,"audio_max_bitrate":20000,"audio_max_bitrate_edge":16000,"audio_max_bitrate_gprs":8000,"audio_max_bitrate_saving":8000,"audio_init_bitrate":16000,"audio_init_bitrate_edge":8000,"audio_init_bitrate_gprs":8000,"audio_init_bitrate_saving":8000,"audio_bitrate_step_incr":1000,"audio_bitrate_step_decr":1000,"use_system_ns":true,"use_system_aec":true,"force_tcp":false,"jitter_initial_delay_60":2,"adsp_good_impls":"(Qualcomm Fluence)","bad_call_rating":true,"use_ios_vpio_agc":false,"use_tcp":false,"audio_medium_fec_bitrate":20000,"audio_medium_fec_multiplier":0.1,"audio_strong_fec_bitrate":7000}
Invalid return value 0 for stream protocol
Invalid return value 0 for stream protocol
Invalid return value 0 for stream protocol
telegram-desktop: malloc.c:2394: sysmalloc: Assertion `(old_top == initial_top (av) && old_size == 0) || ((unsigned long) (old_size) >= MINSIZE && prev_inuse (old_top) && ((unsigned long) old_end & (pagesize - 1)) == 0)' failed.
А</details>

**Additional Info**:
If you call from same phone but using TelegramX for Android everything works

**Comment by ilya-fedin** [comment]
Please don't report gentoo package bugs here.
