### ISSUE TITLE
[Problem Report] Work Mode Doesn't work.

### ISSUE THREAD

**Issue by taha-ghadirian** [telegramdesktop/tdesktop#9848]
### Steps to reproduce
1. Open Telegram.
2. Open Settings.
3. Write 'workmode' text.

### Expected behaviour
Enable work mode dialog appears.

### Actual behaviour
It doesn't work.

### Configuration
**Operating system:** Windows 10

**Version of Telegram Desktop:** 2.4.7

### NOTE: 
**Also some of other [Hidden-modes](https://github.com/telegramdesktop/tdesktop/wiki/Hidden-modes) doesn't work. Ex: testmode,

**Comment by ilya-fedin** [comment]
there's no workmode/testmode anymore

**Comment by RememberTheAir** [comment]
Related: #7483

**Comment by taha-ghadirian** [comment]
> there's no workmode/testmode anymore

Why test mode is gone?!

**Comment by RememberTheAir** [comment]
@taha-ghadirian see https://github.com/telegramdesktop/tdesktop/issues/7483#issuecomment-605544827

**Comment by taha-ghadirian** [comment]
> @taha-ghadirian see [#7483 (comment)](https://github.com/telegramdesktop/tdesktop/issues/7483#issuecomment-605544827)

Yes I see, Its for Work-Mode that can handled by Folders.
And for accessing Test servers?

**Comment by RememberTheAir** [comment]
@taha-ghadirian not sure but I think now it's CRTç+ALT + click on "add account" in the sidebar

**Comment by taha-ghadirian** [comment]
> @taha-ghadirian not sure but I think now it's CRTç+ALT + click on "add account" in the sidebar

![image](https://user-images.githubusercontent.com/36773254/101152725-b8b6fa80-3638-11eb-85cd-4f3aa7debe39.png)
I don't think it's gain access to test servers.

**Comment by RememberTheAir** [comment]
It's ALT+SHIFT+right click
