### ISSUE TITLE
[Feature Request] Ability to increase days with mouse scolling in schedule messages popup

### ISSUE THREAD

**Issue by amirmahdi-nsh** [telegramdesktop/tdesktop#9849]
### Is your feature request related to a problem?
That problem which is a little hard to create schedule message just for 1 or 2 days later.

### Describe the solution you'd like
Ability to increase days by using mouse scroll in Reschedule popup and in send schedule messages popup.
![2020-12-04_21-12-1607103006](https://user-images.githubusercontent.com/67676939/101194850-c9d12d00-3673-11eb-9ca0-d8aeab9f6052.jpg)

### Additional context
I think this idea can also be used for time(increase 1 hour by mouse scrolling)

**Comment by ilya-fedin** [comment]
According to https://github.com/telegramdesktop/tdesktop/issues/6557#issuecomment-663063216, this is possible since 2.1.13

**Comment by amirmahdi-nsh** [comment]
> According to [#6557 (comment)](https://github.com/telegramdesktop/tdesktop/issues/6557#issuecomment-663063216), this is possible since 2.1.13

Yes, you are right. the problem was that feature didn't work in Sway WM and I think it's a bug in sway
thanks
