### ISSUE TITLE
[Feature Request] Rescheduling multiple messages at once

### ISSUE THREAD

**Issue by Drayko** [telegramdesktop/tdesktop#9851]
### Is your feature request related to a problem?
No

### Describe the solution you'd like
Rescheduling multiple messages at once when I select them, may have an option to rescheduling all messages selected to an hour

### Describe alternatives you've considered
When I select multiple messages with right click i see options: copy, send, delete and clear. Another option could be: Reschedule

**Comment by Neurotoxin001** [comment]
What the point of doing that? Why do you need to send multiple messages at one time?
