### ISSUE TITLE
Formatting sticks until second word of next line

### ISSUE THREAD

**Issue by renyhp** [telegramdesktop/tdesktop#9855]
### Steps to reproduce
1. Write a message, don't send
2. Select the message and format it (bold, italic, or whatever)
3. Insert newline and type two words

### Expected behaviour
Both words inserted in step 3 should be not formatted

### Actual behaviour
The first word in step 3 is formatted

### Configuration
**Operating system:** Xubuntu 20.04.1

**Version of Telegram Desktop:** 2.4.7

**Installation source (Linux Only)** - the official website

**Comment by jq2** [comment]
Confirmed.

**Comment by renyhp** [comment]
This is fixed now!
