### ISSUE TITLE
Do Not Disturb is still ignored at macOS

### ISSUE THREAD

**Issue by VitalyEmelyanov** [telegramdesktop/tdesktop#9857]
### Steps to reproduce
1. Turn on Do Not Disturb
2. Receive a message

### Expected behaviour
The message sound should not appear

### Actual behaviour
The message sound is still present

I saw there were some similar issues in the past, and they were closed. But the problem is still present, despite this functionality seems to be very basic.

### Configuration
**Operating system:** macOS Big Sur 11.0.1

**Version of Telegram Desktop:** 2.4.11

**Used theme**: Default

UPD: Still not fixed in  v4.2.3 at macOS 12.6

**Comment by VitalyEmelyanov** [comment]
This is still not fixed. Any suggestions for this problem?

**Comment by Aokromes** [comment]
you are using telegram for macos not telegram desktop.

**Comment by postrou** [comment]
I use telegram desktop, and I have this issue.

specs: macbook pro 15 2018
os: macOS Monterey 12.0.1
tg version: 3.3

**Comment by change-agent** [comment]
I have this issue too.

**Comment by ewqqx** [comment]
I guess this issue been here since forever. 

Telegram from AppStore. 
Monterey 12.3.1 (21E258)
MacBook Pro (13-inch, M1, 2020)

**Comment by ShadowJonathan** [comment]
Especially with Focus mode coming to macOS, this has still not been fixed, can this be bumped up?

**Comment by almottier** [comment]
It is not working for calls either. Very annoying 😢

**Comment by VitalyEmelyanov** [comment]
Still not fixed, version 4.2.3 at macOS 12.6.
Two major versions since this issue is created, and still such basic info is not working properly.
Now Mac has these awesome Focus modes, and Telegram is the only app that ignores it so far...

**Comment by ShadowJonathan** [comment]
Discord also ignores it, last time i checked.

**Comment by ilya-fedin** [comment]
Given that tdesktop is open source, you're free to submit a fix for this issue. Here's the current DnD check implementation: https://github.com/telegramdesktop/tdesktop/blob/7b5781b84573ba02cf968b093fa37f23c6b4cb3f/Telegram/SourceFiles/platform/mac/notifications_manager_mac.mm#L32-L47

**Comment by VitalyEmelyanov** [comment]
The way the app is handling DND seems to be not working anymore since Big Sur. I did not manage to find much, but this looks like a possible way to handle focus modes: https://developer.apple.com/forums/thread/682143
I'm not very proficient in macos development, can someone help with this?

**Comment by ShadowJonathan** [comment]
@VitalyEmelyanov this is related to the Focus Status api, not the notification API. It is intended to pass on DnD statuses in-app, not to filter notifications with.

If telegram would use Focus Status, then no notification would be displayed at all if the user selects "focus status" in the focus preferences. This is deliberately disjointed with the actual application selection for notification filtering, as it is meant to be an entirely different concept (availability) to the notification api (notifications).

**Comment by dakyskye** [comment]
I hope this issue will get fixed soon.

**Comment by ilya-fedin** [comment]
@dakyskye there's still no idea how to fix this

**Comment by ShadowJonathan** [comment]
There is an idea how to fix this, the development will and resources are just not there; embed an audio transcoder so that macOS notification sounds are delivered in the right format, and/or have only default-sound notifications deliver their sound through the Notification Center

**Comment by ilya-fedin** [comment]
Well, maybe there's a way to fix this without implementing that feature, e.g. with some private system APIs

**Comment by ShadowJonathan** [comment]
Then the question of "will it break" will not be a question of "when", but "if". I highly recommend against using any private API.

**Comment by ilya-fedin** [comment]
It might be that there never will be time to implement the proper solution

**Comment by ShadowJonathan** [comment]
For future reference, the commit seems to be https://github.com/telegramdesktop/tdesktop/commit/32e650548f2786e10917503a76aeb637f9826362

---

In it, I see you're basically checking for *any* focus mode, basically?

That seems acceptable, but isn't as configurable as something the likes of focus filters might be, but alas.

**Comment by john-preston** [comment]
@ShadowJonathan Yup :(

Well, better than before. If it works :D

**Comment by ShadowJonathan** [comment]
Agreed, some people's configurations will likely not work with this, but mine will.

**Comment by john-preston** [comment]
Should be fine in 4.6.12 beta.

**Comment by ptxmac** [comment]
Not working for me in 4.7.0

**Comment by john-preston** [comment]
@ptxmac Is it the version from the website or the version from MacAppStore?

**Comment by john-preston** [comment]
@ptxmac Yes, unfortunately there I can't get the status because of the sandbox. It should work in the version from the website.

**Comment by ptxmac** [comment]
@john-preston thanks! I expected apple to have a way to query the focus status. I guess the "correct" way to do it would be that all sounds Telegram makes go through the notifications API instead.

**Comment by john-preston** [comment]
@ptxmac Yes, but right now this is not planned, sorry. Apple doesn't provide a way to query it and it looks like it actively prevents apps from getting this information, closing one way after another :(

**Comment by ShadowJonathan** [comment]
@john-preston would a focus filter be a way to do it via the appstore version?

**Comment by almottier** [comment]
Should it mute the ringtone when receiving a call too?
