### ISSUE TITLE
Copy paste bug in SourceFiles/mainwindow.cpp 

### ISSUE THREAD

**Issue by qarmin** [telegramdesktop/tdesktop#9858]
True and false have same value

https://github.com/telegramdesktop/tdesktop/blob/638ea3111f0b069147880fc47b1843114f288d20/Telegram/SourceFiles/mainwindow.cpp#L905-L907

**Comment by qarmin** [comment]
This is a bug

**Comment by john-preston** [comment]
@qarmin I was experimenting with different sizes and finally both cases had the same result, no matter what is the digits count. Yes, it could be simplified to just fontSize = 12; else fontSize = 22; now.
