### ISSUE TITLE
Duplicated expressions in both sides of |

### ISSUE THREAD

**Issue by qarmin** [telegramdesktop/tdesktop#9859]
- [ ] - https://github.com/telegramdesktop/tdesktop/blob/e283b4895b240b3b613d39294a126ec0cb808c2f/Telegram/SourceFiles/data/data_peer.cpp#L164
- [ ] - https://github.com/telegramdesktop/tdesktop/blob/e283b4895b240b3b613d39294a126ec0cb808c2f/Telegram/SourceFiles/history/history_message.cpp#L1061-L1062
- [ ] - https://github.com/telegramdesktop/tdesktop/blob/e283b4895b240b3b613d39294a126ec0cb808c2f/Telegram/SourceFiles/data/data_session.cpp#L374
- [ ] - https://github.com/telegramdesktop/tdesktop/blob/e283b4895b240b3b613d39294a126ec0cb808c2f/Telegram/SourceFiles/data/data_session.cpp#L562

**Comment by qarmin** [comment]
This is a bug, which still happens

**Comment by john-preston** [comment]
@qarmin This is a feature. By using `|` expression here I get another type (not Flag, but base::flags<Flag>).
