### ISSUE TITLE
German translation for chat history is ambigious

### ISSUE THREAD

**Issue by ManuelSchneid3r** [telegramdesktop/tdesktop#986]
![](http://storage2.static.itmages.com/i/15/0810/h_1439246124_5721592_781ad2382f.png)

Translated this means "delete chat history" and "delete history", which is almost semantically identical. Correct terms would be, well "delete chat history" or "delete history" for the first and "Delete chat" for the second, which is "Verlauf löschen" for the first and "Chat löschen" for the latter.

**Comment by auchri** [comment]
Thank you, improvent in 0.8.50
