### ISSUE TITLE
unicode keymappings are not working in chat

### ISSUE THREAD

**Issue by Parveshdhull** [telegramdesktop/tdesktop#9860]
In linux emojis can be mapped to keyboard keys, for fast emoji typing, like

`xmodmap  -e  "keycode 49 = U1F44D U1F64F"`

https://github.com/Parveshdhull/emoji-keyboard

But for some reason nothing is happening in chat box when key is pressed, while it works everywhere.

**Comment by ilya-fedin** [comment]
Are you that it works in other Qt applications?

**Comment by Parveshdhull** [comment]
yes, it works everywhere else.

I also tried autokey
https://github.com/autokey/autokey

autokey has many ways of automatic pasting. All failed in telegram, except shift+insert.

I don't know what chat box is doing but after that autokey also freezes.

**Comment by ilya-fedin** [comment]
> yes, it works everywhere else.

Usually when people say "everywhere else", it turns out that Telegram is the only Qt application on their computer and they checked in Gtk applications and not Qt applications.

**Comment by Parveshdhull** [comment]
@ilya-fedin 
Thanks for pointing out that. You were right telegram was only Qt application in my computer.

I tried in another Qt applications and it didn't worked. Same like telegram.
https://www.archlinux.org/packages/community/x86_64/maui-nota/

Can you suggest me any solution for this? Should I report bug for Qt or is this expected behavior.

**Comment by ilya-fedin** [comment]
> Can you suggest me any solution for this? Should I report bug for Qt or is this expected behavior.

I have no idea how that xmodmap magic works, probably you should open a bug report for Qt and ask Qt developers.

**Comment by Parveshdhull** [comment]
Thanks!

**Comment by Parveshdhull** [comment]
**Issue Status:**
https://bugreports.qt.io/browse/QTBUG-89184
https://bugreports.qt.io/browse/QTBUG-65765

**Comment by ilya-fedin** [comment]
1. tdesktop is QtWIdgets-based, not QtQuick-based, unlike maui-note.
2. Other examples of QtWidgets-based applications are VLC and qBittorrent, you could try with them.

**Comment by Parveshdhull** [comment]
@ilya-fedin Thanks for correcting me. I checked in VLC and it has same problem. I updated bug report.

**Comment by Parveshdhull** [comment]
Hey @ilya-fedin,
There is a update on report and a fix is released. Author asked me to verify. But unfortunately I don't know how to apply patch and build and all.

Report: https://bugreports.qt.io/browse/QTBUG-89184
Fix: https://codereview.qt-project.org/c/qt/qtbase/+/251703

**Comment by Parveshdhull** [comment]
**UPDATE**
Bug fixed in Qt 6.0.1

https://bugreports.qt.io/browse/QTBUG-89184

**Comment by ilya-fedin** [comment]
tdesktop won't update to Qt 6 in near two years
