### ISSUE TITLE
[Feature Request] Make a global setting for emoji skin tone

### ISSUE THREAD

**Issue by jaimemnds** [telegramdesktop/tdesktop#9861]
Hey all,

Currently we need to select the skin tone individually for each emoji we enter and for which skin tones apply.
This is nothing new, as many chatting apps recognized this problem already and allow you to setup a default skin tone or those emoji. To avoid need for API support, this could be made as a local setting.

UIs for this feature were already design by the community like this one by DanyGee: https://tx.me/designers/146.

Thanks in advance.

**Comment by ilya-fedin** [comment]
#3339
