### ISSUE TITLE
Get Notifications When DND is Enabled on MacOS

### ISSUE THREAD

**Issue by ILLKX** [telegramdesktop/tdesktop#9862]
### Steps to reproduce
1. Enable Do Not Disturb mode in MacOS.
2. Ask one of your friends or any other contacts/groups that you didn't mute him/her to send a message to you.
3. You will still get a _ding_ sound.

### Expected behaviour
No sound would be played.

### Actual behaviour
I can clearly hear the notification sound from telegram.

### Configuration
**Operating system:**
MacOS big sur 11.0.1
![https://i.loli.net/2020/12/08/b4Ss6gRqlxYAG7M.png](https://i.loli.net/2020/12/08/b4Ss6gRqlxYAG7M.png)

**Version of Telegram Desktop:** 2.4.7

**Installation source (Linux Only)** - the official website / GitHub releases / flatpak / snap / distribution package:

**Used theme**: Telegram default dark mode

<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by ilya-fedin** [comment]
#9857
