### ISSUE TITLE
Constant crashes on MacOS Big Sur after latest update 11.0.1 (20B29)

### ISSUE THREAD

**Issue by championshuttler** [telegramdesktop/tdesktop#9863]
### Steps to reproduce
1. open telegram
2. Video call someone via telegram desktop
3. boom goes the dynamite

It keeps happening very frequently.

### Expected behaviour
Should not crash

### Actual behaviour

Crashes in few seconds in video call

### Configuration
**Operating system:**

Macos Big Sur

7.2.4 

Thanks for such a great app. Kudos to everyone. Let me know if i need to submit crash reports. I need help in generating them though

**Comment by ilya-fedin** [comment]
> 7.2.4

latest version telegram desktop is 2.4.7, you're using not telegram desktop, but other app

**Comment by championshuttler** [comment]
> > 7.2.4
> 
> latest version of telegram desktop is 2.4.7, you're using not telegram desktop, but other app

Hmm 
<img width="254" alt="image" src="https://user-images.githubusercontent.com/22130317/101472828-1c119700-396f-11eb-8533-0e8b6508b45f.png">

Is. not it the official telegram https://macos.telegram.org/, also see the version listed on the page please

**Comment by ilya-fedin** [comment]
> Is. not it the official telegram https://macos.telegram.org/, also see the version listed on the page please

No, this bugtracker is for https://desktop.telegram.org

**Comment by championshuttler** [comment]
Thanks for the info filed the bug there sorry for the noise
