### ISSUE TITLE
Adding users to groups with hidden chat history will automatically include latest messages

### ISSUE THREAD

**Issue by averima** [telegramdesktop/tdesktop#9864]
Messages from hidden history groups are automatically forwarded without prompt when adding new members exposing private messages.

### Steps to reproduce
1. Add new member to group with chat history selected as hidden
2. Latest messages are automatically forwarded without prompt

### Expected behaviour
Mobile versions of Telegram will prompt for sending the latest messages to the newly invited member. There should be similar option to choose if user wants to include newest messages. For hidden chat history it should be off by default. 

### Actual behaviour
Telegram desktop does not prompt for including chat history. Private messages from hidden history chats will be forwarded to person who should not receive them.

### Configuration
Operating system: Windows 10

Version of Telegram Desktop: Version 2.4.7

**Comment by heatherkovich69** [comment]
Wtf

**Comment by heatherkovich69** [comment]
How to remove

**Comment by RememberTheAir** [comment]
Still an issue, or rather a lack of an option to forward these 100 messages or not

**Comment by averima** [comment]
This issue is still relevant.

**Comment by RememberTheAir** [comment]
unstale: https://github.com/telegramdesktop/tdesktop/issues/9864#issuecomment-870354436
