### ISSUE TITLE
Hotkeys and scrolling from touch screen don't work in comments section

### ISSUE THREAD

**Issue by Muhammadrasul446** [telegramdesktop/tdesktop#9865]
Hotkeys, like <kbd>Ctrl+Up</kbd> to reply to latest message and scrolling from touch screen don't work in comments. Scrolling works in regular chats, I'm using touch screen laptop. 
### Steps to reproduce
1. Hotkeys, like <kbd>Ctrl+Up</kbd> to reply to latest message don't work
2. Scrolling from touch screen using a touch screen laptop doesn't work

### Expected behaviour
Everything to work like in regular chats

### Actual behaviour
Nothing works

### Configuration
**Operating system:** Debian 10 Buster

**Version of Telegram Desktop:** 2.4.7

**Installation source (Linux Only)** - the official website

**Used theme**: Dark

**Comment by ilya-fedin** [comment]
#8692

**Comment by Muhammadrasul446** [comment]
@Aokromes What about touch screen scrolling?

**Comment by ilya-fedin** [comment]
@Muhammadrasul446 create a separate issue

**Comment by Aokromes** [comment]
the 2nd i am sure it's duplicate too.
