### ISSUE TITLE
Is "Last seen" only an indicator of interaction with Telegram?

### ISSUE THREAD

**Issue by rpodric** [telegramdesktop/tdesktop#9866]
Because it seems to me that if you put Telegram off to the side so that it's no longer in focus, and you do other things, then the clock starts ticking. Your contacts will see "Last seen 1 hour ago" after an hour of that even though Telegram is still running and you're still there.

That's not optimal and also not the way other similar programs I've used work, such as Skype. They look at system activity (mouse and/or keyboard) on the system in general, not just with the given program, since the whole purpose of the feature is to determine availability, not when Telegram was last touched, which is irrelevant.

**Comment by TGDebug** [comment]
To answer your question, 
yes, "Last seen" is the time since the last interaction (e.g. having the app open and in foreground on your mobile device, or having telegram desktop in focus on PC).
