### ISSUE TITLE
Xss in gamebot Telegram

### ISSUE THREAD

**Issue by keworr** [telegramdesktop/tdesktop#9867]
## Gamebot telegram escape character only on client.

Gamebot Telegram generate base64 link for game like http://tbot.xyz/math/#base64_bla_bla&game=hash
if your nick was \<h1\>Reworr, then in base64 will \&lt;h1\&gtReworr, but if change the nickname into in base64 to \<h1\>Reworr\</h1\>, then:

![image](https://user-images.githubusercontent.com/47640060/101545971-f8b31000-399f-11eb-8248-79d822ef3067.png)

![image](https://user-images.githubusercontent.com/47640060/101548863-8f81cb80-39a4-11eb-96c6-9fda08ec81e0.png)

### Steps to reproduce for black hat
1. Open game in gamebot telegram
2. Add js/html code in nickname in base64 string (example, img src with cookie on requestbin or fake auth form Telegram)
3. Distribute your link
4. Profit!

### Solve
Escape characters

**Comment by ilya-fedin** [comment]
how tdesktop is related to this?

**Comment by keworr** [comment]
¯\_(ツ)_/¯
