### ISSUE TITLE
Make tdesktop look native / Do not set Qt style to win by default

### ISSUE THREAD

**Issue by ManuelSchneid3r** [telegramdesktop/tdesktop#987]
Telegram does not use the gtk style which uses gtk+ engine to render the widgets. Please do not do this. Just do not set it manually at all. As far as I know qt takes the correct style automatically.

Further reads:
http://doc.qt.io/qt-5/qstyle.html#details
http://doc.qt.io/qt-4.8/qgtkstyle.html#details

**Comment by Yanpas** [comment]
Also stop using Open Sans, distance between symbols in some alphabets (russian e.g.) is too big

**Comment by evgenymarkov** [comment]
Linux users want native file dialog and tray menu! QFileDialog does not use the native dialog by default?

**Comment by telegramdesktop** [comment]
I do nothing with the styles, but I use Qt static build, perhaps that is the cause of non-native look.

**Comment by nortexoid** [comment]
Proper theming would be nice, but native picker would be even better. I don't how they do it, but Chrome on linux manages to chooses the gtk picker on Gnome and the kde picker ("KDE File Dialog Widget") on KDE. I would at least be happy with proper theming!

**Comment by ManuelSchneid3r** [comment]
@nortexoid This would introduce unneccesary dependencies. Qt way is to do it platform independent. 

@telegramdesktop At lest the style set manually get [overidden](https://github.com/telegramdesktop/tdesktop/blob/85a2fb18764a4b75a6443636814ee6dbf7349a5c/Telegram/SourceFiles/main.cpp#L69).

**Comment by Yanpas** [comment]
@ManuelSchneid3r Why would it introduce dependecies? Make algorithm like: if there is gtkpeeker - use gtkpeeker, if there is KDE-file-dialog - use kdefile dialog. Otherwise use native. Chrome doesn't have any dependencies

**Comment by nortexoid** [comment]
@Yanpas Sounds right to me. The Qt5 build of QupZilla I'm using doesn't have any GTK/KDE dependencies but it still allows the use of native file picker.

**Comment by solbjorn** [comment]
@Yanpas, Qt-based applications should automatically use system-wide look without any algorithms. As @ManuelSchneid3r said, currently there is an overrride of default style in Telegram code (through fake args), that prevents it.

**Comment by Lesik** [comment]
Everybody seems to be talking only about looks. Sure, looks are important, but this issue is much more urgent than just looks. For example, mounted network drives, or "favourite places" are not shown in Telegram's file picker, although they exist in the native file picker. Another thing is that there is no file preview of the selected file on the right side. These are useful things and it's really annoying to not have those in the desktop client.

**Comment by orschiro** [comment]
I completely subscribe to @Lesik's comment. Thank you for highlighting the visual impairments that affect productivity directly!

**Comment by michaldaniel** [comment]
Please.  File picker is really annoying to use and that is big shame considering how well Telegram works with media.

**Comment by telegramdesktop** [comment]
@michaldaniel If it is something easy and I just do not know how to do that, a pull request fix will be much appreciated. But it should not bring any new dependencies for the resulting binary (it should check library availability at runtime and use them only when they are available or static link them).

**Comment by funksen** [comment]
the main problem is not the style, but the lack of a picture preview

as a workaround I just use the default filebrowser and drag the image to the telegram window which works just perfectly

**Comment by orschiro** [comment]
> as a workaround I just use the default filebrowser and drag the image to the telegram window which works just perfectly

Cool workaround. Thanks for sharing! :)

~ Robert

**Comment by michaldaniel** [comment]
@telegramdesktop I have not idea what is the reason, as far as I know QT should use GTK by default if not overriden. I'll give it a try soon anyway as I love Telegram. Don't really count on much tho, it's not like I've done any QT development before.

**Comment by orschiro** [comment]
@michaldaniel and others, 

hluk, developer of CopyQ, has successfully done the same [here](https://github.com/hluk/CopyQ/issues/388#issuecomment-143543410). 

Maybe you can draw some inspiration? 

~ Robert

**Comment by ManuelSchneid3r** [comment]
Just to clarify as diskussed in #982, this issue is about the style in general. The context menu of the systray icon is affected and presumably every not explicitely styled widget too.

What prevents Telgram widget to be rendered with the native renderer is [this line](https://github.com/telegramdesktop/tdesktop/blob/85a2fb18764a4b75a6443636814ee6dbf7349a5c/Telegram/SourceFiles/main.cpp#L69) in the code:

```
QByteArray args[] = { "-style=0" }; // prepare fake args
```
Is this fake arg really needed?

Just to show the effect: My own Qt application started without parameters: (Well integreated Vertex theme)
![Image](http://i.imgur.com/pDCXvXF.png)
My own Qt application started with --style=0 parameter: (Ugly fallback Winlike theme)
![Image](http://i.imgur.com/7Drqjod.png)

**Comment by AndydeCleyre** [comment]
@telegramdesktop, why is the style explicitly set to zero? What is the purpose of "fake args?"

**Comment by TotalKrill** [comment]
I am using Manjaro linux, tried to compile the binart and removing the "--style=0" fake argument from the binary. I can set environment variables for different apps but i cannot get the Telegram binary to swith to the native file-dialog

**Comment by ManuelSchneid3r** [comment]
Just to clearify again [this bug is NOT about the filechooser](https://github.com/telegramdesktop/tdesktop/issues/987#issuecomment-156718272). For filechoser check #982.

**Comment by telegramdesktop** [comment]
@TotalKrill I'm sure this argument did nothing with the filechooser.

@ManuelSchneid3r I don't quite remember what forced me to dislike reading of QT_STYLE_OVERRIDE env variable :( The main idea is to make the app look as designed in all the supported systems, but it seems that tray icon menu is not controlled by me anyway. Are there any other controls that depend on that argument? Except tray icon context menu.

**Comment by TotalKrill** [comment]
@telegramdesktop This argument does nothing as you say. I do also agree that this issue is not about the filechooser **only**. I will continue my filechooser quest in #982. 

For the --style=0 however, I would recommend to remove it unless it is really needed for something specific, having hardcoded arguments kind of destroys the point a bit. Maybe put that argument inside of the telegram.desktop file instead.

**Comment by telegramdesktop** [comment]
Currently I was forced to rollback the "--style=0" param, because it has very important meaning in some of the environments, see https://github.com/telegramdesktop/tdesktop/issues/1774

**Comment by melvinvermeeren** [comment]
@telegramdesktop I've been trying to get portable builds of a patched telegram I maintain for a few days. And it seems that this can be fixed more properly by adding `-no-gtkstyle -no-glib` to the Qt build options.

After this is works on a Xubuntu 16.04 system without the `-style=0` argument. I cannot confirm how this might impact other platforms.

For others interested in build scripts (main is ubuntu_xenial atm) and what not, check out:
https://git.mel.vin/telegram_desktop/builds

**Comment by BOOtak** [comment]
@telegramdesktop @ManuelSchneid3r I've made PR for it https://github.com/telegramdesktop/tdesktop/pull/2221

**Comment by melvinvermeeren** [comment]
@BOOtak I still find it rather odd that a Qt application gives me a GTK file picker of any sort since I use KDE myself. With this PR however I doubt that `-no-gtkstyle -no-glib` can be added to the Qt configure arguments. Which effectively means `-style=0` needs to be forced still.

**Comment by john-preston** [comment]
I've added -no-gtkstyle in the latest 0.9.57 alpha version (instead of "-style=0" fake param).
I cannot let Qt to load gtk, because it loads gtk-2, while I sometimes load gtk-3 for libappindicator3 and everything crashes.
I'm using gtk file dialog in 0.9.57 alpha version when it is available.

**Comment by png2378** [comment]
Works **great** for me, thanks! (elementary OS 0.4)
![](http://storage5.static.itmages.ru/i/16/0708/h_1467975919_4466982_9119ef9718.png)

**Comment by ManuelSchneid3r** [comment]
@john-preston Note that this option changes in [Qt 5.7](https://github.com/qt/qtbase/commit/899a815414e95da8d9429a4a4f4d7094e49cfc55)

**Comment by michaldaniel** [comment]
@ManuelSchneid3r Looks like they are replacing it with "-no-gtk" or am I reading this wrong?

**Comment by john-preston** [comment]
@ManuelSchneid3r I'm not moving to Qt 5.7 in the near future, at least widely — they drop support for many versions of Windows and one more OS X. I'm still not ready to develop two versions for Windows like I do for OS X :/

**Comment by TotalKrill** [comment]
The usage of the GTK filechooser is a big improvement to the software, what is the stance on making it optional to provide your own theme to the application and how hard would it be to implement?

**Comment by KAMiKAZOW** [comment]
> The usage of the GTK filechooser is a big improvement to the software

No, it is not and worst of all --no-gtkstyle does not work in 0.10.1

**Comment by AndydeCleyre** [comment]
@TotalKrill and @KAMiKAZOW 

I think everything regarding theming will be hacky, rigid, and partial until (if) #1815 gets prioritized.

**Comment by YtvwlD** [comment]
@KAMiKAZOW Yes, this is a bit annoying if your desktop environment uses Qt.

**Comment by Aokromes** [comment]
#667 ?

**Comment by theel0ja** [comment]
![image](https://cloud.githubusercontent.com/assets/5832930/24506618/bf0e63f6-1566-11e7-8c95-bb6834763de5.png)
Context menu has been fixed in 1.0.26.

**Comment by Aokromes** [comment]
#2958 imho better ticket.

**Comment by stek29** [comment]
@Aokromes they're a bit different, this one is for Linux :)

**Comment by Aokromes** [comment]
maybe, but it's sort of generic issue, people wanting a setting to allow to select how GUI is :)
cc https://github.com/telegramdesktop/tdesktop/issues/4358

**Comment by ManuelSchneid3r** [comment]
Actually this one is solved for me. Everything looks fine.
