### ISSUE TITLE
No window scrolling with touchpad

### ISSUE THREAD

**Issue by shooash** [telegramdesktop/tdesktop#9872]
Hi! I am unable to scroll chats and contacts lists with the touchpad even after I select any contact or message. I can still scroll the windows by the scrollbar, with standard mouse and the keyboard arrows. I've had this issue for months.
The interesting part is that the touchpad scrolling starts to work after I connect the mouse, scroll with it and to a three-finger gesture (switch desktop in my case). When the mouse is disconnected Telegrams stops responding to scrolling gesture.

### Steps to reproduce
1. Open chat
2. Try to scroll with the touchpad
3. 

### Expected behaviour
The lists should scroll as do all other apps.

### Actual behaviour
Nothing happens. 

### Configuration
Windows 10

Ver. 2.4.11 beta and previous.

Base theme with and without night mode.

**Comment by ilya-fedin** [comment]
Can't reproduce, I'm able to scroll with two fingers
