### ISSUE TITLE
[visual] lot of space between "search" and "options" icons

### ISSUE THREAD

**Issue by RememberTheAir** [telegramdesktop/tdesktop#9873]
### Steps to reproduce
1. open a chat

### Expected behaviour
The lens icon should be placed near the three dots menu

### Actual behaviour
There's quite some space between the two icons since v2.4.13:

![Telegram_2020-12-09_17-22-23](https://user-images.githubusercontent.com/16143208/101656811-6bc19280-3a43-11eb-95a1-be917c9f400a.png)

### Configuration
**Operating system:** Windows 10

**Version of Telegram Desktop:** 2.4.13

**Used theme**: default dark

<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by ilya-fedin** [comment]
Icons just take care of covid-19 ;)
