### ISSUE TITLE
Please fix fonts between screens and modals

### ISSUE THREAD

**Issue by WuglyakBolgoink** [telegramdesktop/tdesktop#9875]
Wrong utf-8 characters:
![image](https://user-images.githubusercontent.com/2271337/101704196-80724a80-3a84-11eb-839c-b205a65b5100.png)

![image](https://user-images.githubusercontent.com/2271337/101704169-74868880-3a84-11eb-83d5-ca8cf9a4197b.png)

![image](https://user-images.githubusercontent.com/2271337/101704218-8a944900-3a84-11eb-8711-c3f8da790c81.png)

and in user profile the fonts will be correct showed:

![image](https://user-images.githubusercontent.com/2271337/101704242-96800b00-3a84-11eb-8061-f87459649121.png)

macos app

**Comment by ilya-fedin** [comment]
#2520

**Comment by ilya-fedin** [comment]
#6056
