### ISSUE TITLE
[Question] Build instructions for CMake under Ubuntu 14.04

### ISSUE THREAD

**Issue by TrueBober** [telegramdesktop/tdesktop#9877]
Good afternoon. Why isn't the manual updated?

**Comment by ilya-fedin** [comment]
The instructions are only for environment that are used by developers, all others are unsupported.

**Comment by TrueBober** [comment]
I didn't quite understand your answer. I am trying to build a debug version. But I can't, because the instructions for building under Linux are outdated

**Comment by ilya-fedin** [comment]
Maybe I don't understand your question. Do you ask "why the manual doesn't use a newer Ubuntu version?"? If yes, then the answer is that we don't want to use newer Ubuntu versions for build.

**Comment by TrueBober** [comment]
No. This instruction is outdated: https://github.com/telegramdesktop/tdesktop/blob/dev/docs/building-cmake.md (NB: they are outdated.)
But why isn't it updating?

**Comment by ilya-fedin** [comment]
Ah. I don't know ¯\_(ツ)_/¯. Probably no one has a time or a wish for that.

**Comment by TrueBober** [comment]
(⌣́_⌣̀)

**Comment by john-preston** [comment]
@ilya-fedin Because now Linux version is built in CentOS7 docker container.

**Comment by ilya-fedin** [comment]
> Because now Linux version is built in CentOS7 docker container.

Yeah, but he asks why no one updated the instruction

**Comment by TrueBober** [comment]
> @ilya-fedin Because now Linux version is built in CentOS7 docker container.

But what about development?

**Comment by ilya-fedin** [comment]
> But what about development?

in docker :)

**Comment by john-preston** [comment]
@TrueBober Now you can clone the repository, install docker and run:

tdesktop/Telegram/build/docker/centos_env/prepare.sh

This will set up the environment in a "tdesktop:centos_env" docker image.

After that you can run:

docker run -it --rm -v /path/to/tdesktop:/usr/src/tdesktop tdesktop:centos_env scl enable devtoolset-8 -- bash

and you'll be able to go to /usr/src/tdesktop/Telegram, run there "configure.sh" and go to /usr/src/tdesktop/out and run "make", like at the end of the outdated instructions.

**Comment by TrueBober** [comment]
OK, thank you very much
