### ISSUE TITLE
[Question] Telegram PDB

### ISSUE THREAD

**Issue by TGDebug** [telegramdesktop/tdesktop#9882]
Hey,

I'm trying to look into something and currently need to correlate the IDA Pro output and the source code.
A PDB would simplify this process 1000 times.

I'll be honest, I'm too lazy to set up the whole dev. environment just to get the .exe + .pdb.

I've tried to get them via GitHub actions, but it seems like the artifacts are not getting uploaded.

So, can someone please provide a telegram.exe with the associated .pdb. 
Anything from the last year or two would actually do the job just as fine as the current release.

It would help out quite a lot, thanks in advance :)

**Comment by TGDebug** [comment]
@john-preston would you maybe be able to provide the pdb?

**Comment by TGDebug** [comment]
@23rd

**Comment by 23rd** [comment]
[github.com/23rd/tdesktop/suites/1700936161/artifacts/32017504](https://github.com/23rd/tdesktop/suites/1700936161/artifacts/32017504)

**Comment by TGDebug** [comment]
Thanks a lot, 
if there is any way to donate you via Bitcoin, let me know.
