### ISSUE TITLE
[Bug] Telegram Desktop crashes when trying to copy and paste picture from dialog

### ISSUE THREAD

**Issue by garipovroma** [telegramdesktop/tdesktop#9885]
### Steps to reproduce
1. Copy picture from any dialog
2. Paste picture to any dialog

### Expected behaviour
...

### Actual behaviour
Telegram app will crash

### Configuration
**Operating system:** Ubuntu 19.10

**Version of Telegram Desktop:** 2.4.13 Beta

**Installation source (Linux Only)** - the official website / GitHub releases / flatpak / snap / distribution package: official website

**Used theme**: default

<details><summary><b>Logs</b>:</summary>
<a href="https://pastebin.com/AYz3WuEj">pastebin-link</a>
</details>

**Comment by tarcisioe** [comment]
I'm also using this version (2.4.13 beta) on two Arch Linux installs, my laptop and my desktop. On both, Telegram hangs when pasting by pressing ctrl+v, or when I right-click the message box to get the context menu that has the "paste" option.

**Comment by tarcisioe** [comment]
Some more info thta may be useful: CPU Usage is low and memory usage does not increase. The GUI just hangs and I have to kill the process and reopen Telegram. Also, I just can't copy and paste images from it to itself (text works normally).

**Comment by Aokromes** [comment]
cannot reproduce on build from desktop.telegram.org / github on windows, for sure archlinux package only bug.

**Comment by tarcisioe** [comment]
No, I use the version in the official website and @garipovroma said in the issue he does as well.
