### ISSUE TITLE
Bold and Italic Fonts are being used in Telegram app

### ISSUE THREAD

**Issue by anjanik012** [telegramdesktop/tdesktop#9886]
Telegram suddenly started using italic and bold fonts. All other apps use system fonts. I've not updated my system, nor rebooted. 
![image](https://user-images.githubusercontent.com/24349858/101766274-91fd3600-3b08-11eb-960b-73bac150cd26.png)

### Steps to reproduce
1. Open Telegram

### Expected behavior
Telegram desktop should use system fonts as it used to before.

### Actual behavior
Fonts have suddenly become bold and italic.

### Configuration
Operating System: Arch Linux
KDE Plasma Version: 5.20.4
KDE Frameworks Version: 5.76.0
Qt Version: 5.15.2
Kernel Version: 5.4.82-1-lts

**Version of Telegram Desktop:**2.4.7

**Installation source (Linux Only)** -  distribution package: [Arch Linux](https://www.archlinux.org/packages/community/x86_64/telegram-desktop/)

**Used theme**: Night Mode

**Comment by ilya-fedin** [comment]
Please check terminal messages, this could be an issue of how Telegram is built in your distro

**Comment by anjanik012** [comment]
~  telegram-desktop 

(process:55370): Telegram-WARNING **: 21:39:31.751: Unfortunately, GTK integration conflicts with qgtk2 platformtheme and style. Therefore, QT_QPA_PLATFORMTHEME and QT_STYLE_OVERRIDE will be unset.
Telegram-Message: 21:39:31.753: This can be ignored by setting TDESKTOP_I_KNOW_ABOUT_GTK_INCOMPATIBILITY environment variable to any value, however, if qgtk2 theme or style is used, this will lead to a crash.
Telegram-Message: 21:39:31.754: GTK integration can be disabled by setting TDESKTOP_DISABLE_GTK_INTEGRATION to any value. Keep in mind that this will lead to clipboard issues and tdesktop will be unable to get settings from GTK (such as decoration layout, dark mode & more).

**(process:55370): Telegram-WARNING **: 21:39:31.754: Application was built without embedded fonts, this may lead to font issues.**
Telegram-Message: 21:39:32.017: You can disable tray icon counter with TDESKTOP_DISABLE_TRAY_COUNTER and make it look better if it is monochrome.
[ALSOFT] (EE) Failed to set real-time priority for thread: Operation not permitted (1)
error: : cannot open
error: : cannot open
error: : cannot open
qt.svg: Error while inflating gzip file: SVG format check failed
qt.svg: Error while inflating gzip file: SVG format check failed
qt.svg: Error while inflating gzip file: SVG format check failed

**Comment by anjanik012** [comment]
terminal output says that it was built without embedded fonts. What does it mean?

**Comment by ilya-fedin** [comment]
> Application was built without embedded fonts, this may lead to font issues.

This is a distro issue. They should build with embedded fonts or provide Open Sans as a hard (not optional) dependency, Telegram can't work right without Open Sans.

**Comment by anjanik012** [comment]
So I guess it should be fixed after installing open sans fonts?

**Comment by ilya-fedin** [comment]
Yeah, it should be.

**Comment by anjanik012** [comment]
Thanks!!!

**Comment by anjanik012** [comment]
Installing Open Sans solved the issue. I'll report this there to the package maintainers.
