### ISSUE TITLE
Extremely high CPU usage when VPN is disconnected and killswitch is on

### ISSUE THREAD

**Issue by thansk** [telegramdesktop/tdesktop#9887]
### Steps to reproduce
1. Enable "kill switch" on a commercial VPN
2. Disconnect from VPN

### Expected behaviour
Telegram should stay at 0-2% CPU load like it does when I turn off Wi-Fi or when I can connect to the internet.

### Actual behaviour
Usage rises to constant 25% with jumps to 50-70%

### Configuration
**Operating system:** Ubuntu 20

**Version of Telegram Desktop:** 2.4.13

**Installation source (Linux Only)** - the official website / GitHub releases / flatpak / snap / distribution package: GitHub releases

**Used theme**: Default

**Comment by ilya-fedin** [comment]
#8068
