### ISSUE TITLE
[Bug] Call to myself?

### ISSUE THREAD

**Issue by vladislav805** [telegramdesktop/tdesktop#9888]
### Steps to reproduce
1. Open Saved Messages

### Expected behaviour
Button "call" do not shown.

### Actual behaviour
Button "call" is shown. When pressed, the call opens and after a few seconds it is dropped.
![image](https://user-images.githubusercontent.com/10882576/101772809-eac6d180-3afc-11eb-8c6a-2d98c14bbccc.png)

### Configuration
**Operating system:** Arch Linux / Xfce4

**Version of Telegram Desktop:** 2.4.13 beta

**Installation source (Linux Only)** - the official website / GitHub releases / flatpak / snap / distribution package: official website

**Used theme**: Tinted

**Comment by vladislav805** [comment]
Also in the channels between the search icon and three dots empty space appeared.
![image](https://user-images.githubusercontent.com/10882576/101813749-30e85900-3b2e-11eb-808b-a879a5f16bbd.png)

**Comment by ilya-fedin** [comment]
> Also in the channels and chats between the search icon and three dots empty space appeared.

#9873

**Comment by vladislav805** [comment]
Fixed in 2.4.14 beta.
