### ISSUE TITLE
Entering a group call volumes down all the audio

### ISSUE THREAD

**Issue by michele-grifa** [telegramdesktop/tdesktop#9889]
### Steps to reproduce
1. Start any background audio or music
2. Start or enter a group call
3. Volume of background audio is too low

### Expected behaviour
Background audio should remain normal

### Actual behaviour
Background audio is too low

### Configuration
**Operating system:** Windows 10 v1909

**Version of Telegram Desktop:** 2.4.13

**Comment by ilya-fedin** [comment]
#8192
