### ISSUE TITLE
[Voice Group] Can't assign mouse button to voice record shortcut

### ISSUE THREAD

**Issue by Geczy** [telegramdesktop/tdesktop#9890]
Can't assign mouse button to voice record shortcut

<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by alirezaopmc** [comment]
![image](https://user-images.githubusercontent.com/35873101/123526463-5107f000-d6ed-11eb-8b8c-04688a4b8cb2.png)
My voice button disappear sometimes, is it as the same as this topic or a new issue must be commited?
