### ISSUE TITLE
Some errors at launching

### ISSUE THREAD

**Issue by RafaelLinux** [telegramdesktop/tdesktop#9892]
For some reason, I was not able to launch Telegram from desktop (nothing appeared). Then I tried from console, and it works. However, I observe this errors:
`[ALSOFT] (EE) Failed to set real-time priority for thread: Operación no permitida (1)
error: : cannot open
error: : cannot open
error: : cannot open
qt.svg: Error while inflating gzip file: SVG format check failed
qt.svg: Error while inflating gzip file: SVG format check failed
qt.svg: Error while inflating gzip file: SVG format check failed
qt.svg: Error while inflating gzip file: SVG format check failed
qt.svg: Error while inflating gzip file: SVG format check failed
qt.svg: Error while inflating gzip file: SVG format check failed
qt.svg: Error while inflating gzip file: SVG format check failed
  OpenType support missing for "DAOpenSansRegular", script 14
`
Telegram works, but I want to notice those extrange errors.

I can yet launch Telegram from desktop, but each time I launch from console, those errors appear.

Operating System: openSUSE Leap 15.2
KDE Plasma Version: 5.20.3
KDE Frameworks Version: 5.76.0
Qt Version: 5.15.1
Kernel Version: 5.3.18-lp152.50-default
OS Type: 64-bit
Processors: 4 × Intel® Core™ i5-6600K CPU @ 3.50GHz
Memory: 31.3 GiB of RAM

**Comment by ilya-fedin** [comment]
It's ok, that's just toolkit messages

**Comment by RafaelLinux** [comment]
Well, I understand they were errors, not warnings, that's why I notify.

I close issue then
