### ISSUE TITLE
Telegram is freezed, but after ctrl+V pasting image file

### ISSUE THREAD

**Issue by dasturchiuz** [telegramdesktop/tdesktop#9894]
### Steps to reproduce
1. Use Ctrl+c to copy to clipboard image
2. open other user and ctrl + V

### Expected behaviour
Telegram is freezed

### Configuration
**Operating system:**
Debian 10

**Version of Telegram Desktop:**
telegram desktop 2.4.13 BETA
**Installation source (Linux Only)** - the official website / GitHub releases / flatpak / snap / distribution package:

**Comment by ilya-fedin** [comment]
#9885
