### ISSUE TITLE
[Feature Request] Add @admin pseudo role to mention

### ISSUE THREAD

**Issue by snowinmars** [telegramdesktop/tdesktop#9897]
There's a lot of scenarios where I need to mention an admin in big chat. F.e. if a spam message was sended.

Request: `@admin` role that will mention all admins of the channel.

Now this could be implemented by bot, f.e. [mentionrobot](https://ru.botostore.com/c/mentionrobot/), but I'd like to see this feature as core functionality.

Thanks for your time.

**Comment by Aokromes** [comment]
https://bugs.telegram.org/c/11
