### ISSUE TITLE
Crash on Wayland (freebsd)

### ISSUE THREAD

**Issue by timsofteng** [telegramdesktop/tdesktop#9898]
Hello. I'm using Freebsd and Wayland. Telegram crashes with Wayland and with xwayland. With pure xorg it works fine.

Look at the attachment please. Here is output when I start it with `QT_WPA_PLATFORM=wayland` variable.
![20201212_160219_535594784340976485](https://user-images.githubusercontent.com/51912173/101986482-b850dc00-3c96-11eb-9a6b-3127e45f876d.jpg)

### Actual behaviour
Crash

### Configuration
Freebsd 12.2

**Telegram-desktop 2.3.2**

**Comment by Aokromes** [comment]
2.3.2? update to 2.4.13.

**Comment by timsofteng** [comment]
> 2.3.2? update to 2.4.13.

Are you sure problem is due to the version?

**Comment by timsofteng** [comment]
Ok, it works with xwayland now with last version which is in freebsd repo. But native support with `QT_QPA_PLATFORM=wayland` still doesn't.

**Comment by ilya-fedin** [comment]
Looks like this is some error from qtwayland, no one here can help you
