### ISSUE TITLE
[Voice Group] - Audio loss during a group call via airpods 2

### ISSUE THREAD

**Issue by kyemets** [telegramdesktop/tdesktop#9899]
### Steps to reproduce

1. Join a group call
2. Airpods 2 as a microphone source
3. Press the "microphone" button (turn on the microphone for a group call)
4. Press the "microphone" button Again (turn off the microphone for a group call)
5. Lost the sound in the group call

### Expected behaviour
The audio in a group call (audio of participants) must be audible

### Actual behaviour
Loss of sound during a group call when the microphone is turned off again

### Configuration
Windows 10 Pro
version: 20H2
the build of the OS: 19042.685

**Version of Telegram Desktop:**
2.4.13 beta

**Installation source (Linux Only)** - the official website / GitHub releases / flatpak / snap / distribution package:

**Used theme**:
Tinted

**Visual reproduction**
![tg-report](https://user-images.githubusercontent.com/61251118/101987757-20a7b980-3ca7-11eb-9ae7-cecd5257761d.png)

**Comment by ilya-fedin** [comment]
Is this still valid?

**Comment by kyemets** [comment]
> Is this still valid?

 In version 2.6 beta, this problem has been resolved
