### ISSUE TITLE
Generic, scriptable build instructions

### ISSUE THREAD

**Issue by adnelson** [telegramdesktop/tdesktop#990]
I'm wondering if there are any instructions out there (if indeed it is possible) for building tdesktop in an automated way, e.g. via a Makefile or similar. I want to be able to build a customized version and be able to repeat or modify the build whenever I need to, which requires scripting. As it currently stands, the build instructions all seem to depend on some sort of point-and-click software such as XCode, QtCreator, etc.

**Comment by auchri** [comment]
No, such instructions are not available

**Comment by michaelsproul** [comment]
Why did this issue get closed? Having to step through pages of instructions copy-pasting commands certainly isn't an optimal build process.

**Comment by mordillo123** [comment]
Hi all, to have a Makefile script will be a great idea (imho).
Please could you reopen this issue?

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/blob/dev/.travis/build.sh :)

**Comment by Aokromes** [comment]
this issue is still valid after latest cmake migration?

**Comment by Aokromes** [comment]
poke.

**Comment by Aokromes** [comment]
@adnelson

**Comment by Aokromes** [comment]
no answer after more than 1 month, closing.

**Comment by adnelson** [comment]
Thanks, sorry I was awol on this but this is good to go
