### ISSUE TITLE
[Bug] Caller not hearing any voice

### ISSUE THREAD

**Issue by MarouaneMan** [telegramdesktop/tdesktop#9900]
### Steps to reproduce
1. Settings -> Advanced -> Call Settings -> Choose right Input Device.
2. Make call.
3. Caller hearing me on Skype but not on Telegram (using same input device), only voice messages are working as expected.

Tried everything to make it work including turning off firewall / antivirus, downgrading to 2.4.5, upgrading to beta...

### Configuration

**Device input info :** samling rate 48khz, 2 channel, 16 bit

**Audio Driver :** Realtek 6.0.8751.1 (11/07/2019)

**Operating system:** Windows 10 Pro 20H2

**Version of Telegram Desktop:** 2.4.7 (tried last beta version also)

**Used theme**: Classic

**Comment by ilya-fedin** [comment]
#8443
