### ISSUE TITLE
Fullwidth spaces are shown as regular spaces

### ISSUE THREAD

**Issue by emanuele6** [telegramdesktop/tdesktop#9901]
### Steps to reproduce
1. example message: https://t.me/bugreportfortelegramdesktop12312/3

### Expected behaviour
Fullwidth spaces should be shown as fullwidth spaces (as on the android app); respecting the fact that they are [**fullwidth** characters](https://en.wikipedia.org/wiki/Halfwidth_and_fullwidth_forms).
![photo_2020-12-13_02-31-39](https://user-images.githubusercontent.com/20175435/102000806-5cfd0900-3ceb-11eb-921b-5585334b3e44.jpg)

### Actual behaviour
Fullwidth spaces are shown as regular spaces (causing unexpected misalignment).
![msg](https://user-images.githubusercontent.com/20175435/102000828-a77e8580-3ceb-11eb-918c-d9c286b4a83f.png)
NB: this is not a font issue; these characters are actually regular spaces (`0x20`) even though the message contains fullwidth spaces:
 ![file](https://user-images.githubusercontent.com/20175435/102000832-c4b35400-3ceb-11eb-8179-7250a2e75866.png)

### Configuration
**Operating system:** ArchLinux (`Linux 5.4.81-1-lts`)

**Version of Telegram Desktop:** `2.4.7-4`

**Installation source (Linux Only)** - the official website / GitHub releases / flatpak / snap / distribution package: `pacman`

**Used theme**: Classic (night mode)

**Comment by ilya-fedin** [comment]
This is not a bug, tdesktop replaces all special spaces with regular ones.
https://github.com/desktop-app/lib_ui/blob/a02c8923dc6d00bcb4f4c2b1470cd48e2743903a/ui/text/text.cpp#L3427-L3436

**Comment by emanuele6** [comment]
@ilya-fedin, but that character should have the same dimension as a fullwidth character.

**Comment by ilya-fedin** [comment]
¯\_(ツ)_/¯

**Comment by emanuele6** [comment]
I haven't lost interest, but, if you guys don't care about the issue, it's fine.

**Comment by ilya-fedin** [comment]
i gues it's something like 'wontfix'
