### ISSUE TITLE
Ctrl+V doesn't work after Prt Sc to instantly send screenshots to the recipient

### ISSUE THREAD

**Issue by Ritika-Das** [telegramdesktop/tdesktop#9904]
### Steps to reproduce
1. Press Prt Sc to take a screenshot of the entire window
2. Open Telegram Desktop and click on the "Write a Message" bar
3. Press Ctrl+V

### Expected behaviour
I was expecting my screenshot to have automatically been dropped to the recipient, with an option to add Caption and hit Send.

### Actual behaviour
Ctrl+V shortcut doesn't work to paste the screenshotted information. Instead it pastes the previously stored Clipboard text, if any.

### Configuration
It is running on **Ubuntu 20.04**

**Version of Telegram Desktop: 2.4.7**

**Installation source (Linux Only)** - snap

**Used theme**: Light

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/9885
