### ISSUE TITLE
Version of Telegram Desktop isn't shown on running telegram-desktop --version command

### ISSUE THREAD

**Issue by Ritika-Das** [telegramdesktop/tdesktop#9905]
### Steps to reproduce
1. Open Terminal
2. Run the command <code>telegram-desktop --version</code>
3. Hit Enter

### Expected behaviour
I was expecting for the installed Telegram Desktop's version to be displayed as a result.

### Actual behaviour
It shows the following error : 

<code>(process:6973): Telegram-WARNING **: 16:15:11.320: Unfortunately, GTK integration conflicts with qgtk2 platformtheme and style. Therefore, QT_QPA_PLATFORMTHEME and QT_STYLE_OVERRIDE will be unset.
Telegram-Message: 16:15:11.337: This can be ignored by setting TDESKTOP_I_KNOW_ABOUT_GTK_INCOMPATIBILITY environment variable to any value, however, if qgtk2 theme or style is used, this will lead to a crash.
Telegram-Message: 16:15:11.337: GTK integration can be disabled by setting TDESKTOP_DISABLE_GTK_INTEGRATION to any value. Keep in mind that this will lead to clipboard issues and tdesktop will be unable to get settings from GTK (such as decoration layout, dark mode & more).
Qt: Session management error: Could not open network socket</code>

### Configuration
It is running on **Ubuntu 20.04**

**Version of Telegram Desktop: 2.4.7**

**Installation source (Linux Only)** - snap

**Used theme**: Light

It would be nice to get the version number using just a command, or if any other command for the same exists which I am unaware of, please let me know. 
I really like the Light mode of the Desktop App, but the version number isn't quite visible at first glance.

**Comment by ilya-fedin** [comment]
tdesktop is not a terminal application, this is not a bug
