### ISSUE TITLE
Audio input/output selection during calls

### ISSUE THREAD

**Issue by ldeluigi** [telegramdesktop/tdesktop#9906]
### Is your feature request related to a problem?
The problem is that often telegram desktop is unable to select the correct audio device even if is set to default.

### Describe the solution you'd like
I'd like some drop-down menus like button in the call windows to select audio device both for input and for output of the call.

### Describe alternatives you've considered
In the settings of the app, the same dropdowns menus for audio selection for calls.

### Additional context
If necessary I'll provide.

**Comment by ilya-fedin** [comment]
Settings -> Advanced -> Call Settings

**Comment by ldeluigi** [comment]
Thanks
