### ISSUE TITLE
Audio Wrong Durations , Sticker Packs not opening - BETA

### ISSUE THREAD

**Issue by navidmafi** [telegramdesktop/tdesktop#9910]
### Steps to reproduce
1. Restarted PC
2. Restarted Telegram
3. Cleared Media Cache 

### Actual behaviour
Showing Audio Wrong Durations 
and every pack in chat when im clicking on it , does not open and says "This Pack Not found"
### Configuration
**Operating system:**
Windows 8.1 
**Version of Telegram Desktop:**
Latest Beta (forgot numbers) 
**Installation source (Linux Only)** - the official website / GitHub releases / flatpak / snap / distribution package:

**Used theme**:
Main Telegram Theme

**Comment by Brawl345** [comment]
I can at least confirm the "sticker pack not found" on every sticker pack. Version is 2.4.13 beta.

**Comment by toxyxd** [comment]
> every pack in chat when im clicking on it , does not open and says "This Pack Not found"

can confirm on 2.4.13 beta

**Comment by navidmafi** [comment]
Fixed on  version 2.4.14 , update !
