### ISSUE TITLE
New messages don't appear on desktop unless mobile app is opened first.

### ISSUE THREAD

**Issue by Yoshimaster96** [telegramdesktop/tdesktop#9911]
### Steps to reproduce
1. Read all messages (on either mobile, web, or desktop), then close out of the app.
2. Wait for more messages.
3. Open the web or desktop app.

### Expected behaviour
New messages should appear as normal.

### Actual behaviour
New messages don't appear at all. To get them to appear you must open the mobile app and read some messages, then open the desktop or web app and they should appear as normal.

### Configuration
**Operating system:**
Windows 10 64-bit for desktop app, Firefox for web app

**Version of Telegram Desktop:**
2.3.1

**Used theme**:
Light

**Comment by Aokromes** [comment]
plz update to at least 2.4.13

**Comment by ilya-fedin** [comment]
Can't reproduce, new messages appear as normal.

**Comment by Yoshimaster96** [comment]
2.4.7 is the latest version I can download from Telegram's website. IDK where 2.4.13 is.

**Comment by nepumuk-fs** [comment]
The bug also appears in [1.5.11 on debian stable](https://packages.debian.org/buster/telegram-desktop).
I don't get any message from any group here. Chats with single people seem to be not affected.

**Comment by ilya-fedin** [comment]
Old versions were disabled server-side AFAIK

**Comment by Aokromes** [comment]
> The bug also appears in version [1.5.11 on debian stable](https://packages.debian.org/buster/telegram-desktop).
> I don't get any message from any group here. Chats with single people seem to be not affected.

it's very very bad idea to stuck to distributions packages, and even more to one who stays 2 years on same versions, on telegram development they are a lot of fixes and new features.
