### ISSUE TITLE
Problem after update or after closing 

### ISSUE THREAD

**Issue by khali17** [telegramdesktop/tdesktop#9912]
Hi ! 
Today I lost electricity and some of my telegrams on desktop was opened 
After startup ,I lunch them but see that some of them lost channels and groups just see chats ! 
While another telegram have every thing ok 
One of telegrams which opened with problem is opened on phone, there I have all groups and channels ! 
Try to clean install on another pc but nothing ! look like that see just chats !
In settings, I don't change any thing , and it's first time this problem see .
When I search for group or channel I see them in my list without massage quality , when enter them see that I am their follower ! And then can see it in the list ! 
Is there anyway to correct this problem ??

**Comment by Aokromes** [comment]
try to download telegram desktop portable and run telegram from there, for sure your data directory is corrupted.

**Comment by khali17** [comment]
> try to download telegram desktop portable and run telegram from there, for sure your data directory is corrupted.

Thanks for answer , The problem is these telegrams are portable 

But I tried on another pc new one, install portable ( clean install First time installed there ) and the problem stay ))
