### ISSUE TITLE
Media buttons in audio player not working on Bluetooth headset.

### ISSUE THREAD

**Issue by glebanaHACKER** [telegramdesktop/tdesktop#9914]
### Steps to reproduce
1. Connect Bluetooth headset
2. Play music
3. Use media button play/pause on headset

### Expected behaviour
Audio paused

### Actual behaviour
Audio is playing

### Configuration
**Operating system:**
Windows 10 enterprise 19041.685
**Version of Telegram Desktop:**
2.4.7
**Installation source (Linux Only)** - the official website / GitHub releases / flatpak / snap / distribution package:

**Used theme**:
Tinted
<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by ilya-fedin** [comment]
Aleady fixed in 2.4.13

**Comment by glebanaHACKER** [comment]
Thanks!
