### ISSUE TITLE
[Feature Request] Audio settings in app

### ISSUE THREAD

**Issue by tonyrulez** [telegramdesktop/tdesktop#9916]
### Is your feature request related to a problem?
In Windows the voice chat audio doesn't go to the default output device, even though all sounds come out of it. See [issue #418](https://github.com/telegramdesktop/tdesktop/issues/418) where I mentioned this. Even the call dial tone goes to default audio output, but not the voice of the call recipient. Happens when I plug in a secondary output device, and set it as default. Even Telegram app restart didn't help. (Windows 10, latest beta build of Telegram).

### Describe the solution you'd like
With voice call, video call, and now group voice call supported by Telegram, there ought to be a proper audio settings page in the app. Change input and output device, test if the input/output device you set is working. Least important, but being able to set microphone sensitivity or volume gate would be also needed.

### Describe alternatives you've considered
Currently no workaround found for the bug I faced, where all Telegram sound went to default output device **except** voice of the call.

**Comment by ilya-fedin** [comment]
> Change input and output device, test if the input/output device you set is working.

Settings -> Advanced -> Call Settings

**Comment by tonyrulez** [comment]
> Settings -> Advanced -> Call Settings

Well, I feel stupid. Haven't seen it but it's there.

**Comment by starbuck3000** [comment]
> Settings -> Advanced -> Call Settings
Thank you!!
