### ISSUE TITLE
'Save As...' of Image in Full Screen blocks Telegram - Process has to be killed

### ISSUE THREAD

**Issue by komape** [telegramdesktop/tdesktop#9917]
### Steps to reproduce
1. Open an Image in full Sścreen
2. Right-Click to open context menu
3. Click on 'Save As...'

### Expected behaviour
File Explorer opens to submit file location and name.

### Actual behaviour
File Explorer opens but "behind" the full screen of the. Full screen cannot be closed, no reaction to 'Esc' or a click on the close in the top right corner. To shut down Telegram, process needs to be killed.

### Configuration
**Operating system:** Linux Ubuntu 20.10
**OS-Type:** 64-bit
**GNOME Version:** 3.38.1
**Windowing System:** X11

**Version of Telegram Desktop:** 2.4.7

**Installation source (Linux Only)**: the official website

**Used theme**: Dark

**Comment by ilya-fedin** [comment]
Can't reproduce, opens in foreground for me

**Comment by ilya-fedin** [comment]
@komape

**Comment by komape** [comment]
@ilya-fedin works again for me. but was definitely reproducible back then. don't know why it's working now.
