### ISSUE TITLE
Emojis bug, Sticker packs bug.

### ISSUE THREAD

**Issue by taha-ghadirian** [telegramdesktop/tdesktop#9919]
[Full Bug Information In Tweeter](https://twitter.com/tahat4tt/status/1338437605596205057)

**Comment by navidmafi** [comment]
#9910

**Comment by taha-ghadirian** [comment]
@navidmafi This problem is for all users and doesn't fix with #9910 Issue.

**Comment by AndrewLaneX** [comment]
Fixed in [2.4.14](https://github.com/telegramdesktop/tdesktop/commit/cb6db82809e99505f19b421c664bfedba0c1dd1b).
