### ISSUE TITLE
[Feature request] Open main window in one click (linux)

### ISSUE THREAD

**Issue by m00nk** [telegramdesktop/tdesktop#992]
Please, change the reaction to the clicks on the tray icon:
- left click opens the main window
- right click opens the menu.

Now both left and right clicks open the menu.

Thank you.

**Comment by ralesk** [comment]
I'm on linux (KDE 4) and primary button click does not bring up the menu at all.

**Comment by dielsonsales** [comment]
> Now both left and right clicks open the menu.

Yea, it's happening on Gnome 3.

**Comment by m00nk** [comment]
it is on XFCE too.

**Comment by davidbaumann** [comment]
So I'd also be happy to see this, I am runnning Ubuntu 15.04.
Most Applications just open and focus the main window, when clicking/double clicking the tray icon. I think that's the way it should work.

**Comment by kanishkablack** [comment]
its been an request for really long time, let try to patch the code

**Comment by ralesk** [comment]
I've since switched to XFCE (Fedora 23) and main button click opens the window, no menu.

**Comment by ralesk** [comment]
Do all of you use right-handed mouse?

**Comment by davidbaumann** [comment]
Yes here


-------- Ursprüngliche Nachricht --------
Von: Henrik Pauli <notifications@github.com>
Gesendet: 18. Januar 2016 17:37:49 MEZ
An: telegramdesktop/tdesktop <tdesktop@noreply.github.com>
CC: David <davidbaumann@gmx.de>
Betreff: Re: [tdesktop] [Feature request] Open main window in one click (linux) (#992)

Do all of you use right-handed mouse?

---
Reply to this email directly or view it on GitHub:
https://github.com/telegramdesktop/tdesktop/issues/992#issuecomment-172580069
-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by ralesk** [comment]
Hmm, I kinda hoped it was left-handed mouse confusing the tray icon, but apparently not.

**Comment by vanitasvitae** [comment]
Any news on this?

**Comment by m00nk** [comment]
It is working in version 0.10.19 (on MATE). 
I think this issue may be closed.

**Comment by vanitasvitae** [comment]
Its still not working on GNOME Shell 3.22.1 (Telegram 0.10.19), so please DO NOT close this.

**Comment by EgZvor** [comment]
Also on XFCE when clicking on a tray icon first time the menu has somewhat limited size and therefore a scroll and after that it just has a bigger size whish it should be doing right away

**Comment by EgZvor** [comment]
Also on XFCE when clicking on a tray icon first time the menu has somewhat limited size and therefore a scroll and after that it just has a bigger size which it should

**Comment by stek29** [comment]
@EgZvor Seems like it's separate issue.

**Comment by alleyoopster** [comment]
I found by removing libappindicator-gtk2/3 resolved the issue.

**Comment by vanitasvitae** [comment]
@alleyoopster At least now you can open the window with one click. Thank you :)
Hiding the window by clicking again does not work unfortunately, but its a start :+1:

**Comment by m00nk** [comment]
The libraries libappindicator-gtk* are absent in my system. The issue still is under XFCE4 (left click opens Telegram menu, right click opens the xfce panel menu).

**Comment by alleyoopster** [comment]
The name depends on the distro. I'm using Arch Linux. It could be libappindicator* on Debian based.

**Comment by m00nk** [comment]
I'm using Linux Mint 18 (the clone of Ubuntu 16).

**Comment by alleyoopster** [comment]
Ubuntu is based on Debian so the package name should still be the same in Mint. It maybe a little trickier to remove with dependencies but Mint Forums are very helpful.

**Comment by vanitasvitae** [comment]
Unfortunately there are quite some apps with a libappindicator dependency (ring, blueman...)

**Comment by auchri** [comment]
Please try 1.0.29

**Comment by m00nk** [comment]
Version 1.0.29 still does not work like it have to on XFCE (Mint 18). Left click opens Telegram menu, right click opens xfce panel menu.

**Comment by vanitasvitae** [comment]
Works fine on Gnome Shell now! Thank you!

**Comment by yohanson** [comment]
A workaround with libappindicator installed. Try to run Telegram with overridden environment variables:
```
DESKTOP_SESSION=Other XDG_CURRENT_DESKTOP=Other Telegram
```

More info is in the code:
* ['Compute' function that detects OS](https://github.com/telegramdesktop/tdesktop/blob/master/Telegram/SourceFiles/platform/linux/linux_desktop_environment.cpp#L23)
* ['PreferAppIndicatorTrayIcon' function that enables appindicator for selected OSes](https://github.com/telegramdesktop/tdesktop/blob/master/Telegram/SourceFiles/platform/linux/linux_desktop_environment.cpp#L118)

Works with Xfce 4.12 on Debian 9.

**Comment by akkk33** [comment]
> A workaround with installed libappindicator. Try to run Telegram with overridden environment variables:
> 
> ```
> DESKTOP_SESSION=Other XDG_CURRENT_DESKTOP=Other Telegram
> ```
> More info is in the code:
> 
> * ['Compute' function that detects OS](https://github.com/telegramdesktop/tdesktop/blob/master/Telegram/SourceFiles/platform/linux/linux_desktop_environment.cpp#L23)
> * ['PreferAppIndicatorTrayIcon' function that enables appindicator for selected OSes](https://github.com/telegramdesktop/tdesktop/blob/master/Telegram/SourceFiles/platform/linux/linux_desktop_environment.cpp#L118)
> 
> Works with Xfce 4.12 on Debian 9. Telegram Desktop 1.2.17.

Just small edit that works in Manjaro XFCE4
`DESKTOP_SESSION=Other XDG_CURRENT_DESKTOP=Other Telegram`

**Comment by jwsp1** [comment]
Facing the same issues on Zorin 15 (Based on Ubuntu 18.04.2, Gnome shell 3.30). 
Left click on the symbol in taskbar opens the same context menu as a right click does.

**Comment by ralesk** [comment]
I have a feeling it might be the desktop environments / frameworks messing with things... but who knows.  I'm on MATE (also GTK 3 like Gnome Shell) and none of my chat applications do anything for LMB click now (Slack, Discord, Telegram, you name it — Slack used to have the LMB = menu problem a few months ago).

**Comment by vanitasvitae** [comment]
> Facing the same issues on Zorin 15 (Based on Ubuntu 18.04.2, Gnome shell 3.30).
Left click on the symbol in taskbar opens the same context menu as a right click does.

For me it works (Antergos, Gnome Shell 3.32.1)

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/commit/3b4dfa138176b4d1e3cb14be1be638ebe2f52713
