### ISSUE TITLE
Copy / Paste is broken in Wayland while using non-english keyboard layout

### ISSUE THREAD

**Issue by tomastan** [telegramdesktop/tdesktop#9921]
### Steps to reproduce
1. Run Telegram on a standard Wayland session
2. Copy text outside Telegram
3. Switch to non-english layout (Russian Phonetic in my case if it matters). 
4. Paste using (Ctrl+V, or Mouse left key and "Paste")

Another direction example:
1. Run Telegran on a standard Wayland session
2. Switch to non-english layout (Russian Phonetic in my case if it matters). 
3. Try copying text in Telegram message field using keyboard (Ctrl+C)
4. Try pasting elsewhere

### Expected behaviour
Text should be pasted

### Actual behaviour
Nothing pastes. 

### Configuration
Ubuntu 20.10

Telegram: 2.4.7

**Installation source (Linux Only)** - Snap

**Used theme**: Dark theme

**Comment by ilya-fedin** [comment]
This is a bug in Qt 5.12 that is provided by Canonical in core20 runtime. Qt folks fixed that a lot of time ago, but the fix produced a major rewrite in input processing and was never backported to Qt 5.12. Unfortunately, there's nothing we can do about that and this probably won't be fixed until core22, I recommend you to switch to the official binary.

**Comment by tomastan** [comment]
@ilya-fedin thanks for explanation. 
Not sure if I understand versioning of Qt and snap versioning very well. Does it mean that we just need to wait until things get fixed by Caninical team in next release of Ubuntu? 

Alternatively, what **official** binary do you have in mind?

**Comment by ilya-fedin** [comment]
> Not sure if I understand versioning of Qt and snap versioning very well. Does it mean that we just need to wait until things get fixed by Caninical team in next release of Ubuntu?

Snap has runtimes that provide repository packages based on Ubuntu LTS version. Repository packages (including Qt) are not updated within one distro version. The current latest version of snap runtime is core20 that is based on Ubuntu 20.04 repositories that contain Qt 5.12 with https://bugreports.qt.io/browse/QTBUG-66497. The new Qt version will be available in snap only on the next snap runtime release that is core22 (Ubuntu 22.04).

> Alternatively, what **official** binary do you have in mind?

https://desktop.telegram.org

**Comment by tomastan** [comment]
@ilya-fedin Ok thanks, clear.

Will switch to official binary. Hence until there is no official installable deb or snap, it's not very convenient to use ( https://github.com/telegramdesktop/tdesktop/issues/253)

**Comment by ilya-fedin** [comment]
Unpacking a tar.xz is more convenient than having a repository mess.

**Comment by tomastan** [comment]
From developer's point of view you may be right.

However from user's point of view it's not so obvious. There are different caveats:
1. It's hard to tell your mom by phone how to download, unpack (and not accidentally delete it afterwards).
2. You may unpack different versions and have many of them in your downloads folder and then it's getting really a mess. (Just done that aleady having 2 versions of Telegram running). 
3. You may have multple users using same PC. So you need to repeat the procedure for everyone.
4. You cannot use known software center or package managers to remove app or autoupdate. So you need to keep in mind that Telegram is somehow different.

**Comment by ilya-fedin** [comment]
Creating packages for each distro is not a way to go

**Comment by tomastan** [comment]
> Creating packages for each distro is not a way to go

I don't develop for Linux, but I feel it's a pain when you have deb, snap, rpm, flatpack, appimage and more.. I just share my user experience hassle, and it's for you guys to decide which way to go.
