### ISSUE TITLE
[Feature Request] Improve - There is Bad mixing of RTL & LTR languages words (like Persian&English)

### ISSUE THREAD

**Issue by RexNext** [telegramdesktop/tdesktop#9922]
in telegram Desktop , 
When we type a text message   mix of words in Persian and English language , the order of words is true,
but  after send , words shows in disorder.
![telegram](https://user-images.githubusercontent.com/66295368/102089600-b4a58c80-3e31-11eb-9e73-22b4d84e0fa0.png)
this picture is about good and bad situation before and after send text message ,

the right order of words in RTL direction are {
1-hello
2- درود
3- بر 
4- شما
}
درود بر شما Hello

please solve this problem.
obviously the solution is very simple , in cases that user switch the direction and determine it by (CTRL+SHIFT keys),
the message that will be send , must have direction that user specify and follow the user choice, not default behavior .

just needs check a condition in "text change event" for textbox.
direction.something like this ;

txtBox.on(textChange,fn{
if(CTRL+SHIFT){
txtChunk.direction.toggle();
}
});

دوستان به این پست لایک بزنید، شاید نظرشون برای بهبود این قابلیت جلب بشه. 
ممنونم.

**Comment by nmahdi14** [comment]
yes, writing is difficult when mixing RTL & LTR languages.

**Comment by Mehrshad3** [comment]
I have the same problem. I typed {
با
پاپیتا
می
ZWNJ
توانی
به
جملۀ
Left-to-right-embedding
What
is
خرمالو
in
English
Pop Directional Formatting
جواب
بدهی}
and WhatsApp showed it correctly:
![b4 - Copy](https://user-images.githubusercontent.com/75848143/102708100-a2a26e80-42b5-11eb-9abb-002cee60a059.png)
but Telegram desktop and Telegram for Android don't show correctly and show it like:
![b3 - Copy](https://user-images.githubusercontent.com/75848143/102708112-ba79f280-42b5-11eb-8003-1459f006fb91.png)
please fix it
thanks

**Comment by Mehrshad3** [comment]
> yes, writing is difficult when mixing RTL & LTR languages.

but on WhatsApp it is easy. In general, Telegram is much better than WhatsApp but in this issue, WhatsApp is better.

**Comment by ilya-fedin** [comment]
#5518

**Comment by ahangarha** [comment]
> in telegram Desktop ,
> When we type a text message mix of words in Persian and English language , the order of words is true,
> but after send , words shows in disorder.
> ![telegram](https://user-images.githubusercontent.com/66295368/102089600-b4a58c80-3e31-11eb-9e73-22b4d84e0fa0.png)
> this picture is about good and bad situation before and after send text message ,
> 
> the right order of words in RTL direction are {
> 1-hello
> 2- درود
> 3- بر
> 4- شما
> }
> درود بر شما Hello
> 
> please solve this problem.

As per my understanding, Telegram is doing it in right way. The direction of the text is determined by the first letter. You start with English, it shows the text in Left-to-Right direction; you start it with Persian, it shows the text in Right-to-Left direction.

Messengers, Social Media,... are not rich text editor. So the user cannot explicitly tells the program what direction the text should be rendered in. So, they rely on some method to determine the direction. The method in this case is to decide the direction of the paragraph based on the first character.

**Comment by Mehrshad3** [comment]
> > in telegram Desktop ,
> > When we type a text message mix of words in Persian and English language , the order of words is true,
> > but after send , words shows in disorder.
> > ![telegram](https://user-images.githubusercontent.com/66295368/102089600-b4a58c80-3e31-11eb-9e73-22b4d84e0fa0.png)
> > this picture is about good and bad situation before and after send text message ,
> > the right order of words in RTL direction are {
> > 1-hello
> > 2- درود
> > 3- بر
> > 4- شما
> > }
> > درود بر شما Hello
> > please solve this problem.
> 
> As per my understanding, Telegram is doing it in right way. The direction of the text is determined by the first letter. You start with English, it shows the text in Left-to-Right direction; you start it with Persian, it shows the text in Right-to-Left direction.
> 
> Messengers, Social Media,... are not rich text editor. So the user cannot explicitly tells the program what direction the text should be rendered in. So, they rely on some method to determine the direction. The method in this case is to decide the direction of the paragraph based on the first character.

I don't agree because:
1. WhatsApp Shows them correctly and how we except.
2. Telegram desktop has the feature of *"Insert Unicode control character"*.
3. I insert Unicode control characters texts so The characters aren't only these you see. (I think [this website](https://www.unicode.org/reports/tr9) is helpful.)

**Comment by RexNext** [comment]
> > in telegram Desktop ,
> > When we type a text message mix of words in Persian and English language , the order of words is true,
> > but after send , words shows in disorder.
> > ![telegram](https://user-images.githubusercontent.com/66295368/102089600-b4a58c80-3e31-11eb-9e73-22b4d84e0fa0.png)
> > this picture is about good and bad situation before and after send text message ,
> > the right order of words in RTL direction are {
> > 1-hello
> > 2- درود
> > 3- بر
> > 4- شما
> > }
> > درود بر شما Hello
> > please solve this problem.
> 
> As per my understanding, Telegram is doing it in right way. The direction of the text is determined by the first letter. You start with English, it shows the text in Left-to-Right direction; you start it with Persian, it shows the text in Right-to-Left direction.
> 
> Messengers, Social Media,... are not rich text editor. So the user cannot explicitly tells the program what direction the text should be rendered in. So, they rely on some method to determine the direction. The method in this case is to decide the direction of the paragraph based on the first character.

-----------------
In this case , i have illustrated that i changed  direction and force telegram to have RTL direction ,for text box before send message.

obviously the solution is very simple , in cases that user switch the direction and  determine it by (CTRL+SHIFT keys),
the message that will be send , must have direction that user specify and  follow the user choice, not  default behavior .

just needs check a condition in "text change event" for textbox.
direction.something like this ;

txtBox.on(textChange,fn{
if(CTRL+SHIFT){
   txtChunk.direction.toggle();
}
});

عزیزان لطفا به پست اول لایک بدید 
، شاید با بالارفتن لایکش  
، تغییرات رو ایجاد کنند، عجیبه که هیچ اینترکشنی با این ایشو ندارند..

**Comment by Mehrshad3** [comment]
> عزیزان لطفا به پست اول لایک بدید
> ، شاید با بالارفتن لایکش
> ، تغییرات رو ایجاد کنند، عجیبه که هیچ اینترکشنی با این ایشو ندارند..

<p dir="rtl">هممون فارسیم انگلیسی صحبت می‌کنیم😆
<br>به نظرم به تعداد لازم لایک شده. حالا برای منم عجیبه چرا واکنشی نشون نمی‌دن. شاید یکم سنگین باشه debug کردنش. </p>

**Comment by Mehrshad3** [comment]
> obviously the solution is very simple , in cases that user switch the direction and determine it by (CTRL+SHIFT keys),
> the message that will be send , must have direction that user specify and follow the user choice, not default behavior .
> 
> just needs check a condition in "text change event" for textbox.
> direction.something like this ;
> 
> txtBox.on(textChange,fn{
> if(CTRL+SHIFT){
> txtChunk.direction.toggle();
> }
> });

I didn't know ctrl+shift keys thanks.
But I think the feature you said and the code you wrote aren't  enough and I want a feature that suppurts 125 levels of embedding not just 2 or 3 levels. I want to use Unicode control characters and make a lot of embedding levels nested to each others. Because Telegram desktop has the feature to insert this characters.

**Comment by neesti** [comment]
> > obviously the solution is very simple , in cases that user switch the direction and determine it by (CTRL+SHIFT keys),
> > the message that will be send , must have direction that user specify and follow the user choice, not default behavior .
> > just needs check a condition in "text change event" for textbox.
> > direction.something like this ;
> > txtBox.on(textChange,fn{
> > if(CTRL+SHIFT){
> > txtChunk.direction.toggle();
> > }
> > });
> 
> I didn't know ctrl+shift keys thanks.
> But I think the feature you said and the code you wrote aren't enough and I want a feature that suppurts 125 levels of embedding not just 2 or 3 levels. I want to use Unicode control characters and make a lot of embedding levels nested to each others. Because Telegram desktop has the feature to insert this characters.

Linux verion of TDesktop has not this feature (Insert characters)!
/home/afshin/دانلودها/Screenshot from 2021-01-13 22-21-43.png

**Comment by ilya-fedin** [comment]
> 2. Telegram desktop has the feature of _"Insert Unicode control character"_.

It's not Telegram, it's your system...

**Comment by ahangarha** [comment]
This is related to the software not system.

در تاریخ پنجشنبه ۱۴ ژانویهٔ ۲۰۲۱،‏ ۰:۱۰ ilya-fedin <notifications@github.com>
نوشت:

**Comment by ilya-fedin** [comment]
I can say for 100% that this is not implemented in Telegram code.

**Comment by Sh7777777** [comment]
درود تشکر

در تاریخ چهارشنبه ۱۳ ژانویهٔ ۲۰۲۱،‏ ۱۷:۱۹ Mostafa Ahangarha <
notifications@github.com> نوشت:

**Comment by ilya-fedin** [comment]
Please, use only English here

**Comment by Mehrshad3** [comment]
@ilya-fedin
> > 2. Telegram desktop has the feature of _"Insert Unicode control character"_.
>
> It's not Telegram, it's your system...

I can't understand. Why in Telegram I have this feature; in WhatsApp web, I can just set the direction of paragraph; and in the word and python IDLE and Dev C++ I haven't this feature, and in Notepad I have more Unicode Control characters than the Telegram Desktop.
I can't understand how our systems forced the Telegram Desktop to have this feature.
Can you explain more?
thanks
### Additional context
![image](https://user-images.githubusercontent.com/75848143/104580529-a3d77900-5672-11eb-9207-9efe64e5e430.png)

**Comment by ilya-fedin** [comment]
> I can't understand how our systems forced the Telegram Desktop to have this feature.

Qt asks the system for its capabilities and implements some basic features that system provides

**Comment by Mehrshad3** [comment]
> 2\. Telegram desktop has the feature of _"Insert Unicode control character"_.



> Qt asks the system for its capabilities and implements some basic features that system provides

Why in the skype I don't have the feature of *Inserting Unicode control characters*?

**Comment by ilya-fedin** [comment]
Because its toolkit doesn't support that system feature probably

**Comment by ahangarha** [comment]
> Because its toolkit doesn't support that system feature probably

It is a bad software implementation. It is overriding direction. It does what RLO and LRO character does to the text.

**Comment by ilya-fedin** [comment]
> It is a bad software implementation.

What "it is"? :thinking:
The message you quoted is about 

> Why in the skype I don't have the feature of _Inserting Unicode control characters_?

**Comment by Mehrshad3** [comment]
> > Because its toolkit doesn't support that system feature probably
> 
> It is a bad software implementation. It is overriding direction. It does what RLO and LRO character does to the text.

for me, neither Telegram nor Skype doesn't override text.

**Comment by ahangarha** [comment]
when ۱۲۳ becomes ۳۲۱ in RTL it mean there is Right-to-Left direction override (not text override)!

Look at the following example. Both lines start with some invisible character, first line has RTO (U+202E) and the second has RTE (U+202B)

‮یک two سه four عدد ۱۲۳‫

‫یک two سه four عدد ۱۲۳

**Comment by Mehrshad3** [comment]
> Right-to-Left direction override (not text override)!

What is the difference between Right-to-Left direction override and text override?

**Comment by ahangarha** [comment]
> What is the difference between Right-to-Left direction override and text override?

I don't know what text override would mean to you but direction override is exactly what I demonstrated in my previous comment.

I think I shared what I could. I cannot add more to it.

**Comment by Mehrshad3** [comment]
### Steps to reproduce
1. In a group type messages in RTL direction like 
    1. <code dir="rtl">سلام hello درود</code>
    2. <code dir="rtl">سلام👋</code>
    3. <code dir="rtl">با پاپیتا میتوانی به جمله <span dir="ltr">What is خرمالو in English?</span> جواب بدهی.</code> that contains:
        1. <code dir="rtl">با پاپیتا میتوانی به جمله </code>
        2. Start of left-to-right embedding
        3. <code>What is خرمالو in English?</code>
        4. Pop directional formatting
        5. <code dir="rtl">جواب بدهی.</code>
2. Export the chat history in HTML.

### Actual/Unexpected behaviour
It shows the messages incorrectly as shown in the photo:
![image](https://user-images.githubusercontent.com/75848143/114304061-7326a480-9ae6-11eb-8010-9a4fb9654465.png)
HTML texts are:<br>
<pre><code>       &ltdiv class="text"&gt
سلام hello درود
       &lt/div&gt</code></pre>
<pre><code>       &ltdiv class="text"&gt
سلام👋
       &lt/div&gt</code></pre>
<pre><code>       &ltdiv class="text"&gt
با پاپیتا میتوانی به جمله  What is خرمالو in English?  جواب بدهی.
       &lt/div&gt</code></pre>

### Describe the solution you'd like
HTML texts should be:<br>
<pre><code>       &ltdiv class="text"&gt
&ltspan dir="rtl"&gtسلام hello درود&lt/span&gt
       &lt/div&gt</code></pre>
<pre><code>       &ltdiv class="text"&gt
&ltspan dir="rtl"&gtسلام👋&lt/span&gt
       &lt/div&gt</code></pre>
<pre><code>       &ltdiv class="text"&gt
&ltspan dir="rtl"&gtبا پاپیتا میتوانی به جمله &ltspan dir="ltr"&gtWhat is خرمالو in English?&lt/span&gt جواب بدهی.&lt/span&gt
       &lt/div&gt</code></pre>
### Configuration
**Operating system:** PC 32bit, Windows 7

**Version of Telegram Desktop:** 2.7.1

**Used theme**: Classic

**Comment by ilya-fedin** [comment]
There's no HTML

**Comment by Mehrshad3** [comment]
> There's no HTML

I mean the HTML file in the chat export. When I export chats I see some folders and 1 or more files named <code>messages.html</code> or etc. It's strange that you say _there's no HTML_.
Can you explain more?
Also I had checked my html texts and they worked correctly.

**Comment by ilya-fedin** [comment]
This issue is about the app itself and there's no HTML in the UI

**Comment by Mehrshad3** [comment]
> the app itself

do you mean the server? If the issue is about the app and not UI, shouldn't I report it

**Comment by Mehrshad3** [comment]
> the app itself

do you mean the server? If the issue is about the app and not UI, shouldn't I report it⁉️
I don't know maybe the issue is from the server.

**Comment by ilya-fedin** [comment]
This issue is about the UI in the app, tdesktop doesn't use HTML for its UI, purely C++, export is also a part of app, but it's a definitely another part and I don't think that mixing these issues is a good idea.

**Comment by Mehrshad3** [comment]
> 
> 
> This issue is about the UI in the app, tdesktop doesn't use HTML for its UI, purely C++, export is also a part of app, but it's a definitely another part and I don't think that mixing these issues is a good idea.

I think solution of both issues will use the bidi algorythm and they should be similar but I'll report it again in another issue.

**Comment by ilya-fedin** [comment]
What's the bidi algorithm?

**Comment by Mehrshad3** [comment]
https://www.unicode.org/reports/tr9/

**Comment by Mehrshad3** [comment]
Hello
Please [Show texts in correct direction (using the bidi algorythm) in chats list](https://bugs.telegram.org/c/5561).
Thanks

**Comment by cben** [comment]
For HTML export, there is separate bug #16893 (=> PR #16120).  Let this issue remain about the desktop UI.

In the UI, a trick that works for me both on Android and Desktop (at least on Linux) is starting a new line:
![Ekrankopio de 2021-09-03 15-02-51](https://user-images.githubusercontent.com/273688/132002265-4a0e1280-f926-4b81-801e-6faa01f2c588.png)
AFAICT each line gets treated as separate paragraph, with base direction determined by first strong char.

This is not as flexible semantically as full nesting by control chars, but much easier to learn.
3-levels or deeper nested sandwiches, being invisible to reader, get ambiguous & difficult to read across line breaks anyway...
Whereas when you place LTR/RTL segments on separate lines, the overall order of the text is unambiguous top-to-bottom.

**Comment by cben** [comment]
Back to the issue here, it seems there are at least 2 separate bugs mentioned:

1. [issue by RexNext, Windows-specific?]
   UI allows input field direction toggling by left/right Ctrl+Shift, but discards that state when sending the text.  Should translate those to embedding chars — LRE..PDF / RLE..PDF.  (Another option is otherwise send direction out-of-band.  But that'd require upgrade of protocol in all clients, and out-of-band data is too easy to lose e.g. on copy-paste to other apps, so I'd recommend in-band control characters.)

2. [issue by Mehrshad3]
  Bidi control characters interpretted incorrectly.
  The question why "Insert Unicode control character" menu is supported is not really relevant — even if it weren't (as on Linux), you could always paste text with control chars and I assume display would be same?
    The display order here is a clear bug, note the **english text got reversed**:
    > but Telegram desktop and Telegram for Android don't show correctly and show it like:
    > ![b3 - Copy](https://user-images.githubusercontent.com/75848143/102708112-ba79f280-42b5-11eb-8003-1459f006fb91.png)

    This indeed should not happen unless RLO/LRO chars were used:
    http://www.unicode.org/reports/tr9/#Explicit_Directional_Overrides
    (HTML equivalent `unicode-bidi: override;`, almost never useful).

I'm sorry I don't have time now to reproduce/test the latter.  One day I'll learn to use a command-line telegram interface so I can control & inspect the exact sent/recieved texts and compare to UI...

**Comment by cben** [comment]
BTW do left/right Ctrl+Shift affect current line only or whole message?
If single line, supporting them for Windows users familiar with them would be ideal.
If whole message, respecting that would inhibit the per-line auto detection I mention above and IMHO could be a negative for UX (there is no 3rd keyboard combo for "unset direction"), better then to suppress these combos.

Does Telegram desktop on windows do per-line auto direction while editing at all?

**Comment by cben** [comment]
Anyway, I recommend splitting this issue into two.
Good bidi UX is a complex topic of many parts, but we need separate issues focused on single technical problem to help developers understand how to improve it...
