### ISSUE TITLE
Member list broken in "legacy"/classic groups

### ISSUE THREAD

**Issue by Brawl345** [telegramdesktop/tdesktop#9923]
### Steps to reproduce
1. Open a legacy/classic group (no supergroup)
2. Open the member list

### Expected behaviour
Member list is shown.

### Actual behaviour
No member list is shown. See pic. In addition, the text for the members is wrong. E.g. when you look at a bot and switch back to the group it shows "Bot" (amusingly) instead of the # of members and how many are online.

![Unbenannt](https://user-images.githubusercontent.com/5049892/102091934-c0885300-3e1f-11eb-936d-a3c365f9dfbb.png)

This **does not happen with supergroups**, only "legacy" groups that I think you can't even create anymore?

### Configuration
**Operating system:** Windows 8.1 x64

**Version of Telegram Desktop:** 2.4.13 beta

**Used theme**: Doesn't matter

**Comment by CaseyK9** [comment]
I'm going to bump this because this is happening to me as well on the 2.4.13 beta.

**Comment by taha-ghadirian** [comment]
Temporary problem #9919

**Comment by Brawl345** [comment]
Fixed with v2.4.14 beta
