### ISSUE TITLE
Beta 2.4.13: can no longer access archived sticker packs from telegram-desktop

### ISSUE THREAD

**Issue by tux93** [telegramdesktop/tdesktop#9924]
### Steps to reproduce
1. Archive some ticker packs on Telegram mobile
2. Update telegram-desktop to the latest beta
3. Navigate to Chat settings -> Manage Sticker sets

### Expected behaviour
The management window has three tabs: Stickers, Trending and Archived

### Actual behaviour
The Archived tab is missing
![Screenshot_2020-12-14_15-54-28](https://user-images.githubusercontent.com/1749593/102096688-4529a000-3e25-11eb-8bfc-12ccbb28ae2f.png)

### Configuration
**Operating system:**
openSUSE Tumbleweed

**Version of Telegram Desktop:**
2.4.13 beta

**Installation source (Linux Only)** - the official website / GitHub releases / flatpak / snap / distribution package:
Distribution package

**Used theme**:
https://t.me/addtheme/VWUuPC4sPyJPIkrh

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/9919
