### ISSUE TITLE
Can't Join A Group Voice Chat

### ISSUE THREAD

**Issue by i4081i** [telegramdesktop/tdesktop#9925]
### Steps to reproduce
1. Press "Join" button in an existing voice chat

### Expected behaviour
A voice chat window should open and stay open.

### Actual behaviour
The voice chat window opens and then closes and a warning appears which goes like "internal server error".

### Configuration
**Operating system:** Windows 10

**Version of Telegram Desktop:** 2.4.13

[log.txt](https://github.com/telegramdesktop/tdesktop/files/5690190/log.txt)
![error](https://user-images.githubusercontent.com/74790565/102107925-58e3ff00-3e43-11eb-96b9-0fec4004fba8.jpg)

**Comment by AndrewLaneX** [comment]
There were server-side changes and the new beta hasn't been released yet.

**Comment by taha-ghadirian** [comment]
Temporary problem #9919

**Comment by AndrewLaneX** [comment]
Fixed in [2.4.14](https://github.com/telegramdesktop/tdesktop/commit/cb6db82809e99505f19b421c664bfedba0c1dd1b).
