### ISSUE TITLE
Telegram Desktop keeps holding memory (RAM) after closing

### ISSUE THREAD

**Issue by makusudi** [telegramdesktop/tdesktop#9929]
### Steps to reproduce
1. Open Telegram
2. Do something
3. Close Telegram

### Expected behaviour
Telegram Desktop must free memory after closing.

### Actual behaviour
Telegram Desktop keeps holding memory (RAM) after closing. Processes are still alive.

### Configuration
**Operating system:** Ubuntu 20.04

**Version of Telegram Desktop:** 2.4.7

**Installation source (Linux Only)** - snap

**Used theme**: Dracula Mint

**Comment by AndrewLaneX** [comment]
Try Ctrl+Q.

**Comment by makusudi** [comment]
> Try Ctrl+Q.

ty, it works for me, but what about "close" button?)

**Comment by AndrewLaneX** [comment]
TDesktop still runs in the background if you use the close button/<kbd>ctrl</kbd>+<kbd>w</kbd>.

**Comment by makusudi** [comment]
> TDesktop still runs in the background if you use the close button/ctrl+w.

Is it an expected behaviour?

**Comment by Aokromes** [comment]
not a bug, by default telegram desktop have enabled minimize to tray and X or control+w minimizes to tray.
