### ISSUE TITLE
ESC key doesn't exit comments screen anymore

### ISSUE THREAD

**Issue by RememberTheAir** [telegramdesktop/tdesktop#9934]
### Steps to reproduce
1. open a channel with a linked group
2. open a post's comments
3. try to use ESC to return to the channel posts view

### Expected behaviour
You exit the post comments view

### Actual behaviour
ESc doesn't do anything. With version 2.4.13, you had to use it twice to exit (using it once didn't do anything)

### Configuration
**Operating system:** Windows 10

**Version of Telegram Desktop:** 2.4.14

**Used theme**: dark

**Comment by john-preston** [comment]
Should be fixed by https://github.com/telegramdesktop/tdesktop/commit/7f7e7b94d61b00a6f6eab783a854307407477eb2

**Comment by RememberTheAir** [comment]
Thanks!
