### ISSUE TITLE
Comments Link not working[Feature Request] 

### ISSUE THREAD

**Issue by AhyaH-YHWH** [telegramdesktop/tdesktop#9935]
https://t.me/tgbeta/4200?comment=414732

Links to native comments, generated on Android Client Can't be Opened by TD 2.4.14 Windows

please Add this to supported links

https://t.me/TelegramDesktopTalk/52184

**Comment by john-preston** [comment]
@AhyaH-YHWH I don't see comments in this channel.

**Comment by AhyaH-YHWH** [comment]
@john-preston 
sorry
Discussion @tgbeta Channel unlinked recently from group
that must be why the link didn't work
