### ISSUE TITLE
[Feature Request] Sticker preview size

### ISSUE THREAD

**Issue by terion-name** [telegramdesktop/tdesktop#9937]
Non-bundled stickers in TG are often very detailed and contain texts. When you try to find needed sticker the previews are so small, that most of the times it's impossible to read sticker text and the details and you are playing in "guess what I need to send".

It would be great to have option in sticker panel to make previews larger and/or expand the selection panel and/or have a bigger preview on hover

**Comment by ilya-fedin** [comment]
Press and hold the mouse button on a sticker in the list.

**Comment by RememberTheAir** [comment]
@ilya-fedin I think that with "non-bundled" he means webp sticker files that do not belong to a pack
