### ISSUE TITLE
weird behaviour in Ubuntu linux

### ISSUE THREAD

**Issue by s7en75** [telegramdesktop/tdesktop#994]
when telegram is open some times my screen start creating some weird colors and dots especially around the cursor. There is no other control after this unless restarting computer.After restart , my account is gone it's like this is the first time I'm trying to start telegram.I have to enter PIN code from scratch.

**Comment by lunix4** [comment]
Try to start Telegram from the terminal and comment the output

**Comment by auchri** [comment]
"creating some weird colors and dots especially around the cursor." sounds like an issue with your PC :D
