### ISSUE TITLE
[Feature Request] Missing Video Message on Gif Panel compared to Android Client

### ISSUE THREAD

**Issue by AhyaH-YHWH** [telegramdesktop/tdesktop#9940]
When you send a Soundless Video Message (Forward as copy or via https://t.me/NephoBot or ...)
on Android and iOS it is added to Gif Panel, of Telegram Keyboard
and can be sent as reply to Messages

But Telegram Desktop (2.4.14 windows) doesn't include this in Gif panel

for consistency, if possible add this to Desktop as well
https://t.me/TelegramDesktopTalk/52967

![image](https://user-images.githubusercontent.com/73444508/102234251-58606c80-3f06-11eb-9cb1-57abe4286fa1.png)

**Comment by ilya-fedin** [comment]
> But Telegram Desktop (2.4.14 windows) doesn't include this in Gif panel

I have this annoying behavior on tdesktop as well. Isn't this done by the server?

**Comment by M299792458** [comment]
> > But Telegram Desktop (2.4.14 windows) doesn't include this in Gif panel
> 
> I have this annoying behavior (adds every video without sound to the gif panel) on tdesktop as well. Isn't this done by the server?

I guess yes
