### ISSUE TITLE
Editing any message in a group with bots triggers command suggetions

### ISSUE THREAD

**Issue by Henriquelay** [telegramdesktop/tdesktop#9941]
### Steps to reproduce
1. Edit a message
2. Place a `/` as the first character
3. Pressing enter will send the command and not edit the message, as if you have clicked on it

### Expected behaviour
Message should be edited 

### Actual behaviour
Command is sent, message is still in editing mode

### Configuration
**Operating system:** Ubuntu20.04

**Version of Telegram Desktop:** 2.4.14 beta

**Installation source (Linux Only)** - the official website

**Used theme**: Theme independant, a friend confirmed it happens on his installation as well.

**Comment by AtilioA** [comment]
Same on Linux Mint 20, Windows 10 1809, TDesktop 2.4.14 beta

**Comment by ilya-fedin** [comment]
This is not a bug...

**Comment by Henriquelay** [comment]
On editing? Are you sure? This is certainly weird... 
Why would I want, in editing a message, to send a new command while editing, and it doesn't even take in context the rest of the message? When was this first introduced? I certainly remember doing so on older versions and not getting command pallete

**Comment by RememberTheAir** [comment]
This behavior is consistent with the mobile apps, so it's most likely intended (I have a Telegram Desktop 2.3.2 installation dating back to may, and it behaves the same btw)
