### ISSUE TITLE
[Feature Request] Make chat window text font size to be easily editable 

### ISSUE THREAD

**Issue by dFarkhod** [telegramdesktop/tdesktop#9942]
The problem is that the chat window text font size is too small and there is no way to edit it.

Visual Studio has a great feature of changing font size by combination of Ctrl + mouse scroll. Scroll forward and font size will be increased, scroll backwards, and the font size will be decreased.

At least the font size should be somewhere in the settings.

**Comment by ilya-fedin** [comment]
#90
