### ISSUE TITLE
Bug: Lost Account and chats , after every Update , todays.

### ISSUE THREAD

**Issue by RexNext** [telegramdesktop/tdesktop#9945]
Hi , 
i have added two accounts in telegram desktop app ,
but these days after every telegram update ,
my chats in second account have lost , or signed out , .. 
please have attention to this issues , 
thank you .

**Comment by ItsOnlyMeNL** [comment]
Same issue here, but i seem to be still logged in on phone although phone tells me that that old session on windows pc  is still active.
