### ISSUE TITLE
Options: make contacts list static, put contacts under tabs

### ISSUE THREAD

**Issue by fatcat386** [telegramdesktop/tdesktop#9946]
Some contacts are important for me, some not. And i want to order them according my wish with dragging.
This option of course must make them static and don't popup them on new messages.
Also it's good idea to keep contacts under named tabs to hide some of them out of sight.
Currently only one "tab" exist, called Archive. But I would like to see "Work", "Family", "Friends" etc.

**Comment by ilya-fedin** [comment]
> Currently only one "tab" exist, called Archive. But I would like to see "Work", "Family", "Friends" etc.

You can create folders in settings

**Comment by fatcat386** [comment]
Wow! That's what I needed.
Thank you :=)
