### ISSUE TITLE
Single emojis not visible [Telegram Desktop - Linux 64]

### ISSUE THREAD

**Issue by Sanket-Mathur** [telegramdesktop/tdesktop#9947]
### Steps to reproduce
1. Open the telegram-desktop application
2. Open a chat
3. Send a single emoji to the chat

### Expected behaviour
The emoji should be visible in the chat as sent.

### Actual behaviour
A blank space is popping up on the application when an emoji is either sent or received.  
The emoji can be seen in the left sidebar displayed correctly but not in the actual chat.
 
### ScreenShot
![Screenshot from 2020-12-17 16-00-16](https://user-images.githubusercontent.com/52062536/102478964-4573a680-4084-11eb-9a0c-9e6ce94d6086.png)

### Configuration
**Operating system:** Ubuntu 20.04.1 LTS

**OS type:** 64-bit

**Version of Telegram Desktop:** 2.4.7

**Installation source (Linux Only):** snap

<details><summary><b>Logs (Starting telegram-desktop)</b>:</summary>
(process:8159): Telegram-WARNING **: 16:08:33.133: Unfortunately, GTK integration conflicts with qgtk2 platformtheme and style. Therefore, QT_QPA_PLATFORMTHEME and QT_STYLE_OVERRIDE will be unset.
Telegram-Message: 16:08:33.133: This can be ignored by setting TDESKTOP_I_KNOW_ABOUT_GTK_INCOMPATIBILITY environment variable to any value, however, if qgtk2 theme or style is used, this will lead to a crash.
Telegram-Message: 16:08:33.133: GTK integration can be disabled by setting TDESKTOP_DISABLE_GTK_INTEGRATION to any value. Keep in mind that this will lead to clipboard issues and tdesktop will be unable to get settings from GTK (such as decoration layout, dark mode & more).
Qt: Session management error: Could not open network socket
Gtk-Message: 16:08:33.254: Failed to load module "canberra-gtk-module"
Gtk-Message: 16:08:33.254: Failed to load module "canberra-gtk-module"
Telegram-Message: 16:08:33.268: You can disable tray icon counter with TDESKTOP_DISABLE_TRAY_COUNTER and make it look better if it is monochrome.
error: : cannot open
error: : cannot open
error: : cannot open
</details>

**Comment by ilya-fedin** [comment]
Can't reproduce
![image](https://user-images.githubusercontent.com/17829319/102519026-e3b63b00-4089-11eb-856b-5fd2f02c82dd.png)

**Comment by Bipul-Harsh** [comment]
Bro its working might be issue in your system

**Comment by Sanket-Mathur** [comment]
At time of creating this issue, I had tried several times restarting the application but same problem occurred every time. However, this time when starting the application, it worked properly. It might have been caused due to some other aspects.
I'm closing this issue thread.
Thanks for commenting and sorry for creating the issue without testing it enough.
