### ISSUE TITLE
DPI scaling not applied automatically when multiple screens have different resolution

### ISSUE THREAD

**Issue by dickreuter** [telegramdesktop/tdesktop#9948]
### Steps to reproduce
1. Have DPI scalin enabled in windows on a high resolution screen
2. Open Telegram
3. Everything will look very small

### Expected behaviour
It should be scaled and look readable

### Actual behaviour
It all looks very small and unreadable

### Configuration
Windows 10

**Version of Telegram Desktop:**
Latest

**Comment by ilya-fedin** [comment]
Change scale in Telegram settings

**Comment by dickreuter** [comment]
I see, my problem is that I have multiple screens and they don't all have the same resolution. Whatsapp and other messengers I can move around and they adapt automatically.

**Comment by ilya-fedin** [comment]
#1121
