### ISSUE TITLE
webp stickers not showing up in Telegram Desktop - Debian

### ISSUE THREAD

**Issue by AmirBitaraf** [telegramdesktop/tdesktop#995]
Hi there,
I'm using Telegram Desktop 0.8.48 in Debian Stretch/sid and when I drag & drop a webp sticker, it doesn't show up for me but my friend sees it in Android. Here's a screenshot of what happens.

![screenshot from 2015-08-13 01-00-46](https://cloud.githubusercontent.com/assets/8049618/9235887/c87a0fca-4156-11e5-983c-a8e5b2da92e3.png)

**Comment by telegramdesktop** [comment]
Image width and height should be less then 2048 pixels. If this is correct, then please attach the sticker itself here, or send me to https://telegram.me/preston so I could understand, why it is not displayed.
