### ISSUE TITLE
[Feature Request] Proposal to add disable notifications for usually work day (8 hours)

### ISSUE THREAD

**Issue by MairwunNx** [telegramdesktop/tdesktop#9950]
## Why?

Work day usually is 8 hours or 8:30, we all have a friends can write to us when we busy on the job, and it's reason to implement this issue.

## Why №2?

Because official mobile telegram client have it, and desktop version needs it as well.

### Describe the solution you'd like
Just add another radio button to this ↓ menu with 8 hours 

![image](https://user-images.githubusercontent.com/39625750/102575132-8eb70b00-4103-11eb-8525-b8e6b70b4b47.png)

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/151#issuecomment-63627345
