### ISSUE TITLE
Search doesn't find chats starting with a hashtag (#) unless you type that character too

### ISSUE THREAD

**Issue by 0xallie** [telegramdesktop/tdesktop#9953]
### Steps to reproduce
1. Create a chat called `#test`
2. Search for `test` in your chat list

### Expected behaviour
The search should find `#test`, like it does on the official Telegram iOS client.

### Actual behaviour
It fails to find the chat. Searching for something like `#te` works.

### Configuration
**Operating system:** Windows 10 20H2

**Version of Telegram Desktop:** 2.4.14 beta

**Comment by Aokromes** [comment]
cannot reproduce on 2.7.8

**Comment by nyuszika7h** [comment]
It's kinda fixed, but not fully. The initial search that turns up immediately only finds chats without the `#`, but then around 3 seconds later the results incuding `#` load as well.

**Comment by Aokromes** [comment]
i think it must be server side.

**Comment by john-preston** [comment]
@Aokromes well, the server does the job here, it returns the chat in several seconds. The issue is about the local search that is done in tdesktop, before the server returns its results.

**Comment by nyuszika7h** [comment]
This is still relevant.

**Comment by nyuszika7h** [comment]
Still an issue.

**Comment by 0xallie** [comment]
still not fixed
