### ISSUE TITLE
Degraded audio quality systemwide if-and-only-if Telegram has an active call

### ISSUE THREAD

**Issue by slondr** [telegramdesktop/tdesktop#9954]
### Steps to reproduce
1. Start a Telegram call (actually in-call, not just ringing)
2. Wait for any sound to be played system-wide

### Expected behaviour
Tell us what should happen
Sound sounds okay
### Actual behaviour
Tell us what happens instead
Sound is extremely static-y, pops, and echoes
### Configuration
**Operating system:**
Arch Linux
**Version of Telegram Desktop:**
2.4.14 (beta)
**Installation source (Linux Only)** - the official website / GitHub releases / flatpak / snap / distribution package:
aur/telegram-desktop-bin-dev
**Used theme**:
N/A
<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by slondr** [comment]
I'm on the beta client now but this issue is also present on the official release version

**Comment by ilya-fedin** [comment]
Focusrite soundcard?

**Comment by slondr** [comment]
> Focusrite soundcard?

Realtek

**Comment by zaps166** [comment]
>  Sound is extremely static-y, pops, and echoes

I think it can be a PulseAudio issue with low latency audio. I have the same on voice calls for 1 - 2 sec and then it plays normal.

**Comment by slondr** [comment]
@zaps166 Is this something I can solve on my end? Does telegram-desktop support something like Jack?

**Comment by zaps166** [comment]
@slondr 

I never checked this with telegram, but try:
- open terminal
- write  `export PULSE_LATENCY_MSEC=100` 
- run telegram from this terminal

**Comment by slondr** [comment]
I get this error while launching telegram-desktop (no matter what):

Failed to set real-time priority for thread: Operation not permitted

**Comment by slondr** [comment]
Okay I managed to fix that error by playing with ulimits on my system, but that didn't actually solve the audio issues

**Comment by slondr** [comment]
@zaps166 I can confirm that that does not solve the issue

**Comment by ilya-fedin** [comment]
#1548
