### ISSUE TITLE
miscolored "sending" symbol

### ISSUE THREAD

**Issue by duntwave** [telegramdesktop/tdesktop#9956]
### Steps to reproduce
1. change theme to night
2. change accent color
3. send a message

### Expected behaviour
the sending symbol in the chat will be the same as the selected accent color 

### Actual behaviour
the sending symbol is instead the default accent color and it's very annoying
[https://imgur.com/a/zVLR76B](url)
### Configuration
**Windows 10**

**very most recent beta version**

**Installation source (Linux Only)** - the official website / GitHub releases / flatpak / snap / distribution package:

**basic night theme**:

<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by Mehrshad3** [comment]
hello

**Comment by Mehrshad3** [comment]
hello
I use Telegram desktop version 2.4.15 and the problem you said doesn't exist. What was your Telegram version when you said it?

**Comment by duntwave** [comment]
yes 2.4.1.5 beta
![image](https://user-images.githubusercontent.com/50681151/102954645-9aa32400-4499-11eb-80c1-c5cdf6ec1b27.png)
