### ISSUE TITLE
[Feature Request] Add option on every chat to set/unset showing unread messages on the badge counter

### ISSUE THREAD

**Issue by Oscar65** [telegramdesktop/tdesktop#9960]
### Is your feature request related to a problem?
No

### Describe the solution you'd like
Add an option on every chat to set/unset to showing unread messages on the badge counter.

### Describe alternatives you've considered
none

### Additional context
Some chats have hundreds of messages every day and showing his unread messages on the badge counter is not useful. It could be useful to be able to have the option on some chats to do not showing his unread messages on the badge counter. The option to include/exclude muted chats in unread count on Badge counter is not enough.

**Comment by ilya-fedin** [comment]
#6105
