### ISSUE TITLE
[Feature Request] Media control using MPRIS

### ISSUE THREAD

**Issue by JuniorJPDJ** [telegramdesktop/tdesktop#9961]
### Is your feature request related to a problem?
Telegram Desktop is last music player which can't be controller using MPRIS-compatible media player interface on Linux.
Even firefox allows to be controlled by that.
This would allow DE to show playing track, rewind, skip and pause playback.
Also would make possible to control music playback on KDE connect and another similar tools.

### Describe the solution you'd like
Implement MPRIS DBus API

### Describe alternatives you've considered
I don't really know any alternatives, MPRIS is gold standard on linux, supported on Gnome, KDE and other DEs.

### Additional context
Would allow eg. to control music playback with this KDE widget:
![Screenshot_20201220_123110](https://user-images.githubusercontent.com/7334549/102712171-3f1d3e80-42bf-11eb-8b62-a0832505d8fb.png)
Or from phone on KDE connect:
![image](https://user-images.githubusercontent.com/7334549/102712190-6bd15600-42bf-11eb-8f85-470e3e40a3bb.png)

**Comment by ilya-fedin** [comment]
#3960

**Comment by JuniorJPDJ** [comment]
@Aokromes This should be opened now as #3960 was "fixed" in another fashion.

**Comment by ilya-fedin** [comment]
Yeah, this is not a duplicate anymore

**Comment by JuniorJPDJ** [comment]
@ilya-fedin I wanted to thank you very much! Just got this update in arch linux (it was pretty delayed) and it's working like a charm!
![image](https://user-images.githubusercontent.com/7334549/112772449-2a281800-9031-11eb-897b-3aec5a653bbd.png)
The only thing is missing cover art, but it's much better than it was before :D

**Comment by ilya-fedin** [comment]
> The only thing is missing cover art

I have no idea how set it given that it requires setting URL while tdesktop gets covers from mtprotto

**Comment by JuniorJPDJ** [comment]
Isn't it saved anywhere? Like in /tmp or cache dir somewhere?

**Comment by ilya-fedin** [comment]
There are only encrypted cache in custom format which, of course, couldn't be read by other applications

**Comment by JuniorJPDJ** [comment]
> There are only encrypted cache in custom format which, of course, couldn't be read by other applications

wait... pushing it as base64-encoded image in form of url didnt work?

**Comment by ilya-fedin** [comment]
This doesn't seem to work
![изображение](https://user-images.githubusercontent.com/17829319/113187694-ae081d00-9248-11eb-86b3-a7946d8e1cc3.png)
Maybe I'm doing something wrong though...

**Comment by ilya-fedin** [comment]
Yeah, it was me
![изображение](https://user-images.githubusercontent.com/17829319/113188509-a7c67080-9249-11eb-8c59-453cd631030e.png)

**Comment by JuniorJPDJ** [comment]
There's some weird problem with this cover arts in KDE Connect, but maybe it's just KDE Connect bug.
In main KDE applet on PC there's cover art, but I can't see one on phone in KDE Connect.

**Comment by ilya-fedin** [comment]
:thinking: I don't use KDE connect
