### ISSUE TITLE
Folders bug

### ISSUE THREAD

**Issue by Sccar500** [telegramdesktop/tdesktop#9964]
In telegram desktop. the groups in which you are a member remain in the settings folder even after you leave them
![1](https://user-images.githubusercontent.com/76274532/102716584-a7edc200-4291-11eb-81a3-075eb46cc4e8.jpg)
![2](https://user-images.githubusercontent.com/76274532/102716585-a91eef00-4291-11eb-88d5-498c6d4bf151.png)

**Comment by Mehrshad3** [comment]
Yes I think it is true and they remain in folder settings but I think it is good because you might come back to groups and it is good that Telegram remember it

**Comment by ayanginet** [comment]
@Mehrshad3 but on the mobile version there is no such issue. So it is a bug, not a feature :)
