### ISSUE TITLE
Telegram no longer uses system default font

### ISSUE THREAD

**Issue by teoet6** [telegramdesktop/tdesktop#9965]
### Steps to reproduce
1. Open telegram
2. Notice that system font is not used

### Expected behaviour
System font should be used

### Actual behaviour
System font isn't used

### Configuration
**Operating system:**
Arch GNU/Linux 

**Version of Telegram Desktop:**
2.4.7-5

**Installation source (Linux Only)** - the official website / GitHub releases / flatpak / snap / distribution package:
Official arch repository

**Used theme**:
Day

<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by ilya-fedin** [comment]
I don't know which patching your disto does or did, but upstream telegram never used system fonts.

**Comment by qenya** [comment]
For the benefit of anyone else coming across this, I've filed a bug downstream here: https://bugs.archlinux.org/task/69082

**Comment by ilya-fedin** [comment]
They should close it, since the current behavior is the right one. Telegram UI is designed only for Open Sans and various issues may appear with other fonts.

**Comment by kq01526** [comment]
Hi,

> @ilya-fedin commented:
> 
> Telegram UI is designed only for Open Sans and various issues may appear with other fonts.

Any chance an option could be implemented to allow using the system font?

Regards

**Comment by ilya-fedin** [comment]
see #90
