### ISSUE TITLE
crash at startup

### ISSUE THREAD

**Issue by Mehrshad3** [telegramdesktop/tdesktop#9967]
### Steps to reproduce
0. leave your computer and don't do anything with it (I'm not sure if this step is necessary)
1. Click on the Telegrams' icon

### Expected behaviour
Telegram launches and I can use it.

### Actual behaviour
I clicked many times and nothing happened. Once I clicked on the Telegrams' icon, it errored.
![b6](https://user-images.githubusercontent.com/75848143/102750242-bbc12300-437a-11eb-9f42-2423ae9231a4.png)

### Configuration
**Operating system: windows 7**
![image](https://user-images.githubusercontent.com/75848143/102750538-3d18b580-437b-11eb-8b3a-28ef4c2f3347.png)

**Version of Telegram Desktop: Beta 2.4.15**

**Used theme**: classic

<details><summary><b>Logs</b>:</summary>
[log.txt](https://github.com/telegramdesktop/tdesktop/files/5722885/log.txt)
[log_start0.txt](https://github.com/telegramdesktop/tdesktop/files/5722887/log_start0.txt)
[log_start1.txt](https://github.com/telegramdesktop/tdesktop/files/5722888/log_start1.txt)
[log_start2.txt](https://github.com/telegramdesktop/tdesktop/files/5722889/log_start2.txt)
[log_start3.txt](https://github.com/telegramdesktop/tdesktop/files/5722890/log_start3.txt)
[log_start4.txt](https://github.com/telegramdesktop/tdesktop/files/5722891/log_start4.txt)
[log_start5.txt](https://github.com/telegramdesktop/tdesktop/files/5722892/log_start5.txt)
[log_start6.txt](https://github.com/telegramdesktop/tdesktop/files/5722893/log_start6.txt)
[log_start7.txt](https://github.com/telegramdesktop/tdesktop/files/5722894/log_start7.txt)
[log_start8.txt](https://github.com/telegramdesktop/tdesktop/files/5722895/log_start8.txt)
[log_start9.txt](https://github.com/telegramdesktop/tdesktop/files/5722896/log_start9.txt)
</details>

**Comment by Aokromes** [comment]
it looks some failure with your permissions, try to download portable version and run it from c:\telegram to test.

**Comment by Mehrshad3** [comment]
I could launch it yesterday and a few days before so I think the problem isn't permissions. Exactly now I restarted my laptop and the problem solved and I could launch the version I had installed, But I think Telegram desktop has a bug

**Comment by Mehrshad3** [comment]
#10003

**Comment by Mehrshad3** [comment]
It seems that this issue hasn't been repeated. I hope it has been fixed in these updates after I had opened this issue.

**Comment by Mehrshad3** [comment]
I can't understand the exact steps of reproducing but it happened again 😬
![b1](https://user-images.githubusercontent.com/75848143/109410117-3d51b480-79ad-11eb-96ba-5f23ca98b8cc.png)
so I reopened this issue.
### Configuration
The version of Telegram Desktop: 2.6.1
### Additional contexts
1. I understood I can fix this issue by opening the windows task manager and ending all process trees related to the Telegram desktop, but I think this issue should be solved by developers.
2. This issue occurs rarely but it exists.
