### ISSUE TITLE
MacBook screen dims and turns off while playing video in fullscreen

### ISSUE THREAD

**Issue by mahenzon** [telegramdesktop/tdesktop#9968]
### Steps to reproduce
1. Open macOS settings, go to Battery -> Battery and set "Turn display off after:" to something small (1-2 minutes)
2. Open Telegram Desktop, start playing any video there, video length has to be more than time to dim the screen
3. Open video full screen, let it play, don't touch trackpad / kb / touchbar for 1-2 minutes

### Expected behaviour:
Screen doesn't dim and doesn't turn off while playing video (like it is for example when playing youtube fullscreen)

### Actual behaviour
Screen dims and then turns off while playing fullscreen video

### Configuration
**Operating system: macOS Bug Sur 11.1 (20C69)**
**Hardware: MacBook Pro (13-inch, M1, 2020)**
**Version of Telegram Desktop: Version 2.4.7**

**Used theme**: Standard (no custom themes)

**Comment by ilya-fedin** [comment]
#7790
