### ISSUE TITLE
Quit Telegram

### ISSUE THREAD

**Issue by PhilippVerpoort** [telegramdesktop/tdesktop#997]
Am I just blind or is there no option to actually quit the program other than in the status bar icon context menu? I think there should be some button to do so and, if there is one, it should be easier to find.

**Comment by auchri** [comment]
Not yet
#703

**Comment by gayanW** [comment]
I'm on Debian and don't have a status bar. So how could I quit the program?

**Comment by auchri** [comment]
strq+q

**Comment by gayanW** [comment]
@auchri sorry did you mean sysrq?

**Comment by PhilippVerpoort** [comment]
@gayanW: No, I think he meant the keyboard shortcut "Ctrl+Q".

**Comment by gayanW** [comment]
@PhilippVerpoort Thanks. But I see the telegram process still running on the background.

**Comment by john-preston** [comment]
@gayanW Ctrl+Q should quit the program completely :(

**Comment by gayanW** [comment]
@john-preston Ctrl+Q did work. (got it wrong when running `ps aux`. My bad. )
