### ISSUE TITLE
[Feature Request] open links at incognito tab

### ISSUE THREAD

**Issue by Ruberoid** [telegramdesktop/tdesktop#9970]
Hey there guys n girls.

Please do not hesistate to reject this issue if it looks like unfeasible behavior.

The main idea is to open chat-posted external links in an anonymous manner. For example if someone posts an youtube link, I would like to hit something like CTRL + Mouse click, and I expect to open new link in my default browser Chrome (opera, firefox) in a brand new ANONYMOUS TAB.

This might help not to compromise personal youtube feed or other cookie-based issues.
Thanks in advance and best regards!

**Comment by ilya-fedin** [comment]
No system provides such API

**Comment by wizzard0** [comment]
> No system provides such API

At least Chrome on Windows does. Try
`C:\Users\YourUser>start chrome -incognito https://google.com`

**Comment by ilya-fedin** [comment]
This is not a system API and will require having a hardcoded list of browsers what is not good. No app does this.

**Comment by wizzard0** [comment]
well, the user has not lost interest, but there's certainly nothing to add

**Comment by ilya-fedin** [comment]
There's no API to implement that (vendor-locking on Chrome is a no-go imho), this feature request is unimplementable
