### ISSUE TITLE
Crash report when send multiple images

### ISSUE THREAD

**Issue by shahabmohammadi** [telegramdesktop/tdesktop#9971]
Today when I tried to send some picture documents to a user I've got crash issues in the telegram desktop v 2.4.7.
 
![ezgif-3-9ace141f60e1](https://user-images.githubusercontent.com/45038855/102973896-d29a7d80-4512-11eb-8b76-0961c4955819.gif)

**Comment by Aokromes** [comment]
try updating to 2.4.15 beta.

**Comment by develop-shahab** [comment]
> try updating
Same issue with build version 2.4.15 beta.

**Comment by alefvanoon** [comment]
i haven't problem with 2.5.2 beta.
