### ISSUE TITLE
Manual check for updates

### ISSUE THREAD

**Issue by System0x20** [telegramdesktop/tdesktop#9972]
### Is your feature request related to a problem?
You should enable automatic updates in order to check for an update.

### Describe the solution you'd like
A manual button that checks for updates

### Describe alternatives you've considered
Automatic updater notifying instead of just downloading the new version. Maybe I'm on a metered connection and don't want to waste 20-40MB in background

### Additional context
Thanks

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/4643
