### ISSUE TITLE
Titlebar on Linux is: Telegram "

### ISSUE THREAD

**Issue by alosarjos** [telegramdesktop/tdesktop#9973]
### Steps to reproduce
1. Open Telegram

### Expected behaviour
Have Telegram as title of the window

### Actual behaviour
Has Telegram " as title of the window

### Configuration
**Operating system:** Arch Linux / Gnome

**Version of Telegram Desktop:** 2.5

**Installation source (Linux Only)**: The official site

**Used theme**: Night

![image](https://user-images.githubusercontent.com/29999427/102987550-cadad900-4512-11eb-80e1-d923747fb2c0.png)

**Comment by ilya-fedin** [comment]
Can't reproduce on 2.4.15 (2.5.0 was rolled back).

**Comment by alosarjos** [comment]
> Can't reproduce on 2.4.15 (2.5.0 was rolled back and I can't test).

Hmmm, I just checked Telegram again and now is this

![image](https://user-images.githubusercontent.com/29999427/102995804-1ba5fe00-4522-11eb-85fe-82f2fb1a3ca7.png)

Will wait for 2.5.1 to get released and update the issue then.

**Comment by ilya-fedin** [comment]
Maybe it is a bug with your window manager? There's no big changes between 2.4.15, 2.5.0 and 2.5.1

**Comment by alosarjos** [comment]
> Maybe it is a bug with your window manager? There's no big changes between 2.4.15, 2.5.0 and 2.5.1

Just updated to 2.5.1. It's still changing, (And it's changing with the app opened, it's not that it changes when launched.) Not happening with Discord but it's happening with VSCode, so yeah, it seems this is not something related to Telegram.
