### ISSUE TITLE
[Bug] RTL Sidebar

### ISSUE THREAD

**Issue by neesti** [telegramdesktop/tdesktop#9976]
I use Persian language for naming new group name. The direction of writing in this language is right to left.
There is a problem here:
When I write the new group name in Persian, it should normally be right to left, **while** the direction is right **align** in sidebar! 

For example When I add an exclamation mark to the end of name, the exclamation mark is moved to the beginning of the name!
And the reason is that the direction of the text is not right to left; It is right **align**.

**Comment by ilya-fedin** [comment]
#9922
