### ISSUE TITLE
Outdated snap on beta channel

### ISSUE THREAD

**Issue by maxiberta** [telegramdesktop/tdesktop#9979]
The current snap release on the `latest/beta` channel (amd64) is `2.1.21-beta-63-g5655ad25b` from 2020-07-24, while `stable` and `edge` were updated today (2020-12-23). It is expected that the beta snap is somewhere between stable and edge. If that's not possible, maybe just close this channel and leave stable and edge only?
Thanks!

**Comment by ilya-fedin** [comment]
Yeah, updating beta channel doesn't know for some reason and no one know for what exactly reason :(

Looking by https://launchpad.net/~telegram.desktop/+snap/telegram-desktop-dev, it builds beta versions, but they don't being pushed to the store. Why - no one knows. Maybe it is a bug on Launchpad side...

**Comment by maxiberta** [comment]
Ouch. Have you tried raising the issue in [the snapcraft forum](https://forum.snapcraft.io) (under "store")?

**Comment by ilya-fedin** [comment]
@john-preston is who should do this probably, since he is the only one who have access to the launchpad account

**Comment by ilya-fedin** [comment]
beta channel has been closed
