### ISSUE TITLE
Disconnecting under Proxy

### ISSUE THREAD

**Issue by FerDeath** [telegramdesktop/tdesktop#998]
I am having troubles in my job using Telegram. There we connect with a proxy (with authentication) and it connects and disconnects randomly. It's unusable right now. 
Telegram v 0.8.48 on Windows 7 Professional x64.
Please tell me if you need any further information, thanks for your work!

**Comment by auchri** [comment]
Maybe it's a problem with the proxy?

**Comment by auchri** [comment]
Maybe related to #954
