### ISSUE TITLE
[Feature Request] Add option to hide badge counter for "other" accounts

### ISSUE THREAD

**Issue by xZise** [telegramdesktop/tdesktop#9981]
### Is your feature request related to a problem?
My problem currently is that I share my computer with someone else and we are both logged in into Telegram Desktop. Unfortunately I now cannot distinguish between unread messages for me or for my friend. I need to read the messages from the other account to actually get it to zero.

### Describe the solution you'd like
Either an option to not include other accounts in the count or to be able to distinguish between unread messages from the currently active account and unread messages from the other accounts.

### Describe alternatives you've considered
I'm not sure there are alternatives..., except to ignore the badge counter.

### Additional context
Just from this image it is impossible to know whether there are messages for my account or not:
![grafik](https://user-images.githubusercontent.com/417478/103002782-d7b9f580-452f-11eb-81f5-4736ad720e46.png)

**Comment by ilya-fedin** [comment]
#8189
