### ISSUE TITLE
Panel icon is off

### ISSUE THREAD

**Issue by renyhp** [telegramdesktop/tdesktop#9982]
### Steps to reproduce
1. Set an icon theme
2. `export TDESKTOP_DISABLE_TRAY_COUNTER=1`
3. Open Telegram and receive messages

### Expected behaviour
The icon should not look blurry and no counter should get overlaid on the icon

### Actual behaviour
The icon is blurry and the message counter is overlaid on the icon

### Configuration
**Operating system:** Xubuntu 20.04.1

**Version of Telegram Desktop:** 2.5.1

**Installation source (Linux Only)**: the official website

**Used theme**: Papirus

### Additional information

Please revert commit ede7ad1a4cf2335770216ebd32168527aa29507b, as no harm is done by those lines.

**Comment by ilya-fedin** [comment]
#6721

**Comment by ilya-fedin** [comment]
> Please revert commit [ede7ad1](https://github.com/telegramdesktop/tdesktop/commit/ede7ad1a4cf2335770216ebd32168527aa29507b), as no harm is done by those lines.

This was a temporary hack when tray implementation was rewritten. Since tray implementation is stabilized, all hacks were removed. If you need this option, it is tracked by #6721 for all platforms.
