### ISSUE TITLE
Can't connect to voice chat using Socks5/MTProto proxy but calls works well

### ISSUE THREAD

**Issue by sepehr-brj** [telegramdesktop/tdesktop#9984]
### Steps to reproduce
1. Connect to a proxy
2. Start/join a voice chat
3. 

### Expected behaviour
Connect to voice chat

### Actual behaviour
Can't connect

### Configuration
**Operating system:** Windows7

**Version of Telegram Desktop:** 2.5.1

**Installation source (Linux Only)** - the official website / GitHub releases / flatpak / snap / distribution package:

**Used theme**:

<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by mortezae** [comment]
Same problem here on v2.5.1 Linux
Same vps works as transparent vpn but not as socks proxy.

**Comment by navidmafi** [comment]
same problem with MTProto proxy

**Comment by parsibox** [comment]
any suggestion?

**Comment by alefvanoon** [comment]
telegram voice chat and calls not working with mtporoto.
socks5 just working  with calls not voicechat now.

**Comment by NabiKAZ** [comment]
@alefvanoon I try socks5 with enable "use proxy for calls" option, but still does not works.

**Comment by alefvanoon** [comment]
> @alefvanoon I try socks5 with enable "use proxy for calls" option, but still does not works.

Yep!
not working with voice chat!
just call.

**Comment by NabiKAZ** [comment]
Just VPN works for me to Call.
Does not works any SOCKS, HTTP, MTPROTO proxy to Call.

**Comment by mohammadjavad948** [comment]
i have same problem on ubuntu 20.10 & telegram 2.5.9
here is the error that i get in terminal 

Invalid return value 0 for stream protocol
Invalid return value 0 for stream protocol
Invalid return value 0 for stream protocol
[ALSOFT] (EE) Failed to set real-time priority for thread: Operation not permitted (1)

**Comment by DonMGH** [comment]
same issue when using socks5.

Windows 10 1809
Telegram Desktop 2.7.1

**Comment by hsadry** [comment]
same issue when using MTProto

Windows 7
Telegram Desktop 2.7.4

**Comment by mammadataei** [comment]
Same issue using socks5/HTTP proxy.

Kubuntu 20.04
Telegram Desktop 2.8.11

**Comment by parsibox** [comment]
why no body is not responsible to this issue?

**Comment by 0xBYTESHIFT** [comment]
same issue on freshly installed tdesktop v2.8.10 on void linux (musl version of it)

**Comment by itoffshore** [comment]
ping @mohammadjavad948 

> i have same problem on ubuntu 20.10 & telegram 2.5.9 using socks5
> here is the error that i get in terminal
> 
> Invalid return value 0 for stream protocol
> Invalid return value 0 for stream protocol
> Invalid return value 0 for stream protocol
> [ALSOFT] (EE) Failed to set real-time priority for thread: Operation not permitted (1)

This realtime error can be fixed with:

https://wiki.archlinux.org/title/Telegram#Failed_to_set_real-time_priority_for_thread:_Operation_not_permitted

but I still get `Invalid return value 0 for stream protocol` & phone calls crash (making or receiving) after `telegram-desktop` exchanges keys

I'm on Arch Linux with `5.12.19-hardened` - I've tried an LTS kernel / telegram-desktop-2.8 but still the same error - which makes me think perhaps this error comes from `qt5` ?

**Comment by alitoufighi** [comment]
Any updates?

**Comment by john-preston** [comment]
MTProto proxies are not going to work with voice chats (except for broadcast-listen mode, when the user joined as force muted to a large voice chat without being able to talk himself).

Socks5 proxy could work if implemented, but currently it is not done :(

**Comment by NightMachinary** [comment]
Socks5 is still much better than nothing. Telegram would do well to stop adding useless bloat such as animated backgrounds (which would just distract users and cause headaches anyway) and implement its core functionality.

**Comment by Aokromes** [comment]
> Socks5 is still much better than nothing. Telegram would do well to stop adding useless bloat such as animated backgrounds (which would just distract users and cause headaches anyway) and implement its core functionality.

where captains rules (durov) seaman (preston) works.

**Comment by john-preston** [comment]
@NightMachinary Well, backgrounds are used by 100% of the users, and voice chats are used just by a fraction (and a small fraction of that fraction needs and will configure some proxies there). So I think the core functionality is backgrounds here. But I agree that it would be nice to have proxies support as well.
