### ISSUE TITLE
Freezing while scrolling on Manjaro Linux Snap Package

### ISSUE THREAD

**Issue by matifali** [telegramdesktop/tdesktop#9988]
Freezing while scrolling on Manjaro Linux Snap Package. Community package from Manjaro community is working fine.
### Steps to reproduce
1. Install snap package on Manjaro Linux 
2. Run Telegram
3. Scroll

### Expected behavior
Smooth scrolling

### Actual behavior
Stuttering and freezing while scrolling

### Configuration
**Operating system:**  Linux 5.4.80-2-MANJARO x86_64 20.2 Nibia

**DE:** Gnome on (wayland)

**Version of Telegram Desktop:** 2.5.1

**Installation source (Linux Only)**: snap

**Used theme**: Night Mode

<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by ilya-fedin** [comment]
More information needed. DE, Wayland/X11, etc.

**Comment by matifali** [comment]
added the required details.

**Comment by ilya-fedin** [comment]
I don't see information about DE

**Comment by ilya-fedin** [comment]
Wayland is windowing system, it's not DE

**Comment by ilya-fedin** [comment]
Duplicate of #8347

**Comment by matifali** [comment]
This is not a duplicate. As this relates to snap package while #8347 is from the arc linux community repo.

**Comment by ilya-fedin** [comment]
The problem is not related to distribution method, it is related to Wayland

**Comment by matifali** [comment]
But for me if I install through community repo or Linux package binary no lags or freezing.
Its only happening with snap package.

**Comment by ilya-fedin** [comment]
They using XWayland on GNOME by default, if you set `QT_QPA_PLATFORM=wayland`, you should reproduce with them as well.
