### ISSUE TITLE
Telegram right-click menu under linux is crappy

### ISSUE THREAD

**Issue by Yanpas** [telegramdesktop/tdesktop#999]
QT is cross platform toolkit, why do telegram devs invent a wheel? System styles are ignored. Distance between cyrillic symbols is too big.
![_2015-08-15_01-31-51](https://cloud.githubusercontent.com/assets/7345761/9285354/bd4b8578-42ed-11e5-90e0-0399f60a9320.png)

**Comment by auchri** [comment]
Duplicate #987 
The distance of the font is maybe because of the font which Telegram Desktop uses (Open Sans)

**Comment by ManuelSchneid3r** [comment]
I am the author of #987. Note that #987 is *not* about the filechooser. #987 is about the *application style* in general. Check #982 for native filechooser.
