### ISSUE TITLE
Voice chat bad error handling

### ISSUE THREAD

**Issue by peach-lasagna** [telegramdesktop/tdesktop#9993]
### Steps to reproduce
1. Try to invite Deleted account to voice chat
2. catch exception:
![изображение](https://user-images.githubusercontent.com/59787538/103079365-48cbdc80-4606-11eb-8f30-50938412256a.png)

### Expected behaviour
Please add error handling

### Actual behaviour
bad error handling
### Configuration
**Operating system:**
Android 10 

**Version of Telegram Desktop:**
2.5.1

**Comment by ilya-fedin** [comment]
This screenshot is not from tdesktop

**Comment by peach-lasagna** [comment]
> 
> 
> This screenshot is not from tdesktop

oh? yes 😂
