### ISSUE TITLE
issue using through proxy SQUID

### ISSUE THREAD

**Issue by alimurtazo** [telegramdesktop/tdesktop#9994]
We are using Squid proxy. after update to latest version telegram can not send to squid basic authentication. When we are remove this version and install 2.4.7 version telegram working fine. How can we fix this issue?

**Comment by namaiiee2222** [comment]
the squid proxy is so slow with the new versions, is there any update?

**Comment by alimurtazo** [comment]
> the squid proxy is so slow with the new versions, is there any update?

Right now working fine.

**Comment by Aokromes** [comment]
you mean this bug is fixed?

**Comment by alimurtazo** [comment]
> you mean this bug is fixed?

yeah.
